matplotlib/matplotlib

- doc/faq/installing_faq.rst
> Kill some Py2 docs.

- lib/matplotlib/testing/__init__.py
- lib/matplotlib/testing/compare.py
- lib/matplotlib/testing/decorators.py
> Py3fy testing machinery.

- lib/matplotlib/widgets.py
Typical and convenient default for constructing checkboxes.
Minor docstring update and code cleanup.
Not sure it's necessary to explicitly test and document this.
> Make active param in CheckBottons optional, default false

- lib/matplotlib/backend_bases.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/font_manager.py
- lib/matplotlib/pyplot.py
- unit/compare_backend_driver_results.py
... and a few other style fixes.
> Py3fy cbook, compare_backend_driver_results

- .travis.yml
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/tests/test_backends_interactive.py
> Test timers and (a bit) key_press_event for interactive backends.

- examples/pie_and_polar_charts/nested_pie.py
- examples/pie_and_polar_charts/pie_and_donut_labels.py
The PR #10944 attempted to provide a new argument to `pie` whose intention was to implement a donut chart API to the `pie` function. While this is not desireable (see arguments in discussion of that PR), what can be taken from this is that users are not aware of the easy options to produce donut charts in matplotlib. 
This PR changes the existing [nested-pie example](https://matplotlib.org/gallery/pie_and_polar_charts/nested_pie.html#sphx-glr-gallery-pie-and-polar-charts-nested-pie-py) from having several rings, but the inner-most filled to the center, to actually have a hole in them. The concepts of the codes remain; yet the result is more towards applications. It should also be more straight forward to adapt from the new example to a filled version (just leaving out the `width` or …
> update nested-pie example with donut

- examples/misc/zorder_demo.py
- Add tight layout to the first plot
- Use the build it colour cycle for colours
> Clean up zorder example

- examples/lines_bars_and_markers/line_demo_dash_control.py
This improves the [dashes example](https://matplotlib.org/gallery/lines_bars_and_markers/line_demo_dash_control.html?highlight=dashes). In particular:
- more concise description
- more realistic and easier to distinguish dash styles
- simplified code
> Rewrite dashes example

- lib/matplotlib/axes/_axes.py
As part of #10148: Docstring update for `Axes.matshow`.
> Improve docstring of Axes.matshow

- .circleci/config.yml
Looks like release of pip 10 broke the circleci build.  See e.g. https://circleci.com/gh/anntzer/matplotlib/2659?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link, https://github.com/pypa/pip/issues/5221.
Using `python -mpip` instead of `pip` is generally a good thing (tm),
and also what we already do for travis.
> Fix CircleCI build.

- lib/matplotlib/artist.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backend_managers.py
This contains the remaining unmerged docstring changes from #5743. As a result #5743 can be significantly simplified and focus only on a possible switch to napoleon.
> Minor docstring format cleanup

- lib/matplotlib/_constrained_layout.py
- lib/matplotlib/backends/backend_webagg_core.py
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/collections.py
- lib/matplotlib/mathtext.py
- lib/matplotlib/projections/polar.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/ticker.py
> Use chained comparisons where reasonable.

- lib/matplotlib/backends/backend_pdf.py
so no need to format as strings and encode back to ascii.
> bytes % args is back since py3.5

- lib/matplotlib/axes/_axes.py
Maybe fixes #3815? I've also added a couple of other bits of markup to make the docstring nicer in general.
> Add note about hist2d resetting axis limits

- doc/api/next_api_changes/2018-02-15-AL-deprecations.rst
- doc/api/next_api_changes/2018-02-16-AL-deprecations.rst
- lib/matplotlib/testing/compare.py
- lib/matplotlib/testing/decorators.py
- lib/matplotlib/tests/test_compare_images.py
- lib/matplotlib/tests/test_dviread.py
Also includes https://github.com/matplotlib/matplotlib/pull/5858#issuecomment-381366836.
> py3fication of some tests.

- doc/_static/mpl.css
- doc/conf.py
> Enable sphinx.ext.viewcode

- doc/_templates/layout.html
- doc/conf.py
> Doc add sha to footer

- examples/pie_and_polar_charts/pie_demo2.py
Pie Demo2 rewritten. In particular
- switch from `GridSpec` to `plt.subplots()` - simpler in this case.
- `pie does now set aspect=1. No need to do this explicitly anymore`
- use `textprops` kwarg instead of looping over the returned texts
- use `setp` insead of looping over the autotexts.
- improved description.
> Update Pie Demo2

- lib/matplotlib/axes/_axes.py
I'll give it one more minor release as there was no scheduled removal
date...
> Schedule a removal date for passing normed (instead of density) to hist.

- doc/api/next_api_changes/2018-02-15-AL-deprecations.rst
- lib/matplotlib/contour.py
- lib/matplotlib/figure.py
- lib/matplotlib/table.py
(I think 2018 qualifies as beyond "the near future" of "sometime after
2008-08-01", but YMMV...)
> Some more deprecations of old, old stuff.

- .travis.yml
- doc-requirements.txt
Per https://gitter.im/matplotlib/matplotlib?at=5adcfa16109bb04332ec84ba.
Let's also try to unpin pyqt5 to see whether *that* issue is fixed.
Edit: yes, it is.  Closes #10319.
> Pin sphinx to 1.7.2 to unbreak the doc build.

- examples/pie_and_polar_charts/pie_demo2.py
Reverts matplotlib/matplotlib#11089. Might fix #11103
> Revert "Backport PR #11083 on branch v2.2.2-doc"

- lib/mpl_toolkits/mplot3d/art3d.py
- pytest.ini
... at the same time as removing an overly long line.
> py3fy art3d.

- INSTALL.rst
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/backend_agg.py
Document the minimum optional Pillow version.  
Fixes #10633.
> pillow-dependency update

- lib/matplotlib/font_manager.py
A very simple change making this module a bit less chatty. In my opinion these messages are useful for debugging, but not really interested during regular run.
> Use debug level for debugging messages

- doc/_static/mpl.css
- doc/_templates/layout.html
Just built and pushed the docs with this commit.
This will have to be reverted June 8.
> DOC: add plotting contest banner

- lib/matplotlib/axes/_base.py
- lib/matplotlib/pyplot.py
- tools/boilerplate.py
... namely `axis`, `minorticks_{on,off}`, `title`, `{x,y}lim`, `{x,y}scale`, and `sci`.
This helps maintaining the signatures (cf. `title`) and docstring (cf. `axis`) in sync.
> Autogenerate (via boilerplate) more of pyplot.

- lib/matplotlib/backends/backend_wx.py
> Set stacklevel to 2 for backend_wx

- doc/_static/mpl.css
- doc/_templates/layout.html
Remove the fellowship announcement as applications are closed.
> DOC: remove fellowship advertisement

- doc/api/next_api_changes/2018-04-30-AL.rst
- lib/mpl_examples
AFAICT we're not using it for anything, we don't have a similar symlink
to the tutorials, and it annoys my tab-completion when I try to get into
mpl_toolkits...
> Remove mpl_examples symlink.

- lib/matplotlib/text.py
1. Remove some unneeded newlines in the class docstring.
2. Add a space after commas in the repr.
3. Make the constructor docstring's first sentence fit in one line.
edit: added various style fixes across the module...
> Minor cleanup to Text class.

- lib/matplotlib/backends/backend_pgf.py
Closes #11183, followup to #10339, sorry :)
> Fix undefined name error in backend_pgf.

- lib/matplotlib/backends/backend_pgf.py
Sorry, the original PR was kind of sloppy...
> Don't use deprecated get_texcommand in backend_pgf.

- setupext.py
get_win32_compiler (or rather, win32_compiler) is unused.
> Minor cleanups to setupext.

- doc/faq/virtualenv_faq.rst
(milestoning as 3.0 as that version of the venv docs only documents stuff for Py3, e.g. assuming that the venv module is builtin).
> Update venv gui docs wrt availability of PySide2.

- doc/sphinxext/mock_gui_toolkits.py
- lib/matplotlib/backends/backend_cairo.py
- lib/matplotlib/backends/backend_gtk3agg.py
- lib/matplotlib/backends/backend_gtk3cairo.py
- tutorials/introductory/usage.py
> Cleanup/update cairo + gtk compatibility matrix.

- tutorials/introductory/images.py
> Fix broken link

- lib/matplotlib/artist.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/tests/test_artist.py
In most cases, we can just look for 'param : type' in the docstring.
We let ACCEPTS still have the priority to handle weird cases such as
set_xlim where we document the first arg as "bottom", but it's "bottom,
top" for the purpose of the ACCEPTS table; resolving *that* problem is
punted to later.
Only removed a few ACCEPTS entries as a proof of principle.
> Start replacing ACCEPTS table by parsing numpydoc.

- lib/matplotlib/axes/_axes.py
As part of #10148: Docstring update for `Axes.pcolor`.
> Improve docstring of Axes.pcolor

- examples/misc/multiprocess_sgskip.py
If someone knows exactly why the MacOSX backend does not support
fork-based multiprocessing, they should feel free to add a comment; in
any case this commit does not suppress any preexisting info...
> Py3fy multiprocess example.

- doc/api/next_api_changes/2018-05-26-TH.rst
> Add changelog entry for removal of proprietary sphinx directives.

- lib/matplotlib/patches.py
Remove an unintentional deprecation introduced in #11299 .
Closes #11322.
> Undeprecate Polygon.xy from #11299

- lib/matplotlib/image.py
> Minor docstring update of thumbnail

- lib/mpl_toolkits/axisartist/angle_helper.py
Fixes #10814. The original edited lines in `backend_pgf.py` don't exist in the `2.2.x` branch, which is why they haven't shown up here.
> Backport #10806 to v2.2.x

- lib/matplotlib/axes/_axes.py
As part of #10148: Docstring update for `Axes.spy`.
> Improve docstring of Axes.spy

- examples/lines_bars_and_markers/timeline.py
This is a short example to demonstrate how to make a timeline with Matplotlib. @NelleV said it might be useful for the docs since it blends a few different parts of Matplotlib functionality.
Here's what the plot looks like:
> timeline example

- lib/matplotlib/__init__.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/dates.py
- lib/matplotlib/sphinxext/plot_directive.py
- lib/matplotlib/tests/test_mlab.py
- lib/matplotlib/type1font.py
- lib/mpl_toolkits/axes_grid1/axes_divider.py
There were a few places where Py2 wanted str instead of unicode so we had to write `str("foo")` to workaround unicode_literals.  None of that is needed anymore.
> Remove unnecessary str calls.

- examples/lines_bars_and_markers/timeline.py
An update to #11403 per @jklymak and @ImportanceOfBeingErnest 's comments
here's what it looks like:
> removing url dependency and resizing fig

- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_pyplot.py
Just waiting for CI to pass before merging.
> Backport PR #11409: plt.box_bug_fix

- .travis.yml
See https://gitter.im/matplotlib/matplotlib?at=5b23860732618e705ebca4ed and below.
> Pin pytest-timeout to fix the build.

- examples/text_labels_and_annotations/usetex_demo.py
Beautify usetex demo. This demo was too crowded and contained unnecessary commands. This PR simplifies and beautifies it in the hope to lower the risk of eye cancer. 
In total I'm not convinced this demo is entirely necessary, but the way I changed it now, it at least shows some interesting things like the combination of math mode and text mode in one text, or the use of `eqnarray` environements. 
**old**
**new**
> Doc: beautify usetex demo example

- doc/citing.rst
- doc/faq/howto_faq.rst
The DOI foundation recommends [this new resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Yes, a bit ironic that they would change the URL of their service, but it's now [encrypted](https://www.ssllabs.com/ssltest/analyze.html?d=doi.org). Because the old links with the `dx` subdomain continue to work, there is no urgent need to do anything.
However, I'd hereby like to suggest to follow the new recommendation and update all static DOI links.
- ~~Has Pytest style unit tests~~
- ~~Code is PEP 8 compliant~~
- ~~New features are documented, with examples if plot related~~
- ~~Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)~~
- ~~Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way~~
> Hyperlink DOIs against preferred resolver

- examples/pyplots/align_ylabels.py
https://matplotlib.org/gallery/pyplots/align_ylabels.html#sphx-glr-gallery-pyplots-align-ylabels-py shows a hard way to do whats in https://matplotlib.org/gallery/subplots_axes_and_figures/align_labels_demo.html#sphx-glr-gallery-subplots-axes-and-figures-align-labels-demo-py
The hard way is potentially useful, but the easy way should at least be referenced.
> DOC: point align-ylabel demo to new align-label functions

- examples/user_interfaces/pylab_with_gtk_sgskip.py
- lib/matplotlib/__init__.py
- lib/matplotlib/backends/backend_template.py
- lib/matplotlib/figure.py
- lib/matplotlib/mlab.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/quiver.py
- lib/matplotlib/widgets.py
- lib/mpl_toolkits/axes_grid1/colorbar.py
- setup.py
This PR fixes the remaining easy cases. There are still some references in the API/docs, but they are harder to decide what to do. I think this can go in as is as an improvement.
> Remove pylab references

- lib/matplotlib/backends/backend_template.py
- lib/matplotlib/mlab.py
- lib/matplotlib/widgets.py
- tutorials/intermediate/artists.py
- tutorials/introductory/usage.py
This PR fixes two omissions in #11476 and removes additional pylab references.
> remove more pylab references

- .travis.yml
Hope I fixed cherry-pick errors correctly.
> Backport of #11444 to v2.2.2-doc.

- lib/matplotlib/artist.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
- lib/matplotlib/cm.py
- lib/matplotlib/collections.py
- lib/matplotlib/container.py
- lib/matplotlib/figure.py
- lib/matplotlib/image.py
- lib/matplotlib/legend.py
- lib/matplotlib/lines.py
- lib/matplotlib/patches.py
- lib/matplotlib/quiver.py
- lib/matplotlib/spines.py
- lib/matplotlib/table.py
- lib/matplotlib/tests/test_artist.py
- lib/matplotlib/text.py
- lib/mpl_toolkits/axisartist/axis_artist.py
- lib/mpl_toolkits/mplot3d/art3d.py
- lib/mpl_toolkits/mplot3d/axes3d.py
(In the cases where this is "easy".)
Followup to #11300.
> Replace ACCEPTS by standard numpydoc params table.

- lib/matplotlib/backends/backend_template.py
- lib/matplotlib/path.py
- tutorials/introductory/usage.py
> Remove various mentions of the now removed GTK(2) backend.

- doc/_static/mpl.css
- doc/_templates/layout.html
This reverts commit 5fcab07f94c5576ef47fd856a340028e08f49f55.
This removes the plotting contest banner
> Revert "DOC: add plotting contest banner"

- examples/axisartist/demo_parasite_axes.py
- examples/axisartist/demo_parasite_axes2.py
- examples/images_contours_and_fields/barb_demo.py
- examples/images_contours_and_fields/image_masked.py
- examples/images_contours_and_fields/pcolor_demo.py
- examples/images_contours_and_fields/plot_streamplot.py
- examples/images_contours_and_fields/quiver_simple_demo.py
- examples/lines_bars_and_markers/marker_reference.py
- examples/misc/histogram_path.py
- examples/pyplots/align_ylabels.py
- examples/pyplots/pyplot_scales.py
- examples/pyplots/whats_new_1_subplot3d.py
- examples/specialty_plots/sankey_links.py
- examples/text_labels_and_annotations/usetex_demo.py
- examples/units/basic_units.py
- pytest.ini
This is a subset of #11477 to hopefully get pep8 running on the examples again. Contains the minimum number of pep 8 fixes to make the tests pass.
> Re-enable pep8 on examples folder

- examples/subplots_axes_and_figures/axes_margins.py
- lib/matplotlib/axes/_base.py
starts to address the confusion mentioned in #11534
Getting a start on clearing up the Axes.use_sticky_edges vs Axes.margins friction
> DOC: talk about sticky edges in Axes.margins

- lib/matplotlib/offsetbox.py
Simpler solution to #10876 (see in particular https://github.com/matplotlib/matplotlib/pull/10876#issuecomment-376788351).
> Make draggable callbacks check that artist has not been removed.

- lib/matplotlib/axes/_base.py
- lib/matplotlib/backends/qt_editor/formlayout.py
- lib/matplotlib/blocking_input.py
- lib/matplotlib/contour.py
- lib/matplotlib/figure.py
- lib/matplotlib/lines.py
- lib/matplotlib/widgets.py
- lib/mpl_toolkits/axes_grid1/axes_grid.py
See https://docs.python.org/3/library/numbers.html
https://github.com/numpy/numpy/blob/master/doc/release/1.9.0-notes.rst
This makes sure that whenever we typecheck for "float" or "int", numpy scalars also pass.
> Use Integral and Real in typechecks rather than explicit types.

- doc/_static/mpl.css
- doc/devel/documenting_mpl.rst
Pulling some documentation aspects proposed in #10225 into the documentation guidelines.
The guidelines do still need further updates. However, lets start with these so that the amount of changes is still manageable for reviewers.
> Update the documentation guidelines

- lib/matplotlib/ticker.py
> Some docstring cleanup in ticker

- lib/matplotlib/tri/triinterpolate.py
- Use raw-strings for TeX equations in docstrings and reindent an
equation in a more legible manner.
- Remove unused _inv22_vectorized.
> triinterpolate cleanups.

- .travis.yml
wxpython installation was silently failing in CI recently, see e.g. from https://travis-ci.org/matplotlib/matplotlib/jobs/395893835#L1537.
This PR should fix it (basically allowing pip to find the dependency on pypi).  TBH I don't remember why I originally put the --no-index...
> Fix CI install of wxpython.

- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/type1font.py
> Some py3fications.

- lib/matplotlib/pyplot.py
Format `pyplot.matshow()` according to current numpdoc docstring conventions.
> Update docstring of pyplot.matshow()

- examples/lines_bars_and_markers/simple_plot.py
- examples/misc/load_converter.py
- examples/pyplots/annotate_transform.py
- examples/pyplots/auto_subplots_adjust.py
- examples/ticks_and_spines/tick_labels_from_values.py
- lib/matplotlib/lines.py
- lib/matplotlib/mlab.py
- lib/matplotlib/tests/test_artist.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_backend_svg.py
- lib/matplotlib/tests/test_backends_interactive.py
- lib/matplotlib/tests/test_colorbar.py
- lib/matplotlib/tests/test_constrainedlayout.py
- lib/matplotlib/tests/test_contour.py
- lib/matplotlib/tests/test_cycles.py
- lib/matplotlib/tests/test_image.py
- lib/matplotlib/tests/test_tightlayout.py
- lib/matplotlib/tests/test_ttconv.py
- tutorials/advanced/path_tutorial.py
- tutorials/advanced/transforms_tutorial.py
- tutorials/intermediate/artists.py
- tutorials/introductory/usage.py
- tutorials/text/pgf.py
Replace many occurences of 
~~~
ax = fig.add_subplot(111)
~~~
(and similar) with the more canonical `fig, ax = plt.subplots()`
> Use plt.subplots()

- lib/matplotlib/tri/triangulation.py
> Some doc cleanup of Triangulation

- examples/images_contours_and_fields/tricontour_smooth_delaunay.py
- examples/misc/svg_filter_line.py
- examples/misc/svg_filter_pie.py
- examples/specialty_plots/leftventricle_bulleye.py
- examples/specialty_plots/radar_chart.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backend_managers.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/category.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/cbook/deprecation.py
- lib/matplotlib/mlab.py
- lib/matplotlib/offsetbox.py
- lib/matplotlib/patches.py
- lib/matplotlib/tests/test_triangulation.py
- lib/matplotlib/tri/triinterpolate.py
- lib/matplotlib/tri/trirefine.py
- lib/matplotlib/tri/tritools.py
- lib/mpl_toolkits/axes_grid1/axes_size.py
- lib/mpl_toolkits/mplot3d/art3d.py
- lib/mpl_toolkits/mplot3d/axes3d.py
- tutorials/introductory/pyplot.py
- tutorials/introductory/sample_plots.py
- tutorials/text/usetex.py
- tutorials/toolkits/axes_grid.py
- tutorials/toolkits/axisartist.py
> Remove some extra spaces in docstrings/comments.

- lib/matplotlib/tests/test_animation.py
This removes the `None000000.png` that gets created in the working directory.
> TST: Place animation files in a temp dir.

- examples/user_interfaces/embedding_in_wx4_sgskip.py
- examples/user_interfaces/embedding_in_wx5_sgskip.py
> Remove some conditional branches in examples for wx<4.

- doc/users/whats_new.rst
> Clean up what's new

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/dviread.py
- lib/matplotlib/ticker.py
- lib/matplotlib/widgets.py
- lib/mpl_toolkits/axes_grid1/anchored_artists.py
Fix the syntax of wrapped lines, and make sure they are correctly aligned.
> Fix some doctest issues

- README.rst
Depsy is no more (https://twitter.com/depsy_org/status/970376969782149120)
and the image link is broken.
> Fix gitter badge; remove depsy badge.

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/stackplot.py
- lib/matplotlib/streamplot.py
> Minor docstring fixes

- .travis.yml
- INSTALL.rst
- lib/matplotlib/backends/_gtk3_compat.py
- lib/matplotlib/tests/test_backends_interactive.py
This version of pgi fixes a bug in the calling of callbacks, which
affected timers in the GTK3 backends.  Remove a special-casing in the
test suite accordingly (in test_backends_interactive.py).
(See https://github.com/pygobject/pgi/pull/48.)
> Bump pgi requirement to 0.0.11.2.

- src/_tkagg.cpp
(just making it quite a bit shorter...)
> Simplify tkagg C extension.

- doc/devel/coding_guide.rst
- include link to Brett Cannon talk
- re-order bullet points
> DOC: tweak reviewer guidelines.

- .flake8
- lib/matplotlib/tests/test_image.py
- lib/matplotlib/tests/test_lines.py
- lib/matplotlib/tests/test_mathtext.py
(Only cases that allow removing entries from the .flake8 excludes.)
> Boring style fixes.

- doc/users/github_stats.rst
Learning to release sitting next to @tacaswell
> refresh the github stats

- .flake8
- lib/mpl_toolkits/axes_grid1/parasite_axes.py
This manual fetching was previously done in _get_base_axes_attr.
Second commit style-cleans the module.
> Use super() instead of manually fetching supermethods for parasite axes.

- examples/specialty_plots/radar_chart.py
- examples/text_labels_and_annotations/demo_text_path.py
- examples/text_labels_and_annotations/rainbow_text.py
- examples/widgets/menu.py
Most fixes are trivial, except the removal of the call to
_update_patch_transform() in widgets/menu.py: this is OK because calling
Rectangle.draw() will itself call _update_patch_transform() via
get_patch_transform().
> Avoid using private APIs in examples.

- examples/user_interfaces/toolmanager_sgskip.py
This allows one to set the backend from the matplotlibrc or the
MPLBACKEND environment variable.
> Don't force backend in toolmanager example.

- doc/devel/add_new_projection.rst
- doc/devel/testing.rst
- doc/users/dflt_style_changes.rst
See #10108 for explanation why these lists should be dedented.
> Dedent overindented rst bullet lists.

- lib/matplotlib/lines.py
Should have been part of #11105, which made the helper method unused.
> Remove unused private method.

- examples/lines_bars_and_markers/stem_plot.py
This Pull Request improves the documentation of the `stem_plot.py` example.
Adds enough information in the example file for the user to understand every step.
:smile_cat:
> DOC : Improves Documentation for stem_plot.py

- lib/matplotlib/colors.py
- lib/matplotlib/tests/test_axes.py
Its (static)methods are available as freestanding functions now.
> Remove some references to colorConverter.

- .flake8
- lib/matplotlib/_cm.py
- lib/matplotlib/cm.py
See discussion in #11716.
Mostly putting this up as an example of how to exploit functools.partial to keep things picklable.
(pycodestyle doesn't like this but I think this should rather be fixed with an exemption, see also https://github.com/PyCQA/pycodestyle/issues/231.)
> Start work on making colormaps picklable.

- examples/axes_grid1/inset_locator_demo.py
Made a small error in #11026 with resolving a link in `examples/axes_grid1/inset_locator_demo.py`.  I think this fixes it...
> DOC: fix broken link in inset-locator example

- lib/matplotlib/__init__.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/dviread.py
> Replace most uses of getfilesystemencoding by os.fs{en,de}code.

- doc/users/whats_new.rst
> Fix section level of Previous Whats New

- doc/api/next_api_changes/2018-05-06-AL-callbackregistry.rst
- lib/matplotlib/cbook/__init__.py
Code that used to call `_proxy(...)` now needs to call `_proxy()(...)`.
Instead of catching a ReferenceError, that could be either raised by a
failure to dereference the proxy, or by the underlying callable, one can
now check that `_proxy()` does not return None (to distinguish between
the two cases).
This is the same design as the stdlib's WeakMethod.
See https://github.com/matplotlib/matplotlib/pull/9063#discussion_r134396186.
> Require calling a _BoundMethodProxy to get the underlying callable.

- lib/matplotlib/tests/test_axes.py
> Add tolerance to csd frequency test

- requirements/testing/travis36.txt
I don't know whether that works, but would be nice to check before a new release...
> Unpin pandas in the CI.

- lib/matplotlib/backends/backend_cairo.py
- lib/matplotlib/backends/backend_gtk3agg.py
Closes #8798.  Looks like people are actually using the backend and running into the bug :p
I guess this would be nice to have in 3.0 (as it fixes a pretty bad bug) but won't insist on it either.
> Fix cairo's image inversion and alpha misapplication.

- doc/api/api_changes.rst
> Add missing API changes

- .flake8
- lib/matplotlib/backends/backend_agg.py
- src/_backend_agg.cpp
- src/_backend_agg.h
- src/_backend_agg_wrapper.cpp
- The private _get_hinting_flag is unused.
- Despite what the comment says, draw_markers and draw_path_collection
can certainly be defined in update_methods (the comment came in at the
same time as demo_agg_filter.py in b5f348d, which still runs fine
after this patch).
- Remove the unused tostring_bgra (which is not publically exposed in
the wrapper Python-level RendererAgg class -- the C-level class is not
publically accessible).
- Small style fixes.
> Small cleanups to backend_agg.

- setup.py
- There are no symlinks in the mpl source tree anymore.
- MANIFEST was removed from the root directory in 365a0a2f (11 years
ago).
> Remove unnecessary hacks from setup.py.

- lib/matplotlib/figure.py
Maybe I can open a PR that does not break the build? :crossed_fingers:
> DOC: fix minor typo in figure example

- lib/matplotlib/tests/test_text.py
> Remove unnecessary use of nose.

- .flake8
- examples/pie_and_polar_charts/bar_of_pie.py
> example file for making a bar of pie chart

- doc/devel/MEP/MEP24.rst
- lib/matplotlib/ticker.py
> Typo fix in Ticker API

- .flake8
- lib/matplotlib/backends/backend_macosx.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/backends/windowing.py
- lib/matplotlib/pyplot.py
- tools/boilerplate.py
Let's kill some flake8-ignores...
(All changes should be "trivial".)
> Style fixes.

- .flake8
- lib/matplotlib/legend_handler.py
- lib/matplotlib/patheffects.py
- lib/matplotlib/sphinxext/mathmpl.py
- lib/matplotlib/sphinxext/plot_directive.py
Again, nothing really special going on here...
> More style fixes.

- lib/matplotlib/_cm.py
- lib/matplotlib/tests/test_pickle.py
Closes #11716.  See #11723 re: implementation strategy.
> Make all builtin cmaps picklable.

- tutorials/colors/colormaps.py
Small doc change that fixes broken link to IBM's color selection paper.
> DOC: Update link to IBM's colormap selection paper

- tutorials/colors/colormaps.py
Just a quick follow up to #11799 to make the link go to the doi look up.  We really should do this when possible because maintaining the canonical link becomes doi.org's problem, not ours.  The link resolves to the same spot.
> DOC: make ibm link go to doi not ieee site

- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
Follow up to issues mentioned in #11760.
> Argument checking for grid()

- lib/matplotlib/patches.py
The code setting up the renderer and gc are nearly identical, so we can
factor it out as a helper contextmanager.  The only difference is that
FancyArrowPatch then calls draw_path multiple times with various
arguments.
Note that the refactoring exposed the fact that FancyArrowPatches are
(incorrectly, IMO) ignoring joinstyles and capstyles (this is necessary
to make image test pass, but we probably will want to generate new
images with the "correct" (non-ignoring) behavior at some point).
>  Factor out common code between Patch.draw and FancyArrowPatch.draw.

- examples/event_handling/ginput_demo_sgskip.py
1) The sentence in the docstring is both incomplete(?) (at least it ends
with a comma...) and adding no information; just remove it.
2) Print slightly more detailed instructions.
Could probably be further improved, or just removed, but heh...
> Minor fix to ginput_demo.

- .flake8
- examples/color/custom_cmap.py
- lib/matplotlib/cm.py
- lib/matplotlib/colors.py
- tutorials/colors/colormap-manipulation.py
closes #11903  
Shows how to manipulate colormaps.  
rendered version 24 Aug: https://12782-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/tutorials/colors/colormap-manipulation.html#sphx-glr-tutorials-colors-colormap-manipulation-py
> DOC: colormap-manipulation tutorial

- README.rst
Hi team,
Matplotlib is one of the early adopters of LGTM.com, and Python code quality has really improved over time. Keep up the good work :slightly_smiling_face:!
If you'd like to know more about how LGTM calculates code quality, this is definitely worth a read: https://lgtm.com/blog/code_quality_1
> Add LGTM.com code quality badge

- lib/matplotlib/testing/jpl_units/Duration.py
- lib/matplotlib/testing/jpl_units/Epoch.py
- lib/matplotlib/testing/jpl_units/EpochConverter.py
- lib/matplotlib/testing/jpl_units/StrConverter.py
- lib/matplotlib/testing/jpl_units/UnitDbl.py
- lib/matplotlib/testing/jpl_units/UnitDblConverter.py
- lib/matplotlib/testing/jpl_units/UnitDblFormatter.py
- lib/matplotlib/testing/jpl_units/__init__.py
> Make jpl_units a bit less painful to read.

- lib/matplotlib/pyplot.py
This was accidentally bumped to INFO level during the backend-loading
refactor.
Allowing myself to tag this as RC for the same reason as https://github.com/matplotlib/matplotlib/pull/10509.
> Downgrade backend_version log to DEBUG level.

- lib/matplotlib/artist.py
> Fix an invalid escape sequence.

- lib/matplotlib/__init__.py
- lib/matplotlib/artist.py
- lib/matplotlib/contour.py
- lib/matplotlib/gridspec.py
Detected using [codespell -q3](https://github.com/codespell-project/codespell) (still have a number of false positive).
> Fix a couple of typoes.

- doc/api/api_changes.rst
- lib/mpl_toolkits/mplot3d/art3d.py
- tutorials/intermediate/gridspec.py
- tutorials/introductory/pyplot.py
Not sure this really deserve an long explanation. Just much love for all the matplotlib developers.
> Some extra typos

- examples/units/basic_units.py
- lib/matplotlib/artist.py
- lib/matplotlib/axis.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/backend_pgf.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/mlab.py
- lib/matplotlib/testing/decorators.py
- setupext.py
- tools/visualize_tests.py
We don't want to catch `KeyboardInterrupt` and `SystemExit` exceptions in these cases.
https://lgtm.com/rules/6780080/
> Don't use bare except statements

- lib/matplotlib/backends/web_backend/js/mpl.js
- lib/matplotlib/backends/web_backend/js/nbagg_mpl.js
- added a missing space in a text
- added some semicolons (they would be automatically inserted but all other code uses explicit semicolons, so we stay consistent here)
> Minor javascript cleanup

- lib/matplotlib/backends/backend_cairo.py
- lib/matplotlib/backends/backend_gtk3agg.py
- lib/matplotlib/backends/backend_qt5agg.py
- lib/matplotlib/cbook/__init__.py
(missing "i")
noted from #12016
> typo: s/unmultipled/unmultiplied

- lib/matplotlib/backend_bases.py
> Doc markup fixes.

- .flake8
- examples/pyplots/auto_subplots_adjust.py
- examples/pyplots/fig_axes_customize_simple.py
- examples/pyplots/whats_new_98_4_fancy.py
- examples/pyplots/whats_new_99_spines.py
- lib/matplotlib/backends/_backend_tk.py
- lib/matplotlib/backends/backend_agg.py
- lib/matplotlib/backends/backend_cairo.py
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/tkagg.py
- lib/matplotlib/font_manager.py
- lib/matplotlib/fontconfig_pattern.py
- lib/matplotlib/projections/geo.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/rcsetup.py
- lib/mpl_toolkits/__init__.py
- lib/mpl_toolkits/axes_grid1/axes_size.py
- lib/mpl_toolkits/axes_grid1/colorbar.py
- lib/mpl_toolkits/axisartist/angle_helper.py
- lib/mpl_toolkits/axisartist/axis_artist.py
- lib/mpl_toolkits/axisartist/axisline_style.py
- lib/mpl_toolkits/axisartist/axislines.py
- lib/mpl_toolkits/axisartist/clip_path.py
- lib/mpl_toolkits/axisartist/floating_axes.py
- lib/mpl_toolkits/axisartist/grid_finder.py
- lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
- lib/mpl_toolkits/mplot3d/axis3d.py
- lib/mpl_toolkits/mplot3d/proj3d.py
- lib/mpl_toolkits/tests/test_mplot3d.py
I intentionally left in nearly all commented out dead code.
> whitespace(-mostly) style cleanup.

- INSTALL.rst
Fix incorrect url to conda-forge feedstock.  Update URLs to new pypi.  Minor rewordings.
> INSTALL.rst fixes

- lib/mpl_toolkits/mplot3d/axes3d.py
`quiver` seemed to be doing its own thing here
> DOC: formatting fixes to mplot3d

- lib/matplotlib/tests/test_backends_interactive.py
- Fix typo that prevented test of qt5cairo from running.
- wx+osx works again (at least on travis).
> Interactive tests update

- lib/matplotlib/axes/_axes.py
> fix indentation in docstring interpolation for spy.

- lib/matplotlib/backends/backend_qt5agg.py
> Backport PR #12092: Update backend_qt5agg to fix PySide2 mem issues

- lib/matplotlib/colors.py
- tutorials/colors/colormap-manipulation.py
- tutorials/colors/colormaps.py
Link https://jiffyclub.github.io/palettable/ as a place for "more" colormaps....
> DOC: link palettable

- doc-requirements.txt
- doc/conf.py
> Pin to sphinx<1.8; unremove sphinxext.mathmpl.

- examples/axes_grid1/demo_axes_grid.py
- examples/axes_grid1/demo_axes_grid2.py
- examples/axes_grid1/demo_edge_colorbar.py
- examples/axes_grid1/simple_axesgrid.py
- examples/axes_grid1/simple_axesgrid2.py
This adapts some examples to current code style recommendations.
> Cleanup some axes_grid1 examples

- .flake8
- lib/matplotlib/transforms.py
- lib/mpl_toolkits/mplot3d/art3d.py
- lib/mpl_toolkits/mplot3d/axes3d.py
> Style fixes for mplot3d.

- examples/subplots_axes_and_figures/demo_constrained_layout.py
- lib/matplotlib/__init__.py
- lib/matplotlib/_layoutbox.py
- lib/matplotlib/backends/__init__.py
- lib/matplotlib/backends/backend_pgf.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/colorbar.py
- lib/matplotlib/docstring.py
- lib/matplotlib/projections/geo.py
- lib/matplotlib/sphinxext/tests/test_tinypages.py
- lib/matplotlib/testing/__init__.py
- lib/matplotlib/testing/compare.py
- lib/matplotlib/testing/determinism.py
- lib/matplotlib/tests/__init__.py
- lib/matplotlib/tests/test_backend_ps.py
- lib/matplotlib/tests/test_contour.py
- lib/matplotlib/tests/test_cycles.py
- lib/matplotlib/tests/test_legend.py
- lib/matplotlib/tests/test_lines.py
- lib/matplotlib/tests/test_mlab.py
- lib/matplotlib/tests/test_rcparams.py
- lib/matplotlib/tests/test_style.py
- lib/matplotlib/tests/test_units.py
- lib/mpl_toolkits/axes_grid1/colorbar.py
- lib/mpl_toolkits/axisartist/floating_axes.py
- lib/mpl_toolkits/mplot3d/art3d.py
- lib/mpl_toolkits/tests/test_axes_grid1.py
- tutorials/colors/colormap-manipulation.py
Remove unused standard library imports, other imports from tests, and some other hopefully-safe cross-library imports.
> Remove unused imports

- lib/mpl_toolkits/mplot3d/art3d.py
#12032 removed a cbook too many; mplot3d tests fail w/o this...
> MNT: re-add cbook import art3d

- lib/matplotlib/_constrained_layout.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/colorbar.py
- lib/matplotlib/dviread.py
- lib/matplotlib/figure.py
- lib/matplotlib/fontconfig_pattern.py
- lib/matplotlib/image.py
- lib/matplotlib/mathtext.py
- lib/matplotlib/mlab.py
- lib/matplotlib/patches.py
- lib/matplotlib/projections/geo.py
- lib/matplotlib/quiver.py
- lib/matplotlib/stackplot.py
- lib/matplotlib/textpath.py
- setupext.py
- tools/make_icons.py
- tools/memleak.py
Continuation of #11958 
This fixes a number of lgtm alerts:
- unused imports and other import cleanups
- unused variables
> Cleanup unused variables and imports

- doc-requirements.txt
> Fix circleCI on 2.2.x

- doc-requirements.txt
- doc/users/next_whats_new/2018-09-15-AL.rst
- lib/matplotlib/sphinxext/mathmpl.py
- tutorials/text/mathtext.py
Would be kind of nice to have for 3.0, but heh.
> Unbreak the Sphinx 1.8 build by renaming :math: to :mathmpl:.

- examples/color/colorbar_basics.py
I forgot to mention the newly introduced (#11584) colorbar.minorticks_on/off method in the references for the example.
> Mention colorbar.minorticks_on/off in references

- lib/matplotlib/tests/test_units.py
- lib/matplotlib/units.py
> Correctly infer units from emtpy arrays

- lib/matplotlib/axes/_subplots.py
- lib/matplotlib/tests/test_axes.py
ht to @anntzer for the sub-class search code.
> Fixes currently release version of cartopy

- doc/devel/release_guide.rst
- tools/github_stats.py
This prevents pulling PRs that are on master but not to be included in
this release into the stats.
> DOC: update the gh_stats code

- doc-requirements.txt
The use of sphinx 1.8 has two downsides
1. The search on the webpage is broken. See [this link](https://matplotlib.org/3.0.0/search.html?q=imshow&check_keywords=yes&area=default) or just go to the [matplotlib.org](https://matplotlib.org) and type somthing in the "Quicksearch". To see how it should be, see the [2.2.3 version](https://matplotlib.org/2.2.3/search.html?q=imshow&check_keywords=yes&area=default).
2. The [Writing mathematical expressions](https://matplotlib.org/tutorials/text/mathtext.html) tutorial aquires all kinds of red symbols which dont belong there.
While (2) can potentially be fixed from the matplotlib side, (1) cannot. I would hence propose to not use sphinx 1.8 until those are fixed.
> Doc: Don't use Sphinx 1.8

- INSTALL.rst
fix command typo in INSTALL.rst
> DOC: Update INSTALL.rst

- lib/matplotlib/legend.py
- tutorials/introductory/usage.py
Document the slowness of legend's default axis behavior with large amounts of data. Ref #12120.
------------------
p.s. Congrats on 3.0!
> Document legend best slowness

- examples/text_labels_and_annotations/arrow_demo.py
- examples/user_interfaces/embedding_in_wx3_sgskip.py
- examples/user_interfaces/toolmanager_sgskip.py
- setupext.py
- tools/triage_tests.py
- tutorials/intermediate/constrainedlayout_guide.py
- tutorials/introductory/images.py
> Remove some unused variables and imports

- doc/devel/documenting_mpl.rst
> Fix trivial typo in docs.

- examples/color/named_colors.py
- tutorials/colors/colors.py
Two recent ideas (#11927 and #12009) of adding more named colors to matplotlib were decided not be pursued further. In the course of this, however, it [was proposed](https://github.com/matplotlib/matplotlib/pull/11927#issuecomment-416700193) by @timhoffm to sort [the named colors example](https://matplotlib.org/gallery/color/named_colors.html), which is kind of the lookup table for colornames, by category names. 
Despite the fact that we now still have only 4 different categories, such segregated visualization still makes sense. 
This PR changes the example to produce 3 individual figures (XKCD colors are left out, as that would produce a huge figure), one for the BASE_COLORS, the Tableau colors and the CSS colors, respectively.
**Previously:**
[the named colors …
> Doc: Sort named colors example by palette

- doc/api/next_api_changes/2018-09-22-AL.rst
- lib/matplotlib/artist.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
- lib/matplotlib/figure.py
- lib/matplotlib/lines.py
- lib/matplotlib/patches.py
- lib/matplotlib/tests/test_artist.py
- lib/mpl_toolkits/axes_grid1/axes_divider.py
> Less ACCEPTS, more numpydoc.

- lib/matplotlib/animation.py
- lib/matplotlib/legend_handler.py
Giving some more information and adapting to current docstring conventions.
> Improve docstrings of Animations

- lib/matplotlib/blocking_input.py
A small addition of some parameter documentation.
> Add some param docs to BlockingInput methods

- lib/mpl_toolkits/axisartist/axis_artist.py
- lib/mpl_toolkits/tests/test_axisartist_axislines.py
> FIX:  parasite axis2 demo

- lib/matplotlib/text.py
As part of #10148: Docstring update for `Annotation`.
> Improve docstring of Annoation

- lib/matplotlib/dviread.py
> dviread: find_tex_file: Ensure the encoding on windows

- lib/matplotlib/animation.py
The _std{out,err}_buff attributes on Popen objects don't exist anymore
on Unices (since CPython 3.4).  As these buffers are not accessible
anymore in finish(), move the status check and possible exception
throwing to cleanup(), where they are still available.
Don't silently drop exceptions; this shows that ProcessStandin
previously used by HTMLWriter was also buggy (communicate() needed to
return bytes, not str); instead of using it, just do all the work in
finish(), similarly to PillowWriter).
Closes the first part of #9205 (but not https://github.com/matplotlib/matplotlib/issues/9205#issuecomment-372846966).
> Don't use stdlib private API in animation.py.

- .flake8
- lib/mpl_toolkits/axisartist/axislines.py
> Cleanup axislines style.

- lib/matplotlib/animation.py
That's a perfectly reasonable place to put the registry check and avoids
introducing an additional private helper method.
> Move check for ImageMagick Windows path to bin_path().

- lib/matplotlib/__init__.py
- lib/matplotlib/tests/test_matplotlib.py
- tutorials/introductory/usage.py
> Document standard backends in matplotlib.use()

- lib/matplotlib/backends/backend_svg.py
> Minor simplifications to backend_svg.

- .circleci/config.yml
- .flake8
- examples/event_handling/pick_event_demo.py
- examples/images_contours_and_fields/barb_demo.py
- examples/images_contours_and_fields/contourf_demo.py
- examples/images_contours_and_fields/plot_streamplot.py
- examples/lines_bars_and_markers/scatter_masked.py
- lib/matplotlib/contour.py
- lib/matplotlib/lines.py
- lib/matplotlib/patches.py
- lib/matplotlib/projections/geo.py
- lib/matplotlib/projections/polar.py
- lib/matplotlib/streamplot.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_contour.py
- lib/matplotlib/tests/test_image.py
- lib/matplotlib/tests/test_quiver.py
- lib/matplotlib/tests/test_streamplot.py
- lib/matplotlib/tests/test_triangulation.py
- lib/matplotlib/tri/tritools.py
- lib/matplotlib/widgets.py
- lib/mpl_toolkits/mplot3d/proj3d.py
- lib/mpl_toolkits/tests/test_mplot3d.py
Clearer IMO, although perhaps not for the examples?
> Use np.hypot whereever possible.

- doc/faq/howto_faq.rst
Small typo/markup fixes.
Remove TODO on documenting Matplotlib in webservers, these entries have
been around since 2008 (ebe6c5f) and it's unlikely they will ever be
written; moreover essentially all the information relevant on
Matplotlib's side (how to plot headlessly) is given just above.
(Probably that information just above will also need updating now that
we automatically switch to Agg on headless setups (by default), but
that's a separate issue...)
> Minor updates to the FAQ.

- doc/users/next_whats_new/2018-10-08-TH.rst
- doc/users/whats_new.rst
xref #10746, https://github.com/matplotlib/matplotlib/commit/820bea6ddc96c88605aefc7e7ca36e3bc1d415a1#r30819132
> Rollback erronous commit to whats_new.rst from #10746

- lib/matplotlib/font_manager.py
> Don't error if some font directories are not readable.

- lib/matplotlib/tests/test_widgets.py
#10746 added vertical sliders. However, there was just a simple acceptance test.
This PR extends the test to actually verify the layout of the slider patch and thus actually test the orientation.
> Test slider orientation

- lib/matplotlib/font_manager.py
> Fix font_manager.OSXInstalledFonts()

- lib/matplotlib/artist.py
> Document Artist.cursor_data() parameter

- examples/specialty_plots/radar_chart.py
... by reusing already existing utilities to generate regular polygons.
> Simplify radar_chart example.

- doc/devel/min_dep_policy.rst
> DOC: clarify min supported version wording

- .flake8
- tutorials/introductory/usage.py
The plot shown on the page: https://matplotlib.org/tutorials/introductory/usage.html#sphx-glr-tutorials-introductory-usage-py
Will be possible only if plt.show() is outside the loop
> Rectified plot error

- lib/matplotlib/figure.py
> Clarify horizontalalignment and verticalalignment in suptitle

- doc/devel/testing.rst
Closes #12566; I've also encountered that issue myself when doing bisects so I guess we may as well leave the info somewhere in the docs...
> Add note regarding builds of old Matplotlibs.

- lib/matplotlib/backend_bases.py
Trying to improve the docstring of `draw_idle()`. Though I'm not sure what exactly its pupose is and when it should be used. Can someone with more experience on the internals comment on this please?
> Improve docstring of draw_idle()

- lib/matplotlib/axes/_axes.py
> Fix hist() error message

- lib/matplotlib/axes/_base.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_backend_qt.py
> STY: fix whitespace and escaping

- lib/matplotlib/pyplot.py
- lib/mpl_toolkits/axisartist/axis_artist.py
Squash a couple of flake8 problems in 3.0.x 
*NOTE* against 3.0.x, not master...
> FIX: flake8errors 3.0.x mergeup

- lib/matplotlib/afm.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
- Remove the explicit :class: annotation (which isn't necessary).
- Make docstrings of all Axes.add_foo methods consistent among
themselves: a) having a separate Parameters/Returns section for each
of them seems completely overkill; b) most (all?) of them set the
clip_path and the transform on the added artist, so the snippet to
that effect that was present in add_patch should be added to either
all or none of the methods.
> Shorten some docstrings.

- doc-requirements.txt
- doc/devel/documenting_mpl.rst
For some reason the documentation now requires numpydoc 0.8 and sphinx-gallery 0.2. (See https://github.com/matplotlib/matplotlib/pull/11585#discussion_r202523818 for what happens otherwise)
Also changing pillow minuimum version to 3.4. I'm not sure if pillow is really a requirement (it isn't for matplotlib itself, but maybe for the docs), but if it is, it [needs to be >=3.4](https://github.com/matplotlib/matplotlib/pull/11132).
> DOC: update doc requirement

- .flake8
- lib/matplotlib/rcsetup.py
Inspired by #12525, this PR makes rcsetup.py flake8 compliant.
> Make rcsetup.py flak8 compliant

- lib/mpl_toolkits/mplot3d/axes3d.py
> Warn if plot_surface Z values contain NaN

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_base.py
Improve docs on Axes limits and direction. This is part of the overall Axes documentation review #10148.
Only docstring changes.
> Improve docs on Axes limits and direction

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_base.py
Backport PR #12705 on branch v3.0.0-doc:
Improve docs on Axes limits and direction
> Backport PR #12705 on branch v3.0.x

- lib/matplotlib/axes/_base.py
Improve docs on Axes scales. This is part of the overall Axes documentation review #10148.
> Improve docs on Axes scales

- .flake8
This is a bit of future proofing against the per-file-ignores
functionality moving into core flake8.
See https://gitlab.com/pycqa/flake8/merge_requests/263 for issues
running flake8 master branch against our configuration.
> MNT: merge ignore lines in .flake8

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
As discussed in #11383, it would be helpful to extract the color parameter parsing of `Axes.scatter()` to a separate method. This helps in managing the complexity of the code: separted from other stuff in `scatter()`, easier and faster to test because one does need a figure to test the parameter parsing.
- I did only some simple refactorings so far. I'm quite sure this function can be untangled more. This will become easier after this PR, because we can now add a further tests.
- The tests from `TestScatter::test_scatter_c` should be moved to simple tests on the `Axes._parse_scatter_color_args` later on.
- Ideally, `Axes._parse_scatter_color_args` would be a static method. So far, it still has a single `self` reference for obtaining `self._get_patches_for_fill.get_next_color()`. We cannot …
> Refactor color parsing of Axes.scatter

- lib/matplotlib/patches.py
Only docstring update. No code changes.
[current doc](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.patches.Arc.html)
[new doc](https://15779-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/api/_as_gen/matplotlib.patches.Arc.html)
> Improve docstring of Arc

- examples/images_contours_and_fields/irregulardatagrid.py
Also remove some explicit roles (`:meth:`) which don't really help
legibility of the unrendered version.
> Fix typo in example (on-borad -> on-board).

- examples/images_contours_and_fields/irregulardatagrid.py
This clarifies the example with respect to #12762.
> Use level kwargs in irregular contour example

- INSTALL.rst
- doc/devel/testing.rst
- lib/matplotlib/__init__.py
- tutorials/text/usetex.py
> Auto backport of pr 12301 on v3.0.x

- lib/matplotlib/font_manager.py
> Simplify implementation of FontProperties.copy().

- doc/api/next_api_changes/2018-10-19-AL.rst
- lib/matplotlib/font_manager.py
> Make FontManager.score_weight less lenient.

- lib/matplotlib/colors.py
- lib/matplotlib/tests/test_colors.py
- lib/mpl_toolkits/tests/test_axes_grid1.py
> Replace assignments to array.shape by calls to reshape().

- lib/mpl_toolkits/mplot3d/axes3d.py
- No need to convert input_args to lists: broadcast_arrays will handle
the broadcasting just fine on scalars, and later using np.ravel() will
ensure that the result is at least 1D.
- The assertions don't really add much (and are clearly always true
based on the code just above).
- np.linspace(x, y, 2) is a pretty obfuscated way to write np.array([x,
y]).
> Simplifications to quiver3d.

- lib/matplotlib/colorbar.py
> Reword some colorbar docs.

- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/backend_agg.py
- lib/matplotlib/backends/backend_cairo.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_pgf.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/backends/backend_template.py
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/patheffects.py
Reworded some docstrings.
Removed a bunch of duplicated docstrings from Renderer subclasses
(they're inherited anyways cf #12255).
(I didn't think adding "# docstring inherited" for each single inherited docstring was particularly helpful in this case.)
> Cleanup Renderer/GraphicsContext docs.

- lib/matplotlib/axes/_base.py
This debug line doesn't serve much purpose and can be safely removed...
> MNT: remove debug from update_title_pos

- lib/matplotlib/dates.py
> Add missing datestr2num to docs

- doc/users/prev_whats_new/whats_new_1.3.rst
- examples/showcase/xkcd.py
- lib/matplotlib/_color_data.py
- tutorials/introductory/sample_plots.py
... according to https://xkcd.com/about/, which also mentions:
> "Xkcd" is frowned upon.
> Fix spelling of the name Randall Munroe

- lib/matplotlib/testing/conftest.py
Necessary for the test introduced by #12774.
> Don't fail tests if cairo dependency is not installed.

- lib/matplotlib/table.py
Changes:
- Documented `Cell`.
- Rewrote the module docstring.
Do we need the author, copyright, license stuff in the module docstring? Or are the redundant, because this stuff is handled on the project-level?
<s>I could not make sense of the following two sentences in the module docstring. Therefore I removed that information. If anyone knows what these should mean, I'd be happy to add a more clear description.
> The grid need not be rectangular
> You can add additional cells outside this [`(max_row, max_col)`] range to have convenient
ways of positioning more interesting grids.
</s>
> Improve table docs

- lib/mpl_toolkits/mplot3d/axes3d.py
`mask.any()` is more clear and a bit faster than `len(shade[mask]) > 0`.
> Minor code cleanup

- lib/matplotlib/__init__.py
- lib/matplotlib/_layoutbox.py
- lib/matplotlib/_version.py
- lib/matplotlib/artist.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/_backend_tk.py
- lib/matplotlib/backends/backend_agg.py
- lib/matplotlib/backends/backend_gtk3cairo.py
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/offsetbox.py
- lib/matplotlib/patches.py
- lib/matplotlib/text.py
- lib/matplotlib/widgets.py
- lib/mpl_toolkits/axisartist/axislines.py
> Remove unused variables

- lib/matplotlib/legend.py
> Fix a typo

- lib/matplotlib/backends/backend_ps.py
The postscript standard makes no reference to the interpretation of
non-ascii entities, so assuming an encoding is incorrect.
See discussion starting at https://github.com/matplotlib/matplotlib/pull/11130#issuecomment-441225739.
> Restrict postscript title to ascii.

- lib/matplotlib/contour.py
- lib/matplotlib/rcsetup.py
> Validate rcParams["image.origin"].

- doc/api/next_api_changes/2018-11-20-AL-removals.rst
- lib/matplotlib/collections.py
> Cleanup collections docs.

- doc/api/next_api_changes/2018-11-19-AL.rst
- lib/matplotlib/textpath.py
> Deprecate silent dropping of unknown arguments to TextPath().

- lib/matplotlib/backends/backend_cairo.py
- lib/matplotlib/tests/test_backend_cairo.py
Backport PR #12774 on branch v3.0.x:
Cairo backend: Fix alpha render of collections
> Backport PR #12774 on branch v3.0.x

- INSTALL.rst
- build_alllocal.cmd
- doc/devel/testing.rst
- lib/matplotlib/font_manager.py
- setup.py
- tutorials/introductory/customizing.py
> Minor updates following bump to Py3.6+.

- lib/matplotlib/colorbar.py
Backport of #12914: Fix numpydoc formatting
> Backport PR #12914 on branch 3.0.x: Fix numpydoc formatting

- examples/showcase/bachelors_degrees_by_gender.py
- examples/showcase/integral.py
- examples/showcase/mandelbrot.py
- examples/showcase/xkcd.py
As in title; also, fix a few minor warnings due to internal changes.
> Avoid pyplot in showcase examples.

- lib/matplotlib/table.py
Not all of the table API is great, but at least it's documented now.
This PR does only contain docstring changes, but should not be ported back without #12218.
> More table documentation

- doc/api/next_api_changes/2018-12-07-AL.rst
- lib/matplotlib/mathtext.py
- lib/matplotlib/tests/test_mathtext.py
... consistently with TeX.
(AFAICT we never break mathtext over multiple lines so it's just a
normal space for us.)
See e.g. https://tex.stackexchange.com/a/74354/4101 for reference.
Closes #12946.
> Support ~ as nonbreaking space in mathtext.

- examples/text_labels_and_annotations/arrow_demo.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/lines.py
- lib/matplotlib/style/core.py
- lib/matplotlib/table.py
- lib/matplotlib/texmanager.py
> Misc. cleanups.

- doc/api/animation_api.rst
> Remove animated=True from animation docs

- lib/matplotlib/tests/test_backend_nbagg.py
- lib/matplotlib/tests/test_font_manager.py
> Minor simplifications.

- lib/matplotlib/tests/__init__.py
- pytest.ini
Otherwise the error message can be quite obscure.
e.g. https://github.com/matplotlib/matplotlib/pull/12945#issuecomment-445997923
> Fail-fast when trying to run tests with too-old pytest.

- examples/animation/double_pendulum_sgskip.py
The formulas are of the kind where I think that putting +/- at the
beginning of the lines instead of at the end really improves
readability.
> Minor cleanup to double_pendulum example.

- examples/misc/cursor_demo_sgskip.py
- examples/user_interfaces/wxcursor_demo_sgskip.py
- Less pyplot, more OO.
- Showcase both Cursor implementations.
- Misc. cleanups.
> Cleanup cursor_demo.

- lib/matplotlib/ticker.py
> Format MaxNLocator with numpydoc

- INSTALL.rst
- build_alllocal.cmd
> Update windows build instructions

- INSTALL.rst
- build_alllocal.cmd
Backport PR #13001: Update windows build instructions
> Backport PR #13001: Update windows build instructions

- doc/users/next_whats_new/2018-07-18-AL-deprecations.rst
- lib/matplotlib/figure.py
Directly manipulating the visibility of Figure.patch is just as good.
Similar in spirit to #10088, but hopefully less controversial.
> Make Figure.frameon a thin wrapper for the patch visibility.

- lib/matplotlib/cbook/deprecation.py
This avoids duplicating the
```
category = (PendingDeprecationWarning if pending
else MatplotlibDeprecationWarning)
```
logic; right now it's only present twice which is not too bad, but I
plan to add another deprecator (for function arguments) so this is
preliminary work for it.
> Don't split creation of deprecation message and choice of warning class.

- tools/triage_tests.py
- General pathlibification.
- Entry.same is used only once and may as well be inlined.
- Entry.copy_file should be a free function, not a method.
- find_failing_tests can just sort the paths directly and then construct
the Entries, rather than constructing the entries and getting their
paths out for sorting.
> pathlibify/cleanup triage_tests.py.

- lib/matplotlib/backends/backend_webagg.py
> FIX: print out the correct ip address when starting webagg

- doc-requirements.txt
> Pin pillow to < 5.4 to fix doc build

- doc-requirements.txt
> DOC: forbid a buggy version of pillow for building docs

- doc/api/next_api_changes/2018-12-05-AL.rst
- lib/matplotlib/backends/backend_pgf.py
It's an optimization helper that can just as well be implemented
privately using lru_cache.
> Deprecate backend_pgf.LatexManagerFactory.

- examples/statistics/boxplot_demo.py
and additional cleanups to boxplot example.
> Don't use deprecated np.random.random_integers.

- lib/matplotlib/streamplot.py
Does what it says on the tin. I'm happy to fix formatting, but I don't want to deal with the actual docstring content in this PR.
> Convert streamplot to numpydoc

- examples/misc/custom_projection.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/backends/backend_cairo.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/projections/polar.py
- lib/matplotlib/tight_layout.py
> Cleanup unused non-public imports.

- lib/matplotlib/backends/backend_ps.py
Basically the not-failing part of https://github.com/matplotlib/matplotlib/pull/12871.
> Inline some image-handling code for postscript.

- lib/matplotlib/transforms.py
> Delete an unused private method.

- .travis.yml
followup to https://github.com/matplotlib/matplotlib/pull/9787#issuecomment-441441802
attn @jklymak
> Restore the font cache on Travis.

- examples/mplot3d/polys3d.py
Mostly, PolyCollections support alpha directly.
> Simplify the polys3d example.

- lib/mpl_toolkits/tests/test_axisartist_axislines.py
Run `pytest lib/mpl_toolkits/tests/test_axisartist_axislines.py::test_Axes`
to see it.
> Remove an "cannot show figure in agg" warning in test suite.

- .flake8
- examples/lines_bars_and_markers/step_demo.py
- Add a sentence on the purpose of the example.
- Add markers for the data points so that the effect of *where* is easier to see.
- Remove the masked data set. I don't see what that should teach in context of the example. If somebody can explain the purpose, I'm happy to re-add it.
[This is how it looks like](https://17237-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/gallery/lines_bars_and_markers/step_demo.html#sphx-glr-gallery-lines-bars-and-markers-step-demo-py)
> Update example Step Demo

- examples/text_labels_and_annotations/arrow_demo.py
> Remove unused add_dicts from example.

- .flake8
- examples/lines_bars_and_markers/errorbar_limits_simple.py
- Rewrite for more compact code.
- Use non-uniform `yerr` as the more general case.
- Add `uplims=True, lolims=True` case.
- Add references.
> Update errorbar limits example

- lib/matplotlib/axes/_axes.py
Changed the string from "The x/y-coordinate of the arrow base" to "The x and y coordinates of the arrow base".
> Change doc string for Axes.arrow()

- tutorials/colors/colormaps.py
Same as https://github.com/matplotlib/matplotlib/pull/11470 ;-)
- [-] Has Pytest style unit tests
- [-] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [-] New features are documented, with examples if plot related
- [-] Documentation is sphinx and numpydoc compliant
- [-] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [-] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way
> Hyperlink DOIs to preferred resolver

- lib/matplotlib/contour.py
Based on #13038 I've rewritten the docstring for `contourf` `extend` to better explain how to use it.
> Improve docs on contourf extend

- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/quiver.py
- tutorials/introductory/usage.py
Supersedes #7461.  Closes #1558.
> Ensure that arguments to quiver() are not matrices.

- lib/matplotlib/mlab.py
Makes the unrendered docstrings a bit more readable (IMO...).
> Remove :func: markup from mlab docstrings.

- doc/api/widgets_api.rst
- lib/matplotlib/widgets.py
> Update RadioButtons docs numpydoc style

- lib/matplotlib/__init__.py
- lib/matplotlib/backend_tools.py
- lib/matplotlib/colorbar.py
- lib/matplotlib/colors.py
- lib/matplotlib/markers.py
- lib/matplotlib/textpath.py
> Capitalize some docstrings.

- tutorials/introductory/customizing.py
(the paragraph is untrue now that automatic backend selection is implemented)
> Remove an outdated doc point regarding backend selection.

- .flake8
- examples/units/basic_units.py
- lib/matplotlib/__init__.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/axes/_subplots.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/colorbar.py
- lib/matplotlib/container.py
- lib/matplotlib/figure.py
- lib/matplotlib/lines.py
- lib/matplotlib/testing/jpl_units/UnitDblConverter.py
- lib/matplotlib/tests/test_rcparams.py
- lib/matplotlib/text.py
- lib/mpl_toolkits/axes_grid1/axes_divider.py
- lib/mpl_toolkits/axes_grid1/mpl_axes.py
- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/tests/test_axisartist_angle_helper.py
> Remove some more 1-tuples.

- examples/text_labels_and_annotations/demo_annotation_box.py
This pull request adds explanatory text to the Demo Annotation Box gallery example in response to issue #11654.
> Add explanatory comment to annotation box example

- examples/images_contours_and_fields/image_demo.py
Leaving it there as an parenthetical remark "for historical purposes".
> Deemphasize comment about extremely old Matplotlib versions in example.

- examples/axisartist/demo_floating_axes.py
- examples/axisartist/demo_parasite_axes.py
> Cleanup the text of two mpl_toolkits examples.

- .travis.yml
Fixes #13201 . Inspired by changes at #13181, which are for the 2.x branch.
> Add xvfb service to travis

- lib/matplotlib/pyplot.py
- matplotlibrc.template
They would never be selected by the fallback machinery anyways.
> Remove cairo-based backends from backend fallback.

- lib/matplotlib/sankey.py
Note that the previously stated default facecolor and linewidth only
apply in _internal.classic_mode, so don't need to be mentioned.
> numpydocify Sankey.add.

- examples/subplots_axes_and_figures/subplots_demo.py
This is a complete rewrite of https://matplotlib.org/gallery/subplots_axes_and_figures/subplots_demo.html
Improvements:
- Add links to the used API functions
- Structure the topics with headings
- Bring the topics in a logical order
- Add a short explanatory text to each example
> Rewrite subplots_demo

- doc/api/next_api_changes/2019-01-21-AL.rst
- lib/mpl_toolkits/axisartist/axis_artist.py
> Deprecate an unused "internal" API.

- lib/matplotlib/backends/backend_gtk3.py
> Remove an unused local variable in backend_gtk3.

- examples/specialty_plots/sankey_rankine.py
- lib/matplotlib/sankey.py
Running the sankey_rankine example with an info-level logger on emits a
bunch of logs of the form
> The scaled sum of the inputs is 0.039204.
> This may cause poor layout.
> Consider changing the scale so that the scaled sum is approximately 1.0.
but they are clearly intended as such (some flows are just very small,
and they render fine).  Remove that log.
There are also some logs of the form
> The sum of the flows is nonzero (-0.002000).
> Is the system not at steady state?
Improve them by including the patchlabel, so that one can more easily
figure out the potentially incorrect flow values (one now gets
> The sum of the flows is nonzero (-0.002000; patchlabel='\n\nOpen\nheater'); is the system not at steady state?
) (as for the actual values in the example, I guess someone should check …
> Improve sankey logging.

- .appveyor.yml
- .travis.yml
- azure-pipelines.yml
- lib/matplotlib/font_manager.py
- lib/matplotlib/tests/test_animation.py
pytest will only actually output logs if the test fail.
May help with troubleshooting #13137.
> DEBUG-log font-matching results, and print failing logs on CI.

- doc/devel/MEP/MEP25.rst
> DOC: reject MEP25 due to being stalled

- examples/animation/double_pendulum_sgskip.py
> Fix animation speed in double_pendulum example

- examples/axes_grid1/demo_colorbar_with_inset_locator.py
This provides a better title and description of the example, as well as uses fig.colorbar instead of plt.colorbar.
> DOC Better description of inset locator and colorbar

- doc/faq/osx_framework.rst
compare e.g. https://matplotlib.org/faq/osx_framework.html and https://matplotlib.org/faq/virtualenv_faq.html.
> Minor cleanup to OSX FAQ.

- doc/conf.py
... and move the check for graphviz into the _check_dependencies()
helper function, where it logically belongs to.
> Don't emit a non-GUI warning when building the docs on Linux.

- lib/mpl_toolkits/axes_grid1/axes_grid.py
- lib/mpl_toolkits/axes_grid1/axes_size.py
- lib/mpl_toolkits/mplot3d/axes3d.py
> numpydocify (some of) mpl_toolkits.

- lib/matplotlib/bezier.py
> Trivial bezier cleanups.

- lib/matplotlib/tests/test_font_manager.py
> Further investigate flaky failure with wqy-zenhei.ttc on Travis.

- lib/matplotlib/axis.py
> Better explanation of ticks

- lib/matplotlib/dates.py
- lib/matplotlib/tests/test_dates.py
> Backport PR #12678 on branch v3.0.x

- tutorials/intermediate/constrainedlayout_guide.py
Fixes #13311 - we can decide whether to get rid of the message in another PR (my vote would be lets remove it for 3.1)
> Put correct version in constrained layout tutorial

- src/_path.h
- src/_path_wrapper.cpp
Then we don't have to worry about managing the buffer ourselves, such as #13288. I'm a bit bummed that we still need a `try`/`catch` in `__add_number`, but writing an auto-free pointer seems too much work.
> Rewrite convert_to_string using std::string

- lib/matplotlib/image.py
The change to make the abstract ImageBase.make_image raise a
NotImplementedError rather than a RuntimeError is consistent with most
of the library, and should not affect end users anyways.
> Update some (mostly internal) docstrings in image.py.

- lib/matplotlib/axis.py
Axis / tick handing will get an overhaul some time. Until then, it's helpful to know what attributes it offers.
> Update Axis docs

- .flake8
- lib/matplotlib/axis.py
- lib/matplotlib/mlab.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/scale.py
- lib/matplotlib/tests/test_preprocess_data.py
- lib/matplotlib/widgets.py
- requirements/testing/travis_flake8.txt
flake8 3.7 seems to be working fine now.
The associated bump to pycodestyle 2.5 caught a few more style nits.
> Bump to flake8 3.7.

- doc/api/next_api_changes/2019-01-06-TH-use-param.rst
- lib/matplotlib/__init__.py
> Cleanup matplotlib.use

- src/_path_wrapper.cpp
> Simplify parsing of tuple in C extension code.

- doc/api/next_api_changes/2019-01-27-JMK.rst
> DOC: change language a bit

- lib/matplotlib/axis.py
The method is unused since #12158 got merged.
> Kill the unused, private _get_pixel_distance_along_axis.

- .flake8
- lib/mpl_toolkits/axes_grid/axes_rgb.py
- lib/mpl_toolkits/axes_grid1/axes_divider.py
- lib/mpl_toolkits/axes_grid1/axes_grid.py
- lib/mpl_toolkits/axes_grid1/axes_size.py
- lib/mpl_toolkits/axes_grid1/inset_locator.py
- lib/mpl_toolkits/tests/test_axes_grid1.py
> mpl_toolkits style fixes.

- .travis.yml
> CI: add additional qt5 deb package on travis

- .flake8
- .travis.yml
- lib/matplotlib/backends/qt_editor/figureoptions.py
- lib/matplotlib/mlab.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/scale.py
- lib/matplotlib/tests/test_preprocess_data.py
- lib/matplotlib/widgets.py
- requirements/testing/travis_flake8.txt
* CI: add additional qt5 deb package on travis
* Bump to flake8 3.7.
> Backport PR #13412 and #13337 on branch v3.0.x

- lib/matplotlib/tests/test_figure.py
> test_figure style fixes.

- lib/matplotlib/quiver.py
- lib/matplotlib/tri/triinterpolate.py
- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/mplot3d/proj3d.py
Having a function named mod that doesn't do % but computes the norm of a
vector is just a good way to trip the reader (yes, I know about the term
"modulus of a vector", but still).
Also vectorize a normals calculation.
Also we can use % instead of np.mod elsewhere.
> Deprecate proj3d.mod.

- examples/axisartist/demo_curvelinear_grid.py
> Cleanup demo_curvelinear_grid.

- lib/mpl_toolkits/axes_grid1/parasite_axes.py
- lib/mpl_toolkits/tests/test_axes_grid1.py
Second attempt at fixing https://github.com/matplotlib/matplotlib/issues/5581 .
This time it is done by implementing custom `pick` methods for host and parasite axes classes.
In actuality the pick methods are both stolen from [`Artist.pick`](https://github.com/matplotlib/matplotlib/tree/f4209922972afa3917a0ce61ae3d58b2ebba3264/lib/matplotlib/artist.py#L418) and extended, I'm not sure if I should remove [that duplicate wall-of-text comment](https://github.com/productivememberofsociety666/matplotlib/blob/5b1aae649748543b5ceb0a785b66dabc54c4244c/lib/mpl_toolkits/axes_grid1/parasite_axes.py#L366).
Also added tests that check if this behaves exactly as picking on "normal axes" (`pyplot.gca()` on a clean slate) does even for overlapping objects.
> [mpl_toolkits] Fix picking for things drawn on parasite axes

- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/_backend_tk.py
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_macosx.py
- lib/matplotlib/backends/backend_nbagg.py
- lib/matplotlib/backends/backend_qt5.py
- lib/matplotlib/backends/backend_webagg.py
- lib/matplotlib/backends/backend_wx.py
> Inherit some docstrings in backend code.

- lib/matplotlib/rcsetup.py
> Remove some outdated comments from rcsetup.py.

- lib/matplotlib/gridspec.py
The indexing error message is modeled after the one used by numpy.
> Clarify IndexError for out-of-bounds indexing of gridspec.

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/ticker.py
- lib/matplotlib/tri/triangulation.py
- lib/matplotlib/tri/tripcolor.py
- lib/matplotlib/tri/tritools.py
It's shorter, better known, and works directly on 2D inputs without
fiddling with ravel()ing (for the changes for pcolor).
> Replace np.compress by boolean indexing.

- setupext.py
> BLD: only try to get freetype src if src does not exist

- doc/api/api_changes.rst
- doc/devel/release_guide.rst
> DOC: update release guide

- doc/api/next_api_changes/2019-02-20-AL.rst
- lib/matplotlib/text.py
... for consistency with Line2D.
> Add "c" shorthand for "color" for the Text class.

- doc/api/next_api_changes/2019-02-21-AL.rst
- lib/matplotlib/backends/backend_wx.py
> Deprecate backend_wx.IDLE_DELAY.

- lib/mpl_toolkits/axes_grid1/axes_grid.py
Only changes to docstrings. Mostly formatting and a bit of added information.
> Update axes_grid docs

- doc/api/next_api_changes/2019-01-22-AL.rst
- lib/matplotlib/axes/_base.py
- lib/matplotlib/axes/_subplots.py
- lib/matplotlib/axis.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/backends/backend_webagg_core.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/collections.py
- lib/matplotlib/contour.py
- lib/matplotlib/figure.py
- lib/matplotlib/font_manager.py
- lib/matplotlib/lines.py
- lib/matplotlib/mathtext.py
- lib/matplotlib/projections/geo.py
- lib/matplotlib/projections/polar.py
- lib/matplotlib/quiver.py
- lib/matplotlib/scale.py
- lib/matplotlib/text.py
- lib/matplotlib/tri/tripcolor.py
- lib/matplotlib/widgets.py
- lib/mpl_toolkits/axes_grid1/axes_divider.py
- lib/mpl_toolkits/axes_grid1/axes_size.py
- lib/mpl_toolkits/axes_grid1/parasite_axes.py
- lib/mpl_toolkits/axisartist/axis_artist.py
- lib/mpl_toolkits/mplot3d/axes3d.py
> Add helper function to check that an argument is in a list of strings.

- doc/api/next_api_changes/2018-11-07-removals-AL.rst
- lib/matplotlib/__init__.py
- lib/matplotlib/backends/qt_compat.py
- lib/matplotlib/rcsetup.py
- lib/matplotlib/tests/test_rcparams.py
> Remove deprecated rcParams.

- lib/matplotlib/axes/_axes.py
This simple solution is slightly modified from an original idea by
@mhedges.
In my view, this closes #6669.
> Document histogramming pre-binned data.

- doc/devel/release_guide.rst
- tools/github_stats.py
More updates to the release docs.
This is more documenting what is actually done rather than prescribing what should be done.
> Doc more release updates

- examples/subplots_axes_and_figures/subplots_demo.py
> Add missing plt.show() at end of example.

- examples/subplots_axes_and_figures/gridspec_and_subplots.py
> Add missing show() at end of example.

- tutorials/text/annotations.py
Compare the TOC at https://matplotlib.org/tutorials/text/annotations.html and https://6136-7439715-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/tutorials/text/annotations.html.
> Fix heading hierarchy in annotation tutorial.

- examples/mplot3d/3d_bars.py
- examples/mplot3d/lorenz_attractor.py
- examples/mplot3d/voxels_rgb.py
Noted while working on #13520.
> Small cleanup to headings of 3d examples.

- lib/matplotlib/dates.py
- lib/matplotlib/font_manager.py
- lib/matplotlib/fontconfig_pattern.py
- lib/matplotlib/image.py
This makes the unrendered docstrings more readable, IMO.
> Move some links in rst out of running text.

- setup.py
- setupext.py
setupext currently has a complex machinery to define extension modules.
Essentially, the problem is that numpy may not be installed at the time
the extensions are declared, so we can't call np.get_include() to get
the include paths.  So we use a DelayedExtension class and a hook
mechanism to inject the numpy include path later, once it becomes
available.
Instead, we can just declare a dummy extension (so that setuptools
doesn't elide the call to build_ext), then swap in the correct
extensions in build_ext.finalize_options(): at that point, numpy will
have been installed and we don't need any crazy machinery.
Also closes #6928 by not attempting to reload numpy anymore.
> Simplify extension setup.

- lib/matplotlib/backend_bases.py
> More use of cbook._check_in_list.

- .flake8
- doc/api/next_api_changes/2018-08-17-AL-deprecations.rst
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/cbook/deprecation.py
> Use the builtin GTK3 FileChooser rather than our custom subclass.

- lib/matplotlib/ticker.py
This avoids confusion between the three implementations
(OldScalarFormatter, ScalarFormatter, and LogFormatter).
OldScalarFormatter._pprint_val and ScalarFormatter._pprint_val are not
used elsewhere and can be inlined.
LogFormatter._pprint_val is also used by LogFormatterExponent and must
be kept (even though it looks likely that LogFormatterExponent can also
be simplified , e.g. the test
`abs(math.log(x) / math.log(self._base)) > 10000`
is basically never True for any realistic case -- but that'll be for
another time).
Followup to #12924.
> Inline or simplify FooFormatter.pprint_val.

- lib/matplotlib/axes/_axes.py
> pcolorfast simplifications.

- lib/matplotlib/units.py
The caching of the converter was disabled 10 years ago
(be73ef49911eec165c2c70d22f57d3b75c0b0514) and is unlikely to ever work
as the correct converter for ndarrays depends on the type of the
contents, not on the container, so just drop the cache-related code.
When a masked array is passed, it's OK to just get the first underlying
data, even if it is masked (as it should have the same type as the
unmasked entries), for the purpose of getting the converter.
> Simplify units.Registry.get_converter.

- lib/matplotlib/gridspec.py
- Document the width/height ratios
- Add some optional notes
- Fix the `Figure` link
> Improve GridSpec doc

- lib/matplotlib/backends/backend_pgf.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/image.py
> Small cleanups.

- examples/misc/font_indexing.py
- examples/misc/ftface_props.py
> Cleanup two font-related examples.

- lib/matplotlib/contour.py
- lib/matplotlib/tests/test_contour.py
Backport of #11917....
Closes #13456
> Backport of #11917

- lib/matplotlib/axes/_base.py
It's unused since 3bddca5 (2008).
> Kill Axes._connected.

- examples/color/named_colors.py
"Visualizing named colors" -> "List of named colors"
Small change. But it focuses more on the lookup-aspect of the example and less on the process/code of creating such an overview.
> Change title of named colors example

- doc/api/next_api_changes/2018-01-30-AL.rst
Closes #13618 (thanks @ImportanceOfBeingErnest for the example).
Feel free to directly push edits.
> Clarify tick collision API change doc.

- examples/images_contours_and_fields/image_transparency_blend.py
> Small example simplification.

- examples/text_labels_and_annotations/demo_text_rotation_mode.py
- Rewrote description.
- Improved layout, giving more visual focus on the relation between the label and the reference point.
[Old example](https://matplotlib.org/gallery/text_labels_and_annotations/demo_text_rotation_mode.html)
[New example](https://19147-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/gallery/text_labels_and_annotations/demo_text_rotation_mode.html#sphx-glr-gallery-text-labels-and-annotations-demo-text-rotation-mode-py)
> Improve Demo Text Rotation Mode

- lib/matplotlib/widgets.py
Some Examples on page: https://matplotlib.org/api/widgets_api.html did not work.
> widgets.py fix examples connect -> mpl_connect

- setup.py
Only write the minimum version 1 place instead of 3
> BLD: parameterize python_requires

- lib/matplotlib/patches.py
> Fix FancyArrowPatch joinstyle

- doc/Makefile
- doc/devel/documenting_mpl.rst
- requirements/doc/doc-requirements.txt
h/t to pandas and @TomAugspurger
> DOC: fail the doc build on errors, but keep going to end

- lib/matplotlib/tests/test_scale.py
> Suppress some warnings in tests.

- .flake8
- examples/lines_bars_and_markers/stem_plot.py
Update the [stem plot](https://matplotlib.org/devdocs/gallery/lines_bars_and_markers/stem_plot.html) example:
- Make a simpler and more realistic first plot.
- Add a second plot explaining how to further adapt the plot.
Fixes #10165.
> Update stem example

- lib/matplotlib/font_manager.py
Some failures were previously not logged.
> Log all failures to extract font properties.

- doc/_static/mpl.css
- doc/_templates/layout.html
Adds the banner for the 2019 plotting contest
> DOC: add banner for 2019 JHEPC

- lib/matplotlib/backend_tools.py
- lib/matplotlib/backends/_backend_tk.py
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_qt5.py
- lib/matplotlib/backends/backend_wx.py
... by reusing the old Toolbar-based implementations.
If toolmanager ever becomes the default we can move the implementations
there and conversely point the old Toolbar-based implementations to use
the Tools.
> Deduplicate implementation of per-backend Tools.

- doc/api/next_api_changes/2019-03-18-AL.rst
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_qt5.py
- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/contour.py
- lib/matplotlib/image.py
- lib/matplotlib/legend.py
- lib/matplotlib/lines.py
- lib/matplotlib/patches.py
- lib/matplotlib/patheffects.py
- lib/matplotlib/quiver.py
- lib/matplotlib/table.py
- lib/matplotlib/testing/compare.py
- lib/matplotlib/widgets.py
Kill the private ones and deprecate the public ones (most of them are
leftovers from (very) old refactors).
> Kill attributes that are never used/updated.

- lib/mpl_toolkits/axisartist/floating_axes.py
- lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
These are copy-pasted from the same methods in the parent class
FloatingAxisArtistHelper.
Also cleanup a bit the base method implementation.
> Remove duplicated methods in FixedAxisArtistHelper.

- examples/lines_bars_and_markers/stem_plot.py
- tutorials/introductory/sample_plots.py
This fixes two documentation warnings. See comments to the code.
> Fix doc warning

- doc/users/whats_new.rst
> Fix doc markup.

- tutorials/introductory/sample_plots.py
attempt to fix the doc build.  
I guess py 3.7 doesn't like mixing `"""` and `####` comments one after the other for sphinx gallery?  This PR fixes the build process...
> DOC/FIX: try merging comments

- lib/matplotlib/font_manager.py
(There is no such "enabling" anymore, since #10933.)
> Remove mention of "enabling fontconfig support".

- lib/matplotlib/__init__.py
Path objects can't be passed to subprocess.Popen on Windows.
closes #13786.
> Fix failure to import matplotlib.animation on Windows.

- lib/matplotlib/transforms.py
> numpydocify transform_angles.

- doc/api/api_overview.rst
> Doc typos.

- lib/matplotlib/font_manager.py
Use the windows environment variable formatting when talking about windows environment variables.
> Correct windows env variable format

- lib/matplotlib/patches.py
Some minor cleanup of FancyArrowPatch.
> Cleanup FancyArrowPatch docstring

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/cm.py
> Some more usage of _check_in_list.

- INSTALL.rst
- doc/devel/MEP/MEP14.rst
- doc/devel/contributing.rst
- doc/devel/documenting_mpl.rst
- doc/faq/installing_faq.rst
- doc/faq/troubleshooting_faq.rst
- doc/glossary/index.rst
- doc/resources/index.rst
- doc/users/prev_whats_new/whats_new_2.2.rst
- examples/style_sheets/ggplot.py
This should be most of the rest of the broken links fixed.
> Fix remaining links in docs

- lib/mpl_toolkits/axisartist/grid_finder.py
> Style fixes to grid_finder.

- lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
> Style fixes for grid_helper_curvelinear.

- examples/statistics/errorbar_limits.py
- lib/matplotlib/tests/test_axes.py
- lib/mpl_toolkits/axisartist/grid_finder.py
> `zeros_like(x) + y` -> `full_like(x, y)`

- lib/matplotlib/figure.py
> Shorten Figure.set_size_inches.

- lib/matplotlib/axes/_base.py
- lib/matplotlib/collections.py
- lib/matplotlib/colors.py
- lib/matplotlib/patches.py
- lib/matplotlib/path.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/sankey.py
- lib/matplotlib/spines.py
- lib/matplotlib/ticker.py
> rst seealso -> numpydoc "See Also".

- setupext.py
> Remove unused setupext.is_min_version.

- lib/matplotlib/axes/_subplots.py
- lib/matplotlib/tests/test_figure.py
> Check for positive number of rows and cols

- .flake8
- examples/userdemo/connectionstyle_demo.py
- Add introductory description.
- Cleanup code.
- Add references.
> Improve Conectionstyle Demo

- examples/text_labels_and_annotations/stix_fonts_demo.py
> Cleanup STIX Font Demo

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/patches.py
- lib/matplotlib/spines.py
- lib/matplotlib/transforms.py
> Shorten docstrings by removing unneeded :class:/:func: + rewordings.

- lib/matplotlib/category.py
> Style fixes for category.py.

- examples/tests/backend_driver_sgskip.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/hatch.py
> `a and b or c` -> `b if a else c`

- doc/sphinxext/gallery_order.py
- examples/images_contours_and_fields/tricontour_smooth_delaunay.py
- examples/images_contours_and_fields/tricontour_smooth_user.py
- examples/images_contours_and_fields/trigradient_demo.py
- lib/matplotlib/backend_managers.py
- lib/matplotlib/bezier.py
- lib/matplotlib/colors.py
- lib/matplotlib/mathtext.py
- lib/matplotlib/table.py
- lib/matplotlib/tests/test_image.py
- lib/matplotlib/tests/test_mlab.py
- lib/matplotlib/tests/test_triangulation.py
- lib/matplotlib/tri/triinterpolate.py
- lib/matplotlib/widgets.py
- lib/mpl_toolkits/axisartist/axis_artist.py
- lib/mpl_toolkits/tests/test_mplot3d.py
> Bunch of docstring cleanups.

- lib/matplotlib/backend_tools.py
> Make Cursors an (Int)Enum.

- examples/text_labels_and_annotations/rainbow_text.py
- Refactor the function to draw a single text line and control the orientation via a parameter.
- Use actual rainbow colors for the colors.
> Improve Rainbow text example

- lib/matplotlib/colorbar.py
> Fix typo in code example in docstring.

- lib/matplotlib/cm.py
- lib/matplotlib/tests/test_colorbar.py
> Fix colorbar setting without artist

- lib/matplotlib/tests/test_mlab.py
- lib/matplotlib/tests/test_png.py
- lib/matplotlib/tests/test_triangulation.py
> Test cleanups.

- lib/matplotlib/animation.py
> Pathlibify animation.

- doc/api/index.rst
- doc/api/next_api_changes/2019-04-14-AL.rst
- doc/api/quiver_api.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/quiver.py
> numpydocify quiverkey.

- lib/matplotlib/patches.py
#10776 changed the logic inside `Patch.contains()`, and in particular includes the line
```python
codes = self.get_path().codes
```
If this evaluates to `None`, then the proceeding logic doesn't work and raises an error. This has broken scrolling/zooming plots made with custom projections in Astropy (https://github.com/astropy/astropy/issues/8545). I presume this is because there is a custom `Patch` somewhere along the line who's path doesn't contain any codes.
This fix just checks if `self.get_path().codes == None`, and if it is applies the old logic that was used before  #10776 - not sure if this is the long term fix, but in the short term it should be fine.
> Fix patch contains logic for patches that don't have any codes

- lib/matplotlib/pyplot.py
> Fix docstring of pyplot.clim()

- doc/sphinxext/github.py
- examples/axes_grid1/demo_axes_grid.py
- examples/axes_grid1/demo_edge_colorbar.py
- examples/event_handling/pick_event_demo.py
- examples/misc/demo_agg_filter.py
- examples/units/basic_units.py
- examples/widgets/menu.py
- lib/matplotlib/axes/_secondary_axes.py
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_gtk3agg.py
- lib/matplotlib/backends/backend_macosx.py
- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/cbook/deprecation.py
- lib/matplotlib/collections.py
- lib/matplotlib/colorbar.py
- lib/matplotlib/dviread.py
- lib/matplotlib/rcsetup.py
- lib/matplotlib/sphinxext/plot_directive.py
- lib/matplotlib/texmanager.py
- lib/matplotlib/textpath.py
- lib/mpl_toolkits/axes_grid1/axes_size.py
- lib/mpl_toolkits/axes_grid1/colorbar.py
- lib/mpl_toolkits/axisartist/angle_helper.py
- lib/mpl_toolkits/axisartist/axis_artist.py
They can be detected by removing the exclusion of F841 in .flake8.
AFM parsing was made slightly stricter as a consequence (see changelog).
Some other unused variables have been left in, either for symmetry in
the code or because their lack of use may possibly indicate a bug that
needs to be investigated.
> Remove many unused variables.

- doc/api/next_api_changes/2019-04-23-AL.rst
- lib/matplotlib/__init__.py
It is only internally used by the deprecated checkdep_ghostscript.
> Deprecate compare_versions.

- lib/matplotlib/axes/_axes.py
Previously the link did not render properly.
> Fix ax.legend Returns markup

- tutorials/colors/colormaps.py
Fix #14000 by removing references to vischeck
> [BUG] DOC: Remove broken references to vischeck

- lib/matplotlib/path.py
> Cleanup path.py docstrings.

- lib/matplotlib/pyplot.py
> Cleanup some pyplot docstrings.

- examples/lines_bars_and_markers/bar_stacked.py
- examples/units/bar_unit_demo.py
Use label=... to define legend labels (note that in the case here,
`plt.legend((p1[0], p2[0]), (..., ...))` is not even that nice as it
exposes the internals of the bar object, so using `label=...` is clearly
simpler).
Pep8ify variables.
> Cleanup bar_stacked, bar_unit_demo examples.

- doc/api/next_api_changes/2019-04-29-AL.rst
- lib/matplotlib/backend_bases.py
> Deprecate FigureCanvasBase.draw_cursor.

- examples/text_labels_and_annotations/date.py
> Cleanup date example.

- examples/misc/demo_agg_filter.py
- examples/specialty_plots/leftventricle_bulleye.py
> Pep8ify some variable names in examples.

- examples/misc/agg_buffer.py
- lib/matplotlib/pyplot.py
It's longer to type(!) than its actual implementation
(``gcf().canvas.manager``), and mixes the pyplot and the OO-interfaces.
Also make ``plt.subplot_tool`` work even for non-pyplot-managed figures
-- there's no reason not to, it's just that such figures cannot be made
the "current" pyplot figure.
> Deprecate get_current_fig_manager().

- lib/matplotlib/hatch.py
- lib/matplotlib/legend_handler.py
> Trivial cleanups.

- examples/lines_bars_and_markers/scatter_piecharts.py
I agree with #14055 that this example is not really that great; but while that is discussed we can at least make it more readable.
> Simplify scatter_piecharts example.

- lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
1. Pre-normalize extremes from None to +/- np.inf from the beginning,
rather than recheck for None every time they are accessed.
2. Instead of indexing into the 4-element `extremes` list, just give
meaningful names to each element.
> Clarify handling of "extreme" values in FloatingAxisArtistHelper.

- .flake8
- lib/mpl_toolkits/axisartist/floating_axes.py
> Style fixes for floating_axes.

- examples/lines_bars_and_markers/gradient_bar.py
- describe the mechanism how gradients can be created with `AxesImage`.
- generalize the mechanism to allow gradients along arbitrary directions.
- allow to select as subrange of a colormap for the gradient.
- demonstrate how to reasonably use a gradient as an Axes background.
[link to doc build](https://20618-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/gallery/lines_bars_and_markers/gradient_bar.html#sphx-glr-gallery-lines-bars-and-markers-gradient-bar-py)
> Improve Gradient bar example

- examples/misc/demo_ribbon_box.py
- Use AxesImage instead of the more obscure BboxImage.
- Just hardcode the data instead of random-generating it and rounding it
to hundreds when displaying.
- Misc cleanups.
Inspired by #14057 (thanks @timhoffm)
> Simplify ribbon_box example.

- INSTALL.rst
- doc/glossary/index.rst
- tutorials/introductory/usage.py
Remove some entries in the glossary which are only referred to once, in
the usage tutorial (note that the usage tutorial explitictly explains
the terms "raster" and "vector" graphics just before the renderer table.
> Remove uninformative entries from glossary.

- lib/matplotlib/__init__.py
- lib/matplotlib/mlab.py
> Move some toplevel strings into the only functions that use them.

- lib/matplotlib/pyplot.py
> Some simple pyplot doc improvements

- lib/matplotlib/pyplot.py
Backport PR #14109 on branch v3.1.x
> Backport PR #14109 on branch v3.1.x

- examples/showcase/bachelors_degrees_by_gender.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/dates.py
- lib/matplotlib/tests/test_font_manager.py
> Avoid backslash-quote by changing surrounding quotes.

- examples/images_contours_and_fields/plot_streamplot.py
> Dedent overindented list in example docstring.

- setupext.py
We can just use boring old inheritance of check() (check_requirements()
never returns relevant information on success anyways -- the OS returned
by BackendMacOSX.check_requirements() is already displayed through
Platform.check()).
> Remove check_requirements from setupext.

- lib/matplotlib/patches.py
Rewritten to numpydoc and some clarifications.
> Update FancyBboxPatch docs to numpydoc style

- lib/matplotlib/backend_bases.py
`MouseEvent` is a generic class for all mouse events. Some of its attributes do not have a meaning for specific events. This PR documents that.
Closes #4001.
> Clarify scope of MouseEvent attributes

- .flake8
- lib/matplotlib/backends/backend_pgf.py
- lib/matplotlib/type1font.py
> Obey flake8 "don't assign a lambda, use a def".

- .flake8
- examples/images_contours_and_fields/tricontour_smooth_delaunay.py
- examples/misc/multipage_pdf.py
- examples/pyplots/auto_subplots_adjust.py
- examples/user_interfaces/embedding_in_tk_sgskip.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/backend_cairo.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/colors.py
- lib/matplotlib/contour.py
- lib/matplotlib/quiver.py
- lib/matplotlib/scale.py
- lib/matplotlib/tight_layout.py
- lib/mpl_toolkits/axes_grid1/mpl_axes.py
- lib/mpl_toolkits/axisartist/floating_axes.py
> Fix various flake8 indent problems.

- tutorials/introductory/usage.py
The term of "state-machine" seems a bit too complex for what it's worth.
(Also remove mention of pylab at the very beginning.)
> Make intro tutorial less jargony.

- lib/matplotlib/quiver.py
Improve docs on Axes quiver. This is part of the overall Axes documentation review #10148.
> Improve docs on Axes quiver

- examples/lines_bars_and_markers/errorbar_limits_simple.py
- add some explanatory text.
- add legends so that the plots become more self-explanatory.
- reorder the plotted lines so that top to bottom in the plot has the same order as in the code and in the legend.
- add an example of 2xN yerr for comparision.
> Improve Errorbar limits example

- lib/matplotlib/pyplot.py
- `plt.show()` shows all figures as far as I know, so change the first sentence to reflect this.
- Add a proper numpydoc parameters section
> Update plt.show() doc

- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/backend_agg.py
- lib/matplotlib/backends/backend_gtk3cairo.py
This avoids setting the wait cursor when panning or zooming (that
behavior was somewhat annoying), or during an animation that renders at
least one frame per second.
Rename `_set_cursor` to `_update_cursor` as it is fairly different from
`set_cursor` and the previous name could cause confusion.  Move the
defintion of cursor-related methods to a single place.
In the case of gtk, just strip out the offending cursor related code as
the backend is deprecated and slated for removal anyways.
Fixes #9546.
> Only set the wait cursor if the last draw was >1s ago.

- lib/matplotlib/patches.py
> Add missing space in warning message

- lib/matplotlib/colors.py
Numpydoc formatting and more precise descriptions.
> Update docstring of makeMappingArray

- lib/matplotlib/widgets.py
> Fix TextBox not respecting eventson

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
> Normalize properties passed to bxp().

- lib/matplotlib/projections/polar.py
> Updated polar documentation

- doc/users/prev_whats_new/whats_new_3.1.0.rst
> fix minor typo

- lib/matplotlib/axes/_axes.py
I think this version is a bit easier to follow, by making the `try...
except` tighter around the parts that can actually fail, and by avoiding
the "raise a ValueError to catch it later to raise a different
ValueError" pattern.
> Reorganize scatter arguments parsing.

- lib/matplotlib/backends/_backend_tk.py
> Fix #13711 by importing cbook.

- .flake8
- doc/api/next_api_changes/2019-04-21-AL.rst
- lib/matplotlib/backends/_backend_tk.py
- lib/matplotlib/backends/backend_agg.py
- lib/matplotlib/backends/backend_cairo.py
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_pgf.py
- lib/matplotlib/backends/qt_editor/_formlayout.py
Some (clearly intended as internal) globals were removed without
deprecation as they cannot be properly deprecated; see changelog.
PIXELS_PER_INCH is not used anywhere.
> pep8ify backends.

- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/_backend_tk.py
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_macosx.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/backends/backend_qt5.py
- lib/matplotlib/backends/backend_webagg.py
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/backends/qt_editor/figureoptions.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/font_manager.py
- lib/matplotlib/mathtext.py
- lib/matplotlib/tests/test_rcparams.py
- lib/matplotlib/tests/test_text.py
... into a cbook._get_data_path() helper.
> Factor out retrieval of data relative to datapath

- lib/matplotlib/streamplot.py
As part of #10148: Docstring update for `Axes.streamplot`.
> Improve docsstring of Axes.streamplot

- tutorials/introductory/usage.py
> Small grammatical error.

- lib/matplotlib/backend_bases.py
Closes (I think?) https://github.com/matplotlib/matplotlib/issues/14180 and https://github.com/matplotlib/matplotlib/pull/14134#issuecomment-491527998.
@astrofrog @pllim can you confirm?
> Walk the artist tree when preparing for saving with tight bbox.

- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_qt5.py
- lib/matplotlib/backends/backend_wx.py
> Don't set missing history buttons.

- lib/matplotlib/colors.py
- lib/matplotlib/tests/test_colors.py
> Backport PR #14313 on branch v3.1.x

- lib/matplotlib/image.py
_ImageBase._make_image is a big, 267-line (+docstring) beast.  Shorten
it by ~20% by factoring out a helper for _image.resample (that takes
care of allocating the output array), and with various small cleanups.
> Shorten _ImageBase._make_image.

- .flake8
- examples/lines_bars_and_markers/horizontal_barchart_distribution.py
There's only one example for a simple (vertical) stacked bar chart. I think this is a worthwhile addition:
- It's showing the general approach how to stack multiple bars.
- It's illustrates a certain kind of common diagram.
- It shows how to draw labels with values at the bar centers.
[Example:](https://21315-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/gallery/statistics/horizontal_barchart_distribution.html#sphx-glr-gallery-statistics-horizontal-barchart-distribution-py)
> Add example for a stacked horizontal bar chart

- lib/matplotlib/tests/test_dates.py
> Use importorskip for tests depending on pytz.

- lib/matplotlib/markers.py
> Cleanup markers.py.

- lib/matplotlib/animation.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/backends/backend_cairo.py
- lib/matplotlib/collections.py
- lib/matplotlib/colorbar.py
- lib/matplotlib/image.py
- lib/matplotlib/legend.py
- lib/matplotlib/mlab.py
- lib/matplotlib/offsetbox.py
- lib/matplotlib/patches.py
- lib/matplotlib/scale.py
- lib/matplotlib/stackplot.py
- lib/matplotlib/streamplot.py
- lib/matplotlib/text.py
- lib/matplotlib/ticker.py
- lib/mpl_toolkits/axes_grid1/axes_divider.py
- lib/mpl_toolkits/axes_grid1/axes_size.py
- lib/mpl_toolkits/axisartist/axislines.py
- lib/mpl_toolkits/mplot3d/axes3d.py
Pretty much what it says in the title. Should get more consistency in error messages, too.
> Use cbook._check_in_list more often.

- setupext.py
PkgConfig.setup_extension works just fine as a free-standing function.
> Kill the PkgConfig singleton in setupext.

- lib/matplotlib/tests/test_transforms.py
Picking up a loose end from #6731.
> Remove remaining unittest.TestCase uses

- examples/lines_bars_and_markers/marker_reference.py
> Don't use deprecated mathcircled in docs.

- src/checkdep_freetype2.c
- src/checkdep_libpng.c
likely fixes #14370, attn @pllim @astrofrog
> Properly hide __has_include to support C++<17 compilers.

- lib/matplotlib/tests/test_mathtext.py
> Update link to "MathML torture test".

- lib/matplotlib/tests/test_mathtext.py
- tutorials/text/mathtext.py
> Remove remaining unicode-strings markers.

- doc/sphinxext/math_symbol_table.py
> Remove extra \iint in math_symbol_table for document

- matplotlibrc.template
Copied comment from https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/rcsetup.py#L1466
> Add explanation of animation.embed_limit to matplotlibrc.template

- examples/widgets/span_selector.py
> DOC: add note to example about keeping hard-ref to SpanSelector

- lib/matplotlib/figure.py
- lib/matplotlib/pyplot.py
Mostly indentation problems, plus small edits.
> Fix docstring of subplots().

- examples/widgets/span_selector.py
> Fix ReST note in span selector example

- lib/matplotlib/backends/web_backend/js/mpl.js
Apparently fixes #12201.
Note: This fixes the issue. However, I've not dug into the nbagg details. So please check if this is the *right* way to fix it.
> Fix clearing rubberband on nbagg

- examples/animation/random_walk.py
- examples/animation/strip_chart.py
- examples/axisartist/demo_axis_direction.py
- examples/axisartist/demo_curvelinear_grid2.py
- examples/axisartist/simple_axis_pad.py
- examples/event_handling/pick_event_demo2.py
> Misc. docstring cleanups.

- lib/matplotlib/projections/geo.py
Went into these weeds first while searching for a solution for #astropy/astropy#8792
> MAINT: Minor cleanup to make functions more self consisntent

- .travis.yml
They're each used in only a single place so inlining them makes their
usage simpler to follow.
Also various small cleanups to .travis.yml.
> Inline $MPLLOCALFREETYPE/$PYTEST_ADDOPTS/$NPROC in .travis.yml.

- lib/matplotlib/axis.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/contour.py
- lib/matplotlib/legend_handler.py
- lib/matplotlib/text.py
- lib/mpl_toolkits/axisartist/axis_artist.py
- lib/mpl_toolkits/axisartist/floating_axes.py
> Replace list.extend by star-expansion or other constructs.

- lib/matplotlib/gridspec.py
- lib/matplotlib/tight_layout.py
Would still benefit from more cleanup. But that's for some later time.
> Improve docs on gridspec

- pytest.ini
... to run the tests without pytest-timeout installed.
Basically the same as #14353.
> Register timeout pytest marker.

- lib/matplotlib/figure.py
Keep consistance with docstring
close #14467
> change ginoput docstring to match behavior

- lib/matplotlib/gridspec.py
- lib/matplotlib/tight_layout.py
Backport PR #14449: Improve docs on gridspec
> Backport PR #14449: Improve docs on gridspec

- lib/matplotlib/tests/test_units.py
- lib/matplotlib/units.py
closes #14356
This is a slight modification and a test of what @anntzer proposed in the issue.
Will not back port cleanly but :woman_shrugging: .
> FIX: if the first elements of an array are masked keep checking

- lib/matplotlib/tests/test_units.py
- lib/matplotlib/units.py
> Backport #14429 on v3.1.x

- lib/matplotlib/backends/backend_ps.py
Admittedly the nested conditional on %%Title is a bit ugly, but I think
the new form clearly shows the document structure better.
> fstringify backend_ps more.

- doc/api/next_api_changes/2019-06-07-AL.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axis.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/blocking_input.py
- lib/matplotlib/category.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/cm.py
- lib/matplotlib/dviread.py
- lib/matplotlib/figure.py
- lib/matplotlib/rcsetup.py
- lib/matplotlib/spines.py
- lib/matplotlib/table.py
- lib/matplotlib/transforms.py
- lib/matplotlib/tri/trifinder.py
- lib/matplotlib/tri/triinterpolate.py
- lib/matplotlib/tri/tripcolor.py
- lib/matplotlib/tri/trirefine.py
- lib/matplotlib/tri/tritools.py
Does the same as _check_in_list... but for isinstance checks.
A large number of checks for Normalize were grouped into
`ScalarMappable.set_norm`.
> Add _check_isinstance helper.

- lib/matplotlib/rcsetup.py
> Simplify various validators in rcsetup.

- lib/matplotlib/__init__.py
- lib/matplotlib/_constrained_layout.py
- lib/matplotlib/axis.py
- lib/matplotlib/colorbar.py
- lib/matplotlib/dates.py
- lib/matplotlib/image.py
- lib/matplotlib/patches.py
- lib/matplotlib/patheffects.py
- lib/matplotlib/projections/polar.py
- lib/matplotlib/ticker.py
More fixes to pydocstyle D403 (First word of the first line should be properly capitalized); and general docstring improvement on the way.
> More fixes to pydocstyle D403 (First word capitalization)

- lib/matplotlib/quiver.py
As part of #10148: Docstring update for `Axes.barbs`.
> Improve docstring of Axes.barbs

- lib/matplotlib/tests/test_backend_qt.py
In test_backend_qt, qt_key is basically a complicated way to access Qt
modifier keys using nonstandard names that are not used anywhere but in
the tests (ControlKey instead of Key_Control).  Get rid of it and just
use standard Qt modifier key names.  Simplify the qt_module fixture as a
consequence (just returning QtCore).
> Simplify Qt tests.

- examples/event_handling/path_editor.py
- examples/event_handling/pick_event_demo.py
- examples/event_handling/poly_editor.py
- examples/lines_bars_and_markers/filled_step.py
- examples/lines_bars_and_markers/markevery_demo.py
- examples/statistics/barchart_demo.py
- examples/subplots_axes_and_figures/secondary_axis.py
- examples/tests/backend_driver_sgskip.py
- examples/text_labels_and_annotations/demo_text_path.py
- examples/units/basic_units.py
- examples/units/evans_test.py
- examples/widgets/menu.py
- examples/widgets/rectangle_selector.py
- tutorials/colors/colormap-manipulation.py
For now this covers only the examples directory. There's more in the actual code base, but I feel it's better to split that to make the PR not too large and easier to review.
> Fix pydocstyle D403 (First word of the first line should be properly capitalized) in examples

- doc/users/next_whats_new/2019-02-27-AL.rst
- lib/matplotlib/tests/test_units.py
- lib/matplotlib/units.py
> Make unit converters also handle instances of subclasses.

- .flake8
- lib/matplotlib/mathtext.py
> mathtext style fixes.

- tutorials/introductory/usage.py
While discussing about entry-level docs in the weekly call we realized that the beginning of https://matplotlib.org/devdocs/tutorials/introductory/usage.html was written in a fairly confusing manner.  This is an attempt to clarify things a bit.  In particular, note that it **starts** by presenting the OO-approach, because I personally think the magicness of pyplot really impedes clarity.
> Rewrite intro to usage guide.

- lib/matplotlib/sphinxext/plot_directive.py
We can always switch to Agg now.
> Simplify backend switching in plot_directive.

- doc/devel/contributing.rst
That section basically duplicates the "what is a backend" section in the usage guide (https://matplotlib.org/devdocs/tutorials/introductory/usage.html#backends), but does so less well, and doesn't provide relevant information for actually *developing* a new backend.
> Remove the "Developing a new backend" section from contributing guide.

- lib/matplotlib/__init__.py
When suggesting to update matplotlibrc, link to the relased version of the current code, not master.
Follow up to prevent confusion of #14547.
> Link to matplotlibrc of used version

- doc/api/index.rst
- doc/api/sphinxext_plot_directive_api.rst
- doc/devel/documenting_mpl.rst
- doc/devel/index.rst
- doc/devel/plot_directive.rst
- lib/matplotlib/sphinxext/plot_directive.py
Sure, it's mostly for devs, but there's plenty of things in the API
index that are for mostly devs too, so move it there.
> Move plot_directive doc to main API index.

- .flake8
- doc/sphinxext/github.py
- doc/sphinxext/math_symbol_table.py
- doc/sphinxext/skip_deprecated.py
- doc/users/generate_credits.py
- lib/matplotlib/pylab.py
- tools/compare_backend_driver_results.py
> Misc. style fixes.

- doc/faq/howto_faq.rst
Closes (indirectly) #14304.  (The OP needs to use a noninteractive backend; we'll be able to point him to this doc entry.)
> Clarify how to work with threads.

- lib/matplotlib/axes/_base.py
- lib/matplotlib/offsetbox.py
> improve documentation of OffsetBox

- lib/matplotlib/cbook/__init__.py
Some random docstring cleanup.
> cbook docs cleanup

- lib/matplotlib/testing/decorators.py
This seems to shave a few minutes(!) from the CI.
> Use symlinks instead of copies for test result_images.

- lib/matplotlib/axes/_base.py
Accidentally added by @timhoffm in #13591 - if tests pass I will self-merge.
> Remove print statements

- lib/matplotlib/collections.py
- lib/matplotlib/tests/test_collections.py
Fixes #14487. Not entirely sure if casting any input to an array is correct, but will see if the tests all pass.
> Make sure EventCollection doesn't modify input in-place

- lib/matplotlib/backends/_backend_tk.py
Closes https://github.com/matplotlib/matplotlib/issues/1219 (specifically https://github.com/matplotlib/matplotlib/issues/1219#issuecomment-503057822).
Release critical, because a regression.
> Don't assume tk canvas have a manager attached.

- .travis.yml
- doc-requirements.txt
Since there seems to be some interest in `2.2.x` patches, here's an attempt to fix the travis build.
> Try to fix 2.2.x travis building

- .flake8
- setupext.py
> Fix overly long lines in setupext.

- lib/matplotlib/axes/_axes.py
> Update hist2d() docstring.

- doc/devel/contributing.rst
Alternative proposal to #14545, as discussed therein.
> Coding guidelines concerning the API

- lib/matplotlib/animation.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/projections/polar.py
- lib/matplotlib/text.py
- lib/matplotlib/tri/triinterpolate.py
- lib/matplotlib/widgets.py
Some random numpydoc formatting cleanup.
> Fix numpydoc formatting

- examples/misc/custom_projection.py
- examples/statistics/barchart_demo.py
- examples/statistics/boxplot_demo.py
- examples/ticks_and_spines/date_index_formatter2.py
- lib/matplotlib/backends/backend_agg.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/colors.py
- lib/matplotlib/dates.py
- lib/matplotlib/image.py
- lib/matplotlib/patches.py
- lib/matplotlib/projections/geo.py
- lib/matplotlib/tests/test_ticker.py
- lib/matplotlib/ticker.py
- lib/matplotlib/widgets.py
- lib/mpl_toolkits/mplot3d/axes3d.py
Compared to np.round, builtin round is 20x faster for python floats and
2x faster for numpy floats (it's admittedly unlikely that any of the
places patched is an actual bottleneck).
On Py2 builtin round and np.round were not equivalent because builtin
round rounded halves away from zero, but now both round-to-even.
Small misc. changes; the rearrangement in backend_agg.draw_text is to
make the implementation more similar to draw_mathtext (just above).
> Use builtin round instead of np.round for scalars.

- matplotlibrc.template
This PR breaks a long line of _color values_ description into a list.
> Improve readability of matplotlibrc.template

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axis.py
- lib/matplotlib/backends/backend_cairo.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/mathtext.py
- lib/matplotlib/offsetbox.py
- lib/matplotlib/testing/jpl_units/UnitDbl.py
- lib/mpl_toolkits/axisartist/axis_artist.py
- lib/mpl_toolkits/mplot3d/axes3d.py
Also rename the first parameter of these helpers to start with an
underscore, to mark them as effectively positional-only.
See discussion in https://github.com/matplotlib/matplotlib/pull/14565#discussion_r294633199.
> Add a _check_getitem helper to go with _check_in_list/_check_isinstance.

- lib/matplotlib/cm.py
... plus small docstrings cleanups.
> Simplify colormap reversal.

- examples/subplots_axes_and_figures/subplots_demo.py
``plt.subplot`` is different from ``plt.subplots``, and this great introduction article is about ``plt.subplots``.
> Revise the misleading title for subplots demo

- tutorials/intermediate/color_cycle.py
> Make property name be consistent with rc parameter.

- doc/devel/testing.rst
- doc/thirdpartypackages/index.rst
Backport PR #14561 on branch v3.1.1-doc
> Backport PR #14561 on branch v3.1.0-doc

- lib/matplotlib/backends/backend_gtk3.py
I missed this class in #12760.
> More deduplication of backend_tools.

- examples/lines_bars_and_markers/fill_between_demo.py
- More extensive (and hopefully instructive) descriptions.
- Plots better tailored to illustrate the descriptions.
<s>https://22159-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/gallery/lines_bars_and_markers/fill_between_demo.html#sphx-glr-gallery-lines-bars-and-markers-fill-between-demo-py</s>
https://22611-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/gallery/lines_bars_and_markers/fill_between_demo.html#sphx-glr-gallery-lines-bars-and-markers-fill-between-demo-py
> Improve example for fill_between

- doc/faq/howto_faq.rst
- tutorials/intermediate/constrainedlayout_guide.py
- tutorials/intermediate/gridspec.py
- tutorials/text/text_intro.py
> Small patches on Docs (Tutorials and FAQ)

- lib/mpl_toolkits/mplot3d/axis3d.py
> Trivial simplification to Axis3d._get_coord_info.

- examples/text_labels_and_annotations/demo_text_path.py
> Cleanup demo_text_path.

- tutorials/introductory/usage.py
As a newbie, I want to create files, and thus use the non-interactive backends. The tutorial talks about them existing, but doesn't have the one line needed to create files from the plots.
> Point towards how to save output of non-interactive backends

- examples/user_interfaces/svg_histogram_sgskip.py
- lib/matplotlib/image.py
> Tiny docs/comments cleanups.

- lib/mpl_toolkits/axisartist/axis_artist.py
> Remove axis_artist _update, which is always a noop.

- .circleci/config.yml
Merge pull request #14775 from alexrudy/fix-circleci
DOC: Fix CircleCI builds
> Backport PR #14775: DOC: Fix CircleCI builds

- lib/matplotlib/mlab.py
> Cleanup mlab.detrend.

- examples/text_labels_and_annotations/rainbow_text.py
The latter is quite obscure...
> Prefer Affine2D.translate to offset_transform in examples.

- doc/index.rst
It was very difficult to find the developer's guide on the matplotlib website.
So added a pointer to https://matplotlib.org/devel/index.html on the homepage which makes it easy to find.
closes #14754
> DOC: Update the documetation of homepage of website

- lib/matplotlib/dates.py
> Cleanup dates.py module docstrings.

- INSTALL.rst
- doc/users/prev_whats_new/whats_new_1.5.rst
> Fix some broken refs in the docs.

- lib/matplotlib/axes/_base.py
- The unit handling at the top of `__call__` is duplicated with
`Axes._process_unit_info`, so just use that.
- The conditional call to `convert_xunits` in `_xy_from_xy` can
be moved to `_makefill` (the only case where it's needed), and made
non-conditional (if `x` is not unitized, `convert_xunits` will just
return it as is).
- The rest of `_xy_from_xy` can be inlined into its only call site
(`_plot_args`) which also makes clear that the calls to `_check_1d`
are redundant because the caller already calls `_check_1d` (possibly
via `index_of`) immediately before.
> Simplify _process_plot_var_args.

- examples/pyplots/text_layout.py
By working with figure-level artists rather than axes-level ones (where
the axes cover the whole figure...) we don't have do specify the
transform again and again.
> Simplify text_layout example.

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
> Inset orientation

- lib/matplotlib/axes/_axes.py
> Small docstring updates

- lib/mpl_toolkits/axisartist/axis_artist.py
> Kill some never-used attributes.

- doc/api/next_api_changes/2019-07-16-TH.rst
> API change note on automatic blitting detection for backends

- examples/event_handling/pipong.py
- examples/statistics/errorbars_and_boxes.py
- examples/units/evans_test.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/backend_tools.py
- lib/matplotlib/backends/backend_pgf.py
- lib/matplotlib/table.py
- lib/matplotlib/testing/jpl_units/StrConverter.py
- lib/matplotlib/tests/test_mathtext.py
- lib/matplotlib/tight_layout.py
- lib/matplotlib/widgets.py
- lib/mpl_toolkits/axes_grid1/axes_divider.py
- lib/mpl_toolkits/mplot3d/art3d.py
Less list.append, more comprehensions/star-unpacks/list.extend/etc.
> Misc. simplifications.

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/projections/polar.py
- lib/matplotlib/tests/test_backend_cairo.py
- lib/matplotlib/tri/triangulation.py
- lib/mpl_toolkits/mplot3d/axes3d.py
- more check_in_list
- remove unused import
- more literal sets
- more unpacking and star-unpacking
> Various small simplifications

- lib/mpl_toolkits/axisartist/axis_artist.py
- lib/mpl_toolkits/axisartist/floating_axes.py
... in particular merging two consecutive `if ... else ...; if ... else
...` that use the same condition, and replacing `astype(float, copy=True)`
by just `copy()` as it is clear that the arrays are already float at
that point.
Also some minor whitespace fixes.
> More floating_axes cleanup.

- doc/devel/gitwash/configure_git.rst
Small doc changes to help new devs set up git. Removed "Of course..." because words like "of course" and "just do..." can be off-putting to people who don't see what follows as obvious.
> Doc changes to git setup

- lib/matplotlib/backends/backend_wx.py
> Factor out common parts of wx event handlers.

- lib/matplotlib/axes/_axes.py
As part of #10148: Docstring update for `Axes.hexbin`.
> Improve docstring of Axes.hexbin

- lib/matplotlib/axes/_axes.py
Backport PR #14839 on branch v3.1.x
> Backport PR #14839 on branch v3.1.x

- lib/matplotlib/artist.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
- lib/matplotlib/collections.py
- lib/matplotlib/figure.py
- lib/matplotlib/image.py
- lib/matplotlib/legend.py
- lib/matplotlib/lines.py
- lib/matplotlib/offsetbox.py
- lib/matplotlib/patches.py
- lib/matplotlib/quiver.py
- lib/matplotlib/table.py
- lib/matplotlib/text.py
Closes #6324 (... except in rare cases of artists who don't know their parent figure).
> Check canvas identity in Artist.contains.

- lib/matplotlib/tests/test_axes.py
> Stopgap fix for pandas converters in tests.

- lib/mpl_toolkits/mplot3d/axis3d.py
Depends on #13363 (now merged).
> Numpyfy tick handling code in Axis3D.

- examples/lines_bars_and_markers/bar_stacked.py
Avoid using the stateful plt interface
I needed an example of stacked bar that use the more Object oriented interface, so I updated the Matplotlib one and sent a PR.
> Update bar stacked example to directly manipulate axes.

- lib/matplotlib/scale.py
- lib/matplotlib/transforms.py
> Cleanup of docstrings of scales

- doc-requirements.txt
- doc/users/prev_whats_new/whats_new_1.0.rst
Should help the circleCI build (and maybe even fix it!)
> Fix circleCI build on 2.2.x

- lib/matplotlib/axes/_base.py
Fixes https://github.com/matplotlib/matplotlib/issues/13668
> Clearer error message for plt.axis()

- lib/matplotlib/axes/_axes.py
> Vectorize handling of stacked/cumulative in hist().

- lib/mpl_toolkits/mplot3d/axes3d.py
> Remove unused private helper method in mplot3d.

- doc/api/next_api_changes/2019-03-29-AL.rst
- doc/api/testing_api.rst
- lib/matplotlib/testing/disable_internet.py
Goes on top of #13782 (which actually makes this functionality unused).
There are standalone modules doing that and there isn't really a reason for this functionality to be part of mpl.
> Deprecate disable_internet.

- lib/matplotlib/pyplot.py
Unless `costum` is a specific projection related term, but google was of no help.
> DOC: typo x2 costum -> custom

- examples/subplots_axes_and_figures/invert_axes.py
Avoid using the stateful `plt.` way and use the more accepted object
oriented way in matplotlib.
> DOC: Update invert_example to directly manipulate axis.

- lib/matplotlib/__init__.py
> Gracefully handle encoding problems when querying external executables.

- examples/misc/demo_agg_filter.py
- lib/matplotlib/tests/test_agg.py
> Cleanup demo_agg_filter.

- lib/matplotlib/table.py
This cherry-picks the commit from #14965 on to the master branch.
> DOC: correct table docstring

- lib/matplotlib/backends/backend_qt5.py
Can be tested on a non-high-dpi setup by setting e.g. QT_SCALE_FACTOR=2.
before:
after:
Compare with https://github.com/matplotlib/matplotlib/pull/14697, which did this for non-high-dpi setups.
> Don't enlarge toolbar for Qt high-dpi.

- tutorials/introductory/pyplot.py
> Typo fixes in pyplot.py

- tutorials/introductory/usage.py
> Improve backends documentation

- lib/matplotlib/tests/test_dates.py
> No need to access filesystem in test_dates.py.

- setup.py
- setupext.py
> pathlibify/fstringify setup/setupext.

- src/_macosx.m
Removed compiler checks for minimum Mac OS X 10.6, as matplotlib no longer supports <10.6.
> Matplotlib requires Python 3.6, which in turn requires Mac OS X 10.6+

- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/tests/test_axes.py
> FIX: support pandas 0.25

- tutorials/colors/colormap-manipulation.py
Update the colormap manipulation tutorial with two main points:
* There is an important difference between ListedColormaps and LinearSegmentedColormaps which was not at all apparent from the tutorial
* The pretty useful `LinearSegmentedColormap.from_list` method wasn't mentionned at all.
Link to [the proposed tutorial](https://679-100939689-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/tutorials/colors/colormap-manipulation.html#sphx-glr-tutorials-colors-colormap-manipulation-py).
> DOC: colormap manipulation tutorial update

- lib/matplotlib/gridspec.py
> Update docs of GridSpecBase

- lib/matplotlib/backend_bases.py
Describe the `FigureManagerBase` class. While I think "manager" really a bad term here, we're stuck with it. So at least describe what it's about.
Note: Im quite unclear on the role of the FigureManager concerning the event stuff, therefore I've kept that part really vague. If somebody has a better description commits are welcome. Otherwise, this is at least a lot better than the current documentation.
> Describe FigureManager

- lib/matplotlib/gridspec.py
Some of the aspects of relation to figures with constrained layout and the `update()` method are not quite clear to me. I've added docs for them as far as I could understand, but that could certainly be improved further. OTOH this is already an improvement as is and could be merged as such.
> Update docs of GridSpec

- lib/matplotlib/axes/_base.py
> Clarify effect of axis('equal') on explicit data limits

- doc/_templates/donate_sidebar.html
- doc/api/api_changes.rst
- doc/api/prev_api_changes/api_changes_3.1.1.rst
- doc/citing.rst
- doc/devel/documenting_mpl.rst
- doc/devel/gitwash/git_links.inc
- doc/index.rst
- doc/missing-references.json
- doc/users/github_stats.rst
- doc/users/prev_whats_new/github_stats_3.0.2.rst
- doc/users/prev_whats_new/github_stats_3.1.0.rst
- doc/users/shell.rst
- lib/matplotlib/axes/_base.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/ticker.py
- lib/mpl_toolkits/mplot3d/axes3d.py
- tools/gh_api.py
- tools/github_stats.py
- tutorials/introductory/usage.py
Opening a PR to run CI.  It all passes locally, but erring on the side of caution.
> v3.1.x merge up

- doc/conf.py
@tacaswell  enquired on gitter about adding a check on the python version in **doc/conf.py**, so I have added a check and an error message to **conf.py**, it checks if the python version is 2.7.16 or lower, and then tells the user about it.
> Python version conf.py

- doc/devel/documenting_mpl.rst
- doc/missing-references.json
- doc/sphinxext/missing_references.py
- lib/matplotlib/artist.py
This fixes an exception just merged to master and the other half of
the issues @ImportanceOfBeingErnest is having in #14917.
> DOC: more nitpick follow up

- lib/matplotlib/font_manager.py
- tools/make_icons.py
- Auto-download and cache fontawesome otf.
- Support writing results to another directory (useful when testing, to
not mess with the repo).
Also, support for pathlib in font_manager (made necessary by the changes
in make_icons.py -- specifically, backend_pdf's internals don't handle
FontProperties.get_fname returning a Path).
Useful if you want to play with mplcairo wrt. https://github.com/matplotlib/matplotlib/issues/14939 (https://github.com/matplotlib/matplotlib/issues/14939#issuecomment-516813464).
> Improvements to make_icons.py.

- README.rst
Added information about citation.
Added information about citation
> Add citation info to README

- examples/misc/agg_buffer_to_array.py
> DOC: create a Agg figure without pyplot in buffer example

- doc/sphinxext/missing_references.py
following ongoing discussion at https://github.com/matplotlib/matplotlib/pull/15048#discussion_r313353112
> Clarify unnecessary special handling for colons in paths.

- lib/matplotlib/figure.py
n.b. I have no idea what the description for the `forward` argument really means, so if anyone has a better suggestion than what is present please let me know!
> numpydoc set_size_inches docstring

- README.rst
Follow on from #14844, making the text a bit less wordy.
> Make citation bit of README less wordy

- doc/api/prev_api_changes/api_changes_2.0.0.rst
- doc/api/prev_api_changes/api_changes_2.0.1.rst
- doc/api/prev_api_changes/api_changes_2.1.0.rst
- doc/api/prev_api_changes/api_changes_2.1.2.rst
- doc/api/prev_api_changes/api_changes_2.2.0.rst
- doc/missing-references.json
Some more cross reference fixes.
> Fix cross-references in API changes < 3.0.0.

- examples/ticks_and_spines/spines.py
- The usual "dedent the rst list".
- Use constrained_layout instead of some hardcoded spacing.
> Cleanup spines example.

- doc/api/next_api_changes/2019-06-12-AL.rst
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/_backend_tk.py
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_macosx.py
- lib/matplotlib/backends/backend_qt4.py
- lib/matplotlib/backends/backend_qt4agg.py
- lib/matplotlib/backends/backend_qt4cairo.py
- lib/matplotlib/backends/backend_qt5.py
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/pyplot.py
In mpl 3.0, the required_interactive_framework attribute was added to
backend modules.  However, it is sometimes required to access it from a
canvas *instance* (e.g. in _fix_ipython_backend2gui), but the pattern
`sys.modules[cls.__module__].required_interactive_framework` is brittle
(e.g. it is broken by third-party subclasses).
Instead it makes more sense to put the attribute on the canvas class;
one can easily and robustly go from the backend module to the canvas
class by accessing the FigureCanvas attribute.
xref https://gitter.im/matplotlib/matplotlib?at=5ced522cef853135c83ae7d6, #14426.
Milestoned as 3.2 as the API is still quite new so the earlier we fix it, the better.
> Move required_interactive_framework to canvas class.

- doc/devel/coding_guide.rst
As discussed during the dev call.
attn @tacaswell
> Propose change to PR merging policy.

- doc/index.rst
This is at NF's request to standardize this language across all of the
projects.
> DOC: update language around NF

- lib/matplotlib/ticker.py
This is just a cleanup to logic, and hopefully will form part of a larger attempt to clean and fix various parts of `SymLog` locating and ticking.
> Simplify symlog range determination logic

- lib/matplotlib/backends/backend_ps.py
This allows convert_psfrags to also benefit from improvements to
texmanager, such as the recent addition of support for unicode minus (#14567).
> Reuse TexManager implementation in convert_psfrags.

- lib/matplotlib/_layoutbox.py
> Cleanup layout_from_subplotspec.

- doc/api/next_api_changes/2018-02-18-AL.rst
> Fix missing references in doc build.

- lib/matplotlib/quiver.py
Follow up on #14424 for docstring. This is the [suggested edit](https://github.com/matplotlib/matplotlib/pull/14424/files#r318329959) from #14424 as a new PR.
> Follow up on #14424 for docstring

- lib/matplotlib/cm.py
removed a typo r in ScalarMappable
> removed a typo

- lib/matplotlib/dates.py
Closes #15178
This was just a typo...
> FIX: proper call to zero_formats

- lib/matplotlib/tests/test_image.py
- lib/matplotlib/ticker.py
Backport PR #15140 on branch v3.1.x
> Backport PR #15140 on branch v3.1.x

- INSTALL.rst
Forgot to do this in #13064, which removed that option.
> Remove mention of now-removed basedir setup option.

- doc/api/next_api_changes/2019-02-28-AL.rst
- lib/matplotlib/axes/_subplots.py
- lib/matplotlib/gridspec.py
- lib/matplotlib/tests/test_subplots.py
> Improve handling of subplots spanning multiple gridspec cells.

- .flake8
They're already being checked (with a bunch of exclusions) anyways, and
this avoids a bunch of spurious warnings when running flake8 from a
checkout with the docs built.
> Exclude s-g generated files from flake8 check.

- lib/matplotlib/patches.py
- lib/matplotlib/path.py
Closes #14207 by try to document the exact behavior*.
\* I sometimes marvel at the inner workings of Matplotlib :slightly_frowning_face:.
> Update docstrings of contains_point(s) methods

- examples/lines_bars_and_markers/horizontal_barchart_distribution.py
Add `plt.show()` at the end of example.
Quick fix for https://stackoverflow.com/questions/57836989/original-code-from-matplotlib-site-not-work
> Doc: Add `plt.show()` to horizontal bar chart example

- lib/matplotlib/backends/_backend_tk.py
The base class already defines the public .num attribute, let's just use
that like every other backend.
> Kill FigureManagerTk._num.

- lib/matplotlib/widgets.py
> Cleanup widgets.py.

- lib/matplotlib/patches.py
> Minor docstring style cleanup

- lib/matplotlib/figure.py
- lib/matplotlib/projections/__init__.py
> Cleanup projections/__init__.py.

- lib/matplotlib/widgets.py
> Cleanup widgets docstrings.

- lib/matplotlib/patches.py
- lib/matplotlib/path.py
Followup to #15216, which had some typos and unclear formulations.
> contains_point() docstring fixes

- lib/matplotlib/backends/backend_pdf.py
- Inline _unpack into its only caller writeImages.
- Let _writeImg infer the image size and grayscaleness from the data
shape.
preliminary work towards https://github.com/matplotlib/matplotlib/issues/15165.
> Simplify pdf image output.

- tutorials/text/mathtext.py
There was no example with multi-letter subscripts or superscripts in mathtext tutorial, so I added an example to this tutorial to avoid confusion when handling multi-letter subscripts or superscripts for new users.
> added multi-letter example to mathtext tutorial

- lib/matplotlib/backends/backend_gtk3.py
> Turn gtk3 pan/zoom button into togglable buttons.

- lib/matplotlib/rcsetup.py
- lib/matplotlib/tests/test_rcparams.py
Fixes #15240. Solution taken from https://github.com/matplotlib/matplotlib/issues/15240#issuecomment-529859467.
> Fix font weight validation

- doc/devel/coding_guide.rst
Even though reviewers should know, that information was missing.
> Mention labels and milestones in PR review guidelines

- lib/matplotlib/rcsetup.py
- lib/matplotlib/tests/test_rcparams.py
> Backport PR #15271 on branch v3.1.x (Fix font weight validation)

- lib/matplotlib/font_manager.py
- Reword FontManager docstring.
- Fix incorrect doc for rebuild_if_missing paramter to findfont.
- Pass fallback_to_default/rebuild_if_missing as explicit keyword
arguments, rather than positionally (``True, False`` is just too hard
to read).
> Cleanup font_manager.

- lib/matplotlib/rcsetup.py
See https://github.com/matplotlib/matplotlib/pull/15271#pullrequestreview-289635420
I'm sorry, this slipped in with a force push in some late stage.
> Fix typo/bug from 18cecf7

- doc/conf.py
Closes #15285
Instead of hardcoding the Copyright
year, which needs to be changed every year,
it now uses datetime to fetch the current year.
> Autogenerate footer Copyright year

- doc/_static/mpl.css
Closes #15306  The footer is right-justified, and at least to me, looks weird considering the text above has a 240pt margin.  Not sure this is the right solution.  Maybe the footer needs a margin as well, in which case right justification may be OK
> DOC: center footer

- doc/users/event_handling.rst
The list of events you may connect to misses the close event. This adds it to that list.
> Doc: Add close event to list of events

- lib/matplotlib/backends/backend_qt4.py
It's already been removed from backend_qt5 (in 3.2), so without this PR
backend_qt4 just fails to import...
> Remove error_msg_qt from backend_qt4.

- doc/missing-references.json
- doc/sphinxext/missing_references.py
This avoids needlessly big diffs when the file needs to be regenerated (see e.g. #15320).
> Sort missing_references.json.

- lib/matplotlib/colorbar.py
Docstring changes only.
Ping @story645 if you want to check my wording :smile:.
> Update colorbar docs

- lib/matplotlib/backends/backend_wx.py
1) GetDirectory() returns the currently selected directory, which may
not match the user-input directory, e.g. if the user types in an
absolute path ("/home/user/foo.png") -- in that case the file was
saved to the wrong directory.  Instead use GetPath(), which returns
the full path.
2) Correctly use and update rcParams["savefig.directory"], as in the
other backends.
> Fixes for wx savefig dialog.

- examples/user_interfaces/embedding_in_wx4_sgskip.py
- lib/matplotlib/bezier.py
As it turns out, it is simpler to write the d-dimensional version than
the 2-dimensional special case.
I initially tried to rebase the original PR (#9686, from @ijackson) but the codebase has diverged to much for it to make sense.
> Simplify and generalize BezierSegment.

- lib/matplotlib/figure.py
by moving initialization, well, to `__init__`.
Also improve the class docstring.
> Simplify SubplotParams.update().

- lib/matplotlib/backend_bases.py
- lib/matplotlib/patches.py
- lib/matplotlib/tests/test_compare_images.py
- lib/matplotlib/tests/test_image.py
... due to #15210 crossing wires with other PRs.
Also needed to revert part of #14845 (cleanup) which exposed some of the issues hinted at in #14694.
will self-merge on CI pass.
> Fix broken imports.

- tutorials/colors/colormapnorms.py
Backport PR #15364 on branch v3.1.1-doc
> Backport PR #15364 on branch v3.1.1-doc

- lib/mpl_toolkits/mplot3d/axes3d.py
The ```quiver``` function, in the axes3d module, has a loop calling ```calc_arrow``` which operates on a single vector. This can become very time consuming when the number of vectors is large.
The ```calc_arrow``` function could be easily vectorized, which could achieve speedup, and this PR presents a vectorized version.
I did some tests that show significant time reduction, where this loop is the bottle neck, but the tests were not so organized.
I would like to supply simple speed comparison test, but the ```calc_arrow``` function is an inner function of the ```quiver``` function and I couldn't find an elegant way to test.  
Could you suggest a method by which I could supply a time comparison?
Btw i'm quite new in contributing to projects so if there are additional things I should know …
> vectorized calc_arrow loop in quiver

- doc/api/next_api_changes/README.rst
> Update the readme on providing  API changes

- INSTALL.rst
- Corrected spacing error of commands in section Installing from Source and Building on Mac
> Updated INSTALL.rst to correct install commands

- lib/matplotlib/patches.py
Update the documentation of `BoxStyle`.
> Update docs of BoxStyle

- lib/matplotlib/backends/backend_wx.py
> Fix range(len()) usages

- doc/index.rst
Add a mention of discourse to the front page
> DOC: mention discourse main page

- examples/ticks_and_spines/tick-locators.py
- Cleanup to make the code more compact and readable.
- Nicer formatting of the titles (color and monospaced font).
- Meaningful summary at the top.
For comparison:
- [current version](https://matplotlib.org/devdocs/gallery/ticks_and_spines/tick-locators.html)
- [new version](https://circleci.com/gh/matplotlib/matplotlib/25742/artifacts/0//home/circleci/project/doc/build/html/gallery/ticks_and_spines/tick-locators.html)
> Improve example for tick locators

- doc/api/colors_api.rst
- doc/api/prev_api_changes/api_changes_3.2.0/deprecations.rst
- examples/userdemo/colormap_normalizations_diverging.py
- lib/matplotlib/colors.py
- lib/matplotlib/tests/test_colorbar.py
- lib/matplotlib/tests/test_colors.py
- tutorials/colors/colormapnorms.py
closes #15336
attn @ivanov @efiring @ImportanceOfBeingErnest
> API: rename DivergingNorm to TwoSlopeNorm

- .appveyor.yml
- INSTALL.rst
- ci/azure-pipelines-steps.yml
- doc/faq/environment_variables_faq.rst
- doc/faq/installing_faq.rst
- setupext.py
First commit:
A default build of freetype (e.g. the one from MPLLOCALFREETYPE=1) uses
its own vendored version of zlib (see FT_CONFIG_OPTION_SYSTEM_ZLIB in
ftoption.h), so we don't need to link to zlib in that case; if we're
linking against a system freetype then we can assume that pkg-config
will list the right libraries to link.
https://git.savannah.gnu.org/cgit/freetype/freetype2.git/tree/include/freetype/config/ftoption.h#n204
Not linking zlib explicitly means that the staticbuild option is not
used anymore and can just be stripped out.
Second commit:
Update build docs.
TL;DR: set MPLLOCALFREETYPE=1 and call it a day, unless you really know
what you want to do.
> Don't link ft2font to zlib by default.

- setup.cfg.template
I forgot to remove it there when it was removed from setupext.py (in https://github.com/matplotlib/matplotlib/commit/01b5833a1e0cd297452630b7d6b8a1ce909f2579#diff-c28358ce9623af21f7b6e068f69085b7L154).
> Remove staticbuild option from setup.cfg.template.

- examples/ticks_and_spines/tick-locators.py
This code does not have any effect and should have been removed already in #15453.
> Remove unused code (remainder from #15453)

- examples/specialty_plots/anscombe.py
This is a showcase example, so let's polish it up a bit.
> Rewrite Anscombe's quartet example

- lib/matplotlib/_constrained_layout.py
> Trivial style fixes to constrained_layout.

- doc/api/next_api_changes/deprecations.rst
- lib/mpl_toolkits/axisartist/angle_helper.py
- lib/mpl_toolkits/tests/test_axisartist_grid_helper_curvelinear.py
> Rename locator.den to the clearer locator.nbins in mpl_toolkits.

- examples/images_contours_and_fields/matshow.py
- More instructive description.
- Simpler matrix creation code.
> Simplify matshow example

- tutorials/toolkits/axisartist.py
> Cleanup axisartist tutorial.

- lib/matplotlib/axes/_axes.py
Hopefully reduces confusion like https://github.com/matplotlib/matplotlib/issues/7221#issuecomment-546299575.
> Clarify imshow() docs concerning scaling and grayscale images

- doc/users/event_handling.rst
We don't need to be strict with the line length in rst files, but it's
still nice to stay within reasonable bounds.
> Avoid really long lines in event handling docs.

- tutorials/toolkits/axisartist.py
mpl -> Matplotlib (and fix capitalization); Line2d -> Line2D.
> axisartist tutorial fixes.

- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_macosx.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_pgf.py
- lib/matplotlib/backends/backend_qt5.py
- lib/matplotlib/backends/backend_qt5agg.py
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/backends/backend_wxagg.py
Remove unnecessary rst roles.  Use """ for triple quotes.  Inherit some
docstrings.
> Small cleanups to backend docs.

- lib/matplotlib/image.py
I have taken a pretty awful docstring and made it slightly less awful by putting it in numpydoc format... not perfect but slightly better.
> numpydoc AxesImage

- tutorials/introductory/usage.py
> Add pgf to list of builtin backends in docs.

- lib/matplotlib/image.py
Follow up to #15523.
- add description for `ax` parameter
- add default values
- some ReST formatting fixes
> Improve docsting of AxesImage

- doc/users/next_whats_new/2019-10-27-savefig-backend.rst
- lib/matplotlib/backend_bases.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/figure.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_figure.py
- tutorials/introductory/usage.py
This makes it easier e.g. to test the pgf backend without globally
switching the backend.
Makes it easier to work on pgf related issues; also helps with #13994 (attn @ArchangeGabriel; see changelog).
> Add a backend kwarg to savefig.
