lib/matplotlib/pyplot.py
lib/matplotlib/tests/test_backend_webagg.py

Backport PR #15512 on branch v3.1.x

---

lib/matplotlib/pyplot.py
lib/matplotlib/tests/test_backend_webagg.py

xref: #15512, #15582  
attn: @tacaswell

Backport PR #15512 on branch v3.2.x

---

INSTALL.rst
setup.cfg.template
setupext.py

Followup to #15476, suggested in https://github.com/matplotlib/matplotlib/pull/11984#issuecomment-417572465 (attn @QuLogic).

Allow linking against a system qhull as well.

---

lib/matplotlib/backends/backend_qt5.py

... rather than specialcasing it in _init_toolbar.

Declare qt figureoptions tool in toolitems.

---

examples/animation/dynamic_image.py
examples/animation/simple_anim.py

The change here allows one to change animation writer by editing a
single place rather than two (both the import and the actual use).

Make it easier to test various animation writers in examples.

---

lib/mpl_toolkits/axes_grid1/axes_grid.py

The visibility-handling is handled by toggle(); the other changes are
handled by the lines just below.

Remove some commented-out code from axes_grid.

---

lib/mpl_toolkits/axes_grid1/axes_grid.py

Store axes in a 2D, None-initialized numpy array (`axes_array`) rather
than nested lists (converting everything to nested lists with tolist()
at the end for backcompat); this allows one to get rid of self._refax/
self._column_refax/self._row_refax and instead just use
`axes_array[0, 0]`/`axes_array[0, col]`/`axes_array[row, 0]` as axes for
sharing (these default correctly to None on the first iteration).
Minor cleanups: use check_in_list; factor out common kwargs when
constructing self._divider; directly construct self.cbar_axes as a list
comprehension.
Note that the Grid and AxesGrid constructors are almost duplicate of one
another and could be deduplicated later.

Simplify axes_grid.Grid/axes_grid.ImageGrid construction.

---

INSTALL.rst
doc/faq/installing_faq.rst
doc/faq/troubleshooting_faq.rst

The link www.enthought.com/products/canopy is broken, googling doesn't
show anything recent, and the apparently official docs at
http://docs.enthought.com/canopy/ say that canopy only supports Py2.7
and 3.5, neither of which we support anymore.
Reword docs accordingly, and at the same time subsume mentions of
Continuum into Anaconda
(https://www.anaconda.com/continuum-analytics-officially-becomes-anaconda/).

Remove mention of Enthought Canopy from the docs.

---

doc/devel/MEP/MEP19.rst
doc/devel/MEP/MEP29.rst
doc/users/prev_whats_new/changelog.rst
examples/style_sheets/plot_solarizedlight2.py

AFAICT the sf issue links have been lost forever -- I can't find an
archive of them *anywhere*.  So just turn them into plain text by
prepending a backslash.
Found through https://github.com/matplotlib/matplotlib/pull/15648.

Fix some broken links.

---

src/_tkagg.cpp

... as we don't rely on any Tcl_* functions anymore.

Don't mention tcl in tkagg commments anymore.

---

examples/axes_grid1/demo_axes_divider.py
examples/axes_grid1/demo_axes_grid.py
examples/axes_grid1/demo_axes_grid2.py
examples/axes_grid1/demo_axes_hbox_divider.py
examples/axes_grid1/demo_axes_rgb.py
examples/axes_grid1/demo_colorbar_of_inset_axes.py
examples/axes_grid1/demo_edge_colorbar.py
examples/axes_grid1/inset_locator_demo2.py
examples/axes_grid1/simple_axesgrid2.py
examples/axes_grid1/simple_rgb.py
examples/axisartist/demo_curvelinear_grid2.py
examples/color/custom_cmap.py
examples/images_contours_and_fields/image_zcoord.py
examples/images_contours_and_fields/plot_streamplot.py
examples/pyplots/whats_new_99_axes_grid.py
examples/subplots_axes_and_figures/zoom_inset_axes.py
examples/ticks_and_spines/colorbar_tick_labelling_demo.py
examples/ticks_and_spines/spines_dropped.py
examples/user_interfaces/embedding_in_wx3_sgskip.py

It is now the default interpolation method (well, actually the default
is "antialiased" but for the cases here they're the same).
The explicit kwarg was left for examples actually illustrating the
interpolation kwarg.

Remove interpolation="nearest" from most examples.

---

INSTALL.rst
doc/api/next_api_changes/development.rst
lib/matplotlib/__init__.py
lib/matplotlib/axes/_axes.py
requirements/testing/travis36minver.txt
setup.py

Bump numpy dependency to >=1.15.

---

lib/matplotlib/tests/test_mlab.py

Parametrize some spectral tests.

---

doc/api/prev_api_changes/api_changes_3.0.0.rst
doc/devel/MEP/MEP11.rst
doc/devel/MEP/MEP12.rst
doc/devel/MEP/MEP23.rst
doc/devel/MEP/MEP26.rst
doc/devel/documenting_mpl.rst
doc/missing-references.json
doc/users/dflt_style_changes.rst
doc/users/prev_whats_new/whats_new_1.3.rst
doc/users/prev_whats_new/whats_new_1.5.rst
doc/users/prev_whats_new/whats_new_2.0.0.rst
doc/users/prev_whats_new/whats_new_3.0.rst
doc/users/shell.rst
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/colors.py
lib/matplotlib/dviread.py
lib/matplotlib/mlab.py
lib/matplotlib/sphinxext/plot_directive.py
lib/matplotlib/ticker.py

Fix some broken doc refs.

---

lib/matplotlib/_animation_data.py

Add tooltips to HTML animation controls

---

doc/api/prev_api_changes/api_changes_3.1.0.rst
doc/api/prev_api_changes/api_changes_3.1.1.rst
doc/api/prev_api_changes/api_changes_3.2.0/behavior.rst
doc/devel/MEP/MEP11.rst
doc/devel/contributing.rst
doc/missing-references.json
doc/users/prev_whats_new/changelog.rst
doc/users/prev_whats_new/whats_new_1.2.rst
doc/users/prev_whats_new/whats_new_1.3.rst
doc/users/prev_whats_new/whats_new_1.4.rst
doc/users/prev_whats_new/whats_new_1.5.rst
doc/users/prev_whats_new/whats_new_2.0.0.rst
doc/users/prev_whats_new/whats_new_2.2.rst
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/font_manager.py
lib/matplotlib/lines.py
lib/matplotlib/mathtext.py
lib/matplotlib/mlab.py
lib/matplotlib/transforms.py
lib/matplotlib/tri/tricontour.py

Fix more broken refs.

---

.travis.yml
lib/matplotlib/tests/test_backends_interactive.py

Also test PySide2 on CI.

---

lib/matplotlib/dates.py

Cleanup dates.py docstrings.

---

doc/sphinxext/custom_roles.py

Render default values in :rc: directive as literal

---

doc/_templates/donate_sidebar.html

It's now the same link as the one recently added for Github sponsor.

Update donation link

---

doc/_templates/search.html
doc/faq/howto_faq.rst

Remove FAQ on 'Search' -- already referenced in search file

---

lib/mpl_toolkits/mplot3d/axes3d.py

Document scope of 3D scatter depthshading.

---

doc/faq/howto_faq.rst

Update the links to not point to outdated examples.
(matplotlib.org/examples is the old examples, the new ones are under
/gallery).
Wrap the lines.

Update boxplot/violinplot faq.

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/mlab.py
lib/matplotlib/quiver.py
lib/matplotlib/sphinxext/plot_directive.py
lib/matplotlib/transforms.py

For many parameters, reword their description from "Control the foo" or
"Specifies the foo" to "The foo", which is just as clear.

Reword some docstrings.

---

examples/misc/image_thumbnail_sgskip.py
examples/tests/backend_driver_sgskip.py
examples/user_interfaces/mpl_with_glade3_sgskip.py
lib/matplotlib/afm.py
lib/matplotlib/dviread.py
lib/matplotlib/image.py
lib/matplotlib/sphinxext/mathmpl.py
lib/matplotlib/tests/test_font_manager.py
lib/matplotlib/tests/test_png.py
lib/mpl_toolkits/tests/__init__.py

... mostly in places where that actually shortens the code.

Some pathlibification.

---

tutorials/intermediate/legend_guide.py

Fix typos and comma splices in legend guide

---

lib/matplotlib/cbook/__init__.py

Slightly clarify the implementation of safe_masked_invalid.

---

doc/_templates/search.html

The description on the search page was quite wordy. This PR reduces clutter and reproduces my accepted PR at https://github.com/sphinx-doc/sphinx/pull/6814/.

Shorten description on search page

---

lib/matplotlib/colors.py

- Remove ref. to class doctsring: parameters are new documented in
method docstring.
- Don't fill the "bad" values in the array to avoid a warning; correctly
set the warnings filter instead (hopefully should be faster, for large
inputs).
- Don't compute `np.isnan(X)` twice -- once is enough.  Don't bother
"optimizing" by checking whether `np.any(np.isnan(X))` -- that'll need
iterating over the whole array as well.
- Remove reference to very old (and now fixed) putmask endianness bug. (https://github.com/numpy/numpy/issues/1173)
- Indexing is just as fast as ndarray.take nowadays, and clearer. (https://github.com/numpy/numpy/issues/9450#issuecomment-468263525 -- np.take use was added for performance in https://github.com/matplotlib/matplotlib/commit/31deac2)

Cleanup `Colormap.__call__`.

---

tutorials/intermediate/imshow_extent.py
tutorials/introductory/images.py

Just fixes a couple typos I came across while reading tutorials.
- [NA] Has Pytest style unit tests
- [NA] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [NA] New features are documented, with examples if plot related
- [NA] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [NA] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

fix a couple typos in tutorials

---

doc/faq/howto_faq.rst
doc/users/dflt_style_changes.rst
lib/matplotlib/backend_bases.py
lib/matplotlib/ticker.py
tutorials/text/mathtext.py
tutorials/text/usetex.py

Cleanup some references to rcParams in docs.

---

lib/matplotlib/dviread.py

Cleanup dviread docs.

---

lib/matplotlib/artist.py
lib/matplotlib/cm.py
lib/matplotlib/collections.py
lib/matplotlib/patches.py

Numpy-docification of `PolyCollection` and some related methods.

Update docs of PolyCollection

---

lib/matplotlib/backend_bases.py

Cleanup backend_bases docstrings.

---

examples/misc/zorder_demo.py

- Add zorder of more artists
- Reference `axisbelow` property
- Code cleanup

Improve zorder demo

---

lib/matplotlib/figure.py

Improve docs on figure size

---

.travis.yml

Will selfmerge to unbreak the build.

Allow failure on nightly builds.

---

lib/matplotlib/collections.py

DOC: specify the expected shape in the Collection.set_offset

---

doc/faq/environment_variables_faq.rst

Cleanup environment variables FAQ.

---

.travis.yml
azure-pipelines.yml

... whereas ppa:jonathonf/ffmpeg-3 has gone offline.
will selfmerge yada yada

ffmpeg is available on default ubuntu packages now.

---

lib/matplotlib/pyplot.py

- Don't bother listing call signatures (the normal function signature is
fine).
- Slightly tighten the parameters/return value descriptions.

Cleanup xticks/yticks docstrings.

---

doc/devel/documenting_mpl.rst

As discussed in the dev call: Document how we want to document default values.

Document doc style for default values

---

doc/faq/environment_variables_faq.rst

Backport PR #15848 on branch v3.2.x: Cleanup environment variables FAQ

Backport PR #15848 on branch v3.2.x: Cleanup environment variables FAQ

---

lib/matplotlib/backends/backend_ps.py

Use True/False instead of 0/1 as booleans in backend_ps.

---

lib/matplotlib/backend_bases.py

Cleanup backend_bases docs

---

doc/_static/mpl.css
doc/_templates/layout.html
doc/conf.py

Closes #15717. See there for the motivation.
I'm not a HTML/CSS expert, so not sure the code is the best one can do, but it renders as I would like it to :smile: .
[Built docs](https://27361-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/index.html)
Before:
After:

Doc: Move search field into nav bar

---

doc/sphinxext/custom_roles.py

Backport PR #15244 on branch v3.1.x: Change documentation format of rcParams defaults

Backport PR #15244 on branch v3.1.x: Change documentation format of rcParams defaults

---

lib/matplotlib/backend_bases.py

Cleanup backend_bases docs.

---

lib/matplotlib/text.py

Cleanup text.py docstrings.

---

examples/widgets/rectangle_selector.py
lib/matplotlib/axis.py
lib/matplotlib/backend_tools.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/colors.py
lib/matplotlib/offsetbox.py
lib/matplotlib/tests/test_transforms.py
lib/matplotlib/text.py
lib/matplotlib/tri/triinterpolate.py

Mark self.* expressions in docstrings as literal

---

lib/matplotlib/tests/test_backend_webagg.py

Skip webagg test if tornado is not available.

---

lib/matplotlib/widgets.py

Per https://github.com/matplotlib/matplotlib/issues/15852#issuecomment-562853567.
Closes #15852 (I think?).

LassoSelection shouldn't useblit on canvas not supporting blitting.

---

lib/matplotlib/legend.py

Cleanup legend docstrings.

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/backend_bases.py
lib/matplotlib/colorbar.py
lib/matplotlib/contour.py
lib/matplotlib/dates.py
lib/matplotlib/figure.py
lib/matplotlib/pyplot.py
lib/matplotlib/stackplot.py
lib/mpl_toolkits/axes_grid1/inset_locator.py
lib/mpl_toolkits/mplot3d/axes3d.py

More docstrings cleanup.

---

lib/matplotlib/collections.py

See comments.
Closes #15806 (@QuLogic can you confirm?).  Sorry, no tests, but I think the patch makes sense...

Correctly handle non-affine transData in Collection.get_datalim.

---

lib/matplotlib/widgets.py

The usual docstring churn.
Edit: looks like links in the "Methods" section need revisiting.

Update some widget docstrings.

---

lib/matplotlib/backend_managers.py

Update docs of backend_manager

---

lib/matplotlib/tri/tritools.py

Cleanup TriAnalyzer docs

---

lib/matplotlib/axes/_axes.py

- Synchronize `axhspan` / `axvspan` docstrings.
- Fix two links.

Minor doc cleanups

---

lib/matplotlib/type1font.py

This pulls out documentation updates of #15896 (will decide separately if I want to follow up on #15896).

Update docs of type1font

---

lib/matplotlib/tests/test_colors.py

Should add some more coverage; maybe could do with exercising a few more cases.

Test registering cmaps

---

lib/matplotlib/tests/test_ticker.py

Should bump test coverage a little bit.

Add tests for IndexFormatter

---

examples/specialty_plots/radar_chart.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/axis.py
lib/matplotlib/cm.py
lib/matplotlib/dviread.py
lib/matplotlib/font_manager.py
lib/matplotlib/gridspec.py
lib/matplotlib/image.py
lib/matplotlib/patches.py
lib/matplotlib/sphinxext/plot_directive.py
lib/matplotlib/tests/test_ticker.py
lib/mpl_toolkits/axisartist/grid_finder.py

... unless capitalization has a special meaning for the staring word (in particular parameter names stay lowercase).

Exceptions should start with a capital letter

---

doc/_static/mpl.css
doc/_templates/layout.html

Add banner for CZI funded job posting.
Trying to get the docs to rebuild.

Jobs banner

---

doc/users/event_handling.rst
matplotlibrc.template

... which is extremely outdated.  We could consider importing
interesting parts of the scipy cookbook into our gallery later.

Remove references to scipy cookbook.

---

examples/images_contours_and_fields/affine_image.py
examples/images_contours_and_fields/demo_bboximage.py
examples/images_contours_and_fields/image_annotated_heatmap.py
examples/lines_bars_and_markers/scatter_with_legend.py
examples/misc/keyword_plotting.py
examples/pie_and_polar_charts/pie_and_donut_labels.py
examples/recipes/placing_text_boxes.py
examples/shapes_and_collections/line_collection.py
examples/shapes_and_collections/patch_collection.py
examples/text_labels_and_annotations/date.py
examples/ticks_and_spines/multiple_yaxis_with_spines.py
examples/widgets/lasso_selector_demo_sgskip.py
examples/widgets/polygon_selector_demo.py

Remove extraneous :class:.
Additionally reword the docs for affine_image.py (all backends support
affine transforms on images) and date.py (wrt. date2num and num2date).

Fix some examples docstrings.

---

INSTALL.rst
doc/devel/contributing.rst

Tell users to always use a venv and always install in editable mode.
If they know better, great.  But let's not offer too many confusing
options to newcomers.
xref https://discourse.matplotlib.org/t/running-tests-on-git-master/20761/

Be more opinionated for setting up a dev env.

---

examples/axes_grid1/demo_axes_hbox_divider.py
lib/mpl_toolkits/axes_grid1/axes_divider.py
lib/mpl_toolkits/tests/test_axes_grid1.py

Avoid using np.matrix.

---

lib/matplotlib/mlab.py

I think the repetition is large enough to be worth it.  This does make
these functions all refer to themselves as well in the See Also section,
but that seems benign enough.

Templatize spectral helpers.

---

src/_backend_agg.h
src/_backend_agg_wrapper.cpp
src/_contour_wrapper.cpp
src/_image_wrapper.cpp
src/_path_wrapper.cpp
src/ft2font_wrapper.cpp
src/py_converters.h
src/tri/_tri.cpp
src/tri/_tri_wrapper.cpp

Some small improvements to the extension code; see commit messages for details.

Some small extension cleanups

---

lib/matplotlib/backends/backend_wx.py

Just compress down the code a bit.

Shorten wx _onMouseWheel.

---

lib/matplotlib/pyplot.py

This is just duplicating the doc in Axes.add_subplot().

Document support for no-args plt.subplot() call.

---

lib/matplotlib/artist.py
lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/matplotlib/figure.py
lib/matplotlib/legend.py
lib/matplotlib/lines.py
lib/matplotlib/offsetbox.py
lib/matplotlib/patches.py
lib/matplotlib/text.py
lib/mpl_toolkits/axisartist/axis_artist.py

Per https://github.com/matplotlib/matplotlib/pull/16004#discussion_r360711135.

Inherit the Artist.draw docstring in subclasses.

---

examples/images_contours_and_fields/contour_demo.py

Cleanup contour_demo.

---

doc/users/next_whats_new/2017-12-29-3dhome.rst
lib/mpl_toolkits/mplot3d/axes3d.py

No tests because good luck with that, but can be checked manually.
Closes #11178.

Fix home/forward/backward buttons for 3d plots.

---

lib/matplotlib/text.py

The usual standardization of docstrings.

Improve documentation of text module

---

examples/images_contours_and_fields/contourf_log.py
examples/images_contours_and_fields/pcolor_demo.py
examples/text_labels_and_annotations/mathtext_examples.py
examples/userdemo/colormap_normalizations.py
examples/userdemo/colormap_normalizations_power.py
lib/matplotlib/_layoutbox.py
lib/matplotlib/animation.py
lib/matplotlib/artist.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/backend_bases.py
lib/matplotlib/backend_tools.py
lib/matplotlib/backends/backend_svg.py
lib/matplotlib/contour.py
lib/matplotlib/dates.py
lib/matplotlib/hatch.py
lib/matplotlib/image.py
lib/matplotlib/legend.py
lib/matplotlib/mathtext.py
lib/matplotlib/tests/test_figure.py
lib/matplotlib/tests/test_triangulation.py
lib/matplotlib/ticker.py
lib/matplotlib/tri/triinterpolate.py
lib/mpl_toolkits/axisartist/axis_artist.py
lib/mpl_toolkits/mplot3d/axis3d.py
tutorials/colors/colormapnorms.py

- Remove redundant parentheses
- Property setters should not return anything
- use `if myvar:` instead of `if myvar != []:`

Code style cleanup

---

examples/images_contours_and_fields/image_zcoord.py
lib/matplotlib/backends/backend_agg.py
lib/matplotlib/streamplot.py

Simplify some comparisons

---

lib/matplotlib/category.py

For the better or (mostly) the worst, we support both bytes and str.
AnyStr is the union of both of them (per stdlib typing).

Cleanup category.py docstrings.

---

examples/event_handling/path_editor.py

- AFAICT one cannot actually delete vertices interactively.
- pathpatch_changed was never ever used.

Cleanup path_editor example.

---

lib/matplotlib/backend_bases.py

Cleanup docstrings in backend_bases.py

---

doc/api/prev_api_changes/api_changes_0.54.rst
doc/devel/color_changes.rst
doc/devel/contributing.rst

Fix some typos

---

lib/matplotlib/animation.py

Instead of connecting to the xlim_changed/ylim_changed events to clear
the blit cache, use Axes._get_view(), which also works for 3d axes.
Closes #16069.  No test because good luck with that, but one can repro with the example at that issue.

Make animation blit cache robust against 3d viewpoint changes.

---

lib/matplotlib/backend_bases.py

Backport PR #16080 on branch v3.2.x (Cleanup docstrings in backend_bases.py)

---

doc/users/prev_whats_new/whats_new_3.1.0.rst
lib/matplotlib/__init__.py
lib/matplotlib/backend_bases.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/cbook/deprecation.py
lib/matplotlib/colors.py
lib/matplotlib/contour.py
lib/matplotlib/font_manager.py
lib/matplotlib/patches.py
lib/matplotlib/pyplot.py
lib/mpl_toolkits/axes_grid1/axes_size.py
lib/mpl_toolkits/mplot3d/axes3d.py

Backport PR #16079 on branch v3.2.x (Fix restuctured text formatting)

---

lib/matplotlib/animation.py

This avoids a lookup error for third-party animation subclasses for
which there is no corresponding rcParam.
Supersedes #5404.

Delay resolution of animation extra_args.

---

examples/text_labels_and_annotations/arrow_demo.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/contour.py
lib/matplotlib/tight_layout.py
lib/matplotlib/tri/tricontour.py
lib/matplotlib/type1font.py
lib/mpl_toolkits/axes_grid1/colorbar.py

Cleanup:
- unused local variables
- unused parameters of internal functions

Cleanup unused variables

---

doc/api/offsetbox_api.rst
lib/matplotlib/animation.py
lib/matplotlib/artist.py
lib/matplotlib/legend.py
lib/matplotlib/offsetbox.py
lib/mpl_toolkits/axisartist/axisline_style.py

- numpydoc conforming
- extended various descriptions
- Fixed some doc errors in other modules, which I found along the way.

Improve docstrings in offsetbox.py

---

doc/conf.py

Produces sharper images for high-resolution screens.
This is supported since sphinx 1.0: https://www.sphinx-doc.org/en/master/usage/extensions/graphviz.html#confval-graphviz_output_format

Renderer Graphviz inheritance diagrams as svg

---

doc/_static/mpl.css
doc/_templates/layout.html

This reverts commit 83c0e65c128fa54f74e28e196a1475b1660bb9e9, reversing
changes made to 4da7b4b744f0f337bd4dd0deb72fbcf9b3f59c9b.

Revert "Merge pull request #15972 from tacaswell/jobs_banner"

---

doc/api/next_api_changes/deprecations.rst
examples/specialty_plots/skewt.py
lib/matplotlib/axis.py
lib/matplotlib/backend_bases.py
lib/matplotlib/offsetbox.py
lib/matplotlib/path.py
lib/matplotlib/projections/polar.py
lib/matplotlib/streamplot.py
lib/matplotlib/tests/test_skew.py

Unused parameters to public functions.

Deprecate unused parameters

---

.travis.yml

Backport PR #16112 on branch v3.1.x (CI: Fail when failed to install dependencies)

---

requirements/testing/travis36.txt

CI: Do not use nbformat 5.0.0/5.0.1 for testing

---

lib/matplotlib/lines.py

Validate Line2D pickradius when setting it, not when reading it.

---

lib/matplotlib/transforms.py

... and rewrap some docstrings to make them shorter.
(The comment should have been deleted in https://github.com/matplotlib/matplotlib/commit/52d462#diff-9d3a2ed9922d92407a1b5e9c4862d1d1L1662.)

Remove outdated comment re: blended transforms.

---

lib/matplotlib/axes/_axes.py

Cleanup hist() docstring.

---

examples/images_contours_and_fields/contourf_demo.py
examples/misc/transoffset.py
lib/matplotlib/__init__.py
lib/matplotlib/animation.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/backends/backend_mixed.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/figure.py
lib/matplotlib/tests/test_figure.py
lib/matplotlib/tight_bbox.py
lib/mpl_toolkits/axisartist/axislines.py
tutorials/intermediate/constrainedlayout_guide.py
tutorials/intermediate/tight_layout_guide.py
tutorials/introductory/customizing.py
tutorials/introductory/pyplot.py
tutorials/introductory/usage.py
tutorials/text/annotations.py
tutorials/text/text_props.py

It's a MATLABism; Python has functions and methods.  There are some
places where "command" does read fine, though.

(Mostly) avoid the term "command" in the docs.

---

doc/citing.rst

Add badge for citing 3.1.2

---

doc/api/next_api_changes/removals.rst
examples/misc/custom_projection.py
lib/matplotlib/__init__.py
lib/matplotlib/figure.py
lib/matplotlib/projections/geo.py
lib/matplotlib/projections/polar.py
lib/matplotlib/rcsetup.py
lib/matplotlib/texmanager.py
lib/matplotlib/ticker.py

Remove rcParams deprecated in mpl3.0/3.1.

---

lib/matplotlib/patches.py

(I think there are additional issues with the ConnectionPatch docstrings (some key docs appear to be wrong?) but that'll be for another time.)

Cleanup patches docstrings.

---

examples/animation/random_walk.py
examples/axisartist/demo_parasite_axes2.py
examples/axisartist/simple_axisartist1.py
examples/misc/patheffect_demo.py
examples/statistics/barchart_demo.py
examples/subplots_axes_and_figures/secondary_axis.py

Let's be a good example in terms of code style.

Do not use camel case for variables in examples

---

lib/matplotlib/contour.py

Numpydoc ContourSet.find_nearest_contour.

---

examples/event_handling/pipong.py
examples/statistics/boxplot_demo.py
examples/statistics/customized_violin.py
examples/units/basic_units.py

The changes in basic_units are possible because the unit framework now
correctly handles unit subclasses, so we don't need to register
dynamically created subclasses (since https://github.com/matplotlib/matplotlib/pull/13536).
Followup to https://github.com/matplotlib/matplotlib/pull/16199/files; I think the only remaining cases are callback names in wx examples.

UnCamelCase examples.

---

lib/matplotlib/axes/_subplots.py
lib/matplotlib/backends/backend_pgf.py

From https://github.com/matplotlib/matplotlib/pull/13544#issuecomment-573870718

Fix deprecation from #13544

---

doc/api/prev_api_changes/api_changes_3.2.0/behavior.rst
doc/missing-references.json
doc/users/dflt_style_changes.rst
doc/users/prev_whats_new/whats_new_1.4.rst
doc/users/prev_whats_new/whats_new_1.5.rst
doc/users/prev_whats_new/whats_new_2.1.0.rst
doc/users/prev_whats_new/whats_new_3.1.0.rst
lib/matplotlib/artist.py
lib/matplotlib/backends/backend_agg.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/figure.py
lib/matplotlib/image.py
lib/matplotlib/legend.py
lib/matplotlib/patches.py
lib/matplotlib/pyplot.py
lib/mpl_toolkits/mplot3d/axes3d.py

The `FormatStrFormatterNewStyle` name added in 04c734c was just wrong
(it refers to an old name that went away during the PR review).
The docstring of violin_stats was edited to remove awkward wording wrt.
required keys in dicts; these keys are properly listed in the docstring
of bxp() anyways.
The comment re: multiline prop_cycles is just plain wrong --
matplotlibrc files never supported any kind of line continuation.

And more missing references.

---

lib/matplotlib/animation.py

Cleanup animation docs.

---

examples/scales/custom_scale.py

- Various docstring cleanups.
- The axisbelow hack is not necessary anymore (https://github.com/matplotlib/matplotlib/issues/6312#issuecomment-575137906).
- Use a normal FuncFormatter instead of a custom Formatter subclass.
(We can reuse the same formatter for major and minor ticks.)
- No need to make political statements about the Mercator projection.

Cleanup custom_scale example.

---

lib/matplotlib/rcsetup.py

Found this while testing the current master. looks like an inadvertent typo.

DOC: pdf.preamble --> pgf.preamble

---

doc/_templates/donate_sidebar.html

Backport donation links to 2.2.x

---

.travis.yml

Backport PR #16112 on branch v2.2.x (CI: Fail when failed to install dependencies)

---

lib/matplotlib/colors.py

I have made no attempt to update the text, but this should still be a small improvement.

numpydoc-ify SymLogNorm

---

doc/conf.py

Will selfmerge if passes.  May want to revert once https://github.com/scipy/scipy/issues/11401 is fixed.

Fix doc CI by pointing to dev version of scipy docs.

---

lib/matplotlib/colors.py

I'm trying to debug `SymLogNorm`, so thought I'd start by tidying up the `Normalize` docs to make them clearer. Suggestions very welcome.

Clean up and clarify Normalize docs

---

doc/conf.py

This reverts commit 1c8f9b5c889914a56ff36dbe8e9fa371e97e6072.
... because https://github.com/scipy/scipy/issues/11401 was fixed.

Revert "Fix doc CI by pointing to dev version of scipy docs."

---

tutorials/toolkits/axisartist.py

axisartist tutorial markup fixes.

---

lib/matplotlib/category.py
src/ft2font_wrapper.cpp
src/py_converters.cpp

(Not when referring to non-ASCII characters.)

Replace "unicode" by "str" in docs, messages when referring to the type.

---

lib/matplotlib/backends/backend_agg.py

Cleanup backend_agg docstrings.

---

examples/subplots_axes_and_figures/axes_demo.py

Cleanup axes_demo.

---

doc/api/cbook_api.rst
doc/api/colors_api.rst
doc/api/prev_api_changes/api_changes_3.0.0.rst
doc/devel/contributing.rst
doc/missing-references.json
lib/matplotlib/axes/_base.py
lib/matplotlib/cbook/deprecation.py
lib/matplotlib/colors.py
lib/matplotlib/dates.py

Fix some more missing references.

---

lib/matplotlib/cbook/deprecation.py

The previous version was just wrong.

Fix doc regarding deprecation of properties.

---

doc/faq/installing_faq.rst
doc/faq/troubleshooting_faq.rst

Remove mention of now-removed --verbose-foo flags.

---

doc/_static/mpl.css
doc/_templates/sidebar_versions.html
doc/conf.py
doc/index.rst

This is the first step of #16253.
It currently looks like this:
The contents will be adapted during the following steps.

Move version info to sidebar

---

lib/matplotlib/legend.py

Fix the docstring, which was wrong.
Use shorter list comprehensions to construct `vertices` and `bboxes`.
Clarify the failure mode of `np.concatenate`.  Remove an unnecessary
check when constructing `offsets`.

Cleanup Legend._auto_legend_data.

---

lib/matplotlib/backends/backend_qt5.py

Follow up to #16311, making the intention explicit.

Clearer signal handling

---

doc/_static/mpl.css
doc/index.rst

Backport PR #16226 on branch v3.2.x: Reorganize intro section on main page

Backport PR #16226 on branch v3.2.x: Reorganize intro section on main page

---

doc/_static/mpl.css
doc/_templates/sidebar_versions.html
doc/conf.py
doc/index.rst

Backport PR #16255 on branch v2.2.x (Move version info to sidebar).
Need to check that styling is correct via the CI built version of the docs.
I couldn't easily build 2.2.x docs locally probably because my dev env is not compatible to 2.2 anymore.

Backport PR #16255 on branch v2.2.x (Move version info to sidebar)

---

lib/matplotlib/font_manager.py

- Dedent overindented bullet list.
- Remove unnecessary :class:, :func:.

font_manager docs cleanup.

---

.flake8
examples/axes_grid1/scatter_hist_locatable_axes.py
examples/pyplots/text_commands.py
examples/pyplots/whats_new_98_4_fill_between.py
examples/pyplots/whats_new_98_4_legend.py

Style-fix some examples and update .flake8 per-file-ignores.

---

azure-pipelines.yml

Pattern matching on the existing matrix entries.

CI: add py38 to azure matrix

---

examples/pyplots/axline.py

Include axline() in infinite lines example

---

examples/animation/animate_decay.py
examples/animation/bayes_update.py
examples/animation/double_pendulum_sgskip.py
examples/animation/simple_anim.py

- For many examples init_func doesn't do much, the default initial
state is just fine.
- animate_decay is fairly naturally an infinite animation, so don't
limit it artificially to 1000 frames; also there is no need to
disable blitting as that's already the default... and in fact
blit=True would work just as well, but let's not bother.

Cleanup animation examples.

---

doc/api/colors_api.rst

The previous wording was a bit awkward (both "examples" and "tutorials"
demonstrate controlling colors... and do more than showing the
colormaps).

Reword intro to colors api docs.

---

examples/animation/animated_histogram.py
examples/images_contours_and_fields/image_annotated_heatmap.py
examples/lines_bars_and_markers/eventplot_demo.py
examples/lines_bars_and_markers/scatter_star_poly.py
examples/lines_bars_and_markers/timeline.py
examples/misc/histogram_path.py
examples/pie_and_polar_charts/nested_pie.py
examples/scales/logit_demo.py
examples/shapes_and_collections/artist_reference.py
examples/shapes_and_collections/compound_path.py
examples/shapes_and_collections/patch_collection.py
examples/specialty_plots/leftventricle_bulleye.py
examples/statistics/boxplot_demo.py
examples/statistics/confidence_ellipse.py
examples/statistics/errorbar_limits.py
examples/subplots_axes_and_figures/axes_box_aspect.py
examples/text_labels_and_annotations/custom_legends.py
examples/text_labels_and_annotations/text_rotation_relative_to_line.py
examples/ticks_and_spines/date_concise_formatter.py
examples/units/ellipse_with_units.py

There's many places where explicit conversion to np.array is not necessary
-- because matplotlib or numpy already handles the conversion, or
because the variable is already an array.  Removing these calls makes
the examples concentrate more on the plotting-relevant parts.

Remove unnecessary calls to np.array in examples.

---

lib/matplotlib/scale.py

(No method was actually being inherited.)
I guess this would be nice to have in 3.2 but there's actually no directly visible consequence, so either way is fine.
Closes https://github.com/matplotlib/matplotlib/issues/16451.

Don't make InvertedLogTransform inherit from deprecated base class.

---

lib/matplotlib/tests/test_arrow_patches.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_backend_pdf.py
lib/matplotlib/tests/test_backend_qt.py
lib/matplotlib/tests/test_collections.py
lib/matplotlib/tests/test_contour.py
lib/matplotlib/tests/test_dates.py
lib/matplotlib/tests/test_figure.py
lib/matplotlib/tests/test_image.py
lib/matplotlib/tests/test_legend.py
lib/matplotlib/tests/test_mathtext.py
lib/matplotlib/tests/test_pickle.py
lib/matplotlib/tests/test_text.py
lib/matplotlib/tests/test_ticker.py
lib/matplotlib/tests/test_tightlayout.py
lib/matplotlib/tests/test_triangulation.py

... moving them if needed to the toplevel import block.

Remove a bunch of imports-within-tests.

---

INSTALL.rst
tutorials/introductory/usage.py

- Add PySide2 as an option for Qt5Agg.
- Move links in unrendered docs out of the main text, which makes it
more readable.
- Switch some links to readthedocs, which should be more useful than
PyPI links.
- Remove mention of need of cairo for gtk in usage.py, given that the
exact same info (including the need of cairo for gtk3agg) is stated in
the backend table just above.

Update backend dependency docs.

---

lib/matplotlib/colors.py

Update some docstrings in colors.py

Update some docstrings in colors.py

---

setupext.py

Instead of using `devenv` (which may be not installed (it is IDE part) or
the latest compiler were installed without IDE) modify the project file
and change `PlatformToolset` to pick the default version.
Fixes #16243

BLD: Auto-detect PlatformToolset

---

matplotlibrc.template
setup.py

Having to specify formatting style conventions for matplotlibrc.template
is a bit overkill.  Just use normal PEP8 style: no spaces before colons,
two spaces before inline comments, introduce comments with a single #.
Also remove the note re: "editor with python syntax highlighting", given
that the whole template appears as a long comment in Python so syntax
highlighting buys nothing.

Simplify formatting of matplotlibrc.template.

---

examples/axisartist/demo_curvelinear_grid2.py

ExtremeFinderCycle is only necessary for "polar" plots where one of the
coordinates is "angular" and "cycles".  For the example here, the
simpler ExtremeFinderSimple is, well, enough :)

Simplify demo_curvelinear_grid2.

---

doc/api/next_api_changes/removals.rst
lib/matplotlib/dates.py
lib/matplotlib/font_manager.py
lib/matplotlib/mlab.py
lib/matplotlib/path.py
lib/matplotlib/projections/__init__.py
lib/matplotlib/pylab.py
lib/matplotlib/sphinxext/mathmpl.py
lib/matplotlib/tests/test_mlab.py

This pulls out parts of #15890 to make that PR more managable and easier to debug the test failures.

Remove more API deprecated in 3.1

---

lib/matplotlib/axis.py
lib/mpl_toolkits/axisartist/axis_artist.py

(It's the same as before, just shorter...)
Split out of #16228.

Avoid using FontProperties when not needed.

---

doc/index.rst

Fix some typos on the front page

---

doc/index.rst
examples/misc/custom_projection.py
examples/subplots_axes_and_figures/geo_demo.py
lib/matplotlib/projections/geo.py

(basemap is documented as being deprecated.)

Deemphasize basemap in user-facing docs.

---

lib/matplotlib/axes/_axes.py

Fixes #16478 - @torokati44, do you think this is clearer?

Re-phrase doc for bottom kwarg to hist

---

doc/index.rst

#16487
Add link to blog to front page and make list!

Add link to blog to front page

---

doc/users/dflt_style_changes.rst
doc/users/next_whats_new/2019-10-18_rcParams-for-raise-window-behavior.rst
examples/color/color_demo.py
examples/pyplots/fig_axes_customize_simple.py
tutorials/advanced/transforms_tutorial.py
tutorials/colors/colors.py
tutorials/intermediate/color_cycle.py
tutorials/intermediate/tight_layout_guide.py
tutorials/introductory/usage.py
tutorials/text/annotations.py

Doc markup cleanups.

---

examples/animation/bayes_update.py
examples/scales/logit_demo.py
lib/matplotlib/tests/test_mathtext.py
lib/matplotlib/tests/test_mlab.py
lib/matplotlib/tests/test_ticker.py

Sorry, this is a bit of a hodge-podge of things, but I'm trying to catch up on merged PRs, and fixing minor issues as I see them. See individual commits for details (or if you want me to split out anything.)

Various delayed PR reviews

---

lib/matplotlib/projections/polar.py

Although there is discussion about the in-consistent degrees/radians situation, it's probably worth at least documenting what's there.

Document theta getters/setters

---

setupext.py

Just reducing downstream patching.

Add more FreeType tarball hashes.

---

lib/matplotlib/projections/polar.py
lib/matplotlib/tests/test_transforms.py
lib/matplotlib/transforms.py

Factor out common parts of `__str__` for Transform subclasses.

---

lib/matplotlib/axes/_axes.py

Fixes to boxplot() docstring & error messages.

---

lib/matplotlib/transforms.py

Update a comment re: minimum version of numpy working around bug.

---

src/ft2font_wrapper.cpp

Shorten PyFT2Font_get_charmap.

---

lib/matplotlib/artist.py
lib/matplotlib/axis.py
lib/matplotlib/backend_tools.py
lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_agg.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_macosx.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/backends/backend_svg.py
lib/matplotlib/backends/backend_webagg.py
lib/matplotlib/backends/backend_wx.py

Follow up to #16406 and https://github.com/matplotlib/matplotlib/issues/16181.

Don't import rcParams but rather use mpl.rcParams (part 2)

---

doc/api/prev_api_changes/api_changes_3.1.0.rst

Backport PR #16272 on branch v3.1.3-doc

---

doc/devel/coding_guide.rst

Help new contributors to keep the commit history clean. I don't really expect that new contributors will do this by themselves now, but it's a ressouce I can point them to (or copy that section into a PR as a tip).

Recommend to amend pull requests

---

.appveyor.yml
.travis.yml
azure-pipelines.yml
ci/codecov.yml

codecov has changed how they discover the yaml file (it apparently
used to search whole repo, now only looks at top level).
Try to explicitly tell it where to look and to add azure to the set of
things that uploads.

CI: update codecov

---

lib/matplotlib/projections/polar.py

Fixes #16462 - I think this is the best way to go, but suggestions welcome.

Update set_thetalim documentation

---

doc/api/next_api_changes/removals.rst
lib/matplotlib/docstring.py
lib/matplotlib/scale.py
lib/matplotlib/tests/test_scale.py
lib/matplotlib/ticker.py

This pulls out additional parts of #15890 to make that PR more managable and easier to debug the test failures.

Remove more API deprecated in 3.1.

---

lib/matplotlib/mathtext.py

Reformat/reword mathtext docstrings.

---

lib/matplotlib/pyplot.py

Clarify docs of num parameter of plt.figure()

---

lib/matplotlib/axes/_axes.py

DOC: clarify the expected shapes of eventplot input

---

INSTALL.rst
lib/matplotlib/mathtext.py

Update URL to pyparsing.

---

doc/devel/MEP/MEP22.rst
doc/missing-references.json
lib/matplotlib/__init__.py
lib/matplotlib/fontconfig_pattern.py
lib/matplotlib/quiver.py

Minor docstring/references update.

---

lib/matplotlib/testing/compare.py

- In get_cache_dir(), we can assume that get_cachedir always returns a
writable directory (we make the same assumption e.g. in texmanager,
for example), basically since 244e8d8.
- pathlibify convert().

Cleanup testing.compare.

---

lib/matplotlib/figure.py

Update docstrings in figure.py.

---

lib/matplotlib/rcsetup.py

Fix exception causes in rcsetup.py

---

lib/matplotlib/patches.py

Fix typo in docs

---

tutorials/text/annotations.py

Update annotation tutorial.

---

setup.py

We got a trove classifier (https://github.com/pypa/pypi-support/issues/232) , so updated setup.py to use it! We should probably update some of our other classifiers as there's a fairly long list https://pypi.org/classifiers/
xref:#16592

added Framework :: Matplotlib  to setup

---

doc/devel/release_guide.rst

- add note about `twine check`
- correct doc make command
- remove note about source forge

DOC: update doc release guide

---

examples/shapes_and_collections/fancybox_demo.py

Cleanup fancybox_demo.

---

lib/matplotlib/markers.py
lib/matplotlib/mathtext.py
lib/matplotlib/offsetbox.py
lib/matplotlib/patches.py
lib/matplotlib/projections/__init__.py
lib/matplotlib/pyplot.py
lib/matplotlib/sphinxext/plot_directive.py
lib/matplotlib/streamplot.py
lib/matplotlib/style/core.py
lib/matplotlib/table.py
lib/matplotlib/testing/compare.py
lib/matplotlib/testing/decorators.py
lib/matplotlib/text.py
lib/matplotlib/ticker.py
lib/matplotlib/tri/triinterpolate.py
lib/mpl_toolkits/axes_grid1/axes_rgb.py
tools/boilerplate.py
tools/gh_api.py
tools/memleak.py

Fix exception causes in 19 modules

---

setupext.py

Instead of repeatedly unwrapping and rewrapping the file contents in a
BytesIO that needs to be seek()ed, just pass around the bytes object
itself.

Simplify setupext.download_or_cache.

---

README.rst
setup.py

The README now contains some non-ASCII characters, so we should specify an encoding when reading it to produce the long description.
Also, fix the images when the description is put on PyPI; it doesn't have our whole repo, so a relative link doesn't work.

Fix some readme bits

---

lib/mpl_toolkits/axes_grid1/axes_size.py

Rewrite MaxWidth, MaxHeight to reuse the MaxExtent logic.
Docstrings cleanups.
Move some typechecks (`float(...)` -> check_isinstance) to the class
constructors (so that all calls benefit from it).

Cleanup axes_size.

---

README.rst
setup.py

trying to fix backport errors in #16671

Backport PR #16671: Fix some readme bits

---

lib/matplotlib/legend.py

Seems easier to follow that spreading the init of legendPatch across
`__init__` and intertwined with other things.

Group all init of Legend.legendPatch together.

---

lib/matplotlib/axes/_axes.py

Dedupe implementations of fill_between & fill_betweenx.

---

lib/matplotlib/patches.py

- Move the implementation of pprint_styles into the method itself,
rather than an external function (_pprint_styles) which is used
nowhere else and which the method forwards to.
- Register all interpolations in one place, interpolate all style
docstrings in one place, and move the definition of FancyBboxPatch
(which was just copy-pasted) after them so that it can still use
docstring.dedent_interpd.
The patch looks big but it's mostly just the implementation of
FancyBboxPatch which was moved down.

Simplify docstring interpolation for Box/Arrow/ConnectionStyles.

---

lib/matplotlib/axes/_axes.py

Generic cleanup to hist().

---

requirements/testing/travis_all.txt

Backport #16752 to v3.2.x

---

lib/matplotlib/image.py

- rcParams -> mpl.rcParams.
- Reword/fix some docstrings.

Cleanup image.py.

---

lib/matplotlib/axes/_base.py
lib/matplotlib/backend_bases.py

... rather than a plain int -- this makes the documentation easier, and
MouseButton inherits from int anyways.

Reword docstring of panning callbacks, and pass them a MouseButton.

---

.circleci/config.yml
.github/workflows/circleci.yml

Backport PR #16672 on branch v3.2.0-doc

---

lib/matplotlib/patheffects.py

could be used in #15458 as well.

Combine withEffect PathEffect definitions.

---

examples/axes_grid1/demo_colorbar_with_axes_divider.py

make_axes_locatable returns an AxesDivider, not an AxesLocator.

Reword colorbar-with-axes-divider example.

---

tutorials/toolkits/axes_grid.py

Hopefully this is a bit easier to follow...

Reword axes_divider tutorial.

---

doc/api/next_api_changes/deprecations.rst
lib/matplotlib/figure.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_figure.py

Validate positional parameters of add_subplot()

---

lib/matplotlib/backends/backend_svg.py

... between the non-mathtext and mathtext cases.
The only slightly tricky point is whether we still need to special-case
the `len(glyph_path[0]) == 0` case; we don't, because self._convert_path
uses _path.convert_to_string, which handles zero-length paths just fine.

Deduplicate code for text-to-path conversion in svg backend.

---

lib/matplotlib/axes/_base.py
lib/matplotlib/backends/qt_compat.py
lib/matplotlib/dates.py
lib/matplotlib/figure.py
lib/matplotlib/sankey.py
lib/matplotlib/tests/test_backend_qt.py

As proposed in #16181. Follow up to  #16406 and #16525.

Don't import rcParams but rather use mpl.rcParams (part 3)

---

.circleci/config.yml

The old one seems broken.
Will selfmerge on success to unbreak ci.

Update CircleCI URL for downloading humor-sans.ttf.

---

tutorials/introductory/images.py

Everything goes through Pillow now.
& minor capitalization fixes.

Update image tutorial wrt. removal of native png handler.

---

lib/matplotlib/collections.py

Update markup for collections docstrings.

---

lib/matplotlib/testing/decorators.py

When #16770  was merged, it interacted poorly with the last change to `check_figures_equal`, due to the new arguments. This _should_ work on tests both with and without any of those fixtures.
[TAC edited to fix xref]

Fix check_figures_equal for tests that use its fixtures.

---

lib/matplotlib/tri/triinterpolate.py

One more instance of check_in_list.

---

doc/api/next_api_changes/deprecations.rst
lib/matplotlib/mathtext.py

A single Glue class seems enough.

Deprecate some mathtext glue helper classes.

---

lib/matplotlib/ticker.py

Simple cleanups to formatters.

---

README.rst
azure-pipelines.yml
doc/api/matplotlib_configuration_api.rst
doc/api/prev_api_changes/api_changes_3.2.0/behavior.rst
doc/api/prev_api_changes/api_changes_3.2.0/deprecations.rst
doc/citing.rst
doc/devel/documenting_mpl.rst
doc/index.rst
doc/users/github_stats.rst
doc/users/prev_whats_new/github_stats_3.1.2.rst
doc/users/prev_whats_new/github_stats_3.2.0.rst
doc/users/prev_whats_new/whats_new_1.0.rst
lib/matplotlib/__init__.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/colors.py
lib/matplotlib/testing/decorators.py
lib/matplotlib/tests/test_mathtext.py
matplotlibrc.template
setup.py

~~Suddenly a random extra test has started failing for me, so let's see how CI feels about this one.~~ Just had some stray files lying around, I think.
Conflicts:
* .circleci/config.yml
* .github/workflows/circleci.yml
* README.rst
* azure-pipelines.yml
* doc/api/prev_api_changes/api_changes_3.2.0/behavior.rst
* doc/devel/documenting_mpl.rst
* doc/index.rst
* lib/matplotlib/__init__.py
* lib/matplotlib/axis.py
* lib/matplotlib/backends/backend_pgf.py
* lib/matplotlib/category.py
* lib/matplotlib/colors.py
* lib/matplotlib/figure.py
* lib/matplotlib/image.py
* lib/matplotlib/mathtext.py
* lib/matplotlib/rcsetup.py
* lib/matplotlib/tests/test_mathtext.py
* matplotlibrc.template
* requirements/testing/travis_all.txt
* tutorials/colors/colormapnorms.py
- [n/a] New features are documented, …

Merge v3.2.x into master

---

doc/_static/mpl.css
doc/_templates/layout.html

Adds banners for GSOC and JHEPC

DOC: GSOC and JHEP banners

---

examples/user_interfaces/embedding_in_gtk3_sgskip.py
examples/user_interfaces/mpl_with_glade3_sgskip.py

per https://developer.gnome.org/gtk3/stable/GtkScrolledWindow.html#gtk-scrolled-window-add-with-viewport (manually checked that this still works).

Don't use deprecated Gtk add_with_viewport.

---

lib/matplotlib/backends/qt_compat.py

Closes https://github.com/matplotlib/matplotlib/issues/16834, I think (I don't actually have a qt4 install to check :-)).

Don't forget to export isdeleted on Qt4.

---

lib/matplotlib/spines.py
lib/matplotlib/transforms.py

spines doc cleanup

---

examples/lines_bars_and_markers/errorbar_subsample.py

Cleanup errorbar subsampling example

---

lib/matplotlib/backends/backend_qt5.py

Import QtX11Extras from PySide2 instead of PyQt5 if we're otherwise
already using PySide2.

Fix checking of X11 builds with PySide2.

---

.circleci/config.yml
azure-pipelines.yml

Dropping some extra packages may speed it up a teeny bit, but we'll have to confirm it builds first.

Cleanup CI setup

---

setup.py
setupext.py

... in a single function.
Splitting them over multiple classes doesn't really buy much.
Also convert the LibAgg and Qhull classes to toplevel functions,
as they play a role similar to add_numpy_flags.
~~I plan to do the same to agg and tkagg once https://github.com/matplotlib/matplotlib/pull/13075 gets in.~~ done.

In the build, declare all (compulsory) extension modules together.

---

doc/devel/release_guide.rst
doc/devel/testing.rst

This is based on notes I took while making 3.2.1. It also assumes that #16867 will be merged.
- [n/a] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [n/a] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

Update release guide

---

lib/matplotlib/backend_bases.py

Fix trivial docstring typos.

---

lib/matplotlib/backend_bases.py

I think this was missed by https://github.com/matplotlib/matplotlib/pull/13403.

Finish removing mentions of idle_event.

---

lib/matplotlib/_pylab_helpers.py
lib/matplotlib/figure.py
lib/matplotlib/pyplot.py

... stuff that had a "dedupe this" comment :)

Dedupe boilerplate for "adoption" of figure into pyplot.

---

setupext.py

Now that there's no `class Path` in setupext anymore, we can just do
`from pathlib import Path`.
Small followup to https://github.com/matplotlib/matplotlib/pull/14442.

Shorter Path import in setupext.

---

lib/matplotlib/artist.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_cairo.py
lib/matplotlib/contour.py
lib/matplotlib/tests/test_axes.py
lib/mpl_toolkits/axisartist/floating_axes.py

Use more kwonly arguments, less manual kwargs-popping.

---

lib/matplotlib/backends/backend_agg.py

We can compose the figure facecolor against a white background before
rendering the image, rather than after.  This saves an image composition
step.

Improve handling of alpha when saving to jpeg.

---

lib/matplotlib/backends/backend_agg.py

Some crossed PRs removed this import when it was needed by a different PR.
- [n/a] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

Add back missing import.

---

doc/api/next_api_changes/deprecations.rst
lib/matplotlib/backends/backend_qt4.py
lib/matplotlib/backends/backend_qt4agg.py
lib/matplotlib/backends/backend_qt4cairo.py
lib/matplotlib/backends/qt_compat.py

Per https://github.com/matplotlib/matplotlib/issues/16836.

Deprecate support for Qt4.

---

examples/images_contours_and_fields/tricontour_smooth_delaunay.py
lib/matplotlib/artist.py
lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/collections.py
lib/matplotlib/figure.py
lib/matplotlib/font_manager.py
lib/matplotlib/mathtext.py
lib/matplotlib/patches.py
lib/matplotlib/path.py
lib/matplotlib/scale.py
lib/matplotlib/ticker.py
lib/matplotlib/transforms.py
lib/matplotlib/tri/triangulation.py
lib/matplotlib/tri/tricontour.py
lib/matplotlib/tri/trifinder.py
lib/matplotlib/tri/triinterpolate.py
lib/matplotlib/tri/tripcolor.py
lib/matplotlib/tri/triplot.py
lib/matplotlib/tri/trirefine.py
lib/matplotlib/tri/tritools.py
lib/mpl_toolkits/axes_grid1/axes_divider.py
lib/mpl_toolkits/axisartist/axis_artist.py
lib/mpl_toolkits/mplot3d/axes3d.py

Cleanup many docstrings.

---

examples/axes_grid1/demo_axes_hbox_divider.py

- Small rewording.
- Use the make_heights_equal function demo'ed in the example, rather
than copy-pasting it.
- For the central annotation, use a figure-level text() instead of an
invisible axes.

Cleanup demo_axes_hbox_divider.

---

examples/axisartist/demo_parasite_axes.py
examples/axisartist/demo_parasite_axes2.py
examples/axisartist/simple_axisline.py

- We can call new_fixed_axis directly on the axes instance, which will
forward the call to the grid_helper and also correctly set the *axes*
kwarg.
- In demo_parasite_axes and demo_parasite_axes2, group together the
limits and labels settings, and remove some duplicates.
- Reword the description of demo_parasite_axes2.

Cleanup new_fixed_axis examples.

---

doc/api/style_api.rst
lib/matplotlib/style/core.py

Update style docs

---

lib/matplotlib/tests/test_backends_interactive.py

Split out of https://github.com/matplotlib/matplotlib/pull/16921.
edit: proof that it worked: https://codecov.io/gh/matplotlib/matplotlib/compare/54b426397c0e7567edaee4f7f77036c2b8569573...a90006151abc353ad26a3ef36895bf0180cd8762/src/lib/matplotlib/backends/backend_macosx.py

Test the macosx backend on Travis.

---

examples/widgets/slider_demo.py

Added one line that plots the plot with the correct initial color. When I ran the original example and noticed the error I took the chance to do my first contribution to the project. Hopefully it is only the beginning!

FIX: Plot is now rendered with correct inital value

---

doc/_static/mpl.css
requirements/doc/doc-requirements.txt

Updated CSS to fix an issue with the tooltip being cutoff by the
edge of the content. This change is dependent on updates to sphinx
gallery. This will also require a sphinx gallery version bump after the new version is released (otherwise there will be block of extra white space on the page)
requires https://github.com/sphinx-gallery/sphinx-gallery/pull/543

fix tooltip display bug

---

.flake8
lib/matplotlib/__init__.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_secondary_axes.py
lib/matplotlib/axis.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/collections.py
lib/matplotlib/font_manager.py
lib/matplotlib/scale.py
lib/matplotlib/tests/test_agg.py
lib/matplotlib/transforms.py
lib/mpl_toolkits/axes_grid1/inset_locator.py
tutorials/colors/colormap-manipulation.py

And remove the corresponding exceptions.

Fix some small style issues

---

lib/matplotlib/dates.py

Inherit some docstrings.  Fix capitalization, line-wrapping.

Cleanup dates docstrings.

---

lib/matplotlib/backend_tools.py

... by making it forward to the "classic" toolbar implementation.
(I have the vague feeling we need to decide what we really want to do with toolmanager, at some point...)

Dedupe implementation of axes grid switching in toolmanager.

---

doc/_static/mpl.css
requirements/doc/doc-requirements.txt

Merge pull request #15387 from dorafc/fix_tooltip_display_bug
DOC: fix tooltip display bug
Conflict was in requirements file

Backport PR #15387: fix tooltip display bug

---

doc/devel/min_dep_policy.rst

Add link to 3.2 min-supported-requirements.

---

INSTALL.rst

Changed `;`->`.` to make them consistent across the document
Changed heading to `Installtion Guide`

Made INSTALL.rst consistent

---

lib/matplotlib/axes/_axes.py

Closes #16976.
And some minor cleanups.

Add section on artifacts to imshow docs

---

doc/devel/documenting_mpl.rst

Felt the sentence too long and confusing. Tried to make it more understandable.

Improve readability of documenting_mpl.rst

---

lib/matplotlib/contour.py

More could be done, but let's take things a bit at a time.

Cleanups to contour docs.

---

doc/conf.py
doc/missing-references.json

Merge pull request #17045 from anntzer/docrefs
Fix missing-references.json.
Conflicts:
doc/missing-references.json
- fixed by fully regenerating

Backport PR #17045: Fix missing-references.json.

---

doc/index.rst
doc/missing-references.json
lib/matplotlib/pyplot.py

More missing refs fixes.

---

lib/matplotlib/widgets.py

Avoid spurious deprecation warning in TextBox.

---

examples/images_contours_and_fields/pcolormesh_grids.py
examples/lines_bars_and_markers/fill_between_demo.py
examples/subplots_axes_and_figures/subplots_demo.py

Fix minor doc typos.

---

doc/missing-references.json
lib/matplotlib/units.py
lib/matplotlib/widgets.py
tutorials/introductory/customizing.py

More missing refs fixes, and associated doc rewordings.

---

doc/_templates/layout.html
doc/conf.py
doc/missing-references.json

Removed GSoC Banner

---

examples/images_contours_and_fields/multi_image.py

The example has some issues pointed out elsewhere (#17052), but we can make it
less a pain to investigate with small cleanups:
- Don't use a weird/nonstandard colormap.
- Don't scale the data to 1e-6 (which makes editing the values via the
Qt figure options slightly a pain).
(This doesn't fix the underlying issues, though.)

Cleanup multi_image example.

---

tutorials/introductory/lifecycle.py

Fixed a typo in Lifecycle of a Plot

---

examples/images_contours_and_fields/contour_demo.py
examples/misc/demo_agg_filter.py
examples/mplot3d/contour3d.py
examples/mplot3d/contour3d_2.py
examples/mplot3d/contourf3d.py

Use True instead of 1 for boolean parameters.

---

lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_backend_bases.py

_set_view_from_bbox is called to figure out the new axes limits when the
mouse is released in interactive zoom.
- In the common zoom-in case, simplify the code by using `set_x/ybound`
which maintains the previously existing axes inversion (if any),
rather than having a bunch of conditions to sort the arguments
correctly before passing them to `set_x/ylim`.
- In the (more rarely used?) zoom-out case (which is triggered by
right-clicking, and zooms the axes out so that the previous axes
limits fit in the drawn box), use the axis transform directly rather
than just special-casing log-scale; this is necessary to make zoom-out
work for other scales such as logit.
- Tiny cleanups to the `len(bbox) == 3` case, which is only used by
toolmanager to implement zoom-by-scroll, but isn't used by the …

Simplify and generalize _set_view_from_bbox.

---

doc/conf.py

Apply fix for escaped backslashes in docs from https://github.com/scikit-image/scikit-image/pull/4578
Also see:  
https://github.com/numpy/numpydoc/pull/256
Closes https://github.com/matplotlib/matplotlib/issues/17119

[DOC] strip_signature_backslash

---

lib/matplotlib/figure.py

BUGFIX: conditional for add_axes arg deprecation

---

doc/users/event_handling.rst

... and homogenize grammatical form of descriptions to "noun verb
(object)".

Clarify that draw_event occurs after the canvas draw.

---

lib/matplotlib/__init__.py
lib/matplotlib/backends/backend_agg.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/figure.py
lib/matplotlib/image.py

- Rewrite in numpydoc style.
- Also consistently use `path-like` instead of `PathLike` everywhere.

Update docs of rc_context()

---

examples/axisartist/demo_axisline_style.py
examples/recipes/centered_spines_with_arrows.py
examples/ticks_and_spines/spine_placement_demo.py

Replacement for #17170. (see discussion there)
Closes #17157

Doc: spines arrows example

---

setup.py

Backport PR #17076: Fix SyntaxErrors when running setup in old Python

Backport PR #17076: Fix SyntaxErrors when running setup in old Python

---

lib/matplotlib/backends/_backend_tk.py

... consistently with other backends.
The code for syncing button state is similar to the one for gtk3.

Switch tk pan/zoom to use togglable buttons.

---

tutorials/colors/colormapnorms.py

DOC: Remove extra word

---

lib/matplotlib/gridspec.py
lib/matplotlib/tests/test_gridspec.py

Backport PR #17131 on branch v3.2.x

Backport PR #17131 on branch v3.2.x

---

lib/matplotlib/text.py

- Use Bbox attributes more.
- Early-exit Annotation._update_position_xypixel if arrowprops is None
to dedent most of the function.  Save many repeated calls to
Text.get_window_extent(self, renderer) in that function.

Cleanup text.py.

---

doc/api/transformations.rst
lib/matplotlib/transforms.py

Document `Transform.__add__` and `.__sub__`.

---

lib/mpl_toolkits/axisartist/axis_artist.py

In a few places, axisartist temporarily sets the transform of an artist
to `new_transform = artist.get_transform() + additional_transform`
with an originally empty (identity) `additional_transform` and then
later adjusts the `additional_transform` by calling `rotate_deg`
or `translate` on it, which has the effect of also modifying
`new_transform` in place.  Instead, directly add the correct
`additional_transform` at the site of use.

Simplify some axisartist code.

---

lib/matplotlib/image.py

Inlining _draw_unsampled_image makes the parallel between unsampled and
resampled paths much more obvious.
Moving the check of whether the renderer supports option_scale_image()
out of _check_unsampled_image() lets let latter just concentrate on
properties of the image itself, rather than having to look at the
renderer too.

Inline unsampled-image path; remove renderer kwarg from _check_unsampled_image.

---

examples/text_labels_and_annotations/demo_text_rotation_mode.py

There's a t missing, it broke my copy-pasta :D

Text Rotation Example: Correct roation_mode typo

---

lib/matplotlib/font_manager.py

Currently, we warn if fc-list is slow, but not if iterating over the
fonts is slow, which is actually more likely.  Fix that.
This should help with #17140 (and close it?).
(#15933 may help too.)

Move slow FontManager warning to FontManager constructor.

---

doc/missing-references.json

Normally just do the merge and push, but we merged a number of other PRs to master in between starting this and the tests passing locally,  This seems simpler to manage than re-doing the merge against current master (the conflicts were not bad, but don't really want to make sure I got them all right again).

V32 mergeup

---

lib/matplotlib/cm.py

Fix incorrect deprecation.

---

lib/matplotlib/lines.py

Instead of changing the numpy errstate, replace `a / b <= 1` by `a <=
b` and use np.hypot() for `sqrt(x**2+y**2)` (which avoids overflows from
`x**2`).
Otherwise a call to segment_hits should "always" be protected by
manipulating the numpy errstate.

Don't divide by zero in Line2D.segment_hits.

---

lib/matplotlib/quiver.py
lib/matplotlib/text.py

Fix doc wording

---

lib/matplotlib/animation.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/cm.py
lib/matplotlib/image.py
lib/matplotlib/patches.py
lib/mpl_toolkits/axes_grid1/axes_grid.py

Use deprecate_privatize_attribute more.

---

lib/matplotlib/axes/_axes.py

Closes https://github.com/matplotlib/matplotlib/issues/15899.

Improve docs of bar() and barh()

---

lib/matplotlib/projections/polar.py
lib/matplotlib/pyplot.py

As proposed in
https://github.com/matplotlib/matplotlib/pull/16988#issuecomment-606873639

Make pyplot signatures of rgrids() and thetagrids() explicit

---

examples/subplots_axes_and_figures/secondary_axis.py

On [stackoverflow](https://stackoverflow.com/questions/61596813/offset-secondary-axis-in-matplotlib), someone found `secondary_xaxis` but didn't realize that the location could be a float.  This improves the last example to make that clear.

DOC: add offset axes to secondary_axes

---

lib/matplotlib/pyplot.py

Added tight_layout and kwargs argument description to plt.figure.

DOC added kwargs and tight_layout description in plt.figure

---

doc/api/api_changes_3.3/behaviour.rst
lib/matplotlib/axes/_axes.py

See details in changelog note.

For single datasets, don't wrap artist added by Axes.hist in silent_list

---

lib/matplotlib/gridspec.py

Cleanup docstring of subplots().

---

lib/matplotlib/testing/compare.py
src/_macosx.m

* Fix macosx segfault #17084
* Fix missing attribute in _SVGConverter. #17210

Backport #17084 and #17210 to v3.2.x

---

doc/_templates/autosummary.rst
lib/matplotlib/colors.py

Cleanup colors.py docstrings.

---

lib/matplotlib/backends/backend_qt5.py

... by reusing the logic of NavigationToolbar2QT.

Also use light color tool buttons in qt+toolmanager+dark theme.

---

doc/faq/troubleshooting_faq.rst

Small updates to troubleshooting guide.

---

lib/matplotlib/__init__.py
lib/matplotlib/testing/compare.py

See https://github.com/matplotlib/matplotlib/pull/16394.  May be nice for 3.3.

Fix running the test suite with inkscape>=1.

---

lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/tests/test_mplot3d.py

This is identical to #15594 but I've squashed the changes into a single commit and pushed out the unused images.
All three contributors are credited.

Fix marker overlap

---

examples/user_interfaces/embedding_in_wx2_sgskip.py
examples/user_interfaces/embedding_in_wx3_sgskip.py
examples/user_interfaces/embedding_in_wx4_sgskip.py
examples/user_interfaces/fourier_demo_wx_sgskip.py
examples/user_interfaces/mathtext_wx_sgskip.py
examples/user_interfaces/wxcursor_demo_sgskip.py

- Move toplevel code under `if __name__ == "__main__"` block.  (This
makes sense specifically for embedding examples as they have very
little toplevel code and are indeed otherwise "importable".)
- Replace App(0) by App() (the argument defaults to False).
- Replace Show(1) by Show() (the arguments defaults to True).

Cleanup wx examples.

---

lib/matplotlib/rcsetup.py

I'm slowly turning all validator functions to be private, so let's start
right away with this one (which is not in any released version yet).

Keep validate_date private.

---

src/_tkagg.cpp

It's unlikely to matter unless embedding Python in a dynamic library and
doing really weird stuff, but dlclose()ing everything seems like good
practice.

Don't forget to dlclose() main_program in tkagg init.

---

INSTALL.rst

- --prefer-binary should prevent "I can't compile" related bug reports
- --no-user should prevent all of the edges cases where `--user` fails

DOC: be more opinionated about flags passed to pip

---

doc/api/api_changes_3.3/deprecations.rst
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/backends/backend_wx.py

Followup to #17092, but for toolmanager.

Remove status bars in toolmanager mode as well.

---

lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/tests/test_backends_interactive.py

tk/wx: Fix saving after the window is closed

---

lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/tests/test_backends_interactive.py

Backport PR #17391 on branch v3.2.x

---

doc/devel/coding_guide.rst

Clarify how we use milestones in practice.

DOC: clarify that milestones are intentions not approvals

---

doc/api/api_changes_3.3/deprecations.rst
examples/user_interfaces/embedding_in_qt_sgskip.py
lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/backends/qt_compat.py

Use qVersion, not QT_VERSION_STR -- the latter doesn't exist in PySide2.

---

doc/api/api_changes_3.3/behaviour.rst
examples/axes_grid1/demo_axes_divider.py
examples/axes_grid1/demo_axes_grid.py
examples/axes_grid1/demo_axes_grid2.py
examples/axes_grid1/demo_axes_rgb.py
examples/axes_grid1/demo_colorbar_of_inset_axes.py
examples/axes_grid1/demo_edge_colorbar.py
examples/axes_grid1/inset_locator_demo2.py
examples/axes_grid1/simple_axesgrid2.py
examples/frontpage/3D.py
examples/images_contours_and_fields/shading_example.py
examples/lines_bars_and_markers/scatter_demo2.py
examples/mplot3d/custom_shaded_3d_surface.py
examples/recipes/common_date_problems.py
examples/recipes/fill_between_alpha.py
examples/specialty_plots/topographic_hillshading.py
examples/subplots_axes_and_figures/zoom_inset_axes.py
examples/text_labels_and_annotations/date.py
examples/text_labels_and_annotations/date_index_formatter.py
examples/ticks_and_spines/centered_ticklabels.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/tests/test_colors.py
lib/mpl_toolkits/tests/test_axes_grid1.py
tutorials/colors/colormapnorms.py

This makes examples shorter and more to the point by simplifying the
data-load part.  A small (standard) backcompat-dance is needed.
Edit: will also depend on #15645.
Edit: now good to go.

Make get_sample_data autoload npy/npz files.

---

lib/matplotlib/backends/backend_cairo.py
lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/backends/backend_qt5agg.py

Test with e.g. examples/event_handling/poly_editor.py.
Doing the same for the other foocairo backends is left as an exercise to
the reader.
cf. https://github.com/matplotlib/matplotlib/pull/10187#discussion_r426298512.

Add support for blitting in qt5cairo.

---

lib/mpl_toolkits/axisartist/angle_helper.py
lib/mpl_toolkits/axisartist/floating_axes.py
lib/mpl_toolkits/axisartist/grid_finder.py

Let's try to figure out how this whole thing is constructed :)  At least
that PR is my understanding.
Minor refactorings as well.
~~Goes on top of https://github.com/matplotlib/matplotlib/pull/13878.~~

Add some documentation for axisartist's ExtremeFinder, plus some cleanups.

---

lib/matplotlib/axes/_axes.py

- Move check that x and y have same size to top.
- Replace xywhere by a more general mask-application function; then, in
the various xlolims/xuplims/... handling blocks, apply all masks at
once.
- Apply xlolims/xuplims in extract_err, which allows drawing all
errorbars in a single call to vlines()/hlines().
- We don't need to check the size of lolims/uplims because they go
through broadcast() earlier.
- Clarify the docstring a bit.
---
tbh, based on the somewhat debatable interpretation of lolims/uplims (should it be uplims/lolims? -- see docstring edit), the lack of anyone ever mentioning that, and the fact that their interpretation was inverted in https://github.com/matplotlib/matplotlib/pull/2452 with no apparent complaints, I believe it's likely that this feature …

Simplifications to errorbar().

---

examples/misc/customize_rc.py

If you know how to set to rcParams (which is "just a dict"), you'll
figure out how to read from it as well.  The ability of save a few
keystrokes in rc() is not worth the different API -- at least for the
example.

Prefer demo'ing rcParams rather than rc in examples.

---

lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_axes.py

closes #17331
Applies patch suggested by @anntzer  in https://github.com/matplotlib/matplotlib/issues/17331#issuecomment-624109727

FIX: cancel pending autoscale on manually setting limits

---

lib/matplotlib/axes/_subplots.py
lib/matplotlib/figure.py
lib/matplotlib/pyplot.py

Rather minor corrections/improvements.

Update docs on subplot2grid / SubplotBase

---

.flake8
examples/lines_bars_and_markers/curve_error_band.py

Inspired by and closes #17398.

Add example for drawing an error band around a curve

---

lib/matplotlib/pyplot.py

Update subplot2grid doc to use Figure.add_gridspec, not GridSpec.

---

lib/matplotlib/pyplot.py

Not sure why GitHub didn't show any conflicts before merging #17550.

DOC: Remove duplicate Returns in subplot2grid.

---

examples/showcase/mandelbrot.py

Fixes https://github.com/matplotlib/matplotlib.github.com/issues/43

Fix link in doc

---

lib/matplotlib/ticker.py

As usual, add/improve some docstrings.
Towards fixing of #16239 (needs still a bit more, but this one is enough for today).

Improve docstrings of ScalarFormatter

---

lib/matplotlib/collections.py

Meant to just add the appropriate `:rc:` links to the `collections.py` docs, but then realized that the docs in there were reasonably out of sync with our style conventions, so I tried my best to get these sync'd up to match what I understand we would want the docs to look like if they were new contributions. 
There are some warnings when I compile the docs locally, but then again, I also get warnings on `master`, so I went ahead and opened the PR to see if readthedocs has better luck than I. 
- [N/A] …

DOCS: update collections.py docstrings to current doc conventions

---

tutorials/introductory/usage.py

This was added in #14714, and then backported in #14822 to `v3.1.x`, and
a merge up must have accidentally included both.
Fixes #17613.

DOC: Remove duplicated line.

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_qt5.py

Correct documentation (and slight bug in Qt implementation) of start_event_loop.
closes #17615

Doc event loop

---

lib/matplotlib/cbook/__init__.py
lib/matplotlib/tests/test_cbook.py

- special case methods because they are descriptors
- fail on any other non-instance attribute
This is a simpler version of  #17561

MNT: make _setattr_cm more conservative

---

doc/_templates/layout.html

remove the banner, but leave skeleton to make it easy to put one back in the future.

DOC: remove banner

---

lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/backends/qt_compat.py

More qt fractional DPI fixes

---

doc/users/prev_whats_new/whats_new_3.0.rst
doc/users/prev_whats_new/whats_new_3.1.0.rst
doc/users/prev_whats_new/whats_new_3.2.0.rst
doc/users/prev_whats_new/whats_new_3.3.0.rst

Cleanup typos and a few style inconsistencies.

Small fixes to recent What's New

---

lib/matplotlib/dates.py

Clarify docs of AutoDateLocator.intervald

---

tutorials/colors/colors.py

Document that some single char colors are shaded

---

INSTALL.rst

DOC: specify that the LaTeX installation needs to include cm-super

---

.circleci/deploy-docs.sh

Actually, this is just debug right now...

ci: Print out reasons for not deploying docs.

---

examples/pyplots/pyplot_simple.py

- [X ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [X ] New features are documented, with examples if plot related
- [X ] Documentation is sphinx and numpydoc compliant
- [X ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [X ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way
In this PR I added a description to examples/pyplots/pyplot_simple.py as raised in issue "Add one-line descriptions to remaining examples #8921". I'm sorry if I did something wrong with this PR. This is my first real contribution and I am just trying to learn the flow of these things. :)

Add description examples/pyplots/pyplot simple.py

---

lib/matplotlib/backends/backend_svg.py

This is already mentioned by the DC/RDF metadata a few lines below.

Remove "created-by-matplotlib" comment in svg output.

---

lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/cbook/__init__.py
setupext.py
src/_c_internal_utils.c

Closes https://github.com/matplotlib/matplotlib/issues/17144.  Note that jupyter qtconsole essentially does the same, per https://github.com/jupyter/qtconsole/pull/71/files (except that they use ctypes and don't worry about being embedded in another app).

Set Win32 AppUserModelId to fix taskbar icons.

---

doc/conf.py

Follow-up to #17275.
Test oversampling by x2.

Oversample thumbnail x2

---

lib/matplotlib/font_manager.py

Previously, when using findfont with rebuild_is_missing (the default)
_rebuild() would generate a new fontManager instance, but because
findfont is defined as `findfont = fontManager.findfont`, this would
keep using the old fontManager instance; we can't just fix this with
`def findfont(...): return fontManager.findfont(...)` because people may
be importing the fontManager instance anyways and not benefitting from
the rebuilt one.
Instead, overwrite(!) the contents of the existing fontManager instance
with the new one as needed.
@timhoffm IIRC you had some issues with font cache rebuilding, perhaps this helps?

FontManager fixes.

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/colorbar.py
lib/matplotlib/dates.py
lib/matplotlib/legend.py
lib/matplotlib/lines.py
lib/matplotlib/offsetbox.py
lib/matplotlib/sankey.py

Sorry, this is a bit all-over-the-place. I started this a _long_ time ago, and in the interest of it not becoming further out of date, I decided to clean it up a bit and post it. Unfortunately, it's a bit of a hodge-podge of different things right now.

Numpydoc-ify various functions

---

tutorials/intermediate/artists.py

We've added custom repr for many objects, so these hard-coded results are not what someone would see in the console. Also, capitalize Matplotlib.

Update hard-coded results in artist tutorial

---

lib/mpl_toolkits/axisartist/axisline_style.py

Plain trigonometry is easier to follow...

Don't use bezier helpers in axisartist.

---

doc/users/next_whats_new/colorbar_position.rst

Per https://github.com/matplotlib/matplotlib/pull/17753#pullrequestreview-438623366

Fix whatsnew confusing typo.

---

.mailmap

update mailmap
attn @ivanov @Carreau  @sameshl @SidharthBansal can you all please confirm that these are correct?

MNT: update mailmap

---

doc/devel/MEP/MEP11.rst
examples/misc/custom_projection.py
examples/pie_and_polar_charts/pie_features.py
examples/shapes_and_collections/arrow_guide.py
examples/showcase/integral.py
examples/statistics/histogram_multihist.py
lib/matplotlib/tests/test_ticker.py
lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/mplot3d/axes3d.py
tutorials/intermediate/legend_guide.py

Fix overindented bullet/enumerated lists.

---

doc/api/api_changes_3.4/deprecations.rst
examples/specialty_plots/leftventricle_bulleye.py
examples/statistics/barchart_demo.py
examples/statistics/boxplot_demo.py
lib/matplotlib/backend_bases.py

This really belongs on the manager, and is a mild footgun on the canvas.
See discussion at https://github.com/matplotlib/matplotlib/issues/17721.

Deprecate FigureCanvas.{get,set}_window_title.

---

lib/matplotlib/colorbar.py

Improve docstring of ColorbarBase.set_label()

---

tutorials/intermediate/tight_layout_guide.py

Fix typos in tight layout guide

---

lib/matplotlib/cbook/__init__.py
lib/matplotlib/tests/test_cbook.py

This fixes a regression introduced by commit ac018af76cae81054dd27c2d4039dfd5467a1366.
Closes #17820

FIX: Keep lists of lists of one scalar each 2D in _reshape_2D

---

lib/matplotlib/axes/_axes.py

The description was a bit terse and thus difficult to understand for non-experts.

Clarify plotnonfinite parameter docs of scatter()

---

lib/matplotlib/axis.py

Adresses #17136 by documenting the behavior.

Document that set_ticks() increases view limits if necessary

---

examples/shapes_and_collections/hatch_style_reference.py

Added density and combination hatching examples

---

tutorials/introductory/images.py

Updated doc in images.py by adding direct link to 24-bit stink bug png

---

lib/matplotlib/tests/test_backend_svg.py

In title; also use a context manager.
- [N/A] Documented in doc/api/next_api_changes/* if API changed in a backward-incompatible way

Remove unnecessary file save during test

---

examples/images_contours_and_fields/barcode_demo.py

This example is a bit particular anyway, but let's make it practical by
generating a real bar code and not only some random lines.
Fun fact: The used code is the GTIN-13 for "The Visual Display of
Quantitative Information", Edward R. Tufte.

Rewrite the barcode example

---

tutorials/advanced/blitting.py

I revised some words in `blitting.py`

Fix some words

---

doc/api/api_changes_3.4/deprecations.rst
lib/matplotlib/dates.py
lib/matplotlib/tests/test_dates.py

Manual backport of pr 17983 on v3.3.x

---

lib/matplotlib/path.py

update_from_data_xy is much slower than needed; we can use plain numpy
instead.  (This speeds up #17974 another ~30-40% on top of #17994.)
For polylines, we can completely skip the bezier handling for even more
speedup.  (This fixes the performance regression.)

Avoid using Bbox machinery in Path.get_extents; special case polylines.

---

lib/matplotlib/tight_bbox.py

It's more readable to directly define the relevant callbacks
(axes_locator, apply_aspect) as one-line lambdas at the point of use,
instead of having to define them much earlier.  Pickling is not an issue
as these lambdas are only set temporarily while computing the figure
tightbbox for saving.

Shorten tight_bbox.

---

.gitignore
lib/matplotlib/tests/test_matplotlib.py

This simple test may prevent something like issue #17970

add test with -OO

---

lib/matplotlib/__init__.py

Fix flipped paths in non-writable config dir warning.

---

.flake8
lib/matplotlib/axes/_secondary_axes.py
lib/matplotlib/backends/backend_gtk3cairo.py
lib/matplotlib/bezier.py
lib/matplotlib/figure.py
lib/matplotlib/gridspec.py
lib/matplotlib/rcsetup.py
lib/matplotlib/testing/decorators.py

And fix some extraneous blank lines.

Remove some unused imports.

---

examples/misc/custom_projection.py
lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/matplotlib/backend_bases.py
lib/matplotlib/backend_managers.py
lib/matplotlib/collections.py
lib/matplotlib/container.py
lib/matplotlib/legend.py
lib/matplotlib/offsetbox.py
lib/matplotlib/projections/geo.py
lib/matplotlib/projections/polar.py
lib/matplotlib/quiver.py
lib/matplotlib/scale.py
lib/matplotlib/tests/test_skew.py
lib/matplotlib/tests/test_transforms.py
lib/matplotlib/transforms.py
lib/mpl_toolkits/axes_grid1/anchored_artists.py
lib/mpl_toolkits/axes_grid1/mpl_axes.py
lib/mpl_toolkits/axisartist/axis_artist.py
lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/mplot3d/axis3d.py

I limited this to about ~100 lines of add/delete. Ref #3129.

Super-ify parts of the code base, part 1

---

doc/api/next_api_changes/README.rst
doc/users/next_whats_new/README.rst

This mostly affects what's new/API changes, so put the suggestion there.

Discourage references in section headings.

---

doc/devel/contributing.rst
examples/text_labels_and_annotations/line_with_text.py
examples/userdemo/colormap_normalizations.py
lib/matplotlib/colorbar.py
lib/matplotlib/colors.py
lib/matplotlib/contour.py
lib/matplotlib/dviread.py
lib/matplotlib/legend.py
lib/matplotlib/legend_handler.py
lib/matplotlib/lines.py
lib/matplotlib/mathtext.py
lib/matplotlib/text.py
lib/matplotlib/tri/tricontour.py
lib/matplotlib/tri/trifinder.py
lib/matplotlib/tri/triinterpolate.py
lib/matplotlib/tri/trirefine.py
lib/mpl_toolkits/axes_grid1/colorbar.py
lib/mpl_toolkits/axisartist/axis_artist.py
lib/mpl_toolkits/mplot3d/art3d.py
tutorials/colors/colormapnorms.py

Again, limited this to about ~100 lines of add/delete. Ref #3129.

 Super-ify parts of the code base, part 2

---

tutorials/text/usetex.py

typo in usetex.py example

---

doc/api/next_api_changes/removals/18070-DS.rst
doc/api/prev_api_changes/api_changes_3.2.0/behavior.rst
lib/matplotlib/rcsetup.py

These are all the 3.2 deprecations in `rcsetup.py`.

Remove rcsetup deprecations

---

lib/matplotlib/axis.py

Add a note on working around limit expansion of set_ticks()

---

examples/units/basic_units.py
examples/widgets/menu.py
lib/matplotlib/animation.py
lib/matplotlib/dates.py
lib/matplotlib/gridspec.py
lib/matplotlib/hatch.py
lib/matplotlib/image.py
lib/matplotlib/patches.py
lib/matplotlib/patheffects.py
lib/matplotlib/quiver.py
lib/matplotlib/table.py
lib/matplotlib/ticker.py
lib/matplotlib/widgets.py
lib/mpl_toolkits/axes_grid1/axes_divider.py
lib/mpl_toolkits/axes_grid1/inset_locator.py
lib/mpl_toolkits/axisartist/grid_finder.py
lib/mpl_toolkits/mplot3d/art3d.py

Again, limited this to about ~100 lines of add/delete. Ref #3129.

Super-ify parts of the code base, part 3

---

.github/workflows/reviewdog.yml
lib/matplotlib/axes/_axes.py
lib/matplotlib/rcsetup.py

ci: Fix linting being ignored by reviewdog

---

examples/subplots_axes_and_figures/figure_title.py

Cleanup figure title example

---

.github/workflows/reviewdog.yml
lib/matplotlib/bezier.py
lib/matplotlib/figure.py

Backport of #18091, plus correction of flake8 error (see commits).

Fix linting on v3.3.x

---

lib/matplotlib/backends/backend_pdf.py

I believe it should work equivalently, but looks a bit better semantically.

pdf: Convert operator list to an Enum.

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backend_tools.py
lib/matplotlib/backends/_backend_tk.py

This fixes some inconsistencies between the MEP 22 tool manager and the regular toolbar.

Fix ToolManager inconsistencies with regular toolbar

---

.travis.yml
ci/osx-deps
lib/matplotlib/tests/test_backend_qt.py
lib/matplotlib/tests/test_backends_interactive.py

This sets up Travis so that the Mac tests use XCode 9 on MacOS 10.12.
Homebrew doesn't support this configuration, so we install the library dependencies without it. Tests requiring Qt5 are skipped because [Qt5 requires 10.13 or later](https://doc.qt.io/qt-5/macos.html). We do install Qt4 and at least PySide seems to work, so it is possible to write tests for Qt4.

Build on xcode9

---

lib/matplotlib/figure.py

DOC: fix align_xlabels() typo

---

examples/user_interfaces/embedding_in_wx2_sgskip.py
examples/user_interfaces/embedding_in_wx3_sgskip.py
examples/user_interfaces/embedding_in_wx4_sgskip.py
examples/user_interfaces/embedding_in_wx5_sgskip.py
examples/user_interfaces/fourier_demo_wx_sgskip.py
examples/user_interfaces/mathtext_wx_sgskip.py
examples/user_interfaces/wxcursor_demo_sgskip.py
lib/matplotlib/backend_tools.py
lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_agg.py
lib/matplotlib/backends/backend_cairo.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_nbagg.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/backends/backend_svg.py
lib/matplotlib/backends/backend_webagg_core.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/backends/qt_editor/_formlayout.py
lib/matplotlib/blocking_input.py

A similar PR to the others, wrt #3129. Not entirely sure all backends support this, so I guess we'll see how CI feels.

Use `super()` more in  backends

---

examples/lines_bars_and_markers/hat_graph.py

With reference to this issue : hat graphs need an example... #17537
I have added the example @timhoffm

Hat graph example

---

lib/matplotlib/__init__.py
lib/matplotlib/image.py
lib/matplotlib/testing/conftest.py
lib/matplotlib/tests/test_image.py
requirements/testing/travis_all.txt
setup.py
setupext.py

Uses the suggested fix of @tdpetrou .
closes #18129

FIX: fix reading from http/https urls via imread

---

.github/workflows/cibuildwheel.yml

This is enabled for push & pull_request right now, but since we have nowhere to upload anything permanent, I'll probably switch this to tags-only for final usage, if merged.
- [n/a] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant

Try out cibuildwheel.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/maintenance.md
.github/ISSUE_TEMPLATE/questions.md

Closes: #18160
- Added a feature request template that will automatically be tagged with the `New Feature` label. 
- Moved ISSUE_TEMPLATE.MD to ISSUE_TEMPLATE/bug_report.md so that both issue templates will show up as options for opening a new issue.
The feature request template is an almost exact copy of the jupyterlab template but I wrote the jupyterlab version so I think it's fine to just copy it w/o attribution. 
ping @story645 
- na Has Pytest style unit tests
- na Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- na New features are documented, with examples if plot related
- na Documentation is sphinx and numpydoc compliant
- na Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- na Documented in …

Add more specific GitHub issue templates

---

.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/maintenance.md

Documentation and Maintenance issues were not automatically receiving the correct label on issue creation
@story645 my bad for missing this the first time around!
- na Has Pytest style unit tests
- na Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- na New features are documented, with examples if plot related
- na Documentation is sphinx and numpydoc compliant
- na Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- na Documented in doc/api/next_api_changes/* if API changed in a backward-incompatible way

correctly autolabel Documentation and Maintenance issues

---

doc/users/next_whats_new/errorbars_3d.rst
doc/users/whats_new/errorbars_3d.rst

Also, move what's new entry to new location.
- [n/a] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant

Fix broken links in doc build.

---

examples/misc/packed_bubbles.py

Added example on how to make packed bubble charts

Added example on how to make packed bubble charts

---

lib/matplotlib/axes/_axes.py

boxplot: Add conf_intervals reference to notch docs.

---

lib/matplotlib/artist.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/axis.py
lib/matplotlib/legend.py

More nouns/imperative forms in docs.

---

lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/tests/test_mplot3d.py

Technically, it's tested, though the test wasn't strictly designed to do so (#18156). Not sure if I should write a different test.

Fix scatter3d color/linewidth re-projection

---

lib/matplotlib/animation.py

xref https://github.com/matplotlib/matplotlib/issues/18381 - should make the docstring a little bit clearer.

Clarification in ArtistAnimation docstring

---

examples/widgets/menu.py

The first commit has some pretty generic cleanups.
The second commit switches from using the slightly obscure MathTextBackend to convert text to bitmaps (even though there's no equations in it...) to drawing text with boring Text objects.

Cleanup menu example

---

lib/matplotlib/backends/_backend_tk.py

Merge pull request #18395 from richardsheridan/multi-toggle-fix
FIX: deselect buttons that are not the current _Mode

Backport PR #18395: TkAgg bugfix: deselect buttons that are not the current _Mode

---

tutorials/introductory/sample_plots.py

Currently clicking the `widgets examples` link on the sample plots page puts you at the top of the page rather than the at the widgets examples section. This changes it so you are placed at the correct section.
You can find the offending link here: https://matplotlib.org/3.3.1/tutorials/introductory/sample_plots.html#gui-widgets
which then leads to here:
https://matplotlib.org/3.3.1/gallery/index.html
instead of 
https://matplotlib.org/3.3.1/gallery/index.html#widgets
- na Has pytest style unit tests (and `pytest` passes).
- na Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- na New features are documented, with examples if plot related.
- na Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and …

Correct link to widgets examples

---

lib/matplotlib/backends/web_backend/js/mpl.js
lib/matplotlib/backends/web_backend/js/nbagg_mpl.js
requirements/testing/travis_extra.txt

This backports #18361 and #18454 to v3.3.2

Nbagg backports

---

doc/devel/contributing.rst

Modified terminal command language to indicate that user can control directory for creating new environment.
- [ x] Has pytest style unit tests (and `pytest` passes).
- [ x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ x] New features are documented, with examples if plot related.
- [ x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and run `flake8 --docstring-convention=all`).
- [x ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [x ] API changes documented in …

New environment terminal language

---

lib/matplotlib/ticker.py

It's only used in one place, in a tiny function, and doesn't have a
particularly intuitive name, so it's actually easier to follow the logic
by having it all in one place.  Moreover the implementation can be
greatly simplified by separately computing and formatting the mantissa
and the exponent, rather than trying to parse the locale-dependent
result of the formatting of the entire number.

Inline ScalarFormatter._formatSciNotation.

---

doc/api/next_api_changes/removals/18502-TH.rst
lib/matplotlib/cm.py

Remove the deprecated matplotlib.cm.revcmap()

---

doc/MCSE.2007.55.bib
doc/citing.rst

An attempt in solving problem described in issue  #18442, by extracting BibTeX citation to a seperate file. 
The bib file is then included in the citation page when generating the docs. Also added a simple "download button" as described in the issue. 
Unsure about where to put the bib-file. Added it to the root of the docs along with the existing citing.rst, as this probably will be the only bib file for the documentation?
- [N/A] Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and run `flake8 …

Change to literalinclude and downloadable BibTeX citation  #18442

---

lib/matplotlib/_api.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/matplotlib/backends/backend_cairo.py
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/collections.py
lib/matplotlib/colorbar.py
lib/matplotlib/mathtext.py
lib/matplotlib/offsetbox.py
lib/matplotlib/path.py
lib/matplotlib/quiver.py
lib/matplotlib/scale.py
lib/matplotlib/testing/jpl_units/UnitDbl.py
lib/matplotlib/tests/test_api.py
lib/matplotlib/tests/test_cbook.py
lib/mpl_toolkits/axisartist/axis_artist.py
lib/mpl_toolkits/mplot3d/axes3d.py

Follow-up to #18494. Another step towards #16181. This PR
- Moves cbook._check_shape() to _api.check_shape()
- Moves cbook._check_getitem() to _api.check_getitem()

Private api2

---

lib/matplotlib/colorbar.py

There's so many helper functions in ColorbarBase that I find the code
logic a bit hard to follow...
In draw_all:
- Simplify and inline _find_range as a one-liner.
- _outline can also be inlined after a bit of shortening using fancy
indexing, which I find easier to read anyways: we just take the first
two and last two values on the first column, and then the last two and
first two values on the second column.
- Also everything is in data units now; the comment about self._mesh()
has been outdated for a while.
In _mesh:
- Simplify and inline _central_N.

Inline some helpers in ColorbarBase.

---

examples/misc/patheffect_demo.py
examples/pie_and_polar_charts/bar_of_pie.py
examples/text_labels_and_annotations/demo_text_path.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_backend_pgf.py
lib/matplotlib/tests/test_contour.py
lib/matplotlib/tests/test_image.py
tutorials/text/annotations.py

Addresses part of the cases of #17335.
Plus some minor cleanup along the way.

Replace subplot(ijk) calls by subplots(i, j)

---

examples/subplots_axes_and_figures/axes_zoom_effect.py
lib/matplotlib/widgets.py

... and small additional cleanups.

Use get_x/yaxis_transform more.

---

lib/matplotlib/tests/test_afm.py
lib/matplotlib/tests/test_agg.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_bbox_tight.py
lib/matplotlib/tests/test_cbook.py
lib/matplotlib/tests/test_text.py

Mostly suggestions by a code checker and readability improvements.

Random test cleanups

---

lib/matplotlib/backends/backend_pdf.py

Factor out pdf Type3 glyph drawing.

---

doc/users/next_whats_new/axes_class.rst
examples/axes_grid1/demo_axes_divider.py
examples/axes_grid1/parasite_simple2.py
examples/axisartist/axis_direction.py
examples/axisartist/demo_axis_direction.py
examples/axisartist/demo_axisline_style.py
examples/axisartist/demo_curvelinear_grid.py
examples/axisartist/demo_curvelinear_grid2.py
examples/axisartist/demo_floating_axes.py
examples/axisartist/demo_floating_axis.py
examples/axisartist/demo_parasite_axes.py
examples/axisartist/demo_ticklabel_alignment.py
examples/axisartist/demo_ticklabel_direction.py
examples/axisartist/simple_axis_direction01.py
examples/axisartist/simple_axis_direction03.py
examples/axisartist/simple_axis_pad.py
examples/axisartist/simple_axisartist1.py
examples/axisartist/simple_axisline.py
examples/axisartist/simple_axisline2.py
examples/axisartist/simple_axisline3.py
lib/matplotlib/figure.py
lib/matplotlib/tests/test_figure.py
tutorials/toolkits/axisartist.py

Implements https://github.com/matplotlib/matplotlib/issues/18548, see discussion there.

add_subplot(..., axes_class=...) for more idiomatic mpl_toolkits usage.

---

lib/matplotlib/patches.py

In Rectangle: no need to keep track and update of `self._x1` and
`self._x2` all the time, just when we compute the patch_transform
(which doesn't need to be split out into its own function, or stored
into an instance variable, given that it's never accessed via the
private attribute name).
In RegularPolygon: likewise, we can just compute the transform in
get_patch_transform(), and nowhere else, so the other attributes can
just be plain attributes instead of properties that update the transform
all the time.

Simplify Rectangle and RegularPolygon.

---

doc/devel/documenting_mpl.rst

Fixes #18355. tl;dr: You need Inkscape, optipng, and Humor Sans fonts installed locally for the docs to build without warnings.

DOCS: optional doc building dependencies

---

doc/devel/documenting_mpl.rst

More structure and less wordy.

Improve instructions for building the docs

---

doc/api/next_api_changes/deprecations/18527-AL.rst
lib/matplotlib/colorbar.py
lib/matplotlib/figure.py
lib/matplotlib/tests/test_colorbar.py
lib/matplotlib/tests/test_colors.py
lib/matplotlib/tests/test_constrainedlayout.py
lib/matplotlib/tests/test_image.py
lib/mpl_toolkits/axes_grid1/axes_grid.py

It is easier to have an internal switch on the mappable type, rather
than having a separate "internal" (per the documentation) API to support
hatchings.  Also note that the previous version would fail in obscure
cases where the contourset was changed from not using hatches to using
hatches after the colorbar was created.

Fold ColorbarPatch into Colorbar, deprecate colorbar_factory.

---

.github/workflows/cibuildwheel.yml
setup.py

BLD: certifi is not a run-time dependency

---

doc/api/axis_api.rst
doc/api/index.rst
doc/api/prev_api_changes/api_changes_3.1.0.rst
doc/api/tight_bbox_api.rst
doc/missing-references.json
doc/users/dflt_style_changes.rst
doc/users/prev_whats_new/whats_new_1.2.rst
doc/users/prev_whats_new/whats_new_3.0.rst
doc/users/prev_whats_new/whats_new_3.1.0.rst
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/dviread.py
lib/matplotlib/offsetbox.py
lib/matplotlib/patheffects.py
lib/matplotlib/testing/compare.py
lib/mpl_toolkits/axes_grid1/anchored_artists.py
lib/mpl_toolkits/axes_grid1/axes_divider.py

Fix some missing references.

---

lib/matplotlib/axes/_axes.py

Follow up to #18700. It's actually a little more complex as x and/or y may be 2D. Also I think it's better to illustrate a case with a non-default x.

Improve documentation of plot() with arrays

---

lib/matplotlib/tests/test_mlab.py

When there's approximately 3x more lines for defining inputs and outputs
than for the actual testing, the purpose of the tests becomes difficult
to see.
Not using `parametrize` because it's a bit tricky to define the
inputs/outputs in the decorator, and adding more indirection would
defeat the purpose of the PR.

Shorten mlab tests.

---

lib/matplotlib/backends/backend_pdf.py

This is supported since 19359c1, results in smaller files (*much*
smaller when using CJK fonts), and avoids running into issues with type
42 embedding and certain pdf readers such as Acrobat Reader.
Closes https://github.com/matplotlib/matplotlib/issues/12636.

Allow Type3 subsetting of otf fonts in pdf backend.

---

lib/matplotlib/colors.py

- Fix the docstring regarding `__init__`, which was previously
incorrect (pointed out by @jklymak in https://github.com/matplotlib/matplotlib/pull/16457#issuecomment-703275655).
It's very long, but I can't really think of a better wording...
- Set `__signature__` on `__init__`, for better instrospection.

_make_norm_from_scale fixes.

---

examples/images_contours_and_fields/image_transparency_blend.py
examples/images_contours_and_fields/pcolor_demo.py
examples/images_contours_and_fields/pcolormesh_levels.py
examples/mplot3d/quiver3d.py
examples/statistics/hexbin_demo.py
lib/matplotlib/_cm.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/cm.py
lib/matplotlib/colors.py
lib/matplotlib/contour.py
lib/matplotlib/figure.py
lib/matplotlib/image.py
lib/matplotlib/mlab.py
lib/matplotlib/path.py
lib/matplotlib/stackplot.py
lib/matplotlib/transforms.py
lib/matplotlib/tri/triangulation.py
lib/matplotlib/tri/triinterpolate.py
lib/matplotlib/tri/trirefine.py
lib/matplotlib/tri/tritools.py
lib/mpl_toolkits/axisartist/axislines.py
lib/mpl_toolkits/mplot3d/axes3d.py
lib/mpl_toolkits/tests/test_mplot3d.py
tutorials/introductory/sample_plots.py

As documented in the [docstring guide](https://matplotlib.org/devdocs/devel/documenting_mpl.html#parameter-type-descriptions).

Consistently use 3D, 2D, 1D for dimensionality

---

.github/PULL_REQUEST_TEMPLATE.md
examples/style_sheets/plot_solarizedlight2.py
examples/text_labels_and_annotations/rainbow_text.py
lib/matplotlib/backends/backend_agg.py
requirements/testing/flake8.txt
tutorials/text/mathtext.py

Our docs used to cause pydocstyle>4 to raise, so we had this instruction in the pull request template which appears to no longer be needed.
Tested locally in a new conda environment:
```bash
$ conda create -n doc_check python=3.8
$ conda activate doc_check
$ pip install flake8-docstrings
$ flake8 --docstring-convention=all lib/matplotlib  # no longer raises
```
Old version:
New version:

CI: pydocstyle>=5.1.0, flake8-docstrings>=1.4.0 verified to work

---

doc/faq/howto_faq.rst
examples/user_interfaces/web_application_server_sgskip.py
tutorials/introductory/usage.py

Follow up to #18767.
Minor cleanups.

Update description of web application server example.

---

examples/text_labels_and_annotations/legend_demo.py
lib/matplotlib/tests/test_legend.py
tutorials/colors/colormaps.py

This cleans up some usages that were missed in #14096.

Consistently use axs to refer to a set of Axes (v2)

---

lib/matplotlib/axes/_axes.py

Towards #18726
Use Axes instead of axes in `_axes.py`.

DOC Use 'Axes' in _axes.py docstrings

---

examples/specialty_plots/anscombe.py

Hi!
This PR includes a tiny change to the [Anscombe's Quartet example](https://matplotlib.org/gallery/specialty_plots/anscombe.html):
- current version: the linear regression lines only go from `min(x)` to `max(x)` per plot.
- updated version: the lines go the entire length of the plots, similar to the [Wikipedia page](https://en.wikipedia.org/wiki/Anscombe%27s_quartet)
Reason for this update:
When I looked at the IV quadrant, I thought that its linear regression line was different from the rest in terms of its _intercept_, slope seemed the same, but even though I squinted hard, I still doubted my prior assumption that all 4 datasets should result in the same summary statistics (and therefore also regression slopes & intercepts). I visited Wikipedia and confirmed that indeed the 4 lines …

[Example] update Anscombe's Quartet

---

lib/matplotlib/figure.py

Follow-up / correction of #18811.

Fix axes -> Axes changes in figure.py

---

doc/api/axis_api.rst
tutorials/intermediate/artists.py

Add cross-references to Artist tutorial

---

examples/animation/animated_histogram.py

Newly  a BarContainer from hist() function is used.
Related to #18570 I diverged from using plt.stairs because resulting plot was different (stairs does not form bars, just an outline of the histogram). However, I simplified the code by utilizing normal histogram function. Moreover, I believe that there was an misconception with dynamically allocated bins that rendered manual histogram with errors (if we set constant number of bins, but range of `np.random.normal` is different, then edges and counts are out of sync). This was fixed by pre-calculating edges and making them constant.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow …

Simplification of animated histogram example

---

lib/matplotlib/backends/backend_wx.py

AFAICT this fixes https://github.com/matplotlib/matplotlib/issues/8249 on Windows and doesn't break Linux.

Bind WX_CHAR_HOOK instead of WX_KEY_DOWN for wx key_press_event.

---

setup.py

Fixes #18882. Updated the minimum version of Matplotlib from 3.1 to 3.4 in setup.py.

Update version of Matplotlib that needs Python 3.7

---

lib/matplotlib/tests/test_backend_pgf.py

`ucs` is a dependency of `\usepackage[utf8x]{inputenc}`, but if it
is absent we fail later with the slightly confusing error message
"Keyboard character used is undefined in inputencoding `utf8x'" (as
can be observed by temporarily uninstalling `ucs`).  Instead, make
the dependency explicit.  Also, in test_rcupdate, only one of the two
iterations uses `[utf8x]{inputenc}`, so run the other iteration first
(giving it a chance to fail) and skip the test only at the second
iteration if needed.

Add dependency on ucs for pgf tests using [utf8x]{inputenc}.

---

lib/matplotlib/tests/test_backends_interactive.py

- Move the long test-scripts to separate functions and extract their
source using `inspect.getsource` to pass that to the subprocess; this
avoids having really long source snippets in strings and lets us have
e.g. syntax highlighting on them.
- Use ThreadPoolExecutor in test_interactive_thread_safety /
_test_thread_impl which provides a much simpler (basically automatic)
API to rethrow exceptions from within the thread.

Rework interactive backends tests.

---

examples/images_contours_and_fields/contourf_hatching.py

Tiny fix, changes from bad string formatting and hard to understand see-thru background:
to the following:

DOCS: fix contourf hatch demo legend

---

lib/matplotlib/animation.py

- Simplify the implementation of `repeat_delay`: instead of switching
callbacks back and forth, just set the timer interval at each
iteration to either the normal delay or the end-of-loop delay.
- Fix support for `repeat_delay` when `frames` is an iterable: the
previous implementation handled looping in `iter_frames` and therefore
`_step` never saw the end of the iterable.  Instead, just iterate
through `frames` once in `iter_frames`, but still `tee` the iterable
so that `_step` can take care of repeating the animation.
Can be checked with
```python
import matplotlib.animation as animation
line, = ax.plot(range(10))
def animate(i):
line.set_ydata(range(i, i + 10))  # update the data.
return line,
ani = animation.FuncAnimation(
fig, …
```

Simplify repeat_delay and fix support for it when using iterable frames.

---

lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/tests/test_mplot3d.py

Code from a debugging session on the phone with @QuLogic

FIX: make sure scalarmappable updates are handled correctly in 3D

---

lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/tests/test_mplot3d.py

Backport PR #18929 on branch v3.3.x

---

lib/matplotlib/path.py

For reference: Issues that are concerned with this behavior: #9704, #17279, #18879.

Document limitations of Path.contains_point() and clarify its semantics

---

doc/api/next_api_changes/removals/18909-TH.rst
lib/matplotlib/artist.py
lib/matplotlib/container.py

They are unused.
Closes #4877.

Remove Artist.eventson and Container.eventson

---

lib/matplotlib/axes/_axes.py

Update _axes.py to include mentions of rasterization within pcolormesh fixes #17708
PyData sprint contribution to enhance the documentation of rasterization within the pcolormesh function.

Document rasterized parameter in pcolormesh() explicitly

---

.flake8
examples/misc/rasterization_demo.py
lib/matplotlib/artist.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py

Inspired by, but independent of #18956.

Improve documentation on rasterization

---

examples/lines_bars_and_markers/categorical_variables.py

More information, less wordy. :smile:

Minor cleanup of categorical example

---

tutorials/introductory/usage.py

- Replace the open bracket with a comma, following the rest of the sentence's structure, i.e., in that section the number of open and closing parenthesis was of the unequal number as one of the commas might have been typed as "(".
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst …

Fix punctuation in doc.

---

doc/api/next_api_changes/behavior/18988-TH.rst
doc/api/next_api_changes/behavior/18989-TH.rst

- Use correct issue number in filename
- Fix typo `non` -> `None`

Fix API change message from #18989

---

lib/matplotlib/cbook/__init__.py

- If a single type is passed in, save an iteration over a tuple.
- Don't compute the type names for the error message unless an error
actually occurred.
Together, this speeds up `_check_isinstance(int, x=1)` by more than
2-fold, and `_check_isinstance((float, int), x=1)` by a few dozen-%.

Micro-optimize check_isinstance.

---

lib/matplotlib/backend_bases.py

Store all the relevant state in a single dict (`_pan_info`), similar
to the one used for zoom (`_zoom_info`), instead of scattering it
in two attributes (`_button_pressed`/`_xypress`).  Slightly reorder
logic in `press_pan` to match the order in `press_zoom`; likewise sync
`release_pan` with `release_zoom`.
We don't need to store the axes index (as was done in `_xypress`).
In `release_zoom`, move the less-than-5px check out of the loop, as it
only needs to be done once.

Cleanup interactive pan/zoom.

---

lib/matplotlib/backends/backend_pgf.py

There isn't much of a point in splitting them into separate functions,
we don't even gain an indent level...

Inline _print_pdf_to_fh, _print_png_to_fh.

---

lib/matplotlib/contour.py

The old implementation was quite expansive; compactify it a bit.  Also
reformat the docs.

Compactify the implementation of ContourLabeler.add_label_near.

---

lib/matplotlib/_mathtext.py

Unpacking implicitly performs the relevant length checks.

Replace mathtext assertions by unpacking.

---

lib/matplotlib/backends/backend_macosx.py
lib/matplotlib/backends/backend_pdf.py

We don't bother with the staple comments about pylab integration in
other backends, so remove them from backend_macosx
It seems better to let FigureCanvasMac and FigureCanvasPdf just inherit
the parent docstrings (and move comments about implementation details of
FigureCanvasMac to, well, comments).

Cleanup comments/docs in backend_macosx, backend_pdf.

---

doc/api/axes_api.rst

The methods are directly inherited, so don't need a separate doc entry.  (See https://github.com/matplotlib/matplotlib/pull/14960 for a longer discussion of a similar case.)

Remove individual doc entries for some methods Axes inherits from Artist

---

doc/users/interactive.rst

See https://matplotlib.org/devdocs/users/interactive.html#ipython-integration.

Fix markup in interactive figures doc.

---

lib/matplotlib/offsetbox.py

Closes #18942. This simple solution is based on `Patch.__init__`.

Fix kwargs handling in AnnotationBbox

---

.github/CODE_OF_CONDUCT.md
CODE_OF_CONDUCT.md
doc/devel/contributing.rst
doc/index.rst

It would be good for @story645 and @tacaswell to double check the contact info (added in the second commit).

Add code of conduct

---

lib/matplotlib/ticker.py

The note about not sharing `Locator` instances should be more prominent than hiding in the base class docs, which most users have no need to examine (since they'll use one of many subclasses 99% of the time).
I opted not to add anything to the `text_intro.py` tutorial, but I'm open to doing so if someone has suggestions on the right level of detail for that.

DOC: Add note about locators at top of ticker docs

---

doc/devel/contributing.rst

Completely stole @timhoffm 's language & added a bit about help w/ non-code ways of contributing.  follow up to #19125

Added non-code contributions to incubator docs 

---

lib/matplotlib/artist.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/axes/_subplots.py
lib/matplotlib/collections.py
lib/matplotlib/figure.py
lib/matplotlib/lines.py
lib/matplotlib/patches.py
lib/matplotlib/pyplot.py
lib/matplotlib/quiver.py
lib/matplotlib/sankey.py
lib/matplotlib/spines.py
lib/matplotlib/table.py
lib/mpl_toolkits/axes_grid1/inset_locator.py
lib/mpl_toolkits/mplot3d/axes3d.py

As discussed in https://github.com/matplotlib/matplotlib/pull/19122#issuecomment-745614808.

Normalize docstring interpolation label for kwdoc() property lists

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_macosx.py
lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/backends/backend_webagg_core.py
lib/matplotlib/backends/backend_wx.py
src/_macosx.m

Probably someone on macOS should check that this works on the macos backend.

Dedupe window-title setting by moving it to FigureManagerBase.

---

lib/mpl_toolkits/axisartist/axislines.py
lib/mpl_toolkits/tests/test_axisartist_floating_axes.py

Fixes https://github.com/matplotlib/matplotlib/issues/19099

Fix axes direction for a floating axisartist

---

lib/matplotlib/widgets.py

Minor doc cleanup

---

lib/matplotlib/artist.py
lib/matplotlib/tests/test_artist.py

Regression was introduced in #18912.

Fix Artist.remove_callback()

---

tutorials/colors/colors.py

Follow-up to #19093.
- Nicer formatting of the color comparision plot.
- Some wording.

Cleanup comparision between X11/CSS4 and xkcd colors

---

.github/workflows/pr_welcome.yml

The action was failing because GITHUB_TOKEN on regular `pull_request` events have read-only access (for security). Change to `pull_request_target` allows the action to run with full permissions (since it only uses workflows
from the target branch). Original issue is actions/first-interaction#10. `pull_request_target` was added in [August](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/).
There's no way to test this easily without just merging, but it should fix it if I spelled everything right.

Fix PR welcome action

---

examples/text_labels_and_annotations/date.py

Addresses #19203.
As noted there, I had no idea what lines 60-61 were doing, so I've expanded the comment to clarify that.  While I was in there, I also:
* enforced capital letters and full stops to make the comments consistent through the file.
* replaced the old-style "%" string formatting with an f-string (line 61).
I have checked the `flake8`, but I'm not 100% sure which of the other tests are relevant here.  The guidance makes the testing look a bit too involved to do "just in case" and I'm assuming the CI tests will pick up any problems.  Obviously I'm happy to be advised if there is more I should have done here.
- [N/A] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 …

Clarify Date Format Example

---

lib/matplotlib/cbook/__init__.py

Fix Grouper example code

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/workflows/pr_welcome.yml

closes #18417 by asking for doc version & mpl version in doc issue template, added short code for finding mpl version to doc & bug templates, some grammar checks on PR bot

added version ask/hint to issue templates, grammar on pr bot

---

.flake8
examples/statistics/boxplot.py
examples/statistics/boxplot_color.py
examples/statistics/boxplot_demo.py
examples/statistics/boxplot_vs_violin.py
examples/statistics/bxp.py
examples/statistics/confidence_ellipse.py
examples/statistics/customized_violin.py
examples/statistics/errorbar.py
examples/statistics/errorbar_features.py
examples/statistics/errorbar_limits.py
examples/statistics/errorbars_and_boxes.py
examples/statistics/hexbin_demo.py
examples/statistics/hist.py
examples/statistics/histogram_cumulative.py
examples/statistics/histogram_features.py
examples/statistics/histogram_histtypes.py
examples/statistics/histogram_multihist.py
examples/statistics/multiple_histograms_side_by_side.py
examples/statistics/time_series_histogram.py
examples/statistics/violinplot.py

As the title says.
I didn't add every function used in the examples,  rather I erred on the side of caution against overlinking things such as `set_ylabel` and tried to include only the functions that the examples focus on.
- [NA] Has pytest style unit tests (and `pytest` passes).
- [NA] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [NA] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [NA] API changes documented in …

Add reference section to all statistics examples

---

tutorials/introductory/usage.py

As a newcommer to matplotlib, I was surprised to see only qt4. I quickly saw that qt5 is also supported and I believe it should be listed.
I don't know enough to know whether "How do I select PyQt4 or PySide?" section should also be updated
- [N/A]] Has pytest style unit tests (and `pytest` passes).
I tried, but got multiple error. I stopped at:
> ModuleNotFoundError: No module named 'matplotlib._api'
There are error in other files
>
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow …

Update first occurrence of QT to show both 4 and 5

---

lib/matplotlib/_api/__init__.py
lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/matplotlib/backend_bases.py
lib/matplotlib/blocking_input.py
lib/matplotlib/category.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/cm.py
lib/matplotlib/colorbar.py
lib/matplotlib/dviread.py
lib/matplotlib/figure.py
lib/matplotlib/rcsetup.py
lib/matplotlib/spines.py
lib/matplotlib/table.py
lib/matplotlib/transforms.py
lib/matplotlib/tri/trifinder.py
lib/matplotlib/tri/triinterpolate.py
lib/matplotlib/tri/tripcolor.py
lib/matplotlib/tri/trirefine.py
lib/matplotlib/tri/tritools.py
lib/mpl_toolkits/axes_grid1/axes_size.py

Followup of moving all API helpers to matplotlib._api (#18657).

Move cbook._check_isinstance() to _api.check_isinstance()

---

lib/matplotlib/axes/_base.py

Cleanup and document _plot_args()

---

.appveyor.yml
azure-pipelines.yml

Backport PR #19301 on branch v3.3.x

---

lib/matplotlib/colors.py

... by special-casing lists-of-rgb(a) tuples in to_rgba_array.
This speeds up colorcet's import nearly twofold, from ~430ms to ~250ms
on my machine.  (colorcet generates a lot of colormaps at import time.)

Speedup LinearSegmentedColormap.from_list.

---

src/_path_wrapper.cpp

(See https://github.com/matplotlib/matplotlib/pull/15009 for the format of docstrings for functions implemented in C.)

Improve docs of _path C-extension.

---

doc/api/next_api_changes/removals/XXXXX-AL.rst
lib/matplotlib/__init__.py
lib/matplotlib/rcsetup.py

Supersedes https://github.com/matplotlib/matplotlib/pull/16417.

Remove the deprecated rcParams["datapath"].

---

examples/event_handling/trifinder_event_demo.py
examples/lines_bars_and_markers/psd_demo.py
examples/misc/custom_projection.py
examples/scales/symlog_demo.py
examples/shapes_and_collections/ellipse_demo.py
examples/text_labels_and_annotations/multiline.py
examples/userdemo/simple_legend01.py

Replaced use of `pyplot` calls with their OO equivalents in a few examples.  Presumably they were missed in previous attempts to do this.  In turn, I do not guarantee that I haven't missed some either :smile:

Replace use of pyplot with OO api in some examples

---

lib/matplotlib/__init__.py
lib/matplotlib/mlab.py

Single colon make the full block to be seen as a comment for sphinx.
And make proper underline length.

Doc: Minor formatting

---

doc/api/next_api_changes/deprecations/19341-TH.rst
lib/matplotlib/lines.py
lib/matplotlib/markers.py
lib/matplotlib/tests/test_marker.py

as discussed in yesterdays dev call.
See also https://github.com/matplotlib/matplotlib/pull/17850#issuecomment-763195168.

MarkerStyle is considered immutable

---

lib/matplotlib/animation.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_svg.py
lib/matplotlib/bezier.py
lib/matplotlib/contour.py
lib/matplotlib/figure.py
lib/matplotlib/lines.py
lib/matplotlib/tight_layout.py
lib/matplotlib/type1font.py
tutorials/provisional/mosaic.py

The uppercase generics (List, etc.) are deprecated by PEP 585 in favor
of the lowercase ones (which also look nicer IMO).

Switch to documenting generic collections in lowercase.

---

azure-pipelines.yml

Tweaks what jobs we run on azure.

CI: remove win prerelease azure + add py39

---

doc/devel/contributing.rst
doc/devel/index.rst

At least I think they are improvements. I tried to go through the process as if I didn't know and was starting by clicking the contributing tab. These changes address the areas where I felt I would have gotten stuck or knocked off course.
See also: https://discourse.matplotlib.org/t/contributor-onboarding-retention/21714
I tried to make granular commits and leave explanations in the body of the commit messages.

Improvements to Docs for new contributors

---

.gitignore

Hi,
This PR ignores coverage files generated per python files
This avoid to have the following `git status` output
```
Untracked files:
(use "git add <file>..." to include in what will be committed)
lib/matplotlib/__init__.py,cover
lib/matplotlib/_animation_data.py,cover
lib/matplotlib/_api/__init__.py,cover
lib/matplotlib/_api/deprecation.py,cover
lib/matplotlib/_cm.py,cover
lib/matplotlib/_cm_listed.py,cover
lib/matplotlib/_color_data.py,cover
lib/matplotlib/_constrained_layout.py,cover
lib/matplotlib/_enums.py,cover
lib/matplotlib/_internal_utils.py,cover
lib/matplotlib/_layoutbox.py,cover
lib/matplotlib/_layoutgrid.py,cover
lib/matplotlib/_mathtext.py,cover
[...]
```

Ignore files from annotate coverage reports

---

lib/matplotlib/figure.py

Document how to handle #18049.

Add note on writing binary formats to stdout using savefig()

---

lib/matplotlib/artist.py
lib/matplotlib/axes/_base.py
lib/matplotlib/figure.py
tutorials/advanced/blitting.py

Clarify the animated property and reword blitting tutorial a bit

---

examples/text_labels_and_annotations/autowrap.py
lib/matplotlib/text.py

Add note on interaction between text wrapping and bbox_inches='tight'

---

examples/user_interfaces/README.txt
tutorials/introductory/sample_plots.py
tutorials/introductory/usage.py

Also reorder mentioned backends by fallback order (which is effectively
our preference order), except that the OS-specific macos backend goes
last.
Capitalization follows the docs of each project.

Replace references to pygtk by pygobject in docs.

---

lib/matplotlib/backends/qt_compat.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/pyplot.py
lib/matplotlib/testing/conftest.py

sys.modules entries can be explicitly set to None to block imports, so
the `name in sys.modules` check should rather be written
`sys.modules.get(name)` (... is not None).
While we're at it, disentangle a bit install_repl_displayhook to exit
early if `not sys.modules.get("IPython") or not get_ipython()`, which
avoids having to throw a local NotIPython exception just to `goto end`.
(Also note that the import of `backend2gui` should not throw an
ImportError, as that mapping has been around since <2011).
xref #19597 (I intentionally left out the case handled by #19597 to avoid a conflict)

Handle None entries in sys.modules.

---

lib/matplotlib/figure.py

I'd guess more people directly use the `.axes` property, so make that
handle the docstring as well, and just copy it for `get_axes`.  (Also, I
think reusing the property's docstring in the method reads better than
the other way round.)

Dedupe docstrings of Figure.{get_axes,axes}.

---

lib/matplotlib/font_manager.py
lib/matplotlib/tests/test_font_manager.py

This prevents segfaults when multiple threads try to manipulate the
FT2Font object simultaneously.
closes #19560

FIX: make the cache in font_manager._get_font keyed by thread id

---

doc/devel/contributing.rst

Fixes https://github.com/matplotlib/matplotlib/issues/19594

Fix CoC link

---

.github/workflows/cibuildwheel.yml

From v1.8.0, cibuildwheel allows to build non-native architectures using CIBW_ARCH_LINUX. See https://cibuildwheel.readthedocs.io/en/stable/options/#archs for more details.
Also, use numpy v1.19. aarch64 wheels are available for it. Cuts down on time spent building aarch64 numpy wheels under emulation.
Use cibuildwheel option to build aarch64 wheels.

Build aarch64 wheels

---

lib/matplotlib/backends/backend_cairo.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/testing/jpl_units/Duration.py
lib/matplotlib/testing/jpl_units/Epoch.py
lib/matplotlib/testing/jpl_units/UnitDbl.py

This is shorter and yields better signatures on the resulting methods
(as partialmethod forwards to the signature of the underlying helper).
For example, the signature of FigureCanvasCairo.print_ps is now
`(self, fobj, *, orientation='portrait')` rather than
`(self, fobj, *args, **kwargs)`.
For the cairo/wx print_foos, also note that we can delete the `*args` in
the various print methods with no deprecation as they were not supported
to start with (the underlying call to `_save` and `_print_image` would
have raised if such `*args` were passed in).

Dedupe various method implementations using functools.partialmethod.

---

.github/ISSUE_TEMPLATE/documentation.md

It is now the same as in `bug_report.md`.

Fix colon placement in issue template.

---

matplotlibrc.template

Small style fixes to matplotlibrc.template.

---

lib/matplotlib/dates.py

In particular, it is not necessary to create a FuncFormatter; a plain
callable works fine.

Reword AutoDateFormatter docs.

---

lib/matplotlib/backends/backend_cairo.py
lib/matplotlib/backends/backend_nbagg.py
lib/matplotlib/backends/backend_pdf.py

(The authorship formulation for the pdf backend matches the one for
cairo.)

Minor backend docstring fixes.

---

lib/matplotlib/cbook/__init__.py

They are unused since the replacement of cbook.dedent by
inspect.cleandoc.

Remove unused _find_dedent_regex & _dedent_regex.

---

lib/matplotlib/backends/backend_pgf.py

Using "\n".join to keep things properly indented should have negligible
overhead compared to the subsequent tex subprocess invocation.  Also,
generating TeX strings (with a lot of curly braces) is one of the few
cases where old-style (%) formatting is more legible than .format
formatting.
(The papersize option of geometry is documented as equivalent to
{paperwidth,paperheight}).

Cleanup string formatting in backend_pgf.

---

.appveyor.yml
.circleci/config.yml
.github/workflows/tests.yml
doc/devel/development_setup.rst
doc/faq/installing_faq.rst
doc/faq/troubleshooting_faq.rst

- Fixes all the python -mpip typos found in the repository …

Fixed python -mpip typo

---

INSTALL.rst

DOC: fix minor typo from 19725

---

lib/matplotlib/backends/backend_svg.py

Replace _get_clip (which just returns a clip id) by _get_clip_attrs,
which also takes care of formatting it and preparing to pass it as as
xml attribute.

Factor out clip-path attr handling in backend_svg.

---

doc/_templates/layout.html
doc/api/index.rst

This yields a much quicker ingress to the useful parts of the API page, and a quick example to orient the reader...

DOC: simplify API index

---

doc/_static/mpl.css
doc/devel/documenting_mpl.rst
examples/lines_bars_and_markers/fill.py

Closes #19232.
- Description.
- One example how this looks like.
I will create a good first issue to migrate all existing reference blocks to the new format once this PR is merged.

Document how to create sphinx-gallery references to examples

---

doc/api/next_api_changes/removals/XXXXX-AL.rst

It's been integrated into the 3.4 release notes (https://matplotlib.org/stable/api/api_changes.html#rcparams).

Remove outdated api changes notes.

---

doc/sphinxext/custom_roles.py
tutorials/introductory/usage.py

Closes https://github.com/matplotlib/matplotlib/issues/19813

Clarify default backend selection doc.

---

lib/matplotlib/__init__.py
lib/matplotlib/mpl-data/matplotlibrc
lib/matplotlib/rcsetup.py
setup.py

See comments in `matplotlib/__init__.py` and `setup.py`.  Test
by updating your local repo to this branch and `pip install
git+file:///path/to/repo` (doing so with the current master throws
`ValueError: Key backend: '' is not a valid value for backend`.
Closes #19848, see #19854 for an alternate approach, but see also https://github.com/matplotlib/matplotlib/pull/19854#issuecomment-812717296.

Correct handle default backend.

---

doc/faq/installing_faq.rst

This does not contain information that is not already present in the
main installing docs.

Remove FAQ Installing - Linux notes

---

doc/Makefile

`make clean` should also remove the `source/plot_types` directory (analogous to removing `source/gallery` and `source/tutorials`

DOC/MNT fix make clean for plot_types

---

lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_axes.py

Implement ArtistList.__[r]add__.

---

doc/faq/howto_faq.rst
examples/misc/zorder_demo.py

One explanatory sentence and a reference to the detailed example are
enough.

Shorten "how-to draw order"

---

lib/matplotlib/widgets.py

The cursor used to be black but the default of vlines color now matches
`rcParams["lines.color"]` (blue) (#16953), so change that back to black.  Setting
the linewidth to 1 also looks a bit nicer (than the thicker default
linewidth).
before:
after:
(Technically changing the color is a bugfix and whereas the linewidth is a new "feature", but splitting this into two PRs seems overkill.  Also there's no tests whatsoever for TextBox right now...)

Fix textbox cursor color, set its linewidth.

---

lib/matplotlib/image.py

It's been around for too long to really be deprecatable.
Closes https://github.com/matplotlib/matplotlib/issues/19907.

Discourage use of imread & improve its docs.

---

doc/api/projections_api.rst
doc/missing-references.json

... at a lower level, together with projections.polar.

Include projections.geo in api docs.

---

extern/ttconv/pprdrv.h
extern/ttconv/pprdrv_tt.cpp
extern/ttconv/pprdrv_tt2.cpp

get_pdf_charprocs and TTDictionaryCallback were added in 7a10b51.

Remove now unused patches to ttconv.

---

lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

Fixes https://github.com/matplotlib/matplotlib/issues/19960. Added a test, and did some minor readability updates to surrounding code.

Fix valinit argument to RangeSlider

---

lib/matplotlib/figure.py
lib/matplotlib/pyplot.py

Follow on to #19964 to note the order in the docstring
@QuLogic merged the PR about 40s before I pushed!

DOC: add note about axes order to docstring

---

plot_types/stats/README.rst

`plot_type/stats/README.rst` had a heading level that was one higher than its peers.  Demoted it here...

DOC: fix heading level for plot_types/stats

---

doc/devel/development_setup.rst
tutorials/text/usetex.py

- Capitalization, spacing.
- Make bullet points consistently not end with period.

Small fixes to latex-related docs.

---

lib/matplotlib/stackplot.py

Clarify docs for stackplot.

---

lib/mpl_toolkits/axes_grid1/axes_divider.py

HBoxDivider.new_locator doesn't have ny, ny1 parameters.
The HBoxDivider.locate and VBoxDivider.locate docstrings are just
copy-pasted from the parent one.
Clarify some non-trivial calculations.

Cleanup axes_divider docstrings, and detail calculations.

---

doc/api/next_api_changes/behavior/20077-TH.rst
lib/matplotlib/artist.py

Expire Artist.set() property reordering

---

examples/lines_bars_and_markers/filled_step.py
lib/matplotlib/_color_data.py
lib/matplotlib/artist.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_svg.py
lib/matplotlib/tests/test_rcparams.py
lib/matplotlib/tests/test_style.py
tutorials/colors/colormaps.py

... and simplify related code.

Remove some usages of OrderedDict

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

Fix bar_label for bars with nan values

---

lib/matplotlib/__init__.py
lib/matplotlib/font_manager.py
lib/matplotlib/tests/test_matplotlib.py

(as long as MPLCONFIGDIR is set).
Closes https://github.com/matplotlib/matplotlib/issues/20122.

Ensure that Matplotlib is importable even if there's no HOME.

---

tutorials/toolkits/axes_grid.py

Probably still needs further work (not in this PR), but hopefully an
improvement over the current state...

Copy-edit axes_grid tutorial.

---

lib/matplotlib/tight_layout.py

Directly operating on slice pairs (with half-open semantics, and
carrying row and column info separately) is much nicer than switching
back and forth between flattened indices and row/column, and having a
bunch of +1's.
The auto_adjust_subplotpars compat wrapper needs an adapter, but it'll
go away after the deprecation elapses.

Switch _auto_adjust_subplotpars to take rowspan/colspan as input.

---

doc/index.rst

Fixed the link to ggplot. The site has been moved from http://ggplot.yhathq.com to https://yhat.github.io/ggpy/.

Fix broken link to ggplot in docs

---

doc/api/next_api_changes/behavior/20150-TAC.rst
doc/api/next_api_changes/behavior/99999-tac.rst
lib/matplotlib/figure.py
lib/matplotlib/pyplot.py
tutorials/provisional/mosaic.py

This gives us the option to in the future combine *tight_layout* and *constrained_layout* into a single *layout* kwarg.
Even though this is provisional so I do not think we need to do a deprecation cycle, we may want to hold adding the layout kwarg until 3.6?
I took this opportunity to update the tutorial to use `fig.subfigures()` as well!

Rename mosaic layout

---

doc/api/next_api_changes/behavior/20150-TAC.rst
lib/matplotlib/figure.py
lib/matplotlib/pyplot.py
tutorials/provisional/mosaic.py

Merge pull request #20150 from tacaswell/rename_mosaic_layout
Rename mosaic layout

Backport PR #20150 on branch v3.4.x

---

doc/api/next_api_changes/deprecations/18346-TH.rst
examples/ticks_and_spines/date_demo_convert.py
examples/ticks_and_spines/date_demo_rrule.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/dates.py

Soft-deprecate Axes.plot_date()

---

lib/matplotlib/patches.py

... by moving {begin,end}arrow and fill{begin,end} to class attributes.

Shorten Curve arrowstyle implementations.

---

lib/matplotlib/tests/test_figure.py

These were not tested at all previously.

Add tests for ginput and waitforbuttonpress.

---

lib/mpl_toolkits/axisartist/floating_axes.py

- _axes_class_floating is just the `super(FloatingAxesBase, self)` class
(per its definition in floatingaxes_class_factory), so we can just use
super-calls instead of explicitly referring to it (both in `__init__`
and in `cla`); and then we can just delete _axes_class_floating.
- Combine _gen_axes_patch into a single line (it's not as if the
intermediary variable names were particularly helpful).
- In cla(), the super() axes patch is already not in the draw tree
(it's FloatingAxesBase._gen_axes_patch() which is there, so no need
to adjust its visibility); ~~its figure and transform are already set
by super().cla() as well so no need to adjust them~~.  Finally,
_original_patch is never used anywhere, so delete it.

Small simplifications to FloatingAxesBase.

---

setup.py

This was noticed while [attempting Ubuntu 20.04 builds](https://github.com/matplotlib/matplotlib/pull/20154#issuecomment-833124753), but actually affects any system with new gcc. I was able to reproduce on Fedora by setting `CPPFLAGS=--coverage`.
The problem is that gcc will save the object file name and the time it was created, and warn about producing coverage if those differ. This is the case for our extensions, because we share some source files between them, and setuptools builds object files in the same directory.
The fix is simply to override the temporary directory while building a single extension to some path that is unique. Additionally, when generating coverage, we need to tell gcc to save absolute paths (for CI.)
You can test this by compiling with `CPPFLAGS=--coverage` in …

Fix C coverage

---

doc/devel/index.rst
doc/devel/style_guide.rst

- Added Documentation Style guide from #19183
- Included reference in TOC tree for developers-guide-index .rst file

Documentation Style Guide for contributors

---

doc/devel/contributing.rst

... or rather, add a mention in the docs so that we can link to it when
reviewing PRs.
Given that the section about pyflakes got removed, also remove the
remaining mention about coverage in that list (in fact, it should be
pytest-cov instead; that part really belongs in testing.rst anyways; and
we don't really enforce the "at least 70% rule"...).
(See https://github.com/matplotlib/matplotlib/pull/20242/files#r633145582 (thanks @Illviljan for pointing out the problems with math expressions) and https://github.com/matplotlib/matplotlib/issues/18796#issuecomment-716865805.)

Explicitly reject black autoformatting.

---

lib/mpl_toolkits/axisartist/floating_axes.py
lib/mpl_toolkits/axisartist/grid_finder.py
lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py

axisartist can generate "slanted" or "curved" axes defined using either
a custom Transform, or a custom pair of callables (forward, backward)
which define the Transform.  Instead of repeatedly testing the two cases
in `transform_xy` and `inv_transform_xy`, just wrap the
pair-of-callables into a custom Transform subclass (which should
probably not be moved to the main library, as it uses the transposed
convention compared to the usual one), and expose it through a getter.
This allows later combining this transform using "standard" transform
addition (and get benefits such as single multiplication of matrices
in affine transforms, exact cancellation of inverses, or (later) more
accurate transforming of arcs in polar transforms), instead of having to
manually call successive transforms.  See …

Move axisartist towards using standard Transforms.

---

examples/user_interfaces/embedding_in_tk_sgskip.py

From the example in https://matplotlib.org/stable/gallery/user_interfaces/embedding_in_tk_sgskip.html it is not clear how to update plots in interactive user interfaces (see https://github.com/matplotlib/matplotlib/issues/20159). This PR extends the example with an *update* button which shows how to update the plot in the `FigureCanvasTkAgg`.
- [ N/A] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).

Update Axes showcase in "Embedding in Tk" example

---

doc/api/next_api_changes/removals/20245-GL.rst
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_agg.py
lib/matplotlib/collections.py
src/_backend_agg.h
src/_backend_agg_basic_types.h
src/_backend_agg_wrapper.cpp
src/_path.h
src/_path_wrapper.cpp
src/py_converters.cpp
src/py_converters.h

This removes the 3.3 deprecation of `offset_position` from the Collection class.

MAINT: Removing deprecated `offset_position` from Collection

---

doc/api/next_api_changes/deprecations/15604-AL.rst
lib/matplotlib/axes/_axes.py

Deprecate auto-removal of grid by pcolor/pcolormesh.

---

lib/matplotlib/testing/decorators.py

It's much easier to just call `pytest.skip` from within the test
function than trying to apply a pytest mark.

Simplify handling of uncomparable formats in tests.

---

tutorials/text/mathtext.py
tutorials/text/pgf.py
tutorials/text/usetex.py

Capitalization, markup, removal of uninformative subtitle/figure
caption.

Tiny fixes to mathtext/usetex tutorials.

---

doc/api/index.rst

- Remove extra indent of bullet list; remove trailing spaces.
- Link using module references.

Small markup fixes in api docs.

---

lib/matplotlib/text.py

This makes it clearer that `textobj` is actually the same object as
`self`.

Replace text._wrap_text by _cm_set().

---

lib/matplotlib/quiver.py

Clarify the effect of PolygonCollection properties on Quiver

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/figure.py

- Add `legend(handles=handles)`
- Reorder such that the discouraged signature `legend(labels)` is last
- Minor text changes
Closes #20213

Document legend(handles=handles) signature

---

lib/matplotlib/colors.py
lib/matplotlib/legend_handler.py
tutorials/colors/colors.py

- Deduplicate color format specification, plus minor clarifications in the remaining table
- Reworded a note on legend handlers (I thought it's small enough so that we can handle it inside this PR).

Deduplicate color format specification

---

README.rst

this helps make sure that people contributing to this repo are aware metrics will be gethered as part of the study over the next twelve months :)
- [n/a] API …

Add research notice

---

lib/matplotlib/mpl-data/matplotlibrc

- Move hinting/kerning/antialiasing out of the LaTeX section (it doesn't
belong there.
- Remove suggestion to "inquire at the mailing list" (requests can just
go to the bug tracker like any other new feature).

Reorganize a bit text-related rcs in matplotlibrc.

---

examples/user_interfaces/canvasagg.py

In particular, show how Pillow can be used to save images in formats not
directly supported by Matplotlib.  Also directly convert the buffer to
an array (with only brief, in-passing mention of memoryviews), as
memoryviews are rather technical.
See https://discourse.matplotlib.org/t/create-a-bmp-from-pyplot/22099.
Perhaps https://matplotlib.org/stable/gallery/misc/agg_buffer.html and https://matplotlib.org/stable/gallery/misc/agg_buffer_to_array.html could be merged into this example too?

Small improvements to canvasagg example.

---

examples/axes_grid1/demo_colorbar_of_inset_axes.py
examples/axes_grid1/demo_edge_colorbar.py
examples/axes_grid1/demo_fixed_size_axes.py
examples/axes_grid1/demo_imagegrid_aspect.py
examples/axisartist/demo_axis_direction.py
examples/axisartist/demo_floating_axis.py
examples/subplots_axes_and_figures/subplot_demo.py
examples/text_labels_and_annotations/demo_annotation_box.py

Cleanup some examples titles & texts.

---

tutorials/toolkits/axisartist.py
tutorials/toolkits/mplot3d.py

We can have figure captions, but the ones removed here provide no
information...

Remove non-informative figure captions.

---

doc/users/prev_whats_new/whats_new_0.99.rst
doc/users/prev_whats_new/whats_new_1.1.rst
tutorials/introductory/sample_plots.py
tutorials/toolkits/mplot3d.py

It's not "special" and doesn't warrant its own section; we can just
mention that in passing.
Also remove the "Getting started" section, which is by itself at its
level (see TOC at https://matplotlib.org/devdocs/tutorials/toolkits/mplot3d.html).

Remove separate section for support of 3d subplots.

---

examples/text_labels_and_annotations/arrow_demo.py

- Skip unnecessary numbered_bases_to_rates, lettered_bases_to_rates.
- Don't use pyplot, but pass axes to make_arrow_plot.
- letter colors only depend on the start point, not the end point.
- Don't hard-code coordinates of arrows, but compute them from the
letter coordinates.
- Only include one dataset.
- Directly show all three possibilities (length, width, alpha).
- head_starts_at_zero=True resulted in incorrect alignment e.g. when
calling `arrow_demo.py realistic length` previously; one should use
the default value of head_starts_at_zero=False.
Before, when called with arguments `realistic length` (note the completely incorrect alignment):
After:

Cleanup arrow_demo.

---

lib/matplotlib/tests/test_path.py
src/_path.h

Closes #20328
What I did:
- Implemented the code to solve the issue
- Added tests for the cases mentioned in #20328
I will wait for the automated checks to pass before asking for a review.
Edit: ready for review.

Pathing issue

---

examples/text_labels_and_annotations/fancyarrow_demo.py
lib/matplotlib/patches.py

Don't alphabetically sort the arrowstyles; the order of definition in
the source makes more sense.  (The `sorted` call was necessary back when
dicts were unsorted.)  Also move the definition of BracketAB after
BracketA and BracketB, for consistency with the other arrow styles.
Various small fixes (making the axis invisible is already done by
frameon=False, no need to use mathtext).
before:
after:

Improve fancyarrow_demo.

---

lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/gridspec.py
lib/matplotlib/markers.py
tutorials/intermediate/gridspec.py

Small doc cleanups.

---

examples/mplot3d/polys3d.py

Mostly to have a nicer looking image.

Improve example for 3D polygons

---

lib/matplotlib/backends/backend_ps.py

Make the debugPS functionality more systematic.
Remove the command parameter to _draw_ps, which is never used, and make
fill and stroke kwonly (as they always are).
Small misc. cleanups.

Small cleanups to backend_ps.

---

plot_types/README.rst
plot_types/arrays/README.rst
plot_types/arrays/contourf.py
plot_types/arrays/imshow.py
plot_types/arrays/pcolormesh.py
plot_types/arrays/quiver.py
plot_types/arrays/streamplot.py
plot_types/basic/README.rst
plot_types/basic/bar.py
plot_types/basic/pie.py
plot_types/basic/plot.py
plot_types/basic/scatter_plot.py
plot_types/basic/stem.py
plot_types/basic/step.py
plot_types/stats/README.rst
plot_types/stats/barbs.py
plot_types/stats/boxplot_plot.py
plot_types/stats/errorbar_plot.py
plot_types/stats/eventplot.py
plot_types/stats/hexbin.py
plot_types/stats/hist2d.py
plot_types/stats/hist_plot.py
plot_types/stats/violin.py
plot_types/unstructured/tricontour.py
plot_types/unstructured/tripcolor.py
plot_types/unstructured/triplot.py

- Do not show a partial signature in the title. Something like
`contour[f]([X, Y], Z, [levels=], ...)` is rather confusing.
- Add a link to the docstring of the respective function.
- Minor text cleanups on the gallery page.

Cleanup plot types docs

---

examples/statistics/hist.py

- Rename x, y variable names to `dist1`, `dist2` (dist is short for distribution) - fixes https://github.com/matplotlib/matplotlib/issues/20379
- Use numpy's preferred method of random number generation. This also makes the code more readable as the generation function is now `standard_normal` instead of `randn`.
I think this is a minor improvement to the example, but doesn't address the larger suggestions in https://github.com/matplotlib/matplotlib/issues/20379#issuecomment-855901412
- [ n/a New features are documented, with examples if plot related.
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow …

Rename data variables in histogram example.

---

lib/matplotlib/tests/tinypages/conf.py

When tests are being run it is already necessary that the version of
matplotlib being tested is the one in sys.path, so we don't need to
manipulate sys.path additionally.

tinypages/conf.py doesn't need to manipulate sys.path.

---

lib/matplotlib/testing/compare.py

Search the GS output stream for either "GS<" or "GS>" explicitly rather
than any "GS", in order to prevent the code from wrongly matching stray
"GS".  This fixes a recent test regression on Gentoo where the following
output seems to have been wrongly matched:
**** Error 'gs' ignored -- ExtGState missing from Resources.
^^
Fixes #20472

_GSConverter: handle stray 'GS' in output gracefully

---

lib/matplotlib/contour.py

I think the Z matrix shape is flipped -- it should maybe be (N,M)?

Fix shape of Z in contour docs

---

lib/matplotlib/axis.py
lib/matplotlib/backends/web_backend/js/nbagg_mpl.js
lib/matplotlib/figure.py
lib/matplotlib/markers.py
lib/matplotlib/offsetbox.py

These are all overwritten later on without being read.

Remove dead code from LGTM alerts.

---

tutorials/text/annotations.py

Turning things into a comment makes things more homogeneous between the
first section and the subsequent ones.
The figure titles are not particularly meaningful.
Split out of #20531.

Make most of annotation tutorial a comment, and remove figure titles.

---

plot_types/arrays/contourf.py
plot_types/arrays/imshow.py
plot_types/arrays/pcolormesh.py
plot_types/arrays/quiver.py
plot_types/basic/bar.py
plot_types/basic/pie.py
plot_types/basic/plot.py
plot_types/basic/scatter_plot.py
plot_types/basic/stem.py
plot_types/basic/step.py
plot_types/stats/barbs.py
plot_types/stats/errorbar_plot.py
plot_types/stats/eventplot.py
plot_types/stats/hexbin.py
plot_types/stats/hist2d.py
plot_types/stats/hist_plot.py
plot_types/stats/violin.py
plot_types/unstructured/tricontour.py
plot_types/unstructured/tripcolor.py
plot_types/unstructured/triplot.py

Some simplifications and more standard code style.

Cleanup plot types

---

lib/matplotlib/widgets.py

Follow up to #20113.
- IMHO two parameters were not named clearly, so renaming
- `line_props` -> `handle_props`
- `maxdist` -> `handle_grab_distance`
- Minor improvements:
- document default for `buttons`
- document default for `drag_from_anywhere`
- properly document `onselect`
Heads up: I also see a naming issue with `interactive` (see https://github.com/matplotlib/matplotlib/pull/20113#discussion_r661819516), but it's unclear if we should go back to the old `span_stay` or a different new name. To be discussed in tomorrows dev call. This can be addressed separately from this PR.

Rename recently introduced parameters in SpanSelector

---

lib/matplotlib/__init__.py

Per discussion at https://gitter.im/matplotlib/matplotlib?at=60e1fec28c12474d8ceab2a6.

Clarify allowable backend switches in matplotlib.use().

---

doc/api/next_api_changes.rst
doc/devel/coding_guide.rst
doc/devel/color_changes.rst
doc/devel/contributing.rst
doc/devel/min_dep_policy.rst
doc/devel/release_guide.rst
doc/devel/style_guide.rst
doc/devel/triage.rst
doc/faq/environment_variables_faq.rst
doc/resources/index.rst
doc/users/github_stats.rst
doc/users/index.rst
doc/users/interactive.rst
doc/users/interactive_guide.rst
doc/users/license.rst
tools/github_stats.py

Only use a capital letter for the first word (and special names).

Consistent capitalization of section headers

---

lib/matplotlib/backends/backend_svg.py

Splitting the implementation in two parts doesn't buy us anything, and
merging them makes it easier to have an explicit signature on print_svg.

Inline _print_svg into its only call site (print_svg).

---

lib/matplotlib/axes/_subplots.py

Closes #19982 #19938
The current implementation of figbox only gets the subplotspec position, but the user can modify that.  
Tested with 
```
import matplotlib.pylab as plt
from matplotlib.transforms import BboxTransformFrom
box = np.array([0.1,0.2,0.3,0.4])
ax.set_position(box)
print(ax.get_position())
print(ax.figbox)
```
Now gives identical output to v3.3.4

FIX: fix figbox deprecation

---

doc/conf.py

The build date of the software shouldn't really have any bearing on
the copyright dates, but by respecting SOURCE_DATE_EPOCH, it at least
limits this to the last time something in the source was changed.
https://reproducible-builds.org/specs/source-date-epoch/

doc/conf.py: if set, use SOURCE_DATE_EPOCH to set copyright year.

---

doc/users/fonts.rst
doc/users/index.rst

A new entry to User Guide - Fonts! (modelled after [interactive_guide](https://matplotlib.org/stable/users/interactive_guide.html))
This document would contain everything Matplotlib knows about fonts, and is bootstrapped with the different types of fonts and font subsetting with this PR. This guide would especially be useful for issues related to font subsetting. (for eg., https://github.com/theislab/scanpy/issues/1720)
Also the first time we're mentioning anything about `'fonttypes'` in docs.
Related issues: https://github.com/matplotlib/matplotlib/issues/127

[Doc] Font Types and Font Subsetting

---

examples/axes_grid1/make_room_for_ylabel_using_axesgrid.py
examples/axes_grid1/simple_axisline4.py
examples/axisartist/demo_ticklabel_alignment.py
examples/images_contours_and_fields/image_annotated_heatmap.py
examples/lines_bars_and_markers/bar_label_demo.py
examples/lines_bars_and_markers/barchart.py
examples/lines_bars_and_markers/barh.py
examples/lines_bars_and_markers/broken_barh.py
examples/lines_bars_and_markers/hat_graph.py
examples/pyplots/auto_subplots_adjust.py
examples/scales/log_bar.py
examples/showcase/integral.py
examples/specialty_plots/mri_with_eeg.py
examples/statistics/barchart_demo.py
examples/statistics/boxplot_vs_violin.py
examples/statistics/customized_violin.py
examples/statistics/multiple_histograms_side_by_side.py
examples/style_sheets/ggplot.py
examples/style_sheets/style_sheets_reference.py
examples/text_labels_and_annotations/multiline.py
examples/ticks_and_spines/spines_bounds.py
examples/units/bar_unit_demo.py
tutorials/toolkits/axes_grid.py

Split out of #20631 for easier review.

Use set_xticks(ticks, labels) instead of a separate set_xticklabels()

---

examples/axes_grid1/demo_axes_divider.py
examples/axes_grid1/inset_locator_demo2.py
examples/event_handling/ginput_manual_clabel_sgskip.py
examples/images_contours_and_fields/contour_demo.py
examples/subplots_axes_and_figures/shared_axis_demo.py
examples/ticks_and_spines/date_precision_and_epochs.py
lib/matplotlib/tests/test_polar.py

We have better ways for achieving the same.

Remove some usages of plt.setp()

---

doc/faq/environment_variables_faq.rst
tutorials/introductory/usage.py

$DISPLAY (or $WAYLAND_DISPLAY) is not the only thing we consider; we
also check that one can indeed connect to the display server (#17396).  (But
there's no point of writing a full explanation of the Linux display
protocols; there's much better docs for that elsewhere online.)

Reword docs about fallbacks on headless linux.

---

examples/statistics/barchart_demo.py

Simplify barchart_demo

---

lib/matplotlib/contour.py

This just adds a short note about the contouring algorithm we use with a link to the Wikipedia article.   I'm not sure if we usually reference the source code like this, but for now it is the only place with the details.  (I avoid explicitly linking the source because it is too long and will make PEP8 made).

DOC: add note about contouring algorithm

---

examples/userdemo/colormap_interactive_adjustment.py

Added an example to the gallery for discussion regarding #19515.  All that needs to happen in each event is to modify the colorbar norm vmin and vmax, although the particular interactivity that was desired in #19515 would require a little more creativity in the callbacks.
Hoping for feedback as to: 
1. whether to actually include in gallery
2. style of new gallery page
3. code review

add interactive colorbar example to gallery

---

lib/matplotlib/lines.py
lib/matplotlib/tests/test_lines.py

... except for `markevery=<float>` or `(<float>, <float>)` which is a
spec relative to the axes size (keeping handling of that specific case
into _mark_every_path).
The main use case is the monolithic Line2D legend handler proposed in #11358, in combination with figlegend (https://github.com/matplotlib/matplotlib/pull/11358#issuecomment-393753340, https://github.com/matplotlib/matplotlib/pull/11358#discussion_r194247428): in that case, a line+singlemarker legend entry would be represented using `markevery=[1]` (which there isn't really a reason not to support).

Support markevery on figure-level lines.

---

lib/matplotlib/tests/test_axes.py

The change is imperceptible, so just increase the tolerance.
Fixes #20617.

Fix tests with Inkscape 1.1.

---

doc/index.rst

Start on a landing page.  
Closes  #20735

DOC: new index page

---

doc/resources/index.rst

Hi,
I've recently been invited to write this [blogpost](https://matplotlib.org/matplotblog/posts/python-graph-gallery.com/) on the matplotblog page.
After some discussion with the matplotlib twitter account maintainer it sounds like the python graph gallery could be a great fit for your external resources page, so here is the PR.
Please tell me if that looks reasonable to you!
Best,

Add new external resource: Python Graph Gallery

---

examples/widgets/mouse_cursor.py

This makes it easy to test that cursors are working in a new backend (or if we add new cursors).
I'm not sure if it belongs in the `widgets` section.

Add an example showing alternate mouse cursors.

---

lib/matplotlib/backends/backend_ps.py

_num_to_str is never used by itself and can be folded into the plural
version.  It is never called with a str argument so that check can be
removed.  Exact integer arguments can also be directly handled by the
floating-point handling path (Technically, this will cause a rounding
error for integers greater than `2**53`, but the PostScript standard
only supports 32-bit integers anyways); the performance cost should be
negligible (in fact, possibly more than compensated by the removal of
the instance check in the common case of float arguments).

Simplify backend_ps._nums_to_str.

---

examples/showcase/bachelors_degrees_by_gender.py

add doc-link to dufte

---

.circleci/config.yml

[1] https://circleci.com/docs/2.0/circleci-images/#next-gen-language-images

circle: Switch to next-gen image.

---

doc/index.rst

Addresses #20762 of adding back the external resources link to the devdoc landing page.

Add external resources to devdoc landing page

---

lib/matplotlib/__init__.py
lib/matplotlib/style/core.py
lib/matplotlib/textpath.py
tutorials/intermediate/constrainedlayout_guide.py
tutorials/introductory/customizing.py

Closes #20800
The tutorial [Customizing Matplotlib with style sheets and rcParams](https://matplotlib.org/stable/tutorials/introductory/customizing.html#sphx-glr-tutorials-introductory-customizing-py) was not clear about what rcParams can be set in style sheets. The blacklist of rcParams that cannot be set in style sheets is now documented in the docstring of `matplotlib.style.use` and the tutorial links to this blacklist.

Clarify tutorial "Customizing Matplotlib with style sheets and rcParams"

---

doc/resources/index.rst

Added an additional external resource (book chapters) to the [External Resources](https://matplotlib.org/stable/resources/index.html) page.

Add additional external resource.

---

lib/matplotlib/tests/test_backends_interactive.py

Otherwise, e.g., `PYTHONPATH` is not available.

Ensure full environment is passed to headless test.

---

lib/matplotlib/animation.py

Improve deleted Animation warning

---

doc/users/release_notes.rst

Fix missorted changelog entry.

---

plot_types/basic/pie.py
plot_types/basic/plot.py
plot_types/basic/scatter_plot.py

Fix variable capitalization in plot types headings

---

lib/matplotlib/axes/_base.py

DOC Use 'Axes' instead of 'axes' in axes._base.py

---

doc/api/next_api_changes/deprecations/20995-AL.rst
lib/matplotlib/backends/backend_gtk3.py

It is nicer to just define them at the point of use rather than ~400
lines later.

Deprecate some backend_gtk3 helper globals.

---

lib/matplotlib/colors.py

added numpydoc style documentation of parameters to the colors.to_hex function

[Doc] colors.to_hex input & output

---

lib/matplotlib/legend.py

The indirection with `locals()` and `setattr()` is obscuring more than it's worth.

Simplify setting Legend attributes

---

doc/_static/mpl.css
doc/_templates/cheatsheet_sidebar.html
doc/_templates/donate_sidebar.html

Fix layout of sidebar entries

---

lib/matplotlib/__init__.py

At the time of writing (latest master just installed), the installed and runtime version (from a git repository) are:
```python
>>> import importlib_metadata
>>> importlib_metadata.version('matplotlib')
'3.5.0.dev1801+g298e92f6bf'
```
and
```python
>>> import matplotlib
>>> matplotlib.__version__
'3.4.2.post1801+g298e92f6bf'
```
With this PR, the runtime version is:
```python
>>> import matplotlib
>>> matplotlib.__version__
'3.5.0.dev1802+g3593a0c333'
```
Relevant previous PR on this topic: https://github.com/matplotlib/matplotlib/pull/18869, https://github.com/matplotlib/matplotlib/pull/20369,  …

Use release-branch version scheme 

---

doc/_templates/mpl_nav_bar.html
doc/index.rst
doc/users/backmatter.rst
doc/users/index.rst
doc/users/release_notes_next.rst

Fix capitalizations

---

examples/images_contours_and_fields/colormap_interactive_adjustment.py
examples/images_contours_and_fields/colormap_normalizations.py
examples/images_contours_and_fields/colormap_normalizations_symlognorm.py

Move colormap examples from userdemo to images_contours_and_fields.

---

examples/README.txt

in accordance what we've already done in the top-level menu (see also the [dev call](https://hackmd.io/YA_MIqDlTRKTQuZENX8djA?both#website)).

Rename section title Gallery -> Examples

---

examples/axes_grid1/README.txt
examples/axisartist/README.txt
examples/pyplots/README.txt

(See https://matplotlib.org/devdocs/users/index.html for how it currently looks.)

Capitalization fixes in example section titles.

---

plot_types/arrays/contourf.py
plot_types/arrays/imshow.py
plot_types/arrays/pcolormesh.py
plot_types/unstructured/tricontour.py
plot_types/unstructured/tripcolor.py

- Most 2D data examples don't need Z.min() subtraction (the
normalization adjusts itself as needed).
- Tweak spacing in the expression for Z to be the same everywhere.
- Use shorter .min(), .max() methods instead of free functions.

Simplify/uniformize sample data setup in plot_types examples.

---

lib/matplotlib/pyplot.py

Currently:  https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.html#module-matplotlib.pyplot

DOC: clarify what we mean by object oriented in pyplot api

---

plot_types/arrays/streamplot.py

- zorders don't need to be explicitly set, the contour is already below
the streamplot.
- alpha=0.5 for the contour seems too faint IMO; fully opaque seems
better?
before:
after:

Tweak streamplot plot_types example.

---

examples/lines_bars_and_markers/curve_error_band.py

- Use finite differences to estimate derivative rather than splines
(which are conceptually much more complicated).
- Include a "constant error" case, which shows that the band does have
constant width in that case.
- Force the axes aspect to 1 (so that constant width actually appears
constant).
- Use np.full() to set up the codes array.
old version, for reference: https://matplotlib.org/devdocs/gallery/lines_bars_and_markers/curve_error_band.html
new (second) plot:

Improve curve_error_band example.

---

doc/faq/howto_faq.rst
doc/users/prev_whats_new/whats_new_1.0.rst
doc/users/prev_whats_new/whats_new_1.1.rst
doc/users/prev_whats_new/whats_new_1.2.rst
doc/users/prev_whats_new/whats_new_1.3.rst
doc/users/prev_whats_new/whats_new_1.4.rst
doc/users/prev_whats_new/whats_new_1.5.rst
tutorials/introductory/sample_plots.py

Most of these were likely autogenerated during the transition to s-g.
(cf https://github.com/matplotlib/matplotlib/pull/20536 which includes a similar change.)

Remove uninformative `.. figure::` titles in docs.

---

doc/api/animation_api.rst
lib/matplotlib/animation.py

I noticed that `to_jshtml()` didn't have a docstring, so have attempted to add one. I'm not too sure what 'embed_frames' does, so haven't added a description there.

Improve docs for to_jshtml()

---

doc/devel/contributing.rst

cf #21175, and a few older PRs which were touching the same code.

Discourage making style changes to extern/.

---

lib/matplotlib/mlab.py
lib/matplotlib/sphinxext/plot_directive.py

- mlab doesn't just do spectral computations, it also has GaussianKDE.
- The "caption" example in the plot_directive doc has a quote which gets
incorrectly highlighted as a Python string in the rendered docs; the
technically correct solution would be to wrap the whole thing in a `..
code-block:: rst` but just removing the quote works just as well and
avoids mangling the unrendered version.

Small doc fixes.

---

doc/api/backend_agg_api.rst
doc/api/backend_cairo_api.rst
doc/api/backend_gtk3_api.rst
doc/api/backend_gtk4_api.rst
doc/api/backend_mixed_api.rst
doc/api/backend_nbagg_api.rst
doc/api/backend_pdf_api.rst
doc/api/backend_pgf_api.rst
doc/api/backend_ps_api.rst
doc/api/backend_qt_api.rst
doc/api/backend_svg_api.rst
doc/api/backend_template_api.rst
doc/api/backend_tk_api.rst
doc/api/backend_webagg_api.rst
doc/api/backend_wx_api.rst

Previously, the first header would be used in the ToC/sidebar, resulting
e.g. in a "matplotlib.backends.backend_gtk3agg" entry even though the
page documents both backend_gtk3agg and backend_gtk3cairo.  Instead,
merge the titles, and also get rid of the common "matplotlib.backends"
prefix (the individual API doc entries keep the fully qualified name
anyways).
Also fix the qt docs: the canonical version is now at qtagg/qtcairo, not
qt5agg/qt5cairo.

Rework headers for individual backend docs.

---

lib/matplotlib/image.py

make_image is a huge function; shorten it (in physical screen space) a
bit by rewriting/rewrapping some comments, and a few small stylistic
changes.

Compress comments in make_image.

---

examples/statistics/confidence_ellipse.py

Correct the confidence interval corresponding to 3 standard deviations in 2-D. The value is taken from [this paper](https://doi.org/10.1371/journal.pone.0118537) — see Eq. 19.
The paper includes a [table](https://journals.plos.org/plosone/article/figure?id=10.1371/journal.pone.0118537.t001
) which gives confidence levels for different numbers of standard deviations (their "Magnification factor"):
I think, with this robust reference, we could improve upon #19074. Thanks for the support @CarstenSchelp.
- [N/A] API changes documented in …

Use correct confidence interval

---

doc/resources/index.rst

updated resources

---

doc/faq/environment_variables_faq.rst
doc/faq/index.rst
doc/faq/troubleshooting_faq.rst
doc/index.rst

Typo/capitalization/punctuation/styling.
I think the only debatable point is whether to emphasize "most" in the
Reference part, but I didn't see any good reason to do it (and it looks
a bit too much to me).

Small doc nits.

---

doc/devel/coding_guide.rst
doc/devel/contributing.rst

It's a bit of a whack-a-mole, but heh...

Fix some syntax highlights in coding and contributing guide.

---

examples/userdemo/colormap_interactive_adjustment.py

Manual backport of #21236 to v3.5.x

Backport PR #21236: DOC: Update interactive colormap example

---

examples/axes_grid1/scatter_hist_locatable_axes.py

See https://matplotlib.org/devdocs/gallery/axes_grid1/scatter_hist_locatable_axes.html.

Fix incorrect markup in example.

---

tutorials/introductory/usage.py

changed "however, it is preferable pick one of them and stick to it" to "however, it is preferable to pick one of them and stick to it"

typo-correction-on-line-185

---

lib/matplotlib/collections.py
src/_path_wrapper.cpp

Followup to https://github.com/matplotlib/matplotlib/pull/20245.

Further remove remnants of offset_position.

---

doc/api/prev_api_changes/api_changes_3.5.0/development.rst
doc/users/explain/backends.rst
doc/users/prev_whats_new/whats_new_3.5.0.rst

Adds some new features that were not previously documented, a few more images, and some development notes based on issues from the rc.

Add more 3.5 release notes

---

.github/PULL_REQUEST_TEMPLATE.md

Previous the checklist was not ordered in a meaningful way. I think this makes it easier to fill out (and to parse as a reader). I also combined the two flake8 items into one as the second was a superset of the first.

Organize checklist in PR template

---

requirements/doc/doc-requirements.txt

See https://github.com/sphinx-gallery/sphinx-gallery/issues/879

Pin sphinx to fix sphinx-gallery

---

examples/mplot3d/voxels.py

Fix documentation link with renaming `voxels` to `voxelarray`

---

requirements/doc/doc-requirements.txt

There is a bugfix 0.10.1 release of sphinx-gallery out now that should fix the build.

Revert "Pin sphinx to fix sphinx-gallery"

---

.github/workflows/clean_pr.yml

... as is currently the case in #21562.
As in #21359, this currently contains two additional commits at the top that should cause CI to fail; I will edit these commits out of existence once this PR is approved.

Check for images added-and-modified in a same PR

---

doc/devel/contributing.rst

#21393 @story645 @anntzer @QuLogic @jklymak
I suggest the following changes to make things a bit clearer.

Added the definition of Deprecation and made Deprecation Process clearer

---

README.rst

#21702
@simonthor @tacaswell
Changed the link in the README file

Changed the link to the correct citing example

---

lib/matplotlib/backend_managers.py
lib/matplotlib/backend_tools.py

Closes https://github.com/matplotlib/matplotlib/issues/20998 (going for https://github.com/matplotlib/matplotlib/issues/20998#issuecomment-913143550).
No test, because toolmanager is currenly only defined for interactive
backends, and it's not worth checking whether we can set up a tk canvas
or not just for that...  But can be manually tested.

Delay-load keymaps in toolmanager.

---

examples/axisartist/demo_floating_axis.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/colorbar.py
lib/matplotlib/colors.py
lib/matplotlib/dates.py
lib/matplotlib/figure.py
lib/matplotlib/mathtext.py
lib/matplotlib/offsetbox.py
lib/matplotlib/pyplot.py
lib/matplotlib/rcsetup.py
lib/matplotlib/tests/test_bbox_tight.py
lib/matplotlib/tests/test_dates.py
lib/matplotlib/tests/test_patches.py
lib/matplotlib/tests/test_text.py
lib/matplotlib/text.py
lib/matplotlib/ticker.py
lib/mpl_toolkits/mplot3d/axis3d.py

Small code cleanups and style fixes.

---

src/_macosx.m

This should not change any code logic.
I intentionally did not touch the parts currently worked on by the key-modifier and subplot_tool PRs.

Whitespace/braces/#defines cleanup to macosx.

---

lib/matplotlib/backends/backend_macosx.py
src/_macosx.m

Pass `canvas` as argument to `__init__`, relying on PyArg_ParseTuple to
check type (and non-NULL-ness).
Also declare some variables closer to point of use, and use
NSMakeRect/NSMakeSize to create NSRects and NSSizes.

Simplify macosx toolbar init.

---

src/_macosx.m

This seems to compile and work, but the test mac is kind of slow, so not sure if it'll break anything. It also doesn't have a retina display, so I can't actually confirm that the content is not quarter sized.
Fixes #21648

Use standard subplot window in macosx backend

---

.gitattributes

i.e., when showing a diff on _macosx.m, the `@@ ...` header shows the
correct current function.
Split out of #16931.

Update gitattributes so that objc diffs are correctly contextualized.
