matplotlib/matplotlib

lib/matplotlib/colors.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_colors.py

closes #18411
This fixes the problem discussed in the linked issue in the most simple and general way.
- [NA] Has pytest style unit tests (and `pytest` passes).
- [NA] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [NA] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

2-D array RGB and RGBA values not understood in plt.plot()

---

lib/matplotlib/image.py
lib/matplotlib/tests/test_image.py

Deal with `imshow`ing an array that is completely masked without emitting a warning. The added test/code emits 3 warnings on `master`, none of which are particularly informative. The test on `master` fails with:
<details>
```
lib/matplotlib/image.py:639: in draw
im, l, b, trans = self.make_image(
lib/matplotlib/image.py:924: in make_image
return self._make_image(self._A, bbox, transformed_bbox, clip,
lib/matplotlib/image.py:476: in _make_image
vrange = np.array([vmin, vmax], dtype=scaled_dtype)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = masked
def __float__(self):
"""
Convert to float.
"""
if self.size > 1:
raise TypeError("Only length-1 arrays …
```

BUG: Fix all-masked imshow

---

lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/tests/test_mplot3d.py

This causes a crash when re-broadcasting with the colour that is then (0, 4)-shaped.

Fix depth shading when edge/facecolor is none.

---

examples/userdemo/pgf_preamble_sgskip.py
lib/matplotlib/mpl-data/stylelib/classic.mplstyle

In pgf_preamble_sgskip, replace examples of using `units` and `metalogo`
package by `url`, which is in TeXLive latex-base (unlike the others) and
thus most likely to be present (also, the url works in the pdf, which is
nice).  Remove dependency on xits-math.otf font.
Sync the description of text.latex.preamble in classic.mplstyle with the
current template description.  This removes the substrings
"\usepackage{bm},\usepackage{euler}", which caused some linux packagers
in adding dependencies on these packages; moreover, the comma is now
wrong.

Fewer "soft" dependencies on LaTeX packages.

---

lib/matplotlib/backends/backend_ps.py
lib/matplotlib/tests/test_backend_ps.py

The elements should be integers; for floating point, the `HiResBoundingBox` can be used.
I believe this broke some time ago in d3aef44ca7d5516cf85e0d05a8c26ad2f96567e3, though it did not use `ceil` at the time, so this is slightly better.
This was reported on gitter.

Fix BoundingBox in EPS files.

---

doc/api/next_api_changes/removals/18513-ES.rst
doc/api/prev_api_changes/api_changes_3.2.0/deprecations.rst
lib/matplotlib/dates.py
lib/matplotlib/projections/polar.py
lib/matplotlib/ticker.py

Remove Locator.autoscale.

---

lib/matplotlib/backends/backend_ps.py
lib/matplotlib/tests/baseline_images/test_backend_ps/useafm.eps
lib/matplotlib/tests/test_backend_ps.py

See e.g.
```
rcParams["ps.useafm"] = True
text(.5, .5, "qk")
axhline(.5)
savefig("/tmp/test.ps")
```
Previously the bottom of the tip of the "q" would be on the baseline;
now the baseline is correctly positioned.
(I picked a relatively generic name for the test because we could later
update the baseline image "in place" for more afm tests.)

Correctly position text with nonzero descent with afm fonts / ps output.

---

lib/matplotlib/offsetbox.py
lib/matplotlib/tests/test_legend.py

Addresses issue #17518 regarding a warning being shown when legend is added while using Tex. Code by @anntzer.

Remove font warning when legend is added while using Tex

---

.github/CODE_OF_CONDUCT.md

This is in a similar vein to the numpy equivalent: https://github.com/numpy/numpy/blob/master/.github/CODE_OF_CONDUCT.md
Fixes https://github.com/matplotlib/matplotlib/issues/18534

Add a code of conduct link to github

---

doc/api/next_api_changes/removals/18516-ES.rst
doc/sphinxext/math_symbol_table.py
lib/matplotlib/font_manager.py
src/ft2font_wrapper.cpp

Remove deprecated font-related things.

---

doc/api/figure_api.rst
doc/api/next_api_changes/removals/18522-ES.rst
doc/api/prev_api_changes/api_changes_2.1.0.rst
doc/users/prev_whats_new/whats_new_1.4.rst
lib/matplotlib/__init__.py
lib/matplotlib/figure.py
lib/matplotlib/mlab.py
lib/matplotlib/style/core.py
lib/matplotlib/tests/test_mlab.py
lib/matplotlib/transforms.py
lib/mpl_toolkits/axisartist/axis_artist.py
lib/mpl_toolkits/axisartist/grid_finder.py
lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
lib/mpl_toolkits/mplot3d/axes3d.py

Remove mlab, toolkits, and misc deprecations

---

src/_image_wrapper.cpp

Templatize _image.resample to deduplicate it.

---

lib/matplotlib/backends/backend_ps.py
lib/matplotlib/tests/baseline_images/test_backend_ps/useafm.eps
lib/matplotlib/tests/baseline_images/test_path/nan_path.eps

And update Creator field to match other backends.

Don't leak file paths into PostScript metadata

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/contour.py
lib/mpl_toolkits/mplot3d/axes3d.py

1st commit: Change the signature of `_process_unit_info` to make it work both for the 2D and the 3D cases (instead of passing `xdata`, `ydata` as separate named parameters, pass a single axis-to-dataset mapping).  This avoids having to redefine it for the 3D case.
2nd commit: Make `_process_unit_info` directly perform unit conversion as well (nearly all calls to `_process_unit_info` are followed by a call to `convert_x/yunits`, and it semantically makes sense to have both of them together, too).
3rd commit: Fix incorrect unit application for horizontal histograms (which should use the y units, not the x units).

Unit handling improvements

---

doc/users/next_whats_new/steppatch_and_stairs.rst
examples/lines_bars_and_markers/stairs_demo.py
examples/lines_bars_and_markers/step_demo.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/patches.py

Addresses bullet points 1 and 3 of https://github.com/matplotlib/matplotlib/pull/18275#pullrequestreview-487347047:
- Comparison of `.pyplot.step` and `.pyplot.stairs` could use some explanatory text.
- Some docstring parameters don't have a description. Even if they state something apparently obvious, they should be explicit.

Documentation improvements for stairs()

---

doc/api/next_api_changes/deprecations/18528-AL.rst
examples/misc/anchored_artists.py
examples/text_labels_and_annotations/demo_annotation_box.py
lib/matplotlib/legend.py
lib/matplotlib/offsetbox.py
lib/mpl_toolkits/axes_grid1/anchored_artists.py

The implementation of `Text._get_layout` has effectively enforced
`minimumudescent=True` (`d = max(d, lp_d)`) since ee3af298 (mpl 1.3).
(See also the images in the corresponding PR, #2070.)

Deprecate TextArea minimumdescent.

---

lib/matplotlib/tests/test_animation.py

I got some TemporaryDirectory ResourceWarning's in a sphinx-gallery-based doc builds with matplotlib animations, so I started trying to replicate them with some minimal code. I couldn't, but it looked like there weren't any explicit `_repr_html_` tests in the `test_animation.py` code, so I figured I'd open a PR to add some basic ones (these were my minimal examples that showed no problems at the mpl end).

TST: Add test for _repr_html_

---

lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_axes.py

In Axes.redraw_in_frame().
Fixes #18539.
Fixes error in `Axes.redraw_in_frame`.

Call to ExitStack.push should have been ExitStack.callback.

---

lib/matplotlib/backend_bases.py

Simple change. There was a straggling spot in `lines.py` that still did its own validation of joinstyle/capstyle instead of using `rcsetup.validate_joinstyle`/`_capstyle`.

CLEANUP: validate join/cap style centrally

---

doc/api/next_api_changes/behavior/18525-ES.rst
lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/tests/test_mplot3d.py

And simplify the calculations to avoid the duplicate position.

Add Text3D position getter/setter

---

lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/tests/test_backend_pdf.py

Tell the user what keys and types are expected.
This still needs tests.  Happy if anyone wants to adopt the PR and finish it.

MNT: improve error messages on bad pdf metadata input

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

Closes #18547
For `pcolor(mesh)` the new "nearest" interpolation was being done before unit conversion, so datetime (for instance) did not work.  This moves unit conversion inside `_pcolorargs`. 
```python
from datetime import datetime
x_coords = [datetime.fromtimestamp(x * 3600) for x in range(24)]
y_coords = [*range(0, 10)]
plt.pcolormesh(x_coords,
y_coords, [[*range(24)] for _ in range(10)],
shading="nearest")
plt.show()
```
failed before, and works now...

FIX: unit-convert pcolorargs before interpolating

---

doc/api/next_api_changes/removals/18515-ES.rst
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_agg.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_macosx.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/backends/backend_wx.py

Remove deprecated backend code.

---

lib/matplotlib/axis.py
lib/matplotlib/tests/test_axes.py

closes #18427
This line came in via b2a80a7 / #1589 .  It looks like everything still passes without it (!!) so I think that means either we never needed it or the work done since then on the colorbar code has made it redundant. 

FIX: do not reset ylabel ha when changing position

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

backport pr 18549

---

doc/users/next_whats_new/mplot3d_modification.rst
lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/tests/test_mplot3d.py

closes #3370
We need to do an extra step to propagate the color information back to
the 3D projections
Replaces #5598, still needs tests.

FIX: Add get/set methods for 3D collections

---

.coveragerc
doc/api/next_api_changes/behavior/8987-Z.rst
lib/matplotlib/tests/test_ticker.py
lib/matplotlib/ticker.py

When formatting and setting useLocale to True, the numbers greater than 1000 are not grouped as specified by the locale. 1000 should be 1,000 in certain locales. By setting the last argument to locale.format_string the locale dependent grouping is honored.

Tick formatter does not support grouping with locale

---

lib/matplotlib/backend_bases.py

Specifying an ill-defined *clip_path* leads to a seg-fault (#4448) with agg backends. Here is an minimal example.
```python
import io
import matplotlib.figure as mfigure
from matplotlib.projections import PolarAxes
import matplotlib.patches as mpatches
from matplotlib.backends.backend_agg import FigureCanvasAgg
fig = mfigure.Figure()
ax = fig.add_subplot(111)
l1, = ax.plot([-1, 1], [-1, 1])
tr = PolarAxes.PolarTransform()
p = mpatches.Polygon(np.arange(-3, 3).reshape((3, 2)), transform=tr)
l1.set_clip_path(p)
FigureCanvasAgg(fig).print_png(io.BytesIO())
```
The current PR simply fix this by making *GraphicsContextBase.get_clip_path* returns None if it contains values that are not finite.

get_clip_path checks for nan

---

lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_backend_pdf.py
lib/matplotlib/tests/test_backend_svg.py
lib/matplotlib/tests/test_collections.py
lib/matplotlib/tests/test_dates.py
lib/matplotlib/tests/test_legend.py
lib/matplotlib/tests/test_lines.py
lib/matplotlib/tests/test_patches.py
lib/matplotlib/tests/test_spines.py

Use
~~~
~~~
instead of 
~~~
ax = plt.subplots(1, 1, 1)
~~~
The latter was a common pattern in tests. The former is shorter and thus adds less clutter to the tests.
More similar patterns could be replaced, but that's for another time.
Also fixed here along the way:
- One test that used `plt.errorbar` instead of `ax.errorbar` - we should test using the OOP API unless we want to test pyplot specifically.
- Some copy-paste errors in comments.

Use fig, ax = plt.subplots() in tests

---

lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_backend_pdf.py
lib/matplotlib/tests/test_bbox_tight.py
lib/matplotlib/tests/test_legend.py
lib/matplotlib/tests/test_patches.py
lib/matplotlib/tests/test_text.py
lib/matplotlib/tests/test_usetex.py

Slight variation of #18553, replacing
~~~
ax = plt.subplots()
~~~
by 
~~~
~~~
in tests.

Use fig, ax = plt.subplots() in tests (part 2)

---

doc/api/next_api_changes/behavior/18560-AL.rst
examples/axisartist/demo_curvelinear_grid.py
lib/mpl_toolkits/axes_grid1/parasite_axes.py

The override of `pcolor`, `pcolormesh`, `contour`, and `contourf` in
parasite axes was actually incorrect.  Perhaps things were different
when that code went in, but nowadays things work just fine without any
need for overriding.
See e.g. the new version of demo_curvelinear_grid before and after the
changes.
old:
new:
The default gridding of `pcolor`/`pcolormesh` changed to match the one
of normal Axes; I don't think this is worth going through a deprecation
period...

Remove incorrect override of pcolor/contour in parasite axes.

---

.circleci/config.yml
doc/_templates/layout.html
doc/conf.py
doc/devel/release_guide.rst

DOC: Add an option to disable Google Analytics.

---

lib/matplotlib/testing/compare.py

For image comparison tests in svg/pdf/ps formats, the result images are
converted to png for comparison.  Previously the conversion results were
cached for the baseline images, but not for the test-generated images
(because of non-deterministic svg/pdf/etc. results, due to
hash-salting, dict ordering, etc.).
Now that the test-generated images are generally deterministic, we can
enable the cache for baseline images as well.  This speeds up
`pytest -k '[svg]'` by ~30% (81s initially -> 55s on a seeded cache) and
`pytest -k '[pdf]'` by ~10% (62s -> 55s) (there are too few (e)ps image
comparison tests to see an effect).  Also add logging regarding the
cache which may help troubleshooting determinacy problems.
~This is a much simpler version of PR#7764, which added more sophisticated
reporting …

Use test cache for test result images too.

---

doc/users/next_whats_new/errorbar_errorevery.rst
lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

I did not add support for floating-point step sizes though, as errorbars are not continuous.
This also fixes a bug where passing `markevery` would crash, introduced in #17930, when the property dictionaries were changed around.
I haven't implemented for 3D, but will do that with #18436.

Accept same types to errorevery as markevery

---

lib/matplotlib/tests/test_artist.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_image.py

Some simple cases that create a full subplot grid.

Replace some usages of plt.subplot() by plt.subplots() in tests

---

lib/matplotlib/_mathtext.py

Instead of a weird `dict` thing.

Convert _math_style_dict into an Enum.

---

doc/api/prev_api_changes/api_changes_2.0.1.rst
doc/api/prev_api_changes/api_changes_2.2.0.rst
doc/devel/color_changes.rst
doc/thirdpartypackages/index.rst
doc/users/dflt_style_changes.rst
doc/users/next_whats_new/colormap_repr.rst
doc/users/prev_whats_new/changelog.rst
doc/users/prev_whats_new/whats_new_2.0.0.rst
examples/images_contours_and_fields/image_masked.py
examples/mplot3d/surface3d.py
examples/mplot3d/surface3d_radial.py
lib/matplotlib/_cm.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/collections.py
lib/matplotlib/colorbar.py
lib/matplotlib/colors.py
lib/matplotlib/contour.py
lib/matplotlib/image.py
lib/matplotlib/pyplot.py
lib/matplotlib/tests/test_collections.py
lib/matplotlib/tests/test_colorbar.py
lib/matplotlib/tests/test_colors.py
lib/mpl_toolkits/axes_grid1/colorbar.py
lib/mpl_toolkits/mplot3d/axes3d.py
tutorials/introductory/images.py

Fix this across the entire codebase and docs.
In #15127 @dopplershift  pointed out all of the places I used 'color map' instead of 'colormap', so via ack + sed I fixed it everywhere.
- [ x Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ N/A ] New features are documented, with examples if plot related.

DOC: prefer colormap over color map

---

doc/api/next_api_changes/behavior/15127-TAC.rst
doc/users/next_whats_new/2019-08_tac.rst
lib/matplotlib/cm.py
lib/matplotlib/colors.py
lib/matplotlib/tests/test_colors.py

- protect re-defining built in color maps
- warn on re-defining user-defined color maps
- add de-register function

ENH/API: improvements to register_cmap

---

doc/api/next_api_changes/behavior/18564-AL.rst
doc/api/next_api_changes/deprecations/18564-AL.rst
examples/userdemo/demo_gridspec06.py
lib/matplotlib/axes/_base.py
lib/matplotlib/axes/_subplots.py
lib/matplotlib/colorbar.py
lib/matplotlib/figure.py
lib/matplotlib/gridspec.py
lib/matplotlib/tests/test_collections.py
lib/matplotlib/tests/test_colorbar.py
lib/matplotlib/tests/test_figure.py
lib/mpl_toolkits/mplot3d/axes3d.py
lib/mpl_toolkits/tests/test_mplot3d.py
tutorials/intermediate/gridspec.py

It should be possible to merge SubplotBase into AxesBase, with all Axes
having a `get_subplotspec()` method -- it's just that that method would
return None for non-gridspec-positioned Axes.  The advantage of doing so
is that we could get rid of the rather hackish subplot_class_factory,
and the dynamically generated AxesSubplot class, which appears nowhere
in the docs.  (See discussion at https://github.com/matplotlib/matplotlib/issues/18222.)
- Deprecate most Subplot-specific API: while it's fine for all axes to
have a `get_subplotspec` which may return None, it would be a bit
weird if they all also have e.g. a `is_last_row` for which it's not
clear what value to return for non-gridspec-positioned Axes.  Moving
that to the SubplotSpec seems natural enough (and these are pretty
low-level …

Prepare for merging SubplotBase into AxesBase.

---

examples/pie_and_polar_charts/pie_and_donut_labels.py

Closes #18428 
In #18428 , @Dan-Lt pointed out that if we use round function to calculate the value of absolute, we will not lose about 3% of the counts. So I updated its value.

FIx precision in pie and donut example 

---

lib/matplotlib/backends/backend_webagg_core.py

It doesn't allow 0, so set a very small minimum.
Fixes #18580.

Fix setting 0-timeout timer with Tornado.

---

requirements/testing/travis_all.txt

Pin pytest until we can fix...  temporarily closes #18593

FIX: pin pytest

---

lib/matplotlib/text.py

Fix the docstring of _get_textbox.  (`Text.get_extents` doesn't exist.)
Inline `_draw_bbox` into its sole call site (the first half is the same
as `update_bbox_position_size`; this does mean calling
`convert_xunits/convert_yunits` twice but that should be cheap compared
to everything else).
`Annotation.draw` doesn't need to also call `update_bbox_position_size`
as `Text.draw` will do it (I think the call was duplicated because the
draw-a-bbox functionality was present in Annotation before it also moved
to Text).
rcParams -> mpl.rcParams.
Remove an extraneous import.

Text cleanups.

---

lib/matplotlib/axes/_base.py

The docstring of zaxis_date appends an addendum to the other axis_dates
(about the fact that it doesn't actually work...), but previously the
docstring appending incorrectly went to `_axis_method_wrapper.__doc__`,
not `zaxis_date.__doc__`.  Perform docstring interpolation earlier to
fix that.

Fix docstring of zaxis_date.

---

requirements/testing/travis_all.txt

This reverts PR https://github.com/matplotlib/matplotlib/pull/18594 / commit 14c19a97798128875f58a35c8d761356d3c7edb4, re: https://github.com/matplotlib/matplotlib/issues/18593.
The pytest-rerunfailures plugin version 9.1.1 has just been released which supports newest pytest 6.1:
* https://github.com/pytest-dev/pytest-rerunfailures/blob/master/CHANGES.rst#911-2020-09-29
- [n/a] Conforms to …

Revert "FIX: pin pytest"

---

lib/matplotlib/backends/backend_wx.py

Previously, pressing "p" would unclick the "Pan" button if it was
already pressed, but not press it if it wasn't (even though it did
correctly start panning).  Fix that.

Correctly sync state of wx toolbar buttons when triggered by keyboard.

---

matplotlibrc.template

They got accidentally merged together in 7d08d3d.

Correctly separate two fantasy font names.

---

lib/matplotlib/patches.py
lib/matplotlib/tests/test_axes.py

CC @andrzejnovak 
Fixes:
- `check_figures_equal` tests did not test anything because fixture figures were not used. Instead the tests created new figures, which were not compared.
- Limited the `check_figures_equal` tests to png. - No need to additionally test vector backends, because this is about the logic creating the artist, not how it's drawn by a backend.
- Failure tests must assert with `pytest.raises`. `pytest.xfail` is only for excluding broken tests.
- Logic change: Don't draw an edge for filled `StepPatch` by default (`_edge_default = False`). This was proposed anyway in https://github.com/matplotlib/matplotlib/pull/18275#pullrequestreview-487347047 / https://github.com/matplotlib/matplotlib/pull/18275#issuecomment-692442104. IMHO it's the right thing to do as most of our …

Fix stairs() tests

---

lib/matplotlib/backends/backend_wx.py

`TimerWx._timer_set_single_shot` currently tries to start the timer without interval or any other setting, which is not what this method is supposed to do; it should only modify settings on internal objects. Since single shot mode is fully handled in `TimerWx._timer_start`, this method is unnecessary.
Fixes #18620.

Fix singleshot timers in wx.

---

doc/_static/mpl.css

The previous styling looked a bit dated and is harder to read.
before / after:

Remove special styling of sidebar heading

---

doc/api/next_api_changes/deprecations/18591-AL.rst
examples/text_labels_and_annotations/mathtext_asarray.py
examples/user_interfaces/mathtext_wx_sgskip.py
lib/matplotlib/contour.py
lib/matplotlib/mathtext.py
lib/matplotlib/sphinxext/mathmpl.py
lib/matplotlib/tests/test_mathtext.py

`MathTextParser("bitmap")` is rather low-level APIs to convert text
strings to images.  Instead, one can use a much more generic method,
namely directly drawing to a new Figure() and saving with
`bbox_inches="tight"`.  Alternatively, if one really wants a single
function call, there's still `mathtext.math_to_image`.
Also fix the wx example to use light text colors when so directed by the
system theme.

Deprecate MathTextParser("bitmap") and associated APIs.

---

lib/matplotlib/backend_bases.py

They don't occur anymore since 3ccc17b.

Remove outdate comment about canvases with no manager attribute.

---

lib/matplotlib/lines.py
lib/matplotlib/markers.py
lib/matplotlib/tests/test_axes.py

#Deeper marker copies in Line2D update_from
Markers already support a copy construction: `MarkerStyle.set_marker`
accepts other instances of `MarkerStyle`.  However, Line2D, when
copying markers, instead construct the copy from the other instance's
`get_marker` and `get_fillstyle` methods.  This destroys (unsupported)
manipulations the user might make to the marker, as discovered in
issue #18600.
By switching constructors, we can get a more faithful copy without
explicitly relying on any of `MarkerStyle`'s private methods in places
they do not belong.
This change is also more in line with the `self = other` style of the rest of the method's body.
- Some tests failed, but they also failed when I cloned `master`:
- test_pcolormesh_alpha[pdf]
- test_transparent_markers
- test_xelatex[pdf]
- …

bugfix #18600 by using the MarkerStyle copy constructor

---

lib/matplotlib/figure.py

A slash was missing between "and" and "or".  Also reworded the thing a
bit.

Fix typo in warning message.

---

lib/matplotlib/axes/_axes.py

This addition might be unnecessary, but explicit is better than implicit, right?
It's just based on my recent experience: https://github.com/scikit-image/scikit-image/pull/4946#issuecomment-702301758

Specify case when parameter is ignored.

---

lib/matplotlib/widgets.py

Otherwise, if the selector is made inactive and then back to active, the
"old" selector gets captured in the background image and spurious
appears.
No tests because good luck with that, but can be tried with
examples/widgets/rectangle_selector.py.
Closes #17476.

Regenerate background when RectangleSelector active-flag is set back on.

---

lib/matplotlib/patches.py
lib/matplotlib/tests/test_patches.py

This rebases the branch in #5696 by @Rezangyal, plus a small cleanup, and adds a test.
Fixes #5519.

Support linestyle='none' in Patch

---

lib/matplotlib/colorbar.py

`set_label` can just forward everything to either `set_xlabel` or
`set_ylabel`, which already have all the logic for handling `loc`,
instead of duplicating that logic.
`_edges` is really just a call to `np.dstack`, and factoring it to a
separate function doesn't really help legibility.

Simplify Colorbar.set_label, inline Colorbar._edges.

---

lib/matplotlib/backends/backend_ps.py
lib/matplotlib/tests/baseline_images/test_backend_ps/type3.eps
lib/matplotlib/tests/test_backend_ps.py
lib/matplotlib/tests/test_font_manager.py

... similarly to the change for pdf (#18181), but easier because there are no
baseline images for which we need to provide bug-level backcompat :-)
Drop the FontInfo metadata (which is explicitly optional in the
PostScript spec) to avoid having to figure out the correct encoding
(which can be quite obscure).
Replace the implementation of the `_sc` command from
`7 -1 roll{setcachedevice}{pop pop pop pop pop pop}ifelse` to a plain
`setcachedevice` (as I cannot see any case where the "other" branch is
taken).
Drop the splitting of long commands using `exec` (`_e`) -- this is only
needed for level-1 postscript, which has a small fixed stack size; we
output level-2 postscript (per backend_version) and I guess level-1 is
rarely in use nowadays anyways (probably the feature could be added back …

Move PostScript Type3 subsetting to pure python.

---

lib/matplotlib/pyplot.py
lib/matplotlib/tests/test_figure.py

It's already possible to activate (in the `gcf()` sense) a figure
via an instance *if there's any axes on it* using `gca()`, but not
if the figure has no axes.  It seems reasonable enough to add this
capability (which is really just calling `Gcf.set_active(manager)`) to
`plt.figure()`.

Support activating figures with plt.figure(figure_instance).

---

lib/matplotlib/backends/web_backend/js/nbagg_mpl.js

In JavaScript, the event handlers are called for both the element and also bubbled up from any children. If the Matplotlib figure is the only thing in the output, that's fine, as closing the figure when one of the `canvas` or `div`s clears is the same as when the `OutputArea` is cleared. However, if there are other outputs, such as widgets, we do not want to close the figure if one of them is cleared.
As there's no way to clear just the figure output, only close the figure if the _entire_ `OutputArea` div is cleared (i.e., the element we've attached to).
Fixes #18638.
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without …

nbagg: Don't close figures for bubbled events.

---

lib/matplotlib/image.py

self._transform/get_transform() can just be inherited from the base
Artist class.  A BboxTransform starting at the unit bbox is equivalent
to BboxTransformTo.

Small simplifications to BboxImage.

---

lib/mpl_toolkits/axisartist/grid_finder.py

... rather than as dynamical attributes using local functions.
This way they show up in the docs, and avoid making GridFinder
unpicklable.

Define GridFinder.{,inv_}transform_xy as normal methods.

---

lib/matplotlib/testing/compare.py

This prevents multiple processes from trying to cleanup the directory at the same time (e.g., using `pytest -nauto`).
Fixes #18641.

TST: Lock cache directory during cleanup. 

---

doc/api/next_api_changes/deprecations/18673-AL.rst
examples/axes_grid1/parasite_simple2.py
lib/mpl_toolkits/axes_grid1/parasite_axes.py

Setting axis zorder in cla() is unnecessary since 51f8468 (zorders are
now set in set_axisbelow() instead of draw()).
Deprecate the peculiar `update_viewlim` API which is really just an
internal helper.
No need to explicitly set frameon=False, this is forced by the
ParasiteAxesBase constructor.
We can factor the various twin axes removers into a single one.  (Also,
avoiding local functions helps picklability, as usual.)
In twin() we can also use viewlim_mode="transform" when the transform is
None (IdentityTransform()), because that just means that we apply an
additional IdentityTransform() to the viewlims.
In parasite_simple2 we don't need to set viewlim_mode, this is already
done by `twin`.

Small cleanups to parasite axes.

---

lib/matplotlib/__init__.py
lib/matplotlib/image.py

In #18636 we removed certifi as a runtime dependency, but it turns out
we do try to use it if you read from a url in a handful of places.
This makes us fail gracefully and log if we can not import certifi.

MNT: make certifi actually optional

---

lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/tests/test_backend_pgf.py

backend_pgf uses a complicated way to handle temporary directories, in
particular because (on top of the normal calls to tex) it runs a
separate, long-standing tex instance to compute text bounding boxes.
I'm not sure this is actually needed, but at least, for the places
where we just run tex locally, we can certainly just use normal
TemporaryDirectories with automatic cleanup.
Do so in _print_pdf_to_fh (also with some pathlibification),
_print_png_to_fh, and PdfPages._run_latex (where all the temporary files
can be set up in `_run_latex`, rather than in `__init__`, which saves
the need for a bunch of attributes).

Simplify tmpdir handling in backend_pgf.

---

doc/users/next_whats_new/pdf_urls.rst
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/tests/test_backend_pdf.py

This is the minimum needed to get what I wanted ~~, but it still needs some work to be fully implemented. It currently only works for plain text, and not text that goes through `draw_tex`, as I don't yet know how to get the text bounding box in that path.~~
~~Also needs tests and documentation.~~

pdf: Support setting URLs on Text objects

---

tools/triage_tests.py

Small simplification to triage_tests.py.

---

lib/matplotlib/artist.py

Numpydocify setp.

---

doc/api/next_api_changes/deprecations/18682-AL.rst
lib/matplotlib/sphinxext/plot_directive.py

docutils' Image.align has existed since 2006.

Small API cleanups to plot_directive.

---

examples/userdemo/pgf_fonts.py
examples/userdemo/pgf_preamble_sgskip.py
examples/userdemo/pgf_texsystem.py
tutorials/text/pgf.py

Switch from pyplot to OO style, and swap a font selector so that it doesn't warn as much.

Cleanup pgf examples

---

doc/api/next_api_changes/deprecations/18679-AL.rst
lib/matplotlib/backends/backend_pgf.py

By carefully tearing down components of LatexManager in the right order
(first the subprocess), we avoid the need for a global registry of
things that need to be cleared at process termination.

Further simplify pgf tmpdir cleanup.

---

doc/api/next_api_changes/behavior/17791-AL.rst
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/tests/test_backend_gtk3.py
lib/matplotlib/tests/test_backend_qt.py

More accurate handling of unicode/numpad input in gtk3 backends.

---

lib/matplotlib/cbook/deprecation.py

This is tricky to fix correctly and anyways quite rare, so just document
the limitation for now.
Closes https://github.com/matplotlib/matplotlib/issues/18690.

Document limitations on `@deprecated` with multiple-inheritance.

---

SECURITY.md
doc/devel/release_guide.rst

Create security policy

---

lib/matplotlib/rcsetup.py
lib/matplotlib/tests/test_rcparams.py

From a `matplotlibrc` point of view, the only input would be strings, which could raise `ValueError`. But from a code point of view,
_anything_ could be assigned to `rcParams`. This raises a `TypeError` instead of the validator message.
That is, previously you would get:
```python
>>> plt.rcParams['patch.linewidth'] = None
File "<stdin>", line 1, in <module>
File ".../matplotlib/lib/matplotlib/__init__.py", line 632, in __setitem__
cval = self.validate[key](val)
File ".../matplotlib/lib/matplotlib/rcsetup.py", line 248, in validator
return cls(s)
TypeError: float() argument must be a string or a number, not 'NoneType'
```
and now you get the validator message:
```python
>>> plt.rcParams['patch.linewidth'] = None
File …
```

Catch TypeError when validating rcParams types.

---

lib/matplotlib/axes/_axes.py

This example from the plot docstring was unclear and/or incorrect. This modifies in a way that I at least find clearer.
```python
fig, (ax1, ax2, ax3) = plt.subplots(1,3, sharey=True, figsize=(10,5))
a = np.arange(6).reshape(3,2)
ax1.plot(a[0], a[1:], 'o-') #old example
ax2.plot(a, 'o-')
for i in range(2):
ax3.plot(a[:, i], 'o-')
ax1.set_title('Old Example')
ax2.set_title('New Example - part 1')
ax3.set_title('New Example - part 2')
ax1.set_xlim(ax3.get_xlim())
```
See discussion on gitter starting here: https://gitter.im/matplotlib/matplotlib?at=5f80c4dfdc95072254c78916
- …

clarify example in plot docstring

---

doc/api/next_api_changes/behavior/17791-AL.rst
lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/cbook/__init__.py

Some keys are still misreported, e.g. numpad keyreleases (keypresses are
fine), but I think this is already an improvement.
(followup to https://github.com/matplotlib/matplotlib/pull/17791)

Also fix tk key mapping, following the same strategy as for gtk.

---

.github/workflows/cibuildwheel.yml
setup.py

As of 60b03f1571c775f60bbd701d3381357a31eaf8bb the minimum version is
1.16.  This got missed as part of that PR.
:sheep: I missed this in https://github.com/matplotlib/matplotlib/pull/17662

BLD: sync build and run time numpy pinning

---

lib/matplotlib/axes/_base.py

The previous versions made it sound like this would be applied per plot command, whereas the autoscale_on really is applied at draw time.
Closes #18662

DOC: fix autoscale docstring

---

lib/matplotlib/backends/backend_wx.py

Like for qt/gtk, it's much easier to just draw the rectangle at
gui_repaint time.
AFAICT this now works on Wayland too, and closes the rubberbanding part of https://github.com/matplotlib/matplotlib/pull/10417 / https://github.com/matplotlib/matplotlib/pull/11944.

Simplify wx rubberband drawing.

---

doc/api/next_api_changes/deprecations/18564-AL.rst
lib/mpl_toolkits/axes_grid1/axes_divider.py

The deprecations parallel the ones in 261f706.

Sync SubplotDivider API with SubplotBase API changes.

---

doc/api/next_api_changes/deprecations/17737-AL.rst
examples/userdemo/custom_boxstyle01.py
lib/matplotlib/cbook/deprecation.py
lib/matplotlib/patches.py

... by moving the mutation_aspect logic to FancyBboxPatch, so that
boxstyles can be plain classes just implementing `__call__` and not
inheriting from anything, which removes the need to inherit from a
private base in `userdemo/custom_boxstyle01.py`.
A similar approach could be implemented for FancyArrowStyle._Base and
ConnectionStyle._Base.
Closes https://github.com/matplotlib/matplotlib/issues/13199#issuecomment-646949629.

Deprecate BoxStyle._Base.

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/cbook/__init__.py
setupext.py
src/_c_internal_utils.c

We currently check the $DISPLAY environment variable to autodetect
whether we should auto-pick a non-interactive backend on Linux, but that
variable can be set to an "invalid" value.  A realistic use case is for
example a tmux session started interactively inheriting an initially
valid $DISPLAY, but to which one later reconnects e.g. via ssh, at which
point $DISPLAY becomes invalid.
Before this PR, something like
```
DISPLAY=:123 MPLBACKEND= MATPLOTLIBRC=/dev/null python -c 'import pylab'
```
(where we unset matplotlibrc to force backend autoselection) would crash
when we select qt and qt fails to initialize as $DISPLAY is invalid (qt
unconditionally abort()s via qFatal() in that case).
With this PR, we correctly autoselect a non-interactive backend.
~~Note that we were *already* relying …

Improve headlessness detection for backend selection.

---

doc/api/next_api_changes/deprecations/18675-AL.rst
examples/axisartist/demo_curvelinear_grid.py
lib/mpl_toolkits/axes_grid/parasite_axes.py
lib/mpl_toolkits/axes_grid1/parasite_axes.py
lib/mpl_toolkits/axisartist/__init__.py
lib/mpl_toolkits/axisartist/parasite_axes.py
lib/mpl_toolkits/tests/test_axisartist_axislines.py
lib/mpl_toolkits/tests/test_axisartist_grid_helper_curvelinear.py

It doesn't warrant being a separate mixin class (cf. merging of Subplot
into Axes -- flat is better than nested).
Also, currently mpl_toolkits axes mixins create non-picklable Axes
subclasses because they lack the same pickling machinery as the
standard SubplotBase mixin.  It's not too hard to also set up the
same machinery for mpl_toolkits mixins (planned for a later PR), but
also supporting the double-mixin case (both ParasiteAxesBase and
ParasiteAxesAuxTransBase) adds unnecessary complications.

Merge ParasiteAxesAuxTransBase into ParasiteAxesBase.

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

Ok hopefully last follow up on #18579. The current setup, unfortunately, ignores stickies when `baseline=None`
Updating datalim as well fixes this. Thanks @anntzer 
@timhoffm @jklymak

fix: keep baseline scale to baseline 0 even if set to None

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/contour.py

Both use the same docstring from `mcontour.QuadContourSet._contour_doc`.
At least let's make the summary line and call signatures explicit to be more
clear.

Individualize contour and contourf docstrings

---

lib/matplotlib/backends/backend_wx.py

Shorten GraphicsContextWx.get_wxcolour.

---

examples/lines_bars_and_markers/timeline.py
examples/showcase/bachelors_degrees_by_gender.py
examples/statistics/customized_violin.py
lib/matplotlib/axes/_base.py
lib/matplotlib/axes/_subplots.py
lib/matplotlib/testing/jpl_units/StrConverter.py
lib/matplotlib/tests/test_bbox_tight.py
lib/matplotlib/tests/test_polar.py
lib/matplotlib/tests/test_subplots.py
lib/matplotlib/tests/test_ticker.py
lib/mpl_toolkits/tests/test_axes_grid1.py

We're already largely doing this in code base and examples.
This PR changes some remaining usages and discourages the use of the
getters in their docstrings. For now I'm not going so far as to deprecate the
methods. Keeping them around does little harm.
*Note on API consistency*: While we generally use getters, I'm not too
worried that people may find this inconsistent. An axis is rather a
sub-part than a property. In particular, it will mostly be used as an
indirection to one of its properties, i.e. `ax.xaxis.get_units()`.
Here we still have a final getter call. IMHO it even looks better / more
pythonic than a method chain: `ax.get_xaxis().get_units()`.
I'm also not too worried that people may try to overwrite the plain
attributes `Axes.x/yaxis`. While one could turn them into properties …

Use attributes Axes.x/yaxis instead of Axes.get_x/yaxis()

---

doc/api/next_api_changes/deprecations/18680-AL.rst
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/backends/backend_wxagg.py
lib/matplotlib/backends/backend_wxcairo.py

- Deprecate origin kwarg to wx gui_repaint().  It's really just a
slightly obscure way to add a special-path for the (long deprecated)
wx backend, which can be done more explicitly.
- Deprecate unused NavigationToolbar2Wx.get_canvas.

wx backend API cleanups.

---

lib/matplotlib/_mathtext.py
lib/matplotlib/_mathtext_data.py

The `use_cmex` flag and `latex_to_cmex` table is a
fallback-to-computermodern mathtext system that is strictly less
powerful than the `mathtext.fallback_to_cm` (now `mathtext.fallback`)
system.  Also, the `latex_to_cmex` table was incomplete.
Previously, with something like
```
rcParams["mathtext.fontset"] = "custom"; figtext(.5, .5, r"$\leftangle\langle$")
```
`\leftangle` would get unconditionally replaced by a Computer Modern
glyph, whereas `\langle` would stay as DejaVu Sans (as DejaVu provides
that glyph).  With this patch, both glyphs now use DejaVu.
Conversely, if one forces the use of a font which does not contain the
`\langle` glyph (e.g. adding `rcParams["mathtext.rm"] = "Comic Sans
MS"`), then both `\leftangle` and `\langle` get substituted to use
Computer Modern; this is not …

Remove the use_cmex font fallback mechanism.

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/contour.py

Remove extra newlines in contour(f) docs.

---

examples/misc/custom_projection.py
lib/matplotlib/__init__.py
lib/matplotlib/artist.py
lib/matplotlib/axes/_base.py
lib/matplotlib/contour.py
lib/matplotlib/projections/geo.py
lib/matplotlib/projections/polar.py
lib/matplotlib/streamplot.py
lib/mpl_toolkits/mplot3d/axes3d.py

Large parts of the code base already use that phrase. Let's get the rest of in line.
This is more natural language than "Return True if", and it includes the negative outcome, which the latter technically does not.

Use "Return whether ..." docstring for functions returning bool

---

examples/images_contours_and_fields/image_nonuniform.py

add_image sets up a few additional things on the artist (it makes
`remove()` work and generates a label), and avoids directly manipulating
the `.images` attribute, which may become read-only in the future (#18216).

Use ax.add_image rather than ax.images.append in NonUniformImage example

---

examples/animation/double_pendulum.py

I have added a plot of the trajectory of the endpoint of the double pendulum. This illustrates nicely the chaotic behavior of the pendulum.

Added the trace plot of the end point

---

lib/matplotlib/image.py

Currently NonUniformImage just inherits get_cursor_data from the base
class, resulting in nonsensical cursor info.  While properly
implementing NonUniformImage.get_cursor_data would be better, at least
we can disable cursor info in the meantime.

Disable mouseover info for NonUniformImage.

---

lib/matplotlib/backends/backend_nbagg.py
lib/matplotlib/backends/web_backend/js/mpl.js
lib/matplotlib/backends/web_backend/js/nbagg_mpl.js

Theoretically, this would be a bit faster perhaps, but I don't think I noticed. Maybe could get a What's new, but only if its effects are apparent?
Fixes #4382.

Support binary comms in nbagg.

---

lib/matplotlib/tests/test_animation.py

xref https://github.com/ImageMagick/ImageMagick/issues/2720
This should un-break OSX on azure and travis, prevent breakage on other CI as the imagemagick update makes its way through packaging.

TST: skip if known-bad version of imagemagick

---

doc/users/next_whats_new/date_usetex.rst
lib/matplotlib/dates.py
lib/matplotlib/tests/test_dates.py

Support usetex in date Formatters

---

doc/api/next_api_changes/deprecations/18687-AL.rst
lib/matplotlib/backends/backend_ps.py

The conversion functions (which is the only thing GraphicsContextPS
adds) are really internal to the PS format and can be done at the
renderer level instead, saving the need for an separate GraphicsContext
subclass.

Deprecate GraphicsContextPS.

---

lib/matplotlib/ticker.py

Add some docs to `LogLocator`. I don't have the time right now to figure out all the corner cases of how the other parameters work, but I think this is strictly speaking an improvement.

DOCS: document log locator's `numticks`

---

.github/workflows/reviewdog.yml

See GitHub's post about switching away from add-path:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
- [n/a] Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and run `flake8 --docstring-convention=all`).
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst …

Fix deprecation warning in GitHub Actions.

---

lib/matplotlib/_mathtext.py
lib/matplotlib/animation.py
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_cairo.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/cbook/deprecation.py
lib/matplotlib/contour.py
lib/matplotlib/texmanager.py
lib/matplotlib/widgets.py
lib/mpl_toolkits/mplot3d/axes3d.py

This lets us write deprecated properties with single-line lambdas, which
is quite a bit more compact (as shown by the line diff).

Shorter property deprecation.

---

lib/matplotlib/axis.py

These privates attributes were used prior to c3f87d4 to coordinate with
the tick sub-components instantiation machinery, but now that ticks
subcomponents are immediately instantiated, the private attributes have
become unused.

Remove some unused tick private attributes.

---

.github/workflows/cibuildwheel.yml

This updates PyPy, and so should [fix v.3.3.x wheels on macOS](https://github.com/QuLogic/matplotlib/runs/1278690889?check_suite_focus=true).
While that also adds 3.9 support, we currently will skip it until NumPy releases its wheels. …

Update to latest cibuildwheel release.

---

lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/matplotlib/tests/test_axes.py
lib/mpl_toolkits/axisartist/axislines.py

Remove the separate _gridOnMajor/_gridOnMinor attributes and store
visibility together with all other grid attributes in the
_major_tick_kw/_minor_tick_kw dicts under the "gridOn" key.  This makes
it possible to update just that entry in `Axis.grid`.
Also, don't normalize `b` to True `if len(kwargs)` in `Axes.grid`:
we need to keep it as `None`, normalizing it only to True/False in
`Axis.grid` (which handles that just fine), so that `Axis.grid` can
handle the consistency checks between `b` and `visible`.
Closes https://github.com/matplotlib/matplotlib/issues/18758.

Support `ax.grid(visible=<bool>)`.

---

lib/matplotlib/tests/test_ticker.py
lib/matplotlib/ticker.py

If we have both a small target number of ticks and a small displayed
range we would previously pick a tick stride that was the same size or
bigger than the visible data range which would result in only 1 tick
being visible on the axis.
This patch ensures that, with a floor at 1, the stride is smaller than
the estimated data range.
re-closes #8768  (same symptoms, different cause)
attn @aggna

FIX: make sure we have more than 1 tick with small log ranges

---

doc/api/colors_api.rst
doc/users/next_whats_new/centerednorm.rst
lib/matplotlib/colors.py
lib/matplotlib/tests/test_colors.py
tutorials/colors/colormapnorms.py

Adds `SymNorm`, a new norm that automatically creates linear colormaps that are symmetrical around a center. Useful for symmetrical data and in combination with diverging colormaps.
I often create plots where I want the color norm to be symmetric around a center, typically for visualizing anomalies. I tend to use one of the diverging colormaps and I often end up with code like this, where the norm is adjusted after creating the plot to make it symmetric:
```
pc = ax.pcolormesh(...)
vmax = max(-pc.norm.vmin, pc.norm.vmax)
pc.norm.vmin = -vmax
pc.norm.vmax = vmax
```
While the above is not a long piece of code, its more elegant to achieve the same goal automatically using a new norm. This approach also has the advantage of easily being able to set a center different from 0 (using, e.g.: …

Enh: SymNorm for normalizing symmetrical data around a center

---

lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/matplotlib/tests/test_axes.py
lib/mpl_toolkits/axisartist/axislines.py

Conflicts are in Axes, due to `cbook` -> `_api`, and in `test_axes` due to minor cleanups of `subplots` and extraneous parentheses. There should not have been any functional conflicts.

Backport PR #18769 on branch v3.3.x

---

doc/users/next_whats_new/2019-06-28-AL.rst
examples/images_contours_and_fields/image_masked.py
examples/images_contours_and_fields/quadmesh_demo.py
examples/specialty_plots/leftventricle_bulleye.py
lib/matplotlib/colors.py
lib/matplotlib/tests/test_image.py
tutorials/colors/colorbar_only.py

See changelog.  See also the number of explicit copies in the examples,
which suggest that the old setter-based API is a bit of a footgun (as
forgetting to copy seems easy).

Add a helper to copy a colormap and set its extreme colors.

---

lib/matplotlib/axes/_axes.py

Precedence of edgecolor and edgecolors in scatter() documentation was incorrect. This changes the documentation to match the observed precedence.
Issue #18392 

Fix documentation of edgecolors precedence for scatter()

---

examples/subplots_axes_and_figures/zoom_inset_axes.py

Adds an `edgecolor='black'` to the inset indicator in the example. 
I learned how to do this earlier today and actually didn't realize from the example that there was already an inset indicator because I didn't notice it on account of it being so faint against the background. So I ended up googling something and then fond the api of `indicate_inset`. I think with this change I would have done all my learning from this example.
original:
this pr:
**Ancillary suggestion:** Change the default value of `edgecolors` from `'0.5'` to `'gray'`
https://github.com/matplotlib/matplotlib/blob/db6206d2318375707341c89b9b0de2f4771fb373/lib/matplotlib/axes/_axes.py#L355-L357
I actually didn't know you could specify colors like this in matplotlib and then got very confused when I got an error when I …

Make inset indicator more visible in the example

---

doc/api/next_api_changes/deprecations/18302-ES.rst
lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/mplot3d/axes3d.py
lib/mpl_toolkits/mplot3d/axis3d.py

There's no need to do so, as artists have `.axes` property from which they can get the same information. Since this is a weird internal undocumented draw thing, I'm not sure if it needs a deprecation/API note.

Remove 3D attributes from renderer

---

doc/api/next_api_changes/deprecations/18798-JKS.rst
lib/matplotlib/mathtext.py
lib/matplotlib/tests/test_backend_ps.py

Deprecate ps.useafm for mathtext

---

doc/users/next_whats_new/2019-06-28-AL.rst
examples/color/custom_cmap.py
examples/subplots_axes_and_figures/colorbar_placement.py
lib/matplotlib/tests/test_colors.py
lib/matplotlib/tests/test_image.py

- Minor style fix for #14645 (Don't use links in titles)
- Use `cmap` as a canonical variable name for a colormap, not `cm`. --> More readable; and we do it in most places already. This fixes the few remaining places.

Cmap cleanup

---

doc/api/next_api_changes/behavior/18772-BGB.rst
lib/matplotlib/tests/test_tightlayout.py
lib/matplotlib/text.py
lib/matplotlib/tight_layout.py

In short, there is a difference between our treatment of `Annotation` objects at draw time versus when computing `get_tightbbox`.
If <strike>a `Text` is the empty string `''`, or</strike> an `Annotation` has `annotation_clip=None` and its position (*in data space*) is outside the data limits of its parent `Axes`, then that annotation is simply not drawn (`Annotation.draw` simply returns immediately). 
On the other hand, this check is missing `Annotation.get_window_extents`. `Annotation.get_tightbbox` should check for this condition and return a `Bbox.null`, so that e.g. `tight_layout` correctly excludes them from the `Bbox` calculation.
Edit: The bug this is solving is that 
```python
ax.annotate('test', xy=[-1, -1])
plt.tight_layout()
```
returns 
instead of …

BF: text not drawn shouldn't count for tightbbox

---

lib/matplotlib/backends/backend_wx.py

Remove unused wx private attribute.

---

lib/matplotlib/figure.py

Towards #18726
- [N/A ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [N/A ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

DOC Use 'Axes' instead of 'axes' in figure.py

---

lib/matplotlib/cbook/__init__.py

This behavior is actually relied upon in some parts of the codebase, so
let's just document it.

Clarify behavior of CallbackRegistry.disconnect with nonexistent cids.

---

lib/matplotlib/tests/test_ticker.py
lib/matplotlib/ticker.py

Changes `coeff` computation in `LogFormatter.__call__`, `LogFormatterMathtext.__call__`, and `LogFormatterSciNotation` to avoid underflow/overflow and adds a simple test.
Closes #18800.

Change LogFormatter coeff computation

---

examples/statistics/time_series_histogram.py

Follow up to issue #18643. This PR seeks to add an example to the gallery which shows an alternative way to visualize time series by reinterpreting them as 2d histograms, allowing for
1. faster plotting of large numbers of time series
2. easier identification of temporal patterns even under overwhelming noise
The example script generates a plot like the following, where a sinusoidal signal is visible in the 2nd/3rd plots despite large amounts of noise:
- [N/A] Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and run `flake8 …

Time series histogram plot example

---

lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/tests/test_backend_pgf.py

Closes the second half of https://github.com/matplotlib/matplotlib/issues/18808.

Warn in pgf backend when unknown font is requested.

---

doc/users/event_handling.rst

Let's make it future-proof against qt6 as well...

Update Qt version in event handling docs.

---

lib/matplotlib/dates.py

Closes #18743
`date2num` was slowed down for long lists of datetime. This pr simply tries to convert them to datetime64 before we convert to a num which seems fast.
I think that if we had a list of date times with timezones it would still be quite slow, but this fixes the naive-datetime case.  Open to better suggestions..
```python
import matplotlib.dates as mdates
import matplotlib.units
import datetime
import time
def datetime_range(startDate, endDate, deltaDate):
current = startDate
while current < endDate:
yield current
current += deltaDate
return
listOfDates = [date for date in datetime_range(datetime.datetime(2020, 1, 1, 0, 1),
datetime.datetime(2020, 12, 31, 23, 59),
datetime.timedelta(minutes=1))]
start = time.perf_counter() …
```

FIX: improve date performance regression

---

lib/matplotlib/tests/test_text.py
lib/matplotlib/text.py

We take in a dictionary (called kwargs rather than collecting kwargs)
which we mutate in the method.  We pop bbox and fontproperties keys
out of the user supplied dictionary (to make sure the precedence and
default behaviors are correct) which is propagated back out to user
code.
This makes an internal copy of the dictionary before we mutate it.
closes #18838
@shevawen Can you please confirm that this fixes your problem?

MNT: make sure we do not mutate input in Text.update

---

lib/matplotlib/_layoutgrid.py
lib/matplotlib/_mathtext.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/collections.py
lib/matplotlib/dates.py
lib/matplotlib/patches.py
lib/mpl_toolkits/mplot3d/axes3d.py

numpydoc style requires a space between parameter name and colon.

Fix sphinx formatting issues

---

lib/matplotlib/tests/test_text.py
lib/matplotlib/text.py

Backport PR #18839 on branch v3.3.x

---

examples/axes_grid1/demo_anchored_direction_arrows.py
examples/axes_grid1/demo_axes_divider.py
examples/axes_grid1/demo_axes_grid2.py
examples/axes_grid1/demo_axes_rgb.py
examples/images_contours_and_fields/barb_demo.py
examples/text_labels_and_annotations/demo_text_path.py
examples/text_labels_and_annotations/demo_text_rotation_mode.py
examples/text_labels_and_annotations/fancyarrow_demo.py
examples/text_labels_and_annotations/fancytextbox_demo.py
examples/text_labels_and_annotations/mathtext_demo.py
examples/text_labels_and_annotations/stix_fonts_demo.py
examples/ticks_and_spines/colorbar_tick_labelling_demo.py
examples/ticks_and_spines/date_demo_rrule.py
examples/ticks_and_spines/spine_placement_demo.py
examples/user_interfaces/wxcursor_demo_sgskip.py
examples/userdemo/connectionstyle_demo.py
examples/widgets/lasso_selector_demo_sgskip.py
examples/widgets/polygon_selector_demo.py
examples/widgets/slider_demo.py

In the context of example titles "Demo" is a fill word without meaning. All examples are demos.
This PR removes some usages of "Demo". If possible, the title is changed to something more meaningful. (Which is also the reason, I'm only doing part of the examples. Good titles need a bit of thought for every single case).

Remove "Demo" from example titles

---

lib/matplotlib/tests/test_backend_pgf.py

Slightly compress down the pgf tests.

---

lib/mpl_toolkits/axes_grid1/axes_rgb.py

Indent the ASCIIart so that it gets rendered as is.
(Current misrendering: https://matplotlib.org/api/_as_gen/mpl_toolkits.axes_grid1.axes_rgb.RGBAxes.html#mpl_toolkits.axes_grid1.axes_rgb.RGBAxes).

Fix RGBAxes docs markup.

---

lib/matplotlib/font_manager.py

- Indicate each default property when it occurs, rather than at the end
(where it's unclear what each instance of "normal" means); also fix
the default size.
- List supported math_fontfamilies using the same inline list as other
properties, which avoids having `and` getting highlighted as a Python
keyword in the rendered docs.

Reword FontProperties docstring.

---

lib/matplotlib/colorbar.py

Closes https://github.com/matplotlib/matplotlib/issues/18595
This preserves the existing behaviour without a deprecation warning.  The existing behaviour is highly questionable, but...

FIX: stop deprecation message colorbar

---

lib/matplotlib/colorbar.py

Backport #18860 on branch v3.3.x

---

lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/backends/backend_qt5agg.py
lib/matplotlib/backends/backend_qt5cairo.py
lib/matplotlib/backends/qt_compat.py

setDevicePixelRatioF never existed, per https://github.com/matplotlib/matplotlib/pull/15656#issuecomment-712934812.  I'll let @timhoffm sort out the situation wrt devicePixelRatioF :) (https://github.com/matplotlib/matplotlib/pull/15656#issuecomment-713121375)

Remove fallback to nonexistent setDevicePixelRatioF.

---

lib/matplotlib/font_manager.py

... instead of delaying it until rendering time.  This makes it
consistent with the behavior of `rcParams["font.family"]`.  (While lazy
resolution may be useful too, it seems better to be consistent with
family, whose behavior is constrained by backcompat, whereas
mathtext_fontfamily has not been released yet.)

Resolve mathtext.fontset at FontProperties creation time.

---

lib/matplotlib/animation.py

I intentionally chose a note admonition over the numpydoc `Notes` section to make this more prominent. It's a bit on the nose, but it's really something unusual and from the effect alone ("animation is not running") one cannot find the needed solution.
Closes #18893.

Add note on keeping a reference to animation docstrings

---

lib/matplotlib/tests/test_backends_interactive.py

It can apparently pass sometimes, per https://travis-ci.org/github/anntzer/matplotlib/jobs/741731058#L1951.

Unmark wx-threading-test-failure as strict xfail.

---

doc/api/next_api_changes/deprecations/18817-BGB.rst
doc/conf.py
lib/matplotlib/_api/__init__.py
lib/matplotlib/_api/deprecation.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/lines.py
lib/matplotlib/patches.py
lib/matplotlib/tests/test_api.py

Needed for #18544 (GSOD). Some new machinery was needed to add the deprecation while keeping the existing API (namely, the ability to access `validJoin` as a class property directly, i.e. `Line2D.validJoin`), so I pulled the necessary code out into this PR.
These properties already have long-existing comments marking them as "only there for backwards compatibility", and deprecation was initially suggested by @QuLogic.

MAINT: deprecate validCap, validJoin

---

doc/api/next_api_changes/behavior/18532-AL.rst
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_macosx.py
lib/matplotlib/backends/backend_nbagg.py
lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/backends/backend_webagg.py
lib/matplotlib/backends/backend_wx.py

Previously `draw_if_interactive` would call `show()` on tk and nbagg, but only
`draw_idle()` on the other backends.  I would guess this was an accident
of history.
Remove that discrepancy, and the customization point
(`trigger_manager_draw`) that I previously implemented to repro
the historical behavior. (`trigger_manager_draw` is in the private
`_Backend` class, so doesn't need a deprecation period.)

Consistent behavior of draw_if_interactive across interactive backends.

---

lib/matplotlib/axes/_base.py

This PR fixes a typo in an error message for `plt.axes()`.

Fix typo in error message: interable -> iterable.

---

lib/matplotlib/_api/deprecation.py

Clearly we're not updating the removal version dict anymore, and always
saying "removed two minor releases later" seems just fine anyways.

Remove hard-coded API removal version mapping.

---

lib/matplotlib/__init__.py
lib/matplotlib/tests/test_animation.py

7.0.10-34 is effectively a non-existent ImageMagick for us.

Move ImageMagick version exclusion to _get_executable_info.

---

lib/matplotlib/figure.py
lib/matplotlib/tests/test_figure.py

Closes #18731.
This allows
~~~
plt.subplot_mosaic("AB;CC")
~~~
instead of the verbose
~~~
plt.subplot_mosaic(
"""
AB
CC
""")
~~~

Single-line string notation for subplot_mosaic

---

doc/conf.py
doc/devel/documenting_mpl.rst
examples/animation/rain.py
examples/images_contours_and_fields/contourf_demo.py
examples/images_contours_and_fields/pcolormesh_grids.py
examples/images_contours_and_fields/pcolormesh_levels.py
examples/specialty_plots/advanced_hillshading.py
examples/style_sheets/style_sheets_reference.py
examples/subplots_axes_and_figures/secondary_axis.py
examples/text_labels_and_annotations/usetex_baseline_test.py
examples/ticks_and_spines/date_precision_and_epochs.py
examples/userdemo/colormap_normalizations.py
examples/userdemo/colormap_normalizations_symlognorm.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/cbook/deprecation.py
tutorials/intermediate/tight_layout_guide.py

Whenever possible, I removed the deprecated/warning code altogether in favor of a more "recommended" solution. Whenever the example was explicitly there to document the deprecated behavior, I made sure to ignore the warning in a way that will cause CI to break if the deprecation is carried out but the example not removed.
Only two types of warnings have to be silenced globally (importing deprecated modules in autodoc, autosummary of deprecated class properties), but I currently also manually silence `tight_layout` as a workaround until I get some clarity on #18904.
With the new configuration, any warning or error during docs build will cause CI to fail, however every warning and error will be shown in the output if there are multiple, both for gallery examples/tutorials and for API docs. …

Make docs fail on Warning (and fix all existing warnings)

---

lib/matplotlib/artist.py
lib/matplotlib/container.py

... but wrap callbacks in lambdas to maintain the old semantics of never
using weakrefs and not dropping duplicates.
Same advantages as in https://github.com/matplotlib/matplotlib/pull/18226.

Use CallbackRegistry for {Artist,Collection}.add_callback.

---

lib/mpl_toolkits/axes_grid1/parasite_axes.py

Factor out common functionality in HostAxes.twin{,x,y}.

---

.flake8
lib/matplotlib/_animation_data.py

Added aria label attributes to generated HTML to increase accessibility for screenreaders.
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow …

Added Aria-Labels to all inputs with tooltips for generated HTML animations: issue #17910

---

.github/workflows/cibuildwheel.yml

Note, this does mean that our Python 3.9 wheels will be built against NumPy 1.19, because there are no older wheels available.

Add CPython 3.9 wheels.

---

lib/matplotlib/texmanager.py
tutorials/text/usetex.py

usetex is supported by all backends (including svg and cairo), so remove
the obsolete list of backends.
Remove the separate usetex-with-unicode section: the example is actually
the same as the one just above, so add a reference to unicode there.
Many unicode characters are in fact unsupported (that's basically set by
`inputenc`).
Remove, in the tutorial, the reference to the minimum version of
GhostScript: gs9 dates back to 2010 so it's rather unlikely people are
using older unsupported versions.  In the module docstring (which serves
as actual reference), update to the actual version bound (9.0, as set in
`_get_executable_version`).
Standard capitalization/markup edits; minor rewordings.

Edit usetex docs.

---

lib/matplotlib/animation.py

Closes matplotlib/matplotlib#18891
Fixes MIME type for svg frame_format in HTMLWriter from `image/svg` to `image/svg+xml`.

Fixes MIME type for svg frame_format in HTMLWriter.

---

lib/matplotlib/font_manager.py
lib/matplotlib/tests/test_font_manager.py

See example of warning message in the test.
Closes https://github.com/matplotlib/matplotlib/issues/18926.

Improve warning message for missing font family specified via alias.

---

setup.py

Introduce variable since which mpl version the minimal python version requirement holds.
By introducing a variable instead of a hard-coded value in the error message, I hope that we remember to update `since_mpl_version` when we update `py_min_version`.
Followed from #18888, where it was noticed that the values were out of sync.

Introduce variable since which mpl version the minimal python version

---

lib/matplotlib/axes/_axes.py

On the implementation side, we can use `vlines`/`hlines` to generate the
correct `LineCollection`.
On the documentation side, it seems perfectly valid to only specify a
linestyle and no color in `linefmt` (e.g.
`stem([0, 1], [2, 3], linefmt="-.")` works just fine).  On the other
hand markers are indeed silently dropped (possibly we could emit a
warning there, but that should be another PR).  So reword accordingly;
and also slighly reword the doc for `markerfmt`.
Noted while reviewing https://github.com/matplotlib/matplotlib/pull/18310.
@timhoffm You wrote in https://github.com/matplotlib/matplotlib/pull/10154 that just setting the linestyle (`-.`) is "beyond the intention of the method" but did I miss something?

Cleanup stem docs and simplify implementation.

---

lib/matplotlib/patches.py

- No need to explicitly convert to arrays in `codes`; `concatenate`
will do that for us.
- We only need to compute the Path once at the end of the loop
(all other iterations are just thrown away).
- Both `verts` and `codes` are being concatenated along their
first axis, so using different stackers (`vstack`/`hstack`) just
hides that symmetry.

Small cleanup to StepPatch._update_path.

---

examples/lines_bars_and_markers/hat_graph.py

Extract a `hat_graph()` function, that can be readily copy/pasted by end-users.
It would also be good to have some other data semantics. Hat graphs are designed to compare datasets with respect to a reference dataset. For players A/B, it seems a bit arbitrary that Player A is considered the reference player. Unfortunately, I currently cannot think of a good domain/data semantics. Suggestions welcome.

Improve hat graph example

---

lib/matplotlib/tests/test_backend_pgf.py

- [NA] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [NA] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

added needs_ghostscript; skip test

---

doc/users/interactive.rst
doc/users/prev_whats_new/whats_new_3.3.0.rst
lib/matplotlib/gridspec.py

They're shorter, and not tied to s-g.

Replace sphinx-gallery-specific references by standard :doc: refs.

---

lib/matplotlib/pyplot.py

It is slightly inelegant for pyplot to special-case the PS backend for
fixed dpi, and anyways unnecessary because FigureCanvasPS._print_ps
forces the dpi to 72 when saving the figure anyways.  This is the same
strategy as used by the other vector backends (pdf/svg).

Remove special-casing for PostScript dpi in pyplot.py.

---

lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/matplotlib/blocking_input.py

`get_xscale()` returns "log" (lowercase) even after `set_xscale("LOG")`.
The `__name__` of `XTick`/`YTick` instances are already lowercase, no
need to lowercase them again.
Special (backspace/delete/...) keys are always in lowercase already.

Remove unnecessary calls to lower().

---

lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/tests/test_backend_pgf.py

Fixes https://github.com/matplotlib/matplotlib/issues/18826

Pgf plotting

---

doc/api/next_api_changes/deprecations/18949-TH.rst
lib/mpl_toolkits/axisartist/axis_artist.py

Due to conversion to a property, setting ZORDER now raises an error. However, before that you could set ZORDER, but it would not have had any effect. Therefore, I accept the change to raising and I do not introduce a deprecated setter property.

Deprecate AxisArtist.ZORDER

---

lib/matplotlib/contour.py
lib/matplotlib/tests/test_contour.py

`tight_layout.get_renderer()` does the right dance to set up a
renderer for any canvas.  Perhaps it also should be moved somewhere
more easily findable and it should be better disambiguated with
`backend_bases._get_renderer()`, but that can be left for another
time...
Accidentally broke this in https://github.com/matplotlib/matplotlib/pull/16171.

Fix clabel() for backends without canvas.get_renderer()

---

lib/matplotlib/pyplot.py

`plt.subplot(1, 2)` should be `plt.subplots(1, 2)`, 
otherwise raises 
`TypeError: subplot() takes 1 or 3 positional arguments but 2 were given`

Fix typing error in pyplot's docs

---

examples/images_contours_and_fields/contour_label_demo.py

Using a custom float subclass is very overkill, one can simply use a
custom formatter.
xref https://github.com/matplotlib/matplotlib/issues/18974.

Simplify contour_label_demo.

---

lib/matplotlib/backends/backend_qt5.py

In order to support fractional HiDPI without rounding, Qt 5.14 added a [new policy](https://doc.qt.io/qt-5/qguiapplication.html#setHighDpiScaleFactorRoundingPolicy), which allows `devicePixelRatioF` to actually return fractions, instead of rounded integers.
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there)

Support fully-fractional HiDPI added in Qt 5.14.

---

examples/showcase/firefox.py

In the SVG parser: simplify the regexes; do not drop "z" codes (they
were previously dropped because they are immediately followed by another
code, and thus did not match `path_re`; things only worked because the
SVG source was careful to explicitly move back to the start point before
issuing CLOSEPOLYs) but instead include them explicitly.
Don't rely on later in-place modification of `verts` propagating back to
`path`, but modify it first.
Make the figure background gray (as was the case for the classic style);
that makes the white outline visible again (otherwise that white outline
doesn't really make sense).  Also just generally compress the rest of
the code down.

Cleanup Firefox SVG example.

---

lib/matplotlib/streamplot.py
lib/matplotlib/tests/test_streamplot.py

This PR fixes #18898, adds check for strictly increasing `x` and `y` in `matplotlib.streamplot.Grid`, and adds test coverage for it.

Strictly increasing check with test coverage for streamplot grid

---

doc/api/next_api_changes/behavior/18894-AL.rst
lib/matplotlib/backends/backend_ps.py

`key scale selectfont` is literally defined as `key findfont scale
scalefont setfont`,
but "almost always more efficient" (according to the spec).
Also unify the AFM and non-AFM codepaths.
I decided to just change the behavior of `set_font` in the AFM case as
it seems unlikely people were relying on that; the alternative would be
to just completely deprecate `set_font` in favor of a new `_set_font`
with the new behavior, which in fact seems more disruptive...

Use selectfont instead of findfont + scalefont + setfont in PostScript.

---

doc/api/next_api_changes/behavior/18988-TH.rst
lib/matplotlib/artist.py

It is now a bool only. Before the default was *None* and
`Artist.set_rasterized` documented to accept *None*. However, *None*
did not have a special meaning and was treated as *False*.
This is:
- partly a documentation change: We don't document `set_rasterized` to accept *None*. However as with most bools, we just check the truthiness, so *None* is further accepted implicitly.
- a change of the default value from *None* to *False*. Technically, this is an API change. But it's very unlikely that a user will have queried `get_rasterized() is None` because *None* has no special meaning.
Because of the above I dare go without deprecation.

The Artist property rasterized cannot be None anymore

---

lib/matplotlib/backends/backend_tkagg.py

`buffer_rgba()` basically does the same from the point of view of
`_backend_tk.blit` (which will extract the buffer object from
`renderer._renderer` otherwise).
Restricting oneself to public renderer API makes it easier to use
mplcairo to patch out the agg renderer.

Don't access private renderer attributes in tkagg blit.

---

lib/matplotlib/backend_bases.py

The parameter is always a bbox, not a tuple, as shown by both all call
sites and the changelog for mpl 0.98.0 (before which it was a tuple).
Also shorten the doc for set_clip_path at the same time.

Fix the doc of GraphicsContextBase.set_clip_rectangle.

---

lib/matplotlib/__init__.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/mathtext.py
lib/matplotlib/style/core.py
lib/matplotlib/testing/__init__.py
lib/matplotlib/testing/conftest.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_cbook.py
lib/matplotlib/tests/test_mathtext.py
lib/matplotlib/tests/test_rcparams.py
lib/matplotlib/tests/test_ticker.py
lib/matplotlib/ticker.py
lib/matplotlib/widgets.py
lib/mpl_toolkits/axes_grid/parasite_axes.py
lib/mpl_toolkits/axes_grid1/parasite_axes.py
lib/mpl_toolkits/axisartist/__init__.py
lib/mpl_toolkits/axisartist/parasite_axes.py
lib/mpl_toolkits/tests/test_axisartist_axislines.py

Followup of moving all API helpers to `matplotlib._api` (#18657). 
This cleans up internal usages.

Move cbook._suppress_matplotlib_deprecation_warning() from cbook to _api

---

lib/matplotlib/backends/backend_pgf.py

This used to be required to support unicode minus (#13944), but we now strip
out the minuses ourselves (#18830).

Remove reference to unicode-math in pgf preamble.

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/tests/test_cbook.py
lib/matplotlib/widgets.py

There's quite a few places where it's natural to pass None to
normalize_kwargs, so directly support that in normalize_kwargs instead
of having to do it at each call site.

Support normalize_kwargs(None) (== {}).

---

lib/matplotlib/offsetbox.py

Just inherit the `__init__` from PackerBase, and move the docstring
there too.  Note that the old defaults (`align=None`, `mode=None`) were
invalid values (per `_get_packed_offsets`/`_get_aligned_offsets`), so it
seems reasonable to change them to the same valid ones as used by
V/HPacker (which are the only subclasses of PackerBase).

Common `__init__` for VPacker and HPacker.

---

lib/matplotlib/offsetbox.py

Also set its default to False instead of None.  (We only check
truthiness, so False and None are equivalent.)
Also don't explicitly set the default verticalalignment in textprops to
"baseline" -- that is already the normal default of `Text`, and is thus
redundant; moreover, the old implementation would cause property
collision if "verticalalignment" (fully spelt out) was passed in
instead (basically, a call to `normalize_kwargs` was missing).
Also minor misc. docstring improvements.

Better document multilinebaseline (and other small TextArea fixes)

---

doc/api/next_api_changes/deprecations/19008-AL.rst
lib/matplotlib/backend_bases.py

Calling the standard handlers (`key_press_handler`,
`button_press_handler`) directly is just fine.  If someone wants to
simulate a key or button event they should pass the event to the
CallbackRegistry (as noted in the API changes note) so that things also
work when using toolmanager.
(The wrapper methods made more sense before https://github.com/matplotlib/matplotlib/pull/17110, where they also needed to adjust the call signature.)

Deprecate event processing wrapper methods on FigureManagerBase.

---

lib/matplotlib/offsetbox.py

Improve docs of _get_packed_offsets, _get_aligned_offsets.

---

lib/matplotlib/figure.py
lib/matplotlib/gridspec.py

`GridSpec.subplots`, while user-facing, is relatively more low-level
than `Figure.subplots`, so it doesn't seem worth duplicating the
docstring in both places (I'm fine having it duplicated both in
`pyplot.subplots` and `Figure.subplots` are both are very much
user-facing).  Less duplication also means fewer chances to forget to
update the docs in all places, as was the case for the remark regarding
`set_units` (which is already present in the docs of `pyplot.subplots`,
though).
Also note that a specific check a bit further down can go away once a
deprecation elapses.

Dedupe docs of GridSpec.subplots.

---

doc/api/next_api_changes/deprecations/19019-AL.rst
lib/matplotlib/backends/_backend_tk.py

AFAICT this was present since all the way back in e34a333 but never
actually used.  The standard way of registering callbacks (either at the
Tk level or at the Matplotlib level) seems good enough.

Deprecate never used `resize_callback` param to FigureCanvasTk.

---

doc/api/next_api_changes/deprecations/19018-AL.rst
lib/matplotlib/contour.py

`get_label_coords` is clearly an internal helper to `locate_label`; e.g.
the `distances` parameter needs to be filled in with a very specific
array that's internally computed by `locate_label`.  Inline it, which
also makes clearer the possibility to save some further computation for
`locate_label` to return a linearized index (the part that was commented
"There must be a more efficient way..."; indeed converting the array to
a list of tuples to get back the index seems pretty inefficient).
Also better document the implementation of `get_label_coords` (I'm not
actually changing any of the code logic).

Inline and optimize ContourLabeler.get_label_coords.

---

doc/missing-references.json
doc/users/event_handling.rst

Much reformatting.
Remove documentation for `picker=<float>` which is deprecated in favor
of `pickradius`.
Add reference to default keymaps (closes https://github.com/matplotlib/matplotlib/issues/11472).
Modernize examples: use `pickradius`, use `subplots()` instead of
`add_subplot(111)`, etc.

Update event handling docs.

---

lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
lib/mpl_toolkits/tests/test_axisartist_grid_helper_curvelinear.py

- `np.full` already defaults to the dtype of the `value` passed in, no
need to explicitly pass it.
- `set_extremes` already normalizes None to +/-inf, no need to handle
them again in `get_tick_iterators`.  Also, `set_extremes` and
`update_lim` already clearly assume that extremes are sorted, so
unsorted extremes already break elsewhere, so no need to sort them in
`get_tick_iterators`.
- There's a public setter for extremes, no need to touch private
attributes in test_axis_direction.

grid_helper_curvelinear cleanups.

---

lib/matplotlib/axis.py
lib/matplotlib/rcsetup.py

- Validate rcParams["{x,y}tick.direction"].
- Move common validation and application to base Tick.apply_tickdir
class.  Note that previously YTick.apply_tickdir failed to
_check_in_list the tickdir value.

Better validate tick direction.

---

doc/api/next_api_changes/deprecations/19046-AL.rst
doc/missing-references.json
lib/matplotlib/animation.py

The docs only mention `finish()`; but the implementations of `finish()`
simply forwards themselves to `cleanup()` (and do a bit more).  One can
instead just put all the relevant logic in `finish()` and not expose a
separate (basically internal) API.

Prepare inlining MovieWriter.cleanup() into MovieWriter.finish().

---

lib/matplotlib/animation.py

It plays two fairly different roles in MovieWriter (it's the stdin of
the long-standing ffmpeg-like subprocess) and FileMovieWriter (it's the
ever-changing handle of the frame currently being saved), with different
life-cycles and no reuse between the subclasses, so it's easier to just
inline it at the call site (and skip a comment about how
FileMovieWriter._frame_sink gets closed in grab_frame, hinting at the
tight-coupling between the two of them).
Also, no need to close the process stdin after calling communicate() --
communicate() does it for us.

Inline MovieWriter._frame_sink.

---

lib/matplotlib/cbook/__init__.py

- Describe the signature of `exception_handler` in prose (the parameter
name is not actually relevant, nor is the return value).
- "Consuming" an exception is not a standard idiom.
- Picklability is a detail here only relevant if you want to pickle the
CallbackRegistry, and anyways it is generally true that setting an
unpicklable attribute on an otherwise picklable object will make that
object unpicklable.
- The description of the default exception handler was incorrect.

Reword docs for exception_handler in CallbackRegistry.

---

.flake8
doc/users/next_whats_new/slider_snap_to_array.rst
examples/widgets/buttons.py
examples/widgets/check_buttons.py
examples/widgets/cursor.py
examples/widgets/lasso_selector_demo_sgskip.py
examples/widgets/multicursor.py
examples/widgets/polygon_selector_demo.py
examples/widgets/radio_buttons.py
examples/widgets/rectangle_selector.py
examples/widgets/slider_demo.py
examples/widgets/slider_snap_demo.py
examples/widgets/span_selector.py
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

Closes: https://github.com/matplotlib/matplotlib/issues/18562
Adds a `valsnap` argument to the Slider widget to allow specifying the values the slider should snap to. This overrides the `valstep` argument.
I also made a new slider demo to show the use of `valstep` and `valsnap` as I think they would get lost in the current [slider demo](https://matplotlib.org/3.3.1/gallery/widgets/slider_demo.html). For a point of context I have read through the existing tutorial multiple times, but never managed to encode that `valstep` existed until I started working on this PR
- I used `searchsorted` instead of `argmin` as it is significantly faster.
- This works for `idx=0` because then the indexing just becomes `-1` and we compare the largest and smallest elements of the array.
I have a few questions …

More generic value snapping for Slider widgets

---

README.rst

Currently the link to pepy https://pepy.tech/project/matplotlib/month results in this:
The right link should be
https://pepy.tech/project/matplotlib/

Fix broken link in Readme

---

.github/workflows/tests.yml
requirements/testing/minver.txt

I don't think we've gotten back any reply from Travis yet. This ports Linux and macOS builds over to GitHub Actions; it takes roughly the same build time overall, though the queue might be shorter. I'm not entirely sure whether I used the right keys for caching or if it's really very effective yet.
I believe interactive backend tests are running though, so this should restore our code coverage results.

Start testing using GitHub Actions

---

lib/mpl_toolkits/axisartist/axis_artist.py

- As far as I can see, AxisArtist._draw_{ticks2,labels2} have never been
used, and are exactly identical to `_draw_{ticks,labels}` with the
exception that the call to `_update_{ticks,labels}` has additionally
been inlined.
- We don't need to compute the window extents in `_update_ticks` and
forward it in `_draw_ticks`: it's never used at the call sites, and
`get_tightbbox` (which is the sole consumer of this info) calls again
`major_ticklabels.get_window_extent` (as well as
`minor_ticklabels.get_window_extent`) itself.

Remove _draw_{ticks2,label2}; skip extents computation in _update_ticks.

---

doc/api/next_api_changes/deprecations/19042-AL.rst
lib/mpl_toolkits/axisartist/axislines.py
lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py

GridHelperBase.invalidate/valid and Axes.invalidate_grid_helper are
never used externally and appear to be internal.  But invalidation
doesn't need to be stored in a separate flag (`_force_update`), one can
simply reset `_old_limits` (which only serves this purpose) and unify
that with `_old_values` (which does the same).
The only `_update` method that was previously called to regenerate
invalidated grid info was `GridHelperCurveLinear._update`, which, other
than the redundant check of staleness (already done in `_update_lim`),
just forwarded to `_update_grid`, so get rid of `_update` and just
stick to `_update_grid`.

Simplify GridHelper invalidation.

---

tutorials/intermediate/autoscale.py

I hope I have covered basic usage of autoscaling. Maybe there is a need to go more into details, but I suggest to do it in another tutorial, along with suggestions from #18401 
Closes #17417 

Add tutorial about autoscaling

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/image.py

It is implemented but was left out of the list of methods the
interpolation parameter for `imshow()` and `AxesImage()`.

DOC: Add 'blackman' to list of imshow interpolations

---

lib/matplotlib/projections/geo.py

- Use np.sinc instead of rewriting it ourselves.  (This way, if numpy
ever switches sinc to C, we get the speedup too.)
- Make InvertedAitoff return nan (which is clearly suggests "we can't
compute this") instead of being a noop (which makes it return
nonsensical data with no user warning).  AFAICT this is only used
to print mouseover coordinates.  See e.g.
`subplots_axes_and_figures/geo_demo.py` where the mouseover
coordinates for aitoff were just completely wrong.

Small improvements to aitoff projection.

---

lib/matplotlib/axes/_axes.py

We don't remove zero-count patches, as can easily be checked with e.g.
`print(hist([0, 0, 0, 10], 10, log=True))`.  The incorrect statement
came in in f24d06c, but it is clear that that patch did not implement
that behavior, instead filtering out such patches in
`_update_patch_limits`.

Remove incorrect statement about `hist(..., log=True)`.

---

lib/matplotlib/backend_bases.py

Closes #7238 (I can't think of other places where we could mention this...).

Mention in a few more places that artists default to not-pickable.

---

lib/matplotlib/colors.py

Some norms now have "scales" associated with them.  This PR adds `self._scale` to `class Normalize`.  This is carved off #18900, and this attribute gets used by colorbar now.

FIX: add a default scale to Normalize

---

.github/workflows/tests.yml
.travis.yml
requirements/testing/minver.txt
requirements/testing/travis36minver.txt

Note, at some point on `master`, the requirements file was renamed from `travis36minver.txt` to `minver.txt`, so I did that in this PR as well to reduce differences between the branches.
It also runs slightly different Python versions, since older Python is still supported for this branch.

Backport PR #19036 on branch v3.3.x

---

lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/matplotlib/tests/test_scale.py

Currently `axis.set_scale` cannot accept an instance of `ScaleBase` as an argument.  This PR makes that possible.  Needed for #18900, but this seems generally useful.

ENH: allow passing a scale instance to set_scale

---

examples/statistics/confidence_ellipse.py

When I first created this example I stated that a plotted ellipse of e.g. 3 standarddeviations would contain 99.7% of the total observations, if the data was normally distributed.
However, this reference to the 68-95-99.7 rule does not hold with more than one dimension. I have corrected this statement and added a very brief explanation.
If you want to read more on this, please look at the comments on my [gitHub-Gist](https://gist.github.com/CarstenSchelp/b992645537660bda692f218b562d0712) on the same subject. The comments there pointed me to the issue, in the first place.
- [N/A] API changes documented in …

correct reference to 68-95-99.7% rule

---

lib/matplotlib/axes/_base.py

We forgot to add `FuncScale` to the list of scales in `set_x/yscale`

DOC: add FuncScale to set_x/yscale

---

lib/mpl_toolkits/mplot3d/axis3d.py
lib/mpl_toolkits/tests/test_mplot3d.py

Closes #19091
Old code was doing the transform by hand instead of using a transform...
Added a smoketest.  This brought up a different bug, but its separate from mplot3d...

Fix use transform mplot3d

---

src/_tkagg.cpp

Per
https://numpy.org/doc/1.17/reference/c-api.array.html#c.NO_IMPORT_ARRAY
Other extension modules in Matplotlib already use the same mechanism.

Suppress -Wunused-function about _import_array when compiling tkagg.cpp.

---

lib/matplotlib/testing/decorators.py

If we are removing ticks from all the axes in a figure, we should remove them from child axes as well.  Needed for #18900.

FIX/TST: recursively remove ticks

---

doc/missing-references.json
lib/matplotlib/animation.py

- Warn if the requested frame format is unsupported and fallback occurs.
- FFMpegFileWriter does not support 'raw' or 'rgba' (AFAICT there's no
way to forward the relevant frame size/bitdepth info).
- ImageMagickFileWriter supports 'rgba' but requires explicit frame_size
and depth to do so (they are the same as for ImageMagickWriter, and
passing them doesn't negatively impact other formats), but it does not
support 'raw' (per https://imagemagick.org/script/formats.php).
Test script:
```python
import matplotlib.animation as animation
x = np.arange(0, 2*np.pi, 0.01)
line, = ax.plot(x, np.sin(x))
def animate(i):
line.set_ydata(np.sin(x + i / 50))  # update the data.
return line,
ani = animation.FuncAnimation(
fig, …
```

Cleanup Animation frame_formats.

---

lib/matplotlib/tests/test_animation.py
lib/matplotlib/tests/test_image.py

... per https://docs.pytest.org/en/stable/usage.html#unraisable.

Fix failing animation test with pytest 6.2.

---

lib/matplotlib/backends/backend_webagg_core.py
lib/matplotlib/backends/web_backend/nbagg_uat.ipynb

Closes: https://github.com/matplotlib/matplotlib/issues/4288
Closes: https://github.com/matplotlib/ipympl/issues/228
Supersedes: https://github.com/matplotlib/matplotlib/pull/9240
I replaced the second Agg renderer by storing the previous buffer in a private attribute. Removing the second renderer as suggested by @tacaswell eliminates the the flickering issues noted in https://github.com/matplotlib/matplotlib/pull/9240#issuecomment-528170704
I also tried out a modified version of the test case by @mbewley in https://github.com/matplotlib/matplotlib/pull/9240#issuecomment-332677090 and found that performance was improved considerably when blitting was enabled.
```python
from imp import reload
import matplotlib
reload(matplotlib)
matplotlib.use('nbagg')
import …
```

Support blitting in webagg backend

---

doc/api/next_api_changes/behavior/16220-AL.rst
lib/matplotlib/backend_bases.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/figure.py
lib/mpl_toolkits/mplot3d/axes3d.py

In order to reset the mouse interaction callbacks on unpickled 3d plots,
the callback registry really needs to be on the Figure object rather
than the Canvas, because the canvas doesn't exist yet when the 3d axes
is being unpickled (it is only set on the figure at the very end of
unpickling).
So move the callback registry to the figure (with a proxy property on
the canvas).
Then, add a private mechanism to pickle select callbacks, and combine
everything together.  (Bound methods of picklable objects are picklable.)
Test with e.g.
```
import pickle
fig.add_subplot(111, projection='3d')
p = pickle.dumps(fig)
plt.close("all")
pickle.loads(p)
plt.show()
```
Closes #10843.
Goes on top of #15855.  Would also be nice to get #16219 in first and …

Fix interaction with unpickled 3d plots.

---

doc/users/next_whats_new/axline_transform.rst
examples/pyplots/axline.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/lines.py
lib/matplotlib/tests/test_axes.py

for plotting  a line through a point in axes coordinates and with a slope in data coordinates
see #18625 for details and example.

Axes.axline: implement support transform argument (for points but not slope)

---

lib/matplotlib/backends/backend_webagg_core.py

As noted in #19059, there is both a `buff` and `buf` in this function. The latter is a PNG file, so rename it to `png`.

Rename a confusing variable.

---

lib/matplotlib/axes/_base.py

Small change to take into account `transSubfigure` instead of `transFigure`...
Added a couple of documentation fixes that were in this file as well.  Breaks out some unrelated parts of #18900 to make it a tad smaller.  Also more urgent...

FIX: update a transfrom from transFigure to transSubfigure

---

doc/users/next_whats_new/2019-06-28-AL.rst
lib/matplotlib/rcsetup.py

This makes it possible to set the rcParam to a non-registered colormap
(which cannot be referred to by name).  A use-case is to set it to e.g.
`viridis.with_extremes(bad="k")`.

Support setting rcParams["image.cmap"] to Colormap instances.

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/figure.py
lib/matplotlib/table.py
lib/matplotlib/text.py

We use docstring interpolation for `Text` in quite a few places, but that is extremely hard to trace through the code.  Changed to `_Text_docst`.

FIX/DOC - make Text doscstring interp more easily searchable

---

lib/matplotlib/backends/backend_nbagg.py
lib/matplotlib/backends/backend_webagg.py
lib/matplotlib/backends/backend_webagg_core.py

FigureCanvasWebAgg and FigureCanvasNbAgg empty subclasses of
FigureCanvasWebAggCore.  They only differed in that WebAggCore did not
define the (common) timer class, which is easily fixed (but the
TimerTornado definition needs to be moved above the
FigureCanvasWegAggCore definition), and that WebAgg explicitly redefined
`show` to use the module's `show`, whereas WebAggCore's `show` uses
`pyplot.show`... but `pyplot.show` is defined as calling the backend
module's `show`, so it comes down to the same.
Still it's useful for them to be subclasses rather than straight
aliases, to keep the possibility of a canvas->manager mapping (#18854).
No need to explicitly mark WebAggCore as `supports_blit`, as that's
autodetected now (one can easily check that
`FigureCanvasWebAggCore.supports_blit` is …

Cleanups to webagg & friends.

---

lib/matplotlib/tests/test_backends_interactive.py
lib/matplotlib/tests/test_rcparams.py

Since #17396, backends now check for Wayland settings as part of headless detection. However, the headless tests do not override those settings. When running on Wayland, they thus think the display exists when they are not supposed to.

Fix headless tests on Wayland.

---

lib/matplotlib/backends/backend_wx.py

Fixes test failure on Python 3.10, https://bugzilla.redhat.com/show_bug.cgi?id=1902382

Always pass integers to wx.Size.

---

doc/conf.py
doc/sphinxext/math_symbol_table.py
tutorials/text/mathtext.py

This is a rebase of #15797, plus additional fixes for new errors and a patch for macOS font paths.

DOC: Fix latexpdf build

---

doc/devel/contributing.rst

Adds prose to docs about the "incubator" (nee `#tidepool`) discussed on the call.
The purpose of this channel is that, operating on the theory than the hardest PR to a project is the first, is to provide some mentoring / support to people who want to become regular contributors but do not know where to start.
The other issue I think we have in the user -> first PR -> multiple PR -> reviewer pipeline as that we can not tell who of our first time contributors wants to become a regular contributor and who is doing a drive-by PR to scratch their itch.   This is a path where we are asking people to self-identify as wanting to be come regular contributors.

DOC: contributor incubator

---

doc/conf.py
tutorials/text/mathtext.py

These are the minimum changes necessary to get the PDF building again.

Backport latexpdf fixes to v3.3.3-doc

---

lib/matplotlib/backends/web_backend/js/mpl.js

Sending the pixel ratio in initialization fails because the WebSocket is not open yet; this is already sent in the `onopen` handler, so just remove it from initialization.
Also, fix a similar bug in sending resizes too early. This one is non-fatal because it is in an async handler.

Fix WebAgg initialization

---

lib/matplotlib/figure.py

Docstring substitution uses %-formatting, not {}-formatting.

Fix the docstring of suptitle/subxlabel/supylabel.

---

lib/matplotlib/animation.py
lib/matplotlib/tests/test_animation.py

This could maybe be tested, but I think maybe after the cleanup from #19044.
Additionally, copy the logging setting that is done in `FFMpegWriter._args`.

Support raw/rgba frame format in FFMpegFileWriter

---

lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/backends/backend_qt5agg.py
lib/matplotlib/backends/backend_qt5cairo.py
lib/matplotlib/tests/test_backend_qt.py

With this, we don't need to check things on every draw, but can instead rely on Qt telling us to update DPI.
This also fixes the pixel ratio test, which has never really worked for me. Hopefully it is not broken elsewhere.

Use Qt events to refresh pixel ratio.

---

lib/matplotlib/_api/__init__.py
lib/matplotlib/_api/deprecation.py
lib/matplotlib/_mathtext.py
lib/matplotlib/animation.py
lib/matplotlib/axis.py
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/cm.py
lib/matplotlib/image.py
lib/matplotlib/offsetbox.py
lib/matplotlib/patches.py
lib/mpl_toolkits/axes_grid1/axes_grid.py

Followup of moving all API helpers to `matplotlib._api` (#18657). 
This changes internal usages:
- `cbook._deprecate_method_override` -> `_api.deprecate_method_override`
- `cbook._deprecate_privatize_attribute` -> `_api.deprecate_privatize_attribute`

Move from cbook._deprecate_*() to _api.deprecate_*()

---

lib/matplotlib/axes/_base.py
lib/matplotlib/lines.py
lib/mpl_toolkits/mplot3d/axes3d.py

Make the `units finalize` event handlers picklable, and request that
they be restored upon unpickling.
I have yet to see a case where the unit change handlers actually have an
observable effect, but at least this seems theoretically more correct...
Followup to https://github.com/matplotlib/matplotlib/pull/16220.

Don't lose unit change handlers when pickling/unpickling.

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/cbook/__init__.py

Followup of moving all API helpers to matplotlib._api (#18657).

Move from @cbook._classproperty to @_api.classproperty

---

lib/matplotlib/dates.py
lib/matplotlib/tests/test_dates.py

Currently ConciseDateFormatter includes redundant offset text when largest scale is in months or years. This PR suppresses this behaviour and closes #19118.

FIX: suppress offset text in ConciseDateFormatter when largest scale is in years

---

lib/matplotlib/tests/test_backend_pdf.py

Apparently sys.getsizeof(io.BytesIO(...)) doesn't work on PyPy, and
anyways it's a rather strange way to compute the length of a buffer.
See https://github.com/matplotlib/matplotlib/issues/19160.

Simplify test_backend_pdf::test_multipage_properfinalize.

---

doc/conf.py
doc/users/prev_whats_new/github_stats_3.3.0.rst

There is a small typo in doc/conf.py.
Should read `backslashes` rather than `backslahes`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, backslahes -> backslashes

---

doc/missing-references.json

These are already ignored using a shorter path, so just ignore them when using the full import path as well.
I can't reproduce locally, but adding these doesn't break anything for me, and hopefully fixes CI.

Ignore missing _FancyAxislineStyle doc targets.

---

lib/matplotlib/animation.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/tests/test_image.py

Backport PR #19108 on branch v3.3.x
In contrast to the original PR, no changes in tests are needed because we did not have tests that would trigger the warning back in 3.3.x.

Backport PR #19108 on branch v3.3.x

---

doc/devel/index.rst
doc/devel/triage.rst

This adds documentation to add a "triage team" to our organization as discussed on today's call.  The purpose of this is to:
- provide a low barrier to formally recognize users as contributing to the maintenance of Matplotlib  (by giving them power and responsibility)
- empower more people to help where they are willing and able
- to incentive more people to triage issues
- (secondary) provide a ramp / pipeline to contributing PRs (and reviewing PRs!) for new contributors
This text is based on https://scikit-learn.org/dev/developers/bug_triaging.html  and modified to better fit Matplotlib.
Task that need to be done immediately  outside of a PR if we merge this:
- create triage_team in the github ACL system (I think only me @dopplershift and @efiring can currently do that?) with triage …

GOV/DOC: add section to docs on triaging and triage team

---

.github/workflows/pr_welcome.yml

Not sure how to test this?  
Below the line is how I think this should render:
--------
Thank you for opening your first PR into Matplotlib!
If you have not heard from us in a while please feel free to ping `@matplotlib/developers` or anyone who has commented on the PR.  Most of our reviewers are volunteers and it is easy for things to fall through the cracks.
You can also join us [on gitter](https://gitter.im/matplotlib/matplotlib) if real-time discussion would be useful.
For details on testing, write docs, and our review process please see [the developer guide](https://matplotlib.org/devdocs/devel/index.html)
We strive to be a welcoming and open project, please follow our [Code of Conduct](https://github.com/matplotlib/matplotlib/blob/master/CODE_OF_CONDUCT.md).

CI: add github action to post to first-time PRs openers

---

lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_axes.py

CLOSEPOLY verticies are not actual points in a path, but _update_patch_limits uses them anyhow when computing dataLim. This patch removes the CLOSEPOLY vertices from the list of vertices used in the computation. Fixes #19078. 

Ignore CLOSEPOLY vertices when computing dataLim from patches

---

lib/matplotlib/_mathtext.py
lib/matplotlib/animation.py
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/_backend_pdf_ps.py
lib/matplotlib/backends/backend_cairo.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/backends/qt_compat.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/contour.py
lib/matplotlib/mathtext.py
lib/matplotlib/sphinxext/plot_directive.py
lib/matplotlib/texmanager.py
lib/matplotlib/ticker.py
lib/matplotlib/widgets.py
lib/mpl_toolkits/mplot3d/axes3d.py

Followup of moving all API helpers to matplotlib._api (#18657).

Deprecate @cbook.deprecated and move internal calls to @_api.deprecated

---

doc/users/next_whats_new/multiple_labels_for_Axes_plot.rst
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_legend.py

Since plt.plot() supports multidimensional input it would be reasonable to support multiple labels. 
It was mentioned on SO [here](https://stackoverflow.com/questions/11481644/how-do-i-assign-multiple-labels-at-once-in-matplotlib).
```python
x = [1, 2, 5]
y = [[2, 4, 3],
[4, 7, 1],
[3, 9, 2]]
plt.plot(x, y, label=['one', 'two', 'three'])
plt.legend()
```
It works with all iterable types, with string instances and non-iterables the behavior is just the same as before.

Add multiple label support for Axes.plot()

---

doc/api/next_api_changes/behavior/18127-ES.rst
doc/api/prev_api_changes/api_changes_3.2.0/behavior.rst
lib/matplotlib/tests/test_axes.py
lib/mpl_toolkits/mplot3d/axes3d.py
lib/mpl_toolkits/tests/test_mplot3d.py

Since `Axes3D` derives from 2D `Axes`, this lazy autoscale was partially implemented. This might cause extraneous re-scaling since the 3D case did not always turn it off. It might also cause re-scaling to be missed since 2D `Axes` does not check z.
Fixes #18112.
This is a regression in 3.2.0 when lazy autoscaling was put in, but it's half a new feature, so I'm not sure if it belongs in 3.3.1. ~~I should probably figure out how to update a test for this, and write an API change to match the 2D case.~~

Implement lazy autoscaling in mplot3d.

---

lib/matplotlib/collections.py

In response to #19168. Hopefully this is now better to understand.

Clarify meaning of facecolors for LineCollection

---

lib/matplotlib/tests/test_backend_qt.py
lib/matplotlib/tests/test_determinism.py
lib/matplotlib/tests/test_matplotlib.py
lib/matplotlib/tests/test_sphinxext.py

When running headless or with an unavailable backend set in `matplotlibrc`, some tests fail when they shouldn't. These tests should either use Agg, or be skipped.

Ensure backend tests are skipped if unavailable

---

doc/devel/coding_guide.rst

While responding to a question on the mailing list I discovered we had never removed the 2.2.x branches from the docs, this does so.
We also still have the 2.2.x and 2.2.5-doc branches on the repo, I'm inclined to drop those now as well.

DOC: remove reference to 2.2.x branches from list of active branches

---

doc/users/next_whats_new/range_slider.rst
examples/widgets/range_slider.py
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

Closes: https://github.com/matplotlib/matplotlib/issues/18563
Creates a SliderWidget that has a movable min and movable max. This enables doing things like this:
The `RangeSlider` is as analogous to `Slider` with the major difference being that `val` is an array rather than a float. To accomplish this I made a new class `_SliderBase` that both the sliders inherit their callback and other shared functionality from. 
- Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).

Create a RangeSlider widget

---

lib/matplotlib/testing/decorators.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_testing.py

xref https://github.com/matplotlib/matplotlib/issues/18581. Perhaps this should be a warning instead to start with in case anyone else is using this function outside of MPL?

Check that no new figures are created in image comparison tests

---

lib/mpl_toolkits/axisartist/axis_artist.py

Issue - The axisartist.axis_artist docs page has a typo: ax.axis["bottom"].major_ticks.set_ticks_out(True) should be ax.axis["bottom"].major_ticks.set_tick_out(True) (remove 's' after 'tick' in 'set_tick_out')
Fixed it by removing the s
closes #19100

Fixed part of Issue - #19100, changed documentation for axisartist

---

lib/matplotlib/quiver.py

Fix trivial quiver doc typo.

---

lib/matplotlib/testing/compare.py

Cache autocleanup was implemented in https://github.com/matplotlib/matplotlib/pull/15932.

Fix incorrect statement regarding test images cache size.

---

lib/matplotlib/tri/triangulation.py

xref https://github.com/matplotlib/matplotlib/issues/18946. I'm not sure this fixes the issue, but it:
- Documents the triangles parameter
- Removes duplicated documentation for two attributes that are really properties, and therefore have their own property docstrings.

Document Triangulation.triangles

---

INSTALL.rst
doc/faq/installing_faq.rst

This PR tries to consolidate the install from source docs in FAQ section and INSTALL.rst according to the issue #17327

Consolidated the Install from Source docs

---

.github/workflows/pr_welcome.yml

The welcome message seems to be working now (see https://github.com/matplotlib/matplotlib/pull/19210#pullrequestreview-560512912) but it is very compressed.  Try to add more white space in the workflow to see if that will render nicer.

MNT: try to put more whitespace in welcome message

---

doc/devel/release_guide.rst

It had one level "All Releases" which has no siblings. That made TOCs a bit harder to read than necessary:

Remove one TOC level from the release guide

---

lib/matplotlib/sphinxext/__init__.py
lib/matplotlib/sphinxext/plot_directive.py
lib/matplotlib/sphinxext/static/plot_directive.css
lib/matplotlib/tests/test_sphinxext.py
lib/matplotlib/tests/tinypages/some_plots.rst

Currently, non-sphinx-gallery plots in the documentation (for example, from a `.. plot::` directive in a docstring) produce plots that do not scale with screen size. This means that on e.g. phones, the plots get chopped off, as seen here:
Other Sphinx extensions (gallery, the inheritance diagram extension, etc) add their own custom CSS to make the images fit in the page. I copied the approach taken by `sphinx.ext.graphviz` to get the following result:
This became increasingly important for my GSOD work (e.g. #18544, where the API docs center around the inclusion of a "demo" figure showing the various options).
Edit: additionally, I had to fix an existing bug in `plot_directive.TEMPLATE` that caused Sphinx to warn (failing our tests) whenever there is both a caption and a custom class …

Give plot_directive output a `max-width: 100%`

---

doc/api/next_api_changes/deprecations/19176-AL.rst
lib/mpl_toolkits/mplot3d/axes3d.py

Previously, a 4th positional parameter to plot_surface would be
nonsensically interpreted as the `sizes` property of the PolyCollection,
and a 4th positional parameter would be interpreted as the `linewidths`
of the LineCollection, which is more useful but not so obvious.
Instead, deprecate these uses (one can still set these using keyword
arguments), in preparation of overloading these functions as
`plot_{surface,wireframe}([X, Y], Z)` instead (i.e., defaulting X and Y
to the correct meshgrid, similarly to what we already do e.g. for
the 2D `pcolor`-style functions).

Deprecate additional positional args to plot_{surface,wireframe}.

---

lib/matplotlib/axes/_axes.py

I noticed in https://github.com/matplotlib/matplotlib/pull/19214 that `pie()` doesn't currently request an autoscale at the end, but it probably should to fall in line with the rest of the `Axes` plotting methods. This is needed in https://github.com/matplotlib/matplotlib/pull/19214 to make some of the pie chart limits more sensible, but I thought it was orthogonal enough to warrant a separate PR.

Request an autoscale at the end of ax.pie()

---

lib/matplotlib/axes/_base.py
lib/matplotlib/collections.py
lib/matplotlib/path.py
lib/matplotlib/tests/test_collections.py
lib/matplotlib/transforms.py
src/_path_wrapper.cpp

This is an attempt to fix #16552. I'm not sure if it's the best change, API-wise, but seems to work without breaking anything. Possibly could do with an API change note.
Essentially, we have the right information to do log auto-scaling correct, but that's thrown away at the `Collection.get_datalim`/`Axes.add_collection` interface. This propagates that information onto the `Bbox` that's passed between those two functions, and uses it when updating `Axes.dataLim`.

Propagate minpos from Collections to Axes.datalim

---

lib/matplotlib/image.py
lib/matplotlib/tests/test_image.py

When an image artist gets an additional transform supplied via `set_transform` or the `transform=...` argument, the data cursor will give values at the wrong coordinates. Example:
```python
from matplotlib.transforms import Affine2D
trans = Affine2D().scale(2).rotate(0.5)
im = ax.imshow(np.arange(100).reshape(10, 10),
transform=trans + ax.transData)
ax.set_xlim(-12, 20)
ax.set_ylim(-5, 30)
plt.show()
```
This happens because the current `AxesImage.get_cursor_data` uses the `xdata` and `ydata` attributes in the MouseEvent, which only undo the axis transform, but not the additional artist transform.
This PR adds a test and fixes the issue by applying the inversion of the image artists transform directly to the …

Fix data cursor for images with additional transform

---

lib/matplotlib/colors.py
lib/matplotlib/tests/test_colors.py

Closes  #19239 by processing the input for inverse as well as `__call__` for `_make_norm_from_scale`

FIX: process lists for inverse norms

---

lib/matplotlib/backends/backend_ps.py
lib/matplotlib/tests/test_backend_ps.py

The clip path/clip box were simply not set at all before.
Also move `_convert_path`/`_get_clip_cmd` (previously `_get_clip_path`)
above the block where all `draw_foo`s are defined, rather than being in
the middle of them.
Closes https://github.com/matplotlib/matplotlib/issues/4321.
Goes on top of https://github.com/matplotlib/matplotlib/pull/18894.

Set clip path for PostScript texts.

---

lib/matplotlib/path.py
lib/matplotlib/tests/test_path.py

When calculating the extents of a path, any ~MOVETO,~ CLOESPOLY, or STOP codes shouldn't be taken into account.  This is a follow up to https://github.com/matplotlib/matplotlib/pull/16832.

Ignore non-draw codes when calculating path extent

---

examples/mplot3d/pathpatch3d.py

Fix markup for mplot3d example.

---

lib/mpl_toolkits/mplot3d/art3d.py

... instead of sometimes being a list.  At least the implementation of
bar3d assumes it's always an array (#19246) (and the only other call site, in
`patch_2d_to_3d`, doesn't care).
(I didn't actually check this fixes #19246, as there's no repro.)

Make return value of _get_patch_verts always an array.

---

lib/matplotlib/backends/qt_compat.py

I'm not sure why this never triggered an error before.
But we set this environment variable by accident once and I didn't fully understand the error message.
It seems that the QT_API_ENV is expected to be lowercase, but it doesn't really convert the user's potentially uppercase option to lowercase.

handle usecase where QT_API is specified with some capitals

---

examples/subplots_axes_and_figures/secondary_axis.py

This clarifies that the mapping functions for secondary_axis need to be defined beyond the nominal plot range, which requires special care when doing ad-hoc mappings using interpolation functions.
I've also added a very brief note that at least hints at how to use ad-hoc mapping when defining the interpolation beyond the data range is impractical. I'll be the first to admit it is probably a bit too cryptic as written, but I also didn't want to add a novel.
Addresses matplotlib#19205
- [N/A ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [N/A ] New features have an entry in …

Clarify Doc for Secondary axis, ad-hoc example

---

lib/matplotlib/widgets.py

TextBox now checks for both `return` and `enter` to check for submission. On my system:
```
Thinkpad T490
PopOs 20.04 
5.8.0-7630-generic #32~1605108853~20.04~8bcf10e-Ubuntu SMP Wed Nov 11 22:42:16 UTC  x86_64 x86_64 x86_64 GNU/Linux
```
Hitting the key silkscreend as labelled `Enter` produces a KeyEvent with `event.key` of `return`
You can check this on your system with:
```python
def _keypress(event):
print(event)
print(event.key)
fig.canvas.mpl_connect('key_press_event', _keypress)
plt.show()
```
- [NA ] New features are documented, with examples if plot related.
- [NA ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- …

more robust check for enter key in TextBox

---

.github/workflows/tests.yml

This leaves us at the mercy of whenever Actions updates the formula database in the image, but also prevents it from trying to update stuff in the image that we don't want it to update.
Also, disable fail-fast.
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow …

Don't update homebrew on GitHub Actions

---

lib/matplotlib/tests/test_mathtext.py

... and let the test pass, instead of letting the test blow up and
marking them as xfail.

Use proper pytest functionality for warnings and exceptions

---

examples/widgets/range_slider.py
examples/widgets/slider_demo.py
examples/widgets/slider_snap_demo.py

I tried to address all the things I remember finding frustrating when I first figuring out widgets
1. Removed the `RadioButtons`
- The have their own example and distract from the main thrust of this example
2. Added an example of a vertical slider (in the space formerly occupied by the radio buttons
3. longer more explicit names (e.g. `sfreq` -> `freq_slider`)
- I think this helps in the context of an example when you are scanning through and trying to decipher.
4. Made a function that gets plotted rather than rewriting the equation in multiple places.
5. Added a reference to the other slider examples.
- xref https://github.com/matplotlib/matplotlib/issues/19230
6. More explanatory comments everywhere
7. Added links to the other slider examples
- I never found this frustrating as those …

Expand on slider_demo example

---

doc/_templates/search.html

Search does not work on our current devdocs, which are built with Sphinx 3.4.x.
Sphinx stopped loading language_data.js globally in 3.4.
This file now has to be loaded explicitly on the search page.
See
- https://github.com/sphinx-doc/sphinx/pull/8445
- https://github.com/readthedocs/sphinx_rtd_theme/pull/1021

Fix sphinx search

---

lib/matplotlib/transforms.py

It's been unused since b6e9ae7.

Remove the unused TransformNode._gid.

---

examples/misc/svg_filter_line.py
lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_axes.py

`plt.plot(x, y, fmt)` allows to specify marker, linestyle and color via
`fmt`. Warn if there are additionally keyword arguments that specify the
same properties.
Closes #19275.
Builds on top of #19278, which cleans up _plot_args(). This separation
is done for easier review of the cleanup.

Warn on redundant definition of plot properties

---

lib/matplotlib/lines.py

Clarify return format of Line2D.get_data.

---

.github/ISSUE_TEMPLATE/bug_report.md

Fix misplaced colon in bug report template.

---

doc/devel/testing.rst

My plan is to rewrite the testing documentation. However in a first step, this PR removes irrelevant information.
It's simpler to rewrite when I know and we have agreed upon what parts of the current docs are not needed.
I'll comment below as to why I think specific parts are obsolete.

Strip irrelevant information from testing docs

---

.appveyor.yml
azure-pipelines.yml
lib/matplotlib/tests/test_backends_interactive.py

* Fix brew installation on Azure pipelines.
* Don't allow pyzmq 21.0.0 on AppVeyor.
This version is broken on Windows: zeromq/pyzmq#1470.
* TST: Mark Cairo backends as not threadsafe.
Cairo backends save the `cairo_t` object on the graphics context (as
`self.gc.ctx`), but this object is not threadsafe.
This should fix sporadic failures in `test_interactive_thread_safety`.
- [n/a] New features …

Fix several CI issues

---

doc/api/colors_api.rst
examples/userdemo/colormap_normalizations.py
lib/matplotlib/colors.py
lib/matplotlib/tests/test_colors.py
tutorials/colors/colormapnorms.py

Derives a func norm from func scale.  From the example:
```python
###############################################################################
#
def _forward(x):
return np.sqrt(x)
def _inverse(x):
return x**2
N = 100
X, Y = np.mgrid[0:3:complex(0, N), 0:2:complex(0, N)]
Z1 = (1 + np.sin(Y * 10.)) * X**2
norm = colors.FuncNorm((_forward, _inverse), vmin=0, vmax=20)
pcm = ax.pcolormesh(X, Y, Z1, norm=norm, cmap='PuBu_r', shading='auto')
ax.set_title('FuncNorm(x)')
fig.colorbar(pcm, shrink=0.6)
plt.show()
```

ENH: Add func norm

---

examples/event_handling/resample.py

Changed the convolution filter from [1, 1] to [1, 1, 1] such that the mask is dilated on both sides, not only at the end.

Extended the convolution filter for correct dilation

---

tutorials/intermediate/legend_guide.py

The assignment doesn't have any effect (except for being confusing).
It was most likely added by accident.

DOC: remove stray assignment in "multiple legends" example

---

doc/api/next_api_changes/deprecations/18302-ES.rst
lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/mplot3d/axis3d.py

Deprecate project argument to Line3DCollection.draw.

---

lib/matplotlib/tests/test_colors.py
lib/matplotlib/tests/test_scale.py
lib/matplotlib/tests/test_transforms.py
lib/matplotlib/transforms.py

Closes #18119; more general than #18126?

Make all transforms copiable (and thus scales, too).

---

lib/matplotlib/text.py

See also `set_verticalaligment()` where the value "center_baseline" is documented and processed.

Add missing possible return value to docs of get_verticalalignment()

---

doc/devel/documenting_mpl.rst
lib/matplotlib/axes/_axes.py

Fix some docstring interpolations

---

lib/matplotlib/backends/backend_qt5.py

display_is_valid takes care of everything now.  Also note that AFAICT
PyQt6 does not export QtX11Extras.

Simplify X11 checking for Qt.

---

lib/matplotlib/axes/_base.py

Better to be explicit with 'none' and not pretend to have a sentinel, that actually has hidden meaning.
See https://github.com/matplotlib/matplotlib/pull/19277#discussion_r556962369 for motivation and context.

Cleanup code for format processing

---

MANIFEST.in
ci/check_wheel_licenses.py

Fix the license check for the added Qhull license and avoid adding a huge `node_modules` directory to the sdist.

Fix some packaging issues

---

lib/matplotlib/axes/_axes.py

This updates the doc of matplotlib.pyplot.plot and closes #19274. The Markers part of matplotlib.pyplot.plot is not up to date with matplotlib.markers. 

Update the markers part of matplotlib.pyplot.plot document (fix issue #19274)

---

.github/workflows/tests.yml

This will be relevant once we also include PyQt6 support, as details of
enum access have changed in PyQt 5.11 (#19255).
PyQt is not actually a dependency so I don't think we can use the
constraints file (minver.txt) for that.

Pin to oldest supported PyQt on minver CI instance.

---

lib/matplotlib/backends/backend_pgf.py

Running into this issue again preparing to 3.4, so better commit what fix we have right now.
Fixes #17765.

Fix PGF with special character paths.

---

lib/matplotlib/tests/test_animation.py

For certain formats, ImageMagick delegates to ffmpeg.

Skip an ImageMagick test if ffmpeg is unavailable.

---

setup.py
setupext.py

It always tries to download it, even with the option set. It also links against `qhull`, but should use `qhull_r` now.

Fix building against system qhull

---

lib/matplotlib/text.py

Closes #19084. Added a note in the documentation to describe the behavior of annotations when used with arrows.

Explain annotation behavior when used in conjunction with arrows

---

src/ft2font_wrapper.cpp

(See https://github.com/matplotlib/matplotlib/pull/15009 for the format.)
I know it's still not perfect, but let's do things incrementally...

Improve FT2Font docstrings.

---

extern/agg24-svn/include/agg_basics.h
extern/agg24-svn/include/agg_image_accessors.h
extern/agg24-svn/include/agg_trans_affine.h
extern/agg24-svn/src/platform/win32/agg_platform_support.cpp

This storage class has been removed from C++17, and causes a warning when compiling with latest gcc:
```
warning: ISO C++17 does not allow ‘register’ storage class specifier
```

Remove register storage class from Agg files.

---

doc/api/next_api_changes/deprecations/19153-LPS.rst
doc/users/next_whats_new/axes_kwargs_collision.rst
lib/matplotlib/axes/_subplots.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/figure.py
lib/matplotlib/pyplot.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_figure.py
lib/mpl_toolkits/tests/test_mplot3d.py

This replaces #18978, and addresses the comments from @tacaswell and @jklymak to preserve the behavior of repeated calls to `plt.subplot` with the same subplot spec.
In Matplotlib 2.1, the behavior of reusing existing axes when created with the same arguments was deprecated (see #9037). This behavior is now removed.
The behavior of the functions to create new axes (`pyplot.axes`, `pyplot.subplot`, `figure.Figure.add_axes`, `figure.Figure.add_subplot`) has changed. In the past, these functions would detect if you were attempting to create Axes with the same keyword arguments as already-existing axes in the current figure, and if so, they would return the existing Axes. Now, these functions will always create new Axes. A special exception is `pyplot.subplot`, which will reuse any existing …

MNT: Remove deprecated axes kwargs collision detection (version 2)

---

doc/api/next_api_changes/deprecations/19336-AL.rst
lib/matplotlib/artist.py
lib/matplotlib/lines.py

This partially reverts commit a2de5bbe3437e19c2886cf481b8a53e714a1ae51 (#16154).
(The cleanup to legend_picking.py is kept; using `set_picker` here there
fine.)
See discussion at https://github.com/matplotlib/matplotlib/issues/19039#issuecomment-764915803.

Revert "Deprecate setting Line2D's pickradius via set_picker."

---

tutorials/colors/colormaps.py

This should solve #19308. However, I'm not sure if setting figsize explicitly is the way to go.

Whitespace in Choosing Colormaps tutorial plots

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/markers.py
lib/matplotlib/patches.py
lib/matplotlib/ticker.py

concatenate is (much) faster than hstack, while being essentially
equivalent in the 1D case; when working on 2D arrays it can replace
vstack too.
Timings:
```
In [1]: u = np.arange(5)
In [2]: %timeit np.concatenate([u, u])
842 ns ± 8.16 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
In [3]: %timeit np.hstack([u, u])
2.43 µs ± 7.43 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
In [4]: u = np.arange(1000)
In [5]: %timeit np.concatenate([u, u])
1.2 µs ± 2.67 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
In [6]: %timeit np.hstack([u, u])
2.9 µs ± 10.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
In [7]: u = np.arange(10).reshape((5, 2))
In [8]: %timeit np.concatenate([u, u])
934 ns ± 19.9 ns per loop (mean ± std. dev. of 7 runs, …
```

Prefer concatenate to h/vstack in simple cases.

---

INSTALL.rst
doc/devel/testing.rst

This replaces the "Test data" section in installation. Because testing an installation is rarely needed, I've also moved this to the "Testing" docs. IMHO a regular user wanting to install Matplotlib should not be bothered in any way with rather distracting testing information.

Describe how to test regular installations of Matplotlib

---

lib/matplotlib/mpl-data/stylelib/classic.mplstyle

... instead of the newfangled ConciseDateConverter.
This is specifically useful for running tests when one also has
`date.converter: concise` in their user-level matplotlibrc, as that
setting otherwise never gets overwritten by the test machinery, and
`test_figure.py::test_axes_removal` then fails (as it depends on
having `date.converter: auto`).

Force classic ("auto") date converter in classic style.

---

lib/matplotlib/tests/test_axes.py

In NumPy 1.20, the fft is slightly different (more accurate?) and returns 0 as the last entry, instead of some small number ~1e-30. This causes a divide-by-zero warning in `log10`. However, this test doesn't really care about the spectrogram, just the frequencies, so we can change the scale to linear to avoid the warning.

Fix specgram test on NumPy 1.20.

---

lib/matplotlib/markers.py

- Use dict lookups for fillstyle.
- When possible, prefer defining `path` and `alt_path` to the same path
and just make `alt_transform` the 180°-rotated version of `transform`.
(This is consistent with what's already being done for "circle" and
"octagon".)
Doing so requires redefining the half-X and half-plus marker paths to
not require a (-.5, -.5) translation but that actually makes the
path symmetries more apparent.

Shorten/make more consistent the half-filled marker definitions.

---

.github/workflows/tests.yml
setup.py
setupext.py
src/_tkagg.cpp
src/py_converters.cpp
src/py_converters.h

Fix build with LTO disabled in environment

---

lib/matplotlib/axes/_axes.py

This PR closes #19372 by changing the default label of inset axes to '_indicate_inset' from 'indicate_inset', which will prevent a legend entry to be inserted.

Modify indicate_inset default label value

---

setup.cfg.template
setup.py
setupext.py

The whole sample data folder is ~500K now, which is much less than many
compiled extension modules (backend_agg, ft2font, _image, _path, _qhull
shared objects all weight ~2-3M).  Always installing sample_data is a
step towards making Matplotlib installs more homogeneous (i.e., fewer
variants).

Always include sample_data in installs.

---

doc/conf.py

The incorrect reference is fixed in pytest git, but won't be in a released version for some time.
https://github.com/pytest-dev/pytest/pull/8280#issuecomment-768745131
Closes  #19366.

Temporarily switch intersphinx to latest pytest.

---

doc/api/next_api_changes/deprecations/18649-TH.rst
lib/matplotlib/image.py
lib/matplotlib/tests/test_image.py

Replaces https://github.com/matplotlib/matplotlib/pull/18649, with the suggestion to directly using the Pillow API (https://github.com/matplotlib/matplotlib/pull/18649#pullrequestreview-503145250).  Closes #18648.

Deprecate imread() reading from URLs

---

.appveyor.yml

This version is broken on Windows:
https://github.com/zeromq/pyzmq/issues/1496.

Don't allow pyzmq 22.0.0 on AppVeyor.

---

lib/matplotlib/backends/qt_compat.py

The qt backend is not working on mac big sur as reported in #18954.
It is fixed in qt 5.15.2 (https://codereview.qt-project.org/c/qt/qtbase/+/322228) and in the coming 5.12.11 (https://codereview.qt-project.org/c/qt/qtbase/+/322507) but setting this environment variable is necessary for qt <5.15.2.
Even if in a ideal word `matplotlib` shouldn't be setting this variable environment, this is pragmatic and very convenient fix!

Fix qt backend on mac big sur

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

Even though we are going to ignore it, set the facecolors to the user
specified color and edgecolor to 'face' to maintain
back-compatibility.
We now warn if the user passes in an edgecolor that we ignore.
closes #17849
partially reverts #17543 / d86cc2bab8183fd3288ed474e4dfd33e0f018908
Do we want an API change note for the warning?

MNT: set the facecolor of nofill markers

---

lib/matplotlib/backends/backend_wx.py

Alas, my fix in #19052 was incomplete, or something changed in the meantime. There are a few more places that wx does not accept floats (see commit messages for details). This only appears to happen with Python 3.10, but looking at the C++ wx side, there are no floating point overloads, so I'm not sure why it ever worked.

wx: Use integers in more places

---

doc/_templates/layout.html
doc/devel/release_guide.rst

Depends on https://github.com/matplotlib/matplotlib.github.com/pull/47
Makes `matplotlib.org/stable` the canonical root.

DOC: make canonical version stable

---

lib/matplotlib/font_manager.py
lib/matplotlib/tests/test_backend_bases.py
lib/matplotlib/tests/test_backend_pgf.py
lib/matplotlib/tests/test_font_manager.py
setupext.py

- Ensure that environment variables set to empty values behave as if
unset (hence replacing `os.environ.get(foo, bar)` by
`os.environ.get(foo) or bar`).
- Misc. additional cleanups.

os.environ-related cleanups.

---

lib/matplotlib/tests/test_constrainedlayout.py

Checks for bug in which align_ylabel drives y labels of some subplots off the edge of the plot when using constrained layout under the circumstances laid out here: https://github.com/matplotlib/matplotlib/issues/19152 . This is my first contribution to open-source, so any feedback is helpful! On the first checklist item, I'm not sure what "pytest style unit tests" are in particular, and I'm having trouble getting the test suite to run at all, though I managed the first time I cloned the repository and my added test performed as it should have. 
- [N/A ] Documentation is sphinx and numpydoc compliant (the docs should …

test for align_ylabel bug with constrained_layout

---

lib/matplotlib/axes/_base.py

Improve doc of default labelpad.

---

lib/matplotlib/_constrained_layout.py

the off by one made it look like to rst/numpydoc that the parameters
h_pad, w_pad ... etc are part of the indented block of the `rendered`
parameter.
This is not rendered on the matplotlib doc AFAICT, but no reason to have
it wrong...

DOC: correct off by one indentation.

---

examples/units/basic_units.py

This is needed to avoid a deprecation warning with numpy 1.20, and fixes the doc build.
See https://numpy.org/doc/stable/release/1.20.0-notes.html#arraylike-objects-which-do-not-define-len-and-getitem for more information. Essentially, `__len__` and `__getitem__` needed to be implemented for numpy to recognise the class as a sequence.

Make TaggedValue in basic_units a sequence

---

doc/conf.py

Single line fix to remove a hard-coded slash that was preventing the docs from building on windows in Anaconda.

BF: DOCS: fix slash for windows in conf.py

---

matplotlibrc.template

Because DejaVu is shipped with Matplotlib, searching font.serif will
never go beyond the first item (`DejaVu Serif`), and likewise for
font.sans-serif and font.monospace.  So delete the entries which are
clearly never used.  (If someone really wants to strip the fonts in a
custom distribution of Matplotlib, and not provide DejaVu separately,
they'll have to adapt the list as desired -- they already need to fix
the last-resort fallback to DejaVu in font_manager.py anyways.)
Also reword the description of `font.family`.

Better document font.<generic-family> rcParams entries.

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backend_managers.py
lib/matplotlib/collections.py
lib/matplotlib/tri/triinterpolate.py
lib/mpl_toolkits/axisartist/axis_artist.py

Also uniformise indent of one section to match the rest of the file

DOC: fix incorrect parameter names

---

lib/matplotlib/tri/triinterpolate.py

Style fixes to triintepolate docs.

---

lib/matplotlib/axes/_axes.py

- [b/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

Add units to bar_label padding documentation.

---

doc/_templates/sidebar_versions.html

Change the cheatsheet link from https://github.com/matplotlib/cheatsheets to https://github.com/matplotlib/cheatsheets#cheatsheets
This makes this a much friendlier link to click, as your screen is immediately filled with what you want, rather than the code that was used to make the cheatsheets.

Move cheatsheet focus to the cheatsheets away

---

lib/matplotlib/backends/backend_gtk3.py

fixes #19405. updated GTK3 method for cursor control for GTK3 backend. fixes the TypeError constructor returned NULL error that prevents pyplot to run under Wayland.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst …

fixes TypeError constructor returned NULL in wayland session

---

lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/tests/test_mplot3d.py

This came from testing #19363; it was broken for 3.3.0, but we aren't planning new releases there.

Fix empty Poly3DCollections

---

lib/matplotlib/patches.py
lib/matplotlib/tests/test_axes.py

Closes https://github.com/matplotlib/matplotlib/issues/18934 (although @timhoffm has argued against supporting this case).

Support empty stairs.

---

lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/tests/test_mplot3d.py

It simply copies the value from the 2D version to `self._facecolor3d`, and then later to `self._facecolor2d`, but never does anything to require these additional copies.
Fixes #18815.

Remove unnecessary facecolor cache in Patch3D.

---

lib/matplotlib/backend_bases.py

Dropping curve control points is also consistent with the behavior of
the SVG marker-mid property.
Closes https://github.com/matplotlib/matplotlib/issues/8790 (based on the SVG spec, I decided to keep the actual behavior).

Fix the docstring of draw_markers to match the actual behavior.

---

lib/matplotlib/backends/backend_gtk3.py

- set_double_buffered (deprecated since gtk3.14) is unnecessary, gtk
(even gtk2) defaults to being double-buffered (this line of code comes
from the old gtk2 backend which used to disable double buffering).
https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-set-double-buffered
- gtk_window_get_pointer is deprecated since gtk3.0.
https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#gdk-window-get-pointer
- get_window_size_request is deprecated since gtk3.0.  Also inline
add_widget, which is used exactly once.
https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-size-request

Replace gtk3 deprecated APIs that have simple replacements.

---

doc/devel/index.rst

Fix the link to discourse. Otherwise it ends up linking to https://matplotlib.org/devdocs/devel/discourse.matplotlib.org
See: https://matplotlib.org/devdocs/devel/index.html#
Follow up to https://github.com/matplotlib/matplotlib/pull/19344 so attn @timhoffm

Use absolute link for discourse

---

doc/api/toolkits/mplot3d.rst

Closes #19446.
Also:
- remove the table of contents on that page. It's still available in
the side bar and removing reduces the clutter in the main body.
- slightly reword the note on maturity of 3D plotting (nobody needs to
know that this was improved for 1.1.0)

Add note that pyplot cannot be used for 3D.

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/backends/backend_qt5agg.py
lib/matplotlib/backends/backend_qt5cairo.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/tests/test_backend_bases.py

Auto-instantiating a Figure seems reasonable enough, and helps with GUI
builders.  (The auto-instantiated figure must be a plain Figure(), not
a a pyplot-registered figure, both because most likely one should not
use pyplot when building GUIs, and also more prosaically because that
would run into a circular dependency (pyplot needs a canvas already
instantiated (actually a manager that holds a canvas) to store into its
global registry).
Closes https://github.com/matplotlib/matplotlib/issues/17349.

Make figure parameter optional when constructing canvases.

---

doc/devel/documenting_mpl.rst
examples/lines_bars_and_markers/hat_graph.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/backend_bases.py
lib/matplotlib/bezier.py
lib/matplotlib/collections.py
lib/matplotlib/colors.py
lib/matplotlib/contour.py
lib/matplotlib/path.py
lib/matplotlib/pyplot.py
lib/matplotlib/stackplot.py
lib/matplotlib/tri/triangulation.py
lib/matplotlib/tri/tricontour.py
lib/matplotlib/tri/triinterpolate.py
lib/matplotlib/tri/trirefine.py
lib/matplotlib/tri/tritools.py
lib/mpl_toolkits/axes_grid1/axes_rgb.py
lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/mplot3d/axes3d.py

Also use "array" instead of "array-like" for return types if
appropriate.  Some instances were left unchanged as they may need more
editing anyways.
See discussion at https://github.com/matplotlib/matplotlib/issues/16161#issuecomment-772922194.

Switch array-like (M, N) to (M, N) array-like.

---

lib/matplotlib/rcsetup.py

Fix trivial typo in error message.

---

lib/matplotlib/backends/backend_pgf.py

This will make it easier to troubleshoot failures on CI.

Include tex output in pdf LatexError.

---

lib/matplotlib/lines.py
lib/matplotlib/tests/test_axes.py

#18647 broke loglog scale axlines (see #19445). This PR fixes it by adding `transScale` to the transformations applied to the points of the line and adds a test to verify the result (based on the example given by @anntzer in #19445).
This should have no effect on results with linear scales, and the remaining tests are still passing, so it looks like it works correctly.

fix regression of axline behavior with non-linear scales

---

lib/matplotlib/lines.py

As discussed elsewhere, the first form is both faster and more accurate
as it can handle exact cancellations.
followup to #19485.

Prefer `tr1-tr2` to `tr1+tr2.inverted()`.

---

lib/matplotlib/pyplot.py
lib/matplotlib/tests/test_pyplot.py

Currently, the `TypeError` thrown when an inappropriate type is passed to `pyplot.close()` has the following message:
> TypeError: close() argument must be a Figure, an int, a string, or None, not '%s'
This is clearly a typo (introduced in f6bdcb5fe60fabe8fa2093981383b5e23a109fce) as it says `'%s'` instead of telling the user the type that was passed in.
We update the `raise` statement to include the type so that `pyplot.close(1.1)` gives
> TypeError: close() argument must be a Figure, an int, a string, or None, not <class 'float'>
instead of 
> TypeError: close() argument must be a Figure, an int, a string, or None, not '%s' …

Fix error message in plt.close().

---

doc/users/next_whats_new/mathtext.rst
lib/matplotlib/_mathtext.py

This is a continuation of the previous PR https://github.com/matplotlib/matplotlib/pull/18916,
w.r.t. this comment: https://github.com/matplotlib/matplotlib/pull/18916#issuecomment-776654901

Add overset/underset whatsnew entry

---

lib/matplotlib/backends/backend_gtk3.py

This is consistent with the other backends (although this seems to be
broken on wx too), which allows semi-transparent figures to be rendered
against a consistent background (this can be checked e.g. with
`figure(facecolor=(0, 0, 0, 0))` or `figure(facecolor=(1, 1, 1, .5))`),
which would previously be rendered differently on gtk3 when using a dark
theme.
~~While override_background_color is marked as deprecated on gtk3, the
alternative seems to involve a bunch of CSS, and it seems unlikely to
ever be removed now that gtk development has switched to gtk4...~~
xref https://github.com/matplotlib/matplotlib/pull/9698.

Set the GTK background color to white.

---

doc/api/next_api_changes/deprecations/19503-AL.rst
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/backends/backend_svg.py
lib/matplotlib/backends/backend_template.py

This patch avoids a deprecation warning ("unexpected argument 'dpi'")
on `Figure().tight_layout()`.  To do so we stop passing `dpi` to
`print_foo`, which is actually fine because `print_figure` already sets
the figure dpi to whatever value we will want, so `print_foo` can just
read `self.figure.dpi`.
Closes https://github.com/matplotlib/matplotlib/issues/19486.

Fix tight_layout() on "canvasless" figures.

---

matplotlibrc.template

(see also the Axes.autoscale_view docstring)
Closes https://github.com/matplotlib/matplotlib/issues/2298 (mostly, the existence of `axes.autolimit_mode` allows toggling the behavior desired by the issue reporter).

Clarify axes.autolimit_mode rcParam.

---

examples/subplots_axes_and_figures/colorbar_placement.py

Update the colorbar placement tutorial to point out the utility of `ax.inset_axes` for placing colorbars when the axes has fixed aspect ratios...

DOC: add fixed-aspect colorbar examples

---

lib/matplotlib/tests/test_backend_bases.py
lib/matplotlib/tests/test_backend_pdf.py
lib/matplotlib/tests/test_backend_pgf.py

Skip setting up a tmpdir in tests that don't need one.

---

doc/api/next_api_changes/development/19500-AL.rst
lib/matplotlib/__init__.py
lib/matplotlib/transforms.py

We now require numpy 1.16 (per setup.py and NEP29).

Remove workaround for numpy<1.16, and update version check.

---

lib/matplotlib/tests/test_backend_pgf.py

It's already implemented in dviread.

Simplify checking for tex packages.

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/backends/backend_svg.py
lib/matplotlib/backends/backend_template.py
lib/matplotlib/testing/__init__.py
lib/matplotlib/tests/test_backend_bases.py
lib/matplotlib/tests/test_backend_pgf.py

Previously the non-interactive backends, other than Agg, did not
define `draw` methods and fell back to the base no-op version.
However, we have been documenting that the correct way to update the
various internal state we keep (run tight/constrained layouts, auto
limits, text size/position, ...), this is now a bug due to our
suggested usage drifting.
closes #18407
I could be convinced that this should actually be backported for 3.3.2
I'm mixed if these needs an API change note or not.

FIX/API: `fig.canvas.draw` always updates internal state

---

lib/matplotlib/dviread.py
lib/matplotlib/testing/__init__.py
lib/matplotlib/tests/test_backend_pgf.py
lib/matplotlib/tests/test_usetex.py

Applies the patch from @anntzer and adds a test
Fixes #19234.

Fix text position with usetex and xcolor

---

doc/users/next_whats_new/collection_color_handling.rst
lib/matplotlib/axes/_axes.py
lib/matplotlib/cm.py
lib/matplotlib/collections.py
lib/matplotlib/patches.py
lib/matplotlib/tests/test_collections.py
lib/mpl_toolkits/mplot3d/art3d.py

Color handling in collections is confusing: there are faces and edges, each of which can have a fixed color or a mapped color. Fixed colors (which can be single specifications or arrays matching the elements in the collection) are always available via initialization with defaults.  If the collection has a data array set, then it will be used to map colors for edges and/or faces, depending on how their respective fixed color attributes are set.  The purpose of this PR is to clarify the logic by consolidating it in a private function.  This closes #1302, and is an alternative to #12226.
Edited, 2020-09-25
Working with the collections code is complicated by the aliasing combined with the subclassing.  Here's how it looks to me:
1) The direct effect of the aliasing is to generate additional …

Clarify color priorities in collections

---

examples/pie_and_polar_charts/nested_pie.py
examples/pie_and_polar_charts/polar_scatter.py
examples/pyplots/annotation_polar.py
lib/matplotlib/figure.py
lib/matplotlib/pyplot.py

... per dev call.
The docstring of add_axes/add_subplot still needs to be changed, but
this should wait until after projection reuse behavior is finalized.
Also, cases of polar=True in the tests have been left as such, to keep
exercising that API.

Prefer projection="polar" over polar=True.

---

lib/matplotlib/axis.py
lib/matplotlib/figure.py

A single implementation can be written in the base class.
Also, the alignment groupers only need to be defined in FigureBase;
we don't need to redefine them in the Figure subclass.

Dedupe implementations of {XAxis,YAxis}._get_tick_boxes_siblings.

---

lib/matplotlib/__init__.py

This is the only place that we directly access the cwd in the main library.
You can drive your self to this state by in one shell cd'ing to a directory and then from a different shell removing that directory.  The first shell will still think it's working directory is the (now non-existent) path and mild chaos ensues.
This has probably been broken forever (at least back to the 2.2.x series), however I do not think that it is worth the trouble to set up this weird state in the tests.   If you are in this state IPyhon will not start and PyQt5 will not import.

FIX: ensure we import when the user cwd does not exist

---

doc/api/next_api_changes/behavior/18564-AL.rst
examples/pyplots/whats_new_99_mplot3d.py
lib/matplotlib/figure.py
lib/matplotlib/tests/test_collections.py
lib/mpl_toolkits/mplot3d/axes3d.py
lib/mpl_toolkits/tests/test_mplot3d.py

Only do this when directly created by the user, not via our machinery.
Alternative to #19413.
This still needs tests and updates to the docs.

MNT: Restore auto-adding Axes3D to their parent figure on init

---

doc/users/next_whats_new/top-left-shared-subplots.rst
lib/matplotlib/gridspec.py
lib/matplotlib/tests/test_subplots.py

On the following example
```python
rcParams.update({"xtick.labeltop": 1, "xtick.labelbottom": 0,
"ytick.labelright": 1, "ytick.labelleft": 0})
subplots(3, 3, sharex=True, sharey=True)
```
subplots() now correctly leaves the xlabels on the first row and the
ylabels on the last column, rather than the other way round.
old:
new:
On the following example
```python
rcParams.update({"xtick.labeltop": 1, "xtick.labelbottom": 1,
"ytick.labelright": 1, "ytick.labelleft": 1})
subplots(3, 3, sharex=True, sharey=True)
show()
```
subplots() now correctly leaves the xlabels on the first and last row
and the ylabels on the first and last column.
old:
new:

Fix default label visibility for top-or-left-labeled shared subplots().

---

doc/api/next_api_changes/behavior/19438-TAC.rst
doc/users/next_whats_new/axes_kwargs_collision.rst
lib/matplotlib/axes/_base.py
lib/matplotlib/figure.py
lib/matplotlib/pyplot.py
lib/matplotlib/tests/test_figure.py
lib/matplotlib/tests/test_pyplot.py

This adds a small amount of additional state to the Axes created via
Figure.add_axes and Figure.add_subplot (which the other Axes creation
methods eventually funnel through) to track the kwargs passed
through.
We then use that state in `pyplot.subplot` to determine if we should
re-use an Axes found at a given position or create a new one (and
implicitly destroy the existing one).
closes #19432
closes #10700

FIX: restore creating new axes via plt.subplot with different kwargs

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

In scatter, fix single rgb edgecolors handling

---

lib/matplotlib/cbook/__init__.py
lib/matplotlib/tests/test_cbook.py

This PR fixes the issue #19474, and probably the issue #19345
- Plus rewrite some code for readability (like full name instead of letter, intricate loop, try-catch potentially caching many things)
- Plus coverage for the method `disconnect`
A much shorter change count be done to only fix the issue, if you like.

Fix CallbackRegistry memory leak

---

lib/matplotlib/axes/_axes.py

Small doc change to plot_date so people realize they don't need to use it if they just pass bare dates in.

DOC: fix plot_date doc

---

examples/statistics/boxplot.py

linestyle='none' [here](https://github.com/matplotlib/matplotlib/blob/a5ea869114fd67ee4db17b22e77a1e495f45336f/examples/statistics/boxplot.py#L63) has no effect in removing the marker edges, thus
it was changed to markeredgecolor='none' to achieve this outcome.
Solves #19427 
| With `linestyle='none'` (no effect)              | With `markeredgecolor='none'` (border removed)                     |
| ------------------------------ | ------------------------------------ |
| <img width="170" alt="previous" src="https://user-images.githubusercontent.com/37598144/109292066-7b769900-7832-11eb-939a-8244e6402c71.png"> | <img width="166" alt="current" src="https://user-images.githubusercontent.com/37598144/109292230-b8db2680-7832-11eb-871d-c39d89ca2311.png"> |

Changes linestyle parameter of flierprops

---

lib/matplotlib/cbook/__init__.py

All backends previously normalized both the return key and the (numpad)
enter to "enter" (see e.g. the presence of two "enter" entries in the
old FigureCanvas{GTK3,Tk}.keyvald . When revamping the gtk and tk key
names lookup I accidentally normalized both to "return" instead (#17791, #18693),
so fix that.
Test with
```
gcf().canvas.mpl_connect("key_press_event", lambda e: print(e.key))
```

Fix "return"->"enter" mapping in key names.

---

doc/api/next_api_changes/deprecations/19585-AL.rst
lib/matplotlib/style/core.py

STYLE_FILE_PATTERN is unused, the usual approach would be to check
whether a path's suffix matches STYLE_EXTENSION.
load_base_library is just a one-liner used in one place; hiding it
behind a function only obscures things.
iter_user_library is a combo of os.path.expanduser (which can be
inlined) and checking whether entries are existing directories (which is
unnecessary in update_user_library) as Path.glob helpfully returns empty
lists when globbing non-existing paths or into non-directories.
(Also note that none of these APIs are exported in `style/__init__.py`,
which is the real "intended public" API.)

Deprecate trivial helpers in style.core.

---

lib/matplotlib/colors.py
lib/matplotlib/lines.py
lib/matplotlib/tests/test_text.py
lib/matplotlib/text.py

Otherwise, the error is only raised when drawing the artist, which is
always confusing.  Also add a general `_check_color_like` mechanism and
use it for Line2D as well, instead of relying on a slightly strange
`if not is_color_like(): check_in_list(get_named_colors_mapping())`
call where the check_in_list *always* fails.
Closes https://github.com/matplotlib/matplotlib/issues/19569 (well, likely the OP was confused about other stuff, but this should at least bring the error message closer to the relevant place).

Fail early when setting Text color to a non-colorlike.

---

lib/matplotlib/_api/__init__.py

Dedupe part of error message in check_in_list.

---

lib/matplotlib/backend_bases.py

When blocking import of `IPython` by defining `sys.modules["IPython"] = None`, creating plots fails because `backend_bases.FigureCanvasBase._fix_ipython_backend2gui` attempts to check if `IPython` is already imported by looking for an entry in `sys.modules`. It then attempts to import `IPython`, which fails due to the import being blocked.
Code sample to reproduce the issue:
```
import sys
sys.modules['IPython'] = None
from matplotlib import pyplot
plt = pyplot.subplots(1,1)
```
which results in:
```
File "<module1>", line 5, in <module>
File "C:\Users\Phil\envs\mp_dev\lib\site-packages\matplotlib\cbook\deprecation.py", line 451, in wrapper
return func(*args, **kwargs)
File "C:\Users\Phil\envs\mp_dev\lib\site-packages\matplotlib\pyplot.py", line 1287, in …
```

Fix IPython import issue

---

doc/api/next_api_changes/deprecations/19517-AL.rst
lib/matplotlib/__init__.py

They certainly don't warrant being defined at the toplevel.  Also, we
don't actually need regexes here.

Deprecate toplevel is_url, URL_REGEX helpers.

---

lib/matplotlib/colors.py
lib/matplotlib/tests/test_colors.py

Closes #19544 using @anntzer suggested fix....

FIX: check for a set during color conversion

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/quiver.py

add docstring to ax.quiver

---

examples/text_labels_and_annotations/date.py

Modernize and give some alternatives here.  I can't believe we actually have `fig.autofmt_xdate` as a thing still.

DOC: more improve date example

---

lib/matplotlib/streamplot.py

They have already been removed in d60c9fc.

Remove suggestion to remove rk4/rk45 integrators from streamplot.

---

lib/mpl_toolkits/mplot3d/axes3d.py

Remove unmaintained version notes/annotations from axes3d.py. This also corrects an inline markup escape sequence to generate a doc link properly.

Remove versionadded notes; correct doc link

---

lib/matplotlib/tests/test_arrow_patches.py
lib/mpl_toolkits/tests/test_axisartist_grid_helper_curvelinear.py
lib/mpl_toolkits/tests/test_mplot3d.py

See scratch build here:
https://koji.fedoraproject.org/koji/taskinfo?taskID=62275793

Increase tolerances for other arches.

---

lib/matplotlib/backends/backend_wx.py

Fix for issue https://github.com/matplotlib/matplotlib/issues/17769
1) On figure window (FigureFrameWx) close - remove figure manager from from Gcf class
previously Gcf.destroy was called with FigureFrameWx not FigureManagerWx instance so figure was not removed correctly.
2) Destroy now done from FigureManagerWx.destroy() method to prevent multiple calls to the close event handler.
3) Remove unneeded wx mainloop yield calls that cause crash on windows from both FigureManagerWx.destroy and FigureFrameWx.Destroy.
Tested on windows 10, and mint 20.1. 
- …

Fix for issue 17769: wx interactive figure close cause crash

---

lib/matplotlib/dates.py

This attempts to improve the dates.py intro to give the user some idea what is going on.  This page comes up first if you type `matplotlib dates` into Google, but I don't think anyone would know how to use dates from the original.

DOC: better intro for dates.py

---

tutorials/intermediate/artists.py

remove() works for all artists, and is thus more useful to know than
delaxes() (which is does exactly the same, but only for axes).
See also https://github.com/matplotlib/matplotlib/pull/15290.

Prefer Axes.remove() over Figure.delaxes() in docs.

---

lib/matplotlib/figure.py

It was accidentally ignored since 154a616.

Fix handling of warn keyword in in Figure.show.

---

lib/matplotlib/figure.py
lib/matplotlib/tests/test_figure.py

Also check that the first element of the a list layout is not a string.
closes #19631

FIX: do not allow single element list of str in subplot_mosaic

---

lib/matplotlib/backend_bases.py
lib/matplotlib/figure.py
lib/matplotlib/tests/test_backend_bases.py

pick_events were previously incorrectly emitted twice due to the
combination of two recent(ish) chnages: Figures now always start with a
FigureCanvasBase attached -- eventually switching to a concrete subclass
of FigureCanvasBase for display or saving --, and callbacks are now
actually stored at the Figure level rather than the Canvas level.
Hence, the button_pick_id callback (in charge of emitting picks) would
previously be both registered both through the FigureCanvasBase and the
concrete subclass.  The fix is to also move that callback to the Figure
level, so that each Figure only has one such callback.

Fix double picks.

---

lib/matplotlib/widgets.py

I'm doing some widget work, and this comment confused me for a little while. I think the implementation was probably intended to be clockwise, but as currently implemented the edges are actually returned in an anti-clockwise manner.

Fix comment in RectangleSelector

---

lib/matplotlib/testing/__init__.py
lib/matplotlib/tests/test_backend_bases.py
lib/matplotlib/tests/test_backend_pgf.py

It was accidentally(?) added to the public API in the yet-to-be-released
1173770.

Don't turn check_for_pgf into public API.

---

lib/matplotlib/tests/test_transforms.py
lib/matplotlib/transforms.py

The problem that this PR resolves is that `Bbox.frozen()` does not copy the minpos values which is a problem when using log scaling. This should resolve #19296.

Fix Bbox.frozen() not copying minposx/minposy

---

lib/matplotlib/cbook/__init__.py
lib/matplotlib/figure.py
lib/matplotlib/tests/test_figure.py

This is a simplified version of the `AxesStack` removed in #19153, but removing the key entry, and just tracking the index with the `Axes`. We no longer need to track keys.
Fixes #19598.

Restore _AxesStack to track a Figure's Axes order.

---

lib/matplotlib/cm.py

While this seems to have been working, manipulating `locals()` is not guaranteed to have any effect.
https://docs.python.org/3/library/functions.html#locals

Use globals() instead of locals() for adding colormaps as names to cm module

---

lib/matplotlib/patches.py
lib/matplotlib/tests/test_patches.py

This adds an `angle` property, such that the `Rectangle` is labelled stale when it is updated. All the other properties use `set_` and `get_`, but to maintain backwards compatibility I've used a property here since `Rectangle.angle` already existed.

Add angle setter/getter to Rectangle

---

lib/matplotlib/_api/deprecation.py
lib/matplotlib/backend_bases.py
lib/matplotlib/backend_tools.py
lib/matplotlib/cm.py
lib/matplotlib/colorbar.py
lib/matplotlib/tests/test_api.py

... with no changes (there's now a test for that).

deprecate_privatize_attribute also works for privatizing methods.

---

lib/matplotlib/colors.py
lib/matplotlib/tests/test_colors.py

Right now we are deprecating access to the global colormaps, but users can only avoid it by doing `newcmap = copy.copy(cmap)` which is a bit heavy-handed.  Here we provide a simple `copy` method to `Colormap` so we can do `newcmap = cmap.copy()`.  
See discussion in #19609, #16991, #18503

ENH: add a copy method to colormaps

---

doc/api/axis_api.rst
doc/api/next_api_changes/deprecations/19655-AL.rst
lib/matplotlib/axis.py

apply_tickdir doesn't actually update the tick markers on the existing
Line2D objects used to draw the ticks (as can be checked with e.g.
`plt.gca().xaxis.majorTicks[2].apply_tickdir("inout")`), so it's really
mostly an internal helper that cannot be meaningfully called from
outside (it needs to cooperate with `_apply_params` to actually work).

Deprecate Tick.apply_tickdir.

---

lib/matplotlib/ticker.py

Amended docstring for FormatStrFormatter so there is documentation for how to get a unicode minus instead of a dash.
Closes #17967.

Changed FormatStrFormatter documentation to include how to get unicode minus

---

lib/matplotlib/backends/backend_gtk3.py

Repro:
mpl.use('GTK3Agg')
plt.figure().canvas.mpl_connect('resize_event', lambda e: plt.pause(1))
plt.show()
Closes https://github.com/matplotlib/matplotlib/issues/19593.
No test because heh.

Fix crash in early window raise in gtk3.

---

doc/api/next_api_changes/deprecations/19487-AL.rst
lib/matplotlib/backends/backend_agg.py
lib/matplotlib/backends/backend_gtk3agg.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/backends/backend_svg.py
lib/matplotlib/backends/backend_template.py

These `*args` are never used.
gtk3agg's print_png can just be directly inherited from agg (likely, it
is a remnant of a time when gtk3 would rely on cairo's png output by
default).
For the pgf backend, `*args` can be directly deleted because it would
previously have caused exceptions when forwarded to _print_pgf_to_fh.

Deprecate unused \*args to print_<foo>.

---

doc/sphinxext/redirect_from.py

This allows you to re-run doc builds without cleaning.

Only warn about existing redirects if content differs.

---

lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

multicursor now checks if `event.inaxes` is one of the axes it will draw on.
Fixes: https://github.com/matplotlib/matplotlib/issues/19635
Before
After:
There aren't any multicursor tests - does this change need a test?
- [ NA? ] Has pytest style unit tests (and `pytest` passes).
- [NA] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

Correctly check inaxes for multicursor

---

doc/users/license.rst

Partly adresses #19687.
Changes:
- Replaced the license text by a literal include of our license file `LICENSE/LICENSE` in the repo.
We should not carry two versions of the license. Note that the deleted text used the explicit version `|version|` in many places, which `LICENSE` does not. As far as I understand licenses this is not necessary, and I haven't seen this in other licenses. so this technical change is ok. Anyway we cannot have two different license wordings.
- some capitalization of "Matplotlib"

Cleanup license page in docs

---

examples/shapes_and_collections/arrow_guide.py

The arrow guide mistakenly made it sound like the arguments for FancyArrowPatch are (x, y) and (dx, dy), whereas they are (x_tail, y_tail) and (x_head, y_head).

DOC: fix dx in Arrow guide

---

examples/shapes_and_collections/arrow_guide.py

Just some corrections to the typos and redundancy in `arrow_guide.py`. 

Fix arrow_guide.py typo

---

lib/matplotlib/backends/backend_svg.py

Sorting had been added in cb5893d for reproducible outputs, but dicts
now maintain insertion order so this is not needed anymore; moreover,
not sorting allows keeping attributes in a more semantic meaning --
e.g., attributes of the toplevel `<svg>` are now in the order
`xmlns:xlink width height viewBox xmlns version` rather than
`height version viewBox width xmlns xmlns:xlink`; the `<use>` elements
of ticks now have attributes `xlink:href x y style` rather than
`style x xlink:href y`.
The order is still not perfect due to other issues, but that'll be
addressed another time.

Don't sort lexicographially entries in SVG output.

---

lib/matplotlib/backends/backend_cairo.py
matplotlibrc.template

I don't think there's many people who want non-antialiased output for
cairo; rather, this is mostly so that I can remove the "agg-only" point
in the docs (as mplcairo already supports these).

Respect antialiasing settings in cairo backends as well.

---

lib/matplotlib/backends/backend_svg.py

(It is unused since the removal of svg fonts, deprecated in 5072e59 and
removed after.)

Remove unused _fonts attribute in RendererSVG.

---

lib/mpl_toolkits/axisartist/axis_artist.py

Reword the axis_artist module docstring.

---

lib/matplotlib/lines.py
lib/matplotlib/tests/test_lines.py

This was done when the deprecation was added, but then removed when it was undeprecated. However, people now seem to be relying on this new behaviour, and it seems more correct, so we should add it back.
Fixes #19700.

Only override pickradius when picker is not a bool.

---

INSTALL.rst
doc/users/installing_source.rst

- Move "Installing from source" contents to it's own page to declutter the main installing page.
The [Installation FAQ](https://matplotlib.org/devdocs/faq/installing_faq.html) should be merged in to the new "Installing from source" page, but that's for a separate PR.
- Rewording.
Adresses part of #17327. Still to do is merging the Installation FAQ (see above).

Cleanup installing docs

---

lib/matplotlib/lines.py

(The comment at the end regarding instance methods is completely
outdated and doesn't even match the current code anymore.)

Update some matplotlib.lines docstrings.

---

lib/matplotlib/cbook/__init__.py

... by relying on dicts maintaining insertion order (which is what was
previously tracked separately in `_killkeys`).
Note that both the original and new implementations actually evict keys
by *insertion* order, not as LRU.

Simplify maxdict implementation.

---

doc/devel/contributing.rst

The top-level files INSTALL.rst and README.rst both use the version with the space between the -m and the module in the command that is executed. To be more consistent, this was changed here as well.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow …

Changed 'python -mpip' to 'python -m pip' for consistency

---

lib/matplotlib/axes/_subplots.py
lib/matplotlib/gridspec.py
lib/matplotlib/tests/test_subplots.py

This allows label_outer() to also benefit from handling of top-or-right
labeled axes (not only for the tick labels, but also for the axis labels
themselves).
followup to #19472.
edit: this should also be useful for https://github.com/matplotlib/matplotlib/issues/18305.

Share subplots() label visibility handling with label_outer().

---

lib/matplotlib/backends/web_backend/js/nbagg_mpl.js

The WebSocket wrapper around the IPython comm does not define `readyState`, and so resizes are never forwarded to the Python side.

Fix resizing in nbAgg.

---

doc/api/next_api_changes/removals/19552-GL.rst
lib/matplotlib/cm.py
lib/matplotlib/collections.py
lib/matplotlib/tests/test_collections.py
lib/mpl_toolkits/mplot3d/art3d.py

The updates to scalar mappable would only occur if the
array was updated. This meant that updating the vmin/vmax of
the sm's norm would not be propagated to the drawn artists. This
update removes the array update checks from scalar mappable to calculate
the colors regardless of updates to the array.

Remove scalarmappable private update attributes

---

lib/matplotlib/backend_tools.py

Properties already show up with their docstrings in the generated docs,
so no need to list them in a separate API section (also note that the
document type of the figure attribute was wrong).

Cleanup backend_tools docstrings, and minor refactorings.

---

doc/devel/documenting_mpl.rst
doc/users/license.rst

- shorten `.. literalinclude:` example
- link to Sphinx inheritance-diagram docs instead of explaining it ourselves
- remove emacs helpers. IMHO this is not relevant enough to justify additional clutter. (But hard-core emacs users may object).

Minor cleanup of documentation guide

---

lib/matplotlib/backends/backend_webagg_core.py

We now implement the required underlying methods (copy_from_bbox and
restore_region), but there are issues with the double buffering in nbagg,
initialization issues, and with updates to the front end being dropped.
For mpl3.4.0 over-ride the class property that checks for the required methods
until we can fix the issues with blitting.
Closes #19701

FIX: do not report that webagg supports blitting

---

lib/matplotlib/_api/deprecation.py

`_delete_parameter` is currently used on `Tick.__init__`, which is
called *very* often when creating many axes.  This patch speeds up
```
MPLBACKEND=agg python -mtimeit -s 'from matplotlib.figure import Figure' -- 'Figure().subplots(10, 10)'
```
by ~20-25% (currently, just generating an 10x10 empty grid of axes takes
~1s).

Speed up _delete_parameter.

---

lib/matplotlib/colors.py

The deprecation would normally be removed 2 releases later (i.e., 3.5 for a 3.3 deprecation), but we need to extend it as we didn't fully determine the intermediate changes to make.
See #16991 and #19609.

Set colormap modification removal to 3.6.

---

.circleci/config.yml
examples/units/basic_units.py

The unit examples are broken in NumPy < 1.20. This fixes a bug that was exposed by #19415 ~~, but does not fix the examples fully. `radian_demo` is fixed by this change, but `ellipse_with_units` is still broken. I do not understand the NumPy subclassing methods enough to fix it short of reverting #19415..~~
A unit is a scalar, not a length-1 array. Though `BasicUnit` implements `__rmul__`, if multiplying by an array, the NumPy implementation will call `__array__` instead. If the LHS is an array, everything is fine, but if the LHS is a scalar, the previous code would incorrectly cause it to be upcast to a 1D array. When `__getitem__` was added in #19415, `np.atleast_1d` started iterating each (now 1D, not scalar) `TaggedValue`, seeing it was length 1, and made the x/y arrays into (N, 1) …

Fix example's BasicUnit array conversion.

---

lib/matplotlib/image.py

This deprecation is missing the addition/removal version, and it triggers an extra warning because it uses the old `cbook.warn_deprecated`.

Fix deprecation for imread on URLs.

---

doc/users/interactive_guide.rst

Small typo fixes to interactive guide.

---

doc/index.rst

The link is not modified by Sphinx and  just goes to `../CODE_OF_CONDUCT.md`, which doesn't exist in the Sphinx docs.
I already directly patched this on the docs repo after building 3.4.0 docs.

Fix code-of-conduct link on doc homepage.

---

doc/api/next_api_changes/removals/19801-AL.rst
lib/matplotlib/__init__.py
lib/matplotlib/_mathtext.py
lib/matplotlib/rcsetup.py
lib/matplotlib/tests/test_mathtext.py

Expire deprecation of mathtext.fallback_to_cm.

---

doc/api/next_api_changes/removals/19796-AL.rst
lib/matplotlib/__init__.py
lib/matplotlib/backend_bases.py
lib/matplotlib/backend_tools.py
lib/matplotlib/rcsetup.py

Expire ``keymap.all_axes``-related deprecations.

---

lib/matplotlib/offsetbox.py
lib/matplotlib/tests/test_offsetbox.py

`kwargs` need to be handled separately via `Artist.update`.  This
pattern is consistent with other artist subclasses (Line2D, _ImageBase,
Text, etc.).
Closes https://github.com/matplotlib/matplotlib/issues/7650.

Fix zorder handling for OffsetBoxes and subclasses.

---

doc/api/next_api_changes/deprecations/19795-AL.rst
doc/api/next_api_changes/removals/19795-AL.rst
examples/text_labels_and_annotations/usetex_baseline_test.py
lib/matplotlib/__init__.py
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/dviread.py
lib/matplotlib/rcsetup.py
lib/matplotlib/texmanager.py

Remove usetex-related APIs deprecated in Matplotlib 3.3.

---

doc/sphinxext/redirect_from.py

Fixes #19780.  @anntzer actually wrote the code, so perhaps he has a more elegant solution...

Fix non existent URI s

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

close #19776.
I don't know if this is exactly the reason for the problem, but it can fix the reported problem.

FIX errorbar problem with fillstyle

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/legend.py

Correct small typos in _axes.py and legend.py

---

lib/matplotlib/backends/backend_cairo.py

The `cairo.Antialias` Enum was added in pycairo 1.13, but we support 1.11. It also appears to not exist in cairocffi (https://github.com/Kozea/cairocffi/issues/183/).

Fix antialiasing with old pycairo/cairocffi.

---

lib/matplotlib/tests/test_backend_pdf.py

Depending on the exact way the pdf file is written, iterating over
Annots can fail after the file has been closed.  This is not the case
for matplotlib-generated pdfs, but is the case for mplcairo-generated
ones.  As a simple repro of the different behavior between
"in-the-contextmanager" and "out-of-the-contextmanager":
```python
plt.figtext(.5, .5, "hello, world", url="https://www.google.com")
plt.savefig("/tmp/test.pdf", backend="pdf")
import pikepdf
with pikepdf.Pdf.open("/tmp/test.pdf") as pdf:
page = pdf.pages[0]
print(repr(page.Annots)) # within contextmanager: ok
with pikepdf.Pdf.open("/tmp/test.pdf") as pdf:
page = pdf.pages[0]
print(repr(page.Annots))  # after contextmanager: AttributeError
```

Access pdf annotations while inside pikepdf.Pdf context manager.

---

lib/matplotlib/testing/compare.py

Closes https://github.com/matplotlib/matplotlib/issues/19809, at least locally (@jungerm2 can you confirm it works for you?)
I'd rather not figure out how to mess with CI to get Inkscape on Windows as well...

Fix Inkscape cleanup at exit on Windows.

---

lib/matplotlib/backends/_backend_tk.py

Closes https://github.com/matplotlib/matplotlib/issues/17584 (well, perhaps not https://github.com/matplotlib/matplotlib/issues/17584#issuecomment-640607651 but that seems to be a separate point which I didn't fully get...)

Fix tk event coordinates in the presence of scrollbars.

---

lib/matplotlib/backends/qt_editor/figureoptions.py

As described in [#19607](https://github.com/matplotlib/matplotlib/issues/19607), when multiple curves are given the same label, only the first one of each redundant label can be edited in the PyQT backend. This is because the curves and their corresponding labels have been saved in a dictionary. It's possible that a user may have a use case for giving multiple curves the same label, so they should be able to edit them separately as well.
To accommodate this, we modified the dictionary which was saving the labeled curves, replacing it with a list of tuples. The list of tuples is sorted in the same way.
I am not sure how to add the tests for this; so far I just tested it manually creating an instance of `NavigationToolbar2QT` and giving it redundantly named curves, and verify that they can …

Change dictionary to list of tuples to permit duplicate keys

---

doc/api/next_api_changes/removals/19810-AL.rst
lib/matplotlib/__init__.py
lib/matplotlib/backends/backend_agg.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/figure.py
lib/matplotlib/rcsetup.py
lib/matplotlib/tests/test_image.py

Looks like the change in default quality means test_jpeg_alpha must be slightly tweaked, but note that even as far back as when it was added, `num_colors` was already not completely deterministic... (https://github.com/matplotlib/matplotlib/pull/5324#issuecomment-151829388)

Remove JPEG-specific parameters and rcParams.

---

doc/api/next_api_changes/deprecations/19575-AL.rst
lib/matplotlib/text.py

get_prop_tup was intended as a general caching mechanism for reusing
Text layouts, but it ended up only being used by _get_layout (which
backends have to call anyways to handle multiline text).  Note that in
fact, if we really wanted to make backends use that info for caching,
whether e.g. the text color needs to be taken into account would likely
depend on the backend's own caching mechanism.
Replace it by a private `_get_layout_cache_key`, which does not take
color into account (color doesn't affect layout), which will later allow
removing a color-must-be-hashable check.

Deprecate Text.get_prop_tup.

---

lib/matplotlib/widgets.py

Both in other places in `widgets.py`, and in `patches.py`, it is convention to use `x0, y0` for the lower left corner of a rectangle, and `x1, y1` for the upper right.
This PR converts a few places in `widgets.py` to this convention for easy of readability.

Consistent corner variables names in widgets.py

---

doc/faq/howto_faq.rst
lib/matplotlib/axes/_axes.py

The explanation of a box plot is better placed at to the `boxplot()` function.

Move "howto interpreting box plots" to boxplot docstring

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_units.py

This allow using normal numpy constructs rather than manually looping
and broadcasting.
_process_unit_info was already special-handling `data is None` in a few
places; the change here only handle the (theoretical) extra case where a
custom unit converter would fail to properly pass None through.

Apply unit conversion early in errorbar().

---

lib/matplotlib/axes/_axes.py

Unfortunately, this bug only triggers with astropy's unit
implementation, but not with either of matplotlib's "test" units
(testing.jpl_units and test_units.Quantity).  So I don't have a
self-contained way to add a test...
Closes https://github.com/matplotlib/matplotlib/pull/19526#issuecomment-813423653.

Fix unit handling in errorbar for astropy.

---

lib/matplotlib/tests/test_backend_tk.py

Probably it can also be shared with test_interactive_backends in the
future.

Factor out machinery for running subprocess tk tests.

---

doc/faq/installing_faq.rst

This is only a link to the installation docs, which should be regarded
as the primary reference. We don't need FAQ entries that just link
there (We also don't have a FAQ entry "How do I install using conda").
Mid-term goal is to get rid of the "installing FAQ" altogether and
move relevant content directly to the installing docs.

Remove "Install from source" from Installing FAQ

---

doc/faq/howto_faq.rst
lib/matplotlib/pyplot.py

and move relevant content to show() docstring instead.
- "call once per skipt" is outdated --> removed.
- Relation to `savefig()` moved (and expanded).
- Interactive mode is linked in `show()` and does not need a detailed discussion here.
- Added a section on auto-show in jupyter notebooks.

Remove "Use show()" from how-to 

---

doc/faq/howto_faq.rst

- Remove "How-to: Plotting" subheader (it is the only header at this
level).
- Make all titles of the form "verb-complement" (so that the ToC reads
like a bunch of "how to... do this or that" entries; nearly all
sections already use that format).
- Strip extra whitespace.

Small cleanups to FAQ.

---

doc/faq/howto_faq.rst

Remove two sections from Plotting FAQ
- "Configure the tick widths"
This is a standard `tick_params()` parameter. Thus, the elaboration
on the implementation details (ticks are markers) is not needed for
the specific question. It's an off-topic comment, and as mentioned
also described in `axis-container` `tick-container` refs.
Furthermore, tick width is too specific for a FAQ.
- "Skip dates where there is no data"
As stated this is described in
`/gallery/text_labels_and_annotations/date_index_formatter`, so the
information is already available. I consider this too specific as well
to justify a FAQ entry.

Remove two sections from Plotting FAQ

---

lib/matplotlib/axes/_base.py

Previously, printing e.g. `ax.lines` would show a bunch of `<Line2D object at 0x...>`.  Now it's all hidden between an `<ArtistList>`, which is useful in itself (#18216); but displaying the length of the list (which is the main thing that could be seen from the `[<Line2D object at 0x...>` representation) is useful at least for debugging purposes.

Include length in ArtistList repr.

---

doc/api/next_api_changes/deprecations/19858-AL.rst
lib/matplotlib/axes/_base.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/lines.py

... rather than having each Line2D instance connect its own
callback.  (If we imagine a future where other artist classes can
also update themselves to use new units, one can imagine simply
having an `update_units` method on all artists (currently named
`recache_always`)).
I believe that the `units` and `units finalize` signals both
existed only to ensure that Line2D.recache_always was called before
`Axes._unit_change_handler`, but that's not necessary anymore (perhaps
we need a generic way of manipulating callback order but that'd be a
separate story).  Deprecating the signal directly on CallbackRegistry is
a bit ugly but that's how it was done for idle_event too...

Move Line2D units handling to Axes & deprecate "units finalize" signal.

---

doc/faq/howto_faq.rst

This is not worth mentioning anymore. `numpy.datetime64` work as
expected out of the box. The additional pandas converters comment is
off-topic. Overall, I don't think we need to mention them at all.
Third party packages are welcome to provide custom converters, but
that's none of Matplotlibs business.

Remove Howto: Plot numpy.datetime64 values

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/backends/backend_qt5agg.py
lib/matplotlib/backends/backend_qt5cairo.py
lib/matplotlib/backends/backend_webagg_core.py
lib/matplotlib/backends/web_backend/js/mpl.js
lib/matplotlib/tests/test_backend_qt.py

This is already implemented in two backends (Qt5 and nbAgg), and I plan to implement it in TkAgg, so it's better to remove the repetition.
It may also be useful for external backends.
~~I haven't fully tested this yet (though the test suite passes), as it's waiting for #19083 and #19123.~~
- [?] New features are documented, with examples if plot related.

Move pixel ratio handling into FigureCanvasBase

---

lib/matplotlib/pyplot.py

I read the code of `plt.xticks()` and got the impression that the x/yticklabels kwargs are applied twice in case labels are given.
I wonder if the application of the `kwargs` via `l.update()` should be in the true-branch of the if statement directly above:
If labels are given, `ax.set_xticklabels` is already passed the kwargs, so a subsequent `label.update(kwargs)` is not necessary. (Same for `yticks()`.)
I have tried to run the unit tests after this change, but I failed to set up a working development environment.
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) …

pyplot: do not apply kwargs twice in to x/yticklabels

---

doc/thirdpartypackages/index.rst

added information about including Framework :: Matplotlib in setup.py & that it's a searchable classifier on PyPI. And expanded a drop on what needs to be in the PR to get added to the page. 
Partially addresses matplotlib#16592

Added PyPI info to third party page

---

lib/mpl_toolkits/mplot3d/axes3d.py

... both the degree sign and the minus sign, which look better than the
pure ascii version.

Use unicode when interactively displaying 3d azim/elev.

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backend_tools.py

first commit:
Putting the case where a tool is active first avoids negated conditions
(e.g. re: event.inaxes), making things easier to follow.
Also, let SetCursorBase keep a reference to the currently active tool,
rather than its cursor, to avoid having the slightly confusing
`._cursor` next to `._default_cursor` and `._last_cursor`.
second commit:
Zoom/pan cannot be used e.g. on colorbars, which are "non-navigatable".
So don't set the zoom/pan cursor when the mouse is over them, either.
Putting the case where a tool is active first avoids negated conditions
(e.g. re: event.inaxes), making things easier to follow.
Also, let SetCursorBase keep a reference to the currently active tool,
rather than its cursor, to avoid having the slightly confusing
`._cursor` next to `._default_cursor` and …

Don't set zoom/pan cursor for non-navigatable axes.

---

lib/matplotlib/type1font.py

1st commit: Avoid constructing temporary strings in type1font parsing.
Just avoiding to construct a bunch of temporary strings (by instead
asking regexes to start their search at a given position) speeds up
```
python -c 'from pylab import *; mpl.use("pdf"); rcParams["text.usetex"] = True; plot(); [savefig("/tmp/test.pdf", backend="pdf") for _ in range(100)]'
```
by ~5%.
2nd commit: Combine whitespace and comment regexes.
This shaves off another percent or two of runtime.
3nd commit: Avoid repeatedly accessing enum values in type1font parsing.
Enum getattr is surprisingly slow; avoiding repeated attribute accesses
speeds up
```
python -c 'from pylab import *; mpl.use("pdf"); rcParams["text.usetex"] = True; plot(); [savefig("/tmp/test.pdf", backend="pdf") for _ in range(100)]'
```
by ~5%

Micro-optimize type1font loading

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

Fix errorbar drawstyle

---

doc/api/next_api_changes/removals/19922-ES.rst
lib/matplotlib/compat/__init__.py
lib/matplotlib/ttconv.py
src/_ttconv.cpp

Remove 3.3 deprecated modules

---

doc/api/next_api_changes/removals/19900-ES.rst
lib/matplotlib/_mathtext.py
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_agg.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/backends/backend_svg.py
lib/matplotlib/font_manager.py
lib/matplotlib/mathtext.py

Remove 3.3 text deprecations

---

doc/api/next_api_changes/removals/19901-ES.rst
doc/api/prev_api_changes/api_changes_3.3.0/deprecations.rst
lib/matplotlib/rcsetup.py
lib/matplotlib/tests/test_rcparams.py

Remove 3.3 rcParam deprecations

---

doc/api/next_api_changes/removals/19898-ES.rst
doc/api/prev_api_changes/api_changes_3.3.0/deprecations.rst
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/_backend_pdf_ps.py
lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_cairo.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/backends/backend_wx.py

Remove 3.3 backend deprecations

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

Fixes https://github.com/matplotlib/matplotlib/issues/19936

Allow numpy arrays to be used as elinewidth

---

doc/api/next_api_changes/deprecations/19934-DS.rst
examples/widgets/rectangle_selector.py
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

See https://github.com/matplotlib/matplotlib/issues/17473 for the behaviour of `drawtype='line'`, which is very odd and doesn't really work as a selector; @timhoffm suggested deprecating it in https://github.com/matplotlib/matplotlib/issues/17473#issuecomment-632396993, and I agree. Doing this will allow the internals of `RectangleSelector` to be greatly simplified, making it much easier for it to be modified in the future.
At the same time, `drawtype='none'` can just be achieved by making the rectangle invisible, so deprecate `drawtype` altogether.

Deprecate drawtype to RectangleSelector

---

lib/matplotlib/ticker.py

Follow up on https://github.com/matplotlib/matplotlib/pull/16003. This just avoids an implicit conversion from a numpy array of shape `(1,)` to a float. (Towards https://github.com/numpy/numpy/pull/10615).

avoid implicit np.array -> float conversion

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py
lib/mpl_toolkits/mplot3d/axes3d.py

And simplify a bit, plus generalize the naming.

Copy errorbar style normalization to 3D

---

lib/matplotlib/backends/backend_pdf.py

Closes https://github.com/matplotlib/matplotlib/issues/19506, see discussion there.

Don't create page transparency group in pdf output (for pdftex compat).

---

lib/matplotlib/figure.py
lib/matplotlib/tests/test_figure.py

Closes #19958
subfigure.get_tightbbox failed if there was nothing in the subfigure.  This adds a fallback to the bbox of the subfigure (and a small smoketest)

FIX: subfigure tightbbox

---

lib/matplotlib/tests/test_category.py

The plot function in `test_StrCategoryLocator1` in `test_category` is parametrized, but the test was using `ax.plot` so this PR has it use the parameter instead.

test_StrCategoryLocator using parameterized plotter

---

src/path_converters.h

MemorySanitizer complains about use-of-uninitialized-value in one of my tests.
WARNING: MemorySanitizer: use-of-uninitialized-value [....]src/path_converters.h:425:42 in PathClipper<PathNanRemover<agg::conv_transform<py::PathIterator, agg::trans_affine> > >::vertex(double*, double*)

Initialize members of PathClipper and check for m_has_init

---

.circleci/config.yml

Change the ssh key used to push back to devdocs.

CI: update the ssh key used to push the devdocs

---

lib/matplotlib/projections/polar.py
lib/matplotlib/tests/test_polar.py

Trying `set_xlim()` and undoing the changes if the range is wrong is
perhaps not the most elegant, but much easier than parsing the various
ways `*args, **kwargs` can be passed in.  Also this should be marginally
faster if the inputs are valid (and slower if they are invalid).
Closes https://github.com/matplotlib/matplotlib/issues/19986.

Fix set_thetalim((min, max)).

---

lib/matplotlib/backends/backend_ps.py
lib/matplotlib/tests/test_backend_ps.py

Closes https://github.com/matplotlib/matplotlib/issues/19979.
A rather "interesting" bug :p

Fix handling of "d" glyph in backend_ps.

---

lib/matplotlib/projections/polar.py

Minor fixes to polar locator docstrings.

---

lib/matplotlib/figure.py
lib/matplotlib/tests/test_figure.py

The order the Axes are added to the Figure (and hence the order they are in
the returned dictionary and fig.axes) is now based on the first time we see the
key if the layout were recursively unraveled as a c-style array.
Closes #19736
I don't think this needs an API change note as the order was previously unreliable.

FIX: add subplot_mosaic axes in the order the user gave them to us

---

doc/users/next_whats_new/widget_dragging.rst
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

As it says in the what's new entry:
The `~matplotlib.widgets.RectangleSelector` and `~matplotlib.widgets.EllipseSelector` have a new keyword argument, ``select_whole_region``, which when set to `True` allows you to click and drag from anywhere inside the selector to move it. Previously it was only possible to move it by either activating the move modifier button, or clicking on the central handle.
Questions:
- Any opinions on turning this on by default?
- Does anyone have any better ideas for the keyword argument name? `select_whole_region` is the best I came up with, but it doesn't feel great.
Here's an example:
https://user-images.githubusercontent.com/6197628/110214508-c892e480-7e9c-11eb-8544-fa0dc196bb12.mov

Allow Selectors to be dragged from anywhere within their patch

---

doc/users/next_whats_new/fig_draw_no_output.rst
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/backends/backend_svg.py
lib/matplotlib/figure.py
lib/matplotlib/tests/test_constrainedlayout.py
lib/matplotlib/tests/test_figure.py

Make user-facing `draw_no_output` to do the same thing as `fig.canvas.draw`

ENH: draw no output

---

lib/matplotlib/projections/polar.py

Immediately returning the desired ticks seems simpler than going through
a separate `show_all` flag.  (We could also compress all the `ifs` into
a single large expression...)

Small simplification to RadialLocator.

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/category.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/contour.py
lib/matplotlib/mlab.py
lib/matplotlib/patches.py

Misc fixes for proper numpydoc parsing, misnamed and non-existing parameters.

DOC: Fix numpydoc syntax, and parameters names.

---

lib/matplotlib/legend.py
tutorials/intermediate/autoscale.py

Correct minor typos in legend.py and autoscale.py

---

lib/matplotlib/tests/test_category.py

It saves only a line in each test, which is not worth the indirection.

Remove ax fixture from category tests.

---

lib/matplotlib/projections/polar.py

This ensures that there's a single place handling the restriction of
theta scales, which makes it simpler to follow (otherwise, in
ThetaAxis._set_scale, it's not clear what values can be taken by
`value`).
(see e.g. https://github.com/matplotlib/matplotlib/pull/20012/files#diff-f883675cd20e3f5e0f3c82d72bee7fc65253dea7cf2397e662551fdade5cd157R393)

Move restriction of polar theta scales to ThetaAxis._set_scale.

---

doc/devel/development_setup.rst
doc/devel/testing.rst

Don't really know where to put this, but I just spent like half an hour and a lot of install/uninstall/banging my head against a wall trying to figure out why pytest and numpy were conflicting in weird ways until I remembered that in conda you have to usually explicitly install pytest. Figure there are a couple of other really common things that mostly don't go out of date that might be worth including.

Dev install troubleshooting

---

lib/matplotlib/figure.py
lib/matplotlib/tests/test_figure.py

Closes #19947.  
The indexing to locate subfigures was wildly off.  Worked fine for 2x2 but was incorrect for anything larger.  
This PR fixes that and adds a test.

FIX: subfigure indexing error

---

doc/api/next_api_changes/behavior/20012-AL.rst
lib/matplotlib/projections/polar.py
lib/matplotlib/tests/test_polar.py

Currently, non-full-circle polar plots may (depending on the axes size)
put theta ticks at positions that make sense for linear plots, but are a
bit weird for polar plots (e.g. 50° or 25°).  Instead, prefer "standard"
angles (90°, 45°, 30°, 15°, 10°).  For really small axes, there's still
a problem because a single tick may end up at 150°, but fixing the
machinery to allow 15° while rejecting 150° would be trickier.
(Likewise, really thin slivers likely want ticks at 0.5° steps rather
than 0.45° :/)
```python
for ax in gcf().subplot_mosaic("AAAABBC", subplot_kw={"projection": "polar"}).values(): ax.set_thetalim(0, np.pi)
```
before:
after:

Fix default theta tick locations for non-full-circle polar plots.

---

lib/matplotlib/figure.py

- width_ratios and height_ratios are never None (None gets normalized to
[1, 1, ...] in the setters).
- We don't need to separately handle the `is_first_row()/is_last_col()`
cases (the sums will evaluate to 0/1 as needed).
- Naming the width/height dx/dy makes everything line up neatly.

Simplify _redo_transform_rel_fig.

---

doc/api/next_api_changes/behavior/20027-AL.rst
lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_polar.py

There's already special-casing for polar plots in bar() (using the same
`_interpolation_steps = 100`); it seems reasonable to use the same
approach for axvspan (e.g. `polar(); axvspan(0, pi/4)`).
It seems like making axhspan work (basically drawing full rings) is less
easy, but there's an easy enough workaround
(`polar(); bar(0, bottom=1, height=1, width=2*pi)`) as the "x" (theta)
extent is actually known in that case.
`plt.polar(); plt.axvspan(np.pi/4, np.pi/2)`
before:
after:

Fix axvspan for drawing slices on polar plots.

---

lib/matplotlib/tests/test_transforms.py
lib/matplotlib/transforms.py

Scaling transforms (with just nonzero diagonal terms) are quite common,
and special-casing them makes many transform reprs shorter, helping with
debugging.  See e.g. changes in the test_transforms reference output.

Shorten the repr of scaling transforms.

---

examples/widgets/cursor.py
examples/widgets/span_selector.py

- don't use 90ish background color. The default style is good enough (actually better IMHO).
- In the span selector:
- `'-'` is the default style. We don't need to specify it explicitly.
- It's more logical that the bottom "selected region" plot is empty at the beginning, when nothing has been selected so far.
- Use blue as a selection color (Nicer appearance IMHO)
- Some variable renaming.

Cleanup widget examples

---

src/ft2font_wrapper.cpp

Closes https://github.com/matplotlib/matplotlib/issues/20014 (see https://github.com/matplotlib/matplotlib/issues/20014#issuecomment-823565018).

Don't generate wheels unusable on PyPy7.3.{0,1}.

---

doc/api/next_api_changes/deprecations/13860-AL.rst
lib/matplotlib/collections.py
lib/matplotlib/colorbar.py
lib/matplotlib/dates.py
lib/matplotlib/tests/test_dates.py
lib/matplotlib/tests/test_ticker.py
lib/matplotlib/ticker.py
lib/mpl_toolkits/axisartist/grid_finder.py

Directly manipulating the underlying axis' view and data intervals is
clearer (see e.g. the changes in dates.py which ultimately just deletes
code that sets `self.axis`'s view and data intervals to themselves).

Deprecate {Locator,Formatter}.set_{{view,data}_interval,bounds}.

---

doc/api/next_api_changes/removals/20051-AL.rst
lib/matplotlib/offsetbox.py

Remove offsetbox APIs deprecated in Matplotlib 3.3.

---

examples/text_labels_and_annotations/demo_text_rotation_mode.py

The example can be written without involving axes_grid.
old: https://matplotlib.org/gallery/text_labels_and_annotations/demo_text_rotation_mode.html#sphx-glr-gallery-text-labels-and-annotations-demo-text-rotation-mode-py
new:
(admittedly the inability to set the absolute spacing between subplots is mildly annoying)

Don't use ImageGrid in demo_text_rotation_mode.

---

doc/users/next_whats_new/animatable_FancyArrow.rst
lib/matplotlib/axes/_axes.py
lib/matplotlib/patches.py
lib/matplotlib/tests/test_patches.py

Addresses point 7 of https://github.com/matplotlib/matplotlib/issues/5699 
Makes the `FancyArrow` Patch animatable. While `FancyArrowPatch` is somewhat animatable with `set_positions` there is no easy way to animate the Polygon that is returned from `plt.arrow`. This PR addresses that gap allowing things like this:
```python
%matplotlib ipympl
import ipywidgets as widgets
arrow = ax.arrow(0, 0, 0.5, 0.5)
ax.set_xlim([0, 1])
ax.set_ylim([0, 1])
width_slider = widgets.FloatSlider(min=0, max=0.5, step=0.02, description="width")
x_slider = widgets.FloatSlider(min=0, max=0.5, step=0.02, description="x")
def f(change):
arrow.set_data(x=x_slider.value, width=width_slider.value)
width_slider.observe(f, names="value")
x_slider.observe(f, …
```

make FancyArrow animatable

---

doc/api/next_api_changes/removals/20052-AL.rst
lib/mpl_toolkits/axes_grid1/axes_grid.py
lib/mpl_toolkits/axes_grid1/axes_rgb.py
lib/mpl_toolkits/axes_grid1/parasite_axes.py
lib/mpl_toolkits/axisartist/angle_helper.py
lib/mpl_toolkits/axisartist/axes_rgb.py
lib/mpl_toolkits/axisartist/axis_artist.py
lib/mpl_toolkits/axisartist/grid_finder.py

Remove axes_grid/axisartist APIs deprecated in Matplotlib 3.3.

---

lib/matplotlib/backends/backend_qt5.py

I don't know how often they are used, but it seems reasonable to allow
using them for distinguishing between axes.
No test because... because.
Closes https://github.com/matplotlib/matplotlib/issues/19929#issuecomment-817081916.

Include left and right titles for labeling axes in qt axes selector.

---

doc/api/next_api_changes/deprecations/20065-AL.rst
lib/mpl_toolkits/axes_grid1/axes_divider.py

This was never ever used in the git history, has a simple alternative,
and is consistent with 3b4d7c4 which removed the similar `add_all` from
other axes_grid APIs.

Deprecate AxesDivider.append_axes(..., add_to_figure=True).

---

doc/api/next_api_changes/deprecations/20063-AL.rst
lib/mpl_toolkits/axes_grid1/axes_divider.py
lib/mpl_toolkits/axes_grid1/axes_grid.py

They've never been used in the entire git history, are untested, and
seem easy enough to reimplement using public API if someone *really*
needs them.

Deprecate some untested, never used axes_grid1 methods.

---

doc/index.rst

This PR adds a top-level Sphinx `.. module::` definition for matplotlib to enable intersphinx links to the main matplotlib documentation, like :mod:`matplotlib`. This fixes #20061.

[DOC] Add top-level .. module:: definition for matplotlib

---

examples/axes_grid1/simple_axes_divider1.py

Improve labeling in simple_axes_divider1 example.

---

lib/matplotlib/axes/_base.py
lib/matplotlib/transforms.py
lib/mpl_toolkits/axes_grid1/axes_divider.py

... across the library.  I left the table for Axes.set_anchor (likely
the most common entry-point), but it doesn't seem worth copying it at
the other use sites.
Divider.set_anchor also supports pairs of floats (it just forwards to
Bbox.anchored anyways).

Harmonize descriptions of the 'anchor' parameter.

---

doc/conf.py

Reverts matplotlib/matplotlib#19389, as pytest 6.2.3 is out now and should fix the reference.

Revert "Temporarily switch intersphinx to latest pytest."

---

lib/mpl_toolkits/axes_grid1/axes_divider.py

They share some common calculation helpers, but a VBoxDivider is not a
specialization of an HBoxDivider, so just move the helpers out to free
functions (they're staticmethods or nearly so anyways).
Also rename "equivalent" to "equal" and "appended" to "summed", which I
think actually express the constraints better, and are shorter too.
Also document their usage, and PEP8-ify a couple of variables.

Don't make VBoxDivider inherit from HBoxDivider.

---

doc/api/next_api_changes/deprecations/20091-AL.rst
lib/matplotlib/tight_layout.py

- In get_tight_layout_figure, num2 is never None (since 658bbd5).  Also
rename some variables for pep8.
- auto_adjust_subplotpars could also be adjusted to remove the
`num2 is None` case, but in theory one could directly pass a
None-containing argument to it.  On the other hand it seems unlikely
that anyone is actually directly calling auto_adjust_subplotpars,
given the complex list of arguments needed (IOW it is clearly just a
helper for get_tight_layout_figure), so just deprecate the whole
function as public API, leaving a thin compat wrapper that remove
None-inputs as needed.

Cleanup tight_layout.

---

doc/api/next_api_changes/behavior/20064-AL.rst
lib/mpl_toolkits/axes_grid1/axes_divider.py
lib/mpl_toolkits/tests/test_axes_grid1.py

Note that the semantics of the rcParams are *relative* sizes, so they
should be interpreted as such here too.

Expire deprecation of AxesDivider defaulting to zero pads.

---

lib/matplotlib/backends/qt_compat.py

Apparently, this happens (see #20040 and related issues) sporadically. We don't care if we can't change the sip API version (if it's already been set), so also stop caring if the `setapi` function doesn't exist. This should simply cause the Qt4 backend to fail correctly later with an `ImportError` instead, and thus fall back to the next backend candidate.
Fixes #20040.
- [n/a?] Has pytest style unit tests (and `pytest` passes).
- [n/a] API changes …

Ignore errors for sip with no setapi.

---

doc/api/axis_api.rst
doc/api/next_api_changes/removals/20095-ES.rst
doc/api/prev_api_changes/api_changes_3.3.0/deprecations.rst
lib/matplotlib/axis.py
lib/matplotlib/backend_bases.py
lib/matplotlib/backend_tools.py
lib/matplotlib/dates.py
lib/matplotlib/pylab.py
lib/matplotlib/tests/test_ticker.py
lib/matplotlib/ticker.py

Plus some related Axis things.

Remove 3.3 ticker deprecations

---

lib/matplotlib/backend_bases.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/figure.py
lib/matplotlib/tests/test_axes.py

(The implementation of open_file_cm is very close to the second example
in the stdlib docs for nullcontext.)

Use nullcontext more as do-nothing context manager.

---

lib/mpl_toolkits/axes_grid1/anchored_artists.py
lib/mpl_toolkits/axes_grid1/inset_locator.py

- Prefer string locations to integers (reusing the description used in
the base AnchoredOffsetbox class).  Also switch from bullet list to
plain text list (with correct layout in asciiart), as I think having
the whole docstring fit in one screenful is also nice.
- Likewise, suppress blank lines between parameters (when all parameters
have a single-paragraph description) to avoid really long docstrings.
- Group axes_class and axes_kwargs parameters together; also very
slightly cleanup the implementation.
- Minor typo fixes.

Cleanup anchored_artists, inset_locator docstrings.

---

doc/sphinxext/redirect_from.py

The new `redirect_from` plugin prevented sphinx from running in parallel and changed the doc build performance from awfully slow to insanely slow.
This change improves the performances again to awfully slow 😄 . It's only relevant for people who arebuilding the docs in parallel (`make html -j4`).

Declare sphinxext.redirect_from parallel_read_safe

---

lib/matplotlib/axis.py
lib/matplotlib/figure.py
lib/matplotlib/projections/polar.py
lib/matplotlib/tests/test_polar.py

There's really two separate fixes here:
- Move isDefault_{maj,min}{loc,fmt} tracking to the Ticker instances,
where they logically belong (note the previous need to additionally
track them manually on axes removal, when that info was tracked on
the Axis).  This has the side effect of fixing removal of sharex'd
polar axes, as ThetaLocators rely on _AxisWrappers which don't have
that isDefault attribute.  (Note that the patch would have resulted
in a net decrease of lines of code if it didn't need to maintain
backcompat on isDefault_foos).  Closes #19988.  Split out of #13482.
- Ensure that RadialLocator correctly propagates Axis information to
the linear locator it wraps (consistently with ThetaLocator), so that
when an axes is removed the wrapped linear locator doesn't stay
pointing at an …

Fix removal of shared polar axes.

---

lib/matplotlib/patches.py

We can still support None angles as synonym to zero, but don't really
need to document them.

Shorten bracket arrowstyle docs.

---

doc/api/next_api_changes/deprecations/20108-AL.rst
lib/matplotlib/contour.py

Text.get_window_extents returns pixels, which get_label_width converts
to points, only for all call sites to immediately convert back to
pixels.  Just introduce a new internal API which uses pixels throughout.
(We could possibly deprecate get_label_width, but heh.)
Edit: get_label_width is deprecated, per the discussion below.

Skip back-and-forth between pixels and points in contour code.

---

.flake8
tools/subset.py

Fix flake8 and problems running on Python 3.

Cleanup subsetting tool.

---

lib/matplotlib/font_manager.py

Remove workaround unneeded on Py3.7+, which we require now.

---

.circleci/config.yml
.github/workflows/cibuildwheel.yml
doc/api/next_api_changes/development/20003-ES.rst
doc/devel/dependencies.rst
doc/devel/min_dep_policy.rst
lib/matplotlib/__init__.py
lib/matplotlib/tests/test_axes.py
requirements/testing/minver.txt
setup.py

Bump minimum NumPy to 1.17

---

lib/matplotlib/dviread.py
lib/matplotlib/tests/baseline_images/dviread/test.map
lib/matplotlib/tests/test_dviread.py

1st commit:
For reminder, pdftex.map is a file that maps tex font names ("cmr10") to
filesystem font names ("cmr10.pfb"), together with additional metadata
(font encoding, postscript special commands).  When using pdf output
with usetex, we parse usetex-generated dvi files and then need to locate
and load these fonts for embedding into the pdf file, hence then need to
parse pdftex.map.
On some systems (likely with large texlive installs), pdftex.map can be
really large (>10^4 entries), and parsing it is quite slow (>500ms on
the matplotlib macos).
This patch implements a new (simpler?) parser, which is ~25% faster
(so it can cut hundreds of ms on systems with large maps).  The patch
additionally correctly handles entries of the form `foo <bar.pfb`
(i.e., with no postscript font name -- in …

Speedup pdftex.map parsing.

---

doc/api/next_api_changes/deprecations/20109-AL.rst
lib/matplotlib/sphinxext/plot_directive.py
lib/matplotlib/tests/tinypages/some_plots.rst

The problem was that an input like
```
Some text.
>>> python_code()
The end.
```
would get split to
```
Some text.
>>> python_code()
```
and
```
The end.
```
and that unescape_doctest would then believe that `The end.` is already
python code (as it doesn't contain a `>>>`) and try to run it as is.
To fix this, instead of repeatedly calling `contains_doctest` everywhere
to guess whether fragments are doctest or python, just do it once at the
beginning, do the escaping once if needed at the beginning and then call
the new _functions (`_split_code_at_show`, `_run_code`) which don't try to
guess anymore.  Because of the new (non-guessing) semantics these must
go to new functions, so let's make them private and just deprecate the old
(public) ones.
The escaping itself was done by …

Fix trailing text in doctest-syntax plot_directive.

---

lib/matplotlib/backends/_backend_tk.py

Closes #19940. With these changes, the example script in that issue no longer has the `after` related stderr spam. No automated tests because the bug arises in a nested interactive event loop which is not a generally supported situation I think.
- [N/A] API changes …

Bugfix Tk start_event_loop

---

doc/users/next_whats_new/polygons_selector_remove_points.rst
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

This allows one to remove individual points of a `PolygonSelector` by right-clicking on them (mouse button 3).

Allow PolygonSelector points to be removed

---

lib/matplotlib/_text_helpers.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/tests/test_text.py
lib/matplotlib/textpath.py
src/ft2font.cpp

Improves the warning for cases like https://github.com/matplotlib/matplotlib/issues/16367.
Trying e.g. to use an Indic script now gives
```
<string>:5: UserWarning: Glyph 3520 (\N{SINHALA LETTER VAYANNA}) missing from current font.
<string>:5: UserWarning: Matplotlib currently does not support Sinhala natively.
```
We could even make the warning point to mplcairo... not that I particularly relish getting tons of bug reports about how to install it on obscure (i.e. nonlinux :-)) platforms.
The list of unicode blocks is at https://en.wikipedia.org/wiki/Unicode_block (I don't think it's available in the stdlib); I just hardcoded a few (Hebrew, Arabic, various Indic scripts) that I know are (almost) certainly not working due to shaping needs.
I moved the warning generation to Python because I …

Improve warning for unsupported scripts.

---

lib/matplotlib/figure.py
lib/matplotlib/pyplot.py
lib/matplotlib/tests/test_figure.py

Implements the True/False case of https://github.com/matplotlib/matplotlib/issues/18305 (the "row"/"col" case is still missing).

Support full-sharex/y in subplot_mosaic.

---

lib/matplotlib/_constrained_layout.py
lib/matplotlib/afm.py
lib/matplotlib/animation.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/colorbar.py
lib/matplotlib/font_manager.py

Quite a few are left, some for clarity (for now...), others because they
may possibly hint at underlying bugs (e.g. https://github.com/matplotlib/matplotlib/issues/20130).

Cleanup some "variable assigned but not used" lints.

---

examples/mplot3d/box3d.py

Suggestion from https://github.com/matplotlib/matplotlib/issues/19310
This pull request adds a new example for the 3D plots.
I am not sure how to check all steps from the Checklist, but it is simply adding a new example.
Origin of this suggestion: https://github.com/matplotlib/matplotlib/issues/19310

Create box3d example

---

tools/boilerplate.py

In Python 3.10 the repr and str representation of Enums changed from
str: 'ClassName.NAME' -> 'NAME'
repr: '<ClassName.NAME: value>' -> 'ClassName.NAME'
which is more consistent with what str/repr should do, however this breaks
boilerplate which needs to get the ClassName.NAME version in all versions of
Python. Thus, we locally monkey patch our preferred str representation in
here.
bpo-40066
https://github.com/python/cpython/pull/22392/
Other options considered:
- patch `MouseButton.__str__` in `matplotlib.backend_bases`.  This has the advantage of maintaining stability of `str(MouseButton.Left)` over time, but this feels like something we should not fight upstream on.  If they chose to break this intentionally we should follow them and not make our Enum "special"
- re-writing …

FIX: MouseButton representation in boilerplate generated signatures

---

lib/matplotlib/colors.py
lib/matplotlib/tests/test_colors.py

Fixed the CenteredNorm bug in issue #19972

fixed bug in CenteredNorm, issue #19972

---

lib/matplotlib/tests/test_artist.py
src/_backend_agg.cpp

This kind of path clipping just cuts the path on the bounding box, which produces an invalid clip path, since it is no longer closed or complete.
Fixes #20127.

Don't clip clip paths to Figure bbox.

---

src/_contour.cpp
src/_path.h
src/ft2font.cpp
src/mplutils.h
src/tri/_tri.cpp

This makes `TriContour` match `QuadContour` a little closer, by using `array_view`, and creating the final `tuple` in the same way.
It also removes redundant definitions of Path codes.

Cleanup some consistency in contour extensions

---

setupext.py
src/qhull_wrap.c
src/qhull_wrap.cpp

Converting the Qhull wrapper to use `array_view` means converting it to C++, but also means doing some rework to avoid `goto` and use destructors for cleanup instead. This works better with any exception flow.
Fixes #19627 with #19918.

Convert Qhull wrapper to C++ and array_view

---

.github/workflows/cibuildwheel.yml
.github/workflows/circleci.yml

The minimum NumPy with Python 3.8 wheels is 1.17.3, so bump CI to use that version. This should be fine since there aren't supposed to be ABI changes in micro releases.
Also drop remnants of 3.6 builds, that are mostly disabled already.
Corresponds to [this test build](https://github.com/QuLogic/matplotlib/actions/runs/808855055), which is working again …

Fix wheel builds on CI

---

doc/conf.py
requirements/doc/doc-requirements.txt

This adds the `image_srcset` parameter to our doc conf.py  This will require us to use sphinx-gallery dev version, which I'm not exactly sure how to setup on circleCI.  
https://github.com/sphinx-gallery/sphinx-gallery/pull/808

DOC: make 2x versions of all gallery figures

---

lib/matplotlib/artist.py
lib/matplotlib/axes/_base.py
lib/matplotlib/backend_bases.py
lib/matplotlib/figure.py
lib/matplotlib/widgets.py

This corresponds to _setattr_cm, but for Artist properties.
(Calling it `_set_cm` sounded too much like setting a "cm" property.
Perhaps `_setattr_cm` should have been `_cm_setattr`...)
See https://github.com/matplotlib/matplotlib/pull/19342#issuecomment-767018093 and discussion above.

Add Artist._cm_set for temporarily setting an Artist property.

---

lib/matplotlib/axis.py
lib/matplotlib/tests/test_axes.py

Actually, there were two issues:
- 'gridOn' state should always be contained in the _tick_kw settings.
This is needed because we support toggling via grid() and thus need
to be able to query the state. Therefore, the _tick_kw dicts must be
resetted instead of cleared.
- grid(some_kwarg=...) i.e. with b=None and keywords must be treated
explicitly as b=True as the docs already propose.
Closes #20149.

Fix resetting grid visibility

---

lib/matplotlib/gridspec.py
lib/matplotlib/tests/test_polar.py

In particular, hiding the "x/y" (i.e. theta/r) ticklabels doesn't make
sense for polar axes, and I'd guess likewise for most projections other
than the default rectilinear.  Try e.g.
`subplots(2, 2, subplot_kw=dict(projection="polar"), sharex=True, sharey=True)`.
before:
after:

Don't hide shared "x/y"ticklabels for grids of non-rectilinear axes.

---

doc/contents.rst
doc/devel/documenting_mpl.rst
doc/index.rst
doc/thirdpartypackages/index.rst

We now have a lighter third-party page at https://matplotlib.org/mpl-third-party that we hope will have a lower bar to entry than the current page (https://matplotlib.org/stable/thirdpartypackages/index.html).  This PR moves the page.

DOC: move third-party packages to new page

---

lib/matplotlib/tests/test_polar.py

Breakage arose from bad interaction between https://github.com/matplotlib/matplotlib/pull/19994 and https://github.com/matplotlib/matplotlib/pull/20161.

Fix broken test re: polar tick visibility.

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

Fix for #19871 but still needs tests.
I am hesitant to register the pandas converters because the test should still be useful to us even if pandas changes to returning arrays and because making sure we de-register the pandas handlers on failure is a bit fiddly.
This probably also fixes some latent bugs where the `safe_masked_invalid` was up-converting to an array too soon.

FIX: re-order unit conversion and mask array coercion

---

examples/text_labels_and_annotations/label_subplots.py

This new example demos a few approaches to adding labels to subplots, since this is a frequent request.

DOC: add example of labelling axes

---

doc/api/next_api_changes/removals/20188-ES.rst
lib/matplotlib/cbook/__init__.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_cbook.py

Remove 3.3 deprecations in cbook.

---

tutorials/introductory/usage.py

Usage guide edit

---

tutorials/colors/colormaps.py

As discussed in #20121, there are more packages that provide proper colormaps for MPL than is currently shown in the [colormaps tutorial](https://matplotlib.org/stable/tutorials/colors/colormaps.html) in the docs.
Instead of modifying this list every time such a thing is created, I replaced the links to `colorcet` and `palettable` with a link to the third-party colormap packages list [here](https://matplotlib.org/mpl-third-party/#colormaps-and-styles), as suggested in #20121.
I will add CMasher to the third-party list myself.
I think we should also add `palettable` and `colorcet` there to make sure they are still mentioned.
PS: I am not sure if this counts as a 'new feature', so I marked it as 'N/A' below.
- [N/A] Is [Flake …

Replaced links to colormap packages with link to third-party packages list in MPL docs

---

examples/pie_and_polar_charts/pie_and_donut_labels.py

On webpage `int(pct/100.*np.sum(allvals))` cause a wrong round and absolute number representation.
Here `int(round(foo))` make a not needed `int(foo)` conversion.
Remove the `int(foo)`.

Update round fix

---

lib/matplotlib/tight_layout.py

1st commit: Small style fixes.
Rename variables (inches->inch) for consistency and make formulas fit in
one line.
Small consistency fixes to warnings messages.
Doc fixes.
2nd commit: Simplify initial calculations in get_tight_layout_figure.
3rd commit: Comment re: non-working case of tight_layout.

More tight_layout cleanups

---

doc/api/next_api_changes/behavior/20046-BB.rst
doc/conf.py
lib/matplotlib/_api/deprecation.py
lib/matplotlib/tests/test_figure.py

We are currently unable to unintrusively deprecate class-level attributes (because we subclass UserWarning and not DeprecationWarning). Based on a previous dev call, we decided the solution was to "do it anyway". This led to a couple of issues, e.g. #19080 and #19839 and #19850. 
The history of the decision to not subclass DeprecationWarning has to do with a decision from core Python in the 2.x days to not show DeprecationWarnings to users. However, there is now a more sophisticated filter in place (see https://www.python.org/dev/peps/pep-0565/). 
Users that want to see MatplotlibDeprecationWarning in their CI will now have to `export PYTHONWARNING=d`, launch python with `-Wa`, or use warning filters to enable DeprecationWarnings (or MatplotlibDeprecationWarning specifically, depending on …

Deprecation warning

---

lib/matplotlib/lines.py
lib/mpl_toolkits/axisartist/axis_artist.py

We don't actually support color="auto" (we only support mfc="auto" and
mec="auto", which mean "use the main color").
This can easily be tested using `plt.plot([1, 2], c="auto")` which
crashes.

Fix validation of Line2D color.

---

doc/devel/MEP/MEP22.rst

Fix markup on MEP22.

---

lib/matplotlib/lines.py

np.any is quite slow, so avoid it if no numpy arrays are involved.
Because all ticks internally use lines, this change already speeds up
```sh
MPLBACKEND=agg python -mtimeit -s 'from matplotlib.figure import Figure' -- 'Figure().subplots(10, 10)'
```
by ~5%.

Speedup Line2D marker color setting.

---

lib/matplotlib/axes/_base.py

It is private, so we can restrict it to only support Cycler instances
and None (rather than also supporting `*args, **kwargs` from which a
new Cycler is constructed: the caller Axes.set_prop_cycle already takes
care of conversion into Cycler instances).
Split out of https://github.com/matplotlib/matplotlib/pull/19484 as the hopefully non-controversial part of it.

Simplify _process_plot_var_args.set_prop_cycle.

---

doc/api/next_api_changes/behavior/20199-AL.rst
lib/matplotlib/lines.py

Resolving None to mean "the rcParam" is both consistent with the
behavior in `__init__` (which manually maps None to the rcParam) and
with markeredgewidth.  In particular, being consistent with `__init__`
ensures that in
```
from pylab import *; from matplotlib.lines import Line2D
rcParams["lines.markerfacecolor"] = "red"
gca().add_artist(Line2D([.1, .9], [.1, .9], marker="o", markerfacecolor=None))
gca().add_artist(Line2D([.1, .9], [.9, .1], marker="o", mfc=None))
```
both lines use "red" as markerfacecolor (previously, the second one
would go through the setter and use "auto" (i.e. the line's color)
instead).
I guess this should have been done when the rcParams were added in
1d9880c, but missed back then.
(No change for markerfacecoloralt because there's no corresponding
rcParam; …

Make set_marker{edge,face}color(None) more consistent.

---

doc/api/next_api_changes/deprecations/20206-AL.rst
lib/mpl_toolkits/axisartist/floating_axes.py
lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py

axisartist stores in .grid_info various intermediary calculations used
to draw gridlines (which may be curved) and ticks.  It may be helpful to
change the internal representation of this info in the future (e.g.
using Paths directly rather than x, y arrays which have to be
continuously packed and unpacked), but doing so means that the attribute
should become private first.
Also remove the private _get_line_path, which was added in 008b765 but
apparently never ever used (we can always reintroduce something like
that if needed).

Cleanup axisartist in preparation for future changes.

---

lib/matplotlib/legend.py

... and remove a trailing dot in an exception message (consistently with
most of such messages).

Use check_getitem in legend location resolution.

---

doc/api/next_api_changes/deprecations/20209-AL.rst
lib/matplotlib/cbook/__init__.py

It's unrelated to Matplotlib's functionality, and more importantly it
likely never worked on Py3 (currently raising "'int' object has no
attribute 'split'") because the subprocess needs to be called with
`universal_newlines=True`, otherwise (currently) stdout is returned as
bytes and indexing that gives an int, not a str...

Deprecate cbook.report_memory.

---

examples/axes_grid1/simple_axes_divider1.py
examples/axes_grid1/simple_axes_divider3.py
lib/mpl_toolkits/axes_grid1/axes_divider.py
tutorials/toolkits/axes_grid.py

Closes https://github.com/matplotlib/matplotlib/pull/20069#issuecomment-826334326.
Goes on top of #20069 and #20072.  The example now gives
Writing a test specifically for this case is currently left as an exercise to the reader...

Support SubFigures in AxesDivider.

---

lib/matplotlib/cm.py
lib/matplotlib/image.py
lib/matplotlib/tests/test_collections.py

`imshow` allows `set_array` to pass lists, `Collection` does not. (Since `_ImageBase` overrides `set_array` of `ScalarMappable`, adding the ability to pass `array-like` inputs, and copy the input so changing list after calling function doesn't affect the plots)
This PR expands the `ScalarMappable` class to make a copy of the original input and casting it to arrays.
Fixes #18841

Expand ScalarMappable.set_array to accept array-like inputs

---

lib/matplotlib/axes/_axes.py

Shorten the implementation of violin().

---

doc/api/next_api_changes/deprecations/20170-AL.rst
lib/matplotlib/_api/deprecation.py
lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/figure.py
lib/matplotlib/tests/test_api.py
lib/matplotlib/widgets.py

SubplotParams.validate was previously only used in SubplotTool so that
when resetting the SubplotParams, a temporarily invalid SubplotParams
would be ignored.  But the temporary `validate = False` was put at the
wrong place (it should wrap `_on_reset`'s implementation, not its
attachment to `buttonreset`).  Indeed, setting e.g. "left" to 0.0 and
"right" to 0.01 and then pressing reset (when using e.g. tk) would throw
an exception (because "left" would first be reset to 0.125 before
"right" gets reset to 0.9, and the intermediate state is invalid).
Instead, just use the already existing `Widgets.eventson` mechanism to
temporarily disable updates.
Also apply the corresponding change for Qt's own SubplotTool.
Deprecate the then unused (and undocumented) SubplotParams.validate; in
order to …

SubplotParams.validate-associated fixes.

---

lib/matplotlib/_mathtext.py
lib/matplotlib/tests/test_mathtext.py

- fixes #17007 cmr10 negative sign `RuntimeWarning: Glyph 8722 missing from current font.`
- implementation suggested by https://github.com/matplotlib/matplotlib/issues/17007#issuecomment-685951519
Before this PR, this code would not render negative signs on the axes tick labels.
```python
import matplotlib
matplotlib.rcParams.update({
'font.family': 'cmr10',
'axes.formatter.use_mathtext: True
})
plt.figure()
plt.plot(range(-1, 1), range(-1, 1))
plt.title(r"dash (-) $mathtext:negative (-)\bf{mathtext.bf:negative (-)}$")
plt.xlabel(r"dash (-) $mathtext:negative (-)\bf{mathtext.bf:negative (-)}$")
``` …

fix cmr10 negative sign in cmsy10 (RuntimeWarning: Glyph 8722 missing)

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backends/_backend_tk.py
setupext.py
src/_c_internal_utils.c
src/_tkagg.cpp
src/_tkmini.h

At the moment, Tk does not support updating the 'scaling' value when the monitor pixel ratio changes, or the window is moved to a different one. Thus this needs a patch in the C extension to catch that window message and propagate it to Python. Due to thread locking issues, this needs to be done via a polled queue.
~~This is waiting for the pixel ratio refactor, #19126.~~

Add support for HiDPI in TkAgg on Windows

---

.flake8
doc/api/font_manager_api.rst
lib/matplotlib/font_manager.py

With Python 3.7, we now have [data classes](https://docs.python.org/3/library/dataclasses.html). I'm not sure if we want to start moving towards those, so I just converted one small one for discussion purposes.
(Plus a little cleanup to drop a flake8 exception)
- [?] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

Convert FontEntry to a data class

---

lib/matplotlib/dates.py
lib/matplotlib/tests/test_dates.py

close #19836
Although a little bit clumsy, this PR can serve as the interim solution to the format of month names when usetex=True. At a long term, some alternative way should be considered, as proposed by @anntzer.

FIX DateFormatter for month names when usetex=True

---

doc/users/next_whats_new/set_ticks_labels.rst
lib/matplotlib/axes/_secondary_axes.py
lib/matplotlib/axis.py
lib/matplotlib/tests/test_axes.py

As proposed in https://github.com/matplotlib/matplotlib/issues/18848#issuecomment-720154479 and discussed on today's dev call.
Closes #18848, #19016.
**kwargs:** I've added kwargs for text properties. While this makes the function do a lot (borderline of too much), it is necessary if we want a full replacement of `set_ticklabels(labels, **text_properties)`.
One can argue that this is actually too much, in which case we'd have to advertise
~~~
set_ticks(locs)
set_ticklabels(labels, **text_properties)
set_ticks(locs, labels)
tick_params(**text_properties)
~~~
**Return value:** `set_ticks()` has an undocumented return value (list of the Tick instances). While `plt.xticks()` returns a tuple `(locs, labels)` (list of Ticks and list of Texts), I don't want to do this here. First, I don't think …

Add labels parameter to set_ticks()

---

lib/matplotlib/figure.py

DOC: clarify that savefig(..., transparent=False) has no effect

---

lib/matplotlib/colors.py
lib/matplotlib/tests/test_colors.py

This adds an `__eq__` method to Colormap to test the lookup
tables for equality. This will help for testing whether colormaps are the same even if they aren't the same object.
`plt.get_cmap("Blues") == plt.get_cmap("Blues")` even if they aren't the same object anymore.
Taking just this portion out of the closed #16943.
- [N/A] API …

Adding an equals method to colormaps

---

lib/matplotlib/legend.py
lib/matplotlib/tests/test_legend.py

Previously this would result in the label color being ignored because
colors.to_rgba_array('none') results in a 0 length array which in turn has
a 0 length cycle, which results in the zip over texts and colors terminating
before we have touched any of the texts, ignoring the color.
This makes::
ax.legend(..., legendcolor='none')
ax.legend(..., legendcolor=['none'])
behave the same
Discovered this while reviewing https://github.com/matplotlib/matplotlib/pull/20084 and trying to demonstrate the difference between `None` and `'none'` in our color conventions.
- …

FIX: correctly handle ax.legend(..., legendcolor='none')

---

doc/devel/style_guide.rst

- Adjust widths in terminology table
- Comparison tables: 100% total width, 50% per column
Note: We need to use the `.. table::` directive explicitly to manipulate
the widths that are written in to `<colgroup>` by ReST. CSS alone cannot
override these.
Follow up to #20216.

Style tables in style guide

---

lib/matplotlib/cm.py

- "image array" is too narrow as most children of `ScalarMappable` are no images.
- It is important to note that we don't imply any shape or dimensionality of the array in the base class.

Clarify docstring of ScalarMappable.set/get_array()

---

.circleci/config.yml
doc/conf.py

This exports sphinx-gallery example run results to CircleCI, so we can get some idea of which examples fail often, etc., as in https://sphinx-gallery.github.io/stable/configuration.html#using-junit-xml-files
It _probably_ won't amount to much, but might as well try it out.

ci: Export sphinx-gallery run results to CircleCI.

---

lib/mpl_toolkits/mplot3d/axis3d.py

Explain Axis._get_coord_info better by adding comments and an (atleast to me) easier to read format. Should be no change in functionality.
Simplifies review of #19873 once merged. 

Add comments and format Axis._get_coord_info

---

lib/matplotlib/backends/backend_pgf.py

Saving a pgf file with images to an in-memory buffer
(`import io; imshow([[1, 2]]); savefig(io.BytesIO(), format="pgf")`)
currently warns that this is not possible (because the image needs to be
written to the filesyste), but in fact an exception gets raised
immediately after when trying to construct `Path(self.fh.name)`, so we
may as well replace the original warning by an exception.

Replace pgf image-streaming warning by error.

---

lib/matplotlib/legend_handler.py
lib/matplotlib/tests/test_legend.py

Simplify the legend handler for PolyCollection.
Alternative to #20260; closes #20258.
- [x ] Has pytest style unit tests (and `pytest` passes).
- [ x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).

Legend edgecolor face

---

doc/_templates/autosummary.rst
doc/devel/documenting_mpl.rst

Let's try and see if this works.
Closes #20080.
Follow up to #17151.

Limit documenting special members to __call__

---

lib/matplotlib/widgets.py

This PR fixes two bugs with blitting Selectors:
1. A recursive paint loop when resizing the figure with the qt backend.
2. Fix a similar issue as describe in #9660 but for `RectangleSelector`/`EllipseSelector` and `SpanSelector` once #20113 is merged, therefore fixing #9660 too!
Fix in https://github.com/matplotlib/matplotlib/commit/94a2f46f3cf0a6a621833fd3ac31b958e36e4910
From a juptyer qtconsole:
```python
%matplotlib qt
from matplotlib.widgets import RectangleSelector
values = np.arange(100)
ax.plot(values)
span = RectangleSelector(ax, print, useblit=True, interactive=True)
fig.canvas.flush_events()
span.extents = (26, 55, 32, 71)
```
When resizing the figure, the figure is flickering (in …

Fix blitting selector

---

doc/api/next_api_changes/behavior/20268-JMK.rst
lib/matplotlib/axes/_axes.py
lib/matplotlib/mpl-data/matplotlibrc
lib/matplotlib/tests/test_axes.py

Taking `pcolormesh(x, y, Z)`,  in 3.3.0 (#16258) we introduced the `'nearest'` and '`auto`' kwargs for *shading* in pcolor(mesh) to properly allow for *not* dropping the last row and column in the case that cell centres are passed for x and y.  
- Default: `'flat'`
- Cell edges: Z.shape = M, N, len(x) = N+1, len(y) = M+1
- 'flat': x and y specify cell edges
- 'nearest'/'gouraud': `TypeError`
- 'auto': 'flat'
- Cell centers: Z.shape = M, N, len(x) = N, len(y) = M
- 'flat': DeprecationWarning and drop last row and column
- 'nearest'/'gouraud': x and y specify cell centers
- 'auto': 'nearest'
- Default: `'auto'`
- Cell edges: Z.shape = M, N, len(x) = N+1, len(y) = M+1
- 'flat': x and y specify cell edges
- 'nearest'/'gouraud': `TypeError`
- 'auto': 'flat'
- Cell centers: Z.shape = M, N, …

Api pcolorargs deprecation

---

lib/matplotlib/_mathtext.py

No need to repeat the tokens expansion twice, and it seems reasonable
enough to check the string itself instead of inventing a separate
parameter just to pass the information of whether an overset or an
underset is being handled.

Fully fold overset/underset into _genset.

---

lib/matplotlib/axes/_axes.py

Factor out x/y lo/hi handling in errorbar.

---

doc/api/next_api_changes/deprecations/20126-AL.rst
lib/matplotlib/font_manager.py
lib/matplotlib/tests/test_font_manager.py

The font enumeration logic on Windows was relatively difficult to
follow, being split over three different functions (win32FontDirectory,
_win32RegistryFonts, and win32InstalledFonts), with variable names that
did not clearly indicate whether they are directories (such as
MSUserFontDirectories) or registry keys (such as MSFontDirectories).
Inline most of the logic to _get_win32_installed_fonts, and also
get rid of the extension filtering (both here and in
get_fontconfig_fonts), as it can be done once for all at the call site
(in `findSystemFonts`); also make the helpers return Paths, for simpler
manipulation (we still convert to strs at the end).

Simplify font_manager font enumeration logic.

---

doc/api/next_api_changes/deprecations/19441-AL.rst
lib/matplotlib/backends/backend_gtk3.py

This should ultimately make it easier to generate apidocs on CI.
The change in value of `cursord` only happens on headless envs, where
the module was not importable at all before, so that's not an API break.

Make backend_gtk3foo importable on headless environments.

---

doc/api/next_api_changes/deprecations/20193-AL.rst
lib/mpl_toolkits/axes_grid1/parasite_axes.py

- The base Axes class now defines `get_axes_locator`, so there's no need
for a hasattr() check.
- Now that all artists are stored in a single list, there's no need to
split the parasite axes' artists by type when pushing them into the
host's artist list.  Also it's fine to include non-visible artists, as
they'll be filtered out later.  This means that
`ParasiteAxesBase.get_images_artists` becomes unused and can be
deprecated (as it's clearly an internal helper).

Simplify HostAxes.draw and its interaction with ParasiteAxes.

---

lib/matplotlib/texmanager.py

If the same font is used in sans + serif, then the `usepackage` gets duplicated. This appears harmless, but can be de-duplicated to shorten the produced LaTeX files.

De-duplicate fonts in LaTeX preamble.

---

doc/api/toolkits/axes_grid.rst
doc/api/toolkits/axes_grid1.rst
doc/api/toolkits/axisartist.rst

Slightly reword intros of mpl_toolkits API docs.

---

doc/api/next_api_changes/behavior/19375-AL.rst
lib/matplotlib/axes/_base.py
lib/matplotlib/figure.py
lib/matplotlib/image.py
lib/matplotlib/tests/test_image.py

Closes https://github.com/matplotlib/matplotlib/issues/18499.

Don't composite path-clipped image; forward suppressComposite as needed.

---

doc/api/next_api_changes/deprecations/20278-AL.rst
lib/matplotlib/texmanager.py

This prevents in particular the gigantic `grey_arrayd` from appearing in
the rendered docs.  (`texcache` could also be deprecated but at least in
theory I can think of reasonable reasons one may want to access it.)
(see https://matplotlib.org/devdocs/api/texmanager_api.html#matplotlib.texmanager.TexManager.grey_arrayd)

Deprecate public access to certain texmanager attributes.

---

examples/event_handling/pipong.py
examples/user_interfaces/fourier_demo_wx_sgskip.py
examples/user_interfaces/svg_histogram_sgskip.py

These are skipped because they can't be run on the docs build for one reason or another, but they broke at some point.

Fix some examples that are skipped in docs build

---

lib/matplotlib/backends/backend_svg.py
lib/matplotlib/tests/test_backend_svg.py
lib/matplotlib/tests/test_mathtext.py

The 'font: ...' shorthand is much more concise than setting each
property separately: This replaces e.g.
`"font-family:DejaVu Sans;font-size:12px;font-style:book;font-weight:book;"`
by `"font: 400 12px 'DejaVu Sans'"`.
Note that the previous font weight was plain wrong...
Also this revealed a bug in generate_css (we shouldn't run it through
escape_attrib, as quotes (e.g. around the font family name) get
mangled); and we don't need to load the font at all (we should just
report whatever font the user actually requested).
Split out of https://github.com/matplotlib/matplotlib/pull/19201, but also including the non-mathtext case.

Improve font spec for SVG font referencing.

---

doc/users/next_whats_new/rcparams_legend.rst
lib/matplotlib/legend.py
lib/matplotlib/mpl-data/matplotlibrc
lib/matplotlib/rcsetup.py
lib/matplotlib/tests/test_legend.py
lib/matplotlib/tests/test_rcparams.py

This is a proposal for a new `legend` rcParam.
The `legend.labelcolor` was proposed in #20049. It's for changing the `labelcolor` of all figures(similar to the labelcolor of `plt.legend`)  
Example:
import lib.matplotlib.pyplot as plt
a = np.arange(2, 3, .02)
c = np.exp(a)
plt.rcParams['legend.labelcolor'] = 'linecolor'
ax.plot(a, c, 'g', label='Model length')
ax.plot(c, a, 'r', label='Data length')
legend = ax.legend()
plt.show()

Add legend.labelcolor in rcParams

---

lib/matplotlib/backends/backend_gtk3.py

This was broken in #19441 because toolmanager uses a fake version of the toolbar2 class which doesn't have any static (or otherwise) methods.

Fix cursor with toolmanager on GTK3.

---

doc/devel/documenting_mpl.rst
doc/missing-references.json
lib/matplotlib/artist.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/axes/_subplots.py
lib/matplotlib/collections.py
lib/matplotlib/docstring.py
lib/matplotlib/figure.py
lib/matplotlib/lines.py
lib/matplotlib/patches.py
lib/matplotlib/pyplot.py
lib/matplotlib/quiver.py
lib/matplotlib/sankey.py
lib/matplotlib/spines.py
lib/matplotlib/table.py
lib/matplotlib/text.py
lib/mpl_toolkits/axes_grid1/inset_locator.py
lib/mpl_toolkits/mplot3d/axes3d.py

This does two things:
- Replace Foo_kwdoc docstring substitutions by auto-generated
Foo:kwdoc substitutions, removing the need to explicitly call
`docstring.interpd.update(Foo_kwdoc=artist.kwdoc(Foo))` for each
artist.
- Decorating a class with `docstring.interpd` will now also perform
interpolation over the docstring of the class' `__init__`, making it
possible to list properties here as well, instead of having to
manually call `docstring.interpd` after the class has been defined.
The new behavior is also explained in documenting_mpl.rst.  I think it's
slightly more magical, but also easier to explain...
Thoughts?

Auto-generate required kwdoc entries into docstring.interpd.

---

doc/api/next_api_changes/deprecations/20237-TH.rst
lib/matplotlib/axes/_axes.py
lib/matplotlib/collections.py
lib/matplotlib/tests/test_collections.py

This is in preparation of changing the signature from 
`__init__(self, meshWidth, meshHeight, coordinates, antialiased=True, shading='flat', **kwargs)`
to 
`__init__(self, coordinates, *, antialiased=True, shading='flat', **kwargs)`
See also: https://github.com/matplotlib/matplotlib/pull/18472#issuecomment-841735177
If we want to make this according to deprecation rules this is a multi-step process:
- Make everything after `coordinates` keyword-only. (This PR).
- When that deprecation expires (in 3.7), change to
`__init__(self, *args, antialiased=True, shading='flat', **kwargs)` and extract `meshWidth, meshHeight, coordinates` from `args, kwargs`. At the same time, deprecate passing `meshWidth, meshHeight, 1d_coordinates` in favor of passing 2D coordinates only.
- When that deprecation …

Make QuadMesh arguments with defaults keyword_only

---

lib/matplotlib/tests/test_ticker.py
lib/matplotlib/ticker.py

Following up the patch mentioned in https://github.com/matplotlib/matplotlib/pull/18397#pullrequestreview-655033417, w.r.t. @anntzer's original comment https://github.com/matplotlib/matplotlib/pull/18397#issuecomment-826615489
> we could even emit a warning when cmr10 is used in a non-mathtext context, as that seems to be pretty common
When using the "cmr10" font (or possibly more mathtext-fonts) for ticks, one should set `rcParams["axes.formatter.use_mathtext"] = True` to trigger the machinery implemented by https://github.com/matplotlib/matplotlib/pull/18397
Possible improvements:
- Move the warning to an outer scope, for all Formatters (not just ScalarFormatter) - do we need to?
- Include other mathtext-fonts

Warn user when mathtext font is used for ticks

---

doc/api/next_api_changes/deprecations/19558-AL.rst
lib/matplotlib/dviread.py
lib/matplotlib/mpl-data/kpsewhich.lua
lib/matplotlib/texmanager.py
tutorials/text/usetex.py

`luatex --luaonly` runs a *lua* interpreter with relevant tex libraries
available, which avoids the overhead of repeatedly initializing
kpathsea (the old approach, very slow on macos and windows).  An
alternative approach would be to use `luatex` followed by `\directlua`
calls, but on windows it appears that one needs to use `lualatex` to get
a working interactive prompt, and just loading the latex format takes
seconds(!).
For the simple following benchmark:
```sh
python -c 'from pylab import *; mpl.use("pdf"); rcParams["text.usetex"] = True; plot(); savefig("test.pdf", backend="pdf")'
```
On a macos machine, this patch brings runtime from ~4.5s to ~2.5s.
On a windows machine, this patch brings runtime from ~6.5s to ~1.7s.
We also need to figure out how to best advertise this (do we emit …

Use luatex in --luaonly mode to query kpsewhich.

---

examples/axes_grid1/inset_locator_demo2.py
examples/lines_bars_and_markers/stem_plot.py
examples/mplot3d/stem3d_demo.py
examples/scales/custom_scale.py
examples/ticks_and_spines/date_concise_formatter.py
examples/ticks_and_spines/date_precision_and_epochs.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/matplotlib/backend_bases.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/collections.py
lib/matplotlib/colorbar.py
lib/matplotlib/gridspec.py
lib/matplotlib/legend.py
lib/matplotlib/path.py
lib/matplotlib/patheffects.py
lib/matplotlib/projections/polar.py
lib/matplotlib/pyplot.py
lib/matplotlib/quiver.py
lib/matplotlib/textpath.py
lib/mpl_toolkits/mplot3d/axes3d.py
tutorials/advanced/blitting.py
tutorials/intermediate/constrainedlayout_guide.py
tutorials/intermediate/imshow_extent.py
tutorials/intermediate/legend_guide.py

From the [shpinx docs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#cross-referencing-syntax):
> If you prefix the content with ~, the link text will only be the last component of the target.
If only a single component is given, the tilde doesn't have any effect
(`` `~.foo` `` is the same as `` `.foo` ``), so we can remove it to increase
readability.

Remove tilde in code links where not necessary

---

lib/matplotlib/image.py
lib/matplotlib/tests/test_image.py

Closes https://github.com/matplotlib/matplotlib/issues/15432.  Supersedes https://github.com/matplotlib/matplotlib/pull/15436.

Support imshow(<float16 array>).

---

lib/matplotlib/dviread.py

Directly read as signed int32 ("i") instead of reading as signed int32
and converting to unsigned later using fix2comp.
Simplify parsing of widths/heights/depths.

Simplify tfm parsing.

---

doc/api/next_api_changes/deprecations/20302-AL.rst
lib/matplotlib/backend_bases.py
lib/matplotlib/collections.py

convert_mesh_to_paths and convert_mesh_to_triangles both rely on
non-flat indexing of `coordinates`, and don't actually need the
meshWidth and meshHeight arguments (they are only used in calls to
reshape(), but reshape() can just use -1 for the unknown dimension).
Instead of going through signature deprecation, just deprecate the
methods, which are essentially helpers to generate calls to
draw_quad_mesh and draw_gouraud_triangles.
Followup to https://github.com/matplotlib/matplotlib/pull/20237.

Further remove use of meshWidth, meshHeight in QuadMesh.

---

tutorials/text/pgf.py

I haven't actually checked, but my guess is that this must have been fixed per some combo of https://github.com/matplotlib/matplotlib/issues/1324#issuecomment-24133506 and https://github.com/matplotlib/matplotlib/pull/18654#issuecomment-704888296.

Remove outdated comment re: pgf/windows.

---

lib/matplotlib/dviread.py

dviread is an implementation detail for most users, so let's not mention
it.

Don't mention dviread in the PsfontsMap "missing entry" error message.

---

lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_polar.py

Special-casing a check for get_xaxis_transform() is a bit ugly and
definitely not general, but fixes the main issue at hand...
(Shortening the variable names to _trf mostly helps avoiding line
continuations, and I also made the layout in _update_line_limits and
_update_patch_limits closer to one another; the main relevant change
feature-wise is just the `if name != "rectilinear"` blocks.)
"Fixes" (effectively) #20030 by adding a special case, but this is not a general solution

axvline()/axvspan() should not update r limits in polar plots.

---

lib/matplotlib/collections.py
lib/matplotlib/tests/test_collections.py

This returns the coordinates used to create the Quadmesh collection. These can be useful for knowing what vertices were used to generate the mesh returned from `pcolormesh`.
closes #18399

Adding a get_coordinates() method to Quadmesh collections

---

doc/api/next_api_changes/deprecations/20311-AL.rst
lib/matplotlib/rcsetup.py
lib/matplotlib/tests/test_rcparams.py

See changelog note for motivation.
Closes bug 1 of https://discourse.matplotlib.org/t/issue-rendering-a-latex-formula/21977/2

Warn if a non-str is passed to an rcParam requiring a str.

---

examples/images_contours_and_fields/contourf_demo.py
examples/images_contours_and_fields/tripcolor_demo.py
examples/lines_bars_and_markers/filled_step.py
examples/lines_bars_and_markers/gradient_bar.py
examples/shapes_and_collections/collections.py
examples/specialty_plots/topographic_hillshading.py
examples/statistics/boxplot.py
examples/statistics/confidence_ellipse.py
examples/statistics/customized_violin.py
examples/statistics/errorbars_and_boxes.py
examples/statistics/hist.py
examples/statistics/histogram_cumulative.py
examples/subplots_axes_and_figures/secondary_axis.py
examples/text_labels_and_annotations/annotation_demo.py
examples/text_labels_and_annotations/fonts_demo.py
examples/text_labels_and_annotations/fonts_demo_kw.py
examples/text_labels_and_annotations/titles_demo.py
examples/ticks_and_spines/custom_ticker1.py
examples/ticks_and_spines/date_concise_formatter.py
examples/units/basic_units.py
tutorials/intermediate/constrainedlayout_guide.py
tutorials/intermediate/imshow_extent.py
tutorials/introductory/lifecycle.py
tutorials/introductory/pyplot.py
tutorials/introductory/usage.py
tutorials/text/text_intro.py
tutorials/text/text_props.py

I like to avoid this particular bit of jargon.
Some additional re-wrapping and correction of argument styling also.

DOC: Spell out args/kwargs in examples/tutorials

---

doc/api/next_api_changes/removals/19033-AL.rst
doc/missing-references.json
lib/matplotlib/axes/_subplots.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_pickle.py
lib/mpl_toolkits/axes_grid1/parasite_axes.py
lib/mpl_toolkits/axisartist/floating_axes.py

This makes mpl_toolkits axes classes picklable (see test_pickle) by
generalizing the machinery of _picklable_subplot_class_constructor,
which would otherwise have had to be reimplemented for each class
factory.

Templatize class factories.

---

doc/api/next_api_changes/deprecations/20208-AL.rst
lib/matplotlib/_blocking_input.py
lib/matplotlib/blocking_input.py
lib/matplotlib/contour.py
lib/matplotlib/figure.py

The new implementation is ~200 lines shorter, does not require
subclassing (and tracking parent methods when trying to understand the
implementation), and keeps all the logic at the place of use instead of
it being in blocking_input.py (which is now deprecated).
(Run `examples/event_handling/ginput_manual_clabel_sgskip.py` to test
`clabel(..., manual=True)`.)

Rewrite blocking_input to something much simpler.

---

doc/api/next_api_changes/removals/19348-OE.rst
lib/matplotlib/dates.py
lib/matplotlib/tests/test_dates.py

This makes  the YearLocator a subclass of RRuleLocator instead of DateLocator.
Advantanges:
- less custom code, tick positions are now determined through rrule, pytz is now handled through the rrulewrapper
- easier implementation of locators for potential timedelta support (#19236)

Make YearLocator a subclass of RRuleLocator

---

lib/matplotlib/tests/test_texmanager.py

This can later be expanded for https://github.com/matplotlib/matplotlib/pull/20293.

Add test for font selection by texmanager.

---

doc/api/next_api_changes/removals/20314-GL.rst
lib/matplotlib/colorbar.py

- Remove multiple mappable updating methods.
- Make the base colormap class take only one argument and the
rest are keywords only.
- Remove the warning when overwriting keyword arguments with
the value from the mappable.

MAINT: Removing deprecated colorbar functions.

---

lib/matplotlib/artist.py
lib/matplotlib/collections.py
lib/matplotlib/image.py
lib/matplotlib/tests/test_collections.py

The motivation is actually to provide get_cursor_data for hist2d, which
uses a QuadMesh to draw itself (see the test).
As it turns out, Collection.contains already contains the relevant code
to find which path contains the mouse event, so just reuse that.

Implement get_cursor_data for QuadMesh.

---

lib/matplotlib/__init__.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/contour.py
lib/matplotlib/quiver.py
lib/matplotlib/stackplot.py
lib/matplotlib/streamplot.py
lib/matplotlib/tests/test_preprocess_data.py

Replaces #19859. This approach uses an explicit template
```
data : indexable object, optional
```
in the docstring and does not try to guess a reasonable insertion
position based on the docstring content. This is much simpler.

Write data parameter docs as regular parameter not as note (v2)

---

lib/matplotlib/axes/_axes.py

A quick googling hasn't shown any use of "co-erce"; MW (e.g.) only gives
"coerce".

Fix spelling.

---

doc/missing-references.json
doc/users/prev_whats_new/whats_new_1.3.rst
doc/users/prev_whats_new/whats_new_1.4.rst
doc/users/prev_whats_new/whats_new_1.5.rst
doc/users/prev_whats_new/whats_new_2.0.0.rst
doc/users/prev_whats_new/whats_new_2.1.0.rst
doc/users/prev_whats_new/whats_new_3.0.rst
doc/users/prev_whats_new/whats_new_3.1.0.rst
lib/matplotlib/pyplot.py

Most are simply converting to other styles (italic for arguments, or code style for something that won't be linked), but there are a few things that were not documented and should have been.

DOC: Fix missing refs in what's new pages

---

.flake8
doc/conf.py
lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_template.py
lib/matplotlib/backends/qt_editor/_formlayout.py
lib/matplotlib/lines.py
lib/matplotlib/offsetbox.py
lib/matplotlib/text.py
lib/matplotlib/tri/triinterpolate.py
lib/mpl_toolkits/axes_grid/__init__.py
lib/mpl_toolkits/axisartist/axis_artist.py
lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
lib/mpl_toolkits/mplot3d/axis3d.py

This resolves the inconsistency that inline comments must start with a space (E262), but block comments are allowed not to.
This is the last followup to #19626 and #19887.

Fix remaining E265 exceptions.

---

lib/matplotlib/legend.py

Better align param comments in `Legend.__init__` signature.

---

doc/api/next_api_changes/deprecations/20237-TH.rst
lib/matplotlib/collections.py
lib/matplotlib/tests/test_collections.py

Fixes #20322 
The default value is now updated and tests for both the old and new Quadmesh signatures for their default value.
I've also updated the previous faulty changelog.

Quadmesh's default value of shading is now set to 'flat' instead of False
