doc/api/animation_api.rst
doc/api/colors_api.rst
doc/api/dates_api.rst
doc/api/transformations.rst
lib/matplotlib/afm.py
lib/matplotlib/legend_handler.py
lib/matplotlib/mlab.py
lib/matplotlib/table.py
lib/matplotlib/texmanager.py
lib/matplotlib/tight_layout.py
lib/matplotlib/units.py

This fixes some minor typos on module pages, and some tweaks to callouts and inheritance diagrams.
Strong recommendations at the top of module are now `.. important`, less strong are now `.. note`. I dropped extra classes from the date and transform inheritance diagrams. I'm not sure if `Artist` should hide `_AnnotationBase` and `ScalaraMappable` as well?
I also noted that the table is lightly maintained and that blume may be preferable, but I'm not sure if we should just point at the third-party page in general? …

DOC: Tweaks to module API pages

---

lib/matplotlib/projections/polar.py
lib/matplotlib/tests/test_polar.py

... similar to what's done for cartesian plots since #16776 (in
ScalarFormatter.format_data_short).

For polar plots, report cursor position with correct precision.

---

doc/api/next_api_changes/deprecations/20334-AL.rst
examples/units/basic_units.py
examples/units/evans_test.py
lib/matplotlib/axis.py
lib/matplotlib/category.py
lib/matplotlib/testing/jpl_units/EpochConverter.py
lib/matplotlib/testing/jpl_units/StrConverter.py
lib/matplotlib/testing/jpl_units/UnitDblConverter.py
lib/matplotlib/tests/test_category.py
lib/matplotlib/units.py

This avoids having each ConversionInterface.convert having to start by
doing the same call to is_numlike.
(Axis.convert_units, which should be the user-facing entry point, checks
_is_natively_supported first, which prevents unitless values from being
sent to ConversionInterface.convert.)

Remove need for ConversionInterface to support unitless values.

---

lib/matplotlib/units.py

- Cleanup module docstring of units.py.
- Cleanup DecimalConverter.convert.
- Make DecimalConverter.{axisinfo,default_units} directly inherit from
base class.  (`info = None` is explicitly checked in
`_update_axisinfo` before calling `set_default_intervals`.)

Small unit-related cleanups.

---

lib/matplotlib/axes/_base.py
lib/mpl_toolkits/mplot3d/axes3d.py

Autoscaling is not applied (anymore) when a plot command is executed,
but at draw time (or when explicitly calling autoscale_view()).
(Re: get_autoscale_on: I usually prefer the "Return whether..." wording,
but here it would make unclear what happens if only some axes are
autoscaled.)

Cleanup autoscale-related docstrings.

---

src/py_adaptors.h

If one calls set() twice on the same PathGenerator, the first m_paths
needs to be decref'd.  (We don't actually ever call set twice, I think,
but stil...)

Fix possible refleak in PathGenerator.

---

extern/ttconv/ttutil.cpp

I don't think it is possible to exercise the failing codepath except
with artificial fonts having extremely long metadata entries, but the
missing write is clear from the context.

Fix missing write in TTStreamWriter::printf.

---

lib/matplotlib/tests/test_agg.py
src/_backend_agg_wrapper.cpp
src/_path_wrapper.cpp
src/py_adaptors.h
src/py_converters.cpp
src/py_converters.h

The PathGenerator constructor does not set a Python-level exception on
failure.  Switch to use a PyArg_ParseTuple-style converter to get proper
error handling.
(Also, CALL_CPP already converts py::exception to Python-level
exceptions, so it doesn't need to be wrapped in a C++-level try...
catch.)
Closes https://gitter.im/matplotlib/matplotlib?at=60b71b8478e1d6477d7ad9a3
(well, the C error handling part at least).

Fix exception handling when constructing C-level PathGenerator.

---

lib/matplotlib/__init__.py

We don't actually require `data` to support `key in data`; we only ever
try `data[key]` (treating any exception as meaning "`key` is not in
`data`, use its value directly").  This can be checked e.g. by creating
a custom type that supports `__getitem__` but throws on `in` checks, and
verify that it can be used as `data`:
```python
class T: __getitem__ = lambda self, k: {"foo": 1, "bar": 2}[k]
l, = plt.plot("foo", "bar", data=T())
l.get_xydata()  # == [[1, 2]]
"foo" in T()  # raises
```
So delete the statement about `s in data`; the statement about `data[s]`
can also be removed as it is clearly implied by the fact that "`s` is
interpreted as `data[s]`".

Remove incorrect statement about data-kwarg interface.

---

setup.py

While setuptools-scm does not yet support our branch naming scheme for release branches, it will soon [1]. And we won't have to worry about that until we actually branch for 3.5.0, since the v3.4.x branch doesn't use it.
[1] https://github.com/pypa/setuptools_scm/pull/573
Fixes #19419.

Switch version scheme to release-branch-semver.

---

doc/_templates/layout.html
doc/_templates/search.html

In particular mobile browsers use correction mechanisms on input fields. Search will often be done with technical terms or even class/method/etc names that these correction mechanisms do not know, resulting in unwanted changes. This PR deactivates these correction mechanisms.
I've also reported this upstream to sphinx at https://github.com/sphinx-doc/sphinx/pull/9307. See there for more background.
Our current theme uses customized templates, so we have to adapt this ourselves.
You can check that this is working by accessing the CI built docs with a mobile device, and compare that with the released docs.
Note: I know the theme may be changing in the near future. But even if this does not make it to a release, it would be a win for me. I often quickly search the dev-docs on mobile when …

Prevent corrections and completions in search field

---

lib/mpl_toolkits/axes_grid1/axes_grid.py
lib/mpl_toolkits/tests/test_axes_grid1.py

- fixes #20372: `axes_all` axes are sorted by order of creation
- uniform description of `direction` in the docstrings of `Grid` and `ImageGrid`

Handle direction="column" in axes_grid.Grid

---

doc/api/axes_api.rst
doc/api/next_api_changes/removals/20331-ES.rst
lib/matplotlib/artist.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/matplotlib/projections/polar.py
lib/matplotlib/pyplot.py
lib/matplotlib/scale.py
lib/matplotlib/tests/test_axes.py

Remove Axis, Tick, and Axes deprecations from 3.3

---

lib/matplotlib/backends/backend_ps.py
lib/matplotlib/backends/backend_svg.py
lib/matplotlib/tests/test_backend_ps.py

Both codecs.getwriter and TextIOWrapper can convert a binary file-like
into a unicode file-like, but TextIOWrapper additionally closes the
underlying file when the wrapper is gc'ed, whereas codecs.getwriter
doesn't -- which is the semantics that we want (when the user passes a
previously opened file-like to savefig).  Thus using codecs.getwriter
simplifies the codepaths.
(The semantics can be verified with
```
import codecs
from io import TextIOWrapper
f = open("/tmp/foo", "wb")
TextIOWrapper(f).write("foo")
print(f.closed)  # True
f = open("/tmp/foo", "wb")
codecs.getwriter("utf-8")(f).write("foo")
print(f.closed)  # False
```
)

codecs.getwriter has simpler lifetime semantics than TextIOWrapper.

---

doc/users/next_whats_new/simplify_font_setting_usetex.rst
lib/matplotlib/tests/test_texmanager.py
lib/matplotlib/texmanager.py
tutorials/text/usetex.py

As suggested in #20289 , create a more user-friendly and simplified version of the font settings for usetex using the `rc::font.family`
Example:
```python
plt.rcParams.update({
"text.usetex": True,
"font.family": "Helvetica"
})
t = np.linspace(0.0, 1.0, 100)
s = np.cos(4 * np.pi * t) + 2
fig, ax = plt.subplots(figsize=(6, 4), tight_layout=True)
ax.plot(t, s)
ax.set_xlabel(r'\textbf{time (s)}')
ax.set_ylabel('\\textit{Velocity (\N{DEGREE SIGN}/sec)}', fontsize=16)
ax.set_title(r'\TeX\ is Number $\displaystyle\sum_{n=1}^\infty'
r'\frac{-e^{i\pi}}{2^n}$!', fontsize=16, color='r')
plt.show()
```

Simplify font setting in usetex mode

---

lib/matplotlib/cbook/__init__.py
lib/matplotlib/tests/test_subplots.py

If subplot_class_factory is passed a base class that already sub-classes
the mixin class, simply return the base class.
This will allow third-party packages to derive from maxes.Subplot rather
than maxes.Axes which will allow easier (by ensuring that our classes
and the third-party classes do not mix in the mro).
This allows a fix to https://github.com/lukelbd/proplot/issues/248 by changing which mpl class they inherit from (which brings them closer inline with the mpl36 goal of merging the subplot logic fulling into Axes
Currently we have:
```
In [10]: matplotlib.axes.subplot_class_factory(proplot.axes.CartesianAxes).mro()
Out[10]: 
[matplotlib.axes._subplots.CartesianAxesSubplot,
matplotlib.axes._subplots.SubplotBase,
proplot.axes.cartesian.CartesianAxes,
proplot.axes.base.Axes, …
```

FIX: if we have already subclassed mixin class just return

---

lib/matplotlib/collections.py
lib/matplotlib/tests/test_collections.py

Quadmesh.set_array validates dimensions

---

lib/matplotlib/dviread.py

Remove mention of now-removed Encoding class.

---

lib/matplotlib/dviread.py

New output of `python -mmatplotlib.dviread /path/to/dvi` for
`$\frac{1}{2}$`:
```
=== new page === (w: 261235, h: 553676, d: 225994)
font: 'cmr7'    scale: 0.4375
x       y       glyph   chr     w       (glyphs)
1061683 1183756 49      1       261235
1061683 1667786 50      2       261235
x       y       w       h               (boxes)
1061683 1291058 26213   261235
```
old output:
```
=== new page ===
font b'cmr7' scaled 0.4375
1061683 1183756 49 1 261235
1061683 1667786 50 2 261235
1061683 1291058 BOX 26213 261235
```

Slightly improve output of dvi debug utilities, and tiny cleanups.

---

lib/matplotlib/tests/test_patheffects.py
lib/matplotlib/tests/test_simplification.py
src/_backend_agg.h
src/_path.h

When `PathClipper` is applied, it is disabled if `has_curves()` is true. However, that method simply checks if the Path has _codes_, not curves. This means Paths created with codes, but using only MOVETO/LINETO, are not clipped when they could be.
Additionally, the description for `PathClipper` says that "Curve segments are not clipped, but are always included in their entirety.", meaning there is no need to turn it off when the Path contains curves, as they will at least be handled, if not fully clipped.
- [n/a] New features have an entry in …

Don't disable path clipping on paths with codes.

---

lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/tests/test_backend_pgf.py

This has been open for many years without any change to LaTeX, so it seems unlikely they are going to change how their parsing works.
Note that this does add clipping for filled paths, which we normally don't do, but it's so so far away, I don't think it'll be a problem.
Fixes #4482. …

PGF: Clip lines/markers to maximum LaTeX dimensions.

---

examples/text_labels_and_annotations/font_family_rc_sgskip.py
tutorials/text/text_props.py

Coming from the answer at https://discourse.matplotlib.org/t/fonts-and-font-families/22132 and a brief discussion with @anntzer, this PR modifies the content of font docs (and one example, for which I have a slight niggle against - because it's not really the most obvious and best way to guide a user into setting font family).
Hopefully, we might be moving font stuff out from this [very long page](https://matplotlib.org/stable/tutorials/text/text_props.html), and probably a better example in future.
This is possibly the beginning of handling https://github.com/matplotlib/matplotlib/issues/5941.

Clarify/Improve docs on family-names vs generic-families

---

lib/matplotlib/patches.py

There's no Arc3Connection, but there is a ConnectionStyle.Arc3, and
likewise for Angle3.

Fix references in ArrowStyle docstring.

---

lib/matplotlib/patches.py

They were underindented relative to the rest of the parameter
docstrings, see e.g. the arrowstyle table at https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.FancyArrowPatch.html#matplotlib.patches.FancyArrowPatch

Fix indentation of Arrow/Box/Connection styles tables.

---

examples/statistics/hexbin_demo.py
lib/matplotlib/axes/_axes.py

- See-also-link between hexbin() and hist2d()
- More compact example code notation
- Better example Introduction

Improve hexbin() documentation

---

doc/api/next_api_changes/deprecations/20428-AL.rst
lib/matplotlib/patches.py

It is a helper for FancyArrowPatch and ConnectionPatch, but no other
Artists expose such a method, while the normal approach is just to apply
`get_transform()` to `get_path()` (which is documented as an
alternative).
This may help future changes in the ArrowStyle API (e.g. allowing the
tip and the body to have different linestyles, https://github.com/matplotlib/matplotlib/issues/20385#issuecomment-856569202).

Deprecate public use of get_path_in_displaycoord.

---

lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/tests/test_mplot3d.py

The issue is introduced by commit f888285: attribute `Patch3DCollection._z_markers_idx` is used within `_maybe_depth_shade_and_sort_colors()` function, but is never assigned.
The same changes were done in the `Path3DCollection` class, but there attribute is set correctly within `set_3d_properties()` function. Assuming this is the expected behaviour, this commit also sets `_z_markers_idx` in `Patch3DCollection.set_3d_properties()`.

Fix missing Patch3DCollection._z_markers_idx

---

lib/matplotlib/dviread.py
lib/matplotlib/tests/baseline_images/dviread/test.map
lib/matplotlib/tests/test_dviread.py

A test has started failing in Fedora Rawhide with Texlive 2021; while I think there are some issues in the `pdftex.map` there (see [my investigation here](https://bugzilla.redhat.com/show_bug.cgi?id=1965547)), I found the parser in Matplotlib to be a bit laxer than it should be. Annoyingly, `dvipdfm` and `pdflatex` appear to use different parsers for this file, but I chose to emulate what `pdflatex` does, as it appears to match what's in the pdfTeX manual, which we claim to follow.
Some more details are available in the commit messages, but behaviour copied from `pdflatex` include:
* ignoring duplicate lines
* ignoring lines with out of range *special* entries, or on the wrong font type
* failing on subset TrueType fonts without encoding files
- [n/a] New features are documented, with …

Make pdftex.map parsing stricter

---

lib/matplotlib/backends/backend_gtk3.py

Also, stop using `gtk_main*` functions; these were deprecated in GTK3, and no longer exist in GTK4. The lower level GLib functions have always been there, and won't go away.

Use a GtkApplication in GTK backend.

---

lib/matplotlib/colors.py
lib/matplotlib/dates.py
lib/matplotlib/mathtext.py
lib/matplotlib/textpath.py

These can cause issues for some static checks (I noticed them in LGTM), and mostly the code in the super `__init__` is duplicated in the subclass.

Add missing super __init__ in subclasses

---

lib/matplotlib/colorbar.py

Non-gridspec colorbar axes have a `_colorbar_info` appended to them, but the gridspec and user-supplied ones do not.  This PR adds the attribute to all colorbar axes, and is set to `'user'` if the axes is provided by the user.
This is helpful in cases where we want to tell if an axes is a colorbar or not, though all colorbar axes should also be of type `ColorbarAxes`, so maybe not strictly needed...

ENH: add colorbar info to gridspec cbar

---

doc/api/prev_api_changes/api_changes_3.4.0/deprecations.rst

I'm not sure why I put this in here, but it is to be deprecated in 3.5, and there's no trace of a deprecation in 3.4.2.

Remove `Tick.apply_tickdir` from 3.4 deprecations.

---

lib/matplotlib/backends/backend_ps.py
lib/matplotlib/mpl-data/matplotlibrc
lib/matplotlib/tests/test_backend_ps.py

... by wrapping ps-specific packages in `\@ifpackageloaded`, which makes
their use transparent to the end user (if they already loaded it
themselves, we don't do anything).  So don't mention them anymore in the
matplotlibrc docs either.
Also, graphicx doesn't need the dvips option (the graphicx docs
explicitly state "normally you should... allow it to be defaulted
automatically".
(The pgf backend is a completely different beast and has its own custom
preamble anyways.)
Closes https://github.com/matplotlib/matplotlib/issues/10042.

Make used tex packages consistent between ps and other backends.

---

.lgtm.yml

I'm not sure if this affects the Python analysis (it might as there are some strange 'issues'), but the C/C++ analysis is definitely broken due to using Python 2 to build.
Also, re-indent the file consistently with YAML conventions. …

Tell LGTM to use Python 3 explicitly.

---

lib/matplotlib/dviread.py
lib/matplotlib/tests/test_usetex.py

It's a bit a whack-a-mole, but heh...
Closes https://github.com/matplotlib/matplotlib/issues/20440.

Fix dvi baseline detector when `\usepackage{chemformula}` is used.

---

lib/matplotlib/axis.py
lib/matplotlib/tests/test_axes.py

Fix deprecation of `Tick.apply_tickdir`.

---

lib/matplotlib/legend.py
lib/matplotlib/tests/test_legend.py

Previously the text added in a legend had `.axes == None`. Fixes https://github.com/matplotlib/matplotlib/issues/20435
Not sure if this needs a changelog entry?

Set the axes of legend text

---

lib/matplotlib/offsetbox.py

The locations are listed in the same format as in inset_locator (#20090).

Shorten the AnchoredOffsetbox docstring.

---

lib/matplotlib/_api/__init__.py
lib/matplotlib/collections.py

This was suggested by @jklymak in https://github.com/matplotlib/matplotlib/pull/20354#discussion_r650115059.  That PR is not merged yet, so right now the only use site is the QuadMesh constructor.

Add a select_overload helper for signature-overloaded functions.

---

doc/users/prev_whats_new/whats_new_3.0.rst
doc/users/prev_whats_new/whats_new_3.3.0.rst
examples/color/colorbar_basics.py
examples/images_contours_and_fields/image_masked.py
lib/matplotlib/colorbar.py
lib/matplotlib/tests/test_colorbar.py

ColorbarBase differs from Colorbar in that it is not associated with a
ScalarMappable (but constructed from explicit cmap/norm), but we already
document in Figure.colorbar that the preferred way to draw colorbars not
associated with an existing artist is to create an empty ScalarMappable
to provide `norm` and `cmap`.
Hence, likewise merge Colorbar and ColorbarBase (creating the
ScalarMappable on-the-fly if no mappable is passed to the constructor),
which should make the APIs clearer.  (Note that we are already
discouraging users to directly call either class' constructors,
anyways).  We could deprecate the backcompat APIs (i.e., the
`ColorbarBase` alias, the `cmap` and `norm` kwargs, and the different
semantics of `add_lines`), but that can be done later; this PR should be
entirely …

Merge Colorbar and ColorbarBase.

---

.github/workflows/tests.yml
examples/units/basic_units.py
lib/matplotlib/__init__.py
lib/matplotlib/backends/qt_compat.py
lib/matplotlib/testing/compare.py
lib/matplotlib/testing/decorators.py
lib/matplotlib/tests/test_backend_pgf.py
lib/matplotlib/tests/tinypages/conf.py
lib/matplotlib/texmanager.py
requirements/testing/minver.txt
setup.py

... as `distutils` is deprecated in Python 3.10.
~~Since this is somewhat lower-level, I picked a minimum version on the same timescale as Python support, namely about 3 years ago.~~ Minimum version is ~12 months ago, since this is a Python-only package and all relevant downstreams appear to have it.
Maybe this should get an API note or something?

Use packaging to do version comparisons.

---

lib/matplotlib/sphinxext/plot_directive.py

Small cleanups to sphinxext.plot_directive.

---

examples/axes_grid1/demo_colorbar_of_inset_axes.py

Less pyplot, more OO in docs.

---

lib/matplotlib/backends/_backend_tk.py

The nominal parent widget of `FigureCanvasTk` can sometimes have a `call` method and sometimes not, occasionally breaking `_update_device_pixel_ratio`. However, the class has complete control over what `_tkcanvas` is, and `_tkcanvas` can substitute for all uses of `_master`.

remove _master attribute from FigureCanvasTk

---

lib/matplotlib/backends/_backend_tk.py

Fixes toolbar for `tk.NoDefaultRoot()` users.

give Font a root widget

---

doc/api/next_api_changes/deprecations/20474-AL.rst
lib/matplotlib/dviread.py
lib/matplotlib/tests/test_dviread.py

The info-level log can easily be hidden, and the KeyError may look like
a bug on Matplotlib's side.  Instead, explicitly raise an exception
whose error message states that Matplotlib doesn't currently support
certain cases.  (https://github.com/matplotlib/matplotlib/issues/20469)
Use a LookupError (a parent class of KeyError, so a slight API break)
rather than a KeyError as KeyError formats its argument as if it was the
missing key (calling repr on it), which would not be the case here.

Make lack of support more explicit for non-postscript fonts + usetex.

---

lib/matplotlib/patches.py
lib/matplotlib/tests/test_patches.py

Previously `vertices[0]` would raise IndexError.  This occurs e.g. with
`cb = colorbar(); cb.patch` which is an empty polygon.

Fix str of empty polygon.

---

doc/api/next_api_changes/deprecations/20466-AL.rst
lib/matplotlib/backends/backend_pgf.py

- Replace _font_properties_str by _escape_and_apply_props, which handles
all the preprocessing needed before sending a str to tex.  (This means
that LatexManager.get_text_width_height_descent now additionally
handles unescaped strings as well, too.)
- Replace str_cache by a (per-instance) lru_cache.
- When querying tex for a string's metrics, send both `\sbox` and
`\typeout` in a single go, which saves one cycle of waiting for the
interactive prompt.

Various cleanups to pgf backend.

---

lib/matplotlib/axes/_axes.py

In this PR I want to fix the docstring for the hexbin parameter `extent`:
https://github.com/matplotlib/matplotlib/blob/2a3037fdefa2daab0b5e27cc400c6d9453bc091b/lib/matplotlib/axes/_axes.py#L4650
It previously said "float", but it actually wants a 4-tuple of floats, as evident from the code:
https://github.com/matplotlib/matplotlib/blob/2a3037fdefa2daab0b5e27cc400c6d9453bc091b/lib/matplotlib/axes/_axes.py#L4755-L4756

DOC: hexbin 'extent' must be 4-tuple of float, not float

---

doc/devel/dependencies.rst

During the removal of Qt4 support, the mentioning of pyside was removed,
however the corresponding footnote stayed (and is currently messing up
footnote numbering). We just have to delete the footnote as well.

Remove obsolete footnote on pyside

---

plot_types/basic/pie.py

Colors are not exactly the same, but solid colors are significantly
simpler. Before, due to using transparency one had to draw a white
pie below the original pie to prevent the grid from shining through.

Simplify plot types pie()

---

doc/conf.py

- Twitter icon as in https://matplotlib.org/mpl-third-party/
- apparently "logo_link" must not have a .html suffix, because that is auto-appended.

DOC: Add twitter icon and fix logo link

---

lib/matplotlib/image.py
lib/matplotlib/tests/test_image.py

Change vmin check to less than or equal to 0 rather than strictly less than.
Fixes #20487

FIX: Include 0 when checking lognorm vmin

---

lib/matplotlib/backends/backend_ps.py
lib/matplotlib/tests/test_backend_ps.py

For a given call to savefig(), we only need to warn once about alpha or
usetex support.  (RendererPS is generated afresh for each savefig()
call, so it's fine to do the caching on it.)

Suppress repeated logwarns in postscript output.

---

examples/lines_bars_and_markers/linestyles.py
tutorials/introductory/customizing.py

`rc_context` is really useful and I think it deserves a mention in the "Customizing" tutorial.  While I was checking which options to use, I realised the comment in the linestyles example was wrong, so fixed it while I was there.

Add rc_context to customizing tutorial

---

lib/matplotlib/axes/_axes.py

Shorten the bxp docstring.

---

lib/matplotlib/sphinxext/plot_directive.py

Document defaults in plot_directive.

---

doc/api/next_api_changes/deprecations/20540-AL.rst
lib/matplotlib/sphinxext/plot_directive.py

(Its value is not read anywhere in the implementation since a205f5460f.)

Deprecate :encoding: option to .. plot::, which has no effect since 2011

---

examples/images_contours_and_fields/image_annotated_heatmap.py
examples/lines_bars_and_markers/filled_step.py
lib/matplotlib/contour.py

It's a quasi-convention to use the letters and ordering (M, N) for a
2D matrix; i.e. M rows and N columns. We already use this convention in
the majority of cases. This switches the letter ordering in some
remaining cases.
Note that this is a pure renaming without change of semantics.

Rename (N, M) -> (M, N) array-like

---

lib/matplotlib/tests/test_contour.py
lib/matplotlib/ticker.py

Non-ordered "ticks" locations can be used when using ScalarFormatter to
format contour lines.  Perhaps ContourLabeler.get_text could arrange for
the "ticks" to be ordered, but it's much easier to just support
non-ordered ticks in ScalarFormatter.
Fixes partially #20529: the lowest contour is now correctly printed as 0.25, not 2.5.  (The exponents are still missing, though.)

Fix ScalarFormatter.format_ticks for non-ordered tick locations.

---

examples/shapes_and_collections/fancybox_demo.py
lib/matplotlib/patches.py

We now have source order, which should be more semantically more
meaningful.
Split out of #20531; see also #20430.

Don't sort boxstyles/arrowstyles/etc. alphabetically.

---

doc/api/next_api_changes/behavior/20367-AG.rst
lib/matplotlib/tests/test_text.py
lib/matplotlib/text.py
lib/matplotlib/widgets.py

Following up the comment: https://github.com/matplotlib/matplotlib/issues/20266#issuecomment-854794023, this PR adds a `override_math` to Text objects, and make TextBox's text object default it to True.
This resolves https://github.com/matplotlib/matplotlib/issues/20266.
It does not allow GUI to go in invalid state when there's invalid mathtext in it, because it isn't parsed at all.
(also allows folks to override mathtext _at all_ in their text objects)
Interactive trial:
```python
from matplotlib.widgets import TextBox
fig.subplots_adjust(left=0.25, top=0.55, bottom=0.45)
text_box = TextBox(ax, "Something in '\$ \$'")                       # try typing wrong mathtext here
plt.show()
```
Static trial:
```python
import …
```

Add parse_math in Text and default it False for TextBox

---

lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_axes.py

This PR addresses issue [#20452](https://github.com/matplotlib/matplotlib/issues/20452) which would raise ZeroDivisionError when 0 in data shape for plotting. Now, it "does nothing".

Plot nothing for incompatible 0 shape in x,y data

---

doc/api/next_api_changes/deprecations/20543-AL.rst
lib/matplotlib/testing/conftest.py
lib/matplotlib/testing/decorators.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_backend_pdf.py
lib/matplotlib/tests/test_backend_pgf.py
lib/matplotlib/tests/test_backend_svg.py
lib/matplotlib/tests/test_category.py
lib/matplotlib/tests/test_collections.py
lib/matplotlib/tests/test_contour.py
lib/matplotlib/tests/test_figure.py
lib/matplotlib/tests/test_image.py
lib/matplotlib/tests/test_patches.py
lib/matplotlib/tests/test_ticker.py
lib/mpl_toolkits/tests/test_mplot3d.py

`@mpl.style.context` can be used in the same way (and is just as
greppable), but doesn't require any support from the pytest machinery.

Deprecate `@pytest.mark.style(...)`.

---

lib/matplotlib/tests/test_widgets.py

This PR addresses the test coverage of TextBox widget on [Issue #20370](https://github.com/matplotlib/matplotlib/issues/20370). This is my first contributing issue, so I grabbed initial approach by the issue opener. I would gladly change whatever is needed.

Add initial TextBox widget testing

---

lib/matplotlib/legend.py
lib/matplotlib/offsetbox.py

Dedupe some box anchoring code between legend.py and offsetbox.py.

---

doc/api/next_api_changes/deprecations/20113-EP.rst
doc/users/next_whats_new/widget_dragging.rst
examples/widgets/span_selector.py
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

This PR updates the `SpanSelector` to make it consistent with `RectangleSelector`:
- Deprecate `span_stays` in favour of `interactive`
- Add edge handle when `interactive=True`
- Add `drag_from_anywhere` option, in line with #19657
- Fix https://github.com/matplotlib/matplotlib/pull/9660
- Improve docstring
- Deprecate `pressv`
- When reviewing the docstrings, I realised that some attributes are not expected to be used by users and should be private - I am happy to revert it back if necessary
- Privatize `rect`, `rectprops`,  for the `SpanSelector`
- Privatize  `to_draw`, `drawtype` for the `RectangleSelector
- Privatize `active_handle` for SpanSelector and RectangleSelector
- Make `direction` a property
If you are happy with the changes, I will do the remaining doc, examples, etc …

Interactive span selector improvement

---

doc/devel/documenting_mpl.rst

- Link to Sphinx reStructuredText primer.
- `make show` for opening locally built docs.
Closes #20552.

Improve the documentation guide

---

doc/api/animation_api.rst
doc/api/artist_api.rst
doc/api/next_api_changes/removals/20465-ES.rst
doc/api/prev_api_changes/api_changes_0.98.0.rst
lib/matplotlib/__init__.py
lib/matplotlib/_enums.py
lib/matplotlib/animation.py
lib/matplotlib/artist.py
lib/matplotlib/backend_managers.py
lib/matplotlib/bezier.py
lib/matplotlib/docstring.py
lib/matplotlib/image.py
lib/matplotlib/lines.py
lib/matplotlib/patches.py
lib/matplotlib/path.py
lib/matplotlib/rcsetup.py
lib/matplotlib/streamplot.py
lib/matplotlib/testing/compare.py
lib/matplotlib/transforms.py
lib/matplotlib/widgets.py

Remove remaining 3.3 deprecations

---

extern/ttconv/pprdrv.h
extern/ttconv/pprdrv_tt.cpp
extern/ttconv/pprdrv_tt2.cpp
extern/ttconv/ttutil.cpp

Factor out DEBUG_TRUETYPE checks in ttconv, & removals of unused defs.

---

lib/matplotlib/figure.py
lib/matplotlib/tests/test_constrainedlayout.py

I was trying to pass `wpad` and wondering why it didn't seem to do anything... No deprecation because constrained layout is still 'experimental'.

Raise if passed invalid kwargs to set_constrained_layout_pads.

---

lib/matplotlib/image.py

Closes #20560 and fixes CI
I'm not sure if the other rawmodes should be fixed?

FIX: PILLOW asarray bug

---

lib/matplotlib/sphinxext/plot_directive.py
lib/matplotlib/tests/tinypages/some_plots.rst

As noted in https://github.com/matplotlib/matplotlib/pull/20540#pullrequestreview-695559714

Fix deprecation of encoding in plot_directive.

---

plot_types/stats/hist_plot.py

hist(x) has a natural y-scale due to the counts. We don't want to
rescale that manually or reduce the sample size (which would make the
distribution not look so nice). So instead we scale up the axis limits.
Previous:
Now:

Fix limits in plot types example hist(x)

---

doc/api/next_api_changes/removals/20563-TH.rst
lib/matplotlib/ticker.py

Expire deprecation of passing nbins to MaxNLocator in two ways

---

doc/_static/mpl.css

I feel the reduced spacing is still not too dense, but it allows to show more content in these quite long tables.
before:
after:

Reduce vertical margins in property tables

---

doc/faq/howto_faq.rst
examples/pyplots/auto_subplots_adjust.py
tutorials/intermediate/constrainedlayout_guide.py
tutorials/intermediate/tight_layout_guide.py

<s>Manual adjusting the subplot parameters should be the exception
nowadays. We don't need to discuss this in the FAQ. Users should
primarily use tight_layout or constrained_layout, which is covered
in the following section.</s>
- Repurpose the example "Auto Subplots Adjust" to "Programmatically
controlling subplot adjustment". The effect of the example has been
largely superseeded by tight layout and constrained layout. It's still
useful as an example of using advanced concepts in Matplotlib such as
Bboxes, transforms, events.
- Remove "How-to: Move the edge of an axes to make room for tick labels"
and move it's content to "Programmatically controlling subplot
adjustment"
- Remove "How-to: Automatically make room for tick labels"
This is basically a documentation of `subplots_adjust()`. …

More concise how to for subplot adjustment

---

lib/matplotlib/axes/_axes.py

Mostly with some judicious variable renamings.

Shorten the implementation of bxp().

---

examples/shapes_and_collections/fancybox_demo.py
examples/text_labels_and_annotations/fancyarrow_demo.py

This will allow later removing the table of values in the annotation
tutorial.
Also, draw things each in their axes and in axes coordinates, to
simplify the code.
Split out of #20531.
Before:
After:
In https://github.com/matplotlib/matplotlib/pull/20531#discussion_r659373062 @timhoffm has argued against the addition of all parameters; I think specifically for the example the effect may be neutral or indeed perhaps slightly negative, but the point is actually to remove the tables at https://github.com/matplotlib/matplotlib/blob/60ff0d4543f5b7e8fae4cc2afe23c9e52a1190ef/tutorials/text/annotations.py#L139-L151 and https://github.com/matplotlib/matplotlib/blob/60ff0d4543f5b7e8fae4cc2afe23c9e52a1190ef/tutorials/text/annotations.py#L241-L256 which can easily go out of sync and aren't …

Show box/arrowstyle parameters in reference examples.

---

lib/matplotlib/patches.py

... which are synonymous, but zero is more explicit (and also consistent
with BracketA and BracketAB).  (None is still supported as input, so
there's no backompat break.)

Switch default ArrowStyle angle values from None to zero.

---

lib/matplotlib/colors.py
lib/matplotlib/quiver.py
lib/matplotlib/tests/test_image.py
lib/matplotlib/tests/test_quiver.py

Due to numpy/numpy#18967, I've audited all our calls to `np.ma.masked_*(copy=False)`. When the input comes directly from the user, or is already stored somewhere already, then we don't want these calls to modify the existing values.
This affects `np.ma.masked_where` and all _simple_ wrappers around it like `masked_less_equal`. It does _not_ affect `masked_invalid`, which continues to not modify the input. I have asked upstream https://github.com/numpy/numpy/issues/19332 whether that is intended. If they intend to change `masked_invalid` also, then we will need to make a few more changes like this, but we are mostly okay.
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should …

Fix calls to np.ma.masked_where

---

examples/ticks_and_spines/auto_ticks.py

- Closes #20508 by moving `plt.show()` into the context.
- Further cleanup.

Fix example for rcParams['autolimit_mode']

---

examples/images_contours_and_fields/tricontour_demo.py

Addresses #19431 to add example of hatching use for tricontourf plots. I tried to follow other tri/contour examples to maintain consistency. 
- [] Has pytest style unit tests (and `pytest` passes).
- [] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [] New features are documented, with examples if plot related.

Add tricontourf hatching example

---

lib/matplotlib/collections.py
lib/matplotlib/tests/test_collections.py

Internally all Collection flavors boil down to calling
renderer.draw_path_collection and the sub-classes primarily provide nicer
user-facing APIs to fabricate the paths that will be passed down to the
renderer.
In LineCollection rather than tracking both the user supplied data and the
internal Path objects, we just keep the Path objects and re-extract segments on
demand.
To do this we use Path.iter_segments with defaults to asking the path if it
should simplify the path (that is drop points that do not matter which is in
turn defined by if the deflection away from "straight" is greater than some
threshold). The Path objects we are holding have values in data-space, but the
default value of "what is the threshold for 'not mattering'" is tuned to make
sense in to pixel space (1/9).  By …

FIX: do not simplify path in LineCollection.get_segments

---

lib/matplotlib/sphinxext/plot_directive.py
lib/matplotlib/tests/test_sphinxext.py
lib/matplotlib/tests/tinypages/included_plot_21.rst
lib/matplotlib/tests/tinypages/some_plots.rst

Fixes #17860. Briefly, to reproduce this bug:
1. Create a file `included.rst` with a plot inside it.
2. Create a file `index.rst` containing the include directive
`.. include:: included.rst`.
3. Build Sphinx documentation.
4. Modify the plotting code inside `included.rst`, but don't touch
`index.rst`.
5. Rebuild the Sphinx documentation. Because `index.rst` wasn't touched,
plot_directive thinks that it's up-to-date and thus the image doesn't
need to be re-created.
This commit fixes the issue by checking the modification times not only
of the source file (`index.rst` in this case), but also of the file(s)
included within it (`included.rst`).
The commit message contains most of the info, but I attach some extra detail here just in case people come across it and find it useful. There are a …

Check modification times of included RST files

---

lib/matplotlib/colors.py

Fix class docstrings for Norms created from Scales.

---

doc/api/next_api_changes/deprecations/19483-JMK.rst
doc/devel/min_dep_policy.rst
doc/devel/style_guide.rst
examples/subplots_axes_and_figures/colorbar_placement.py
examples/widgets/annotated_cursor.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/collections.py
lib/matplotlib/colorbar.py
lib/matplotlib/colors.py
lib/matplotlib/tests/test_mlab.py
plot_types/unstructured/README.rst
tutorials/text/usetex.py

Found via `codespell -q 3 -S ./extern,./doc/users/credits.rst,./doc/api/prev_api_changes,./doc/users/prev_whats_new -L afe,ans,axises,ba,coo,flate,fo,hist,inout,ment,nd,offsetp,oly,ot,te,thisy,vas,whis,wit`

DOC: fix various typos

---

doc/users/next_whats_new/slider_styling.rst
examples/widgets/slider_demo.py
examples/widgets/slider_snap_demo.py
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

Closes: https://github.com/matplotlib/matplotlib/issues/19256
Updates the styling of the slider widgets to look like this:
1. Made the `poly` patch smaller
2. Added a circle handle to indicate that the sliders can be grabbed with the mouse
- ~will change color when grabbed~
3. removed the black border of the `Axes` and indicate the length of the slider with rectangle patch. 
- This is skinnier than previously.
- [NA?] Has pytest style unit tests (and `pytest` passes).
- [I guess?] New features are documented, with examples if plot related.

Change styling of slider widgets

---

lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/backends/qt_editor/_formlayout.py
lib/matplotlib/backends/qt_editor/figureoptions.py

The figure options dialogue is no longer modal, which means the figure can be interacted with while the dialogue is open, and it fixes https://github.com/matplotlib/matplotlib/issues/18965

PR: Remove modality of figure options

---

lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/matplotlib/colorbar.py
lib/matplotlib/figure.py
lib/matplotlib/tests/test_subplots.py
lib/mpl_toolkits/mplot3d/axes3d.py

This means that various places can now iterate over the dicts
and directly support 3D axes: Axes3D doesn't need to override
_request_autoscale_view or _unstale_viewLim or set_anchor anymore, and
can shed most of set_aspect; various subtle points that were missing
before also get fixed (restoring z-axis sharing upon unpickling;
resetting locators and formatters after deleting an Axes3D sharing a
z-axis with another still present Axes3D); etc.
There's just some slightly annoying interaction with ColorbarAxes
vampirizing its inner_ax, but that can be worked around.

Turn shared_axes, stale_viewlims into {axis_name: value} dicts.

---

lib/matplotlib/backends/backend_svg.py

This means one fewer argument to track down the call stack (avoiding
passing it from print_svg to RendererSVG).  Wrapping the file object
in a TextIOWrapper (as done in print_svg) forwards the `.name` to the
wrapper, so we're fine there.

Move svg basename detection down to RendererSVG.

---

lib/matplotlib/backends/backend_svg.py

Otherwise metadata gets silently dropped, as well as correct support for
rasterized elements in tight_bbox outputs.  Try e.g.
`plot([0, 1], rasterized=True); savefig("test.svgz")` and note that the
line is drawn incorrectly.
Don't bother with `*args`, which are ignored anyways.

Don't forget to propagate kwargs from print_svgz to print_svg.

---

doc/api/next_api_changes/behavior/20054-JMK.rst
lib/matplotlib/colorbar.py

It is not used at all anymore (its vertices are not even set correctly)
since the switch to ColorbarAxes.

Deprecate Colorbar.patch.

---

doc/api/next_api_changes/deprecations/19441-AL.rst
lib/matplotlib/backend_tools.py
lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/backends/backend_webagg_core.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/backends/web_backend/js/mpl.js
src/_macosx.m

Tested on GTK, macOS, Qt, and Tk, though for macOS, I was using VNC and couldn't see any change, so that was just a check that it didn't crash.
Also, deprecate `cursord` from the other backends.
I'm not sure about the names; as you can see all toolkits use different names:
* RESIZE_EAST_WEST: 
* GTK: ew-resize
* macOS: resizeLeftRightCursor
* Qt: SizeHorCursor
* Tk: sb_h_double_arrow
*  wx: CURSOR_SIZEWE
* RESIZE_NORTH_SOUTH:
* GTK: ns-resize
* Tk: sb_v_double_arrow
*  wx: CURSOR_SIZENS
* macOS: resizeUpDownCursor
* Qt: SizeVerCursor
- [?] New features are documented, with examples if plot related.

Add directional sizing cursors

---

doc/api/next_api_changes/deprecations/20601-ES.rst
lib/matplotlib/widgets.py

For example, `eventrelease` is only set in the `release` handler, before calling the subclass's `_release`, and then immediately set to `None`. Within that time, it could be accessed from the `onselect` handler, but that's just the second argument passed to it anyway. So there's not really any use for `eventrelease` as a class attribute.
The other two are similarly internal state tracking, and should not be modified externally.

Hide some `_SelectorWidget` state internals.

---

doc/api/next_api_changes.rst
doc/devel/release_guide.rst
doc/users/next_whats_new.rst

This reflects the restructuring in #20132. It should make handling "Whats new" and "API changes" simpler because one doesn't have to touch the respective `next_*.rst` anymore. A release simply gets two new pages `whats_new_X.Y.Z.rst` and `api_changes_X.Y.Z.rst`, which are added to the TOC in `release_notes.rst`.
Ping in particular @QuLogic since you will have to use this.

Adapt the release guide to the new release notes structure

---

examples/subplots_axes_and_figures/zoom_inset_axes.py
examples/text_labels_and_annotations/mathtext_examples.py
lib/matplotlib/projections/geo.py
lib/matplotlib/tests/test_constrainedlayout.py
lib/matplotlib/tests/test_text.py
tutorials/intermediate/constrainedlayout_guide.py

The string variant is not supported according to the docstring. It's
only working by accident due to the list comprehension in 
https://github.com/matplotlib/matplotlib/blob/30cbdf7d2e2963f585f9ab21d7c1d31bd09197d0/lib/matplotlib/axis.py#L1705

Use ticklabels([]) instead of ticklabels('')

---

extern/ttconv/pprdrv_tt.cpp

Manual backport of #20597 because of merge conflicts

Backport PR #20597 on branch v3.4.x

---

examples/axisartist/demo_curvelinear_grid.py
examples/axisartist/demo_curvelinear_grid2.py

Since 8840d6e we ensure that `x` and `y` passed to `tr` and `inv_tr`
are already arrays (see the definition of
`_UserTransform2D.transform_non_affine`), so we don't need additional
casting-to-arrays.

Simplify curvilinear grid examples.

---

doc/api/next_api_changes/deprecations/20638-AL.rst
lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py

- change_tick_coords has never been used by any other function or in any
example in the library's history, and is a custom API not even present
on other AxisArtistHelpers, so deprecate it.
- _limits_inverted is only used in get_tick_iterators, so one can just
test limits inversion there instead of carrying one bit of state
around.

Small simplifications to FixedAxisArtistHelper.

---

doc/faq/environment_variables_faq.rst

xref https://github.com/matplotlib/matplotlib/issues/20661#issuecomment-882082358.

Document $MPLSETUPCFG.

---

examples/color/custom_cmap.py
examples/images_contours_and_fields/contourf_demo.py
examples/style_sheets/ggplot.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_image.py

- Use ax instead of axs when the object is clearly a single Axes
- Use axs.flat instead of ax.ravel()
This only changes examples and tests; i.e. no API changes involved.

Cleanup related to usage of axs

---

lib/matplotlib/legend_handler.py

Rename `kw` to the standard `kwargs`.
In the docstring, use a relatively standard formulation already used in
other modules.
HandlerStepPatch doesn't need to override `__init__` at all.
Move the description of HandlerTuple's parameters into `__init__`, as
for other classes (in this module and elsewhere).

Standardize description of kwargs in legend_handler.

---

doc/api/next_api_changes/deprecations/20585-EP.rst
examples/widgets/span_selector.py
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

Follow up of #20558. Rename parameters (`maxdist`, `markers_props`, etc.) to make them consistent between the different selectors.

Rename parameter selectors

---

lib/matplotlib/_api/deprecation.py

For internal APIs, it seems reasonable to avoid the duplication of
the description of parameters (if anything, the shortened version makes
the difference in `obj_type`'s behavior clearer).
Also compress a bit the docstring of `warn_deprecated`.

Shorten the `@deprecated` docs.

---

lib/matplotlib/backends/backend_pgf.py

The need for a % is not some mysterious tex thing, but a well
documented behavior.

Clarify comment about backend_pgf.writeln.

---

lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

Fix bounds when initialising `SpanSelector`

---

examples/axes_grid1/simple_axes_divider1.py
examples/userdemo/connectionstyle_demo.py
tutorials/colors/colormap-manipulation.py
tutorials/colors/colormaps.py
tutorials/colors/colors.py
tutorials/introductory/sample_plots.py
tutorials/text/annotations.py
tutorials/text/mathtext.py
tutorials/text/usetex.py
tutorials/toolkits/axes_grid.py
tutorials/toolkits/axisartist.py
tutorials/toolkits/mplot3d.py

Figures were originally 50% scale, but this looks tiny in the new theme. Mostly this undoes that, plus some tweaks in examples so that they don't end up too wide at 100%. For example, there's no need for this to be so small:
As done in other PRs, this also drops captions which seem pretty uninformative.
Finally, it makes some tweaks to some of the colour figures, by
a) moving colormaps to their respective tutorial sections
<details>
<summary>(preventing sphinx-gallery from treating them as a list and half-sizing them, like this)</summary>
</details>
b) and improving the xkcd vs CSS colour comparison chart by changing the text colour to contrast the background, plus some tweaks to make better alignment:
<details>
</details>
- [n/a] …

Improve tutorial figures in the new theme

---

lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/tests/test_mplot3d.py

The `xs` is a 1D array that may not have a `shape` attribute.
```python
lines_3d.set_xdata([0, 1])
lines_3d.set_ydata([0, 1])
lines_3d.set_3d_properties([0, 1], zdir='z') # 💥 AttributeError: 'list' object has no attribute 'shape'
```

Fix the way to get xs length in set_3d_properties()

---

doc/api/colors_api.rst
doc/api/next_api_changes/behavior/20405-JMK.rst
lib/matplotlib/colors.py

Internally we now make most norms from scales using `colors._make_norm_from_scale`.  This simply hoists that to public API so downstream libraries can use it as well...

ENH: expose make_norm_from_scale

---

src/_path_wrapper.cpp

`CALL_CPP` may raise an exception, so we should drop the `vertices` ref before calling it. We've already added an automatically-dropping ref with the `array_view`, so we don't need this one.
Fixes #20641.

Fix leak if affine_transform is passed invalid vertices.

---

doc/api/next_api_changes/deprecations/20606-AL.rst
lib/mpl_toolkits/axes_grid1/axes_grid.py
lib/mpl_toolkits/axisartist/axes_grid.py

This is a followup to the introduction of _make_class_factory, and
avoids having to define a separate CbarAxes class in axisartist.

Dynamically generate CbarAxes.

---

doc/api/next_api_changes/deprecations/20254-AL.rst
lib/mpl_toolkits/axisartist/floating_axes.py
lib/mpl_toolkits/tests/test_axisartist_floating_axes.py

Currently, the boundary patch of FloatingAxes is drawn in "parent axes
data" (rectilinear) coordinates, using manual interpolation as defined
in get_boundary.
Instead, it can be defined in child axes data coordinates, and use
`helper_trf + transData` as transform, relying on interpolation
mechanisms already present in the transform machinery (for example, this
means that polar FloatingAxes benefit from the more-accurate
transforming of circular arcs).
Likewise, adjust_axes_lim can use normal path methods to get its
extents, rather than relying on manual interpolation.  This is the cause
of the baseline image tolerance change: in test_curvelinear3, for
example, we now have exactly `bbox.xmin = bbox.ymin = -10` and
`bbox.xmax = bbox.ymax = +10` rather than slightly different values
arising …

Define FloatingAxes boundary patch in data coordinates.

---

src/_backend_agg_wrapper.cpp
src/_contour_wrapper.cpp
src/_image_wrapper.cpp
src/_path_wrapper.cpp
src/ft2font_wrapper.cpp
src/qhull_wrap.cpp
src/tri/_tri_wrapper.cpp

The newly created module may leak if any following initialization fails. Since `import_array` is a macro that hides a `return`-on-failure, that needs to move earlier before the module creation.

Fix some very unlikely leaks in extensions.

---

lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_backend_bases.py

(set_x/ybound doesn't disable autoscaling, unlike set_x/ylim.)
... and also, as a separate commit:
PEP8ify _set_view_from_bbox.
Closes https://github.com/matplotlib/matplotlib/issues/20519.

Don't forget to disable autoscaling after interactive zoom.

---

doc/users/next_whats_new/version_info.rst
lib/matplotlib/__init__.py
lib/matplotlib/tests/test_matplotlib.py

Closes #18312. See there for general background and discussion.
This implementation truncates the version to `(major, minor, micro)`. GitHub post-tag number and commit are left out: The commit ID must be left out because it is not ordered, and the tuple is specifically intended to be compared. One could leave the post-tag number. However, this is non-standard. Moreover git post-tag numbers only appear in development versions and and I doubt there's a use-case for checking only that. So let's keep it simple and to the `(major, minor, micro)` tuple.
One can always expand later with additional parameters or switching to a namedtuple. if there is need.

Add __version_info__ as a tuple-based version identifier

---

doc/api/next_api_changes/behavior/20692-AL.rst
lib/matplotlib/hatch.py

- In Shapes.set_vertices_and_codes, handle `self.filled` just once at
the beginning, and collect the vertices and codes parts in a list and
concatenate them all at the end, rather than keeping track of a
position in the buffers.
- Make SmallFilledCirecles inherit from Circles rather that
SmallCircles, with which it shares no attribute.

Small cleanups to hatch.py.

---

.circleci/config.yml
.github/workflows/circleci.yml
azure-pipelines.yml
doc/devel/coding_guide.rst

1. Build a merged version of each PR instead of the branch itself on CircleCI.
2. Update `circleci-artifacts-redirector-action` to say "Check the rendered docs here!" as its GitHub status title, but this will only take effect once this PR is merged (because the action is triggered by `status` and thus always runs on whatever is in the action in `master`).
3. Add `[skip circle]` and `[circle skip]` support to skip CircleCI
4. Add `[skip azp]` and `[azp skip]` support to skip Azure
5. Document in devdocs that these `skip` options exist, alongside `[skip actions]` and `[skip appveyor]` (which are natively supported by those platforms)
Closes #20658
- [N/A] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on …

CI: Build merged version on CircleCI

---

lib/matplotlib/backends/backend_pdf.py

The parameter to Path.hatch is not a patch, but a hatch(pattern); one
can grep for other calls to Path.hatch to confirm it.

Rename a confusingly named variable in backend_pdf.

---

.github/workflows/tests.yml
lib/matplotlib/backends/backend_gtk3.py

This will reduce the diff between GTK3 and GTK4, in #20321. It also fixes the bug in the backend version.

Small cleanup to GTK backend

---

.circleci/config.yml

There exists a PR on a random fork, which fills in `CI_PULL_REQUEST`, which we don't want to use as merge target when building `master`. Instead, check `CIRCLE_PR_NUMBER`, which is set only on forked PRs. Also, check branch name (which is current, not the _target_) to be certain.
Followup to #20680, @larsoner 
- [n/a] New features have an entry in `doc/users/next_whats_new/` …

Fix Circle merge on master branch.

---

.github/workflows/cibuildwheel.yml
src/_path.h

Only on Linux/macOS x86 for now, but will enable Windows and aarch64 on `master`.
Test build is at https://github.com/QuLogic/matplotlib/actions/runs/1047384795

Enable PyPy wheels for v3.4.x

---

doc/api/next_api_changes/behavior/20634-JKS.rst
lib/matplotlib/tests/test_type1font.py
lib/matplotlib/type1font.py

Implement decryption of the encrypted part of Type-1 fonts. This is a prerequisite of subsetting (#127) although that will need a lot more code.
I looked at using fonttools for Type-1 subsetting, but it seems to lack much of the functionality needed for that, although it does implement this decryption algorithm. (The code in this PR is completely my own implementation.)
cc @aitikgupta - subsetting TTF fonts is more important than Type-1 since it affects a lot more users, but if you want to take a look at Type-1 subsetting, this is the first step

Implement Type-1 decryption

---

plot_types/basic/scatter_plot.py

Adjust the norm limits to include the colors values (between 15 and 80).

Fix color normalization in plot types scatter

---

lib/matplotlib/colorbar.py

Closes #20635
@jklymak the places I was using `cbar.patch`, using `cbar.ax` was the correct solution (e.g., `cbar.ax.set_facecolor` instead of `cbar.patch.set_facecolor`). The message now reads:
```
The patch attribute was deprecated in Matplotlib 3.5 and will be removed two minor releases later. Use ax instead.
```
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow …

DOC: Provide alternative to cbar.patch

---

doc/devel/contributing.rst

In the ["Contributing" section of the docs](https://matplotlib.org/devdocs/devel/contributing.html#contributing-code), there's incorrect syntax resulting in a missing link to the "Setting up Matplotlib for development" page. It appears as "See ref\`<installing_for_devs>\` for instructions" instead.
- Building the docs ends with an nondescript error for me (`make: *** [Makefile:34: html] Error 1`), but it did the same before this change
- [N/A] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 …

Fix broken link in 'Contributing' docs

---

doc/api/next_api_changes/deprecations/20620-ES.rst
lib/matplotlib/backend_bases.py
lib/matplotlib/backend_managers.py
lib/matplotlib/backend_tools.py
lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_macosx.py
lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/backends/backend_webagg_core.py
lib/matplotlib/backends/backend_wx.py

While the toolbar does need to track what it wants to set the cursor to based on the active tool, actually setting it is an act on the canvas (or sometimes the window, but this is toolkit dependent, so we won't worry about that.)
It also means we don't need redundant `set_cursor` definitions on both toolbar/toolmanager ~~(not yet committed.)~~

Move set_cursor from the toolbar to FigureCanvas.

---

lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_preprocess_data.py

Somewhat surprisingly, flake8 doesn't complain about this.

Fix style in `assert(x)`.

---

lib/matplotlib/path.py
lib/matplotlib/tests/test_path.py

The original Path.copy raised RecursionError, the new implementation mimicks deepcopy, but Path members are shared.
Path tests were updated to utilize member functions copy and deepcopy instead of builtin copy functional protocol.
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst …

Improved implementation of Path.copy and deepcopy

---

doc/api/next_api_changes/deprecations/20686-AL.rst
lib/matplotlib/_api/deprecation.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/pyplot.py
tools/boilerplate.py

No independent test (because mocking boilerplate.py is too hard), but
note that the signature change on imshow works.
Closes #20684.

Fix interaction between make_keyword_only and pyplot generation.

---

.github/workflows/tests.yml
doc/api/next_api_changes/development/20391-AG.rst
doc/devel/dependencies.rst
doc/users/next_whats_new/subsetting.rst
lib/matplotlib/backends/_backend_pdf_ps.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/testing/conftest.py
lib/matplotlib/tests/test_backend_pdf.py
lib/matplotlib/tests/test_backend_ps.py
requirements/testing/minver.txt
setup.py
src/_ttconv.cpp

This PR is a fresh rebase from https://github.com/matplotlib/matplotlib/pull/18143.
- Adds a dependency: [`fonttools`](https://github.com/fonttools/fonttools) to handle font subsetting for us
(we already have an external ttconv dependency, which does not handle subsetting)
- Interfaces a `getSubset` utility to get file-like objects containing subsetted font data
Possibly fixes https://github.com/matplotlib/matplotlib/issues/11303 (large file sizes)
Fixes https://github.com/matplotlib/matplotlib/issues/18191.

Type42 subsetting in PS/PDF

---

lib/matplotlib/widgets.py

This sets either a horizontal or vertcal resize cursor when initiating a selection, moving the span, or when hovering over an end handle.
This is half of #20724.
I said I was going to move things to `ToolLineHandles`, but there are two reasons why I didn't:
* It doesn't have `grab_range`, which is needed for determining when we're hovering.
* It doesn't have access to the parent widget, so can't know when it's inactive, or a handle is already active.
I could propagate the information over, but seemed like more work than just handling the cursor entirely in the `SpanSelector` widget. I could finish moving it if we think that makes a better design.

Set the canvas cursor when using a SpanSelector

---

lib/matplotlib/sphinxext/plot_directive.py

Ensure _static directory exists before copying CSS.

---

doc/api/next_api_changes/deprecations/XXXXX-AL.rst
lib/matplotlib/streamplot.py

cm.get_cmap already handles None input, no need to do it again here.
In get_integrator and _integrate_rk12, track x and y together rather
than separately, and the `xyt[1:]` slicing works even if `xyt` is empty.

Small simplifications to streamplot.

---

examples/text_labels_and_annotations/mathtext_asarray.py
examples/text_labels_and_annotations/mathtext_examples.py
examples/text_labels_and_annotations/mathtext_fontfamily_example.py

The mathtext example uses two dictionaries, but that was only to preserve order, which we can do with a single dictionary directly now. Also, move to the object-oriented API, use current cycle colours instead of the old theme colours, and tweak the size so that the text doesn't overflow.

Modernize mathtext examples

---

lib/matplotlib/colorbar.py

Closes #20296
`colorbar.set_ticklabels` is now just an alias to `colorbar._long_axis().set_ticklabels` except it also has a deprecated kwarg.  
Not sure if this really needs an API change or not - its just making the `set_ticklabels` the same as it is on `axis.set_ticklabels`.
Also updated `colorbar.set_ticks` to be the same as the axis command.

FIX: pass colorbar.set_ticklabels down to long_axis

---

lib/matplotlib/figure.py
lib/matplotlib/tests/test_constrainedlayout.py

Closes #20760
If you specify the x-position of an supxlabel (or y position of supylabel) it should not disqualify the label from constrained_layout...
```python
fig, ax = plt.subplots(constrained_layout=True)
lab = fig.supxlabel('Boo', x=0.7)
plt.show()
```

Fix suplabel autopos

---

examples/widgets/rectangle_selector.py
lib/matplotlib/widgets.py

The old EllipseSelector example had similar issues as those fixed in
f288658 for RectangleSelector.
I'm not too happy with the explanation text, but that can be fixed
lated.

Merge EllipseSelector example together with RectangleSelector.

---

doc/api/next_api_changes/deprecations/20753-AL.rst
lib/matplotlib/scale.py

``set_xscale("LOG")`` is likely rare, and removing it avoids having to
duplicate the logic if we want to support setting norms via strs (#20752).

Deprecate support for case-insensitive scales.

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

Matplotlib 3.3 [deprecated](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.3.0.html#parameters-norm-and-vmin-vmax-should-not-be-used-simultaneously) passing `norm` and `vmin` or `vmax` parameters simultaneously to certain functions. The [hexbin](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hexbin.html) plotting method supports a `bins='log'` parameter that applies logarithmic scaling to the colormap of the resulting histogram. Under the hood, this behavior is implemented by generating a `LogNorm` and setting it to the `norm` parameter. This means that `plt.hexbin([], [], bins='log', vmin=1)` raises a deprecation warning (or error in the dev branch), `Passing parameters norm and vmin/vmax simultaneously is deprecated... Please pass vmin/vmax directly to the …

Support vmin/vmax with bins='log' in hexbin

---

lib/matplotlib/backends/backend_ps.py
lib/matplotlib/tests/test_backend_ps.py

A recent change introduced a regression in the PS backend. The line dash offset parameter is written as an integer (string format `d` operator). However according to the PS language spec, the offset can be any number and with the default `"--"` dash setting, the offset is a float.
With the current master, `linestyle="--"` raises a `ValueError` upon saving.
```python
plt.plot([0, 1], linestyle="--")
plt.savefig("x.ps")
```
This PR uses `_nums_to_str()` to format the offset value.
Should I add a test case for this?

Fix line dash offset format in PS output

---

lib/matplotlib/backends/backend_ps.py
lib/matplotlib/texmanager.py

... which avoids having to explain twice its point, as well.

Factor out latex ifpackageloaded pattern.

---

doc/api/index.rst
doc/api/sphinxext_mathmpl_api.rst
doc/conf.py
doc/users/next_whats_new/mathmpl_hidpi.rst
lib/matplotlib/sphinxext/mathmpl.py

Namely, `fontsize`, and `srcset`. We need these for our new theme, which uses 11pt fonts instead of 10pt, and to match the gallery that provides 2x images.

Add HiDPI-related config for mathmpl

---

lib/matplotlib/backends/backend_qt5.py
lib/matplotlib/style/core.py

Remove some remnants of qt4 support.

---

lib/matplotlib/backends/_backend_pdf_ps.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_ps.py

I noticed a few things while reviewing font-related PRs, but as they were not directly related to those PRs, did not comment on them (except for the Type 42 PS subsetting bit, as that one was merged before I could comment.)
See commit messages for details, but this removes redundant character<->ordinal conversion, splits Type 42 PS subsetting into a separate function, and removes some deprecated code.

Cleanup font subsetting code

---

lib/matplotlib/_constrained_layout.py

Fixed #20782. In https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/_constrained_layout.py#L304
fixed typo
`if fig._supylabel is not None and fig._supxlabel.get_in_layout():`
to
` if fig._supylabel is not None and fig._supylabel.get_in_layout():`

Fixed typo in _constrained_layout.py (#20782)

---

lib/matplotlib/figure.py
lib/matplotlib/pyplot.py

This is an alternate approach for #20773, relying only on doc improvements.

Document how to check for the existence of current figure/axes.

---

lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_macosx.py
lib/matplotlib/backends/backend_webagg_core.py

... in backends that didn't do so yet.  release_zoom itself calls
release_rubberband, so implementing release_rubberband it more general
(it allows one to directly call it independently of zoom state).

Implement remove_rubberband rather than release_zoom.

---

doc/conf.py

Addresses #20557 to point the [SOURCE] in docs point to github instead. A proper build config to build the old way is still missing, but perhaps that can be part of separate PR.  Also, this impl was copied from [scipy conf.py](https://github.com/scipy/scipy/blob/master/doc/source/conf.py#L426-L502), but modified slightly to work here instead. 
PS: Building old way is just adding back the `sphinx.ext.viewcode`, but I was not sure how to add it as part of a `make O=-Dmyarg=1 html`.

Point [SOURCE] documents to github

---

doc/users/next_whats_new/collection_offsets.rst
lib/matplotlib/collections.py
lib/matplotlib/tests/test_collections.py

Made some suggested changes related to issue #20698.
* Merged `Collection._uniform_offsets` and `Collection._offsets`, removed the former, kept the latter. Any function dependent on this variable was removed.
* Removed `Collection._offsetsNone`, replaced with a check if offsets were non-zero where used.
* Added `Collection.set_offset_transform()`.
I did add `Collection.set_offset_transform()`, but this isn't really a new feature, since it can already be set …

Fix collection offsets

---

tutorials/intermediate/legend_guide.py

Addresses #20754 to change legend guide from all `pyplot` interface to the `ax` objected oriented approach

Change legend guide to object oriented approach

---

doc/api/next_api_changes/deprecations/20795-TAC.rst
lib/matplotlib/testing/conftest.py
lib/matplotlib/tests/conftest.py
lib/mpl_toolkits/tests/conftest.py

This is left over from an early pass at nose -> pytest conversion

TST/MNT: deprecate unused fixture

---

doc/users/next_whats_new/figure_kwargs.rst
lib/matplotlib/figure.py
lib/matplotlib/tests/test_figure.py

Consistent with other artists and allows properties controlled by `set_XYZ` to
be set at init time.
Discovered this while working on mpl-gui

ENH: pass extra kwargs in FigureBase, SubFigure, Figure to set

---

lib/matplotlib/colorbar.py
lib/matplotlib/tests/test_colorbar.py

Raise a ValueError if a colorbar is created with a collection that has an alpha that is an array. This also adds the ability to override the collection's alpha with a scalar.
closes #19843
closes #20785

FIX: Check for colorbar creation with multi-dimensional alpha

---

lib/matplotlib/__init__.py
lib/matplotlib/_api/deprecation.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/colorbar.py
lib/matplotlib/style/core.py

This PR is mostly just to propose a pattern for defining module-level
`__getattr__`s for deprecating globals.
Relying on lru_cache rather than defining variables as `global` (see
change in `__init__.py`) avoids having to repeat *twice* the variable
name, and allows immediately returning its value without assigning it.
It means later accesses will be very slightly slower (because they'll
still go through the lru_cache layer), but that should hopefully be
negligible, and will mostly concern deprecated variables anyways.
One *could* consider adding a helper API in `_api.deprecation` that just
provides the decoration with `@lru_cache` and generates the
AttributeError message when needed, but that seems rather overkill.
(See https://github.com/matplotlib/matplotlib/pull/20620#issuecomment-87860 …

Deprecate globals using module-level `__getattr__`.

---

lib/matplotlib/animation.py
lib/matplotlib/tests/test_animation.py

If `_init_draw()` fails, assume the animation is dead, but do not fail.
closes #17770
I am not sure this is actually the best fix.  On one hand, this is elides the problem, but does so by ignoring the problem.  There is some poor interaction going on here between the ways access the data sources and how we try to "peek" at the first frame if we are not passed an init function.

FIX: don't fail on first show if animation already exhausted

---

lib/matplotlib/backends/backend_qt.py

These were removed in 15c39a3d0b87f024acc791cd3257ee95806403f5, but resurrected in the Qt6 PR.

Re-remove deprecated Qt globals.

---

doc/api/next_api_changes/deprecations/20799-GL.rst
doc/api/next_api_changes/removals/19552-GL.rst
examples/images_contours_and_fields/multi_image.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/cm.py
lib/matplotlib/colorbar.py

This makes the code more consistent throughout with objects having a `callbacks` attribute, rather than associating a name with them on the end and using camelCase.
First noticed by @timhoffm in https://github.com/matplotlib/matplotlib/pull/19553#issuecomment-893788816

MNT: Rename callbacksSM to callbacks

---

lib/matplotlib/tests/test_dates.py

The epoch is set by explicitly calling `mdates.set_epoch`, or implicitly set to the default by `mdates.get_epoch` (which is also called when converting datetimes.)
However, when running tests in parallel, there is no guarantee that any other call to `[gs]et_epoch` might have been made to lock it in, so we need to do that explicitly.

Make test_change_epoch more robust.

---

lib/matplotlib/style/core.py

PR #20733 added module-level `__getattr__` functions to several modules. All of the functions with the exception of the one in `matplotlib.style.core` had a terminal `raise AttributeError` to handle unmatched attributes.
The omission in `matplotlib.style.core` was probably unintentional; it results in confusing and buggy behavior such as:
```pycon
>>> import matplotlib.style.core
>>> if hasattr(matplotlib.style.core, '__warningregistry__'):
...     del matplotlib.style.core.__warningregistry__
...
File "<stdin>", line 2, in <module>
AttributeError: __warningregistry__
```
This causes problems in the unit tests for astropy affiliated packages. See astropy/astropy#12038.

BUG: __getattr__ must raise AttributeError if name not found

---

tools/triage_tests.py

And some other minor fixes. Note, I did not check that it continued to work with Qt5, but I trust that our compat stuff work.

Fix image triage tool with Qt6

---

doc/users/next_whats_new/callback_blocking.rst
lib/matplotlib/cbook/__init__.py
lib/matplotlib/tests/test_cbook.py

CallbackRegistry objects gain a context manager `.block()` method that can be used to temporarily block callback signals from being processed.
```python
with callbacks.block():
callbacks.process("test")  # Does nothing
with callbacks.block(signal="test"):
callbacks.process("test")  # Does nothing
```
Closes #20802 
Would help with disabling norm update signals in #19553

ENH: Add the ability to block callback signals

---

lib/matplotlib/tests/test_backend_qt.py
lib/matplotlib/tests/test_backend_tk.py
lib/matplotlib/tests/test_backends_interactive.py

Increase the test timeouts from 10 s to 60 s.  The Gentoo arch teams
have reported that the default timeout of 10 s is insufficient for
slower architectures (such as HPPA) and/or busy test systems.
(this is a trivial test constant change, so most of the points above are irrelevant)

Increase test timeouts to 60 s to aid slower architectures

---

lib/matplotlib/tests/test_animation.py
lib/matplotlib/tests/test_mathtext.py

TST: neither warned and pytest upstream deprecated this usage

---

doc/api/next_api_changes/2018-06-01-AFV.rst
doc/api/next_api_changes/behavior/20699-AFV.rst
lib/matplotlib/legend_handler.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_legend.py

This is a rebase of #11358 (fixing #2035, #11357, #18391, #20552) on top of #20670 (to address https://github.com/matplotlib/matplotlib/pull/11358#discussion_r194247428) and with an additional commit on top to address other comments.
I decided to keep both legend handlers public for now (based on comments in the original thread); we can always decide to deprecate the old handler later.
... except for `markevery=<float>` or `(<float>, <float>)` which is a
spec relative to the axes size (keeping handling of that specific case
into _mark_every_path).

FIX/ENH: Introduce a monolithic legend handler for Line2D

---

doc/users/next_whats_new/widget_ignore_events.rst
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

- Fix #20666, but I think this is a misleading behaviour because event are expected to be ignore when the width of the selector is smaller than `minspan`, therefore it would surprising that `onselect` is called when the width is 0 (`vmin == vmax`).
Maybe a better alternative is to add a callback which is called when clearing the selector?
- Add `ignore_outside_event` argument to selectors

Fix selector onselect call when the selector is removed by an "empty" click and add `ignore_event_outside` argument

---

doc/api/next_api_changes/deprecations/20603-AL.rst
lib/matplotlib/widgets.py

These are unused since 61ab6df (and have trivial replacements if
someone *really* wants to call them manually, which seems unlikely).

Deprecate unused LassoSelector event handlers.

---

.flake8
doc/api/matplotlib_configuration_api.rst
doc/users/next_whats_new/colormaps.rst
lib/matplotlib/__init__.py
lib/matplotlib/cm.py

Following the thoughts in https://github.com/matplotlib/matplotlib/pull/16991#discussion_r415340436, this defines a Mapping subclass `ColorbarRegistry` with the following properties:
- read-only mapping: name -> `Colormap`. - Adding new colormaps is for now still done via `register_cmap()`. The class will grow the ability to add elements later, but that needs more API consideration.
- The returned `Colormaps` are copies, so that the global state is not affected by modification to the returned colormaps. - This is the goal for `get_cmap()` anyway (see its deprecation note).
This is a minimal version, that allows to get the registered colormap names. Closes #18490.
Still to be decided: Where should the instance `colormaps` instance live? In `cm`, in `matplotlib`? Should `cm` be integrated …

Add a dedicated ColormapRegistry class

---

lib/matplotlib/backends/backend_qt5.py

These were missed in 1d15bf4, and caused import of `backend_qt5` to fail
with `cannot import name 'SUPER' from 'matplotlib.backends.backend_qt'`.

Re-re-remove deprecated Qt globals.

---

doc/api/next_api_changes/deprecations/20806-TH.rst
lib/matplotlib/cm.py

we can directly use `mpl.rcParams['image.lut']`.

Deprecate matplotlib.cm.LUTSIZE

---

doc/api/next_api_changes/deprecations/20079-AL.rst
lib/mpl_toolkits/axes_grid1/axes_divider.py

See changelog note for motivation.

Prepare axes_divider for simpler(?) indexing-based API.

---

lib/matplotlib/cm.py

PR #20806 added another instance of a module-level `__getattr__` function that was missing a final `raise AttributeError` to catch unknown attributes. This is the same kind of bug as #20822.
See also astropy/astropy#12038.

BUG: __getattr__ must raise AttributeError if name not found (again)

---

setupext.py

Fix typo:
matplotlib -> Matplotlib

Fix minor typo in setupext.py

---

.github/workflows/cibuildwheel.yml
lib/matplotlib/backend_bases.py
lib/matplotlib/patches.py
lib/matplotlib/scale.py
lib/matplotlib/tests/test_animation.py
lib/matplotlib/tests/test_backend_tk.py
lib/matplotlib/tests/test_backends_interactive.py
lib/matplotlib/tests/test_cbook.py
lib/matplotlib/tests/test_quiver.py
lib/matplotlib/tests/test_style.py
src/_c_internal_utils.c

Test build of wheels is here: https://github.com/QuLogic/matplotlib/actions/runs/1137857541
Fixes #20637.
This also fixes all tests except for the `Animation` cleanup ones, which may be a bug in PyPy.
Should we enable testing on PyPy in CI? Note, it is quite a bit slower for me, but I don't know how long it will take on CI.
Fixes #19160.
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst …

Fix PyPy wheels and tests

---

lib/matplotlib/legend.py
lib/matplotlib/tests/test_legend.py

- Closes #20723
As reported in #20723, this changes the `isinstance` check in `Legend` to check against `FigureBase` instead of `Figure`
- N/A: API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

Allow SubFigure legends

---

lib/matplotlib/axis.py
lib/matplotlib/tests/test_axes.py

Currently, only label rotation was broken, but I set up the test to check everything.
Fixes #20791.

Ensure all params are restored after `reset_ticks`.

---

doc/api/next_api_changes/development/20840-RJS.rst
lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/tests/test_backend_tk.py
src/_tkagg.cpp
src/_tkmini.h

This PR releases the GIL while blitting, and chooses a slightly different but sometimes faster function to actually perform the blit.
In my usage, blitting can often be over 100 ms, which is a long time to hold the GIL... especially while not using the Python C API. I verified the safety of releasing the GIL back in 2ad422a78c3794ac5139364c0ea3d6a8d6de6030 but for some reason I took it back out when thread-based parallelism didn't work out. (#18565)
`_tkagg.blit` has been backed by `Tk_PhotoPutBlock_NoComposite` since #6442. This interface is deprecated, and on Tk 8.5 and later `Tk_PhotoPutBlock` gives the option to composite or not as a function argument, avoiding the need for an extra blanking step and permitting a [fast path](https://github.com/tcltk/tk/blob/5745147320011c82db86941f349d …

Speed up Tkagg blit with Tk_PhotoPutBlock

---

lib/matplotlib/__init__.py
lib/matplotlib/_api/__init__.py
lib/matplotlib/_api/deprecation.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/cm.py
lib/matplotlib/colorbar.py
lib/matplotlib/style/core.py
lib/matplotlib/tests/test_getattr.py

Apparently we always forget to generate the fallback AttributeError (#20822, #20855), so
introduce a helper to do so instead.  (I'm not wedded to the exact API...)
The changes in `deprecation.py` are (a) so that one can correctly
suppress the inferred type when deprecating properties (the new check is
coherent with the `if isinstance(obj, type)` and other cases) and (b) to
make single-argument `__get__` work on deprecated properties
(consistently with standard properties).
Would replace #20856.

Propose a less error-prone helper for module-level getattrs.

---

lib/matplotlib/tests/test_backend_qt.py

Fixes a Qt test.  It looks like we had a test that never actually worked (the assert happened in a callback so the failure was ignored) which meant that the parameterized tests always passed.  When the test was fixed to raise on error this brought to light a miss-match between the computed and expected results which is also fixed.

Fix qt key mods

---

setup.py

Which apparently happens in Fedora's automated build requirement generator.

Ignore errors trying to delete make_release_tree.

---

src/_backend_agg_wrapper.cpp
src/_c_internal_utils.c
src/_contour_wrapper.cpp
src/_image_wrapper.cpp
src/_macosx.m
src/_path_wrapper.cpp
src/_tkagg.cpp
src/_ttconv.cpp
src/ft2font_wrapper.cpp
src/qhull_wrap.cpp
src/tri/_tri_wrapper.cpp

- Trailing NULL fields in PyModuleDefs can be left unfilled (they will
be filled with NULLs both in C and in C++, and this is also what
https://docs.python.org/3/extending/extending.html#a-simple-example
does).
- Empty docstrings should be set to NULL (None), not "".
- If no postprocessing is done, the return value of PyModule_Create can
be returned directly without checking for NULL (NULL will just
pass-though).

Remove some boilerplate from C extension inits.

---

lib/matplotlib/ticker.py

I often find the existing list of these hard to read, partly because there is lots of whitespace:
**Before**
I think changing these lists to tables is an improvement:
**After**

Use tables for Locator and Formatter docs

---

doc/devel/min_dep_policy.rst

The dependency list has been moved in version 3.4.

DOC: Fix dependency link.

---

lib/matplotlib/backends/backend_qt.py
lib/matplotlib/backends/qt_compat.py
lib/matplotlib/tests/test_backend_qt.py

This pull request fixes issue #13302 using `signal.set_wakeup_fd()`. 
The implemented `test_fig_sigint()` uses the example from the aforementioned issue. It's rather an integration test, though. It does not fail with the previous behaviour, but never passes either hanging the whole testing process.
I also changed `test_fig_signals()` to pass with the new code.

Qt5: SIGINT kills just the mpl window and not the process itself

---

doc/api/next_api_changes/deprecations/20881-AL.rst
lib/matplotlib/backends/qt_compat.py

Especially, note that QT_RC_MAJOR_VERSION originally pointed to the qt
major version selected by the rcParams (qt4agg/qt5agg), which doesn't
even have an equivalent now that we moved to a single qtagg backend.

Deprecate some old globals in qt_compat.

---

lib/matplotlib/backends/qt_compat.py

This was unnecessarily added.
Also, is_pyqt5 is no more, so declaring it as global has no effect.

Don't add QtNetwork to the API exported by qt_compat.

---

doc/api/next_api_changes/deprecations/19892-TH.rst
lib/matplotlib/figure.py
lib/matplotlib/tests/test_figure.py

Having separate and competing parameters `tight_layout` and `constrained_layout` is not a great API choice and can cause confusion
(#17339).
This PR addresses the problem by introducing a new parameter `layout` and suggests to use it instead.
Since `tight_layout` has been around for ages and is used probably a lot, I dare not right away deprecate the parameters and force all users to adapt. Therefore, `tight_layout` and `constrained_layout` are only marked as "discouraged" for now. (We might deprecate eventually some versions down the road). This is somewhat cumbersome, but IMHO the best way forward.
I put the "discouraged" concept in as a proposal. This adds a bit of overhead in the docs and code-wise, but gently paves the way for a better API. Feedback is welcome.
If this gets accepted, …

Add Figure parameter layout and discourage tight_layout / constrained_layout

---

doc/api/next_api_changes/deprecations/20586-TH.rst
doc/devel/testing.rst
lib/matplotlib/__init__.py

This is not a function that can be easily executed by the end user with a standard setup.  Testing requires substantial setup such as installing additional dependencies and reference data.  A function `matplotlib.test()` gives the false impression that a user can simply call it to verify if Matplotlib is working correctly.  Running pytest explicitly has become a de-facto standard and allows users to customize the run by various command line arguments.  There is no point in having a second own and more limited entry point to tests.

Deprecate matplotlib.test()

---

examples/axes_grid1/demo_edge_colorbar.py
examples/color/colormap_reference.py
examples/color/custom_cmap.py
examples/images_contours_and_fields/contourf_demo.py
examples/images_contours_and_fields/demo_bboximage.py
examples/images_contours_and_fields/quadmesh_demo.py
examples/images_contours_and_fields/tricontour_smooth_delaunay.py
examples/images_contours_and_fields/tricontour_smooth_user.py
examples/images_contours_and_fields/trigradient_demo.py
examples/pie_and_polar_charts/nested_pie.py

Use the new ColormapRegistry `mpl.colormaps` in examples.
Also don't obtain the Colormap object if it only passed to a colormapping
function. Passing the name is sufficient in such cases.

Use mpl.colormaps in examples

---

lib/matplotlib/tests/test_backend_qt.py
requirements/testing/extra.txt

From https://github.com/matplotlib/matplotlib/pull/13306/files/c3772ae037c5a2c7614013a9c36954675c5d9de0#diff-ee95644f45380b6c0cf91171c8c048ed673628bd67f14876ddd60abe0a3e0371

Make pywin32 optional in Ctrl+C Qt test.

---

.github/workflows/tests.yml
lib/matplotlib/backends/backend_qt.py
lib/matplotlib/backends/qt_editor/_formlayout.py
lib/matplotlib/testing/conftest.py
lib/matplotlib/tests/test_sphinxext.py
setup.py

Currently, pillow (https://github.com/python-pillow/Pillow/issues/5569) and kiwisolver (https://github.com/nucleic/kiwi/pull/103) do not have wheels, which slows down the build a bit, but it should pass anyway.

Add Python 3.10 testing.

---

doc/api/next_api_changes/deprecations/20693-EP.rst
doc/users/next_whats_new/setting_artists_properties_selector.rst
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

Fix #20618 by adding `set_props` and `set_handle_props` method. ~~This PR needs a bit of tidying up but I would like to know if we are happy with this approach!~~
A few others changes:
- `selector.artists` is now a property returning a tuple of all artists to disallow changing the artists through a public API
- Add `_selection_artist` and `_handles_artists` to access the corresponding artists internally. ~~Remove the use of `SpanSelector._rect` and other, because it is already accessible through `artists[0]`, maybe this is still better to keep a separate attribute?~~
```python
from matplotlib.widgets import SpanSelector
values = np.arange(-10, 100)
ax.plot(values, values)
span = SpanSelector(ax, …
```

Fix setting artists properties of selectors

---

doc/api/index.rst

Some native speaker please check, but I think *discouraged* is the better word.

Label pylab as "discouraged" instead of "disapproved"

---

doc/devel/min_dep_policy.rst

While the target does not exist yet, it will with the release and the
released 3.5 doc should link to its own dependencies.
Also removed `#dependencies` anchor because that's the top-level heading
on that page, so we can simply link that page itself.

Add dependency link for 3.5

---

lib/matplotlib/tests/test_backend_qt.py

Fix broken QApplication init in a test.

---

lib/matplotlib/colors.py

In particular, move the `Returns` block from `__init__` to `__call__`,
where it actually belongs.  I believe that Norms are low-level enough
constructs that it is sufficient to just refer to the base class
docstring, without going through fancy docstring interpolation.

Reword BoundaryNorm docs.

---

lib/matplotlib/patches.py

"auto" was documented as allowed value by 05e4ed9 (@efiring), but AFAICT this was
not actually implemented (there's no handling for such a value anywhere
in the module).
Closes https://github.com/matplotlib/matplotlib/issues/20936.

Fix documented allowed values for Patch.set_edgecolor.

---

.circleci/config.yml
.github/workflows/tests.yml
azure-pipelines.yml
lib/matplotlib/tests/test_font_manager.py

On Linux and Mac. Add a font_manager test that loads the font and uses it. This could be useful in testing the multi-font support (#20740 etc).
I couldn't get the font installed on Windows. There is a Chocolatey installer that installs all of the Noto fonts, which takes a really long time to run.

Try to install the Noto Sans CJK font

---

lib/matplotlib/mathtext.py

Milestoning as 3.5 as these are scheduled to be removed in 3.6 anyways.

Switch documented deprecations in mathtext by `__getattr__` deprecations

---

lib/matplotlib/legend.py

It may be slightly better to only emit the longer message if there were
actually handles that got ignored because of the leading underscore, but
that's actually a bit annoying to check (or requires some refactoring of
_get_legend_handles_labels).
See https://github.com/matplotlib/matplotlib/issues/5200#issuecomment-909423871.

Make warning for no-handles legend more explicit.

---

lib/mpl_toolkits/axes_grid1/parasite_axes.py

There's no call to a `_get_legend_handles` method anywhere in the
codebase; conversely, the `legend._get_legend_handles` function
explicitly handles host/parasite axes already.

Remove unused HostAxes._get_legend_handles.

---

lib/matplotlib/legend.py

- Normalize legend_handler_map=None to {} in a single place (in
_get_legend_handles).
- Use star-unpacking for dict merging.
- Cleanup various docstrings.

legend_handler_map cleanups.

---

lib/matplotlib/backend_bases.py

The main thing was removing the `__init__` docstrings, which appear oddly, and should be integrated into the descriptions. Then some minor cleanup to duplicate sentences, and formatting.

Clean up some Event class docs.

---

doc/users/next_whats_new/callbacks_on_norms.rst
lib/matplotlib/cm.py
lib/matplotlib/colorbar.py
lib/matplotlib/colors.py
lib/matplotlib/contour.py
lib/matplotlib/image.py
lib/matplotlib/tests/test_colors.py
lib/matplotlib/tests/test_image.py

This adds a callback registry to Norm instances that can be connected to by other objects to be notified when the Norm is updated. This is particularly relevant for ScalarMappables to be notified when the vmin/vmax are changed on the Norm. With this update, the axis is now immediately registered as stale in the following example.
```python
norm = plt.Normalize(-2, 2)
ax.imshow([[0, 1], [2, -1]], norm=norm)
norm.vmax = 0.1
print(ax.stale)
```
Closes #4387
Fixes #17052

ENH: Adding callbacks to Norms for update signals

---

lib/matplotlib/backends/backend_qt.py

On anything after #19255, when resizing some plots (on PyQt5 5.15.4) I get:
```
>>> Traceback (most recent call last):
File "/home/larsoner/python/matplotlib/lib/matplotlib/backends/backend_qt.py", line 336, in resizeEvent
if frame.f_code is frame.f_back.f_code:  # Prevent PyQt6 recursion. …
```

BUG: Fix f_back is None handling

---

lib/matplotlib/mathtext.py

- parse() already normalizes prop=None to prop=FontProperties().
- We don't need to explicitly attach a canvas to a plain Figure() before
calling savefig() anymore; FigureCanvasBase is always attached and
handles the dispatching to the correct concrete canvas class.

Small cleanups to math_to_image.

---

.flake8
doc/api/backend_gtk4_api.rst
doc/api/index_backend_api.rst
doc/devel/dependencies.rst
examples/user_interfaces/embedding_in_gtk3_panzoom_sgskip.py
examples/user_interfaces/embedding_in_gtk3_sgskip.py
examples/user_interfaces/embedding_in_gtk4_panzoom_sgskip.py
examples/user_interfaces/embedding_in_gtk4_sgskip.py
examples/user_interfaces/gtk3_spreadsheet_sgskip.py
examples/user_interfaces/gtk4_spreadsheet_sgskip.py
examples/user_interfaces/pylab_with_gtk3_sgskip.py
examples/user_interfaces/pylab_with_gtk4_sgskip.py
lib/matplotlib/__init__.py
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/_backend_gtk.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_gtk4.py
lib/matplotlib/backends/backend_gtk4agg.py
lib/matplotlib/backends/backend_gtk4cairo.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/mpl-data/matplotlibrc
lib/matplotlib/pyplot.py
lib/matplotlib/rcsetup.py
lib/matplotlib/tests/test_backends_interactive.py
mplsetup.cfg.template
tutorials/introductory/sample_plots.py
tutorials/introductory/usage.py

This is currently sufficient to open a window, do the usual things, like handle key presses, or zoom/pan, but there are still some kinks to work out. The zoom/pan buttons do not stay pressed, the canvas does not resize, and there are probably several other smaller things that are broken.
It is also in a separate file, but several of the changes can be cross-ported to the GTK3 backend, which I will do separately. When that is done, I can likely remove a lot of duplication, and possibly put it all together like Qt5/Qt6 is aiming to do.

Add a GTK4 backend.

---

.github/workflows/cibuildwheel.yml

There are wheels available for kiwisolver, NumPy and Pillow already.
We cannot test because GitHub Actions don't support the M1 in hosted runners, and Apple is somewhat anti-developer CI for some reason.
- [?] Has pytest style unit tests (and `pytest` passes).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow …

Build wheels for Apple Silicon.

---

lib/matplotlib/backend_tools.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/colors.py
lib/matplotlib/lines.py
lib/matplotlib/path.py
lib/matplotlib/testing/widgets.py
lib/matplotlib/widgets.py
lib/mpl_toolkits/axisartist/axisline_style.py

Mostly D401 (imperative mood) fixes, and a few other things.

Docstring cleanups.

---

lib/matplotlib/dviread.py

Cleanup some dviread docstrings.

---

lib/matplotlib/_mathtext.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_ps.py

When referring to a font glyph, "glyph name" is standard terminology
(e.g. FT_Get_Glyph_Name or Adobe docs); additionally there is a separate
concept of "symbol_name" used by the mathtext parser which has a
different meaning (`\foo` commands referring to TeX symbol names), so
let's not confuse them.
symbol_name is kept in the mathtext SimpleNamespaces for backcompat
(changing the SimpleNamespace to a proper class with a property handling
the deprecation is not worth the work).

Rename symbol_name to glyph_name where appropriate.

---

lib/matplotlib/legend_handler.py

The constructores are entirely identical (including wrt. defaults and
docstrings).

Make HandlerLine2D{,Compound} inherit constructors from HandlerNpoints.

---

lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

Try running e.g. examples/widgets/textbox.py together with
`rcParams["toolbar"] = "toolmanager"`.  Before this fix, clicking on the
TextBox would result in "TypeError: push() takes 2 positional arguments
but 3 were given".

Fix ToolManager + TextBox support.

---

lib/matplotlib/__init__.py

These entries have already been removed (with the corresponding API
change documentation: #18753 and #20465).
Also remove the now-unused _all_deprecated.

Remove now-unused rcParams _deprecated entries.

---

lib/matplotlib/gridspec.py

Does what it says in the title. Should make the parameters easier to see at a glance.

Use numpydoc for GridSpecFromSubplotSpec.__init__

---

lib/matplotlib/backends/backend_gtk4.py

On Gtk4, these have never been part of a released version, and can be
directly removed.

Remove unused icon_filename, window_icon globals.

---

examples/ticks/custom_ticker1.py

I intentionally left some "historical" flavor to the text.
Remove the backreference to FuncFormatter, which has become a
semi-internal API now that users should never have to directly
instantiate them.
Also remove the backreference to `subplots()`: although the example
does use it, it's really not about showcasing it.

Reword custom_ticker1 example.

---

lib/matplotlib/tight_bbox.py
lib/matplotlib/tight_layout.py
lib/mpl_toolkits/axes_grid1/inset_locator.py

transform_bbox is much faster when one does not need a TransformedBbox,
i.e. something that keeps track of later changes in the transform:
```
In [1]: from pylab import *
...: from matplotlib.transforms import *
...: tr = plt.gca().transAxes
...: bb = Bbox([[0, 0], [1, 1]])
...: %timeit TransformedBbox(bb, tr).x0
...: %timeit tr.transform_bbox(bb).x0
...: %timeit TransformedBbox(bb, tr).width
...: %timeit tr.transform_bbox(bb).width
11.8 µs ± 145 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.72 µs ± 31.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
11.9 µs ± 183 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.83 µs ± 16.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
(I don't know if any of the places changed here are actually …

Avoid TransformedBbox where unneeded.

---

lib/matplotlib/tests/test_rcparams.py

Possibly in preparation of trying to fix (later) #13118/#20249.

Test the rcParams deprecation machinery.

---

lib/matplotlib/artist.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/tests/test_backend_pgf.py

Fixes matplotlib#20516
PGF's `random steps` decoration seems to be the most similar,
but does not exactly match the behaviour described in matplotlib's docs.
Therefore I repurposed the `randomness` argument as a seed to give
control on how the line looks afterwards:
with same seed for both lines: 
I only tested this with '3.0.2', though.

 Support sketch_params in pgf backend

---

lib/matplotlib/backend_managers.py

There's already a fair amount of indirection involved, let's reduce that
a bit.

Inline ToolManager._trigger_tool to its sole call site.

---

lib/matplotlib/colorbar.py
lib/matplotlib/tests/test_colorbar.py

Closes #20978
If a colorbar was removed it was not being removed from a list of colorbars associated with an axes.  This would confuse constrained_layout, as in #20978
This now works...
```python
figure, axes = plt.subplots(1, 1, constrained_layout=True)
data = np.random.normal(size=(10,10))
im = axes.imshow(data)
colorbar = figure.colorbar(im, ax=axes)
colorbar.remove()
plt.show()
```

FIX: remove colorbar from list of colorbars on axes

---

lib/matplotlib/lines.py
lib/matplotlib/tests/test_lines.py

`Line2D` objects are "sub sliced" if they are well-ordered, and their view window is smaller than the actual data extents. However, if someone applies a transform, in particular a lateral translation, then the data all ends up out of view.  This adds a check to only apply the subslice algorithm if the transform is `ax.transData`.   
Closes #21008

FIX: Don't subslice lines if non-standard transform

---

lib/matplotlib/_constrained_layout.py
lib/matplotlib/artist.py
lib/matplotlib/axes/_base.py
lib/matplotlib/tight_layout.py
lib/mpl_toolkits/mplot3d/axes3d.py

This avoids duplicating try... except in a bunch of places, and also
gives a single centralized point if (possibly) we ever want to deprecate
support for subclasses that do *not* support for_layout_only.

Factor out for_layout_only backcompat support in get_tightlayout.

---

doc/api/next_api_changes/behavior/21031-AL.rst
lib/matplotlib/dates.py
lib/matplotlib/rcsetup.py
lib/matplotlib/tests/test_dates.py

Register a custom unit conversion interface for dates that reads the
relevant rc values when needed.
This will allow having multiple rcParams instances existing at the same
time, with only one of them actually being active and affecting the
library's behavior.
As discussed during the call; xref #21015.

Make date.{converter,interval_multiples} rcvalidators side-effect free.

---

lib/matplotlib/artist.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/projections/polar.py
lib/matplotlib/tests/test_image.py
lib/matplotlib/ticker.py

Currently (since #12459), when a colorbar is present, the cursor data under imshow() is
formatted using the colorbar's cursor formatter (the idea being that
that formatter should be able to "smartly" take normalization limits
into account); if no colorbar is present a fixed format string ("%0.3g")
is used (see #12473 for a stalled attempt to work around that).
In fact, there is a better scale that defines the number of significant
digits one should display in an imshow cursor data: it arises because
colormaps are discrete (usually with 256 colors, but in any case the
value is available as `cmap.N`).  This quantization tells us, for a
given value, by how much one needs to move before the underlying color
changes (at all); that step size can be used to to determine a number
of significant …

Improve formatting of imshow() cursor data independently of colorbar.

---

examples/axes_grid1/inset_locator_demo.py
examples/lines_bars_and_markers/marker_reference.py
examples/shapes_and_collections/compound_path.py
examples/statistics/errorbars_and_boxes.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/lines.py
lib/matplotlib/patches.py
lib/mpl_toolkits/mplot3d/axes3d.py

(Markers are left untouched, as they don't support "none"; nor are
linestyles, for which the "canonical" version is still "None".)
See https://github.com/matplotlib/matplotlib/issues/19300.

Prefer "none" to "None" in docs, examples and comments.

---

lib/matplotlib/legend.py

The `handleheight` parameter was missing from the `Legend` kwarg documentation. This PR adds it. I've confirmed that the 29 other kwargs are documented.
- [N/A] API …

Document `handleheight` parameter of `Legend` constructor

---

lib/matplotlib/backends/backend_wx.py

This PR adds the support for using the `MouseButton.FORWARD` and `MouseButton.BACKWARD` on the WX backend.

Support for forward/back mousebuttons on WX backend

---

lib/matplotlib/rcsetup.py

Make type lists fit in a single line.  A strict reading suggests that
all types should be separated with ` or ` rather than a comma, but
avoiding a backslash continuation seems more useful.
Also, *s* can also be a str.
(Old (incorrect) rendering: https://matplotlib.org/devdocs/api/rcsetup_api.html#matplotlib.rcsetup.validate_markevery)

Fix validate_markevery docstring markup.

---

setup.py

This was introduced in 2015 when support for running nose tests via
`setup.py test` was removed. We do not need to explicitly tell people
anymore that this is not possible.

Remove dummy test command from setup.py

---

lib/matplotlib/markers.py

See https://github.com/matplotlib/matplotlib/blob/23f1da49f6ebdacbf51252b0066f7ac804612f5d/lib/matplotlib/markers.py#L277

Correct the default for fillstyle parameter in MarkerStyle()

---

doc/_templates/mpl_nav_bar.html

I was recently working on some documentation and the new template took my attention, it looks great, good work. I found an typo in the main navigation bar `Tutoraials` -> `Tutorials`. Despite the fact that this is a single character PR I believe it has major impact and this will ease the process. I have not done any proof reading of the new documentation.
- [ N/A ] Has pytest style unit tests (and `pytest` passes).
- [ N/A ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ N/A ] New features are documented, with examples if plot related.
- [  ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ N/A ] Conforms to Matplotlib …

Fix typo in template of current dev-docs

---

doc/api/next_api_changes/deprecations/21056-AL.rst
lib/matplotlib/markers.py
lib/matplotlib/tests/test_marker.py

As noted in the module docstring, there is a confusion between using a
generic default MarkerStyle (empty) and the artist-specific one (e.g.
scatter plots use `rcParams["scatter.marker"]`).  Fortunately, direct
construction of MarkerStyles (especially of empty ones) is hardly ever
needed, so we can just make the parameter required.

Deprecate support for no-args MarkerStyle().

---

.github/workflows/cibuildwheel.yml

This PR modifies `cibuildwheel.yml` to create wheels for Python 3.10. I propose this as a draft because it is currently blocked on numpy's wheel (https://github.com/numpy/numpy/issues/19630).
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow …

Add CPython 3.10 wheels

---

lib/matplotlib/backend_bases.py
src/py_converters.cpp

This was deprecated in 3.3 (eb76378) and removed in most places in
c51ae6d5; this patch removes supports on the C side and mentions of it
in docs.
Also remove the `dashobj == NULL && dashobj == Py_None` check, which can
never be true.

set_dashes does not support offset=None anymore.

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_cairo.py
lib/matplotlib/backends/backend_gtk3cairo.py
lib/matplotlib/backends/backend_gtk4cairo.py
lib/matplotlib/backends/backend_qtcairo.py
lib/matplotlib/backends/backend_tkcairo.py
lib/matplotlib/backends/backend_wxcairo.py
lib/matplotlib/tests/test_figure.py

Since Cairo renderers exist forever, we need to ensure they are using the correct DPI, or else physical sizes are incorrect.
Fixes #21024.

Fix Cairo backends on HiDPI screens

---

setup.py
setupext.py

They are instead replaced by slightly roundabout ways to get hold of the
same objects (CompilerError, CCompiler).
Only distutils.sysconfig remains; we should investigate whether the
stdlib's sysconfig is a satisfactory replacement for it.
See https://github.com/matplotlib/matplotlib/issues/21057.
(Even if we waited for setuptools to correctly export these names or provide
replacement APIs, it would be slightly awkward to immediately require a very
new setuptools version for build.)

Remove most visible dependencies on distutils.

---

setupext.py

Use sysconfig directly instead of through distutils

---

doc/users/next_whats_new/marker_none.rst
lib/matplotlib/legend_handler.py
lib/matplotlib/markers.py
lib/matplotlib/tests/test_axes.py

As for other APIs (#19300), this is less likely to be confused with the None
object.

Support marker="none" to mean "no marker".

---

lib/matplotlib/figure.py
lib/matplotlib/tests/test_axes.py

Fixes https://github.com/matplotlib/matplotlib/issues/18925. This doesn't reset the original Axes' locator/formatter which requires a much larger change, but at least calling `remove()` doesn't error with this PR.

Break links between twinned axes when removing

---

doc/api/next_api_changes/removals/20990-AL.rst
lib/matplotlib/_api/__init__.py
lib/matplotlib/backend_managers.py
lib/matplotlib/backend_tools.py
lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_gtk4.py
lib/matplotlib/backends/backend_qt.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/docstring.py

Don't mess up with overwriting backend_tools globals, which would fail if multiple backend modules are imported.
This proposes an API to fix #17986 (and therefore unblock https://github.com/matplotlib/matplotlib/pull/20273#issuecomment-845703009).  I had tried another approach back in #9941, but that PR did many more cleanups at the same time and therefore got bogged down in side discussions; this one solely implements canvas-specific tool subclass registration.  That registration mechanism is private for now, but we can always consider making it public if there's demand for it.  (I actually guess there would not be that much demand for third-party tool implementers because even if the tool really required some backend-specific logic, it could just use a plain old if-switch instead …

Explicit registration of canvas-specific tool subclasses.

---

.circleci/config.yml
setupext.py

This seems to be failing a bit more often today, so hopefully this will help a little.

Cache build dependencies on Circle

---

lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_gtk3agg.py
lib/matplotlib/backends/backend_gtk3cairo.py
lib/matplotlib/backends/backend_gtk4.py
lib/matplotlib/backends/backend_gtk4agg.py
lib/matplotlib/backends/backend_gtk4cairo.py

I had this written for GTK3 some time ago, but was waiting for GTK4 to go in so I could add that in as well. Mostly the same as Qt, but linking to the GTK version of events, etc.

Add HiDPI support in GTK.

---

doc/users/interactive.rst

(This results in a very large double-indent in the rendered docs too.)

Fix overindented bullet list in docs.

---

lib/matplotlib/artist.py

The behavior was tweaked in 0911f8a.
(I noted that the docstring was outdated while writing https://gitter.im/matplotlib/matplotlib?at=6142fd1ed206b85e4f9efdfa.)

Update sticky_edges docstring to new behavior.

---

doc/api/pyplot_summary.rst
doc/users/next_whats_new/colormaps.rst
examples/images_contours_and_fields/contourf_demo.py
examples/images_contours_and_fields/demo_bboximage.py
examples/images_contours_and_fields/pcolormesh_levels.py
examples/images_contours_and_fields/quadmesh_demo.py
examples/lines_bars_and_markers/horizontal_barchart_distribution.py
examples/mplot3d/polys3d.py
examples/pie_and_polar_charts/nested_pie.py
examples/userdemo/colormap_interactive_adjustment.py
lib/matplotlib/cm.py
lib/matplotlib/pyplot.py

- Mark the new ColormapRegistry API as experimental
- Add the ColormapRegistry to `pyplot` as `plt.colormaps`.
Follow-up to #18503.
See also #20853.

Add ColormapsRegistry as experimental and add it to pyplot

---

doc/api/next_api_changes/deprecations/21056-AL.rst
lib/matplotlib/lines.py
lib/matplotlib/markers.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_marker.py

See docstring change for the confusion that this resolves.
We can normalize None inputs on the caller side (and note that directly
constructing MarkerStyles is not something that most users need to do).

Deprecate MarkerStyle(None).

---

examples/subplots_axes_and_figures/demo_tight_layout.py

- Remove an extraneous plt.show() (the one at the end suffices).
- This example has both pyplot and OO subexamples; if using pyplot,
don't assign the `fig` name (better be fully implicit than stopping
half-way); if using OO, use `fig.tight_layout()` instead of
`plt.tight_layout()`.
- Remove some blank lines.

Cleanup demo_tight_layout.

---

lib/matplotlib/__init__.py
lib/matplotlib/tests/test_rcparams.py

This avoids accidentally triggering backend resolution via other
RcParams instances.
See #21015; #21031 is somewhat similar.

Make rcParams["backend"] backend fallback check rcParams identity first.

---

doc/conf.py
doc/contents.rst

Index and module index are currently linked at the very bottom at:
https://matplotlib.org/devdocs/contents.html#complete-sitemap
The index is not really helpful. Search is better for all practical purposes.
The module index is redundant to the [module list on the reference page](https://matplotlib.org/devdocs/api/index.html#modules).
And the latter is better because we can control what to show; e.g. we
leave out the specific backend modules.

Remove the index and module index pages

---

plot_types/stats/README.rst
plot_types/stats/errorbar_plot.py

- use a marker and no line for the data points
- hard-code yerr instead of using random with a fixed seed
- Slightly move y so that the data points don't always fall on the grid
- Remove "specialized" from section title. There are no more special
than any other plots.

Improve errorbar plot types example

---

lib/matplotlib/colors.py
lib/matplotlib/tests/test_colors.py

`make_norm_from_scale` can be used "inline", rather than as a class
decorator, to dynamically create norm classes.  However, in that case,
the second parameter (`base_norm_cls`) would normally be set to the root
base norm class (`mcolors.Normalize`).  In that case, we should
generate a new `__name__` for the dynamically generated class, to avoid
the slightly confusing situation of having two different classes both
called `mcolors.Normalize`.
(See the "additional confusion" in the expected outcome section of https://github.com/matplotlib/matplotlib/issues/20755#issue-954604558.)

Fix make_norm_from_scale `__name__` when used inline.

---

doc/_static/mpl.css

The original thumbnail margin in gallery.css is 5px. We reduce the
horizontal margin to 2px so that four columns fit within the available
width in the pydata-sphinx-theme.

Adapt css so that galleries have four columns

---

doc/_static/mpl.css

When using the default padding and the pydata-sphinx-theme, the image
is shifted away from the center. While that should be fixed in
sphinx-gallery (and I will report it there), this serves as a workaround
on the matplotlib side, because I don't think they will have it fixed
ready for the 3.5 release.
Before:
After:

Fix decenter of image in gallery thumbnails

---

lib/matplotlib/pyplot.py
lib/matplotlib/tests/test_pyplot.py

Fix polar() regression on second call failure

---

lib/matplotlib/colorbar.py

- `__scale = "manual"` doesn't exist anymore since d1c5a6a.
- Shorten Boundary/NoNorm inversion and norm._scale check.
- No need to define `x` well before its use point, and no need to make
it an array explicitly.

Small cleanups to colorbar.

---

doc/api/next_api_changes/behavior/19515-GL.rst
lib/matplotlib/axes/_base.py
lib/matplotlib/backend_bases.py
lib/matplotlib/colorbar.py
lib/matplotlib/tests/test_backend_bases.py

I've wanted to zoom/pan on values rather than extents of the image before and haven't figured out a clean way to do that without adding widgets. For example, if I set the range poorly the first time with my data and want to zoom in on a specific region of data, or if outliers made the vmin/vmax too large the first time. This adds zoom and pan capabilities to the colorbar. When zooming and panning on the axis, this updates the vmin/vmax of the scalar mappable norm associated with the colorbar. Currently, this changes the xlim/ylim of the axis holding the colorbar, which I don't think is desired behavior.
For this to work, we need the parent axis for events, and the scalar mappable object. I wasn't sure where the best place to implement these methods is, as we need to override the parent …

Colorbar axis zoom and pan

---

lib/matplotlib/backend_bases.py

This has been the case since at least mpl2.0, so let's just fix the doc
for now.  Likely there was some confusion with zoom/pan mode, where CTRL
does fix the aspect.

CTRL does not fix aspect in zoom-to-rect mode.

---

.github/workflows/tests.yml
lib/matplotlib/tests/test_backend_qt.py

closes #21110
This fixes the QT tests to pass on OSX and tries to enable running them on GHA.

Mac qt ctrl

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

Previously, clim would be implicitly handled as part of kwargs, and
therefore get overwritten when the norm is set.  The solution is to set
the norm first.
Closes https://github.com/matplotlib/matplotlib/issues/4132.

Fix clim handling for pcolor{,mesh}.

---

lib/matplotlib/artist.py
lib/matplotlib/tests/test_image.py

Without this fix, hovering the mouse over a nan pixel in an imshow()
would result in `Warning: converting a masked element to nan.` and then
`ValueError: cannot convert float NaN to integer`.  Fix that.
The format_cursor_data test doesn't explicitly check the return value
of get_cursor_data anymore because np.ma.masked is returned for nan
inputs (this is expected from the general approach for handling invalid
data); checking that format_cursor_data gives the right string is
sufficient.
Regression coming from #20949.

Fix format_cursor_data with nans.

---

examples/animation/double_pendulum.py

The pixel-sized marker previously use (",") was so small that it looked
more like a rendering artefact than an actual data point.
Previous: https://matplotlib.org/devdocs/gallery/animation/double_pendulum.html#sphx-glr-gallery-animation-double-pendulum-py
This PR: https://63727-1385122-gh.circle-artifacts.com/0/doc/build/html/gallery/animation/double_pendulum.html?highlight=double

Increase marker size in double_pendulum example.

---

lib/matplotlib/axes/_axes.py

- `[notes section required to get data note injection right]` has been
obsoleted by DATA_PARAMETER_PLACEHOLDER; get rid of them.
- loglog, semilogx, semilogy are thin wrappers around plot; it seems
fine to not document data there and leave it implicitly part of
`**kwargs: all parameters supported by plot`.  Then "Other Parameters"
only contains `**kwargs` whose description is quite short, so it can
just be lifted into the main Parameters section rather than requiring
a separate section just for itself.
- Likewise for `step`, but that method actually explicitly lists `data`
in its signature, so just move its (already existing) description down
to its correct position.
This change was motivated by the fact that DATA_PARAMETER_PLACEHOLDER is
not correctly handled for these simple plot() …

Docstring cleanups around DATA_PARAMETER_PLACEHOLDER.

---

lib/matplotlib/axis.py
lib/matplotlib/colorbar.py
lib/matplotlib/figure.py
lib/matplotlib/patches.py
lib/matplotlib/projections/polar.py
lib/matplotlib/pyplot.py
lib/matplotlib/quiver.py
lib/matplotlib/tests/test_quiver.py
lib/mpl_toolkits/axisartist/grid_finder.py
lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py

Rename `**kw` to `**kwargs`.

---

environment.yml

This should make it much easier to set up a development environment. Essentially one should be up and running with
~~~
git clone https://github.com/matplotlib/matplotlib.git
cd matplotlib
conda env create -f environment-dev.yml
conda activate mpl-dev
pip install -ve .
~~~
This must still be added to the docs.
I've copied the dependencies together from the requirements files and https://matplotlib.org/devdocs/users/installing.html#dependencies. Not sure what to do about the optional dependencies ffmpeg, ImageMagick, LaTeX and fontconfig.

Add conda environment.yml for developers

---

doc/sphinxext/gallery_order.py
lib/matplotlib/mpl-data/stylelib/_mpl-gallery-nogrid.mplstyle
lib/matplotlib/mpl-data/stylelib/_mpl-gallery.mplstyle
plot_types/arrays/contour.py
plot_types/arrays/contourf.py
plot_types/arrays/imshow.py
plot_types/arrays/pcolormesh.py
plot_types/arrays/quiver.py
plot_types/arrays/streamplot.py
plot_types/basic/bar.py
plot_types/basic/pie.py
plot_types/basic/plot.py
plot_types/basic/scatter_plot.py
plot_types/basic/stem.py
plot_types/basic/step.py
plot_types/stats/barbs.py
plot_types/stats/boxplot_plot.py
plot_types/stats/errorbar_plot.py
plot_types/stats/eventplot.py
plot_types/stats/hexbin.py
plot_types/stats/hist2d.py
plot_types/stats/hist_plot.py
plot_types/stats/violin.py
plot_types/unstructured/tricontour.py
plot_types/unstructured/tricontourf.py
plot_types/unstructured/tripcolor.py
plot_types/unstructured/triplot.py

All changes are small. I thought it's ok to put them in a single PR to not run CI that often.
- Include new plots into gallery ordering
- Use a second style for plot types gallery entries without grid - to declutter the actual plotting code more (removes `ax.grid(False)`
- Minor formatting fixes
- Simplify unstructured data generation: There is no need to generate a regular grid and statistically choose points from that. Instead, we can immediately choose random points.

More (minor) plot types gallery fixes.

---

doc/api/next_api_changes/deprecations/21126-TH.rst
lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

This will allow to simplify the implementation because, currently,
`stem(*args, linefmt=None, ...)` still tries to resolve excess
positionally passed args, to *linefmt* and following parameters, which
is quite a bit of logic (see `# fallback to positional argument` comments
in the implementation).
OTOH, since we have 3 formats, passing them positionally is already
difficult from a usability/readability perspective, because they can
easily be mixed up.

Deprecate passing formatting parameters positionally to stem()

---

lib/matplotlib/backends/backend_agg.py
lib/matplotlib/tests/test_agg.py
lib/matplotlib/tests/test_simplification.py
src/_backend_agg.cpp

This does 2 important things:
- makes the errors when you exceed the chunk size more instructive of how to fix your problem
- makes the upper limit higher so it will be hit less often
and 2 less important things:
- makes a test more pathological
- makes sure the simplification threshold is propagated when chunking.

Enh improve agg chunks error

---

examples/mplot3d/contour3d.py
examples/mplot3d/contour3d_2.py
examples/mplot3d/contour3d_3.py
examples/mplot3d/contourf3d.py
examples/mplot3d/contourf3d_2.py

Axes3D.clabel is a noop, so don't use it in examples (perhaps it should
in fact throw a NotImplementedError, but let's not worry about that
here).
Various other small cleanups.
https://github.com/matplotlib/matplotlib/blob/7c2a3c4384368b65227f68543ee96acca948388e/lib/mpl_toolkits/mplot3d/axes3d.py#L974-L976

Cleanup contour(f)3d examples.

---

lib/matplotlib/backends/backend_qtagg.py
lib/matplotlib/backends/backend_qtcairo.py

While testing out Matplotlib 3.5.0b1 with pyqtgraph, pyqtgraph CI pipelines were failing for PySide2 bindings.
https://github.com/pyqtgraph/pyqtgraph/pull/1999
The segfault was due to an old PySide2 QImage leak workaround. This leak was addressed in https://bugreports.qt.io/browse/PYSIDE-140 and versions of PySide2 >= 5.12 no longer need this workaround. 
This PR skips the workaround for PySide2 >= 5.12.
The other change of casting to int for PyQt6 avoids the following warning:
```
c:\work\venv\allqt\lib\site-packages\matplotlib\backends\backend_qtagg.py:67: DeprecationWarning: an integer is required (got type PyQt6.sip.voidptr).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
```
Note: pyqtgraph only exercises the changes …

skip QImage leak workaround for PySide2 >= 5.12

---

doc/devel/contributing.rst

Update contributing guide.

---

doc/api/next_api_changes/deprecations/ZZZZZ-AL.rst
lib/matplotlib/mlab.py
lib/matplotlib/tests/test_mlab.py

The functionality is directly provided by numpy>=1.20 (it will be a
while before we can rely on that version of numpy, but we can still
deprecate stride_windows as public API in the meantime, as we don't want
to encourage users to rely on mlab for that).

Deprecate mlab.stride_windows.

---

doc/api/next_api_changes/deprecations/21187-AL.rst
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_wx.py

They are clearly intended for Matplotlib's internal use (e.g.
error_msg_wx sets the title of the message dialog to "Matplotlib backend
error"), and similar helpers have already been removed from other
backends.
Also correctly set the parents on the message dialogs, don't bother
setting the button on wx.MessageDialog (which already defaults to
CENTRE|OK), make the wx title also apply to other wxfoo backends, and
rename a variable in backend_wx for consistency.

Deprecate error_msg_foo helpers.

---

plot_types/arrays/quiver.py

While quiver can be used on individual points, the most common use case
is gridded data. We should use the common use case as the example.
Another reason is that, `quiver()` is assigned to the arrays category
in plot types.

Rework plot types quiver

---

lib/matplotlib/axes/_axes.py

Previously, `csd([0, 0], [0, 0])` would fail with a ZeroDivisionError
when computing yticks.  Fix that by copying the logic from psd, and
streamlining it in both places.  Also fix an unformatted exception
message in specgram.

Fix very-edge case in csd(), plus small additional cleanups.

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

intervaly would not be ordered if the yaxis is inverted; get_ybound() is
always ordered.  Fix that, add a test, and also test the full-zero input
case recently fixed.

Fix more edge cases in psd, csd.

---

lib/matplotlib/tests/test_backend_pdf.py
lib/matplotlib/tests/test_backend_svg.py
lib/matplotlib/tests/test_usetex.py

Parametrize/simplify test_missing_psfont.

---

doc/_templates/mpl_nav_bar.html
doc/users/index.rst

- Nav link closes #21161.
- The release and date are already shown on the new top-level https://matplotlib.org/devdocs/contents.html page.

Fix nav link for "Usage guide" and remove release/date info from that page

---

.circleci/config.yml
doc/conf.py
doc/devel/release_guide.rst

This adds a release mode tag, which encapsulates all the things we disabled for CircleCI, as well as other things we'd put in tagged release docs. It disables these by default, so local development will be quicker as well. And then it _re-enables_ release mode when building devdocs.
This covers image compression, HiDPI images, the theme navigation, analytics, and plot directive formats.

DOC: Add a release mode tag

---

doc/faq/howto_faq.rst

The original wording was inaccurate as both the pdf and pgf backends
provide this functionality.  I tried fixing that, but duplicating all
links to both backends seemed unwieldy; additionally the "narrative"
version of the FAQ reads worse (we should just encourage `pp.savefig()`
instead of explaining that `plt.savefig()` needs workarounds, and also
prefer `with PdfPages(...) as pp:`).  Given that the docstring of both
classes have examples, I just got rid of most of the FAQ entry instead
(see also the next FAQ entries, which also have no code).

Shorten PdfPages FAQ entry.

---

.appveyor.yml
lib/matplotlib/backends/qt_compat.py
lib/matplotlib/tests/test_backend_qt.py

This prevents them accidentally breaking the test runner itself, depending on platform. Also, enable Qt tests on AppVeyor. A followup to #20883.
~~I haven't converted `test_fig_sigint_override` yet, as I want to see if this works on Windows.~~ `test_fig_sigint_override` doesn't actually fire any signals, but I modified it to ensure it doesn't leave broken global state.

Move sigint tests into subprocesses

---

examples/lines_bars_and_markers/fill_between_alpha.py
examples/lines_bars_and_markers/filled_step.py
examples/lines_bars_and_markers/gradient_bar.py
examples/lines_bars_and_markers/stackplot_demo.py

- Fill between alpha: Use default color palette more
- Hatch filled historgrams: Soften fill colors using alpha
- Bar chart with gradients: Replace the strong orange background
gradient with softened red-green horizontal gradient. This looks
nicer and the red-green background could even be used as a semantic
good-bad indicator.
- Stackplot: Soften fill colors using alpha

DOC: Adapt some colors in examples

---

doc/users/prev_whats_new/whats_new_3.5.0.rst

Fix release notes typos.

---

.flake8
README.rst
doc/conf.py
environment.yml
requirements/doc/doc-requirements.txt

Instead of trying to figure out a regex, just use `packaging` to parse the version, and link to either `master` branch or a tag directly if a release.

DOC: Fix source links and flake8 cleanup

---

.flake8
README.rst
doc/conf.py
requirements/doc/doc-requirements.txt

Backport PR #21240: DOC: Fix source links and flake8 cleanup

---

doc/conf.py

We normally replace prerelease docs with final anyway, but until that time, the links using `Version.base_version` would point to the final tag, which won't exist yet. But `Version.public` includes the prerelease part and should point to the right tag.

DOC: Fix source links to prereleases

---

examples/images_contours_and_fields/colormap_interactive_adjustment.py

The colormaps have interactivity with zoom/pan now, so demonstrate what those modes do with this new example. This is instead of using callbacks and mouse events for updates that were used in the previous example.
Example modified from: https://github.com/matplotlib/matplotlib/pull/19515#issuecomment-850017535
xref: #19515 and #20471

DOC: Update interactive colormap example

---

examples/subplots_axes_and_figures/figure_size_units.py

DOC: Fix footnote that breaks PDF builds

---

lib/matplotlib/backends/backend_qt.py

pixelDelta() is explicitly documented as "unreliable" and not-to-be-used
on X11 (https://doc.qt.io/qt-5/qwheelevent.html#pixelDelta);
locally, it reports the same value as angleDelta, but
because it isn't scaled, the value is 120x too big.  So add
a check that forces the use of angleDelta() on X11 (see also
https://doc.qt.io/qt-6/qguiapplication.html#platformName-prop).
This would be nice to have in 3.5 (I guess something recently changed in
the underlying X11 stack, exposing that bug).  I'll mark as release critical
just to get some attention :-) but am fine if this gets pushed back too.

Don't use pixelDelta() on X11.

---

setupext.py

Pass along a few options to ensure that FreeType doesn't end up with a mixed compiler or bit-ness compared to the rest of the compiled `ft2font` extension.

Ensure internal FreeType matches Python compile

---

doc/devel/contributing.rst

This is a combination of @anntzer and @jklymak's language on issues not being assigned, though I put it under "new contributor issues"
* https://gitter.im/matplotlib/matplotlib?at=615aca48fb3dcd4e8808f439
* https://gitter.im/matplotlib/matplotlib?at=615acbf9f2cedf67f96662fd

Add language about not assigning issues

---

doc/users/next_whats_new/extending_MarkerStyle.rst
examples/lines_bars_and_markers/marker_reference.py
examples/lines_bars_and_markers/multivariate_marker_plot.py
lib/matplotlib/lines.py
lib/matplotlib/markers.py
lib/matplotlib/tests/test_marker.py

Add user supplied transforms and join/cap styles …
Improvement was done in instantiating new instance utilizing deep copy should preserve immutability of MarkerStyle members (e.g. Path, or Transform). However deepcopy of MarkerStyle(r"$|||$") fails. Originally it was needed in lines.py, but I think it can be optimized out to avoid multiple re-instantiation of MarkerStyle.
I followed the discussion for issue #19195 and tried several cases:
```python
from matplotlib import transforms
from matplotlib.lines import Line2D
from matplotlib.transforms import Affine2D
from matplotlib.markers import MarkerStyle, JoinStyle, CapStyle
text_style = dict(horizontalalignment='right', verticalalignment='center',
fontsize=12, …
```

19195 rotated markers

---

lib/matplotlib/cbook/__init__.py
lib/matplotlib/tests/test_image.py

Previously, moving the cursor over
`plt.imshow(1 + np.random.randn(10, 10) * 1e-15)` would result in
`ValueError: math domain error` (when trying to compute
`math.log10(delta)` with `delta = 0`).  This is because the full range
of normalization implied by the image above (~1e-15) is representable
with float precision, but the spacing between individual colors (256x
less) is too small to be represented, and thus rounded to zero.
In general, I consider that such floating point errors should be fixed
on the user side, but this specific error seems worth fixing as the 1)
the image is still rendered correctly, 2) errors in the mouse event
handler (rendering the cursor text) are somewhat obscure for end users,
and 3) it used to work before Matplotlib 3.5.

Fix format_cursor_data for values close to float resolution.

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

The PR adds a validator for `xerr` and `yerr` arguments in errorbar method to fix  #21101.
It brings implementation compliant with the documentation:
>Note that all error arrays should have *positive* values.
source: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axes/_axes.py#L3183

Fix #21101 Add validator to errorbar method

---

examples/animation/animate_decay.py
examples/animation/pause_resume.py

Without a newline before lists, the text is crammed into one paragraph.

DOC: Fix some lists in animation examples

---

setupext.py

The changes in #21263 caused wheel builds to fail, which we didn't see because they aren't run on pull requests. I've made sure that [wheel CI](https://github.com/QuLogic/matplotlib/actions/runs/1306485729) passes this time.
The problem is that setting `CC` only is incomplete, and we need to set the linker, etc. It is better to grab that from `sysconfig` rather than messing around with the `distutils` compiler that I originally did. Also, fix build on PyPy as well.
- [n/a] Conforms to Matplotlib style …

Fix freetype wheel building

---

lib/matplotlib/tests/test_backends_interactive.py

It appears to no longer timeout on that system, and is breaking CI, which just switched to it.

Allow macosx thread safety test on macOS11

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

If it's passed as a keyword argument, then it needs to be removed from `kwargs`, or not passed again explicitly. Other handling of `snap` uses `setdefault`, so do that here too.
This fixes the `pcolormesh` tests in Cartopy. Also, added a test here, since it was apparently not caught. …

Fix snap argument to pcolormesh

---

environment.yml
requirements/doc/doc-requirements.txt

Now that it's out, we don't need to depend on a random commit.

DOC: Bump to the sphinx-gallery release

---

lib/matplotlib/_layoutgrid.py
lib/matplotlib/tests/test_constrainedlayout.py
lib/matplotlib/tests/test_figure.py

Closes #21480
In that issue, gridspec indexing with open slices fails with constrained_layout for subfigures...

FIX: spanning subfigures

---

lib/matplotlib/widgets.py

Adding tutorial links for blitting in widgets.py

---

lib/matplotlib/axes/_base.py
lib/matplotlib/cm.py
lib/matplotlib/figure.py
lib/matplotlib/pyplot.py
tutorials/text/mathtext.py

This is non standard, and does not work with all rst parsers.
And those are the only few while there is approximatively 1200 directive
that don't use space in the codebase

Do not use space in directive calling.

---

lib/matplotlib/axes/_base.py
lib/mpl_toolkits/mplot3d/axes3d.py

The bounds on zmargin values can match those on x/ymargins.

Reword margins docstrings, and fix bounds on zmargin values.

---

lib/matplotlib/backends/backend_wx.py

The arg has always defaulted to False in wx4
(https://wxpython.org/Phoenix/docs/html/wx.App.html#wx.App.__init__ +
scavenging git history), and unless you are well-versed in the wxPython
API it is not clear what it means.

Remove unnecessary False arg when constructing wx.App.

---

lib/matplotlib/pyplot.py
lib/matplotlib/tests/test_pyplot.py

Closes #21441  
```
pos1 = [0.1, 0.1, 0.3, 0.8]
pos2 = [0.5, 0.1, 0.4, 0.6]
ax1 = plt.axes(position = pos1)
ax1.plot([0,1], [0, 1], color = 'r', linewidth = 3)
ax2 = plt.axes(position = pos2)
ax2.plot([1, 0], [0, 1], color = 'b', linestyle = '--')
```
is documented to work, but position is silently ignored.  `position` is just redundant with `rect`, so go ahead and check for position if rect is None.

FIX: re-instate ability to have position in axes

---

doc/api/prev_api_changes/api_changes_3.5.0/deprecations.rst
lib/matplotlib/collections.py
lib/matplotlib/tests/test_collections.py

This fixes a regression from #20717 in networkx (Fixes #21517), but we'll go forward with the change in a later release to give them time to fix it.
Since this will be reverted for 3.6, this is targeting v3.5.x directly.

Ignore transOffset if no offsets passed to Collection

---

doc/api/artist_api.rst
lib/matplotlib/artist.py
lib/matplotlib/axes/_base.py

This allows one to write e.g. `imshow(array, mouseover=False)` instead
of `im = imshow(array); im.mouseover = False`.
The Python property is kept for backcompat.

Turn mouseover into a mpl-style getset_property.

---

lib/matplotlib/figure.py
lib/matplotlib/pyplot.py

#21532 @timhoffm
Added links to the provisional API documentation for the subplot_mosaic function in both the ``figure`` and ``pyplot`` module docstrings
- [ N/A] New features are documented, with examples if plot related.
- [ N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).

Added links to the mosaic docs in figure and pyplot module docstrings

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

Closes #21552
positions in event plot can be a list of lists, but our unit-processing machinery only handles array-like, so process each element of the list separately after we have turned arbitrary inputs into a list of lists.

Fix eventplot units

---

lib/matplotlib/_blocking_input.py
lib/matplotlib/blocking_input.py

This was missed in 3ccc17b.  Closes #21548.
Milestoning as 3.5 as this is a regression in 3.3 and the fix seems simple enough, but feel free to push to 3.6.

Fix check for manager presence in blocking_input.

---

lib/matplotlib/rcsetup.py
lib/matplotlib/tests/test_rcparams.py

MNT: reject more possibly unsafe strings in validate_cycler

---

lib/matplotlib/axis.py
lib/matplotlib/tests/test_colorbar.py

The return type changed accidentally when remove_overlapping_locs was
introduced (except for NullLocator, which always returned a plain list).
Make the API consistent with majorticks, which are (mostly) always
returned as an array.
Modifying the test in test_colorbar is so-so, but that's the only place,
AFAICT, that currently tests anything with get_ticklocs(minor=True),
so...
Closes https://github.com/matplotlib/matplotlib/issues/19559.

Return minorticks as array, not as list.

---

lib/matplotlib/streamplot.py
lib/matplotlib/tests/test_streamplot.py

- Support array-like, but not array, x/y.
- Support fully masked inputs.  (Closes https://github.com/matplotlib/matplotlib/issues/19323.)
- Don't mention the Grid class (effectively internal) in error messages.

Various small fixes for streamplot().

---

lib/mpl_toolkits/mplot3d/axes3d.py

This is particularly important when the vast majority of artists are
expected to be invisible, e.g. when using ArtistAnimation.
Mostly closes #10207 (see https://github.com/matplotlib/matplotlib/issues/10207#issuecomment-358516597); perhaps some more fancy solutions are possible but this should be good enough for now...

Skip invisible artists when doing 3d projection.

---

lib/matplotlib/colorbar.py
lib/matplotlib/tests/test_colorbar.py

Fixes #21378
This PR introduces `formatter` as property to fetch axis format and thus new style string formatter is used
If applying a similar logic to major and minor locators, we can end up with removing the code from `update_ticks`.
Tricky part is with `self.norm`.
If we are ok with this solution, I can work on doing the same for `locator` and `minorlocator`.
Context: PR from PyData Global 2021 mentored sprint
cc @tacaswell

[ENH]: Use new style format strings for colorbar ticks

---

lib/matplotlib/spines.py
lib/matplotlib/tests/test_spines.py

If the name does not exist, then `__getattr__` should raise `AttributeError`, not `ValueError`.
Fixes #21554

Raise correct exception out of Spines.__getattr__

---

lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

Fixes https://github.com/matplotlib/matplotlib/issues/21578
attn: @PBiret
- [NA] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [NA] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

Fix RangeSlider.reset

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_gtk4.py

UnCamelCase it in NavigationToolbar2.  Remove it from
FigureCanvasGTK{3,4} (it is now never accessed via the canvas, only via
the toolbar; this likely goes back to the original (pre-NT2) toolbar
design.

Rename/remove _lastCursor, as needed.

---

lib/matplotlib/backends/backend_gtk3.py

The fullscreen state can also change via the window manager, so read the
state instead of trying to keep an internal flag.  All other backends
already use a similar strategy.
(`self.window` is a GtkWindow, whereas `self.window.get_window()` is a
GdkWindow...)

Make gtk3 full_screen_toggle more robust against external changes.

---

examples/showcase/anatomy.py

In 3.5.0rc1, the call to `ax.legend()` in the [Anatomy of a figure](https://matplotlib.org/3.5.0/gallery/showcase/anatomy.html) example is now placing the legend in the lower right corner:
In [version 3.4.3](https://matplotlib.org/stable/gallery/showcase/anatomy.html), this call is determining that the "upper right" is the best location for the legend so the example works. I modified the call to `ax.legend()` to specify `loc="upper right"` to ensure we always have the legend in the correct spot.

[BUG in 3.5.0rc1] - Anatomy of a Figure has the legend in the wrong spot

---

setupext.py

Versions prior to 2.7.1 cannot be accessed without indexing the 'freetype-old' folder on the savannah site. Pypi installs for Matplotlib can request earlier versions (e.g. 2.6.1) and thus cause some builds to fail where sourceforge access is blocked.
- [N/A] New features …

Support for pre 2.7.1 freetype savannah versions

---

lib/matplotlib/backends/_backend_gtk.py

When the application is shut down, it's intended that all windows are closed. This shutdown event is also run if interrupted with Ctrl-C. But then the main loop is no longer running, and windows do not notice the close event sent to them.
In IPython, the input hook runs the loop and allows the windows to close down. But in plain Python, there is no input hook integration, and the windows sit around in limbo without accepting any events.
Absent any new input hook integrations, the workaround is to iterate the main loop on interrupt.
- [n/a] New features have an …

Fix interrupting GTK on plain Python

---

lib/matplotlib/hatch.py

We want to wait until an official API is available to define custom
hatches. One can currently add custom patches via monkeypatching, which
would be prevented by the hatch validation:
https://github.com/matplotlib/matplotlib/issues/20690#issuecomment-965638949

Defer enforcement of hatch validation

---

lib/matplotlib/axes/_subplots.py
lib/matplotlib/figure.py
lib/matplotlib/gridspec.py
lib/matplotlib/tests/test_polar.py

This allows having it both in subplots() (which had that check before)
and in subplot_mosaic (which didn't, see test).  (All Axes returned by
subplots() have the same projection, so `all(ax.name == "rectilinear")`
can be replaced by independently checking each Axes.)
xref #19994, again this may mess up some third-party axes (https://github.com/matplotlib/matplotlib/pull/19994#issuecomment-821595763) but the tradeoff seemed OK back then.  (We can always consider adding a "does this want to participate in label_outer" flag if there's demand for it, but let's not overengineer things for now.)
Edit, following review: Also improve the rectilinearity check by testing the shape of the axes
patch instead (so that e.g. skewT also participates in
outer-only-labels), and add an escape hatch so that …

Move label hiding rectilinear-only check into _label_outer_{x,y}axis.

---

doc/_templates/cheatsheet_sidebar.html

Cheatsheets now has a website (https://matplotlib.org/cheatsheets/) so link to that instead of the GitHub page.

DOC: link to cheatsheets site, not github repo

---

lib/matplotlib/backends/backend_ps.py
lib/matplotlib/tests/test_backend_ps.py

This tests that we have not re-defined a short-cut by checking that we do not
have two `/name` lines in the output file.
closes #21509

FIX: Make sure we do not over-write eps short cuts

---

lib/matplotlib/testing/compare.py

The `stack` variable should default to bytes, not str, which we can compress into a single statement for clarity.

Fix GhostScript error handling types

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Followup to #20688.
The goal is to make this as concise as possible.
Previews can be seen here: https://github.com/timhoffm/matplotlib/tree/doc-issue-template/.github/ISSUE_TEMPLATE

Shorten issue templates

---

lib/matplotlib/_mathtext.py
requirements/doc/doc-requirements.txt
requirements/testing/all.txt

cf https://github.com/matplotlib/matplotlib/pull/21489#issuecomment-954225531 (@ptmcg I'm not super certain about the expected semantics, but the need to explicitly skip whitespace here *looks* like a bug to me?)
For master, I think #21448 also fixes that.

Refix for pyparsing compat.

---

lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

@dstansby, as mentioned in https://github.com/matplotlib/matplotlib/pull/20839#issuecomment-966512282, this is the first part of #20839.
- Fix centre and square state of rectangle selector in interactive mode. These states were working only when creating the selector.
- Fix name coordinate handle: N and S were swapped.
- Rebased on latest main branch.
```python
from matplotlib.widgets import RectangleSelector
values = np.arange(0, 100)
ax.plot(values, values)
selector = RectangleSelector(ax, print, interactive=True, drag_from_anywhere=True)
```
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions …

Fix centre square rectangle selector part 1

---

src/_backend_agg_wrapper.cpp
src/_contour_wrapper.cpp
src/_path_wrapper.cpp
src/ft2font_wrapper.cpp
src/tri/_tri_wrapper.cpp

A bunch of functions are declared with [`METH_VARARGS`](https://docs.python.org/3/c-api/structures.html?highlight=meth_varargs#METH_VARARGS) calling convention which should have signature [`PYCFunction`](https://docs.python.org/3/c-api/structures.html?highlight=meth_varargs#c.PyCFunction). However, they are declared instead with an extra `PyObject* kwds` argument as if they had `METH_VARARGS | METH_KEYWORDS` calling convention. They just ignore this argument.
I am coming from Pyodide. Web assembly has no native support for function pointer casting -- a function declared with a certain signature must be called with the same signature, or it will fail with `RuntimeError: function signature mismatch`. Emscripten has support for emulating function pointer casts which we are currently using, …

Fix METH_VARARGS method signatures 

---

lib/matplotlib/__init__.py
lib/matplotlib/backends/qt_compat.py
lib/matplotlib/texmanager.py

Version numbers from non-Python packages don't have to follow PEP440,
and there are at least a few cases where we can check for string
equality (when we don't need ordering) or rely on the library's own
version parsing (qt).

Skip some uses of packaging's PEP440 version for non-Python versions.

---

examples/units/basic_units.py
lib/matplotlib/lines.py
lib/matplotlib/tests/test_lines.py
lib/matplotlib/tests/test_units.py

Fixes #21147
This fixes the earlier PR https://github.com/matplotlib/matplotlib/pull/21299 by @kinshukdua which was abandoned due to tricky problem with unit test failure

Make Line2D copy its inputs

---

doc/api/prev_api_changes/api_changes_3.5.0/deprecations.rst
doc/users/github_stats.rst
doc/users/prev_whats_new/github_stats_3.4.3.rst
doc/users/release_notes.rst
doc/users/release_notes_next.rst
lib/matplotlib/_mathtext.py
lib/matplotlib/tests/test_mathtext.py
setupext.py

Also reverts #21550, which was not intended for 3.6.

Merge 3.5.x into main

---

.github/workflows/tests.yml
setup.py

Closes #21660
We are missing a new line when formatting the matplotlibrc

FIX: put newline in matplotlibrc when setting default backend

---

lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/tests/test_mplot3d.py

A 2D array-like was accepted and only issued an obscure warning. This
can easily happen if one has only one polygon and forgets to warp it in
a list.
Closes #21652.
Note: I refrain from an additional check that each Polygon has shape
(N_i, 3) because that will reasonaly error out later, so we don't have
to blow up parameter checking too much.

Validate that input to Poly3DCollection is a list of 2D array-like

---

lib/matplotlib/axes/_axes.py

1) Move the test into x/y loop, to write it just once.
2) Change the test to directly also work for timedelta, rather than
having to manually test it.  (In practice, the relevant question is
whether the "low" end of the errorbar is indeed below the "high" end
of the errorbar.)

Simplify test for negative xerr/yerr.

---

lib/matplotlib/colorbar.py
lib/matplotlib/tests/test_colorbar.py
lib/matplotlib/tests/test_contour.py

Closes #21671 
Fixes an issue where the BoundaryNorm colorbar was broken if the boundaries were negative.  Added new test to make sure this doesn't break again.  
I'll be honest, I find this part of the colorbar code a bit inscrutable, and it doesn't have a lot of unit tests.  So more bug reports to help get all the combinations down would be helpful.  

Fix boundary norm negative

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_qt.py
lib/matplotlib/pyplot.py

- More the implementation to backend_bases and have pyplot read it,
rather than having backend_bases fetch it from pyplot, which was a
bit weird.
- Attach the subplot_tool to the toolbar, which avoids having to keep
a reference to it (when calling plt.subplot_tool), and prevents
opening two subplot_tools for the same figure.  On most backends,
closing the subplot_tool deletes the reference, because reopening a
closed figure seems not guaranteed to work; on Qt, which has its own
subplot_tool, reopening the closed QDialog does work, so just reuse
it.
- Ensure that closing the main figure also closes the subplot_tool.
(#21679, the main motivation for this PR.)

Bind subplot_tool more closely to target figure.

---

doc/api/next_api_changes/removals/21591-AL.rst
lib/matplotlib/backend_tools.py

See rationale in changelog entry.
Unfortunately, this breaks some backcompat, but keeping shims around
seems not trivial (accessing the toggled state, in particular, would
need to be implemented per-backend), and backend_tools is provisional
anyways...

Make ToolFullScreen a Tool, not a ToolToggle.

---

.github/workflows/tests.yml

This will limit the tests to the main repository and reduce CI waste from running tests twice on both forks and the main repo.

CI: Remove CI test runs from forks of matplotlib

---

lib/matplotlib/backends/backend_ps.py

`:g` format drops non significant zeros, and also uses scientific
notation as appropriate; PostScript explicitly supports scientific
notation (PostScript Language Reference section 3.2).
The point is mostly to improve the legibility of the PostScript output.

Drop non-significant zeros from ps output.

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

This is the same issue and same fix as for pcolor{,mesh} in 2d8f3be (#4132, #21146).

Fix support for clim in scatter.

---

lib/matplotlib/gridspec.py

Fixed typo in GridSpec height_ratio description

---

lib/matplotlib/colors.py
lib/matplotlib/transforms.py
lib/matplotlib/tri/triinterpolate.py
lib/matplotlib/widgets.py
lib/mpl_toolkits/mplot3d/axes3d.py

Note that the warning in transform_angles was poorly worded: `angles` is
1D, and thus not a "column vector" and doesn't have "rows".
In RangeSlider.set_val we don't need to explicitly cast to arrays as
np.sort will do that for us anyways.

Use _api.check_shape more.

---

doc/api/prev_api_changes/api_changes_3.5.0/development.rst

Done in #20871 as part of de-conflicting our config files from other tools.
closes #21713

DOC: note renaming of config.cfg.template to mplconfig.cfg.template

---

setupext.py

The `CC`/`CFLAGS`/etc flags from the Python config should be our default, but we should always listen to an existing `CC` set in the environment.
Fixes https://github.com/conda-forge/matplotlib-feedstock/pull/312#issuecomment-973902767

Fix compiler configuration priority for FreeType build

---

lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_axes.py

Addresses #21394 so that the padding is consistent, if not exactly what the user wants.  
```
fig, axs = plt.subplots(2, 1, sharex=sharex)
axs[0].set_title(f'A sharex={sharex}', pad=-40)
axs[1].set_title('B', pad=-40)
```
Note how when we sharex the title is displaced downwards, but only in the first plot, not the last one.  This is inconsistent with the sharex=False behaviour, which is to manually move the axes outside the axes bounds (regardless of the users' pad argument).
We did discuss this behaviour, and decided it was OK, if less than great.  Users can get around this by specifying `y` manually (i.e. `y=1.0001` works fine).   We probably should deprecate the `pad` argument in favour of just asking folks to specify the title position using `y`.

FIX: logic of title repositioning

---

doc/conf.py

When `SOURCE_DATE_EPOCH` is set, then Sphinx will attempt to 'fix' the year in the copyright:
https://github.com/sphinx-doc/sphinx/issues/3451#issuecomment-877801728
We already correctly understand that envvar, so this is unexpected and wrong.
Sphinx looks for a 4-digit year followed by a space or two 4-digit years separated by a dash. We can fix this by using an en-dash, which is the correct typographical symbol for date ranges anyway, and thwarts Sphinx.
Fixes #20854 …

Fix copyright date with SOURCE_DATE_EPOCH set

---

lib/mpl_toolkits/axes_grid1/inset_locator.py
lib/mpl_toolkits/tests/test_axes_grid1.py

Closes https://github.com/matplotlib/matplotlib/issues/17711; see description there.  Milestoning as 3.6, but I guess 3.5 would be good too.

mark_inset should manually unstale axes limits before drawing itself.

---

tutorials/colors/colormap-manipulation.py

This fixes an erroneous statement in the colormap tutorial;  closes #15884.

Doc fix colormap inaccuracy

---

lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_axes.py

Closes #11416
The error message was pretty mysterious if you called `ax.axis('equal')` on a shared axes...
Not clear that the functionality users are _trying_ to get from this could not be provided, but at least clarifying the error message will help...

FIX: better error message for shared axes and axis('equal')

---

src/_contour_wrapper.cpp
src/_image_wrapper.cpp
src/ft2font_wrapper.cpp
src/tri/_tri_wrapper.cpp

In particular, all methods were missing the self arg in the documented
signature (one can check that this matters e.g. by inspecting
`inspect.signature(matplotlib.ft2font.FT2Image.draw_rect)`).
(xref #15009)

Fix/add docstring signatures to many C++ methods.

---

examples/misc/coords_report.py

- add remark that this only pertains to the interactive backend
- PEP8 fixes
The [coord reports example](https://matplotlib.org/stable/gallery/misc/coords_report.html#sphx-glr-gallery-misc-coords-report-py) prominently shows the plot produced by the example. This can be a bit midleading as the demonstrated feature is only visible in the interactive backend. As this can lead to some confusion (see e.g. #2205), I added a short explanatory remark.  
(the same pertains to the [modifying the coordinate formatter example](https://matplotlib.org/3.5.0/gallery/images_contours_and_fields/image_zcoord.html))
[N/A] New features are documented, with examples if plot related.
[N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in …

DOC: Clarify Coords Report Example

---

lib/matplotlib/backends/backend_pdf.py

As for svg (10145a2 #19717), this makes outputs marginally easier to read, and
is not necessary anymore now that dicts maintain insertion order.

Don't sort pdf dicts.

---

lib/matplotlib/backends/backend_pdf.py

Also, such directly output streams don't need an explicitly set Length,
as the stream outputter will fill in that entry itself.  This is why
e.g. the invalid entry for toUnicodeMapObject (where Length was set to
unicode_cmap rather than len(unicode_cmap)) was not a problem: it was
overwritten in endStream().

Add a helper for directly output pdf streams.

---

lib/matplotlib/figure.py
lib/matplotlib/tests/test_figure.py

As reported on gitter, if an axes does not have a subplotspec `align_ylabels` will fail:
```python
fig, ax = plt.subplot_mosaic('AABB', figsize=(5, 2), constrained_layout=True)
pm = ax["A"].pcolormesh(np.random.randn(100, 100))
plt.colorbar(pm, ax=ax['A'], shrink=0.69, pad=0)
fig.align_ylabels()
```
This PR fixes this and tests the fix.  

FIX: align_x/ylabels

---

lib/mpl_toolkits/mplot3d/axes3d.py
lib/mpl_toolkits/tests/test_mplot3d.py

Previously, when finding the 3D zorder, external artists were assumed to
use the calling convention of `Patch3D.do_3d_projection` from Matplotlib
3.3, where it took a positional `renderer` parameter.  This triggered
a deprecation warning, even if the artist could support the new
convention.  Now we attempt to bind the signature first, and only emit a
deprecation warning if the calling convention does not appear to work.
- [N/A] Documentation is sphinx and numpydoc …

Reduce do_3d_projection deprecation warnings in external artists

---

.github/workflows/tests.yml

The log is useful even on success, e.g. to check for warnings.  It is
also consistent with what's already being done on Azure Pipelines.

Don't hide build log on GHA.

---

src/_macosx.m

Inherit many macos backend docstrings.

---

tutorials/intermediate/arranging_axes.py

DOC: fix missing ref

---

lib/matplotlib/backends/backend_macosx.py
lib/matplotlib/tests/test_backend_macosx.py

Make sure that a cached renderer gets added to the figure after calling fig.canvas.draw() on the macosx backend. This changes the draw path to go through adding a renderer to the figure first.
closes #19197
closes #13968
closes #7550

FIX: Make sure a renderer gets attached to figure after draw

---

lib/matplotlib/backend_bases.py

Do not fully understand what changed, but without this change `walk_stack`
would start 2 frames higher (in the test module, not in backend_bases) which
would mean we never saw the frame with `print_figure` and hence was getting
warnings which we converted to failures on a vast majority of the tests.
I suspect that this is related to the fast-Python work and avoiding making
unneeded structures during the calls, but chased that theory down yet.
Discovered on a commit between py311a2 and py311a3.
This will need a followup PR to main that rips out almost all of this code.  We should have ripped it out in mpl35, but do not think we should do that in a patch release so also updated the deprecation date.

MNT: make print_figure kwarg wrapper support py311

---

lib/matplotlib/colorbar.py
lib/matplotlib/tests/test_tightlayout.py
lib/matplotlib/tight_layout.py

Closes #21749 
The subplotsepc logic was not correct for manually added colorbars so that tight_layout would raise instead of warn about the manual colorbar not being part of a layout.  

FIX: manual colorbars and tight layout

---

lib/matplotlib/gridspec.py

Documentation for height_ratios in GridSpec.__init__ uses "column" where it should use "row", one of the uses of column likely having escaped from changes when adapting the width_ratios documentation to height_ratios.  This fixes the mixup.
(This is a one-word change to documentation.)
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in …

Fixes row/column mixup in GridSpec height_ratios documentation.

---

src/_macosx.m

Accidentally removed in f7a432a.
Closes https://github.com/matplotlib/matplotlib/commit/f7a432a7523d4c99b19f0cd56b17e0310fcb3c20#r61013322.  Would be nice if we could run with -Werror instead, which would have caught this, but I assume @dopplershift had a good reason to only use -Werror=unguarded-availability in #17956?
It's also not completely clear to me why the only call to closeButtonPressed (in windowShouldClose) is protected by respondsToSelector, and whether it could just be inlined there instead, using something like
```patch
diff --git i/src/_macosx.m w/src/_macosx.m
index 64875fe7f1..cf84ef02fa 100755
--- i/src/_macosx.m
+++ w/src/_macosx.m
@@ -1519,12 +1519,8 @@ - (BOOL)windowShouldClose:(NSNotification*)notification
data1: 0
data2: 0];
[NSApp postEvent: event atStart: true];
- …
```

Fix missing return value in closeButtonPressed.

---

lib/matplotlib/blocking_input.py

The whole module has been deprecated as the library is now using
_blocking_input, which does not have the same problem, but it still
seems better to fix this typo asap.
Closes https://github.com/matplotlib/matplotlib/pull/21553#issuecomment-981273647; compare https://github.com/matplotlib/matplotlib/pull/21553/files#diff-40db16a7cd74c616dae604fc6676f18401651520bc8bff358d27b8d2b4b0862f.

Refix check for manager presence in deprecated blocking_input.

---

lib/matplotlib/dates.py
lib/matplotlib/tests/test_dates.py

Closes #21670
When plotting > 1year with concisedateformatter, no offset text is shown,.  However, when you zoom it _should_ be shown.  However, we were hard-fixing the parameter for the locator, and it didn't reset itself.  This PR fixes the zooming and adds a test to fix this. 

Fix ConciseDateFormatter offset during zoom

---

setupext.py

Change to `-Werror` to catch all warnings during build on mac machines.

MNT: Turn all macosx warnings into errors while building

---

lib/matplotlib/backends/backend_qt.py

On most platforms, windows have their own icons that are displayed in conjunction with windows. On macOS, icons are used differently. Individual windows should not have an icon unless they are associated with a file. On the other hand, processes ("Apps") have icons that can be set.
@greglucas suggested applying these fixes within derivations of FigureManagerBase. FigureManagerBase should only be instantiated when Matplotlib is responsible for running the GUI and its event loop. In this case, it makes sense for Matplotlib to control the App icon. (see https://github.com/matplotlib/matplotlib/pull/14930#issuecomment-980795349) …

Set macOS icon when using Qt backend

---

doc/users/explain/event_handling.rst
src/_macosx.m

The flagsChanged event handles single presses of modifier keys, so we need to send the corresponding string to our key press handlers from within that routine. Modifier + second key is handled within the KeyUp/KeyDown routines already, so leave those alone.
Taking the example from issue #20486
```python
def on_key(event):
print('you pressed', event.key, event.xdata, event.ydata)
def on_key_release(event):
print('you released', event.key, event.xdata, event.ydata)
fig.canvas.mpl_connect('key_press_event', on_key)
fig.canvas.mpl_connect('key_release_event', on_key_release)
plt.show()
```
this adds the single modifier key presses back in. Before this, the (modifier + key) "cmd+a" would show up, but there wasn't a single "cmd" (modifier) …

MNT: Add modifier key press handling to macosx backend

---

src/_macosx.m

Both because we don't need an ObjC specific API here, and because the
old code layout caused way too long lines for my editor... (Also,
switch-case should be marginally faster, not that it should matter at
all here.)

Replace NSDictionary by switch-case.

---

setup.py

Drop setuptools-scm requirement in wheels

---

lib/matplotlib/figure.py
lib/matplotlib/tests/test_figure.py

Closes #21839
The tighbbox  was not being properly calculated for figures with subfigures.  Even more embarrassing, the tightbbox test for this was nonsense.  

FIX: bbox subfigures

---

lib/matplotlib/collections.py
lib/matplotlib/tests/test_collections.py

Collections `set_offset` was coercing to float, which ruins any units we want to do.  Closes #21803
Needs tests....
Tested with 
```python
x = np.linspace(0, 10)
y = np.sin(x)
d = x * np.timedelta64(24, 'h') + np.datetime64('2021-11-29')
sc = plt.scatter(d, y) # showsw a plot
sc.set_offsets(list(zip(d, y)))
plt.show()
```

Fix collections coerce float

---

examples/text_labels_and_annotations/fancyarrow_demo.py

Fix [Annotation arrow style reference](https://matplotlib.org/3.5.0/gallery/text_labels_and_annotations/fancyarrow_demo.html#sphx-glr-gallery-text-labels-and-annotations-fancyarrow-demo-py):
Wrap long text to prevent overlapping. Wrap at every comma if it'll result in 4 lines or at every second comma for longer text.

DOC: Fix Annotation arrow style reference example

---

lib/matplotlib/tests/test_widgets.py

This moves a MultiCursor test from within a block of PolygonSelector tests to the end of the file, making an uniterrupted block of all the PolygonSelector tests.
Eventually I want to split widget tests into one file per widget, but will wait until a number of ongoing widget PRs are merged to do that.

Re-order a widget test function

---

doc/_static/mpl.css
examples/images_contours_and_fields/barb_demo.py
examples/images_contours_and_fields/contourf_demo.py
examples/images_contours_and_fields/image_demo.py
examples/lines_bars_and_markers/fill_betweenx_demo.py
examples/text_labels_and_annotations/accented_text.py
examples/text_labels_and_annotations/annotation_demo.py
examples/ticks/tick-formatters.py
examples/userdemo/demo_gridspec03.py

This overrides the sphinx-gallery CSS when multiple figures are output, so that they appear as a single column (except if they are already narrow enough to fit together.) In a few cases, it is possible to split up examples so that figures are not stuck together anyway, so do that where possible.
This generally looks better to me, even if a few figures get bunched up.

Display example figures in a single column

---

lib/mpl_toolkits/axes_grid1/inset_locator.py

We don't need to repeat the definition of `loc` again and again across
helper functions.

Shorten some inset_locator docstrings.

---

lib/matplotlib/backends/backend_ps.py

I missed this possibility in 26253f7a, but the idea is the same (see motivation there).
Move `format` to be the first parameter of `_print_ps` and friends, to
make the partialmethods easier to define.  Also rename `format` to `fmt`
while we're at it, to avoid shadowing the builtin `format` function.

Use partialmethod for better signatures in backend_ps.

---

lib/matplotlib/backends/backend_wx.py
lib/matplotlib/backends/backend_wxagg.py

This arg is unused since 744b7f8; we only need to clip when actually
blitting to the destination bitmap, not when first converting the agg
buffer to a bitmap.  Also make the conversion function directly take an
rgba buffer as input and rename it, as it isn't really agg-specific.
Also switch the construction of MemoryDC to directly pass in the
Selected bitmap as arg, rather that having a separate SelectObject call
(this is supported all the way back since wx3).

Remove unused bbox arg to _convert_agg_to_wx_bitmap.

---

doc/api/next_api_changes/removals/21395-AL.rst
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_agg.py
lib/matplotlib/backends/backend_cairo.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/backends/backend_svg.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/tests/test_figure.py

i.e. make print_figure() error on non-supported kwargs.
We can further remove the need to decorate each and every print_method
by instead doing the wrapping when fetching the method instead; this
wrapping is done in a _switching_canvas_and_get_print_method helper.

Expire _check_savefig_extra_args-related deprecations.

---

.github/workflows/clean_pr.yml
doc/users/next_whats_new/list_font_names.rst
lib/matplotlib/font_manager.py
lib/matplotlib/tests/test_font_manager.py
tutorials/text/text_props.py

Added list of available fonts. Changes in this PR allows the user to find a list of available fonts by running:
`matplotlib.font_manager.get_font_list()`. Edit: Fixes #21761.
**Comments**
- About get_font_list()
I added get_font_list() as a method in FontManager. However, for convenience, I also added it as global function. In this way, although the method itself belongs to FontManager (`matplotlib.font_manager.fontManager.get_font_list()`) , is easily accessible one level up at  `matplotlib.font_manager.get_font_list()`. 
- Test Units
Although I was considering the use of a fixture to extract all the fonts from scratch but ended up skipping it. …

Added get_font_names() to fontManager

---

doc/api/next_api_changes/deprecations/20839-EP.rst
doc/users/next_whats_new/rectangle_patch_rotation.rst
doc/users/next_whats_new/selector_improvement.rst
lib/matplotlib/axes/_axes.py
lib/matplotlib/patches.py
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

- Fix centre and square state of rectangle selector in interactive mode. These states were working only when creating the selector.
- Fix name coordinate handle: N and S were swapped
- Add method to add a default state
- Privatize state_modifier_keys
- Add `data_coordinates` state to define if the square ratio should be calculated in data or figure coordinates
- Add rotation of `RectangleSelector` and `EllipseSelector` taking into account aspect ratio of the axes and using the center of the shape as rotation center.
```python
from matplotlib.widgets import RectangleSelector
values = np.arange(0, 100)
ax.plot(values, values)
selector = RectangleSelector(ax, print, interactive=True, …
```

Fix centre and square state and add rotation for rectangle selector

---

lib/matplotlib/colorbar.py
lib/matplotlib/tests/baseline_images/test_colorbar/nonorm_colorbars.svg
lib/matplotlib/tests/test_colorbar.py

Closes #21870
This adds another special-case path for NoNorm and tweaks the contents of another.
These special-cases are required because NoNorm (like BoundaryNorm) has a
different return value than ever other Norm (it directly returns integers to
index into the LUT rather than [0, 1] that is later mapped into the LUT.
I added this as an SVG because getting the text right is a critical part of this and SVG will not suffer from our free-type issues.
(I went through a minor panic when I was not seeing ticklabels in the svg, but luckily that was a viewer (emacs) bug 😌 but I did have 15 minutes of thinking we had stopped outputting _any_ text on SVGs!  This may be (another) rsvg bug....)

FIX: colorbars with NoNorm

---

doc/users/prev_whats_new/whats_new_3.4.0.rst
doc/users/prev_whats_new/whats_new_3.5.0.rst

Sphinx embeds these verbatim, so if you link to `/foo`, then it will go to `matplotlib.org/foo`, which will pop up a redirect now. Using a relative link will go directly to `matplotlib.org/stable/foo`.
For example, on [this what's new entry](https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.5.0.html#image-interpolation-now-possible-at-rgba-stage), the image and the link after it should both point to the same place, but the former is at the toplevel while the latter is under `stable`.
- [n/a] API changes …

Make figure target links relative

---

doc/users/next_whats_new/polygon_vert_setter.rst
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

This allows one to set up a `PolygonSelector` programmatically without having to click, and is similar to already-implemented functionality in `RectangleSelector`.

Add a PolygonSelector.verts setter

---

doc/conf.py

This doubles the size of the PDF, and makes it impossible to upload to GitHub Pages.
In the future, I will make the images vectorized, but this requires work in sphinx-gallery or some rather large hacks.

Drop retina images when building PDF docs

---

lib/matplotlib/axes/_axes.py

closes #21669
Tested manually locally via:
```python
import unyt as un
un.matplotlib_support.enable()
x = un.unyt_array([1, 2], "cm")
y = un.unyt_array([3, 4], "kg")
yerr = un.unyt_array([0.1, 0.2], "kg")
ax.errorbar(x, y, yerr=(yerr, yerr))
plt.show()
```
We do not currently have _any_ tests of errorbar + units, in interest of getting 3.5.1 out with this fix and the colorbar fixes I move we merge this without a test and kick this particular technical debt can down the road as making sure we have good test coverage is in-scope for the NASA grant.

FIX: be more careful about coercing unit-full containers to ndarray

---

lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_axes.py

Fixes #21772 
1) Added elif blocks to center `xlabel` and `ylabel`
2) Added a test for the same in `test_axes.py`
3) Additionally, in `set_ylabel`, the `horizontalalignment` was getting reset instead of `verticalalignment`

FIX: Reset label of axis to center

---

lib/matplotlib/testing/decorators.py

In [importlib mode](https://docs.pytest.org/en/latest/explanation/pythonpath.html#import-modes), files are not added to `sys.modules`, so we cannot use that to find the file path.
Fixes #21885

Fix image testing decorator in pytest importlib mode

---

src/qhull_wrap.cpp

This is more of the same function pointer cast removal maintenance, see #21628.
Now the problem is that the qhull version function is declared as taking no arguments, but is supposed to be a `METH_NOARGS` function. `METH_NOARGS` functions should take two `PyObject*` arguments. This tiny patch fixes that.

MAINT Fix signature qhull version function 

---

lib/matplotlib/tests/test_backend_nbagg.py
setupext.py

Additionally, the test requires `nbconvert` to execute, and `ipykernel` as the Python 3 kernel.
A redo of #21665.
Fixes #21654

Include test notebooks in test package

---

lib/matplotlib/widgets.py

When `use_data_cooordinates == False`, the square is defined in display and not figure coordinates. This can be checked by opening a figure with an aspect ratio != 1, and seeing that the selector is still square (in display coordinates).

Fix use_data_coordinates docstring

---

lib/matplotlib/widgets.py

I think this is the correct way of doing the calculation, and avoids potential division by zero issues with the previous implementation.

Improve square state calculation in RectangleSelector

---

lib/matplotlib/backends/backend_macosx.py
src/_macosx.m

This issue is similar to #14850/#14927. The issue is not isolated to the macos backend. It also happens in Qt5 (at least, possibly others).
Turns out Qt5 broke setWindowIcon. It seems like it is similar to this bug report: https://bugreports.qt.io/browse/QTBUG-55932. It fails silently, you request an icon change and nothing happens on macOS.
I have doubts this will be fixed without some pretty large Qt5 changes. Apple's API doesn't support .svg files. It does support a wide variety of other graphics, including vector graphics: pdf, and postscript, for instance. But Qt's API only supports .svg vector graphics.
We can work around this with png's, etc., but we already have a far superior .pdf logo. Apple users have come to expect high-quality vector graphics on their Retina displays. We …

Set Dock icon on the macosx backend

---

.github/workflows/pr_welcome.yml

The first-interaction GitHub Action doesn't appear to support adding labels and is broken with that config option.
See for example, [the error in this build](https://github.com/matplotlib/matplotlib/runs/4479637445?check_suite_focus=true)
I also silenced some linting by indenting the file consistently.
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow …

Drop labelling from PR welcome action

---

lib/matplotlib/font_manager.py

We already require Py>=3.7.  Even alternative Python implementations
(pyodide, perhaps?) implementations of Python which may not support
fork()ing can likely support register_at_fork (the registered callback
is simply never called in that case).

Update comment re: register_at_fork.

---

lib/matplotlib/axes/_base.py
lib/matplotlib/gridspec.py

Remove outdated comment in `AxesBase.__getstate__` (we don't cache the
renderer on it anymore).
Remove unnecessary `SubplotSpec.__getstate__` (it has become unnecessary
now that SubplotSpec doesn't hold onto layoutbox/poslayoutbox anymore.)

Small `__getstate__` cleanups.

---

lib/matplotlib/tests/test_animation.py

The writer classes themselves have already been removed in Py3.5, but
the tests were kept.

Remove tests for avconv animation writers.

---

doc/missing-references.json
lib/matplotlib/backend_bases.py

Slightly cleanup RendererBase docs.

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/mpl_toolkits/mplot3d/axes3d.py

The API of _request_autoscale_view() was originally modelled to
match the one of autoscale_view() -- hence the scalex/scaley/scalez
kwargs -- but just taking an axis name (or "all") as single arg makes
generalization to 3D easier.
(In bxp(), the autoscale request does not need to be protected by
checking whether the autoscale state is on, as autoscale_view is a noop
for non-autoscaling axises.)

Make _request_autoscale_view more generalizable to 3D.

---

lib/matplotlib/widgets.py

Since https://github.com/matplotlib/matplotlib/pull/21945 is moving to using display coordinates internally, clarify the coordinates used in public facing API properties of `RectangleSelector`.

Clarify coordinates for RectangleSelector properties

---

doc/api/animation_api.rst
lib/matplotlib/animation.py

Some docs of AbstractMovieWriter are still written as if referring to
MovieWriter (which could be better named PipeMovieWriter, i.e. writers
that pipe frame data to a running subprocess).  This probably dates
back to when AbstractMovieWriter was not a thing yet.
Fix that.

Distinguish AbstractMovieWriter and MovieWriter in docs.

---

doc/api/next_api_changes/deprecations/21995-AL.rst
lib/matplotlib/animation.py

ImageMagickWriter previously did not support frame_format = "raw",
unlike ImageMagickFileWriter, because it did not normalize it to "rgba".
(To test this, start e.g. with the simple_anim.py example, set the
writer to an ImageMagickWriter (or ImageMagickFileWriter) and
additionally set writer.frame_format = "raw".)
Also deprecate the ``delay`` and ``output_args``  properties which can
directly be handled by ``_args``, but add an ``input_names`` property
which allows the different customization between ImageMagickWriter and
ImageMagickFileWriter.

Refactor common parts of ImageMagick{,File}Writer.

---

lib/matplotlib/__init__.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/tests/test_backend_pgf.py

... and add a private mechanism ($_MPLHIDEEXECUTABLES) to allow manually
testing both pdftocairo and ghostscript.  No automation for that, sorry.
Closes https://github.com/matplotlib/matplotlib/issues/11738.

Fix transparency when exporting to png via pgf backend.

---

lib/matplotlib/lines.py
lib/matplotlib/patches.py
lib/matplotlib/tests/test_legend.py

Dash offset and pattern are always used together, so just store them as
single attributes on lines and patches, instead of separate ones.

Store dash_pattern as single attribute, not two.

---

examples/animation/pause_resume.py
examples/event_handling/close_event.py
examples/event_handling/coords_demo.py
examples/event_handling/data_browser.py
examples/event_handling/figure_axes_enter_leave.py
examples/event_handling/ginput_manual_clabel_sgskip.py
examples/event_handling/image_slices_viewer.py
examples/event_handling/keypress_demo.py
examples/event_handling/lasso_demo.py
examples/event_handling/legend_picking.py
examples/event_handling/looking_glass.py
examples/event_handling/path_editor.py
examples/event_handling/pick_event_demo.py
examples/event_handling/pick_event_demo2.py
examples/event_handling/poly_editor.py
examples/event_handling/pong_sgskip.py
examples/event_handling/resample.py
examples/event_handling/timers.py
examples/event_handling/trifinder_event_demo.py
examples/event_handling/viewlims.py
examples/event_handling/zoom_window.py

Adds a note about lack of interactivity in static docs, and tweaks some examples to look better once the multi-column sphinx-gallery CSS is removed.

Small improvements to interactive examples

---

examples/axes_grid1/demo_colorbar_with_inset_locator.py

Merge comment into header text, small relayout/reordering.

Reword inset axes example.

---

lib/matplotlib/backend_bases.py

Note that the definition of "corresponding entry" is intentionally left
a bit vague, because the current behavior is in fact not consistent
between backends (#12021) and will need to be harmonized first.  The goal of this
change here is mostly to describe the order in which `master_transform`,
`all_transforms`, and `offsetTrans` are applied.

Clarify current behavior of draw_path_collection.

---

examples/lines_bars_and_markers/markevery_demo.py

- Reword description
- Remove non-distinguishing examples: We don't need three float
examples, (0.0, 0.1) is the same as 0.1.
- This makes for 9 cases, which can be laid out easily in a 3x3 grid,
so we don't need axes calculation and removal logic.

DOC: Simpify markevery demo

---

lib/matplotlib/figure.py
tutorials/intermediate/constrainedlayout_guide.py

Constrained layout is not really experimental any more, and we probably should not break it at this point....

DOC: remove experimental tag from CL

---

lib/matplotlib/scale.py

This is similar to the approach in b218e7c, which made sure that
SymmetricalLogTransform no longer returns masked arrays for nonmasked
inputs.

InvLogTransform should only return masked arrays for masked inputs.

---

lib/matplotlib/backends/backend_wx.py
lib/matplotlib/tests/test_backends_interactive.py

Locally (Arch standard packages), it otherwise fails with
File "/usr/lib/python3.10/site-packages/wx/core.py", line 1098, in _DC_DrawLineList
return self._DrawLineList(lines, pens, [])
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Likely the same root cause as https://github.com/matplotlib/matplotlib/pull/19395.

Fix rubberbanding on wx+py3.10.

---

doc/api/next_api_changes/deprecations/21981-AL.rst
lib/matplotlib/backends/backend_cairo.py
lib/matplotlib/backends/backend_gtk3cairo.py
lib/matplotlib/backends/backend_gtk4cairo.py
lib/matplotlib/backends/backend_qt5cairo.py
lib/matplotlib/backends/backend_qtcairo.py
lib/matplotlib/backends/backend_tkcairo.py
lib/matplotlib/backends/backend_wxcairo.py

Initialization of RendererCairo is duplicated across all
FigureCanvasCairo subclasses (and also in FigureCanvasCairo itself),
so just move it to a single place (in a delayed-init property to avoid
having to play around multiple inheritance and GUI frameworks).
RendererCairoGTK{3,4} simply add a set_context method, which can just as
well be defined on the base RendererCairo class (which after all already
defines set_ctx_from_surface for the benefit of {qt,tk,wx}cairo).

FigureCanvasCairo can init RendererCairo; kill RendererCairo subclasses.

---

lib/matplotlib/colors.py
lib/matplotlib/tests/test_colors.py
lib/matplotlib/tests/test_pickle.py

Closes #20755.
Also fix their qualname, which was missed in a00a909.

Fix picklability of make_norm_from_scale norms.

---

doc/api/next_api_changes/deprecations/21992-AL.rst
lib/matplotlib/backends/_backend_gtk.py
lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_gtk4.py

Looks like a few opportunities were missed in the conversion.
The Tk _rubberband_rect has to move to the canvas instance (consistently
with other backends), as hanging it off the temporary pseudo-toolbar
won't work.
Also fix the inheritance of ConfigureSubplotGTK, while we're at it, and
delete the private _get_canvas method, which is not used anywhere in the
codebase.

Use _make_classic_style_pseudo_toolbar more.

---

lib/matplotlib/backends/backend_cairo.py
lib/matplotlib/backends/backend_qtcairo.py

... to avoid having subclasses (qt) being forced to do so and handle
supercalls.

Initialize RendererCairo.{width,height} in constructor.

---

lib/matplotlib/legend_handler.py
lib/matplotlib/tests/test_legend.py

of polycollection (e.g. from fill_between) by updating original edge and face color too.
Closes #21966 
When updating the properties of the legend patch from the `PolyCollection` returned by `fill_between`, the HandlerPolyCollection failed to set the original edge and face colors so that  when later setting the alpha of the patch, its color was set to the default `C0`.    
This was fixed by updating the original edge and face colors too.
- [n/a] Documentation is sphinx and …

FIX: Prevent set_alpha from changing color of legend patch

---

lib/matplotlib/text.py

_get_layout_cache_key is only ever called from _get_layout, which always
passes a renderer arg which is never None (_get_layout calls
`renderer.get_text_width_height_descent` immediately after).  So we can
make the `renderer` arg required and not check for None.
Also, get_unitless_position() can be directly used instead of unpacking
it.

Slightly tighten the _get_layout_cache_key API.

---

doc/api/next_api_changes/behavior/21983-AL.rst
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/backends/backend_wxagg.py
lib/matplotlib/backends/backend_wxcairo.py

Remember that the wx backends have a slightly different init order
because the canvas cannot be instantiated *before* the containing window
(a "frame" in wx parlance), so previously different wx backends
implemented different frame subclasses so that each of them can
instantiate different canvas subclasses.
Instead of doing that (and having to assign them to the private
`_frame_class` attribute, which is a problem e.g. for third-party
backends such as mplcairo), directly pass the canvas class as a
parameter to FigureFrameWx.

Simplify canvas class control in FigureFrameWx.

---

lib/matplotlib/artist.py
lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_tightlayout.py

This PR is adapted from SciTools/cartopy#1956 following our discussion there.
This PR significantly improves the speed of `Axes.get_tightbbox()` for non-rectilinear axes (in particular, matplotlib's PolarAxes and cartopy's GeoAxes) by preventing unnecessary and expensive `get_window_extent()` computations. In the presence of complex, high-resolution artists, it can result in a **2x improvement** to the draw time when "tight layout" is enabled (since artists are effectively only drawn once instead of twice).
There may be a better way to implement this -- looking forward to everyone's thoughts.
To prevent unnecessary and expensive `get_window_extent()` computations, `Axes.get_tightbbox()` skips artists with `clip_on` set to True and whose `clip_box.extents` are equivalent to …

Significantly improve tight layout performance for cartopy axes

---

lib/matplotlib/backend_bases.py

This can be checked by grepping for flipy in the codebase.  See also https://github.com/matplotlib/matplotlib/pull/3806#issuecomment-63349983.

flipy only affects the drawing of texts, not of images.

---

doc/api/next_api_changes/behavior/21042-AL.rst
lib/matplotlib/__init__.py
lib/matplotlib/tests/test_rcparams.py

... so that `rcParams.update(<previously-copied-rcparams-instance>)`
doesn't emit DeprecationWarnings even if some entries are deprecated.
(See comment in tests.)
Supersedes #21015.
Closes #13118.  Closes #15781.  Closes #20249.

Make rcParams.copy() return a new RcParams instance.

---

lib/mpl_toolkits/mplot3d/axes3d.py

The box_aspect argument of the Axes3D constructor was missing a docstring. This adds it.

Fill in missing Axes3D box_aspect argument docstring

---

examples/lines_bars_and_markers/broken_barh.py

This pull request adds explanatory comments to the "broken" horizontal bar plot example. PR related to issue [#11654](https://github.com/matplotlib/matplotlib/issues/11654). 

Add explanatory comments to "broken" horizontal bar plot example

---

doc/api/next_api_changes/deprecations/22050-AL.rst
lib/matplotlib/backend_bases.py

Not to be confused with FigureManager.resize, which is implemented and
used by various subclasses.

Deprecate the noop, unused FigureCanvasBase.resize.

---

doc/api/next_api_changes/deprecations/22051-AL.rst
lib/matplotlib/backend_bases.py
lib/matplotlib/pyplot.py

All FigureCanvas subclasses that inherit from FigureCanvasBase already
have that attribute (which may be None), so the getattr is redundant.
In practice, it would be extremely difficult to write a FigureCanvasLike
class that does not inherit from FigureCanvasBase, but to be safe, go
through a deprecation period.

Make required_interactive_framework required on FigureCanvas.

---

lib/matplotlib/axes/_axes.py

Autopositioning only works if `rcParams["axes.titley"]` is `None` in addition
to `y` being `None` in the function call. If `rcParams["axes.titley"]` is set
to a float, there's no way to enforce autopositioning by function call
parameters (passing `y=None` has no effect in this case).
Link to current doc: https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.set_title.html
Example:
```python
plt.rcParams["axes.titley"] = 1.0
ax.xaxis.tick_top()
ax.set_title('Title', y=None)  # trying to override rcParams["axes.titley"] here
```
- [N/A] New features have an …

DOC: Clarify y parameter in Axes.set_title

---

lib/matplotlib/units.py

[Doc] Fix typo in `units.py` documentation example

---

lib/matplotlib/axes/_axes.py

Add a single-letter to fix spelling mistake ("loation" --> "location") in `set_title()`'s docstring.

Fix a small typo in docstring ("loation" --> "location")

---

lib/matplotlib/tests/test_ticker.py
lib/matplotlib/ticker.py

Fix regression in 3.4.0 introduced by b5fb685a61f0 (#18506).  
Closes #22065.

FIX: Remove trailing zeros from offset significand

---

doc/users/explain/interactive.rst
doc/users/explain/interactive_guide.rst
examples/color/colorbar_basics.py
examples/subplots_axes_and_figures/demo_tight_layout.py
examples/subplots_axes_and_figures/gridspec_nested.py
lib/matplotlib/figure.py
lib/matplotlib/gridspec.py
lib/matplotlib/image.py
lib/matplotlib/pyplot.py
tutorials/intermediate/arranging_axes.py
tutorials/intermediate/constrainedlayout_guide.py
tutorials/introductory/usage.py

`figure.Figure` actually looks not so nice in rendered docs and `Figure`
is just as clear; one can suppress the leading `figure` with a tilde but
it can also just be removed.

Remove unnecessary `.figure` qualifier in docs.

---

doc/api/next_api_changes/behavior/21026-DS.rst
doc/api/prev_api_changes/api_changes_3.5.0/behaviour.rst
doc/users/prev_whats_new/whats_new_1.4.rst
doc/users/prev_whats_new/whats_new_1.5.rst
tutorials/toolkits/mplot3d.py

There are some API listings in the 3D tutorial that are duplicates of the actual API documentation. Remove these so it's possible to do e.g. \`.Axes3D.plot\` in sphinx RST without getting a duplicate entry warning.

De-duplicate mplot3D API docs

---

lib/matplotlib/_enums.py

This was certainly overlooked in #18544, otherwise it would make no sense to derive `CapStyle` from `_AutoStringNameEnum`.

MNT: Set CapStyle member names automatically

---

doc/index.rst

The documentation's main page at https://matplotlib.org/stable/index.html (also https://matplotlib.org/devdocs/index.html) contains a link to the Matplotlib FAQ:
but the link points to the Python FAQ at https://docs.python.org/3/faq/index.html. I could reproduce this with a local build from `main`.
The raw `.rst` looks like this:
```rst
How-tos
^^^^^^^
- :doc:`Example gallery <gallery/index>`
- :doc:`Matplotlib FAQ <faq/index>`
```
It seems that the `<faq/index>` is incorrect, it should be `<users/faq/index>`, and there happen to be two intersphinx items by that path in Python:
```py
[
'faq-index std:label -1 faq/index.html#$ Python Frequently Asked Questions',
'faq/index std:doc -1 faq/index.html Python Frequently Asked Questions',
]
```
(I just decompressed the python.org intersphinx …

Fix reference to Matplotlib FAQ in doc/index.rst

---

lib/matplotlib/colorbar.py

Closes https://github.com/matplotlib/matplotlib/issues/22085
I guess I'm not 100% sure why the old code breaks, but this new code does not leak memory.
Tested via 
```python
from matplotlib import colorbar
import psutil
import gc
p = psutil.Process()
for i in range(20):
fig, ax = plt.subplots(1, 1)
ax.imshow(np.random.normal(size=(10,10)))
cax, _ = colorbar.make_axes(ax)
plt.pause(0.1)
plt.close(fig)
del fig
del cax
del ax
gc.collect()
print(p.memory_full_info().uss/1e6)
```
```
66.297856
60.760064
...
86.355968
87.8592
```
(OK, there actually appears to be a slow memory leak somewhere else, but it is _far_ slower than this memory leak...)
```
55.66464
51.818496
...
57.421824
57.63072
```

FIX: squash memory leak in colorbar

---

doc/users/next_whats_new/color_support_for_math_to_image.rst
lib/matplotlib/mathtext.py
lib/matplotlib/tests/test_mathtext.py

A `color` optional keyword argument was added to `math_to_image`. 
As `to_png` etc are deprecated and e.g. IPython relies on the Matplotlib rendering if no LaTeX compiler exists, it seems like a convenient feature to provide a `color` argument instead of modifying the rc parameters.

Added color keyword argument to math_to_image

---

doc/api/next_api_changes/removals/22081-AL.rst
lib/matplotlib/colorbar.py
lib/matplotlib/figure.py

Expire colorbar-related deprecations.

---

examples/text_labels_and_annotations/watermark_text.py
lib/matplotlib/tests/test_figure.py
lib/matplotlib/tests/test_text.py
lib/matplotlib/text.py

xref https://github.com/matplotlib/matplotlib/issues/19223. I think checking for `numbers.Real` is the right thing to do here?

Validate text rotation in setter

---

doc/api/prev_api_changes/api_changes_3.5.0/behaviour.rst
examples/axes_grid1/demo_axes_divider.py
examples/axes_grid1/make_room_for_ylabel_using_axesgrid.py
lib/mpl_toolkits/axes_grid1/axes_divider.py

`append_axes` is a more general API which is basically just as
ergonomic, and avoids exposing the slightly unusual feature of
axes_grid having indices increasing towards the top for vertical
stacks (contrary to gridspec which goes towards the bottom), and hence
`new_vertical(append_start={True,False})` behaving in the opposite
direction as one may naively expect.
Given that `new_horizontal` and `new_vertical` would basically stay as
helpers, it seems overkill to deprecate them, but perhaps we can at
least hide them from the docs (`:meta private:`).  Also promote
`axes_class` to be a plain normal parameter.

Very soft-deprecate AxesDivider.new_{horizontal,vertical}.

---

lib/matplotlib/axes/_base.py

Fix a small typo in `reset_position` docstring: "the a" -> "the".

Fix a small typo

---

lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_gtk4.py
lib/matplotlib/backends/backend_wx.py

Closes #22012
Not clear how to add a test for it.
Also, should this be documented with a "what's new"? Seems quite marginal...
(I couldn't figure out how the macosx-version worked, and do not have a mac to test it...)

Right-aligned status text in backends

---

lib/matplotlib/transforms.py

The following test script shows a ~3x speedup.
```python
import math, numpy as np
mtx = np.array([[.1, .2, .3], [.4, .5, .6], [0, 0, 1]])
theta = np.pi / 4
def rotate(mtx, theta):
a = math.cos(theta)
b = math.sin(theta)
rotate_mtx = np.array([[a, -b, 0.0], [b, a, 0.0], [0.0, 0.0, 1.0]],
float)
return np.dot(rotate_mtx, mtx)
def rfast(mtx, theta):
a = math.cos(theta)
b = math.sin(theta)
(xx, xy, x0), (yx, yy, y0), _ = mtx.tolist()
mtx[0, 0] = a * xx - b * yx
mtx[0, 1] = a * xy - b * yy
mtx[0, 2] = a * x0 - b * y0
mtx[1, 0] = b * xx + a * yx
mtx[1, 1] = b * xy + a * yy
mtx[1, 2] = b * x0 + a * y0
return mtx
%timeit rotate(mtx, theta)
%timeit rfast(mtx, theta)
```

Micro-optimize rotation transform.

---

doc/devel/contributing.rst
lib/matplotlib/_api/deprecation.py
lib/matplotlib/axis.py
lib/matplotlib/backend_bases.py
lib/matplotlib/backend_tools.py
lib/matplotlib/collections.py
lib/matplotlib/dates.py
lib/matplotlib/mathtext.py
lib/matplotlib/spines.py
lib/matplotlib/tests/test_api.py
lib/matplotlib/ticker.py

There are 90 deprecations currently, for 38 of which alternatives are given in the deprecation warning. These alternatives are not included, however, in the documentation.  
The first commit enables inclusion of alternatives along with links in the documentation and the second commit adds links to the documentation for the existing alternatives if they refer to another function or class.
Documentation: ![grafik](https://user-images.githubusercontent.com/19879328/147122069-17decf72-a5d6-470f-a62c-a214f129d6ac.png)
Documentation: ![grafik](https://user-images.githubusercontent.com/19879328/147122274-1321e178-6b03-41fd-b1a2-fed0b43bfeee.png)
Include alternatives to deprecations in the documentation
- add `alternative` and `addendum` to the documentation by including
them in the second …

DOC: Include alternatives to deprecations in the documentation

---

lib/matplotlib/_constrained_layout.py
lib/matplotlib/figure.py

gca() order is only tracked by the toplevel axstack; _localaxes can be a
plain list, just tracking the order in which axes were added to the
figure.

Turn _localaxes into a plain list.

---

doc/users/next_whats_new/polygon_selector_box.rst
examples/widgets/polygon_selector_demo.py
lib/matplotlib/lines.py
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

This allows one to put a bounding box around a PolygonSelector, that can be used for resizing and moving (and eventually rotating) the selector points.
```python
from matplotlib.widgets import PolygonSelector
sel = PolygonSelector(ax, lambda *args, **kwargs: None, draw_box=True)
plt.show()
```
https://user-images.githubusercontent.com/6197628/144757647-ca03dba5-2ab4-4812-a9dd-e80b294b286e.mov

Add option of bounding box for PolygonSelector

---

lib/matplotlib/patches.py
lib/matplotlib/tests/test_patches.py

This is pulled out of https://github.com/matplotlib/matplotlib/pull/21945 because it's a standalone feature, and I think it's worth the scrutiny of a separate PR.

Add corner coordinate helper methods to Ellipse/Rectangle

---

examples/style_sheets/style_sheets_reference.py

- Exclude internal styles (Closes #21838)
- Make style names a bit larger and bold for better readability
- Use a different curve than sin for the plot lines with colorcycle. - The sin curves have a lot of crossing which makes it hard to follow the colorcycle. - I've still one crossing section included to make it look a bit more interesting, but we could even remove that in case somebody thinks this is still too cluttered.

DOC: Update style sheet reference

---

src/_macosx.m

- The FigureCanvas init already errors out if self->view is NULL, and, more importanly, ObjC explicitly does allow calling methods ("sending messages") on NULL (they just return NULL/0 in that case).  Ditto for FigureManager and self->window.
- Also remove unnecessary NULLs at the end of PyObject_CallMethod calls (which are unneeded and in fact technically wrong).
- Use NSMakeRect more; declare variables closer to initialization.

Remove unnecessary null checks in macosx.m, and some more maintenance

---

lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_axes.py

There is no `add_text` method, use `add_artist` instead.
closes #22093

FIX: there is no add_text method, fallback to add_artist

---

lib/matplotlib/transforms.py

Similarly to what was recently done for rotate().  (skew is rather rarely used, but given that @timhoffm suggested this in https://github.com/matplotlib/matplotlib/pull/22108#pullrequestreview-845087314, I may as well do it too :-))
To address @timhoffm's other comment ("Does it still make sense to keep Affine2D._mtx as a numpy array if we only do element-wise operations?"): I'm quite convinced the whole transform stack would be faster if the transformation matrix was not a numpy array (because 3x3 is a size where the numpy's overhead is generally bigger than the gains from vectorization), but changing everything at once (even better would be to move things to C, but using plain C structs (or equivalently C++ objects) to store the coefficients) would be quite a big PR.  So I'm doing the …

Micro-optimize skew().

---

doc/api/next_api_changes/behavior/22063-SR.rst
lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_axes.py

Move the title above the offset text if present.  
**OLD:**  
**NEW:** 
Closes #22062.

FIX: Autoposition title when yaxis has offset

---

environment.yml
examples/mplot3d/polys3d.py
requirements/doc/doc-requirements.txt

See discussion at https://github.com/matplotlib/matplotlib/pull/22043#discussion_r774668335.

Drop dependency on scipy in the docs.

---

doc/api/next_api_changes/deprecations/22123-TH.rst
lib/matplotlib/axes/_base.py
lib/matplotlib/figure.py

This will align the API with the general `.Artist.get_window_extent` API.
All parameters were ignored anyway.
After the deprecation, we'll use `get_window_extent(renderer=None)`.

Deprecate accepting arbitrary parameters in some get_window_extent() methods

---

src/_macosx.m

This was missed in the review of #22109. Without this on a hidpi monitor there is a blank bar on the top of the figure, previously I was testing on a non hi-dpi monitor so apparently that wasn't a big enough canvas to create the blank bar).
Here is the method definition: https://developer.apple.com/documentation/foundation/1391329-nsmakerect

FIX: width/height were reversed in macosx rectangle creation

---

lib/matplotlib/backends/_backend_tk.py

As mentioned in the comments of #22028, the tooltips for the navigation toolbar buttons in the Tk backend overlap the right side of the buttons (probably DPI/resolution dependent), as the x-offset is hardcoded. This makes the right half of the buttons unresponsive, as the tooltip is continuously being shown and hidden. This PR always makes the tooltip appear directly to the right of its button.
- [N/A] …

Prevent tooltips from overlapping buttons in NavigationToolbar2Tk (fixes issue mentioned in #22028)

---

lib/matplotlib/backends/backend_qt.py

Closes #22131.
I'll refrain from writing a test for this because that would be quite cumbersome. One can manually test the correctness be deleting one of the `_large` icons. Then the plot window falls back to the low-res version of that icon.
It's also unlike to break again, because the comment should make future authors aware that we have to have the fall back for user icons.

Fix loading user-defined icons for Qt plot window

---

lib/matplotlib/backends/backend_wx.py

Previously, typing "o" and "p" on a wx window would result in both the
zoom and the pan button being pressed at the same time.  Fix that by
relying on the same strategy as all other backends.

Update both zoom/pan states on wx when triggering from keyboard.

---

doc/api/next_api_changes/deprecations/21965-AL.rst
examples/event_handling/lasso_demo.py
examples/shapes_and_collections/collections.py
examples/shapes_and_collections/ellipse_collection.py
examples/specialty_plots/mri_with_eeg.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/collections.py
lib/matplotlib/legend.py
lib/matplotlib/legend_handler.py
lib/matplotlib/quiver.py
lib/matplotlib/tests/test_artist.py
lib/matplotlib/tests/test_collections.py
tutorials/intermediate/autoscale.py

Note that most APIs *previously* already accepted *offset_transform* as
kwarg, due to the presence of the `set_offset_transform` setter.  Prefer
that name (shortening it to `offset_trf` for local variables).
Backcompat for the old `transOffset` name is kept in most places by
introducing a property alias.

Switch transOffset to offset_transform.

---

lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

Fix drawing animated artists changed in selector callback

---

lib/matplotlib/_constrained_layout.py
lib/matplotlib/tests/test_constrainedlayout.py

Closes #22143
If subgridspecs were identical, then their strings were identical, and the dictionary we had for the layoutgrids was being addressed with the same key twice.  Changed the key to a unique repr for the subgridspec.   

Fix cl subgridspec

---

lib/matplotlib/testing/widgets.py
lib/matplotlib/tests/test_widgets.py

Also define a generic noop function to use in the tests, which reduces more duplicated lines in the tests. Fixes https://github.com/matplotlib/matplotlib/issues/21774.

Use a fixture to get widget testing axes

---

lib/matplotlib/_mathtext.py
lib/matplotlib/_mathtext_data.py
lib/matplotlib/tests/test_mathtext.py

I set out to improve the test coverage of `mathtext` and related modules.
The method `c_over_c` only had support `\AA`. However, that is not used in any of the practical cases as the Unicode mapping is used instead. Hence, I removed `c_over_c`. There is of course a risk that there will be fonts used that do not have a Unicode mapping for it, but since `\AA` has a quite low code point (197), it seems unlikely that it will render any sensible maths anyway.
I also added support for `\aa` (the lower case version of `\AA`) which earlier gave an error.
Not sure if and where this should go in the documentation of the next version. Maybe not worth mention that `\aa` is now supported?
For tests, it primarily ended up in triggering exceptions.

Improved coverage of mathtext and removed unused code

---

.github/workflows/tests.yml

Just thought it would look better to use 3.10, rather than 3.10-dev.
(Also tried if the extra requirements have wheels now. Not yet.)

Removed dev from 3.10-version

---

doc/users/faq/howto_faq.rst
examples/ticks/ticks_too_many.py

Users _often_ get confused when they get too many ticks or those that are out of order, because we plot lists of strings as categoricals.  This PR seeks to at least have a FAQ entry to address that problem and encourage them to convert to numbers of some sort.

DOC: explain too many ticks

---

src/_macosx.m

Only check for "python" case insensitive to match either Python or pythonw.
From the linked issue, the reproducer is to start a `pythonw` terminal, which freezes interactivity on main, but works with this patch.
```python
plt.ion()
plt.figure()
plt.plot([1], 'ko')    # plot a point
```
Closes #8400

FIX: macosx check case-insensitive app name

---

lib/matplotlib/axes/_axes.py

This PR fixes a small typo in the `axhline` docstring: "across the axis" → "across the Axes".
It now matches the corresponding  `axvline` [docstring](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/axes/_axes.py#L746).
- [N/A] Documentation is sphinx and …

Fix typo in `axhline` docstring

---

doc/api/next_api_changes/behavior/22013-AL.rst
lib/matplotlib/backends/backend_wx.py

The previous approach manually positioned the toolbar to have it at the
bottom of the window, but this can in fact be achieved just with
style=wx.TB_BOTTOM.
Removing manual sizing of the toolbar also fixes a bug previously
present on Windows, whereby a `set_size_inches` reducing the size of the
canvas would *not* reduce the window width, likely because it was forced
to its max value by the toolbar's explicit size.

Use standard toolbar in wx.

---

doc/api/next_api_changes/deprecations/22098-AL.rst
lib/mpl_toolkits/axes_grid/parasite_axes.py
lib/mpl_toolkits/axes_grid1/axes_divider.py
lib/mpl_toolkits/axes_grid1/parasite_axes.py
lib/mpl_toolkits/axisartist/__init__.py
lib/mpl_toolkits/axisartist/axis_artist.py
lib/mpl_toolkits/axisartist/axislines.py
lib/mpl_toolkits/axisartist/parasite_axes.py
lib/mpl_toolkits/tests/test_axisartist_axislines.py

Expire axes_grid1/axisartist deprecations.

---

doc/api/next_api_changes/deprecations/22084-SS.rst
lib/mpl_toolkits/mplot3d/axes3d.py

Expose 3D plot zoom as a parameter, do input checking, clean up docstrings.

Clean up 3d plot box_aspect zooming

---

.circleci/config.yml

The git:// URL is not supported and causing the following error:
>   The unauthenticated git protocol on port 9418 is no longer supported.
> Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

DOC: Fix upstream URL for merge in CircleCI

---

src/_macosx.m

Backport PR #22179 on branch v3.5.x (FIX: macosx check case-insensitive app name)

---

doc/api/hatch_api.rst
doc/api/index.rst
doc/api/prev_api_changes/api_changes_3.5.0/behaviour.rst

We don't have much there, but it may eventually be expanded.

DOC: Add hatch API to reference

---

lib/matplotlib/_enums.py
lib/matplotlib/lines.py
lib/matplotlib/patches.py

- remove '(default)' from cap style demo as this is only true for Line2D
and the default rcParameters
- document default cap styles for Line2D and Patch in their cap style
setters
- document default cap style for GraphicsContextBase in the same way as
it's already done for joinstyle
Closes #21979. If this goes in I can do the same for join styles, see #18597 (just documenting the current state).

DOC: Document default cap styles

---

lib/matplotlib/_mathtext.py

Just adding a small helper function.

Factor out underline-thickness lookups in mathtext.

---

lib/matplotlib/backends/qt_editor/_formlayout.py

It looks like the merge of https://github.com/matplotlib/matplotlib/pull/18966 had an issue. #18965 is back. This fixes it.

PR: Fix merge of 18966

---

doc/api/next_api_changes/development/22205-ES.rst
doc/api/prev_api_changes/api_changes_3.2.0/development.rst
doc/api/prev_api_changes/api_changes_3.4.0/development.rst
doc/devel/dependencies.rst
doc/devel/min_dep_policy.rst
environment.yml
lib/matplotlib/__init__.py
lib/matplotlib/tests/test_axes.py
requirements/testing/minver.txt
setup.py

By [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html), the rollover to 1.18 occurred on July 26, but we missed it due to delays in 3.5. The rollover to 1.19 occurred on Dec 22.

Bump minimum NumPy to 1.19

---

doc/devel/gitwash/development_workflow.rst
doc/devel/gitwash/following_latest.rst
doc/devel/gitwash/maintainer_workflow.rst
doc/devel/gitwash/patching.rst
doc/devel/gitwash/set_up_fork.rst

See https://github.blog/2021-09-01-improving-git-protocol-security-github/
Today is a brownout day.
I removed the sentence that git:// is RO and https:// is RW as you soon
won't be able to use git://
Personally I use https:// as RO and ssh:// as RW, but I understand it
might not be convenient on windows.

DOC: git:// is deprecated.

---

lib/matplotlib/backends/qt_editor/figureoptions.py

With #18216, the order that artists are added to an Axes is their canonical order. The dialog should not be sorting them in some other manner.
Additionally, this fixes a bug in that `apply_callback` indexes back to the original list, which means that changes will be made to the *wrong* artist if sorting actually occurred. It also makes the legend almost entirely wrong as well.
See https://discourse.matplotlib.org/t/bug-on-re-generate-automatic-legend-of-matplotlib-figure-property/22511
- [n/a] API changes documented …

Stop sorting artists in Figure Options dialog

---

doc/api/axes_api.rst
lib/matplotlib/axes/_base.py

Closes #22094.
While `ArtistList` will vanish again in 3.7. Users can encounter it and thus should know what it is and how it is supposed to be used.

Document ArtistList

---

lib/matplotlib/lines.py
lib/matplotlib/patches.py

Document default join style in the same way as the default cap styles (see #22053).
This just documents the current behavior, which may or may not be changed in the future, see #18597.

DOC: Document default join style

---

.circleci/config.yml
.github/workflows/clean_pr.yml

The `v*-doc` backport branches build docs against the released version. This is not enforced in the CI, and PRs can be backported that have no effect (e.e.g, #21631).
This PR adds a check that `lib` files are not modified on backports, and also attempts to run CircleCI with the right version.
Also fixes the added-and-modified check which was incorrectly failing in #21799, as noted on gitter.

Enforce backport conditions on v*-doc branches

---

tutorials/intermediate/arranging_axes.py

Fix typo in `tutorials/intermediate/arranging_axes.py`

---

doc/api/index.rst
doc/api/layout_engine_api.rst
doc/api/next_api_changes/behavior/20426-JK.rst
doc/users/next_whats_new/layout_engine.rst
lib/matplotlib/_constrained_layout.py
lib/matplotlib/_tight_bbox.py
lib/matplotlib/backend_bases.py
lib/matplotlib/figure.py
lib/matplotlib/layout_engine.py
lib/matplotlib/tests/test_constrainedlayout.py
lib/matplotlib/tests/test_figure.py
lib/matplotlib/tests/test_tightlayout.py
tutorials/intermediate/constrainedlayout_guide.py

This is based on #20229 (constrained_layout is only called at draw time) and #19892 (encourage `layout='tight'` and `layout='constrained'`.  
This is a backwards compatible re-architecting of how we do layout; in particular 
```python
from my_layout_engine import my_favourite_layout
fig = plt.figure(layout=my_favourite_layout(option1=0.4, option2=0.7))
```
and then `my_favourite_layout.execute()` is called when the figure is drawn, and presumably moves axes around, or resizes figures, etc before the draw.  Two new layout engines are provided `constrained_layout_engine` and `tight_layout_engine` that are back-compatible so far as I can tell.

ENH: Layout engine

---

lib/matplotlib/figure.py

Figures always have a canvas attached (even if it's just a
FigureCanvasBase), and canvases always have a "manager" attribute (which
may be None).
Canvases also always have a "toolbar" attribute (which also may be
None).
Altogether this allows avoiding a couple of getattrs.

Remove some unnecessary getattrs.

---

lib/matplotlib/markers.py
lib/matplotlib/patches.py

There's an API inconsistency in the return values of  `get_capstyle` / `get_joinstyle`: For `Line2D`, `Collections` and `GraphicsContextBase` they return a string whereas for `MarkerStyle` and `Patch` they return an enum object, see also https://github.com/matplotlib/matplotlib/issues/21979#issuecomment-996235405.
[`_enums`](https://matplotlib.org/devdocs/api/_enums_api.html) was introduced in #18544 in mpl 3.4.0 without being mentioned in the [release notes](https://matplotlib.org/devdocs/api/prev_api_changes/api_changes_3.4.0.html). Its [documentation](https://matplotlib.org/devdocs/api/_enums_api.html) states:
> The classes in this module are used internally and serve to document these concepts formally.
From this I conclude that the enum should not leak out to the user, i.e. …

FIX: Return value instead of enum in get_capstyle/_joinstyle

---

lib/matplotlib/figure.py
lib/matplotlib/tests/test_colorbar.py

This PR turns the grid off for the colorbar axes created automatically (when user doesn't explicitly specify `cax`) by `fig.colorbar` or 'plt.colorbar'. This is needed since Auto-removal of grids by pcolor() and pcolormesh is deprecated.
```python
plt.rcParams['axes.grid'] = True  
ax.grid(False) 
im = ax.pcolormesh([0, 1], [0, 1], [[1]])
fig.colorbar(im) 
```
possibly closes #21723?
- [N/A] Documentation is sphinx …

turn off the grid after creating colorbar axes

---

.github/workflows/cibuildwheel.yml
doc/devel/coding_guide.rst

When I need to change the wheel building process, I need to push a copy to my fork's `main`, and then force push that away. But we can enable this on PRs by checking for a special label, reducing this extra work.
I used the "Run cibuildwheel" label, but if there's consensus for a better label name, we can use it. Then I'll actually create the label.

Run wheel builds on PRs when requested by a label

---

doc/api/next_api_changes/deprecations/22245-AL.rst
lib/matplotlib/backends/backend_agg.py
lib/matplotlib/backends/backend_macosx.py
lib/matplotlib/backends/backend_webagg_core.py

This makes it easier for to mock the agg backend (e.g., in mplcairo).
Note that this is anyways only a shorthand for calling a method
(`.clear()`) on the renderer itself, so just issuing that call is just
as simple, more explicit, and can be done even when one just has access
to the renderer and not to the canvas (an admittedly rather hypothetical
case).

Deprecate cleared kwarg to get_renderer.

---

doc/api/next_api_changes/deprecations/22021-AL.rst
lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_gtk4.py
lib/matplotlib/backends/backend_qt.py
lib/matplotlib/backends/backend_wx.py

i.e. with the same signature: with `canvas` as sole arg for the
old-style toolbars, with `toolmanager` as sole arg for the new ones.
Subclasses that explicitly support setting a parent widget keep that
support (except for gtk, which stashed that in the `.win` attribute but
never used it), but that argument is always optional now; the default is
the canvas' parent.
The goal is to later replace all _get_toolbar implementations by a
simple call (always with the same signature (dependent on the value of
rcParams["toolbar"])) to the correct class in the FigureManagerBase
constructor.

Ensure that all toolbar (old/new) subclasses can be init'ed consistently

---

src/_macosx.m

Reverts matplotlib/matplotlib#22195, as it breaks the wheel build, and we probably don't want to bump the minimum supported MacOSX (currently 10.9) in a bugfix release to fix this.

Revert "Backport PR #22179 on branch v3.5.x (FIX: macosx check case-insensitive app name)"

---

lib/matplotlib/tests/test_widgets.py

There aren't currently any tests for the `minspan{x,y}` arguments, so add some. There isn't any public API for checking if a given selector is currently 'active', so I had to use the private `tool._selection_completed` flag for that.

Add some tests for minspan{x,y} in RectangleSelector

---

.github/workflows/tests.yml
azure-pipelines.yml

GitHub Actions tests are already disabled for direct pushes, but not for the PRs directed at -doc branches. Azure is not disabled in any case. I'm not sure if I have that config right though.

Skip tests on the -doc branches

---

doc/conf.py

Fix version switcher now that json file is in place.
Note that changes to the json file itself will have to be merged, but the switcher is still not quite working, so lets make sure we understand that first.  

DOC: fix version switcher 

---

.circleci/config.yml
.github/workflows/clean_pr.yml

Merge pull request #21833 from QuLogic/clean-doc-backports
CI: Enforce backport conditions on v*-doc branches

Backport PR #21833: Enforce backport conditions on v*-doc branches

---

lib/matplotlib/backends/backend_qt.py

This was missed in the global fixing of enums for PyQt6 (now using
_enum everywhere).  To trigger, try to interactively save a figure but
input an invalid format, e.g. "foo.bar".

Fix Qt enum access.

---

lib/matplotlib/colorbar.py

In partial response to #21932: we deprecated `filled` from clashing with the ContourSet mappable, but none of the other mappables can change *filled*, so we have basically made the argument useless.  This PR simply deprecates the useless kwarg.  
The *filled* kwarg doesn't directly do anything and filling is completely controlled by the mappable.
OTOH, maybe we want to reinstate the ability of *filled* to fill ContourSets that are not filled - that is what #21932 would like?
Also deprecates `draw_all` as a public method.  This doesn't draw anything, and its is not used as public API:
- values
- boundaries
- solids 
- solids_patches 
- lines
- orientation
- cmap
- norm
- alpha
- outline

MNT: privatize colorbar attr

---

lib/matplotlib/colorbar.py

`colorbar.make_axes` (and `make_axes_gridspec`) are low-level enough
that it's not worth the complexity in docstring interpolation to split
out "main" parameters and "other" parameters, when the docstring of
the more commonly used `plt.colorbar` smashes them together.  (Also,
`pad` is not really much more low-level than `shrink` or `aspect`...)

Colorbar docstring reorg

---

doc/api/next_api_changes/behavior/22254-DS.rst
lib/matplotlib/collections.py
lib/matplotlib/tests/test_collections.py

For moderately sized QuadMeshes getting the cursor data is very slow - see https://github.com/matplotlib/matplotlib/issues/21917#issuecomment-1002201750. As such, disable by default for now, but allow users to manually enable it.
Fixes https://github.com/matplotlib/matplotlib/issues/22253
Fixes https://github.com/matplotlib/matplotlib/issues/21917

Disable QuadMesh cursor data by default

---

lib/matplotlib/backends/_backend_tk.py

This changes the parameters of the buttons in the Tk navigation toolbar to give them a flat look (with an outline showing when the mouse is over the button), similar to the Qt backend. For comparison:
Old:
New:

Give the Tk toolbar buttons a flat look

---

lib/matplotlib/font_manager.py

Simplify FontProperties.copy().

---

lib/matplotlib/axis.py

Expanded documentation of `Axis.set_ticks` as per discussion in #22262 to help protect future users from pitfalls when trying to add special/custom ticks.

Expanded documentation of Axis.set_ticks as per discussion in issue #22262

---

lib/matplotlib/colorbar.py
lib/matplotlib/tests/test_colorbar.py

This is to prepare to address #22233
Currently the user can set the colorbar locator and formatter by direct access to the properties `cb.formatter`, `cb.locator`, and `cb.minorlocator`.  However, they can also set `cb.ax.yaxis.set_major_locator` etc.  
This moves the attributes to properties with setters and getters.  The advantage of this is keeping the attributes in sync, but also we can track if the user set the locators via the properties.  If not, then we assume we can replace the locators and formatters with defaults. 
This does _not_ catch if the user set the locator and formatter using `cb.ax.yaxis.*`, so we may still have some things to figure out there.  

MNT: colorbar locators properties

---

lib/matplotlib/_constrained_layout.py
lib/matplotlib/backend_bases.py
lib/matplotlib/bezier.py
lib/matplotlib/testing/compare.py
lib/mpl_toolkits/axes_grid1/mpl_axes.py
tools/make_icons.py

Removed some unused code and unused variables.

Removed unused code and variables

---

lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_axes.py

and increase coverage for axes/_base.py
Main purpuse was to increase test coverage, but when I played around, I found the following:
```
>>> ax.secondary_xaxis('bottom')
File ~\miniconda3\lib\site-packages\IPython\core\formatters.py:707 in __call__
printer.pretty(obj)
File ~\miniconda3\lib\site-packages\IPython\lib\pretty.py:410 in pretty
return _repr_pprint(obj, self, cycle)
File ~\miniconda3\lib\site-packages\IPython\lib\pretty.py:778 in _repr_pprint
output = repr(obj)
File ~\matplotlib\lib\matplotlib\axes\_base.py:711 in __repr__
title = self.get_title(loc=k)
AttributeError: 'SecondaryAxis' object has no attribute 'get_title'
```
so I fixed that as well.
- [N/A] New features are documented, with examples if plot …

Fixed `repr` for `SecondaryAxis`

---

lib/matplotlib/axes/_base.py

I had something like `for i in range(n): plot(..., f"oC{i}")` which
works for n up to 10, but for greater values one gets "oC10" which is
not supported (which is reasonable, as some single-digit strings are
actually *marker* abbreviations); mentioning the full format string in
the error message ("Unrecognized character 0 in format string 'oC10'")
makes it clearer.

Display bad format string in error message.

---

lib/matplotlib/ticker.py

closes #22305
We were relying on an implicit import of a sub-module. 
We could test this by adding a sub-process test, but I am not sure that it is worth it.  That said, if someone wants a test on this I will add it.

FIX: ensure that used sub-packages are actually imported

---

doc/api/next_api_changes/deprecations/22097-AL.rst
lib/mpl_toolkits/axisartist/axislines.py

Standard ticks use _interval_contains_close (in Axis._update_ticks); do
the same in mpl_toolkits and deprecate the custom slops delta1, delta2
(if such knobs are really needed, we should try to have the same API in
the main library anyways).

In mpl_toolkits, use the same floating point slop as for standard ticks.

---

lib/matplotlib/backends/_backend_tk.py

Since 3.5, `NavigationToolbar2.set_cursor` is deprecated in favour of `FigureCanvasBase.set_cursor`. This adds the `set_cursor` method to `FigureCanvasTk` to make the cursor respond to move/zoom modes again, and removes it from `NavigationToolbar2Tk` as the parent `NavigationToolbar2.set_cursor` just calls `FigureCanvasBase.set_cursor` now.
I'm setting the cursor for the canvas specifically rather than for the canvas's master as before, as the cursor change should only ever affect the canvas (and not the toolbar, or any sibling widgets if dealing with an embedded plot).

Add set_cursor method to FigureCanvasTk

---

lib/matplotlib/axes/_axes.py

Fixes #21723.
See https://github.com/matplotlib/matplotlib/issues/21723#issuecomment-977288943
for a full desrciption of motivation and edge cases.

Don't warn on grid removal deprecation if grid is hidden

---

examples/mplot3d/wire3d_animation_sgskip.py
examples/pie_and_polar_charts/bar_of_pie.py
tutorials/intermediate/artists.py

There are some bits of the tutorials that should have been changed to remove reference to modifying the Axes sublists.
Also remove the use of the sublists in the 'bar of pie' example, and improve its colours.

Remove Axes sublists from docs

---

lib/matplotlib/backends/_backend_tk.py

Closes #20130. This makes the [`toolmanager_sgskip.py`](https://matplotlib.org/stable/gallery/user_interfaces/toolmanager_sgskip.html) example behave correctly in the Tk backend.

Respect `position` and `group` argument in Tk toolmanager add_toolitem

---

lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/tests/test_backend_tk.py

Currently, when using the Tk backend, Matplotlib sets the focus to the figure canvas upon its creation, as this is required to process keyboard events. As reported in #14081, this takes away the focus from other widgets when embedding a plot in a tkinter GUI, which creating a widget should never do (though the issue of other widgets being unable to take back the focus [was fixed in Tk 8.6.11](https://github.com/tcltk/tk/commit/b36fe5790a29cf78c58ab273cce93ab0604076ba)). Since a recent Python/Tk update, the focus doesn't get set to the canvas at all (#22028), though I cannot reproduce this outside of Matplotlib so can't tell what exactly caused this regression. Finally, the canvas has no visual indicator of having the focus, which makes it hard to get it to accept keyboard events again …

Fix keyboard event routing in Tk backend (fixes #13484, #14081, and #22028)

---

lib/matplotlib/backends/_backend_tk.py

This PR seeks to make the failure modes more consistent and manageable when blitting on the `TkAgg` backend. Draft for now because I don't think it is release critical and some feedback is needed on design choices.
The thread safety changes of #18565 interact a bit awkwardly with the memory safety changes of #14478, namely when `_tkagg.blit` raises, it pops directly out of the tkinter `mainloop` call and poisons the current instance of tkapp so that pumping the event loop always raises the `ValueError` forever. This isn't a big deal for bad values of `comp_rule` or `photoimage` since those are matplotlib's responsibilities, however as a user-facing API this prevents a client application from gracefully handling bad bboxes; they are basically fatal.
Why, if this is so bad, did nobody …

Implement a consistent behavior in TkAgg backend for bad blit bbox

---

requirements/testing/all.txt

About 24 hours ago (some time 2022-01-25) we started getting random failures on CI that look like:
```
__________________________________ test_fork ___________________________________
[gw0] linux -- Python 3.7.12 /opt/hostedtoolcache/Python/3.7.12/x64/bin/python
@pytest.mark.skipif(not hasattr(os, "register_at_fork"),
reason="Cannot register at_fork handlers")
def test_fork():
_model_handler(0)  # Make sure the font cache is filled.
ctx = multiprocessing.get_context("fork")
with ctx.Pool(processes=2) as pool:
>           pool.map(_model_handler, range(2))
lib/matplotlib/tests/test_font_manager.py:206: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/multiprocessing/pool.py:623: in __exit__ …
```

CI: ban coverage 6.3 that may be causing random hangs in fork test

---

lib/matplotlib/tests/test_contour.py

Added tests of a previously untested method.

Added tests for ContourSet.legend_elements

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_gtk4.py
lib/matplotlib/backends/backend_macosx.py
lib/matplotlib/backends/backend_nbagg.py
lib/matplotlib/backends/backend_qt.py
lib/matplotlib/backends/backend_webagg_core.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/tests/test_backend_bases.py

... by instantiating classes specified by _toolbar2_class or
_toolmanager_toolbar_class.  (Third-parties can still manually
instantiate their toolbars the old-fashioned way.)
Note that this would read a bit nicer if the toolbar classes were
defined before the manager classes, as this would allow _toolbar2_class
and _toolmanager_toolbar_class to be set using normal class attributes,
but moving large chunks of code around did not seem worth it.  I only
did so for the macosx backend, where the moved code is very little.
This means that all toolbars default to having the standard tools added,
not just the interactive ones.  See e.g. changes in
test_toolbar_zoompan: it is no longer necessary to explicitly register
all the tools (this actually now emits a duplicate tool warning).
This also …

Unify toolbar init across backends.

---

lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_axes.py

Manual cherry-picking as the original attempt to back-port had conflicts.
(I included all the additional tests as well as I am not sure if you merge 3.5.x and main at some stage or not and no harm having them there anyway,)

Backport PR #22283: Fixed `repr` for `SecondaryAxis`

---

doc/api/next_api_changes/behavior/19368-DS.rst
lib/matplotlib/image.py
lib/matplotlib/tests/test_image.py

Fixes https://github.com/matplotlib/matplotlib/issues/19276. This still needs:

Raise warning and downsample if data given to _image.resample is too large

---

lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

Previously when using `.verts` manually as a setter the box wasn't drawn.

Add box when setting `PolygonSelector.verts`

---

lib/matplotlib/dates.py
lib/matplotlib/tests/test_dates.py
lib/matplotlib/ticker.py

Edit:
There were inconsistent use/documentation of the `tz` parameters in `dates`, where the documentation stated string in some cases, although only `tzinfo` was working. Now, both approaches do work (and there is even an error if the `rcParams`-provided string is not a valid time zone). See below for discussion.
Original purpose: Added a bunch of tests for `dates.py` to increase coverage.
In addition: Found an issue with `datestr2num` where passing a list and a default `datetime` object gives an error in current `main`.
``` python
import datetime
import matplotlib.dates as mdates
dt = datetime.date(year=2022, month=1, day=10)
mdates.datestr2num(['2022-01', '2022-02'], default=dt)
```
results in
```
File "/tmp/ipykernel_117358/3002628473.py", line 1, in …
```

`dates` classes and functions support `tz` both as string and `tzinfo`

---

doc/api/next_api_changes/behavior/22229-TAC.rst
lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_axes.py

If you remove artists during iteration some of the artists will be skipped due
to the underlying list being mutated.

FIX: make safe to add / remove artists during ArtistList iteration

---

doc/api/next_api_changes/deprecations/22323-GL.rst
lib/matplotlib/cbook/__init__.py
lib/matplotlib/tests/test_text.py
lib/matplotlib/text.py

... and expand the cache size, while we're at it.
Actual deprecation of maxdict can be done in https://github.com/matplotlib/matplotlib/pull/22299.

Replace sole use of maxdict by lru_cache.

---

lib/matplotlib/_animation_data.py

The template for HTML export of an animation included an `</input>` tag, which is not valid HTML. This causes some HTML parsers to fail (specifically the one in [MathJax for Node](https://github.com/mathjax/MathJax-demos-node)).
Removed the `</input>` tag from the HTML template for the `animation.HTMLWriter.finish()` function.
- [N/A] ~~Has pytest style unit tests (and `pytest` passes).~~
- [N/A] ~~New features are documented, with examples if plot related.~~
- [N/A] ~~New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).~~
- [N/A] ~~API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).~~
- [N/A] ~~Documentation is sphinx and numpydoc compliant (the docs should …

Remove invalid `</input>` tag in `animation.HTMLWriter`

---

lib/matplotlib/transforms.py

Let TransformedPatchPath inherit most functionality from TransformedPath.

---

lib/matplotlib/figure.py

AxesStack is fairly independent from cbook.Stack: cbook.Stack handles
the forward/back/home buttons of the navbar, and therefore additionally
maintains a movable "cursor" in the stack; AxesStack, on the other hand,
needs to keep track both of "original" order and of "gca" order.
Rewriting it from scratch, and using "original" order as main storage
order (the "gca" stack being tracked using indices) shortens the
implementation and simplifies it (as there's no more need to figure out
what the super()calls do).

Rewrite AxesStack independently of cbook.Stack.

---

src/ft2font_wrapper.cpp

... by moving all the "adding-stuff-to-the-module-object" calls to a
single block.

Slightly shorten ft2font init.

---

src/qhull_wrap.cpp

Docstrings for _qhull.

---

lib/matplotlib/backends/backend_wx.py

Instead of reimplementing Destroy and fiddling around with supercalls
and IsBeingDeleted, move the toolbar disconnection to the _on_close
handler (which anyways already unregisters the figure from Gcf, so it's
definitely going to destroy the figure) and inherit Destroy from the
base class.

Simplify wxframe deletion.

---

lib/matplotlib/backends/backend_agg.py

We don't need to implement it twice, nor to mark the figure as stale by
temporarily switching its facecolor.

Reuse imsave()'s background-blending code in FigureCanvasAgg.print_jpeg.

---

doc/api/next_api_changes/deprecations/22025-AL.rst
lib/matplotlib/backends/backend_wx.py

They all have simple aliases under more standard names.
... and while we're at it, also deprecate the never-ever-used
RendererWx.offset_text_height, and switch the RendererWx deprecation to
use a standard decorator.

Deprecate various custom FigureFrameWx attributes/methods.

---

lib/matplotlib/mpl-data/kpsewhich.lua

If `tex` is not installed, then setting the program name to it will fail to find the 'program' in the current directory, and then be unable to find any TeX files.
Setting it to `latex` should be okay, since that's what we're running to create the `.dvi` in the first place.
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-do …

Use latex as the program name for kpsewhich

---

doc/api/next_api_changes/removals/22365-OG.rst
lib/matplotlib/animation.py

Removed deprecated `MovieWriter.cleanup`.
(Diff looks a bit weird...)

Remove deprecated `MovieWriter.cleanup`

---

lib/matplotlib/texmanager.py

- Don't use a nested format string (`fontcmd % tex`); simply pass
`fontcmd` and `tex` separately.
- Use named formats to make things easier to track.

Slightly refactor TeX source generation.

---

doc/api/next_api_changes/deprecations/22268-OG.rst
lib/matplotlib/ticker.py

Deprecating two functions that should be internal. Original issue (as discussed on gitter):
---
Digging into ticker.py and found the following concern: is_close_to_int uses a keyword argument atol (absolute tolerance?) comparing using absolute tolerance. However, it is also called from isdecade where the keyword argument rtol (relative tolerance?) is passed as absolut tolerance.
1) It seems like relative tolerance makes more sense for is_close_to_int
2) It seems inconsistent to pass rtol as atol (if now the keyword naming actually says something)
If I would change this, I guess the safest way is to provide an additional keyword argument to is_close_to_int, rtol=None, check if that is set and if so use that instead? For isdecade it is not so obvious as making it consistent will break the …

Deprecated is_decade and is_close_to_int

---

lib/matplotlib/axes/_axes.py

- Avoid having to copy() `x` and `y`, by not overwriting the original
`x` and `y` variables but instead storing the transformed values in
`trfx`/`trfy`.
- Directly construct lattice1 and lattice2 as flat arrays (they are
flattened at the end anyways), which allows using flat indices:
the `C is None` case, becomes a simple `bincount`, the `C is not None`
case can use a list-of-lists instead of an object array.
- Factor out the x/y marginals handling into a for-loop, which
additionally allows inlining coarse_bin.
- Make the factor of 2 between nx and ny clearer (in the `for zname...`
loop setup).  (See also https://github.com/matplotlib/matplotlib/issues/21349#issuecomment-943128653.)
- Construct marginals `verts` in a vectorized fashion.
Even if we decide to ultimately deprecate …

Refactor hexbin().

---

examples/subplots_axes_and_figures/ganged_plots.py

Issue #22369
Corrected a mistake in comments
Changed horizontal to vertical since hspace is used to denote the vertical space between the axis and not the horizontal space
-  Fixed a Typo

Corrected a mistake in comments (Issue #22369)

---

lib/matplotlib/tests/test_figure.py
lib/matplotlib/transforms.py

Currently, a deepcopy of a figure does not work because the transform tree does not get fully copied to the new state. I am not sure we actually need to override `__deepcopy__` on the transformNode, so just remove that and use the one that comes along with the class. I might be missing something obvious, but this does appear to work as I'd expect and not copy over any transform state to the new axes.
closes #21554

FIX: Remove the deepcopy override from transforms

---

doc/api/next_api_changes/behavior/21238-AL.rst
lib/matplotlib/artist.py
lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/cm.py
lib/matplotlib/colors.py
lib/matplotlib/container.py
lib/matplotlib/figure.py
lib/matplotlib/tests/test_cbook.py
lib/matplotlib/widgets.py

I chose not to emit warnings during a deprecation period as otherwise
the semantics of the `signals` parameter would again have to change at
the end of the deprecation period (from warning to raising), which would
be another backcompatibility break...
Closes #8839.

Raise when unknown signals are connected to CallbackRegistries.

---

doc/api/next_api_changes/deprecations/22345-JK.rst

#22345 was merged while our circle CI was failing, so bad formatting in the api change was missed.  Sorry about that!

TST: fix doc build

---

lib/matplotlib/axes/_base.py
lib/mpl_toolkits/mplot3d/axes3d.py

... and minor edits to 2D Axes.margins docs as well.

Tweak Axes3D docstrings that refer to 2D plotting methods.

---

lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/matplotlib/projections/polar.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_dates.py
lib/matplotlib/tests/test_image.py
lib/mpl_toolkits/mplot3d/axes3d.py

The change in set_top_view is necessary because super().set_xlim no
longer goes to 2D semantics (it's on the Axis.set_view_limits that one
would need to do a supercall), but in any case the old behavior was
actually more buggy because it would e.g. confuse data-limits sharex and
2D projection sharex; e.g.
`subplots(1, 2, sharex=True, subplot_kw={"projection": "3d"})`
was previously wrong.
As a side effect, also fixes `invert_yaxis`/`invert_zaxis` on 3d axises (#21369)
(because they just go to the base `Axis.set_inverted`).  Redoing the inheritance
hierarchy (#21424) would probably(?) still be nice, at least from a semantic PoV.
old bad 3d sharex:

Factor out common limits handling for x/y/z axes.

---

.github/ISSUE_TEMPLATE/documentation.yml

We don't need the code version installed by the user. If anything we need to
know the version of the docs the user is looking at.
Most of that is covered by the "Documentation Link" entry. It may point
to "stable" which could change contents in the future, but IMHO that's
not a practical problem.
Closes #22403.

Remove "Matplotlib version" from docs issue template

---

lib/matplotlib/ticker.py

See title
^ I did none of the above, I hope it's still ok.

DOC: imbalanced backticks.

---

lib/matplotlib/axes/_base.py

Trying to fix https://github.com/matplotlib/matplotlib/pull/21442#issuecomment-1033344534.

Fix ambiguous link targets in docs.

---

doc/conf.py
doc/devel/documenting_mpl.rst

As noted in https://github.com/scipy/scipy/issues/15545 the object inventory has moved. Though there's a redirect, it has paths like `reference/..` which doubles the `reference` in the URL.
Additionally, we don't need explicit entries in `reference_url` because sphinx-gallery will get them from the intersphinx config.

Update Scipy intersphinx inventory link

---

examples/misc/zorder_demo.py

Fix typo in doc. No actual code change.
- [N/A]  Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

fix method name in doc

---

lib/matplotlib/axis.py
lib/matplotlib/colors.py
lib/matplotlib/tests/test_colors.py

Partial fix for #22231.
This is clearly a logic error fix, see comment in code. Unfortunately, there is a much larger underlying problem, which is why this PR alone won't fix the problem and I cannot add tests.
The underlying problem lies in the arcane tick mechanism; roughly: via the `_LazyTickList`s we generate `majorTicks[0]`, which gets not parameters and thus resolves `rcParams['grid.alpha']` to a float. OTOH new ticks are created by copying properties from existing ticks. Even though this PR fixes the tick gridline initialization to respect a color alpha, `_copy_tick_props()` overwrites the gridline alpha afterwards.
I've spent a couple of hours digging this out and trying to find a proper fix. My time budget on this issue is exhausted. You may merge this PR as a partial fix if you …

Partial fix for grid alpha

---

doc/api/next_api_changes/deprecations/22422-AL.rst
lib/matplotlib/backends/backend_ps.py

It is tightly coupled to Matplotlib's choice of using psfrags to
implement ps+usetex (e.g., through the renderer.psfrag attribute) and
thus unlikely to be useful elsewhere (unlike the distiller functions,
which mplcairo reuses).  Making it private also allows getting rid of
now unused args (font_preamble and custom_preamble), supporting only
pathlib.Path args, and may perhaps later allow getting rid of paper
orientation handling too.

Deprecate backend_ps.convert_psfrags.

---

doc/api/next_api_changes/deprecations/22415-AL.rst
lib/matplotlib/axes/_base.py
lib/matplotlib/projections/polar.py
lib/mpl_toolkits/mplot3d/axes3d.py

This should help with later improving argument checking in the setters,
e.g. to make `set_xlim(3)` error out (requiring `set_xlim(left=3)`), as
that is likely a logic error.
Goes on top of #21442 to avoid a rebase.

Make emit and auto args of set_{x,y,z}lim keyword only.

---

lib/matplotlib/quiver.py

(I was trying to improve the docs re: u,v in x,y units as discussed during the call, but can't figure out what `scale_units=None` (the default) is supposed to mean.  Perhaps @efiring knows? :-))

Small cleanup to quiver.

---

lib/matplotlib/legend.py
lib/matplotlib/tests/test_legend.py

Replaces and closes #17488.
Co-authored-by: Clement Walter <clement0walter@gmail.com>

Clarify warning about labels with leading underscores.

---

lib/matplotlib/backends/_backend_gtk.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_gtk4.py

The gtk version checks are not the nicest, but sharing most of the setup
code between gtk3 and gtk4 still seems worthwhile?
(Note that on gtk3, it is explicitly OK to not bother to destroy the
vbox and toolbar, as gtk3 always destroys child widgets upon parent
destruction.)

Share FigureManager class between gtk3 and gtk4.

---

.github/workflows/tests.yml
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_colors.py

Test future numpy versions with Matplotlib to see if anything needs to be done in the future to address deprecations
or other pending changes.
* Currently will run once per week at 03:47 UTC on Saturdays.
* Only runs on Linux and for 3.9/3.10 currently as this is mostly just a smoke test for future issues.
* I think it will upload an issue on failure to notify the repo, but that is untested. Perhaps there is a better way here that someone knows about.
Link to a run on my branch (it should only run on matplotlib/matplotlib now)
https://github.com/greglucas/matplotlib/runs/4204821100?check_suite_focus=true
```bash
FAILED lib/matplotlib/tests/test_units.py::test_plot_masked_units[png] - matp...
= 1 failed, 8352 passed, 148 skipped, 13 xfailed, 4 xpassed in 537.93s (0:08:57) =
```
```bash …
```

TST: Add future dependency tests as a weekly CI job

---

.github/workflows/cibuildwheel.yml

In the previous change #22235, the condition to enable wheels with a label left out pushes, so wheels have not been building on `main` like they should have been. (and also tags, but we haven't made any.)
I'm adding the label now to ensure that things haven't broken in the interim.
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#buildi …

Re-enable cibuildwheel on push

---

lib/mpl_toolkits/axisartist/axis_artist.py
lib/mpl_toolkits/tests/test_axisartist_axis_artist.py

- Remove trivial private `_get_offset_radius` / `_set_offset_radius`
- Remove trivial private `_get_ref_angle` / `_set_ref_angle`
- Remove trivial private `_get_external_pad` / `_set_external_pad`
- Turn `_get_text_ref_angle` and `_get_offset_ref_angle` into properties

Remove some trivial private getters/setters in axisartist

---

lib/matplotlib/offsetbox.py
lib/matplotlib/tests/test_offsetbox.py

... so that we don't mutate dicts passed in by the user (we in fact pop
a key from arrowprops a bit later), and so that later mutations to the
dict from the user side don't affect the artist.

Copy arrowprops argument to FancyAnnotationBbox.

---

examples/specialty_plots/radar_chart.py

This PR fixes the gridlines for non-circular radar charts. This fixes #19981. Starting with version 3.3.0 the autoconversion to circular arcs in PolarAxes.PolarTransform forced all gridlines to be circular. This PR provides the necessary changes in the example for radar charts to produce gridlines of the same shape as the frame.
Many thanks to @anntzer for identifying the cause of the problem and distilling the proposed fix to a minimal solution.

Fix Radar Chart Gridlines for Non-Circular Charts

---

examples/specialty_plots/radar_chart.py
lib/matplotlib/projections/polar.py

A small block at the end of polar.py is described as not strictly
necessary, but is in fact used by the radar_chart example.  Perhaps a
unittest would be better, but for now, just note that this should not be
changed without manual checking.
RESOLUTION is unused; remove it.
followup to https://github.com/matplotlib/matplotlib/pull/22458

Small improvements related to radar_chart example.

---

lib/matplotlib/offsetbox.py

Inline _update_position_xybox into update_positions.  Avoid unpacking
x,y pairs where unnecessary.  Don't bother copying arrowprops, as we
don't actually modify it.  Reuse mutation scale for both patch and
arrow.  Clarify the doc for frameon (closes #17018).  Various small extra cleanups.
(re: #17018: I think the docs should only be added to AnnotationBbox, not to OffsetImage, which is only indirectly affected when associated with an AnnotationBbox.)

Cleanup AnnotationBbox.

---

lib/matplotlib/artist.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/matplotlib/collections.py
lib/matplotlib/image.py
lib/matplotlib/lines.py
lib/matplotlib/offsetbox.py
lib/matplotlib/patches.py
lib/matplotlib/projections/polar.py
lib/matplotlib/pyplot.py
lib/matplotlib/table.py

`plot([], [], foo=42)` previously emitted
```
'Line2D' object has no property 'foo'
```
which refers to the Matplotlib-specific concept of "properties".  It now
instead emits
```
Line2D.set() got an unexpected keyword argument 'foo'
```
which is modeled after the standard error message for unknown keyword
arguments.
(To maximize backcompat, the implementation goes through a new
_internal_update, which does *not* error when the same prop is passed
under different aliases.  This could be changed later, but is not the
goal of this PR.)
(This was triggered by https://discourse.matplotlib.org/t/line2d-object-has-no-property-line-error/22585)

Clarify error message for bad keyword arguments.

---

doc/api/next_api_changes/removals/22465-AL.rst
lib/mpl_toolkits/axes_grid1/axes_size.py

It's actually still used in get_vsize_hsize, but that is also currently
deprecated.  Also, there's a reasonable replacement.  The replacement
may be very slightly less efficient because it constructs deeply nested
Add objects, but given the low level of maintenance for axes_grid1,
decreasing the public API still seems a good idea.

Deprecate unused AddList.

---

lib/matplotlib/axes/_secondary_axes.py

The documentation dos not specify that the functions used to set the secondary axis must be able to accept numpy arrays as inputs. The relevant docstring has been edited for better clarity.
Resolves #22473

Clarify secondary_axis documentation

---

lib/matplotlib/backends/backend_agg.py

Rename _get_agg_font to _prepare_font, as it doesn't really do
anything agg-specific.  Fix its docstring.  Rename the *prop* arg to
*font_prop*, which makes its type clear in the context (and avoids
having to mention it in the docstring, thus keeping the docstring
single-line).
_get_agg_font/_prepare_font never returns None (e.g. we always call
`clear` on the font instance) so skip a None check in draw_text.
Skip a few temporary variables, which don't add much to legibility.

Small cleanup to font handling in agg.

---

lib/matplotlib/_mathtext.py

This changes the repr of mathtext lists from e.g.
```
[Hlist <70.39 41.78 0.00 0.00> [Hlist <0.00 0.00 0.00 0.00> ] [Hlist <37.62 40.09 0.00 0.00> `V` k1.11] [Hlist <32.76 41.78 0.00 0.00> ` ` `l` k10.34]]
```
to
```
Hlist<w=70.39 h=41.78 d=0.00 s=0.00>[Hlist<w=0.00 h=0.00 d=0.00 s=0.00>[], Hlist<w=37.62 h=40.09 d=0.00 s=0.00>[`V`, k1.11], Hlist<w=32.76 h=41.78 d=0.00 s=0.00>[` `, `l`, k10.34]]
```
These are internal structures that should only ever be seen when
debugging mathtext layout and can be quite deeply nested, so a somewhat
concise notation should is good (e.g., backticks for Chars, k for
Kerns), but still...
- indicate what each of the four numbers correspond to
(width/height/descent shift),
- move the brackets *after* the class name and metrics, which makes it
clearer what is …

Improve readability of mathtext internal structures.

---

lib/matplotlib/backends/qt_editor/_formlayout.py

adds _enum qualifier for QColorDialog.ShowAlphaChannel. Closes #22471.

---

lib/matplotlib/markers.py

As implied by the comment, it may not be worth having this as a separate
variable.

Remove _point_size_reduction.

---

.github/workflows/cibuildwheel.yml
doc/devel/dependencies.rst
doc/users/next_whats_new/min_macos_version.rst
src/_macosx.m

This is a draft to see if we can specify the macosx minimum version to be higher to fix wheel building. See https://github.com/matplotlib/matplotlib/pull/22179#issuecomment-1013696274 for details on why the wheels are currently failing.
As per https://github.com/matplotlib/matplotlib/pull/18128#issuecomment-667354695 and other discussion on that issue I've set the minimum version to 10.12.
Fixes https://github.com/matplotlib/matplotlib/issues/18066

Add minimum macosx version

---

lib/matplotlib/collections.py
lib/matplotlib/tests/test_collections.py

A scatter point at (0, 0) has offsets with 0s and `any(offsets)`
then gets evaluated to False. We still want to include this point
in the autoscaling if it is there.
Closes #22470

FIX: Include (0, 0) offsets in scatter autoscaling

---

doc/api/next_api_changes/behavior/22485-TH.rst
lib/matplotlib/image.py

- The current implementation was unhelpful / incorrect: It returned
the axes bounding box: Fixes #20294.
- The string should contain helpful information. I argue that the
figure coordinates of the image are not helpful most of the time.
Instead, giving the number of pixels seems more useful. Note that
__str__ does not need to be unique.
- Also move the definition to the base class and make it
type-agnostic so that it works correctly for all derived classes.

Change string representation of AxesImage

---

examples/text_labels_and_annotations/arrow_demo.py

The old version renders a bit small in the web docs (https://matplotlib.org/stable/gallery/text_labels_and_annotations/arrow_demo.html).
old:
new:

Tweak arrow demo size.

---

doc/api/next_api_changes/deprecations/22490-AL.rst
lib/matplotlib/transforms.py

`Affine2D()` is exactly identical (it's the implementation...), shorter
to type, and we have clearly standardized on using that; removing
identity() also avoids any possible confusion with IdentityTransform
(see also the removed docstring).

Deprecate unused, untested Affine2D.identity().

---

lib/matplotlib/mathtext.py

See a46dd3b which recently did the same thing to
_get_text_metrics_with_cache.
Also, the comment was outdated.

Don't key MathTextParser cache off a mutable FontProperties.

---

lib/matplotlib/mathtext.py

00ad9c4 replaced the entries for "bitmap", etc. to
MathtextBackendAgg/MathtextBackendPath (from the earlier
MathtextBackendBitmap, etc., which had been deprecated in 3.4), but the
intent was actually to remove these entries as well upon deprecation
expiration; e.g. in 3.5 `MathTextParser("bitmap").parse("foo")` raises a
DeprecationWarning.

Remove entries of MathTextParser._backend_mapping deprecated in 3.4.

---

tutorials/introductory/quick_start.py

cf. https://discourse.matplotlib.org/t/axis-labels-inverted-in-basic-usage-doc/22596
Also shrink figure slightly to not be larger than the HTML content width.

Fix units in quick start example

---

lib/matplotlib/backends/backend_webagg.py

Adds a keyword-only block kwarg to the show method on webagg (like all other backends)

FIX: make the show API on webagg consistent with others

---

lib/matplotlib/tests/test_patches.py
lib/matplotlib/tests/test_text.py

Some minor coverage improvements.

Increase coverage

---

doc/api/next_api_changes/removals/22486-OG.rst
lib/matplotlib/lines.py
lib/matplotlib/patches.py

Expired deprecations in lines and patches.
There are some more deprecations in patches, but I didn't really understand what should be kept and not.

Expire deprecations in lines and patches

---

lib/matplotlib/artist.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/mpl_toolkits/mplot3d/axes3d.py

They are attribute-like and using them as properties makes
the code a bit more readable.
Also, move them up next close to the definition of the related
`_axis_names`. And move the explanation on the used names from
`_axis_map` to `_axis_names`.
Edit:
Removed the `_axis_list` completely in favor of `_axis_map.values()`.

Turn _get_axis_map() into a property and remove _get_axis_list()

---

lib/matplotlib/tests/test_agg.py
src/py_converters.cpp

This occurs (rarely) when combining patheffects and mplot3d.
Closes #8650.  Closes #19563.  Closes #20991.

Support passing rgbaFace as an array to agg's draw_path.

---

lib/matplotlib/axes/_base.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/tests/test_cbook.py
lib/mpl_toolkits/mplot3d/axes3d.py

The API may be made public in the future, but right now the point is
only to make its internal use more ergonomic as it can be helpful in
some other internal places too (to be updated in a separate patch).

Simplify the internal API to connect picklable callbacks.

---

lib/matplotlib/contour.py

Closes #22532
Seemingly a leftover from name change/deprecation removal. I think it should go into 3.5.2.
Try the code in the issue to test it out.

Fix issue with manual clabel

---

lib/mpl_toolkits/mplot3d/axes3d.py
lib/mpl_toolkits/tests/test_mplot3d.py

Removed deprecated support for `shade=None`, will add release note.
Updated documentation and removal version for `auto_add_to_figure`. Should there be a release note for this? If so, not obvious in which category. (I assume that this should not go into 3.5 now?)
There are also:
https://github.com/matplotlib/matplotlib/blob/6eba0af3a8cec1b576cbdee9d20d85df47d1df2b/lib/mpl_toolkits/mplot3d/axes3d.py#L236-L241
Should the pending be removed? If so, removal in two versions or later? Release note?

Deprecation removal/updates in axes3d

---

doc/api/next_api_changes/deprecations/20071-AL.rst
examples/axes_grid1/make_room_for_ylabel_using_axesgrid.py
lib/mpl_toolkits/axes_grid1/axes_divider.py
lib/mpl_toolkits/axes_grid1/axes_size.py
lib/mpl_toolkits/tests/test_axes_grid1.py

Document behavior of auto_adjustable_area, and slightly modernize the
example.
Simplify its implementation: `Padded` is just size addition and
`GetExtentHelper` and `SizeFromFunc` can reasonably be fused into a
single class; none of them are used anywhere else, so just deprecate
them as public APIs.
Add a test.

Document, test, and simplify impl. of auto_adjustable_area.

---

lib/matplotlib/backends/backend_agg.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_gtk4.py
lib/matplotlib/backends/backend_macosx.py
lib/matplotlib/backends/backend_mixed.py
lib/matplotlib/backends/backend_nbagg.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/backends/backend_qt.py
lib/matplotlib/backends/backend_qt5agg.py
lib/matplotlib/backends/backend_qt5cairo.py
lib/matplotlib/backends/backend_qtagg.py
lib/matplotlib/backends/backend_tkagg.py
lib/matplotlib/backends/backend_webagg.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/backends/backend_wxagg.py
lib/matplotlib/backends/backend_wxcairo.py
lib/matplotlib/backends/qt_compat.py

Remove unused imports and local variables.
I split some import lines into two: one with the used and one with the unused. In this way, tools will warn if any previously used import becomes unused.

Cleanup unused imports and variables in backends

---

doc/api/next_api_changes/deprecations/22539-AL.rst
lib/matplotlib/tests/test_text.py
lib/matplotlib/text.py

get_rotation had been made a toplevel function a long time ago to be
used in TextWithDash, which has now been removed, so there isn't much
justification to have it separate.  Also, note that while the toplevel
get_rotation's implementation also supported string-form of floats (see
test_text.test_get_rotation_string), this was not consistent with the
docstring, and, more importantly, it was not possible to set a Text's
rotation to e.g. "15." because Text.set_rotation() would first reject
that anyways.
Also, we can directly normalize angles in Text.set_rotation, rather than
doing it again and again in Text.get_rotation.  Again, this made the old
inconsistency (on supporting string-form floats) clearer.

Deprecate toplevel mpl.text.get_rotation; normalize rotations early.

---

doc/api/next_api_changes/development/22550-AL.rst
doc/conf.py
requirements/doc/doc-requirements.txt

both are nearly two years old now (so OK wrt NEP29); the version bump
allows dropping some backcompat code.

Require sphinx>=3 & numpydoc>=1.0 for building docs.

---

doc/conf.py

- Autogen most of the checked list.
- Replace outdated pydata_sphinx_theme entry.
- matplotlib and its dependency pillow don't need to be explicitly
listed, as we already import matplotlib at the top of the file anyways
so if it's not importable, we won't even reach _check_dependencies.

Tweak dependency checking in doc/conf.py.

---

.github/workflows/cibuildwheel.yml

I had the wrong condition in #22375, so that they were still not triggered on push.
This time I've done a full check of the PR cycle on my fork, including labelling, re-opening, and merging.

Really fix wheel building on CI

---

lib/matplotlib/offsetbox.py

There's not much reason to drop draggability on pickling.
(This was a motivation for #22484.)

Use picklable callbacks for DraggableBase.

---

doc/api/next_api_changes/removals/22514-OG.rst
lib/matplotlib/__init__.py
lib/matplotlib/_api/deprecation.py
lib/matplotlib/cbook/__init__.py
lib/matplotlib/cbook/deprecation.py
lib/matplotlib/collections.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_backend_ps.py
lib/matplotlib/tests/test_colors.py
lib/matplotlib/tests/test_pyplot.py

Expire deprecations in cbook.deprecation. Will add a release note, but was a bit confused which things actually are deprecated.
cbook.MatplotlibDeprecationWarning and cbook.mplDeprecation are deprecated based on the earlier release note:
> The module matplotlib.cbook.deprecation is considered internal and will be removed from the public API. This also holds for deprecation-related re-imports in matplotlib.cbook, i.e. matplotlib.cbook.deprecated(), matplotlib.cbook.warn_deprecated(), matplotlib.cbook.MatplotlibDeprecationWarning and matplotlib.cbook.mplDeprecation.
If needed, external users may import MatplotlibDeprecationWarning directly from the matplotlib namespace. mplDeprecation is only an alias of MatplotlibDeprecationWarning and should not be used anymore.
However, it is possible to …

Expire deprecations in cbook.deprecation

---

lib/matplotlib/patches.py
lib/matplotlib/text.py

This PR fixes issue #22563 and changes the documentation of the `annotation_clip` parameter in the suggested way.
Because it is a minor change I did not check any boxes below.

fix doc for annotation_clip parameter

---

lib/matplotlib/axis.py
lib/matplotlib/container.py
lib/matplotlib/image.py
lib/matplotlib/streamplot.py
lib/matplotlib/testing/jpl_units/EpochConverter.py
lib/matplotlib/testing/jpl_units/UnitDblConverter.py
lib/matplotlib/tests/test_backend_bases.py
lib/matplotlib/tests/test_cbook.py
lib/matplotlib/tests/test_constrainedlayout.py
lib/matplotlib/tests/test_dates.py
lib/matplotlib/tests/test_figure.py
lib/matplotlib/tests/test_png.py

```
import matplotlib.foo as foo
```
is typically better (shorter) written as
```
from matplotlib import foo
```
Note that some of the existing ones are changed in #22148 so these should be (most) of the remaining ones.

MNT: Simplify imports

---

lib/matplotlib/legend.py
lib/matplotlib/tests/test_legend.py
lib/matplotlib/text.py

Closes #19121.
Text was not included in the Artists collected for a legend, so text created with a label had no legend entry. This PR issues warnings when:
1. Text with a label is found
2. a rectangular handle is substituted for a Patch that is not a Rectangle

Issues warnings for legend handles without handlers

---

lib/matplotlib/cbook/__init__.py
lib/matplotlib/tests/test_axes.py

Closes https://github.com/matplotlib/matplotlib/issues/22125 and #22330
This was an issue with handling 
```
x = pd.Series(x, dtype="Float32")  
```
in the logic of our plot argument parsing.
`x.values` returns a `FloatingArray`.  But it doesn't behave like a numpy array, in that `x.values[:, None]` returns a `ValueError: values must be a 1D array`.  I actually think this is a Pandas bug, but I'll leave that to someone with more pandas knowledge to inform them.  However, we can get around it by using `x.to_numpy()` which seems to work fine.  

Fix check 1d

---

lib/matplotlib/backend_bases.py

In https://github.com/matplotlib/matplotlib/issues/14498#issuecomment-650409733 it is mentioned that an all zero `dashes` hangs.
This PR introduces an exception for this case.
One may consider changing https://github.com/matplotlib/matplotlib/blob/c57c8781a7b9d8e5e9ece7c4cb8acee3b692f7f2/lib/matplotlib/backend_bases.py#L925 to use <= instead. It would be consistent with the error message and as far as I can tell, 0 dash values do not affect anything. But it may break stuff, I assume.
I did not manage to test this properly. Code that generates exceptions in the shell does not do it in the tests. Not sure why.

Require non-zero dash value

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

*dashes* is another Line2D only kwarg that should not be passed to all of the
artists created.
closes #22590

FIX: do not pass dashes to collections in errorbar

---

setup.py

As reported in https://github.com/matplotlib/matplotlib/issues/21660#issuecomment-1057440502

Fix backend in matplotlibrc if unset in mplsetup.cfg
