matplotlib/matplotlib

doc/users/explain/event_handling.rst
=> Fix doc typo.

src/_macosx.m
Also, explicitly checking for whether zoombutton/panbutton are non-null
is unnecessary, as objc explicitly defines sending a message to null as
a noop.  (See e.g. "Sending Messages to nil" in
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ObjectiveC/Chapters/ocObjectsClasses.html)
Also, they should never be nil anyways...
=> Factor out some macosx gil handling for py-method calls from callbacks.

.flake8, tutorials/introductory/usage.py
This fixes a few typos and missed commas in `usage.py`.  
Follow up of #21641
=> DOC: some minor fixes to the usage rewrite

src/_macosx.m
Backport PR #21663 on branch v3.5.x (Use standard subplot window in macosx backend)
=> Backport PR #21663 on branch v3.5.x (Use standard subplot window in macosx backend)

lib/matplotlib/text.py
=> Clarify Annotation arrowprops docs

.flake8, tutorials/introductory/usage.py
DOC: some minor fixes to the usage rewrite
Manual backport of #21794
=>  Manual backport of #21794

.flake8, tutorials/introductory/usage.py
DOC: some minor fixes to the usage rewrite
=> Manual Backport #21794 from jklymak/doc-basic-usage-fixes

src/_macosx.m
Because ObjC is based on C and not C++, we can just use designated
initializers (as suggested by the Python docs themselves).
Also inline various entries.
=> Shorten PyObjectType defs in macosx.m.

lib/matplotlib/_api/__init__.py, lib/matplotlib/_api/deprecation.py, lib/matplotlib/category.py
single colon are comments, and not admonitions.
=> DOC: Misc rst syntax fixes

.flake8, examples/ticks/date_formatters_locators.py
Add Date Tick Locators and Formatters example. Closes #17283.  
I noticed that https://github.com/matplotlib/matplotlib/blob/2ccc67f89dca929d1acfeed9ebeb3c11f1c3a52b/lib/matplotlib/dates.py#L982-L983 has no docstring and hence can't be referred to in the documentation (see `admonition:: References`; the same pertains to https://github.com/matplotlib/matplotlib/blob/2ccc67f89dca929d1acfeed9ebeb3c11f1c3a52b/lib/matplotlib/dates.py#L144).
<br><br>  
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow …
=> DOC: Add Date Tick Locators and Formatters example

examples/showcase/anatomy.py
I have taken the liberty of tweaking the colors and fonts of this venerable graphic to something more in keeping with the current style.  
=> DOC: update anatomy of figure

lib/matplotlib/widgets.py
I am working towards improving `RectangleSelector` to allow rotation past +/- 45 degrees. This PR cleans up some of the movement code to:
- Add a short docstring
- Add the `xy` and `xy_press` variables to make the code more readable
- Add a block of three lines at the top to determine whether to rotate, resize, or move
- Use these variables in the if/else blocks below, to make it clear what is going on in each block
=> Clean up RectangleSelector move code

lib/matplotlib/image.py
Both caches are used when converting images to rgba; the only difference
is that rgbacache was specifically used for PcolorImage (via
PcolorImage.make_image) whereas imcache covered the rest (via
_ImageBase._make_image).  One can instead use a single attribute (also
avoiding to duplicate their invalidation).
Also update the comment, and a bit the implementation, on
`__getstate__`: a long time ago imcache was (probably?) a non-picklable
custom subclass; now it is picklable but it still makes sense not to
pickle it.
=> Fold _rgbacache into _imcache.

lib/matplotlib/testing/widgets.py, lib/matplotlib/tests/test_widgets.py
Addresses part of https://github.com/matplotlib/matplotlib/issues/21774.
=> Add a click_and_move widget test helper

lib/matplotlib/backend_bases.py
This defines all the cycling behavior in a single block, rather than
spreading modulo operations all over.
=> Use cycling iterators in RendererBase.

doc/api/next_api_changes/deprecations/21982-AL.rst, lib/matplotlib/backends/backend_gtk3agg.py, lib/matplotlib/backends/backend_gtk4agg.py
This is consistent with other GUI backends: we can just directly use
FigureManagerGTK{3,4}.
=> Deprecate duplicated FigureManagerGTK{3,4}Agg classes.

doc/api/next_api_changes/removals/21980-CC.rst, lib/matplotlib/__init__.py
This is just a one-line change. Closes #21978
=> Removed loaded modules logging

lib/matplotlib/colors.py
Instead of special-casing lognorm to only autoscale from positive
values, perform autoscaling from values that map to finite transformed
values.  This ensures e.g. that make_norm_from_scale(LogitScale)
automatically does the right thing (autoscaling from values in [0, 1]).
This means that autoscale() and autoscale_None() are now slightly more
expensive (because the transform needs to be applied), so skip the call
to autoscale_None if not needed.  However, note that these should
typically only be called once per norm anyways, so hopefully this isn't
a bottleneck.
(Another idea would be to use `trf.inverse().transform([-np.inf, np.inf])`
as clipping bounds, but there are some tests using `x->x**2`
/ `x->sqrt(x)` as a test for FuncNorm, which 1. doesn't go all the way
to -inf, and 2. isn't …
=> Autoinfer norm bounds.

lib/matplotlib/backends/backend_wx.py
They are all private (OnClose lives on the private _HelpDialog class),
and they weren't following wx's TitleCaseIncludingFirstWord either
anyways.
=> PEP8ify wx callback names.

lib/matplotlib/cbook/__init__.py, lib/matplotlib/tests/test_cbook.py
=> BUG: fix handling of zero-dimensional arrays in cbook._reshape_2D

doc/devel/contributing.rst
(See other logging-output blocks, which are specified in the same way.)
=> Fix syntax highlighting in contrib guide.

lib/matplotlib/backends/backend_wx.py
Instead of swapping the bitmap attribute, it is enough to create a new
renderer with a different target and save that target to a file.
The isinstance(..., wx.Image) check is always false (we have a wx.Bitmap
instead), so skip it.
=> Simplify wx _print_image.

lib/matplotlib/backends/_backend_gtk.py, lib/matplotlib/backends/backend_gtk3.py, lib/matplotlib/backends/backend_gtk4.py
Mostly remove redundant imports, and share mpl_to_gtk_cursor between
gtk3 and gtk4.
=> Some gtk cleanups.

lib/matplotlib/dates.py
=> Added docstring to rrulewrapper class

lib/matplotlib/font_manager.py
They are not released yet (they came in in #21904) and don't need to be made public.
=> Keep FontEntry helpers private.

doc/conf.py
for sphinx.ext.linkcode
For decorated functions, get the source code of the decorated function instead of the decorator.
Closes #22039.
The source link of the example from the issue [MicrosecondLocator.set_data_interval](https://65710-1385122-gh.circle-artifacts.com/0/doc/build/html/api/dates_api.html#matplotlib.dates.MicrosecondLocator.set_data_interval) points to the [correct function](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/dates.py#L1693-L1696) now.
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst …
=> Get correct source code link for decorated functions

tutorials/text/pgf.py
Closes https://github.com/matplotlib/matplotlib/issues/15493 (https://github.com/matplotlib/matplotlib/issues/15493#issuecomment-999198824).
=> Document how to prevent TeX from treating `&`, `#` as special.

doc/users/resources/index.rst
Adds a new external resource: [workshop](https://github.com/stefmolin/python-data-viz-workshop) slides and notebooks for a data visualization in Python tutorial covering Matplotlib and HoloViews.
=> DOC: Add new tutorial to external resources.

lib/matplotlib/colorbar.py
Merge pull request #22089 from jklymak/fix-memleak-make-colorbar
FIX: squash memory leak in colorbar
=> Backport PR #22089: FIX: squash memory leak in colorbar

.flake8, doc/devel/documenting_mpl.rst, doc/index.rst, doc/users/getting_started/index.rst, tutorials/introductory/images.py, tutorials/introductory/pyplot.py, tutorials/introductory/quick_start.py
The new usage guide is not referenced many places, and performs poorly on google search.  Lets rename to something more evocative, and lets reference a few more places
=> DOC: rename usage tutorial to quick_start

lib/matplotlib/backends/backend_pdf.py, lib/matplotlib/contour.py, lib/matplotlib/figure.py, lib/matplotlib/mlab.py, lib/matplotlib/transforms.py, lib/mpl_toolkits/axisartist/axis_artist.py, lib/mpl_toolkits/axisartist/floating_axes.py
=> Simple style(ish) fixes.

examples/animation/double_pendulum.py, examples/mplot3d/lorenz_attractor.py
Slightly cleanup the lorenz_attractor example; also use Euler's method
for the double pendulum.  It is less accurate, but sufficient for
illustrative purposes (also, 1. the double pendulum is chaotic anyways
so even RK4 will end up quite far from the actual behavior, if one waits
for long enough, as can be checked by trying various integrators in
solve_ivp; 2. we're fine with using Euler's method for the also chaotic
lorenz_attractor).
The point is also to make fewer examples dependent on scipy.
=> Cleanup differential equations examples.

doc/api/mathtext_api.rst, doc/api/next_api_changes/removals/22107-OG.rst, doc/sphinxext/math_symbol_table.py, lib/matplotlib/_mathtext.py, lib/matplotlib/backends/_backend_pdf_ps.py, lib/matplotlib/backends/backend_cairo.py, lib/matplotlib/backends/backend_pdf.py, lib/matplotlib/backends/backend_ps.py, lib/matplotlib/backends/backend_svg.py, lib/matplotlib/mathtext.py, lib/matplotlib/tests/test_mathtext.py
Will add API-change information later on, but want to see how the tests work. (I have problem running things locally due to cyclic imports in `main`).
=> Expire mathttext-related deprecations

lib/matplotlib/backends/_backend_tk.py
Tk equivalent of #22135, closes #22131
=> Fix loading user-defined icons for Tk toolbar

lib/matplotlib/__init__.py, lib/matplotlib/axes/_axes.py, lib/matplotlib/quiver.py, lib/matplotlib/text.py, lib/matplotlib/widgets.py, tools/subset.py
Some things pointed out by LGTM. Redundant assignments, unused variables etc.
=> Removed unused variables etc.

lib/matplotlib/widgets.py
It's easier to track them in a single list.
Also init _selection_artist and _polygon_handles with empty arrays, as
there's no reason to pretend that they start with 0, 0.  On the other
hand, _xys does need to start as a non-empty array as the last point
gets updated as being the cursor position.
=> Jointly track x and y in PolygonSelector.

.circleci/config.yml, .github/workflows/clean_pr.yml
Merge pull request #21833 from QuLogic/clean-doc-backports
CI: Enforce backport conditions on v*-doc branches
=> Backport PR #21833: Enforce backport conditions on v*-doc branches

tutorials/text/annotations.py
Initially I just wanted to capitalize "matplotlib", but the wording was
a bit awkward too, so...
=> Trivial doc fix to annotations tutorial.

src/ft2font.cpp
This prints out human-readable error messages for failures.
As an example, `FT2Font("setup.py")` now raises
```
RuntimeError: In FT2Font: Can not load face (unknown file format; error code 0x2)
```
(sure, this specific error was special-cased before, but that's not the case for e.g. https://github.com/matplotlib/matplotlib/issues/22212, which is the motivation for this PR.)
=> Improve ft2font error reporting.

doc/_static/switcher.json, doc/conf.py, doc/devel/release_guide.rst, requirements/doc/doc-requirements.txt
This won't work because the json file needs to be hard coded versus relatively coded, and I'm also not sure we pull pydata-sphinx-theme 0.8   However, when we do, and when this gets merged into stable, it will allow a drop-down menu of version info.  See https://pydata-sphinx-theme.readthedocs.io/en/latest/
=> DOC: add dropdown

examples/ticks/tick_xlabel_top.py
Primarily describe how to do this for a single Axes (using `tick_params`).
Only mention the `rcParams` in a note. Globally changing `rcParams` is
usually not a good idea and should not be demonstrated. The whole
topic of `rcParams` (global, context, matplotlibrc) is too long to
be discussed here and not the focus of the example.
=> Modify example for x-axis tick labels at the top

lib/matplotlib/tests/test_text.py, lib/matplotlib/text.py
Instead of caching the text layout based on a bunch of properties, only
cache the computation of the text's metrics, which 1) should be the most
expensive part (everything else in _get_layout is relatively simple
iteration and arithmetic) and 2) depends on fewer implicit parameters.
In fact, the old cache key was insufficient in that it would conflate
usetex and non-usetex strings together, even though they have different
metrics; e.g. with the (extremely artificial) example
```python
figtext(.1, .5, "foo\nbar", size=32)  # (0)
figtext(.1, .5, "foo\nbar", usetex=True, size=32, c="r", alpha=.5)  # (1)
figtext(.3, .5, "foo\nbar", usetex=True, size=32, c="r", alpha=.5)  # (2)
```
the linespacing of the first usetex string (1) would be "wrong": it is
bigger that the one of the second usetex …
=> Rework/fix Text layout cache.

.pre-commit-config.yaml, doc/devel/development_setup.rst, environment.yml
Add a `.pre-commit-config.yaml` file for use with [pre-commit](https://pre-commit.com/) as well as add instructions for setting it up. When installed this should shorten the feedback loop for catching flake8 errors as it will run every time you attempt to `git commit` - it also is smart about running only on files staged for commit.
I find this to be very convenient and think it would be nice to include as an option for those who want to use it. But this is certainly something that would be up for discussion.
- [NA] Has pytest style unit tests (and `pytest` passes).
- I know it is because of pre-commit!
- [i hope.. ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
=> Add pre-commit config and dev instructions

lib/matplotlib/animation.py, lib/matplotlib/artist.py, lib/matplotlib/axes/_base.py, lib/matplotlib/axis.py, lib/matplotlib/backend_bases.py
=> DOC: More cleanup axes -> Axes

lib/mpl_toolkits/axisartist/floating_axes.py, lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
A few instances I missed in fb18d95.  At least grepping for delta
doesn't yield anything else.
=> More standardization of floating point slop in mpl_toolkits.

lib/matplotlib/backends/backend_template.py, lib/matplotlib/backends/backend_wx.py
... not in new_figure_manager.  Otherwise, unpickling a figure fails
with wx if no figure was created previously:
```
$ MPLBACKEND=wxagg python -c 'from pylab import *; plot(); import pickle; pickle.dump(plt.gcf(), open("/tmp/pkl", "wb"))'
$ MPLBACKEND=wxagg python -c 'import pickle; pickle.load(open("/tmp/pkl", "rb"))'
```
fails with "wx._core.PyNoAppError: The wx.App object must be created first!"
Because new_figure_manager calls new_figure_manager_given_figure (see
note in backend_template), it doesn't need to copy the instantiation.
Also note that backend_tk was already doing the init in
new_figure_manager_given_figure.
=> wx.App() should be init'ed in new_figure_manager_given_figure

lib/matplotlib/axis.py
This keeps the exact logic and only rewrites it in a more readable way.
Some more refactoring would be possible, that would clean up the logic
itself a bit more, but I'll leave that for some later time.
=> Cleanup Axis._translate_tick_kw

doc/api/next_api_changes/deprecations/21962-AL.rst, lib/matplotlib/backends/backend_pgf.py, lib/matplotlib/tests/test_backend_pgf.py
... and merge the now private get_preamble and get_fontspec together.
=> Privatize various internal APIs of backend_pgf.

examples/pyplots/text_commands.py, examples/text_labels_and_annotations/accented_text.py, lib/matplotlib/_mathtext.py, lib/matplotlib/backends/backend_pdf.py, lib/matplotlib/backends/backend_qt.py, lib/matplotlib/backends/qt_editor/_formlayout.py, lib/matplotlib/mpl-data/stylelib/classic.mplstyle, lib/matplotlib/projections/polar.py, lib/matplotlib/tests/test_backend_qt.py, lib/matplotlib/tests/test_ticker.py, lib/matplotlib/texmanager.py, lib/matplotlib/textpath.py, lib/matplotlib/ticker.py, tools/create_DejaVuDisplay.sh, tools/gh_api.py, tools/subset.py, tutorials/text/README.txt, tutorials/text/text_intro.py
See e.g. https://en.wikipedia.org/wiki/Unicode,
https://docs.python.org/3/howto/unicode.html.
Also associated minor doc cleanups.
=> Properly capitalize "Unicode".

.appveyor.yml, .circleci/config.yml
=> Pin dependencies to fix CI

src/_macosx.m, src/_tkmini.h
(github's diff doesn't show it, but these are indeed tab->spaces replacements)
=> Replace tabs with spaces in C code.

doc/conf.py, doc/users/explain/api_interfaces.rst, doc/users/explain/index.rst
This is an initial attempt to explain the different Matplotlib APIs.  Note the terminology here is suggested by @timhoffm "Axes", "pyplot" and I've suggested "Data" for the third pandas/xarray interface.  
- There are quite a few places in the docs where we could remove similar half explanations and reference this page (or what it turns into).
- The proposed terminology should be worked into the docs in quite a few places where "OO"/"pyplot" is discussed.  
=> DOC: attempt to explain the main different APIs

lib/matplotlib/widgets.py, lib/mpl_toolkits/mplot3d/axes3d.py
In line with https://github.com/matplotlib/matplotlib/issues/18726.
=> Axes capitalization in widgets and axes3d

README.rst
Hi, this is my first pull request in an open source project.
I know it's not fair to write this kind of description here, but it's just a way for you to leave a message.
Advice is welcome, thank you!
=> [DOC]: Removed a redundant 'The'

requirements/testing/all.txt
The newly released 6.3.1 is still sporadically failing from https://github.com/nedbat/coveragepy/issues/1310
=> Pin coverage to fix CI

lib/matplotlib/backends/backend_ps.py
Even though it is unlikely that the glob-remove will hit any
non-temporary files (because tmpfile will typically be, well, a
temporary file with a non-guessable filename), it still looks not so
nice and can easily be replaced by using controlled temporary filenames
and using TemporaryDirectory for auto-cleanup.
=> Avoid indiscriminate glob-remove in xpdf_distill.

lib/matplotlib/cm.py
=> Clarify note in get_cmap()

lib/matplotlib/pyplot.py
- Don't suggest using backends for customization (it's quite heavy
handed anyways, and we may soon have figure hooks to simplify that).
- Replace tight_layout/constrained_layout by layout engines (none of the
kwargs appear explicitly in the signature, but because figure() is
such a central entry point, it seems reasonable to be a bit more wordy
in the descriptions).
=> Update plt.figure() docstring.

lib/matplotlib/backends/backend_webagg.py, lib/matplotlib/backends/backend_webagg_core.py
Applying diff from @anntzer in https://github.com/matplotlib/ipympl/issues/426
I don't fully understand what's happening here but without this patch `ipympl` will break on main.
=> move `_toolbar_2` from webagg_core to webagg

doc/api/next_api_changes/deprecations/22421-AL.rst, lib/matplotlib/figure.py, lib/matplotlib/pyplot.py
This will allow tweaking the displayed signature of figure(), e.g.
hiding `facecolor` and `edgecolor` (likely rarely used) into `kwargs`
while making e.g. `layout` more prominent.
(I deemed that passing figsize or dpi positionally, although probably not a good idea, could *possibly* make sense, but that's almost certainly not the case for facecolor and edgecolor...)
=> Make most params to figure()/Figure() kwonly.

lib/matplotlib/_api/__init__.py, lib/matplotlib/axes/_base.py, lib/matplotlib/cbook/__init__.py, lib/matplotlib/collections.py, lib/matplotlib/lines.py, lib/matplotlib/patches.py, lib/matplotlib/text.py, lib/mpl_toolkits/mplot3d/axes3d.py
This is an API-related function and better placed in the recently added _api module.
=> Move cbook._define_aliases() to _api.define_aliases()

examples/axes_grid1/make_room_for_ylabel_using_axesgrid.py, examples/widgets/buttons.py, examples/widgets/check_buttons.py, examples/widgets/radio_buttons.py, examples/widgets/range_slider.py, examples/widgets/slider_demo.py, examples/widgets/slider_snap_demo.py
=> Un-pyplot some examples which were already explicitly referencing axes.

.flake8, setupext.py
=> Linewrap setupext to 79 character lines.

lib/matplotlib/_mathtext.py
- Turn _mathtext.ship into a plain function.
Making it a plain function with two nested mutually recursive functions,
instead of a singleton object with methods, makes ship() thread-safe at
no cost (otherwise, two threads calling ship() at the same time would
overwrite each other's instance variables).
- Remove unused recursion depth tracking in ship.
=> Turn _mathtext.ship into a plain function.

lib/matplotlib/font_manager.py
The various setters already set the None attributes to the rcParams
values; no need to do this twice in `__init__`.
Also inline the now-single-use _normalize_font_family, move the aliases
all to a single block, and prefer get_size to get_size_in_points.
=> Simplify FontProperties init.

doc/api/text_api.rst
Text/Annotation/OffsetFrom seems like a nicer order than the
alphabetical Annotation/OffsetFrom/Text.  Also, the toplevel
get_rotation probably doesn't even warrant an entry...
(this was the reason for #22539)
We could consider at some point using some degree of autodoc_member_order = "bysource" (https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_member_order) but that would be a much longer-term thing.  (Plus it would be nice to have e.g. automodules by source and autoclasses by alphabetical order, something that may be doable with member-order.)
=> Reorder text api docs.

lib/matplotlib/animation.py
Disable all animated artists after the animation has stopped. Also, remove the resize callback from the animation framework.
Closes #12528
=> FIX: Handle stopped animation figure resize

lib/matplotlib/backends/backend_wx.py
Closes #21798
The solution was given, but I thought it makes sense to get it into the code base as well... I can confirm from manual tests that it does solve the problem (as in that it doesn't happen, if it breaks anything else remains to see, but nothing I have seen yet).
=> Fix issue with unhandled Done exception

doc/api/next_api_changes/removals/22486-OG.rst, doc/users/next_whats_new/list_font_names.rst, lib/matplotlib/axes/_base.py, lib/matplotlib/collections.py, lib/matplotlib/figure.py, lib/matplotlib/layout_engine.py, lib/matplotlib/tests/test_constrainedlayout.py, lib/matplotlib/tests/test_widgets.py, lib/matplotlib/widgets.py, tutorials/introductory/quick_start.py
=> DOC: fix various typos

src/_tkagg.cpp
Closes https://github.com/matplotlib/matplotlib/issues/22378.
=> Fix loading tk on windows when current process has >1024 modules.

src/_macosx.m
This makes the images used for the buttons a template image which can be adjusted based on the system theme chosen by the user. The text in the toolbar when hovering an image already follows the theme changing from white/black appropriately.
Light mode:
Dark mode:
Closes #22605
=> ENH: Add dark/light mode theme to the buttons

lib/matplotlib/dates.py
=> Fix alternative suggestion in epoch2num() deprecation

lib/matplotlib/animation.py
Updated grammar to reflect more common usage of output vs outputted (see https://books.google.com/ngrams/graph?content=was+output%2Cwas+outputted&year_start=1800&year_end=2000&corpus=15&smoothing=3&direct_url=t1%3B%2Cwas%20output%3B%2Cc0%3B.t1%3B%2Cwas%20outputted%3B%2Cc0)
- …
=> Updated grammar to reflect more common usage of output vs outputted in animation.py

doc/api/next_api_changes/removals/22516-OG.rst, lib/matplotlib/backends/_backend_tk.py, lib/matplotlib/backends/backend_agg.py, lib/matplotlib/backends/backend_pdf.py, lib/matplotlib/backends/backend_pgf.py, lib/matplotlib/backends/backend_ps.py, lib/matplotlib/backends/backend_svg.py, lib/matplotlib/backends/backend_wx.py
~Will add release notes.~ Done!
=> Expire deprecations in backends

lib/matplotlib/axes/_base.py
These locations were missed in a merge causing test failures on main, so update them to the new name.
=> FIX: Change get_axis_map to axis_map now

lib/matplotlib/colorbar.py
This removes a deepcopy of the norm in Colorbar, instead updating
the vmin/vmax via the context manager and ignoring any
callback updates in the process.
xref: #22313
=> MNT: Use a context manager to change the norm in colorbar code

lib/matplotlib/backends/backend_svg.py
Test e.g. with
`figtext(.5, .5, "hello", rotation=45); savefig("test.svg")`
See discussion at
https://gitlab.com/inkscape/inkscape/-/issues/1058#note_296145942
=> Add space between individual transform components in svg output.

examples/widgets/polygon_selector_demo.py, examples/widgets/polygon_selector_simple.py, lib/matplotlib/widgets.py
=> Add example to polygon selector docstring showing how to set vertices programmatically

setupext.py
The comment was made outdated by ff2d796.
=> Remove reference to now-deleted reminder note.

lib/matplotlib/cbook/__init__.py, lib/matplotlib/tests/test_cbook.py
=> Raise on missing closing quotes in matplotlibrc

doc/conf.py
This closes https://github.com/matplotlib/matplotlib.github.com/issues/68 going forward, though it doesn't go back and fix 3.5 and 3.5.1
3.5.0 and 3.5.1 do not list the canonical links as `/stable/index.html` (etc) and google has started surfacing `/3.5.1/index.html` as the canonical and ignoring `/stable/index.html` as a duplicate.  We want `stable` to be the canonical, so this adds:
`<link rel="canonical" href="https://matplotlib.org/stable/index.html" />` to `index.html` or 
`<link rel="canonical" href="https://matplotlib.org/stable/gallery/frontpage/3D.html" />` to `gallery/frontpage/3D.html` etc.  
=> DOC: set canonical

doc/_static/switcher.json
This just makes the version switcher shorter...
Note skipping CI because there is nothing to test here.  
=> DOC: condense version switcher

lib/matplotlib/axes/_axes.py, lib/matplotlib/backend_tools.py, lib/matplotlib/path.py, lib/matplotlib/transforms.py
Fix a few cross references in the documentation. Plus one error (cross-reference not working, but should be `output_dims` I assume.)
=> Correct cross-references in documentation

doc/users/installing/index.rst
Resolves a problem identified by @ianhi in https://github.com/matplotlib/matplotlib/pull/22733#issuecomment-1085263102 where just installing with
```
python -m pip install --upgrade --index-url https://pypi.anaconda.org/scipy-wheels-nightly/simple matplotlib
```
will fail because of dependencies not being present on the package index. This is expected, but isn't very clear if people have never had to deal with this before, and they could still run into issues like what PR #22751 addresses.
This PR adds the `--pre` flag to allow for a dev release to take precedence over a stable release and the `--extra-index-url` of normal PyPI `https://pypi.org/simple` to allow for matplotlib's dependencies to still get installed normally.
https://github.com/matplotlib/matplotlib/pull/22733#issuecomment-1 …
=> DOC: Correct nightly wheels pip install command

doc/_static/mpl.css, doc/_templates/sidebar_announcement.html, doc/conf.py
This stick the a box in the location that the template uses for the ads (if you opt into that).
=> DOC: add job advert

examples/lines_bars_and_markers/csd_demo.py, lib/matplotlib/mlab.py
=> Improve mlab documentation (and example)

.github/workflows/tests.yml
The weekly dependency test was creating multiple issues when several
of the matrix jobs would fail. To fix that, we move the issue creation
script to a new job to only be triggered once. Additionally, add in the
job run link for quicker reference to the CI failure.
I did a quick test of this on my fork and it appears to be working as I'd expect.
Success (didn't run the upload issue): https://github.com/greglucas/matplotlib/actions/runs/2096657469
Failure (did run the upload issue with the correct run link in the logs): https://github.com/greglucas/matplotlib/actions/runs/2096667795
- [N/A] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 …
=> CI: Update weekly dependency test job

doc/users/explain/backends.rst, doc/users/explain/interactive.rst
Change links from github to the new docs page: https://matplotlib.org/ipympl/index.html
-  [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [we can hope ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
=> add ipympl website links

doc/api/next_api_changes/deprecations/22797-OG.rst, lib/matplotlib/backends/backend_pdf.py, lib/matplotlib/backends/backend_ps.py, lib/matplotlib/backends/backend_svg.py
These small local helper functions should probably be considered private.
~Will add API-change note once PR number is obtained.~ Done.
=> Deprecate functions in backends

tutorials/advanced/transforms_tutorial.py
I tried to clarify some of the transform tutorial prose based on https://github.com/matplotlib/matplotlib/issues/22688#issuecomment-1077791458
=> Doc tweak transform tutorial

doc/_static/mpl.css, doc/_templates/sidebar_announcement.html, doc/conf.py
Reverts matplotlib/matplotlib#22758
Take down the job posting.
=> Revert "DOC: add job advert"

lib/matplotlib/axes/_axes.py, lib/matplotlib/cbook/__init__.py, lib/matplotlib/dates.py, lib/matplotlib/testing/conftest.py, lib/matplotlib/tests/conftest.py, lib/matplotlib/tests/test_cbook.py, lib/matplotlib/units.py, requirements/testing/extra.txt
See https://stackoverflow.com/questions/13187778/convert-pandas-dataframe-to-numpy-array/54508052#54508052 for motivation.
Related to #16402
=> Improve pandas/xarray/... conversion

requirements/testing/all.txt
It is already a basic requirement:
https://github.com/matplotlib/matplotlib/blob/5bc10b121a7476d03f5c407150b85247c5d02c36/setup.py#L316
=> Remove python-dateutil as test requirement

lib/matplotlib/backends/backend_nbagg.py, lib/matplotlib/pyplot.py
We require Python 3.8, which is itself not compatible with IPython<7.3
due to https://github.com/ipython/ipython/issues/11590.
(You can also try manually to run older IPythons on Python 3.8 to check.)
As a side benefit, this avoids slightly confusing error messages in
backend_nbagg when IPython is installed but not ipykernel (we now always
depend on ipykernel for backend_nbagg, and ipykernel itself depends on
IPython but not the other way round).  (See e.g. the error message at #22880.)
=> Remove support for IPython<4.

doc/devel/triage.rst
Fixed typo in triage acknowledgment(doc/devel/triage.rst).
Issue: https://github.com/matplotlib/matplotlib/issues/22900
=> Fixed typo in triage acknowledgment

lib/matplotlib/pyplot.py
_IP_REGISTERED and _INSTALL_FIG_OBSERVER effectively encode a 3-state,
so just store that as a single _REPL_DISPLAYHOOK variable.  Also make
post_execute a globally available (private) function, so that it doesn't
need to be smuggled via _IP_REGISTERED to uninstall_repl_displayhook.
=> Clarify logic for repl displayhook.

doc/devel/coding_guide.rst
Adjusted pull request guidelines titles from PR to "pull request" to match the title in the section. 
Requested by @noatamir in #22932
Closes #22932
=> Adjusted wording in pull request guidelines

lib/matplotlib/_mathtext.py
pyparsing.Forward only needs to be used for mutually recursive mathtext
elements; others can be defined directly (using `=` instead of `<<=`).
This speeds up
```
MPLBACKEND=agg python -c 'import time; from pylab import *; from matplotlib.tests.test_mathtext import math_tests; fig = figure(figsize=(3, 10)); fig.text(0, 0, "\n".join(filter(None, math_tests)), size=6); start = time.perf_counter(); [fig.canvas.draw() for _ in range(10)]; print((time.perf_counter() - start) / 10)'
```
by around 6%.
(This was the first suggestion in https://github.com/matplotlib/matplotlib/issues/20821#issuecomment-951958910.)
=> Remove Forward definitions where possible.

lib/matplotlib/backend_bases.py, lib/matplotlib/backends/_backend_tk.py, lib/matplotlib/backends/backend_gtk3.py, lib/matplotlib/backends/backend_gtk4.py, lib/matplotlib/backends/backend_macosx.py, lib/matplotlib/backends/backend_nbagg.py, lib/matplotlib/backends/backend_qt.py, lib/matplotlib/backends/backend_template.py, lib/matplotlib/backends/backend_webagg.py, lib/matplotlib/backends/backend_wx.py
The `new_manager` classmethod may appear to belong more naturally to the
FigureManager class rather than the FigureCanvas class, but putting it
on FigureCanvas has multiple advantages:
- One may want to create managers at times where all one has is a
FigureCanvas instance, which may not even have a corresponding manager
(e.g. `subplot_tool`).
- A given FigureManager class can be associated with many different
FigureCanvas classes (indeed, FigureManagerQT can manage both
FigureCanvasQTAgg and FigureCanvasQTCairo and also the mplcairo Qt
canvas classes), whereas we don't have multiple FigureManager classes
for a given FigureCanvas class.
Still, put the *actual* logic in FigureManager.create_with_canvas and
access it via some indirection, as suggested by timhoffm (#22895).
See discussion at …
=> Standardize creation of FigureManager from a given FigureCanvas class.

doc/api/next_api_changes/removals/22952-TH.rst, lib/matplotlib/markers.py
by removing the deprecated public methods that could modify it.
=> Make MarkerStyle immutable

src/_macosx.m
As the title suggests. The script below should enter full-screen and keypress "f" should toggle back and forth.
```python
fig.canvas.manager.full_screen_toggle() # toggle fullscreen mode
plt.show()
```
- [N/A] Documentation …
=> ENH: Add full-screen toggle to the macosx backend

examples/text_labels_and_annotations/text_alignment.py, lib/matplotlib/text.py
=> Document text alignment

doc/users/installing/index.rst
Originally from an issue we resolved in [Gitter](https://gitter.im/matplotlib/matplotlib?at=62757238fa846847c951a836) as I was building from source. The docs currently don't specify which parts of Visual Studio that Windows users need when installing matplotlib from source. This PR adds this information to the docs, and also provides a link to a page from which VS can be downloaded.
=> Additional details on VS install on installation page

examples/text_labels_and_annotations/font_family_rc.py
Fixes a typo I introduced in #22891
=> Fix typo in font family

doc/sphinxext/redirect_from.py, lib/matplotlib/testing/__init__.py, lib/matplotlib/tests/test_animation.py, lib/matplotlib/tests/test_sphinxext.py, setupext.py, tools/run_examples.py
read_text/write_text default to the locale encoding, which may or may
not be utf8 (see #23019).  Fix these by making the encoding explicit or by using
bytes.
=> Fix some possible encoding issues for non-utf8 systems.

doc/api/next_api_changes/behavior/23031-AL.rst, lib/matplotlib/__init__.py, lib/matplotlib/mpl-data/matplotlibrc, lib/matplotlib/tests/test_rcparams.py, lib/matplotlib/tests/test_style.py, setup.py
I don't think other encodings really worked previously, so there's no
deprecation period (see #23026).  Closes #23026.
=> Specify that style files are utf-8.

.github/workflows/tests.yml
=> Fix missing section header for nightly builds

lib/matplotlib/tests/test_backends_interactive.py
This test should run on more than just PyQt5.
=> TST: fully parameterize test_lazy_linux_headless

setupext.py
run autogen.sh before configure freetype
https://github.com/matplotlib/matplotlib/issues/22754
run autogen.sh before configure freetype
=> Maybe run autogen as part of freetype install

lib/matplotlib/tests/test_backends_interactive.py
closes #23004
This is testing that we warn something is a bad idea and failing because it is indeed a bad idea.
=> TST: forgive more failures on pyside2 / pyside6 cross imports

lib/matplotlib/backends/backend_agg.py, lib/matplotlib/font_manager.py, lib/matplotlib/pyplot.py
With Python 3.7 and above, the threading module is always available.
https://docs.python.org/3.7/library/dummy_threading.html
=> MNT: Remove dummy_threading because threading is always available

src/_tkagg.cpp, src/_tkmini.h
Always load all three C functions both on Windows and on non-Windows,
for simplicity (the extra dlsym call should have negligible cost).
Followup to #23051.
=> Slightly simplify tcl/tk load in extension.

lib/matplotlib/backend_bases.py
_Backend.show() is used to generate a backend_module.show() method (by
wrapping _Backend.mainloop() with some boilerplate), which is then what
pyplot.show() calls.  Currently, it contains a cutout for webagg (wrt.
`block` support), but that's not really needed: the webagg backend
defines a show() function *directly*, without going through the mainloop
helper (this was the case even before the introduction of the _Backend
helper in 5141f80), and thus the `if get_backend() == "WebAgg"` check is
never reached when using webagg (try adding a print there and running
`MPLBACKEND=webagg python -c 'from pylab import *; plot(); show()'`).
So we can just remove the cutout.
=> Remove unneeded cutout for webagg in show().

doc/api/next_api_changes/removals/23093-GL.rst, doc/api/next_api_changes/removals/23XXX-GL.rst, lib/matplotlib/axes/_base.py, lib/matplotlib/axes/_subplots.py, lib/matplotlib/backend_bases.py, lib/matplotlib/cbook/__init__.py, lib/matplotlib/contour.py, lib/matplotlib/gridspec.py, lib/matplotlib/image.py, lib/matplotlib/offsetbox.py, lib/matplotlib/sphinxext/plot_directive.py, lib/matplotlib/testing/conftest.py, lib/matplotlib/tests/test_image.py, lib/matplotlib/widgets.py
This removes more 3.4 deprecations. I've put each removal into a separate commit, this seemed easier than opening a bunch of PRs, but I can do that if it would be easier to review.
=> MNT: Removing 3.4 deprecations

tutorials/toolkits/axes_grid.py
Fix a handful of typos. The references to methods could probably be `:meth:` or `:mod:` links, but I'm just making these changes in the GitHub UI so kept it simple. …
=> DOCS Fix typos

doc/users/resources/index.rst
Added entry to my (open access) book.
I did not test build (because it's quite simple addition).
=> Added my (open access) book

pytest.ini, tests.py
See https://github.com/matplotlib/matplotlib/pull/22627#issuecomment-1139469594.
=> Restore accidentally removed pytest.ini and tests.py.

lib/matplotlib/artist.py
https://github.com/matplotlib/matplotlib/issues/23050
=> Corrected docstring for artist.Artist.set_agg_filter

lib/matplotlib/backends/backend_webagg_core.py
- Directly reuse FigureCanvasAgg.get_renderer.  We don't need to init
_last_buff there as we can just use buff.copy() in get_diff_image()
(If we really care about reusing the same array whenever possible, we
could add a shape check before the removed copyto() and reuse the old
array if the shapes match, but I doubt it matters.)  Instead, init it
once to a non-valid shape in the constructor.
Note that the comments in the function were outdated since 78c182d.
- First creating `pixels` and then viewing it as `buff` is slighly
simpler than doing it the other way round.
The animation example in #19059 works for me.
=> Simplify webagg blitting.

lib/matplotlib/transforms.py
I hit the module page in a google search, but wanted the tutorial, but its not linked.  Added a link here. 
=> DOC: link the transforms tutorial from the module

doc/_static/switcher.json, doc/conf.py, requirements/doc/doc-requirements.txt
Closes #23193 by adding a URL field to the version switcher json file. This is [new in pydata-sphinx-theme](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/configuring.html#add-a-dropdown-to-switch-between-docs-versions)
=> DOC: Fix version switcher links to documentation

examples/widgets/radio_buttons.py
=> Fix invalid value in radio buttons example

environment.yml
I moved the `pikepdf` package under the pip instalation area, this is because this package is not available on windows throught `conda-forge`, so it was failing to create the conda environment, but it is present as a pip package.
Changes:
```yml
#
#
name: mpl-dev
channels:
- conda-forge
dependencies:
- cairocffi
- contourpy>=1.0.1
- cycler>=0.10.0
- fonttools>=4.22.0
- kiwisolver>=1.0.1
- numpy>=1.19
- pillow>=6.2
- pygobject
- pyparsing
- pyqt
- python-dateutil>=2.1
- setuptools
- setuptools_scm
- wxpython
- colorspacious
- graphviz
- ipython
- ipywidgets
- numpydoc>=0.8
- packaging
- pydata-sphinx-theme
- sphinx>=1.8.1,!=2.0.0
- sphinx-copybutton
- sphinx-gallery>=0.10
- sphinx-design
- pip
- pip:
- mpl-sphinx-theme
- sphinxcontrib-svg2pdfconverter
- pikepdf
- coverage
- flake8>=3.8
- …
```
=> Changing environment.yml for it to work on Windows

lib/matplotlib/_mathtext.py
=> In mathtext, replace manual caching (via `glyphd`) by lru_cache.

lib/matplotlib/backends/backend_pdf.py
Factor out a common method for URL annotation generation. Helps with #23152 and #23205
I do not generate the object directly for readability and possible extension.
=> Refactor URL handling in PDF backend

lib/matplotlib/backends/backend_pdf.py
This is similar to #23287; a quick timing shows that str.translate is ~4x faster despite the extra decode/encode pair (although once again it's unlikely to really matter).
=> Replace re.sub by the faster str.translate.

lib/matplotlib/backends/backend_mixed.py, lib/matplotlib/backends/backend_pdf.py, lib/matplotlib/backends/backend_pgf.py, lib/matplotlib/backends/backend_ps.py, lib/matplotlib/backends/backend_svg.py, lib/matplotlib/tests/test_figure.py, lib/matplotlib/text.py
Merge pull request #23278 from scottjones03/main
FIX: Remove internal use of get_dpi/set_dpi
(cherry picked from commit 047254dd0c5fcf602a19b245e3b14a38d1af1614)
=> Backport PR #23278: Remove internal use of get/set dpi

lib/matplotlib/axes/_axes.py, lib/matplotlib/tests/test_axes.py
Merge pull request #23333 from anntzer/en
Fix errorbar handling of nan.
(cherry picked from commit a2ad1f7a036be86b089faf1db4c9528d0d93f018)
Conflicts:
lib/matplotlib/axes/_axes.py
Other min -> manmin type changes on main
=> Backport PR #23333: Fix errorbar handling of nan.

lib/matplotlib/collections.py, lib/matplotlib/contour.py, lib/matplotlib/patches.py
A few loops are rewritten as list comprehensions (which are slightly faster).
=> MNT: Use list comprehension

lib/matplotlib/backend_bases.py, lib/matplotlib/backends/backend_gtk3.py, lib/matplotlib/backends/backend_gtk3agg.py, lib/matplotlib/backends/backend_gtk3cairo.py, lib/matplotlib/backends/backend_gtk4.py, lib/matplotlib/backends/backend_gtk4agg.py, lib/matplotlib/backends/backend_gtk4cairo.py, lib/matplotlib/backends/backend_macosx.py, lib/matplotlib/backends/backend_qt.py, lib/matplotlib/backends/backend_qtagg.py, lib/matplotlib/backends/backend_qtcairo.py, lib/matplotlib/backends/backend_wxcairo.py, src/_macosx.m
Instead of having e.g. FigureCanvasQT inherit from QWidget and then
FigureCanvasBase, which requires workarounds to handle the fact that
PySide.QWidget does not participate in cooperative multiple inheritance
(we work around that with _allow_super_init in qt, and manual super
calls in other toolkits), just swap the order of bases to
(FigureCanvasBase, QWidget) and make sure that FigureCanvasBase *does*
participate in cooperative multiple inheritance.
Also note the changes in FigureCanvasGTK{3,4}Agg.draw, where the new
inheritance order also makes more sense.
=> Simplify FigureCanvas multiple inheritance init by swapping bases order.

lib/matplotlib/animation.py, lib/matplotlib/mpl-data/matplotlibrc
- Don't hard-code/expose CREATE_NO_WINDOW on Windows (I'll aggressively
remove the global without a deprecation here), taking advantage of the
fact that the subprocess module now exposes the constant on Windows.
- Clarify the documentation in the rcParams for ffmpeg_path and
convert_path.  1) subprocess.Popen (which is really what we're using)
is not exactly just searching in the $PATH -- see the big warning to
that respect in the CPython docs.  2) One doesn't actually need to put
an absolute path for convert on Windows -- Matplotlib now handles this
transparently.
=> Small cleanups to animation.

examples/axes_grid1/demo_axes_rgb.py, examples/images_contours_and_fields/image_masked.py, examples/lines_bars_and_markers/fill_between_alpha.py, examples/pyplots/fig_axes_customize_simple.py, examples/subplots_axes_and_figures/align_labels_demo.py
Related to, but does not completely fix, #23372.
=> Use tick_params more often over tick iteration

lib/matplotlib/axes/_axes.py, lib/matplotlib/collections.py, lib/matplotlib/colorbar.py, lib/matplotlib/markers.py, lib/matplotlib/patches.py, lib/matplotlib/path.py, lib/matplotlib/tests/test_lines.py, lib/matplotlib/tests/test_path.py, lib/matplotlib/tests/test_transforms.py, lib/mpl_toolkits/axes_grid1/inset_locator.py
Instead of having to manually append an unused vertex that corresponds
to the CLOSEPATH code, add a _make_closed helper (private for now) which
does that for us.
=> Add a helper to generate closed paths.

examples/mplot3d/rotate_axes3d_sgskip.py, examples/mplot3d/wire3d_animation_sgskip.py
Also use double quotes in English text.
Also inline definition of Z array; it's not as the docstring of
generate() was helpful at all.
=> Link 3D animation examples to one another.

lib/matplotlib/tests/test_agg.py
Each one allocates over 2G, and are right next to each other, so when running in parallel, they can combine to OOM very easily. It would be nice to drop the large memory usage entirely, but at least we can remove 5 extra copies of it.
=> Combine chunk size tests into one

examples/showcase/stock_prices.py
The old name was when the example was still "bachelor's degree by
gender".
=> Update filename in example.

examples/axisartist/demo_floating_axes.py
This is the only full featured example with floating axes, so displaying
grids makes it easier to check that grids are indeed working.
=> Display grid in floating axes example.

lib/matplotlib/axes/_base.py, lib/matplotlib/tests/test_axes.py, lib/mpl_toolkits/tests/test_mplot3d.py
... by putting spaces where expected in normal style.  Also slightly
refactor the implementation.
=> Tweak Axes repr.

setup.py
=> Pin setuptools_scm on v3.5.x

src/_tkagg.cpp
Define `PyErr_SetFromWindowsErr` on Cygwin.  This function is defined on Windows, not Cygwin.
Closes #22997.
=> BLD: Define PyErr_SetFromWindowsErr on Cygwin.

.github/ISSUE_TEMPLATE/bug_report.yml
I can never remember whether to include triple-backquotes or not...
=> Clarify formatting of the code-for-reproduction field in bug reports.

doc/users/explain/backends.rst
As noted in 01c3ce1, all gtk backends depend strictly on pycairo, not on
cairocffi, so fix that.  Also slightly tweak the wording for other
backends.
=> Fix imprecise docs re: backend dependencies.

lib/matplotlib/backends/backend_cairo.py, lib/matplotlib/backends/backend_gtk3cairo.py, lib/matplotlib/backends/backend_gtk4cairo.py
... and inline _to_context, which is not used anywhere else and can thus
also be deleted at the same time.
=> Move the deprecated RendererGTK{3,4}Cairo to a single place.

lib/matplotlib/pyplot.py
We can actually just put the "exit" logic into an ExitStack callback.
If the return value is never `__enter__`'d via a "with" statement, it is
never `__exit__`'d either.
=> Simplify impl. of functions optionally used as context managers.

lib/matplotlib/sankey.py, lib/matplotlib/tests/test_sankey.py
=> Add tests for sankey and minor fixes

examples/axes_grid1/parasite_simple.py
- Use `legend(labelcolor=...)` instead of setting colors manually.
- Use `ax.legend` instead of `plt.legend`.
- Order imports.
=> Cleanup parasite_simple example.

lib/matplotlib/axes/_base.py, lib/matplotlib/figure.py, lib/mpl_toolkits/mplot3d/axes3d.py
Two small separate commits wrt. apply_aspect.
... not once per title.
... and relying on the fact that `apply_aspect()` and
`apply_aspect(None)` are equivalent.
=> apply_aspect cleanups

lib/mpl_toolkits/mplot3d/axis3d.py
Remove a bunch of redundant lookups and computations.
Restructured code a bit.
=> Cleanup axis3d.Axis.draw

lib/matplotlib/tri/triangulation.py, lib/matplotlib/tri/tricontour.py, lib/matplotlib/tri/triinterpolate.py, lib/matplotlib/tri/tripcolor.py
Some clean ups:
* Argument checking
* Simplify code
* Minor doc fix
=> Clean up code in tri

.github/workflows/cibuildwheel.yml, .github/workflows/tests.yml
See https://github.com/actions/virtual-environments/issues/6002
Should we do the same for Azure now as well?
=> Bump Ubuntu to 20.04 on GitHub Actions

doc/devel/development_setup.rst
#21611 
- [ X] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
=> Add conda env to setup instructions 

doc/devel/contributing.rst
This PR edits clarifies the reasons `Difficulty: Medium` and `Difficulty: Hard` labels might be added.
It is based on conversations arising in the new contributor meeting.
Feedback is welcome!
=> Editing "issues for new contributors"

lib/matplotlib/axes/_base.py
This PR documents the position paramter in apply_aspect()
Issue: https://github.com/matplotlib/matplotlib/issues/23583
- [ N/A] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ N/A] New features are documented, with examples if plot related.
- [ N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
=> [Doc]: Document the position parameter in apply_aspect()

doc/api/artist_api.rst, doc/users/installing/index.rst, examples/lines_bars_and_markers/linestyles.py, examples/ticks/centered_ticklabels.py, lib/matplotlib/mpl-data/matplotlibrc, lib/matplotlib/tri/triangulation.py, lib/matplotlib/tri/tricontour.py, setup.py, tutorials/intermediate/artists.py, tutorials/introductory/customizing.py
Spent some time looking through the documentation tags and sort out a few.
Closes #8187
Closes #22746
Closes #23220 
Adds examples to Artist methods
Use `tick_params` for a few more things.
=> Fix issues in examples, docs, and tutorials

doc/api/next_api_changes/behavior/00001-ABC.rst, doc/api/next_api_changes/development/00001-ABC.rst, doc/api/next_api_changes/removals/00001-ABC.rst, doc/users/next_whats_new/README.rst, doc/users/next_whats_new/font_fallback.rst, doc/users/next_whats_new/inset_axes_improvements.rst, doc/users/next_whats_new/windows_arm64.rst
Based on https://matplotlib.org/stable/devel/documenting_mpl.html#section-formatting section titles should be Upper lower. As I've been confused about what the standard is (not reading the above link and rather relying on the templates), I thought it made sense to change the templates.
I also changed the few next User What's New (skipped the API ones).
=> Change Title Case to Upper lower in templates

doc/users/explain/fonts.rst, tutorials/text/text_props.py
=> DOC: update and extend fonts explanation 

.github/workflows/nightlies.yml
As [`anaconda-client` is no longer supported with `pip`](https://github.com/Anaconda-Platform/anaconda-client/issues/618) then all modern installations must be done with `conda` or `mamba`. To make this process simple, use the [`mamba-org/provision-with-micromamba` GitHub Action](https://github.com/mamba-org/provision-with-micromamba) and have it only install `anaconda-client=1.10.0`. The GitHub Action will additionally print out the environment information which is useful for reproducibility and debugging information.
* The option `channels: main` is required to be used as anaconda-client is currently only maintained on the ["main" channel](https://anaconda.org/main/anaconda-client).
* The [default shell is also set to `bash -l {0}`](https://github.com/mamba-org/provision-with-micromamba/ …
=> CI: Use anaconda-client v1.10.0 for upload of nightlies

lib/matplotlib/tests/test_mathtext.py
Changed it to a working link. Also updated the comment above it, since they aren't all prefixed with `'mltt'` any more.
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) …
=> Fix broken link to MathML torture tests.

examples/lines_bars_and_markers/bar_colors.py
Adding a new bar plot example after https://github.com/matplotlib/matplotlib/pull/23525 to showcase the `color` and `label` arguments.
=> Add bar color demo.

azure-pipelines.yml
In the Azure config, the Ubuntu version is pinned to 18.04. However, the following warning is being raised in the Azure pipelines. 
```
##[warning]The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
```
The linked issue https://github.com/actions/runner-images/issues/6002 says that 18.04 will be unsupported on 12/1/22, and the first "brownout" where jobs will fail will happen `August 22, 12:00 UTC - August 22, 16:00 UTC`. IMO it's a poor approach to only have the warning up for 2 weeks before breaking tests, but best to get ahead of it at any rate. 
This PR updates most of the linux versions to `ubuntu-latest`, and pins the lowest python …
=> CI: Azure update from ubuntu-18.04 to ubuntu-latest and ubuntu-20.04

doc/api/afm_api.rst, doc/api/docstring_api.rst, doc/api/prev_api_changes/api_changes_0.91.0.rst, doc/api/tight_bbox_api.rst, doc/api/tight_layout_api.rst, doc/api/type1font.rst, doc/users/prev_whats_new/whats_new_1.1.rst
=> Fix generated documentation for deprecated modules

lib/matplotlib/backend_bases.py, lib/matplotlib/backends/backend_pdf.py, lib/matplotlib/backends/backend_ps.py, lib/matplotlib/backends/backend_svg.py, lib/matplotlib/backends/backend_template.py
Followup to https://github.com/matplotlib/matplotlib/pull/23551.
=> Uncamelcase offsetTrans in draw_path_collection.

lib/matplotlib/patches.py
- Rely on `__init_subclass__` to avoid the need for the out-of-order
`interpd.update`/`dedent_interpd`.
- Use consistent wording for all setters, and add ACCEPTS list in all
cases.
- Move get_boxstyle right next to set_boxstyle (consistently with the
other setters/getters).
- Make the type check in the setters consistent in all cases (check for
str, not for forcing inheritance from the private _Base).
- Support `set_connectionstyle()` as equivalent to
`set_connectionstyle(None)`, consistently with the other two setters.
=> Harmonize docstrings for boxstyle/connectionstyle/arrowstyle.

lib/matplotlib/projections/polar.py
See https://github.com/matplotlib/matplotlib/pull/14852, https://github.com/matplotlib/matplotlib/pull/23592#discussion_r950727941.
=> Document polar handling of _interpolation_steps.

tutorials/text/annotations.py
Minor change to docs, added a missing link to the ConnectionPatch class where is is being discussed.
=> DOC: Added link to class under discussion

lib/matplotlib/tests/test_colors.py
=> Loosen up test_Normalize test

doc/conf.py
Due to the merging of https://github.com/matplotlib/mpl-sphinx-theme/pull/26
=> DOC: Update theme configuration for upcoming changes

lib/matplotlib/axis.py
=> DOC: add numpydoc docstring + commentary to Axis.get_ticklocs

examples/lines_bars_and_markers/bar_label_demo.py, examples/lines_bars_and_markers/bar_stacked.py, examples/lines_bars_and_markers/barchart.py, examples/units/bar_unit_demo.py
=> Changing bar examples to tea and coffee

doc/users/next_whats_new/font_fallback.rst
Remove the hedging in the whats new entry
=> DOC: fontfallback works for most of the backends

doc/devel/dependencies.rst, lib/matplotlib/backends/backend_cairo.py
This is simply documenting the status quo and putting an earlier check for it (rather than erroring out with an AttributeError at runtime), so no changelog.
Also, technically, only the gtk backends need pycairo 1.14 (the other backends can stick to 1.11), but 1.14 is old enough (2017) that it doesn't seem worth the complication of having two different bounds.
Closes #23827.
=> Clarify that pycairo>=1.14.0 is needed.

doc/devel/development_setup.rst
- Put clone https/ssh variants in tabs
- Move the optional pre-commit hook description to the end (first do all mandatory stuff).
=> Further improve dev setup instructions

lib/mpl_toolkits/tests/test_mplot3d.py
=> Add even more mplot3d tests

examples/event_handling/pick_event_demo.py
Fix **wrong** formatting of the [pick even demo example](https://matplotlib.org/devdocs/gallery/event_handling/pick_event_demo.html):
**Fixed** formatting:
=> DOC: Fix formatting of pick event demo example

lib/matplotlib/axes/_axes.py
Small addition to clarify that by default hist computes bins, based on https://twitter.com/TheQuantumMage/status/1568037678670659587
Also tweaked the sentence explaining the return values. attn  @TheQuantumMagician
=> clarified that hist computes histogram on unbinned data

lib/matplotlib/backend_bases.py, lib/matplotlib/tests/baseline_images/test_backend_ps/scatter.eps, lib/matplotlib/tests/test_backend_ps.py
This was not tested as all earlier.
Also added a missing argument to the `draw_text` doc-string.
~I have problems figuring out how to obtain a PathCollection which leads to optimized rendering.~ Also, I have noted that it seems possible to save the reference image as pdf instead. Any input here would be appreciated.
=> Add PathCollection test for ps backend

tutorials/introductory/images.py
Turn python comment with link to numpy docs into rst link and fix minor typos.
**OLD:**
**NEW:**
=> DOC: Fix formatting in image tutorial

doc/_static/switcher.json
=> DOC: fix versions is doc switcher

doc/conf.py
Remove dead links to source code as _source directory was intentionally removed in the circle config config.yml because store_artifcats uploads files one by one which takes an inordinate amount of time.
Closes #23876 .
=> DOC: remove dead "Show Source" links

doc/Makefile, doc/conf.py, doc/devel/documenting_mpl.rst
Adds an `html-noplot` option to the Makefile, following the [Sphinx-Gallery documentation](https://sphinx-gallery.github.io/stable/advanced.html#build-the-gallery-without-running-any-examples).  With this option the gallery structure is still generated, but we do not get the gallery images.  On my laptop this option takes about a third of the time it takes to run `make html`.  I think this would be useful for contributors who want to check other aspects of the documentation besides the gallery.
This option does trigger a lot of warnings, where various rst files link to the gallery images, so I'm not sure whether it makes sense to include the `SPHINXOPTS` variable used in the other options.  I have for now.
The change to `conf.py` follows advice at …
=> Implement Sphinx-Gallery's `make html-noplot`

doc/devel/documenting_mpl.rst
from the Writing Documentation section of the developer's docs. Animations get perfectly well embedded in the documentation by sphinx without the need of linking to youtube. More complex examples can be posted in the Discourse Showcases section instead of contacting Michael Droettboom for the login password to upload youtube videos.
Closes #23955.
- [N/A] API changes documented …
=> DOC: Remove Adding Animations section

examples/mplot3d/contour3d_3.py, examples/mplot3d/contourf3d_2.py
See  matplotlib/matplotlib#23895:
- the 3D surface was unrecognizable due to the invisible edges,
- the links in the documentation were broken,
- the wording in the title did not conform to the guidelines.
Closes matplotlib/matplotlib#23895.
- [N/A] Documentation is sphinx …
=> Fix edge color, links, wording; closes matplotlib/matplotlib#23895

examples/mplot3d/2dcollections3d.py, examples/mplot3d/contour3d.py, examples/mplot3d/contour3d_2.py, examples/mplot3d/contourf3d.py, examples/mplot3d/hist3d.py, examples/mplot3d/lines3d.py, examples/mplot3d/lorenz_attractor.py, examples/mplot3d/mixed_subplots.py, examples/mplot3d/offset.py, examples/mplot3d/rotate_axes3d_sgskip.py, examples/mplot3d/surface3d.py, examples/mplot3d/text3d.py, examples/mplot3d/trisurf3d_2.py, examples/mplot3d/voxels_numpy_logo.py, examples/mplot3d/voxels_rgb.py, examples/mplot3d/wire3d_animation_sgskip.py, examples/mplot3d/wire3d_zero_stride.py
=> Edit mplot3d examples for correctness and consistency

lib/matplotlib/axes/_axes.py, lib/matplotlib/colorbar.py, tutorials/introductory/lifecycle.py
Found a repeated word typo when reading the tutorial, also searched and fixed others in *.py files.
=> Fix repeated word typos

tutorials/introductory/lifecycle.py
There was an incorrect sentence that needed rewording. Links added for easier navigation. Add a ,. Replace 1 with one.
=> Fix wording and links lifecycle tutorial

examples/widgets/span_selector.py
=> Reword SpanSelector example.

examples/text_labels_and_annotations/font_family_rc.py
=> DOC: Fix incorrect redirect

lib/matplotlib/backends/backend_svg.py
We can delay quoting and deduplication until quite late.
=> Simplify svg font expansion logic.

.github/workflows/cibuildsdist.yml
Added installing twine and checking that the README can be parsed correctly for PyPy. `twine` returns exit code 0 on success, 1 on failure, so I don't think it needs a wrapper script. follow up to #24067 
=> test readme rendering

lib/matplotlib/offsetbox.py
Adjust OffsetBox.get_window_extent to use get_extent (which is typically redefined in subclasses) instead of get_extent_offsets (which is not), and make it check whether the current class' get_offset takes any arguments or not (which is not consistent, but fixing that requires some backcompat work).
Also set the offset-getter of AnchoredOffsetbox as a fixed method on the class, rather than dynamicaly setting in that class' get_extent_offset.
These changes then let us inherit the implementation of OffsetBox.get_window_extent across most subclasses instead of having to copy-paste it again and again.
This mostly replaces #21699 without touching the more complex question of changing/harmonizing the signature of get_offset.
=> Inherit OffsetBox.get_window_extent.

lib/matplotlib/axes/_secondary_axes.py
Not everything was checked correctly earlier. Checking also leads to simplifications of x/y checking.
=> MNT: Clean up code in SecondaryAxis

lib/matplotlib/pyplot.py
This is mainly for the benefit of PyPy.
Fixes #24094
=> Fall back to Python-level Thread for GUI warning

doc/devel/coding_guide.rst
Added tests to the guidance about milestoning for the next patch release based on the discussion on today's call. cc @QuLogic
=> test only PR milestoning guidance

lib/matplotlib/axes/_axes.py
=> DOC: Explain gridsize in hexbin()

lib/matplotlib/animation.py
https://github.com/matplotlib/matplotlib/issues/24150#issuecomment-1279589581
=> [DOC]: added parent link for `FuncAnimation` and `ArtistAnimation`

tutorials/introductory/quick_start.py
Remove useless semicolons in tutorial https://matplotlib.org/stable/tutorials/introductory/usage.html#sphx-glr-tutorials-introductory-usage-py.
=> Remove useless semicolons in "Introductory / Basic Usage" tutorial

lib/matplotlib/backends/_backend_gtk.py, lib/matplotlib/backends/_backend_tk.py, lib/matplotlib/backends/backend_agg.py, lib/matplotlib/backends/backend_cairo.py, lib/matplotlib/backends/backend_gtk3.py, lib/matplotlib/backends/backend_gtk4.py, lib/matplotlib/backends/backend_ps.py, lib/matplotlib/backends/backend_qt.py, lib/matplotlib/backends/backend_qt5.py, lib/matplotlib/backends/backend_qt5agg.py, lib/matplotlib/backends/backend_qtagg.py, lib/matplotlib/backends/backend_svg.py
It's not really clear if we really need to keep the backend_version backend attribute, but currently it is getting overridden by _Backend.export to "unknown" (as can be checked e.g. by printing backend_agg.backend_version).  Move the definition to within the _Backend class to fix that, and inherit that information where possible.
=> Properly set and inherit backend_version.

lib/mpl_toolkits/axes_grid1/anchored_artists.py, lib/mpl_toolkits/axes_grid1/axes_divider.py, lib/mpl_toolkits/axes_grid1/axes_rgb.py, lib/mpl_toolkits/axes_grid1/inset_locator.py, lib/mpl_toolkits/axes_grid1/parasite_axes.py, lib/mpl_toolkits/axisartist/axes_rgb.py, lib/mpl_toolkits/axisartist/axis_artist.py, lib/mpl_toolkits/axisartist/axislines.py, lib/mpl_toolkits/mplot3d/art3d.py, lib/mpl_toolkits/mplot3d/axes3d.py, lib/mpl_toolkits/mplot3d/axis3d.py, lib/mpl_toolkits/mplot3d/proj3d.py
A bit of links and numpydocifying.
(Probably won't work at the first attempt as I cannot build locally...)
And a minor change in the code for efficiency.
=> Improve mpl_toolkit documentation

examples/misc/demo_agg_filter.py
This fixes the pie chart in [demo_agg_filter.py] (https://matplotlib.org/stable/gallery/misc/demo_agg_filter.html) which is incorrectly displayed with simple black color . Fixed image is shown below. It also add new `shrink` parameter and a bit of more documentation.
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) …
=> Fix pie chart in demo_agg_filter.py

.github/PULL_REQUEST_TEMPLATE.md, doc/devel/coding_guide.rst
Added policy to coding guidelines and PR guidelines based on discussion in #23506, samples of the directives are at  #24160
=> Versioning directives policy

examples/event_handling/pong_sgskip.py, examples/units/basic_units.py, examples/user_interfaces/toolmanager_sgskip.py, lib/matplotlib/backends/backend_wx.py, lib/matplotlib/font_manager.py, lib/matplotlib/patches.py, lib/matplotlib/path.py, lib/matplotlib/sphinxext/plot_directive.py, lib/matplotlib/tests/test_png.py, lib/matplotlib/ticker.py, lib/mpl_toolkits/axisartist/angle_helper.py, setupext.py
=> Remove unnecessary/replaceable explicit str calls.

lib/matplotlib/image.py
=> DOC: add warning note to imsave

examples/animation/animate_decay.py
going by @QuLogic's response in #24296, I think the easiest fix to have the axes changes show up in the docs is to change the initial xmax. I'm trying 1, don't have much of an opinion so long as the rendered html docs can show the changing x axis.
Eta: also updated the interval to be little longer 'cause 10 was a bit fast for smaller bounds
=> show axes changing in animate decay example

tutorials/text/annotations.py
Follow up to #23606.
- Move the basic text() vs. annotate() discussion to the top
- Styling in "Annotating with boxed text": move the text from Axes edge to center; less glaring colors
There's still more that can be done in later PRs ...
=> Minor improvements to Annotations Tutorial

lib/matplotlib/tight_layout.py
get_renderer was removed in #22745 despite being a public (listed) function, see https://github.com/matplotlib/matplotlib/issues/24300#issuecomment-1295800262
Closes #24300 
=> Restore get_renderer function in deprecated tight_layout

examples/images_contours_and_fields/demo_bboximage.py
=> Cleanup BboxImage example.

doc/api/pyplot_summary.rst
Similar to what we do in Axes:
https://matplotlib.org/stable/api/axes_api.html#plotting
Note: `test_doc_pyplot_summary()` ensures that the PR does not add or remove entries -> you don't have to check that in the review.
=> DOC: Group pyplot plotting commands

lib/matplotlib/figure.py
subfigures() usually adds more than one subfigure at a time, despite what the docstring previously said.  Fix that.  The new wording mostly matches the one of subplots().
=> Fix docstring of Figure.subfigures.

tutorials/colors/colors.py
- "Commutative" is a bit jargony, and technically applies to *binary* operations (see e.g. wikipedia), not to "reordering".
- The fact that drawing (with or without alpha) is order-dependent is not something specific to Matplotlib.
=> Reword "Reordering is not commutative" phrase in tutorial.

doc/api/backend_gtk3_api.rst, doc/api/backend_gtk4_api.rst, doc/api/backend_qt_api.rst, doc/api/backend_wx_api.rst, doc/users/explain/backends.rst, doc/users/faq/environment_variables_faq.rst, doc/users/prev_whats_new/whats_new_3.5.0.rst
- Make the API docs for backend_qtagg/backend_qtcairo the main point documenting QT_API.  Reorder the information to first present what's most relevant for end users (1. there are multiple bindings, 2. this is how to select them) before going into the older approach and qt_compat (which is an implementation detail).
- Let the backend explanatory docs just refer to the API docs, instead of rewriting essentially the same thing.
=> Tighten the Qt binding selection docs.

lib/matplotlib/backend_bases.py, lib/matplotlib/backends/_backend_gtk.py, lib/matplotlib/backends/_backend_tk.py, lib/matplotlib/backends/backend_gtk3.py, lib/matplotlib/backends/backend_gtk4.py, lib/matplotlib/backends/backend_macosx.py, lib/matplotlib/backends/backend_qt.py, lib/matplotlib/backends/backend_webagg.py, lib/matplotlib/backends/backend_wx.py, lib/matplotlib/pyplot.py, lib/matplotlib/tests/test_backend_template.py
~~Goes on top of #23090 (see https://github.com/matplotlib/matplotlib/pull/23090#issuecomment-1133763234).~~
It's actually not clear whether to move it to FigureCanvas or
FigureManager.  FigureCanvas already has start_event_loop (cf.
start_main_loop), but pyplot_show/start_main_loop is more a
global/pyplot-only concept, so perhaps it belongs to FigureManager
instead?  OTOH, being on canvas_class makes it easier for switch_backend
to access it (it doesn't need to go through
`canvas_class.manager_class.pyplot_show`, which is relevant considering
that some designs of inheritable backends didn't even have a
manager_class attribute).
Finally, a document stating what's needed in a backend!
(only the pyplot interaction part, not the rendering part.)
Edit: now moved to #24218.
**Tests and …
=> Move show() to somewhere naturally inheritable / document what pyplot expects from a backend.

lib/matplotlib/ticker.py
- Make formula in the first line consistent with symbols used in the parameter docs
- Add allowed strings to type documentation of 'subs'
- Minor language improvements
=> Minor improvements to LogLocator docstring

tutorials/colors/colors.py
Follow-up to #24407.
- Rewrite section on transparency
- Add more subsections to the tutorial for better structure (and use the appropriate level marker (`======`) accordings to https://matplotlib.org/devdocs/devel/documenting_mpl.html#section-formatting
=> DOC: Clarify transparency in colors

doc/conf.py, requirements/doc/doc-requirements.txt
`pydata-sphinx-theme` updated, renaming some configuration names.
(only one of which we actually configure)
While they are just warnings for now, we are configured to error on
warning so CircleCI is indicating failure.
This does the 'easy' route of just changing to the new name and expecting
the version in which it is implemented.
If desired, I could do a larger change to accomodate both by checking
the version, but I'm also not _too_ worried about more tightly pinning
already relatively tight requirements.
- [N/A] New features are marked with a `.. versionadded::` directive in the docstring and documented in …
=> Update for pydata-sphinx-theme 0.12.0

.github/workflows/cibuildsdist.yml, .github/workflows/tests.yml
=> Update tests to run with 3.11 (not rc)

doc/conf.py
Pydata-sphinx-theme actually deprecated the top level config key
"google_analytics_id" a few releases ago, though with a standard
DeprecationWarning (which is silenced by default) so we did not catch
it.
The deprecation was expired for 0.12.0, which resulted in a warning (and
thus CircleCI reporting failure).
Further, this option is only added in "release mode" builds, so standard PRs do not pick it up.
For more info see [the pydata-sphinx-theme docs](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/analytics.html).
Essentially, it is simply adding a layer of nesting for the analytics
tokens.
- [N/A] New …
=> Update adding of google analytics key for docs

examples/axisartist/demo_floating_axes.py
... per our usual approach to example titles.
=> Remove link from demo_floating_axes title.

tutorials/toolkits/axes_grid.py, tutorials/toolkits/axisartist.py, tutorials/toolkits/mplot3d.py
=> Tweak markup in toolkits tutorials.

doc/users/explain/backends.rst, doc/users/explain/index.rst, doc/users/explain/writing_a_backend_pyplot_interface.rst
(split out of #23101 to make that easier to go in first; goes on top of it.)
Closes #12324.
Now ready to go.
=> Document what pyplot expects from a backend.

lib/matplotlib/offsetbox.py, lib/matplotlib/patches.py, lib/matplotlib/path.py, lib/matplotlib/sankey.py, lib/matplotlib/spines.py, lib/matplotlib/streamplot.py, lib/matplotlib/text.py, lib/matplotlib/ticker.py, lib/matplotlib/transforms.py, lib/matplotlib/widgets.py
=> Doc: Fix grammar and spelling

lib/matplotlib/artist.py, lib/matplotlib/axis.py, lib/matplotlib/bezier.py, lib/matplotlib/collections.py, lib/matplotlib/colorbar.py, lib/matplotlib/colors.py, lib/matplotlib/contour.py, lib/matplotlib/dates.py, lib/matplotlib/dviread.py, lib/matplotlib/figure.py, lib/matplotlib/font_manager.py, lib/matplotlib/gridspec.py, lib/matplotlib/image.py, lib/matplotlib/layout_engine.py
A bunch of minor fixes. For comments, I only modified when it was sort of obviously the wrong word, so very few grammar fixes (although a few before I stopped).
=> DOC: improve grammar and consistency

lib/matplotlib/axes/_axes.py, lib/matplotlib/axes/_base.py, lib/matplotlib/backends/backend_agg.py, lib/matplotlib/backends/backend_pdf.py, lib/matplotlib/backends/backend_ps.py, lib/matplotlib/backends/backend_qt.py, lib/matplotlib/backends/backend_template.py, lib/matplotlib/backends/backend_wx.py, lib/matplotlib/cbook/__init__.py, lib/matplotlib/projections/geo.py, lib/matplotlib/projections/polar.py, lib/matplotlib/tri/_tricontour.py, lib/matplotlib/tri/_triinterpolate.py, lib/matplotlib/tri/_trirefine.py, lib/matplotlib/tri/_tritools.py
This is most likely the last one (for the code base) for now.
=> [Doc] fix more spelling and grammar

tutorials/introductory/animation_tutorial.py
A one-stop tutorial that covers all the major points of creating an animation using the `matplotlib.animation` module. (Reference issue: #24228 by @story645)
=> Animation Tutorial

lib/matplotlib/axes/_axes.py, lib/matplotlib/pyplot.py, lib/matplotlib/tests/test_axes.py
=> FIX: Support passing one alpha per event sequence to eventplot()

.circleci/config.yml, .github/workflows/cibuildsdist.yml, .github/workflows/cibuildwheel.yml, .github/workflows/circleci.yml, .github/workflows/clean_pr.yml, .github/workflows/nightlies.yml, .github/workflows/pr_welcome.yml, .github/workflows/reviewdog.yml, .github/workflows/tests.yml
Merge pull request #24579 from QuLogic/action-permissions
Add explicit permissions to GitHub Actions
(cherry picked from commit 24f912845dd2765c86863945ed9a5fda82ed418b)
There was a modified file that does not exist on this branch.
=> Backport PR #24579: Add explicit permissions to GitHub Actions

tutorials/advanced/transforms_tutorial.py
=> Update the polar transform information in doc #24499

lib/matplotlib/pyplot.py
This is a simple solution following the issue [#24578](https://github.com/matplotlib/matplotlib/issues/24578). Adding a reference `draw_idle` may reduce confusion to audiences who is visiting this page.
=> DOC: add "See Also: draw_idle" reference to pyplot.draw

lib/matplotlib/axes/_base.py
See discussion at https://github.com/matplotlib/matplotlib/pull/24627#discussion_r1039726950.
=> Init axes._children early enough to avoid need for some getattr calls.

tutorials/provisional/mosaic.py
None of the section titles in this tutorial uses titlecase.
=> Tiny capitalization fix.

lib/matplotlib/backends/backend_qtagg.py, lib/matplotlib/cbook/__init__.py
Closes #23968 (according to https://github.com/matplotlib/matplotlib/issues/23968#issuecomment-1345611272, at least).
We can discuss bumping the minimal support qt version (https://github.com/matplotlib/matplotlib/issues/23968#issuecomment-1345612767) elsewhere; let's fix the issue at hand first.
=> Avoid rgba8888->argb32 conversion if qt can do it for us.

src/_macosx.m
Match the zoom box styling of the other backends with alternating white/black paths.
closes #23777
- [N/A] API changes are marked with a `.. versionchanged::` directive in …
=> STY: Update macosx zoom rect styling

lib/matplotlib/figure.py
=> DOC: tweak wording on Figure.show warning

lib/matplotlib/ticker.py
This function does not, in fact, work when provided string input as
implied by the current docstring. …
=> Remove quotes from EngFormatter.format_eng example

lib/matplotlib/gridspec.py, lib/matplotlib/tests/test_subplots.py
This PR allows to use either 0 or 1 in place of `False` or `True` in `sharex` and `sharey` options. Fixes  #24349.
=> Allow bool-like values for sharex/sharey

README.md
closes #24717 per @yochannah
https://github.com/matplotlib/matplotlib/issues/24717#issuecomment-1354709630
=> DOC: remove research notice

lib/matplotlib/backend_bases.py, lib/matplotlib/backends/_backend_tk.py, lib/matplotlib/backends/backend_gtk3.py, lib/matplotlib/backends/backend_gtk4.py, lib/matplotlib/backends/backend_qt.py, lib/matplotlib/backends/backend_webagg_core.py, lib/matplotlib/backends/backend_wx.py, lib/matplotlib/backends/web_backend/js/mpl.js, lib/matplotlib/tests/test_backend_qt.py, src/_macosx.m
Ensure that modifier keys are correctly reported for mouse events even if the last key press occurred out of the canvas.
Whether the event modifiers are directly available on enter/leave events
depends on the backend, but all are handled here (except possibly for
macos, which I haven't checked).
There's a first separate commit for the macosx backend for some preliminary work with ObjC.
Followup to #16931 (it's the reason for that big PR...).  Supersedes #6159.  See also the side note at https://github.com/matplotlib/matplotlib/issues/23436#issuecomment-1186302186.
=> Separately track modifier keys for mouse events.

examples/widgets/check_buttons.py
Now that dictionaries are ordered, do not simulate an ordered dictionary via two lists.
=> DOC: simplify CheckButton example

examples/specialty_plots/leftventricle_bulleye.py
Closes #24771 
Maybe one should replace `2 - 1` with `1`? (The other subtractions are a bit more "pedagogical".)
=> Fix Left ventricle bullseye example

doc/devel/development_workflow.rst
#24762 
Fix a typo and grammar errors on #24762
```diff
- Making an new branch for each set of related changes will make it easier for
+ Making a new branch for each set of related changes will make it easier for
-Enter a title for the set of changes, and some explanation of what you've done.
-Say if there is anything you'd like particular attention for - like a
+Enter a title for a set of changes with some explanation of what you've done.
+Mention anything you'd like particular attention for - such as a
-There's an embarrassing typo in a commit you made? Or perhaps the you
-made several false starts you would like the posterity not to see.
+Is there any embarrassing typo in a commit you made? Or perhaps you
+made several false starts you don't want posterity to see.
-and the history …
```
=> DOC: update typos and grammar errors

doc/api/next_api_changes/removals/21661-TAC.rst, lib/matplotlib/sphinxext/plot_directive.py, lib/matplotlib/tests/test_sphinxext.py, lib/matplotlib/tests/tinypages/range6.py, lib/matplotlib/tests/tinypages/some_plots.rst
This will close #20656 .
I started but did not get through writing tests, I think I see a way to test just `render_figures` in a self-contained way, but wanted to push this up so it did not get lost.
=> Fix plot directive with func calls

doc/api/next_api_changes/deprecations/24474_CM.rst, doc/api/prev_api_changes/api_changes_2.1.0.rst, lib/matplotlib/tests/test_widgets.py, lib/matplotlib/widgets.py
ref: #24471 
With the current implementation, the boxes get stretched into rectangles if the aspect ratio is not maintained. To overcome this, the boxes are now created using scatter instead to maintain their shapes.
=> Use scatter for check boxes and set facecolors correctly in check boxes and radio buttons

lib/matplotlib/category.py, lib/matplotlib/cm.py, lib/matplotlib/collections.py, lib/matplotlib/colors.py, lib/matplotlib/dates.py, lib/matplotlib/figure.py, lib/matplotlib/image.py, lib/matplotlib/quiver.py, lib/matplotlib/transforms.py, lib/mpl_toolkits/mplot3d/axes3d.py
=> [Doc] Fix ndarray-links for arguments

doc/users/next_whats_new/widget_blitting.rst, lib/matplotlib/widgets.py
=> Add blitting support to button widgets

examples/lines_bars_and_markers/span_regions.py
In preparation for a possible deprecation of BrokenBarHCollection (#24827), which may be a good idea.
Using axes methods is usually simpler for end users, anyways.
=> Show that fill_between and span_where provide similar functionalities.

examples/color/named_colors.py
=> Minor cleanups to named colors example.

lib/matplotlib/tests/test_axes.py, lib/matplotlib/tests/test_colorbar.py, lib/matplotlib/tests/test_contour.py, lib/matplotlib/tests/test_image.py, lib/matplotlib/tests/test_lines.py, lib/matplotlib/tests/test_mathtext.py
I previously had this downstream in Fedora, but as we may soon get real ARM CI (#24597), it makes sense to put it in here now.
=> Increase a few test tolerances on some arches

doc/index.rst, doc/users/getting_started/index.rst
The current install instructions for installing from conda recommend doing `conda install matplotlib` which doesn't ensure the latest matplotlib version. Just updated that to `conda install -c conda-forge matplotlib` as was decided upon after the discussion in #24421.
- [N/A] Release notes conform with instructions in  `next_whats_new/README.rst` or …
=> update install instructions for conda

doc/users/next_whats_new/per_subplot_mosaic.rst, doc/users/prev_whats_new/whats_new_3.3.0.rst, examples/subplots_axes_and_figures/mosaic.py, lib/matplotlib/figure.py, lib/matplotlib/pyplot.py, tutorials/intermediate/arranging_axes.py, tutorials/introductory/quick_start.py
Mark mosaic as no longer provisional.
I also moved this from tutorials -> examples as this is much a how-to and "gallery" is what we have that matches the divio "how-to" best.
=> DOC: mark mosaic as no longer provisional

.github/workflows/tests.yml
We don't have the build dependencies installed anyway
Closes #24901
=> Add --only-binary to nightly pip install

lib/matplotlib/__init__.py
This is just the first commit of #23681.
Fixes #23646
=> DOC: Improve documentation for set_loglevel

src/_c_internal_utils.c, src/_macosx.m, src/_path.h, src/ft2font_wrapper.cpp
With requiring Python 3.9 (and even 3.8), these are no longer required.
There is still a single PYPY compiler directive in the MacOS backend which I think can be removed, but since I cannot test it, I am not fully convinced...
(Would it make sense to run the tests on PyPy for a random platform/version?)
=> Remove special casing for PyPy not required anymore

tutorials/introductory/animation_tutorial.py
The new animation tutorial takes over 30s to render in sphinx gallery on my machine.  That seems unnecessary for didactic purposes.   This version takes less than 5 s.  Maybe someone wants different aesthetics, but this really is pretty slow.  
@chahak13 I think you wrote the original.  happy to defer to your interest in how this looks, but I still strongly encourage that it be _much_ faster.  
=> DOC: animation faster

.appveyor.yml, .circleci/config.yml, .github/workflows/cibuildsdist.yml, .github/workflows/cibuildwheel.yml, .github/workflows/circleci.yml, .github/workflows/reviewdog.yml, .github/workflows/tests.yml, azure-pipelines.yml, doc/api/next_api_changes/development/24919-KS.rst, doc/devel/dependencies.rst, lib/matplotlib/tests/test_getattr.py, requirements/testing/extra.txt, requirements/testing/minver.txt, setup.py
=> Remove support for python 3.8

examples/animation/animate_decay.py, examples/animation/animated_histogram.py, examples/animation/animation_demo.py, examples/animation/bayes_update.py, examples/animation/double_pendulum.py, examples/animation/dynamic_image.py, examples/animation/frame_grabbing_sgskip.py, examples/animation/multiple_axes.py, examples/animation/pause_resume.py, examples/animation/rain.py, examples/animation/random_walk.py, examples/animation/simple_anim.py, examples/animation/simple_scatter.py, examples/animation/strip_chart.py, examples/animation/unchained.py
=> Auto backport of pr 24897 on v3.7.x

doc/conf.py
Fix `html_use_opensearch` in conf.py: the current value of `'False'` is misinterpreted as the url `False`. If no OpenSearch description file should be created the value must be empty (default), but I think OpenSearch is a very handy feature, so I'd like to enable it.
See also https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_use_opensearch.
Closes https://github.com/matplotlib/mpl-sphinx-theme/issues/56.
- [N/A] API changes are marked with a `.. versionchanged::` …
=> DOC: Enable Opensearch

lib/matplotlib/colors.py
Mostly, we don't need to manually handle/clip out of bounds float values if we compute the masks early enough (note that these masks are always computed at some point anyways, so there's no cost of doing that a bit earlier).
=> Simplify handling of out-of-bound values `Colormap.__call__`.

lib/matplotlib/figure.py
Also slightly tweak the docstring.
=> Clarify/shorten gca management in colorbar().

lib/mpl_toolkits/mplot3d/axes3d.py
=> Minor refactoring of Axes3D

examples/pie_and_polar_charts/pie_features.py
following instructions for manual backport (yes am rebasing to fix this mess now)
- okay actual solution was to change target branch in dropdown.
=> Backport PR #24812 on branch v3.7.x ([Doc] expanded basic pie example)

examples/shapes_and_collections/artist_reference.py, examples/shapes_and_collections/patch_collection.py
In particular, add each artist directly to its own axes, instead of shifting each of them by some offset and grouping all of them together in a PatchCollection.  Note that this makes the example no longer showcase the use of PatchCollection, but at least based on the docstring that was not the intent of the example anyways, and PatchCollection is showcased elsewhere (in the patch_collection.py example, in particular).
=> Simplify "artist reference" example.

examples/pie_and_polar_charts/nested_pie.py, examples/specialty_plots/leftventricle_bullseye.py
It is much simpler to take advantage of bar()'s support for polar plots. Also improve z-ordering of various elements so that edges don't get overdrawn (or clipped).
before
after
Note the subtle difference in the bold edges in the last plot.
=> Rewrite bullseye example to use bar() instead of pcolormesh().

lib/matplotlib/backends/backend_pgf.py
=> Remove unused import of re introduced in #23442

doc/api/next_api_changes/deprecations/24985-OG.rst, lib/mpl_toolkits/mplot3d/art3d.py, lib/mpl_toolkits/mplot3d/axes3d.py, lib/mpl_toolkits/mplot3d/axis3d.py, lib/mpl_toolkits/mplot3d/proj3d.py, lib/mpl_toolkits/mplot3d/tests/test_axes3d.py
Related to #24098
A bit arbitrary, but primarily unused in the code base (or only used once) and/or not documented (or scarcely documented). Some of more general interest remains, see https://github.com/matplotlib/matplotlib/pull/23449#issuecomment-1268069279
Will add api change notes.
=> Deprecate unused/undocumented functions in proj3d

examples/lines_bars_and_markers/scatter_custom_symbol.py, lib/matplotlib/axes/_base.py, lib/matplotlib/colors.py, lib/matplotlib/lines.py, lib/matplotlib/patches.py, lib/matplotlib/path.py, lib/matplotlib/streamplot.py, lib/matplotlib/transforms.py, src/_backend_agg_wrapper.cpp, src/_path.h, src/mplutils.h, src/py_converters.cpp, tutorials/colors/colormap-manipulation.py
We already mostly use "(M, N)", but there were still quite a few instances of "MxN".  Also add a helper to generate the error messages in extensions.
=> Consistently document shapes as (M, N), not MxN.

lib/matplotlib/contour.py
The docstring for _make_paths is extremely lengthy for what is just a list of map()s and can be more easily explained in a comment.
=> Inline ContourSet._make_paths.

doc/devel/contributing.rst, doc/devel/dependencies.rst, doc/devel/development_workflow.rst, doc/devel/maintainer_workflow.rst, doc/devel/triage.rst
Two commits. One spelling GitHub correctly and one adding links for downloading C++-compilers and to example TeX distributions.
Download links is possibly primarily motivated by #24779 where finding/installing a C++-compiler is more tricky than on e.g. linux. The current links where primarily for proving that the stated version for C++-11 support is correct.
=> [DOC] GitHub spelling and links

lib/matplotlib/axes/_axes.py
See issue for discussion.
https://github.com/matplotlib/matplotlib/issues/25134#issue-1568623320
Slight change of the documentation wording to make it more precise.
Not applicable: - [ ] Has pytest style unit tests (and `pytest` passes)
Not applicable:  - [ ] New plotting related features are documented with examples.
=> Whisker length, more precise description

setupext.py
The main point is actually to get rid of the comment that "static linking on Windows is almost certainly broken"; this may have been true when this first came in in 2015 but now that the PyPI builds use that things should work just fine.
The rest is just small style changes.
=> Minor style tweaks to freetype build.

.circleci/config.yml, .github/workflows/cygwin.yml, .github/workflows/tests.yml, azure-pipelines.yml, doc/devel/coding_guide.rst
Currently we can add messages to the commit to tell various CIs to not run.  However, if you only make a documentation change, you need to specify `[skip-azp] [skip appveyor] [skip actions]`.
This adds the `[ci doc]` option so that only circleCI doc building will happen.
I think I did this right, but not sure.  
=> BLD: only doc CI build

examples/ticks/tick-locators.py
Signed-off-by: priyanshi <noxdot1134@gmail.com>
Fixes #25172 
=> Add locator API links to tick-locators example

doc/devel/coding_guide.rst
We have guidance for adding flags to commit messages to control which CI tasks run.  Currently this starts with "If you know your changes do not need to be tested (this is very rare!)..."  My instinct on reading this is to think this whole bullet point is not for me, and not bother reading the rest.  So I re-ordered to start with the doc-only check, as I think that would be most commonly used, followed by skip circle.  Also added some context for when it would be appropriate to use those.
=> DOC: reorder CI control guidance

lib/matplotlib/artist.py, lib/matplotlib/axes/_axes.py, lib/matplotlib/axis.py, lib/matplotlib/colors.py, lib/matplotlib/lines.py, lib/matplotlib/patches.py, lib/matplotlib/pyplot.py, lib/matplotlib/rcsetup.py, lib/mpl_toolkits/axes_grid1/axes_size.py
In many cases a complex will give an error later on, so better check for Real.
=> Replace checking Number with Real

.github/workflows/cibuildsdist.yml, .github/workflows/cibuildwheel.yml, .github/workflows/cygwin.yml
I guess this was renamed recently?
=> Re-enable CI buildwheel and cygwin labels

.github/workflows/cibuildsdist.yml, .github/workflows/cibuildwheel.yml
Re-enable CI buildwheel and cygwin labels
Note: cygwin ci does not exist on v3.7.x, so cygwin changes are omitted
(cherry picked from commit 60f01751c0bfb486dec45faf1c494e4c1042f236)
=> Backport PR #25236: Re-enable CI buildwheel and cygwin labels

.github/workflows/tests.yml
We don't need to waste CI cycles for doc-only changes and having to remember to add `[doc skip]` to commit messages is asking a lot of users. Also removed extra CI conditionals for skipping that are already handled by GitHub: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
(except [skip github], but that isn't documented and it should really be [skip actions], so let's just remove all of them).
I tested this on an example PR on my fork to verify: https://github.com/greglucas/matplotlib/pull/21
I only added this to `pull_request:`, we could also add this to `push:`, but it seems fine to run tests on every push to `main` regardless.
=> [CI] Skip tests on doc-only changes

README.md
Two consecutive hyphens were used to approximate an em dash when it wasn't available. Today, we have Unicode, and also an HTML character code for it. (The latter is, according to [this Stack Overflow answer](https://stackoverflow.com/a/52377269), the official method to insert em dashes.)
Also, it looks more professional than consecutive hyphens.
There are consecutive hyphens in multiple documentation files, but since the README file is directly presented to the user, it might be a good first place to make this change.
- [N/A] New plotting …
=> Em dashes instead of consecutive hyphens.

lib/matplotlib/backend_bases.py, lib/matplotlib/backend_managers.py, lib/matplotlib/colorbar.py, lib/matplotlib/colors.py, lib/matplotlib/figure.py, lib/matplotlib/gridspec.py, lib/matplotlib/image.py, lib/matplotlib/layout_engine.py, lib/matplotlib/text.py, lib/matplotlib/transforms.py, lib/matplotlib/widgets.py
Trying out [velin](https://github.com/Carreau/velin) and these are fixes for some of the identified issues 
(not including incorrect indentation etc).
(Some are identified when searching for the location of the actual issue...)
=> Fix doc-string issues identified by velin

lib/matplotlib/backend_bases.py, lib/matplotlib/backend_managers.py, lib/matplotlib/colorbar.py, lib/matplotlib/colors.py, lib/matplotlib/figure.py, lib/matplotlib/gridspec.py, lib/matplotlib/image.py, lib/matplotlib/layout_engine.py, lib/matplotlib/text.py, lib/matplotlib/widgets.py
One of the changes is missing as that was related to a 3.8 API-change.
=> Backport PR #25327 on branch v3.7.x (Fix doc-string issues identified by velin)

doc/users/explain/interactive.rst
Ipympl has docs now - nice to link to them instead of github
=> link to ipympl docs instead of github

requirements/doc/doc-requirements.txt
As discussed on the call today.
=> Pin sphinx themes more strictly

lib/matplotlib/backends/_backend_tk.py
=> Tk: Fix size of spacers when changing display DPI

.github/workflows/stale.yml
Based on https://github.com/matplotlib/matplotlib/pull/25163#issuecomment-1453146852, and the fact that 10 issues are currently labelled, I think next run would only catch 3 issues.  Increasing the workflow's operations-per-run by 20 should let it label an extra 5 issues.
=> "Inactive" workflow: bump operations-per-run

lib/matplotlib/pylab.py
Numpy added round, max, min to their exported names which we don't want when we import * from Numpy.
xref: https://github.com/numpy/numpy/pull/23302
closes #25379
=> FIX: Remove some numpy function overrides from pylab

doc/api/transformations.rst, lib/matplotlib/backend_bases.py, lib/matplotlib/cm.py, lib/matplotlib/colors.py, lib/matplotlib/contour.py, lib/matplotlib/image.py, lib/matplotlib/markers.py, lib/matplotlib/path.py, lib/matplotlib/texmanager.py, lib/mpl_toolkits/mplot3d/axes3d.py, src/_image_wrapper.cpp
Some documentation fixes for consistency/linking. Split into four commits for ease of reviewing/sensible commit message.
(It seems like `numpy.uint8` is really an alias so it may make sense to document `numpy.ubyte` although `uint8` is more descriptive on its own. Same with all the other `int/floatXX` types.)
=> Documentation fixes

lib/matplotlib/path.py
=> Add links for path types and general improvements

.github/workflows/stale.yml
The workflow is not making much progress because it’s using up most of its available operations checking the issues it already labelled (https://github.com/matplotlib/matplotlib/pull/25163#issuecomment-1453146852).  An extra 25 operations means an extra ~6 issues can be labelled in the next run.
I think we will need to keep increasing this through the first month.  After that, it will start closing previously labelled issues and so free up some operations for itself.
=> “Inactive” workflow: increase operations to 75

.circleci/config.yml, doc/conf.py
#25423 didn't quite get th logo correct, in particular the dark logo was not being used in dark mode.  I'm not sure what caused this, because it works fine in mpl-sphinx-theme, but mpl-sphinx-theme doesn't set `html-logo` so let's try removing that.  
=> DOC: remove default logo [ci doc]

galleries/examples/misc/tickedstroke_demo.py, lib/matplotlib/patheffects.py
Took me a while and a bit of trial and error to figure it out.
The ant example in the doc-string is not that good since for plot, it seems like to points are reordered, so `plot([0, 1], [0, 1])` and `plot([1, 0], [1, 0])` actually gives the same tick direction. I guess it is correct though, and that plot swaps when creating the line.
One may argue if changing sign or adding/subtracting 180 is the "correct way", but I think that once one realize that it is the angle that one should modify, one can figure out the rest. (Changing sign of the length is also an option, but more limited and I do not think that has any actual advantage...)
Must of course not go into 3.7.2, but if it was only the example, it would probably go into 3.7-doc and so on.
=> [DOC] Clarify how to change side of the TickedStroke ticks

doc/api/backend_gtk3_api.rst, doc/api/backend_gtk4_api.rst, doc/api/backend_wx_api.rst
These modules are not actual backends but rather serve as bases for the corresponding agg/cairo backends, but adding them to the docs allows referring to them from elsewhere.
Note that backend_qt is already listed; _backend_tk is currently private but we could consider making it (or a subset of it) public like the others (I already rely on it in mplcairo, for example).
=> Add references to backend_{gtk3,gtk4,wx} in docs.

.appveyor.yml
The path matching for skipping the Appveyor tests doesn’t work - they were queued up in #25461.  So I had a closer look at the [file matching rules](https://www.appveyor.com/docs/how-to/filtering-commits/#file-matching-rules), and I think this should do it.
=> Skip Appveyor for doc only change (second attempt)

doc/api/next_api_changes/deprecations/25469-AL.rst, galleries/examples/axes_grid1/demo_axes_divider.py, galleries/examples/axes_grid1/demo_axes_grid.py, galleries/examples/axes_grid1/demo_axes_grid2.py, galleries/examples/axes_grid1/demo_axes_rgb.py, galleries/examples/axes_grid1/demo_colorbar_of_inset_axes.py, galleries/examples/axes_grid1/demo_edge_colorbar.py, galleries/examples/axes_grid1/inset_locator_demo2.py, galleries/examples/axes_grid1/simple_axesgrid2.py, galleries/examples/images_contours_and_fields/shading_example.py, galleries/examples/lines_bars_and_markers/fill_between_alpha.py, galleries/examples/lines_bars_and_markers/scatter_demo2.py, galleries/examples/mplot3d/custom_shaded_3d_surface.py, galleries/examples/specialty_plots/topographic_hillshading.py, galleries/examples/subplots_axes_and_figures/zoom_inset_axes.py, galleries/examples/text_labels_and_annotations/date.py, galleries/examples/ticks/centered_ticklabels.py, galleries/examples/ticks/date_index_formatter.py, galleries/tutorials/colors/colormapnorms.py, lib/matplotlib/cbook.py, lib/matplotlib/tests/test_colors.py, lib/mpl_toolkits/axes_grid1/tests/test_axes_grid1.py
This makes the examples cleaner (the focus should be on plotting, not on loading data), and it's also somewhat unlikely that one really wants to have a open()ed npy file without calling np.load anyways.
=> Autoload numpy arrays in get_sample_data.

lib/matplotlib/__init__.py
- remove verbatim formatting
- directives can't be used in docstrings
** OLD **
** NEW **
=> DOC: Fix docstring formatting

galleries/examples/lines_bars_and_markers/barh.py
The call to `rcdefaults` in this example seems superfluous.  Because it's there, the example is linked from the [API docs for rcdefaults](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.rcdefaults.html#matplotlib.pyplot.rcdefaults), which gives the user the impression that they may learn more about the function by looking at the example.  The other linked example is much more useful for this.
=> DOC: remove rcdefaults from barh example

.gitignore
I think `doc/users/explain` is now being generated by sphinx-gallery, so needs to be included in `.gitignore`.
=> gitignore doc/users/explain

.circleci/config.yml, environment.yml, requirements/doc/doc-requirements.txt
I think SG release 0.12 is compatible with what we need for flexible rst-passing in SG per #25395 
=> DOC/BLD: stop using sg head [ci doc]

requirements/doc/doc-requirements.txt
Previously was a transitive dependency from ipywidgets, but that was
removed in favor of a lower level comm package created/used by the
jupyter ecosystem (including ipykernel).
Upon them releasing that change, Circle doc builds began failing as the
nbagg/webagg backends require ipykernel and it was not installed.
Reference https://github.com/jupyter-widgets/ipywidgets/pull/3533/files#diff-d3df85288b79c378bd5be0ae897814abd0db4f90bed160b7259d805a7e77425e
=> Add ipykernel as an explicit doc dependency

galleries/examples/axes_grid1/demo_colorbar_with_axes_divider.py
Sphinx Gallery 0.11.0 left RST formatting characters in the thumbnail titles. This was fixed in version 0.12.2 for most cases by sphinx-gallery/sphinx-gallery/pull/1005, which doesn't cover default roles. So to restore the previous behavior we need to explicitely specify a role.
Closes #23884.
- [N/A] Release notes conform with instructions in …
=> DOC: Fix thumbnail title for sphinx gallery

.github/workflows/stale.yml
As https://github.com/matplotlib/matplotlib/pull/25424. Increase available operations so more issues are labelled on the next run.
From midweek this week the bot should start closing issues.  This will free up some operations for subsequent runs, so hopefully we won’t need more PRs like this (or at least not so often).
=> "Inactive" workflow: bump operations to 150

doc/api/colors_api.rst
closes #25521 
- documented exported colors array in colors.api
=> DOC: Added exported colors to colors.api

lib/mpl_toolkits/mplot3d/art3d.py, lib/mpl_toolkits/mplot3d/tests/test_legend3d.py
This fixes #25560 and legend for 3d plots by making sure that colors is an array.
=> making sure colors has the attribute size

environment.yml, requirements/testing/extra.txt
cf. https://github.com/jupyter/nbconvert/issues/1970
=> TST: Avoid broken nbconvert

.github/workflows/tests.yml
=> TST: Unbreak pyside65 by installing libxcb-cursor0

galleries/users_explain/text/README.txt
I wanted to add a reference/redirect to the examples page for text, labels, and annotations, similar to the user_explain\colors\README.txt file reference to <color_examples>, as I felt that there are similar examples and more examples that would be beneficial for the user.
I added similar text with a changed reference to <text_labels_and_annotations> in user_explain\text\README.txt.
I also made some minor capitalization/typo changes to the description of the page that felt necessary.
=> DOC: Update user_explain\text\README.txt to reference example page

lib/matplotlib/hatch.py
=> Bump invalid hatch removal

requirements/testing/mypy.txt
Mypy still moves quite fast, and sometimes changes are introduced which include either bugs or
additional checks which may be desireable to be fixed but should not start failing CI for reasons
unrelated to the change.
Recently mypy v1.2.0 introduced python/mypy#15015
I do intend to keep an eye on mypy releases and try them out.
Currently this requirements file is _only_ used for CI purposes (it is not included in the dev requirements).
=> Pin mypy to v1.1.1 for CI

lib/matplotlib/backends/backend_pgf.py, lib/matplotlib/tests/test_backend_pgf.py
=> pgf: Add clipping to text outputs

lib/matplotlib/tests/test_text.py, lib/matplotlib/text.py
Inspired the the exception from #25625.
=> More informative exception messages

azure-pipelines.yml, doc/devel/coding_guide.rst
Skip the checks on Azure Pipelines when the changes are all under `doc/` and/or `galleries/`.  We already did this for Github Actions at #25261 and Appveyor at #25383, so this completes the set.
Relevant Azure docs:
* [Including or excluding paths](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#paths)
* [More details on path/wildcard matching](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops)
Also added a small note to the dev guide about this skip being automatic.  Since this PR has changes both inside and outside the "exclude" directories, the tests should still run.  This seems worth checking as I couldn't see anything in the Azure docs that spells out what happens in this …
=> CI: skip Azure Pipelines for doc-only change

doc/devel/MEP/MEP13.rst, doc/users/prev_whats_new/changelog.rst, doc/users/prev_whats_new/github_stats_3.5.0.rst, galleries/examples/text_labels_and_annotations/font_family_rc.py, lib/matplotlib/backends/backend_pdf.py, lib/matplotlib/tests/test_dates.py, tools/github_stats.py
=> DOC: Fix duplicated words

lib/matplotlib/__init__.py, lib/matplotlib/font_manager.py, lib/matplotlib/rcsetup.py, lib/matplotlib/text.py
=> Doc: Replace matplotlibrc.template

doc/docutils.conf
Leverage docutils to automatically set the `loading` attribute of images to `"lazy"` in the HTML docs. This should hopefully improve performance, especially on cellular or low-bandwidth connections.
Closes #24331  
=> Enable lazy-loading of images in HTML docs

README.md
* Change to shields.io badges for some.
* Add conda version.
* Direct links to pypi.
* Link to devel-section of documentation instead of git book. (Maybe should be two links?)
* Better codecod-link.
=> Update, correct, and add badges/links

lib/matplotlib/axes/_axes.py
Close [#25758](https://github.com/matplotlib/matplotlib/issues/25758)
=> Doc : Updates default value for nonpositve parameter

galleries/examples/images_contours_and_fields/contour_corner_mask.py
=> Document default value of corner_mask in the corresponding example.

galleries/examples/event_handling/lasso_demo.py
- No need for a separate Datum data model, which feels a bit overengineered.
- Showing how to directly use the collection's array to store the relevant info and colormapping for display purposes seems more interesting.  This also allows directly using the return value of contains_point() to update the collection's array.
- In general it is a good idea to not store a reference to the canvas (which can be swapped underneath you).
=> Simplify lasso_demo example.

lib/matplotlib/patches.pyi
Fixes typing bug from me merging #25389 
The CI on that PR was from before we merge the typing so this was not checked.
=> MNT: update Shadow init signature

galleries/examples/mplot3d/tricontour3d.py, galleries/examples/mplot3d/tricontourf3d.py
The examples have been renamed (removing the _demo suffix).
=> Fix incorrect doc references.

pyproject.toml
List mpl_toolkits as being a first-party import rather than having it in a separate section and then removing the blank line before it via no_lines_before.
This doesn't change any of the actual sorting behavior.
=> Simplify isort config.

galleries/users_explain/text/fonts.py
=> Fix typo of missing quote in core font docs

lib/matplotlib/figure.py
Added variable "fig" for creating a figure
Closes #25900 
In PR #25900 the line missed "fig" variable , as it is essential to create the figure, hence added
=> #25900 update figure.py

doc/devel/development_workflow.rst
There seems to be consensus at #25857 that the advice to delete your main branch is no longer helpful.  I am not attempting to address the ensuing discussion in that issue(!) so am not linking it here.
=> DOC: don't advocate deleting main branch

lib/matplotlib/text.py
- Reorder logic in _get_xy_transform to make the case of xy0 not being specified (i.e. invalid bbox_name) fail more obviously.
- Document "offset fontsize" option.
See discussion at #25907.
=> Cleanups to Annotation.

galleries/examples/lines_bars_and_markers/stackplot_demo.py
This puts the legend key in the same order as the stacked data, with oceania at the top (near invisible), then europe, ..., with africa at the bottom.
Before:
After:
=> Reverse stackplot legend to match data display

lib/matplotlib/axes/_axes.py
=> Update performance note of hist() to mention stairs().

.github/workflows/nightlies.yml
Follow up to #25952
Sorry for this 😅 it should work now
=> Fix nightly CI

pyproject.toml
From the [virtualenv user guide](https://virtualenv.pypa.io/en/latest/user_guide.html#seeders):
>  Installing setuptools and wheel is disabled by default on Python 3.12+ environments.
This is just explicitly requiring setuptools that has otherwise been
provided by default. While we may be "saved" for a bit longer yet by
transitive dependency on setuptools (e.g. via setuptools_scm), better to
be explicit. (And even setuptools_scm is likely to drop the dependency,
actually, according to @henryiii)
- [N/A] *Plotting …
=> Add setuptools as an explicit build requirement

.github/workflows/stale.yml
To partially address concerns raised within #25938, this PR will have the stale action add a label to any issue it closes (currently "status: closed as inactive" but better suggestions welcome).  This will make it more explicit why the issues were closed and also make it easier to find and retrospectively review issues that were closed by the bot.
=> "Inactive" workflow: add close label for inactive issues

doc/users/installing/index.rst
~(Should follow PR #25950)~
The Scientific Python org is requesting that users of the https://pypi.anaconda.org/scipy-wheels-nightly/ package index migrate nightly builds to the new package index https://pypi.anaconda.org/scientific-python-nightly-wheels/ which will have community support moving forward.
- c.f. https://scientific-python.org/specs/spec-0004/
- c.f. PR #25950
Example showing all instances are fixed in the docs:
```console
$ git grep "scipy-wheels-nightly" -- doc
doc/users/prev_whats_new/github_stats_3.6.0.rst:* :ghpull:`23349`: CI: Remove old scipy-wheels-nightly uploads to ensure space
```
- [N/A] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue …
=> DOC: Use scientific-python-nightly-wheels for nightly build index

.github/workflows/nightlies.yml
=> Upload nightlies to new location

.github/workflows/tests.yml, lib/matplotlib/tests/test_backend_tk.py, lib/matplotlib/tests/test_backends_interactive.py
(cherry picked from commit 330969c1704dad0a83a238446d7ae210e4c34fa9)
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docst …
=> Backport PR #26005 on branch v3.7.x (Fix backend tests on CI)

.github/workflows/good-first-issue.yml
Started taking #25942 offtrack so integrated those comments into a revision and gonna hide em there. Also pulled in the why from the contributors guide 'cause wanted to make more explicit/set expectations that it's not a difficulty level thing. The language around duplicating PRs might be slightly charged, but it's another case where I'm hoping articulating why we want certain behavior might be more persuasive than just asking for it.
=> good first issue bot rewording

lib/matplotlib/cm.py
Closes #8965 
As suggested in the issue discussion, added alias to match the different spellings of gray and grey in the end of _gen_cmap_registry function in cm.py
cmap_d['grey'] = cmap_d['gist_grey'] = cmap_d['gray']
cmap_d['Grays'] = cmap_d['Greys']
cmap_d['gist_yerg'] = cmap_d['gist_yarg'] = cmap_d['gray_r']
cmap_d['grey_r'] = cmap_d['gray_r']
=> added alias to gray and grey match same colormaps

.github/workflows/cibuildwheel.yml
Following @QuLogic's suggestion in https://github.com/matplotlib/matplotlib/pull/26023#discussion_r1212575095:
For security best practices pin at the commit SHA corresponding to the last stable release and let Dependabot update the commit SHA and comment as new releases come out.
- c.f. https://github.com/scientific-python/upload-nightly-action
- [N/A] *New …
=> MNT: Use commit SHA of cibuildwheel action release

lib/mpl_toolkits/axes_grid1/axes_grid.py
- Simplify AxesGrid._init_locators.
- Simplify label on/off logic in AxesGrid:
* Inline _tick_only to its only calling method.  Also note that the kwargs to tick_only were previously named somewhat strangely (bottom_on = "turn off the bottom ticklabels and label", ditto for left_on).
* Simplify the condition checks for "L" mode (left only on for the first column, bottom only on for the last row).
followup to #26020
=> Cleanup AxesGrid

.github/workflows/nightlies.yml
Follow up PR to PR #25950.
* Use the [`scientific-python/upload-nightly-action` GitHub Action](https://github.com/scientific-python/upload-nightly-action) to upload the nightly wheels to the [`scientific-python-nightly-wheels` Anaconda Cloud package index](https://anaconda.org/scientific-python-nightly-wheels). For security best practices pin at the commit sha corresponding to the last stable release and let Dependabot update the commit sha and comment as new releases come out.
* Remove the workflow step for querying and removing all but the last 5 nightly wheel uploads to the scientific-python-nightly-wheels Anaconda Cloud package index as this is now centrally done by the Scientific Python org for all projects that upload to https://anaconda.org/scientific-python-nightly-wheels.
- c.f. …
=> CI: Use scientific-python/upload-nightly-action

.github/workflows/pr_welcome.yml
Update advice on what to do to get our attention:
* As establish at #24599, new contributors cannot ping the team, but just leaving a comment should hopefully be noticed by someone.
* Be more explicit about how long it's reasonable to wait because "a while" can mean very different things to different people.  I noticed one new contributor waited over a month.  I'm not wedded to "a week or so" but I think I've seen other team members suggest it directly to new contributors.
=> PR welcome: getting attention

.github/workflows/stale.yml
We agreed on the call to reduce the run frequency of the stale action.  This PR sets it to run only on Monday, Wednesday and Friday 01:30 UTC, following @jklymak's suggestion at https://github.com/matplotlib/matplotlib/pull/25938#pullrequestreview-1456264803.
=> 'Inactive' workflow: reduce run frequency

src/_tkagg.cpp
Otherwise the second dlclose() could clear the exception set by the first one.
See https://github.com/matplotlib/matplotlib/pull/25850#discussion_r1190464497
=> Get dlerror() immediately after dlclose() fails.

doc/conf.py
Closes #25590.  I think the consensus there is that we should just not show the type hints in the docs, at least for now.
=> Don't show type hints in rendered docs

galleries/examples/ticks/date_formatters_locators.py
Small formatting and modernizing updates.
=> Cleanup date tick locators and formatters

galleries/examples/specialty_plots/ishikawa_diagram.py
Closes #25222. Adds a fishbone plot to the specialty plots example in the docs. This PR is a continuation of https://github.com/matplotlib/matplotlib/pull/25248 except the plot is different. It's a simple representation of a fishbone plot which takes the input data as a nested list or tuple. The diagram will scale depending on the number of arguments that are passed to it.
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/8CgGPgvP/ishikawa.png' border='0' alt='ishikawa'/></a>
=> add ishikawa diagram to examples

.github/workflows/tests.yml
=> Install extra requirements when testing with 3.11 on GH

lib/matplotlib/image.py
=> Factor out common checks for set_data in various Image subclasses.

doc/users/next_whats_new/mpl_toolkit_pep420.rst, lib/mpl_toolkits/__init__.py, setup.py
=> ENH: switch mpl_toolkits to implicit namespace package (PEP 420)

.github/workflows/tests.yml
I had originally thought this was included in #25950 (hence why I had waited so long to merge it...), but apparently it was not.
Now that both pandas and numpy are uploading to the new location, this is the expected install location for new nightlies …
=> [MNT] Update nightly wheels install location

.github/workflows/tests.yml
We currently skip the GitHub Action tests for changes in the galleries, except for the `users_explain` gallery.  I think that’s just because `users_explain` was added more recently than we set up the skips.  This PR changes the filter so we skip the tests on all gallery-only changes.
=> Skip tests for users-explain gallery

galleries/users_explain/artists/artist_intro.rst, galleries/users_explain/artists/index.rst, galleries/users_explain/axes/axes_intro.rst, galleries/users_explain/axes/index.rst, galleries/users_explain/figure/figure_intro.rst, galleries/users_explain/figure/index.rst
This fixes user/explain/figure, user/explain/axes, user/explain/artists to have a more conventional TOC page, followed by all the sub-pages.  This is more like what sphinx expects, and makes the relevant sections show up as peers in the TOC.
Note there are no content changes other than the new TOC pages.
=> DOC: fix levels in user/explain/figure

lib/mpl_toolkits/mplot3d/art3d.py
Related to #26146 (maybe closes it).
=> Clarify how to get data from Line3D and fix formatting issue

galleries/users_explain/colors/colors.py
Motivated by https://github.com/matplotlib/matplotlib/pull/24691#issuecomment-1609268528
=> [Doc] Add note about (str, alpha) version added

lib/matplotlib/artist.py, lib/matplotlib/axes/_axes.py, lib/matplotlib/axes/_base.py, lib/matplotlib/axis.py, lib/matplotlib/backend_bases.py, lib/matplotlib/backends/backend_mixed.py, lib/matplotlib/backends/backend_pgf.py, lib/matplotlib/backends/backend_template.py, lib/matplotlib/cm.py, lib/matplotlib/colorbar.py, lib/matplotlib/contour.py, lib/matplotlib/figure.py, lib/matplotlib/image.py, lib/matplotlib/legend.py, lib/matplotlib/legend_handler.py, lib/matplotlib/lines.py, lib/matplotlib/offsetbox.py, lib/matplotlib/patches.py, lib/matplotlib/patheffects.py, lib/matplotlib/pyplot.py, lib/matplotlib/quiver.py, lib/matplotlib/sankey.py, lib/matplotlib/scale.py, lib/matplotlib/table.py, lib/matplotlib/testing/widgets.py, lib/matplotlib/text.py, lib/matplotlib/textpath.py, lib/matplotlib/widgets.py
From https://matplotlib.org/stable/devel/documenting_mpl.html#referencing-types
"Use full references `~matplotlib.colors.Normalize` with an abbreviation tilde in parameter types."
This should be all that misses a `~` but has a fully qualified name. Then there are quite a lot that doesn't have fully qualified names...
=> [Doc] Improve documentation types

lib/matplotlib/artist.py, lib/matplotlib/axes/_axes.py, lib/matplotlib/axes/_base.py, lib/matplotlib/axis.py, lib/matplotlib/backend_bases.py, lib/matplotlib/backends/backend_mixed.py, lib/matplotlib/backends/backend_pgf.py, lib/matplotlib/backends/backend_template.py, lib/matplotlib/cm.py, lib/matplotlib/colorbar.py, lib/matplotlib/contour.py, lib/matplotlib/figure.py, lib/matplotlib/image.py, lib/matplotlib/legend.py, lib/matplotlib/legend_handler.py, lib/matplotlib/lines.py, lib/matplotlib/offsetbox.py, lib/matplotlib/patches.py, lib/matplotlib/patheffects.py, lib/matplotlib/pyplot.py, lib/matplotlib/quiver.py, lib/matplotlib/sankey.py, lib/matplotlib/scale.py, lib/matplotlib/table.py, lib/matplotlib/testing/widgets.py, lib/matplotlib/text.py, lib/matplotlib/textpath.py, lib/matplotlib/widgets.py
=> Auto backport of pr 26186 on v3.7.x

galleries/plot_types/basic/stairs.py
Rebase of #25924 which seems to have stalled.  I couldn't push directly to their branch - maybe because it's main?  The `git` error was a bit cryptic.
Closes #25924, closes #22277.  The original PR also linked #23204, though that discussion is rather more involved than just step vs stairs. …
=> DOC: replaced step with stairs in basic plot types

doc/api/next_api_changes/behavior/25247-AL.rst
=> Better document the ContourSet API change.

galleries/examples/spines/spines.py
Fix rst formatting in https://matplotlib.org/devdocs/gallery/spines/spines.html:
=> DOC: fix rst formatting

lib/matplotlib/patches.py
=> update the doc string for fancyarrowpatch to link to annotate

doc/api/font_manager_api.rst
=> remove quote box from font_manager

lib/matplotlib/cbook.py, lib/matplotlib/colors.py, lib/matplotlib/transforms.py
In this PR some micro optimizations are applied to the matplotlib plotting. Optimizations selected are in methods that show in the profiling (cProfile).
Benchmark
```
Mean +- std dev: [main] 2.58 ms +- 0.23 ms -> [pr] 2.49 ms +- 0.23 ms: 1.04x faster
```
on script
```
import matplotlib
import pyperf
setup = """
x=[1,2,3,4,5]
y=[5,6,3,3,4]
n=6
def go():
for ii in range(n):
plt.figure(1)
plt.plot(x,y)
"""
runner = pyperf.Runner()
runner.timeit(name="mpl", stmt="go()", setup=setup)
```
- [N/A] new and changed code is …
=> Micro optimization of plotting

doc/api/next_api_changes/deprecations/26329-AL.rst, lib/mpl_toolkits/axisartist/axes_grid.py, lib/mpl_toolkits/axisartist/axes_rgb.py
They combine two relatively obscure features, are untested, and are readily provided by the axes_class API (nowadays we'd probably not provide such wrappers anyways).
Not a huge argument but the duplicated classes also make sphinx references somewhat tedious (one must provide nearly the entire module path to disambiguate the references).
=> Deprecate wrappers combining axes_grid1 and axisartist.

lib/matplotlib/axes/_base.py, lib/matplotlib/collections.py, lib/matplotlib/patches.py, lib/matplotlib/text.py
=> Some more micro optimizations

lib/matplotlib/sankey.py
=> Tweak Sankey docs.

galleries/examples/specialty_plots/mri_with_eeg.py
- Use more modern API
- Replace the unwieldy LineCollection by a simple plot-loop over the datasets
=> Simplify MRI with EEG example

doc/devel/dependencies.rst, setupext.py
Partially addresses #25179 
- [/] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [/] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [/] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
=> DOC: add note about manually downloading qhull + freetype

examples/misc/packed_bubbles.py, lib/matplotlib/dviread.py, lib/matplotlib/font_manager.py, lib/matplotlib/tests/test_axes.py, lib/matplotlib/tests/test_cbook.py, lib/matplotlib/tests/test_image.py, lib/matplotlib/tests/test_scale.py
(cherry picked from commit f7a8cabc1cf1ac9b35502f08e764d74d07d865ac)
=> Backport PR #26414: Fixes for pycodestyle v2.11

galleries/examples/widgets/check_buttons.py, galleries/examples/widgets/radio_buttons.py
Use an inset Axes for the radio buttons, and a mosaic to setup the check buttons. Also, add a note about the styling parameters.
=> Improve button widget examples a bit

doc/devel/dependencies.rst
I guess that `setuptools` is really a build dependency? `pybind11` was missing. `pyparsing` duplicated. Not sorting fully alphabetically since NumPy should be updated in #26443 (and it doesn't seem sorted anyway...).
=> [DOC] Update dependency documentation

.github/workflows/tests.yml
As mentioned here: https://github.com/matplotlib/matplotlib/pull/17497#discussion_r1100638438
=> Enable branch coverage for C/C++ code

lib/matplotlib/axes/_base.py, lib/matplotlib/figure.py, lib/matplotlib/gridspec.py
`check_patch` does not explain what this parameter is achieving.
=> Rename an internal parameter of _label_outer_x/yaxis()

lib/matplotlib/backends/backend_macosx.py, lib/matplotlib/backends/qt_compat.py, lib/matplotlib/tests/test_backend_qt.py, lib/matplotlib/tests/test_backends_interactive.py, src/_macosx.m
Support is largely copy-pasted from, and tests are shared with, the qt implementation (qt_compat._maybe_allow_interrupt, #13306), the main difference being that what we need from QSocketNotifier, as well as the equivalent for QApplication.quit(), are reimplemented in ObjC.
qt_compat._maybe_allow_interrupt is also slightly cleaned up by moving out the "do-nothing" case (`old_sigint_handler in (None, SIG_IGN, SIG_DFL)`) and dedenting the rest, instead of keeping track of whether signals were actually manipulated via a `skip` variable.
Factoring out the common parts of _maybe_allow_interrupt is left as a follow-up.
(Test e.g. with
`MPLBACKEND=macosx python -c "from pylab import *; plot(); show()"` followed by Ctrl-C.)
Closes #3991 (which was closed as cantfix in …
=> Fix support for Ctrl-C on the macosx backend.

galleries/examples/statistics/histogram_features.py
Remove reference to IQ scores and "Smarts" in figure; modify distribution parameters; update RNG syntax. Closes [#26604](https://github.com/matplotlib/matplotlib/issues/26604#issue-1867812030).
=> [Doc] Revise histogram features example (Closes #26604)

.github/workflows/tests.yml
=> Test with Python 3.12

galleries/examples/images_contours_and_fields/specgram_demo.py, galleries/examples/lines_bars_and_markers/cohere.py, galleries/examples/lines_bars_and_markers/csd_demo.py, galleries/examples/lines_bars_and_markers/psd_demo.py, galleries/examples/lines_bars_and_markers/spectrum_demo.py, galleries/examples/lines_bars_and_markers/xcorr_acorr_demo.py
I know that the mlab module is questioned, but I was still annoyed with a few inconsistencies in the examples.
=> [Doc] Improve DSP-related examples

lib/matplotlib/widgets.py
Do not render fully qualified names.
=> [Doc] Shorten documentation links in widgets

doc/api/backend_webagg_core_api.rst, doc/api/index_backend_api.rst, doc/api/prev_api_changes/api_changes_2.1.0.rst, lib/matplotlib/backend_bases.py, lib/matplotlib/backends/backend_webagg.py, lib/matplotlib/backends/backend_webagg_core.py
edit: looks like some references need to be fixed?
=> List the webagg_core module in the sphinx docs.

.github/workflows/cibuildwheel.yml
We should probably figure out tests #24711, but that shouldn't stop us from making the wheels at least.
Fixes #26557
=> MNT: Enable wheels for Python 3.12

lib/matplotlib/tests/test_ticker.py, lib/matplotlib/ticker.py
=> Test some untested Locator code

lib/matplotlib/tests/test_backends_interactive.py
If the final communication times out or asserts, there is nothing to enforce that the subprocess is killed.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and …
=> TST: Ensure test_webagg subprocess is terminated

galleries/examples/text_labels_and_annotations/line_with_text.py, galleries/examples/userdemo/connectionstyle_demo.py, galleries/users_explain/artists/paths.py, galleries/users_explain/axes/arranging_axes.py, galleries/users_explain/axes/axes_scales.py, galleries/users_explain/figure/figure_intro.rst, lib/matplotlib/figure.py, lib/matplotlib/legend.py
=> DOC: Fix some small issues

.github/workflows/cibuildwheel.yml
I spent too much time trying to figure out why there was two jobs called "Build CI wheels / Build wheels on ubuntu-20.04" in #26695, so I thought it was better to add information about which architectures the wheels are built for to make it a bit more clear...
=> Improve naming of cibuildwheel jobs

setup.py
For bookkeeping purposes, mostly. …
=> Add a Python 3.12 classifier

doc/_static/mpl.css, doc/api/index.rst
Following up on the discussion in #26623 / #26624, I've tried to make this as informative and concise as possible.
**Note: This is a proposal, I'm not wedded to any of the details, and I'm also fine to close if this does not go into the right direction.**
=> [DOC] Enhance API reference index

lib/matplotlib/artist.py
Related to #26522 
Check the type before comparison to avoid non-informative errors.
=> Check type for set_clip_box

lib/matplotlib/axis.py
These were deprecated in c3f87d4 and later made unused, but not removed.
=> Remove unused Axis private init helpers.

doc/api/next_api_changes/removals/26798-OG.rst, doc/api/toolkits/mplot3d/axes3d.rst, lib/mpl_toolkits/mplot3d/axes3d.py
=> Remove deprecated methods and attributed in Axes3D

doc/devel/contribute.rst
Made some content changes to the contribute page in #26737 that I think make it a little clearer (I really like the fork icon) so manually backporting it
=> Backport changes to contribute from PR #26737

lib/matplotlib/cbook.py
This does not change functionality. The code path for `safe_first_element` is `_safe_first_finite(skip_nonfinite=False)` which
is separate code block and does not interact with the
skip_nonfinite=True case. IMHO this is more readable.
Also add a comment on the exception handling recently modified in #26806.
=> Reoder safe_first_element() and _safe_first_finite() code

lib/matplotlib/container.py, lib/matplotlib/tests/test_container.py
=> Fix issue with non-string labels and legend

src/_path.h, src/mplutils.h
Also, the final element is never accessed.
Purpose is to have a "cleaner" mplutils.h (with the long term plan to reduce the number of "helper" .h-files as part of the pybind11 transition).
- [N/A] …
=> [MNT] Move NUM_VERTICES from mplutils.h to the only file it is used in

lib/matplotlib/axes/_base.py, lib/matplotlib/axes/_base.pyi, lib/matplotlib/pyplot.py
Fixes [#25974](https://github.com/matplotlib/matplotlib/issues/25974). 
-->
=> [MNT]: Cleanup ticklabel_format (style=)

doc/api/next_api_changes/removals/26852-OG.rst, lib/matplotlib/dates.py, lib/matplotlib/tests/test_dates.py
=> Remove Julian date support

galleries/users_explain/artists/transforms_tutorial.py
- In the Axes coordinates example, point to the "labelling subplots" example which is arguably a better approach for labelling (it ensures that the labels stay aligned even if the axes have different widths). The current example in the tutorial is still useful for pedagogical purposes, though.
- Shorten the entries in the transformations tables to avoid having overly long lines.
=> Tweak transforms tutorial.

ci/mypy-stubtest-allowlist.txt, lib/matplotlib/offsetbox.pyi, lib/matplotlib/rcsetup.pyi, lib/matplotlib/transforms.pyi
Mark the expected interface for some things such as Transform.input_dims as read-only via a property and remove redundant versions in subclasses
Same for some offsetbox code
Fix rcsetup ignores
=> [TYP] Remove some stubtest allowlist entries

doc/users/prev_whats_new/whats_new_3.8.0.rst, galleries/users_explain/text/mathtext.py
Closes #26968 (probably) by explaining difference between mathtext and usetex.
=> DOC: clarify usetex versus mathtext

galleries/examples/ticks/date_concise_formatter.py, galleries/examples/ticks/date_formatters_locators.py, galleries/examples/units/basic_units.py, galleries/users_explain/axes/axes_units.py, galleries/users_explain/axes/index.rst
=> DOC: add units to user/explain [ci doc]

environment.yml
Updates environment.yml to match requirements in the requirements/ folder files.
Related to https://github.com/matplotlib/mpl-sphinx-theme/issues/80
=> MAINT: Update environment.yml to match requirements files

doc/users/project/index.rst, doc/users/release_notes.rst
Reformatted the release notes as per the style conventions at https://matplotlib.org/devdocs/devel/document.html#section-formatting.
=> Formatted docs

tools/generate_matplotlibrc.py
https://peps.python.org/pep-0394/
Addresses part of the issues identified on AIX in https://github.com/matplotlib/matplotlib/pull/26621#issuecomment-1766391015
=> BLD: use python3 for shebang consistent with pep-394

doc/api/figure_api.rst
so that we have the sections:
- Figure
- SubFigure
- FigureBase
- Helper functions
Follow-up to #26629.
=> DOC: Move figure member sections one level down

doc/devel/release_guide.rst
Updated the developer release guide to follow the matplotlib formatting standards and conventions (https://matplotlib.org/devdocs/devel/document.html#section-formatting). This PR closes one of tasks listed in the issue https://github.com/matplotlib/matplotlib/issues/26862
=> Update developer release guide to follow conventions

doc/devel/development_workflow.rst
Accidentally missed this in my review on #26998 but automated tests makes more sense as a standalone then as a subsection of commit history tasks.
=> changed automated tests from subsection to section in workflow

doc/devel/dependencies.rst, doc/devel/development_setup.rst, doc/users/installing/index.rst
This PR simplifies the titles of a couple of sections on the dependency page, mostly by removing building and Matplotlib because I think those are a given cause it's the dependency page. It makes the right hand side more scannable.
-->
=> DOC: concise dependency heading + small clarifications

galleries/examples/color/named_colors.py
and slightly reword their description
=> Link xkcd color survey in named colors example

src/_macosx.m
The `PyOS_InputHook` is used to run our event loop while waiting on standard input from the user. This means we should flush our events while waiting for any input from the user so the figures are responsive.
Rather than reverting the cleanup commit https://github.com/matplotlib/matplotlib/commit/ec6717aa7ad66868a3dc6186af031b970bb21c8e I tried to rewrite that in the newer NS framework utilities instead of all of the CF work that was being done. I added comments along the way indicating what is actually happening for the next time someone has to dig into this.
Test-case from the linked Issue:
```python
import matplotlib
from matplotlib import cm
plt.style.use("_mpl-gallery")
X = np.arange(-5, 5, 0.25)
Y = np.arange(-5, 5, 0.25)
X, Y = …
```
=> FIX: Add PyOS_InputHook back to macos backend

doc/devel/development_setup.rst
Per https://github.com/matplotlib/matplotlib/issues/27168#issuecomment-1784103537, figured it wouldn't hurt to signpost "hey, we have a troubleshooting section over there (that links to our other troubleshooting section)"  Went slightly more general than that comment suggested just because there's more than just Windows mentioned in the troubleshooting guide.
=> DOC: link out to troubleshooting guide in install

galleries/users_explain/figure/figure_intro.rst, galleries/users_explain/figure/interactive.rst
Following issue #27144, this PR updated the suggested improvement to include the classic notebook versions in the documentation. I also made some changes to the writing of the section and simplifying the text.
=> Fixing Matplotlib Notebook Text

galleries/examples/subplots_axes_and_figures/axes_box_aspect.py, galleries/examples/text_labels_and_annotations/angle_annotation.py
Two files [axes_box_aspect.py](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/galleries/examples/subplots_axes_and_figures/axes_box_aspect.py) and [angle_annotation.py](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/galleries/examples/text_labels_and_annotations/angle_annotation.py) have been updated to meet formatting standards. 
This is for issue #26862
=> Updated axes_box_aspect.py and angle_annotation.py to regularize formatting

doc/users/faq.rst, galleries/users_explain/figure/backends.rst, galleries/users_explain/figure/figure_intro.rst, galleries/users_explain/figure/interactive.rst, galleries/users_explain/quick_start.py, lib/matplotlib/figure.py
Inspired by issues like: https://github.com/matplotlib/matplotlib/issues/13988
More "Hello worlds" welcome.
Output: https://output.circle-artifacts.com/output/job/1cef73ac-7b2b-4f72-b5b0-38acc20c9306/artifacts/0/doc/build/html/users/explain/figure/backends.html#debugging-the-figure-windows-not-showing
=> [DOC] debug backends

doc/devel/communication_guide.rst, doc/users/project/mission.rst
Follow up to #26703, last winter(ish) @melissawm, @noatamir, and me worked on writing up the reasoning for the communications guidelines and objectives for the strategy. I figure especially w/ the move to the main repo, it's worth having it in the doc as grounding for the guidelines.
=> DOC: reasoning for communications guidelines

galleries/examples/color/README.txt, galleries/examples/color/named_colors.py, galleries/examples/images_contours_and_fields/image_demo.py, galleries/examples/images_contours_and_fields/pcolor_demo.py, galleries/examples/text_labels_and_annotations/accented_text.py, galleries/examples/text_labels_and_annotations/annotation_demo.py, galleries/examples/text_labels_and_annotations/font_file.py, galleries/examples/text_labels_and_annotations/legend_demo.py, galleries/users_explain/axes/constrainedlayout_guide.py, galleries/users_explain/axes/legend_guide.py, galleries/users_explain/axes/tight_layout_guide.py, galleries/users_explain/colors/colormap-manipulation.py, galleries/users_explain/colors/colormaps.py, galleries/users_explain/text/text_intro.py
Mostly removing "in Matplotlib" (where it is clear that it's a Matplotlib example illustrating how to do stuff in Matplotlib), and removing redundant subtitles.
=> Copy-edit various examples.

doc/devel/development_setup.rst, doc/devel/development_workflow.rst
* fix grammar in setup
* fix formatting in workflow
=> DOC: minor fixes to dev workflow

doc/_static/mpl.css, doc/users/project/license.rst
Figured this was a good place to try out dropdowns, to address:
> We should consider extending the second page to include the text of all the other files in https://github.com/matplotlib/matplotlib/tree/main/LICENSE
_Originally posted by @tacaswell in https://github.com/matplotlib/matplotlib/issues/27277#issuecomment-1796293605_
https://output.circle-artifacts.com/output/job/8dced7bf-bcdc-4044-a940-8030532a253e/artifacts/0/doc/build/html/users/project/license.html
<strike>I'm not keen on the styling but figure this is the cleanest way to have all the information on one page. </strike>
=> DOC: added rest of licenses to license page

lib/matplotlib/projections/__init__.py
Needed for the same reasons as #27178 (Namely that we should not be failing on import just because mpl_toolkits is broken), but mpl 3.6 presents with an AttributeError rather than ImportError
See discussion in #26827 and #27289
Just expanded liberally in case there are other presentations we have not seen
=> Expand 3D import to handle any exception not just ImportError

src/_qhull_wrapper.cpp, src/meson.build
Cherry-picked out of #23787, rebased and modified for Meson.
=> Use pybind11 for qhull wrapper

galleries/plot_types/basic/stairs.py
closes #27307 that redirects step to stairs 
- [ n.a] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ n.a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [n.a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
=> Doc: Step redirect

.github/workflows/cibuildwheel.yml, azure-pipelines.yml, doc/users/github_stats.rst
=> Fix CI on v3.7.x branch

lib/matplotlib/figure.py, lib/matplotlib/tests/test_figure.py
=> Implement SubFigure.remove.

galleries/examples/lines_bars_and_markers/stackplot_demo.py
Y axis says it's million but numbers are in thousands, so trying to make y-axis show a million. (demo for a how to contribute talk)
- [n/a ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ n/a] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [n/a ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
=> DOC: clarify stackplot limits

.gitignore, lib/matplotlib/tests/test_datetime.py
Added code for `test_fill` in `test_datetime.py` as requested in #26864 
Image of an output:
=> Add test_fill in test_datetime.py

lib/matplotlib/tests/test_datetime.py
Smoke test for `Axes.stem` using datetime data in `lib/matplotlib/tests/test_datetime.py`. This PR addresses one of the tasks listed in https://github.com/matplotlib/matplotlib/issues/26864
The image displays the plot of the test case:
=> Added smoke test for Axes.stem

doc/devel/development_setup.rst, doc/devel/index.rst, doc/users/installing/dependencies.rst, doc/users/installing/index.rst
Based on discussion in #27386 and #22866, it seems consensus is towards the documents under `/devel` being version independent. Since the dependencies are tracked to the version, I moved the `dependencies` document  from `/devel` to `users/installing/` and updated the cross references.  ETA: this move is specifically intended so that `dependencies.html` does not get caught in a bulk redirect to the development version.
* `/devel/dependencies` -> `/users/installing/dependencies`
* changed heading levels so that install FAQ and Troubleshooting are sections of the installation document 
* removed dependencies from `/devel/index` because its explicitly listed as a step in development_setup
* removed environment_variables from `/devel/index` and add a link in the `build options` section of …
=> DOC: Moved dependencies under install because they're version dependent

doc/devel/testing.rst, doc/users/installing/dependencies.rst
Learned about the test_viz tool from #27470 so added it to tests docs.
=> Doc: visualizing_tests and `triage_tests` tools

lib/matplotlib/tests/test_datetime.py
add code for Axes.stairs in test_datetime.py as requested in https://github.com/matplotlib/matplotlib/issues/26864.
=> Added Axes.stairs test in test_datetime.py

lib/mpl_toolkits/mplot3d/art3d.py, lib/mpl_toolkits/mplot3d/axes3d.py
=> [Doc] Improve/correct docs for 3D

lib/mpl_toolkits/axisartist/axislines.py, lib/mpl_toolkits/axisartist/grid_finder.py
In the spirit of  #27517 I tried to find other places where something similar can be achieved.
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write …
=> Micro-optimizations related to list handling

lib/matplotlib/markers.py, lib/matplotlib/markers.pyi
The second commit removes mentioning that None is deprecated. Not updated in https://github.com/matplotlib/matplotlib/pull/25456 (?).
=> [Doc] Minor consistency changes and correction of Marker docs

lib/matplotlib/legend.py
Best legend location is slow as it is. May just as well avoid additional list allocations where possible.
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#w …
=> Best-legend-location microoptimization

.github/workflows/tests.yml, doc/users/installing/dependencies.rst, doc/users/installing/environment_variables_faq.rst, doc/users/installing/index.rst, doc/users/installing/troubleshooting_faq.inc.rst, galleries/examples/shapes_and_collections/hatch_demo.py, galleries/examples/shapes_and_collections/hatch_style_reference.py, galleries/examples/user_interfaces/svg_histogram_sgskip.py, galleries/users_explain/animations/blitting.py, galleries/users_explain/figure/backends.rst, galleries/users_explain/figure/event_handling.rst, galleries/users_explain/figure/interactive_guide.rst, lib/matplotlib/animation.py, lib/matplotlib/backends/backend_qt.py, lib/matplotlib/tests/test_backends_interactive.py, meson_options.txt, src/_macosx.m
Our minimum supported Mac OS X/macOS version is 10.12, which is [when the name changted to macOS](https://en.wikipedia.org/wiki/MacOS#macOS). So change mentions of OSX to macOS where appropriate in code comments and docs.
=> Use macOS instead of OSX in comments/docs

galleries/examples/event_handling/viewlims.py
- No need to subclass Rectangle; a plain callback is fine.
- ax.get_xlim/ylim seems more idiomatic than accessing viewLims.
- Skip duplicated code in initialization.
Closes #25979.  Supersedes #26166.
=> Cleanup viewlims example.

lib/matplotlib/text.py
Changed link in see also box in https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.annotate.html
Link currently points to https://matplotlib.org/devdocs/users/explain/text/annotations.html#plotting-guide-annotation, changed so it goes to  https://matplotlib.org/devdocs/users/explain/text/annotations.html b/c  there's no good reason to start in the middle.
=> DOC: Updated link in annotation API docs to point to annotation user guide

.github/dependabot.yml
Related to PR #27563, this PR groups dependabot updates to reduce the number of PRs, which is also required for CI/CD to not break in certain paired GitHub Actions.
- c.f. sp-repo-review [GH212: Require GHA update grouping](https://learn.scientific-python.org/development/guides/gha-basic/#GH212)
c.f. https://github.com/scientific-python/cookie/pull/348, https://github.com/scikit-hep/pyhf/pull/2413
- [N/A] *Plotting related* features are demonstrated in an …
=> CI: Group dependabot updates

.github/workflows/nightlies.yml
This is a followup to #27563, as it looks like I missed a copy of the artifact name in the `nightlies.yml` workflow. We instead need to look for a pattern instead of a single name since upload names are now unique.
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features …
=> ci: Update nightly upload for artifacts v4

.github/PULL_REQUEST_TEMPLATE.md
As @QuLogic pointed out in https://github.com/matplotlib/matplotlib/pull/27310#issuecomment-1887972417, the pr template now links to the wrong section so changed that. Also tried making the "go to API changes doc" clearer , but don't love the use of admonitions here.
=> MNT: fix api changes link in PR template

.flake8, galleries/examples/color/individual_colors_from_cmap.py
Closes #27671 by adding an example to show using colormaps in places where we need discrete sets of colours.
The plots themselves could be more interesting, but I guess the more interesting we make them the more code there will be to distract from the main point.
=> DOC: selecting individual colors from a colormap

lib/matplotlib/tests/test_table.py
Tests that table doesn't participate in the unit pipeline by testing that it doesn't convert datetimes.
=> MNT: test that table doesn't try to convert unitized data

galleries/users_explain/axes/legend_guide.py
Th incorrect reference was accidentally commited in #27731.
=> Fix incorrect API reference in docs

README.md
Closes #27782. The link to the citation page on the read me file was broken, so I reverted it back to the previous link (https://matplotlib.org/stable/users/project/citing.html) which seems to work.
=> Update README.md to fix citation link

lib/matplotlib/axes/_axes.py, lib/matplotlib/mlab.py
Some corrections and small rewrites.
=> DOC: Update violinplot() docs

lib/matplotlib/collections.py
Fixes https://github.com/matplotlib/matplotlib/issues/27826 - I'm guessing the author of that issue copied the example in the docstring, and then found it didn't work for large values. Since the text says "creates three legend elements, one for each color" I think it makes sense to put the `num=None` kwarg here to make sure "one for each color" remains true for larger data sizes.
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and- …
=> Make example in legend_elements doc more generalisable

lib/matplotlib/tests/test_axes.py
closes #23839
This implements the suggestion from @timhoffm in https://github.com/matplotlib/matplotlib/issues/23806#issuecomment-1239069010
=> TST: adding tests of current clear behavior on ticks

galleries/examples/animation/random_walk.py, galleries/users_explain/animations/animations.py, lib/matplotlib/lines.py
- use `set_data_3d`
- cross-reference `Line2d` `set_data`, `set_xdata`, `set_ydata`
- Rewrite parts of the FuncAnimation description
Inspired through #27830.
=> DOC: Update some animation related topics

doc/conf.py
Should fix https://github.com/matplotlib/matplotlib/issues/27876. I'm not sure if theres a way of testing this apart from merging and seeing what happens... ?
=> Fix devdocs version switcher

.flake8, lib/matplotlib/pyplot.py, tools/gh_api.py
This got accidentally ignored in #25147.
We want D213 (#17125, #17193)
https://matplotlib.org/devdocs/devel/document.html#quote-positions
=> FIX: Restore D213 in flake8

README.md
The contribute link in the project's README.md currently links to:
https://matplotlib.org/devdocs/devel/contributing.html
However, this page no longer exists. This PR changes the link to:
https://matplotlib.org/devdocs/devel/contribute.html …
=> DOC: Fix dead link in README

src/_backend_agg.cpp, src/_backend_agg.h, src/_backend_agg_basic_types.h, src/_image_resample.h, src/_path.h, src/_tkagg.cpp, src/_ttconv.cpp, src/array.h, src/ft2font.h, src/ft2font_wrapper.cpp, src/mplutils.h, src/path_converters.h, src/py_adaptors.h
Either remove unused, or switch to more specific ones.
=> Clean up headers in extensions

doc/devel/development_setup.rst
This looks much better and is consistent with development_workflow.rst and release_guide.rst, which rely on the same mechanism.
=> Highlight development_setup code snippets as bash, not python.

lib/matplotlib/mpl-data/images/hand.svg
Current url points to online sextoys store.
=> Update "Created with" url in hand.svg

lib/matplotlib/axes/_axes.py, lib/matplotlib/tests/test_axes.py
=> Clarify error message for bad-dimensionality in pcolorfast().

lib/matplotlib/collections.py, lib/matplotlib/contour.py, lib/matplotlib/patches.py, lib/matplotlib/tri/_tricontour.py
Even the builtin cairo backend supports it now.
=> Remove documentation that some backends don't support hatching.

.github/workflows/cibuildwheel.yml, pyproject.toml, setup.py
This is in preparation for an mpl prerelease of 3.8.4rc1 (built against numpy beta, hence rc)
We may wish to do the same change to the CIBW job on `main` (@QuLogic thoughts?) as that will also affect the builds uploaded to nightly.
I did it just for the release branch for now, in part because I needed to unpin in setup.py anyway.
=> Unpin numpy 2, build against prerelease numpy in CIBW

.github/workflows/cibuildwheel.yml, doc/_static/switcher.json, doc/users/github_stats.rst, doc/users/prev_whats_new/github_stats_3.8.3.rst, doc/users/release_notes.rst, pyproject.toml
Conflicts (so pay the most attention to these):
CONFLICT (content): Merge conflict in .github/workflows/cibuildwheel.yml
CONFLICT (content): Merge conflict in pyproject.toml
CONFLICT (modify/delete): setup.py deleted in HEAD and modified in v3.8.x.  Version v3.8.x of setup.py left in tree.
In particular, since the numpy pin is included in the build requires in pyproject.toml, I have removed the `--pre` handling from cibw that was making np2 compatible builds on main.
- Backport PR #27921: Avoid modifying user input to Axes.bar
- Backport PR #27875: macosx: Clean up single-shot timers correctly
- Backport PR #27933: Update "Created with" url in hand.svg
- Backport PR #27975: DOC: Fix typo in ```ax.transData.inversed()```
- Backport PR #27975: DOC: Fix typo in ```ax.transData.inversed()``` …
=> Merge up v3.8.4

lib/matplotlib/artist.pyi
This just separates the case where we know more about the the return type of `findobj`.
This was requested by https://github.com/pydata/xarray/pull/8889#discussion_r1544463148
=> Be more specific in findobj return type

doc/devel/style_guide.rst
as proposed in https://github.com/matplotlib/matplotlib/issues/21817#issuecomment-983705359 and #26388
and already used in #26402.
Closes #21817.
=> DOC: Clarify interface terminology

galleries/examples/subplots_axes_and_figures/invert_axes.py
=> DOC: Improve inverted axis example

doc/install/dependencies.rst
=> Document Qt5 minimal version.

requirements/doc/doc-requirements.txt
Interactions between pydata-sphinx-theme, mpl-sphinx-theme, and sphinx broke
=> DOC: exclude sphinx 7.3.*

galleries/users_explain/text/pgf.py, lib/matplotlib/backends/backend_pgf.py
- Remove vague mention of outdated tex packages (first because it was written more than 10 years ago so packages too old for backend_pgf compatibility are unlikely to be seen nowadays, and second because if we don't actually provide compatibility bounds such a statement is not particularly useful).
- Fix consistency between xetex/xelatex, and also for capitalization.
- Remove an unnecessary encoding step in PdfPages by directly formatting bytes.
=> Minor maintenance on pgf docs/backends.

lib/matplotlib/hatch.py
No big deal, but can still be better not to get a deprecation message in 3.9 that says that this feature is removed in 3.9... …
=> Bump custom hatch deprecation expiration

requirements/doc/doc-requirements.txt
This is a test of running the updated theme; I'll make a final release and un-draft this PR  once this build looks good.
=> DOC: Bump mpl-sphinx-theme to 3.9

lib/matplotlib/tests/test_axes.py, lib/matplotlib/tests/test_lines.py, lib/matplotlib/tests/test_patheffects.py, lib/mpl_toolkits/mplot3d/tests/test_axes3d.py
Closes #28168
Closes #28145
Closes #28034
Some tolerances were just a bit tight and for some reason fell on the other side here (Including a couple that rounded to the same number as the tolerance).
One test I swapped from "if you are one of these archetectures add a tolerance" to "if you are x64, don't add a tolerance".
Checked the images, most of these were not human-visible. The line collection test had the largest change, but already had a large enough tolerance on other platforms, so just extended that.
=> [TST] Bump some tolerances for Macos ARM

.github/workflows/tests.yml, azure-pipelines.yml
I just followed the instructions in the last failing build, so hopefully this is fine.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#wri …
=> CI: Fix font install on macOS/Homebrew

lib/matplotlib/pyplot.py
Improves typing for static type checkers such as pyright.
Close #28022 
=> Add extra imports to improve typing

galleries/plot_types/arrays/README.rst
Is on the level of typo, removed the colon from the Gridded Data heading 😓 b/c we don't colons after any of the others and I didn't notice this in #26328
=> [DOC] plot type heading consistency

lib/matplotlib/axes/_axes.py
=> Solved #28296 Added missing comma

lib/matplotlib/colorbar.py
=> Removed drawedges repeated definition from function doc string

.github/workflows/cibuildwheel.yml, .pre-commit-config.yaml
* Add generation of GitHub artifact attestations to built sdist and wheel before upload. c.f.:
- https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/
- https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds
This PR is related to https://github.com/scientific-python/summit-2024/issues/9 so cc @QuLogic for review. c.f. https://github.com/scikit-hep/pyhf/pull/2473 for reference.
- [N/A] *Plotting related* features are …
=> CI: Add GitHub artifact attestations to package distribution

galleries/examples/mplot3d/intersecting_planes.py
=> DOC: Add example for 3D intersecting planes

galleries/examples/lines_bars_and_markers/multicolored_line.py
I opened issue #28242, which is asking for better ways to plot a line with a color at each point assigned by a third value. @timhoffm suggested a nice way to do this. This PR adds a new example that implements his improved method.
@timhoffm said this should replace [this example](https://matplotlib.org/devdocs/gallery/color/color_by_yvalue.html). @rcomer also thought [this example](https://matplotlib.org/stable/gallery/lines_bars_and_markers/multicolored_line.html) could be replaced by it. I haven't removed either of the examples since I want to be clear on the expectations before I start deleting previous work.
The approach in previous methods produce results that look something like this:
The new approach in the provided example applied to the same plot produces this:
=> DOC: New color line by value example

lib/matplotlib/text.py
Closes #28358 by documenting the effect of wrap.
=> DOC: Clarify scope of wrap.

lib/matplotlib/mathtext.py
We already check the state of the antialiasing rcParam in MathTextParser._parse_cached; we just need to do the same with the hinting rcParam (which is hidden behind backend_agg.get_hinting_flag, but that just converts the rcParam to its freetype-specific representation).
=> Take hinting rcParam into account in MathTextParser cache.

.github/workflows/circleci.yml
#28413 introduced a pre-commit failure for the line length, that we missed amongst all the other CI failures.
=> Fix Circle yaml line length

.github/workflows/circleci.yml, .yamllint.yml
Follow up to #28425 and #28413
YAML is sometimes confusing and puts the ending `\n` on a multiline string with `|`, which made the job fail.
I moved the comment, hopefully it doesn't mess with dependabot being able to automatically update it, but the line was still too long with the comment on the same line.
=> Fix circleci yaml

lib/matplotlib/__init__.py, lib/matplotlib/axes/_axes.py
See https://github.com/matplotlib/matplotlib/issues/9844#issuecomment-2167954868
=> DOC: Improve doc wording of data parameter

lib/matplotlib/axis.py, lib/matplotlib/pyplot.py
To clarify expectations c.f. https://github.com/matplotlib/matplotlib/issues/23272#issuecomment-2189516852
=> DOC: Document kwargs scope for tick setter functions

lib/matplotlib/figure.py, lib/matplotlib/figure.pyi, lib/matplotlib/tests/test_pickle.py
=> Fix pickling of SubFigures

lib/matplotlib/figure.py, lib/matplotlib/tests/test_figure.py
=> FIX: stale root Figure when adding/updating subfigures

lib/matplotlib/backends/registry.py, lib/matplotlib/tests/test_backend_registry.py, lib/matplotlib/tests/test_backend_template.py
Closes #28432
This adds checks to avoid changing cases of `module://` names.
Entry point names and default names will still be normalized.
Adds a test to ensure loading is case sensitive as well as a unit test of the normalization function (which is private, but fairly central)
=> Do not lowercase module:// backends

doc/users/next_whats_new/mpl_toolkit_colorbar_pad.rst, lib/mpl_toolkits/axes_grid1/axes_grid.py, lib/mpl_toolkits/axes_grid1/tests/test_axes_grid1.py
This PR removes the inconsistent pad between the axes and the colorbar of `ImageGrid` with `cbar_mode="single"` and therefore closes #28343. Instead of changing the test image I updated the image creation. I am not entirely sure I made the "changelog" entries correctly for mpl - let me know if any changes are required.
=> FIX: colorbar pad for `ImageGrid`

lib/matplotlib/stackplot.py
=> DOC: Add version directive to hatch parameter in stackplot

lib/matplotlib/axes/_base.py
=> cycler signature update.

doc/conf.py
So I think we should probably just wait for https://github.com/sphinx-gallery/sphinx-gallery/pull/1355 b/c fix in CI means no rebases, but this should suppress the warning message and let the docs build.
=> DOC: hack to suppress sphinx-gallery 17.0 warning

doc/devel/development_workflow.rst
(This change was done during SciPy2024 sprints)
It's a good practice to set up the branch tracking when pushing changes so I have changed the push command to have the tracking. However, this doesn't work in git versions lower than 1.7 so I added a tab without this for previous versions. This is how it looks like:
=> Add branch tracking to development workflow instructions

lib/matplotlib/animation.py
Removes old and out of date todo's from animation.py
Closes #28626
=> remove out of date todos on animation.py

galleries/examples/subplots_axes_and_figures/axhspan_demo.py
Because there are multiple axes here, titling the axes w. the function it's demoing helps highlight what's going on. Basically, would have found titles helpful for the discussion in https://github.com/matplotlib/matplotlib/issues/28152#issuecomment-2274589927
=> Doc: add axes titles to axhspan/axvspan

lib/matplotlib/patches.py
Fixed arrowstyle doc interpolation in FancyPatch.set_arrow() #28698.
=> Fixed arrowstyle doc interpolation in FancyPatch.set_arrow() #28698.

galleries/users_explain/artists/transforms_tutorial.py, lib/matplotlib/axes/_axes.py
=> DOC: Clarify axhline() uses axes coordinates

.github/workflows/tests.yml, lib/matplotlib/tests/test_axes.py, lib/matplotlib/tests/test_contour.py, lib/mpl_toolkits/mplot3d/tests/test_axes3d.py
It works locally mostly, but let's see how things go on CI.
=> ci: Enable testing on Python 3.13

lib/matplotlib/artist.py, lib/matplotlib/cm.py
By introducing an explicit override function, we can move the formatting code to ScalarMappable, where it logically belongs. Also, artist.py does no longer depend on colors.py and cm.py, which simplifies module dependencies.
=> MNT: Better workaround for format_cursor_data on ScalarMappables

lib/matplotlib/_api/__init__.py, lib/matplotlib/tests/test_cbook.py
Python 3.12 added the `skip_file_prefixes` argument, which essentially does what this helper function does for us.
Technically, I think the old implementation would set the stack level to the tests, if called in one, but this one doesn't. However, that shouldn't be a problem, as either 1) warnings are errors, or 2), we catch the warning with `pytest.warns` and don't see the stack level.
- [n/a] *New Features* and *API Changes* are noted with a [directive …
=> Simplify _api.warn_external on Python 3.12+

doc/devel/contribute.rst, doc/devel/index.rst
Discussion from #28335 had me thinking that my issues w/ the guidance being in the wrong place was that triage is its own category of contribution and therefore it should get a section in `contribute.html` 
This also incorporates the guidance from #28335 (particularly language/reasoning from https://github.com/matplotlib/matplotlib/pull/28335#issuecomment-2146751622) and therefore supercedes it.
=> Doc: added triage section to new contributor docs

galleries/users_explain/figure/event_handling.rst, galleries/users_explain/figure/interactive.rst, galleries/users_explain/figure/interactive_guide.rst
Interactivity is useful even when not working with "data" (e.g. when plotting mathematical equations).
Closes #19037 (the doc hierarchy issue also mentioned has actually already been fixed).
=> Tweak interactivity docs wording (and fix capitalization).

environment.yml
Following #27797, so that conda users automatically have everything they need to build the docs.  I tested this by successfully building the docs in a new GitHub Codespace.
=> Add sphinxcontrib-video to environment.yml

.circleci/config.yml, doc/missing-references.json
locks out numpy version we think is breaking our docs build do to https://github.com/numpy/numpy/pull/26904
=> quick fix dev build by locking out numpy version that's breaking things

lib/matplotlib/backends/qt_editor/figureoptions.py, lib/matplotlib/image.py
=> Fix places where "auto" was not listed as valid interpolation_stage.

lib/matplotlib/animation.py
=> Add Returns info to to_jshtml docstring

doc/api/next_api_changes/removals/28767-REC.rst, lib/matplotlib/contour.py, lib/matplotlib/contour.pyi, lib/matplotlib/tests/test_contour.py
Expire the v3.8 deprecations for `ContourSet`.  ~The two methods removed from `ContourLabeller` seem to have been really intended for internal use and I couldn't find a v3.8 changenote for them, so I didn't add a changenote for them here either.~
=> MNT: expire `ContourSet` deprecations

doc/api/figure_api.rst
=> DOC: Fix duplicate Figure.set_dpi entry

lib/matplotlib/lines.py
Got attention to this while looking at #28800.
=> DOC: Clarify AxLine.set_xy2 / AxLine.set_slope

galleries/examples/style_sheets/petroff10.py
Add example of petroff10 in practice to resolve the first part of #28750.
=> Add example of petroff10 in the style sheets to show how to use the color sequence. 

galleries/examples/animation/frame_grabbing_sgskip.py
Convert the set_data arguments of the frame grabbing example to lists.
This PR closes #[28794](https://github.com/matplotlib/matplotlib/issues/28794).
- [ x ] "closes #[28794](https://github.com/matplotlib/matplotlib/issues/28794)" 
- [ x ] code is not part of the pip package, it affects the gallery. 
- [ x ] This PR fixes an example in the gallery.
- [ x ] This PR does not introduce new features.
=> add brackets to satisfy the new sequence requirement

galleries/users_explain/text/usetex.py
TL;DR: add the sfmath package to the preamble.
Also do some additional minor rewordings of the rest of the usetex tutorial; in particular, remove the comment regarding direct usage of dvi files (which is not particularly relevant for end users, and where the "future" mentioned may still be quite far away (or not)).
Closes #11586.
=> Document how to obtain sans-serif usetex math.

lib/mpl_toolkits/axes_grid1/axes_size.py
Closes #27930. This adds __dunder__ methods (mul, and divide notably) to make interacting with `axes_grid1.Size` object better. 
The original code for Size object interaction is not tested, so I don't know how to proceed to add some test for these changes. Overall, the direct usage of `Size` objects is quite niche, so I seek guidance as well for the documentation (maybe a new example ?) 
- [N/A ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines
Thanks in advance!
=> feat: add dunder method for math operations on Axes Size divider

galleries/examples/animation/simple_scatter.py
Hello! This PR adds the tags for the simple scatter demo. I tagged a few more examples during the sprint. I wanted to start with just one to see how it goes.
Link to the scatter demo:
https://matplotlib.org/devdocs/gallery/animation/simple_scatter.html
Related: https://github.com/matplotlib/matplotlib/issues/27235
=> Tags for simple_scatter.py demo

galleries/examples/animation/bayes_update.py, galleries/examples/animation/dynamic_image.py, galleries/examples/animation/random_walk.py, galleries/examples/animation/strip_chart.py, galleries/examples/lines_bars_and_markers/multivariate_marker_plot.py, galleries/examples/subplots_axes_and_figures/geo_demo.py, galleries/examples/subplots_axes_and_figures/subplots_demo.py, galleries/examples/widgets/polygon_selector_simple.py
Tags from the spreadsheet from #27235 - I'm breaking them up into batches by author to make reviewing easier. These are by @RickyP24, @smcgrawDotNet, and @kakun45
Is waiting on sphinx-tag merging open PRs for supporting content in body of tag.
=> DOC: batch of tags

galleries/examples/axes_grid1/inset_locator_demo.py, galleries/examples/axes_grid1/inset_locator_demo2.py
=> In examples, prefer named locations rather than location numbers.

src/_backend_agg.cpp, src/_backend_agg.h, src/_backend_agg_wrapper.cpp, src/meson.build, src/py_converters.cpp, src/py_converters.h, src/py_converters_11.h, src/py_exceptions.h
This is somewhat partially implemented, in that the NumPy array parts are not changed yet. I think I'll want to do path first, to make this simpler. I'll leave this as draft until then.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write- …
=> Convert Agg extension to pybind11

lib/matplotlib/axes/_axes.py
Minimal fix for #28873. One can still further improve, but this fixes the release-critical part of #28873.
=> DOC: Fix documentation of hist() kwarg lists

lib/matplotlib/axes/_base.py, lib/matplotlib/image.py
Follow up to / enabled by #28825.
=> DOC: Cross-link Axes attributes

doc/devel/development_setup.rst, doc/install/dependencies.rst
closes #28892 by including minimal dependency info from dependencies file. Took the include approach so that the guidance remains in sync/reduce duplication.
=> doc: specify non-python dependencies in dev install docs

lib/matplotlib/axes/_axes.py, lib/matplotlib/tests/test_axes.py
=> MNT: Check the input sizes of regular X,Y in pcolorfast

galleries/examples/axes_grid1/parasite_simple.py, lib/matplotlib/axes/_base.py, lib/matplotlib/axis.py, lib/matplotlib/backends/qt_editor/figureoptions.py, lib/matplotlib/tests/test_axes.py, lib/mpl_toolkits/axisartist/axis_artist.py, lib/mpl_toolkits/mplot3d/axes3d.py
Closes #27971.
For a complete explanation see https://github.com/matplotlib/matplotlib/issues/27971#issuecomment-2016955731
=> MNT: Prevent users from erroneously using legend label API on Axis

doc/api/axis_api.rst, lib/matplotlib/axis.py
=> DOC: Fix Axis.set_label reference

doc/missing-references.json, doc/users/next_whats_new/3d_clip_to_axis_limits.rst, galleries/examples/mplot3d/axlim_clip.py, galleries/users_explain/toolkits/mplot3d.rst, lib/matplotlib/collections.py, lib/matplotlib/text.py, lib/mpl_toolkits/mplot3d/art3d.py, lib/mpl_toolkits/mplot3d/axes3d.py, lib/mpl_toolkits/mplot3d/proj3d.py, lib/mpl_toolkits/mplot3d/tests/test_axes3d.py
Closes https://github.com/matplotlib/matplotlib/issues/25804
This PR introduces "dynamic clipping" of the data in 3D plots, such that data outside the axis limits is not shown. I did a deep dive into stackoverflow and found 12 separate questions asking for this sort of functionality (see that list in [this comment](https://github.com/matplotlib/matplotlib/issues/25804#issuecomment-1723985066)).
All 3D plotting functions now support the `axlim_clip` keyword argument (default `False`), which when `True` will clip the data to the axes view limits, hiding all data outside those bounds. This clipping will be dynamically applied in real time while panning and zooming.
Please note that if one vertex of a line segment or 3D patch is clipped, the entire segment or patch will be hidden. Not being …
=> [ENH] Implement dynamic clipping to axes limits for 3D plots

lib/matplotlib/axes/_axes.py
=> DOC: Clarify the returned line of axhline()/axvline()

.github/workflows/tests.yml, lib/matplotlib/tests/test_axes.py, lib/matplotlib/tests/test_contour.py, lib/mpl_toolkits/mplot3d/tests/test_axes3d.py
We have 3.13 wheels on this branch, so should probably have testing as well.
This also includes the fixes to the test tolerances.
=> Backport PR #28689 on branch v3.9.x (ci: Enable testing on Python 3.13)

galleries/users_explain/animations/animations.py
imageio_ffmpeg distributes the ffmpeg binary with their binary wheel; suggesting its use seems convenient enough.
=> Suggest imageio_ffmpeg to provide ffmpeg as animation writer.

galleries/examples/lines_bars_and_markers/linestyles.py
Today I had reason to want to know exactly what the "dotted" pattern is and thought this example could have been more helpful.  So I
- added a sentence about configuration by `rcParams`
- removed the statement that "dotted" is the same as the pattern (1, 1), since the default rcParam for that is (1, 1.65)
- in the tuple examples, increased the spacing for "dotted" as it was identical to "densely dotted".  I picked 5 to be consistent with the other examples that are not "densely" or "loosely".
- [n/a] *Plotting …
=> DOC: correct linestyle example and reference rcParams

.github/workflows/cibuildwheel.yml, doc/users/next_whats_new/freethreading.rst, src/_backend_agg_wrapper.cpp, src/_c_internal_utils.cpp, src/_image_wrapper.cpp, src/_path_wrapper.cpp, src/_qhull_wrapper.cpp, src/_tkagg.cpp, src/ft2font_wrapper.cpp, src/tri/_tri_wrapper.cpp
This PR includes all the current and future pybind11 PRs, so it might be rebased or otherwise modified without notice. So don't bother reviewing any of the changes, unless you want to note them in the original PRs.
The only important thing here is the resulting wheels, which should be useful for testing.
@greglucas
=> Mark all extensions as free-threading safe

lib/matplotlib/axes/_base.py, lib/matplotlib/rcsetup.py
The call signature code for form2 is incorrect. This pull request changed `set_prop_cycle(label=values[, label2=values2[, ...]])` to `set_prop_cycle(label=values, label2=values2, ...)`.
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-feat …
=> Cycler signature code format fix

lib/matplotlib/figure.py
=> DOC: Better explain suptitle / supxlabel / supylabel naming

galleries/examples/statistics/boxplot.py, galleries/examples/statistics/boxplot_color.py, galleries/examples/statistics/boxplot_demo.py, galleries/examples/statistics/boxplot_vs_violin.py, galleries/examples/statistics/bxp.py, galleries/examples/statistics/confidence_ellipse.py, galleries/examples/statistics/customized_violin.py, galleries/examples/statistics/errorbar.py, galleries/examples/statistics/errorbar_features.py, galleries/examples/statistics/errorbar_limits.py, galleries/examples/statistics/errorbars_and_boxes.py, galleries/examples/statistics/hexbin_demo.py, galleries/examples/statistics/hist.py, galleries/examples/statistics/histogram_bihistogram.py, galleries/examples/statistics/histogram_cumulative.py, galleries/examples/statistics/histogram_histtypes.py, galleries/examples/statistics/histogram_multihist.py, galleries/examples/statistics/histogram_normalization.py, galleries/examples/statistics/multiple_histograms_side_by_side.py, galleries/examples/statistics/time_series_histogram.py, galleries/examples/statistics/violinplot.py
Batch of tags for the stats functions, started by @ktnharris22 in #27235
I mostly didn't add to the tags except to flag stuff that's veering into tutorial or might belong in plot-types.  I put/propose stashing internal-tags in an ifconfig b/c I think they can be useful on dev as a flag of what to work on and confusing/clutter on any of the stable versions.
=> DOC: initial tags for statistics section of gallery

doc/missing-references.json
Problems were introduced by #28048, specifically relating to set_sizes.
I simply ran with the flag to regenerate, so more changes were made, which I do not fully understand why they were not problematic earlier.
=> [DOC] Update missing-references.json

galleries/users_explain/axes/axes_units.py, lib/matplotlib/category.py, lib/matplotlib/tests/test_category.py
- Use getter in docs
- Use a single instance of StrCategoryConverter for all types
- avoids warning since some methods convert to `np.str_` and others are
just `str`, which previously got separate instances
- added test
=> Cleanup converter docs and StrCategoryConverter behavior

lib/matplotlib/ticker.py
=> Tweak AutoMinorLocator docstring.

galleries/users_explain/figure/event_handling.rst
fix broken cross links 
xref #28920
=> DOC: escape broken cross links

src/_tkagg.cpp, src/_tkmini.h
Provides both the older and newer APIs for compatibility with both tcl 9 plus and older versions.
Closes #29126
=> Use both TCL_SETVAR and TCL_SETVAR2 for tcl 9 support

galleries/examples/text_labels_and_annotations/dfrac_demo.py, lib/matplotlib/pyplot.py, lib/matplotlib/tests/test_pyplot.py, lib/matplotlib/ticker.py
=> Minor cleanups to docstrings, comments, and error messages.

lib/matplotlib/image.py
=> Minor tweaks to image docs.

doc/devel/contribute.rst, doc/devel/development_workflow.rst, doc/devel/document.rst, doc/devel/testing.rst
Closes #29181.  The aim is to set a minimum bar that a proposed solution to an issue should actually solve the issue (and not create others).  At the same time, we do not want to give the impression that everything has to be perfect so things like adding a test come under "address as much of the PR Guidelines list as you can".
Also modified the "Start a PR" section so it is clearer that looking through the checklist comes before opening the PR. …
=> DOC: verify your changes

.appveyor.yml, .github/workflows/tests.yml, azure-pipelines.yml
After an audit of all CI, we don't believe we are gaining anything by duplicating GitHub Actions here.
- [tbd] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html) …
=> ci: Remove Linux & macOS from Azure

lib/matplotlib/animation.py
In some cases, such as GIF output, Pillow must convert to P (palette) mode. Unfortunately, when done on RGBA images, this can lose some colour information (cf, https://github.com/python-pillow/Pillow/issues/6832) But when the image starts in RGB mode, the conversion to P mode works better, so convert frames to RGB when they don't have any transparent pixels.
Fixes #29190
I'm not sure we have any tests for GIF, etc., other than smoke tests.
- [n/a] …
=> ANI: Reduce Pillow frames to RGB when opaque

lib/matplotlib/mpl-data/matplotlibrc
=> DOC: Better explanation of rcParams "patch.edgecolor" and "patch.force_edgecolor"

lib/matplotlib/figure.py
=> DOC: Add note to align_labels()

doc/devel/api_changes.rst
The added recommendation is already in use in our codebase.
Enhances #29078. Closes #19017.
=> DOC: Enhance documentation on discouraged API

lib/matplotlib/axes/_base.py, lib/matplotlib/axis.py, lib/mpl_toolkits/mplot3d/axes3d.py
Apply #29303 where it was missing
=> DOC: Add [*Discouraged*] prefix to summary lines

lib/matplotlib/lines.py
the same assignment is already done ~15 lines before (L1341).
=> MNT: Remove duplicate assignment

doc/api/next_api_changes/removals/20866-JKS.rst, doc/api/prev_api_changes/api_changes_3.1.0.rst, lib/matplotlib/axes/_base.py, lib/matplotlib/sphinxext/plot_directive.py, lib/matplotlib/tests/test_colorbar.py, lib/matplotlib/tests/test_widgets.py, pyproject.toml
=> DOC: fix typos

doc/_static/switcher.json
=> DOC: update switcher for 3.10

galleries/examples/scales/symlog_demo.py
Closes #29335 via addressing https://github.com/matplotlib/matplotlib/issues/29335#issuecomment-2548980673.
=> DOC: Explain parameters linthresh and linscale of symlog scale

lib/matplotlib/axes/_axes.py
=> MNT: Warn on using pixel marker for scatter()

doc/devel/communication_guide.rst
Rename Twitter to X in [communication_guide.rst](https://github.com/matplotlib/matplotlib/blob/main/doc/devel/communication_guide.rst).
=> DOC: Rename Twitter to X

lib/matplotlib/axes/_axes.py
In particular, mention the different behavior on duplicates compared to using `tick_label` explicitly.
Closes #29507.
=> DOC: Document the behavior of bar() for categorical x data

galleries/examples/lines_bars_and_markers/broken_barh.py
Follow-up to #29488.
It's simpler to count upwards and use `invert_yaxis()` to order top-to-bottom rather than counting backwards
Also add a references section.
=> DOC: Minor improvement on broken_barh()

doc/devel/communication_guide.rst
Moves the bluesky and mastadon account to the active socials list per the call today.
=> DOC: update active social media list

lib/matplotlib/tests/test_arrow_patches.py, lib/matplotlib/tests/test_axes.py, lib/matplotlib/tests/test_bbox_tight.py, lib/matplotlib/tests/test_collections.py, lib/matplotlib/tests/test_constrainedlayout.py, lib/matplotlib/tests/test_contour.py, lib/matplotlib/tests/test_figure.py, lib/matplotlib/tests/test_legend.py, lib/matplotlib/tests/test_lines.py, lib/matplotlib/tests/test_patches.py, lib/matplotlib/tests/test_path.py, lib/matplotlib/tests/test_patheffects.py, lib/matplotlib/tests/test_simplification.py, lib/matplotlib/tests/test_skew.py, lib/matplotlib/tests/test_subplots.py, lib/mpl_toolkits/axes_grid1/tests/test_axes_grid1.py, lib/mpl_toolkits/mplot3d/tests/test_axes3d.py, lib/mpl_toolkits/mplot3d/tests/test_legend3d.py
Merge pull request #29518 from QuLogic/arch-tolerance
TST: Increase tolerance on more arches
(cherry picked from commit 8c3f4eca28ddc7e47675cfeafe38ca6c85853313)
=> Backport PR #29518: TST: Increase tolerance on more arches

lib/matplotlib/__init__.py
Ignoring the deprecation warning (present since IM 7.1.1-33, May 2024) is the quickest fix.
The proper fix would be to switch to using "magick" everywhere but the command's syntax is a bit different and the CLI usage thus needs to be verified; moreover this would break users with very old installs of imagemagick (unless adding some version sniffing code) although IMv7 has been out since 2016 so that is likely acceptable.  (That proper fix likely also needs some fiddling around the special-casing of `rcParams["animation.convert_path"] = "convert"` in ImageMagickBase.bin_path; e.g. should the rcParams be renamed to `"animation.magick_path"` and have "magick" be the special case...)
Closes (in the short term) #29567, although (per the above) a better fix would be welcome, and it would also …
=> Ignore ImageMagick deprecation of "convert" command.

doc/devel/communication_guide.rst
Remove invalid link in Communication Guide.
This link does not work:
https://x.com/matplotlib/status/1244178154618605568
=> DOC: Remove invalid link in Communication Guide

doc/api/collections_api.rst, doc/missing-references.json
=> DOC: More cleanup of missing-references.json

galleries/examples/ticks/fig_axes_customize_simple.py
- do not assign the patch to a separate variable - one typically would not do this in actual code
- Correct references
=> DOC: Minor example cleanup

galleries/users_explain/axes/tight_layout_guide.py
=> DOC: Document that tight_layout may not converge

lib/matplotlib/cbook.py
Add docstrings to matplotlib.cbook.GrouperView
=> DOC: Add docstrings to matplotlib.cbook.GrouperView

lib/matplotlib/ticker.py
DOC: Add docstrings to get_usetex and set_usetex in ticker.py.
`get_usetex()`:  
Return whether TeX's math mode is enabled for rendering.
`set_usetex(val)`:
Set whether to use TeX's math mode for rendering the numbers in the formatter.
=> DOC: Add docstrings to get_usetex and set_usetex in ticker.py

galleries/examples/text_labels_and_annotations/figlegend_demo.py
Revising the Figure Legend Demo Example. Elaborated on the difference between `outside left upper` and `outside upper right` of legend locations.
https://matplotlib.org/devdocs/gallery/text_labels_and_annotations/figlegend_demo.html
=> DOC: Revising the Figure Legend Demo Example

galleries/users_explain/axes/tight_layout_guide.py, lib/matplotlib/layout_engine.py
Closes #17339 by addressing the remaining open issue https://github.com/matplotlib/matplotlib/issues/17339#issuecomment-625516913.
=> DOC: Recommend constrained_layout over tight_layout

doc/_static/mpl.css, doc/devel/development_setup.rst, doc/devel/index.rst
At today's new contributor meeting, a new contributor got a bit tripped up on instructions, so I:
* split the pyenv linux&mac/bat/powershell into tabs
* put the codespaces and local blurbs into a list to make 'em standout
* pushed the local install instructions into subheadings to restructure the index to try and making it clearer that local and github were equal but different options:
=> DOC: improve dev install docs

lib/matplotlib/axes/_axes.py
Follow up to #27786, which in the end went into v3.10.
=> MNT: correct version in plotting method deprecation warnings

.github/workflows/tests.yml
This fixes pinning PyGObject in the macOS tests - see https://github.com/matplotlib/matplotlib/pull/29734#issuecomment-2718719713 for more context. Without the quotes, the `<` acts like a pipe.
=> Fix PyGObject version pinning in macOS tests

galleries/examples/color/individual_colors_from_cmap.py, galleries/examples/lines_bars_and_markers/scatter_demo2.py, galleries/examples/statistics/time_series_histogram.py
Closes #29753.  I also added the colormap tag to the scatter example since it is mapping values to viridis.
=> Consolidate color tags

galleries/examples/animation/animated_histogram.py, galleries/examples/animation/bayes_update.py, galleries/examples/animation/dynamic_image.py, galleries/examples/animation/multiple_axes.py, galleries/examples/animation/random_walk.py, galleries/examples/event_handling/resample.py, galleries/examples/lines_bars_and_markers/bar_colors.py, galleries/examples/lines_bars_and_markers/hat_graph.py, galleries/examples/lines_bars_and_markers/line_demo_dash_control.py, galleries/examples/lines_bars_and_markers/scatter_demo2.py, galleries/examples/lines_bars_and_markers/simple_plot.py, galleries/examples/lines_bars_and_markers/span_regions.py, galleries/examples/lines_bars_and_markers/timeline.py, galleries/examples/mplot3d/stem3d_demo.py, galleries/examples/pie_and_polar_charts/polar_scatter.py, galleries/examples/statistics/bxp.py, galleries/examples/statistics/confidence_ellipse.py
=> DOC: consolidate tags

galleries/examples/animation/rain.py, galleries/examples/animation/unchained.py, galleries/examples/event_handling/pong_sgskip.py, galleries/examples/images_contours_and_fields/barcode_demo.py, galleries/examples/shapes_and_collections/dolphin.py, galleries/examples/shapes_and_collections/donut.py, galleries/examples/showcase/xkcd.py
Expand use of the "fun" tag and add other relevant tags to these examples.
I was disapointed that "fun" didn't link to much!
=> DOC: expand use of fun tag

galleries/examples/scales/logit_demo.py
Adding a description to logit_demo.py script
The change is necessary because it lacks a description so making it unclear to demonstrate how logit scale is used.
It expalins how the logit scale works and why it is useful for visualising probabilities.
The script demonstrates how logit scale spreads probability values between 0 and 1, which helps user compare different distributions
=> Add description to logit_demo.py script

.github/workflows/cibuildwheel.yml, .github/workflows/mypy-stubtest.yml, .github/workflows/reviewdog.yml, .github/workflows/tests.yml
Also updates setup-python to v5.5.0 where it's used elsewhere.
=> replace quansight-labs/setup-python with actions/setup-python

src/_macosx.m
See https://github.com/matplotlib/matplotlib/issues/28611#issuecomment-2749886810 for context.
=> Declare free-threaded support in MacOS backend extension

lib/matplotlib/dviread.py
Again, mostly maintenance work in preparation for #29807.
To test, run e.g.
```python
set_loglevel("debug")
figtext(.5, .5, r"gff\textwon$\frac12$", usetex=True)
show()
```
Grab the path of the dvi file that appears last in the log, then run
```bash
python -mmatplotlib.dviread /path/to/dvi
```
Prior to this patch, the output was
```
=== new page === (w: 1668654, h: 553676, d: 225994)
font: 'cmss10'	scale: 0.625
x	y	glyph	chr	w	(glyphs)
983040	1441792	103	g	327681
1310721	1441792	11	.	382295
font: 'tcss1000'	scale: 0.625
x	y	glyph	chr	w	(glyphs)
1693016	1441792	142	.	618800
font: 'cmr7'	scale: 0.4375
x	y	glyph	chr	w	(glyphs)
2390459	1183756	49	1	261235
2390459	1667786	50	2	261235
x	y	h	w		(boxes)
2390459	1291058	26213	261235
```
With this patch, the output is
```
=== …
```
=> Improve output of dvi debug parsing.

doc/users/faq.rst, lib/matplotlib/pyplot.py
See https://github.com/matplotlib/matplotlib/issues/29782#issuecomment-2765800056
=> Improve docs regarding plt.close().

lib/matplotlib/transforms.py
The function can easily be inlined into its sole caller without affecting readability; this avoids having to lengthily document its inputs and outputs.
(This was introduced by @scottshambaugh in #29399 so perhaps he can comment on whether he planned to reuse the method elsewhere.)
=> Inline _calc_extents_from_path.

lib/matplotlib/pyplot.py
Fixes a grammatical error in the `lib\matplotlib\pyplot.py` ("single a Axes" → "a single Axes").
No functional code changes are introduced.
```python
```
=> doc: a grammatical error in pyplot comment

galleries/examples/units/basic_units.py
Going off the discussion in #28780, figured it'd be useful to add a sentence or two explaining that basic units is implementing a mini library so folks who don't need to can back out before trying to read the code.
=> [doc] minimally document what basic units is doing

galleries/users_explain/figure/interactive_guide.rst
Cherry-picked the commit from #29943 to also fix the v3.10.1-doc branch.
(cherry picked from commit 09bea955b84937ae177ded93d6384b233de6c707)
=> Fix doc build on 3.10.1-doc

doc/api/axes_api.rst, lib/matplotlib/axes/_base.py
Closes #29964, by hanging a docstring from a class level type hint.  I did not know you could do this - so thanks to @timhoffm for the pointer.
=> Document Axes.spines

doc/api/typing_api.rst, lib/matplotlib/typing.py
=> DOC: Add descriptions to matplotlib.typing

doc/install/dependencies.rst
Wrote out the list of latex dependencies from https://github.com/matplotlib/matplotlib/pull/27282#issuecomment-1800861075 b/c I had to update to texlive 2025 and got errors until I installed the whole list. 
I think this also closes #24646 b/c  'minimal' is probably encapsulated in the collections.
=> added latex requirements from fedora spec

doc/api/prev_api_changes/api_changes_3.8.0/behaviour.rst
=> DOC: document the issues with overlaying new mpl on old mpl

lib/matplotlib/figure.pyi
This is a proof-of-concept PR to address https://github.com/matplotlib/matplotlib/issues/29334
=> Type annotation add_subplot for projection="3d"

doc/install/dependencies.rst
Accidentally lost `be` in #29764 and figured if I was opening up a PR to fix it, I may as well put the latex dependencies in a linkable subsection.
=> DOC: missing word + add latex dep section

doc/api/next_api_changes/removals/30015-DS.rst, lib/mpl_toolkits/axisartist/axislines.py, lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
Deprecated in 3.9, so time to expire in 3.11.
=> Expire deprecation of nth_coord arguments

doc/install/dependencies.rst, galleries/users_explain/text/pgf.py, galleries/users_explain/text/usetex.py
- Merge "Troubleshooting" and "Possible hangups".
- Don't list $PATH issues twice.
- Remove mention of dvipng for pgf (which doesn't use dvipng).
- Be more generic re: missing latex packages (this applies to all texlive installs, and the required list is given elsewhere).
=> Improve usetex and pgf troubleshooting docs.

galleries/examples/color/color_sequences.py
* Add petroff6 and petroff8 as a follow up to PR https://github.com/matplotlib/matplotlib/pull/30065.
* Resolves https://github.com/matplotlib/matplotlib/issues/30086
=> DOC: Add petroff6 and petroff8 to 'Named color sequences' example

doc/devel/document.rst
Pulls plot types content guidelines out of #26389 and moves the guidelines under the example guidelines.
=> DOCS: add plot types content guidance to docs

doc/devel/document.rst
* Renames write docstrings to API documentation per discussion in #28578, which is roughly that folks need to know docstrings b/c they're writing API docs (& may not know they're called docstrings)
* pulls generate inheritance diagrams into new API documentation section per #28578
* Pulls in the API docs guidelines from #26389 as the intro to the API docs section
=> DOC: add API docs content guidelines to api docs instructions

galleries/plot_types/basic/scatter_plot.py
The documentation [in API menu](https://matplotlib.org/3.10.1/api/axes_api.html) is cropped because of a point in the middle of the sentence.
=> remove point troubling regex

doc/install/dependencies.rst, lib/matplotlib/mpl-data/matplotlibrc, lib/matplotlib/mpl-data/stylelib/classic.mplstyle, lib/matplotlib/tests/test_backend_svg.py, lib/matplotlib/tests/test_usetex.py, lib/matplotlib/texmanager.py
... to fix unicode glyph sizing issues for svg & patheffects.
This is the patch at https://github.com/matplotlib/matplotlib/issues/29791#issuecomment-2745448994 with a test.  Closes https://github.com/matplotlib/matplotlib/pull/12928#issue-386907972.  Closes #27654.  Closes #28675.  Closes #29791.  Supersedes #14159.
=> Use fix-cm instead of type1cm.

src/ft2font.cpp, src/ft2font.h
Provide a simple macro to call a FreeType function and throw an exception if an error is returned, while also including the source file and line location for the error.  For example, trying `FT2Font(open("pyproject.toml", "rb"))` now raises "FT_Open_Face (ft2font.cpp line 220) failed with error 0x02: unknown file format" instead of "Can not load face (unknown file format; error code 0x2)".
cf. discussion starting at https://github.com/matplotlib/matplotlib/pull/30059#issuecomment-2899636790.
=> Simplify/improve error reporting from ft2font.

src/_backend_agg.h
Instead of a fixed-size buffer, a dynamic buffer, and all the tracking for them, just use a standard C++ container, which will clean up for itself automatically.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pa …
=> Simplify RendererAgg::draw_markers buffers

lib/matplotlib/animation.py
deques are exactly suited for the task at hand, and should be (here, marginally) more efficient than repeatedly slicing off the start of the list.
Also drop unneeded reference to old_frame_seq (the iterator already keeps that data alive).
=> Use collections.deque to store animation cache data.

lib/matplotlib/backends/_backend_tk.py, lib/matplotlib/backends/backend_pdf.py
xref https://github.com/python-pillow/Pillow/pull/9018
=> BUG: fix future incompatibility with Pillow 13

doc/devel/tag_guidelines.rst, doc/users/prev_whats_new/whats_new_3.8.0.rst, galleries/examples/scales/custom_scale.py
remove redundant words in comment
=> chore: remove redundant words in comment

doc/users/faq.rst
=> DOC: Recommend to use bare Figure instances for saving to file

ci/schemas/conda-environment.json, doc/api/prev_api_changes/api_changes_0.90.1.rst, doc/api/prev_api_changes/api_changes_1.5.0.rst, doc/users/prev_whats_new/github_stats_3.0.0.rst, doc/users/prev_whats_new/github_stats_3.0.1.rst, doc/users/prev_whats_new/github_stats_3.0.2.rst, doc/users/prev_whats_new/github_stats_3.1.0.rst, doc/users/prev_whats_new/github_stats_3.1.2.rst, doc/users/prev_whats_new/github_stats_3.1.3.rst, doc/users/prev_whats_new/github_stats_3.2.0.rst, doc/users/prev_whats_new/github_stats_3.3.0.rst, doc/users/prev_whats_new/github_stats_3.3.1.rst, doc/users/prev_whats_new/github_stats_3.4.0.rst, doc/users/prev_whats_new/github_stats_3.4.2.rst, doc/users/prev_whats_new/github_stats_3.4.3.rst, doc/users/prev_whats_new/github_stats_3.5.0.rst, doc/users/prev_whats_new/github_stats_3.5.1.rst, doc/users/prev_whats_new/whats_new_3.10.0.rst, lib/matplotlib/axes/_base.py, lib/matplotlib/tests/test_triangulation.py, lib/matplotlib/tri/_triinterpolate.py
Just a few new things found with codespell.
Also, don't worry about regenerating the issue/PR lists; I've fixed all titles on GitHub already.
=> Fix several minor typos

lib/matplotlib/figure.pyi
=> [MNT] Typing: correct typing overloads for ``Figure.subfigures``

.github/workflows/cibuildwheel.yml
- Backport PR #30195: ci: Enable wheel builds on Python 3.14'
=> Manual Backport PR #30195 on branch v3.10.x (ci: Enable wheel builds on Python 3.14)

galleries/examples/axisartist/demo_axis_direction.py, galleries/examples/axisartist/simple_axis_pad.py
The code follows the style in demo_axis_direction.  The new version remains reasonably legible, and that setup is not really the point of the example anyways (which is about axis padding).
Also remove special handling of underscore which is now unnecessary since usetex already auto-handles that.
=> Shorten setup of axes in simple_axis_pad demo.

doc/install/index.rst, doc/install/troubleshooting_faq.inc.rst
Almost all code-blocks should be highlighted as shell, not python (most were already tagged so, but some were still mis-highlighted).  The remaining python blocks are actually all doctests, and can thus use their own rst syntax.
(See e.g. the previously mis-highlighted dash in `py38-pip` at https://matplotlib.org/devdocs/install/index.html#installing-macos-binary-wheels)
=> Fix highlighting of install docs.

lib/matplotlib/tests/test_determinism.py
Currently, half the Axes are in a 2x2 grid, half are over the whole figure, and half are in a 1x6 grid (yes, that's more than 100% since they all overlap).
Instead, place each optional section in a subfigure, and auto-size the figure based on how many sections there are. So instead of how it looks in #30360, it will look like:
I don't think this will do anything to fix the flakiness, but at least it will look reasonable when trying to compare the results.
=> TST: Make determinism test plots look less pathological

lib/matplotlib/tests/test_backend_qt.py
It doesn't seem very useful now, since we import `QtGui` at the top level anyway.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-do …
=> TST: Remove qt_core fixture

galleries/examples/subplots_axes_and_figures/geo_demo.py
The Cartopy docs have a new home :house:
=> DOC: update Cartopy url

doc/index.rst, doc/install/index.rst, doc/install/quick_install.inc.rst, doc/users/getting_started/index.rst
This PR puts the tab set of install instructions into a stand alone file that's then included on the index, install/index, and getting started pages. The motivation is ensuring consistent quick install instructions across the docs. ~The end line is to exclude the toc-tree, but I don't know how to comment that w/o breaking the build.~ 
xref: #29775
=> doc: factor out quick install tab for reuse

galleries/users_explain/artists/imshow_extent.py
We need to make text font normal rather than italics.
https://matplotlib.org/devdocs/users/explain/artists/imshow_extent.html
=> DOC: Fix text formatting of imshow_extent example

doc/install/dependencies.rst
pytz link should be from PyPI:
https://pypi.org/project/pytz/
The original link is unrelated:
https://fonts.google.com/noto/use#faq
=> DOC: pytz link should be from PyPI

.github/workflows/tests.yml, LICENSE/LICENSE_FREETYPE, LICENSE/LICENSE_HARFBUZZ, LICENSE/LICENSE_LIBRAQM, LICENSE/LICENSE_SHEENBIDI, doc/project/license.rst, doc/release/next_whats_new/libraqm.rst, extern/meson.build, lib/matplotlib/__init__.py, lib/matplotlib/_text_helpers.py, lib/matplotlib/ft2font.pyi, lib/matplotlib/tests/test_ft2font.py, lib/matplotlib/tests/test_text.py, meson.build, meson.options, src/ft2font.cpp, src/ft2font.h, src/ft2font_wrapper.cpp, src/meson.build, subprojects/freetype2.wrap, subprojects/harfbuzz.wrap, subprojects/libraqm-0.10.3.wrap, subprojects/packagefiles/harfbuzz-11.2.0-bundle-freetype.patch, subprojects/packagefiles/libraqm-0.10.2-bundle-freetype.patch, subprojects/packagefiles/libraqm-203.patch, subprojects/sheenbidi.wrap
This is based on #29816 but doesn't yet include #29794 and #29695. I'm mostly opening it to see how CI will cope.
=> Implement text shaping with libraqm

galleries/users_explain/text/fonts.py
Remove unnecessary info snippets e.g. re: fractal rendering (this isn't a table for font designers); merge Type 42 entry together with TrueType (they are essentially the same technology).
=> Copy-edit the "fonts in pdf and postscript" table.

lib/matplotlib/backends/backend_pdf.py
Currently, we split text into single byte chunks and multi-byte glyphs, then iterate through single byte chunks for output and multi-byte glyphs for output.
Instead, output the single byte chunks as we finish them, then do the multi-byte glyphs at the end.
This was split out of #30512 and based on #30335.
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-chan …
=> pdf: Merge loops for single byte text chunk output

doc/release/next_whats_new/violin_stats.rst, lib/matplotlib/axes/_axes.py, lib/matplotlib/cbook.py
Follow up to #30387.  That refactor was done for maintainance purposes but, as shown by [this StackOverflow question](https://stackoverflow.com/questions/79777583/how-to-use-matplotlib-axes-axes-violin), pulling the default KDE functionality into `violin_stats` can also be useful to the user.
=> DOC: add what's new info for violin_stats

src/_c_internal_utils.cpp
=> Use auto to remove long typedefs in dlsym/GetProcAddress calls.
