- lib/matplotlib/animation.py
- src/_macosx.m
- Emit a resize_event signal when the pixel ratio is updated. This
enables an animation to move between hidpi and standard dpi screens
without ruining the blitting.
- Init the draw in the animation. This is only necessary for macosx
because an initial resize isn't emitted upon figure manager creation,
versus the other backends where it is. This would cause the first frame
to be stale on the macosx animations when used with blitting.
Closes #18451
This is the example I was testing with that kept the first frame previously, but now updates as expected like the other backends.
https://matplotlib.org/stable/gallery/animation/simple_anim.html
I'm not sure if there is a simple test for these updates as they are interactive-based primarily. Happy to add one if someone has a good idea for how to …
> FIX: Update macosx animation handling

- lib/matplotlib/backends/backend_macosx.py
- lib/matplotlib/tests/test_backends_interactive.py
- src/_macosx.m
This moves some of the drawing and blitting code to the AGG canvas (instead of trying to use the objc routines) and leverages that to handle when a full AGG re-render should happen. The macosx code always grabs the full AGG buffer when drawing to the GUI window at the objc level (inside drawRect). I removed `_draw()` and added an `update()` routine in objc that requests a screen draw within the main run loop.
closes #10980
closes #17445 (Only does a full redraw once now!)
Fixes the example from #17642, but I'm not sure this is still feature-parity with what "flush_events" means on the other backends, so I guess it probably shouldn't be closed.
* I tried to draw on some of the logic in the QT backend. That portion would be good to have someone take a look at and provide suggestions for …
> FIX: Update blitting and drawing on the macosx backend

- doc/api/next_api_changes/deprecations/22554-AL.rst
- lib/matplotlib/ticker.py
create_dummy_axis() sets up some internal _DummyAxis, which should not
really have been leaked to end users; instead, we should just always
attach a _DummyAxis to locators and formatters at init to start with.
_DummyAxis should actually be quite cheap to create, but it does create
two Bbox.unit() (dataLim and viewLim) which are *slightly* expensive to
create, can be placed by plain tuples, and do not correspond to any APIs
on "standard" Axises (there's Axes.dataLim/viewLim, not
Axis.dataLim/viewLim).  While the offending attributes are on a private
class, they are publically accessible e.g. via
`locator.create_dummy_axis(); locator.axis` so go through a deprecation
to be extra safe.
> Prepare for making create_dummy_axis not necessary.

- src/_path.h
- src/ft2font.cpp
- src/ft2font_wrapper.cpp
Minor fix getting rid of type cast warnings (on Windows).
```
C:\Users\Oscar\matplotlib\src\_path.h(843): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
...
C:\Users\Oscar\matplotlib\src\_path.h(1157): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
```
(Editor removed some trailing spaces.)
> MNT: Fix types in C-code to reduce warnings

- doc/users/next_whats_new/double_quotes_matplolibrc.rst
- lib/matplotlib/__init__.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/mpl-data/matplotlibrc
- lib/matplotlib/tests/test_cbook.py
This enables using the comment character # within strings. Also it lets you write hex colors more consistently as "#FFFFFF" rather than FFFFFF (i.e. omitting the hash). We discourage the latter but keep it for backward compatibility.
Closes #19288.
Superseeds #22565.
> Support quoted strings in matplotlibrc

- lib/matplotlib/mpl-data/matplotlibrc
- lib/matplotlib/patches.py
Some minor fixes for patches.
* No need to lookup rcParam fallback in __init__ as it is
done in the set-methods and not used before calling set-methods.
* patch.linewidth is a float, so represent default as float.
> Remove redundant rcParam-lookup in patches

- doc/api/next_api_changes/deprecations/22547-AL.rst
- lib/matplotlib/backend_bases.py
- lib/matplotlib/textpath.py
Mostly take advantage of the fact that TexManager() now always returns
the same instance, so get_texmanager isn't really needed anymore.  Still
keep RendererBase.get_texmanager as backcompat for now as inheriting
renderers (e.g. mplcairo) may be using that to also support older
versions where there was no singleton logic); OTOH probably(?) no one is
inheriting from TextToPath (which is mostly the text_to_path singleton)
so we can deprecate *its* get_texmanager.
> Small cleanups around TexManager usage.

- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
- lib/matplotlib/image.py
- lib/mpl_toolkits/mplot3d/axes3d.py
As always, this can makes it easier to write generic code looping over
all axises.
> Move tracking of autoscale status to Axis.

- lib/matplotlib/colorbar.py
- lib/mpl_toolkits/tests/test_axes_grid1.py
Update the colorbar `get_subplotspec()` to only access attributes
after a check for it having the attribute, else return None.
Fixes #22576
This will still warn about the Axes not being compatible, but I think that is expected as an AxesGrid `inset_axes()` without a colorbar also warns.
> FIX: Colorbars check for subplotspec attribute before using

- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
- lib/matplotlib/tests/test_colorbar.py
- tutorials/introductory/quick_start.py
Fix offsetText for colorbars with extends so they are above the extends...  Closes #22312
> Fix colorbar exponents

- doc/users/prev_whats_new/whats_new_1.5.rst
- lib/matplotlib/layout_engine.py
While sphinx/docutils seem to accept it, it is technically not in the
spec and many parsers get that as a comment
--- 
You can actually see that in github highlighting of the diff, where the `.. code-block :: python` remove is in gray, while `.. code-block:: python` is blue + purple.
> DOC: remove space in directive.

- doc/api/next_api_changes/deprecations/22509-AL.rst
- lib/matplotlib/backend_managers.py
- lib/matplotlib/backend_tools.py
On the addition side, inline ToolManager._tool_added_event.  It's used
at a single place, and other events emitted by ToolManager are not split
out into their own helper methods.
On the removal side, deprecate the Tool.destroy handle: it's unused, and
if a tool really wants to know when it's getting removed, it can just
connect to its own tool_removed_event, which can also be used by other
callers.
> Simplifications to ToolManager.{add,remove}_tool.

- doc/api/next_api_changes/behavior/22639-RA.rst
- src/_macosx.m
> ENH: MacOSX backend to use sRGB instead of GenericRGB colorspace

- lib/matplotlib/cm.py
Replace
```
File "../matplotlib/cm.py", line 131, in __getitem__
return self._cmaps[item].copy()
KeyError: 'foo'
During handling of the above exception, another exception occurred:
File "<string>", line 4, in <module>
File ".../matplotlib/cm.py", line 133, in __getitem__
raise KeyError(f"{item!r} is not a known colormap name")
KeyError: "'foo' is not a known colormap name"
```
by just the latter block.
> Suppress exception chaining in colormap lookup.

- lib/matplotlib/backends/backend_macosx.py
Closing a window would keep the window around with a spinning ball. If we flush the pending events, the window can close immediately.
```python
import time
x = np.arange(5)
y = np.arange(5)
plt.plot(x, y)
plt.show()
time.sleep(5)
```
This will need to be tested manually. I'm not sure how we would be able to test it otherwise.
Closes #11861
- [N/A] Documentation is …
> FIX: Flush events after closing figures in macosx backend

- lib/matplotlib/colorbar.py
- lib/matplotlib/tests/test_colorbar.py
This fixes the colorbar extensions to use the proper color when the long axis is inverted. One of the issues is that the extensions are created immediately upon colorbar creation, but not updated with new draws. This adds a callback listener on xlim/ylim changes for the colorbar axes to redraw the extensions, so it is a bit unfortunate in that sense, but not too bad.
Closes #22052 …
> FIX: Handle inverted colorbar axes with extensions

- lib/matplotlib/colorbar.py
- lib/matplotlib/tests/test_colorbar.py
> Manual backport of pr 22635 on v3.5.x

- src/ft2font_wrapper.cpp
As noted at https://github.com/matplotlib/matplotlib/pull/22604#discussion_r821118057
> Fix new leak in ft2font introduced in #22604

- lib/matplotlib/axis.py
This is a follow-up to #20826, which makes the exceptions from clearing more explicit.
While being a bit more verbose, this makes it more clear what is going on. Also I think having proper `_reset_*_tick_kw` methods will make patching the 3D default tick direction for https://github.com/matplotlib/matplotlib/pull/22517#issuecomment-1050349508 easy. Something along the lines (to be tested):
```
class Axis(...):
def reset_major_tick_kw(keep_tick_and_label_visibility=False)
super().reset_major_tick_kw(keep_tick_and_label_visibility)
self._major_tick_kw['tickdir'] = 'inout'
```
The test introduced in #20826 should verify that this solution is equivalent and does not break something.
> Refactor handling of tick and ticklabel visiblity in Axis.clear()

- setupext.py
> Simplify FreeType version check to avoid packaging

- doc/devel/documenting_mpl.rst
- lib/matplotlib/axes/_axes.py
Updated the documentation example with the current code.
I was originally interested in seeing if the See also-example without a space before : did work and realized that it wasn't the current code.
Also, all See also-sections are spelled See Also in the code, but rendered as See also. So while I change to See Also in the See also-example, I am not sure if I should also change the caption and text before the example... That is
```
``See Also`` section
```
etc.
> Update documentation example and fix See also

- examples/subplots_axes_and_figures/colorbar_placement.py
- No need to plt.show() after every block; this makes running the
example from the command line easier.
- inset_axes defaults to transAxes, no need to pass that explicitly.
> Tweak colorbar_placement example.

- doc/api/font_manager_api.rst
- lib/matplotlib/font_manager.py
- lib/matplotlib/rcsetup.py
- lib/matplotlib/tests/test_font_manager.py
- lib/matplotlib/tests/test_rcparams.py
Closes #22582
Closes #22586
Always convert input to `str` first.
Also update the documentation a bit.
Cannot really see how this can be tested as I do not know of any ttf-font locations on the CI... Edit: I found a ttf-font in the test data, so at least it should be possible to test passing a Path without errors. Edit 2: Test added.
Also added a validation function for `font.stretch`, so now rcParam-values can also be ints.
Kept it as four separate commits, but can of course merge to a single.
> Fix Path/str-discrepancy in FontManager.addpath and improve documentation

- lib/matplotlib/cm.py
- lib/matplotlib/colors.py
- lib/matplotlib/figure.py
- lib/matplotlib/patches.py
- lib/matplotlib/widgets.py
A number of parameters were missing a space before the :, which affects the rendering.
> Add missing space before : for parameters

- azure-pipelines.yml
https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/#windows says that 'vs2017-win2016' will likely work with 'windows-2019' as well.
This changes from VisualStudio 2017 to VisualStudio 2019. Not sure if that's a problem. Lets's see.
N.b. 'windows-2019' is the same as 'windows-latest', and the py38 and py39 builds use the latter. Is there a reason that we pin the version here?
> Update deprecated vmImage 'vs2017-win2016' in azure pipelines

- doc/conf.py
The original implementation broke the sphinx config state detection for
caching, so that the cache was always invalidated.
Closes #22671.
This reduces incremental build time from 380s to 280s on my machine. - Still quite slow given that (almost) nothing changes, but definitively a step in the right direction.
> Rewrite plot format detection from sphinx build target

- lib/matplotlib/colors.py
- lib/matplotlib/tests/test_colors.py
Closes #22662
The error message when supplying an empty string for color was a bit confusing:
``` 
raise ValueError("Using a string of single character colors as "
"a color sequence is not supported. The colors "
"can be passed as an explicit list instead.")
```
Now a dedicated version is used for the empty string:
```
raise ValueError("Using an empty string for color is not "
"supported. Use 'none' if you do not want to "
"set a color.")
```
- [N/A] Documentation is …
> Improve error message for incorrect color string

- doc/api/next_api_changes/deprecations/21425-AL.rst
- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/mplot3d/axis3d.py
Setting `adir` to a direction not matching the specific axis class
doesn't make sense anyways; the viewlims and datalims properties
previously got init'ed to their preexisting values; and init3d doesn't
warrant being a separate public API.
Also deprecate the 3D-specific d_interval and v_interval attributes, as
they have direct replacements compatible with 2D.
> Make Axis3D constructor signature closer to the one of 2D axis.

- lib/matplotlib/tests/test_backend_tk.py
This will increase the reported coverage of the tk tests, but shares commits
with #22005 and should be merged after that.
> TST: increase coverage on tk tests

- lib/matplotlib/collections.py
Closes #22520.
Replaces (IMO) #22691.
I think #22254 should be reverted, as the knob it introduces doesn't actually work *and* the desired knob already exists (it's the mouseover property).
> Remove QuadMesh from mouseover set.

- doc/api/next_api_changes/behavior/22254-DS.rst
- doc/api/next_api_changes/behavior/22691-JMK.rst
- lib/matplotlib/collections.py
- lib/matplotlib/tests/test_collections.py
Closes #22694
Follows up on https://github.com/matplotlib/matplotlib/pull/22693
Removes ineffective toggle for cursor data, and updates usage note to point out that mouseover is set to False by default.  It is possible we will want more documentation of this as per @timhoffm 
Closes #22520
#19908 made using a mouse over large pcolormesh unusably slow.  
https://github.com/matplotlib/matplotlib/pull/22254 attempted to make this togglable with short circuit.  
Despite the changes in #22254, pcolormesh is still _really_ slow if you try and move a mouse around.  I actually do not understand why this is the case, because the short circuit in #22254 is actually called.  However, I'll put the onus of understanding the problem on the folks who want the cursor data, and I think we should pull this …
> FIX: remove toggle on QuadMesh cursor data

- lib/matplotlib/textpath.py
- verts of glyph_map entries are created with FT2Font.get_path() and are
thus already arrays; no need to convert them again.
- We can always extend verts and codes regardless of whether verts1 is
empty (extend will just be a noop in that case); empty verts should be
exceptional anyways.
> Small simplification to textpath.

- lib/matplotlib/backends/_backend_tk.py
- lib/matplotlib/tests/test_backend_tk.py
Closes #22150
Threshold taken from https://github.com/matplotlib/matplotlib/blob/bf3c6515d00d26d0243c8a3574802d024899fdd9/lib/matplotlib/backends/backend_qt.py#L694 Icon colouring taken from https://github.com/matplotlib/matplotlib/blob/bf3c6515d00d26d0243c8a3574802d024899fdd9/lib/matplotlib/backends/backend_wx.py#L1128
> Change colour of Tk toolbar icons on dark backgrounds

- lib/matplotlib/mpl-data/matplotlibrc
- lib/matplotlib/rcsetup.py
- lib/matplotlib/tests/test_text.py
- lib/matplotlib/text.py
Based on the discussion in #22537, there was a question about controlling `parse_math` through rcParams. Assuming that one often would like to use some special packages, it probably would be quite convenient to do that.
Should this be documented as a new feature?
(It is not obvious to me how the default value is controlled...)
> Add text.parse_math rcParams

- doc/api/next_api_changes/deprecations/22697-OG.rst
- lib/matplotlib/testing/decorators.py
`CleanupUnitTest` and the `cleanup` decorator are not used. 
`check_freetype_version` is only used inside the file so makes sense to make private.
> Deprecate in testing.decorators 

- lib/matplotlib/_mathtext.py
mathtext can now do fallbacks to fonts other than computer modern, so
the name cm_fallback is outdated.  The module is private, so we can
rename the attribute without deprecation.
> Rename confusingly-named cm_fallback.

- doc/api/next_api_changes/deprecations/22418-AL.rst
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_pyplot.py
In particular, note that the OO add_subplot does not have this behavior.
Closes #4976.  Closes #11435 (which was deemed "not a bug", but still...)
> Deprecate auto-removal of overlapping Axes by plt.subplot{,2grid}.

- lib/matplotlib/dviread.py
- lib/matplotlib/tests/test_text.py
- lib/matplotlib/texmanager.py
- lib/matplotlib/text.py
Previously, multiline strings were split at `\n` and passed one at a time to TeX -- likely, this is a remnant of how multiline strings are handled for the non-TeX case, as Matplotlib also renders one line at a time.  This series of commits switches things to instead pass entire multiline strings all at once to TeX, which is useful e.g. if a tex font command must apply to arbitrary strings that may contain newlines.  Goes on top of #22359.
1st commit: Switch TeX baseline detection to use a dvi special.
Insert a `\special` at the end of the TeX output and record the baseline
position there.  This should be more robust than trying to guess the
format of the dvi preamble, and more importantly this will also allow
detecting the last baseline of *multiline* TeX output, which will then
allow …
> Let TeX handle multiline strings itself.

- lib/matplotlib/tests/test_triangulation.py
- lib/matplotlib/tri/triangulation.py
- lib/matplotlib/tri/tripcolor.py
Commits:
- Rewrite `Triangulation.get_from_args_and_kwargs` to make parameter parsing testable; and add tests.
- Warn when passing `triangles` or `mask` alongside a `Triangulation` to `tripcolor()`
- Cleanup logic and documentation of `tripcolor()`
This issues additional warnings and more precise error messages but does not change behavior.
The only "semantic" change is that I have discouraged passing *triangles* positionally: `tripcolor(x, y, triangles, C)`
is a bit odd and IMHO has too many positional arguments.
Closes #22303. Follows up on #10148.
> Cleanup tripcolor()

- lib/matplotlib/dates.py
- lib/matplotlib/tests/test_dates.py
with `{\fontfamily{\familydefault}\selectfont ...}`, instead of using
math and selectively escaping parts of the string.
Note that this is only possible now that tex strings are passed "all at
once" to the tex process (#22360) rather than "one line at a time", because if
breaking at `"\n"` as previously done, then the braces of the tex
command above would become unbalanced (and lines other than the first
would not see the `\selectfont`).
The main difference in rendering is that hyphens (e.g. in YY-MM-DD) are
now rendered as plain hyphens rather than minus signs, but some googling
suggests that this is in fact correct (see e.g. ctan datetime2 or
isodate packages).  Also, month names are now rendered with serif, but
that seems more consistent with day and years which are also serifed
(and …
> Revert datetime usetex ticklabels to use default tex font.

- lib/matplotlib/tests/test_widgets.py
- lib/matplotlib/widgets.py
This bug fix is in response to issue #22706.
There was an issue with the handles not updating when set_val was called on a RangeSlider object. 
I updated set_val to adjust the appropriate handles when set_val is called. There are still other issues with handles in the RangeSlider class, but this pull request should address the issue highlighted.
Here is an example test that I used to reproduce the original issue:
```
from matplotlib.widgets import RangeSlider
np.random.seed(19680801)
N = 128
img = np.random.randn(N, N)
fig, axs = plt.subplots(1, 2, figsize=(10, 5))
fig.subplots_adjust(bottom=0.25)
im = axs[0].imshow(img)
axs[1].hist(img.flatten(), bins='auto')
axs[1].set_title('Histogram of pixel intensities')
slider_ax = …
```
> RangeSlider handle set_val bugfix

- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_figure.py
Closes #22137 
``Figure.clf()`` and ``Figure.clear()`` were broken 
when ``Figure`` contained axes not stored in `Figure._localaxes`. #  Moved the
``clear`` and ``clf`` methods to ``FigureBase``, so ``Subfigure``s can now be
independently cleared. Added a routine to clear ``Figure.subfigs`` when 
``Figure.clear()`` is called. This effects the API as it removes active 
subfigure references when clearing a figure.     
This scenario occurred when ``Figure`` was instantiated with ``Subfigure``s.
The bug was thrown in a call to ``_localaxes.remove`` in ``FigureBase.delaxes``.
The children ``Subfigure``s do not register their axes in ``_localaxes``,
which meant that the ``_localaxes`` are empty during clear, leading to the bug.
This was fixed first by moving the ``.clear`` and ``.clf``
methods …
> Fix clearing subfigures

- lib/matplotlib/category.py
- lib/matplotlib/tests/test_category.py
Closes  #22640
Simple fix based on @anntzer's suggestion. Seems to get rid of the deprecation warning if nothing else. 
Makes sense to get it in for 3.5.2? (As it is caused by a change in 3.5 if I understand it correctly.)
Should I add a smoke test for it?
> Fix incorrect deprecation warning

- .github/workflows/nightlies.yml
- doc/users/installing/index.rst
* Resolves #21635
* Resolves #9994
* Closes #21637 ([supersedes](https://github.com/matplotlib/matplotlib/pull/21637#issuecomment-1082582723))
This PR adds a `nightlies.yml` GitHub Action workflow that uses the `gh` CLI API to download the 'wheels' artifact from the latest completed build of the `cibuildwheel` workflow from the 'main' branch (idea taken from https://github.com/actions/download-artifact/issues/3#issuecomment-1017141067).
<details>
<summary>gh run example:</summary>
```console
$ gh run --repo matplotlib/matplotlib list --branch main --workflow cibuildwheel.yml
STATUS  NAME                                                                  WORKFLOW         BRANCH  EVENT         ID          ELAPSED   AGE
✓       Merge pull request #22719 from …
```
> CI: Add GHA workflow to upload nightly wheels

- lib/matplotlib/tests/test_triangulation.py
- lib/matplotlib/tri/tripcolor.py
tripcolor was ignoring ```clim``` input.
Added parameters to collection instantiations in tripcolor to ensure that all parameters are being handled properly (including ```kwargs```).
Closes #22726
Example code:
```
x, y, z = np.random.rand(100), np.random.rand(100), np.random.rand(100)
tripcolor(x, y, z, clim=(0.25, 0.75))
colorbar()
show()
```
> Added clim support to tripcolor

- doc/api/next_api_changes/deprecations/22725-AL.rst
- lib/matplotlib/tests/test_texmanager.py
- lib/matplotlib/texmanager.py
Previously, TexManager needed to call get_font_config at a specific
place in the middle of processing to update some internal attributes
before proceeding with TeX source generation.  Instead, move towards
making TexManager stateless (except for caching), i.e. the user facing
API should be thought of as a bunch of independently callable functions
`make_tex()`, `make_dvi()`, etc. (they will probably stay as methods on
a "empty" TexManager object for a long time for backcompat, in fact).
> Move towards making texmanager stateless.

- lib/matplotlib/backend_managers.py
If not overridden, this will crash since it attempts to call `None()`.
> Fix deprecation of backend_tools.ToolBase.destroy

- lib/matplotlib/backends/_backend_gtk.py
- lib/matplotlib/backends/backend_qt.py
- lib/matplotlib/backends/backend_wx.py
Note, the Tk backend in 3.5 uses an old subplot tool that was manually generated, so that part of #22743 has been dropped.
> Backport PR #22743: Fix configure_subplots with tool manager

- azure-pipelines.yml
setuptools 60 re-enabled their local copy of `distutils`: https://github.com/pypa/setuptools/pull/2896
This apparently fails to set up paths that can find `msbuild`, so switch back the standard library `distutils`.
> Use system distutils instead of the setuptools copy

- setup.py
We missed relaxing the requirement in
https://github.com/matplotlib/matplotlib/pull/21501
The 3.5.x branch is already un-pinned.
> BLD: do not put an upper bound on pyparsing

- .github/workflows/nightlies.yml
Resolves #22757 
Amends PR #22733
Add the `--skip-existing` option for `anaconda upload` to
> Skip errors on package batch upload if it already exists
This will keep the [`nightlies.yml` workflow](https://github.com/matplotlib/matplotlib/blob/162e30645dd38cb265e315f3650a7d8dee8c4a5c/.github/workflows/nightlies.yml) from erroring out if no new wheels were generated, or if a workflow is manually rerun.
As `anaconda-client` does not have any stable releases on PyPI that support the API desired for uploads (c.f. https://github.com/Anaconda-Platform/anaconda-client/issues/540), pin it to the last commit on https://github.com/Anaconda-Platform/anaconda-client known to install and work (which is the merge commit of https://github.com/Anaconda-Platform/anaconda-client/pull/589). This is done for …
> MNT: Skip existing wheels during nightly wheel upload

- azure-pipelines.yml
- lib/matplotlib/animation.py
- lib/matplotlib/backends/backend_pdf.py
https://pillow.readthedocs.io/en/stable/deprecations.html#constants
Image.None -> Image.Dither.None
Image.ADAPTIVE -> Image.Palette.ADAPTIVE
un-break CI by not triggering warnings from Pilllow
> FIX: account for constant deprecations in Pillow 9.1

- lib/matplotlib/colorbar.py
- lib/matplotlib/tests/test_colorbar.py
This was accidentally broken in 16d639b (oops): `panchor` and
`loc_settings["panchor"]` can be different, so it is incorrect to
replace one by the other.
> Fix colorbar stealing from a single axes and with panchor=False.

- lib/matplotlib/axes/_axes.py
After https://github.com/matplotlib/matplotlib/pull/20331 this is not valid.
> Remove outdated doc for pie chart

- lib/matplotlib/_constrained_layout.py
- lib/matplotlib/layout_engine.py
Closes #22673
`tight_layout` and `constrained_layout` were both calling `backend_bases._get_renderer`.  However, that was probably too low-level, and seems to cause canvas-dpi related flakiness as in #22673, in particular some users were seeing changed dpi because `savefig.format` was set to a vector backend. 
This uses the more robust algorithm in `_tight_layout.get_renderer`.  In particular if `fig.canvas` already exists and has a renderer, use that because it means the user has already (perhaps interactively) created a canvas.  This stops prematurely falling back to a default canvas indicated by `savefig.format`.  This probably _mostly_ worked for folks because the default `format` is `png` which is enough like on-screen display that things didn't break.   …
> FIX: maybe improve renderer dance

- examples/mplot3d/projections.py
- examples/scales/asinh_demo.py
- lib/matplotlib/scale.py
These are not displayed in the documentation. Not sure if that is caused by the formatting or not, but at least the projection example had incorrect formatting. (The others just "old".)
> Fix LaTeX formatting in examples

- examples/misc/demo_agg_filter.py
- examples/misc/svg_filter_line.py
- lib/matplotlib/tests/test_agg.py
The full word `transform` fits, so there's no need to abbreviate.
> Fix 'misspelled' transform variable

- lib/matplotlib/figure.py
Merge pull request #22732 from jklymak/fix-renderer-dance
FIX: improve cached renderer dance
(cherry picked from commit 9e0eb54fd98bb804f51a74101db88164870a2458)
The changes had to be moved to figure.py due to a major refactoring that will
be released in 3.6 that is already on main.
> Backport PR #22732: FIX: maybe improve renderer dance

- lib/matplotlib/tests/test_backend_ps.py
Reverts matplotlib/matplotlib#22442
Eventually we expect that the environment on the OSX machines will update which ever dependency is the problem and we can remove this work-around.
Hopefully what ever the problem was we will jump over it on the other CI systems.
> Revert "CI: skip test to work around gs bug"

- doc/api/prev_api_changes/api_changes_3.0.0.rst
- doc/users/prev_whats_new/changelog.rst
- lib/matplotlib/figure.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_figure.py
- lib/matplotlib/tests/test_usetex.py
Follow on to #22138 adjusting the canonical name.
> MNT: prefer Figure.clear() as canonical over Figure.clf()

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Improve bar_label method
Fix #22414
> Improve bar_label annotation

- lib/matplotlib/testing/compare.py
Chaining an empty _ConverterError doesn't add useful info; instead,
print out the output stream.
e.g. modify _GSConverter to use the invalid `-sDEVICE=1234`; previously
`_GSConverter()("foo", "bar")` would give:
```
File ".../matplotlib/testing/compare.py", line 110, in __call__
self._read_until(b"\nGS")
File ".../matplotlib/testing/compare.py", line 95, in _read_until
raise _ConverterError
matplotlib.testing.compare._ConverterError
The above exception was the direct cause of the following exception:
File "<string>", line 1, in <module>
File "/home/antony/src/extern/matplotlib/lib/matplotlib/testing/compare.py", line 112, in __call__
raise OSError("Failed to start Ghostscript") from err
OSError: Failed to start …
```
> Tweak _ConverterError reporting.

- lib/matplotlib/testing/compare.py
This lead me down a several hour rabbit hole, but on Inkscape 1.1.2 (0a00cf5339, 2022-02-04, custom) I need these patches for the test to run locally.    I am not convinced that the version of inkscape this is actually the problem though.  I updated on March 3 and I only started having trouble with the tests in the last few days.  I'm happy to share my pacman logs if someone wants to chase this down.
> Fix inkscape tests

- doc/users/explain/performance.rst
"Simplification" could be understood as "drawing a marker with a
simpler shape", whereas subsampling exactly describes the effect of
*markevery*.
> Replace "marker simplification" by "marker subsampling" in docs.

- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/tests/baseline_images/test_backend_ps/coloredhatcheszerolw.eps
- lib/matplotlib/tests/test_backend_ps.py
Closes #22792
Color was not set when linewidth = 0. This adds a condition that either linewidth is non-zero or there are hatches.
~I'm having problem adding a test for this as the generated eps-files differ in size when converted to png.~ Edit: the test code was more clever than me...
> Fix ps export of colored hatches with no linewidth

- lib/matplotlib/axes/_base.py
- lib/matplotlib/collections.py
- lib/matplotlib/patches.py
- lib/matplotlib/rcsetup.py
- lib/matplotlib/sphinxext/plot_directive.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_patches.py
- lib/matplotlib/tests/test_text.py
- lib/matplotlib/text.py
Related to  #21959
Added tests for some of the errors.
> Use repr in error messages

- doc/api/prev_api_changes/api_changes_3.0.0.rst
- doc/users/prev_whats_new/changelog.rst
- lib/matplotlib/figure.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_figure.py
- lib/matplotlib/tests/test_usetex.py
Merge pull request #22138 from stanleyjs/subfigure-clear
Fix clearing subfigures
(cherry picked from commit a395083238625500dd3fa879e4976617d5353342)
I think that we should backport #22735 at the same time.
> Backport PR #22138: Fix clearing subfigures

- doc/api/index.rst
- doc/users/project/history.rst
- examples/misc/pythonic_matplotlib.py
- examples/subplots_axes_and_figures/multiple_figs_demo.py
- lib/matplotlib/__init__.py
- lib/matplotlib/pyplot.py
- tutorials/introductory/images.py
- tutorials/introductory/lifecycle.py
- tutorials/introductory/pyplot.py
- tutorials/introductory/quick_start.py
- tutorials/text/text_intro.py
Closes #18249
I search for every use of "object-oriented" in the code base and make sure they all had some reference to the https://matplotlib.org/devdocs/users/explain/api_interfaces.html 
```
$ ack 'object[- ]oriented'
doc/api/index.rst
125:At its core, Matplotlib is an object-oriented library. We recommend directly
138:- Most of the :ref:`examples <examples-index>` use the object-oriented approach
doc/users/explain/api_interfaces.rst
11:  been called an "object-oriented" interface.
doc/users/prev_whats_new/changelog.rst
1264:    object-oriented and pylab interfaces. It is now strictly object-oriented -
doc/users/prev_whats_new/github_stats_3.1.1.rst
177:* :ghissue:`1219`: Show fails on figures created with the object-oriented system
doc/users/prev_whats_new/github_stats_3.5.0.rst
418:* …
```
> DOC: Add links to explicit vs implicit API everywhere "OO" is used

- lib/matplotlib/figure.py
Closes #22804 
Not clear that SubFigures shouldn't get their own callback - @anntzer  and @greglucas  better understand how these work or what the right scope should be.  
> FIX: callback for subfigure uses parent

- lib/matplotlib/quiver.py
Instead of registering a callback to update itself whenever the dpi
changes, do the same thing as every other artist which depends on dpi
(e.g. FancyArrowPatch), i.e. update oneself as needed.  We can still
save duplicate calculations by only doing the init if the figure dpi
changed compared to last time.
Also drop _new_UV, which is never read.
Closes #22804.
> Replace quiver dpi callback with reinit-on-dpi-changed.

- lib/matplotlib/colors.py
- lib/matplotlib/tests/test_pickle.py
Closes #20755 (again), https://github.com/matplotlib/matplotlib/pull/22313#issuecomment-1093359287
> Fix pickling of globally available, dynamically generated norm classes.

- lib/matplotlib/contour.py
- lib/matplotlib/tests/test_contour.py
The find_nearest_contour function was defined incorrectly. I fixed the bug and added a simple test, based on the original issues test. 
Thank you @jhelmboldt for finding this issue and offering a solution to it.
Closes #22762
> Fixed bug in find_nearest_contour

- doc/devel/gitwash/development_workflow.rst
- doc/devel/gitwash/following_latest.rst
- doc/devel/gitwash/maintainer_workflow.rst
- doc/devel/gitwash/patching.rst
- doc/devel/gitwash/set_up_fork.rst
> Backport PR #22199 on branch v3.5.x (DOC: git:// is deprecated.)

- lib/matplotlib/backends/_backend_pdf_ps.py
- lib/matplotlib/tests/test_backend_pdf.py
Since https://github.com/matplotlib/matplotlib/pull/20804 isn't merged yet, the commit https://github.com/matplotlib/matplotlib/commit/1b53070f7c5ba8d9edbb855435960e30ae8cbd5a can go as a hotfix for https://github.com/matplotlib/matplotlib/issues/21893.
> Specify font number for TTC font subsetting

- lib/matplotlib/backends/_backend_tk.py
Fixes #22836 introduced in #22163
- N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
> Fix Tk error when updating toolbar checkbutton images

- lib/matplotlib/axis.py
- lib/matplotlib/projections/polar.py
The tick class hierarchy has a standard mechanism for creating ticks
via `_get_tick()` The only element that is changing in these functions
is the tick class. All other logic is identical.
This PR makes the tick class a class attribute of Axis so that we can
use one generic `_get_tick` implementation across all Axis subclasses.
Note that users/downstream libraries can still define their own
`_get_tick()` methods on subclasses if they want to have a different
behavior.
> Simplify tick creation

- lib/matplotlib/tests/test_ticker.py
This avoids the floating point issues with tests in the asinh tick locator by moving away from the 100 log10 cliff. This was failing with the new AVX instruction updates in numpy. The underlying issue here is that the floating point accuracy around 100 changes from one side to the other and the `floor()` call doesn't accept precision arguments. This is not what we are trying to test, so just move the test values away from that edge.
Closes #22708
Showing the tests passing on my fork: https://github.com/greglucas/matplotlib/actions/runs/2177190522
- [N/A] New features are documented, with examples if plot …
> TST: Avoid floating point errors in asinh ticker

- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_bbox_tight.py
- lib/matplotlib/tests/test_colorbar.py
- lib/matplotlib/tests/test_constrainedlayout.py
- lib/matplotlib/tests/test_contour.py
- lib/matplotlib/tests/test_figure.py
- lib/matplotlib/tests/test_subplots.py
- lib/matplotlib/tests/test_units.py
> Remove non-needed remove_text=False.

- doc/api/next_api_changes/removals/22738-JL.rst
- examples/misc/custom_projection.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/figure.py
- lib/matplotlib/projections/geo.py
- lib/matplotlib/projections/polar.py
- lib/matplotlib/spines.py
- lib/matplotlib/tests/test_axes.py
- lib/mpl_toolkits/axes_grid1/mpl_axes.py
- lib/mpl_toolkits/axes_grid1/parasite_axes.py
- lib/mpl_toolkits/axisartist/axislines.py
- lib/mpl_toolkits/axisartist/floating_axes.py
- lib/mpl_toolkits/mplot3d/axes3d.py
We (myself and @neil-gurnani) consolidated all implementations of cla/clear under a clear method (the clear functionality is implemented in clear, and cla calls clear for the sake of minimizing code duplication and improving maintainability). We added 2 tests ensuring subclasses do not override cla. Existing tests for cla were left as-is; since cla calls clear, coverage is not compromised.
Every subclass has both cla and clear, since it was mentioned in #22738 that cla is still too widely used to be fully deprecated as of now. We added appropriate docstrings/comments for all cla/clear methods.
We left all original '_api.deprecated' decorators as-is but did not add any new decorators (please let us know if this is needed).
Finally, please let us know if there's any issue with this PR we …
> MNT: make Axes.cla an alias for Axes.clear in all cases

- doc/api/next_api_changes/deprecations/22813-GL.rst
- lib/matplotlib/figure.py
This removes callbacks from the figure level. It only allowed the "dpi_changed" signal, which is not used anywhere in the library anymore after #22807
A quick note that `resize_event` is apparently not always emitted on a dpi change, but forcing it with `self.canvas.resize_event()` triggers some other test failures, so I'm not sure we want to send that signal within the dpi change routine either. I think this is more of a messaging thing in what do we want to list as an alternative rather than a show-stopper and needing to keep this signal around.
- …
> MNT: Deprecate figure callbacks

- lib/matplotlib/backend_tools.py
> Slightly simplify twin axes detection in MEP22 zoom.

- doc/api/prev_api_changes/api_changes_0.91.0.rst
- doc/api/prev_api_changes/api_changes_0.98.x.rst
- doc/api/prev_api_changes/api_changes_0.99.x.rst
- doc/api/prev_api_changes/api_changes_1.3.x.rst
- doc/api/prev_api_changes/api_changes_1.4.x.rst
- doc/api/prev_api_changes/api_changes_1.5.0.rst
- doc/api/prev_api_changes/api_changes_2.2.0.rst
- doc/api/prev_api_changes/api_changes_3.0.0.rst
- doc/api/prev_api_changes/api_changes_3.1.0.rst
- doc/api/prev_api_changes/api_changes_3.2.0/behavior.rst
- doc/users/explain/interactive_guide.rst
- doc/users/prev_whats_new/whats_new_3.5.0.rst
- lib/matplotlib/__init__.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_base.py
Primarily in the old release notes, stuff that was removed over time.
Also some fixes that should lead to working cross-references in pyplot documentation.
I will continue along these lines as time allows and at some time regenerate the whole missing references-file.
> Fix removed cross-references

- lib/matplotlib/dviread.py
- lib/matplotlib/tests/test_usetex.py
- lib/matplotlib/textpath.py
dviread.Text specifies individual glyphs in parsed dvi files; this is
used by the pdf and svg backends (via textpath, for svg) to parse the
result of usetex-compiled strings and embed the right glyphs at the
right places in the output file (as a reminder, agg currenly uses dvipng
to rasterize the dvi file, and the ps backend relies on pstricks).
Unfortunately, if third-party backends (e.g. mplcairo) want to do use
the same strategy as pdf/svg, then they need to jump through a few hoops
(e.g. understand PsfontsMap and find_tex_font) and use some private APIs
(_parse_enc), as explained below.  Try to improve the situation, by
adding some methods on the Text class (which may later allow deprecating
PsfontsMap and find_tex_font as public API).
First, the actual font to be used is speficied …
> Improve usability of dviread.Text by third parties.

- lib/matplotlib/_mathtext.py
- lib/matplotlib/tests/test_mathtext.py
This makes the definitions much easier to read, by removing the need to
use Group() and Suppress(): previously, these would be used to nest the
parsed tokens and remove the unnecessary ones (e.g, braces), but such
tokens can also easily be ignored by giving names to the tokens we use
(instead of accessing them by position).  (See e.g. the implementation
of subsuper, which is also somewhat simplified.)
Also remove a few other pyparsing combinators that are not
needed: Combine (just concatenate the strings ourselves), FollowedBy
(use lookahead regexes), Literal (use plain strings, in particular
braces which are very common).
Also remove right_delim_safe, as self._right_delim already includes the
backslash-escaped closing brace rather than the unescaped one
(right_delim_safe dates back to …
> Use named groups in mathtext parser.

- examples/specialty_plots/leftventricle_bulleye.py
- tutorials/colors/colorbar_only.py
AFAICT these do not affect the resulting colorbar at all (run the code
before and after to compare).
> Remove some unnecessary extra boundaries for colorbars with extensions.

- doc/users/next_whats_new/snap_selector.rst
- lib/matplotlib/tests/test_widgets.py
- lib/matplotlib/widgets.py
Snap SpanSelector position to specific values.
```python
from matplotlib.widgets import SpanSelector, RectangleSelector
y = np.arange(25)
snap_values = np.append(y-0.5, [y[-1] + 0.5])
snap_values_2D = np.array([y]*2)
ax.plot(y, 'o')
span = SpanSelector(ax, print, direction='horizontal',
interactive=True,
drag_from_anywhere=True,
snap_values=snap_values)
```
> Snap selectors

- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
- lib/matplotlib/tests/test_colorbar.py
- tutorials/introductory/usage.py
Manual backport of #22313; there were conflicts in `lib/matplotlib/axes/_base.py` (due to #21398 not being backported), and `lib/matplotlib/tests/test_colorbar.py` (due to an additional test on `main` conflicting with the new one here).
> Backport PR #22313 on branch v3.5.x (Fix colorbar exponents)

- lib/matplotlib/dates.py
- lib/matplotlib/tests/test_dates.py
Closes #22472
Maybe this should go in 3.5.2 (previous related fix went in 3.5.1)? Marking as 3.5.2 for now.
> Fix year offset not always being added

- lib/matplotlib/_mathtext.py
- Don't return fontsize from _get_glyph anymore, as the value is always
unmodified from the passed-in value.
- Rename `fname` to `family` (it is not a filename, which is what
`fname` usually means).
- List mathtext commands using raw strings.
> Small cleanups to mathtext.

- doc/api/next_api_changes/deprecations/22883-AL.rst
- lib/matplotlib/tests/test_triangulation.py
- lib/matplotlib/tri/tripcolor.py
For incorrect number of parameters, switch to raising a (standard)
TypeError and use a standard-ish signature mismatch error message.  Note
that exception type stability was already broken in 3.6 because it was
previously an IndexError (that was triggered later) and 703b574 changed
that to a ValueError.
Also deprecate support for passing extra parameters (as we now tend to
do for all such overly accepting APIs).  Note that the changelog entry
states that such parameters were previously silently ignored, even
though the patch replaces a warn_external() by a warn_deprecated(); this
is simply because the warn_external() wasn't present yet in the last
released version.
Also closes #22882.
> Tweak argument checking in tripcolor().

- doc/api/next_api_changes/deprecations/22885-AL.rst
- lib/matplotlib/backends/backend_pdf.py
When Op was converted to an enum, the Operator class could have been
folded into it; this PR implements that.  Also deprecate `.op` in favor
of the standard `enum.value` interface.  Also fix "extra" commas in the
enum definition (which didn't actually matter, as enum init unpacks
tuple args, but we may just as well do things properly).
> Deprecate two-layered backend_pdf.Op enum.

- doc/devel/dependencies.rst
A bit redundant as if you are in a notebook where it is usable you already have
ipykernel installed but better to be explicit.
> DOC: add ipykernel to list of optional dependencies

- doc/api/next_api_changes/removals/22107-OG.rst
- doc/devel/MEP/MEP27.rst
- doc/users/explain/interactive_guide.rst
Tried the sphinx-lint tool, https://github.com/sphinx-contrib/sphinx-lint,  and found some issues (and I knew of an issue with one of my previous removal notes so I added it here).
There are still a bunch of warnings about trailing whitespaces and tab usage (primarily in old release notes and copied git output), but in the long run, it may be an idea to consider using this for checking the rst-files.
<details><summary>Output from sphinx-lint after this PR</summary>
<p>
```
[2] doc/devel/MEP/MEP22.rst:170: code sample missing surrogate space before plural: '``set_tool_keymap(self, name, ``*'
[2] doc/users/prev_whats_new/whats_new_1.3.rst:166: code sample missing surrogate space before plural: '```\nA call to  without any arguments now\nacts the same as ``s'
[2] …
> Fix documentation markup issues

- .github/workflows/tests.yml
If people push multiple commits to PRs (like I did in https://github.com/matplotlib/matplotlib/pull/22912) this will cancel the runs. I've used this for months in other repos and it seems to work well. It could be added to other GH actions workflows but I'm assuming `tests.yml` is the only one slow enough to really matter, but I'm happy to add this elsewhere if desired!
N/A
> CI: Add concurrency skips for GH Actions

- lib/matplotlib/pyplot.py
Still not clear to me: Does this have to be a public function? When
would a user call it explicitly?
> Clarify docstring of [un]install_repl_displayhook()

- lib/matplotlib/font_manager.py
add win32 fonts directory check
> FIX: skip sub directories when finding fonts on windows

- lib/matplotlib/backend_bases.py
- lib/matplotlib/tests/test_lines.py
Closes #22930
Test fails on `main` but passes on this PR
> BUG: Fix regression with ls=(0, ())

- environment.yml
- lib/matplotlib/_pylab_helpers.py
- lib/matplotlib/backends/_backend_tk.py
- lib/matplotlib/tests/test_backend_tk.py
- lib/matplotlib/tests/test_backends_interactive.py
- requirements/testing/all.txt
This PR is an attempt to fix #20490. Basically it allows a normally-forbidden `self.window.update()` if we detect that the `tkinter` mainloop is not running. The new test currently still fails though because of some additional leak related to the HiDPI stuff in #19167.
I took the liberty of introducing a new dependency in the test suite. Let me know if I should insert it into any other files or if you would rather find a different way to observe the leak.
> Fix TkAgg memory leaks and test for memory growth regressions

- lib/matplotlib/backends/backend_macosx.py
- src/_macosx.m
This enables the rcParam "figure.raise_window" to control whether the macosx backend raises the window to the foreground or not, keeping consistency with the other backends.
closes #22915
To test this, move the window to the back and it should stay hidden.
```python
from matplotlib import rcParams
rcParams['figure.raise_window'] = False
while True:
plt.plot()
plt.pause(.1)
```
- [N/A] Documentation is sphinx and numpydoc compliant (the …
> ENH: Add option to disable raising the window for macosx

- lib/matplotlib/backends/_backend_tk.py
On Windows, the DPI that Tk sees is 96 for regular screens and some multiple of that for HiDPI screens.
On Linux, the DPI is the true DPI (or at least what the display server tells it is true), and doesn't have anything to do with HiDPI. 
On macOS, the DPI appears closer to 72 by default. If anyone with a retina screen could check what the value of `self._tkcanvas.tk.call('tk', 'scaling')` is in `FigureCanvasTk._update_device_pixel_ratio`, then perhaps we could enable HiDPI-on-startup there, at least.
- [n/a] API …
> Only set Tk scaling-on-map for Windows systems

- environment.yml
- lib/matplotlib/_pylab_helpers.py
- lib/matplotlib/backends/_backend_tk.py
- lib/matplotlib/tests/test_backend_tk.py
- lib/matplotlib/tests/test_backends_interactive.py
- requirements/testing/all.txt
FIX: TkAgg memory leaks and test for memory growth regressions (#22002)
tkinter variables get cleaned up with normal `destroy` and `gc` semantics but tkinter's implementation of trace is effectively global and keeps the callback object alive until the trace is removed.
Additionally extend and clean up the tests.
Closes #20490
Co-authored-by: Elliott Sales de Andrade <quantum.analyst@gmail.com>
(cherry picked from commit 1a016f0395c3a8d87b632a47d813db2491863164)
> Backport PR #22002: Fix TkAgg memory leaks and test for memory growth regressions

- lib/matplotlib/axes/_axes.py
Addresses @efiring's concerns about the docstring and comments in #21884 (issue #21901).
Closes #21901
> Fixed _upcast_err docstring and comments in _axes.py

- lib/matplotlib/collections.py
- lib/matplotlib/tests/test_collections.py
Alternative to #22945
This keeps the None-default case in `self._offsets` and then transforms to the zeros for default math in the `get_offsets()` method. This is necessary to handle the (0, 0) offset case that is desired and distinguishing that from the initial empty offset of None. In particular, this is necessary for the non-transData IdentityTransform passed in during tight_layout calculations.
closes https://github.com/matplotlib/matplotlib/issues/22921
- [N/A] …
> FIX: Handle no-offsets in collection datalim (alternative)

- lib/matplotlib/collections.py
- lib/matplotlib/tests/test_collections.py
This adds a check for whether the collection has offsets
passed in initially. This is necessary to handle the (0, 0) offset
case that is desired and distinguishing that from the initial empty
offset of (0, 0). In particular, this is necessary for the
non-transData IdentityTransform passed in during tight_layout calculations.
closes #22921
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#buildin …
> FIX: Handle no-offsets in collection datalim

- lib/matplotlib/tests/test_backends_interactive.py
`macos-latest` test is failing due to memory leakage being slightly over the threshold. I raised the threshold by 1,000,000 to account for potential fluctuations.
Closes #22959
> Raised macosx memory leak threshold

- lib/matplotlib/backends/backend_macosx.py
- src/_macosx.m
This moves the `set_cursor` definition over to the FigureCanvas rather than requiring a separate module-level call.
> MNT: Move set_cursor to the FigureCanvas

- lib/matplotlib/collections.py
fixes incorrect check if numpy array is none.
- `if x` fails for numpy arrays due to array-broadcasting!
- `if x is None` does what it should...
> fix "is" comparison for np.array

- lib/matplotlib/collections.py
- lib/matplotlib/tests/test_collections.py
> Backport PR #22946: FIX: Handle no-offsets in collection datalim

- lib/matplotlib/tests/test_backend_gtk3.py
- lib/matplotlib/tests/test_backend_qt.py
All the Qt tests in this file already do this, and the remaining one fails if running headless. Similarly for the GTK3 test.
> Skip additional backend tests on import error

- lib/matplotlib/collections.py
- lib/matplotlib/tests/test_collections.py
As noted in https://github.com/matplotlib/matplotlib/pull/22957#issuecomment-1114868463 it would be nice to have a few more tests for the contains of QuadMesh.
* Update QuadMesh.get_cursor_data to handle multiple contains hits
* Test that an empty array doesn't return any cursor_data
* Test a few points in a standard QuadMesh
* Test points within and around a concave QuadMesh …
> TST: Add some tests for QuadMesh contains function

- doc/api/colors_api.rst
- doc/api/matplotlib_configuration_api.rst
- doc/api/pyplot_summary.rst
- lib/matplotlib/__init__.py
- lib/matplotlib/colors.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_colors.py
Color sequences are simply lists of colors, that we store by name in
a registry. The registry is modelled similar to the ColormapRegistry
to 1) support immutable builtin color sequences and 2) to return copies
so that one cannot mess with the global definition of the color sequence
through an obtained instance.
Note that some details of `ColormapRegistry` are different and we need
different docstrings so that it's easier to have a separate class and not try
to factor out some common aspects in a base class.
For now, I've made the sequences used for `ListedColormap`s available
as builtin sequences, but that's open for discussion.
More usage documentation should be added in the color examples and/or
tutorials, but I'll wait with that till after the general approval of
the structure and API. …
> Add a registry for color sequences

- doc/api/next_api_changes/deprecations/22298-GL.rst
- lib/matplotlib/backends/qt_editor/figureoptions.py
- lib/matplotlib/cm.py
- lib/matplotlib/colors.py
- lib/matplotlib/tests/test_colors.py
- lib/matplotlib/tests/test_pickle.py
This is the removal of the deprecated `mpl.cm.cmap_d` dictionary. This is related to #20853, but does not close that as none of the `mpl.cm` globals are deprecated here.
Note that rather than adding pop() to the Registry, I went with the `unregister()` that was already on `cm.unregister_cmap()`. I'm not sure if we'd rather it behave like a dictionary with item access/removal that way, or with the register/unregister methods. I don't have a major preference one way or the other.
> MNT: Remove cmap_d colormap access

- examples/text_labels_and_annotations/rainbow_text.py
The issue was the transformation was done in pixels, which caused issues with dpi changes. I adjusted it by using ```offset_copy``` and converted pixels to inches in the transforms.
I tried to base the solution off what was said in #22893. I am still new to a lot of parts of matplotlib, so if there is a better way to write this process, please let me know!
Previous issue:
Fix (that looks the same on any dpi):
Closes #22893 
> Fixed dpi bug in rainbow text example

- lib/matplotlib/tests/test_backends_interactive.py
Extension of #22959.
We are still seeing intermittent failures on OSX with the memory leak check on tkagg.
This is taking the gentler approach and increasing the limits again, however there may may be a case for skipping these tests until we understand:
1. the remaining source of the leak in tk (and if this is even a real leak vs legitimately still held objects) 
2. we understand the source of the variation
> CI: bump test limit from tkagg on osx

- .pre-commit-config.yaml
- ci/codespell-ignore-words.txt
- lib/matplotlib/tests/test_cbook.py
Resolves #22740
Add https://github.com/codespell-project/codespell as a pre-commit hook that checks for common misspellings of English words in files with the following extensions: `.py`, `.c`, `.cpp`, `.h`, `.m`, `.md`, `.rst`, `.yml`.
Ignore instances of:
* 'ans', 'axises', 'curvelinear', 'hist', 'nd', 'oly', 'thisy', 'wit'
* 'ba' for bound axis and bound args
* 'cannotation' for centered annotation
* 'coo' for COO (Coordinate list)
* 'flate' for Flate compression
* 'inout' for lib/matplotlib/rcsetup.py
* 'ment' for alignment with formatting
* 'whis' for whikser plot
* ~'ot' for offset transform~ (Resolved in PR #22784)
* 'sur' for Big Sur
* 'TE' for triangle elements
and skip checking [doc/users/project/credits.rst](https://github.com/matplotlib/matplotlib/blob/8b1881fd49b49bf85a7b91575 …
> DEV: Add codespell to pre-commit hooks

- lib/matplotlib/cm.py
PR #22298 got merged with typos before PR #22777, which introduced the codespell pre-commit hook, which would have caught them. This simply fixes those typos. :+1: 
> STY: Fix typos in colormap

- doc/conf.py
THIS PR closes #22982 which allows to use the `copy` button on the docs without copying the `>>>` prompt, and only copying the relevant code. 
- [X ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
> Docs: ignore >>> on code prompts on documentation prompts

- lib/matplotlib/tests/test_widgets.py
- lib/matplotlib/widgets.py
Change the way that polygon is initilized to cover edge case of same init values. The method axhspan is no longer used and the polygon is created manually. (closes #22686 )
> Fix RangeSlider for same init values #22686

- doc/users/installing/index.rst
I'm think `python -mpip ...` is supposed to be `python -m pip ...` in both of the cases in the installation guide.
> Fixed installation guide command typo

- tutorials/provisional/mosaic.py
This PR would close #22917 which adds a small paragraph to the docs that shows the string compact notation for `suplot_mosaic`. Additionally, I took the liberty to fix a typo and add a section title to the current tutorial that I believe improves readability a bit.
> docs: add subplot-mosaic string compact notation

- doc/users/installing/index.rst
Skimming the discussion in #23009 I noticed that we are suggesting to use sudo + pip to install things 😱 which is something that you should never do. …
> DOC: do not suggest to sudo pip install Matplotlib

- doc/sphinxext/redirect_from.py
> DOC: Fix charset declaration in redirects

- lib/matplotlib/tests/test_legend.py
Fixed elsewhere. Closes #17960 
> Add test to close legend issue

- lib/matplotlib/font_manager.py
For `FontProperties(stretch=12345)`; before:
```
File ".../matplotlib/font_manager.py", line 888, in set_stretch
raise ValueError()
ValueError
The above exception was the direct cause of the following exception:
File "<string>", line 1, in <module>
File ".../matplotlib/font_manager.py", line 695, in __init__
self.set_stretch(stretch)
File ".../matplotlib/font_manager.py", line 891, in set_stretch
raise ValueError("stretch is invalid") from err
ValueError: stretch is invalid
```
after
```
File "<string>", line 1, in <module>
File ".../matplotlib/font_manager.py", line 695, in __init__
self.set_stretch(stretch)
File ".../matplotlib/font_manager.py", line 900, in set_stretch
raise …
```
> Suppress exception chaining in FontProperties.

- lib/matplotlib/axes/_axes.py
- lib/mpl_toolkits/mplot3d/axes3d.py
> Factor out errorevery parsing for 2D and 3D errorbars.

- examples/text_labels_and_annotations/demo_text_path.py
> Demonstrate both usetex and non-usetex in demo_text_path.py.

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Fixes #22622 
Closes #22773 (easier to start all over than to restore everything there)
Before (for test case):
Now:
Thanks @jklymak for coming up with a much better and easier solution than the one proposed in #22773 
> Fix issue with hist and float16 data

- src/_tkagg.cpp
This fixes the following error in mingw gcc toolchain. Also clang
also have same error.
```
src/_tkagg.cpp:274:26: note:   crosses initialization of 'bool tk_ok'
274 |     bool tcl_ok = false, tk_ok = false;
|                          ^~~~~
src/_tkagg.cpp:274:10: note:   crosses initialization of 'bool tcl_ok'
274 |     bool tcl_ok = false, tk_ok = false;
|          ^~~~~~
```
According to C++ standard (6.7.3):
> It is possible to transfer into a block, but not in a way that bypasses
> declarations with initialization. A program that jumps from a point where
> a variable with automatic storage duration is not in scope to a point
> where it is in scope is ill-formed unless the variable has scalar type...
> Fix variable initialization due to jump bypassing it

- doc/api/dates_api.rst
- lib/matplotlib/dates.py
Closes #21880 
Builds on #21993
> Add rrulewrapper to docs

- lib/matplotlib/backends/backend_macosx.py
- lib/matplotlib/tests/test_backend_macosx.py
- src/_macosx.m
This adds the rcParams savefig.directory option into the macosx
backend for the savefig dialog window.
Additionally cleans up some of the UTF8 string allocations in this code block.
Closes #21710
> ENH: Use rcParams savefig.directory on macosx backend

- lib/matplotlib/text.py
> Cleanup Annotation.update_position.

- examples/text_labels_and_annotations/mathtext_examples.py
This changes the "mathtext example" code snippet to not use `ax.fill_between()` to place rectangular background shades but rather use `ax.axhspan()` instead.
https://matplotlib.org/devdocs/gallery/text_labels_and_annotations/mathtext_examples.html
`fill_between()` isn't the right thing to use here, I think. It might do the same thing (as long as the plot isn't interacted with / zoomed out), but it feels real clunky and I think it should not be encouraged to be used like that in this user facing example. I only encountered this because this plot actually was showing up as a usage example on the `plt.fill_between()` API docs page (older version, 3.1.1, changed in current docs it seems) and I found this real odd.
Can rebase if it should go in a different branch.
From 3.1.1 docs screenshot: …
> doc: mathtext example: use axhspan() instead of fill_between() for backdrop rectangle shading

- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/tests/test_units.py
Second attempt: closes #22973
Arrays sometimes don't have all the methods arrays should have, so
add another check here.  Plot requires both ndim and shape and this
will extract the numpy array if x does not have those attributes.
Otherwise leave the object alone, because unit support (currently only
in plot) requires the object to retain the unit info.
> MNT: fix __array__ to numpy

- setupext.py
followup to https://github.com/matplotlib/matplotlib/pull/22755
> Pathlibify autotools invocation in build.

- src/_c_internal_utils.c
> Slight refactor of _c_internal_utils to linewrap it better.

- .github/workflows/tests.yml
The `>` is redirecting instead of setting a minimum, and hiding all the output of that step.
> Fix installing contourpy on CI

- doc/api/axis_api.rst
- doc/api/next_api_changes/removals/23078-GL.rst
- lib/matplotlib/axis.py
Follows the deprecation period
> MNT: Remove deprecated axis.cla()

- doc/api/next_api_changes/removals/23076-GL.rst
- lib/matplotlib/collections.py
- lib/matplotlib/tests/test_collections.py
This follows the deprecation period.
> MNT: Remove positional argument handling in LineCollection

- doc/api/next_api_changes/removals/23079-GL.rst
- lib/matplotlib/backend_bases.py
This removes these methods following the deprecation.
> MNT: Remove key_press and button_press from FigureManager

- doc/api/next_api_changes/deprecations/23081-OG.rst
- lib/matplotlib/dates.py
- lib/matplotlib/tests/test_dates.py
As discussed in #23013 it may make sense to deprecate `date_ticker_factory` since `AutoDateLocator` and `AutoDateFormatter` has been available for 15-16 years.
> MNT: Deprecate date_ticker_factory

- doc/devel/documenting_mpl.rst
Slightly tweaked the wording so that it repeats that options must be at the end on windows cause the original wording was a bit ambiguous.
> more explicit in windows doc build instructions

- lib/matplotlib/tests/test_figure.py
For historic reasons, this test was in `test_gca()`: Originally the test test tested that `gca()` picks up the Axes created by `add_axes()`. But not passing a parameter was deprecated and the test turned into a check that is
doesn't work anymore. The test is now better placed in `test_invalid_figure_add_axes()`.
The `assert ... is None` stems also from the deprecation period. I does not make sense now that an exception is raised.
> Move test that fig.add_axes() needs parameters

- src/_tkagg.cpp
Wrapping the internally raised exception should make it easier
to debug any failures.  Test e.g. by replacing `__file__` by
`_file_` in the same source file and recompiling to trigger an
AttributeError-that-gets-wrapped-by-ImportError.
See https://github.com/matplotlib/matplotlib/issues/23074#issuecomment-1132368413.
> Normalize tk load failures to ImportErrors.

- lib/matplotlib/dviread.py
`python -mmatplotlib.dviread` is useful to verify how matplotlib parses
dvi constructs, but the output inverted the width and height of boxes.
> Fix width/height inversion in dviread debug helper.

- lib/matplotlib/axes/_base.py
- lib/matplotlib/tests/test_axes.py
Closes #23083 (IMO).
FWIW I agree that the current behavior can be a bit confusing (I'm not sure really like the whole data kwarg business due to the confusion it creates in combination with plot()'s weird signatures, but that ship has sailed long ago).
> Improve error for invalid format strings / mispelled data keys.

- lib/matplotlib/backend_bases.py
We really only care about whether the attribute is present (even
nowadays, _needmain is always False; it appears to never have changed in
IPython's history).
> Tweak check for IPython pylab mode.

- lib/matplotlib/pyplot.py
- lib/matplotlib/testing/conftest.py
- lib/matplotlib/tests/test_backend_template.py
Followup to the introduction of FigureCanvas.new_manager (#22925): allow backend
modules to not define new_figure_manager anymore, in which case we
derive the needed function from FigureCanvas.new_manager.  (In the
future, I plan to do the same with draw_if_interactive and show, so that
"a backend is just a module with a FigureCanvas class"; the advantage is
that the FigureCanvas subclass provided by the module can inherit
methods as needed from the parent class.)
For backcompat, the old codepath is maintained (and has priority).
To test this, manually alter backend_bases._Backend.export and remove
the new_figure_manager entry from the exported functions, which deletes
that global function from all of the builtin methods (actually, we'll
need a deprecation cycle), and check that pyplot …
> Derive new_figure_manager from FigureCanvas.new_manager.

- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_pyplot.py
closes #23042
In #22005 we change `pyplot` so that at import time we do not force a switch of
the backend and install the repl displayhook.
However, this meant that in some cases (primarily through `ipython --pylab`) to
end up with a session where `install_repl_displayhook` had never been called.
I'm still thinking about how to test this.
> FIX: ensure switching the backend installs repl hook

- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/tests/test_image.py
np.spacing can return negative values, so we need an abs().
Closes #23108.
> Fix _g_sig_digits for value<0 and delta=0.

- lib/matplotlib/tests/test_pyplot.py
It's basically here for that purpose...
Followup to #23057.
> Reuse subprocess_run_helper in test_pylab_integration.

- lib/matplotlib/tests/test_backend_tk.py
- lib/matplotlib/tests/test_backends_interactive.py
Stopgap solution for #23094.
Mid-term we should get the CI environment sorted out to have a working Tk setup. But until then, it's better to xfail than to have all PRs cluttered with these failures.
This is a blind attempt. - CI will decide whether I did everything correctly.
> Try to unbreak CI by xfailing OSX Tk tests

- tutorials/text/text_intro.py
Seems that when the docs are generated ([here](https://matplotlib.org/3.5.0/tutorials/text/text_intro.html#titles)), it outputs the default (which is actually 6) so this bit of text is wrong and redundant.
> DOC fixed duplicate/wrong default

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Closes #22910 
Also handles nan in vlines and hlines better. Earlier it "worked", but with a run-time warning. The bounding box was not scale correctly though.
Not sure if the way bounds are tested here is the best possible.
> Handle NaN in bar labels and error bars

- lib/matplotlib/_api/deprecation.py
This breaks the summary from Pytest when warnings are errors, as then you just get a bunch of:
```
FAILED lib/matplotlib/tests/test_getattr.py::test_getattr[matplotlib.afm] - matplotlib._api.deprecation.MatplotlibDeprecationWarning:
```
with no real context as to the problem.
Also, as noted at the original PR [1], it makes setting `filterwarnings` more complicated.
[1] https://github.com/matplotlib/matplotlib/pull/11224#issuecomment-435167674
- [?] API changes documented in `doc/api/next_api_changes/` (follow …
> Remove newline from start of deprecation warnings

- lib/matplotlib/afm.py
- lib/matplotlib/fontconfig_pattern.py
- lib/matplotlib/tight_bbox.py
- lib/matplotlib/tight_layout.py
- lib/matplotlib/type1font.py
The default message already says more than enough over the manually created one, e.g.,
```
The module matplotlib.afm is deprecated since 3.6.
```
vs.
```
The matplotlib.blocking_input module was deprecated in Matplotlib 3.5 and will be removed two minor releases later.
```
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-do …
> Make module deprecation messages consistent

- requirements/testing/all.txt
The upstream issue [1] has been fixed and released in 6.4.
[1] https://github.com/nedbat/coveragepy/issues/1310
> Unpin coverage again

- .github/workflows/tests.yml
- pytest.ini
Apparently, NumPy or whatever dependency has fixed the warnings that we needed to ignore. [Tests with nightlies enabled](https://github.com/QuLogic/matplotlib/actions/runs/2381432665) seem to be passing just fine.
And having this file is causing pytest to drop some config we used to have, making it load files we don't want.
Fixes #23084.
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building …
> Drop pytest warning config in nightly tests

- lib/matplotlib/backends/backend_macosx.py
- src/_macosx.m
Remove some unnecessary calculations and add some comments. Switch
to string passing since we are guaranteed UTF-8 with Python 3 now.
Set text alignment to the right, which matches the qt5agg backend.
Closes #20797
> MNT: Clean up macosx backend set_message

- lib/mpl_toolkits/axes_grid1/parasite_axes.py
This is a remnant of the pre-staleness system, where all pyplot
functions used to call draw_if_interactive to trigger a draw_idle; this
has now been superseded with the stale system which likewise triggers a
draw_idle (here via add_subplot, which marks the figure as stale).
This way, the only remaining places that call draw_if_interactive
internally are in plt.figure() and in figure unpickling.
> No longer call draw_if_interactive in parasite_axes.

- lib/matplotlib/axes/_axes.py
See https://github.com/matplotlib/matplotlib/pull/22929#issuecomment-1137722649
This is not possible to test without importing `astropy`, but if I only had selected this approach first, no one would have objected. (Our `Quantity`-mock class does not show this problematic behavior.)
Thanks @greglucas for suggesting the very simple solution (simple enough so that I didn't believe it would solve it...).
For a description of why the earlier approach using `zeros_like` didn't work see https://github.com/numpy/numpy/issues/21603
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst …
> Minor fix for astropy units support broken in earlier PR

- lib/matplotlib/testing/__init__.py
- lib/matplotlib/tests/test_backend_tk.py
- lib/matplotlib/tests/test_backends_interactive.py
On general grounds, an API like
`subprocess_run_helper(func, *args, timeout, **extra_env)`
is problematic because it prevents one from passing an environment
variable called "timeout".
Instead, pass the extra environment variables as a dict, without
unpacking.
(Technically this has been released in 3.5.2 as public API, but 1) I'm
not really sure it should have been a public API to start with (should
we deprecate it and make it private?), and 2) hopefully tweaking that in
3.5.3 with no deprecation is not going to disrupt anyone...  I can still
put in a changelog entry if that's preferred.)
> Tweak subprocess_run_helper.

- lib/matplotlib/mpl-data/stylelib/_mpl-gallery-nogrid.mplstyle
- lib/matplotlib/mpl-data/stylelib/_mpl-gallery.mplstyle
- plot_types/basic/stackplot.py
Area plots (stackplots) are a fairly common plot type, so I figure should be included in the plot type listing. They're structurally similar to fill_between, which is why I put this in the same 'basic' section
eta: no idea why my rebase/squash isn't working (it is locally) so folks are welcome squash. 
eta2: no idea what combination of button mashing got me to a clean commit
> Add stackplot to plot types listing

- doc/api/next_api_changes/deprecations/23166-ES.rst
- lib/matplotlib/legend.py
There are so many of them, it really doesn't make sense to do positionally.
> Deprecate passing most Legend arguments positionally

- lib/matplotlib/collections.py
- lib/matplotlib/tri/triplot.py
As part of #10148: Docstring update for `Axes.triplot()` and `PatchCollection`.
> Improve docstring of triplot() and PatchCollection

- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_contour.py
Makes sure that `_cachedRenderer` is added to `SubFigure` instances by moving it to `FigureBase`. Closes #23173 
Maybe the code in contour should behave differently, but I assume that sooner or later the same problem may happen in other code when applied to a `SubFigure` and not a `Figure`.
> Make sure SubFigure has _cachedRenderer

- doc/_static/mpl.css
- doc/_templates/donate_sidebar.html
- doc/conf.py
- doc/devel/index.rst
- doc/index.rst
- doc/users/getting_started/index.rst
- environment.yml
- requirements/doc/doc-requirements.txt
[sphinx-design](https://sphinx-design.readthedocs.io/en/pydata-theme/) is replacing sphinx-panels, reduces the amount of custom CSS we have, and is responsive. I have 2 column layout switch to single column at the 'small' transition (768px).
Though there are a few CSS tweaking classes we could apply to get things closer if we wish, I did not try to exactly match the existing layout.
> DOC: Migrate to sphinx-design

- doc/api/next_api_changes/behavior/23170-JMK.rst
- lib/matplotlib/axis.py
- lib/matplotlib/tests/test_axes.py
I think if the user asks for the tick labels, they should be allowed to waste a few cpu cycles actually getting the tick labels rather than forcing a whole draw.  However, its possible I don't understand some subtlety.  
Ref: #6103. Probably a lot more, and many stack overflow issues.  
```python
ax.plot(range(10))
labels = ax.xaxis.get_majorticklabels()
print(labels)
```
```
[Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, ''), Text(0, 0, '')]
```
```
[Text(-2.0, 0, '−2'), Text(0.0, 0, '0'), Text(2.0, 0, '2'), Text(4.0, 0, '4'), Text(6.0, 0, '6'), Text(8.0, 0, '8'), Text(10.0, 0, '10')]
```
> ENH: update ticks when requesting labels

- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_pyplot.py
- Backport PR #23057: FIX: ensure switching the backend installs repl hook
- Merge pull request #23106 from anntzer/tpi
> Backport PR #23057 and #23106

- doc/conf.py
The switcher default value must match a version given in `switcher.json`. We either want to go to `stable` or `devdocs`.
Extracted from #23142, because I don't want to mix this fix with position and styling discussions.
Additional question to @QuLogic: Local and CI versions will still not work after the fix, because they cannot access `switcher.json`:
> Access to XMLHttpRequest at 'https://matplotlib.org/devdocs/_static/switcher.json' from origin 'https://output.circle-artifacts.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Is it possible to set `Access-Control-Allow-Origin` on the website (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin)?
> Point the version switcher to a name listed in switcher.json

- lib/matplotlib/backends/backend_agg.py
This avoids the need for getattr checks.  We explicitly don't do the
same for FigureCanvasAgg.renderer because 1) if _lastKey has been set to
a non-None value, then renderer has also been set and 2) initing
renderer to e.g. None would change the possible types of a public
attribute.
> Init FigureCanvasAgg._lastKey in `__init__`.

- lib/matplotlib/tests/test_backend_tk.py
- lib/matplotlib/tests/test_backends_interactive.py
Try to unbreak CI by xfailing OSX Tk tests (#23095)
* Try to unbreak CI by xfailing OSX Tk tests
Stopgap solution for #23094
* Update lib/matplotlib/tests/test_backend_tk.py
* Update lib/matplotlib/tests/test_backend_tk.py
Co-authored-by: Oscar Gustafsson <oscar.gustafsson@gmail.com>
(cherry picked from commit d6ee414ec175870b9fe8c65297e6c56114fe19a3)
> Backport PR #23095: Try to unbreak CI by xfailing OSX Tk tests

- doc/api/next_api_changes/behavior/22745-JMK.rst
- lib/matplotlib/_constrained_layout.py
- lib/matplotlib/_tight_layout.py
- lib/matplotlib/artist.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
- lib/matplotlib/collections.py
- lib/matplotlib/contour.py
- lib/matplotlib/figure.py
- lib/matplotlib/gridspec.py
- lib/matplotlib/image.py
- lib/matplotlib/layout_engine.py
- lib/matplotlib/legend.py
- lib/matplotlib/lines.py
- lib/matplotlib/offsetbox.py
- lib/matplotlib/table.py
- lib/matplotlib/text.py
- lib/matplotlib/widgets.py
- lib/mpl_toolkits/axes_grid1/parasite_axes.py
- lib/mpl_toolkits/axisartist/axis_artist.py
- lib/mpl_toolkits/mplot3d/art3d.py
- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/mplot3d/axis3d.py
This PR is a proof of concept of making renderers globally optional.  We don't need to use this in `tight_layout` because it has a funky `_draw_disabled` context.  However, constrained_layout can have all the renderer tracking pulled out and still works in the tests and interactively so far as I can tell.  
See #22744 for more discussion, but I think deciding on the renderer at the Figure level is the right thing to do, and stop trying to sort it out at a higher level.  
See also:
- https://github.com/matplotlib/matplotlib/pull/21319
- https://github.com/matplotlib/matplotlib/pull/21758
> MNT: Don't require renderer for window_extent and tightbbox

- doc/api/next_api_changes/behavior/23188-JMK.rst
- lib/matplotlib/dates.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_dates.py
Closes #23151 
Currently date axes default to 2000-2010.  A 10-year default date range seems arbitrarily large, and conflicts with the default axes limits of 0-1 (days in the units of Matplotlib numbers).  This changes the default to 1970-01-01 to 1970-01-02, which for the default epoch corresponds to floats 0-1.  
> Mnt new default dates

- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_contour.py
Merge pull request #23174 from oscargus/clabelsubfigures
FIX: Make sure SubFigure has _cachedRenderer
(cherry picked from commit af835787ac405d6021d4ed11e57734873c401b9c)
> Backport PR #23174: Make sure SubFigure has _cachedRenderer

- lib/matplotlib/dates.py
- lib/matplotlib/tests/test_dates.py
~Extended `date_ticker_factory` to return `SecondLocator` and `Microsecondlocator`. The format strings can be discussed.~
Removed dead code.
Added tests for more cases in `dates`.
Should we remove the special handling for dateutil <= 2.3? 2.4 appears to have been release 2014-2015 or so.
https://github.com/matplotlib/matplotlib/blob/65e962008a1f43fca4b1096c6f88685892d1ab2d/lib/matplotlib/dates.py#L1526-L1528
- [N/A] Documentation is sphinx and numpydoc compliant (the docs …
> Add tests for date module

- lib/matplotlib/tri/tricontour.py
- lib/matplotlib/tri/tripcolor.py
As part of #10148: Docstring update for `Axes.tricontour()` and `Axes.tricontourf()`.
> Rework tricontour and tricontourf documentation

- lib/matplotlib/backend_bases.py
As mentioned in #23208, the docs currently link to a post script reference (the blue book) that is on a system with restricted access, so I changed the link to the Red book since I found that on an official adobe site. Also changed the page # to where the reference is in the red book & took a first stab at copy pasting in the official description for offset. 
I think this partially addresses #23220
> Changed offset reference, add small doc

- doc/api/next_api_changes/removals/23237-AL.rst
- lib/matplotlib/patches.py
See #17737 for when the deprecation was introduced.
> Expire BoxStyle._Base deprecation.

- lib/matplotlib/_constrained_layout.py
- lib/matplotlib/_layoutgrid.py
- lib/matplotlib/figure.py
- lib/matplotlib/layout_engine.py
- lib/matplotlib/tests/test_constrainedlayout.py
- tutorials/intermediate/arranging_axes.py
- tutorials/intermediate/constrainedlayout_guide.py
Replaces #20016
We _often_ want a grid of fixed-aspect ratio axes, but constrained_layout and tigt_layout leave large blank spaces between the axes because they only work with the original axes positions, not the aspect-modified versions.  
Here I proposed an extension to constrianed_layout that works for simple grids of axes...
```python
nrows = 2
ncols = 3
for compress in ['constrained', 'compressed']:
print('compress?', compress)
fig, axs = plt.subplots( nrows, ncols, figsize=(4,4),
layout=compress,
sharex=True, sharey=True)
fig.patch.set_facecolor("0.9")
#fig.set_constrained_layout_pads(compress=True)
for i in range(nrows):
for j in range(ncols):
ax = axs[i, j]
ax.set_aspect(1)
pc = ax.pcolormesh(np.random.randn(30, 30))
axs[0, …
```
> ENH: compressed layout

- lib/matplotlib/colorbar.py
- lib/matplotlib/tests/test_colorbar.py
Fixes #23157.  Also added a test for the case where `panchor` is set to something different to the existing anchor setting on the main axes.  Both tests fail without the change in the main code.
> Honour `panchor` keyword for colorbar on subplot

- doc/api/next_api_changes/deprecations/23045-OG.rst
- lib/matplotlib/__init__.py
- lib/matplotlib/testing/_markers.py
- lib/matplotlib/tests/test_backend_bases.py
- lib/matplotlib/tests/test_backend_pdf.py
- lib/matplotlib/tests/test_backend_pgf.py
- lib/matplotlib/tests/test_backend_ps.py
- lib/matplotlib/tests/test_backend_svg.py
- lib/matplotlib/tests/test_determinism.py
- lib/matplotlib/tests/test_legend.py
- lib/matplotlib/tests/test_text.py
- lib/matplotlib/tests/test_usetex.py
Identical test marks were defined in multiple files. This moves them to `testing.marks` (for consistency, even if they were only defined in a single file).
Also deprecates `matplotlib.checkdep_usetex`.
Closes #14455
- [N/A] Documentation is sphinx and numpydoc compliant (the …
> MNT: Merge locally defined test marks

- lib/matplotlib/_mathtext.py
Found a minor error in the documentation of `vpack` using the wrong argument name.
The keyword arguments for `HList` and `VList` were not used. I assume that they either should be used (here) or removed. Only makes a difference when trying to call `HList` or `VList` using those arguments, which doesn't happen in the code base (but that I tried in an attempt to fix an issue).
> Correct docs and use keyword arguments in _mathtext.py

- .matplotlib-repo
- lib/matplotlib/__init__.py
Closes #23114, where somebody has installed matplotlib into another
git repo.
Just checking that two levels up is a .git is not enough. We have to make sure this is the matplotlib git repo. I've now added a check that the `__init__.py` is in the folder `lib/matplotlib`. Is there maybe even a better check that this is the matplotlib git repo?
> Only import setuptools_scm when we are in a matplotlib git repo

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/tests/test_axes.py
Increase test coverage, primarily for erroneous input.
> Add tests, improve error messages in axis/_base, and code cleanup

- lib/matplotlib/testing/_markers.py
- lib/matplotlib/tests/test_backend_bases.py
- lib/matplotlib/tests/test_backend_pgf.py
Fixes https://github.com/matplotlib/matplotlib/pull/23045#discussion_r895001860
> Rename test markers

- lib/matplotlib/_mathtext.py
AFAICT, (incorrect) support for the double-backslashed version was
accidentally introduced in 027dd2c.
> Don't allow `r"$\left\\|\right.$"`, as in TeX.

- lib/matplotlib/tests/test_mathtext.py
> Small simplifications to mathtext tests.

- doc/users/next_whats_new/rename_ncol_keyword_in_legend.rst
- lib/matplotlib/backends/qt_editor/figureoptions.py
- lib/matplotlib/legend.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_legend.py
- lib/matplotlib/tests/test_offsetbox.py
Closes #12078
It seems like only legend uses ncol and that nrow is not used (only nrows).
~Will add release note once I get a PR number and I see that I have not missed anything.~ Done!
> Rename ncol parameter in legend to ncols

- lib/matplotlib/testing/compare.py
- lib/matplotlib/tests/test_mathtext.py
Redo of #19201 (decrease size of mathtext svg baselines, by switching to embedding text as text, not as paths), but without removing the other formats or restricting fonts.  Suggested as a preliminary to #22852 (which would just need to move the affected tests to the new `svgastext_math_tests` list.
Intentionally contains an example test in a second commit, which is reverted by the third commit: checkout the second commit to test locally.  I will remove these two commits from history (and hence get rid of the "unclean PR" lint) if this PR gets approved.
This reverts commit ce14a1b.
> Support not embedding glyphs in svg mathtests.

- lib/matplotlib/_api/__init__.py
- lib/matplotlib/image.py
- lib/matplotlib/tests/test_api.py
Found a minor issue basically disabling argument checking.
Also added a check to avoid this type of errors in the code.
> Fix argument checking for set_interpolation_stage

- lib/matplotlib/_mathtext.py
- lib/matplotlib/tests/test_mathtext.py
This also ensures consistency in the names in the error strings; see
e.g. changes in test_mathtext (the contents of `\overline` are indeed a
"body", not a "value").
Renaming "simple_group" to "opt_group" is not only to make definitions
of over/underset fit in a single line, but also because the name seems
semantically more meaningful too.  (req_group, OTOH, is just for
conciseness.)
> Add a helper to generate mathtext error strings.

- lib/matplotlib/backend_bases.py
Follow up to #23223.  I somewhat belatedly remembered that the "Blue Book" was referenced twice in this module, on both the `get_dashes` and `set_dashes` methods.
> DOC: remove Blue Book url

- doc/devel/dependencies.rst
It may be easy to not think about, especially when you already have Inkscape installed...
> DOC: Add note about Inkscape install on Windows

- lib/matplotlib/__init__.py
- lib/matplotlib/backends/qt_compat.py
- lib/matplotlib/pyplot.py
... avoiding having to spell out the `dict.__getitem__` dance, which is
really an implementation detail of rcParams.
> Private helper to get requested backend without triggering resolution.

- lib/matplotlib/backends/qt_compat.py
Also note that `None` is never keyed off `_ETS`, which allows removing
the `None: None` entry have some more simplifications.
Also avoid the need for exception chaining suppression (`raise ... from
None`).
Also clarify the error message when no qt binding can be imported
(the original motivation here; see https://github.com/matplotlib/matplotlib/issues/22673#issuecomment-1154378941).
> Simplify qt_compat, in particular post-removal of qt4 support.

- lib/matplotlib/colorbar.py
Add self.alpha to PathPatch creation in _do_extends method in order for the extend patches of the colorbar to have the correct alpha. (closes #22970)
> Fix Colorbar extend patches to have correct alpha

- lib/matplotlib/colorbar.py
This is unused. Only referenced in a now removed comment.
> MNT: Remove dead code in Colorbar

- lib/matplotlib/backends/backend_svg.py
> MNT: Remove dead code in SVG backend

- examples/scales/semilogx_demo.py
* Resolves #23214 
* [Requested on Gitter](https://gitter.im/matplotlib/matplotlib?at=629ec382da83520ac36ae8f2)
In PR #23130 it was noticed that certain example files had 'test' in their name and were getting picked up automatically by `pytest` accidentally. To avoid this,
https://github.com/matplotlib/matplotlib/blob/8e2987b9804b6eaa32b8ffa40059e0d5267960ee/pytest.ini#L10
was added to `pytest.ini`. While this is sufficient to avoid future problems, removing the word 'test' from example files and replacing it with 'demo', which is commonly used in other matplotlib examples, provides future safeguards.
~~To further this idea, uses of the phrase 'test' in the example docstrings are replaced with 'demo'.~~ (do this later on given https://github.com/matplotlib/matplotlib/pull/23219#issuecommen …
> MNT: Rename example files with 'test' in name

- lib/matplotlib/_mathtext.py
- lib/matplotlib/tests/test_mathtext.py
TeX is perfectly happy to start with a closing parenthesis and end with
an opening one; no need to distinguish them.
Also fix a bug with old pyparsing versions for empty `\left\right`
blocks.
> Support inverted parentheses in mathtext.

- lib/matplotlib/colorbar.py
- lib/matplotlib/tests/test_colorbar.py
Closes #22864
Maybe the test can be simplified/written in a better way?
> Fix issue with colorbar extend and drawedges

- lib/matplotlib/backends/backend_pdf.py
- Fix `__str__` for Python3.
`__str__` is never actually used (but can be nice to have for
debugging purposes); still, `str(Name("foo"))` currently returns
`/b'foo'` where the surrounding `b''` is almost certainly a fallout
from the Py2/Py3 str transition; the intent was to return the same
thing as `pdfRepr`, but ascii-decoded.  Fix that.
- Micro-optimize hex escapes.
In the presence of characters to be escaped, `str.translate` is quite
faster than `regex.sub`:
`$ python -mtimeit -s 'from matplotlib.backends.backend_pdf import Name' 'Name("foo\xff\x01")'`
shows a >2x speedup, for example.
(There is no difference when no characters are actually subbed.  I
guess the overhead likely comes from the function calls?)
This is unlikely to matter in reality, but is also shorter and just as
legible …
> Minor tweaks to pdf Name.

- doc/api/next_api_changes/deprecations/23166-ES.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axis.py
- lib/matplotlib/collections.py
- lib/matplotlib/figure.py
- lib/matplotlib/image.py
- lib/matplotlib/lines.py
- lib/matplotlib/offsetbox.py
- lib/matplotlib/patches.py
- lib/matplotlib/table.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_collections.py
- lib/matplotlib/tests/test_patches.py
- lib/matplotlib/text.py
Follow up to and generalization of #23166.
This should have very little impact on the practical use, as it's anyway
error-prone to pass more than a few arguments by position. But enforcing
keyword-only makes future API changes simpler for us.
> Deprecate positional passing of most Artist constructor parameters

- doc/api/next_api_changes/deprecations/23289-AL.rst
- lib/matplotlib/backends/backend_pdf.py
I accidentally removed it without deprecation in #23287.  Unlikely to matter, but I may as well play by the rules.
> Properly make Name.hexify go through a deprecation cycle.

- doc/api/next_api_changes/deprecations/23232-TH.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
the signature is `stem([locs], heads, linefmt=None, ...)`
So we should support both:
```
stem(heads, linefmt='r')
stem(heads, 'r')
```
We had a kwonly deprecation for 3.5 that was aiming at
`stem([locs], heads, *, linefmt=None, ...)`
but now I'd rather relax this to
`stem([locs], heads, linefmt=None, *, ...)`
because it's reasonable to still support `stem(heads, 'r')`. That's
analogous to `plot(y, 'r')`. The code overhead for supporting both
positional and keyword passing for the single `linefmt` parameter
is bearable.
> Fix passing stem markerfmt positionally when locs are not given

- .github/workflows/tests.yml
- lib/matplotlib/tests/test_backends_interactive.py
- lib/matplotlib/tests/test_font_manager.py
Enable the extra dependencies for ubuntu 3.10. 
Disable blitting tests for GTK4-cairo.
A minor addition to the get_font_names test to see which font actually differs.
(The things discussed below are from temporary versions that included more OS and python version tests.)
> Update build environment and improve test

- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_figure.py
This fixes the following error: 
matplotlib\lib\text.py line 1489, dop = self.figure.get_dpi()/72. AttributeError: 'SubFigure' object has no attribute 'get_dpi'.
Effect: in v3.5.2 it is not possible to save a figure with a subfigure to a PDF.
- [N/A ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
> Add get/set methods for DPI in SubFigure

- lib/matplotlib/backends/backend_mixed.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_pgf.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/tests/test_figure.py
- lib/matplotlib/text.py
There has been a mismatch between use dpi property and get/set methods internally. This has caused bugs for SubFigure objects. Please see my previous PR for more details on the issues.
- [ N/A] New features are documented, with examples if plot related.
> Remove internal use of get/set dpi

- lib/matplotlib/tests/test_compare_images.py
Stick uuid onto image 1 to avoid using the same file if the tests run in parallel. ( closes #22992 )
> Fix test_image_comparison_expect_rms

- doc/api/next_api_changes/deprecations/23014-OG.rst
- lib/matplotlib/tests/test_ticker.py
- lib/matplotlib/ticker.py
Earlier `LogFormatter` and `LogLocator` had a bit of an usual API to set parameters. This deprecates those and introduce alternative methods.
~Will add a change note once I realize if any tests are failing and I get a PR number.~ Done!
> Improve consistency in LogLocator and LogFormatter API

- examples/pyplots/fig_axes_customize_simple.py
Since upgrade from matplotlit 3.2 to 3.3, the set_color method for tickline line2d object not work anymore.
While the mechanism behind it still being unknow, the set_color method can be changed to set_markeredgecolor as alternative. 
> Modify example of "Fig Axes Customize Simple"

- requirements/doc/doc-requirements.txt
I don't want to have to backport all the changes necessary to make it work on 3.5.x.
> Pin to an older pydata-sphinx-theme for v3.5.x

- lib/matplotlib/axes/_base.py
- lib/matplotlib/projections/polar.py
There's already some subclasses that return a plain dict (e.g., geo
axes); moreover, the return value is passed to Spine.from_dict which
anyways `**kwargs`-expands it, so that stage also affects whether order
is maintained.
> No need to return OrderedDict from _gen_axes_spines.

- lib/matplotlib/tests/test_axes.py
- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/tests/test_mplot3d.py
Also, add a test for cartesian Axes as well.
Fixes #23308
> Don't draw invisible 3D Axes

- doc/_static/mpl.css
As a corollary to https://github.com/matplotlib/mpl-sphinx-theme/pull/36
> Drop CSS styles that are in mpl-sphinx-theme

- doc/api/next_api_changes/behavior/23270-AL.rst
- doc/api/next_api_changes/deprecations/22507-AL.rst
- lib/matplotlib/_mathtext.py
- lib/matplotlib/tests/baseline_images/test_mathtext/mathtext0_cm_00.svg
- lib/matplotlib/tests/baseline_images/test_mathtext/mathtext0_dejavusans_00.svg
- lib/matplotlib/tests/test_mathtext.py
hyphen-to-unicode-minus replacement now occurs at the parsing stage, and
thus does not need to be done again in get_unicode_index (otherwise,
text hyphens also get incorrectly substituted.
Strictly speaking, one would need either to fully deprecate
get_unicode_index and replace it by a private helper (for which `math`
is always False), or introduce a deprecation period during which users
*must* pass the `math` kwarg (any value other than False results in a
warning) and then another one that deprecates that kwarg; which is quite
long; hopefully the change is in a private-enough part of the library
that we can just do it as is.
Also do some more changes to the mathtext-svg-text-only-tests that I
missed when the feature first went in: only test svg (that's the
point of it...) and only test …
> Fix handling of nonmath hyphens in mathtext.

- examples/lines_bars_and_markers/eventcollection_demo.py
- examples/specialty_plots/mri_with_eeg.py
- examples/units/ellipse_with_units.py
- examples/user_interfaces/mpl_with_glade3_sgskip.py
- examples/userdemo/pgf_fonts.py
- examples/userdemo/pgf_preamble_sgskip.py
- examples/userdemo/pgf_texsystem.py
(Looking at the list of titles at
https://matplotlib.org/stable/gallery/index.html the weak consensus
seems to be using no titlecase (which is also my preference), but
there's certainly room for improved consistency there as well.)
> Tweak examples capitalization/punctuation.

- examples/text_labels_and_annotations/fonts_demo.py
- examples/text_labels_and_annotations/fonts_demo_kw.py
- Unpyplot the examples; assigning the results to "t" doesn't really say
anything (this would be different if the example was about text
objects); other style fixes.
- In the OO example, instead of mutating a global FontProperties, create
one locally and set the properties on it.  (Even better would be to
just do `font = Fontproperties(prop=...)`, but
`FontProperties(family="sans-serif")` currently fails due to confusion
between the family kwarg and fontconfig patterns... #10249)
- x-large bold italic was misplaced in the OO example -- compare with
the kwargs example.
> Cleanup FontProperties examples.

- doc/api/next_api_changes/deprecations/22167-EP.rst
- lib/matplotlib/tests/test_widgets.py
- lib/matplotlib/widgets.py
As noticed in #22146, the use of the selector `visible` attribute is ambiguous. This PR deprecate the `visible` attribute in favour of using `set_visible`/`get_visible` to be consistent with other matplotlib objects.
> Deprecate selector `visible` attribute

- lib/matplotlib/tests/test_backend_bases.py
Panning was very scarcely tested.
> Add tests for pan

- doc/users/next_whats_new/url_active_areas_rotate.rst
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/tests/test_backend_pdf.py
> Correct URL area with rotated texts in PDFs

- lib/matplotlib/artist.py
- lib/matplotlib/tests/test_artist.py
This should fix #21915 with an `isinstance(norm, BoundaryNorm)` check and special logic to figure out the `delta` for calculating the value for the significant digits to show as cursor data output.
I opted to use the boundaries of the `BoundaryNorm` directly, instead of calculating the midpoints of neighboring regions (midpoint is done in the non-`BoundaryNorm` cases).  
I also added tests in `lib/matplotlib/tests/test_artist.py::test_format_cursor_data_BoundaryNorm`. For the tests I compare the cursor data output to identically formatted strings with fixed `delta` taken as the stepping of `np.linspace` that is used to create the boundaries for `BoundarNorm`. The fixed `delta` values are not identical to what this PR computed, but should give identical output for the strings.
**Tests and …
> Fix BoundaryNorm cursor data output

- doc/api/next_api_changes/deprecations/21981-AL.rst
- lib/matplotlib/backends/backend_cairo.py
- lib/matplotlib/backends/backend_gtk3cairo.py
- lib/matplotlib/backends/backend_gtk4cairo.py
- lib/matplotlib/backends/backend_qtcairo.py
- lib/matplotlib/backends/backend_tkcairo.py
- lib/matplotlib/backends/backend_wxcairo.py
This avoids a redundant set_width_height on the caller side, and
prevents the width/height from getting out of sync from the actual
surface size.
Followup to #21981, which conveniently introduces a new API whose
semantics we can still modify :)
> Make RendererCairo auto-infer surface size.

- lib/matplotlib/style/core.py
- lib/matplotlib/tests/test_style.py
> Remove now inexistent "datapath" rcParam from style blacklist.

- .pre-commit-config.yaml
* Use `--pytest-test-first` option over `--django` for name-test-tests for greater clarity of convention. While this commit is somewhat trivial (there is no change in functionality) I personally think that as a developer having `pytest` in the option name makes more sense as it is enforcing the `pytest` default style of naming convention (and matplotlib doesn't use Django).
* Amends PR #23213
- I didn't see that this was updated in https://github.com/pre-commit/pre-commit-hooks/pull/779 for `pre-commit/pre-commit-hooks` `v4.3.0` when I made PR #23213 otherwise I would have just applied it then. Sorry about that.
For further reference see:
* https://github.com/scikit-hep/pyhf/pull/1892
* https://github.com/scikit-hep/scikit-hep.github.io/pull/231
- [N/A] Has pytest …
> MNT: Use '--pytest-test-first' option for naming clarity

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Closes https://github.com/matplotlib/matplotlib/issues/23330.  Fixes a regression, so let's mark this as RC?
> Fix errorbar handling of nan.

- lib/matplotlib/patches.py
The `if not hasattr(self, 'axes'): raise RuntimeError(...)` check was
ineffectual, as artists now always have an Axes attribute, which can
just be None for some artists.  In fact, small Arcs are drawn just fine
without a parent Axes; e.g.
```
from matplotlib.patches import *
fig = figure()
fig.add_artist(Ellipse((.2, .2), .1, .3, angle=45))  # for comparison
fig.add_artist(Arc((.2, .2), .1, .3, angle=45, theta1=0, theta2=45))
```
works just fine.  Remove the check, and adjust the docs accordingly.
On the other hand, large arcs *did* previously fail,
but that occurred a bit further down, when computing
`transforms.BboxTransformTo(self.axes.bbox)` (`self.axes` is None -->
AttributeError).  Fix that by using the figure bbox in that case (as the
point is to limit the …
> Remove ineffective exclusion of Arcs without parent Axes.

- lib/matplotlib/tests/test_text.py
- lib/matplotlib/text.py
... and also tweak test_two_2line_texts to not set up an axes (just a
figure), as it doesn't need that.
Closes #19223 (transform_rotates_text is no longer a problem since #19575).
> Validate Text linespacing on input.

- lib/matplotlib/contour.py
- lib/matplotlib/tests/test_contour.py
I made the `negative_linestyles` for contours toggle-able via kwarg. The only way to toggle this currently is with `rcParams`.
*I am re-opening this issue from a fresh branch. There was some discussion in #23102.*
In the attached issue, we had some discussion on whether this is a good idea or not, but I think it is worth considering. We can maintain current functionality and just apply the kwarg if it is defined. This will not break previous functionality. I wrote some tests for this, but I know they can be improved. I'm not completely certain on using baseline_images with parametrized inputs.
Please use this PR and the attached issue to discuss whether this is a good idea or not. I'm happy to take this in a different direction if there are some better ideas!
Closes #23028
``` …
```
> negative_linestyles kwarg in contour.py

- lib/matplotlib/tests/test_font_manager.py
This should fix the intermittent failures on CI.
The issue is that the test `test_addfont_as_path` was adding an extra font (on top of what we normally discover).  When the test are run in parallel it random if this test and `test_get_font_names` run on the same worker or not. 
> FIX: make sure addFont test removes the test font

- lib/matplotlib/backends/backend_nbagg.py
The _Backend class machinery can autogenerate a backend_module.show()
function, which (in short) calls manager.show() on all managers and then
calls the optionally-provided mainloop() function.
backend_nbagg currently completely bypasses this autogeneration because
it wants to additionally fiddle with callbacks and Gcf (it doesn't need
any mainloop()), but that logic can just as well go to
FigureManagerNbAgg.show() instead.  This way it benefits from the
default-generated show; moreover, it seems a bit strange that figures
shown with manager.show() (instead of plt.show()) do indeed get
displayed, but just don't have their callbacks/Gcf-ness adjusted.
This is also related to the move towards putting show()-generating
information on the canvas class for inheritability (#23090).
**Tests and …
> Remove custom backend_nbagg.show(), putting logic in manager show.

- examples/spines/spines.py
- lib/matplotlib/spines.py
It is really hard to find the Spine class  from the examples given, and it is hard to find the examples from the Spine class.  This attempts to improve that...
> DOC: improve spines crosslinking

- lib/matplotlib/backends/_backend_gtk.py
- lib/matplotlib/backends/backend_gtk3agg.py
- lib/matplotlib/backends/backend_gtk4agg.py
Gtk-based backends require pycairo (cairocffi is unsupported:
https://pygobject.readthedocs.io/en/latest/guide/cairo_integration.html).
Prior to this patch, trying to run gtk{3,4}{agg,cairo} fails *at draw
time* `TypeError: Couldn't find foreign struct converter for 'cairo.Context'`).
This patch moves the import check for cairo to the top of the common
_backend_gtk, and also simplifies backend_gtk{3,4}agg to always use
pycairo (in which case backend_cairo._to_context is a no-op) as they
cannot inter-operate with cairocffi anyways.
> Simplify/improve check for pycairo in Gtk-based backends.

- setupext.py
- src/_macosx.m
This updates the objective C macosx backend to use automatic reference counting instead of relying on manual tracking and releasing of the memory. It seems like this is recommended now, but I am definitely not an expert in this.
- [N/A] Documentation is sphinx and numpydoc …
> MNT: Change objective C code to Automatic Reference Counting (ARC)

- doc/users/next_whats_new/width_height_ratios.rst
- lib/matplotlib/figure.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_subplots.py
- tutorials/provisional/mosaic.py
I'm guessing 99.9% of the use of gridspec_kws is to set the height or width ratios of axes.  And it is pretty esoteric to ask people to know about gridspecs in order to access this.  Here we add `width_ratios` and `height_ratios` to the subplots and subplot_mosaic calls.  
Previously we would do 
```python
fig, axs = plt.subplots(1, 2, gridspec_kw={'width_ratios': [1, 2]})
```
This PR allows
```python
fig, axs = plt.subplots(1, 2, width_ratios=[1, 2])
```
> ENH: add width_ratios and height_ratios to subplots

- doc/api/next_api_changes/behavior/23299-TAC.rst
- lib/matplotlib/__init__.py
- lib/matplotlib/tests/test_rcparams.py
The motivating issue is that if the backend was the auto backend sentinel and
the backend was first fully resolved in an `rc_context` block, then we would
reset back to the sentinel an exit which would lead to strange behavior with
figures being erroneously closed.
~Adding a general purpose exclusion list seems like a better option than special
casing either the backend key or the backend value.~
Special case `'backend'` key to not be reset.
Closes #23298
~If people like this idea I will write the tests and docs. ~
> FIX/API: do not reset backend key in rc_context

- examples/user_interfaces/embedding_in_tk_sgskip.py
Use root.destroy to close Tk window instead of root.quit 
Refer to https://github.com/matplotlib/matplotlib/issues/23334#issuecomment-1167837601
- [ N/A ] Has pytest style unit tests (and `pytest` passes).
- [ N/A ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ N/A ] New features are documented, with examples if plot related.
- [ N/A ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ N/A ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ N/A ] Documentation is sphinx and numpydoc compliant (the docs should …
> embedding_in_tk_sgskip.py: use root.destroy

- .github/workflows/nightlies.yml
Resolves the space problem in https://github.com/matplotlib/matplotlib/issues/22757#issuecomment-1142381595
Remove all but the last `"${N_LATEST_UPLOADS}"` package version uploads to the matplotlib scipy-wheels-nightly index to ensure space. To do this, rely on the output form of `anaconda show` to be able to filter on the item delimiter character sequence for each version currently uploaded.
As an explicit example (from today 2022-06-26):
```console
$ anaconda show scipy-wheels-nightly/matplotlib
Using Anaconda API: https://api.anaconda.org
Name:    matplotlib
Summary:
Access:  public
Package Types:  pypi
Versions:
+ 3.6.0.dev2553+g3245d395d9
+ 3.6.0.dev2569+g3522217386
+ 3.6.0.dev2573+g3eadeacc06
To install this package with pypi run:
pip install -i …
```
> CI: Remove old scipy-wheels-nightly uploads to ensure space

- .circleci/config.yml
The circle config I had before wasn't working because I didn't specify the step.  However, just as easy to put in the install reps rather than add another step
> MNT: use devel version of theme

- src/_backend_agg_wrapper.cpp
- src/_macosx.m
- src/ft2font_wrapper.cpp
- src/mplutils.h
- src/tri/_tri_wrapper.cpp
Moving the PyModule_AddObject call out of init_type makes it clearer
which types are added to the module globals are which ones are not.
Static variables are always zero-inited (this is part of the C++
standard), therefore various memset zeroing calls can be removed.
> Shorten/clarify definition of extension types.

- lib/matplotlib/tests/test_texmanager.py
- lib/matplotlib/texmanager.py
Closes #23019
Thanks @anntzer for the rapid fix.
> Fix issue with tex-encoding on non-Unicode platforms

- doc/api/next_api_changes/behavior/23371-AL.rst
- lib/matplotlib/mpl-data/matplotlibrc
On the simple_anim.py example, adding e.g.
```python
plt.rcParams["animation.writer"] = "imagemagick"
plt.rcParams["animation.convert_args"] = []
ani.save("old.gif")
plt.rcParams["animation.convert_args"] = ["-layers", "OptimizePlus"]
ani.save("new.gif")
```
shows that OptimizePlus yields a >2.5x decrease in gif size.  (Admittedly I haven't tried more examples.)
Goes on top of #23370.  Supersedes #15784.  Thanks to @erelson for suggesting to use `-layers`.
> Default animation.convert_args to ["-layers", "OptimizePlus"].

- tutorials/text/mathtext.py
- tutorials/text/pgf.py
- tutorials/text/usetex.py
- Fix typos/mismatched parentheses/markup in mathtext.py.
- Make the title of pgf.py consistent with the title of usetex.py.
- Prefer "modern" approach for setting fonts in usetex.py, but keep the
old approach around (as the new API is only on Matplotlib 3.5).
- Clarify non-standard tex settings.
> Tweak mathtext/tex docs.

- examples/color/custom_cmap.py
Switch `-- text --` into real headers, use code style on variable names, and clean up the dictionary style.
Also, add a second example that actually shows the discontinuous setup.
> Clean up formatting of custom cmap example

- CODE_OF_CONDUCT.md
This is the last place we had `matplotlib@numfocus.org` in the docs. 
We hand funding from CZI EOSS4 for CoC training and I intend to stand up a proper CoC sub-committee, however for now the streering-council is a reasonable standin.
> GOV: point CoC reports at CoC steering council subcomittee mailing list

- .github/workflows/cibuildwheel.yml
The cibuildwheel Action is not passed an argument specifying an output directory (as was done when installing manually), so it defaults to `wheelhouse`, not `dist`.
This broke in #23146, but I only noticed because nightly uploads failed to find anything just now. Apparently not having any artifacts to upload is not fatal by default, so I've set that to error as well.
- [n/a] Documentation is sphinx and numpydoc …
> Upload wheel artifacts from the correct directory

- lib/matplotlib/tests/test_axes.py
Not sure why this didn't fail in CI, but it fails with pytest 6.2.5.
> TST: Add missing warning type to pytest.warns

- examples/statistics/multiple_histograms_side_by_side.py
As noted in https://discourse.matplotlib.org/t/tiny-error-in-matplotlib-gallery/22978
> DOC: Fix calculation of bin centers in multi-histogram

- doc/api/next_api_changes/removals/23291-AL.rst
- lib/matplotlib/backends/backend_template.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_backend_template.py
The customization point is not really needed (it can go into the canvas
constructor or manager.show or a few other places), but removing support
for it would be a bit tricky if not coupled with the introduction of a
new API (manager_class).  This way, we can simply say "if you want to
use the new API, then you cannot customize draw_if_interactive".
backend_template gets updated without deprecation as the point of that
backend is really to be documentation for what a backend module is;
moreover, putting a deprecation on new_figure_manager (for example)
would actually be counter-productive as pyplot would still try to call
that function (and thus emit a warning, even though the backend itself
is not deprecated).
Closes #23105.  See that PR for a more detailed discussion.
Once merged, the …
> In the new/simplified backend API, don't customize draw_if_interactive.

- lib/matplotlib/lines.py
- lib/matplotlib/tests/test_pickle.py
Make the class picklable, by making `canvas` a property and using a
picklable callback connect.  Also some docstring fixes.
> Small cleanup to VertexSelector.

- examples/units/units_sample.py
- Use tight layout so axis labels aren't hidden
- Set the x-limits to values that show the actual plot (before this it was just a little bit of the plot in the top left corner of the axes)
> Minor improvements to units_sample example

- lib/matplotlib/tests/test_agg.py
Follow up to #23413.
- Add a note why test_chunksize_fails() covers multiple test scenarios
- Don't use path.Path if we have Path already imported
- Reorder commands to make the function more understandable.
> Clean up test_chunksize_fails()

- doc/api/animation_api.rst
Found this doc typo thanks to this Stackoverflow question:
https://stackoverflow.com/questions/73002265/wrong-axes-limits/73002556
One of the example was mixing the pyplot interface with the object oriented
approach. This led to wrong axis limits.
Fixed the typo to use the object oriented approach.
> Fixed typo in docs animation api

- lib/matplotlib/backends/backend_pgf.py
- lib/matplotlib/tests/test_backend_pgf.py
- We don't need to escape underscores manually, but can rely on the
underscore package like we already do for usetex.
- We don't actually escape dollars (we parse them as math delimiters
first).
- Slightly tweak error message generation.
- Move escaping tests before the big `create_figure` definition, which
is used for further tests below.
(Moves towards https://github.com/matplotlib/matplotlib/pull/23381#issuecomment-1183758517, where I suggest to try to do away with pgf escapes entirely.)
> Tweak pgf escapes.

- lib/mpl_toolkits/mplot3d/proj3d.py
- lib/mpl_toolkits/tests/test_mplot3d.py
PR https://github.com/matplotlib/matplotlib/issues/22624/ didn't fix the runtime error popping up when the two points have the same X and Y but differing Z coordinates. This fixes that.
```
File "/mnt/c/Users/Scott/Documents/Documents/Coding/matplotlib/lib/mpl_toolkits/mplot3d/proj3d.py", line 30, in _line2d_seg_dist
u = (x01*x21 + y01*y21) / (x21**2 + y21**2)
FloatingPointError: invalid value encountered in double_scalars
```
- [N/A] …
> Fix divide by 0 runtime warning

- lib/matplotlib/dates.py
> DOC: numpydoc-ify date Locator classes

- doc/users/next_whats_new/strnorm.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/cm.py
- lib/matplotlib/collections.py
- lib/matplotlib/colors.py
- lib/matplotlib/contour.py
- lib/matplotlib/figure.py
- lib/matplotlib/image.py
- lib/matplotlib/streamplot.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_image.py
- lib/matplotlib/tri/tricontour.py
Implements #20746.
~Proof of concept implementation for #20746.~
~Still needs a lot of docs, but otherwise mostly works.~
~Remaining issues:~
- ~autoscale() will run into issues for scales with limited domains, e.g. we should/need to be able to auto-infer that LogNorm only normalizes based on the positive values (cf. overrides of `autoscale()` in LogNorm).  Closed by #21989.~
- ~The autogenerated norm classes are not picklable, which can be considered a slightly obscure limitation, but can be solved using semi-standard boilerplate as in #19033.  This is tracked by #20755.~
> Set norms using scale names.

- lib/matplotlib/pyplot.py
See https://github.com/matplotlib/matplotlib/issues/23419#issuecomment-1186595755.  Regardless of how that entire issue gets resolved, the check here just seems better?
> Compare thread native ids when checking whether running on main thread.

- lib/matplotlib/axes/_base.py
- lib/matplotlib/tests/test_axes.py
- lib/mpl_toolkits/tests/test_mplot3d.py
Axes3D did not have the zlabel included in its repr, this adds that. We could cut down on code duplication by modifying the base axes string, but that seems a little sketchy.
> Generalize Axes __repr__ to 3D

- doc/api/next_api_changes/behavior/23233-TH.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
<s>This builds on top of #23232.</s>
If stem markerfmt does not contain a color, use the color from linefmt
instead of the hard-coded 'C0'. While this is technically a breaking
API change, it is unlikely that somebody wants to color their lines,
but intentionally leaves their marker color as default 'C0'. I think
there is no simple mechanism that'd allow a deprecation. All I can
think of would require user actions at the beginning and at the end
of the deprecation period. Given that this should only affect very
few users and there is a simple workaround (state both format explitly).
> Default stem marker color follows the linecolor

- doc/api/next_api_changes/deprecations/23448-AL.rst
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/backend_gtk4.py
- lib/matplotlib/figure.py
Currently, pick events are generated by button_press and scroll events,
which call canvas.pick, which itself checks the widgetlock and then
calls Figure.pick, which is actually Artist.pick; Artist.pick checks
whether to emit a PickEvent for the current artist, then calls itself
recursively on children artists.
This PR gets rid of the intermediate canvas.pick layer, moving the
widgetlock check to Figure.pick (Figure.pick still calls the super()
pick, i.e. Artist.pick, after the check).  The advantages are that 1)
this avoids colliding with pick methods that may be present in the
native GUI classes (this is not a theoretical case: see the changes in
the GTK4 case) and 2) this makes it easier to fix button_pick_id and
scroll_pick_id to use picklable connections (which they should do).  In …
> Tweak callbacks to generate pick events.

- doc/api/next_api_changes/deprecations/23455-OG.rst
- lib/mpl_toolkits/mplot3d/axes3d.py
Originally deprecated in #11387.
> Deprecate properties w_xaxis, w_yaxis, and w_zaxis

- doc/api/next_api_changes/deprecations/23463-OG.rst
- lib/matplotlib/axis.py
> Deprecate Tick.label

- doc/api/next_api_changes/deprecations/23464-AL.rst
- lib/matplotlib/backends/backend_macosx.py
- src/_macosx.m
This is similar to the `_widgetclosed` handler in qt and the `_on_close`
handler in wx.
> Deprecate macos close handler.

- lib/matplotlib/backend_bases.py
- lib/matplotlib/tests/test_backend_bases.py
Closes #23324 
To fix the crash, when toggling zoom or pan tools, first check if widgetlock is available to proceed.
Btw, I only could test it with MACOSX backend and it was ok.
> Fix pan/zoom crashing when widget lock is unavailable

- doc/api/next_api_changes/behavior/23443-AL.rst
- lib/matplotlib/backends/backend_pgf.py
Apparently the minimal class is problematic from some use cases, and its
used discouraged (https://tex.stackexchange.com/questions/42114).
This does require loading hyperref using a standard usepackage, though.
While we're at it, remove the early font loading, which seems
unnecessary too.  (Or we should add a test or a comment that shows a
case where it's needed.)
Closes #18271.  Admittedly I don't *know* for sure that this won't break any use cases, but I don't see how to find that out without trying...
> Try running the pgf backend off the article class.

- lib/mpl_toolkits/axisartist/floating_axes.py
- lib/mpl_toolkits/axisartist/grid_finder.py
- lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
factor=None (meaning =1) was deprecated in e900be3 (3.2) and support for
factor=None was removed everywhere else in 3.4; the changes here had
just been missed.
Also normalize lon_levs, lat_levs to arrays early, rather than having to
do this multiple times.
> Remove old handling for factor=None in axisartist.

- doc/api/next_api_changes/deprecations/16931-AL.rst
- lib/matplotlib/artist.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/_backend_tk.py
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_gtk4.py
- lib/matplotlib/backends/backend_macosx.py
- lib/matplotlib/backends/backend_qt.py
- lib/matplotlib/backends/backend_webagg_core.py
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_backends_interactive.py
- lib/matplotlib/tests/test_offsetbox.py
- lib/matplotlib/tests/test_widgets.py
- src/_macosx.m
Currently, UI events (MouseEvent, KeyEvent, etc.) are generated by
letting the GUI-specific backends massage the native event objects into
a list of args/kwargs and then call
`FigureCanvasBase.motion_notify_event`/`.key_press_event`/etc.  This
makes it a bit tricky to improve the metadata on the events, because one
needs to change the signature on both the `FigureCanvasBase` method and
the event class.  Moreover, the `motion_notify_event`/etc. methods are
directly bound as event handlers in the gtk3 and tk backends, and thus
have incompatible signatures there.
Instead, the native GUI handlers can directly construct the relevant
event objects and trigger the events themselves; a new `Event.process`
helper method makes this even shorter (and allows to keep factoring some
common …
> Make it easier to improve UI event metadata.

- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_figure.py
There is a bit of extra caution in extracting the original DPI
just in case there is a canvas class that does something very funny
and the `_orignial_dpi` attribute does not get set (it is set to the `Figure`
instance in the `CanvasBase` init, not in the `Figure` init).
closes #23471
> FIX: reset to original DPI in getstate

- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_figure.py
Merge pull request #23476 from tacaswell/fix/unpickle_dpi
FIX: reset to original DPI in getstate
(cherry picked from commit 330124862b46dc003ff3e38427efcc9000b9d7ab)
> Backport PR #23476: FIX: reset to original DPI in getstate

- lib/matplotlib/_mathtext.py
Fixes https://github.com/matplotlib/matplotlib/issues/23474.
The width of the space inserted by, for instance, `\,` and `\mathrm{\,}`, is now the same.
> Mathtext spaces must be independent of font style.

- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_pickle.py
When saving a figure with the `pickle` module in one `python` process and then loading it in a different process a following error appears:
```
/figure.py", line 2911, in __setstate__
mgr = plt._backend_mod.new_figure_manager_given_figure(num, self)
AttributeError: 'NoneType' object has no attribute 'new_figure_manager_given_figure'
```
This PR replaces the `plt._backend_mod` with the call to `plt._get_backend_mod()` in the `Figure.__setstate__` method. This change ensures that the `_backend_mod` is not `None` during `pickle` load.
A reproducible example is provided in the comments
> Fix AttributeError for pickle load of Figure class

- lib/matplotlib/backends/backend_webagg_core.py
manager_class and _toolbar2_class were correctly set for the webagg and
nbagg subclasses, but the embedding_webagg_sgskip example directly
instantiates a webagg_core manager, so it needs these attributes too.
Fixes the problem noted at https://github.com/matplotlib/matplotlib/pull/23495#issue-1320551840.
> Fix direct instantiation of webagg_core managers.

- lib/matplotlib/tests/test_backends_interactive.py
The comment should have been updated together with the event processing
refactor.
> Fix outdated comment re: event handlers in test_backends_interactive.

- lib/matplotlib/pyplot.py
I tried to plot a couple of figures in a quick succession in a for loop and I got the warning
```
RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
fig, axes = plt.subplots(rows, cols, figsize=(fig_width, fig_height))
```
I do not use matplotlib often, so I naturally started googling as I did not know how to solve this situation efficiently and I came across this [stack overflow](https://stackoverflow.com/questions/24500065/closing-matplotlib-figures) question with a great answer.
I thought we could save users a bit of hassle by providing a better error message with a hint. …
> Add hint when More than {max_open_warning} figures have been opened

- setupext.py
This is to make it support IBM i OS.
- [Y] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
> supporting IBM i OS

- doc/conf.py
Replaces #23508
The problem is a combination of:
- the unit registry is managed by a dictionary at the module level of `mpl.units`
- in sg 0.11 the default matplotlib reset reloads that module which (resets the registry).  The motivation for this on their side was to make sure that the date formatter config did not leak between examples.
- we have a local module (`basic_units`) that lives in the examples directory that we use for the unit examples
- the first time it is imported the example units get registered
- on the second import call Python grabs the module from `sys.modules` (so we do not get to run any code) but `mpl.units` has been reloaded so our example units are no longer registered
This PR fixes the issue by telling sg to also remove `'basic_units'` from `sys.modules` so that …
> Fix doc build

- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_pickle.py
There were a number of complications with the backport:
- the new test generalized an existing test that had picked up
additional changes on the main branch
- the signature of the subproccess helper has changed on the main branch
> Backport PR #23462: Fix AttributeError for pickle load of Figure class

- doc/api/index_backend_api.rst
- doc/api/matplotlib_configuration_api.rst
- lib/matplotlib/__init__.py
Since we already have an explicit listing of module members, that needs to be turned off here. Also, don't add it to the index as we already have `matplotlib` pointing to the top level page (though maybe that should change?)
Fixes #17973
> Restore matplotlib.__doc__ in Sphinx docs

- examples/misc/image_thumbnail_sgskip.py
- examples/user_interfaces/embedding_in_gtk3_panzoom_sgskip.py
- examples/user_interfaces/embedding_in_gtk4_panzoom_sgskip.py
- examples/user_interfaces/embedding_in_wx5_sgskip.py
- examples/user_interfaces/fourier_demo_wx_sgskip.py
- examples/user_interfaces/mathtext_wx_sgskip.py
Some do not run, and some have minor breakage.
`examples/user_interfaces/embedding_webagg_sgskip.py` is also broken due to some manager/canvas API change, but I'm not sure how to fix; cc @anntzer.
> Fix sgskip'd examples

- lib/matplotlib/tests/test_image.py
1. The class should `return NotImplemented` rather than `raise NotImplementedError`: https://numpy.org/devdocs/user/basics.subclassing.html#array-ufunc-for-ufuncs
2. Allow unitless comparison operators to pass-through
Closes #23382
> TST: Update Quantity test class

- lib/matplotlib/tests/test_triangulation.py
This was caught by new version of linter.
Either flake8 4.0.1 -> 5.0.0 or pycodestyle 2.8.0 -> 2.9.0
> STY: fix whitespace on an assert

- doc/api/next_api_changes/behavior/23475-WLQ.rst
- lib/matplotlib/axes/_axes.py
Add `markerfacealt` as a line kwarg that should be passed through when making error bars. See issue #23375 
- [✔️] Has pytest style unit tests (and `pytest` passes).
- [✔️] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [✔️] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [✔️] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
> Add markerfacealt to pass-through arguments for error bar lines

- doc/api/next_api_changes/deprecations/23469-AL.rst
- lib/mpl_toolkits/axes_grid1/mpl_axes.py
- lib/mpl_toolkits/axisartist/axislines.py
clear() is the only caller of these inhernal axisartist helpers, so just
inline them there.  Note that these helpers are tightly coupled to
clear() anyways (see the note about setting gridlines clip_path).  Also,
this makes it clearer that _init_axis_artist is never called with
`axes != self` and that _init_gridlines is never called with
`grid_helper != self.get_grid_helper()`.
Also get rid of the `new_gridlines` helpers, which likewise become
inlined.
> Inline _init_axis_artists & _init_gridlines into clear.

- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
- lib/mpl_toolkits/mplot3d/axes3d.py
... so that the implementation also works for 3D.  This means also
adding a sharez() method, which is copy-pasted from sharex()/sharey()
(note that it is resolves a slight inconsistency in the old
Axes3D.clear, which would previously not copy the z-autoscaleness status
of a z-shared axes).
Using Axis._set_lim in the loop also means that we need to pass auto
explicitly to it anyways (it is a required parameter), so we can get rid
of the set_autoscalex/y/z calls.
Also, note that Axis.clear() explicitly resets the scale to "linear", so
the extra `_set_scale("linear")` calls are unneeded.
Finally, remove the silencing of TypeErrors when setting limits in
clear(), which was added in 917de33 to handle initialization order
problems in Axes3D but which seem not needed anymore (and are rather …
> Let Axes.clear iterate over Axises.

- doc/users/next_whats_new/legend_align.rst
- lib/matplotlib/legend.py
- lib/matplotlib/tests/test_legend.py
Attempt to solve issue #12388
Closes #12388 (just so that it is automatically closed when merged).
Changes:
> [Features] Allow setting legend title alignment

- lib/matplotlib/font_manager.py
Address part of  #23492
- [N/A]] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A]] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
> DOC: make "family" less ambiguous in FontProperties docs

- examples/user_interfaces/embedding_webagg_sgskip.py
Allow specifying a port, and gracefully handle Ctrl+C.
> Small improvements to WebAgg example

- .github/workflows/tests.yml
- doc/devel/testing.rst
Add run workflow trigger to test github workflow to allow running the test suite in fork repository.
> Add workflow dispatch GitHub CI

- lib/matplotlib/axes/_base.py
- lib/matplotlib/tests/test_axes.py
- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/tests/test_mplot3d.py
Built on top of #23453 so better merge that first.
The documentation says:
```
Passing both positional and keyword
arguments is invalid and will raise a TypeError.
```
But it is currently possible to pass e.g. `margins(0.2, x=0)` which will set both margins to 0.2.
As this corrects the stated behaviour of the doc-string I assume that no change note is required? …
> Make margins error as claimed in doc-string

- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
- lib/mpl_toolkits/mplot3d/axes3d.py
... together with an _axis_method_wrapper.
It may be worth trying to figure out later whether Axis._set_scale and
Axis._set_axes_scale need to have subtly different behaviors...
> Move the common implementation of Axes.set_x/y/zscale to Axis.

- doc/api/next_api_changes/deprecations/23444-AL.rst
- lib/matplotlib/backends/backend_pgf.py
> Deduplicate common parts in LatexManager.{__init__,_setup_latex_process}

- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/tests/test_backend_bases.py
> Remove transform arguments from _iter_collection

- doc/users/next_whats_new/figure_label_rcparams.rst
- lib/matplotlib/figure.py
- lib/matplotlib/mpl-data/matplotlibrc
- lib/matplotlib/mpl-data/stylelib/classic.mplstyle
- lib/matplotlib/rcsetup.py
- lib/matplotlib/tests/test_figure.py
Closes  #22564
Add `figure.labelsize` and `figure.labelweight` rcParams to set figure label size and weight different from title.
Test added also for titlesize/-weight rcParams as I didn't find any.
> Add rcparam for figure label size and weight

- .circleci/config.yml
- doc/api/ft2font.rst
- doc/api/index.rst
- doc/users/next_whats_new/font_fallback.rst
- lib/matplotlib/backends/backend_agg.py
- lib/matplotlib/font_manager.py
- lib/matplotlib/tests/test_ft2font.py
- src/ft2font.cpp
- src/ft2font.h
- src/ft2font_wrapper.cpp
This PR modifies the internal structure of `FT2Font` (the interface between fonts and Matplotlib) in favor of implementing [Font Fallback](https://www.w3schools.com/css/css_font_fallbacks.asp) for Matplotlib, and allow Agg backend to use the new codepath.
It builds on the previous PR: https://github.com/matplotlib/matplotlib/pull/20549, which was the 'first-step', i.e., "parsing multiple families".. this PR implements _using_ those families for font fallback.
This would help us in multi-language support, for example (Previous / After):
<p float="left" align="middle">
</p>
^the fonts are chosen such that the difference is visually noticeable.
A flowchart explaining the text rendering algorithm with font fallback:
Here's the script:
```python …
```
> Implement Font-Fallback in Matplotlib

- doc/api/axis_api.rst
- lib/matplotlib/axis.py
- lib/matplotlib/collections.py
- lib/matplotlib/lines.py
Always store in `self._pickradius`. Added property where needed. Added check for positive number (not for Collection since a negative number can be used according to docs).
Not sure if the `rename_parameter` is really needed since these are typically not called using kwargs, but better safe than sorry.
> Unify set_pickradius argument

- doc/api/next_api_changes/behavior/23550-OG.rst
- lib/mpl_toolkits/axes_grid1/axes_divider.py
- lib/mpl_toolkits/axes_grid1/axes_grid.py
- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/tests/test_axes_grid1.py
Raise a more exact type.
Better argument checking.
Minor cleanups.
> Change exception types, improve argument checking, and cleanups in mpl_toolkits

- src/_macosx.m
Python 3 always passes UTF8 encoded strings, so just use that directly
instead of specifying the encoding later.
replaces #21756 because the autorelease semantics was already changed in another PR.
> MNT: Use UTF-8 string in macosx backend

- doc/users/next_whats_new/fix_dash_offset_Patch.rst
- lib/matplotlib/patches.py
- lib/matplotlib/tests/test_patches.py
Pass the given offest in the draw method of the Patch class. In this way, the Patch class no longer ignores the dash offset. (closes #22977 )  
> Fix dash offset bug in Patch

- lib/matplotlib/patches.py
> Remove noop setattr_cm.

- doc/api/next_api_changes/behavior/23516-MS.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_colorbar.py
first pr, happy to add/make any necessary changes
closes #23487
The changed test in `test_colorbar.py` was related removing a colorbar from a scatter plot. I don't think the `cmap` there was necessary to test this. And running the tests on my own revealed the `cmap` wasn't changing the color of the scatter plot anyways
> warning when scatter plot color settings discarded

- lib/matplotlib/figure.py
- lib/matplotlib/layout_engine.py
- lib/matplotlib/tests/test_figure.py
This may be too simplistic as it just sets it to None which gives you ability
to "go through zero" and change to an incompatible layout engine.
> ENH: add ability to remove layout engine

- .circleci/config.yml
We are supposedly on medium Docker VMs, which offer 2 vCPUs, so we should try to build in parallel.
> Circle: Build docs in parallel.

- lib/matplotlib/tests/test_figure.py
This only occurs on `v3.5.x` because the test has been rewritten on `main`.
> STY: Fix whitespace error from new flake8

- lib/matplotlib/colorbar.py
- lib/matplotlib/figure.py
It seems clearer to just put in the docstring "as is" at the (only)
expected place rather than define it in another module and move it
around.
Also group all "other parameters" together into a standard numpydoc
section, which avoids having to fiddle with indents.
> Move colorbar() doc to method itself.

- doc/api/next_api_changes/removals/23594-OG.rst
- src/ft2font_wrapper.cpp
There was actually one more deprecation to expire. (I thought all was done.)
> Expire deprecation on passing bytes to FT2Font.set_text

- lib/mpl_toolkits/axes_grid1/axes_grid.py
- lib/mpl_toolkits/axes_grid1/mpl_axes.py
While looking into #23595 (to no avail), I found some minor things to sort out.
> Minor cleanup of axes_grid1

- .github/workflows/cibuildwheel.yml
We need newer versions of c++ for the font fallback.
A compatible version of pip is in the CPython source for
manylinux2010 : py 3.8.0+
manylinux2014 : py 3.9.0+
https://github.com/pypa/manylinux#manylinux
> BLD: update the manylinux versions used

- .github/workflows/cibuildwheel.yml
The macos-10.15 runner is deprecated:
https://github.com/actions/virtual-environments/issues/5583
> Migrate cibuildwheel workflow to macos-11

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/dates.py
- lib/matplotlib/tests/test_cbook.py
- lib/matplotlib/units.py
#23580 
- cbook/__init__.py
- modified safe_first_element() to obtain the first non-None element
- test_cbook.py
- added a test for safe_first_element()
- [ N/A] New features are documented, with examples if plot related.
- [ N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
> BUG:datetime list starting with none

- lib/mpl_toolkits/mplot3d/axes3d.py
Adds documentation showing azimuth and elevation angles needed to look at the primary planes in 3d plots. Fulfills some of the needs of https://github.com/matplotlib/matplotlib/issues/23544, resulting views are in that issue
> DOC: view_init docstring for 3d axes primary view angles

- examples/images_contours_and_fields/plot_streamplot.py
- examples/lines_bars_and_markers/linestyles.py
- examples/lines_bars_and_markers/psd_demo.py
- examples/text_labels_and_annotations/demo_text_rotation_mode.py
By using `subfigures`, the new support for `height_ratios`/`width_ratios` directly in `subplots`, or just using `subplots`.
> Avoid gridspec in more examples 

- doc/api/next_api_changes/deprecations/23202-GL.rst
- lib/matplotlib/axes/_base.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/backend_cairo.py
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_backend_macosx.py
- lib/matplotlib/tests/test_image.py
- lib/mpl_toolkits/tests/test_axes_grid1.py
Let the canvas decide whether to cache the renderer or not and let the figure request the renderer from the canvas. The canvas can either return a cached version or a new one.
This is a proof-of-concept after the discussion on the dev call last week to see if we can move the cache from the figure-level to the canvas-level.
> MNT: Remove cached renderer from figure

- doc/conf.py
Added a statement printing the version of docs being built. This is cause installing the dependencies for doc builds installs a released version of Matplotlib and at least I keep forgetting to reinstall afterwards. This seemed like a really easy way to raise a flag about which version is installed. 
attn: @QuLogic 'cause I think this was your suggestion
> print version number when building docs

- lib/matplotlib/tests/test_ft2font.py
Following up on #23559 to relax the tests on discovering that Noto Sans is installed.
> TST: be more forgiving about IDing Noto

- lib/matplotlib/tests/test_backend_tk.py
- lib/matplotlib/tests/test_backends_interactive.py
The [upstream issue](https://github.com/actions/setup-python/issues/402) has been closed, so let's see if it will work again.
Reverts matplotlib/matplotlib#23095
> Revert "Try to unbreak CI by xfailing OSX Tk tests"

- .git_archival.txt
- .github/workflows/cibuildsdist.yml
- ci/check_version_number.py
- setup.py
Closes #23325
Closes #23386
Removes setuptools_scm_git_archive as dependency, but increases the setuptools_scm version requirement from 4 to 7. …
> Remove setuptools_scm_git_archive dependency and add sdist test

- doc/api/next_api_changes/behavior/23206-OG.rst
- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/tests/test_backend_svg.py
Better checking of metadata with better error messages. Tests for all metadata errors (changed ValueError to TypeError as should be more appropriate, release note required?). 
Test for `_escape_attrib`.
> Change exception type for incorrect SVG date metadata

- doc/devel/dependencies.rst
This is an update to our documented dependencies to match what the code does:
- notes we now require c++11
- the versions of manylinux wheels we use for wheels + minimum pip dependency
- notes we now require the underscore LaTeX package
- adds all of the optional test dependencies (audited via ` ack importorskip --ignore-dir=build --python`)
- adjust the heading levels a bit + cosmetic changes to inline footnotes.
- moves inkscape and gs to be "optional" test dependencies (we do not install them on all of our CI jobs!)
> Doc update deps

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
- lib/matplotlib/colorbar.py
- lib/matplotlib/figure.py
The [*Discouraged*] prefix in the summary line is added in analogy to
the [*Deprecated*] prefix we add automatically. We do this so that
these "labels" are prominently visible also in summary overviews of
the functions in the docs.
Since we rarely discourage whole functions, for now I just do this
manually, and not yet add a policy.
> Add discouraged admonitions

- .github/workflows/cibuildwheel.yml
With [`cibuildwheel` `v2.9.0`](https://github.com/pypa/cibuildwheel/releases/tag/v2.9.0), CPython 3.11 wheels are now built (by default) and as NumPy now has CPython 3.11 wheels out as of NumPy v1.23.2, matplotlib can build CPython 3.11 wheels (though as of 2022-08-16 [`contourpy`](https://pypi.org/project/contourpy/) does not have 3.11 wheels yet).
- [N/A] API changes …
> BLD: Add Python 3.11 builds to CI

- plot_types/basic/bar.py
`bar` / `barh` was the only plot type mentioning two
functions, but the plot only showed the vertial one
anyway.
IHMO we can leave out `barh`. It's mentionend in the
"See also" section of `bar`. (But I'm open to leaving
a comment in the plot type description if desired -
I mainly want to remove it from the title, because it's
the only one spanning two lines:
)
> Leave out `barh` from the basic plot types.

- .github/workflows/tests.yml
Follow on to #23610 to try installing a different font via brew.
The thing to check is that the Noto tests in `test_ft2font` are not skipped.
> CI: try installing a different version of noto on OSX

- .github/workflows/cibuildwheel.yml
> Enable wheels for PyPy 3.8+

- doc/conf.py
- doc/devel/MEP/MEP14.rst
- doc/devel/MEP/MEP29.rst
- doc/devel/dependencies.rst
- doc/devel/style_guide.rst
- doc/devel/triage.rst
- doc/sphinxext/custom_roles.py
- doc/sphinxext/redirect_from.py
- doc/users/faq/troubleshooting_faq.rst
- doc/users/prev_whats_new/changelog.rst
- examples/images_contours_and_fields/shading_example.py
- examples/user_interfaces/web_application_server_sgskip.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/patheffects.py
- lib/matplotlib/tests/test_quiver.py
This fixes several dead links and HTML errors found after building docs for 3.5.3.
> Fix doc bugs found in 3.5.3

- doc/api/next_api_changes/deprecations/23647-OG.rst
- lib/mpl_toolkits/mplot3d/axis3d.py
There are three distinct commits in this PR:
1. Deprecate `set_pane_pos`: the set value is not used and overwritten at draw time, so should not be public.
2. Simplify the pane creation (removed properties overwritten anyway)
3. Allow any color to be used when setting pane color.
> Allow any color format to be used for axis3d.Axis.set_pane_color

- doc/devel/MEP/MEP14.rst
- doc/devel/MEP/MEP29.rst
- doc/devel/dependencies.rst
- doc/devel/style_guide.rst
- doc/devel/triage.rst
- doc/sphinxext/custom_roles.py
- doc/sphinxext/redirect_from.py
- doc/users/faq/troubleshooting_faq.rst
- doc/users/prev_whats_new/changelog.rst
- examples/images_contours_and_fields/shading_example.py
- examples/user_interfaces/web_application_server_sgskip.py
Note, this skips changes in `lib` because they are just comments, and changes in those files can't affect the doc builds anyway.
> Backport PR #23641 on branch v3.5.3-doc (Fix doc bugs found in 3.5.3)

- doc/devel/MEP/MEP14.rst
- doc/devel/MEP/MEP29.rst
- doc/devel/dependencies.rst
- doc/devel/style_guide.rst
- doc/devel/triage.rst
- doc/sphinxext/custom_roles.py
- doc/sphinxext/redirect_from.py
- doc/users/faq/troubleshooting_faq.rst
- doc/users/prev_whats_new/changelog.rst
- examples/images_contours_and_fields/shading_example.py
- examples/user_interfaces/web_application_server_sgskip.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/patheffects.py
- lib/matplotlib/tests/test_quiver.py
> Backport PR #23641 on branch v3.5.x (Fix doc bugs found in 3.5.3)

- tools/triage_tests.py
Otherwise it cannot find the expected result file for failing EPS tests.
> Add eps to extension list in image triager

- lib/matplotlib/tests/test_backend_pdf.py
- lib/matplotlib/tests/test_backend_ps.py
- lib/matplotlib/tests/test_backend_svg.py
Apparently Ubuntu 20.04 (our CI system) has Zen Hei 0.9.45, while Fedora has 0.9.46. These versions have slight differences in the glyphs. This tolerance should still be small enough to catch completely missing glyphs though.
> Increase tolerance on multi-font tests

- lib/matplotlib/_mathtext.py
> Remove unused fontsize argument from private mathtext _get_info.

- setupext.py
- src/_macosx.m
Reverting the ARC PR to avoid the segfault from the subplot_tool for now.
xref: #23653
Revert "MNT: Change objective C code to Automatic Reference Counting (ARC)"
This reverts commit b46ab89ec227e9f7d026a4f60db0ffc632791a03.
Revert "FIX: remove one more autorelease"
This reverts commit ec0a325ab08f3bffe2c60bde6cacc83c501e57ee.
> Reverts macosx change to ARC

- lib/matplotlib/tests/test_figure.py
Closes #23660
As seen there is a minor deviation in the anti-aliasing for this test. If someone has a better idea how to solve it than adding a minor tolerance, feel free to do so. But in the meanwhile...
> Add tolerance to test failing on ppc64le

- lib/matplotlib/font_manager.py
Mostly, we don't need to manage rcparams and call _findfont_cached; we
can directly rely on findfont which exactly handles that for us.  Also
some minor stylistic(ish) things.
> Small cleanups to _find_fonts_by_props.

- lib/matplotlib/testing/compare.py
- The previous `*255*10` factor was necessary when using the old _png
module to read images, which read them as 0-1 floats, the 255 factor
was needed prior to conversion to uint8.  Now we use pillow everywhere
in matplotlib.testing.compare and work with uint8 throughout, so the
extra 255 is incorrect (it basically caused any slight difference to
be fully saturated).
- We don't use _png to write the diffs anymore, and pillow handles RGB
just fine, so we don't need to add an alpha channel if it's not there.
> Simplify/fix save_diff_image.

- .flake8
- doc/api/tri_api.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/backends/backend_gtk3cairo.py
- lib/matplotlib/backends/backend_gtk4.py
- lib/matplotlib/backends/backend_gtk4cairo.py
- lib/matplotlib/backends/backend_pgf.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/backends/backend_qt.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/lines.py
- lib/matplotlib/style/__init__.py
- lib/matplotlib/tests/conftest.py
- lib/matplotlib/tests/test_backend_qt.py
- lib/matplotlib/text.py
- lib/matplotlib/tri/__init__.py
- lib/mpl_toolkits/axes_grid1/__init__.py
- lib/mpl_toolkits/axisartist/axes_divider.py
- lib/mpl_toolkits/axisartist/axes_rgb.py
- lib/mpl_toolkits/axisartist/axislines.py
- lib/mpl_toolkits/mplot3d/__init__.py
- lib/mpl_toolkits/tests/conftest.py
> MNT: Remove unused imports

- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_ps.py
> Fix flake8 errors introduced by crossed PRs

- doc/users/next_whats_new/bar_plot_labels
- doc/users/next_whats_new/bar_plot_labels.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Currently, if you need to label each bar in a plot say for an animation, you have to loop over the bars in the bar container that `Axes.bar()` returns and call `set_label()` on each bar. I have an example [here](https://stefmolin.github.io/python-data-viz-workshop/slides/html/workshop.slides.html#/26/7) in a workshop I deliver. When compared with `stackplot()` (which has a `labels` argument for this) this can be a gotcha for newcomers. There is a `label` key shown in the docs as available on the `Rectangle`, but it doesn't have the expected effect of labeling the bars, rather it labels the `BarContainer`:
```python
>>> import matplotlib.pyplot as plt
>>> x = ["a", "b", "c"]
>>> y = [10, 20, 15]
>>> fig, ax = plt.subplots()
>>> bar_container = ax.barh(x, y, label=x)
>>> …
```
> Add functionality to label individual bars with Axes.bar()

- doc/api/next_api_changes/deprecations/23572-AL.rst
- lib/matplotlib/gridspec.py
The API was added in f8dfea7 (@jklymak) but never actually used anywhere.
> Deprecate `get_grid_positions(..., raw=True)`.

- doc/api/next_api_changes/deprecations/23665-GL.rst
- lib/matplotlib/backends/backend_macosx.py
It is unused now that there is a `configure_subplots()` method on the base toolbar.
> MNT: Deprecate macosx prepare subplots tool

- lib/mpl_toolkits/mplot3d/art3d.py
- lib/mpl_toolkits/tests/test_mplot3d.py
Closes #23459
The dimensions were different since `get_xdata` and `get_ydata` have processed the return values. So do a similar processing here.
> Fix issue with drawing 3D lines where points are from nparray

- lib/matplotlib/testing/__init__.py
This follows from #23443 where pgf started using `article` instead of `minimal`, but the testing check was not updated for it.
- [x/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
> TST: Use article class when checking for pgf

- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/mplot3d/axis3d.py
I seem to recall that one should use `mpl.rcParams` (and in any way not import it from `Axes`).
> MNT: Get rcParams from mpl

- doc/api/next_api_changes/deprecations/23675-OG.rst
- lib/mpl_toolkits/mplot3d/axis3d.py
The two functions are not in the public documentation and are helper functions which should be considered private.
> Deprecate helper functions in axis3d

- doc/devel/documenting_mpl.rst
- doc/make.bat
I have not actually tested this... cc @story645
`if defined` does require command extensions to be enabled, but a) they're enabled by default, and b) we need them for `%~dp0` above already.
Fixes #23622 
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should …
> make.bat: Don't override SPHINXOPTS/O from the environment

- lib/mpl_toolkits/mplot3d/art3d.py
- lib/mpl_toolkits/tests/test_mplot3d.py
Closes #4067 
I was about to extract the relevant parts of `do_3d_projection`, but it looked like about half of it was required anyway, so I went the simple path.
> Fix issue with get_edgecolor and get_facecolor in 3D plots

- doc/api/next_api_changes/deprecations/22506-AL.rst
- lib/matplotlib/_mathtext.py
- lib/matplotlib/mathtext.py
The MathtextBackend ("MB") mechanism was previously used to let actual
backends customize how they received mathtext results -- either as lists
of glyphs and rectangles (for vector backends: MathtextBackendPath),
or a bitmap (for raster backends: MathtextBackendAgg); in both cases,
metrics are also provided.  MBs also controlled font hinting.  Note that
the MB mechanism was not publically user-extendable (this would require
touching the private MathTextParser._backend_mapping dict), so third
parties could not meaningfully provide their own backends.
MBs were attached to _mathtext.Fonts objects, which were central to
the "shipping" stage of the parse (ship(), which converts the nested
parse tree created by pyparsing into flat calls to render_glyph and
render_rect_filled).  This led to a …
> Replace MathtextBackend mechanism.

- lib/matplotlib/axes/_axes.py
- tutorials/intermediate/legend_guide.py
Related to the recent discussion about duplicate labels #23664 and SO-questions like:
https://stackoverflow.com/questions/13588920/stop-matplotlib-repeating-labels-in-legend (63k views)
https://stackoverflow.com/questions/19385639/duplicate-items-in-legend-in-matplotlib (47k views)
and especially the comment:
```
As the [docs](http://matplotlib.org/users/legend_guide.html) say, although it's easy to miss:
If label attribute is empty string or starts with “_”, those artists will be ignored.
```
Maybe this PR won't make all questions go away, but can still be worth highlighting this.
- [N/A] New features have an entry in …
> DOC: Highlight information about avoiding labels in legend

- lib/matplotlib/patches.py
It doesn't actually need to be a context manager, but can be a plain
function, with an easier to explain behavior.
> Simplify _bind_draw_path_function.

- examples/text_labels_and_annotations/custom_legends.py
- lib/matplotlib/_layoutgrid.py
- lib/matplotlib/_tight_layout.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/colors.py
- lib/matplotlib/font_manager.py
- lib/matplotlib/gridspec.py
- lib/matplotlib/lines.py
- lib/matplotlib/markers.py
- lib/matplotlib/mathtext.py
- lib/matplotlib/offsetbox.py
- lib/matplotlib/projections/geo.py
- lib/matplotlib/projections/polar.py
- lib/matplotlib/spines.py
- lib/matplotlib/streamplot.py
- lib/matplotlib/tests/test_backends_interactive.py
- lib/matplotlib/tests/test_constrainedlayout.py
- lib/matplotlib/tests/test_figure.py
- lib/matplotlib/texmanager.py
- lib/mpl_toolkits/axisartist/axis_artist.py
- lib/mpl_toolkits/axisartist/axislines.py
Realized that this was quite inconsistent. It is still not really consistent, but I doubted half-ways that there is a preferred way...
Related to #23680 (almost closes it...)
So, is there are preferred way among
``` python 
...
mp.rcParams[...]
```
and
``` python
from matplotlib import rcParams
...
rcParams[...]
```
?
> Get rcParams from mpl

- src/_macosx.m
Rather than just bursting the runloop for a short amount of time, we can run it until all pending events have been processed. In this example on main, the buttons are all unable to be pushed and close/minimize are grayed out. The buttons should all work with this update.
```python
import matplotlib, random
matplotlib.use('macosx') #Works fine with tkagg
data = []
#Initial Draw
fig, axes = plt.subplots(1)
line, = axes.plot(data, label='Some data', color='#CC0000')
fig.canvas.draw_idle()
plt.show(block=False)
while True:
data += [random.randint(0,50) for i in range(20)]
tseries = range(0, len(data))
line.set_ydata(data)
line.set_xdata(tseries)
axes.relim()
axes.autoscale_view(tight=False)
if fig.stale: fig.canvas.draw()
fig.canvas.flush_events() #Listen for …
```
> FIX: macosx flush_events should process all events

- doc/users/next_whats_new/plt_xyticks_support_minor.rst
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_pyplot.py
Closes #21107
Will think about tests. Should there be a release note?
> Add `minor` keyword argument to `plt.x/yticks`

- doc/api/next_api_changes/deprecations/23668-TC.rst
- doc/api/pyplot_summary.rst
- doc/users/next_whats_new/resample_colormaps.rst
- examples/images_contours_and_fields/contour_image.py
- examples/images_contours_and_fields/image_annotated_heatmap.py
- examples/lines_bars_and_markers/multivariate_marker_plot.py
- lib/matplotlib/cm.py
- lib/matplotlib/colors.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/streamplot.py
- lib/matplotlib/tests/test_artist.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_collections.py
- lib/matplotlib/tests/test_colorbar.py
- lib/matplotlib/tests/test_colors.py
- lib/matplotlib/tests/test_image.py
- lib/matplotlib/tests/test_lines.py
- lib/matplotlib/tests/test_triangulation.py
- lib/mpl_toolkits/tests/test_mplot3d.py
- tutorials/colors/colormap-manipulation.py
- tutorials/colors/colormaps.py
This is my attempt to turn the crank on the depractions on the cm functions.
The changes were more extensive than I anticipated 
> Api deprecate cmap functions

- lib/matplotlib/axis.py
- lib/matplotlib/text.py
To solve [this issue](https://github.com/matplotlib/matplotlib/issues/21239),  not only content but its fontsize will be defaulted value in `clear` method.
> Fix: axis, ticks are set to defaults fontsize after ax.clear()

- doc/api/next_api_changes/behavior/23710-ES.rst
- lib/matplotlib/cm.py
- lib/matplotlib/tests/test_colors.py
Some names in the deprecation messages were incorrect, and the `get_cmap` copying did not have an API note.
> Fix cmap deprecations

- lib/matplotlib/__init__.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/testing/decorators.py
- lib/mpl_toolkits/mplot3d/axis3d.py
Formerly, the deprecation message would say "Use Vendor the code instead"; now they say "Use a vendored copy of the code instead", etc.
This weird grammar can cause some confusion, cf #23244
> Fix deprecation messages for vendoring unused things

- doc/api/matplotlib_configuration_api.rst
- doc/api/next_api_changes/deprecations/23720-RS.rst
- doc/api/next_api_changes/removals/22514-OG.rst
- doc/api/prev_api_changes/api_changes_3.5.0/behaviour.rst
- doc/devel/contributing.rst
- lib/matplotlib/cbook/__init__.py
> Restore deprecation class aliases in cbook

- lib/matplotlib/backends/backend_qt.py
As suggested in issue #22409, using sys._getframe can lead to a memory leak which then causes PyQt to send the wrong event type. This solves the issue by and using a cleaner solution which avoids sys._getframe for determining recursion.
> Use cleaner recursion check in PyQt FigureCanvas' resizeEvent.

- doc/devel/contributing.rst
This PR adds information about the new contributor meeting, and introduces some edits to the section in which it fits to set it up.
No conflict is expected from #23588 which introduces some changes to this page as well.
> Adding the new contributor meeting

- lib/matplotlib/_pylab_helpers.py
Matplotlib has a large number of circular references (between figure and
manager, between axes and figure, axes and artist, figure and canvas, and ...)
so when the user drops their last reference to a `Figure` (and clears it from
pyplot's state), the objects will not immediately deleted.
To account for this we have long (goes back to
e34a333d00814124d3e19d462b9d78ac35e7a49a the "reorganize code" commit in 2004
which is the end of history for much of the code) had a `gc.collect()` in the
close logic in order to promptly clean up after our selves.
However, unconditionally calling `gc.collect` and be a major performance
issue (see https://github.com/matplotlib/matplotlib/issues/3044 and
https://github.com/matplotlib/matplotlib/pull/3045) because if there are a
large number of long-lived user …
> FIX: do not try to help CPython with garbage collection

- doc/api/next_api_changes/removals/22081-AL.rst
- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_colorbar.py
> Clarify error for colorbar with unparented mappable

- doc/api/next_api_changes/deprecations/23735-ES.rst
- lib/matplotlib/axes/_base.py
- lib/matplotlib/tests/test_axes.py
In #22802, `Axes.clear` was made the primary interface over `Axes.cla`. However, while this can be enforced internally, that can't be said for third-party subclasses. I'm pretty sure we did not intend to remove or deprecate `Axes.cla` given its wide use, though I'm not sure if we wanted to discourage it (by undocumenting or just putting that in the docstring.)
This fixes, e.g., Cartopy, but probably most other third-party packages that will subclass `Axes`.
> Correctly handle Axes subclasses that override cla

- doc/sphinxext/custom_roles.py
- lib/matplotlib/mpl-data/matplotlibrc
The `rcParam` typo was accidentally introduced by me in #23641.
Fixes #23745
> Fix rcParams documentation

- examples/user_interfaces/embedding_webagg_sgskip.py
- lib/matplotlib/backends/backend_webagg_core.py
- lib/matplotlib/tests/test_backend_webagg.py
We must not try to make a toolbar for the classes in backend_webaggcore because
ipympl inherits from these classes and requires its own toolbar to be used.
This also fixes the webagg embedding example without breaking ipympl.
closes #23699
> FIX: unbreak ipympl

- lib/matplotlib/artist.py
- lib/matplotlib/axis.py
- lib/matplotlib/text.py
During import of matplotlib.pyplot the `ArtistInspector` performs actions for objects of type `Artist`. Several actions are performed twice and can be avoided by caching the result.
This PR improves the import time from by 1149 ms to 808 ms (the numbers are system dependent, quoted numbers are on Windows with python 3.10).
The PR consists of 3 elements:
* Adding a `lru_cache` to `ArtistInspector.is_alias`.
* Creating a cached method `ArtistInspector.number_of_parameters(` for `len(inspect.signature(func).parameters)`
* Creating a method `getdoc_pure` that is equal to `inspect.getdoc`, but without an expensive call to `inspect.cleandoc`.
Notes:
This part of the code was identified by using https://github.com/asottile/importtime-waterfall and https://jiffyclub.github.io/snakeviz/. Analysis …
> Improve matplotlib.pyplot importtime by caching ArtistInspector

- lib/matplotlib/legend.py
- lib/matplotlib/tests/test_legend.py
Closes https://github.com/matplotlib/matplotlib/issues/23761
The check is not supposed to warn if an artist has no label or a `'_no_legend_'` label.  However we actually add labels to lots of artists, and we don't deal with labels with leading underscores anyway, so just skip anything with a leading underscore.
> FIX: legend handler warning too liberal

- doc/users/next_whats_new/3d_plot_aspects.rst
- doc/users/next_whats_new/3d_plot_focal_length.rst
- doc/users/next_whats_new/3d_plot_roll_angle.rst
The previous plots were squished with overlapping titles, this cleans them up.
> 3d plots what's new cleanups

- lib/matplotlib/dates.py
It should be `autoformatter`, not `autoformat`.
> Correct rcParams-name in AutoDateFormatter doc-string

- examples/animation/animation_demo.py
- examples/event_handling/data_browser.py
Also, minor improvement to animation demo.
> Remove `Axes.cla` from examples

- .circleci/config.yml
We missed doing this when adding the Plot types section.
> ci: Add plot types to sphinx-gallery artifacts

- lib/matplotlib/dates.py
There is no addition of one anymore.
> DOC: Fix num2date docstring

- doc/conf.py
We have seen both in `/stable` and `/3.6.0` (e.g., #23760), some styling is broken because old CSS is cached. CSS might change from updating sphinx-gallery, mpl-sphinx-theme, pydata-sphinx-theme, etc. Adding a versioned query breaks the cache.
It's a bit over-eager to base it on Matplotlib version and not the file contents (since those dependencies may not have updated), but this should work well enough.
> DOC: Add cache busting to all static assets

- lib/matplotlib/cm.py
- lib/matplotlib/tests/test_colors.py
Previously this would raise a `ValueError`, the refactor caused it to raise
`KeyError`.   This inadvertently located a bad test in x-array, but restoring
the old behavior.
https://github.com/pydata/xarray/runs/8104117777?check_suite_focus=true#step:8:673
> FIX: ensure type stability for missing cmaps in `set_cmap`

- lib/matplotlib/tests/test_texmanager.py
- lib/matplotlib/texmanager.py
Because of the security implications of being able to read/write arbitrary files, even with user permissions, TeX's path resolution system [kpathsea restricts file access](https://www.tug.org/texinfohtml/kpathsea.html#Calling-sequence) by default. While most configs overwrite this with more permissive options, a secure setup (particularly in settings where TeX is being supplied from untrusted inputs) should have `openin_any = p` in the system's `texmf.cnf` or equivalent. This setting disallows, among other things, traversal to parent directories.
PR #21414 worked around a problem with paths that contain `~` by traversing through the parent: https://github.com/matplotlib/matplotlib/blob/25b39d41d3528329b3e5164bbf71feb0d556af80/lib/matplotlib/texmanager.py#L298
That code makes it impossible …
> Fix TexManager's support for `openin_any = p`

- doc/users/next_whats_new/bar_label_formatting.rst
- examples/lines_bars_and_markers/bar_label_demo.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_cbook.py
Addresses #23689
Enhancement to `Axes.bar_label()` to make it possible to format values with f-strings.
> Add new-style string formatting option and callable option to `fmt` in `Axes.bar_label()`.

- lib/matplotlib/tests/test_triangulation.py
- lib/matplotlib/tri/triplot.py
This is a fix for bug https://github.com/matplotlib/matplotlib/issues/22965. It pops `label` from `kw` to avoid duplicated labels on `triplot`.
> Triplot duplicated label

- doc/devel/development_setup.rst
- Write section headers as imperative steps; add a table of contents that thus reads like a recipe. - The TOC is redundant to the side bar, but I think there is value in listing it again at the top of the page as a summary recipe what needs to be done.
- Put description for dev environments in sphinx-design tabs
Tabs make it more clear that these are alternatives. Also,  they reduce the overall length of the page, making it appear less intimidating.
> [DOC] Improve dev setup description

- doc/conf.py
search is now accessible via a button in the nav bar, which opens an overlay search field.
> Remove search field from sidebar

- lib/matplotlib/axis.py
This reverts commit 2357c92d87d96d519c8470776e76180e71663d0b. (#22587)
Reversal due to a regression #23808.
Decision on the dev call: We revert this change so that the exact code from 3.5 is still used in 3.6.
We plan to have a full discussion on what `clear()` should do for 3.7.
> Revert "Refactor handling of tick and ticklabel visiblity in Axis.clear"

- doc/_static/switcher.json
The links listed in the version switcher `switcher.json` file are missing a trailing slash, creating broken links.
Closes #23794
> Fix version switcher links

- doc/devel/documenting_mpl.rst
is basically a typo type thing, removed a `using` that I think stuck around from an old construction.
> removed single word in documenting doc

- .github/workflows/tests.yml
- setup.py
> Start testing on Python 3.11

- setupext.py
Instead of passing `BUILD_GNU_TYPE` as the host, it should be `HOST_GNU_TYPE`. This fixes cross-compilation for osx_arm64 on conda-forge. See https://github.com/conda-forge/matplotlib-feedstock/pull/329.
I wasn't able to find any quick documentation for these keys, but [this discussion post](https://discuss.python.org/t/towards-standardizing-cross-compiling/10357) is what clued me in. @QuLogic did you have something else that led you to use `BUILD_GNU_TYPE` when you added it originally?
> Fix cross-compiling internal freetype

- tutorials/intermediate/autoscale.py
- tutorials/introductory/images.py
- ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
- Passing the rotation parameter of __init__() positionally is deprecated since Matplotlib 3.6; the parameter will become keyword-only two minor releases later.
> DOC: fix deprecation warnings

- .flake8
- .pre-commit-config.yaml
- requirements/testing/flake8.txt
Add plugin to fix flake8's behavior to run all checks even if there is a syntax
error.
Despite upstream's view that they "fixed" a bug, there was a regression in functionality in flake8 v4 that suppresses all other warnings if there is a syntax error.   https://github.com/kmaehashi/flake8-force is a flake8 plugin that lets you opt back into the previous behavior.
> DEV: add flake8-force plugin

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/baseline_images/test_axes/test_centered_bar_label_nonlinear.svg
- lib/matplotlib/tests/test_axes.py
Fixes #23688
Incorporated @anntzer's [solution](https://github.com/matplotlib/matplotlib/issues/23688#issuecomment-1221603145) from the issue into the `Axes.bar_label()` method.
---
Example using a log scale:
```python
bar_container = ax.barh(['c', 'b', 'a'], [1_000, 5_000, 7_000])
ax.set_xscale('log')
ax.set_xlim(1, None)
ax.bar_label(bar_container, label_type='center')
```
Current output:
Output with this change:
- …
> Fix bug in `Axes.bar_label(label_type='center')` for non-linear scales.

- examples/mplot3d/box3d.py
- examples/shapes_and_collections/artist_reference.py
- examples/shapes_and_collections/patch_collection.py
- examples/specialty_plots/leftventricle_bulleye.py
- examples/text_labels_and_annotations/figlegend_demo.py
- The dist attribute was deprecated in Matplotlib 3.6 and will be removed two minor releases later.
- Passing the loc parameter of __init__() positionally is deprecated since Matplotlib 3.6; the parameter will become keyword-only two minor releases later.
- Passing the radius parameter of __init__() positionally is deprecated since Matplotlib 3.6; the parameter will become keyword-only two minor releases later.
- Passing the closed parameter of __init__() positionally is deprecated since Matplotlib 3.6; the parameter will become keyword-only two minor releases later.
- Auto-removal of grids by pcolor() and pcolormesh() is deprecated since 3.5 and will be removed two minor releases later; please call grid(False) first.
(#23855 was for the tutorials, this is for the examples, sorry - I …
> DOC: fix deprecation warnings in examples

- .circleci/config.yml
- examples/images_contours_and_fields/pcolormesh_grids.py
- examples/images_contours_and_fields/pcolormesh_levels.py
Adds a separate step that summarized the warnings and errors during documentation build.
Adds a step which checks for deprecation warnings in examples and tutorials.
I'm quite sure that there is an issue for that which I cannot find, but ideally this should be fed back to GitHub as a comment so it will still not be closed.
Anyway, this should help a bit as it is easier than scrolling back in the very long log (and some messages may have disappeared...).
Helps with #23866 
> Show errors and warnings in doc CI after build.

- lib/mpl_toolkits/axes_grid1/anchored_artists.py
`angle` must be passed as keyword argument from 3.6.
I'm working on tests for this and other anchored artists, but thought this should go on its own in 3.6 to not stall it with reviewing tests etc.
Tests are in #23863 (but not as important to get those into 3.6).
> Remove triggering of deprecation warning in AnchoredEllipse

- requirements/testing/extra.txt
Try to fix installing test deps on windows + mac
> CI: prefer (older) binaries over (newer) sdists

- tutorials/introductory/images.py
Should fix https://github.com/matplotlib/matplotlib/pull/23855#issuecomment-1245059589
> Fix Pillow compatibility in example

- tutorials/introductory/images.py
- Use Pillow to load the image rather than the discouraged plt.imread.
- Remove discussion about rescaling to 0-1 as dropping the use of plt.imread also gets rid of that (not so nice) behavior.  Also drop the lengthy discussion about uint8 and float32, which seems out of place here (if anything it should be in the Pillow docs).  Make corresponding fixes to code to use 0-255 instead of 0-1.
- Fix subplot management to go full pyplot (the local switch to OO-style is a bit weird).
- Fix interpolation discussion as the default is now "nearest" (actually it's now "antialiased", but let's sweep that under the rug for this tutorial for now).
See #22790.  Probably the tutorial could be further improved, but let's consider this a small step in that direction. …
> Update image tutorial.

- doc/conf.py
- mpl_icon_links to the very right, as in the base mpl_sphinx-theme
- I would have liked the version-switcher to be on the very left, but somehow the search button is magically added there (note that we have not listed "search-button", but it still shows up). Since I don't have time to dig into that magic now, the minimal-effort reasonable- result change is the order
> [search] [theme] [version-dropdown] [links]
> DOC: Rearrange navbar-end elements

- lib/matplotlib/offsetbox.py
- lib/mpl_toolkits/axes_grid1/inset_locator.py
It is only called in `get_window_extent` -- and in `draw`, but *that* call is immediately followed by a call to `get_window_extent`, so it is redundant.
Split out of #21699; this change should be less controversial than the rest of that PR.
> Inline AnchoredOffsetBox._update_offset_func.

- lib/matplotlib/legend.py
- lib/matplotlib/tests/test_legend.py
> Add draggable as param to Legend init

- lib/matplotlib/pyplot.py
This is to un-break pycharm's backend_interagg
Closes #23911
I'm not sure the best way to test this, I guess we need to make a minimal backend that does not have FigureCanvas and try push it through the machinery?  Is it worth the effort?
> FIX: only expect FigureCanvas on backend module if using new style

- doc/api/next_api_changes/deprecations/23824-OG.rst
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/collections.py
Closes #23820 #23819
Main benefit, see more above, is that we can remove code which is now effectively dead.
> Deprecate draw_gouraud_triangle

- src/_macosx.m
Avoids `resize_event()` deprecation notices that stem from switching dpis or starting with HiDPI. Likely missed while rebasing PR https://github.com/matplotlib/matplotlib/pull/16931, I tried looking for other potentially deprecated `*_event()`s hidden in the macos code and I didn't find any at a cursory glance.
closes #23921
- [N/A] API changes documented in …
> FIX: use process_event in dpi changes on macosx backend

- doc/users/github_stats.rst
These make pre-commit fail with spellcheck error.
While one ne could argue that we should keep the literal message including the typo, I think it is ok to correct this here: Logical: The PR numbers are stated here, so the PR title not needed as an ID, but rather a description. Also from a practical point of view, it's simpler to fix this than to teach pre-commit to ignore the typo.
Note: This goes directly into the 3.6 branch. The merge #23918 should be rebased on this.
> Fix typos in guthub_stats.rst

- README.rst
I think it's confusing to tell people read the install docs or install.rst (I totally didn't even parse that they were the same doc at first) and we link to the docs in other sections of the readme.
> made explict that install link is install docs in readme

- doc/devel/coding_guide.rst
before, the milestone section used V3.X.Y notation while the backport section used V3.N.M and it tripped me up, so teeny change for them both to use N.M notation based on this discussion https://gitter.im/matplotlib/matplotlib?at=63276b4a11a6a83d04bf3626
> consistent notation for minor/patch branches

- doc/_static/switcher.json
This changes ![image](https://user-images.githubusercontent.com/2836374/191008193-9ec7111b-05e0-40ad-af28-2ed624f1eb25.png) to only show "dev".
While the url is devdocs historically, and I'm not going to change this, the displayed names should be "stable" and "dev". This has the added advantage that dev takes a little less space in the menubar, and thus wrapping occurs slightly later.
> DOC: Display "dev" instead of "devdocs" in the version switcher

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/dates.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_cbook.py
- lib/matplotlib/units.py
Due to the way we handle units on the bar width having an invalid value in the
first position of the x bar (of y of barh) would effectively poison all of the
widths making all of the bars invisible.
This also renames the cbook function _safe_first_non_none function ->
_safe_first_finite and adjusts the behavior to also drop nans
closes #23687
> FIX: show bars when the first location is nan

- src/_tkagg.cpp
Fix building matplotlib on MINGW. Recent changes in https://github.com/matplotlib/matplotlib/commit/e1fcc90c13b037da1501aa53b3491d27081598ca broke it.
Fixes #23943
> Fix building on MINGW

- doc/_static/switcher.json
Reverts matplotlib/matplotlib#23936
Duplication that does not need a backport. Likely we got trapped somewhere with asynchronous updates on both branches.
> DOC: fix versions in v3.6.x doc switcher

- doc/conf.py
AFAICS we're not using it, so don't need to import it in conf.py
> DOC: Don't import doctest because we're not using it

- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_constrainedlayout.py
closes #23986
While fixing this I discovered that `plt.figure(..., constrained_layout={})` can take a dictionary but that is not documented.  Given that it is discouraged, I did not document this feature, but added a test and decided that an empty dictionary should be "True" for this purpose.
> FIX: do not set constrained layout on false-y values

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
> FIX: ValueError when hexbin is run with empty arrays and log scaling.

- doc/conf.py
- tutorials/intermediate/artists.py
- tutorials/intermediate/autoscale.py
By default, sphinx-gallery captures the last output of each code block and shows it in the generated html in yellow boxes. Especially in tutorials with frequently interleaving code and text blocks this may appear confusing and reduces readability. In some cases, however, the output is desired (although it could always be replaced by printing).
The global configuration is now changed to "capture nothing", for one tutorial with multiple desired outputs this is overridden in the file to show the output and in other cases with just one desired output it's converted to a call to print().
(I went through all the examples and tutorials by searching the generated rst files for `.. rst-class:: sphx-glr-script-out` to see if we need the generated output, hopefully I didn't overlook some desired …
> DOC: Suppress IPython output in examples and tutorials where not needed

- examples/color/colormap_reference.py
- lib/matplotlib/colors.py
- tutorials/colors/colormap-manipulation.py
changed the note about reversing a colormap into a section of the colormap reference 'cause it was kind of buried in the preamble
> added a reversing section to colormap reference

- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/tests/test_backend_ps.py
Closes #23954
(Identical to #23910 which I forgot existed. This has a test though...)
> Fix issue with empty line in ps backend

- doc/api/next_api_changes/behavior/23579-AL.rst
- examples/axisartist/demo_curvelinear_grid.py
- examples/axisartist/demo_parasite_axes.py
- lib/mpl_toolkits/axes_grid1/parasite_axes.py
- lib/mpl_toolkits/tests/test_axisartist_axislines.py
- lib/mpl_toolkits/tests/test_axisartist_grid_helper_curvelinear.py
- tutorials/toolkits/axisartist.py
Directly manipulating a list of child axes is strange compared to the
standard Matplotlib axes creation API, so don't use that in mpl_toolkits
parasite axes either.  Instead, use the already existing get_aux_axes
API.  However, that API needs to be improved to support arbitrary
kwargs that get forwarded to the Axes constructor, which is easy to do.
Also replace the default axes_class in that API by _base_axes_class,
which is consistent with HostAxes.twin()/twinx()/twiny(), and also
corresponds to the practical use cases demonstrated in the examples: if
the host axes class is from axisartist, the parasite axes class is also
from axisartist (see examples/axisartist/demo_parasite_axes.py); using
another parasite axes class won't work.
This is preliminary work for making parasite_axes a thin …
> Remove direct manipulation of HostAxes.parasites by end users.

- lib/matplotlib/stackplot.py
- lib/matplotlib/tests/test_axes.py
This is not documented, and likely unwanted, and it breaks using cycle colours ('C0', 'C1', etc.) in the colour list.
Fixes #24024
> Don't modify Axes property cycle in stackplot

- .github/workflows/tests.yml
- lib/matplotlib/testing/compare.py
Currently, the ps backend positions eps images into an imaginary page (the smallest standard page size which can contain the figure size, which happens to be lettersized for the default figure size), setting the %%BoundingBox based on that positioning.  But the eps file format doesn't actually record the full page size (that's not the intent of the eps format anyways), just the position of the drawing relative to an origin.
GhostScript is then used to rasterize the eps images during testing; it implicitly assumes a default page size of "letter" (https://ghostscript.readthedocs.io/en/latest/Use.html#choosing-paper-size) which just happens to match the page size selected above.  So things are OK... except if the test figure is nondefault and actually *bigger* than lettersized; in that case …
> When comparing eps images, run ghostscript with -dEPSCrop.

- lib/matplotlib/backends/_backend_gtk.py
Using the [same method as `__init__`](https://github.com/matplotlib/matplotlib/blob/a283d20f9d682543e40a3d5acb63f299aee92aa4/lib/matplotlib/backends/_backend_gtk.py#L174-L175) to avoid the deprecated-in-GTK3 and removed-in-GTK4 API.
Closes #24015
> Fix _FigureManagerGTK.resize on GTK4

- examples/widgets/span_selector.py
The spanselector example currently has the code broken up into two chunks by a plot. This is confusing because it's easy to copy the first block without the second and then get confused why it doesn't work (like just happened to me). I think that this will make the codeblock continuous so it's easier to copy and not get confused.
- [NA] Has pytest style unit tests (and `pytest` passes).
- [NA] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [NA] API changes documented in …
> [DOC]: make spanselector example codeblock continuous

- lib/matplotlib/tests/test_backend_tk.py
This should fix macOS errors on Azure (or I'm hoping it will.)
> Ignore 'CFMessagePort: bootstrap_register' messages

- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/font_manager.py
- lib/matplotlib/tests/test_backend_svg.py
This:
- expands the generic fonts families to the user configured specific fonts
in the svg output
- ensures that each font family only appears once per text element in the svg output
- ensures that generic families are unquoted and specific families are
closes #22528
closes #23492
I still need to write a test for this, but interactively this gives things like
```svg
<text style="font: 10px 'DejaVu Sans', 'WenQuanYi Zen Hei', 'DejaVu Sans', 'Bitstream Vera Sans', 'Computer Modern Sans Serif', 'Lucida Grande', 'Verdana', 'Geneva', 'Lucid', 'Arial', 'Helvetica', 'Avant Garde', sans-serif; text-anchor: start" x="236.16" y="174.528" transform="rotate(-0 236.16 174.528)">There are 几个汉字 in between!</text>
```
> FIX: correctly handle generic font families in svg text-as-text mode

- examples/style_sheets/style_sheets_reference.py
This PR adds gridlines to the last plot in the stylesheets example and adds an annotation `ax.grid(True)` as well as a divider to clearly distinguish between subplots. This addresses https://github.com/matplotlib/matplotlib/issues/23601
> [DOC]: adding a grid to the style sheet reference.

- lib/matplotlib/axes/_axes.py
Resolves #23700
Adding clarification of markers size in `scatter()` as suggested in #23700 to describe the size of the marker in inches.
> Clarification of marker size in scatter

- lib/matplotlib/colorbar.py
- lib/matplotlib/figure.py
Small docstring correction.  `make_axes` specifically handles numpy arrays
https://github.com/matplotlib/matplotlib/blob/fd5cf5c88123653b656a8f908aa611e5a20dc923/lib/matplotlib/colorbar.py#L1391-L1392
and there is an example in the [Constrained Layout Guide](https://matplotlib.org/stable/tutorials/intermediate/constrainedlayout_guide.html#colorbars) where a 2D array of Axes is passed.
> DOC: colorbar may steal from array of axes

- lib/mpl_toolkits/axes_grid1/axes_grid.py
> Revert argument checking for label_mode

- lib/matplotlib/tests/test_axes.py
The tests test_hexbin_empty and test_hexbin_log_empty use the same target image, however if they the tests ended up being run in different workers when running the tests in parallel they will step on each other if one of the test starts writing the output file while the other is trying to read the test image.
By putting them in the same test they will save and evaluate in order.
I verified I could break both tests.
The other option here is to make a copy of the file (which should be free at the git level due to content based addressing).  I am happy to switch to that if the consensus that is a better approach happy to switch (I was very much on the fence).
This should fix the current rash of transient failures.  We are running `-n 2` on CI so we need to get unlucky that the tests go to …
> TST: force test with shared test image to run in serial

- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_colorbar.py
Closes #23973 where we, without warning, started raising if a colorbar's mappable had no axes.  This adds a deprecation, and otherwise restores the previous behaviour.
> MNT: make orphaned colorbar deprecate versus raise

- doc/api/next_api_changes/deprecations/24088-JMK.rst
Belated API change note for #24088 
> DOC: add API change note for colorbar deprecation

- lib/matplotlib/axes/_axes.py
I did not bother adding any new tests, as the existing tests will already break with the latest nightly NumPy wheels.
Fixes #24106
> Fix mask lookup in fill_between for NumPy 1.24+

- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_colors.py
This is failing on current pytest.
> Add exception class to pytest.warns calls

- doc/api/prev_api_changes/api_changes_3.6.0/deprecations.rst
- lib/matplotlib/cm.py
- lib/matplotlib/tests/test_colors.py
After putting pending deprecations on `cm.get_cmap` we discovered that downstream libraries (pandas) were using the deprecated method to normalize between `None` (to get the default colormap), strings, and Colormap instances. This adds a method to `ColormapRegistry` to do this normalization.
This can not replace our internal helper due to variations in what exceptions are raised.
Closes #23981
I opted to edit the existing deprecation message as this seemed like the lest-bad option.
> FIX: add missing method to ColormapRegistry

- lib/matplotlib/hatch.py
> Bump version when invalid hatches error

- lib/matplotlib/contour.py
- lib/matplotlib/tri/tricontour.py
Issue #24121.
The docstrings implied a functionality that does not exist and never has, this PR updates to what actually happens.
> DOC: align contour parameter doc with implementation

- doc/api/next_api_changes/removals/24128-OG.rst
- doc/api/prev_api_changes/api_changes_3.3.0/deprecations.rst
- doc/api/prev_api_changes/api_changes_3.3.1.rst
- lib/matplotlib/dates.py
- lib/matplotlib/pylab.py
- lib/matplotlib/tests/test_dates.py
- lib/matplotlib/ticker.py
> Expire deprecations in dates and ticker

- doc/devel/coding_guide.rst
- doc/devel/contributing.rst
Hi, I just started with open source and this is my first PR. Noticed some types in the documentation and fixed them.
> [DOC] Fix some documentation typos

- lib/matplotlib/contour.py
- lib/matplotlib/tests/test_contour.py
Closes https://github.com/matplotlib/matplotlib/issues/5332.
> Add QuadContourSet.remove.

- doc/api/next_api_changes/deprecations/24140-AL.rst
- lib/matplotlib/contour.py
ContourLabeler previously optionally used a custom Text subclass to ensure that text rotation took place in data space, not in screen space, but this is now available for all Text instances via the transform_rotates_text property, so directly use that.  This means that _get_label_text, _add_label, and set_label_props can also directly get inlined into their now only callsite (add_label).
> Replace ClabelText by set_transform_rotates_text.

- .github/workflows/tests.yml
- pyproject.toml
- setup.py
This is the start of a transition to a `pyproject.toml` build system (issue #23815) and is a alternative to (or precursor to) PR #23829.
This is the only part of the `pyproject.toml` transition that is required for the `pybind11` progress to continue. So after this is merged work can continue on both `pyproject.toml` and `pybind11` independently.
> Simplest pyproject.toml containing build-system only

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
> FIX: handle input to ax.bar that is all nan

- .github/workflows/tests.yml
- lib/matplotlib/backends/qt_compat.py
I also set the "Minimum versions" job to test the minimum supported versions of all the Qt bindings. Due to [bugs in PySide2](https://bugreports.qt.io/browse/PYSIDE-1140), I had to set its minimum to 5.14 instead of 5.11.2 like PyQt5.
Fixes #24155.
> Fix Qt with PySide6 6.4.0

- examples/subplots_axes_and_figures/subplots_demo.py
variable `axs` was not defined in the code snippet of `Sharing x per column, y per row` figure, rather it was defined in some earlier snippets. The intended use here is applying `label_outer()` on the axes of the figure in the current snippet.
> Fix example where wrong variable was used

- doc/make.bat
added `html-noplot` and `show` targets to make.bat  so that it supports all the [documented build options](https://matplotlib.org/stable/devel/documenting_mpl.html#setting-up-the-doc-build) and updated the clean to fully clean (#11319)
> windows doc build parity

- doc/api/next_api_changes/deprecations/24144-AL.rst
- lib/matplotlib/contour.py
The deprecated attributes cannot be updated after the ContourLabeler has been set up (i.e. if the end user overwrites them it does not update the labels) *and* all have direct replacements available.  We could consider later adding new getters/setters (`get/set_font_properties`) which would actually update the properties on the label texts.
While at it, prefer using `manual` over the equivalent but longer `self.labelManual`; `_get_nth_label_width` doesn't need to explicitly set the text size as that info is also carried by the fontproperties object.
> Deprecate some label-related attributes on ContourLabeler.

- lib/matplotlib/tests/test_cbook.py
- lib/matplotlib/tests/test_mlab.py
A minimal change to resolve #24148.  Replaced Nose's `setup` with pytest's [`setup_method`](https://docs.pytest.org/en/7.1.x/how-to/xunit_setup.html?highlight=setup_method#method-and-function-level-setup-teardown).  I note that there is already an instance of `setup_method` within [test_transforms.py](https://github.com/matplotlib/matplotlib/blob/c744161bdaf8b2a40bf96dcc0ebcd37ea0444319/lib/matplotlib/tests/test_transforms.py#L229).  I installed `pytest` with
`pip install git+https://github.com/pytest-dev/pytest.git@main`
and verified that
* With a clean branch, I reproduce the errors shown at #24148.
* With the change, these test modules pass.
- [N/A] New features have an entry in …
> TST: convert nose-style tests

- doc/api/next_api_changes/deprecations/24000-TH.rst
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_pyplot.py
Until now, the test made some exclusions (_NON_PLOT_COMMANDS) and reqired all functions to be documented in a single autosummary block.
This change ensures the documentation of the _NON_PLOT_COMMANDS and it allows the commands to be spread across arbitrary many autosummary sections. This is in preparation of regrouping the pyplot commands similar to the Axes documentation.
This also pending deprecates `pyplot.get_plot_commands`, which should not be a public function. I'm defensive by using pending, because if `get_plot_commands` is used somewhere, that's most likely some downstream lib and we want to give them time to adapt.
Correctness of this change is automatically tested by by passing `test_pyplot.py::test_doc_pyplot_summary`.
> Generalize validation that pyplot commands are documented

- setup.py
It can be missing rather than false when invoke as
$ pip install --no-build-isolation .
> BLD: be more cautious about checking editable mode

- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/_backend_pdf_ps.py
- lib/matplotlib/backends/backend_agg.py
Less duplicated code.
The `RendererBase` version of it is not tested, but I guess it should still be there?
> MNT: Refactor `Renderer.get_text_width_height_descent`

- doc/devel/coding_guide.rst
- doc/users/explain/interactive.rst
Closes #22905. Not sure why we had the `.. toctree::` entry there or what sphinx is doing with it. But it's not needed and without it the page becomes a structure leaf like it's sibling pages.
> DOC: Fix toc structure in explain/interactive

- doc/api/next_api_changes/removals/24129-OG.rst
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backend_managers.py
- lib/matplotlib/backend_tools.py
- lib/matplotlib/backends/_backend_tk.py
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_qt.py
- lib/matplotlib/backends/backend_qt5.py
- lib/matplotlib/backends/backend_wx.py
It didn't look like `cursord` was deprecated in Qt, despite https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.5.0.html#cursord-in-gtk-qt-and-wx-backends
https://github.com/matplotlib/matplotlib/blob/924e2107069c8fe9b8d7683a0b5ec0055c7c3647/lib/matplotlib/backends/backend_qt.py#L82-L92
> Expire cursor-related deprecations

- doc/api/next_api_changes/deprecations/24198-AL.rst
- lib/matplotlib/backends/backend_ps.py
The entire contents of the class have previously been deprecated and removed, but the class itself and its sole instance were left around.
> Deprecate unused backend_ps.{PsBackendHelper,ps_backend_helper}.

- .github/workflows/conflictcheck.yml
Not sure if one can actually see the effects of this without merging...
> Automatically update rebase label

- doc/api/next_api_changes/deprecations/24208-AL.rst
- lib/matplotlib/backends/backend_webagg.py
It is clearly just for internal use, can be replaced by a plain Thread(target=...), and removing it gets rid of a large block in the webagg api docs that just restates the standard Thread docstring (https://matplotlib.org/devdocs/api/backend_webagg_api.html#matplotlib.backends.backend_webagg.ServerThread).
> Deprecate backend_webagg.ServerThread.

- lib/mpl_toolkits/axisartist/axislines.py
Note that get_label_{offset_transform,pos} only ever existed in very old
versions of axisartist; get_axislabel_{transform,pos_angle} are what's
been used ever since then.
> Small cleanups to axislines docs.

- lib/matplotlib/backend_managers.py
- lib/matplotlib/tests/test_backend_bases.py
> Add tests for ToolManager

- lib/matplotlib/tests/test_triangulation.py
- lib/matplotlib/tri/tricontour.py
- lib/matplotlib/tri/tripcolor.py
Changes:
- `tricontour(x, y, Z, ...)` --> `trcontour(x, y, z, ...)` (and same for `tricontourf()`
- `tripcolor(x, y, C, ...)` --> `tricpcolor(x, y, c, ...)`
There is no reason here for uppercase C or Z, the preceding parameters x, y are also not uppercase.
Note that this is not an API change since these parameters are positional-only (created from *args). Thus, we can change the names without a deprecation.
> DOC: Lowercase some parameter names

- doc/api/next_api_changes/deprecations/24221-AL.rst
- src/_backend_agg_wrapper.cpp
These methods are unused; it is better to directly get array views (this saves a copy); and removing them prepares for a possible future where BufferRegions mostly go away and copy_from_bbox/restore_region directly operate on numpy arrays (#23882).
> Deprecate BufferRegion.to_string{,_argb}.

- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/backend_pgf.py
- lib/matplotlib/backends/backend_svg.py
Doc-string is maybe not required as it is so close to `draw_text`, but still...
> MNT: Remove redundant method, fix signature and add doc-string to `draw_tex`

- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_figure.py
Noticed this while reviewing #24189 .
> FIX: do not mutate dictionaries passed in by user

- lib/matplotlib/legend.py
- lib/matplotlib/tests/test_legend.py
As raised by #20577, setting `labelcolor` to any of the string options did not work with a scatter plot as it is a PathCollection with possible multiple color values. This commit fixes that. Now, if there is a colormap or a scatter plot with multiple values, then, the legend text color is not changed, but otherwise, the text color is changed to the color of the scatter markers.
> Add textcolor to legend based on labelcolor string

- lib/matplotlib/tests/test_text.py
- lib/matplotlib/text.py
- lib/matplotlib/widgets.py
I updated the position_cursor function of Textbox so that it doesn't approximate the position of the cursor incorrectly anymore. Now, instead, to calculate the cursor's position, we accumulate the width of each character contained in the text and find the index where the distance between the click position and the accumulated sum is minimal.
I found that the approximation used in the position_cursor function before this PR was really buggy sometimes, running this code block and trying to set the cursor in different positions makes it apparent :
```
from matplotlib.widgets import TextBox
fig = plt.figure(figsize=(4, 3))
box_input = fig.add_axes([0.1, 0.5, 0.8, 0.2])
text_box = TextBox(ax=box_input, initial=f'kkkkkk iiiii kkkkkk', label='')
fig.show() …
```
> Fixed the positioning of cursor in Textbox: no approximation

- lib/matplotlib/backends/_backend_tk.py
- lib/matplotlib/backends/backend_wx.py
Closes #23969 (as there is a separate OSX issue #23777)
Draw a solid white rectangle and then add a dashed black rectangle so that it works on both light and dark backgrounds. For the tk backend it messes up the deprecated `lastrect` as bit since it only can contain one of the two rectangles. Not sure what `lastrect` is used for. If it is only to get the position it should be OK, but if it is to possibly modify the rectangle it may not work.
No obvious way to test it in the CI.
> Improve rubberband rendering in wx and tk

- lib/matplotlib/axes/_base.py
- lib/matplotlib/tests/test_axes.py
This PR fixes the issue where the function set_aspect when given a negative number as a parameter leads to infinite loop (#23847)
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-doc …
> Raise ValueError on negative number inputs for set_aspect 

- doc/devel/color_changes.rst
- doc/devel/contributing.rst
This is a long standing policy (the reference I found is from 2015 and I remember that being the position when I started to work on Matplotlib in 2012) and is being documented here.
This position is consistent with our testing scheme (that strives for pixel identical renderings across platforms, Python versions, and Matplotlib versions).
Changing the default colormap (and the rest of the styling) was the proximal cause of 2.0 not being 1.6 due to this policy.
----
This PR is not an opportunity to debate if this _should_ be the position we take, it documenting what it currently is.  If we want to start a discussion about changing the then that must be done in a follow on PR.
> DOC: document that appearance is part of our stable API

- lib/matplotlib/backends/qt_editor/figureoptions.py
As mentioned in #23566 , for the figure options, things were hard coded for the X and Y axes but were not implemented for the Z axis. With this commit, all the options in the Figure options dialogue box are generated dynamically based on the axes present in the figure. This removes all the hard coded part and should make it more modular to make further changes.
> Set figure options dynamically

- lib/matplotlib/animation.py
Clarify that it is OK to pass blit=True even if the backend does not support it.  Tweak the progress_callback example to avoid a backslash escape.  Small additional doc/style fixes.
> Small animation docs/style fixes.

- lib/matplotlib/ticker.py
> Improve documentation for ticker

- lib/matplotlib/tri/tricontour.py
Related to #5943 (not sure where to check that z is indeed finite).
> Clarify that z must be finite for tricountour(f)

- doc/api/next_api_changes/deprecations/24240-OG.rst
- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/mplot3d/axis3d.py
I cannot see that there is any valid public use for these. No doc-string either.
> Deprecate unit_cube-related methods in Axes3D

- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_backend_bases.py
> Fix key reporting in pick events

- lib/matplotlib/__init__.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_pyplot.py
I think this should go in for 3.1.1 as it helps to reduce the
action-at-a-distance issues around the auto-backend / IPython
configuration.
> FIX: don't close figures if switch_backend is a no-op

- doc/api/next_api_changes/removals/24253-OG.rst
- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
- lib/mpl_toolkits/axisartist/axislines.py
- lib/mpl_toolkits/mplot3d/axes3d.py
> Expire deprecation of grid argument name

- lib/matplotlib/style/core.py
- lib/matplotlib/tests/test_style.py
> Restore (and warn on) seaborn styles in style.library

- lib/matplotlib/tests/test_contour.py
- lib/matplotlib/tests/test_streamplot.py
This is similar to #22132 in that NumPy has added more code paths that now take advantage of AVX512 optimizations and causes slight variations in results.
Fixes #24060
> TST: Increase fp tolerance on more tests for new NumPy

- lib/matplotlib/axes/_axes.py
- lib/mpl_toolkits/axes_grid1/parasite_axes.py
Based on discussion on call and in #23506, trying out some versioning directives. Policy at #24161 
Haven't styled anything yet, tried w/o and w/ description cause wasn't sure what made more sense. I guess w/o is a pointer to go look up those release notes, but not sure how to document that. The issue is that these two are partially new things - polar errobars and more valid parameter values, rather than wholly new things.
> sample versioning directives, empty + description

- doc/api/next_api_changes/removals/24251-OG.rst
- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_collections.py
- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/tests/test_mplot3d.py
> Expire deprecation for `auto_add_to_figure=True` in `Axes3D`

- doc/api/next_api_changes/deprecations/24220-AL.rst
- lib/matplotlib/_fontconfig_pattern.py
- lib/matplotlib/tests/test_fontconfig_pattern.py
- Warn on unknown constant names, e.g. ``DejaVu Sans:unknown`` (as opposed e.g. to ``DejaVu Sans:bold``); they were previously silently ignored.
- Rewrite the parser into something much simpler, moving nearly all the logic into a single block post-processing the result of parseString, instead of splitting everything into many small parse actions.  In particular this makes the parser mostly stateless (except for the cache held by pyparsing itself), instead of having the various parts communicate through the _properties attribute.
> Simplify and tighten parse_fontconfig_pattern.

- examples/text_labels_and_annotations/angles_on_bracket_arrows.py
- lib/matplotlib/patches.py
PR relates to this [issue](https://github.com/matplotlib/matplotlib/issues/23176). Added `AngleAnnotation` patches to mark the angles and included `FancyArrowPatch` arrows to show the directions of AngleA and AngleB.
> Updated Angles on Bracket arrow styles example to make angles clear #23176

- pyproject.toml
Otherwise, a new version will be installed in the isolated build environment, and Matplotlib will fail to import in an existing environment with older NumPy.
According to its docs, this _should_ be okay even though we target a newer version at runtime, and this linkage may possibly go away if we move to pybind11 anyway.
- [n/a] New features are marked with a `.. versionadded::` directive in the docstring and documented in …
> Use oldest-supported-numpy for build

- lib/mpl_toolkits/mplot3d/axes3d.py
`voxels` does not use `cmap` at all, and thus does not modify `shade` in relation to `cmap` being passed in, this appears to be copy/pasted from 3D methods which _do_ use `cmap`.
> Remove comment about cmap from voxels docstring

- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/streamplot.py
> Rely on builtin round() instead of manual rounding.

- lib/matplotlib/backends/backend_ps.py
Fixes issue #23965 by converting stream logic to a simpler group by form
_Suggested by @tacaswell_
_Originally posted by @anntzer in https://github.com/matplotlib/matplotlib/pull/23910#issuecomment-1252201631_
>  Simplifying glyph stream logic in ps backend

- lib/matplotlib/tests/test_font_manager.py
The test uses _get_fontconfig_fonts methods
> Run test if fontconfig is present

- examples/images_contours_and_fields/image_zcoord.py
> Cleanup image_zcoord example.

- examples/statistics/time_series_histogram.py
- lib/matplotlib/colors.py
- lib/matplotlib/image.py
- lib/matplotlib/patches.py
- lib/mpl_toolkits/mplot3d/axes3d.py
`round` does return an `int` (at least in Python 3).
> MNT: Remove redundant int after round

- examples/event_handling/path_editor.py
- examples/subplots_axes_and_figures/secondary_axis.py
- examples/units/basic_units.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/collections.py
- lib/matplotlib/contour.py
- lib/matplotlib/image.py
- lib/matplotlib/patches.py
- lib/matplotlib/sankey.py
- lib/matplotlib/testing/compare.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_collections.py
- lib/matplotlib/tests/test_colors.py
- lib/matplotlib/tests/test_sankey.py
- lib/matplotlib/tests/test_transforms.py
- lib/matplotlib/tests/test_triangulation.py
- lib/matplotlib/transforms.py
- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/mplot3d/axis3d.py
- lib/mpl_toolkits/tests/test_axes_grid1.py
Quite often numpy will call asarray for us, saving us the need to call asarray explicitly.
When we do call asarray (or array) ourselves, a dtype can directly be passed in, rather than immediately calling astype immediately after. Passing the dtype makes it unnecessary for asarray to infer the dtype of the passed-in container, and can also save an extra array allocation if asarray first has to allocate an array of a type and astype immediately has to allocate an array of another type.
> Remove unnecessary np.{,as}array / astype calls.

- tutorials/text/annotations.py
Updated the annotation tutorial to hopefully clarify how relative positioning of offsets works. attn @ubitux  
ETA: Also ended up moving things around to try and create some conceptual groupings. 
ETA 2: I have no idea what the capitalization convention is supposed to be
> added offset section & restructured annotations tutorial

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/colors.py
3d2ffef0 added special-casing to handle empty log-scale hexbins, but the more back-compatible fix is to switch make_norm_from_scale to reproduce the old behavior of setting vmin/vmax to np.ma.masked when autoscaling with an empty array.  (Whether that behavior is really better is unclear, but until this is properly investigated, it seems safer to go back to it.)
See #23944, #23922.
> Move empty hexbin fix to make_norm_from_scale.

- lib/matplotlib/backends/web_backend/js/mpl.js
This fixes the resize grip on WebKit, which is a bit buggy [1, 2]. We additionally need to ignore pointer events on both canvases, even though their `z-index` puts the `div` on top.
For mouse events, we no longer prevent the default handler in most browsers, because that will block the resize grip from working now that it is handling events from the same `div`. Due to the same bugs in WebKit, we _do_ still need to prevent the default handler there, or else any mouse drags (i.e., for pan and zoom), will cause the browser to try and select the canvas.
The mouse position calculation is somewhat simplified as well.
To ensure keyboard events make it to the canvas `div`, it now has a `tabindex`.
[1] https://bugs.webkit.org/show_bug.cgi?id=144526
[2] …
> nb/webagg: Move mouse events to outer canvas div

- lib/matplotlib/_fontconfig_pattern.py
- Switch _family_escape, _value_escape to be more similar to _family_unescape, _value_unescape.
- generate_fontconfig_pattern doesn't need to go through the generic escape_val, but instead rely on the fact that prop.get_family() always returns a list whereas the other getters always return a scalar value, and directly do the escaping and joining as needed.
> Simplify generate_fontconfig_pattern.

- doc/api/next_api_changes/deprecations/24305-AL.rst
- lib/matplotlib/patches.py
... and deprecate the SimpleEvent helper.
> Unify logic of ConnectionStyle._Base.{_clip,_shrink}.

- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/widgets.py
Found while testing out `flake8-rst` (for which there are unfortunately a few too many false positives.)
> Fix some minor docstring typos

- SECURITY.md
I have checked with the numpy and scipy maintainers who have been happy with using tidelift to manage security vulnerability in both the case of valid and invalid reports.
matplotlib-steering-council@numfocus.org is still the email address that tidelift has to contact when they get a report.
The contract does not open us to any additional liability.
> GOV: change security reporting to use tidelift

- doc/api/animation_api.rst
- lib/matplotlib/animation.py
Fixes #20326
Closes #20358
Closes #24139
Merged contents from #20358 and #24139 with comments. Probably have missed something...
> Update example and docstring to encourage the use of functools.partial in FuncAnimation

- doc/users/next_whats_new/shade_poly3dcollection.rst
- lib/mpl_toolkits/mplot3d/art3d.py
- lib/mpl_toolkits/mplot3d/axes3d.py
Fixes #19509.
Refactors shading of Poly3DCollection and moves it to the constructor of the collection rather than in every individual plotting method, Can still be done anywhere though.
> Add shading of Poly3DCollection

- doc/api/pyplot_summary.rst
This groups the pyplot functions in logical groups, which should make it easier to find functionality.
To keep things simple this only regroups the existing listed functions (note that the `test_doc_pyplot_summary` guarantees that no function was accidentally added or removed). One can and should do a bit more (see notes below), but I'll leave that for a follow-up PR.
Notes:
- There have been and still are some module-level variables missing, most prominently `rcParams`.
- I've copied the original "Colormaps" section verbatim to "Colormapping-related commands". This is a bit out-of-style because all other sections only contain the autosummary links. However two aspects make this non-trivial:
1) the variables `colormaps` and `color_sequences` do not have autogenerated stubs. It seems …
> DOC: Group pyplot commands by category

- doc/devel/documenting_mpl.rst
The make option `-Dplot_gallery=0` is superseeded by `make html-noplot`. While we have removed it from the simple calls (#23870), it was still present in examples with multiple options.
Remove it in the example calls and replace it by a still used option.
> DOC: Minor cleanup in "Writing documentation"

- lib/matplotlib/_tight_layout.py
- lib/matplotlib/figure.py
- lib/matplotlib/gridspec.py
- lib/matplotlib/layout_engine.py
... instead of triplicating it on the caller side.
> Emit "axes not compatible with tight_layout" in a single place.

- lib/matplotlib/__init__.py
Inspired by #24351
Reading the docstring of `rc_context` it was very unclear that all rcparams set in the body will be reset not just those set in the context invocation.  This has been the behavior back to 2012 when we added this to the code base in 2045bdbd2c00cb71fbce3c03c066b06213aa1567 .
> DOC: clarify rc_context resets all rcParams changes

- .github/workflows/tests.yml
- doc/api/next_api_changes/development/24257-AL.rst
- doc/devel/dependencies.rst
- doc/users/next_whats_new/styles_from_packages.rst
- environment.yml
- lib/matplotlib/style/core.py
- lib/matplotlib/tests/test_style.py
- requirements/testing/minver.txt
- setup.py
- tutorials/introductory/customizing.py
The first commit inlines the logic of the undocumented _remove_blacklisted_style_params and _apply_style helpers into mpl.style.use, which makes it easier to follow (the exact semantics of `_apply_style` are really not that clear without going to check its implementation anyways).  It's mostly just preparation for the second commit.
The second commit implements loading of style files from third-party packages (as `mpl.style.use("package.name.style_name")`, which loads `package/name/style_name.mplstyle`).  This fixes the long-standing issue of how third-parties can distribute style sheets (for those who really don't want to actually import the third-party package).
The exact syntax and semantics could be discussed, but I think the basic design is there.
Fixes #17978 …
> Load style files from third-party packages.

- tutorials/advanced/transforms_tutorial.py
I blindly copy-pasted the suggested code and got:
```
SyntaxError: positional argument follows keyword argument
```
I changed it to use positional-only, but I could change them all to be `kwarg`s instead if you want.
> DOC: Fix syntax of suggestion

- doc/api/next_api_changes/removals/24355-OG.rst
- lib/matplotlib/backends/backend_agg.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/backends/backend_template.py
> Expire unused positional parameters in canvas subclasses

- doc/api/next_api_changes/removals/24356-OG.rst
- lib/matplotlib/collections.py
- lib/matplotlib/tests/test_collections.py
Tests crash locally (they sometimes do), so will run the tests here and then add a release note.
> Expire QuadMesh old signature deprecation

- doc/devel/development_setup.rst
Tell users to install dev dependencies before doing the editable install. This makes sure a C++ compiler ist available for the build step.
> DOC: Install dev dependencies before building matplotlib

- lib/mpl_toolkits/mplot3d/axis3d.py
Closes #21878
As I understand it, it is primarily a bonus when editing the svg file later. Doesn't seem to break anything (in local tests, hence running all tests here now).
A bit unclear how to actually test it and if any release note is required.
> Change default rotation mode for 3D labels to 'anchor'

- doc/api/prev_api_changes/api_changes_3.0.0.rst
- doc/api/toolkits/mplot3d.rst
- doc/api/toolkits/mplot3d/axes3d.rst
- doc/users/prev_whats_new/whats_new_3.4.0.rst
- examples/mplot3d/stem3d_demo.py
- lib/mpl_toolkits/mplot3d/axes3d.py
Organize [Axes3D doc](https://matplotlib.org/devdocs/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.html) with sections and tables, similar to the [Axes doc](https://matplotlib.org/devdocs/api/axes_api.html?highlight=axes#plotting). Adds a new file, doc/api/toolkits/mplot3d/axes3d.rst.
For Issue #23901.
Further improvements for this PR:
1. ~~Exclude or add docstrings to undocumented `axes3d.Axes3D` public methods.~~
~~a. Should deprecated methods be excluded? (`Axes3D.unit_cube()`, `Axes3D.tunit_cube()`, and `Axes3D.tunit_edges()`)~~
~~b. `Axes3D.update_datalim()` is an empty method that only contains `pass`. The docstring seems to be inherited from matplotlib/axes/_base.py. Should the `Axes3D.update_datalim()` docstring be changed to something like "Not implemented in Axes3D."?~~
~~c. …
> DOC: Organize Axes3D methods into sections

- examples/event_handling/image_slices_viewer.py
- lib/matplotlib/backend_bases.py
> DOC: Improve Image Slices Viewer example

- examples/spines/spine_placement_demo.py
- lib/matplotlib/spines.py
- use `subplot_mosaic()` instead of `subplot(n, m, k)` calls
- hide spines using `set_visible(False)` instead of `set_color('none')`
- use multi-assignment (`spines[['left', 'bottom']].set_*`) when possible
- remove `ax.xaxis.set_ticks_position('bottom')` and `ax.yaxis.set_ticks_position('left')`, because these are already the defaults
- reference the example in `spine_set_positions()` docstring
> DOC: Cleanup Spine placement example

- doc/users/next_whats_new/colorbar_has_location_argument.rst
- lib/matplotlib/colorbar.py
- lib/matplotlib/tests/test_colorbar.py
Closes #22676
Is this an API change or a user change?
~Will add an unrelated test for #23260 here as well.~ Added. However, they do not look great... The png looks OK, but locally I get in Spyder:
so there it seems like there is a bit of overlap that is not visible in the test image. For the svg there is a gap instead, although this seems to depend on the renderer...
~Also, I do not understand why the test images are not just four squares as the pasted image...~
> Add location keyword argument to Colorbar

- doc/api/fontconfig_pattern_api.rst
- doc/api/index.rst
- lib/matplotlib/_fontconfig_pattern.py
- lib/matplotlib/fontconfig_pattern.py
Remove the single-method class in favor of plain functions.  The backcompat class can be moved to the deprecated public fontconfig_parser (no underscore) module, so they'll get removed at the same time.  While we're at it do the same for {family,value}_{escape,unescape}; however, despite the comment, I decided to keep the new versions of _{family,value}_{escape,unescape} still underscore-prefixed within the private module (signalling that these aren't intended to be used even from other Matplotlib modules).
> Kill FontconfigPatternParser.

- lib/matplotlib/tests/test_font_manager.py
- src/ft2font_wrapper.cpp
Per [conversation on gitter](https://gitter.im/matplotlib/matplotlib?at=636c7bc50513b562e8a30787), I was trying to add fonts and thought I could pass in the path to the folder of fonts cause the docs say path, so I wanted to make it a bit clearer that path means path to file.
> made f2tfont error message explicit that it needs path to file

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Implements the proposed solution in issue #21959. Error message now outputs the user’s input via `repr`.
> Use `repr` in error message Addresses #21959

- doc/users/next_whats_new/show_source_links_directive_option.rst
- lib/matplotlib/sphinxext/plot_directive.py
- lib/matplotlib/tests/test_sphinxext.py
The Sphinx plot directive (`.. plot::`) now supports a `:show-source-link` option to show or hide the link to the source for each plot. The default is set using the `plot_html_show_source_link` variable in `conf.py` (which itself defaults to True).
> Add :shows-source-link: option to Sphinx plot directive

- doc/users/next_whats_new/bar_label_formatting.rst
I noticed that a what's new entry I submitted as part of a [previous PR](https://github.com/matplotlib/matplotlib/pull/23690) is not rendering the plots. I switched to render the plot and the source code like the other examples.
- [N/A] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in …
> DOC: Fix What's New entry for bar_label() formatting.

- doc/users/next_whats_new/colorbar_has_location_argument.rst
The example for the What's new entry on colorbar location is currently being cut off. I added a call to `tight_layout()` to fix this:
After the change, it looks like this ([link to this in the built docs](https://output.circle-artifacts.com/output/job/7c7b133c-59ff-4536-8681-342778427566/artifacts/0/doc/build/html/users/next_whats_new/colorbar_has_location_argument.html)):
- [N/A] New features are marked with a `.. versionadded::` directive in the docstring and …
> DOC: Fix colorbar what's new entry so it isn't cut off.

- lib/matplotlib/axes/_base.py
Adds a listing of the valid values of `which` to `get_xaxis_transform` and `get_yaxis_transform` docstrings.
> Add valid values to `get_*axis_transform` docstring

- doc/users/next_whats_new/imshow_extent_units.rst
The example for the What's new entry on the `extent` parameter to `imshow` currently has a very crowded y-axis and the labels are being cut off:
I reduced the number of major ticks and adjusted the figure size in addition to calling `tight_layout()` to fix this. It now looks like the below in the [built docs](https://output.circle-artifacts.com/output/job/0e4b2611-e306-4e93-9804-442b8365b5a9/artifacts/0/doc/build/html/users/next_whats_new/imshow_extent_units.html).
- …
> DOC: Fix example for what's new imshow so it isn't cut off or crowded.

- lib/matplotlib/_api/__init__.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/contour.py
- lib/matplotlib/gridspec.py
- lib/matplotlib/quiver.py
- lib/matplotlib/tests/test_quiver.py
... matching the wording for standard functions.
Note that nargs_error returns the exception without raising it itself to
make the control flow clearer on the caller side.
> Factor out error generation for function calls with wrong nargs.

- .appveyor.yml
- environment.yml
- lib/matplotlib/tests/test_backends_interactive.py
- lib/matplotlib/tests/test_font_manager.py
- lib/matplotlib/tests/test_getattr.py
Closes #24394
Avoid mixing conda and pip (except for those pip dependencies in the environment.yml)
Should fix appveyor tests failing due to pip pywin32 version.
> Simplify appveyor to only use conda

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
When to use what:
- warnings.warn() in library code if the issue is avoidable and the client application should be modified to eliminate the warning
- logging.warning() if there is nothing the client application can do about the situation, but the event should still be noted
There are unambiguous ways for the user to specify the color (see the message). Here, the user should take action and switch from using *c* to using *color*. Thus warnings.warn() is the way to go.
Closes half of #23422.
> MNT: Issue a warning instead of logging if RGB(A) passed to scatter(..., c)

- lib/matplotlib/axis.py
- lib/matplotlib/tests/test_axes.py
`Axis.set_ticks()` allows kwargs to pass without using them if `labels=None`.
With these changes, `Axis.set_ticks()` now raises an exception when `labels=None` and kwargs are passed.
Does this change need API doc updates?
Resolves #24273. 
> ENH: Check labels arg when kwargs passed in Axis.set_ticks()

- doc/api/backend_agg_api.rst
- doc/api/backend_bases_api.rst
- doc/api/backend_cairo_api.rst
- doc/api/backend_gtk3_api.rst
- doc/api/backend_gtk4_api.rst
- doc/api/backend_managers_api.rst
- doc/api/backend_mixed_api.rst
- doc/api/backend_nbagg_api.rst
- doc/api/backend_pdf_api.rst
- doc/api/backend_pgf_api.rst
- doc/api/backend_ps_api.rst
- doc/api/backend_qt_api.rst
- doc/api/backend_svg_api.rst
- doc/api/backend_template_api.rst
- doc/api/backend_tk_api.rst
- doc/api/backend_tools_api.rst
- doc/api/backend_webagg_api.rst
- doc/api/backend_wx_api.rst
We don't use links in titles.
Fixes part of #24398.
> DOC: Fix title formats in backend api docs

- lib/matplotlib/figure.py
- lib/matplotlib/pyplot.py
Closes #24433
The method name for `Figure.legend` in `pyplot` is `figlegend` due to a name collision.
As such, a `.replace` call is used to translate the docstring from the one written for `Figure.legend` to make sense for users interacting with `plt.figlegend`.
This behavior was originally introduced in #11975, using `legend(` alone (with no dotted name).
The docstring was updated in #18106, with additional examples that used `fig.legend(` in additional examples.
These new examples were caught by the replace and became `fig.figlegend(`.
This PR makes all calls `fig.legend` and simply removes the dot for the replace call.
This leads to some _slightly_ incongrous examples which are using the object based api to call `ax.plot` but following that with `figlegend` from `pyplot`. (not _wrong_ …
> Fix pyplot.figlegend docstring

- examples/text_labels_and_annotations/legend_demo.py
* removed unused variable `lines` in line 169
* should be create custom classes, not custom objects
> removed unused variable and fixed text in doc

- lib/matplotlib/offsetbox.py
- lib/matplotlib/tests/test_offsetbox.py
Instead of passing a list of (widths, xdescents) where xdescent is unused, just pass a list of widths.  This helper is private so we just need to adjust the call sites and tests with no deprecation.
This patch is preliminary work for some further cleanup on the offsetbox module (somewhat motivated by #24386).
> Don't pass unused xdescent to _get_packed_offsets.

- lib/matplotlib/colors.py
They're the same if autoscale() first resets vmin/vmax to None.  This ensures e.g. that the exact semantics of fully invalid arrays (in_trf_range is empty) for make_norm_from_scale are consistent between the two methods.
Followup to #24259.
> Define autoscale() based on autoscale_None().

- lib/matplotlib/testing/decorators.py
Swapped `fig_ref` and `fig_test` in the error message so that it'd match the order in the function signature. Technically I think order doesn't matter since it's done by signature, but I think having them in the same order slightly reduces friction.
> [DOC] swapped params in fig_compare_error msg

- .github/PULL_REQUEST_TEMPLATE.md
Since flake is now a part of the CI test and recommended as part of the pre-commit hooks, figured it can be dropped from the checklist and then the template can be condensed a drop.
> [DOC] removed flake8 from PR template

- examples/text_labels_and_annotations/demo_annotation_box.py
- lib/matplotlib/offsetbox.py
Closes #24390.
* Add a description of the `bboxprops` keyword for `AnnotationBbox` instantiation.  At https://github.com/matplotlib/matplotlib/issues/24390#issuecomment-1307083940 @oscargus noted that `arrowprops` and `fontsize` are also missing from the docstring, but possibly they are covered by "Other parameters are identical to Annotation"?  I note that the `arrowprops` description in [Annotation](https://matplotlib.org/stable/api/text_api.html#matplotlib.text.Annotation) is quite extensive, so am not sure of the wisdom of copying it across to related docstrings.
* Modify the AnnotationBbox demo to include some examples using the `bboxprops` keyword.  ~While I was in there I also changed all double quotes to single quotes, as there is currently a mixture and I think it should be …
> DOC: AnnotationBbox keyword descriptions

- requirements/doc/doc-requirements.txt
Fix single column layout and extra white space caused by pydata-sphinx-theme 0.10.0, see #23976. This was fixed in pydata/pydata-sphinx-theme/pull/964.
Closes #23976.
> DOC: Fix examples gallery layout issues

- lib/matplotlib/tests/test_ticker.py
- lib/matplotlib/ticker.py
As part of investigating https://github.com/matplotlib/matplotlib/issues/24383, I noticed that `LogLocator` has custom behaviour for polar Axes. This dates back 13 years (!!) to https://github.com/matplotlib/matplotlib/commit/1fdd5a8af97df3443d9a26a902b9f3513f33fe92. Since log-scaled polar Axes are broken anyway, I thought I would remove this logic and see if any existing tests break.
I've also added a new test to check the y-ticks on a log-scaled polar plot. Prior to this PR the ticks were given at `[ 0.01  0.1   1.   10.  ]`, not including the max limit of `100`, showing that the custom polar logic in `LogLocator` was wrong anyway.
> Remove custom polar behaviour in LogLocator

- examples/animation/strip_chart.py
I left this running to about 3500s and it had not drifted out of the 2s interval.
Fixes #24476
> Fix floating-point drift in oscilloscope example

- doc/users/project/mission.rst
Mostly it just looks superfluous in autogenerated table of contents (xref #24493)
> DOC: Removed matplotlib from mission statement title

- lib/matplotlib/animation.py
I don't know about testing this, but I did check that it works correctly if you save to an absolute path or to a relative path above the current directory.
Fixes #23581 …
> Use relative frame path in HTMLWriter

- doc/conf.py
- requirements/doc/doc-requirements.txt
`pydata-sphinx-theme` updated, renaming some configuration names. (only one of which we actually configure)
While they are just warnings for now, we are configured to error on warning so CircleCI is indicating failure.
This does the 'easy' route of just changing to the new name and expecting the version in which it is implemented.
If desired, I could do a larger change to accomodate both by checking the version, but I'm also not _too_ worried about more tightly pinning already relatively tight requirements.
- [n/a] New features are marked with a `.. versionadded::` directive in the docstring and documented in …
> Backport PR#24488 to v3.6.2-doc

- doc/conf.py
- requirements/doc/doc-requirements.txt
`pydata-sphinx-theme` updated, renaming some configuration names. (only one of which we actually configure)
While they are just warnings for now, we are configured to error on warning so CircleCI is indicating failure.
This does the 'easy' route of just changing to the new name and expecting the version in which it is implemented.
If desired, I could do a larger change to accomodate both by checking the version, but I'm also not _too_ worried about more tightly pinning already relatively tight requirements.
- [n/a] New features are marked with a `.. versionadded::` directive in the docstring and documented in …
> Backport of PR#24488 (Update for pydata-sphinx-theme 0.12.0)

- lib/mpl_toolkits/mplot3d/art3d.py
- lib/mpl_toolkits/mplot3d/tests/test_art3d.py
This PR is targeted to resolve issue [#23155](https://github.com/matplotlib/matplotlib/issues/23155) by maintain offset order for indexing purpose. And z-ordered offset will only be applied during rendering peroid.
- [N/A] Release notes conform with …
> Make Path3DCollection store indexed offset, and only apply z-ordered offset during draw

- lib/mpl_toolkits/axisartist/tests/test_floating_axes.py
Subplot has been subsumed into Axes; use add_subplot(axes_class=...) instead of manually adding axes to figures; inline some variables; rely on the ability to index multiple axises at once.
> Modernize a bit floating_axes tests.

- lib/mpl_toolkits/axes_grid1/anchored_artists.py
- lib/mpl_toolkits/axes_grid1/axes_divider.py
- lib/mpl_toolkits/axes_grid1/axes_grid.py
- lib/mpl_toolkits/axes_grid1/axes_size.py
- lib/mpl_toolkits/axes_grid1/inset_locator.py
- lib/mpl_toolkits/axisartist/axisline_style.py
- lib/mpl_toolkits/axisartist/grid_finder.py
- lib/mpl_toolkits/mplot3d/art3d.py
- lib/mpl_toolkits/mplot3d/axes3d.py
> Doc: improve spelling and grammar

- lib/matplotlib/contour.py
It may be that imin is never assigned. All other variables that are in the same if-clause have default values, so an option is to remove all those if we are sure that they will always be assigned a value. But probably safer to provide a default value for imin.
> Fix potential issue in contour

- lib/matplotlib/legend_handler.py
> MNT: remove unused arguments to private methods and minor doc fixes

- lib/matplotlib/animation.py
- lib/matplotlib/tests/test_animation.py
This fixes issues with encoding that do not support transparency and when the
Figure facecolor is transparent.
Closes #19040
I'm not sure how to test this as it is a visual thing is h254 encoded output. 
> FIX: pre-composite animation frames to white background

- doc/api/next_api_changes/removals/XXXXX-AL.rst
- lib/matplotlib/backends/backend_template.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_backend_template.py
See comment in pyplot.py explaining the change, and the associated tests.
I chose to directly break backcompat on backend_template (removing the global show) as that backend essentially serves as documentation of how to define a backend, so it seems better to directly showcase the encouraged approach.
See #24524.
> Fix testing of whether backends use the new pyplot_show API.

- lib/matplotlib/patches.py
- lib/matplotlib/path.py
- When a Path ends with a CLOSEPOLY, it is not necessary to put a LINETO to the closing position before it (in fact that can result in an incorrect line join at that position), and the xy position associated with the CLOSEPOLY can just be (0, 0), as it is irrelevant.
- For defining the codes arrays, for short paths (such as the patch shapes here), one can just use list unpacking for shorter definitions.
- Rename the _path and _fillable lists in ArrowStyle to plural names.
- Rely on the default tolerance of
split_bezier_intersecting_with_closedpath (which is 0.01) rather than
re-specifying the same magic value everywhere.
- Remove inapplicable comment re: make_compound_path_from_polys (which
only applies to polygons all of with the same number of sides, which
is not the case when clipping …
> Simplify some patches path definitions.

- doc/api/prev_api_changes/api_changes_3.6.0/removals.rst
- lib/mpl_toolkits/axes_grid1/parasite_axes.py
update_viewlim as an independent method was deprecated in da2f77a and
has since then been removed.  We could just inline _update_viewlim into
apply_aspect, but transforming it into a callback on
xlim_changed/ylim_changed helps moving towards the removal of
ParasiteAxes as a separate class and its replacement by standard (child)
axes with some extra attributes/callbacks set.
> Transform ParasiteAxesBase._update_viewlim into standard callback.

- doc/api/next_api_changes/behavior/24132-GL.rst
- lib/matplotlib/colors.py
- lib/matplotlib/tests/test_colorbar.py
- lib/matplotlib/tests/test_colors.py
This updates `CenteredNorm` to be consistent between all setting/getting of `vcenter`, `halfrange`, `vmin`, and `vmax`. The norm is defined by `vcenter` and `halfrange`, and `vmin`/`vmax` are adjusted accordingly.
Currently, if we change the center of the norm, the halfrange also gets updated based on the distance away from the previous `vmin`/`vmax` values. This "feature" is hard to maintain in this refactor, so I'm going to propose that this should be changed to not modify `halfrange` (i.e. if I update `vcenter` I just pan the center limit and keep the linear scaling out from the center fixed). I'm not sure how easy it would be to deprecate, so I think this needs some discussion and should not be backported to 3.6.
Additionally, now setting `vmin` or `vmax` is equivalent to updating the …
> CenteredNorm changes

- lib/mpl_toolkits/mplot3d/axes3d.py
> In mplot3d, fix a doc typo and autogen zaxis_inverted.

- lib/mpl_toolkits/mplot3d/tests/test_axes3d.py
> Add test for mutating input arrays #8990

- examples/style_sheets/style_sheets_reference.py
There is different number of circles in the last figure of each style, when cycling is disabled.
This causes mismatch between docstring and the actual output.
This tries to support the problem reported in #24022.
> Rework style sheet reference example to cycle props

- doc/devel/dependencies.rst
Closes #24530
@rcomer Can you confirm if this works for you?
> DOC: add note about enabling c++11 support for old gcc

- lib/matplotlib/image.py
- lib/matplotlib/tests/test_image.py
`AxesImage` can take a transform parameter. However,  `AxesImage.get_window_extent` does not respect its value and simply use the hardcoded value of `transData` (the `draw` method does respect the transform parameter).
The PR makes the `get_window_extent` method to use the return value of `get_transfrom`.
- [N/A] API changes are …
> Fix incorrect window_extent of AxesImage

- .github/workflows/codeql-analysis.yml
- setupext.py
- src/_backend_agg.cpp
- src/_backend_agg.h
- src/_backend_agg_wrapper.cpp
- src/_path.h
> Ci add codeql

- doc/api/next_api_changes/behavior/24570-GL.rst
- lib/matplotlib/offsetbox.py
- lib/matplotlib/tests/test_offsetbox.py
The bottom and top alignments were incorrectly defined before, this updates them to have the expected alignment.
closes #24386
> FIX: VPacker and HPacker bottom/top alignment

- src/_path.h
Noted this warning while recompiling which lead to the comment about isnan and since we now require C++ 11 anyway...
```
In file included from src/_path_wrapper.cpp:3:0:
src/_path_wrapper.cpp: In function ‘Py_is_sorted(_object*, _object*)’:
src/_path.h:1275:17: warning: ‘last_value’ may be used uninitialized in this function [-Wmaybe-uninitialized]
if (current_value < last_value) {
^
src/_path.h:1253:11: note: ‘last_value’ was declared here
T last_value;
^
```
The warning seems to be a false positive, but I guess there is limited harm in initializing the variable.
Edit: it seems like newer compilers do not warn for this, but I guess that they then also can detect that the initialization is a nop anyway?
> Use std::isnan and fix compiler warning

- src/_path.h
- src/_path_wrapper.cpp
We don't need a separate specialization for ints (we can rely on the compiler to inline isnan<int> as always false), and having a separate loop to find the first non-nan value isn't necessary either.
One change in behavior this causes (in this private function) is that a fully nan input is considered as being sorted, but this is consistent with empty inputs being considered sorted too, and also OK with the actual use of the function (determine whether to go through a fast path in drawing lines -- fully nan lines are not drawn anyways).
followup to #24575, which I unfortunately have to slightly revert (going back to `x != x`) due to the lack of `isnan(IntegralValue)` on MSVC (https://stackoverflow.com/questions/61646166/how-to-resolve-fpclassify-ambiguous-call-to-overloaded-function), even …
> Simplify implementation of _is_sorted.

- .circleci/config.yml
- .github/workflows/cibuildsdist.yml
- .github/workflows/cibuildwheel.yml
- .github/workflows/circleci.yml
- .github/workflows/clean_pr.yml
- .github/workflows/conflictcheck.yml
- .github/workflows/nightlies.yml
- .github/workflows/pr_welcome.yml
- .github/workflows/reviewdog.yml
- .github/workflows/tests.yml
While everything we do is basically public, there's no reason to give the tokens on these jobs full permissions. (Note, once a single item is added, all other permissions are disabled.)
Also update the CircleCI check to the action's latest recommended jobs.
- [n/a] API changes are marked with a `.. versionchanged::` directive in …
> Add explicit permissions to GitHub Actions

- doc/api/next_api_changes/deprecations/24577-AL.rst
- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
- lib/mpl_toolkits/mplot3d/axes3d.py
I chose to use "labels" as kwarg name (previously it was "labels" for Axes.set_x/yticklabels, but ticklabels for Axis.set_ticklabels), because this avoids a deprecation on the more commonly used (I think) Axes method, for consistency with Axis.set_ticks, and also because it is shorter.
> Fold _set_ticklabels into set_ticklabels.

- lib/matplotlib/rcsetup.py
- lib/matplotlib/tests/test_rcparams.py
Partially closes - #22338
Gracefully fail the string validator when tuple values are provided to rcParams. Addresses the first part of the issue.
> Fix: Gracefully fail the string validator for tuple inputs

- examples/axes_grid1/demo_axes_grid.py
Get rid of the individual example functions, as they are not really independent from one another anyways (given that they use absolute subplot positioning onto the main figure).  This also allows not having to reload the sample data in each function, and thus concentrate more on showcasing the ImageGrid functionality.
Group some kwargs to ImageGrid in a single line; e.g. the cbar arguments clearly logically belong together.
Inspired by the point about example length at https://discourse.matplotlib.org/t/new-approach-to-matplotlib-example-galleries/23359.
> Shorten demo_axes_grid example.

- .appveyor.yml
We rarely need them, and if so, then there's the cibuildwheel job on GitHub Actions that can be enabled _where necessary_ (and matches what actually goes on PyPI.) We also create nightly wheel snapshots from there already, so there's even less use for the AppVeyor wheels.
- [n/a] API changes are marked with a `.. …
> ci: Stop building wheels on AppVeyor

- .circleci/config.yml
I'm quite sure that this helps with https://github.com/matplotlib/matplotlib/issues/22176#issuecomment-1335738111
Still not good enough to solve the whole issue, but at least useable now...
> Check for errors/warnings on failed doc-builds

- lib/matplotlib/backends/backend_gtk4.py
closes #24602
We do not currently test gtk4 on CI (see #22389)
> FIX: do not use deprecated API in gtk4 backend

- doc/users/next_whats_new/rgba_pcolormesh.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/collections.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_collections.py
Allow a user to set the array values to explicit colors with RGB(A) values in the 3rd dimension. We already use `mcolors.to_rgba()` to set the facecolors and that will do the RGB(A) handling for us as long as we use 3D arrays. i.e. we can't handle `(h*w, 4)` flattened arrays with colors.
closes #4277
closes #24418
closes #22236 (separate commit to handle pcolorfast in case we want this as a separate PR)
> ENH: Allow RGB(A) arrays for pcolormesh

- doc/api/next_api_changes/removals/24624-AL.rst
- lib/matplotlib/patches.py
(Note that the 3.6 kwonlyification of mutation_scale is subsumed by the removal of bbox_transmuter.)
> Expire FancyBboxPatch deprecations.

- doc/conf.py
This may happen if Python is installed on C: and Matplotlib is installed on some other drive. As the point of this extension is to create GitHub links for Matplotlib *only*, we should ignore all paths that cannot be relativized to it.
Fixes #24574
- [n/a] API changes are marked with a `.. versionchanged::` directive in the …
> DOC: Don't try to link paths that are on a different drive

- lib/matplotlib/backends/backend_gtk4.py
Merge pull request #24606 from tacaswell/fix_gtk_closevent
FIX: do not use deprecated API in gtk4 backend
(cherry picked from commit 0aac9f17b9373f66c709f436149568bda69595b3)
> Backport PR #24606: FIX: do not use deprecated API in gtk4 backend

- lib/matplotlib/gridspec.py
- lib/matplotlib/tests/test_figure.py
`plt.subplot(1, 2, 0.5)` raises `ValueError: num must be 1 <= num <= 2, not 0.5`, which is not so useful. 
This PR changes it to report `Subplot specifier must be an integer, not 0.5`
- [N/A] …
> Improve error message for gridspec when the index is not an integer. 

- lib/matplotlib/patches.py
Making each edge fit on a single line seems better to grasp the whole definition at once and justifies squeezing the definitions a bit.
> Shorten the definition of sawtooth boxstyle.

- .appveyor.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/tests.yml
- lib/matplotlib/tests/test_triangulation.py
- lib/matplotlib/tri/_triangulation.py
- pyproject.toml
- setupext.py
- src/tri/_tri.cpp
- src/tri/_tri.h
- src/tri/_tri_wrapper.cpp
This is a `pybind11` wrapping of the `_tri` module. It is taken from the `pybind11` proof of concept (#23787) with some of @anntzer's extra comments addressed. Also see `pybind` transition plan #23846.
Worthy of note for future PRs that wrap C/C++ code using `pybind11` is how I have chosen to deal with passing `None` in lieu of NumPy arrays from Python to C++ (i.e. when the array is optional). These are auto converted to arrays using the target `dtype`. So for float and bool arrays this is fine but it doesn't work for integer arrays
```python
>>> np.array(None, dtype=int)
File "<stdin>", line 1, in <module>
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```
Hence passing from a Python `Triangulation` to a …
> Use pybind11 for tri module

- lib/matplotlib/font_manager.py
Hi! 👋 
I am gratefully making use of MPL's font management code for our text rendering in [PyGfx](https://github.com/pygfx/pygfx). While I was examining the code, I found what I think is a bug. 
The `isfile()` test is applied on the relative pathname and will thus always fail. This PR should fix that. I would expect that it should also test for the extension, but I'm not 100% sure so I did not add this yet.
Diving a bit deeper, this bug has likely gone unnoticed because the code to detect fonts follows two paths on Windows:
* It checks the registry for known installed fonts in a small set of predefined directories.
* It detects font files *in these same directories* using `os.listdir` or `os.walk`.
Why are these two paths followed? I can see how the second route can find fonts that are …
> Fix that font files never pass the test on Win

- examples/misc/custom_projection.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/projections/geo.py
- lib/matplotlib/projections/polar.py
_init_axis is called only in the Axes constructor, where it is followed by a call to clear, which itself already calls _update_transScale (which is needed to take into account the axis scales that get set in it).  So _init_axis doesn't need to call _update_transScale itself.  Removing it avoids showcasing a private method in the custom_projection demo, and helps moving towards a system where updating an axis scale directly invalidates whatever is necessary (e.g. via a TransformWrapper) instead of requiring manual invalidation calls (i.e. _update_transScale).
> Remove unneeded _update_transScale calls in _init_axis.

- doc/users/explain/interactive_guide.rst
Addresses https://github.com/matplotlib/matplotlib/issues/24632 by removing "above" wording from the docs.
> Removed 'above' wording from Input hook integration docs (#24632)

- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_figure.py
Warn the user with a `UserWarning` when a figure's layout changes from 'constrained' or 'compressed' to 'tight.'
Addresses #24387 
> BUG: Warn when an existing layout manager changes to tight layout

- lib/matplotlib/tests/test_transforms.py
- lib/matplotlib/transforms.py
Move _init() and _set() into set().
_init was split out in 5478183 to improve the pickling of TransformWrappers but was made unnecessary in 08387d8 following improvements in pickling in recent Pythons.  _set and set can also easily be combined.
Make input_dims, output_dims straight properties similarly to is_affine & friends; and improve the error message for mismatched dimensions (to indicate the wrong values).
> Small TransformWrapper cleanups.

- lib/matplotlib/colorbar.py
... instead of going through an intermediate Colorbar._set_scale. (Admittedly _set_axes_scale is a more recent addition.)
Also delete the now unused Colorbar.__scale (if we need it again it shouldn't be too onerous to put it back).
> Directly call _long_axis()._set_axes_scale in Colorbar.

- doc/devel/testing.rst
Clarify that `style='mpl20'` and `remove_text=True` are preferred in image comparison tests.
> Doc: clarify preferred image comparison test settings

- doc/api/next_api_changes/deprecations/24664-OG.rst
- lib/matplotlib/offsetbox.py
This shows up in the documentation (although not documented). Shouldn't really need to be there.
> Deprecate offsetbox.bbox_artist

- lib/matplotlib/tests/test_axes.py
Until we have proper GUI tests, this is the only way to test it (AFAIK).
Edit: rebased to get better coverage report.
> Test scroll zoom bbox update

- lib/mpl_toolkits/axes_grid1/parasite_axes.py
- lib/mpl_toolkits/axes_grid1/tests/test_axes_grid1.py
Each Artist keeps a reference to `Axes._children.remove` as `art._remove_method`.  If we replace the `_children` instance on the Axes with a different list instance the Artists will not be updated and their remove method will refer to the wrong list.  This will cause subsequent failures on the next draw because on remove we reset the `art.axes` and `art.figure` to None.
xref https://discourse.matplotlib.org/t/host-subplot-and-artist-remove/23374
> FIX: do not replace the Axes._children list object

- lib/mpl_toolkits/axes_grid1/parasite_axes.py
- lib/mpl_toolkits/tests/test_axes_grid1.py
Manual backport of #24677 due to conflicts, which were just additional tests in main from #23861, so simply removed these.
> Backport PR #24677 on branch v3.6.x (FIX: do not replace the Axes._children list object)

- lib/mpl_toolkits/axes_grid1/tests/test_axes_grid1.py
- lib/mpl_toolkits/mplot3d/tests/test_axes3d.py
- lib/mpl_toolkits/mplot3d/tests/test_legend3d.py
The long term plan is that all test images should use `style='mpl20'` (= `style='default'). To be able to change the default of `image_comparison` to this, it makes sense to change all tests that doesn't explicitly specify style to use the current default.
This PR handles mpl_toolkits.
The comment isn't that explicit as I expect that once the default is changed, one can simply reword it to drop the style. (I do not expect many regenerated images before that happens...)
> TST: set style in mpl_toolkits to ease later transition

- tutorials/introductory/lifecycle.py
Backport of #24003
Manual backport due to conflict from one-line change in this file at #23974.
> Backport PR #24003 on branch v3.6.2-doc: Fix wording and links lifecycle tutorial

- lib/matplotlib/axes/_base.py
Backport of #24654.
Manual backport required due to simple conflict caused by the first removed line being different in main and v3.6.x, having previously been modified at #24634.
> Backport PR #24654: Don't manually invalidate cached lines in _update_transScale

- tutorials/advanced/blitting.py
- tutorials/advanced/path_tutorial.py
- tutorials/advanced/transforms_tutorial.py
- tutorials/colors/colormapnorms.py
- tutorials/colors/colormaps.py
- tutorials/intermediate/arranging_axes.py
- tutorials/intermediate/artists.py
- tutorials/intermediate/constrainedlayout_guide.py
- tutorials/intermediate/tight_layout_guide.py
- tutorials/introductory/lifecycle.py
- tutorials/introductory/pyplot.py
- tutorials/introductory/quick_start.py
- tutorials/provisional/mosaic.py
- tutorials/text/annotations.py
- tutorials/text/text_intro.py
> [Doc] Fix spelling and grammar in tutorials

- examples/misc/demo_ribbon_box.py
- examples/shapes_and_collections/collections.py
- examples/shapes_and_collections/line_collection.py
- Don't use to_rgba where not needed (as noted in https://github.com/matplotlib/matplotlib/pull/24691#issuecomment-1346706406 many examples that link to it don't really showcase its use).
- Remove duplicated text in line_collection.py, and reword a bit.
> Cleanup a few examples.

- lib/mpl_toolkits/axisartist/floating_axes.py
- lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
- lib/mpl_toolkits/axisartist/tests/test_grid_helper_curvelinear.py
grid_helper_curvelinear and floating_axes, which can both draw axes that are neither horizontal nor vertical, need to compute the derivatives of the data-coords-to-screen-coords transform (actually, of data-coords-to-data-coords-of-intermediate-horizontal/vertical-axes) to get the angles at which to draw the axes labels, ticks and ticklabels.
Factor out this calculation into a _value_and_jacobian helper.  Instead of selecting the step size as some fraction of
lat_factor/lon_factor/delta_extremes, use the square root of machine precision epsilon, which is standard and (approximately) optimal for non-centered numerical differentiation (see e.g.
scipy.optimize.approx_fprime, or the Wikipedia article on numerical differentiation) -- and also happens to avoid introducing an extra paremeter …
> Factor out & improve accuracy of derivatives calculations in axisartist.

- doc/api/next_api_changes/development/24710-AL.rst
- doc/devel/min_dep_policy.rst
- lib/matplotlib/backends/backend_qt.py
- lib/matplotlib/backends/backend_qtagg.py
- lib/matplotlib/backends/backend_qtcairo.py
- lib/matplotlib/backends/qt_compat.py
... and update GUI minver policy.
Closes #24693.
> Drop support for Qt<5.10.

- lib/matplotlib/projections/polar.py
The Locator `refresh` method was deprecated in 3.3 and removed in 3.5.
But this subclass was apparently missed in the removal process.
As such, this method will raise if called, thus I do not personally
think it requires a separate deprecation period or even api note (though
willing to do so if others disagree, of course)
- [N/A] Release notes conform with …
> Remove refresh function from polar ThetaLocator

- lib/matplotlib/artist.py
- lib/matplotlib/tests/test_artist.py
This un-breaks astropy which added additional inputs to custom draw methods.  Suspect that they are not the only ones.
> FIX: be more forgiving in default draw wrapper

- lib/matplotlib/offsetbox.py
- lib/matplotlib/tests/test_offsetbox.py
> Offsetbox default arguments

- .circleci/config.yml
- .circleci/fetch_doc_logs.py
- .github/workflows/circleci.yml
This posts the warnings and deprecations from the doc builds as artifacts, then fetches them from the GitHub Action for CircleCI posting, and posts them as commit checks.
It also removes the URL check that I added in #24579. While it can be fixed, it would still "error" when the build initially starts (because there are no artifacts) and we've lasted without it so far, so I took it out.
Now, I've found out that the `status` event only triggers for the workflow on the default branch, so the changes here won't be directly reflected until merged (and is why the URL check thing above wasn't noticed before merging). Therefore, I have pushed this change to my fork's `main` branch, then opened a PR that breaks a reST target and a deprecation in an example. You can see this posting here: …
> DOC: Post warnings as reviews on PRs

- lib/matplotlib/colorbar.py
- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_colorbar.py
Allow to pass a tuple of axes as "ax" parameter of make_axes function.
It restores functionality available in this function, before memory leak fix
(in PR: https://github.com/matplotlib/matplotlib/pull/22089 ).
> Fix: restore make_axes to accept a tuple of axes

- lib/mpl_toolkits/mplot3d/axes3d.py
This was correct earlier, but changed in 3.6 via #23409
> Correct note about aspect

- doc/_static/mpl.css
- doc/conf.py
When Graphviz is given a page size (which Sphinx does by default), it will layout the whole graph, and then scale the _entire_ thing down to fit. This means that text and lines on large diagrams are inconsistent with ones that fit.
Additionally, the default size is larger than the content width which means the browser will also scale the image down a bit. But the URL map is _not_ scaled down, so the links will appear in the wrong spot.
To fix this, set the page size in Graphviz very large, and make the diagram scrollable with CSS.
Plus a few minor tweaks to font and line sizes now that images are a consistent scale.
- [n/a] …
> Improve inheritance diagrams

- lib/mpl_toolkits/mplot3d/axes3d.py
On line 330 of
https://github.com/matplotlib/matplotlib/blob/d8bb1a52316c38434e526412c27d9c4b01960084/lib/mpl_toolkits/mplot3d/axes3d.py#L327-L332
`super().set_aspect` calls `self.set_adjustable`
https://github.com/matplotlib/matplotlib/blob/d8bb1a52316c38434e526412c27d9c4b01960084/lib/matplotlib/axes/_base.py#L1744-L1746
which in turn calls `_api.check_in_list` and sets `self._adjustable`.
https://github.com/matplotlib/matplotlib/blob/d8bb1a52316c38434e526412c27d9c4b01960084/lib/matplotlib/axes/_base.py#L1796-L1811
It ought to be safe to remove the extra validation code.
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#build …
> Minor redundancy cleanup of code which sets 3D aspect 3D

- lib/matplotlib/backends/backend_webagg.py
Use `asyncio.get_running_loop()` to check if a loop is already running. Only try to start a new one when there is no running loop.
Fixes #24119 …
> don't try to start a new event loop in WebAgg when in an ipykernel

- lib/matplotlib/colorbar.py
- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_colorbar.py
Follow on to #24408
Accept anything that passes `np.iterable`
> MNT: make fig.colorbar(..., ax=INPUT) even more forgiving

- lib/matplotlib/dates.py
- lib/matplotlib/tests/test_dates.py
Related to https://github.com/matplotlib/matplotlib/pull/24732#issuecomment-1352981155
Now, `date2num` does not strip any mask information.
> Support masked dates

- doc/api/next_api_changes/deprecations/19763-ES.rst
- lib/matplotlib/tests/test_widgets.py
- lib/matplotlib/widgets.py
This can be all handled in the mouse move event handler instead, and prevents triggering extra draws in nbAgg.
Fixes #19633.
Additionally, mark access to said event handlers as deprecated.
> Remove visibility changes in draw for *Cursor widgets

- lib/matplotlib/ticker.py
Doc string is not accessible as it is placed in `__init__` instead of class.
> MAINT: Move docstring of `LogLocator` to class

- lib/matplotlib/backends/backend_cairo.py
They are unused since 15c39a3.
> Remove unused dicts from backend_cairo.

- lib/matplotlib/lines.py
The _contains attribute is never accessed anywhere in the library (since the removal of get/set_contains).  Note that this patch intentionally doesn't try to disentangle the much more complex interplay between set_picker and set_pickradius (#19039)...
> Don't set the never-used Line2D._contains in set_picker.

- tutorials/provisional/mosaic.py
A small tweak to the text of the `subplot_mosaic` tutorial, as the `height_ratios`/`width_ratios` example no longer (since #23191) uses the `gridspec_kw` keyword.
> DOC: `subplot_mosaic` tutorial - clarify ratios keywords used directly

- examples/animation/strip_chart.py
With numpy 1.24 we are ending up with the y-data being passed to the line that looked like
```
[0, 0.0, 0.0, 0.0, 0.0, array([0.75523994])]
```
which was then causing issues when we went to convert that list to an array.  I did not track down if this is a change in the behavior of `np.random.rand` or in how picky the list->array casting logic is.
For reasons that are very unclear to me this also unbreaks the unchained example when building the docs which suggests to me that the examples are not as isolated as we think (I could not get the unchained demo to fail outside of the docs build which also suggests some state leakage between them).
> DOC: fix strip_chart example with numpy 1.24
