doc/api/next_api_changes/deprecations/24538-OG.rst
lib/matplotlib/legend.py
lib/matplotlib/legend_handler.py
lib/matplotlib/patches.py
lib/matplotlib/tests/test_legend.py
lib/mpl_toolkits/mplot3d/tests/test_legend3d.py

Closes #20639
I'm not 100% sure about the documented arguments in `legend_handlers`, so please check those carefully.

[Doc] Document legend_handles and legend_handlers

---

.github/workflows/cibuildwheel.yml
doc/api/next_api_changes/development/24724-ES.rst

This causes the MSVC runtime to be bundled, which enables importing Matplotlib on systems that do not have it installed.
Fixes #24704.

Run delvewheel on Windows for wheels

---

examples/animation/bayes_update.py
examples/animation/strip_chart.py

Passing 1 means we get a 1D array with a single element, but passing nothing means a 0D array, aka a single float.
Also reverts #24774 as it should be unnecessary.
- [n/a] Release notes conform …

Fix random generation of single floats

---

tutorials/intermediate/artists.py

The example /gallery/pyplots/dollar_ticks is included into the artists tutorial. #24054 Moved that example and added a `.. redirect-from::` directive. This was then duplicated by the include.
This PR fixes the issue by moving the include start point after the redirect.
Closes #24058.

DOC: Fix duplicate redirect

---

lib/matplotlib/ticker.py
lib/matplotlib/transforms.py

Simplified a bit of code related to masked arrays.
* ~`basic_units`: already converted to non-masked a few lines up~
* `ticker`: may just as well use the MaskedConstant class (clearer, only a single check)
* `MaskedArray` is a subclass of `nparray`
(Was about to change many `isinstance(.., MaskedArray)` to `is_masked`, but the time for `is_masked` is much higher compared to `isinstance()`, so while it probably will be beneficial in the few cases where a `MaskedArray` object does not have any masked content, this seems a bit too exotic. One may consider the opposite though, replace `is_masked` with `isinstance`.)

MNT: Simplify code related to masked arrays

---

lib/matplotlib/widgets.py

The return type is a list, not a tuple, adjust the docstring to match
implementation. …

Correct docstring of CheckButtons.get_status

---

lib/matplotlib/widgets.py

Small correction to a docstring to match implementation.
The call is actually made with a tuple (vmin, vmax).
Somebody expecting a numpy array may be surprised to find it is not
actually an array. …

Correct docstring of RangeSlider.on_changed

---

lib/matplotlib/collections.py
lib/matplotlib/streamplot.py

zorder is a float value, not an int (though _most_ places are integers
for simplicity) …

Correct type in docstring of zorder for streamplot and LineCollection

---

lib/matplotlib/collections.py
lib/matplotlib/tests/test_collections.py

`scatter` allows using masked arrays as data and it also respects it by not plotting the masked points (#24545 , #24732 , #24733). But, if the offsets are updated using `set_offsets` and the input data is a masked array, the mask information is lost in `set_offsets` and the new plot contains all the points. A quick example:
```python
x = np.ma.array([1, 2, 3, 4, 5], mask=[0, 0, 1, 1, 0])
y = np.arange(1, 6)
scat = ax.scatter(x, y)
x = x/ 2
scat.set_offsets(np.ma.column_stack([x, y]))
ax.set_xlim(0, 6)
plt.show()
```
Current behaviour:
Proposed behaviour:
This is a small effort in lines with #24733 .
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should …

Allow using masked in `set_offsets`

---

lib/matplotlib/widgets.py

Fix deprecations of *Cursor widget event handlers

---

doc/api/index.rst
doc/api/text_api.rst
doc/api/textpath_api.rst
examples/lines_bars_and_markers/multivariate_marker_plot.py
examples/misc/logos2.py
examples/text_labels_and_annotations/demo_text_path.py
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_svg.py
lib/matplotlib/markers.py
lib/matplotlib/text.py
lib/matplotlib/textpath.py
lib/mpl_toolkits/axes_grid1/anchored_artists.py

The textpath module was created in 2009, but the status has
been a bit vague with many examples and exisiting code found
on the internet importing from text instead.
In this PR everything is changed to point at text, although textpath
is still available for backwards compatibility.
See discussion in https://github.com/matplotlib/matplotlib/pull/23565#discussion_r939468812
Also a bit of cleanup of related documentation.
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst …

Soft deprecate the textpath module (import from text instead)

---

lib/matplotlib/axes/_axes.py

We use `_api.check_in_list` in the method body, so arbitrary strings are
not accetable and will raise if it is not precisely "vertical" or
"horizontal".
This brings the docstring in line with this behavior.
Many other places which have an orientation kwarg are similarly
documented.
- [n/a] API changes are marked with a `.. …

Axes.stem docstring document orientation as literals

---

doc/api/next_api_changes/deprecations/24806-KS.rst
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

This argument is a holdover from seemingly a debugging print statement
that has long since been removed.
It is not used internally, and was passed entirely different things in
the two places it was called (once in tests, once in library code).
- no docstring to begin with, not sure its worth adding for just an already unused argument being deprecated

Deprecate 'x' argument for widgets.TextBox.begin_typing

---

doc/_templates/autosummary_class_only.rst
doc/api/axes_api.rst
lib/matplotlib/axes/_axes.py

- Move the Axes class documentation to a sub-page. The constructor is quite lengthy and not needed by most users.
- Add an introductory sentence to set the context for the subsequent listing and structure of the Axes methods.
Note: I've removed the inheritance diagram, because it does not contain much relevant information.
The inheritance from `_AxesBase` is shown in the class docstring as well (and is not of much use since the private `_AxesBase` does not have generated documentation. The only additional information is that it originally inherits from `Artist`, which I've now included as a sentence in the docstring.

Improve matplotlib.axes documentation

---

doc/_static/mpl.css
doc/users/explain/event_handling.rst

The existing table is too wide, and overflow is clipped, so that not all toolkits are visible.
Fixes (partially?) #24741
I also changed `Nothing` to `*nothing*` to make it clearer and added a `*nothing*` to the macosx table for <kbd>AltGr</kbd>.

DOC: Change event handling table into a tab set

---

lib/matplotlib/texmanager.py

This PR is a fix for issue #23779. I decided to try implementing the first suggested solution: to use a nested 2-letter 4-level folder hierarchy. This addresses the problem of putting too many files in a single directory, but still has unbounded space.

Implement nested four-level TeX cache

---

examples/animation/multiple_axes.py
lib/matplotlib/lines.py
lib/matplotlib/tests/test_lines.py
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py
lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/mplot3d/axis3d.py
lib/mpl_toolkits/mplot3d/tests/test_axes3d.py

When creating a Line2D, x/y data is required to be a sequence. This is not enforced when modifying the data, or with Line3D.
Closes #22308

Enforce that Line data modifications are sequences

---

doc/api/next_api_changes/deprecations/24465-AL.rst
lib/matplotlib/offsetbox.py
lib/matplotlib/tests/test_offsetbox.py
lib/mpl_toolkits/axes_grid1/inset_locator.py

Passing a single bbox instead of (xdescent, ydescent, width, height) separately is easier to follow (see e.g. the changes in VPacker and HPacker, which no longer have to repeatedly pack/unpack whd_list), and avoids having to figure out e.g. the sign of the descents and whether width/height includes the descents, for example.
Currently get_offset keeps a backcompatible signature (we *could* consider killing the old signature but let's not do that for now), and _get_bbox_and_child_offsets is private because I *may* want to later also change the convention to make offsets relative to the bbox (0, 0) point rather than the bbox lower-left corner.

Reparametrize offsetbox calculations in terms of bboxes.

---

lib/matplotlib/legend.py

removed line casting handles to legend b/c  in the line above, the handles are set to a list that was created right before the loop. 
Please merge after #24759 so it won't need to be rebased.

removed casting handles to list in legend

---

lib/matplotlib/legend.py

missed that version added was missing a space in #24759 so it's not rendering right currently

space in version added for reverse in legend

---

lib/matplotlib/animation.py

`cleanup` is removed (never existed? cannot find when it was removed...).
Not sure that the edited comment is actually true, but at least it is no longer obviously incorrect.

Fix incorrect method in doc

---

.github/workflows/tests.yml

Pandas builds at 3:27 and we build at 3:47, but their wheels take nearly 2 hours to build, so delay ours to avoid missing wheels.
Fixes #24815
- [n/a] Release notes conform with instructions in …

Delay nightly wheel builds by 2 hours

---

doc/api/next_api_changes/behavior/24829-AL.rst
lib/matplotlib/collections.py
lib/matplotlib/tests/test_collections.py

This can be done now that the previously existing allowance for `A` having the wrong shape but right number of elements has been removed.
Also, raising ValueError in all cases is more consistent (https://github.com/matplotlib/matplotlib/pull/24356#discussion_r1013429346).

Simplify shape-checking in QuadMesh.set_array.

---

lib/matplotlib/axes/_axes.py

Inspired by https://github.com/matplotlib/matplotlib/pull/22314/files#r793095283
This was the location where I think it made a difference. For example, `height = top - bottom` is quite a bit clearer than `height = m - bottom`.

[MNT] Improve variable naming in bar

---

.circleci/config.yml
doc/api/next_api_changes/behavior/24131-OG.rst
doc/api/next_api_changes/deprecations/24131-OG.rst
doc/missing-references.json
examples/animation/animate_decay.py
examples/animation/rain.py
examples/animation/strip_chart.py
examples/animation/unchained.py
lib/matplotlib/animation.py
lib/matplotlib/tests/test_animation.py

Not sure if the deprecation warning could actually be triggered without setting anim.save_count after creating the animation. Anyway, it's been around from 2.2 so I think this is OK.
The Python bug mentioned seems to have been fixed in 3.8(?): https://github.com/python/cpython/issues/74722
Privatized the save_count attribute as well as the `repeat` attribute. I cannot really see a use case for changing these after creating the animation.

Deprecate attributes and expire deprecation in animation

---

examples/event_handling/resample.py
examples/images_contours_and_fields/contour_corner_mask.py
examples/images_contours_and_fields/image_annotated_heatmap.py
examples/lines_bars_and_markers/eventplot_demo.py
examples/lines_bars_and_markers/filled_step.py
examples/misc/table_demo.py
examples/pie_and_polar_charts/pie_and_donut_labels.py
examples/scales/asinh_demo.py
examples/specialty_plots/topographic_hillshading.py
examples/subplots_axes_and_figures/axes_margins.py
examples/text_labels_and_annotations/font_table.py
examples/text_labels_and_annotations/legend_demo.py
examples/ticks/custom_ticker1.py
examples/units/basic_units.py
examples/user_interfaces/embedding_webagg_sgskip.py
examples/user_interfaces/fourier_demo_wx_sgskip.py
examples/user_interfaces/svg_histogram_sgskip.py
examples/user_interfaces/svg_tooltip_sgskip.py
examples/user_interfaces/wxcursor_demo_sgskip.py

Just some minor modernization.

DOC: Replace .format by f-strings in examples

---

doc/api/projections/geo.rst
doc/api/projections/polar.rst
doc/api/projections_api.rst

Instead of having all the API reference crowded on the Projections page, create new pages for polar/geo projection API.

Move geo/polar projections to their own pages

---

lib/matplotlib/collections.py
lib/matplotlib/tests/test_collections.py

The type check and mapping for strings is also done at the start of `_get_dash_pattern`:
https://github.com/matplotlib/matplotlib/blob/7c6e057148533e7a0b28154c485aeef9b6209bb5/lib/matplotlib/lines.py#L36-L37
So it's redundant here.
- [N/A] Release notes …

`Collection.set_linestyle`: remove redundant string handling

---

doc/api/next_api_changes/deprecations/24846-ES.rst
lib/matplotlib/cm.py
lib/matplotlib/tests/test_colors.py

This is the next stage of #20853.

Promote pending cm deprecations to full deprecations

---

lib/matplotlib/projections/polar.py
lib/matplotlib/tests/test_polar.py

This allows scales to be set on polar Axes where 0 is not in the valid scale limits (e.g. a log scale falls into this category). Because there is some special casing in polar radial view limits that tries to include zero all the time, I didn't want to break this, so instead I've gone for the most general check of running the interval [0, 1] through the scale's `limit_range_for_scale` method, and checking if a 0 comes out. If it doesn't, the deafult behaviour of the locator is used to set the view limits and nonsingular values.
Goes part way to fixing https://github.com/matplotlib/matplotlib/issues/24383

Allow polar scales where zero is not in valid interval

---

lib/matplotlib/projections/polar.py

Since `t` is often used for transforms in the code base, clarify a possible ambiguity here and use `theta` as a variable name instead.

Variable rename t > theta

---

lib/matplotlib/projections/polar.py

This adds a bit more context and information to the `PolarAffine` docstring.

Improve PolarAffine docstring

---

examples/event_handling/poly_editor.py
lib/mpl_toolkits/mplot3d/axes3d.py
lib/mpl_toolkits/mplot3d/proj3d.py
lib/mpl_toolkits/mplot3d/tests/test_axes3d.py

The version in poly_editor is relatively simple because it only supports array inputs and doesn't vectorize over any input.
The version in proj3d is private so the API can be changed, but it needs (currently) to at least support non-array inputs and to vectorize over `p`.
- Rename the parameters to make the difference between the "segment ends" (`s0, s1`) and the "point" (`p`) parameters clearer.
- Switch `p` to support (N, ndim) inputs instead of (ndim, N) (consistently with most other APIs); adjust test_lines_dists accordingly.
- Use vectorized ops everywhere, which also caught the fact that previously, entries beyond the third in (what was) `p1, p2` would be silently ignored (because access was via `p1[0]`, `p1[1]`, `p2[0]`, `p2[1]`).  Instead now the vectorized version naturally …

Simplify/robustify segment-point distance calculation.

---

lib/mpl_toolkits/mplot3d/axes3d.py

Closes #24842
I am not sure if anything else is required here. It seems like explicitly listing the six positional arguments is the sensible thing to do. It was previously possible to pass more arguments, that option was 
removed in #23076 (and deprecated earlier), although the consequence here was probably not handled/foreseen.

Fix argument checking in `Axes3D.quiver`

---

doc/api/next_api_changes/deprecations/19763-ES.rst
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

By implementing `_onmove` in a similar manner to `Cursor`. Also, deprecate the related `needclear` attribute in both widgets.
Followup to #19763.

Fix toggling of MultiCursor.{horizOn,vertOn}

---

doc/users/explain/fonts.rst

Note that the ttconv link was linking to an unrelated library also called ttconv.  I don't know if the ttconv we vendor actually still has any significant online presence...

Copy-edit fonts docs.

---

lib/matplotlib/projections/polar.py

Add parameter doc to PolarTransform

---

doc/api/next_api_changes/behavior/24870-AL.rst
lib/matplotlib/contour.py
lib/matplotlib/tests/test_contour.py
lib/matplotlib/tri/_tricontour.py

Closes #24321: for bool inputs, contour now defaults to levels=[.5] and contourf to levels=[0, .5, 1].

Better default bool contour levels.

---

examples/lines_bars_and_markers/marker_reference.py
lib/matplotlib/markers.py
lib/matplotlib/tests/test_lines.py

... which it really is.  Closes #23849.
Also remove a bunch of unnecessary plt.show() from the marker reference example, to make it more convenient to run from the command line.

Document "." as a filled marker.

---

doc/users/next_whats_new/documentation.rst

As [discussed on gitter](https://gitter.im/matplotlib/matplotlib?at=6397a6b30c89e71a3377677c), added a what's new entry for large documentation contributions. Very likely missed some so please add!

add new & improved doc notices to what's new

---

doc/sphinxext/redirect_from.py

`otherdata` is a dict
Given that this is a helper sphinx extension that we do not ship, I do no think we need a test (but this error existing made debugging a build issues easy!).

FIX: error in formatting in error string in redirect extension

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backend_tools.py

It doesn't add much over the button state and the button tooltip (note that the state isn't even displayed when the cursor is over an axes, as the coordinates take precedence), and collides with other possible end-user customizations of the toolbar (currently, end-users can override the coordinate string via format_coord, but not the navigate mode string).
Closes #24867.

Skip displaying pan/zoom navigate mode in toolbar.

---

doc/api/next_api_changes/deprecations/24864-AL.rst
examples/lines_bars_and_markers/span_regions.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/collections.py

It doesn't warrant a separate class; also, directly doing the unit conversion in broken_barh is actually easier (one doesn't need to go through _convert_dx, instead we directly move to using xmin/xmax).
Closes #15973 (... by making the user use fill_between instead).
See also #24827 and #4897 (where I assume the first item refers to BrokenBarHCollection, as there's no BarHCollection).
I milestoned as 3.7 due to the deprecation, but can just rewrite it as a 3.8 deprecation as well.

Deprecate BrokenBarHCollection.

---

lib/matplotlib/artist.py

Closes #24890 
How to make a clipping bbox was a little mysterious, so add a short description of how the default clipbbox is made.  

DOC: explain clipbox a bit better

---

doc/devel/index.rst

Changed the link for the "write documentation" button on 
from https://matplotlib.org/devdocs/devel/contributing.html#contributing-documentation to https://matplotlib.org/devdocs/devel/documenting_mpl.html  because the way I use this button is to find the "writing documentation" section (which did not notice it was in the sidebar 'til now). 
Was considering moving the "contributing-documentation" section of the guide to the "writing docs" guide as a preamble, but I also get why it may be worth having in the contributing documentation page for folks skimming it so might be worth writing up a similar overview for the "writing docs" page, possibly once we sort out guidelines https://github.com/matplotlib/matplotlib/issues/24746#issuecomment-1356499911
Alternatively since that page is so …

changed contribute docs link to writing docs

---

doc/api/next_api_changes/behavior/24889-AL.rst
lib/matplotlib/_api/__init__.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/figure.py
lib/matplotlib/image.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/ticker.py

... via a kwarg_error helper (see nargs_error for a similar design).  In particular the type of the exception thrown by AxesImage.set_extent changed, and parentheses were added to the error thrown by _process_plot_var_args.

Harmonize exceptions for unknown keyword arguments.

---

lib/matplotlib/pyplot.py

Remove provisional note from pyplot.subplot_mosaic

---

tutorials/introductory/animation_tutorial.py

The animation tutorial has a table of plotting methods and the underlying artists to illustrate what to look for in the docs. I didn't catch on review that this has patches.Circle as the first entry. 
Since Ellipse isn't the underlying patch I change the first entry to `Axes.add_patch` b/c I like 'em all as axes methods, but I'm unsure of @chahak13 intent here. (My guess is the example started as circle and morphed to ellipse)

changed method in animation tutorial table of methods

---

doc/api/next_api_changes/deprecations/22314-AL.rst
lib/mpl_toolkits/axisartist/axislines.py

AxisArtistHelper can generate either x or y ticks/gridlines depending
on the value of self.nth_coord.  The implementation often requires
generating e.g. shape (2,) arrays such that the nth_coord column is
set to a tick position, and the 1-nth_coord column has is set to
0.  This is currently done using constructs like ``verts = [0, 0];
verts[self.nth_coord] = value`` where the mutation doesn't really help
legibility.  Instead, introduce a ``_to_xy`` helper that allows writing
``to_xy(variable=x, fixed=0)``.

Add a helper to generate xy coordinates for AxisArtistHelper.

---

lib/mpl_toolkits/axisartist/axislines.py
lib/mpl_toolkits/axisartist/floating_axes.py
lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
lib/mpl_toolkits/axisartist/tests/test_axis_artist.py

git says there has never been an AxisArtistFloating class in the codebase, so the commented code referring to it likely predates even the integration of axisartist; let's just remove it.
Also rename _helper to helper (except for rare cases there isn't much to be gained by marking local variables as "private"), and tweak some surrounding whitespace.

Remove some long-obsolete commented code in grid_helper_curvelinear.

---

doc/api/next_api_changes/deprecations/24904-AL.rst
lib/mpl_toolkits/axisartist/axislines.py

A "top y-axis" or a "left x-axis" doesn't make sense.
See https://github.com/matplotlib/matplotlib/pull/22314#issuecomment-1374427550.

Deprecate AxisArtistHelpers with inconsistent loc/nth_coord.

---

doc/api/next_api_changes/deprecations/24913-AL.rst
lib/matplotlib/transforms.py

This previously returned a copy of the bbox itself, and was completely unused; let's deprecate this for clarity ("anchoring a bbox to itself" doesn't make much sense anyways).

Deprecate Bbox.anchored() with no container.

---

.github/workflows/tests.yml
requirements/doc/doc-requirements.txt

Sphinx 6.1.2 introduces new behavior which causes python source files to
be copied into the images folder errantly.
For a more full write up refer to sphinx-doc/sphinx#11117

Pin sphinx != 6.1.2

---

lib/matplotlib/figure.py
lib/matplotlib/tests/test_constrainedlayout.py
lib/matplotlib/tests/test_tightlayout.py

Re-uses the tests from #22849, but also tests that going _back_ on works as well.
Fixes #22847

Fix toggling layout engines

---

lib/matplotlib/cbook.py
lib/mpl_toolkits/axes_grid1/inset_locator.py
lib/mpl_toolkits/mplot3d/axes3d.py

- Remove now-incorrect comment in cbook docstring (cbook now imports matplotlib at the top).
- Simplify implementation of GrouperView, now that it doesn't forward deprecated methods to the inner grouper anymore.  (followup to #24923)
- Minor tweak to BboxConnector init.
- Axes3D doesn't need to call norm_angle (which just normalizes angles to -180..+180 degrees) before computing sin/cos.

Small unrelated cleanups/style fixes.

---

tutorials/colors/colormapnorms.py

I was having some trouble building docs locally due to some bad interaction between
the ipython sphinx directive and running in a virtual environment (despite ipython being installed in the environment)
Rather than spending a large amount of time figuring out how to resolve those incompatibilities, I just removed
the directive that was causing the problem and replaced it with `code-block`  which is what we use everywhere else (that isn't a plot) anyway.
- [N/A] API changes are marked with a …

Swap ipython directives for code-block directives

---

doc/api/next_api_changes/behavior/24655-AK.rst
lib/matplotlib/font_manager.py
lib/matplotlib/tests/test_font_manager.py

* Follow-up on https://github.com/matplotlib/matplotlib/pull/24641, which introduces a bug (fonts are added regardless of their extension).
* Undoes https://github.com/matplotlib/matplotlib/pull/22909 and implements another way to fix https://github.com/matplotlib/matplotlib/issues/22859: don't scrape dirs with `list_fonts` on Windows.

Update font_manager to only use registry on Win

---

doc/sphinxext/gallery_order.py

Tweaked the gallery ordering script so that we can explicitly list sections last, in particular so that provisional can be the last section in the tutorials since it's empty (and also this allows it to stand out) and userdemo can be the last section in the gallery since it has random content.

[MNT] specify which gallery sections come last

---

examples/specialty_plots/leftventricle_bullseye.py

Fix typo in filename.
Tighten axes layout, and use relative coordinates to position colorbars instead of hardcoded absolute positions (which become wrong as soon as the figure size changes).
before
after

Cleanup bullseye plot example.

---

doc/api/next_api_changes/deprecations/24254-OG.rst
doc/api/next_api_changes/removals/24254-OG.rst
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

~Will add notes etc, but~ think about the keyword-only aspect of Selectors/Widgets. ~Also, `lineprops` is unused in RectangleSelector, but I guess I cannot really remove it?~

Expire deprecations in widgets and keyword only arguments for Selectors

---

doc/api/next_api_changes/removals/24948-ES.rst
doc/api/prev_api_changes/api_changes_3.5.0/deprecations.rst
doc/api/prev_api_changes/api_changes_3.5.0/removals.rst
doc/api/testing_api.rst
lib/matplotlib/__init__.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/matplotlib/backend_bases.py
lib/matplotlib/category.py
lib/matplotlib/legend_handler.py
lib/matplotlib/pyplot.py
lib/matplotlib/rcsetup.py
lib/matplotlib/scale.py
lib/matplotlib/testing/conftest.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_category.py
lib/matplotlib/tests/test_rcparams.py
lib/matplotlib/units.py
lib/mpl_toolkits/axes_grid1/axes_divider.py
lib/mpl_toolkits/axes_grid1/axes_grid.py

Remove remaining deprecations from 3.5

---

doc/api/next_api_changes/behavior/24912-AL.rst
lib/matplotlib/contour.py
lib/matplotlib/tests/test_contour.py

If the user explicitly passes a levels array (the default is auto-determined), let's assume that they know what they are doing.  Closes #23778.
(I *could* consider keeping the warning for now in the case where the user didn't pass `levels` but `z` is uniform throughout, as that's more likely to be a "data-exploration" case.)

Remove contour warning for "no-valid-levels".

---

doc/api/next_api_changes/removals/24948-ES.rst
doc/api/next_api_changes/removals/24965-ES.rst
lib/matplotlib/axes/_base.py
lib/matplotlib/backends/backend_webagg_core.py
lib/matplotlib/colorbar.py
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

Note that there are additional changes in widgets because we missed deprecations due to a pytest peculiarity pytest-dev/pytest#9288
Also, the `cursor` removal was already documented in #24129.

Remove additional deprecations from 3.5

---

lib/matplotlib/mpl-data/matplotlibrc

Percent signs needed to be escaped as %% in the past when using  '%' formatting to generate default matplotlibrc file. The 4 remaining double percent signs were overlooked in 5206cb011.
- [N/A] …

MNT: Fix double % signs in matplotlibrc

---

lib/matplotlib/_tight_bbox.py
lib/matplotlib/tests/test_figure.py

Fixes #24954 (I think!)  I don't claim to fully understand everything that's going on here, but it seems to me that these lines are doing the same job as
https://github.com/matplotlib/matplotlib/blob/018c5efbbec68f27cfea66ca2620702dd976d1b9/lib/matplotlib/backend_bases.py#L2356-L2357
Since `restore_bbox` gets called within the above context manager, the final result is the layout engine continues to be what was set with `fig.set_layout_engine(None)`.
- [N/A] New features are marked with a `.. versionadded::` …

FIX: adjust_bbox should not modify layout engine

---

lib/matplotlib/colors.py
lib/matplotlib/tests/test_colors.py

Since we use subtraction to compute the lookup table indices we need to cast `uint`s in addition to `float`s, so we can move the cast outside of the float block.
closes #24865 
- [N/A] Release notes conform with instructions in …

FIX: Handle uint8 indices properly for colormap lookups

---

lib/matplotlib/_fontconfig_pattern.py

Closes #24972
I do not think that it is possible to test in any other way than running with `-W all`.

Suppress pyparsing warning

---

doc/api/next_api_changes/deprecations/24990-OG.rst
lib/matplotlib/axes/_base.py
lib/matplotlib/figure.py
lib/mpl_toolkits/axes_grid1/parasite_axes.py
lib/mpl_toolkits/mplot3d/axes3d.py

Make arguments other than `renderer` keyword-only for `get_tightbbox`

---

tutorials/intermediate/constrainedlayout_guide.py

A tiny suggestion for the Constrained Layout Tutorial, as I found the "double indexing" here a little hard to parse.  Possibly it's just a matter of what I'm used to though, so others may prefer the existing version.

DOC: tweak array indexing in constrained layout tutorial

---

examples/axes_grid1/README.txt
examples/axisartist/README.txt
examples/pyplots/README.txt
examples/specialty_plots/README.txt

The headings in the example section are mostly upper case, but also a few lowercase headings::
This pr capitalizes all headings.

Capitalize headings in example Gallery

---

doc/sphinxext/gallery_order.py

Separates each gallery ordering into its own list to make it a little cleaner to find/order each gallery. Should maybe be a conf file but this was a quick proof of concept inspired by ordering being a pain in https://github.com/matplotlib/matplotlib/issues/24746#issuecomment-1396425509
ETA: I like @QuLogic's idea https://github.com/matplotlib/matplotlib/issues/24746#issuecomment-1396482343 of putting the ordering in each readme better but don't really have the time to implement that...I think it would basically be populate these lists w/ the contents of those readmes

seperate out folders in gallery ordering

---

examples/pie_and_polar_charts/pie_features.py

added small examples of labels, autopct, colors, hatch, and distance in an attempt to scaffold up to exploding example. I also kinda really like this model of documenting the plotting methods - small isolated example of each notable keyword - so if other folks do too, this could be a way to consolidate some of the examples. It's also a style I'm seeing a lot in blog posts and social media tutorials so I think it's popular. (ETA: also is how the subplot mosaic guide is written, see [24891](https://github.com/matplotlib/matplotlib/pull/24891))
Plus the section headers make the navigation really nice:
Pulled this out of #24470 to make reviewing easier, so this also documents the `hatch` keyword introduced there & therefore all the things will break until that PR is merged. Also tries to …

[Doc] expanded basic pie example

---

.github/workflows/nightlies.yml

The [last job](https://github.com/matplotlib/matplotlib/actions/runs/3964030919) failed because it was looking at a build that completed, but had failed.
Also, print out status of the chosen build, and clean up yamllint warnings.
- [n/a] API changes are marked with a `.. versionchanged::` directive in the docstring and …

ci: Only attempt to upload nightlies from successful builds

---

lib/matplotlib/widgets.py

The drawtype argument was removed in an earlier PR, but this block was not.

Remove dead code from deprecated-and-removed block

---

.github/workflows/nightlies.yml

This is needed because of the way the micromamba provisioning works, or else anything installed in the mamba environment is not found.
I also added a comment explaining it so that it won't be accidentally removed in the future (or will if that requirement is dropped.)
Now that I know you can trigger `workflow_dispatch` runs from _any_ branch, I checked this before opening this PR: https://github.com/matplotlib/matplotlib/actions/runs/3972489758
- [n/a] New …

ci: Re-add the login shell to nightlies jobs

---

doc/users/faq/howto_faq.rst

Note the double occurrence of "check" in the previous version.

Reword awkward sentence in FAQ.

---

doc/users/explain/figures.rst
doc/users/explain/index.rst
lib/matplotlib/figure.py

New short intro on Figures in Matplotlib.  I don't think this info exists except in snippets of the getting-stated guide.  Could use some more cross-references.  

DOC: figure explanation

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

Fix for pcolormesh doesn't allow shading = 'flat' in the option #24678

fix for pcolormesh doesn't allow shading = 'flat' in the option

---

doc/api/next_api_changes/behavior/25061-DS.rst
lib/matplotlib/colors.py
lib/matplotlib/tests/test_colors.py

Fixes https://github.com/matplotlib/matplotlib/issues/24283.

Ensure TwoSlopeNorm always has two slopes

---

lib/matplotlib/backends/web_backend/all_figures.html
lib/matplotlib/backends/web_backend/single_figure.html

Added a small change to the JavaScript for the WebAgg backend. The added JavaScript code will check the protocol and updated the websocket uri to `wss:` if `https:` is being used.
This is to fix an issue with matplotlib running behind a reverse proxy that adds HTTPS and secure HTTP headers like HSTS. The connection to the insecure websocket i.e. `ws:` is blocked by the browser with the message:
```
Mixed Content: The page at 'https:/<some_website>/' was loaded over HTTPS,  but attempted to connect to the insecure 
WebSocket endpoint 'ws://<some_website>/1/ws'. This request has been blocked; this endpoint must be available over WSS.
``` 
Not sure whether or not I need to update any documentation, so please let me know if I do.
Thank you

Updated WebAgg JS to check and send request over wss if using HTTPS

---

doc/sphinxext/redirect_from.py
lib/matplotlib/_afm.py
lib/matplotlib/_mathtext.py
lib/matplotlib/backends/backend_webagg_core.py
lib/matplotlib/font_manager.py

In particular f-string:
There are many reason not to use f-string in logs,
- F-strings are eager, so might be slow. So this may affect performance (we can filter before formatting).
- prevent structured logging or handler to highlight.
- Security (untrusted input can lead to DOS on formatting, https://discuss.python.org/t/safer-logging-methods-for-f-strings-and-new-style-formatting/13802)
But also % formatting in a couple of places.

MAINT: don't format logs in log call.

---

lib/matplotlib/colors.py
lib/matplotlib/tests/test_colors.py

Signal are sent for every vmin/vmax update, when autoscaling we were changing vmin/vmax to None, then updating them which would cause 4 update signals to be sent. We really don't care about the intermediate signals and only want a single one sent after all the updates are complete.
closes #25077
NOTE: The colorbar says "if not norm.scaled(): set vmin/vmax to 0, 1" which doesn't work for the LogNorm scales. Perhaps we should also change that arbitrary 0, 1 expansion. But, this at least makes sure we don't go through the `vmin=None` path here while we are actively updating the norm.
- [-] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [-] New plotting …

FIX: Only send one update signal when autoscaling norms

---

azure-pipelines.yml

cibuildwheel is on setuptools 66 and we don't set the env there, so try reverting matplotlib/matplotlib#22756.

Revert "Use system distutils instead of the setuptools copy"

---

doc/users/github_stats.rst

I've fixed the original issue/PR titles directly to prevent this from happening at next rc/final.

DOC: Fix typos in GitHub stats

---

lib/matplotlib/tests/test_ticker.py
lib/matplotlib/ticker.py

Add the new SI prefixes to ticker (-30, -27, 27, 30) according to BIPM [The International System of Units
9th edition (2019) - see Table 7. SI prefixes](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf#page=29)
If there is Documentation or Release Note needed for this, let me know.
- [N/A] API changes are …

feat: add new SI prefixes to ticker

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/figure.py

https://github.com/matplotlib/matplotlib/pull/24983#discussion_r1070586892 applied to the rest of the code base.
`_axis_map` relies on `getattr`, so will be slightly slower, but code is if nothing else more understandable this way.

Use `_axis_map` instead of `getattr` in `Axes` and `Figure`

---

doc/users/explain/figures.rst

Not sure why the original didn't work, perhaps because I need to use older `sphinx-gallery` to produce working PDF structures.
But this file has a target specified at the top, so use that instead. This fixed the PDF build for 3.7.0rc1.

DOC: Fix broken cross-reference when building PDF

---

setupext.py

This is not caught in CI, because test data is not distirbuted by default, but it is downstream. …

Fix distribution of test data

---

lib/matplotlib/figure.py
lib/matplotlib/tests/test_figure.py

This is a continuation on #22816 to make sure `savefig(..., transparent=True)` handles nested figures and axes. Also updates the test figure to include doubly-nested cases to test against.
Closes issue #22674  

[FIX]: Make inset axes transparent on savefig(..., transparent=True)

---

.flake8
doc/api/next_api_changes/development/24893-KS.rst
doc/devel/MEP/MEP08.rst
doc/devel/coding_guide.rst

As discussed on the call this week, we should consider making the style enforced line length slightly longer.
Going to 88 matches the default of black.  https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length is a nice explanation of how they landed there.
Key points from the call:
- we should keep this low enough that GH's side-by-side diff view works
- keep this small enough 2 or 3 panels can be up next to each other in an editor
- we can make it bigger in the future, but making it smaller would be rough
There are no plans to re-flow the entire code base, but new stuff could come in more relaxed.

STY: make allowed line length 9 longer to 88 from 79

---

lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/tests/test_backend_pgf.py

See https://github.com/matplotlib/matplotlib/pull/23381#issuecomment-1183758517 for motivation.  Supersedes #23381.  @painch Can you check whether this works for you?
Support for `^` is inspired from the support for `_` as implemented
in underscore.sty, but much simpler because 1) we don't care about
hyphenation, 2) we don't care about substituting a real underscore by
a rule box when the current font lacks an underscore (there's no real
way out if the font has no caret, anyways), and 3) we don't care about
the active character ending up in tex `\commands` because the character
is only made active in the context of matplotlib-provided strings, not
globally.
Note that tex_escape is still being tested by
test_minus_signs_with_tex, which explicitly checks support for unicode
minus.
----- …

Remove need to detect math mode in pgf strings

---

lib/matplotlib/widgets.py

valinit is becoming keyword-only.
It's not really clear why the warning is getting suppressed e.g. with the tk backend, though.

Correctly pass valinit as keyword in SliderTool.

---

.flake8

Update this to:
- Re-arrange some of the files into alphabetical order
- Remove some error ignores that we don't need any more
For reference I managed to 95% automate this by parsing the outptut of `flake8` into a list of ingore rules:
```python
from collections import defaultdict
with open('flake8.txt') as f:
lines = f.readlines()
lines = [l.split(': ') for l in lines]
files = [l[0].split(':')[0] for l in lines]
codes = [l[1].split(' ')[0] for l in lines]
errs = defaultdict(set)
for f, c in zip(files, codes):
errs[f].add(c)
errs = {k: list(v) for k, v in errs.items()}
for f in sorted(errs):
err_str = ', '.join(sorted(errs[f]))
print(f"{f}: {err_str}")
```

Update flake8 per-file ignores

---

lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/tests/test_backend_tk.py

Choosing to noop (rather than erroring) is consistent with other backends.
Closes #16580, closes #23809.

tk blitting to destroyed canvases should be a noop, not a segfault.

---

examples/lines_bars_and_markers/horizontal_barchart_distribution.py
examples/text_labels_and_annotations/legend_demo.py
examples/user_interfaces/mplcvd.py
examples/userdemo/simple_legend01.py
tutorials/intermediate/legend_guide.py

Since 958e329b198a9036fc121d11775815ded7c9acad the preferred keyword for controlling the number of columns in a legend is `ncols`. However,
```shell
$git grep ncol= a30c0b13386ca9469ffcfed5fa24fd21aaba49c5  # current main
```
reveals several uses of the old keyword. This pull request replaces most of them with the new recommended `ncols`, but three uses of `ncol` should remain in place:
- an old what's new entry: https://github.com/matplotlib/matplotlib/blob/a30c0b13386ca9469ffcfed5fa24fd21aaba49c5/doc/users/prev_whats_new/whats_new_0.98.4.rst#L40
- the definition of the old keyword for backwards compatibility: https://github.com/matplotlib/matplotlib/blob/a30c0b13386ca9469ffcfed5fa24fd21aaba49c5/lib/matplotlib/legend.py#L383
- a test that checks that the old keyword still works: …

Stop recommending `ncol` in legend examples

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_collections.py

Opening this as a draft for discussion.
If someone passes in a 2-D array to `.pcolormesh()` should we automatically call `.ravel()` on it? See question from @jklymak here: https://github.com/matplotlib/matplotlib/pull/24619#discussion_r1039818371 Flattening is what historically has been done, but we've been moving towards QuadMesh being a primary 2-D collection lately and could get rid of this restriction on flattening input.
The updates here are all primarily surrounding what shapes the returned arrays are from the function calls and how to compare them, so drawing hasn't changed. Also note that this would introduce a deviation between `pcolor(z2d).get_facecolors() == colors1d` which returns the flattened array, while `pcolormesh(z2d).get_facecolors() == colors2d` returns the original …

MNT: Remove auto-flattening of input data to pcolormesh

---

lib/matplotlib/axis.py

AFAICT the overlap avoidance (i.e. labelpad) has never been implemented by making a scaled-up copy of the label box...

Fix outdated comment re: _update_label_position.

---

src/path_converters.h

Getting rid of a few redundant/not required computations. Have not checked the assembly code to confirm that the compiler doesn't already optimize it away though.

Minor cleanup and optimization of Sketch

---

lib/matplotlib/tests/test_transforms.py
lib/matplotlib/transforms.py

The issue is that TransformedPath only regenerates its cache for changes to the non-affine part of the transform.  When TransformWrapper for tranScale changes from log -> linear the non-affine part of the log transform is still cached, but when the transforms are invalidated after switching to linear the invalidation only reports changing the affine part so the cache in TransformedPath escapes being updated (nulled out in this case) and when we re-draw with linear is drawing the line off screen (or at least clipped).
This change invalidates all of the parents before changing the internals of TransformWrapper before we switch it which will cause the non-affine part to be correctly recomputed the next time we need it.
closes #25124

FIX: fully invalidate TransformWrapper parents before swapping

---

tutorials/text/annotations.py

Jumping off of #25094, that an annotate can be positioned relative to an artist is mentioned in the annotate docstring but was <strike>missing from the tutorial</strike> buried in the coordinates section as a chaining annotations example. Figured a small example would make this functionality slightly more discoverable, and arrows are a good artist for this example since they're used for diagramming.

add section on annotating an artist using axes.annotate

---

lib/matplotlib/backends/backend_qt.py
lib/matplotlib/backends/qt_compat.py

The API is now the same for all qt bindings we support.

Don't special-case getSaveFileName in qt_compat anymore.

---

examples/lines_bars_and_markers/timeline.py

Just realized that https://matplotlib.org/stable/gallery/lines_bars_and_markers/timeline.html often seems to time out so that the fallback data is used. Even locally, 0.4 seems to not be enough. Increasing to 1 which at least locally seems to do the trick.
Edit: Seems to work better now https://output.circle-artifacts.com/output/job/1146acc6-be05-4922-a20e-a5622d444218/artifacts/0/doc/build/html/gallery/lines_bars_and_markers/timeline.html

Increase timeout to GitHub API

---

lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/cbook.py

Tk and Gtk reported "super" when "command" was pressed, while qt and macosx reported "cmd". Make all backends consistent by reporting "cmd" in all of them.
@Co-authored-by: Antony Lee <anntzer.lee@gmail.com>
follow-up to:  #23473 
Note the extra change to cbook, which accounts for the single key command press, where it isn't a modifier.
- [-] Has pytest style unit tests (and `pytest` passes)
- [-] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [-] New plotting related features are documented with examples.
- [-] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/` …

FIX: Correctly report command keypress on mac for Tk + Gtk

---

tutorials/intermediate/constrainedlayout_guide.py

**If** I have understood correctly, passing `None` to `set_layout_engine` essentially means "set the default layout engine" where the default is determined by what `rcParams` you have set.  Passing `"none"` will set the layout engine to either `None` or `PlaceHolderLayoutEngine`, depending what was previously set.  So I think `"none"` is the more reliable way to turn the layout engine off.
https://github.com/matplotlib/matplotlib/blob/11258883230848ad88c656786f804fd1cd3bdf6e/lib/matplotlib/figure.py#L2566-L2618

DOC: use 'none' in set_layout_engine

---

examples/event_handling/cursor_demo.py
examples/widgets/annotated_cursor.py
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

- Revert "Fix deprecations of *Cursor widget event handlers"
- Revert: Deprecate access to Cursor/MultiCursor event handlers.
- Add simulated mouse events to cursor demos
- remove calls to set_visible(False)
Closes #25107
The event handlers were deprecated for mpl 3.7 in #19763 (with correction for the deprecation notices in #24750)
This has not been released as a final matplotlib version (only the rc).
However, one of examples demonstrated subclassing these classes specifically to override these methods.
The callbacks registered internally were for the privitized version of the functions, thus the overrides did nothing.
Given that it is suggested in our docs, we determiened in #25107 that we should undeprecate these methods.
The original PR kept the calls to `set_visible(False)` in the …

Undeprecate Cursor event handlers

---

lib/matplotlib/backend_bases.py

Disconnect SubplotTool destroyer callback on tool_fig close

---

setupext.py

In my experience, mplcairo has only ever worked on macOS if imported prior to matplotlib (which means that in particular just setting the backend rcParam will not work, including via matplotlibrc), or (I have recently discovered) if using a non-local-freetype version build of ft2font.  If none of these conditions are not satisfied, various bad things happen, such as segfaults at runtime.  I realized recently the (one?) reason for this problem.  Below, I only consider the case of local-freetype builds (the only problematic case).
C-level cairo functions call FreeType for text rendering, and there are two different libfreetype libraries involved: the one statically linked into matplotlib's ft2font, and the OS-level one (which comes into play even for local-freetype builds because …

On macOS, limit symbols exported by extension modules linking FreeType.

---

lib/matplotlib/mlab.py
lib/matplotlib/tests/test_mlab.py

Simply drop the `np.abs()` on window to fix the wrong scaling factor for window with negative value. For more detail refer to https://github.com/matplotlib/matplotlib/issues/24821
**Caution**: With this fix, the behavior would change for window with complex value.
With `np.abs()` on window, it seems can handle complex value, but I don't think it's the right way to do it. As it can't fall back to real value case for complex value with zero imaginary part and negative real part (for example -1 + 0j).
Also, I didn't understand the need for complex window, so here I simply ignore the complex case. And this is consistent with the implementation of [scipy](https://github.com/scipy/scipy/blob/d9f75db82fdffef06187c9d8d2f0f5b36c7a791b/scipy/signal/_spectral_py.py#L1854-L1859).
Closes #24821 …

FIX: scaling factor for window with negative value

---

lib/matplotlib/backends/_backend_tk.py

Fixes #24820
May be worth checking if the memory leak tests can be tightened.

fix FigureCanvasTkAgg memory leak via weakrefs

---

lib/matplotlib/tests/test_image.py
src/_image_wrapper.cpp

Move it all to a single place rather than having some of it interspersed with the dtype dispatch later.
Also reorder the dtype dispatch to be consistent in the 2D and 3D cases, and remove _array from many local variable names.

Group shape/dtype validation logic in image_resample.

---

doc/api/next_api_changes/behavior/25101-AL.rst
doc/api/next_api_changes/deprecations/25101-AL.rst
lib/matplotlib/backend_bases.py

Keeping around lastevent can delay garbage collection of a torn-down axes, and can also keep around an actual GUI event object (guiEvent) associated with a long-torn down widget, which can be problematic for some GUI toolkits.
Instead, only keep track of the last inaxes attribute.
Unfortunately there are no tests for axes_enter_event/axes_leave_event, but this can be manually tested by running the
event_handling/figure_axes_enter_leave.py example.
See #24820, https://github.com/matplotlib/matplotlib/issues/22211#issuecomment-1070237468.

Deprecate LocationEvent.lastevent.

---

examples/subplots_axes_and_figures/colorbar_placement.py
tutorials/intermediate/constrainedlayout_guide.py

Small changes to the opening paragraphs of Constrained layout tutorial.  Also stopped referring to it as `constrained_layout` since we really want people to use `layout='constrained'`.  Improved some cross-links

FIX: improve CL description and remove constrained_layout text

---

lib/matplotlib/axis.py
lib/matplotlib/backend_bases.py
lib/matplotlib/cbook.py
lib/matplotlib/colors.py
lib/matplotlib/dates.py
lib/matplotlib/figure.py
lib/matplotlib/patches.py
lib/matplotlib/path.py
lib/matplotlib/textpath.py
lib/matplotlib/transforms.py
lib/mpl_toolkits/mplot3d/art3d.py
src/_image_wrapper.cpp

Throughout the library, array usually means "numpy array" (we also have "array-like" for the more permissive case), so no need to repeat "numpy" every time (I left it in when I judged that the emphasis was reasonable).  Also some other associated docstring cleanups.

Use "array" instead of "numpy array" except when emphasis is needed.

---

.github/workflows/tests.yml

missing parenthesis introduced in #25145 
Reformatted the if block based on a similar set of conditions from the cygwin tests to make it more readable and help locate the error.
I will exercise the unbreak CI one-review merge upon green CI (unless objected to)

BLD: Unbreak github tests workflow

---

lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/tests/test_backend_tk.py
lib/matplotlib/tests/test_backend_tools.py
lib/matplotlib/tests/test_backends_interactive.py

Fixes #25164 by converting a PIL icon image to RGBA when loading it. Also created unittest to check the bug in the future.

Accept LA icons for the toolbar

---

lib/matplotlib/backends/backend_nbagg.py

Closes #25181
I'm not sure how to test this without invoking a lot of notebook machinery....
On this branch we have:
```
$ git grep 'close_event('
lib/matplotlib/backend_bases.py:    def close_event(self, guiEvent=None)
```

FIX: do not use deprecated API internally

---

lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

Because we may switch the canvas to a different type (that may not support blitting) when saving, check it `_clear` that the current canvas is the canvas we expect when we update the blitting caches on the draw_event callback.
Closes #25075

FIX: only try to update blit caches if the canvas we expect

---

lib/matplotlib/ticker.py

- Remove redundant "always positive" comment (abs is always always positive!)
- Improve docstring for `steps` argument
- Clean up logic for filtering the step sizes in the classic autolimit mode. I thought using a loop for this before was quite opaque, so hope what I've done here is clearer?
- Add a comment above the loop through steps, explaining what it's doing.

Clean + comment MaxNLocator

---

doc/conf.py
requirements/doc/doc-requirements.txt

Depends on https://github.com/matplotlib/mpl-sphinx-theme/pull/54 being merged.
We used to include the exact commit used to build the docs in the footer (see https://matplotlib.org/3.4.3/index.html) however that got lost as part of the move to mpl-sphinx-theme. This adds the option to put this in the footer again.

DOC: restore SHA to footer

---

lib/matplotlib/backends/backend_ps.py
lib/matplotlib/tests/baseline_images/test_backend_ps/colorbar_shift.eps
lib/matplotlib/tests/test_backend_ps.py

Fix displacement of colorbar for eps with bbox_inches='tight'

---

lib/matplotlib/collections.py
lib/matplotlib/lines.py
lib/matplotlib/tests/test_collections.py

Closes #24796.
Following #23208, which implemented the `gapcolor` property for `Line2D`, this PR implements `gapcolor` for `LineCollection`.  So we can set a colour (or list of colours) to fill the gaps in dashed lines and make a striped effect.  For example
```python
_, ax = plt.subplots()
ax.vlines(range(1, 5), 0, 1, linestyle=':', linewidth=5,
color='k', gapcolor=['r', 'b'])
plt.show()
```
I marked this functionality as "experimental" to be consistent with `Line2D`.
My current implementation works, but I'm pretty unsure about the way I've structured it: it doesn't seem great to have the `LineCollection`-specific handling within `Collection`.  The only way I can see to avoid that is to define `LineCollection.draw`, but that would mean duplicating some …

Stripey `LineCollection`

---

doc/api/next_api_changes/deprecations/25196-EP.rst
lib/matplotlib/lines.py
lib/matplotlib/tests/test_lines.py

Follow up on https://github.com/matplotlib/matplotlib/pull/22329 to add a deprecation cycle for this API change and avoid breaking dependent libraries! :)
The following will now raise a `MatplotlibDeprecationWarning` instead of `RuntimeError`:
```python
l = ax.axhline(y=0.5)
l.set_ydata(0.25)
```
- [n/a] API changes are marked …

Add deprecation for setting data with non sequence type in `Line2D`

---

lib/matplotlib/_mathtext.py

Explicitly listing unknown_symbol (i.e., `\nonexistingsymbol`) in the `\operatorname` mathtext parser doesn't really matter as the parse action for such symbols is to immediately throw an exception; so we may as well not bother listing them.

Don't handle unknown_symbols in `\operatorname`.

---

src/_backend_agg.h
src/mplutils.h
src/path_converters.h

Most uses of `mpl_round` is casting back to `int`, so better keep the result as `int`. It may be possible that the compiler realizes that `(int)(double)(int)` should be simplified to `(int)` though...

Add mpl_round_to_int

---

lib/matplotlib/axes/_axes.py

Tiny doc fix.  I think the default shading for `pcolormesh` can only be the rcParam, consistent with [pcolor](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.pcolor.html#matplotlib.axes.Axes.pcolor).

DOC: correct default value of pcolormesh shading

---

examples/axes_grid1/demo_fixed_size_axes.py
tutorials/intermediate/arranging_axes.py

Also added some facecolor to some of the figures that could use it.

DOC: explain how to make a fixed-size axes

---

lib/matplotlib/scale.py

This PR doesn't directly solve any real-world problems, but will make life easier in the future.
```python
if self._base > 1:
axis.set_major_formatter(LogFormatterSciNotation(self._base))
else:
axis.set_major_formatter('{x:.3g}'),
👆
```
The comma doesn't have any effect, but triggers a lint warning: Expression value is unused. (`a,` means the tuple `(a,)`)
_Additional information_: This line was introduced in [65eff09](https://github.com/matplotlib/matplotlib/commit/65eff091b35fda2dc9af3103d74df062cf732665#diff-aa9ad5f5699f4aead65ab741dc9b34f6de86cbfe85fe6ebbc0927b38bbb775d9R545).
:warning: I'm not sure whether this kind of PR is welcomed. If not so, sorry for taking up time.
- [N/A] Documentation is …

Remove a redundant comma in `AsinhScale`

---

lib/matplotlib/backends/backend_qt.py
lib/matplotlib/pyplot.py

vars(...) may fail if the third-party manager_class has no `__dict__`, which can happen in contrieved cases involving `__slots__` or extension modules, or more simply if the backend has no FigureCanvas attribute or if the canvas class has no manager_class attribute, in which case manager_class = None.  (Note that this can only be the case if that third-party FigureCanvas doesn't inherit from FigureCanvasBase, which is probably not a great idea.)
In any case, instead of vars(), inspect.getattr_static does what we want too and also handles that case.
Also replace another (unrelated) use of vars() with a plain getattr.
See #25227 (which is still due to pycharm being outdated, but this patch should make the error less obscure and could be relevant in other (more contrieved) cases). …

Avoid calling vars() on arbitrary third-party manager_class.

---

doc/users/faq/howto_faq.rst
tutorials/colors/colormap-manipulation.py
tutorials/colors/colormapnorms.py
tutorials/intermediate/arranging_axes.py
tutorials/intermediate/constrainedlayout_guide.py
tutorials/intermediate/legend_guide.py

Following #25198, which removed the discouraged form `constrained_layout=True` from examples, this PR does the same for the tutorials and the user guide.  Also put the phrase "constrained layout" in italics consistent with #25144.
Although this is just documentation, I milestoned this for v3.8: it partially builds on #25144 which was not backported due to conflicts, so conflicts for this one will likely be worse!

DOC: remove constrained_layout kwarg from tutorials and user guide

---

doc/api/next_api_changes/behavior/25192-DS.rst
lib/matplotlib/backends/backend_wx.py

Expire wx canvas param deprecation

---

lib/matplotlib/pyplot.py

added layout="compressed" for pyplot #25223

---

.github/workflows/reviewdog.yml

The reviewdog action is not compatible with npm v9 yet, and node 18.14+ comes with npm v9+.
closes #25251

CI: Pin reviewdog eslint to use node 18.13

---

lib/matplotlib/backends/backend_wx.py
lib/matplotlib/backends/backend_wxagg.py
lib/matplotlib/backends/backend_wxcairo.py

- The "origin" keyword (for wx) has been deprecated in 591f92a and since then removed.
- The canvas classes docstrings are inherited, but we don't even bother marking them as being inherited for other backends.

Cleanup wx docstrings.

---

lib/matplotlib/path.py
lib/matplotlib/tests/test_path.py

Previously `codes[i]` would fail if codes (i.e. the concatenated path) had length zero.
Split out as preparatory work for #25247 (which introduces empty paths for contour levels that don't actually result in any level being drawn).

Support make_compound_path concatenating only empty paths.

---

lib/matplotlib/style/core.py
lib/matplotlib/tests/test_style.py

This PR fixes bug  #25242 by also catching `TypeError` exceptions when importing style files via a relative path. I also added an additional test case for importing styles with relative paths.
- [N/A] Release notes conform with instructions in …

Fix import of styles with relative path

---

lib/matplotlib/axis.py
lib/matplotlib/tests/test_axes.py

Matplotlib 3.7.0 has a bug where rcParams settings are being ignored for formatting axes labels.  This bug was introduced with #21253, specifically the use of the `Text._reset_visual_defaults()` method to reset the formatting of an axis label, including during the initialization of an axis.  Since the axis label is just a `Text`, the color gets reset to `text.color` instead of `axes.labelcolor`, and `axes.labelsize` and `axes.labelweight` are ignored.  (This bug is not readily apparent when `text.color` and `axes.labelcolor` happen to be the same, as is common for many styles.)
Example script:
```python
with mpl.rc_context({'axes.labelcolor': 'red', 'axes.labelsize': 20, 'axes.labelweight': 'bold'}):
plt.plot([1, 2, 1]) …
```

Fixed a bug where rcParams settings were being ignored for formatting axes labels

---

doc/api/next_api_changes/behavior/25255-RR.rst
lib/matplotlib/figure.py
lib/matplotlib/tests/test_figure.py

This issue was written because the solid facecolor on subfigures was hiding the parent figure suptitle. A few solutions were identified and discussed in the issue thread #24910 . It was decided that the best solution is to change the default facecolor value to "none" (transparent). This PR makes that change.

Make default facecolor for subfigures be transparent ("none"). Fix for issue #24910

---

lib/matplotlib/style/core.py
lib/matplotlib/tests/test_style.py

Fix import of styles with relative path
(cherry picked from commit ee7d75eeaecf795d6d2134607139a5864c101b60)
Conflict was caused by pyupgrade changing IOError to OSError (which are
aliases of each other since py3.3)

Backport PR #25268 on branch v3.7.x (Fix import of styles with relative path)

---

.github/workflows/reviewdog.yml

Reverts #25262.  Reviewdog just cut a release that I believe should fix the problem:
https://github.com/reviewdog/action-eslint/releases/tag/v1.18.0

CI: unpin reviewdog eslint

---

lib/matplotlib/backends/backend_gtk4.py

In the upcoming 4.10 release, the type annotation was fixed [1]. There may be some overrides added in PyGObject [2] to avoid this difference, but we don't depend on a specific version of it to be able to rely on that (and it's not released yet.) This code should work with the override as well.
[1] https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/5441
[2] https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/231
- [n/a] New features are marked with a `.. versionadded::` directive in the docstring and …

Fix setting CSS with latest GTK4

---

doc/api/next_api_changes/deprecations/25282-AL.rst
lib/matplotlib/transforms.py

The INVALID_NON_AFFINE state is never used, except at init, but there it can be replaced by a fully invalid state (the difference is that calls to invalidate() will not be propagated, but that's OK because any (necessarily new) dependent of the new node will also already be in an invalid state as well).
Thus, for clarity, replace the 4 possible values of `._invalid` (0-3) by only 3 values (0-2), and get rid of bit-twiddling in TransformedPath._revalidate.  Also rename "value" to (invalidation) "level", invert the logic in _invalidate_internal (I find the new order easier to follow), and get rid of a seemingly incorrect statement about invalidation stickiness (as far as I can tell, once a node has been revalidated (`._invalid = 0`), it can again be invalidated as affine_only). …

Simplify transforms invalidation system.

---

doc/conf.py

This will ensure that the switcher is promptly updated when we push updates to the devdocs.
I noticed that the switcher still said that 3.7 was "dev" which was fixed by reloading with caching disabled.  Use the same query-based technique we use on the rest of our static assets to ensure users do not see chimera sites.

DOC: add cache-busting query to switcher json url

---

lib/matplotlib/tests/test_backends_interactive.py

It seems that macOS is failing a bit more now; hopefully a slightly longer timeout is all that is needed.

Increase timeout for interactive backend tests

---

lib/matplotlib/animation.py
lib/matplotlib/tests/test_animation.py

Closes #25233
Not clear to me how to check it. As in how the animation testing actually works... Once setup, I am sure how to test for the particular error.

Check file path for animation and raise if it does not exist

---

.pre-commit-config.yaml
plot_types/3D/surface3d_simple.py
plot_types/3D/trisurf3d_simple.py
plot_types/3D/wire3d_simple.py
plot_types/basic/bar.py

Fixes https://github.com/matplotlib/matplotlib/issues/25303. I missed this directory out of my initial PR, but I think it makes sense to include it in the import sorting.

Add import sorting to `/plot_types`

---

examples/lines_bars_and_markers/gradient_bar.py

- Don't list `extent` explicitly in the signature, but let it be passed as kwargs.  (It's not more, or less, special than `transform`.)
- Use the shorter `clim` instead of `vmin, vmax`.
- Pass aspect="auto" within gradient_image (the caller shouldn't have to do that).

Cleanup gradient_bar example.

---

lib/matplotlib/colors.py
lib/matplotlib/tests/test_colors.py

Adds parameter documentation, and a new test to check that masking behaviour conforms to the doc.

Document PowerNorm parameters

---

lib/matplotlib/figure.py
lib/matplotlib/pyplot.py

Closes #25223.  Documents the `layout='none'` option for creating a figure.

DOC: add layout='none' option to Figure constructor

---

lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_pgf.py

Use setattr_cm more.

---

.github/workflows/stale.yml

Proposed stale action...
It labels PRs after 60 d, but never closes them.  
It does close issues after 1 year with 30 day warning.   

GitHub: auto set inactive label

---

.github/workflows/stale.yml

Looks like we have a small typo:
https://github.com/matplotlib/matplotlib/actions/runs/4278121008

"Inactive" workflow: fix typo

---

lib/matplotlib/contour.py
lib/matplotlib/tests/test_contour.py

As discussed in #25330, we're removing the typecase to float with `z.min().astype(float)`.
Closes #14124.

Fix for all NANs in contour

---

lib/matplotlib/offsetbox.py
lib/matplotlib/tests/test_pickle.py

Make draggable legends picklable.

---

lib/matplotlib/cbook.py
lib/matplotlib/tests/test_pickle.py

Support pickling of figures with aligned x/y labels.

---

lib/matplotlib/tests/test_lines.py

Not sure why it changed, but it's failing with RMS of 0.640 now, which seems small enough to keep allowing.

TST: Increase test_set_line_coll_dash_image tolerance slightly.

---

lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

The clipping in the setter ensures that min <= max, but if you are setting both values outside the existing range, this will incorrectly set new minimum to old maximum and vice versa.
The tests also passed accidentally because all the new ranges overlapped with the old, and did not trigger this issue.
Fixes #25338
- [n/a] API changes are marked with a `.. versionchanged::` directive in …

Fix RangeSlider.set_val when outside existing value

---

lib/matplotlib/tests/test_text.py
lib/matplotlib/text.py

Fixes #25336.
Constrained layout here relies on `Text.get_tightbbox`, which calls `Text.get_window_extent`, which calls `Text._get_layout`.  The example code in the issue now produces:
- [N/A] Release notes conform with instructions in …

FIX: use wrapped text in Text._get_layout

---

lib/matplotlib/figure.py
lib/matplotlib/legend.py

As we now have different docs for the *loc* parameter to `Figure/Axes.legend`, we can replace the ambiguous 'axes/figure' with the correct type. And also remove 'best' from the `Figure.legend` version.
Note, I did not remove 'best' from the numerical table, as that would be annoying to do, so I just annotated it.
Fixes #25323
- [n/a] Release notes conform with …

Clean up legend loc parameter documentation

---

requirements/doc/doc-requirements.txt

A similar thing was done for the `v3.6.x` branch.

Pin mpl-sphinx-theme on the v3.7.x branch

---

lib/matplotlib/axis.py
lib/matplotlib/tests/test_axes.py

Fixes #25165
Updates the offset text color according to the tick attribute "labelcolor" or "color"

Fix unmatched offsetText label color

---

doc/api/next_api_changes/deprecations/25352-GL.rst
lib/matplotlib/axes/_base.py
lib/matplotlib/cbook.py
lib/matplotlib/tests/test_cbook.py
lib/mpl_toolkits/mplot3d/axes3d.py

Rather than handling the weakrefs ourselves, just use the builtin WeakKeyDictionary and WeakSet instead. This will automatically remove dead references meaning we can remove the clean() method.
Follow-up from: #25332
- [-] Has pytest style unit tests (and `pytest` passes)
- [-] New plotting related features are documented with examples.
- [-] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [-] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`

MNT: Use WeakKeyDictionary and WeakSet in Grouper

---

src/_macosx.m

The attribute is never referenced in the entire file; it appears to be a leftover of old style navigation toolbars, which were removed in 28effb4 and earlier.

Remove unused menu field from macos NavigationToolbar2.

---

lib/matplotlib/animation.py
lib/matplotlib/tests/test_animation.py

This tests is checking that the animation raises a reasonable error if it cannot be saved to a directory. But that triggers the warning that the animation was not saved.

Disable discarded animation warning on save

---

requirements/doc/doc-requirements.txt

Done manually to fix conflicts between #25369 and #25307.

Backport PR#25369: Pin sphinx themes more strictly

---

.github/workflows/cibuildwheel.yml

We couldn't work out what exactly changed to stop the license being included, so work around that by pre-downloading it.
Fixes #25212
- [n/a] Release notes conform with instructions in …

BLD: Pre-download Qhull license to put in wheels

---

galleries/examples/text_labels_and_annotations/angles_on_bracket_arrows.py
lib/matplotlib/patches.py

By combining A/B parameters, to match the style of the CurveBracket, CurveFilled, etc.
Also, tweak the example image so that it is not scaled down in the docs, and explicitly shows 0°.
Fixes #25361.

Clean up Curve ArrowStyle docs

---

lib/matplotlib/patheffects.py

The module is `patheffects`, not `path_effects`.
This is the updated version:

Correct patheffects doc

---

galleries/examples/axisartist/simple_axis_direction01.py
galleries/examples/axisartist/simple_axis_direction03.py

Not so clear which label is which if the same label text is used.
Also, changed the casing of the example name. 1 and 3 are not ideal, but not really sure what a better name should be.

Better axis labels for examples

---

doc/devel/contributing.rst

As per #25080, a note has been added to the `contributing.rst`

added a note to avoid f-strings in logging

---

.appveyor.yml

Consistent with recent changes for CI on other platforms (#25145, #25261), this change should mean the Appveyor CI is skipped if the only changes are under `doc` or in the `galleries`, or if `[ci doc]` is in the commit message.  Following the guidance here:
https://www.appveyor.com/docs/how-to/filtering-commits/
I added `[ci doc]` to the current commit, to test it works.

CI: skip appveyor for doc only change

---

doc/users/github_stats.rst
examples/axisartist/simple_axis_direction03.py

Fixes a typo from #25388, and a typo from generating the GitHub stats page that is causing pre-commit to complain.

DOC: Fix a couple typos

---

doc/users/github_stats.rst
examples/axisartist/simple_axis_direction03.py

Fixes a typo from #25388, and a typo from generating the GitHub stats page that is causing pre-commit to complain.
This PR is just to confirm that pre-commit is happy.

Merge v3.7.1-doc into v3.7.x

---

lib/matplotlib/backends/_backend_tk.py

The `crosshair` cursor maps to a native cursor on Windows, the current `tcross` does not.

Make tk backend use native crosshair cursor

---

lib/matplotlib/dates.py

Related to #25419.
It would have been slightly easier to realize that something surprising was going on if one could have seen the incorrectly passed `tz` argument (which was not the one that a user would expect that they had just passed...).

Print incorrect tz argument in error message

---

doc/api/next_api_changes/deprecations/25138-AL.rst
lib/matplotlib/colorbar.py
lib/matplotlib/contour.py
lib/matplotlib/tests/test_contour.py

Directly construct the relevant path objects and the collections with the right properties instead of carrying around another copy of the information in raw array form.  By having fewer intermediate objects lying around for a long time (as attributes of the QuadContourSet) this makes the logic easier to follow.  This also prepares for #25128, but I'd say the change is worthwhile even if we eventually  decide not to go that route.

Deprecate QuadContourSet.allsegs, .allkinds, .tcolors, .tlinewidths.

---

doc/conf.py
requirements/doc/doc-requirements.txt

Now that pydata-sphinx-theme is out, it is compatible with mpl-sphinx-theme.
Note we are still using mpl-sphinx-theme from git.

DOC/BLD: make logo compatible with pydata-sphinx-theme

---

lib/matplotlib/legend.py

Typo causes `Legend.set_draggable(True, update="bbox")` to be broken.

Fix Legend.set_draggable() with update="bbox"

---

lib/matplotlib/backends/backend_wx.py

fix the order of flushing and closing the wx Clipboard in `backend_wx.Copy_to_Clipboard()`
- [N/A] Release notes conform with instructions in  `next_whats_new/README.rst` or …

wx backend should flush the clipboard before closing it

---

lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

This is the only selector widget that needs to remember its properties separately from the artist, because the artist can be recreated.
Fixes #25199 …

Move _SelectorWidget._props into SpanSelector

---

doc/conf.py
lib/matplotlib/tests/test_doc.py

Resolves #25416.  I just followed the instructions in the test docstring
https://github.com/matplotlib/matplotlib/blob/bacd02582a94d286aaa326bbf40a44b66046665c/lib/matplotlib/tests/test_doc.py#L6-L10

TST: unbreak appveyor

---

.github/workflows/tests.yml

At some point, one of our dependencies must have required `pytz`, but then recently dropped it. Pandas also requires it, but because we install the nightly wheels using `--index-url`, `pip` can only install files from that index, which does not contain `pytz`. And we want to use that index exclusively because we only want the nightly wheels, and nothing else. So explicitly install `pytz` when running nightlies.
Also, make `-i` into the more explicit `--index-url`, and word-wrap that step.
Fixes #25431
- [n/a] New plotting related features are …

ci: Install pytz for Pandas nightly wheel

---

doc/api/next_api_changes/deprecations/25427-AL.rst
lib/mpl_toolkits/axisartist/floating_axes.py

Make the value returned by ExtremeFinderFixed be the canonical place to query the value of the extremes parameter.
This may make it easier to change the extremes post-facto (there's fewer places to update): #25426.  (Though some further work is needed...)
Also deprecate the related get_data_boundary method, which doesn't exist anywhere else and isn't really needed as a separate API: we can just inline it into its only call site instead.

Store FloatingAxes "extremes" info in fewer places.

---

doc/api/next_api_changes/deprecations/23200-OG.rst
lib/matplotlib/path.py

Closes #1735
Based on the issue, the outcome of an empty offsets is not well defined. This is now deprecated.

Deprecate empty offsets in get_path_collection_extents

---

lib/matplotlib/figure.py
lib/matplotlib/tests/test_backend_bases.py

Otherwise, _nothing_ will remove the grab, and no other Axes can grab the mouse (either raising the `RuntimeError` exception, or in the case of widgets, ignoring mouse events altogether.)
Fixes #25345
- [n/a] Release notes conform with instructions in …

Release mouse grabs when owning Axes is removed

---

lib/matplotlib/backends/backend_agg.py
lib/matplotlib/figure.py
lib/matplotlib/image.py
lib/matplotlib/tests/test_figure.py

Closes #25401
As requested, the error message is more related to what users are
actually doing.
Slight behavior change, though not sure it's worth a release note in
that `imsave` will error if metadata is given for formats that don't
support it (this was done because it was unused if it was passed, and
if and when we add metadata support for those formats, it will be
implemented in imsave)

Edit error messages for when metadata is passed to `savefig`

---

galleries/examples/statistics/histogram_cumulative.py

Closes #25458 
Changes "normed" in the documentation to "density" due to the parameter being renamed in v3.3

Fix issue #25458 by changing "normed" to "density" in documentation

---

.github/workflows/stale.yml

As #25424.  Increase available operations so more issues are labelled on the next run.

“Inactive” workflow: bump operations to 100

---

lib/matplotlib/tri/_tripcolor.py

The check was overly restrictive (str inputs work just fine per normal ScalarMappable API) and we can just let the TriMesh/PolyCollection ctors handle the validation.
Closes #25453.

Remove unnecessary norm typecheck in tripcolor().

---

lib/matplotlib/offsetbox.py
lib/matplotlib/tests/test_offsetbox.py

Once a draggable artist has been removed from its parent figure, we cannot access `self.canvas` (i.e. a property for
`self.ref_artist.figure.canvas`) anymore to disconnect the relevant callbacks.  Instead, we should keep track from the very beginning (in the DraggableBase constructor) of the place from which the callbacks should be disconnected.
Closes #25440.
Release critical as it's a regression due to #25311.

Fix disconnection of callbacks when draggable artist is deparented.

---

lib/matplotlib/offsetbox.py
lib/matplotlib/tests/test_offsetbox.py

Fix disconnection of callbacks when draggable artist is deparented.
(cherry picked from commit 370547ebfc12e879aefe0f914eaa94d72eb95a9b)
Required manual backport because additional tests for offsetbox were added on `main` in #24486 .

Backport PR #25442 on branch v3.7.x (Fix disconnection of callbacks when draggable artist is deparented.)

---

doc/api/next_api_changes/behavior/24531-DOS.rst
doc/api/next_api_changes/development/24531-DOS.rst
doc/devel/dependencies.rst
lib/matplotlib/backends/_backend_tk.py

This also allows us to sort all extensions in alphabetical order, in line with the other backends, rather than having to put the default option first.
This change required raising the minimum supported version of Tk to 8.5, as discussed in #24450. I also removed a try statement around `iconphoto`, which should only have failed on Tk < 8.5 - it didn't feel big enough to deserve its own PR, but happy to separate it out if anyone disagrees.
Closes #24450.
- [N/A] New features are marked with a `.. versionadded::` …

Use user-selected format in Tk savefig, rather than inferring it from the filename

---

doc/devel/release_guide.rst
doc/users/release_notes.rst
tools/cache_zenodo_svg.py

TODOS
- I have a relatively minimal change that puts "create the release branch" in the same part of the workflow, just instead of releasing from main and then creating the release branch during the `.0` release, we create it for the last anticipated micro release of the previous minor version. This is closer, I think to what we actually do, but not sure if we want to reorganize that thought.
- This is referred to later on to uncomment, but it doesn't actually say to comment it in the linked section.
- Alternatively, may be able to use rst to ignore it for releases and not have to edit this at all.
- Does this only happen for `.0` releases, or every release
- If conflicts do arise, how are they resolved (can a standard answer be given?)?
- Is the only real need for this for the purposes …

Update release guide instructions post v3.7.0

---

lib/mpl_toolkits/axisartist/floating_axes.py
lib/mpl_toolkits/axisartist/tests/test_floating_axes.py

Without this patch, calling clear() in a FloatingAxes will reset the limits of the (invisible, parent, rectilinear) axes to (0, 1), (0, 1), instead of the values computed by adjust_axes_lim.  For example, try adding a call to ax1.clear() in demo_floating_axes immediately after the call to setup_axes1; this previously resulted in a blown up left axes.

Adjust parent axes limits when clearing floating axes.

---

galleries/examples/showcase/stock_prices.py
galleries/examples/subplots_axes_and_figures/figure_title.py

The kwarg to switch the returned object is a bit unsightly, and in the cases here genfromtxt handles the file object as input just fine.

Use get_sample_data(..., asfileobj=False) less.

---

lib/matplotlib/_api/__init__.py
lib/matplotlib/cbook.py
lib/matplotlib/font_manager.py
lib/matplotlib/tests/test_font_manager.py

This leads to caching the tracebacks which can keep user's objects in local namespaces alive indefinitely.  This can lead to very surprising memory issues for users and will result in incorrect tracebacks.
Responsive to #25406

FIX: do not cache exceptions

---

lib/matplotlib/legend.py
lib/matplotlib/tests/test_legend.py

Co-authored-by: John Paul Jepko <jpjepko@users.noreply.github.com>
This pull request adds a check to the loc argument of legend. It checks that loc is one of the following:
- valid location string (this validation was already present)
-  a 2-tuple of floats or ints
-  a string numeric value (0-10)
The code raises a ValueError otherwise. This resolves #24605 . The docstrings already mentioned the fact that loc is a pair of floats so we did not add any changes to any docstrings. We also added test cases for the new validation checks. For details on the valid options refer to this [doc](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.legend.html) 

Bugfix for loc legend validation

---

lib/matplotlib/image.py
lib/matplotlib/tests/test_image.py

Fixes #22494. Continuation of draft PR #22510. Added the `get_shape` commit and wrote tests for `get_size` method and the newly added `get_shape` method.

Added get_shape as an alias for get_size + tests

---

doc/api/next_api_changes/deprecations/XXXXX-AL.rst
lib/matplotlib/backends/backend_agg.py

As noted previously (#5336, see in particular the comments in the thread), silently dropping alpha can be confusing.  Also, directly accessing the buffer array is more efficient (it does not involve copying to a string buffer) and should cover most use cases.
Closes #5336.

Deprecate tostring_rgb.

---

.github/workflows/cibuildwheel.yml
doc/api/next_api_changes/development/25475-ES.rst

NumPy dropped these builds first in 1.21.2 (Aug 15, 2021) for Python 3.10 only, and for all builds in 1.22 (Dec 31, 2021).
SciPy dropped these builds first in 1.8.0 (Feb 5, 2022) for Python 3.10 only, and for all builds in 1.9.2 (Oct 8, 2022).
Also, simplify workflow file to remove some duplication.
Theoretically we could join all the `Build wheels for CPython 3.X` steps, but I left them separate so that there wouldn't be a timeout for a single step taking too long (though I don't think that'd happen).
- [n/a] New features are marked with a `.. versionadded::` directive in the docstring and documented in …

Stop building 32-bit Linux wheels

---

lib/matplotlib/path.py

I found it confusing that it was listing A, A, A, A... a bunch of times, so I gave each type unique identifiers. Also, add an initial line for short docs.

DOC: Clarify note in get_path_collection_extents

---

.github/workflows/stale.yml

As https://github.com/matplotlib/matplotlib/pull/25424. Increase available operations so more issues are labelled on the next run.

"Inactive" workflow: bump operations to 125

---

lib/matplotlib/backend_bases.py

There is no `pyplot` module in the system registry, as the module is imported as `matplotlib.pyplot`.
This code tries to detect when `matplotlib.pyplot.show()` is invoked in a script run via the %run IPython's magic while in interactive mode as enabled by the `%pylab` or `%matplotlib` IPyhton's magic commands.  In these modes, matplotlib.pyplot.show() should not block.
Failing do detect these modes, a simple `test.py` script as this
```
plt.figure()
plt.show()
```
run in IPython as follows
```
%matplotlib
%run test.py
```
is not expected to block on `matplotlib.pyplot.show()`.  Without this patch it does.  Additionally, the redraw implemented by IPython at the end of %run caused an empty figure to be displayed when the script terminates.
Fixing the module …

BUG: fix IPython's %pylab mode detection

---

lib/matplotlib/axis.py

set_ticks actually already calls set_locs, so the calls here are redundant.
Preparatory to deprecating set_locs as a public API (#13323, https://github.com/matplotlib/matplotlib/issues/5787#issuecomment-1475940049).

Remove unnecessary calls to Formatter.set_locs.

---

lib/matplotlib/_tight_bbox.py
lib/matplotlib/tests/test_figure.py

Fixes #22625.  The problem was that `_ColorbarAxesLocator` was not used to set the aspect ratio before `adjust_bbox` stripped it off.  A simpler but presumably less efficient fix might be to trigger a draw before calling `adjust_bbox`.  We already do that if `bbox_inches == "tight"`.
https://github.com/matplotlib/matplotlib/blob/78bf53caacbb5ce0dc7aa73f07a74c99f1ed919b/lib/matplotlib/backend_bases.py#L2358-L2361
- [N/A] New features are marked with a `.. versionadded::` directive in the docstring and documented in …

FIX: use locators in adjust_bbox

---

galleries/users_explain/text/annotations.py

Three stylistic improvements
- Modify "Annotating an Artist" of Annotations tutorial
to a horizontal arrow so that the arrow line does not cross the
artist. This is somewhat special but visually more pleasing and
possibly a real use case.
**old:**
**new:**
- Change coordinates in Annotations tutorial
... in the `transAxes` / "axes fraction" example. Brining the
annotations closer to the coordinate axes makes it easier to
see that they are really the same. Also, the previous positioning
(0.5, 0.5) without centered alignment results in almost, but not
exactly centering of the text in the Axes frame, which is not
quite nice visually.
**old:**
**new:**
- Modify "Annotating an Artist" of Annotations tutorial
to a horizontal arrow so that the arrow line does not cross the
artist. This is …

Annotations tutorial

---

src/_backend_agg_wrapper.cpp
src/_image_wrapper.cpp
src/_path_wrapper.cpp
src/_qhull_wrapper.cpp
src/_tkagg.cpp
src/_ttconv.cpp
src/ft2font_wrapper.cpp

Since Python 3.9, the `PyMODINIT_FUNC` has included explicit default visibility [1], and so works when we set visibility to be hidden globally.
[1] https://github.com/python/cpython/commit/0b60f64e4343913b4931dc27379d9808e5b78fe1
- [n/a] Release notes …

Remove explicit symbol visibility pragmas

---

lib/matplotlib/transforms.py

The extension of AFFINE_ONLY invalidations into FULL invalidations in CompositeGenericTransform._invalidate_internal was too generous; it is only needed in case (b) , not in case (a).  This is actually the argument made by Phil Elson (in
https://discourse.matplotlib.org/t/16538/2, starting at "If the invalid part is a1...") when he first introduced the _invalidate_internal API, but for some reason his implementation further added case (a).  Remove that case.

Limit full-invalidation of CompositeGenericTransforms.

---

lib/matplotlib/artist.py
lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/matplotlib/collections.py
lib/matplotlib/figure.py
lib/matplotlib/image.py
lib/matplotlib/legend.py
lib/matplotlib/lines.py
lib/matplotlib/offsetbox.py
lib/matplotlib/patches.py
lib/matplotlib/quiver.py
lib/matplotlib/table.py
lib/matplotlib/text.py

The old _default_contains check was geared towards custom contains checkers (set via set_contains), which have been removed.  Get rid of that and instead, add a check for canvas identity which is more useful.
Closes #6324.

In Artist.contains, check that moussevents occurred on the right canvas.

---

lib/matplotlib/widgets.py

They corresponded to the old pressv/prev attributes, which have been deprecated and then removed.

Remove unused private SpanSelector._pressv and ._prev.

---

lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_backend_bases.py
lib/mpl_toolkits/mplot3d/axes3d.py

When pressing the "home" key, the autoscaling state should be restored as well, as interactive zoom/pan could have turned it off. test_toolbar_home_restores_autoscale shows an example of why.  Assume one starts with `plot(range(11), range(11))`.  In linear scale this autoscales to (0, 10) (assuming no margins or the old round limits mode); in log scale this autoscales to (1, 10) (dropping the zero).  But previously, when "home" did not restore autoscale state, then a manual zoom followed by "home" (in linear scale) would set the limits to (0, 10) and turn off autoscale, after which switching to log scale interactively would give incorrect autolimits.
Closes #6630.

Restore autolimits status when pressing "home" key.

---

doc/api/next_api_changes/deprecations/25557-AL.rst
lib/matplotlib/legend.py
lib/matplotlib/text.py

For all other artists the parameter name is *mouseevent*.

Rename parameter of Annotation.contains and Legend.contains.

---

src/_macosx.m

The main thread is the one that is running when started, so we should put all timers we control on that thread. Otherwise, we need to start and control runloops on the other threads which may or may not be started. This is particularly important for `draw_idle()` calls that may be sent from a separate thread where work was being done, but the draw should happen on the main thread still.
closes #5675
To test, you can use the example from #5675 with some updates from other comments in there (save to file and run in interactive mode `python -i mac-threading-test.py`. Previously, the canvas would never be updated and freeze after the fact due to the extra thread waiting to have a runloop started and capture the draw events that were sent. There is a slight concern that we could hang the GUI …

FIX: macosx, always put timers on main thread

---

lib/matplotlib/tests/test_ticker.py
lib/matplotlib/ticker.py

Fixes #23626 
Closes #24079
Replace unintended space in locale.format_string function

Fix unintended space after comma as a decimal separator

---

lib/matplotlib/tests/test_ticker.py
lib/matplotlib/ticker.py

Resolves #24092 
A simplification of the stride calculation in [this commit](https://github.com/matplotlib/matplotlib/commit/a06f343dee3cebf035b74f65ea00b8842af448e9) seems to have introduced some incorrect behavior, as the simplified version isn't mathematically equivalent to the old one. This caused the method to return an empty array when it shouldn't, which meant ticks would not appear on the grid axes. 
This PR reverts the stride calculation in the case where `mpl.rcParams['_internal.classic_mode']` is `False` to one equivalent to the while-loop the simplification replaced, as well as adding tests for the scenario described in #24092. …

Fix incorrect stride calculations in LogLocator.tick_values()

---

doc/api/next_api_changes/deprecations/25559-AL.rst
lib/matplotlib/backend_bases.py

Make guiEvent available only within the event handlers.

---

lib/matplotlib/colorbar.py
lib/matplotlib/tests/test_colorbar.py

When switching norms of the mappable we should autoscale the norm using the data if possible rather than setting it to (0, 1). From the linked issue, this currently errors due to vmin=0 when updating the norm, even though the data is all valid for LogNorm.
```python
from matplotlib.colors import LogNorm, Normalize
img = np.arange(1, 11).reshape((2, 5))
fig, ax = plt.subplots(1, 1)
plot = ax.imshow(img, cmap='gray')
cb = fig.colorbar(plot, ax=ax)
plot.norm = LogNorm()
plt.show()
```
closes #5424
- [-] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [-] New plotting related features are documented with …

FIX: Use mappable data when autoscaling colorbar norm

---

lib/matplotlib/tests/test_ticker.py
lib/matplotlib/ticker.py

Fix issue with shared log axis

---

lib/matplotlib/pyplot.py

The typing PR found that this was returning a generator [1], but this was an error from #24000, as 3.6 and earlier returned a list.
[1] https://github.com/matplotlib/matplotlib/pull/24976#discussion_r1152872718
- [n/a] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in …

Fix return type of get_plot_commands

---

galleries/examples/widgets/textbox.py
lib/matplotlib/backends/qt_editor/_formlayout.py

In the textbox example we need eval because we are taking symbolic input from the user and then plotting it.  I restricted the namespaces a bit to set a better example, but I think we fundamentally do need to use `eval` in this case.
In the qt editor eval was changed to ast.literal_eval which only handles literals so is safer.
These were the main things that I did not think were false-positives from running semgrep on our code base.

MNT: use less eval

---

lib/matplotlib/axes/_axes.py

DOC: improve interpolation kwarg doc in imshow [ci doc]

---

lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_lines.py
src/_backend_agg.h
src/_backend_agg_basic_types.h
src/ft2font.cpp

Replace constant divisions with constant multiplications (1.0/64.0 can be exactly represented, it seems like the x86 LLVM compiler backend optimizes the division to a multiplication anyway, but it will be compiler and architecture dependent as the LLVM IR still has an fdiv).
Group/reorder computations to allow constant folding.
Move computations out of loop. 
Only compute sin/cos once.
There are some minor floating-point related changes in the results (as floating-point computations in general are not commutative), but will have to see on the CI which ones actually breaks... 
Edit: I think that it is the move-out-of-loop that causes the failures. One is 0.001, so really neglible (I cannot even see where the non-black pixel is in the diff), while the other is 0.19, which looks like a …

Optimize C code

---

doc/api/next_api_changes/deprecations/24312-AL.rst
galleries/users_explain/toolkits/axes_grid.py
lib/mpl_toolkits/axes_grid1/axes_divider.py
lib/mpl_toolkits/axes_grid1/tests/test_axes_grid1.py

The axes_divider module creates axes locator objects, allowing the following pattern.
```
divider = Divider(<divider-args>)  # or a subclass of Divider
locator = divider.new_locator(<locator-args>)
ax.set_axes_locator(locator)  # will call locator(ax, renderer) at draw time
```
`locator` is actually an AxesLocator instance, which gets passed `divider` and `<locator-args>`; `locator(ax, renderer)` then simply calls (something like) `divider.locate(<locator-args>, ax, renderer)`, i.e. the AxesLocator instance simply exists to hold arguments for calling back into a divider method.
One issue of this approach is that all the communication between the Divider and the AxesLocator class becomes public API (e.g., the locate method), even though these are essentially internal implementation …

Deprecate axes_divider.AxesLocator.

---

lib/matplotlib/axes/_axes.py

closes #25410
I do not think the long analysis in the comments of #25410 has a good home in the docs, but hopefully this is enough to point people in the right direction if things look funny.
There was another issue (that I can not find again) that reported the area of markers was too big (but they might have been using `Circle`) so also added a note about that while I was touching this docstring.
- [/] Has pytest style unit tests (and `pytest` passes)
- [/] New plotting related features are documented with examples.

DOC: add a note about linewidth to scatter docs

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/legend.py
lib/matplotlib/rcsetup.py

Use _api.nargs_error in more places

---

pyproject.toml

Should mean that the figure no longer gets shown when running stubtest. I had previously been working around by setting the MPLBACKEND envvar to a non-gui backend

Ensure tinypages ignored by mypy/stubtest

---

lib/matplotlib/figure.py
lib/matplotlib/tests/test_figure.py

closes #7805
- [na] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [na] New plotting related features are documented with examples.

FIX: correctly unset the layout engine in Figure.tight_layout

---

lib/matplotlib/backends/backend_cairo.py
lib/matplotlib/backends/backend_gtk3.py
lib/matplotlib/backends/backend_gtk4.py

Otherwise, you can get, e.g., a test skip with an empty message like:
```
lib/matplotlib/tests/test_getattr.py::test_getattr[matplotlib.backends.backend_gtk3] SKIPPED (Cannot import matplotlib.backends.backend_gtk3 due to)
```
- [n/a] Release notes …

Ensure ImportError's have a message

---

environment.yml
requirements/testing/extra.txt

reference jupyter/nbconvert#1970

TST: Bump exclude for newly released nbconvert

---

lib/matplotlib/backends/qt_editor/figureoptions.py

One can directly pass the cmap str name to ScalarMappable.set_cmap.

Don't use deprecated cm.get_cmap in qt figureoptions.

---

ci/mypy-stubtest-allowlist.txt
doc/api/next_api_changes/deprecations/25651-REC.rst
lib/matplotlib/tests/test_ticker.py
lib/matplotlib/ticker.py

As far as I can tell, this parameter is not used for anything.
Closes #25638 

MNT: deprecate unused numdecs LogLocator param

---

.circleci/config.yml
.github/workflows/circleci.yml

The CircleCI artifact redirector action (which creates the docs preview links in PRs) [is failing](https://github.com/matplotlib/matplotlib/actions/runs/4681038876). This is due to [an upstream bug](https://github.com/larsoner/circleci-artifacts-redirector-action/issues/40). Following the advice on that thread, this PR adds the `api-token` definition in the configuration file for the action.
- [N/A] New features are marked with a `.. versionadded::` …

MAINT: Add api-token for CircleCI redirector action

---

doc/users/next_whats_new/mathtext_supports_text.rst

Seems like I messed up with the formatting...
https://matplotlib.org/devdocs/users/next_whats_new/mathtext_supports_text.html

Fix what's new note for text

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

This is not finalized, but more a base for discussion. (Tests will be added once the final solution is decided.)
Closes #7560 
There are two issues that are considered here:
1. There seems to be a bit of copy-and-paste errors (the original issue in #7560). Here, the proposed solution is to error on empty iterables. This changes the earlier solution, but only for a few of the parameters (although the error message will change for all).
2. There is a bit of code for dealing with the positions not being an iterable. However, although this is put within a list, it will break later as the actual position is still not an iterable. Here, it is suggested to support that type of call (`eventplot(1)`), but one can also consider raising an error with an appropriate error message already there. …

Fixed `eventplot` issues

---

lib/matplotlib/tests/test_api.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_backend_ps.py
lib/matplotlib/tests/test_contour.py
lib/matplotlib/tests/test_dates.py
lib/matplotlib/tests/test_lines.py
lib/matplotlib/tests/test_pyplot.py
lib/matplotlib/tests/test_rcparams.py
lib/matplotlib/tests/test_widgets.py
lib/mpl_toolkits/axes_grid1/tests/test_axes_grid1.py

Just a minor thing I noticed in https://github.com/matplotlib/matplotlib/pull/25651/files/fe0b069b06e3ee98108a20b30d9c1f10915ee77d#diff-fd4f809a4a2ca8b97875eff013bac232c55ca3f92f165117f778960ca1795869
- [n/a] Release notes conform with instructions in …

TST: Import MatplotlibDeprecationWarning consistently

---

lib/matplotlib/tests/test_text.py
lib/matplotlib/text.py

Fixes https://github.com/matplotlib/matplotlib/issues/23810
The mathtext was being treated as normal text during the width calculations, added a check that allows for it to be automatically directed to the proper backend functions. 

Fixed bug: mathtext rendered width not being calculated correctly

---

.github/codecov.yml

Addresses https://github.com/matplotlib/matplotlib/issues/25695
The `codecov.yml` file was invalid:
```
$ cat .github/codecov.yml | curl --data-binary @- https://codecov.io/validate
Error at ['coverage', 'status', 'project', 'library', 'paths']:
must be of list type
```
I corrected the issues, so it is now valid:
```
$ cat .github/codecov.yml | curl --data-binary @- https://codecov.io/validate
Valid!
{
...
}
```
- [N/A] New features are marked with a `.. …

Fix codecov.yml so it is valid.

---

lib/matplotlib/_api/__init__.py

Use true positional args in check_foo APIs instead of simulating them.

---

doc/_static/mpl.css

`visibility:hidden; height: 0px` still keeps margins, creating a large amount of whitespace. `display: none` is the correct way to remove an HTML element completely.
before (with margins highlighted):
now:
Also reported upstream: https://github.com/sphinx-gallery/sphinx-gallery/pull/1131

Correctly hide download buttons using CSS

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

Addresses https://github.com/matplotlib/matplotlib/issues/25625
When using `bar_label(label_type='center')` and axis limits that cut off some of the bars, an exception was raised because the Bbox intersection was `None`. This PR makes sure the plot can still be created.
- [N/A] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in …

BUG: Return null Bbox when there is no intersection for bar_label center.

---

.github/workflows/mypy-stubtest.yml

Unfortunately, the way that `stubtest` outputs its error messages makes it difficult to post a message on _both_ the `.py` and `.pyi` stub, so we decided to take the full message and post it only on one.
As a test, I have made PR in my repo https://github.com/QuLogic/matplotlib/pull/30 which started from the previously-unfixed #25542, and then I also added a commit with multiple argument mismatches to confirm that `stubtest` didn't output some different format.
Results are at the bottom of https://github.com/QuLogic/matplotlib/pull/30/files
- …

Post stubtest results to GitHub checks

---

doc/devel/coding_guide.rst

- make less prescriptive
- fix formatting (the milestone guidelines were in a nested list?)
- minor wording tweaks
closes #25649

DOC: clarify the milestoning and backport policy wording

---

lib/matplotlib/tests/test_pyplot.py
tools/boilerplate.py

The test is already skipped if the boilerplate script is missing (i.e., not a git checkout), but should also be skipped if black is not installed.
Also, the boilerplate script ignored if running black failed, leading the test to show lots of line differences instead of just erroring out earlier.
- [n/a] API changes are marked with a `.. versionchanged::` directive in the docstring and …

TST: Handle missing black more resiliently

---

ci/mypy-stubtest-allowlist.txt
doc/api/next_api_changes/deprecations/25584-KS.rst
doc/api/next_api_changes/removals/25584-KS.rst
lib/matplotlib/colorbar.py
lib/matplotlib/colorbar.pyi
lib/matplotlib/figure.py
lib/matplotlib/tests/test_triangulation.py
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/tri/_tripcolor.py
lib/matplotlib/widgets.py
lib/matplotlib/widgets.pyi

- Remaining mpl3.6 deprecations
- Update tests for deprecated behavior
I believe the only `3.6` deprecations that remain are still marked as "pending", those include some in axis3d and some in Figure.
The expiration for `Colorbar` filled kwarg is rather minimal.
It was originally deprecated in #21933, @jklymak do you think more clean up is needed?

Expire remaining 3.6 deprecations

---

.github/workflows/tests.yml
azure-pipelines.yml

At some point, Azure servers were having a small hiccup, and I noticed this setup in some unrelated repository. Allowing a couple retries _may_ help with minor issues like those.
- [n/a] Release …

ci: Set apt to retry operations on failure

---

lib/matplotlib/backends/backend_qtagg.py
lib/matplotlib/backends/backend_wx.py

AFAICT, `print_figure` is only called in `savefig`, and thus has no relation to backend drawing. We went through a lot of trouble to make `savefig` self-contained, so if this really had any effect, it would be a bug in it instead. But other backends don't do this override and seem to work fine, so these seem superfluous as well.
After this change, just opening a window in Qt and using the save button did not seem to break anything, nor did running `savefig` with an interactive window open. I did not test Wx, but given the callers of `print_figure`, I don't see how it could be different.
Fixes #5234
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should …

Remove print_figure overrides in backend subclasses

---

doc/devel/contributing.rst

The paragraph on assigning issues and duplicating PRs is the last paragraph of the section for new contributors, so I just added a section title to make it clear that it's a general policy and not just for new contributors.

added assigning and duplicating section heading to contribute guide

---

lib/matplotlib/tests/test_path.py

Add test for Path.contains_path

---

lib/matplotlib/tests/test_text.py

There were no test coverage for right aligned nor rotated texts.

Add tests for missing text wrap cases

---

lib/mpl_toolkits/axisartist/grid_finder.py
lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py

- GridHelperCurveLinear: numpydocify; remove unused _aux_trans attribute.
- GridFinder: This class is used nowhere else but as attribute on GridHelperCurveLinear and could probably be inlined into it; for now, remove the duplicated constructor docstring.

Cleanup GridHelperCurveLinear/GridFinder.

---

.github/PULL_REQUEST_TEMPLATE.md

This changes the PR template to prompt/remind the user to link the issue it resolves. This is to make sure that it reduces duplicate PRs, as having a back link would make it easier to know that there's work being done on a particular issue.
- [N/A] API changes are marked with a `.. versionchanged::` directive in the docstring …

Update PULL_REQUEST_TEMPLATE.md to include issue cross-reference.

---

doc/missing-references.json
lib/mpl_toolkits/axisartist/axislines.py
lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py

The axisartist has a concept of "axis_artist_helper", which computes
various computations to draw slanted/curved axises.  Confusingly,
`AxisArtistHelper` (and likewise `AxisArtistHelperRectlinear`) do *not*
define such helper classes; they are simply namespaces that hold the
`{AxisArtistHelper,AxisArtistHelperRectlinear}.{Fixed,Floating}` nested
classes which *do* define helpers.  More specifically,
`AxisArtistHelper.{Fixed,Floating}` act as abstract base classes for
`AxisArtistHelperRectlinear.{Fixed,Floating}` which are actually usable.
In order to slightly disentangle this move the actual helper classes to
the toplevel (as `_{Fixed,Floating}AxisArtistHelperBase` and
`_{Fixed,Floating}AxisArtistHelperRectlinear`), keeping the old
"purely namespace" classes around for backcompat.  (But …

Move AxisArtistHelpers to toplevel.

---

galleries/users_explain/figure/api_interfaces.rst

Fix typo in api_interfaces.rst

---

doc/api/next_api_changes/behavior/24661-AAMW.rst
lib/matplotlib/tests/test_colorbar.py
lib/matplotlib/tests/test_ticker.py
lib/matplotlib/ticker.py

Resolves issue where first and last minor ticks do not appear, as mentioned in issue #22331
- [ Yes ] Has pytest style unit tests (and `pytest` passes)
- [ N/A ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ N/A ] New plotting related features are documented with examples.
- [ N/A ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ N/A ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ N/A ] Release notes conform with instructions in  `next_whats_new/README.rst` or …

Plots first and last minor ticks #22331

---

lib/matplotlib/cm.py
lib/matplotlib/colors.py
lib/matplotlib/tests/test_colors.py

When registering a colormap you can use a different name than the `cmap.name` attribute now. This will set the colormap based on the registered name rather than `cmap.name`.
closes #5087
- [-] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [-] New plotting related features are documented with examples.
- [-] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [-] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [-] Release notes conform with instructions in …

FIX: Allow different colormap name from registered name

---

doc/api/next_api_changes/removals/25648-TS.rst
doc/api/toolkits/mplot3d/axes3d.rst
lib/mpl_toolkits/mplot3d/axes3d.py

Fixes #24689. Remove `Axes3D.set_frame_on` and `get_frame_on` from the codebase and from the link in the documentation.

Remove nonfunctional Axes3D.set_frame_on and get_frame_on methods.

---

lib/matplotlib/backends/backend_macosx.py
src/_macosx.m

We need to take the refcount of the figuremanager down when we close a window. (apparently dealloc on the Window isn't being called?) We could call this within the FigureManager_dealloc method, or just inline it here because close gets called during the FigureManager_dealloc already, so I decided this simplifies the code.
This was causing leaking figures before, per: https://github.com/matplotlib/matplotlib/issues/19769
and this PR does fix the issue on v3.5.x, but unfortunately there is a new leak that I introduced in https://github.com/matplotlib/matplotlib/pull/21790 :( There are no leaks when we `plt.show()` figures and fire up the GUI mainloop. However, when we are calling `savefig()` without ever showing we are now creating singleshot Timers in the app, but the callback never gets …

FIX: Decrease figure refcount on close of a macosx figure

---

galleries/examples/axisartist/demo_axis_direction.py
lib/mpl_toolkits/axisartist/axislines.py

- Show the curvilinear grid, without which the orientation of the ticks on the surrounding rectangular frame doesn't make much sense.
- Constrained layout works reasonably well enough, no need to set axes spacings by hand, but this exposed a bug where GridlinesCollection set paths to None (instead of an empty list), which breaks get_datalim (which calls len(paths)).
- Inline most intermediate constructs in setup_axes (avoiding lines like `extreme_finder=extreme_finder`).
- Many small style fixes.
Old: https://matplotlib.org/stable/gallery/axisartist/demo_axis_direction.html
New: 

Tweak axis_direction demo.

---

lib/matplotlib/backends/qt_compat.py
lib/matplotlib/tests/test_backends_interactive.py

After I closed #25673 because the root cause of that issue is in IPython mapping "qt" to "qt5agg", I realized that perhaps we could still do better about our error message.
While this change would not have actually resolved the question of "what is asking this to be qt5??", it would have at least not also raised the question of "why is qt6 not working? It is installed."
```python
>>> plt.switch_backend("qtagg")
...
ImportError: Failed to import any of the following Qt binding modules: PyQt6, PySide6, PyQt5, PySide2
>>> plt.switch_backend("qt5agg")
...
ImportError: Failed to import any of the following Qt binding modules: PyQt5, PySide2
```
Now only outputs the bindings which were actually tested, rather than all 4 …

Only print actually tested QT APIs when erroring

---

galleries/examples/axes_grid1/demo_axes_divider.py

Mostly cleanups to demo_locatable_axes_hard (and some misc. rewordings).
- No need to use the custom axes_grid1.mpl_axes.Axes subclass, plain axes are just fine; no need to use the axes_grid specific `toggle` API, we already call `set_tick_params(labelright=False)` which is enough.
- No need to provide a separate label kwarg when constructing ax_cb, subplot collision has been removed.
- Directly pass the locators when constructing the axes.
- Inline the definition of divider size components.

Cleanup demo_axes_divider.

---

doc/api/next_api_changes/deprecations/25774-AL.rst

Fix release note reference to pyplot.axis

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

Closes #25682 by preventing `Axes.fill_between()` from automatically adjusting the axes limits when using axes coordinates. When axes coordinates are not in use and thus no transformation is passed to `Axes.fill_between()`, then adjusting the axes limits is necessary, but previously, in some cases, a transformation might have been in use and using axes coordinates could have caused the axes limits to be resized improperly.
- [N/A] New features are marked with a `.. versionadded::` directive in the docstring and …

Prevents axes limits from being resized by axes.fill_between

---

.github/PULL_REQUEST_TEMPLATE.md

Condensed checklist by linking out to the related section of the contributing guide and removed stuff about building/passing tests since that's handled in the CI. Hoping that shortening it will improve usage of it. Also swapped out the gitwash link for the development guide.

condensed pull request template

---

doc/api/prev_api_changes/api_changes_3.3.0/deprecations.rst
doc/api/prev_api_changes/api_changes_3.5.0/removals.rst

Just a small thing I noticed while I was looking at #10063.

DOC: Fix minor typo in API change notes

---

doc/api/next_api_changes/deprecations/25781-AL.rst
galleries/examples/axes_grid1/simple_anchored_artists.py
lib/mpl_toolkits/axes_grid1/anchored_artists.py
lib/mpl_toolkits/axes_grid1/tests/test_axes_grid1.py

Needing to construct exactly just an anchored ellipse seems unlikely, and any customization will need accessing the underlying APIs (AnchoredOffsetbox, AuxTransformBox, Ellipse) anyways.  Mashing together the parameters of all three constructors is rather awkward, too.

Deprecate AnchoredEllipse.

---

galleries/examples/misc/anchored_artists.py

- Pass kwargs to DrawingArea to make params explicit; skip defaulted args.
- No need to effectively inline something very close to the definition of axes_grid1.anchored_artusts.AnchoredSizeBar (anyways, that's already demoed in the axes_grid1/simple_anchored_artists example); instead, directly construct the relevant artists in draw_sizebar. This also avoids mashing together the sep and pad/borderpad params, which are in different units.

Shorten anchored_artists example.

---

galleries/examples/text_labels_and_annotations/demo_text_path.py

- No need to set transforms on artists that will be added to an AuxTransformBox, as the latter will override the artist transform anyways.
- No need to rescale the image data to 0-1.

Cleanup demo_text_path.

---

.github/workflows/conflictcheck.yml

We currently have enough open PRs _with conflicts_ that the automated labels are no longer being added.
For example, #25787 had conflicts when #25607 was merged, but the logs show it was not ever considered as the action had only reached up to #22678. (Also, it was rebased before that could happen due to the action's retry delay, but the important thing is that the action didn't get to it yet.)
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl …

ci: Increase retry count on PR conflict check

---

lib/matplotlib/axes/_base.pyi
lib/matplotlib/axes/_secondary_axes.pyi
lib/matplotlib/axis.py
lib/matplotlib/axis.pyi
lib/matplotlib/colorbar.py
lib/matplotlib/pyplot.py

This was originally flagged during the review of #24976, but was deferred to a follow up because it required adjusting the docstring as well as type hints.
This is that follow up.
xref pydata/xarray#7802
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-a …

[DOC/TYP]: Allow any array like for set_[xy]ticks, not just list of float

---

doc/users/index.rst

Changed title from Users guide to User guide so that it's consistent with the nav bar.

Users guide->User guide

---

lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_polar.py
lib/mpl_toolkits/mplot3d/tests/test_axes3d.py

Closes #25789, see there for detailed discussion of what changed
This is addressing the extremely small (literally Unit of Least Precision, ULP) changes to how numpy computes sin/cos on main.
Through a combination of ratios of small numbers and relying on precise edge case behavior in tests of floats, we saw 3 cases where the miniscule difference compounded to test failures.
Two cases of projections having degenerate points where the edge case is inherently unstable:
- Mollweide projection is degenerate at the poles, we were lucky that the floating point operations precisely canceled
- Fixed by just not testing round tripping of the poles, as they _shouldn't_ necessarily round trip
- Formatting of polar coordinates
- Polar coordinates are degenerate at r=0, thus we were relying on …

[TST] Adjust tests to be more tolerant to floating point math operations being imprecise

---

doc/devel/development_setup.rst

The dev guide currently suggests that cloning your fork will automatically add the upstream remote, but I _think_ you have to add it manually.

DOC: add remote upstream

---

doc/devel/dependencies.rst
doc/users/prev_whats_new/whats_new_3.6.0.rst
galleries/users_explain/text/fonts.py

This PR  replaces usage of WenQuanYi Zen Hei with the Noto Sans CJK font, which is already used in other examples and still available on Homebrew. This provides a more convenient and consistent experience for macOS users. The changes were made to the relevant examples in the docs/galleries, and the documentation was updated to reflect the font change.

Replace usage of WenQuanYi Zen Hei by Noto Sans CJK

---

doc/api/toolkits/mplot3d/axes3d.rst
doc/users/next_whats_new/3d_plots_shareview.rst
lib/mpl_toolkits/mplot3d/axes3d.py
lib/mpl_toolkits/mplot3d/tests/test_axes3d.py

Replaces https://github.com/matplotlib/matplotlib/pull/17442
Closes https://github.com/matplotlib/matplotlib/issues/11181
3D axes can now be rotated together! Here's a video of the plots from the new baseline image being interacted with:
https://user-images.githubusercontent.com/14363975/236504480-c3ef233e-6adf-4ed3-a216-41e76916f30c.mp4

3D plots shared view angles

---

lib/matplotlib/_constrained_layout.py
lib/matplotlib/axes/_base.py
lib/matplotlib/mpl-data/matplotlibrc
lib/matplotlib/rcsetup.py

- The correct bound on margins value, documented in set_x/y/zmargin, is margin>-0.5.  Fix the docstring of margins() and the rc validators.
- The only constraints on tight/constrained layout margins is left<right and bottom<top, but values outside of [0, 1] can in fact be valid.  It would be annoying to enforce this at the rcparams level (this would force the user to update individual rcparams in a careful order), so just don't bother validating the values beyond "float".  (See discussion at https://github.com/matplotlib/matplotlib/pull/11231#issuecomment-388394543)
- Remove the somewhat overengineered _range_validators.
- Move the comment about the values of figure.constrained_layout.h/w_pad to the default matplotlibrc (in rcsetup.py it was far away from the actual values, which made …

Fix invalid range validators.

---

doc/api/next_api_changes/deprecations/25841-AL.rst
lib/matplotlib/axis.py

... as detailed in the deprecation notice.
Closes #25833.

Deprecate Tick.set_label{1,2}.

---

lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

This PR implements PolygonSelector.clear() to delete all vertices and enable visibility.

Fix PolygonSelector.clear()

---

lib/matplotlib/tests/test_constrainedlayout.py

Adds a memory leak test to make sure we don't bring the cyclic reference back in the future. Follow-up to #25853

TST: Add test for layoutgrid memory leak

---

galleries/examples/axes_grid1/demo_edge_colorbar.py

- The labels already default to being on; no need to call toggle_label(True).
- Tweak the figure size (to the default size) so that the "Bar" label isn't hidden by default (currently: https://matplotlib.org/stable/gallery/axes_grid1/demo_edge_colorbar.html)

Tweak demo_edge_colorbar.

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/cbook.py
lib/matplotlib/tests/test_cbook.py

This function used to be named `_safe_first_non_none` (#23751), and at v3.6.0 we have
```python
import matplotlib.cbook
arr = np.full(5, np.nan)
print(matplotlib.cbook._safe_first_non_none(arr))
```
```
nan
```
So this PR reinstates previous behaviour.  Currently on `main`, `_safe_first_finite` raises `StopIteration` when passed an all-nan array.
Fixes #18294 and fixes #24818.  The examples from both those issues now successfully produce empty plots.  The example from #18294 no longer throws the originally reported warning, but the example from #24818 does throw
```
/home/ruth/git_stuff/matplotlib/lib/matplotlib/axes/_axes.py:1185: RuntimeWarning: All-NaN axis encountered
miny = np.nanmin(masked_verts[..., 1])
/home/ruth/git_stuff/matplotlib/lib/matplotlib/axes/_axes.py: …
```

FIX: `_safe_first_finite` on all non-finite array

---

galleries/examples/axes_grid1/demo_axes_grid.py
galleries/examples/axes_grid1/demo_axes_grid2.py

- No point in tweaking the patch of the inner_titles because the patch is set to invisible (frameon=False).
- No need to toggle the colorbar labels on (they are on by default).
- Use clim=(min, max) instead of constructing an explicit Normalize instance.
- Group axes tweaking in set() calls.
- Remove unnecessary subplots_adjust.
- Some reformatting.

Cleanup demo_axes_grid{,2}.

---

doc/api/next_api_changes/deprecations/25889-AL.rst
galleries/examples/axes_grid1/demo_axes_grid.py
lib/mpl_toolkits/axes_grid1/axes_grid.py

It's a completely ad-hoc API which exists nowhere else, and can be easily replaced by more standard calls.  (Perhaps there should be a generic way for a colorbar to toggle its ticklabels without knowing the side on which they are, but that's another question, and it would probably not be spelled toggle_labels.)
Followup to #23595.

Deprecate CbarAxesBase.toggle_label.

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

I think this behaviour was not intended. Spotted the issue due to a question posted on Stackoverflow https://stackoverflow.com/questions/76195580/when-plotting-autocorrelation-function-plot-getting-ufunctypeerror
When using a list of integers in the `xcorr` function, the following lines:
https://github.com/matplotlib/matplotlib/blob/4bdae2e004b29d075f96a7dbbee918f7dfb13ed1/lib/matplotlib/axes/_axes.py#L2118-L2119
result in an under-the-hood downcasting to int, and as a result, the following error is thrown: 
```python
File "---/pythonProject/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 2120, in xcorr
correls /= np.sqrt(np.dot(x, x) * np.dot(y, y))
TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') 
according …
```

[BUG] Prevent under the hood downcasting of values

---

lib/matplotlib/figure.py

In looking at #25871 I noted that the documentation on colorbar was not clear about the default behavior.
The docstring from `ax` explains the default behavior of the `cax` parameter and nothing explained the default value of `ax`.

DOC: clarify how colorbar steals space

---

lib/matplotlib/testing/decorators.py

On WSL for image comparison tests, when placing the expected image in the results_images folder, symlinks are broken when accessing those images afterwards via the Windows interface. The symlink command does not fail, so the error logic does not catch it and we need to add a check for this special case. 
Before, when opening an *-expected.png file:
After, the image opens correctly.
- [N/A] *New Features* and *API Changes* are noted with a …

Fix broken symlinks for expected images on WSL

---

lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_rcparams.py

Resolves #25864 and adds tests for nargs_err in _axes.py and rcsetup.py. 
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

Adds tests for nargs_err in legend, stem, pcolorfast and cycler.

---

doc/users/next_whats_new/tick_labelfont_param.rst
lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/matplotlib/axis.pyi
lib/matplotlib/tests/test_axes.py

Closes #18425.  Added a `labelfont` kwarg to change tick label fonts conveniently, without changing the rest of the text.

Tick label font family via tick_params

---

lib/matplotlib/figure.py
lib/matplotlib/tests/test_colorbar.py

... which is the figure on which the colorbar is actually added, and not necessarily the figure on which colorbar() is called.
See the asterisk note in https://github.com/matplotlib/matplotlib/issues/25871#issuecomment-1546358063.

Check gridspecness of colorbars on the right figure.

---

lib/matplotlib/tests/test_transforms.py
lib/matplotlib/transforms.py

Passing an incorrect unit and no fig gave 'For units of inches or points a fig kwarg is needed' which really didn't make sense.
Will still return a ValueError, but with a more sensible message.
(I know that there are discussions if one should leave the final case out after check_in_list or not, but here it did nothing...)

Rewrite offset_copy for better error message

---

doc/devel/contributing.rst

Per call, changed the channel for incubator invite requests to community. Pulled this out of #25913 cause I was doing a lot there and didn't want this getting tangled up in those reviews.

changed incubator invite channel link to community channel

---

galleries/examples/text_labels_and_annotations/annotation_demo.py

The first example in the [Annotation Demo](https://matplotlib.org/devdocs/gallery/text_labels_and_annotations/annotation_demo.html#specifying-text-points-and-annotation-points) is very cramped, with text disappearing offscreen. I propose some minor changes to the script, shown in the before and after images below.
**Before:**
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/vmM4TBPy/old-figure.png' border='0' alt='old-figure'/></a>
**After:**
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/5tqFSvHj/new-figure.png' border='0' alt='new-figure'/></a>

DOC: Fix figure annotation example

---

lib/matplotlib/tests/test_transforms.py
lib/matplotlib/transforms.py

... by checking whether the inverse-transformed the query point is in the untransformed bbox.
Closes #12057.

Fix TransformedBbox.{,full_}contains.

---

.github/workflows/nightlies.yml

provision-with-micromamba is deprecated and setup-micromamba should be used instead, see [here](https://github.com/mamba-org/provision-with-micromamba#readme).
Supersedes #25951

Switch from provision-with-micromamba to setup-micromamba

---

doc/users/next_whats_new/auto_minor_tick.rst
lib/matplotlib/mpl-data/matplotlibrc
lib/matplotlib/rcsetup.py
lib/matplotlib/tests/test_ticker.py
lib/matplotlib/ticker.py

Pull request to resolve #14233 - Allow setting default AutoMinorLocator.
This PR is related to PR #16762 which is stale for a while and seems to abandoned by the developer. 
The behavior is similar to what is described in PR #16762 and Issue #14233 .
In this PR I include: 
- Validator of for the non-negative integers
- Validator for the new `rcParams` option `ndivs` for the number of minor ticks
- Automated tests for the new options

Allow setting default AutoMinorLocator 

---

lib/matplotlib/figure.py
lib/matplotlib/layout_engine.py
lib/matplotlib/tests/test_figure.py

- fix non-existing function `get_info()`
- complete docs
closes #25963

Fix get_constrained_layout_pads

---

galleries/examples/ticks/scalarformatter.py

Move everything to a single figure for better comparability and remove repeated code.
old: https://matplotlib.org/stable/gallery/ticks/scalarformatter.html
new:

Cleanup scalarformatter.py example.

---

.github/workflows/good-first-issue.yml

Who knows if this works? @melissawm feel free to update the text.

Add comment on issues marked 'good first issue'

---

lib/matplotlib/figure.py
lib/matplotlib/layout_engine.py
lib/matplotlib/tests/test_figure.py

Backport PR #25964 on branch v3.7.x (Fix get_constrained_layout_pads)

---

lib/matplotlib/axes/_axes.py

Issue https://github.com/matplotlib/matplotlib/issues/25758 was about a falsely documented default value in [`loglog`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.loglog.html) function and mentioned that this must be an issue with other functions as well. Another PR #25776 fixed this only for the loglog function. This PR addresses semilogx and semilogy as well.

Doc: Updates default value for nonpositve parameter for semilogx and semilogy

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

Closes #19120 
I've created an exception when you pass both singular and plural arguments of pyplot.scatter for edgecolor(s) and linewidth(s), I also created test suits for the exception.

Raise on plural scatter

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

Closes #25654
```python
start = np.array([np.datetime64('2012-01-01'), np.datetime64('2012-02-01'), np.datetime64('2012-01-15')])
stop = np.array([np.datetime64('2012-02-07'), np.datetime64('2012-02-13'), np.datetime64('2012-02-12')])
ax.bar([0, 1, 3], height=stop-start, bottom=start)
```
used to not assign a AutoDateFormatter to the y axis.  Now it does:

Fix bar datetime

---

doc/api/next_api_changes/behavior/25044-YI.rst
lib/matplotlib/axes/_axes.py

Always thank you developpers for maintaining Matplotlib!
Currently in `hexbin`, `linewidths` given to `PolyCollection` is hard-coded as `1.0`. In `pcolormesh` and `hist2d`, the default value respects :rc:`patch.linewidth` (default: `1.0`). To improve the consistency among the methods, in this very short PR I would like to suggest respecting `patch.linewidth` also in `hexbin`.
While this PR does not change the default behavior, do we need to have some additional tests?
The default `linewidth` in `pcolormesh` and `hist2d` may be not immediately visually noticeable because the default `edgecolors` value is `none`.  (In `hexbin`, `edgecolors` defaults to `face`.)
The default linewidths in `pcolor` and `tripcolor` are also hard-coded but as `0.25`. It may be also possible to respect …

Modify `hexbin` to respect :rc:`patch.linewidth`

---

lib/matplotlib/gridspec.py

It may not be the nicest API, but let's at least document it.
Closes #13109.

Document that GridSpec.get_subplot_params ignores gridspec.figure.

---

lib/matplotlib/tests/test_text.py

Closes #25907. Adds a test to check that the annotation `offset_fontsize` parameter actually offsets the text by the correct fontsize units. The unit distance was measured by comparing the fontsize against the number of points in `offset_points`

test annotate(textcoords=offset fontsize)

---

lib/matplotlib/tests/test_ticker.py
lib/matplotlib/ticker.py

closes #25945
I'd like to see if this breaks any existing test before I add a new one.
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

FIX: resolve an issue where no ticks would be drawn for a colorbar with SymLogNorm and ranging exactly from 0 to linthresh

---

galleries/examples/subplots_axes_and_figures/subfigures.py
lib/matplotlib/figure.py

Assuming we still leave is provisional in 3.8 per https://github.com/matplotlib/matplotlib/issues/25947#issuecomment-1557689476
This matches the notes at https://matplotlib.org/stable/gallery/subplots_axes_and_figures/subfigures.html#figure-subfigures

Add note that subfigure is still provisional to docstring

---

lib/matplotlib/backends/_backend_pdf_ps.py

This table contains a list of design/supported languages, which it doesn't make sense to keep in a subset.
I don't really know that there's an easy way to test, as the current known trigger is Times New Roman, which we can't ship here.
Fixes #24025
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) …

Drop metadata table when subsetting fonts

---

lib/matplotlib/backend_bases.py

Including whitespace seems to be the current behavior for agg and makes right-alignment works as it does.  It is also necessary to make e.g. the currently PR'ed rainbow_text (based on `annotation(..., xycoords=textobj)` implementation work.
Documenting the behavior is in particular useful for third-party backend implementers (mplcairo got this wrong previously).

Better document the semantics of get_text_width_height_descent.

---

lib/matplotlib/cbook.py
lib/matplotlib/figure.py

... by inlining _reset_locators_and_formatters and _break_share_link; and, in the case of twinned axes, relying on groupers allowing the removal of elements not in the grouper at all.  Also document that latter behavior.

Simplify delaxes.

---

.github/workflows/good-first-issue.yml

The wrapping makes for some pretty awkward formatting in the post so I think it's worth it to just strip it out and let github handle it for now.

removed wrapping from first-issue-bot

---

lib/mpl_toolkits/axes_grid1/axes_grid.py
lib/mpl_toolkits/axes_grid1/tests/test_axes_grid1.py

Closes #17069.
Not particularly elegant, but seems like the straightforward solution.  (The SimpleAxisArtist objects are the same as those that would be created by the mpl_axes.Axes adapter.)

Let AxesGrid support Axes subclasses that don't override axis().

---

.github/workflows/tests.yml

I missed an environment in #26021.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and …

ci: Skip PySide6 6.5.1 on another environment

---

galleries/users_explain/figure/backends.rst

Added subsubsection titles for the static and interactive backend tables, mostly cause I wanted anchors to more easily link these two.

subsubsection titles for backend tables

---

doc/devel/triage.rst

Document how to nominate someone (or your self) to get triage rights.

DOC: add steering council email to triage page + remove unactionable instructions

---

doc/api/index.rst
doc/api/sphinxext_figmpl_directive_api.rst
doc/conf.py
doc/users/next_whats_new/plot_directive_srcset.rst
doc/users/prev_whats_new/whats_new_3.3.0.rst
lib/matplotlib/sphinxext/figmpl_directive.py
lib/matplotlib/sphinxext/plot_directive.py
lib/matplotlib/tests/test_sphinxext.py
lib/matplotlib/tests/tinypages/conf.py
lib/matplotlib/tests/tinypages/index.rst
lib/matplotlib/tests/tinypages/nestedpage/index.rst
lib/matplotlib/tests/tinypages/nestedpage2/index.rst

Closes #25497
The `.. plot::` directive currently makes 100 dpi figures, which don't look good on hiDPI screens.  
This PR uses a new sphinx directive "figmpl" in the plot-directive to add a `srcset=` entry to the image tag to allow high resolution images (2x in this case).

DOC/BLD: plot directive srcset

---

src/py_converters.cpp

set() can throw an exception; we must check for that to properly get that exception propagated to the python side; otherwise we get a SystemError ("method ... returned a result with an exception set"). Example repro:
```
gca().add_collection(mpl.collections.LineCollection(rand(2, 2, 2), array=0))
```
(Here the C extension method receives a single tuple (rgba) color rather than an array of tuple (rgba) colors.)
I'd rather not explicitly test for the exception being raised (a ValueError) because if switching to pybind11 one naturally gets a broadcast of the scalar value into a correctly dimensionalized array; indeed mplcairo handles the above example just fine.
~Also fix an unrelated (harmless) typo in _tkagg.cpp: use a logical or instead of a bitwise or.~

Handle exceptions in numpy::array_view<...>::set().

---

.github/workflows/tests.yml
lib/matplotlib/backends/backend_qt.py

This makes some minor tweaks to avoid some issues that were caused by PyQt6 6.5.1. However, that version is broken on Ubuntu 20.04, so after confirming that this will fix these things, I will add a skip for it too. …

Improve Qt compatibility

---

galleries/examples/text_labels_and_annotations/rainbow_text.py

This pull request is to modify the rainbow_text() function to use annotate() method. Closes #25941

Modify rainbow_text() function to use annotate() function

---

lib/mpl_toolkits/axes_grid1/axes_grid.py

Essentially @QuLogic's comment at https://github.com/matplotlib/matplotlib/pull/26036#pullrequestreview-1456758408.

Further simplify AxesGrid._init_locators.

---

galleries/examples/text_labels_and_annotations/rainbow_text.py

Share more code between horizontal and vertical cases.
Show that x, y can use any transform (as for any text() call).
Standardize docs of "extra" properties.
Small doc rewordings.
followup to #25993.

Further cleanup rainbow_text example.

---

galleries/examples/text_labels_and_annotations/demo_text_path.py
lib/matplotlib/offsetbox.py
lib/matplotlib/offsetbox.pyi

In AnnotationBbox, it makes sense to allow passing xycoords and boxcoords positionally, because (similarly to annotate()) something like `AnnotationBbox(box, xy1, xy2, "axes transform", "offset points")` (for example) actually reads better than
`AnnotationBbox(box, xy1, xy2, xycoords="axes transform", boxcoords="offset points")` once you've seen this often enough and learn that the positional order is just (annotated_xy, box_xy, annotated_coords, box_coords).  (The alternative that's fully explicit would be
`AnnotationBbox(box, xy=xy1, xybox=xy2, xycoords=..., boxcoords=...)` but even that doesn't read too well because the xy kwargs names don't rhyme exactly with the coords names; or one could reorder the args to `AnnotationBbox(box, xy=xy1, xycoords=..., xybox=xy2, boxcoords=...)`, but …

Tweak AnnotationBbox coords specification.

---

doc/api/next_api_changes/deprecations/26780-AL.rst
lib/matplotlib/text.py

This key has been unused for ~8y (197fc9f).

Deprecate unused "frac" key in annotate() arrowprops.

---

doc/api/next_api_changes/behavior/26096-GL.rst
lib/matplotlib/cm.py
lib/matplotlib/tests/test_colors.py

Currently, the mask is ignored if a user passes in RGB(A) input arrays. This sets the alpha channel to 0 when any RGB(A) input is masked. This is relevant for RGB(A) data being used with pcolormesh. xref: https://github.com/SciTools/cartopy/pull/2166 where it will simplify downstream accounting for masks and alpha. …

FIX: Handle masked arrays for RGBA input with ScalarMappables

---

lib/matplotlib/markers.py
lib/matplotlib/tests/test_marker.py

Points with `CLOSEPOLY` or `STOP` codes have vertex values that are meaningless, but the marker bounding box calculation still counts them. This causes several markers to not be correctly centred as expected.
Fixes #26083

Correct bounding box calculation for text markers

---

lib/matplotlib/contour.py
lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

In general, using event.inaxes/event.xdata/event.ydata can be error-prone when there are overlapping axes, because only the topmost axes is the "in"-axes.
In the specific case of widgets/clabel, in particular, we can instead check whether an event occurred over the axes and if so compute xdata/ydata accordingly.  Doing so allows correct handling of widgets on axes for which there's also a twin axes on top of it.
Changes in the tests (other than the change in test_span_selector, which tests the functionality here) ensure that the synthetic button presses indeed occur on top of the desired axes (previously, do_event would directly set event.inaxes and we'd just believe that "as is").
Closes #10009 (by actually fixing the issue, not by documenting the limitation).
Also closes #25030. …

Let widgets/clabel better handle overlapping axes.

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

Closes #12926 
Around [line 4998 in _axes.py](https://github.com/matplotlib/matplotlib/blob/5f297631c2f295b2f3b52cfddeb33f02567a07f5/lib/matplotlib/axes/_axes.py#LL4998) two code paths diverge, depending on whether parameter `C` is given. The strict inequality between `accum` and `mincnt` in L5003 when `C == None` is not symmetric to the strict inequality at L5017, when `C != None`. This causes data points to become "hidden", when the number of data points (`accum`) is equal to `mincnt`.
*'Tis but a scratch*: changing `> mincnt` to `>= mincnt` was enough to get consistent hexbin plots.
<detail>
<summary>
hexbin result before
</summary>
</detail>
<detail>
<summary>
hexbin result after
</summary>
</detail> …

Fixes #12926 - inconsistency upon passing C in hexbin

---

doc/users/prev_whats_new/whats_new_0.99.rst
doc/users/prev_whats_new/whats_new_1.1.rst
doc/users/prev_whats_new/whats_new_1.2.rst

This PR closes #7199 
Changed 3 code example and it's plot on release 0.99
Change from above to 
to this:
to this 
Changed the release 1.1 
from this
to this:
Changed the release 1.2 
from 
to this：
- [N/A ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ N/A] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

Use classic style in old what's new entries

---

lib/matplotlib/backends/backend_webagg_core.py
lib/matplotlib/tests/test_backend_tk.py
lib/matplotlib/tests/test_backends_interactive.py

Test some currently untested GUI methods. (`get_window_title`, ~smoke test for `remove_rubberband`~.)
Replace unittest with pytest.
Add `get_window_title` method to webagg backend.
Remove tk-backend-marks (allowing tests to be run). Importability is checked in `_isolated_tk_test`.

Mnt: GUI tests

---

src/py_converters.cpp

These are triggered by `-Wparenthesis`, from #25850.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) …

Fix new warnings in compiled extensions

---

galleries/users_explain/figure/interactive.rst

In bb8058aaac96b682460b65bbe9dc59cdac8d6315 via #4779 I accidentally deleted the (illustrated) section on what the buttons on the default toolbar do.  I suspect that this was a bad rebase as I do not think I would have intentionally deleted this content.
This commit:
- restores the content as-was: git checkout b49973a04c9c2e42ace78de2650ca9569b2e91d4 doc/users/navigation_toolbar.rst
- fixes the paths to images (the files have moved around)
- copy the navigation content into interactive.rst and re-remove navigation_toolbar.rst
Partially addresses #25266.
Overlaps with #25925, sorry about that @satisf1ed .  A benefit of doing it "the old way" as restored here is that the images we are pulling are the exact files we use to generate the toolbars so they will never get out of sync. …

DOC: restore navigation documentation

---

lib/matplotlib/scale.py
lib/matplotlib/tests/test_scale.py

This reverts commit 041d4e02e60efef1df78d79e34ae0488d8b337ee, reversing changes made to fbfa28d522801dca0aa4e8d688085e4e900cc136.
Closes #26118

Revert "Merge pull request #24555 from parthpankajtiwary/symlog-warn"

---

doc/api/next_api_changes/behavior/25361-TAC.rst
lib/matplotlib/animation.py
lib/matplotlib/mpl-data/matplotlibrc
lib/matplotlib/tests/test_animation.py

closes #25608
Per https://github.com/matplotlib/matplotlib/issues/25608#issuecomment-1496915151 I do not think there is a way to make these keywords work in the context of a saved animation.
- [na] New plotting related features are documented with examples.
- [na] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`

API: forbid unsafe savefig kwargs to AbstractMovieWriter.grab_frame

---

lib/matplotlib/artist.py

Comment doesn't reflect actual state of function. Code was changed in [this commit](https://github.com/matplotlib/matplotlib/commit/bde55a03eba68226b387b931fd2601f22b807ffe) .

Remove outdated comment in `Artist.__getstate__`

---

lib/matplotlib/backends/_backend_tk.py

Copy-pasted from the NavigationToolbar2 implementation.
Closes #26124.

Add missing spacer in tk toolmanager toolbar.

---

doc/devel/development_setup.rst

Apparently on mac, python may not be added to path but python 3 is, so small note to flag that. (also demoing draft pr)

added note about python 3 to venv

---

.github/workflows/cibuildwheel.yml
doc/api/next_api_changes/development/25475-ES.rst

Upstream `cibuildwheel` dropped wheels for these systems. There are some good arguments for that related to support from NumPy (who has no universal2 wheels and will drop win32 soon) to ease of cross-compile with Meson (which we'll be porting to soon.)
This is up for discussion in the dev meeting tomorrow.

Stop building universal2 and win32 wheels

---

lib/matplotlib/tests/test_backend_tk.py
lib/matplotlib/tests/test_backends_interactive.py

Because now Azure broke that as well.

TST: xfail Tk test on Python 3.9 Azure macOS also

---

src/_macosx.m

Keep track of whether the left mouse is up or down so that we can set the proper open/closed cursor hand within set_cursor().
To test this, you can run the `mouse_cursor` example and click down and move the mouse in the "MOVE" section. Previously the cursor would be reset to the open-hand once the cursor is moved. With this update, the open/closed cursor depends on whether the left-button is depressed or not.
`python galleries/examples/widgets/mouse_cursor.py`
Suggested by @daniilS in https://github.com/matplotlib/matplotlib/pull/25412#issuecomment-1480043332 and this PR does help the macOS version of that PR as well.
- [-] Has pytest style unit tests (and `pytest` passes)
- [-] Documentation is sphinx and numpydoc compliant (the docs should …

FIX: macosx keep track of mouse up/down for cursor hand changes

---

.devcontainer/devcontainer.json
.devcontainer/setup.sh

This pull request adds a [GitHub codespaces](https://docs.github.com/en/codespaces) configuration for Matplotlib. With this PR, contributors can open a pre-configured development environment and get started with contributing to Matplotlib right away from their browser. I'm not sure if you can test it as it is, as I believe this needs to be merged to main before anyone is able to open a codespace from the Matplotlib repo.
Once this is merged, it will enable users to go to matplotlib/matplotlib or their own fork and choose "Create codespaces on `<branch>`":
This will open a browser window with a VSCode interface and a pre installed development environment built over an Ubuntu image. Users can then do
```
$ conda activate mpl-dev
$ python -m pip install -e .
```
After that you can run tests, …

Add codespaces configuration

---

.devcontainer/devcontainer.json

This should auto-expose the VNClite port for use in the browser.

MNT: add VNClte porte by default

---

doc/sphinxext/math_symbol_table.py
lib/matplotlib/_mathtext.py
lib/matplotlib/_mathtext_data.py

See https://github.com/matplotlib/matplotlib/issues/14766#issuecomment-1585671248
With this, the `\*corner` delimiters are no longer documented.  Not sure if they should be included in the parsers list of delimiters or what we mean by delimiters here? Options are to include them manually in the docs or in a different section.
It would be easy to include relational operators and arrows as well, but the discrepancy between those are quite big....
Also adds a few misc symbols to the documentation and makes double and triple integral signs drop the subscript to get correct rendering. Adds quadruple integral symbol `\iiiint` and Unicode symbol for already supported `\bigsqcup`.
- [N/A] "closes #0000" is in the body of the PR description to [link the related …

Start basing mathtext tutorial on mathtext parser

---

doc/devel/contribute.rst
doc/devel/document.rst
doc/devel/index.rst

Sorta went down a rabbit hole of changes here:
* per call, changed the channel for incubator invite requests to community (pulled this change out into #25929) 
* per call, changed contributing->contribute all over
* following the contributing->contribute, also did a lot of other case switching in contributing and documenting guides
* added redirects cause changed file names to match cases but this should maybe be reverted...(and I can just add redirects for the case instead)
* moved the sample data section out of contributing and into writing examples
* changed up the contributing preamble to make the code/not code a little more balanced

DOC: contributing and documenting clean ups + community for incubator invites 

---

.github/workflows/tests.yml
environment.yml
setup.py

The simple part of #26152 
No documentation as I see this as a way to get the tests to pass again and hopefully it is fixed before next release.

Restrict pyparsing version

---

lib/matplotlib/tri/_triangulation.py
src/_qhull_wrapper.cpp

This C-level variable is [deprecated in Python 3.12](https://docs.python.org/3.12/whatsnew/3.12.html#id4); the documented replacement there is for _initialization_ and there isn't really a [quick way to get it at runtime](https://github.com/python/cpython/issues/99872), so it seemed easier to fetch the value from Python. …

Avoid Py_VerboseFlag deprecation from Python 3.12

---

lib/matplotlib/cbook.py
lib/matplotlib/figure.py
lib/matplotlib/tests/test_backend_tk.py
lib/matplotlib/tests/test_backends_interactive.py
lib/matplotlib/tests/test_cbook.py

Account for a deprecation in CPython.

MNT: py312 deprecates pickling objects in itertools

---

doc/sphinxext/math_symbol_table.py

Using render_symbol as the sorting key works well enough for Hebrew, I just flipped it 'cause Hebrew is right to left. It also seems to work pretty OK for the Greek?

[Doc] alphabetize mathtext symbols by unicode

---

lib/matplotlib/animation.py

This partially fixes #8794, by dropping `-vframes` when using a temporary directory, as there is no need to limit frame count in that case.
It also changes to the recommended `-framerate` instead of `-r` for input.
~~I have not yet done the [suggested documentation changes](https://github.com/matplotlib/matplotlib/issues/8794#issuecomment-311048972). And~~ I think we should also [decide whether to warn or use an alternative method](https://github.com/matplotlib/matplotlib/issues/8794#issuecomment-1512412069) if _not_ using a temporary directory.

Fix ffmpeg framerates

---

lib/matplotlib/tests/test_image.py
lib/matplotlib/tests/test_legend.py

Closes #15054.  (Even if the baseline machinery gets updated, it seems reasonable to remove unnecessary texts from baselines.)
The other items in #15054 have already been handled elsewhere.

Add note to remove texts in baselines when they are regenerated.

---

doc/api/next_api_changes/deprecations/26190-AL.rst
lib/matplotlib/legend.py
lib/matplotlib/tests/test_legend.py

Supersedes and closes #24713.  See discussion there.

Deprecate removal of explicit legend handles whose label starts with _.

---

setup.py
src/_image_resample.h
src/_image_wrapper.cpp

Now that we're messing up with C++ image resampling... ;)
1st commit: Dedupe some C++ templates.
2nd commit: Make sure we don't use C++14 accidentally.  (Was originally: don't use C++11 accidentally.)
Edit: apparently running into a MSVC bug (per https://devblogs.microsoft.com/cppblog/expression-sfinae-improvements-in-vs-2015-update-3/); will look into it...

Dedupe some C++ templates

---

doc/devel/contribute.rst
doc/devel/development_setup.rst
doc/devel/development_workflow.rst
doc/devel/index.rst
doc/devel/triage.rst

<s>I added `setup environment` as a button and  merged {new feature, report bug}->{open issue} to keep things small. Also added a section/preamble in the contributing guide about opening issues to create an anchor for the button. 
I'm slightly ambivalent in a three buttons are process and one is infrastructure way, but it's also the thing I'm most often looking for when I go to contribute. There definitely needs to be a larger scale reorg, but this seemed like an easy enough start. </s>
Reworked the landing page so that navigation is grouped in cards and grids. Goal is to make the page a bit more skimmable, see last comment for example. 
My general proposal is keep the get connected/intro stuff and consolidate everything else w/ the document that discusses it- so optimally here I'd move …

reorganize contributing landing page

---

.github/workflows/tests.yml

There is a spot reserved for $PRE in the package installation command, but the environment variable doesn't appear to be set anywhere... Let's add it when we are doing our weekly scheduled runs to get other packages' pre-releases, not just the ones from pandas and numpy. Note this may cause more noise and be a little harder to track down where the issue is coming from, but seems like a good thing to do to test against other upcoming packages.

CI: Add pre-release installs to upcoming tests

---

.github/workflows/tests.yml

A small typo was introduced in #26197.

ci: Fix typo for nightly builds

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/figure.py
lib/matplotlib/legend.py
lib/matplotlib/tests/test_legend.py

Currently Figure.legend supposedly supports extra_args, forwarding them to the Legend constructor, but because all parameters of the Legend constructor except for the first two have become keyword-only, extra_args actually causes a TypeError to be raised when calling Legend(...) (try e.g. `plt.figlegend([], [], "right")`).  So just don't bother with extra_args anymore, check the case of "more than two positional args" in _parse_legend_args, and also fix test_legend_label_three_args, which was actually hiding the above exception via a mock and not really testing a relevant case anymore.

Factor out legend/figlegend nargs validation.

---

.github/workflows/clean_pr.yml
.pre-commit-config.yaml
doc/devel/development_workflow.rst

Added a branch protect rule to the pre-commit so that it complains if you try to commit directly to main. I figure folks who really need to push to main also know how to work around it. based on convo in call w/ @greglucas
Not quite sure this is the best way to handle the error message but figure we need to give folks a fix.
Is a replacement for #26170 which I'm not sure how I accidentally created directly on the repo.

precommit warns on main + instructions for fix

---

lib/matplotlib/text.pyi

The former location was deprecated in 3.7 (#23576), and accidentally removed earlier during some cleanup (#25787). …

Re-export textpath types in text

---

lib/matplotlib/_path.pyi
lib/matplotlib/cbook.pyi
lib/matplotlib/pyplot.py
lib/matplotlib/typing.py

These were all deprecated in Python 3.9 by PEP 585 and Generic Alias types (i.e., stuff like `typing.List` -> `list`).
Note, `Hashable`, and `Sized` are not deprecated, but they are aliases, so I moved them as well.
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#ne …

Avoid deprecated typing hints

---

doc/devel/index.rst
doc/devel/min_dep_policy.rst

Implements @rcomer's suggestion in #26196 that minimum dependencies makes more sense as part of the maintainer guidelines than installation guidelines so move the link there (until larger reorg). 
I'm not feeling the title `Minimum version of dependencies policy" but not sure about a shorter equivalent

moved minimum dependencies to maintainance section 

---

galleries/examples/ticks/tick-formatters.py
lib/matplotlib/ticker.py

- Collect all relevant descriptions in the summary text at the top
- Merge everything into one figure. The code should be mostly irrelevant for the example. The figure can serve as a standalone reference.
<s>Also closes 25967 by deleting the "Dollar ticks" example.</s> [Deferred]

Rewrite Tick formatters example

---

lib/matplotlib/scale.py
lib/matplotlib/tests/test_scale.py

Backport of #26126. Only conflict is that the `a` argument of `transform_non_affine` was renamed to `values`.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and …

Backport PR #26126 on branch v3.7.x (Revert "Merge pull request #24555 from parthpankajtiwary/symlog-warn")

---

lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_axes.py

closes #26194
This was a bit of a wild one in terms of the number of things that had to happen to cause this.

FIX: also copy the axis units when creating twins

---

lib/matplotlib/offsetbox.py
lib/matplotlib/tests/test_offsetbox.py

Fixes #24453
Calling `update_positions` before working out the bbox within `get_tightbbox` means constrained layout will get sensible numbers to work with so the example from the issue works as expected.  We can now also have constrained layout make space for the annotation if it is not contained within the axes:
```python
from matplotlib.offsetbox import AnnotationBbox, TextArea
fig, ax = plt.subplots(layout="constrained")
ab = AnnotationBbox(
TextArea("Some text", textprops={"size": 42}),
(1, 0.5),
xycoords="axes fraction",
box_alignment=(0.5, 0.5),
pad=0
)
ax.add_artist(ab)
fig.savefig("annotation_box.png", dpi=100)
```
I'm not sure where `get_window_extent` is used, but I updated that in the same way for consistency (and to get the test passing after I …

FIX: AnnotationBbox extents before draw

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/cbook.py
lib/matplotlib/tests/test_axes.py

Fix: pcolormesh writing to read-only input mask

---

lib/matplotlib/tests/test_triangulation.py
src/tri/_tri.cpp

Closes #25114.
Previously polygons generated by `tricontourf` have finished with a kind code of `2` (`MOVETO`) rather than `79` (`CLOSEPOLY`). This wasn't a problem for rendering but was for people doing something with the generated paths such as using `to_polygons()`.
The fix is to ensure that polygons generated by `tricontour` and `tricontourf` have their last vertex identical to their first vertex, and the correct `CLOSEPOLY` code. This is the same as that produced by `contour` and `contourf`.
Simple reproducer:
```python
import matplotlib.tri as mtri
x = [0, 1, 1, 0, 0.5]
y = [0, 0, 1, 1, 0.5]
z = [0, 0, 0, 0, 1.0]
triangles = [[0, 1, 4], [1, 2, 4], [2, 3, 4], [3, 0, 4]]
triang = mtri.Triangulation(x, y, triangles)
_, ax = plt.subplots()
cs = …
```

Use CLOSEPOLY kind code to close tricontourf polygons

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

FIX: pcolor writing to read-only input mask

---

lib/matplotlib/patches.py

Closes #26222 by adding missing parathesis to FancyBboxPatch docstring for correct type hinting. 

Update FancyBboxPatch docstring

---

galleries/examples/ticks/date_formatters_locators.py
lib/matplotlib/dates.py

The objects to locate ticks are called locators. They are defined in the modules ticker and dates.
xref https://github.com/matplotlib/matplotlib/pull/26254#pullrequestreview-1513072694

DOC: Clarify terminology

---

lib/matplotlib/figure.py
lib/matplotlib/tests/test_figure.py

Fixes #25511.  As discussed in that issue, sometimes a subfigure may be added on a gridspec that is also used for subplots, and it makes sense that the subplots would have larger wspace and hspace than the subfigures would.  So for `Figure.add_subfigure` and the `SubFigure` instantiation method, it makes sense to continue ignoring any white space settings on the passed gridspec.  This PR therefore only modifies the `subfigures` method, updating the subfigure positions after instantiation.
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-f …

FIX: wspace and hspace in subfigures without layout engine

---

galleries/users_explain/figure/figure_intro.rst

closes #26264
The three changes are:
- convert the tightbox to inches (via dpi_scale_trans)
- set the padding added in `FancyBboxPatch` to 0
- set the transform on `fancy` to be `fig.dpi_scale_trans` so at draw time it goes back to the correct pixels

DOC: ensure that the bounding box is scaled with dpi in example

---

doc/api/next_api_changes/deprecations/26241-AL.rst
lib/matplotlib/backend_bases.py

It can easily be inlined and is clearly a helper API for savefig (it explicitly copies the _is_saving private attribute), which has been made mostly unnecessary since 8159c81 (nearly 10y ago).

Deprecate FigureCanvasBase.switch_backends.

---

galleries/users_explain/animations/README.txt
galleries/users_explain/colors/README.txt
galleries/users_explain/index.rst
galleries/users_explain/text/README.txt

Close https://github.com/matplotlib/matplotlib/issues/26261.
We added manual TOC entries to get the depth=2 to work on users/explain/index.rst.  However, that adds two TOC entries to the sidebar.  Remove the manual entries and use `:includehidden:` in users/explain/index.rst.  Locally this works fine to remove the double entries and maintains the look of users/explain/index.html

Doc fix toc users

---

lib/matplotlib/tests/test_axes.py

This PR unbreaks CI by modifying the failing test.
Since the X and Y shape match the Z shape, they represent the centres of the boxes.  `pcolor` therefore needs to work out the locations of the box corners.  In this case, every other column of X and Y were masked, so `pcolor` can't reasonably be expected to do that.
It previously passed because our use of `np.hstack` stripped the mask off, so it was the same as if we'd not added the mask to begin with.  For the test data, there were sensible numbers under the mask but this would obviously not be true in general.  We now (since #25027) use `np.ma.hstack`.
https://github.com/matplotlib/matplotlib/blob/fff2a79ce22ab39bea95067d30438bfdbe47f560/lib/matplotlib/axes/_axes.py#L5834-L5837
The point of the test is to verify that we don't attempt to …

TST: simplify mask in pcolor writing to mask test

---

lib/matplotlib/axes/_secondary_axes.py
lib/matplotlib/tests/test_axes.py

The "orthogonal" axis is invisible, so we can just set the color of all
ticks, spines, and labels, regardless of orientation.
Note that the method is actually unused, untested, and could reasonably be lifted to the base class instead of only being provided for secondary axes, if we decide it's useful functionality (the new implementation doesn't use anything that's specific to secondary axes).

Simplify SecondaryAxis.set_color.

---

lib/matplotlib/axis.py
lib/matplotlib/tests/test_axes.py

Followup to #24334
Closes #26283.

Improve exception message for set_ticks() kwargs without labels

---

lib/mpl_toolkits/axes_grid1/inset_locator.py
lib/mpl_toolkits/axes_grid1/tests/test_axes_grid1.py

Closes #26287
Adds the plumbing to thread through the renderer from the axes to the calls which need it.
Added a test which fails on current main, but simply smoke tests that it doesn't raise (saving with bbox_inches=tight to a BytesIO)

Get correct renderer for axes_grid1 inset axes with bbox_inches=tight

---

doc/api/style_api.rst
galleries/examples/style_sheets/style_sheets_reference.py

While sharing the [Style sheets reference](https://matplotlib.org/stable/gallery/style_sheets/style_sheets_reference.html) gallery page to a colleague, I realized it's not self-contained in the sense that it doesn't explain how to use style sheets nor does it link to the corresponding [Customizing Matplotlib with style sheets](https://matplotlib.org/stable/tutorials/introductory/customizing.html#using-style-sheets) tutorial.
In this small expansion of the top docstring of `style_sheets_reference.py`, I added:
- a short repl code example for `plt.style.use` and a mention to `matplotlib.style.available` (which is used in the script, but it's quite buried)
- a link to the Customizing Matplotlib tutotorial (to the subsection on style sheet usage)
- [N/A] "closes #0000" is in the body of the …

[Doc] link style sheets reference to customization tutorial

---

doc/api/next_api_changes/deprecations/26294-AL.rst
lib/matplotlib/backend_bases.py
lib/matplotlib/backend_tools.py
lib/matplotlib/backends/_backend_gtk.py
lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/backend_qt.py
lib/matplotlib/backends/backend_webagg_core.py
lib/matplotlib/backends/backend_wx.py
lib/matplotlib/cbook.py

~These methods date back to when cbook.Stack also backed AxesStack, but now AxesStack is completely separate (#22114), Stack only backs the toolbar's home/forward/back buttons, and the methods don't make much sense in this class anymore.~
It's really not something we need to provide as public API.
Also, backends don't need to access the private _elements attribute.

Deprecate cbook.Stack.

---

lib/matplotlib/figure.py
lib/matplotlib/tests/test_figure.py

Closes #26290
I was between adding state to the PlaceHolder layout enigne and holding that state via a no-op sub-class.  Ended up going for the second, but could see the case for the first.
- [-] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [-] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [-] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

FIX: do not warn when calling tight_layout multiple times

---

galleries/examples/misc/demo_ribbon_box.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_image.py

If the image transform does not contain transData then setting the axes aspect to 1 will typically not help to make image pixel squares anyways.
Closes #14118.

Only change axes aspect in imshow if image transform is/contains transData

---

doc/api/next_api_changes/deprecations/26295-AL.rst
lib/mpl_toolkits/axes_grid1/inset_locator.py
lib/mpl_toolkits/axes_grid1/tests/test_axes_grid1.py

There's Axes.inset_axes which is an exact replacement without the need of actually understanding what an axes locator is, and which is also more general as one can also set a custom transform on inset_axes instead of being limited to the transAxes of a given parent axes.
Also the method had never been used in the library or examples, and a test was only ever added in 6dd30a2 (2022).

Deprecate inset_locator.InsetPosition.

---

doc/users/next_whats_new/contour_clip_path.rst
lib/matplotlib/contour.py
lib/matplotlib/contour.pyi
lib/matplotlib/tests/test_contour.py

Closes #2369.  Thanks to #25247, we now only need some very minor plumbing to expose _clip_path_ in `contour` and `contourf`.
```python
import matplotlib.patches as mpatches
x = y = np.arange(-3.0, 3.01, 0.025)
X, Y = np.meshgrid(x, y)
Z1 = np.exp(-X**2 - Y**2)
Z2 = np.exp(-(X - 1)**2 - (Y - 1)**2)
Z = (Z1 - Z2) * 2
patch = mpatches.RegularPolygon((0, 0), 5, radius=2, transform=ax.transData)
ax.contourf(X, Y, Z, clip_path=patch)
plt.show()
```
I'm unsure whether this should have an image test.  For now, I just went for the simplest test that fails against `main`.  I didn't add an example because we already have examples for both contours and clipping (the above, which is also the what's new entry, was adapted from …

ENH: clip_path keyword for contour and contourf

---

lib/matplotlib/contour.py
lib/matplotlib/tests/test_contour.py

Fixes #26308.
I'm not loving my test so if anyone can see a neater way to test this, that would be great!
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

FIX: labels at start of contours

---

lib/matplotlib/backends/backend_qtagg.py

In some cases, Qt will itself trigger a paint event after closing the file save dialog. When that happens, we need to be sure that the internal canvas is re-drawn. However, if the user is using an automatically-chosen Qt backend but saving with a different backend (such as pgf), we do not want to trigger a full draw in Qt, so just set the flag for next time.
Fixes #26272
I don't really know how to test this one. …

qt: Mark canvas for re-draw after savefig

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_agg.py
lib/matplotlib/figure.py
lib/matplotlib/tests/test_figure.py

We have for a long time (~2012) had an RLock on `RenderAgg` that was used in `FigureCanvasAgg.draw` to protect the shared cache of ft2font objects (the underlying c++ is very stateful and not thread safe). This lock was also implicitly protecting the mathtext cache when using the Agg backend.
However, given the recent improvements to the layout code there are now ways to call call `Figure.draw(renderer)` without acquiring this lock which leads to exceptions when using mathtext and a layout manager to save independent figures on different threads.
This bug also exists for the other backendends which use both the mathtext parser and the ft2font cache in the case of rendering texts as paths (in the vector backends).
The fix is to:
- pull the lock up to `RendererBase` so all renderer …

FIX: move the font lock higher up the call and class tree

---

doc/api/next_api_changes/development/25363-OG.rst
lib/matplotlib/backends/backend_qt.py
lib/matplotlib/backends/backend_qtagg.py
lib/matplotlib/backends/backend_qtcairo.py
lib/matplotlib/backends/qt_compat.py
lib/matplotlib/backends/qt_editor/_formlayout.py
lib/matplotlib/tests/test_backend_qt.py

Primarily to open the discussion and see if it passes for all QT versions on the CI.
As far as I can tell, 5.12 is the lowest version where there are wheels for Python 3.9. (conda-forge has 5.12.3 as the next after 5.9.2.)
One should maybe get rid of the `_to_int`-stuff as well, but I did not really follow everything with the bit-manipulation there.

Bump minimum QT5 version to 5.12

---

doc/api/next_api_changes/deprecations/26056-OG.rst
lib/matplotlib/__init__.py
lib/matplotlib/texmanager.py

Privatize TexManager.texcache

---

doc/users/next_whats_new/rcParams[legend.loc]_supports_float_tuple.rst
lib/matplotlib/rcsetup.py
lib/matplotlib/tests/test_rcparams.py

closes #22338 
I Added the ability to use int / float-tuple like kwarg legend(loc) for rcParams['legend.loc'], by creating a new validator for rcParams['legend.loc'].
This new change will help to a consistent and a uniform approach to using the legend.
Addresses both parts of the issue

[ENH]: int / float-tuple like kwarg legend(loc) for rcParams['legend.loc']

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/axes/_base.py
lib/mpl_toolkits/axes_grid1/tests/test_axes_grid1.py
lib/mpl_toolkits/mplot3d/axes3d.py

Right now parasite_axes just use self._parent_axes._get_lines as self._get_lines, but it can't update the axes unit when there are twin axes. Therefore, we need to provide axes=self as an extra args to handle this. We also need to change the callees to use axes in kwargs when provided.
The test creates a plot with twin axes where both axes have units. It then checks whether units are appended correctly on the respective axes. The code base without the modification fails the unit test whereas the modification makes it pass the unit test.
Revival of #22789 (I modified the OP's PR), integrating the changes at https://github.com/matplotlib/matplotlib/pull/22789#issuecomment-1378494923.
Closes #22714

Fix parasite_axes does not properly handle units

---

lib/mpl_toolkits/mplot3d/axes3d.py
lib/mpl_toolkits/mplot3d/tests/test_axes3d.py

`axes3d.scatter` handled only `c` function parameter with `cook.delete_masked_points`.
Add support for `color` parameter + test.

    FIX: axes3d.scatter color parameter doesn't decrease in size for non-finite coordinate inputs.

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_macosx.py
lib/matplotlib/tests/test_backends_interactive.py
src/_macosx.m

Newer macos frameworks now support blocks, so we can take advantage of that and inline our method call while creating and scheduling the timer all at once. This removes some of the reference counting and alloc/dealloc record keeping.
In the mac framework, an interval of 0 will only fire once, so we need to account for that code path as well, which is easier with the `repeat:` option now. (See the first test block, which failed when `interval=0` on the timer but we wanted it to keep firing)

MNT/FIX: macosx change Timer to NSTimer instance

---

lib/matplotlib/patches.py

Not used since https://github.com/matplotlib/matplotlib/pull/24603

Remove unused variables

---

lib/matplotlib/artist.py
lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py
lib/matplotlib/cbook.py
lib/matplotlib/font_manager.py
lib/matplotlib/markers.py

Primarily getting rid of redundant calls and optimizing order of if-elif-clauses based on default values.
The change in `stale` improves the performance of `stale` with about 20%. Each call is fast, but there are many calls...

More micro optimizations of plot

---

lib/matplotlib/image.py

See discussion at https://github.com/matplotlib/matplotlib/pull/18737/files#r506773948

Simplify outdated Image.contains check.

---

doc/_static/mpl.css
doc/_templates/sections/announcement.html
doc/conf.py

This was dropped when switching to the pydata-sphinx-theme. They have a method of adding an announcement, but because it's a pure text substitution, we can't have it automatically search like our old banner.
While the theme also supports loading from an http resource, that would mean writing some JavaScript instead of automatically creating this div at build time.
So override the theme component, and create the search link at build time.
I'm only a bit annoyed that the announcement overlays the normal navigation bar. I'm not sure it's really possible to avoid that without wrapping both in their own sticky `div`, but that would require overriding the entire theme layout, and that's a bit too much for my taste. …

DOC: Restore banner indicating docs are unreleased

---

lib/mpl_toolkits/axes_grid1/axes_rgb.py
lib/mpl_toolkits/axes_grid1/tests/test_axes_grid1.py

The same fix as the one recently applied to AxesGrid (#26020).

Support standard Axes in RGBAxes.

---

lib/matplotlib/patches.py

Came in through https://github.com/matplotlib/matplotlib/pull/25779 (was used in early versions, but not in the final).

Remove unused private method

---

lib/mpl_toolkits/axes_grid1/axes_grid.py

... based on the use of AxesX and AxesY in the axes_locators it creates in _init_locators.
Closes #16938 (IMO).

Clarify that ImageGrid requires limits-sharing.

---

lib/matplotlib/tests/test_ticker.py

Partly motivated by #26346 
An interesting thing is that `format_data_short` use `%-12g` as formatter so the output is always zero-padded to 12 characters. This came in through https://github.com/matplotlib/matplotlib/commit/bbbb267295aa9ead405572ea5fa6ffddd5d1e5bd as an attempt to make the cursor look better. However, it seems like no other `format_data_short`-method is doing this.

Add tests for LogFormatter.format_data and format_data_short

---

LICENSE/LICENSE_COLORBREWER

Per http://www.personal.psu.edu/cab38/ColorBrewer/ColorBrewer_updates.html the colormaps are now licensed under Apache V2.0.  This update has been made due to a possible incompatibility between Apache v1.1 and the GPL.
This change is consistent with the license in the colorbrewer (webapp) repository
https://github.com/axismaps/colorbrewer/blob/7d135fc4e19eda73f2eb1bf55fcdf4a04fe4881f/LICENCE.txt
Closes #26336

LIC: Update the license we bundle the colorbrewer colormap data with

---

lib/matplotlib/axes/_base.py
lib/matplotlib/sankey.py
lib/matplotlib/tests/test_cycles.py
lib/matplotlib/tests/test_pickle.py

Instead of relying on itertools.cycle (which is unpicklable, and leads to the axes property cycle being reset to the rcparams value upon unpickling), use a plain, trivially picklable, list-and-index representation (the property cycle is guaranteed to be finite because Axes.set_prop_cycle passes its argument through matplotlib.cycler, which already iterates through all cycler values for validation purposes).
Unfortunately this is not enough to really get rid of the get_next_color/get_next_color_func awkwardness, which also serves the additional purpose of not unnecessarily advancing the prop_cycle when it does not contain a "color" key and a color is requested.
Closes #26082.

Fix pickling of axes property cycle.

---

lib/matplotlib/artist.py

PyCharm has been warning that `Artist.figure` should be a `Figure|None`, not a `bool` as is set in this block.
Based on the previous section of code, I think setting the figure to stale (if the Axes was not already set stale, meaning the Artist was on a Figure *only*) was the intended behaviour.
This [code is 8 years old](https://github.com/matplotlib/matplotlib/commit/01c4b90f28330ab9fe76456bf706e3f9b02fdc81), so I don't expect @tacaswell remembers the intention here, but the commit message does say "marks the parent axes/figure as stale", which I think indicates this PR is what's intended.
- [n/a] …

Fix removal of Figure-level artists

---

doc/users/next_whats_new/macosx_windows_tabs.rst
lib/matplotlib/backends/backend_macosx.py
lib/matplotlib/mpl-data/matplotlibrc
lib/matplotlib/rcsetup.py
src/_macosx.m

Allow users to select how new figures are created when opening new windows. The default is to keep using the system preferences, but one can also select "tab" or "window" to override the default system preferences. I've called the new rcParam `figure.window_mode`, but definitely open to other suggestions. This is currently only enabled on macosx backend, but I could see it being possible on others in the future as well which is why I put it under `figure.*` and not under the more specific `macosx.*`, but I could also see how this would lead to confusion when users set this and don't get the desired result.
closes #13164
Example of the first figure opening in a new window, and the next two figures opening in a separate window with tabs.
```python
import …
```

ENH: macosx allow figures to be opened in tabs or windows

---

lib/matplotlib/axes/_axes.py

Most importantly, hist2d does not use imshow but pcolormesh.  Also a minor formatting fix.

Tweak hist2d docstring.

---

lib/matplotlib/contour.py

If I understand the code, the default _antialiased_ setting for filled contours is `False`.
https://github.com/matplotlib/matplotlib/blob/f08ff369c29e4d82afab483347c25fded28b3be6/lib/matplotlib/contour.py#L800-L802
This discrepancy in the docs pre-dates the recent changes to `ContourSet`.

DOC: contourf antialiased default

---

lib/matplotlib/tests/test_ticker.py
lib/matplotlib/ticker.pyi

This fixes typing errors since they don't (rightly) have these mock classes in the accepted list of types. But it also saves a bit of extra code as well.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) …

TST: Remove extra dummy Axis classes

---

lib/matplotlib/cbook.py
lib/matplotlib/cm.py
lib/matplotlib/colors.py
lib/matplotlib/tests/test_cbook.py

In this PR we apply some micro optimizations to improve the imshow performance. Benchmark:
```
Mean +- std dev: [main] 7.34 ms +- 0.07 ms -> [pr] 6.67 ms +- 0.11 ms: 1.10x faster
```
Notes:
- There is a fast path for the `MaskedArray` in case the mask is `False` (e.g. images without a NaN or Inf value)
- The `np.ma.masked_invalid` undoes the `shrink_mask` from `np.ma.masked_where`, but matplotlib applies it again. So it is faster to call `np.ma.masked_where` directly
- Another possible optimization is in `Normalize.autoscale_None`. There both the setting of `vmin` and `vmax` triggers `_changed`. It is faster to first set vmin and vmax (without triggering _changed) and then calling _changed. This would require a new method `set_vmin_vmax` or some other mechanism to avoid triggering …

Optimize imshow

---

lib/matplotlib/__init__.py
lib/matplotlib/_mathtext.py
lib/matplotlib/animation.py
lib/matplotlib/axis.py
lib/matplotlib/dates.py
lib/matplotlib/image.py
lib/matplotlib/legend.py
lib/matplotlib/text.py

``` python
if foo is None:
foo = mpl.rcParams["bar.foo"]
```
is a very common code pattern, so may be good to have a helper for it. ~Right now I only considered `legend.py`, but if this is an accepted idea there are many places where it can be used.~
(And, yes, the reason I started with legend is that it was defined as a local function there.)

Add _val_or_rc-function

---

lib/matplotlib/axis.py
lib/matplotlib/tests/test_axes.py

Closes #15785 (see https://github.com/matplotlib/matplotlib/issues/15785#issuecomment-837013566).

Emit xlim_changed on shared axes.

---

galleries/examples/misc/packed_bubbles.py
lib/matplotlib/dviread.py
lib/matplotlib/font_manager.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_cbook.py
lib/matplotlib/tests/test_image.py
lib/matplotlib/tests/test_scale.py

`flake8` is currently failing in CI with
```
E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
```
I think this is the relevant change: https://github.com/PyCQA/pycodestyle/pull/1086
In the bubble example, it looks like the type check was there just to make sure we get an array-like out of the method.  We can achieve that with the _keepdims_ keyword.
Everywhere else I just replaced `==` with `is` as that preserves existing behaviour so seems safest.  Possibly some places could have used `isinstance` instead but I do not know if there is an advantage to changing it to that (and I also do not know those parts of the code well enough to make that call).

Fixes for pycodestyle v2.11

---

src/_macosx.m

I noticed this when reviewing some other PR at some point. It doesn't have a huge impact because `None` is a singleton that is never freed, but maybe has consequences in other implementations (PyPy?). …

macos: Don't leak None in Timer cleanup

---

lib/matplotlib/_mathtext.py

Fix pyparsing version check

---

environment.yml
lib/matplotlib/tests/test_mathtext.py
lib/matplotlib/tests/test_text.py
setup.py

Closes #26152
May require backporting a portion of #26198 to the 3.7 branch if we wish to have a 3.7.3.
(specifically the part where token, placeable, and auto_delim are excluded from `setName`)

MNT: Unpin pyparsing, xfail error message tests for pyparsing 3.1.0

---

doc/users/next_whats_new/mathtext_features.rst

Missed adding the next new entries for the added mathtext features, [substack](https://github.com/matplotlib/matplotlib/pull/26151) and [middle](https://github.com/matplotlib/matplotlib/pull/26333) delim.

Add next_whats_new entries for mathtext features

---

doc/sphinxext/gallery_order.py
galleries/plot_types/3D/README.rst
galleries/plot_types/README.rst
galleries/plot_types/arrays/README.rst
galleries/plot_types/basic/README.rst
galleries/plot_types/stats/README.rst
galleries/plot_types/unstructured/README.rst

Changed the plot type headings of the plot type gallery sections so that they'd hopefully be more informative and also generally more consistent in that for the most part they're describing the type of data assumed by each batch of functions. I also tried to have most of the section subheadings follow the same format of describing the assumptions of the structure of the data. Moved stats to be near the discrete/linear plots and unstructured next to gridded to keep the larger structure 0/1D, 2D, 3D. 
I'm not completely feeling this in terms of general audience friendly (attn: @esibinga) but think this provides a more useful side panel/toc for navigation.

[DOC]: improve consistency of plot types gallery

---

doc/api/next_api_changes/deprecations/26444-ES.rst
lib/matplotlib/_mathtext.py
lib/matplotlib/table.py
lib/matplotlib/tests/test_dviread.py
lib/matplotlib/tests/test_table.py
lib/matplotlib/tests/test_ticker.py

There are 3 changes here:
- When iterables were added to `Table.auto_set_column_width` in #6047, the test added a string. Typing correctly points out that that is not accepted, and in fact it does not do anything (as shown in the test image) because column keys are ints, not strings, so the automatic width calculation is applied to nothing. So deprecate accepting random types here.
- `Fonts.used_characters` was removed in #22204, but `Fonts.get_used_characters` (which just returns that attribute) was not. This is private and can be removed directly, AFAICT.
- The `find_tex_file` monkey patch in the test returned the wrong type, which doesn't technically break anything, but was confusing when comparing with the type stubs.
- [n/a] "closes #0000" is in the body of the PR description to …

Fix some bugs found by typing

---

lib/matplotlib/axis.py
lib/matplotlib/tests/test_axes.py

Closes https://github.com/matplotlib/matplotlib/issues/26398
This now warns with
```
/Users/jklymak/matplotlib/testit.py:11: UserWarning: set_ticklabels should only be used with set_ticks or a FixedLocator.
ax.set_yticklabels(map(str, ticks))
```
```python
from matplotlib import cm
for adjust in [True]:
fig, ax = plt.subplots(figsize=(5, 3))
data = [33.4, 33.5, 33.6]
ax.plot(data, data)
ticks = [32.8, 33., 33.2, 33.4, 33.6, 33.8]
ax.set_yticklabels(map(str, ticks))
fig.subplots_adjust(top=0.96)
```

WARN: more direct warning ticklabels

---

lib/matplotlib/cbook.py

Due to NumPy's main namespace being changed in https://github.com/numpy/numpy/pull/24316, here I update warning imports.

ENH: Update numpy exceptions imports

---

lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_colors.py
lib/matplotlib/tests/test_image.py

reference #26422 
These aliases are among the more confident to be removed from numpy, and their replacement is already more commonly used in the codebase, so this is improving consistency and future proofing.

Remove soon to be deprecated nan/inf aliases

---

lib/matplotlib/tests/test_text.py
lib/matplotlib/text.py

The unpacking (`x, y = xy`) is safe wrt. units (we already perform the same unpacking later when actually computing coordinates) and prevents later mutation of the input array from affecting the artist (or the OffsetFrom instance), which is consistent with other artists.
While at it, also inline OffsetFrom._get_scale, which is a one-liner.
Closes #17566; supersedes #17567.

Make annotate/OffsetFrom unaffected by later mutation of coordinates.

---

lib/matplotlib/_type1font.py
lib/matplotlib/backends/backend_pgf.py

Converts some `%` format strings into f-strings.
This is needed because of numpy/numpy#22449, which makes numpy scalars have a repr with e.g. `np.float64(3.0)` rather than just `3.0`.
Thus the `!r/!a` was left off in the conversion to f-string as that is the actual required change.
closes #26460 xref #26422

MNT: Adjust for upcoming numpy repr changes

---

doc/api/index.rst
lib/matplotlib/pylab.py

- switch to Axes interface / pyplot interface terminology (#26388)
- Reduce the interface description to very compact two-sentence descriptions and refer to the interface page for everything else.
The focus here is to point the users to relevant API resources for the respective interfaces, not to discuss these interfaces in detail. The latter is the task of https://matplotlib.org/devdocs/users/explain/figure/api_interfaces.html and I will add some missing pieces there in a follow-up PR.

Restructure interface section of API Reference index page

---

doc/api/next_api_changes/deprecations/26472-AL.rst
lib/matplotlib/backend_bases.py
lib/matplotlib/pyplot.py
lib/matplotlib/testing/conftest.py
lib/matplotlib/tests/test_backend_bases.py
lib/matplotlib/tests/test_backends_interactive.py
lib/matplotlib/tests/test_pyplot.py

Do not `close("all")` figures on (allowable) backend switches, e.g. between qt5agg and qt5cairo, or qt5agg and notebook.
The NonGuiException message had to change, as the backend returned by get_backend() may no longer match the actual canvas class.
Closes #15913.  (Redo of #15918; see also #14471.)

Do not close figures on backend switch.

---

doc/api/next_api_changes/deprecations/25784-ES.rst
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/rcsetup.py
lib/matplotlib/tests/test_backend_ps.py

This automatic selection is not very good, and it's probably better for the user to explicitly select a paper type.
Additionally, I've corrected an inconsistency in EPS, which used the paper size _only_ if not using `usetex` and no distiller. In the latter cases, the paper size is ignored and the distiller is told to use `-dEPSCrop` instead. So this makes the former case consistent with those.

Deprecate papersize=auto in PostScript

---

.devcontainer/setup.sh

The setup.sh script has been updated to that the micromamba installation command does not wait for stdin (see https://github.com/mamba-org/micromamba-releases/blob/main/install.sh)
This was working before, so my understanding is that this broke due to the way codespaces is configured upstream.
- [N/A] *New Features* and *API Changes* are noted with a …

Fix codespaces setup.sh script

---

lib/matplotlib/axes/_base.py
lib/matplotlib/transforms.py
lib/mpl_toolkits/axes_grid1/axes_size.py
lib/mpl_toolkits/mplot3d/axes3d.py

A bunch of fixes, primarily triggered by missing references.
The paths in get_xlim and get_ylim is to make it link in 3D: https://matplotlib.org/stable/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.get_xlim.html#mpl_toolkits.mplot3d.axes3d.Axes3D.get_xlim

[DOC] Documentation fixes

---

doc/conf.py

#26472 triggered these warnings to resume, so this quiets them again. I got rid of the linux specific warning since this is more broadly applicable. 
attn @ksunden

[DOC]: filter non-gui backend warnings when building docs

---

lib/matplotlib/colors.py

Followup to https://github.com/matplotlib/matplotlib/pull/26449#discussion_r1284177392
Closes #26446 
**Major correction: Clipping does not affect masked values**
This can be seen in the following code, where the mask is reapplied
https://github.com/matplotlib/matplotlib/blob/f800bf61cd863a3d8b4d60268b924a4300ee1815/lib/matplotlib/colors.py#L1936-L1939
This code has been unmodified since 2016 and has been the same even before. I therefore believe it's better to just adapt the documentation to the existing behavior.
**Other changes**
Better explanation of the returned values for "outside" inputs and their interplay with colormaps.

Clarify behavior of norm clipping

---

.github/workflows/cibuildwheel.yml
doc/api/next_api_changes/development/26443-TAC.rst
pyproject.toml

closes #26438
I think that this is a generically bad idea (see https://pypackaging-native.github.io/meta-topics/user_expectations_wheels/ for longer comments on this), but given the currently low cost of enabling this there is no good reason to not do this.
I opened the PR so later when I say it was a bad idea at least I am to blame for it ;)

BLD: stop skipping musl wheel builds

---

lib/matplotlib/artist.py
lib/matplotlib/container.py

Original purpose was to not call pchanged or set stale to True if the value did not change (some set-methods already do this). 
However, I found some doc inconsistencies so did a bit of search-and-replace as well...

Only do pchanged and set stale when value changes + doc consistency

---

doc/api/next_api_changes/deprecations/26469-AL.rst
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_pgf.py
lib/matplotlib/tests/test_backend_pdf.py
lib/matplotlib/tests/test_backend_pgf.py

... because 0-page pdfs are not valid pdf files.
Explicitly passing keep_empty=False remains supported for now to help transitioning to the new behavior.
I also delayed file creation in backend_pdf.PdfPages as that seems simpler than re-deleting the file at closure if needed.  I further dropped `__slots__` as the micro-optimization of these classes seem pointless (backend_pdf.PdfPages is wrapping a PdfFile object which is much larger anyways).
Closes #11771 (see https://github.com/matplotlib/matplotlib/issues/11771#issuecomment-1589348758).  Whether we want https://github.com/matplotlib/matplotlib/issues/11771#issuecomment-440301925 too is another question.

Deprecate PdfPages(keep_empty=True).

---

doc/api/next_api_changes/behavior/26479-ES.rst
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/mpl-data/matplotlibrc
lib/matplotlib/rcsetup.py
lib/matplotlib/tests/test_backend_ps.py

We already set the bounding box to coincide with the figure size, but setting an overall paper size can sometimes cause the resulting file to be cropped by the viewer.
We additionally need to pass this through to the distiller.
Fixes #16657

ps: Add option to use figure size as paper size

---

doc/conf.py

top of the build prints the sphinx version, figure it may as well also print the pydata sphinx and mpl-theme versions to help with debugging.

[DOC]: print pydata sphinx/mpl theme versions 

---

lib/matplotlib/legend.py
lib/matplotlib/tests/test_legend.py

The `consider` argument from `Legend._find_best_position`  can be removed, as no-one ever uses it and this is a private method.
Because of an early `return`, the warning that `loc='best'` is slow can sometimes not be triggered, so ensure that is the case.
Finally, improve the test for this warning. By patching the timer instead of using actually large data, we can both:
1. speed up these tests (~7.5s vs <0.2s for both), and
2. consistently trigger the warning even on systems which are fast (such as the M1 systems on Cirrus #24597.)
Also, copy the test data from `test_legend_auto3`, which correctly hits all candidate locations for the 'best' legend locator without having to fill up the entire Axes with data. …

Improve legend(loc='best') warning and test

---

doc/conf.py

Replaces Google Analytics with Plausible. The Plausible service instance is provided by the Scientific Python project. …

Add plausible analytics to the documentation pages

---

lib/matplotlib/tests/test_axes.py
lib/mpl_toolkits/mplot3d/tests/test_axes3d.py

This is [from a Fedora build](https://koji.fedoraproject.org/koji/taskinfo?taskID=104668745), but it also corresponds with Cirrus failures on ARM in #24597.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) …

TST: Increase some tolerances for non-x86 arches

---

lib/matplotlib/backend_bases.py

... as %pylab is deprecated, and %matplotlib is really the relevant mode here.

Replace reference to %pylab by %matplotlib.

---

lib/matplotlib/widgets.py

Mostly, span_stays has been removed; the rest is reformatting.

Update/tweak SpanSelector docs.

---

lib/matplotlib/_api/__init__.py
lib/matplotlib/tests/test_api.py

Fill in "None" dims *from the end* with the letters N, M, L, K, ... so as to get e.g. "(N, 2)", "(M, 2, N)", "(L, M, N)", etc.

Tweak shape repr in _api.check_shape error message.

---

lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/mplot3d/tests/test_axes3d.py

- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines
So far higher level APIs like `plot_surface` and `plot_trisurf` ensure the input for calling `Poly3DCollection` is valid so usually we won't trigger the bug.
By inspecting test code coverage report, this part of code has never been tested. …

Fix input check in Poly3DCollection.__init__

---

lib/matplotlib/path.py

That master_transform is ignored is clear looking at the implementation in _path.h (the `if (Ntransforms)` branch drops master_transform; compare with the implementation of point_in_path_collection).  One can also compare
```
from matplotlib.path import *; from matplotlib.transforms import *
get_path_collection_extents(
Affine2D().scale(2, 3), [Path([(1, 2), (3, 4)])],
[], [(0, 0)], IdentityTransform())
get_path_collection_extents(
Affine2D().scale(2, 3), [Path([(1, 2), (3, 4)])],
[IdentityTransform()], [(0, 0)], IdentityTransform())
```
(We can discuss whether the behavior makes sense, especially as point_in_path_collection has the opposite behavior; it may be a bug, I'm just documenting the actual behavior.)

Clarify interaction between params of get_path_collection_extents.

---

lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/mplot3d/tests/test_axes3d.py

(cherry picked from commit 267b7c08bf39ea2d40ff348e6d7eddf218e94c74)
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docst …

Backport PR #26532: Fix input check in Poly3DCollection.__init__

---

lib/matplotlib/pylab.py

NumPy added abs in 1.26, which we don't want when we import * from it.
Fixes #26553

Remove NumPy abs overrides from pylab

---

doc/conf.py

(cherry picked from commit 48e28914d02dc5d50e3945b29f3d83da645b765f)

Backport PR #26493: Disable ``add_html_cache_busting`` on Sphinx 7.1+

---

lib/matplotlib/_mathtext.py
lib/matplotlib/tests/test_mathtext.py

Fix mathtext mismatched braces

---

.github/workflows/cygwin.yml

Since there are no contourpy wheels, it must be built from source, and pre-packaged ninja is better than trying to build from sdist. This was always done, but broke when contourpy switched to Meson. …

Add ninja to Cygwin builder

---

doc/devel/index.rst

Following on from #26201, this adds a bullet link on the contribute landing page out to the set up part of the contributing guide. Also cleans up the styling in the new contributor section cause it feels really busy on mobile. 
attn: @melissawm

[DOC]: codespace link in contribute index

---

.gitignore

Folder isn't in .gitignore and our docs recommend `git commit -a` and I think this may be the cause of some really messy commit trees :/

MAINT: add __pycache__/ to .gitignore

---

lib/matplotlib/tests/test_backends_interactive.py

This seems to have been accidentally duplicated in 7e2d904 (perhaps a merge problem).

Deduplicate test for toolbar button icon LA mode.

---

lib/matplotlib/dviread.py
lib/matplotlib/tests/test_animation.py
lib/matplotlib/tests/test_backend_webagg.py
lib/matplotlib/tests/test_backends_interactive.py
lib/matplotlib/tests/test_matplotlib.py

mypy does not recognize the latter [1], and there is a typing failure on Windows because of `os.geteuid`.
[1] https://github.com/python/mypy/issues/13002
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) …

Use sys.platform over os.name

---

lib/matplotlib/backend_tools.py

The property must be defined to use self.set_figure as the setter, and not the other way round; otherwise, subclasses that override set_figure (such as ToolToggleBase) won't override the setter on the property.

Fix ToolBase.figure property setter.

---

.github/workflows/tests.yml

We try to install PyGObject everywhere, but this doesn't work because GTK itself is not available from PyPI.
We were discussing this relatedly on the call yesterday. Let's see if this works. …

ci: Install GTK4 from brew on macOS

---

lib/matplotlib/ticker.py

No change to logic, only rewriting things in a slightly more compact manner, and making the `len(majorlocs) < 2` case tested more explicitly than via an IndexError.
Noticed while looking at #26484.

Cleanup AutoMinorLocator implementation.

---

lib/matplotlib/axes/_base.py
lib/matplotlib/figure.py
lib/matplotlib/tests/test_axes.py

Properly disconnect machinery when removing child axes.

---

lib/matplotlib/axis.py
lib/matplotlib/tests/test_axis.py

Fixes #26588 following @anntzer's suggestion at https://github.com/matplotlib/matplotlib/issues/26588#issuecomment-1691130518.  The example code from https://github.com/matplotlib/matplotlib/issues/26588#issuecomment-1691327295 now produces
Is there a better place to put the test?  I wasn't expecting to create a new module...
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and …

FIX: array labelcolor for Tick

---

lib/matplotlib/axes/_base.py
lib/matplotlib/axis.py

[DOC] Clarify some tick-related docstrings

---

lib/matplotlib/figure.py

The space before : is important.

[Doc] Improve set_layout_engine docs

---

lib/matplotlib/axes/_base.py

If I understand things correctly, this will provide information to the property tables and avoid "unknown".

[Doc] Add ACCEPTS for some Axes set methods

---

lib/matplotlib/pyplot.py

Replaced list with tuple in pyplot for axes

---

galleries/examples/shapes_and_collections/ellipse_demo.py

While technical possible, this is an anti-pattern IMHO. We should keep Axes creation and customization separate.
Extracted from the deferred #14411.

[MNT] Do not configure axes properties via subplots(..., subplot_kw={...})

---

lib/matplotlib/backends/backend_qt.py

setQuitOnLastWindowClosed(True) should be equivalent to lastWindowClosed.connect(quit), but is more introspectable (e.g. third-parties can check the value of quitOnLastWindowClosed()).
AFAICT the code used lastWindowClosed.connect(quit) because it dates back to Qt3, where setQuitOnLastWindowClosed did not exist yet.

Use standard method for closing QApp when last window is closed.

---

lib/matplotlib/axes/_base.py
lib/matplotlib/tests/test_category.py

Closes #26596
Ensures that ndarrays can be passed to  later on. In this particular case, we know that we expect a single value.

Squeeze post-converted values when validating limits

---

galleries/examples/images_contours_and_fields/contourf_demo.py

Removed origin keyword as it is not required in the provided examples.
https://matplotlib.org/devdocs/gallery/images_contours_and_fields/contourf_demo.html

Removed unnecessary origin keywords

---

lib/matplotlib/_mathtext.py
lib/matplotlib/_mathtext_data.py
lib/matplotlib/backends/backend_agg.py
lib/matplotlib/mathtext.pyi
lib/matplotlib/textpath.pyi

This adds typing to all of `_mathtext.py` and cuts down `mypy --strict` errors for it from >400 to 14 (all but one of which are pyparsing issues). As a proof of concept, this applies all type hints _inline_.
There is also some refactoring to avoid re-using variables with mixed types, and adding more explicit types for some `SimpleNamespace`. These could be split into separate PRs if desired, but are separate commits at least.
It is based on #26540. …

TYP: Add typing on mathtext internals

---

doc/api/gridspec_api.rst
doc/api/next_api_changes/behavior/26634-TH.rst
galleries/examples/subplots_axes_and_figures/auto_subplots_adjust.py
lib/matplotlib/figure.py
lib/matplotlib/figure.pyi
lib/matplotlib/gridspec.py
lib/matplotlib/gridspec.pyi

Logically, this belongs more to the gridspec layout than to the figure.
There is no API breakage involved, because `matplotlib.figure` reimports `SubplotParams`. Do we nevertheless want an API change note?

[MNT] Move SubplotParams from figure to gridspec

---

lib/matplotlib/__init__.py
lib/matplotlib/tests/test_axes.py

I accidentally broke #25702 trying to rebase it 🤦‍♀️ so this is my amends (and for future I will make a new branch/PR for these sorts of rebases). @jovianw's PR makes it so that **kwargs are also passed through `_sanitize_sequence` and adds a test. 
This pr supercedes #26577, which is why I touched it. 
Let me know if it's considered enough of a new feature to need a what's new.

Added sanitize_sequence to kwargs in _preprocess_data

---

.github/PULL_REQUEST_TEMPLATE.md

Discussion in #26684 makes the point that folks aren't really reading the big block of text comment, so here I'm breaking it up into the sections each part of the comment is related to and deleting the information that's also in the checkbox. The stuff about the title can also be moved into the checkbox. I also maybe wouldn't object to reducing this further and moving some of this content into the contributor guide.

PR template: shorten comment and pull up top

---

.github/PULL_REQUEST_TEMPLATE.md

Looks like documentation guidance has been updated more recently than the PR template.  The links are currently all getting redirected to the top of the doc guidance page.

Update PR template doc links

---

lib/matplotlib/backends/backend_pgf.py

If pgf.texsystem isn't installed, then self.latex will not be created *at all* by _setup_latex_process, and we thus cannot access self.latex.args[0], but must instead read the rc value again.  To make this clearer, move the error handling into _setup_latex_process, instead of having it outside.
No test because that'd require setting up a test env where pgf.texsystem is explicitly *missing* (or go through lots of mocks), which seems not worth it.
This is (I think) the origin of the AttributeError in #26551.

Fix error generation for missing pgf.texsystem.

---

setup.py

Pre-emptively pinning away from the major API break for the last bugfix release of the 3.7.x series. …

Pin NumPy below v2 for 3.7.x

---

.github/workflows/cibuildwheel.yml

We let this go for a while, so automated backports were failing.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstring …

Backport cibuildwheel updates to v3.7.x

---

lib/matplotlib/contour.py

closes #26531
In https://github.com/matplotlib/matplotlib/issues/26531#issuecomment-1679628241 @anntzer postulated that a better fix is possible, I'm open to one, but this works.
Note that I think there still could be some problems if updating vlims later on (this only addresses the setting in `__init__`).
It was also suggested to add an atomic update of both vmin and vmax (which only triggers `changed` once), but that is not yet implemented.

Avoid checking limits when updating both min and max for contours

---

lib/matplotlib/axis.py

In responding to https://github.com/matplotlib/matplotlib/pull/26410#discussion_r1317078471
I discovered a single instance in a docstring of using the type-hint style `ArrayLike`
as opposed to the norm of using `array-like`, introduced (by me) in #25798
This just swaps that out so that the docstrings are consistent.

DOC: consistency in docstrings of formatting of array-like

---

doc/missing-references.json
lib/matplotlib/figure.py
lib/matplotlib/figure.pyi
lib/matplotlib/pyplot.py
lib/matplotlib/typing.py

I'll assert, without proof, that passing a single string, a mosaic list of strings, or a mosaic list all of the same type is more common than passing arbitrary unrelated hashables. Thus it is somewhat convenient if the return type stipulates that the resulting dictionary is also keyed with strings or the common type.
This also fixes the type of the `per_subplot_kw` argument, which also allows dictionary keys of tuples of the entries.
I don't like that we need a few ignores, but this does work from an external point of view:
```
from typing import TYPE_CHECKING
if not TYPE_CHECKING:
reveal_type = print
fig0, ax0 = plt.subplot_mosaic('ab;cd')
reveal_type(ax0)  # Should be str keys
fig1, ax1 = plt.subplot_mosaic([['a', 'b'], ['c', 'd']])
reveal_type(ax1)  # …
```

TYP: Add common-type overloads of subplot_mosaic

---

lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/mplot3d/tests/test_art3d.py

Closes #26497
Regression, so marking as 3.7.3.

Fix issue with missing attribute in Path3DCollection

---

lib/matplotlib/collections.py

Closes #26674. There's two aspects to the issue:
- the `LineCollection` description is slightly unclear. - This is fixed here.
- `Line3DCollection` inherits `__init__` and reuses its docstring. That's problematic because the the description is 2D. I don't see a good solution here. We likely don't want to replicate the whole docstring, and also a comment like "This holds analogously for 3D with points (x0, y0, z0) and Mx3 arrays." is awkward both for the 2D and 3D docstrings.
I therefore propose to leave it at this. If the 2D description is clear, the extension to 3D can be inferred by the user. - Not ideal, but the least bad option IMHO.

[DOC] Slightly improve the LineCollection docstring

---

lib/matplotlib/_constrained_layout.py
lib/matplotlib/backend_bases.py
lib/matplotlib/backends/_backend_pdf_ps.py
lib/matplotlib/backends/backend_svg.py
lib/matplotlib/colors.py
lib/matplotlib/legend_handler.py
lib/matplotlib/patches.py
lib/mpl_toolkits/axes_grid1/axes_divider.py
lib/mpl_toolkits/axes_grid1/axes_rgb.py
lib/mpl_toolkits/axes_grid1/parasite_axes.py
lib/mpl_toolkits/axisartist/axis_artist.py
lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/mplot3d/axis3d.py

[Doc] Small fixes found by velin

---

lib/matplotlib/backends/backend_pgf.py

By moving the conditionals to tex itself, the generated tex code becomes compilable with engines different from the one originally configured; this is similar to the `\ifdefined\pdfpagewidth` test in PdfPages.savefig.

Make generated pgf code more robust against later changes of tex engine.

---

doc/devel/development_workflow.rst

These were deleted in 3.7.0, and a bunch of redirects were added in #24629, but these two were missed.

DOC: Add redirects for old gitwash files

---

.circleci/config.yml
requirements/doc/doc-requirements.txt

We only want the dev version on devdocs. Releases should get their corresponding theme.
Note that even though this was unpinned for the `v3.7.x` branch as well, it inadvertently worked because the version number in `mpl-sphinx-theme`'s `main` branch was still 3.7.1, so it never replaced the version from PyPI. …

DOC: Pin mpl-sphinx-theme to 3.8.x

---

lib/matplotlib/cbook.py
lib/matplotlib/colors.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/tests/test_colors.py

xref numpy/numpy#24682
Only a handful of lines, and _mostly_ in tests/relatively unused utility functions like `rgb_to_hsv`, but still something that should be addressed.
- [n/a] Documentation …

MNT: Numpy 2.0 removals from ndarray class

---

lib/matplotlib/tests/test_transforms.py
src/_backend_agg.h

Agg enters an infinite loop if you give it points that are NaN, due to converting the values to fixed-point integers, and then oscillating between the large values that result from that conversion.
NaN values may be introduced after transforming the input, so we need to trim those after transformation. This matches what is done in normal paths.
The test itself is mostly a smoketest to ensure we don't crash.
Closes #26765 …

Trim Gouraud triangles that contain NaN

---

galleries/examples/lines_bars_and_markers/fill_between_alpha.py
galleries/examples/lines_bars_and_markers/scatter_demo2.py
galleries/examples/misc/keyword_plotting.py
galleries/examples/ticks/centered_ticklabels.py
galleries/examples/ticks/date_index_formatter.py
galleries/tutorials/pyplot.py
galleries/users_explain/quick_start.py

Structured numpy arrays are more fundamental than recarrays and sufficient in all cases.
Superseeds #26664.

Remove usage of recarray

---

.pre-commit-config.yaml
doc/_templates/autofunctions.rst
doc/_templates/automodule.rst
doc/_templates/autosummary.rst
doc/_templates/autosummary_class_only.rst
doc/api/next_api_changes/behavior/25775-HZ.rst
doc/api/prev_api_changes/api_changes_2.1.2.rst
doc/api/prev_api_changes/api_changes_3.5.0/behaviour.rst
doc/api/prev_api_changes/api_changes_3.7.0/behaviour.rst
doc/devel/MEP/MEP23.rst
doc/devel/MEP/MEP28.rst
doc/devel/contribute.rst
doc/devel/document.rst
doc/users/next_whats_new/antialiasing_text_annotation.rst
doc/users/next_whats_new/boldsym_mathtext.rst
doc/users/next_whats_new/mathtext_features.rst
doc/users/next_whats_new/updated_mathtext.rst
doc/users/prev_whats_new/dflt_style_changes.rst
doc/users/prev_whats_new/github_stats_3.0.0.rst
doc/users/prev_whats_new/github_stats_3.2.0.rst
doc/users/prev_whats_new/github_stats_3.4.0.rst
doc/users/prev_whats_new/whats_new_1.5.rst
doc/users/prev_whats_new/whats_new_3.0.rst
doc/users/prev_whats_new/whats_new_3.4.0.rst
doc/users/prev_whats_new/whats_new_3.5.0.rst
galleries/users_explain/text/mathtext.py
galleries/users_explain/toolkits/axisartist.rst
pyproject.toml

Adds [rstcheck](https://github.com/rstcheck/rstcheck) as a pre-commit hook, mostly cause I seem to have a mental block about underlines being same length as title. This pre-commit also has the advantage of being pretty configurable. 
The .rst files in this PR are the linting errors I could fix because I wanted to minimize the ignored errors as much as possible.

MNT: pre-commit rst linter + small linting fixes

---

doc/api/figure_api.rst
doc/api/prev_api_changes/api_changes_3.4.2.rst
doc/api/prev_api_changes/api_changes_3.5.0/behaviour.rst
doc/users/prev_whats_new/whats_new_3.4.0.rst
galleries/examples/subplots_axes_and_figures/figure_title.py
galleries/examples/subplots_axes_and_figures/gridspec_nested.py
galleries/users_explain/axes/arranging_axes.py
galleries/users_explain/figure/figure_intro.rst
galleries/users_explain/figure/index.rst
lib/matplotlib/artist.py
lib/matplotlib/figure.py

This organizes the Figure API in a similar way to the Axes API.  `Figure` is a top-level API, so deserves proper curation.  
Updated a couple of `figure.py` docstrings to have better slugs.  
Edit: built version: https://output.circle-artifacts.com/output/job/a4d69671-bb03-4c9a-a6cc-863209e4ac71/artifacts/0/doc/build/html/api/figure_api.html

DOC: organize figure API

---

lib/matplotlib/image.py

When matplotlib clip image data because it is out of range, it could be useful to know what range was actually inputted. This PR print the given range in the logs.
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and …

specify input range in logs when image data must be clipped

---

lib/matplotlib/_mathtext.py
lib/matplotlib/legend.py
lib/matplotlib/rcsetup.py

While writing #26742 I found some methods that I was unaware of and tried to find cases where they could be used. …

Use cbook methods for string checking

---

lib/matplotlib/tests/test_ticker.py
lib/matplotlib/ticker.py

Fix issue with locale comma when not using math text

---

doc/api/toolkits/mplot3d/axes3d.rst
doc/users/next_whats_new/3d_axis_limits.rst
lib/matplotlib/axis.py
lib/matplotlib/mpl-data/matplotlibrc
lib/matplotlib/mpl-data/stylelib/classic.mplstyle
lib/matplotlib/rcsetup.py
lib/matplotlib/tests/test_collections.py
lib/matplotlib/ticker.py
lib/mpl_toolkits/mplot3d/axes3d.py
lib/mpl_toolkits/mplot3d/axis3d.py
lib/mpl_toolkits/mplot3d/tests/test_axes3d.py

Closes https://github.com/matplotlib/matplotlib/issues/18052
```python
fig, ax = plt.subplots(1, 1, subplot_kw={'projection': '3d'})
ax.set_xlim(0, 0.8)
ax.set_ylim(0, 0.8)
ax.set(xlabel='x', ylabel='y', zlabel='z')
plt.show()
```
Before:
After (exact limits for x and y, z retains default padded limits):
~~There are a ton of test image changes, gonna be a hefty commit.~~
- [N/A] …

Do not add padding to 3D axis limits when limits are manually set

---

environment.yml
lib/matplotlib/__init__.py
requirements/testing/mypy.txt
setup.py

It is documented that kiwisolver was bumped to 1.3.1 and pillow to 8 in MPL 3.8, but not consistently introduced in all files. …

Update kiwisolver and pillow versions to be consistent with requirements

---

doc/api/toolkits/mplot3d/axes3d.rst

Attempt to fix doc build failure introduced with #25272.
I suspect this is sphinx scoping: #25272 reused methods like `Axes.set_xbounds` to generate documentation for Axes3D. However, a see also of invert_xaxis only searches within the same module (or class), and invert_xaxis is not documented for Axes3D. This PR attempt to explicitly document the missing methods for Axes3D.
Only one of #26817, #26818 should be used, preferrably #26818 if it works out.

Fix doc build (alternative)

---

lib/matplotlib/tests/test_bbox_tight.py
lib/matplotlib/tests/test_image.py

Axes is considered private in pyplot. See also #26812.

Remove plt.Axes from tests

---

doc/api/next_api_changes/removals/26797-OG.rst
lib/matplotlib/backend_bases.py
lib/matplotlib/backend_bases.pyi
lib/matplotlib/backends/backend_agg.py
lib/matplotlib/backends/backend_pdf.py
lib/matplotlib/backends/backend_ps.py
lib/matplotlib/backends/backend_svg.py
src/_backend_agg.h
src/_backend_agg_wrapper.cpp

Second commit is a minor refactoring. Maybe one should consider inlining `_draw_gouraud_triangle` completely now?

Remove deprecated draw_gouraud_triangle

---

environment.yml
lib/matplotlib/__init__.py
requirements/testing/mypy.txt
setup.py

- Backport PR #26799: Update kiwisolver and pillow versions to be consistent with requirements
Conflict was due to pinning of numpy for the release branch to `<2`

Backport PR #26799 on branch v3.8.x (Update kiwisolver and pillow versions to be consistent with requirements)

---

lib/mpl_toolkits/mplot3d/axes3d.py
lib/mpl_toolkits/mplot3d/tests/test_axes3d.py

closes #26821 
relevant issue: https://github.com/matplotlib/matplotlib/issues/26821
I made this change based off of timhoffm's comment under the issue about a potential fix. (https://github.com/matplotlib/matplotlib/issues/26821#issuecomment-1724807332)
This PR allows for passing a numpy array to the color argument of ax.scatter when ax is initialized with projection='3d' instead of resulting in a ValueError
The changes passed the tests available for the relevant file (lib/mpl_toolkits/mplot3d/tests/test_axes3d.py), as well as that entire tests folder.
The changes also passed the code reproduction example in the joshuacnewton's bug summary (https://github.com/matplotlib/matplotlib/issues/26821#issue-1901885527)
- [N/A] *New Features* and *API Changes* are noted with a [directive and …

Fix Issue 26821: [Bug]: ValueError: The truth value... when an ndarray is passed to the color kwarg of axes3d.scatter

---

lib/matplotlib/axes/_base.py

_prop_keys is redundant with _cycler_items and not really needed anywhere.  Removing it makes it less likely that a _process_plot_var_args gets in an invalid state if _cycler_items is updated while _prop_keys is not touched.
Inspired by #26831.
A second separate commit adds some minor cleanups.

Reduce redundant information in _process_plot_var_args.

---

doc/api/next_api_changes/development/26849-KS.rst
doc/devel/dependencies.rst
pyproject.toml
requirements/testing/mypy.txt
setup.py

Technically could work with older setuptools and setuptools_scm==7,
but encoding that matrix of dependencies is not something I think is worth worrying about,
and setuptools 64 is over a year old (though not by a _whole_ lot).
setuptools_scm has a version constraint that they do not themselves enforce on the environment
so I've added it to our own requirements, when setuptools_scm is required.
Setuptools_scm's docs are inconsistent in what version they _actually_ require, so I went with
the one that was most up to date and was in their user facing docs.
(My next choice would be 61, as that is what the runtime warning actually checks)
The config in pyproject.toml was taken from #26621
Closes #26846

Bump setuptools required version because of setuptools_scm v8

---

.circleci/config.yml

This is a followup to #26505 as it appears I missed the Ubuntu in the Circle-CI builds. There's probably a lot more recommended LaTeX packages here, so we'll have to see if CI is happy with it.

ci: Don't install recommended packages on Circle

---

doc/api/next_api_changes/removals/26872-AD.rst
lib/matplotlib/animation.py
lib/matplotlib/animation.pyi

This PR removes 3.7-deprecated API from `lib/matplotlib/animation.py` which is mentioned in the issue here: https://github.com/matplotlib/matplotlib/issues/26865

Deprecated code removed in animation.py

---

doc/api/next_api_changes/removals/26871-AG.rst
lib/matplotlib/axis.py

This PR removes the deprecated code during the version 3.7 from l`ib/matplotlib/axis.py` which is a sub issue in the parent issues here: https://github.com/matplotlib/matplotlib/issues/26865
- [ N/A] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ N/A] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [N/A ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- …

Removed the deprecated code from `axis.py`

---

doc/conf.py

I had reason to `git clean` and then the next time I ran `make html-skip-subdirs`, it spend a while generating users/explain.  Adding `'users/explain/*'` to the list of default skipped subdirs fixed that.

Add users/explain to default skip subdirs

---

lib/matplotlib/backends/backend_qt.py

Fix for a case when parent window is modal. Configure subplots hides behind parent modal windows in case of non-modal usage. Other dialogs of NavigationToolbarQT are modal, so it looks like a bug.
tested on pyQT6 …

QT/NavidationToolbar2: configure subplots dialog should be modal.

---

lib/matplotlib/widgets.py

Shorten the code that determines which button has been clicked.
Use Text.contains directly (it calls text.get_window_extent itself) rather than manually going through text.get_window_extent.
The previous code for finding the closest click was actually wrong (transAxes.inverted().transform((event.x, event.y)) is in axes space, but get_offset_transform().transform(get_offsets()) is in screen space, so they cannot be subtracted from one another) but it didn't really matter because a click is, in practice, always contained by a single button anyways (idxs has length at most 1).  Still, fix that.

Simplify CheckButtons and RadioButtons click handler.

---

doc/api/next_api_changes/behavior/26902-RP.rst
lib/matplotlib/lines.py
lib/matplotlib/tests/test_lines.py

Fixed deprecated parts in set_xdata and set_ydata APIs in lines.py
- [N/A ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [N/A ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

Fixed deprecated APIs in lines.py

---

doc/api/next_api_changes/removals/26872-AD.rst

I just noticed that I overlooked making the right changes to the removal documentation when removing deprecated code from animation.py: https://github.com/matplotlib/matplotlib/pull/26872. 
I'm sorry I missed this earlier!
- [ N/A] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new …

DOC: Fix removal doc for Animation attributes

---

doc/api/next_api_changes/removals/26852-OG.rst

The removal notice could state the conversions since they are one-liners.   #26852

DOC: improve removal for julian dates [ci doc]

---

galleries/examples/axes_grid1/demo_colorbar_with_axes_divider.py
galleries/examples/axes_grid1/demo_colorbar_with_inset_locator.py
galleries/users_explain/axes/colorbar_placement.py
galleries/users_explain/axes/constrainedlayout_guide.py

Noted in https://github.com/SciTools/cartopy/issues/2248#issuecomment-1733102735 - placing colorbars inside axes is sometimes a good thing to do (think a map, where you know you have no data coloured over a body of water, so the colorbar fits nicely there).  This adds a couple of simple examples to show how to do that.  Also crosslink from `demo-colorbar-with-inset-locator` and `demo-colorbar-with-axes-divider` and added some notes that these methods can typically be accomplished by easier means.

DOC: add a couple more placement examples, crosslink axes_grid [ci doc]

---

lib/matplotlib/tests/test_image.py
setupext.py
src/_image_resample.h
src/_image_wrapper.cpp
src/py_converters_11.cpp
src/py_converters_11.h

Closes the fourth item of issue #23846.
This changes the `image` module to use `pybind11` rather than our `array_view` classes and direct use of the Python/C API. On my Linux dev machine this brings the `_image*.so` library down from 1.8 MB to 1.0 MB.
I've taken the usual approach of the minimal set of changes to switch to `pybind11`. This means that in some places we are still passing around pointers to array buffers an integer array dimensions. We could consider improving that in future, but it might be better to leave it as it is using the "if it ain't broke" principle.
The standard approach to using `pybind11` is to use the `py` namespace, i.e.
```c++
namespace py = pybind11;
```
but I haven't done this as we already have a `py` namespace in `py_adapters.h` and we can't keep both …

Use pybind11 in image module

---

.pre-commit-config.yaml

required for reading config from pyproject.toml on py<3.11

add tomli to rstcheck extras

---

lib/matplotlib/axes/_axes.pyi
lib/matplotlib/pyplot.py

Closes #26936
Quick scan of other methods with a `cmap` kwarg didn't show any others needing updating.

Add ArrayLike to scatter c arg type hint

---

lib/matplotlib/colors.py

Co-authored-by: Zihao Yang zihaoyng@gmail.com
The original description is not easy to understand for us (without playing with the API) so we tried to make it more clear and added some examples. Also we added documentation for methods that are not documented - we found some description about the methods issue tracker's threads!
- [N/A] *New Features* and *API …

DOC: Clarify description and add examples in colors.Normalize

---

lib/matplotlib/widgets.py

... to make the Cursor redraw logic easier to follow. Also remove the unused return value from _update.

Inline Cursor._update into its sole caller.

---

lib/matplotlib/backends/backend_macosx.py
lib/matplotlib/tests/test_backend_ps.py

There was a typo in `elif rcParams.get("ps.userdistiller") == "xpdf"` which effectively always returned False (the correct spelling is "ps.usedistiller", so the get() call always returned None), which made the skip check for xpdf never run.  Thus, running the test on a machine without pdftops installed would eventually result in an ExecutableNotFoundError when matplotlib actually tries to call the distiller.
To avoid this kind of problems (dict.get hiding typos), directly update the test-specific settings into the main rcParams, and use normal brackets to access rcParams entries, as rcParams keys are a fixed set anyways.
This broke the mplcairo test suite (where I didn't bother configuring CI to have pdftops installed) so labeling as 3.8.1; "somewhat" release critical (though I guess I …

Fix incorrect skip check in test_backend_ps.

---

lib/matplotlib/colors.py
lib/matplotlib/tests/test_colors.py

Fixes #26949.  We just shouldn't assume that a 2-tuple passed to `to_rgba_array` is a single (color, alpha) pair.

FIX 2-tuple of colors in to_rgba_array

---

lib/matplotlib/backend_bases.py
lib/matplotlib/backends/backend_ps.py

This makes it easier for mplcairo (which also outputs PostScript natively) to inherit the deprecation and be able to run the matplotlib test suite both with matplotlib 3.7 (where there should be no warning) and with matplotlib 3.8 (where there should be a warning).

Move papersize="auto" deprecation to backend_bases.

---

doc/api/next_api_changes/deprecations/26960-AL.rst
lib/matplotlib/backends/backend_ps.py

It's clearly an internal helper, and the two parts (the actual bbox header and the rotation command) don't really benefit from being smushed together, so make the function private and split the two parts.

Deprecate backend_ps.get_bbox_header, and split it for internal use.

---

doc/api/next_api_changes/behavior/26917-AL.rst
doc/api/next_api_changes/deprecations/26917-AL.rst
lib/matplotlib/contour.py

We can just dispatch add_label based on the value of the internal _use_clabeltext flag.  This change is also preparing for a possible future change where we always have use_clabeltext=True (which is needed for contour labels to be properly rotated after changes of axes aspect ratio, and should have no drawback except for a tiny(?) performance cost).

Deprecate ContourLabeler.add_label_clabeltext.

---

doc/missing-references.json
doc/sphinxext/missing_references.py

On Windows, the path is absolute and contains a colon after the drive letter, so splitting on colon results in trying to relativize 'c' (or whatever the drive is) to the base directory, which just makes the final path into base directory + file path.
These missing references all broke in #26628, though I'm not sure why builds never failed since they aren't on Windows, or using the same base paths. …

DOC: Fix missing-reference generation on Windows

---

lib/matplotlib/pyplot.py

Add type signature for `pyplot.show`.
This is done to prevent errors when `mypy --strict` is invoked on client code containing `plt.show()`.
Closes #26919.
The signature indicates a return type of `None`, which matches the matplotlib documentation, even though the implementation could actually return non-None if the back-end function does.
- [] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html) …

Add typing to pyplot.show() to avoid errors with mypy --strict.

---

doc/api/next_api_changes/deprecations/26894-AL.rst
lib/matplotlib/backend_bases.py

This feature is unused internally and has simple replacements; removing it will make it easier for subclasses to directly override Timer.start (#26855) rather than having Timer.start handle the interval and then deferring to a private _timer_start.

Deprecate setting the timer interval while starting it.

---

lib/matplotlib/axis.py

This was not made explicit in the docs (it is in essence due to the use of FixedFormatter, but that's a rather involved detail for end users). Also minor rewordings.
Closes #26947.

Clarify that explicit ticklabels are used without further formatting.

---

doc/devel/contribute.rst

* pulled out "how to send PR to Matplotlib" into its own section and fleshed it out a drop b/c I felt like it was getting a little lost. 
* added a  workflow overview  section title to generate an anchor on the rhs
* changed title underlines to documented standard

DOC: made "open PR on MPL" a section in contribute guide

---

.github/workflows/nightlies.yml

The [`scientific-python/upload-nightly-action`](https://github.com/scientific-python/upload-nightly-action/) action has received stability updates in [`0.2.0`](https://github.com/scientific-python/upload-nightly-action/releases/tag/0.2.0) that provides a reproducible runtime environment for the action, which should mitigate issues with stability.
c.f. https://github.com/scientific-python/upload-nightly-action/pull/44
This PR is being opened manually instead of relying on Dependabot to catch it
https://github.com/matplotlib/matplotlib/blob/a99673c970bc1dac1e54175ed3166e5190c9d793/.github/dependabot.yml#L1-L6
as Dependabot runs on a weekly basis and this update mitigates an Issue that affects users now (c.f. https://github.com/scientific-python/upload-nightly-action/issues/43).
- [N/A] …

CI: Update scientific-python/upload-nightly-action to 0.2.0

---

doc/devel/document.rst
galleries/users_explain/toolkits/axisartist.rst

Based on discussion in #26737,  rotated the parameter default table in the [AxisArtist guide](https://matplotlib.org/devdocs/users/explain/toolkits/axisartist.html#rotation-and-alignment-of-ticklabels) and seperated it out into two to try and clarify that the table is showing the default label parameter values for each reference direction. 
general new look:
attn: @oscargus

DOC: seperate and clarify axisartist default tables

---

.github/workflows/cibuildwheel.yml

Also, backport #26699.
Closes #26932, but only required on the `v3.8.x` branch because `main` is using Meson now and doesn't do dependencies this way.

BLD: Remove development dependencies from sdists

---

lib/matplotlib/colorbar.py
lib/matplotlib/tests/test_colorbar.py

Addresses issue #27007 . If the try/except is done inversely, the error happens in the other block, but the edge case is formatted correctly. Then, both exceptions (TypeError and ValueError) will use the StrMethodFormatter. 
The test is created separetly from test_colorbar_format() (L615) to make it clearer.

ValueError exception added to handle mix of {} and % string in colorbar format

---

lib/matplotlib/legend.py
lib/matplotlib/tests/test_legend.py

… when __ len __ exists for both
Closes #24050 . Following the discussion there (And in PRs #24061 and #24063) a warning is issued when the handles and labels have __ len __() and there is a mismatch in its value. A test checks whether the warning is raised.

Warning if handles and labels have a len mismatch

---

doc/users/resources/index.rst

- Added a link to past winners for the JDH plotting contest.  Closes #11129
* Changed placement of the python graph gallery from tutorials section to galleries

Add a section to Highlight past winners for JDH plotting contest in docs

---

lib/matplotlib/contour.py
lib/matplotlib/tests/test_contour.py

Closes #26863.  I think this reinstates the pre-3.8 behaviour.  Adapted @jklymak's example from https://github.com/matplotlib/matplotlib/issues/26863#issuecomment-1732807216 into the new test.

`allsegs` and `allkinds` return individual segments

---

lib/matplotlib/tests/test_datetime.py

Adding code for `test_plot_date` method in `test_datetime.py` mentioned in [#26864](https://github.com/matplotlib/matplotlib/issues/26864)
**Image output -**

add test_plot_date in test_datetime.py

---

.github/workflows/cibuildwheel.yml
.github/workflows/tests.yml

The final release is out, as are non-prerelease wheels, so we can drop those workarounds. …

ci: Clean up Python 3.12 builds

---

.github/workflows/cibuildwheel.yml
.github/workflows/tests.yml

Manual backport of #27059. Conflict was the change to Meson on `main`.

Backport PR #27059: ci: Clean up Python 3.12 builds

---

.github/workflows/reviewdog.yml
pyproject.toml

This tests against the new cycler release candidate, and then drops the flag/comment noted in the ci config.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.htm …

ci: Run mypy against typed cycler

---

lib/matplotlib/tests/test_datetime.py

Added test_hist method in test_datetime.py as part of the #26859

Added test_hist in test_datetime.py

---

lib/matplotlib/_mathtext_data.py

Update stix table with Unicode names

---

.pre-commit-config.yaml
pyproject.toml

Add mypy pre-commit hook, not sure which args are needed to have it behave the same as the one in ci.  See discussion in #26928 -> I both forgot what I'm supposed to run locally and didn't realize I could run mypy locally. attn @ksunden

add a mypy pre-commit hook

---

lib/matplotlib/tests/test_datetime.py

Addresses parts of #26864
This is a clean up of the stubs for methods which have been determined to not use the units machinery that is being tested in this module, this includes the various spectrum plot methods as well as the table method (xref #26953)

Remove datetime test stubs for spectral methods/table

---

src/_backend_agg.cpp
src/_backend_agg.h
src/_backend_agg_basic_types.h
src/_backend_agg_wrapper.cpp
src/_image_wrapper.cpp
src/_path.h
src/_path_wrapper.cpp
src/_ttconv.cpp
src/ft2font.cpp
src/numpy_cpp.h
src/py_adaptors.h
src/py_converters.cpp
src/py_converters_11.cpp
src/py_converters_11.h
src/py_exceptions.h
src/tri/_tri_wrapper.cpp

Then we can use the standard `pybind11` namespace alias of `py`.

Rename py namespace to mpl in extension code

---

galleries/examples/misc/histogram_path.py

Fixes #26990 
Solution: Split image into two rows for two blocks of code resp.

Issue #26990: Split the histogram image into two for each code block. 

---

doc/api/figure_api.rst

This was accidentally lost through #26629.

Restore figaspect() API documentation

---

lib/matplotlib/tests/test_transforms.py
src/_backend_agg.h
src/_backend_agg_wrapper.cpp
src/_path.h
src/_path_wrapper.cpp
src/_qhull_wrapper.cpp
src/array.h
src/mplutils.h
src/numpy_cpp.h

This will generally make it easier to port to pybind11, as then the templated code can stay the same whether using the old `numpy::array_view` or the new `pybind11::array_t`.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) …

Tweak array_view to be more like pybind11

---

doc/api/next_api_changes/deprecations/27095-AL.rst
doc/api/next_api_changes/removals/27095-AL.rst
lib/mpl_toolkits/axisartist/axislines.py
lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py

FixedAxisArtistHelpers place an axis on either the bottom, top, left, or right of an axis per (`loc`); we already infer whether it's an x-axis or a y-axis (`nth_coord`) from that and error out if there's a mismatch, so we may just as well delete the nth_coord parameter (which was already optional to start with).
While at it, also expire deprecation for passing inconsistent nth_coord and loc.

Deprecate nth_coord parameter from FixedAxisArtistHelper.new_fixed_axis.

---

lib/matplotlib/testing/__init__.py

This allows running pytest with any import-mode option.
Related to https://github.com/matplotlib/matplotlib/pull/27094#issuecomment-1764618468 …

TST: Use importlib for subprocess tests

---

lib/matplotlib/mpl-data/matplotlibrc
lib/matplotlib/rcsetup.py
lib/matplotlib/tests/test_rcparams.py

Tried to make it clearer that the rcParam format is `path:sketch: scale, length, randomness`. I originally read it as `path:sketch: (scale, length, randomness)` and that caused loads of test failures. 
This is spun off of #26854 since I think this param is worth clarifying. 
It's probably more sensible to just let path.sketch take a tuple as a valid arg but this tests status quo

MNT: clarify path.sketch rcparam format + test validate_sketch

---

lib/matplotlib/__init__.py
src/ft2font_wrapper.cpp
src/meson.build

Previously, this used a macro defined on the command line to a literal, which was "stringified" with macro magic. But if the command-line definition isn't there, then you just get a stringified version of the macro name.
Instead, don't do any stringification, so that it fails on error. Then pass a string as the defnition. …

BLD: Fix setting FreeType build type in extension

---

lib/matplotlib/tests/test_datetime.py

I have added a datetime/timedelta smoke test for `Axes.barh` in `lib/matplotlib/tests/test_datetime.py`.
This addresses the `Axes.barh` task from #26864.
The image below is the plot generated from this smoke test/example code.
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html# …

Add test_barh to test_datetime.py

---

lib/matplotlib/tests/test_datetime.py

Adds the test_stackplot method in test_datetime.py. The test creates the following stackplots:
1. `datetime` x-axis, stacked numerical y-axis
2. ~~`datetime` x-axis, `datetime` plus stacked `datetime.timedelta` y-axis~~ (not implemented for this pull request)
Stacking multiple `datetime` arrays caused a compile error, because numpy does not support adding two `datetime` objects together. I don't believe it makes much sense to stack `datetime` values in this way, so I have not implemented this test.
This pull request closes the `Axes.stackplot` task in issue [#26859](https://github.com/matplotlib/matplotlib/pull/26859)
**Plot output**
- [N/A] *Plotting related* features are demonstrated in an …

add test_stackplot in test_datetime.py

---

lib/matplotlib/backends/qt_compat.py

Addresses the Qt part of https://github.com/matplotlib/matplotlib/issues/23385#issuecomment-1176773951.
It appears that `qapp.quit()` does not automatically close the windows of the app. We therefore do it explicitly.
A unit test for this would be quite complex. Test this by hand by Ctrl+C in an interactive shell.

Close all plot windows of a blocking show() on Ctrl+C

---

doc/api/next_api_changes/removals/26900-jf.rst
lib/mpl_toolkits/axisartist/axislines.py

This PR removes the depcrecated code during the version 3.7 from patches.py and axislines.py for the issue #26865 
- [ NA] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ NA] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ NA] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ NA] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [ NA] Documentation complies with …

#26865 removing deprecations to patches.py and axislines.py

---

lib/matplotlib/tests/test_datetime.py

Attempting adding code for `test_contourf` method in `test_datetime.py` mentioned in [#26864](https://github.com/matplotlib/matplotlib/issues/26864)
**Image output -**

Add test_contourf in test_datetime.py

---

lib/matplotlib/tests/test_datetime.py

Smoke test for 'Axes.text' using datetime data in 'lib/matplotlib/tests/test_datetime.py'. This PR addresses one of the tasks listed in https://github.com/matplotlib/matplotlib/issues/26864
The image below is the generated plot:

Added smoke test for Axes.text in test_datetime.py

---

doc/conf.py
doc/devel/development_setup.rst
doc/devel/troubleshooting.rst
pyproject.toml

Added a short sentence/command for building with compilation logs enabled cause I figure it's gonna be a commonish need of anyone working with the c-extension files.

Added info for getting compilation output from meson on autorebuild

---

lib/matplotlib/tests/test_datetime.py

I´ve added code for `test_axhspan` method in `test_datetime.py` mentioned in issue [#26864](https://github.com/matplotlib/matplotlib/issues/26864)
Image output: (edited)

added test_axhspan in test_datetime.py

---

lib/matplotlib/tests/test_datetime.py

I´ve added code for `test_axvspan` method in `test_datetime.py` mentioned in issue [#26864](https://github.com/matplotlib/matplotlib/issues/26864)
Image output: (edited)

added test_axvspan in test.datetime.py

---

galleries/examples/statistics/histogram_bihistogram.py

Adds an example to the documentation for plotting a bihistogram (see the closed PR #27180 for prior discussion)
- [NA] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [NA] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)

Add example for plotting a bihistogram

---

lib/matplotlib/tests/test_datetime.py

Added code for test_step method in test_datetime.py mentioned in https://github.com/matplotlib/matplotlib/issues/26864

Add test_step to test_datetime.py

---

doc/api/next_api_changes/behavior/27179-KS.rst
doc/api/prev_api_changes/api_changes_3.8.0/behaviour.rst
lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

Closes #27103
Closes #16865
This changes the default behavior to avoid errors/warnings on empty bins (restoring behavior when mincnt is not specified to that of before v3.8.0).
Additionally corrects the docstring and updates the release notes (retroactively).
A test case has been added to the tests of empty input with `np.max`, a function that errors on empty input.

Restore default behavior of hexbin mincnt with C provided

---

lib/matplotlib/projections/__init__.py

On some installs, the `mpl_toolkits` namespace package gets an old
version which uses deprecated (And removed) code from the main library.
On such the import of Axes3D will error with an `ImportError`.
This prevents users from using any of `matplotlib`, since it is imported
unconditionally by default.
This just try/excepts the imports (and adjusts the registration code
accordingly) to allow users to continue using matplotlib (though not 3D
and possibly not other mpl_toolkits) even with older installs occluding
the mpl_toolkits.
Addresses at least the most pressing part of #26827
(Not quite sure we want to close that or not)

Try/except import of Axes3D

---

doc/devel/document.rst

I guess I forgot to add a line and nobody checked the final build - currently all the urls in the table are batched underneath 😬 
this PR also fixes the links 🤦‍♀️

DOC: clean up links under table formatting docs

---

doc/api/next_api_changes/deprecations/27175-AL.rst
lib/matplotlib/legend.py
lib/matplotlib/tests/test_legend.py

This was previously already a warning and also broken.
Closes #26841.

Deprecate mixing positional and keyword args for legend(handles, labels)

---

galleries/examples/event_handling/legend_picking.py

* Pass an actual pickradius instead of `True`. `True` (`1`) is a bad user experience.
* Fix `on_pick` to work when the legend is draggable. (Early exit)
* For good measure, show that it works with draggable legends.
* Use higher visability syntax for single element destrturing for higher readability.
* Refactor varible names. (`lined` -> `map_legend_to_ax`)
* (Formatted with autopep8)
Live version: https://matplotlib.org/stable/gallery/event_handling/legend_picking.html
- [N/A] "closes #0000" 
- [N/A] (?) new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)

Improve legend picking example

---

lib/matplotlib/axes/_base.py
lib/matplotlib/axes/_secondary_axes.py
lib/matplotlib/figure.py
lib/matplotlib/lines.py
lib/matplotlib/patches.py
lib/matplotlib/text.py

Adding explanation what the color means in `set_facecolor`

docs: adding explanation for color in `set_facecolor`

---

lib/matplotlib/tests/test_datetime.py

I have added a datetime (no timedelta; this function does not support it, and I believe that is correct) smoke test for `Axes.axhline` in `lib/matplotlib/test/test_datetime.py`.
This addresses the `Axes.axhline` task from #26864.
The image below is the plot generated from my example code.
- [N/A] *New Features* and *API Changes* are noted with a [directive and …

Add test_axhline in test_datetime.py

---

lib/matplotlib/_text_helpers.py
lib/matplotlib/tests/test_backend_pdf.py
lib/matplotlib/tests/test_ft2font.py
lib/matplotlib/tests/test_text.py
src/ft2font.cpp
src/ft2font.h

Modified the "missing glyph" warning to also print out the name of the font the glyph is missing from. This is mostly to help me debug why #26854 is failing on CI but working locally but there have been times where I've gotten this error and would have found it helpful to have the added context. 
<strike>second commit adds a :filter-warning: option to the `..plot` directive</strike> spun out into  #27076
- [n/a] *New Features* and *API Changes* are noted …

MNT: print fontname in missing glyph warning

---

lib/matplotlib/tests/test_datetime.py

I have added a datetime smoke test/example code for `Axes.axvline` in `lib/matplotlib/test/test_datetime.py`. This addresses the `Axes.axvline` task from #26864. This is very similar to #27177, where I added example code for `Axes.axhline`; this is the vertical version of that function.
The image below is the plot generated from my example code.
- [N/A] *New …

Add test_axvline to test_datetime.py

---

lib/matplotlib/backends/backend_macosx.py
src/_macosx.m

Follow the same logic with a context manager for the handling of the event interrupts so that we can reuse the logic from the main loop implementation in the `start_event_loop` function as well.
```
python -c 'from pylab import *; plot(); show(block=False); pause(5)'
```
closes #27120 
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#wr …

FIX: Enable interrupts on macosx event loops

---

.github/workflows/cibuildwheel.yml

This uses the NumPy nightlies for non-release builds to ensure the matplotlib nightlies uploaded are build against the new NumPy version.
These nightlies are not tested, but if they were they should actually still be tested against the release NumPy.  This is necessary to allow NumPy to enforce API changes, it does mean that potential C-API breaks in NumPy need quicker follow-up unfortunately (either in NumPy or in matplotlib).
Closes gh-27174
---
I have tested that it calls with `--no-build-isolation` and installs the right NumPy before that.  I am *not* sure that this is the best approach, it is rather tedious to set up all dependencies manually (and I am not a workflow specialist)!
For example, I don't really understand the `>-` but I removed it because that means that newlines are not …

BLD: Use NumPy nightly wheels for non-release builds

---

.gitignore
doc/_static/mpl.css
doc/conf.py
environment.yml
galleries/examples/README.txt
galleries/examples/animation/animated_histogram.py
galleries/examples/animation/multiple_axes.py
galleries/examples/event_handling/resample.py
requirements/doc/doc-requirements.txt

Adds [sphinx-tags](https://sphinx-tags.readthedocs.io/en/latest/index.html) as a dependency and some basic configuration to display tags with color, using [sphinx-design](https://sphinx-design.readthedocs.io/en/latest/).
This is a proof-of-concept implementation of tags for the gallery of examples. The actual tags will be the result of the Google Season of Docs project by @esibinga.
This PR is mostly a demo of how this would work in practice, and feedback is appreciated.
Related: #26851 
There is no release note but this may need one when it is ready to merge.
cc @story645 
Previews:
- [Example gallery entry page, with the link to all tags](https://output.circle-artifacts.com/output/job/63217eb6-7b19-4d1f-b35a-9aa17e8da975/artifacts/0/doc/build/html/gallery/index.html)
- [Tagged animation …

DOC: Add tags infrastructure for gallery examples

---

lib/matplotlib/pyplot.py

The semantics of the fignum parameter are rather confusing, per #22972 (in particular wrt. whether the figure gets resized or not -- it only does if fignum=(None or a non-existing figure number) (which creates a new figure), but not if fignum=0 (which also creates a new figure).
It's probably not worth fixing that (if anything we should just point users to Axes.matshow, which is just fine), but we can still improve the documentation.

Clarify semantics of plt.matshow(..., fignum=...).

---

lib/matplotlib/backends/backend_qt.py

In mpl_gui we are being more proactive about breaking circular references when closing a GUI window so that it is possible for a FigureCanvasQt to be in a state where the figure attribute is None.
In that case short-circuit return in the UI events.

MNT: be more careful in Qt backend that there is actually a Figure

---

doc/_static/mpl.css
doc/devel/coding_guide.rst
doc/devel/communication_guide.rst
doc/devel/index.rst
doc/devel/release_guide.rst
doc/users/project/code_of_conduct.rst
doc/users/release_notes.rst

There's been an open issue for a while to move the communications guidelines out of the governance repository because it should function more like code or documentation guidelines.  In that issue the move was waiting on a new development repo, but I figure as an incremental step it can be moved into the development guidelines section with the other documents that are more geared towards maintainers because maintainers are the audience it is currently written for. I broke up this change into:
1. move over file and add to index, closes https://github.com/matplotlib/governance/issues/24
2. update the guidelines with current info, supercedes https://github.com/matplotlib/governance/pull/36
3. guidelines for changing guidelines, inline with the API guidance, supercedes …

moved communications guidelines from governance, updated and clarified process 

---

lib/matplotlib/backends/web_backend/js/mpl.js

When opening `embedding_webagg_sgskip.py` in Firefox, the empty canvas slowly increases in height until the figure first comes through. Skipping the canvas resize until the WebSocket connects prevents this unnecessary canvas change.
- If it is still connecting, then we will get an initial resize from Python once it connects.
- If it has disconnected, then resizing will clear the canvas and never get anything back to refill it, so better to not resize and keep something visible.
- [n/a] *Plotting related* features …

webagg: Don't resize canvas if WebSocket isn't connected

---

doc/api/next_api_changes/README.rst
doc/devel/coding_guide.rst
doc/devel/contribute.rst
doc/devel/development_setup.rst
doc/devel/development_workflow.rst
doc/users/next_whats_new/README.rst

This started as an attempt to document variable naming conventions to address #22156 and well trying to put a table into a bullet list didn't work well and that had me thinking that a bullet list is the wrong structure when tables are involved so 😅 this PR:
- moves a lot of text out of notes and turns it into the preambles they were functionally acting as
- consolidates the contributor checklists sections, mostly by removing content and instead linking out to where it's discussed/described
- better distinguish contributor content checklist from github checklist
- move the checklist .css into the mpl.css file
- moved info on updating a pull request to the workflow-> as with #26998, this is to better scope the PR guidelines doc to being about the content of the PR and the git workflow doc …

DOC: consolidated coding guide and added naming conventions table

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/colors.py
lib/matplotlib/legend.py
lib/matplotlib/projections/polar.py

Tweak a few docstrings.

---

lib/matplotlib/contour.py
lib/matplotlib/dviread.py
lib/mpl_toolkits/axisartist/axislines.py
lib/mpl_toolkits/axisartist/floating_axes.py
lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py

Three independent cleanup commits:
- in axisartist: Mostly just unwrapping long lists of arguments and other expressions into a single line where possible.
- in contour: Shorten contour._make_paths_from_contour_generator.
- in dviread: Move most one-liner opcode parsers into lambdas with the behavior specified by comments, which seems clearer than spreading them out into proper functions with plenty of intervening blank space.

Various cleanups

---

lib/matplotlib/dviread.py

int.from_bytes has been around since Python 3.2.

Use int.from_bytes instead of implementing the conversion ourselves.

---

.github/ISSUE_TEMPLATE/tag_proposal.yml

FIxes the yml for the new tag template by escaping the space after the : https://github.com/actions/runner/issues/1019#issuecomment-1280938515 - am open to other suggestions but yaml really does not like colons.

MAINT: fix .yml in tag issue template

---

src/_macosx.m

This ensures the GIL is held while freeing the renderer buffer.
Fixes #27262
This became problematic in 3.12, but was likely _possible_ in earlier python versions.
This method is handed to Obj-C code to call upon releasing, which we therefore do not _fully_ control.

Ensure GIL while releasing buffer

---

doc/api/next_api_changes/deprecations/27300-AL.rst
lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py

It's only ever used essentially to expose GridHelperCurveLinear._grid_info to FixedAxisArtistHelper.get_tick_iterators; it seems better to access it from the sole caller.  (Note that floating_axes already does the same direct access to the private _grid_info.)
Removing get_tick_iterator also removes the confusion with get_tick_iterators (plural), which is a common API in axisartist. Also note that the "minor" parameter of get_tick_iterator had a rather peculiar meaning (it only switched the labels off).

Remove idiosyncratic get_tick_iterator API.

---

src/_c_internal_utils.cpp
src/meson.build

I changed to a C++ file, in order to use pybind11, though I'm not sure if the name should change. I also made the `HWND` into a capsule so we could check types a bit more stringently, though this is assuming no-one ever wants to call `SetForegroundWindow` with a handle obtained elsewhere.
This depends on the Meson PR, as it was much easier to iterate with its automatic re-compile in editable installs.
- [n/a] *New Features* and *API Changes* are noted with …

Use pybind11 in _c_internal_utils module

---

lib/matplotlib/backends/backend_qt.py

When a Qt window is closed we do not strip off the Qt components and it is technically possible to re-show it.  However, the latch we use to detect re-entrant destruction does not get reset so the figure can not be re-destroyed.
More subtle behavior details discovered while working on mpl-gui.

FIX: allow re-shown Qt windows to be re-destroyed

---

lib/matplotlib/colorbar.py

Currently, make_axes_gridspec uses two nested gridspecs, first a horizontal (1, 2) gridspec and second a vertical (3, 1) gridspec to position an axes A and the associated left-colorbar C as
```
A.
AC
A.
```
(and similarly for colorbars on other sides of the main axes).  Instead, this can be done with a single (3, 2) gridspec to position both A and C.

Simplify GridSpec setup in make_axes_gridspec.

---

lib/matplotlib/contour.py
lib/matplotlib/tests/test_contour.py

Closes #27333
I would like to simplify down the reproducer further and add a test, but I think the code change itself is largely good.
Just uses `path._iter_connected_components()` to break apart the connected subpaths so that the MOVETO lines don't get considered as close.
There is a small amount of bookkeeping to make sure that the reported index includes all of the subpaths already processed.

Omit MOVETO lines from nearest contour logic

---

.circleci/config.yml
.devcontainer/devcontainer.json
doc/devel/dependencies.rst
lib/matplotlib/mpl-data/matplotlibrc
lib/matplotlib/mpl-data/stylelib/classic.mplstyle
lib/matplotlib/pyplot.py
lib/matplotlib/tests/test_axes.py
lib/matplotlib/textpath.py

This swaps xkcd-script for the Humor sans font b/c the way Humor sans handles the .notdef character is leading to dropped - without warning #27232 
This is cherry picked out of #26854 
I think we should fork a copy of the xkcd branch under matplotlib because I'm uncomfortable with relying on an unmaintained fork of an unmaintained project, but this is the most complete character set.

[MNT] swap xkcd script for humor sans

---

lib/matplotlib/backends/backend_qt.py

Add `@QtCore.Slot()` decorations to `NavigationToolbar2QT` to suppress "Registering dynamic slot" warnings. Closes #27214.

Add `@QtCore.Slot()` decorations to `NavigationToolbar2QT`

---

lib/matplotlib/backends/_backend_tk.py
lib/matplotlib/backends/_tkagg.pyi
lib/matplotlib/tests/test_backend_tk.py
src/_tkagg.cpp
src/meson.build

Another step towards finishing #23846. Once again, this depends on the Meson port.
I moved the array handling parts into pybind11 code instead of Python, which seemed to fix some kind of reference counting bug across the callback boundaries.

Convert TkAgg utilities to pybind11

---

doc/users/next_whats_new/3d_axis_limits.rst

The current what's new shows a poor example of the new exact axis limits introduced in https://github.com/matplotlib/matplotlib/pull/25272/. This is an issue that happens only when the new rc param changes mid-plot-generation, which shouldn't ever happen normally. Workaround is to swap the order the subplots are generated.
Before:
After:
- [n/a] *New Features* and …

[DOC]: Update 3d axis limits whats new

---

lib/mpl_toolkits/axisartist/axislines.py

Closes #27352 as the comments from @anntzer made it clear that it probably doesn't improve anything to make the `nth_coord` attribute private. (I can still continue along that path if requested.)
Parts of the refactoring still makes sense from a code quality perspective though, so that is what is kept here.

Refactor AxisArtistHelpers

---

lib/matplotlib/colorbar.py
lib/matplotlib/tests/test_colorbar.py

Indiscriminately going back up to the topmost gridspec is wrong in the presence of nested gridspecs.  Closes #27329.
We may want to add an API to just go up one level in gridspecs (i.e. public access to _subplot_spec) but I'd like to first consider whether we could e.g. merge GridSpecFromSubplotSpec into GridSpec with the only difference that the former's get_parent() (or another similarly named new method) returns another gridspec whereas the latter's returns a figure.

Fix removal of colorbars on nested subgridspecs.

---

lib/matplotlib/font_manager.py

Fix _Note_ in `_find_fonts_by_props` docstring to match actual return value (list instead of dict).

Fix _find_fonts_by_props docstring

---

lib/matplotlib/backends/_backend_tk.py

The whole module is private, so we can just clean it up directly.
Instead of creating and hiding a new tip window each time, we can just
create a single one and show/hide it as needed.

Simplify tk tooltip setup.

---

galleries/examples/widgets/menu.py

Make example independent of dpi setting when saving the output
with different resolutions to prevent shifting of texts and rects.
Closes #27358.

[DOC]: Fix menu example

---

doc/devel/index.rst

Motivated by a top issue for new contributors being that they're not using the dev docs. xref #18402
So I tried to version guard this so the admonishment will only show on non devel versions but I don't think I can test if this works on non-backports. Aim is it looks like this

Doc: add a "please use dev version" to top of contribute docs

---

lib/matplotlib/tests/test_datetime.py

Removing the test_spy for datetime, since does not make sense for unitful data. Spy is related to plotting at array indices, and provides no way of setting the x and y values to non-integer data.
Therefore, this PR aims to remove test_spy. …

Remove test_spy from test_datetime.py

---

.github/workflows/tests.yml

This seems to be a broken wheel release from upstream: https://www.riverbankcomputing.com/pipermail/pyqt/2023-November/045606.html …

ci: Block PyQt6 6.6.0 on Ubuntu

---

lib/matplotlib/axes/_axes.py
lib/matplotlib/tests/test_axes.py

Closes #27399
I went with the first approach in https://github.com/matplotlib/matplotlib/issues/27399#issuecomment-1833563420

Check that xerr/yerr values are not None in errorbar

---

galleries/examples/text_labels_and_annotations/custom_legends.py
lib/matplotlib/axes/_axes.py
lib/matplotlib/legend.py
lib/matplotlib/tests/test_legend.py
lib/matplotlib/tests/test_pickle.py

Fixes #27145
Also add test_legend_nolabels_warning()
After discussion in the linked issue, it was determined that `warnings.warn()` was better than `log.warning()` for alerting users that we can't draw a legend if there are no labels.  This PR implements the change from `log.warning()` to `warnings.warn` (actually, `_api.warn_external()`)

ENH: Change logging to warning when creating a legend with no labels

---

lib/matplotlib/axis.py
lib/matplotlib/colorbar.py

Add `AsinhScale` to list of built-in scales.

DOC: Add AsinhScale to list of built-in scales

---

galleries/examples/ticks/multilevel_ticks.py

This adds an example showing one method of adding multilevel ticks to a plot.  
Not a substitute for https://github.com/matplotlib/matplotlib/issues/6321, but shows that it's possible with minimal fussing. Also partially addresses https://github.com/matplotlib/matplotlib/issues/27394, or at least gives an example of how to achieve the date axis effect discussed there

DOC: multilevel tick example

---

lib/matplotlib/tests/test_backends_interactive.py

There are currently 7 backends, and this function is called 8 times during test collection. This means that `XOpenDisplay` would be called 56 times (multiplied by process count if using xdist).
Locally, I'm seeing a deadlock after too many calls to `XOpenDisplay` during collection. While this is not directly our bug, it seems prudent to cut this down to only the one check per collection process.
I don't think we can cache this globally, as one might want to re-try a GUI figure after starting an X server (e.g., over SSH or similar), without restarting Python/Matplotlib.
- [n/a] *Plotting related* …

TST: Cache available interactive backends

---

lib/mpl_toolkits/mplot3d/art3d.py
lib/mpl_toolkits/mplot3d/tests/test_axes3d.py

closes #27361
The solution is a slightly adapted version of 1868c05e622ad521efd5671e47eef6bd35e0b8c9 as was suggested by the author @oscargus.
I've added a test for the specific test for the issue which now passes.

Fix get_path for 3d artists

---

lib/matplotlib/tests/test_widgets.py
lib/matplotlib/widgets.py

In the following example, if the first click is outside of the span selector, the span selector will be reset on the press event, while it shouldn't. The reason is that when setting `extents` programmatically after initialisation of the span selector, the attribute `_selection_completed` should be `True`, otherwise the span selector will behave as the selection was incomplete!
```python
from matplotlib.widgets import SpanSelector
ax.plot(range(40))
span = SpanSelector(
ax,
onselect=lambda a, b:None,
direction="horizontal",
interactive=True,
drag_from_anywhere=True,
ignore_event_outside=True,
)
span.extents = (10, 20)
``` …

Fix setting `_selection_completed` in `SpanSelector` when spanselector is initialised using `extents`
