- lib/matplotlib/tests/test_datetime.py
add code for test_fill_between in test_datetime.py as requested in #26864.
Output image:
> Add test for fill_between in test_datetime.py

- lib/matplotlib/artist.py
- lib/matplotlib/offsetbox.py
- lib/matplotlib/tests/test_offsetbox.py
- Picking on subfigures was broken because `ax = getattr(a, 'axes', None)` would return the SubFigure.axes *list* when `a` is a subfigure, so the axes identity test would just be completely wrong.  Fix that by special-casing subfigures.  (Ideally I would entirely remove the axes equality test because that also breaks in the case of overlapping axes, but that's a much bigger change.)
- `ref_artist.figure._canvas_callbacks` would fail when the ref_artist is on a subfigure because subfigures don't have a _canvas_callbacks attribute; instead use `ref_artist.figure.canvas.callbacks` where accessing the canvas attribute correctly goes back to the toplevel figure first.
See test for an example (which would previously fail with an AttributeError).
> Fix draggable annotations on subfigures.

- lib/matplotlib/tests/test_datetime.py
Added code for `test_broken_barh` in `test_datetime.py` as requested in #26864
Here is an image of the output: …
> Added test for broken_barh to test_datetime.py

- lib/matplotlib/tests/test_datetime.py
I have added a datetime/timedelta smoke test for Axes.bxp in lib/matplotlib/tests/test_datetime.py.
This addresses the Axes.bxp task from https://github.com/matplotlib/matplotlib/issues/26864.
The image below is the plot generated from this smoke test/example code.  …
> Add test_bxp in test_datetime.py

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_datetime.py
Currently `xcorr` and `acorr` are in `test_datetimes.py`.  However, I think it is highly unlikely anyone would want to pass datetimes in as `x` values to either of these methods.  It is also not clear what giving the unit conversion means for these arguments.  Modified the docstrings to make this clear.
> MNT/TST: remove xcorr and acorr from test_datetime

- lib/matplotlib/tests/test_datetime.py
Added code for test_fill_betweenx in test_datetime.py as requested in https://github.com/matplotlib/matplotlib/issues/26864
Image for an output
> Added test_fill_betweenx in test_datetime.py 

- lib/matplotlib/tests/test_datetime.py
I have added a datetime smoke test for `Axes.vlines` in `lib/matplotlib/tests/test_datetime.py`. It includes a combination of dates and floats for the axes as well as scalars and arrays for ymin and ymax.
This addresses the `Axes.vlines` task from #26864.
Here is an image of the plots: …
> Add test_vlines to test_datetime.py

- lib/matplotlib/tests/test_datetime.py
I have added a datetime/timedelta smoke test for Axes.bar_label in lib/matplotlib/tests/test_datetime.py.
This addresses the Axes.bar_label task from https://github.com/matplotlib/matplotlib/issues/26864.
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-c …
> Added test for Axes.bar_label

- LICENSE/LICENSE_STIX
The `LICENSE_STIX` files have been out of sync and provided two different terms. This PR synchronizes them by using the more recent version of both.
https://github.com/matplotlib/matplotlib/blob/main/LICENSE/LICENSE_STIX has been created in 2007 and never modified, while https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/mpl-data/fonts/ttf/LICENSE_STIX has been updated in 2010 with new licensing terms: https://github.com/matplotlib/matplotlib/commit/fda682ed211ce7d3e473a3ad733e143389ede712. This made it confusing which actually is the correct license text.
- [N/A] new and changed code is …
> DOC: Synchronize LICENSE_STIX files

- lib/matplotlib/tests/test_datetime.py
This PR adds a smoke test for `Axes.matshow` in lib/matplotlib/tests/test_datetime.py and addresses task `Axes.matshow` in issue https://github.com/matplotlib/matplotlib/issues/26864.
Below is the image of the generated plot:
- [NA ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [NA] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [NA] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines
> Added smoke test for Axes.matshow to test_datetime.py

- galleries/users_explain/figure/api_interfaces.rst
The Pylab import statement was incorrectly given as `matplotlib.pyplot import *` in the description of the pylab interface  in the Matplotlib API overview, https://matplotlib.org/stable/users/explain/figure/api_interfaces.html#appendix-pylab-interface. 
Replaced `pyplot` with `pylab` and replaced the description accordingly using https://matplotlib.org/stable/api/pylab.html.
> Fixing Pylab documentation in API interface overview

- galleries/examples/text_labels_and_annotations/label_subplots.py
The ability of annotate to specify various coordinates systems simplifies label_subplots, by avoiding the need to explicitly construct a ScaledTranslation (while maintaining exact functionality parity).
> Use annotate coordinate systems to simplify label_subplots.

- lib/matplotlib/tests/test_datetime.py
I have added a datetime smoke test/example code under the test_eventplot method in lib/matplotlib/test/test_datetime.py. This addresses the Axes.eventplot task from https://github.com/matplotlib/matplotlib/issues/26864. 
(edited) The plots generated from the latest test code:
> Add test_eventplot to test_datetime.py

- doc/users/installing/dependencies.rst
My latex and fonts have imploded and started deleting themselves and doing a minimal texlive install, I also needed ``collection-fontsrecommended` for the docs to not error out.
> DOC: add collection-fontsrecommended to dependencies

- lib/matplotlib/tests/test_datetime.py
This PR adds a smoke test for `Axes.imshow` in lib/matplotlib/tests/test_datetime.py and addresses task `Axes.imshow` in issue https://github.com/matplotlib/matplotlib/issues/26864. Due to the behavior of `Axes.imshow` with the `mpl.rcParams["date.converter"] = "concise"`, I included year, month, day, and time axis scale plots.
Below is the image of the generated plot:
- [NA ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [NA] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [NA] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest- …
> Added smoke test for Axes.imshow to test_datetime.py

- lib/matplotlib/_pylab_helpers.py
`del manager, num` made sense prior to 9f3861f when we used to then call gc.collect(1) (so we needed to delete the variables from the local frame so that they can be gc'ed if needed), but we have since then removed the explicit gc call; thus the del statement doesn't really do anything anymore (the local frame is about to be destroyed and thus all local variables will be decref'ed anyways).
> Remove unnecessary del local variables at end of Gcf.destroy.

- lib/matplotlib/axes/_base.py
Even axisbelow(True) sets the grid zorder to 0.5, which is still over images (zorder 0).  One may want to have grids *below* images if the image's extent doesn't cover the whole axes limits (e.g. the image only occupies the top left corner of the Axes and one wants to draw gridlines on the rest but keep them below the image otherwise).
(I got bitten by this today...)
> Clarify that set_axisbelow doesn't move grids below images.

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_axes.pyi
- lib/matplotlib/pyplot.py
`axline` returns an `AxLine` instance.
```
In [3]: ax.axline((0, 0), (1, 1))
Out[3]: <matplotlib.lines.AxLine at 0x7f5bf0a1ed10>
```
> DOC: correct return type for axline

- lib/matplotlib/tests/test_transforms.py
This is implicitly tested via all plots and layout. However, this makes it difficult to work on the transform stack directly (cf #22191), which these tests rectify.
I deliberately chose points/angles that were easy to work out in my head, so hopefully there are not any edge cases that were missed here. (Except for `skew`, for which I don't have an inherent idea of what that transform looks like, so I admit to just copy-pasting the existing output there.)
- …
> TST: Add tests for Affine2D

- doc/api/next_api_changes/deprecations/27513-OG.rst
- lib/matplotlib/tests/test_transforms.py
- lib/matplotlib/transforms.py
One may consider deprecating `BboxTransformToMaxOnly` as it is not used in the code base. But at least the doc-string should be correct.
> Fix docs and add tests for transform and deprecate `BboxTransformToMaxOnly`

- lib/matplotlib/tests/test_axes.py
We don't want to replicate the entire calculation from the implementation, or they could both be buggy, but I think this is a reasonable compromise. And using the `top`/`bottom` variables make the `step`/`stepfilled` difference clearer to me. …
> TST: Compress some hist geometry tests

- .github/workflows/stale-tidy.yml
- .github/workflows/stale.yml
Since nobody objected to my comment at https://github.com/matplotlib/matplotlib/pull/27495#issuecomment-1851841617, I went ahead and implemented that.
For the existing workflow
* reduced `operations-per-run` to 20.  If I've done this right, that means we get a maximum of five issues/PRs labelled as inactive for each run, and so max 15 per week.
* bumped the action version to 9, so supercedes and closes #27495.
Because the existing workflow won't get around to checking the issues it already labelled for a long time, add a new workflow to tidy up after the first one.  The difference between the two workflows is:
```diff
< name: 'Label inactive PRs'
---
> name: 'Close inactive issues'
4c4
<     - cron: '30 1 * * 1,3,5'
---
>     - cron: '30 1 * * 2,4,6'
14,15c14,15
< …
```
> Changes for stale GHA v9

- src/_macosx.m
This would slow down the typing at a command prompt while waiting for stdin from the programs because each character would bounce for 0.01 seconds adding up to a noticeable slowdown when piping in characters from an external source. I _thought_ this was needed while I was testing which is why I added that comment, but I just went through a few interactive test cases including the one from https://github.com/matplotlib/matplotlib/issues/26869 which all still worked interactively, and updated the display as expected. So I think we can safely remove it, but I'm not 100% on that.
The only way I could get this to fail was to interactively from my IDE "shift+enter" on the code blocks so that input was piped in. Is there a way to get that same effect in the interactive tests so we could add it …
> FIX: Remove runloop execution while waiting for stdin

- lib/matplotlib/lines.py
Closes #27503 following https://github.com/matplotlib/matplotlib/issues/27503#issuecomment-1852937929.
> Clarify AxLine Params

- src/_macosx.m
The macos timers need to be explicitly added to the main runloop so the drawing takes place there. This causes issues if updating data from other threads and wanting the plot to update.
Fixed previously in: https://github.com/matplotlib/matplotlib/pull/25553
Which then had a regression via: https://github.com/matplotlib/matplotlib/pull/26022 which apparently uses a method that puts the timer onto the currently active thread rather than the main one. So, we need to explicitly add the timer to the main runloop.
I tried adding this as an interactive test, but couldn't get it to trigger the draws properly from the subprocess (not sure if it is because we need to set something up differently when running as `python -i` from a subprocess?). Any thoughts folks have for how to test this so we …
> FIX: Add macos timers to the main thread

- doc/devel/api_changes.rst
- doc/devel/coding_guide.rst
- doc/devel/contribute.rst
- doc/devel/index.rst
- doc/devel/license.rst
- doc/devel/pr_guide.rst
- doc/devel/triage.rst
This is in the vein of #26196 and the high level improvement is that via reorganizing:
* top card of the contribute landing page == roadmapped index into contribute.rst 
* each card in the policies and guidelines page is now a toctree:
Also much better left hand side since I understand how to make those now thanks to @jklymak (yes it took me this long to sort out that LHS goes by toctrees, like RHS goes by headers):
The other changes are:
* pr-guidelines gets its own new page and moved to triage/review b/c it applies to code and doc contributions. 
* https://output.circle-artifacts.com/output/job/46bfc24c-2f79-4092-b58f-e33bfd97f436/artifacts/0/doc/build/html/devel/pr_guide.html#pr-guidelines 
* coding guidelines is moved out of contribute into coding_guidelines.rst, which cleans up the …
> DOC: reorganizing contributing docs to clean up toc, better seperate topics

- doc/api/next_api_changes/behavior/27514-OG.rst
- doc/api/next_api_changes/deprecations/27514-OG.rst
- lib/matplotlib/transforms.py
Passing something else than a `Transform` would lead to an `AttributeError`, but now the better error message should show up. …
> Improve check for bbox

- doc/devel/contribute.rst
Accidentally used \ rather than / for a `` :file:`matplotlib/lib` `` so the \ didn't get rendered.
> DOC: typo fix in contribute doc

- doc/sphinxext/custom_roles.py
- lib/matplotlib/widgets.py
The role is intended to be used for type references in docstrings like
```
Parameters
----------
color : :mpltype:`color`
```
It is easily extendable to other types.
The naming `:mpltype:` was a quick choice. I'm open to other names. (Note that `:type:` seem to be available, but I'm inclinded to say it's too generic: People will find it in the code and have a hard time figuring out where it comes from.)
This PR contains one example usage in `widgets.Button` so that one can see the effect in the built docs. Systematic application throughout the codebase should be deferred to a separate PR.
Closes #24859.
Formalizes #27164.
> DOC: Add role for custom informal types like color

- .appveyor.yml
- .github/workflows/tests.yml
- azure-pipelines.yml
This enables coverage for compiled code on macOS GitHub Actions, as well as all platforms on Azure Pipelines.
Unfortunately, I don't see any coverage for the Objective-C macosx backend, even though my testing showed that the flag was passed in there. …
> ci: Improve coverage for compiled code

- lib/mpl_toolkits/axisartist/grid_finder.py
- lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
Instead of representing the information about tick and gridlines as
```python
{
"lon_lines": [line, ...],  # unused
"lat_lines": [line, ...],  # unused
"lon": [
"tick_levels": [level, ...],
"tick_locs": {"left": [(xy, angle), ...], "bottom": [(xy, angle), ...], ...},
"tick_labels": {"left": [label, ...], "bottom": [label, ...], ...},
"lines": [line, ...],
],
"lat": ...,  # as for lon
}
```
where the locs and labels are implicitly associated by the iteration order, group the information for each tick, and remove the redundant gridlines info as well:
```python
{
"lon": {
"lines": [line, ...],
"ticks": {
"left": [
{"level": level, "loc": (xy, angle), "label": label}, ...
],
"bottom": [...], ...,
}
}
"lat": ...,  # as for lon
}
```
(This representation turns out to make the implementation …
> Transpose grid_finder tick representation.

- doc/devel/tag_glossary.rst
- galleries/examples/subplots_axes_and_figures/multiple_figs_demo.py
Changed `plot type` to `plot-type` cause the space is already being tripped over https://matplotlib.org/devdocs/_tags/tagsindex.html#tagoverview and it's easier to git grep `plot-type` attn: @esibinga
> DOC: changed tag `plot type` to `plot-type`

- .github/workflows/tests.yml
- azure-pipelines.yml
Increase coverage of locale tests.
This will hopefully make coverage on the tests less noisy by reducing the chance we skip this test.
> CI: install German lanugage packs an ubuntu test runners

- lib/matplotlib/figure.py
Added the version of the currently running Matplotlib to the user warning when loading a pickle from a different of Matplotlib.
> MNT: add the running version to pickle warning message

- lib/matplotlib/projections/polar.py
- lib/matplotlib/tests/test_polar.py
Fixes the setting of theta tick labels when the theta limits span a whole circle, but the lower theta limit != 0 degrees.
Fixes https://github.com/matplotlib/matplotlib/issues/25568
-->
> Fix polar labels with negative theta limit

- doc/api/next_api_changes/deprecations/24834-DS.rst
- galleries/examples/axisartist/demo_axis_direction.py
- galleries/examples/axisartist/demo_curvelinear_grid.py
- galleries/examples/axisartist/demo_floating_axes.py
- galleries/examples/axisartist/demo_floating_axis.py
- galleries/examples/axisartist/simple_axis_pad.py
- lib/matplotlib/projections/polar.py
- lib/matplotlib/projections/polar.pyi
- lib/matplotlib/tests/test_transforms.py
- lib/matplotlib/text.py
- lib/mpl_toolkits/axisartist/tests/test_floating_axes.py
- lib/mpl_toolkits/axisartist/tests/test_grid_helper_curvelinear.py
This parameter was introduced in https://github.com/matplotlib/matplotlib/pull/4699 for backwards compatabilty reasons, when shifting theta values was refactored out of `PolarTransform`.
- It think it's reasonable to **not** expect `PolarTransform` to do a theta shift first
- We do not currently test the case `_apply_theta_transforms = True`
- Removing this will simplify the polar transform code slightly
So I think it's worth deprecating and eventually removing this.
> Deprecate apply_theta_transforms=True to PolarTransform

- lib/matplotlib/tests/test_lines.py
- src/_path_wrapper.cpp
> Fix is_sorted_and_has_non_nan for byteswapped inputs.

- environment.yml
- requirements/testing/all.txt
Each calendar year black can make updates/changes to how they format code (see the [black stability policy](https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy)). To make sure our autogenerated `pyplot.py` corresponds to a particular version of `black`, add a pin to the version. When we want to update we can then bump the major version of black and regenerate `pyplot.py` in sync. 
Fixes partially https://github.com/matplotlib/matplotlib/issues/27529 - I'm not sure if there's a way to run the weekly GH actions workflows on a PR to check this works?
> Pin black version

- doc/users/next_whats_new/formatter_unicode_minus.rst
- lib/matplotlib/tests/test_ticker.py
- lib/matplotlib/ticker.py
This is better than the workaround of wrapping the expression in
mathtext (as suggested for the old-style FormatStrFormatter) because it
also works for the hover tooltip in the toolbar (which cannot display
mathtext).
Note that it is not as easy to do so for FormatStrFormatter
(%-formatting) as that would require manually parsing the format string;
I would not bother as that formatter seems to be mostly present for
backcompat.
Goes on top of #27601.
> Let FormatStrFormatter respect axes.unicode_minus.

- doc/api/next_api_changes/removals/26884-JS.rst
- lib/matplotlib/_fontconfig_pattern.py
- lib/matplotlib/tests/test_fontconfig_pattern.py
This PR removes the deprecated code during the version 3.7 from lib/matplotlib/gridspec.py and lib/matplotlib/_fontconfig_patterns.py issues here: https://github.com/matplotlib/matplotlib/issues/26865.
> Remove deprecated code from _fontconfig_patterns

- doc/api/next_api_changes/behavior/27605-DS.rst
- lib/matplotlib/cbook.py
- lib/matplotlib/tests/test_axes.py
Ignore masked data points when plotting boxplots (and calculating boxplot statistics). Fixes https://github.com/matplotlib/matplotlib/issues/13533.
Replaces https://github.com/matplotlib/matplotlib/pull/13651 with a much simpler fix.
> Ignore masked values in boxplot

- .github/PULL_REQUEST_TEMPLATE.md
Adds a space between the summary and checklist b/c currently that lack of space makes distinguishing between the two sections really hard.
> MNT: add spaces to PR template

- doc/api/next_api_changes/behavior/27589-DS.rst
- lib/matplotlib/colors.py
- lib/matplotlib/tests/test_colorbar.py
- lib/matplotlib/tests/test_colors.py
This updates the behaviour of `PowerNorm` to linearly normalize input values < vmin, instead of clipping them.
Fixes https://github.com/matplotlib/matplotlib/issues/25239; replaces https://github.com/matplotlib/matplotlib/pull/25256. See discussion at https://github.com/matplotlib/matplotlib/pull/25256 for more context on this.
> Don't clip PowerNorm inputs < vmin

- lib/matplotlib/image.py
- lib/matplotlib/tests/test_image.py
This is probably the best we can do to fix #27554 at this time, without delving into re-writing the Agg resampler (which, as the Python code notes, does require RGBA.)
Also adds a test, as it appears that nothing checked an RGB input with transparent `alpha` (and my original suggestion from https://github.com/matplotlib/matplotlib/issues/27554#issuecomment-1867431791 using 255/1.0 passed tests even though it didn't work.) …
> Avoid an extra copy/resample if imshow input has no alpha

- .github/workflows/tests.yml
Should avoid CI being duplicated on dependabot PRs (see https://github.com/matplotlib/matplotlib/pull/27628 for an example before this PR)
> Don't run CI twice on dependabot branches

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
If xmin/xmax or ymin/ymax are the wrong way around in `hexbin()`, raise an error. As noted in https://github.com/matplotlib/matplotlib/pull/18875 (which this is pulled from), this prevents issues with the hexbin marginals not being displayed at all if they are requested.
- [n/a] …
> Error on bad input to hexbin extents

- .circleci/config.yml
Circle is warning about this being deprecated:
https://circleci.com/docs/migrate-from-deploy-to-run/ …
> circle: Make deploy stage into a normal step

- .github/labeler.yml
- .github/workflows/labeler.yml
I believe this was not previously usable due to Actions permission changes, but now that the `pull_request_target` trigger exists, it should work again. Unfortunately, because it uses `pull_request_target`, there's no way to test until it's merged.
This is mainly to catch issues like #27628 which should have been labelled with `Run cibuildwheel` to show that it was broken.
Labelling the topics is a bit arbitrary, but I think I've covered enough of them. …
> Auto-label PRs based on changed files

- lib/matplotlib/_docstring.py
- lib/matplotlib/_docstring.pyi
- lib/matplotlib/artist.py
- lib/matplotlib/text.py
As discussed in today's dev call. The effect is visible in the `Axes.text` docstring:
I slightly underestimated the number of artist properties we have. Instead of a few hundred, we have 4119 artist properties. :astonished:. Anyway, using a string given via the decorator should be significantly faster than scraping the docstring for such info. I'm 99.9% certain we won't have longer import times due to the decorator mechanism.
> Proof of concept for adding kwdoc content to properties using a decorator

- .github/workflows/cibuildwheel.yml
- .github/workflows/tests.yml
Also bump the `artifacts` actions to v4.
Note that normally the whole `publish` job should be skipped on non-release events, but I want to confirm that the `artifacts` download stuff works.
- …
> Enable PyPI publishing from GitHub Actions

- lib/matplotlib/_docstring.py
Got merged with small typo in docstring (surprised it wasn't caught by the pre-commit :/) so fixed that. Also added a comma b/c phrase seemed parenthetical.
> Doc: typo fix for #22699

- lib/matplotlib/font_manager.py
... instead of only relying on a fixed list of directories to check.  Note that both previously and with this PR, we continue also querying fontconfig.
See #10932.  This should close the original issue (#10201); for #10932 I would suggest further dropping out the extra hard-coded directories (X11FontDirectories, OSXFontDirectories) that are searched.
> Query macOS for available system fonts.

- .github/labeler.yml
The default is `any`, so the negated glob matches almost all PRs accidentally. So we need to wrap this in an `all` so it's just toolkits-but-not-mplot3d. …
> ci: Fix mpl_toolkits label

- doc/api/font_manager_api.rst
- galleries/examples/widgets/menu.py
- lib/matplotlib/_text_helpers.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/font_manager.py
When these were added in #20118, we had no type annotations, so it made sense to use the functional form. Now that we do, there's no reason not to use the class form.
Also, as `FontEntry` has gained more methods, the functional form looks less clear.
Also, use one in the menu example.
> Use class form of data classes 

- .github/workflows/mypy-stubtest.yml
- .gitignore
- doc/devel/coding_guide.rst
- environment.yml
- tox.ini
This gives developers the option of running stubtests using `tox`. This is useful, because the stubtests can't be run on local editable installs (see https://github.com/matplotlib/matplotlib/issues/27580).
I've added a test commit that breaks stubtest deliberately to show this works - I will leave this here for review purposes, then force push it away once this has one approved review.
~~I can't get this to give me a true negative result locally though 😢 . With the below diff (saved, but unstaged in git), running `tox -e stubtest` still gives me a successful result. I'll investigate a bit further, but I don't suppose anyone has any ideas?~~
Fixes https://github.com/matplotlib/matplotlib/issues/27580.
> Add option of running stubtest using tox

- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/tests/test_backend_pdf.py
- lib/matplotlib/tests/test_colors.py
- lib/matplotlib/tests/test_rcparams.py
- lib/matplotlib/tests/test_ticker.py
The behavior of pytest.warns has changed, particularly with regards to handling of additional warnings
When additional warnings that were not tested for are raised, I simply add a `filterwarnings` (some are artifacts of `with` blocks).
And there are a couple that seem are not actually currently warning at all, but had been occluded by a `pytest.errors`.
> Prepare for Pytest v8

- doc/devel/api_changes.rst
- doc/devel/coding_guide.rst
Spun docs changes out of #27641 to let that one go through faster. Changes here are:
* based on @timhoffm's suggestions at https://github.com/matplotlib/matplotlib/pull/27641#discussion_r1451805456 
* changed `API->changes` to `API->guidelines`
* prioritized new features
* reworked heirarchy in `API Guidelines` so top level is announce, add new features, deprecate
* added a call out in coding guidelines to direct to API guidelines:
* and since the white space balance feels weird to me, commit 2:
> DOC: Added call out to API guidelines to contribute + small API guidelines reorg

- lib/matplotlib/tests/test_ticker.py
- lib/matplotlib/ticker.py
Closes https://github.com/matplotlib/matplotlib/issues/26484. Having `minorticks_on()`  in a multi-Axes Figure that contains more than one boxplot and shares the x-axis was raising an OverflowError. 
As @ksunden pointed out in https://github.com/matplotlib/matplotlib/issues/26484#issuecomment-1674018344, the boxplots set the Locator and Formatter of one axis to be FixedLocator/FixedFormatter, without handling repeated values. This leads to multiple repeated values for the Major ticks, which then the `AutoMinorLocator` does major[1] - major[0] to get the spacing of the major, which returns zero and then divides by 0, leading to the error.
I've implemented the option on the first bullet point of the above comment to call `np.unique` on the `majorticklocs` in `AutoMinorLocator`. This fix …
> Fix error that occurs when minorticks are on multi-Axes Figure with more than one boxplot

- lib/matplotlib/pylab.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_colors.py
Closes #27645 (technically combination of this and #27624, but the comments I've left on there have all been about this part)
Numpy made tweaks to dtype promotions that affected some computation (but only at the limits of floating point precision)
This PR counter acts these:
- `pie` image tests have a tolerance introduced
- could perhaps tweak some of the exact values down a bit, but none were more than (0.01 RMS)
- All differences were imperceptable as a human, and _some_ tolerance would be required regardless, so I did not replace the images
- Technically could be changed by setting the env var `NPY_PROMOTION_state=legacy`, but that is changing intendid numpy 2.0 behavior
- `pylab` updated to ensure builtins are used for two more functions now included in numpy's namespace that occlude …
> Fix Numpy 2.0 related test failures

- lib/matplotlib/tests/test_ticker.py
- lib/matplotlib/ticker.py
Fix error that occurs when minorticks are on multi-Axes Figure with more than one boxplot
(cherry picked from commit b03407b375d8a4b5101f40178f9d19b84bfce822)
> Backport of pr 27647 on v3.8.x

- .github/workflows/cygwin.yml
- .github/workflows/tests.yml
- azure-pipelines.yml
- doc/api/prev_api_changes/api_changes_3.5.0/deprecations.rst
- doc/api/prev_api_changes/api_changes_3.7.0/removals.rst
- doc/devel/testing.rst
- pyproject.toml
This fixes the rewriting so that we get detailed variable information again, which was broken with the move to Meson (which does weird import hacking for editable installs.)
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) …
> TST: Use importlib for importing in pytest

- .github/workflows/mypy-stubtest.yml
- .github/workflows/reviewdog.yml
I presume this is more recent than when reviewdog was setup. Saves a few lines and makes for easier maintenance in the future.
> Use GH action to install reviewdog

- src/_macosx.m
This suppresses a warning that appears with MacOS 14+. `WARNING: Secure coding is not enabled for restorable state!`
Thanks, @QuLogic and @tacaswell for the pointers on what needed to be done!
Testing: It seems like Python compiled with clang 15+ doesn't produce this warning, but installing Python 3.12 downloaded from python.org uses clang 13 and I do get the warnings locally.
Running a simple script you should see the warnings on main and then they should go away on this branch.
```
plt.plot([1, 2, 3])
plt.show()
```
closes #27389
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and …
> Implement macos AppDelegate

- doc/api/next_api_changes/development/27676-ES.rst
- extern/meson.build
- subprojects/freetype-2.11.1.wrap
We needed the new version because autotools didn't know about Windows-on-ARM. But we build with Meson now, and overlay a Meson build system for FreeType, so it either works for both of us or it doesn't (and it does).
Dropping down to the older version means that tests pass on Windows ARM without any need to mess with tolerance or generating new images.
Note: we don't build for Windows on ARM because dependencies aren't there, but they're quite close, so we can enable that soon.
- [n/a] *Plotting related* features …
> BLD: Downgrade FreeType to 2.6.1 on Windows ARM

- .github/labeler.yml
PRs that touch `doc/users/next_whats_new/*` because they have a new feature shouldn't be labelled as "user guide" updates, and similar for API notes.
- [n/a] Documentation …
> ci: Don't include API/what's new notes in general doc labels

- .github/workflows/tests.yml
This is to keep coverage in the test suite up and reduce false-negatives on PRs.
After the pre-release cron job runs the base coverage includes additional uploads.
> CI: skip code coverage upload on scheduled tests

- lib/matplotlib/patches.py
See the docstring of `Patch.contains_point`: 
https://github.com/matplotlib/matplotlib/blob/09eab5b1c471410d238b449ebbac63f70759fc21/lib/matplotlib/patches.py#L174-L197
It explains that one has to use data coordinates when using `contains_point` but then provides an example that uses `Circle` and `get_transform` which isn't correct. This has lead to confusion in the past, see #23178.
The proposed changes in this PR will move the example to use `get_data_transform` and uses values which would fail if one were to use `get_transform`. 
IMHO this closes #23178.
> doc: fix Patch.contains_point docstring example

- doc/users/release_notes.rst
This came in via #21251 and I vaguely remember it had a purpose (possibly something with navigation / what is rendered in the sidebars?) However, in the
current docs, it looks rather useless: https://matplotlib.org/devdocs/users/release_notes.html
Ping @jklymak do you remember why you added a "Past versions" section?
> Remove "Past versions" section from release notes

- .github/labeler.yml
According to the error message and the [labeler docs](https://github.com/actions/labeler#match-object), I think this was a typo. 
eta: also I think running into https://github.com/actions/labeler/issues/628 and not sure if the fix is it needs to be fixed here and that'll fix it or combined w/ a checkout option.
> MNT: fix labeller

- azure-pipelines.yml
The prerelease build was dropped about 3 years ago in 6dde94539f1cf997fa2f503e02f8bf71ffe032e2. …
> ci: Remove prerelease conditions from Azure Pipelines

- lib/matplotlib/backends/backend_gtk4.py
When I try to save a figure using the gtk4 file chooser the default format is `PGF code for LaTeX`, but it should be "png" because I set  `rcParams["savefig.format"] = 'png'` . The default file extension is still `.png` , confusingly. This only started happening after I recently upgraded my system to gtk4. 
Looking at the code, I see an indexing bug when choosing the default format: The previous lines to my diff reorganized the format order so that the default format is the first in the list, therefore to get the default one should use index 0, not the old index before reordering.
- [N/A ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [] new and changed …
> fix default image format in gtk4 savefig dialog

- lib/matplotlib/ticker.py
Improves `Locator` docstrings by adding a single sentence at the beginning of each docstring in a consistent style.
> Improve Locator docstrings

- .circleci/config.yml
- doc/devel/coding_guide.rst
- doc/devel/development_workflow.rst
- Added link to [github docs](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs) that @ksunden  shared and info about what runs workflows are applied to b/c it's useful for debugging actions
- rearranged things to removed nested bullet lists b/c I find nested bullets hard to read
- made skipping its own section b/c convenient for linking
> DOC: clean up automated tests section of workflow docs

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_legend.py
Continuation of PR https://github.com/matplotlib/matplotlib/pull/27568
Fixes https://github.com/matplotlib/matplotlib/issues/20512
> Fix boxplot legend entries part 2

- lib/matplotlib/figure.py
- lib/matplotlib/text.py
Rely on alias normalization machinery to make alias checking simpler and more robust (there are also aliases for fontproperties which were not checked before).
While at it, also slightly reorder Text aliases (this has no actual visible effect) to have the font properties and the alignments grouped.
Noted via #27630 (this should not interfere with the current PR for that issue).
> Simplify Figure._suplabels.

- .pre-commit-config.yaml
- CODE_OF_CONDUCT.md
- README.md
- doc/devel/contribute.rst
- doc/devel/release_guide.rst
- doc/index.rst
- doc/project/citing.rst
- doc/project/code_of_conduct.rst
- doc/project/credits.rst
- doc/project/history.rst
- doc/project/index.rst
- doc/project/license.rst
- doc/project/mission.rst
- tools/cache_zenodo_svg.py
This PR addresses the issue #27396 on moving non user guide related content out of /users. This is the first step, moving `/users/project` -> `/doc/project` and adding redirects.
> Moved /users/project to /doc/project

- galleries/users_explain/axes/legend_guide.py
Adds https://github.com/matplotlib/matplotlib/issues/27725#issuecomment-1921567751 and pulls content in the legend guide into a rename legend entries section cause it's a frequent ask and it's already somewhat documented here.
> DOC: Create explict rename legend entry section in guide

- doc/users/next_whats_new/update_arrow_patch.rst
- lib/matplotlib/patches.py
- lib/matplotlib/patches.pyi
- lib/matplotlib/tests/test_patches.py
Closes #14217. Adds `set_data` method from `FancyArrow` that allows the arrow to be repositioned without re-drawing.
Arrow's `x,` `y,` `dx`, `dy` and `width` parameters are now stored in private variables so that they can be reused for recreating the transform.
e.g.
```py
from matplotlib.patches import Arrow
ax.plot([0, 4], [10, 0])
a = mpl.patches.Arrow(2, 0, 0, 10)
ax.add_patch(a)
a.set_data(x=.5, y=0, dx=3, dy=8, width=1.2)
plt.show()
```
See the discussion here https://github.com/matplotlib/matplotlib/issues/14217#issuecomment-538072364. I don't know what the consensus is on the Arrow class but If this fix is still needed, I'll add a test and a what's new entry.
> Add method to update position of arrow patch

- .github/workflows/codeql-analysis.yml
The workflow is now warning that `CODEQL_PYTHON` should not be set, as it is no longer used. According to the message, we also don't need to install dependencies, so fold everything into the 'build-for-C++' step. …
> ci: Simplify CodeQL setup

- lib/matplotlib/tests/test_backends_interactive.py
It is flaky, and our memory "limit" is pretty much arbitrary. Testing with `tools/memleak.py` shows that memory usage generally rises and only stabilizes close to 200 figures, while this test only does a warmup of 2 figures. Waiting for equilibrium would take too long for a general test, so we might move this to a weekly job later.
For example, with _just_ Agg:
and with the flaky wxAgg:
It's true that the latter uses more memory, but it still takes about 200 or so figure to reach equilibrium.
Closes #27635
- [~] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [n/a] *New Features* and *API Changes* are …
> TST: Remove memory leak test

- galleries/examples/images_contours_and_fields/colormap_normalizations.py
- Turn each norm into a headed section.
- Link to each norm directly in text.
- Consistently use `Z` as data variable, and pass norms (or `vmin`) in the same order for every example.
- Label the colour bars.
- Tweak some descriptions to be clearer.
- Change data for SymLogNorm and use it for the custom norm and BoundaryNorm, in order to match their descriptions.
Fixes #27727
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-f …
> DOC: Improve colormap normalization example

- lib/matplotlib/testing/jpl_units/EpochConverter.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_units.py
This is a minimal change to make the usage from our tests consistent with expectations.
As far as I can tell, the inconsistency for datetimes actually _predates_ the switch of mpl epoch from Jan 0, 0000 to Jan 1, 1970.
We only ever actually instantiate with datetime objects in tests (or via adding/subtracting durations, which don't actually care about the epoch).
I suspect that usage of `jpl_units.Epoch` that _arent_ instantiated datetimes are actually incorrect due to the mpl epoch change.
They are accidentally measuring from mpl epoch due to usage of `date2num` and `num2date`, But they think they are measuring form Jan 1, 0000 (1 day off from what the code assumes is mpl's epoch).
Thus in effect, they are actually measuring from 1969-12-31 when run through the `EpochConverter`.
This …
> [TST] Make jpl units instantiated with datetimes consistent with mpl converters

- src/_macosx.m
Add START/END "ALLOW THREADS" macros to the event loop code.
This breaks the deadlock, which allows the GIL to be acquired in an alternate thread.
It is not clear to me why this is MacOS version dependent, but this does appear to work and seems sensible to me.
Closes #27720
- [xj] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines
> Allow threads during macos event loop

- ci/mypy-stubtest-allowlist.txt
- doc/api/next_api_changes/removals/26965-ER.rst
- doc/api/prev_api_changes/api_changes_0.99.rst
- doc/api/prev_api_changes/api_changes_3.2.0/behavior.rst
- doc/api/prev_api_changes/api_changes_3.3.0/deprecations.rst
- doc/api/prev_api_changes/api_changes_3.4.0/behaviour.rst
- doc/api/prev_api_changes/api_changes_3.6.0/behaviour.rst
- doc/api/prev_api_changes/api_changes_3.7.0/behaviour.rst
- doc/users/prev_whats_new/whats_new_1.2.rst
- doc/users/prev_whats_new/whats_new_3.4.0.rst
- doc/users/prev_whats_new/whats_new_3.5.0.rst
- galleries/examples/color/custom_cmap.py
- lib/matplotlib/_cm.py
- lib/matplotlib/cm.py
- lib/matplotlib/cm.pyi
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_colors.py
PR addresses removal of deprecated API's referenced in issue https://github.com/matplotlib/matplotlib/issues/26865
Removals:
* cm.register_cmap
* cm.unregister_cmap
* cm.get_cmap
* pyplot.register_cmap
> Removal of deprecated API cm

- doc/api/prev_api_changes/api_changes_1.3.x.rst
- doc/conf.py
- doc/devel/MEP/MEP13.rst
- doc/devel/api_changes.rst
- doc/devel/min_dep_policy.rst
- doc/devel/pr_guide.rst
- doc/devel/release_guide.rst
- doc/devel/triage.rst
- doc/users/prev_whats_new/whats_new_1.3.rst
- lib/matplotlib/_api/deprecation.py
- lib/matplotlib/tests/test_pyplot.py
- src/ft2font_wrapper.cpp
- tools/github_stats.py
EffVer very closely articulates what we are already doing.
This was discussed on the developer call last week and was positively received.
I used `git grep` to find all '* version' and `* release` referring to our releases (I left "minor version" in most places in the minimum dependency document when referring to other projects, but expanded the definition at the top).
----
I would like approval from 2 other steering council members before we merge.
> GOV: adopt EffVer

- galleries/plot_types/basic/plot.py
Inspired from the discussion in #27765: We should visually communicate that `plot()` covers all three variants: markers only, line+markers, line-only. They are visually distinct enough that it's not possible to infer the variants if you see only one.
In particular, it's important to communicate that you can draw markers only. We don't want to automatically drive people who want markers (e.g. some discrete measurements of a dependent variable y (x)) to scatter because that's the only one showing discrete markers in the overview.
> Add marker-only and line+marker visuals to the plot() plot types

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Closes #27770
This looks to be a numpy masked array problem, but multiplication doesn't trigger the spurious underflow, and probably is a touch faster as well.
> MNT: pcolormesh robust underflow

- .github/workflows/cibuildwheel.yml
- .github/workflows/cygwin.yml
- .github/workflows/good-first-issue.yml
- Bump the actions group with 3 updates
- Bump the actions group with 2 updates
Cherrypicked from #27715 and #27750, ignoring changes that had conflicts.
In particular, this does _not_ include updating the `[up|down]load_artifacts` actions to v4 (and any associated changes to make that work)
This _also_ does _not_ include the change to the CIBW action to automatically upload to PyPI, because we wanted to test that with RC rather than 3.8.3.
> Manual backport of dependabot cibw upgrades

- galleries/examples/statistics/boxplot_color.py
The [original example](https://matplotlib.org/3.8.0/gallery/statistics/boxplot_color.html) was more complex than need be:
- The two plots only differed in the `notch=True` parameter, which is irrelevant for custom fill colors -> reduce to one
- rework to a more realistic-like plot
> Simplify example: Box plots with custom fill colors

- lib/matplotlib/bezier.py
- lib/matplotlib/tests/test_bezier.py
Closes #27753
This is usually an internal detail of things like `FancyArrowPatch`. The failure mode
is an infinite loop. Since the only case we are changing never worked, no API note is
included
> Add protections against infinite loop in bezier calculations

- lib/matplotlib/testing/__init__.py
- lib/matplotlib/tests/test_backend_nbagg.py
- lib/matplotlib/tests/test_backend_webagg.py
- lib/matplotlib/tests/test_basic.py
- lib/matplotlib/tests/test_determinism.py
- lib/matplotlib/tests/test_font_manager.py
- lib/matplotlib/tests/test_matplotlib.py
- lib/matplotlib/tests/test_rcparams.py
- lib/matplotlib/tests/test_texmanager.py
If you are using this and really need unbounded timeouts, explicitly pass `timeout=None`
This is an attempt to avoid azure from hanging and then timing out.
> TST: always set a (long) timeout for subprocess and always use our wrapper

- lib/matplotlib/backends/backend_pgf.py
On windows on py312 we can not use `.communicate` during process shutdown because it internally uses Python threads which can no longer be created during interpreter shutdown.
Closes #27437
> FIX: be careful about communicating with subprocess

- doc/api/next_api_changes/deprecations/27768-REC.rst
- galleries/examples/misc/demo_ribbon_box.py
- lib/matplotlib/axis.py
- lib/matplotlib/image.py
- tools/stubtest.py
Closes #27745
I am very much appreciating how easy the deprecation module makes this :+1:
> MNT: deprecate draw method args and kwargs

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_legend.py
This PR removes the propagation of `boxplot(..., labels=...)` to any artist legend labels introduced in #27711.
Other than the rest of the plotting functions `labels` is not used for legend labels but for xtick labels. This is only poorly documented via https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.bxp.html and in an [example](https://matplotlib.org/stable/gallery/statistics/boxplot_color.html).
Whatever our way forward regarding the use of `labels` is, we should by no means propagate them simultaneously to xticks and legend entries. This coupling would cripple users' configurability and limit our ability to migrate to a clear API where legend labels and tick labels can be configured independently.
Until we have sorted out a better API (xref …
> Partly revert #27711

- .github/workflows/cibuildwheel.yml
- lib/matplotlib/backends/backend_pgf.py
- lib/matplotlib/tests/test_colors.py
- lib/matplotlib/tests/test_rcparams.py
- lib/matplotlib/tests/test_ticker.py
- src/_macosx.m
Backports #27755 for the macOS crash, #27785 for PGF on Windows, and #26689 just to make the previous backport easier. …
> Backport crash fixes to v3.7.x

- README.md
This is a follow on to https://github.com/matplotlib/matplotlib/pull/27702. 
Given EffVer has been adopted here I wanted to see if folks had an appetite to add the EffVer badge to the README? It would really help raise awareness of the version scheme and hopefully increase adoption in other projects.
Totally understand if you don't want to, but thought I'd ask 😄.
cc @tacaswell @timhoffm @efiring
> Add EffVer badge

- doc/api/next_api_changes/behavior/27767-REC.rst
- doc/api/next_api_changes/deprecations/27767-REC.rst
- lib/matplotlib/axes/_base.py
- lib/matplotlib/tests/test_legend.py
Closes #27762.
* `plot(x, y, label=['foo'])` where _y_ is 1D now results in the legend label "foo" instead of "['foo']" (immediate change).
* `plot(x, y, label=sequence)` where _y_ is 1D and _sequence_ is not of length 1 is deprecated to error in future.
> Update handling of sequence labels for plot

- lib/matplotlib/gridspec.py
- lib/matplotlib/tests/test_gridspec.py
In https://stackoverflow.com/questions/77710768/getting-constrained-layout-to-work-with-nested-subplots-in-matplotlib
the user did 
```python
fig, axs = plt.subplots(1, 2)
gs = mpl.gridspec.GridSpecFromSubplotSpec(2, 1, subplot_spec=axs[0])
```
which isn't crazy, though `subplot_spec` should really be of type `SubplotSpec`.  Indeed it works fine if the user doesn't call `constrained_layout`.  
This PR makes the argument a bit more forgiving and will do `axs[0].get_subplotspec` for the user without complaining, and will check for any other inputs not being type `SubplotSpec`.
> MNT: arghandling subplotspec

- galleries/examples/subplots_axes_and_figures/figure_size_units.py
Remove old reference to 72 DPI
Page for reference: https://matplotlib.org/stable/gallery/subplots_axes_and_figures/figure_size_units.html
Removed the outdated note about DPI.
The default DPI for `matplotlib inline` has been 100 [for a while](https://github.com/ipython/matplotlib-inline/pull/14/files), and with the below test in Jupyter, the saved image is 1000 x 1000 pixels as expected.
```py
%matplotlib inline
fig, ax = plt.subplots(figsize=(10, 10))
ax.plot([1, 2, 3, 2, 3])
fig.savefig('testing.png')
```
Let me know if this change is a bit aggressive and maybe the text could just be updated to indicate which older versions its a problem in. Or are these guides meant to reflect the current version anyway?
- [N/A] "closes #0000" is in the body of the PR …
> Remove old reference to 72 DPI in figure_size_units.py

- doc/_static/mpl.css
This collects two commits:
---
Remove unused `.sphx-glr-thumbcontainer .figure`. The `.figure` div was removed in
https://github.com/sphinx-gallery/sphinx-gallery/pull/906
The workaround is also not needed anymore because that PR fixes the
centering.
---
Set a fixed height for sphinx gallery images
... so that lazy loading does not change heights. Without a fixed
height lazy loading of images interferes with anchor links: Clicking a
link goes to a certain position, but then the loaded images add content
and move the anchor to a different position.
The position change problem that this addresses can be reproduces as follows:
1. Go to https://matplotlib.org/devdocs/gallery/index.html
2. In the right menu "On this page" click a link (somewhat further down) e.g. "Animation"
3. The page …
> Fix sphinx-gallery CSS

- doc/_templates/empty_sidebar.html
- doc/conf.py
The [release note page](https://matplotlib.org/3.8.0/users/release_notes) is only a structured collection of links to sub-pages. The sidebar would repeat all the titles of the sub-pages and thus basically repeat all the content of the page. Even worse, it does not contain the version sectioning structure of the release notes page itself.
It's thus best to deactivate the sidebar here.
Related to https://github.com/matplotlib/matplotlib/pull/27690#issuecomment-1907277251
> Deactivate sidebar for release notes

- lib/matplotlib/axes/_axes.py
- write out defaults coming from `rcParams`
- *see also*-link between `boxplot`/`bxp` and `violinplot`/`violin`
- some rewording
> Improve documentation on boxplot and violinplot

- lib/matplotlib/axis.py
> Clarify that set_ticks() affects major/minor ticks independently

- lib/matplotlib/offsetbox.py
- lib/matplotlib/patches.py
As far as I can tell, these are unused, and cause problems for pickling
Closes #27805
See https://github.com/matplotlib/matplotlib/issues/27805#issuecomment-1955104618 for more details.
> Remove self._renderer from AnnotationBbox and ConnectionPatch

- .appveyor.yml
- .github/workflows/cygwin.yml
- .github/workflows/tests.yml
- azure-pipelines.yml
Pytest 8 brought with it an expansion of the reporting for xfails (and xpasses)
which with our current config (`-ra`) on CI renders the reports rather difficult to
read. This is because we have quite a lot of xfails, for various reasons:
- We have many that are very intentional and are testing our test fixures and explicitly pass `strict=True`
- We have things like the recent templated out tests for units behavior that introduced many xfails at once
As a result seeing the output on xfails is not particularly useful for us, especially.
As `x` is included in the `a` (all) option, we are left to expand out all of the components that we do want, which is a little messy.
Unfortuntately there is not a toggle that still gets us the one line "this test xfails" without
providing the full output, …
> Expand CI pytest reporting config to ignore xfails

- lib/matplotlib/pyplot.py
Closes https://github.com/matplotlib/matplotlib/issues/27659.
By changing the return type annotation to `AbstractContextManager`, Pyright considers the context managers returned by `ion` and `ioff` as not supressing errors and does not give warnings about possibly unbound variables after the `with` block.
This change has absolutely no effect on runtime behavior.
It might cause type errors for users who store the return value of `ion` or `ioff` and attempt to call `ExitStack`-specific methods on it. However, the runtime behavior of such usage has not changed and the number of users who actually do this should be very small, given that the documentation explicitly forbids "storing or accessing" the returned context manager.
- [N/A] new and changed code is …
> Change return type of `ion` and `ioff` to fix unbound variable errors with Pyright

- lib/matplotlib/patches.py
Fix check on annulus width to reflect the error message printed. The logic is presented in this (slightly) convoluted form to better conform with the error message. Obviously, the more concise `if min(self.a, self.b) < width:` works just as well.
This fix will allow annuli to be equivalent to Circles (in terms of area plotted, not underlying object structure). This means plotting (`_recompute_path`, I believe) could be improved by checking for `if w==a or w==b: PLOT WITHOUT HOLE`. Not sure how that would work, but everything does seem to work even without that change.
> Fix Annulus width check

- lib/matplotlib/axis.py
- lib/matplotlib/colors.py
Otherwise this is imporperly parsed and interpreted as the output that should have been produced by the preceding line.
> DOC: use ... for continuation prompt in docstrings

- environment.yml
- requirements/testing/all.txt
Pytest 8.1.0 just released and broke most of our CI.
> pin pytest

- doc/api/next_api_changes/deprecations/27850-REC.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_datetime.py
- lib/mpl_toolkits/axes_grid1/tests/test_axes_grid1.py
Closes #8072.  Deprecating `plot_date` seems to be the consensus at the end of that issue.
> Deprecate `plot_date`

- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_pgf.py
Calling `FigureCanvasPdf(figure)` will call `figure.set_canvas(self)`, meaning the `cbook._setattr_cm` context manager that wraps this change will see the _new_ canvas, and the old canvas isn't restored.
Instead, just pass the `backend` parameter, as `savefig` already knows how to correctly save and restore the canvas if it needs to change backends.
Fixes #27865
> Correctly set temporary pdf/pgf backends

- .circleci/config.yml
- doc/_static/mpl.css
- doc/conf.py
- environment.yml
- requirements/doc/doc-requirements.txt
The goal of this PR is to bump `pydata-shpinx-theme`, so we can take advantage of improvements/bug fixes that have happened since version 0.13.
Things that are ~currently broken~ now fixed:
Fixes https://github.com/matplotlib/matplotlib/issues/27652
Fixes https://github.com/matplotlib/mpl-sphinx-theme/issues/80
> Bump pydata-sphinx-theme

- lib/matplotlib/tests/test_units.py
This fixes some test failures in https://github.com/matplotlib/matplotlib/issues/27844 that we're responsible for. I'm guessing the new requirement on copy/dtype args is from numpy 2.0. I'm not sure if there's a way to run the weekly CI on a PR to check this fixes the issue?
> Add dtype/copy args to internal testing class

- src/_image_wrapper.cpp
- src/_tkagg.cpp
This can eventually be replaced by `std::format` when we require C++20. …
> Use pybind11 string formatter for exception messages

- lib/matplotlib/collections.py
Follow up to https://github.com/matplotlib/matplotlib/pull/27871 addressing the missing `**kwargs` in the Collection docstring
- [NA] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [NA] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [NA] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [NA] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [x?] Documentation complies with …
> doc: add description of **kwargs usage to collections

- src/_path_wrapper.cpp
- src/meson.build
- src/py_converters_11.h
Another part of #23846, but waiting for some other refactoring PRs to be ready. …
> Convert path extension to pybind11

- lib/matplotlib/cm.py
Follow up to #27848.  This `if` was supposed to prevent the RGB from being copied twice but I got my `x` and `xx` mixed up :woman_facepalming:
> FIX: don't copy twice on RGB input

- doc/api/prev_api_changes/api_changes_3.7.0/behaviour.rst
As reported on [Discourse](https://discourse.matplotlib.org/t/typo-in-release-notes-api-changes-for-3-7-0/24308).  This release note entry from #24912 got splintered somehow.
> DOC: fix stray release note entry

- subprojects/freetype-2.6.1.wrap
FreeType is available from both Savannah and SourceForge, and sometimes AppVeyor seems to have trouble downloading from Savannah, so perhaps this fallback will help. We used to try both these URLs in the pre-Meson build system. …
> BLD: Add a fallback URL for FreeType

- doc/devel/document.rst
Since the doc build takes very long, an order-of-magnitude estimate is helpful to manage expectations.
I'm not wedded to the actual numbers, if somebody has better suggestions. A quick test on an old i7 6700 (from 2015) yielded
- `O=-j1`: 23min
- `O=-j4`: 15min
Doc build on CI is around 18min.
> DOC: State approximate documentation build time

- lib/matplotlib/colors.py
- lib/matplotlib/tests/test_colors.py
This change suggests a fix and hopefully closes #27839 by making sure that 'none' colors in a list won't be affected by custom alpha param.
Before the fix, this code:
```
509 if alpha is not None:
510     rgba[:, 3] = alpha
```
will change rgba array of color list ['blue', 'none'] from:
```
[[0. 0. 1. 1.]       # this is blue
[0. 0. 0. 0.]]      # this has no color
```
to
```
[[0. 0. 1. 1.]       # this is still blue
[0. 0. 0. 1.]]      # this becomes black:
```
After the fix, any 'none' color in a list of colors will be kept colorless.
A test is added to make sure the function works as expected.
> Make sure custom alpha param does not change 'none' colors in a list of colors

- doc/sphinxext/custom_roles.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/axes/_secondary_axes.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/collections.py
- lib/matplotlib/colorbar.py
- lib/matplotlib/colors.py
- lib/matplotlib/contour.py
- lib/matplotlib/figure.py
- lib/matplotlib/lines.py
- lib/matplotlib/patches.py
- lib/matplotlib/patheffects.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/quiver.py
- lib/matplotlib/spines.py
- lib/matplotlib/stackplot.py
- lib/matplotlib/streamplot.py
- lib/matplotlib/table.py
- lib/matplotlib/text.py
- lib/matplotlib/tri/_tricontour.py
- lib/matplotlib/widgets.py
- lib/mpl_toolkits/axisartist/axisline_style.py
- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/mplot3d/axis3d.py
> Use :mpltype:`color` for color types

- doc/conf.py
- doc/devel/release_guide.rst
My reasoning here is:
- There is now a version switcher in the top right, as part of the pyadata-sphinx-theme.
- The only other thing the versions in the sidebar adds is a note about the last supported version for Python 2, but Python 2 is long end of life, so I think fine to remove this.
- Removing the versions from the sidebar removes a location where the version has to be manually updated every time a new release is done (e.g., https://github.com/matplotlib/matplotlib/issues/27863).
> Remove versions from sidebar in docs

- lib/matplotlib/patheffects.py
- lib/matplotlib/tests/test_patheffects.py
This code change is to ensure that methods like `open_group` and `close_group` are overridden in `PathEffectRenderer`.
This pull request addresses and hopefully closes #27843.
> Override open_group, close_group methods in PathEffectRenderer

- lib/matplotlib/colors.py
Implements the suggestion https://github.com/matplotlib/matplotlib/issues/27378#issuecomment-1830271599.
Closes #27378.
> Improved error message for malformed colors

- doc/conf.py
With sphinx-doc/sphinx#10614 and the to-be-merged sphinx-doc/sphinx#11634, links now work in SVG inheritance diagrams, including intersphinx links to external packages.  This PR reverts PR #17913, which had switched the documentation to PNG inheritance diagrams. …
> Use SVG inheritance diagrams now that linking has been fixed

- doc/conf.py
- doc/users/index.rst
- galleries/users_explain/index.rst
Fixes https://github.com/matplotlib/matplotlib/issues/27896.
> Remove empty user guide tutorials page

- src/_path_wrapper.cpp
Apparently, macOS incorrectly hides this `std::optional.value` method behind the deployment target, even though it's a header-only implementation, so it shouldn't have any runtime requirement.
Instead of fiddling with deployment targets, use an alternate method for getting the `std::optional` value.
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-de …
> Fix build on older macOS deployment targets

- lib/matplotlib/_fontconfig_pattern.py
- lib/matplotlib/_mathtext.py
Closes #25204
This feels a bit more "workaround" than I'd _really_ like, but it seems to work.
- Pyparsing warns when you try to name a forward reference before it is defined
- As far as I can tell, it actually _does_ work currently, but discussion on pyparsing/pyparsing#95
leads me to believe that we are relying on something that could change
- When names are given, a _copy_ is produced, and thus in theory the forward references won't get their definitions
- In practice, they appear to
- There is a warning which is disabled by default for this behavior.
- Enabled with `python -Wdefault`, but not enabled in our test suite
- The solution I came up with was to wrap it in another layer of forward reference
- This feels like a hack, but the reference the outer forward holds gets filled out …
> Work around pyparsing diagnostic warnings

- src/_macosx.m
Modify `PyTypeObject` definitions to match the 3.9 C-embedding tutorial. Use `PyDoc_STR` for possible optimization purposes. Re-order fields in a bit clearer manner (object information, new+init, dealloc, repr, methods). And finally, use the new `PyModule_AddType`, which does what our `prepare_and_add_type` inline function does. …
> Modernize macosx backend a bit

- doc/api/next_api_changes/behavior/27492-AL.rst
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backend_tools.py
See writeup in changelog note.  Closes #27400.
@tacaswell I think the behavior here also handles the use case you mention at https://github.com/matplotlib/matplotlib/issues/27400#issuecomment-1843773133.
> Fix semantics of MEP22 image names.

- lib/matplotlib/axes/_axes.py
The `error_kw` parameter is a dictionary, on which `setdefault` is called, which would modify user input.
I know we always try to avoid modifying user input, but I couldn't find any tests for it, so I didn't add any. …
> Avoid modifying user input to Axes.bar

- lib/matplotlib/backends/backend_macosx.py
- src/_macosx.m
The `NSTimer` docs state that a non-repeating (aka single-shot in our terms) timer is invalidated after if fires. This means that we should not do it ourselves, and in fact it appears that the pointer itself is no longer valid, so we would be passing an `invalidate` message to a random object or segfault.
~~I believe this is why `test_other_signal_before_sigint` is marked as flaky as well, as it uses a single-shot timer and a segfault is recorded in the XPASS log.~~
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-t …
> macosx: Clean up single-shot timers correctly

- galleries/examples/shapes_and_collections/line_collection.py
Superseeds #27871.
This example is much simpler, but conveys the same LineCollection aspects - except for not using masked arrays. But I argue that this the example should be simple and using masked arrays rather distracts from the core aspects of LineCollection.
If there's concern of not showing masked array support, we should add a third plot for that.
> Simplify the LineCollection example

- lib/matplotlib/backend_tools.py
Fixes a reST syntax error that slipped in through #27492.
> DOC: Fix syntax for ToolBase.image docstring

- lib/matplotlib/pyplot.py
This changes the documentation of the matshow function, making it clearer as to which dimension corresponds to which number in the array passed to the function. The convention used is standard practice, where the first number(rows) corresponds to the length of the vertical column and the second number(columns) corresponds to the length of the horizontal column.
Closes https://github.com/matplotlib/matplotlib/issues/27852 …
> Documentation edit for matshow function

- .github/workflows/do_not_merge.yml
Kinda been bugging @QuLogic about this for a while... 
This PR + some one w. org access adding a [branch protection rule](https://www.jessesquires.com/blog/2021/08/24/useful-label-based-github-actions-workflows/)  that blocks merges when this status check fails would allow us to grey out merging using a specific set of labels.
As you can see in the workflow, the status check fails b/c this is labeled "status: needs comment/discussion" (and I tried to turn off most of the CI checks so folks can play with adding and removing the label)
The motivation is b/c 'request changes' for reviews can be used in two ways:
1. needs change but will be merged after change is implemented
2. needs meta discussion, may not be merged 
And I think using it for 2. has made folks wary of using it for 1, and …
> MNT: prevent merging using labels + branch protection rules

- lib/matplotlib/backends/backend_cairo.py
Closes #363.  Try e.g. `plt.fill([0, 1, 0], hatch="/")`.
Direct transposition of the mplcairo implementation (except for the lack of proper stacking noted in the comments, which was already present for the alpha state so it's not really "worse"), itself translated from the agg implementation.
No tests, but adding tests for the cairo backend would be another adventure.
> Support hatching in cairo backends.

- galleries/examples/statistics/bxp.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/cbook.py
- lib/matplotlib/cbook.pyi
- lib/matplotlib/tests/test_cbook.py
This is up for debate: I'm only +0.2 here.
The renaming was done in #27901, which renamed the parameter `labels` to `tick_labels` for `boxplot()` and `bxp()`.
One can take two views here:
- If `boxplot_stats()` is specifically for the input of `bxp()`, one can justify the renaming as being consistent with the `bxp()` signature. Note however, that the returned dict still contains the key "label" for back-compatibility (There's no easy migration path for that). So, this brings us an inconsistency between the parameter name and the returned dict key.
- One can alternatively view `boxplot_stats()` as a generic function to define box parameters. Here, we'd only have a general `label` for the boy and no information that this should be used as tick label.
If we could make a clean transition and …
> Revert renaming labels to tick_labels in boxplot_stats()

- lib/matplotlib/tests/test_pickle.py
- lib/mpl_toolkits/axes_grid1/axes_size.py
... by not storing a lambda in the _AxesDecorationsSize instance, just a name (the dict lookup cost should be negligible compare to the rest).
> Fix pickling of make_axes_area_auto_adjustable'd axes.

- lib/matplotlib/patches.py
- lib/matplotlib/text.py
closes #27941 
Updates documentation in two places to make it more clear that `FancyArrowPatch` uses point units for the `shrinkA` & `shrinkB` parameters.
This was particularly unclear when accessing `FancyArrowPatch` via `Axes.annotate()` because there is an alternate "simple" way to specify an arrow that uses `shink` as a fraction rather than as points.
Therefore I have also proposed changes to the `Annotation` class in the text module.
Also please summarize the changes in the title, for example "Raise ValueError on
non-numeric input to set_xlim" and avoid non-descriptive titles such as "Addresses
issue #8576".
- [N/A] *Plotting related* features are demonstrated in an …
> Update docs for `FancyArrowPatch` & `Annotation` to make it clear that ShinkA/B parameters are in points and not fractional.

- galleries/plot_types/arrays/barbs.py
- galleries/plot_types/arrays/contour.py
- galleries/plot_types/arrays/contourf.py
- galleries/plot_types/arrays/imshow.py
- galleries/plot_types/arrays/pcolormesh.py
- galleries/plot_types/arrays/quiver.py
- galleries/plot_types/arrays/streamplot.py
- galleries/plot_types/basic/fill_between.py
- galleries/plot_types/basic/plot.py
- galleries/plot_types/basic/scatter_plot.py
- galleries/plot_types/basic/stackplot.py
- galleries/plot_types/basic/stairs.py
- galleries/plot_types/basic/stem.py
- galleries/plot_types/stats/boxplot_plot.py
- galleries/plot_types/stats/ecdf.py
- galleries/plot_types/stats/errorbar_plot.py
- galleries/plot_types/stats/eventplot.py
- galleries/plot_types/stats/hexbin.py
- galleries/plot_types/stats/hist2d.py
- galleries/plot_types/stats/hist_plot.py
- galleries/plot_types/stats/pie.py
- galleries/plot_types/stats/violin.py
- galleries/plot_types/unstructured/tricontour.py
- galleries/plot_types/unstructured/tricontourf.py
- galleries/plot_types/unstructured/tripcolor.py
- galleries/plot_types/unstructured/triplot.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/quiver.py
- lib/matplotlib/stackplot.py
IMHO it's meaningful to give a one-sentence summary on the individual pages, e.g. at
https://matplotlib.org/stable/plot_types/basic/plot.html#sphx-glr-plot-types-basic-plot-py
> Plot y versus x as lines and/or markers.
>
> See `plot`.
is more helpful than just
> See `plot`.
Users can already decide if that's the correct function for them and whether it's worth following the link. Also, the first sentence is used in the tooltip on the index page, where the current "See ..." is not helpful.
I believe it's ok to just copy the text. Automatic insertion or check for consistency are not worth the added complexity. First, these summary lines change rarely. Second, even if we improve the method summary and forget to udpate here, nothing really bad happens; we've maybe a slightly less optimal …
> DOC: Add summary lines to plot types

- galleries/users_explain/figure/api_interfaces.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/pyplot.py
Partial fix for #17786: This adds notes for the pyplot functions auto-generated by boilerplate.py.
As a prerequisite, this includes a first commit fixing the `__qualname__` of Axes methods that are defined as functions in other modules and only added as attributes to Axes.
> Add a note to pyplot docstrings referencing the corresponding object methods

- .github/workflows/cibuildwheel.yml
The wheel workflow is only triggered on pushes and pull requests. So the condition to publish must be based on that, not on generating a GitHub release.
- [n/a] Documentation …
> ci: Fix condition for publishing wheels

- doc/api/next_api_changes/behavior/27943-AL.rst
- lib/matplotlib/axes/_base.py
- lib/matplotlib/tests/test_axes.py
> Support Cn, n>9 in plot() shorthand format.

- doc/users/next_whats_new/boxplot_legend_support.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_axes.pyi
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_legend.py
Closes #27792. Boxplots now get legend entries.
This was previously attempted on  #27711 and then reverted #27780 because it used the same parameter for tick labels and didn't generalize well. These 2 issues have been addressed in this PR.
A new `label` parameter has been added to `Axes.boxplot` and `Axes.bxp`. If called via `ax.boxplot()`, label is passed to the bxp function, otherwise bxp can be directly called with the label parameter.
The label is passed to the `boxes` object if `showbox=True`, otherwise it will be passed to the `medians` object is `showbox=False`. Attaching the label to the boxes makes sure that the legend handles will get a patch which will be displayed on the legend.
If the box is turned off, the legend handles will get a Line2D object from the median line which …
> Add legend support for boxplots

- lib/matplotlib/axes/_base.py
There's a bit of code in the parsing of plot() format shorthands to disambiguate the "1" marker and the "1.0" grayscale color string.  It's actually easier to just explicitly check for the bad strings.
This also makes it clearer that we *could* have supported "0" as unambiguous color string (white) as there's no "0" marker (there's a 0 (int) marker, which is not the same...), but let's not bother with changing any semantics.
Noted while looking at #27827 and #27828.
> Simplify color/marker disambiguation logic in _process_plot_format.

- src/_macosx.m
While looking at #27953, we compared 3.7 with 3.8, and noticed the former used `PyOS_setsig` while 3.8+ uses `sigaction`.
The docs for this function say it wraps `sigaction` or `signal`, and not to use those functions directly.
I believe @ksunden did test this out while trying to see if it would fix anything, and didn't see any change. …
> Use PyOS_setsig in macos backend

- doc/users/next_whats_new/interpolation_stage_rc.rst
- lib/matplotlib/image.py
- lib/matplotlib/mpl-data/matplotlibrc
- lib/matplotlib/rcsetup.py
- lib/matplotlib/tests/test_image.py
As discussed in #18782, where the rcparam was introduced, I would probably always set this to "rgba"...
One question is whether we want to switch back "classic" mode to also use "rgba", which does correspond to pre-2.0 behavior.
> Add an rcparam for image.interpolation_stage.

- galleries/examples/statistics/bxp.py
Previously, the example essentially replicated illustrations of a lot of styling variants, which have already been shown for `boxplot()`. Compare:
- https://matplotlib.org/3.8.3/gallery/statistics/bxp.html
- https://matplotlib.org/3.8.3/gallery/statistics/boxplot.html
I believe it's not necessary to iterate through all that again. Instead, this rewrite focuses on the relation between `boxplot_stats()`, `bxp()` and `boxplot`. And it shows how to use `bxp()` in isolation.
> DOC: Rewrite the example illustrating bxp()

- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/backends/backend_wxagg.py
This PR adds support to the `wxAgg` backend to corrertly render plots in high DPI displays in all three platforms that the wx toolkit supports: Linux, MACOS and Windows.
This PR closes issue #7720
This PR adds support for high DPI displays using the underlying toolkit support for high DPI displays: For information of wxPython support for High DPI displays, see https://docs.wxpython.org/high_dpi_overview.html
The wxPython toolkit is built on top of of the C++ wxWidgets toolkit. For a more detailed explanation of support for high DPI displays in the wx ecosystem see the WxWidgets explanation: https://docs.wxwidgets.org/3.2/overview_high_dpi.html
This PR correctly scales plots in high DPI displays, including figure size, font size and marker and line width. This PR also includes reading …
> Add support for High DPI displays to wxAgg backend

- lib/matplotlib/tests/test_backend_pdf.py
- lib/matplotlib/tests/test_backend_pgf.py
These tests don't chdir back to the original directory on exit, so anything using the current directory would be in the temporary directory of this test.
Most notably, any image comparison results would be dumped in that temporary directory instead of the usual `result_images` in the current directory.
I noticed this while debugging #27723, as the failing test images were not in the artifacts, and logs showed them saved in a temporary directory: https://github.com/matplotlib/matplotlib/actions/runs/8458560380/job/23173084420#step:13:183 …
> TST: Remove superfluous chdir from tests

- lib/matplotlib/backends/backend_gtk3agg.py
- lib/matplotlib/backends/backend_gtk3cairo.py
- lib/matplotlib/backends/backend_gtk4agg.py
- lib/matplotlib/backends/backend_gtk4cairo.py
Originally, the resize event happens first, adds an idle draw callback, and then the widget draws itself. Since the draw callback only happens when _idle_, it happens after the widget's draw, so the figure appears blank. After the mouse is released, the idle draw callback fires, and the figure appears again.
This is already done in the Qt backend [1], and doing so ensures the figure remains visible during resizes with the mouse.
This fixes the bug reported at https://github.com/matplotlib/matplotlib/pull/25861#issuecomment-1545750896
[1] https://github.com/matplotlib/matplotlib/blob/0afc5d6ca49cf6e8aa1da76b5bab0faca2f340f2/lib/matplotlib/backends/backend_qtagg.py#L25 …
> gtk: Ensure pending draws are done before GTK draw

- lib/matplotlib/colors.py
This PR fixes the color sequence data for the `Set2` and `Set3` qualitative colormaps in the `matplotlib.color_sequences` object. They were errorneously assigned to the `Set1` sequence data.
> Fix color sequence data for Set2 and Set3

- src/ft2font_wrapper.cpp
Minor typos introduced in #27702.
> Fix deprecation warnings in ft2font extension

- galleries/examples/subplots_axes_and_figures/secondary_axis.py
- galleries/examples/ticks/ticklabels_rotation.py
In particular, the ticklabels_rotation example is likely the one most easily found by those looking for how to do this; let's not suggest that plt.xticks is "the" way to rotate ticklabels.
Also remove the margins() call (which was really only needed with the old round_numbers autolimits mode) and the subplots_adjust() call (the ticklabels already fit in, and the modern approach would be to use constrained_layout anyways).
> Avoid plt.xticks/plt.yticks in gallery examples.

- lib/matplotlib/backends/backend_macosx.py
Without this a stale figure is shown
This is basically the same concept as what happens just before show in [`plt.pause`](https://github.com/matplotlib/matplotlib/blob/1174aadafd9ae55818436bd3033b36626dcd3b0d/lib/matplotlib/pyplot.py#L731).
Essentially, there is nothing in the macos backend that actually causes a stale figure to be redrawn on `show`.
Other backends (qt, tk in particular, but likely others) seem to be saved by the fact that a resize event is triggered upon show, but macos does not do the same.
Other ideas considered, would be to do this in `plt.show` (which would perhaps leave out some other mechanisms, such as mpl-gui) or to try and do this in backend_bases (which is hard because most do not call `super`).
Could also leave out the condition and just always call …
> Add a draw during show for macos backend

- lib/matplotlib/axes/_base.py
- lib/matplotlib/cbook.py
- lib/matplotlib/tests/test_backend_bases.py
Closes #4284, closes #5506 (also: https://github.com/matplotlib/matplotlib/pull/2986#issuecomment-42146048).
> Display cursor coordinates for all axes twinned with the current one.

- lib/matplotlib/backends/backend_wx.py
Fixes AppVeyor failure noted in
https://github.com/matplotlib/matplotlib/pull/26710#issuecomment-2031349546
This was also broken on non-Windows; it just didn't crash, but instead produced empty buttons.
> wx: Fix file extension for toolmanager-style toolbar

- doc/users/next_whats_new/pie_percent_latex.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Fixes Issue #26377 - Adding Support For % operator in Latex. Continued From #26642
'%' operator is considered as the start of a comment in LaTeX. In order to avoid this behavior, `\%` needs to be used.
Uses Regex to substitute `\%` instead of `%`. It also resolves in case the string is already pre-escaped.
> Fixes Issue #26377 - Auto-escape % Symbol in Latex in pie labels

- doc/devel/testing.rst
Tests and references images are stored in subdirectories for each toolkit.
> DOC: correct path to mpl_toolkits reference images

- doc/devel/contribute.rst
- doc/devel/index.rst
Partially adresses #28005.
The two sections "Report a bug" and "Request a feature" were burried inside of contribute.rst. They were a bit foreign there because all other content is on direct involvement with the project, which needs much more information.
To keep things focussed and directly redirect the "simple" bug report and feature request topics to GitHub, I've deleted the sections and instead created two cards at the top of devel/index.rst with essentially the content of the sections. Note that I've removed the list of things to include in bug reports because that's covered by our issue template on GitHub nowadays and does not need repetition here.
> DOC: Move bug reports and feature requests to top of contributing index

- doc/devel/contribute.rst
- doc/devel/index.rst
- doc/project/citing.rst
Attempt to address hierarchy issues from #28005 by reordering so that:
on contributing page:
- moved the "why should I contribute" into a default open dropdown so that it can both stand out for the folks who need it and can be collapsed for folks who don't. 
- code/docs/community contributions get moved under get-started as sub headings
- issue related blocks get shifted into their own section
- removed double nesting on 'codespaces workflow section'
- slight reordering of contributing section 
And on the index page:
- removed 'good-first-issues' from index page b/c it's always felt kinda weird anyway and it's a special case of claiming issues
- changes buttons as discussed in https://github.com/matplotlib/matplotlib/pull/28011#discussion_r1550271166
- broke up preamble so "everything is …
> [DOC] reshuffle of contributing

- .github/workflows/conflictcheck.yml
This should fix the warning about deprecated nodejs.
Also, changing from the branch name to a tagged commit should be more stable, and I think will fix dependabot to start auto-updating this one.
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-an …
> ci: Update merge conflict labeler

- lib/matplotlib/axes/_axes.py
Some of the docstrings in [ `_axes.py`](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/axes/_axes.py) had the wrong amount of spacing (either 2 or 3 spaces) instead of 4. This PR makes them conform with the rest.
> DOC: Fix inconsistant spacing in some docstrings in _axes.py

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Closes #26752
I think the best we can do here is warn the user they are about to do something silly.  Raising on this combination seems too harsh.
> API: warn if stairs used in way that is likely not desired

- .circleci/config.yml
- azure-pipelines.yml
- meson.build
This should ensure we get the right version when tagging, etc., without having to do manual changes.
We had incorrect sdist/wheel names when building rc1 due to this: https://github.com/matplotlib/matplotlib/actions/runs/8566515999/job/23476414949#step:6:89
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pag …
> BLD: Fetch version from setuptools_scm at build time

- .github/workflows/tests.yml
Supersedes PR #27881 (I'm so sorry for creating unnecessary traffic on this repo.)
Attempts to close #23400 and potentially complete what PR #19466 intended to do
Included a bash script right before the uploading part of the code in the *tests.yml* file to delete all files(.png, .svg, .eps, .pdf) that have not failed in the *result_images* directory. Have tested this using a dummy bash file and the downloaded result_images folder. Please let me know if this approach seems correct, or is blatantly wrong :). …
> Deleting all images that have passed tests before upload

- lib/matplotlib/tests/test_ticker.py
- lib/matplotlib/ticker.py
The trailing spaces were fine when the cursor position was shown as
`x=...    y=...`, but become very ugly now that it's
`(x, y) = (...,    ...)`.  (#25556)
(test e.g. with moving the cursor on a loglog() axes and looking at the coordinates display)
> Strip trailing spaces from log-formatter cursor output.

- lib/matplotlib/backends/_backend_tk.py
... because the toolbar may be a fake object (when using rcParams["toolbar"] = "toolmanager").
Try with `rcParams["toolbar"] = "toolmanager; use("tkagg")` and interactively saving the picture.  No automated tests, sorry.
Closes #28069 (I chose not to parent to None as suggested in the original issue because I'm not 100% sure this won't lead to variables being progressively leaked into tk's global namespace.)
Looks like a regression in 3.8 (#24531), so let's try to get this in 3.9.
> Parent tk StringVar to the canvas widget, not to the toolbar.

- lib/matplotlib/font_manager.py
Especially the previous wording for _find_fonts_by_props ("find font families") was somewhat confusing, as "font families" are strings.
> Clarify that findfont & _find_fonts_by_props return paths.

- galleries/users_explain/text/pgf.py
This should clarify the misunderstanding at https://github.com/matplotlib/matplotlib/issues/28084 (where this block of docs is explicitly quoted).
Also, as a side point, this would be a decent use of a "qtpdf" ("qtpgfpdf"?) backend as suggested in https://github.com/matplotlib/matplotlib/pull/27913#issuecomment-2020304807, where we export as pdf and rely on qt's QPdfView to render the figure.  I guess in the meantime we could even just use pgf's png export (pdf->png via pdftocairo or ghostscript) and use *that* to create an interactive backend...
> Clarify that the pgf backend is never actually used interactively.

- lib/matplotlib/image.py
- lib/matplotlib/tests/test_image.py
> FIX: ensure images are C order before passing to pillow

- galleries/users_explain/quick_start.py
I found this typo  while browsing the "Quick start guide." Instead of "a colors," it should read "colors," as far as I can tell. 
- [N/A ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [N/A ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [] Documentation complies with …
> Fix typo in color mapping documentation in quick_start.py

- galleries/examples/lines_bars_and_markers/capstyle.py
The current [CapStyle example](https://matplotlib.org/devdocs/gallery/lines_bars_and_markers/capstyle.html) partially uses text from the [JoinStyle example](https://matplotlib.org/devdocs/gallery/lines_bars_and_markers/joinstyle.html). I've updated the text with the appropriate description.
- [N/A] *New Features* and *API Changes* are noted with a [directive and …
> [DOC] Fix description in CapStyle example

- lib/matplotlib/tests/test_getattr.py
> TST: wxcairo sometimes raises OSError on missing cairo libraries

- setupext.py
Change similar to #27505 but on the branch 3.8.x as right now the qhull website seems unable to properly deliver the tarball without disconnecting in the middle. Right now I am unable to build matplotlib from `pip install`.
I have no actual ticket for this on branch 3.8, but this is exactly the same issue as in #27159 however with the previous (ie non-meson) build system. …
> BLD: Update Qhull location in branch 3.8.x

- .flake8
- galleries/users_explain/quick_start.py
See the commit messages.
Commits are best be looked at individually.
> DOC: Minor improvements on quickstart

- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/projections/polar.py
The ":d" conversion in polar.py (which confuses pycodestyle due to the nested f-string) is unnecessary as digits is made an int immediately above.  While at it, also remove the comment above, which is just wrong as all supported mathtext fonts support `\circ` (but unicode still seems to be the better option).
> Appease pycodestyle.

- lib/matplotlib/cbook.py
- lib/matplotlib/tests/test_cbook.py
as mentioned in https://github.com/matplotlib/matplotlib/issues/22879#issuecomment-2056729839, adding support for TensorFlow tensors to be converted to numpy (equivalent to what was done for JAX and torch in https://github.com/matplotlib/matplotlib/pull/25887)
Also improved previous handling by using `np.asarray` and allow _the specific subset of arrays (JAX, torch, TF)_ to also use more efficient methods if desired (see also https://numpy.org/devdocs/user/basics.interoperability.html#using-arbitrary-objects-in-numpy).
> Convert TensorFlow to numpy for plots

- galleries/users_explain/quick_start.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_axes.pyi
I suspect the parameter was made keyword-only because the originally planned signature (#11859) was `secondary_xaxis(location, forward=..., inverse=...)` where the keywords actually add some semantics (though that signature overall seems worse); however, for a single `functions` parameter, having to type an extra `functions=` in the call doesn't help the reader much (either they know what secondary_x/yaxis does, in which case the explicit kwarg doesn't matter, or they don't, in which case the kwarg name hardly helps)... and is a bit annoying.  See the modified gallery entry, for example.
> Make `functions` param to secondary_x/yaxis not keyword-only.

- .appveyor.yml
- lib/matplotlib/tests/test_tightlayout.py
AppVeyor is quite slow, but is also the only CI to check the conda environment, so cut it down to only one Python version. But also enable a few more things to see if they work. …
> Update AppVeyor config

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
The problem was that the methods on the norm were called directly on a string instead of the object itself.
So I put this block after `collection.set_norm(norm) in order to call the norm's getter.
```
if norm is not None:
if collection.norm.vmin is None and collection.norm.vmax is None:
collection.norm.autoscale()
```
Seems to solve the issue.
> Fix: [Bug]: Setting norm by string doesn't work for hexbin #28105

- doc/devel/min_dep_policy.rst
This comes up about every other month.
inspired by https://github.com/matplotlib/matplotlib/pull/28110
SC should sign off on this @timhoffm @dopplershift @efiring
> GOV: write up policy on not updating req for CVEs in dependencies

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Instead of assuming that lower ylim=0 when baseline=None, it now takes into account the imputed values. Also, it no longer uses sticky_edges in these cases. Changed the unit test that tested baseline=None.
The error occured when calling the function stairs() with baseline=None. In these cases, the function would assume a value of 0 for the baseline.
```python
plt.stairs(x, edges=bins, baseline=None
```
The issue lies in the following lines of code:
```python
if baseline is None:
baseline = 0
```
I changed it so the baseline now takes into account the values imputed and does not utilize sticky_edges:
```python
if baseline is None:
baseline = values
if orientation == 'vertical':
self.update_datalim([(edges[0], np.min(baseline))])
else:
self.update_datalim([(np.min(baseline), edges[0])])
``` …
> Fix #28016: wrong lower ylim when baseline=None on stairs

- lib/matplotlib/artist.py
This is a follow-up from #25546, whihch removed the `_default_contains` method.
A similar change was made to several other classes, such as Axes and Figure,
however the call within Artist itself was not removed.
This has evidently not presented a problem to anybody (that we know of), since most
artists (that are used interactively at least) have their own `contains` method.
However, if one were to have an Artist without a contains instead of returning `False, {}`,
you would get an AttributeError.
Considered adding a test, but opted not to initially. (Willing to be talked into doing so)
> Remove call to non-existent method _default_contains in Artist

- doc/api/next_api_changes/behavior/28156-AL.rst
- lib/matplotlib/mpl-data/stylelib/dark_background.mplstyle
- lib/matplotlib/mpl-data/stylelib/fivethirtyeight.mplstyle
Previously, the dark_background and fivethirtyeight styles would set the savefig.facecolor and savefig.edgecolor rcParams to the same values as figure.facecolor and figure.edgecolor; i.e., if a user uses a style but tweaks the figure facecolor, this tweak is lost (overridden) when saving the figure.  A concrete example would be using the dark_background style but wanting a dark gray background instead of a black one, e.g. `mpl.style.use(["dark_background", {"figure.facecolor": ".2"}]); plot(); savefig(...)`.
In all likelihood these values were set because the styles predate the ability to set these savefig rcParams to "auto", which means "don't change the figure facecolor, just use it as is" (a feature introduced in #15111 exactly because this auto-switching of color by savefig was …
> Don't set savefig.facecolor/edgecolor in dark_background/538 styles.

- galleries/examples/specialty_plots/ishikawa_diagram.py
- Simplify the code in the `cause` and `draw_body` functions.
- Remove the `draw_spine` code from `draw_body` and turn into its own function.
- Fixed issue where the spine was being rendered multiple times due to being inside a loop.
- Improve docstrings and comments.
- Other minor changes.
> DOC: Refactor code in the fishbone diagram example

- lib/matplotlib/backend_bases.py
add_toolitem is clearly intended as a helper for add_tool (add_tool sets up a bunch of auxiliary arguments for it which the end-user should not bother with).  toggle_toolitem and remove_toolitem also look internal-ish.  Document them as such.
Noted while looking at #28166.
> Clarify public-ness of some ToolContainerBase APIs.

- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/_backend_tk.py
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_gtk4.py
- lib/matplotlib/backends/backend_qt.py
- lib/matplotlib/backends/backend_wx.py
ToolManager.remove_tool calls ToolContainerBase.remove_toolitem (via a tool_removed_event) and cannot know (due to the lack of API) whether the tool is actually on the container (it can also be a keybind-only tool not associated with any entry on the toolbar), so ToolContainerBase.remove_toolitem should work (as a no-op) even for tools not present on the container (and not even set a message in that case, IMO).
Closes #28166 (see example there).  Again I'd say this is a symptom of the MEP22 design (toolmanager not knowing whether a tool is actually in the toolcontainer makes things awkward), but let's just go for the minimal fix.
> Support removing absent tools from ToolContainerBase.

- .circleci/config.yml
- doc/conf.py
- doc/sphinxext/gallery_order.py
- doc/sphinxext/util.py
- lib/matplotlib/tests/test_doc.py
- requirements/doc/doc-requirements.txt
I was following a thread on the same issue in sphinx-gallery [](https://github.com/sphinx-gallery/sphinx-gallery/issues/1286). It seems every callables and classes need to be stringified. There is some work being done on sphinx-gallery side at [1289](https://github.com/sphinx-gallery/sphinx-gallery/pull/1289). But even with this PR the build fails, My assumption is that its because of the callable in  `subsection_order` key which is not being handled on sphinx_gallery side. I was able to get the error for `subsection_order` fixed but had to modify some code within sphinx_gallery. I will ask for the `subsection_order` fix in that [sphinx_gallery PR](https://github.com/sphinx-gallery/sphinx-gallery/pull/1289). but other than that i was able to build the doc without the *not pickleable* …
> [DOC]: Fix compatibility with sphinx-gallery 0.16

- doc/devel/pr_guide.rst
Inspired by questions on some edge cases in the past (e.g. https://github.com/matplotlib/matplotlib/pull/28043#pullrequestreview-1985710930).
One of the approvers should be @tacaswell .
> DOC: Clarify merge policy

- lib/matplotlib/tests/test_backend_bases.py
- lib/matplotlib/tests/test_backend_gtk3.py
- lib/matplotlib/tests/test_backend_qt.py
The current version of pytest is warning that using `importorskip` to catch `ImportError` will start being ignored (and thus raising) with pytest 9.
Fortunately, in all cases, we don't need these calls, as they are:
- already checked for `ImportError` at the top-level of the file
- already checked by the backend switcher
- not actually possible to fail importing …
> TST: Prepare for pytest 9

- .circleci/config.yml
We don't need to use in-development versions here, just as in the `v3.8.x` branch.
(Side note, this shouldn't be merged back to `main`, so one should be a bit careful doing that merge back up.)
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and- …
> DOC: Use released mpl-sphinx-theme on v3.9.x

- .github/workflows/cygwin.yml
- .github/workflows/tests.yml
- azure-pipelines.yml
The conflict was just that the remove-not-failed-images was not backported.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-r …
> Backport PR #28164 on branch v3.9.x (CI: Ensure code coverage is always uploaded)

- lib/matplotlib/image.py
The previous comment (initially from 12c27f3) slowly got out of sync with the implementation (e.g. "Agg updates out_alpha in place" doesn't make sense in the local context anymore); rewrite it.  attn @tacaswell who wrote that originally (even though I have also mangled that comment in the past).
> Clarify the role of out_mask and out_alpha in _make_image.

- lib/matplotlib/testing/__init__.py
- lib/matplotlib/tests/test_backend_inline.py
- lib/matplotlib/tests/test_backend_macosx.py
- lib/matplotlib/tests/test_backend_qt.py
Make the changes suggested by @ianthomas23 in #28205, and also mark the ipython tests as using their backend. While the backend is already checked for availability at the top of the respective files, that only checks whether it can be imported, not whether it can be set as the Matplotlib backend. Adding the marker causes our pytest configuration to actually check and skip the test if unavailable (e.g., on Linux without `(WAYLAND_)DISPLAY` set fails to set an interactive backend).
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write- …
> TST: Followup corrections to #28205

- lib/matplotlib/texmanager.py
Print all unusable font names together after a usable font has been found, rather than one at a time.  This makes the log easier to read.  Noticed while preparing the debugging instructions at https://github.com/matplotlib/matplotlib/issues/28212#issuecomment-2107655992.
> Better group logging of font handling by texmanager.

- doc/api/next_api_changes/deprecations/27998-TS.rst
- doc/users/next_whats_new/violinplot_orientation.rst
- galleries/examples/statistics/violinplot.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_axes.pyi
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_axes.py
Partially closes #13435. Replace the `vert: bool` parameter with `orientation : {'vertical', 'horizontal'}`.
Also changed the Violin plot basics gallery example to reflect the changes.
The other half of issue #13435 is to do the same to boxplots
> Add a new `orientation` parameter to Violinplot and deprecate `vert`

- doc/devel/release_guide.rst
Fixed a typo in documentation: Maplotlib --> Matplotlib in realease_guide.rst
> DOC: Fix typo in release_guide.rst

- galleries/examples/event_handling/path_editor.py
on_draw is triggered via the draw_event callback which is processed after the rest of the rendering in finished, but before the buffer is painted to the screen so the `blit` call was at best redundent (causing two copies of the buffer from our side to the GUI side) and at worst causes segfaults in some versions of Qt.
Closes #28002
> DOC: we do not need the blit call in on_draw

- galleries/plot_types/3D/bar3d_simple.py
- galleries/plot_types/3D/plot3d_simple.py
- galleries/plot_types/3D/quiver3d_simple.py
- galleries/plot_types/3D/stem3d.py
We were missing a good number of 3D plot types on this page: https://matplotlib.org/stable/plot_types/
I added examples for `plot`, `quiver`, `bar3d`, and `stem`.
> DOC: Add more 3D plot types

- doc/devel/release_guide.rst
We no longer need to manually upload sdists or wheels, but keep the section in case something breaks.
> DOC: Update release guide to match current automations

- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_pyplot.py
Closes #27978. This hopefully adds the relevant warning discussed in the issue
> Add warning for multiple pyplot.figure calls with same ID

- .circleci/config.yml
- azure-pipelines.yml
- requirements/dev/build-requirements.txt
- requirements/dev/dev-requirements.txt
Adding explicit docs to make sure the project installs in editable mode
Ref : https://matrix.to/#/!BXmyZMTnRjWJldDRLV:gitter.im/$iAbowa1uqTBT5Kvdqhvn_0hj9w1g0s0E7BOduGgv57g?via=gitter.im&via=matrix.org&via=cadair.com
- [ x] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines
> [MNT]: create build-requirements.txt and update dev-requirements.txt 

- doc/api/prev_api_changes/api_changes_3.5.0/development.rst
- doc/install/environment_variables_faq.rst
- doc/install/index.rst
- pyproject.toml
- src/checkdep_freetype2.c
Meson creates `_version.py` in the build directory, so we shouldn't ask setuptools-scm to do it. I'm not sure why it started creating it again, but taking this option out should stop it.
Also, there's some documentation about `mplsetup.cfg` that is out of date, and should be replaced by Meson build options.
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-ch …
> Clean up some Meson-related leftovers

- lib/matplotlib/backends/_backend_tk.py
- src/_c_internal_utils.cpp
GetForegroundWindow() is documented as sometimes returning NULL (https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getforegroundwindow), which is not a valid argument to PyCapsule_New.  Use None to cover that case, instead.
Closes #28267 (in all likelihood...).
> Handle GetForegroundWindow() returning NULL.

- .github/workflows/codeql-analysis.yml
This is now warning that it does nothing:
https://github.blog/changelog/2024-01-23-codeql-2-16-python-dependency-installation-disabled-new-queries-and-bug-fixes/
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pa …
> ci: Remove deprecated codeql option

- .github/workflows/cibuildwheel.yml
GitHub has recently announced that they would be retired on June 28.
Also, remove the special-casing for `MACOSX_DEPLOYMENT_TARGET`, as meson-python 0.16.0 is out now and handles this automatically for us. …
> BLD: Move macos builders from 11 to 12

- galleries/examples/mplot3d/imshow3d.py
Serving
> * Separate planes (well, one would be enough then) is a simpler example that should be done separately. 
_Originally posted by @story645 in https://github.com/matplotlib/matplotlib/issues/28239#issuecomment-2116840524_
> DOC: Add an example for 2D images in 3D plots

- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/mplot3d/tests/test_axes3d.py
In mplot3d.Axes3D._on_move(), pass roll angle to view_init() in degrees (as it expects; not converted to radians, mistakenly).
Resolves #28256.
> Correct roll angle units, issue #28256

- lib/matplotlib/axes/_base.py
- lib/matplotlib/tests/test_axes.py
1. Part of the calculation of `top` does not depend on `title`, so move it outside the loop.
2. If no titles have been set, skip this logic entirely.
I used `fig_many.savefig(stream, format='svg', bbox_inches='tight')` and `fig_many_sharex.savefig(stream, format='svg', bbox_inches='tight')` from #26150 as benchmarks.  `fig_many.savefig` ran in ~320-330 ms regardless of this change.  For `fig_many_sharex` I got
With `main`:
```
484 ms ± 9.87 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
After (1)
```
328 ms ± 8.95 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
After (2)
```
230 ms ± 9.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
> Faster title alignment

- lib/mpl_toolkits/mplot3d/axes3d.py
Immediately update orientation indication in 3d plot when left mouse button is pressed or released (instead of requiring a mouse movement first): Issue #28310
> Update 3D orientation indication right away

- lib/matplotlib/tests/test_ticker.py
- lib/matplotlib/ticker.py
Resolves IndexError in `MaxNLocator._raw_ticks()`.
The IndexError occurred under the following conditions:
- nbins=1
- rcParams['axes.autolimit_mode'] == 'round_numbers'
- the input parameters for vmin and vmax resulted in no large_steps (all are False)
closes #27603 
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docs …
> Resolve MaxNLocator IndexError when no large steps

- doc/api/toolkits/mplot3d/view_angles.rst
- doc/users/next_whats_new/mouse_rotation.rst
- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/mplot3d/tests/test_axes3d.py
- Addresses Issue #28288, i.e.:
- Makes three-dimensional rotation by mouse independent of the particular orientation at hand, which is natural and intuitive (no 'gimbal lock')
- Extends the rotation to all three rotational degrees of freedom
- Introduces three-dimensional rotation by mouse using a variation on Ken Shoemake's ARCBALL
- Provides a minimal Quaternion class, to avoid an additional  dependency on a large package like 'numpy-quaternion'
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstring …
> Introduce natural 3D rotation with mouse

- lib/mpl_toolkits/mplot3d/axes3d.py
The parameters changed are keyword-only, so the change is backwards compatible.
Move shareview next to the view angles, and then sharez next to shareview.  Move focal_length next to proj_type.
followup to #28359.
> Reorder Axes3D parameters semantically.

- doc/devel/testing.rst
Fixed the code in the [check figures equal](https://matplotlib.org/devdocs/devel/testing.html#compare-two-methods-of-creating-an-image) example in contribute/testing so that it works and creates two equal figures.
> DOC: fixed code for testing check figures equal example

- lib/matplotlib/patheffects.py
The current implementation is exactly the same as in the super class.
Also, move the `__getattribute__` definition higher, before all renderer-specific method definitions.
> PathEffectsRenderer can plainly inherit RendererBase._draw_text_as_path.

- lib/matplotlib/backend_bases.py
The line of code mentioned in the docstring has been removed since e50ff69d, back in 2004...
Replace with a comment in the code, closer to the place relevant for metrics calculations.
> Remove outdated docstring section in RendererBase.draw_text.

- doc/api/next_api_changes/behavior/28363-TS.rst
- doc/users/next_whats_new/subfigures_change_order.rst
- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_figure.py
Closes #28344. Change the iteration order on the rows and columns of `subfigure` to draw them in row-major order.
> flip subfigures axes to match subplots

- lib/matplotlib/backends/registry.py
- lib/matplotlib/tests/test_backend_registry.py
Fixes #28367.
This allows duplicate (name, value) entry points for self-registering backends such as `matplotlib-inline`. This should not occur but sometimes a single `entry_points.txt` file can appear as two identical entry points and hence before this fix a `RuntimeError` was raised. With this fix the duplicated entry points are tolerated.
> Allow duplicate (name, value) entry points for backends

- lib/matplotlib/backend_bases.py
This private helper is only used in a single place (and not by subclasses).  Inlining it makes it clearer that this is not something third-party backends need to worry about (and avoids having to duplicate the description of the parameters).
Also clarify the actual behavior of the `ismath` parameter in `draw_text`.
> Inline RendererBase._get_text_path_transform.

- lib/matplotlib/widgets.py
These code and docstring parts were made obsolete when the compatibility shims were removed in 3.9.
Fixes #28404 
> Clean up obsolete widget code

- lib/matplotlib/tests/test_text.py
- lib/matplotlib/text.py
`_get_dist_to_box()` assumed that the figure box (x0, y0) coordinates are 0, which was correct at the time of writing, but does not hold anymore since the introduction of subfigures.
Closes #28378
Closes #28358
Note that the modified test fails with the original `_get_dist_to_box()` implementation.
> FIX: Fix text wrapping

- lib/matplotlib/projections/polar.py
- lib/matplotlib/tests/test_polar.py
I've fixed `PolarAxes` to use `fmt_xdata` and `fmt_ydata` and added a few simple tests to test that functionality. (#4568)
> Fixed PolarAxes not using fmt_xdata and added simple test (#4568)

- galleries/examples/units/basic_units.py
We are getting reviewdog failures in the galleries/examples tests with numpy 2.0. There are new keyword arguments required for __array__ and __array_wrap__ that are expected in numpy 2.0.
From the release notes https://numpy.org/devdocs/release/2.0.0-notes.html
> __array_wrap__ is now passed arr, context, return_scalar and support for implementations not accepting all three are deprecated. Its signature should be __array_wrap__(self, arr, context=None, return_scalar=False)
https://numpy.org/devdocs/release/2.0.0-notes.html#the-array-special-method-now-takes-a-copy-keyword-argument
> NumPy will pass copy to the __array__ special method in situations where it would be set to a non-default value (e.g. in a call to np.asarray(some_object, copy=False)). Currently, if an unexpected keyword …
> MNT: Update basic units example to work with numpy 2.0

- doc/conf.py
- doc/devel/coding_guide.rst
- doc/devel/development_setup.rst
- doc/install/dependencies.rst
Tried to clean up the explanation of build isolation a bit based on https://github.com/matplotlib/matplotlib/pull/28091#discussion_r1598796997 and added notes about mypy not picking up new functions b/c that's confused contributors in the past.
> DOC: clarify no-build-isolation & mypy ignoring new functions

- .github/workflows/cibuildwheel.yml
#28411 conflicted because #28371 wasn't done yet. But I think we probably want the latter mostly because of the updates to attestation and PyPI publishing workflows.
- [n/a/] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [n/a] …
> Backport of 28371 and 28411

- galleries/examples/ticks/ticklabels_rotation.py
set_xticks only works if redefining the ticks at the same time; tick_params works in all cases.
> Expand ticklabels_rotation example to cover rotating default ticklabels.

- lib/matplotlib/tests/test_image.py
- src/_image_wrapper.cpp
Correct numpy dtype comparisons in `image_resample` C++ code.
Previously we were using `dtype1.is(dtype2)` (the pybind11 C++ equivalent of `dtype1 is dtype2` in Python) whereas we should have been using `dtype1.equal(dtype2)` (the pybind11 C++ equivalent of `dtype1 == dtype2` in Python).
> Correct numpy dtype comparisons in image_resample

- lib/matplotlib/path.py
During a review in Cartopy, it was noted that it was non-obvious that `Path.to_polygons` would also simplify the path.
https://github.com/SciTools/cartopy/pull/2362#issuecomment-2179511074
This adds an explicit note that it will simplify the path according to the `should_simplify` attribute.
- [n/a] *New Features* and *API Changes* are noted with a [directive and …
> DOC: Add note about simplification of to_polygons

- lib/matplotlib/cm.py
- lib/matplotlib/cm.pyi
Addresses https://github.com/matplotlib/matplotlib/issues/28349#issuecomment-2152758163
> We are seeing multiple reports that the warnings in 3.8 were not seen. We should sort out why and consider putting the API in a micro release with a more visible warning (at maybe a custom AttributeError that gives more context?).
This was removed in 3.9, but apparently caused more user trouble than expected. Re-added for 3.9.1 and extended the deprecation period for two additional minor releases.
I did not find a technical reason why people may not see it. My wild guess is that this was quite commonly used and there are enough cases where people jump more than 2 minor versions. Hopefully extending for 2 additional minor releases will be good enough. - I question whether this was too common and …
> MNT: Re-add matplotlib.cm.get_cmap

- src/_macosx.m
Closes #28387
This ensures that we do not get a deadlock when we try to close tabs.
> Add GIL Release to flush_events in macosx backend

- lib/matplotlib/axes/_base.py
Superseeds #23629.
It is somewhat surprising that "_apply_aspect" takes an optional position as input, which seems more functionality than what the name suggests.
The parameter was introduced in 66290aae. Generally, applying an aspect will modify the size and position of an Axes. The fact that position is updated anyway was used to funnel additional position information from a layout into the already existing positioning code.
Deprecating and removing the parameter would be a medium compatibility hassle. Therefore, I chose only to document the status quo and its intention, so that users are less surprised. See
https://github.com/matplotlib/matplotlib/pull/23629#issuecomment-2145669284
> DOC: Document the parameter *position* of apply_aspect() as internal

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/container.py
- lib/matplotlib/container.pyi
Also, make some of the docs consistent between the two places.
Fixes #28467
> Fix typing and docs for containers

- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_figure.py
Manual backport of #28397.  Conflict was just because `main` has an extra test before the new one.
> Backport PR #28397 (FIX: stale root Figure when adding/updating subfigures)

- lib/matplotlib/tests/test_transforms.py
- lib/matplotlib/transforms.py
Formerly, this fell back to the the super-class Transform implementation, which returned `Transform.contains_branch` for both dimensions. This doesn't make sense for blended transforms, which have their own implementation that checks each side. However, it _also_ doesn't make sense for composite transforms, because those may contain blended transforms themselves, so add a specific implementation for it.
Also fix type inconsistency for `Transform.contains_branch_seperately`.
This does fix #28383, though since it has to reach into transform internals to do so might make one a bit wary. …
> Fix CompositeGenericTransform.contains_branch_seperately

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
This only triggers when the normal (without an `axhspan` call) autolimits are far from 0, so modify a test to match that.
Fixes #28341
> Fix autoscaling with axhspan

- lib/matplotlib/font_manager.py
The query can fail in some environments where system_profiler is not available on PATH, but we don't want it to just crash the entire thing.
> Don't fail if we can't query system fonts on macOS

- lib/matplotlib/backends/backend_gtk3cairo.py
- lib/matplotlib/backends/backend_gtk4.py
- lib/matplotlib/backends/backend_gtk4cairo.py
For GTK4Cairo, HiDPI displays were broken because we were scaling unnecessarily, as GTK4 takes care of setting up the Cairo context for us with the right scale.
For GTK3Cairo, _all_ displays were broken, as we inferred the size from the backing surface (since #22004), which is the size of the _window_. Then we re-orient the origin using that height, causing everything to be placed incorrectly. …
> Fix GTK cairo backends

- .appveyor.yml
This is generally faster at solving than conda, and AppVeyor seems to have an older version of the latter too.
But I'm not sure if this will help anything on AppVeyor, so draft for now. …
> CI: Use micromamba on AppVeyor

- doc/api/next_api_changes/removals/28492-GML.rst
- lib/matplotlib/collections.py
- lib/matplotlib/tests/test_collections.py
The mask is no longer compressed and full 2D arrays are used for the PolyQuadMesh objects. This removes the deprecation path that began in v3.8.
> MNT: Remove PolyQuadMesh deprecations

- doc/_static/switcher.json
This should stop the banner from showing up on stable.
> DOC: Fix version switcher for stable docs

- doc/api/next_api_changes/behavior/27833-JA.rst
- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/tests/test_backend_svg.py
- lib/matplotlib/tests/test_determinism.py
This pull request is intended to improve the reproducibility of SVG output from `matplotlib`, by removing variability from the ID generation scheme for the identifiers of `<clipPath>` XML elements (and references to them).
In particular, use of the Python built-in `id(...)` function, that retrieves an integer identifier for an object in memory at runtime -- not _necessarily_ a memory address, but often so -- is removed and replaced by a monotonically increasing counter value.
Closes #27831.
Edit: use a more-direct hyperlink to the test coverage recommendation.
> [SVG] Introduce sequential ID-generation scheme for clip-paths.

- lib/matplotlib/backends/backend_qt.py
Resize the Qwidget causes the FigureCanvasQT width to 0 will raise: `RuntimeWarning: divide by zero encountered in scalar divide fig_aspect = bb.height / bb.width`
Resize the Qwidget causes the FigureCanvasQT height to 0 will raise: `ValueError: 'box_aspect' and 'fig_aspect' must be positive`
Change FiCureCanvasQT widget size (w, h) from non-negative to positive to make sure fig_aspect is positive.
- [N/A] *New Features* and *API Changes* are noted with a …
> Fix value error when set widget size to zero while using FiCureCanvasQT 

- galleries/examples/pyplots/axline.py
- galleries/examples/subplots_axes_and_figures/axhspan_demo.py
- Replace the clutter of many random plot elements by one meaningful example.
- Only cover spans. Remove the lines and instead cross-link to them.
> DOC: Simplify axhspan example

- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_figure.py
Follow up to #28397.  Now that #28177 is merged, we can have the stale callback work on the artist's direct parent (sub)figure, and so the staleness propagates through all the nested figures. …
> Subfigures become stale when their artists are stale

- doc/users/next_whats_new/svg_id_rc.rst
- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/mpl-data/matplotlibrc
- lib/matplotlib/rcsetup.py
- lib/matplotlib/tests/test_backend_svg.py
Exported SVGs now contain a fixed `id="svg1"` attribute in the top level `<svg>` tag.
```svg
<svg 
xmlns:xlink="http://www.w3.org/1999/xlink"
width="50pt" height="50pt"
viewBox="0 0 50 50"
xmlns="http://www.w3.org/2000/svg"
version="1.1"
id="svg1"
>
```
This is useful if you would like to link the entire matplotlib SVG file within another SVG file with the `<use>` tag.
```svg
<use
width="50" height="50"
xlink:href="mpl.svg#svg1" id="use1"
x="0" y="0"
/>
```
Where the `#svg1` indicator will now refer to the top level `<svg>` tag, and will hence result in the inclusion of the entire file.
Closes issue #28535
> [svg] Add rcParam["svg.id"] to add a top-level id attribute to <svg>

- lib/matplotlib/font_manager.py
- lib/matplotlib/tests/test_font_manager.py
The locker works by writing a file to disk.  This can also fail so make sure we can still import in that case.
Closes #28538
The only way I could think to test this is very synthetic and requires messing with the file system at in between importing the top level module and font_manager.  Still not sure how the OP drove their system to expose this issue.   I think it has not come up before because if the directory is not writable we detect that and bail to asking for a temporary directory to work with.
- [-] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [-] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announ …
> MNT: be more careful about disk I/O failures when writing font cache

- lib/matplotlib/image.py
Minor rewrite. I did this as part of trying to understand the intended behavior. It's still not complete but at least makes it more obvious where information is still sparse.
> DOC: Change _make_image signature to numpydoc

- src/_image_resample.h
A fresh build off the main branch was raising the following warning on WSL. This fixes that warning while keeping the behavior, and no warnings are raised during build now.
```
[87/101] Compiling C++ object src/_image.cpython-312-x86_64-linux-gnu.so.p/_image_wrapper.cpp.o
In file included from ../../src/_image_wrapper.cpp:4:
../../src/_image_resample.h: In instantiation of ‘struct is_grayscale<agg::rgba64, void>’:
../../src/_image_resample.h:509:11:   required from ‘struct type_mapping<agg::rgba64>’
../../src/_image_resample.h:708:11:   required from ‘void resample(const void*, int, int, void*, int, int, resample_params_t&) [with color_type = agg::rgba64]’
../../src/_image_wrapper.cpp:190:17:   required from here
../../src/_image_resample.h:503:58: warning: left operand of comma operator …
```
> [BLD] Fix WSL build warning

- .github/ISSUE_TEMPLATE/tag_proposal.yml
Noticed there was no automatic label added on #28565. We don't have a "Tag proposal" label. …
> MNT: Update label for Tag proposal issue template

- lib/matplotlib/backend_tools.py
Instead of having both _add_tool_cbk (the main callback that handles addition of new tools) and _add_tool (which does the same but for pre-existing tools), we can just always use _add_tool_cbk, sending synthetic tool_added_events for the initialization step).
Also move _tool_trigger_cbk down, next to _set_cursor_cbk, with which it is semantically associated.
> Remove one indirection layer in ToolSetCursor.

- lib/matplotlib/figure.pyi
- lib/matplotlib/pyplot.py
Fixes https://github.com/matplotlib/matplotlib/pull/27001#issuecomment-2211785864
My solution is to have 3 possible cases:
1. `squeeze=True`, `nrows=1`, `ncols=1`: `Axes`
2. `squeeze=True`: `np.ndarray`
3. `squeeze=False`: `np.ndarray`
1 and 3 already existed. 2 is _hopefully_ treated as a fallback by mypy for when either `nrows` or `ncols` is not 1. All of my testing with `reveal_type` works as expected, but I would love suggestions for how to formally test this in CI so it doesn't happen again.
> [TYP] Fix overload of `pyplot.subplots`

- lib/matplotlib/projections/geo.py
GeoAxes does not support changing limits. We already raised on `set_x/ylim()`. This now also raises on
`set_x/ybounds()` and `invert_x/yaxis()`.
Closes #28590.
> MNT: Raise on GeoAxes limits manipulation

- doc/users/next_whats_new/histogram_vectorized_parameters.rst
- galleries/examples/statistics/histogram_multihist.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Closes #26718 Distributes keyword args passed to each Patch using a cycler. Probably not the best way to do this?
> Add support for multiple hatches, edgecolors and linewidths in histograms

- .github/workflows/tests.yml
The 6.7.1 wheels on PyPI do not confirm to manylinux 2.28 due to requiring glibc 2.35 symbols, and cannot be loaded on Ubuntu 20.04, which has glibc 2.31. So we need to pin that back to avoid the failures. …
> Pin PyQt6 back on Ubuntu 20.04

- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/tests/test_backend_svg.py
> svg: Ensure marker-only lines get URLs

- doc/api/next_api_changes/deprecations/27385-SS.rst
- lib/matplotlib/path.py
- lib/mpl_toolkits/mplot3d/art3d.py
- lib/mpl_toolkits/mplot3d/proj3d.py
- lib/mpl_toolkits/mplot3d/tests/test_axes3d.py
Closes https://github.com/matplotlib/matplotlib/issues/6305
Lines behind the camera were not being properly culled, and were visible in certain circumstances. Will leave this as a draft until I figure out if this issue applies to all 3D objects and not just lines. Also want to understand what exactly `proj3d.proj_transform_clip` is doing since I would have thought that does exactly this, but swapping to that function didn't solve anything.
Note to self, this is a good reference: https://www.scratchapixel.com/lessons/3d-basic-rendering/perspective-and-orthographic-projection-matrix/opengl-perspective-projection-matrix
- [n/a] *New Features* …
> Fix 3D lines being visible when behind camera

- .github/workflows/cibuildwheel.yml
And also bump cibuildwheel, replacing #28265, which dependabot messed up.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings …
> BLD: Enable building Python 3.13 wheels for nightlies 

- .circleci/config.yml
- doc/conf.py
- requirements/doc/doc-requirements.txt
The latest sphinx-gallery 0.17.0 adds support for parallel building of examples, and the issue in pydata-sphinx-theme was fixed in 0.15.4, so we can try enabling it again.
We're on a large docker instance, with 4 cores and 8GB RAM; the RAM tracking shows we use max 43% / average 37%, so I've set parallelism to 2, which hopefully won't OOM.
cf #28244 for the last attempt that was stalled by the pydata-sphinx-theme issue. …
> DOC: Enable parallel builds

- lib/matplotlib/animation.pyi
`frames` in `FuncAnimation.__init__` can be an Iterable of anything.
I'm assuming this typo was caused by a file-wide search and replace, since all other Iterables in this file are indeed `Iterable[Artist]`
> TYP: Fix a typo in animation.pyi

- .circleci/config.yml
- .github/workflows/circleci.yml
There have been improvements to Python performance in 3.11 and 3.12 thanks to the Faster CPython project, and we hope this might help a little with docs.
> CI: Build docs on latest Python

- lib/matplotlib/axis.py
- lib/matplotlib/tests/test_axis.py
Fixes #28623 in exactly the way suggested there.
> FIX: `Axis.set_in_layout` respected

- lib/matplotlib/axes/_axes.py
Parameters vmin and vmax are not documented inside specgram function.
Issue: https://github.com/matplotlib/matplotlib/issues/28548
> Added documentation for parameters vmin and vmax inside specgram function.

- galleries/examples/images_contours_and_fields/multi_image.py
I've simplified the basic example to only share the norm. This should be sufficient for most users and greatly simplifies the code. Syncing the colorbar moved to a separate comment - for those wo need the extra functionality.
> DOC: Clarify/simplify example of multiple images with one colorbar

- lib/matplotlib/colors.py
ColorMap._repr_html_ produces html that doesn't properly close all div tags.  It was simple fix to add a closing div to the method.
- There wasn't an open issue for this.
> Closed open div tag in color.ColorMap._repr_html_

- galleries/examples/images_contours_and_fields/image_annotated_heatmap.py
Directly rotate ticks in `set_xticks` instead of setting the ticks and then changing them afterwards using `plt.setp(...)`.
Also use the simpler and shorted `range` instead of `np.arange`.
> DOC: Simplify heatmap example

- doc/conf.py
A released version should point to its version, not 'stable', since that doesn't appear in the version switcher. And devdocs should point to 'dev', since that's what it's called in the JSON.
Note that in our JSON, we only list up to meso versions, though the version is noted in full. This means that older micro versions will not have an entry in the switcher, and the switcher will not be set to anything if you go there, but that's probably fine. …
> DOC: Fix matching for version switcher

- lib/matplotlib/lines.py
Fixes code style inconsistencies for docstrings in lines.py
Closes [#28630](https://github.com/matplotlib/matplotlib/issues/28630)
> Fix docstring style inconsistencies in lines.py

- lib/matplotlib/artist.py
- lib/matplotlib/cbook.py
- lib/matplotlib/tests/test_image.py
closes #28648
Special case singular norms and estimating 0 width ranges at 0
- [/] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [/] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [/] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines
> FIX: improve formatting of image values in cases of singular norms

- galleries/examples/user_interfaces/embedding_in_qt_sgskip.py
While developing a Qt application that had to retrieve data as quickly as possible from a measurement instrument, and display that in multiple plots, I encountered an issue with my 1ms timers causing the application to not respond to events, and essentially making the app stuck and unusable. [ChatGPT helped me](https://chatgpt.com/share/2f110cad-77ee-4442-9b66-e773dec678e3) to figure out I need to process the events in my timer timeout function. This has bugged me for a week or so, and this is not trivial to figure out by oneself IMO. Hence this PR. See also https://github.com/pyqtgraph/pyqtgraph/issues/3092.
- [N/A] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-i …
> Qt embedding example: Separate drawing and data retrieval timers

- doc/api/next_api_changes/deprecations/28670-TAC.rst
- lib/matplotlib/patches.py
Remove unused (and untested) helper function.
Noted this while reviewing the existing patch code with @ksunden 
- [/] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [/] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [/] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [/] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines
> API: deprecate unused helper in patch._Styles

- lib/matplotlib/widgets.py
Issue: #28165
The PolygonSelector now correctly hide the cursor when another widget is active, such as the zoom/pan functionality, ensuring a smooth user experience.. This fix ensures that the cursor is temporarily hidden when another interaction is active.
> Fix PolygonSelector cursor to temporarily hide during active zoom/pan

- lib/matplotlib/axis.py
- lib/matplotlib/tests/test_axes.py
Ticks will follow the `rcParams` at the time of their creation, if there were no other settings used. If the `rcParams` are set in a context, then the lazily-generated ticks may start fetching the wrong values. This is fixed via `Axis._copy_tick_props` by copying the properties from the `Tick`'s child `Artist`'s to the new ones. However, internal attributes from `Tick` are not copied, which is generally fine for drawing because nothing is every re-synced from there.
However, in the case of `Spine`'s window extent, it is generated from the tick direction and size attributes on the `Tick`, so being out of sync may cause an incorrect bounding box if the tick direction changes. Since `Spine` chooses a random `Tick`, this will cause tight/constrained layout to be nondeterministic.
Since this …
> Copy all internals from initial Tick to lazy ones

- src/_c_internal_utils.cpp
- src/_tkagg.cpp
This fixes several [warnings I noticed](https://github.com/QuLogic/mplpb11/actions/runs/10280477342/job/28447908104#step:4:347) while debugging source builds for #28551.
Most are harmless, but I think the capsule change in `_c_internal_utils` may have hidden a real error (and possibly MSVC just "did the right thing" for us). …
> Fix warnings from mingw compilers

- doc/conf.py
Otherwise, it will try to find it with intersphinx, and fail.
Note that this needs https://github.com/sphinx-gallery/sphinx-gallery/pull/1363 in order to work correctly (and that's currently patched in to the CI).
> DOC: Tell sphinx-gallery to link mpl_toolkits from our build

- doc/conf.py
- requirements/doc/doc-requirements.txt
Because the default is Base64-encoded frames of PNGs, this should save a substantial amount of space in the resulting docs. We may want to increase the bitrate slightly, though most of the videos seem clear enough to me.
This currently depends on sphinx-gallery/sphinx-gallery#1243 and sphinx-contrib/video#36.
These results are probably on the upper end, depending on if we change the bitrate, but disk usage is reduced substantially:
```
485M	html/
377M	doc/build/html/
```
That's 108M of savings, or 22% of the original disk usage.
- [n/a] new and changed code is …
> DOC: Use video files for saving animations

- .github/workflows/cibuildwheel.yml
This is the commit message #1:
> Merge pull request #28293 from QuLogic/py313
>
> BLD: Enable building Python 3.13 wheels for nightlies
(cherry picked from commit 725ee995000985b2ee24d1b21cd777e0811272c8)
This is the commit message #2:
> Merge pull request #28668 from matplotlib/dependabot/github_actions/actions-167bd8b160
>
> Bump the actions group with 2 updates
(cherry picked from commit fd42e7d63577ef88694913268fe5a5ffd8539431)
Note, I did leave out `CIBW_PRERELEASE_PYTHONS` since it's no longer needed with the new `cibuildwheel`.
> Backport PR #28293 and #28668: Enable 3.13 wheels and bump cibuildwheel

- .github/workflows/cibuildwheel.yml
- doc/api/next_api_changes/development/28687-ES.rst
This may prevent conflicts with other wheels that use the runtime at a different version, and _may_ be an alternative to #28679.
> BLD: Include MSVCP140 runtime statically

- src/path_converters.h
An optimization introduced in #24964 introduced a divide-by-zero error when creating a `Sketch` object in cases where some parameters were set to 0.  This is normally fine as the sketch is not used in these cases and was only detectable when compiled with `-fsanitize=float-divide-by-zero` . Avoid these errors by detecting zero and near-zero values passed in and set derived values to 0 in these cases.
closes #28669 …
> Avoid division-by-zero in Sketch::Sketch

- lib/matplotlib/axes/_axes.py
If you set a float alpha on your patch then including alphas in your face/edgecolor will have no effect.  I expect there are other docstrings that would benefit from spelling this out, but here is a start.
cc @pawjast
> DOC: clarify alpha handling for indicate_inset[_zoom]

- doc/missing-references.json
The numpydoc 1.8.0 release re-ordered some sections [1] in generated docs, which caused our missing reference extension to no longer ignore some entries since they are at different lines.
Fixes #28715
[1] https://github.com/numpy/numpydoc/pull/571
> DOC: Update missing references for numpydoc 1.8.0

- doc/devel/release_guide.rst
I make releases in a new worktree, so it doesn't always have pre-commit setup, so I always forget to check `codespell`, and so making a release can introduce issues from the Issue/PR titles in the GitHub stats.
Also, note another file to update in the documentation repo. …
> DOC: Add a few more notes to release guide

- src/meson.build
As of #28687, our extensions depend on `VCRUNTIME140_1.dll`, and this was allowed because Python 3.8+ started shipping that file. The original report in #18292 was for Python 3.7, which didn't ship the DLL, but we require Python 3.10 now, so it's safe again.
Since we can use that dependency, there's no need to disable the option that started requiring it in the first place. As noted in the original blog post [1], this will make our extensions smaller, and slightly faster.
[1] https://devblogs.microsoft.com/cppblog/making-cpp-exception-handling-smaller-x64/
- [n/a] *Plotting related* features are …
> Stop disabling FH4 Exception Handling on MSVC

- lib/matplotlib/tests/test_backends_interactive.py
- pyproject.toml
These are the minimal changes, but if necessary, we can backport the CI changes to drop GTK4 and pin homebrew more. …
> Backport fixes from #28711

- .github/workflows/cibuildwheel.yml
Due to https://github.com/pypa/distutils/issues/283, kiwisolver fails to build on PyPy. Until kiwisolver has PyPy 3.10 wheels (https://github.com/nucleic/kiwi/pull/182), we should avoid the buggy setuptools.
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-dep …
> ci: Avoid setuptools 72.2.0 when installing kiwi on PyPy

- lib/matplotlib/dviread.py
Admittedly, this is a bit of a stylistic preference, but I find it a bit confusing to do stuff like:
```
w, x, y, z = foo, bar, baz, quux
```
when the RHS parts are more complex than a simple value.
And with simple values like `None`, that can be simplified to:
```
w = x = y = z = None
```
but with things like `[]`, then we _don't_ want to do that, so it's simpler to make those separate lines. …
> Simplify some code in dviread

- lib/matplotlib/tests/test_collections.py
The image comparison directory is determined by `inspect.getfile(func)`, but when a test is wrapped in `rc_context`, the file returned is `contextlib` since that decorator is `contextlib.contextmanager`. Since this test uses `check_figures_equal`, that doesn't break it, but it does break the `triage_tests.py` tool as it cannot find a corresponding baseline image directory.
Moving the `rc_context` decorator above `check_figures_equal` fixes the determined directory. While in this case, the context doesn't set anything that would affect figures, it also makes sense to set the context before figures are created.
- [n/a] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-i …
> TST: Fix image comparison directory for test_striped_lines

- doc/api/next_api_changes/behavior/28734-REC.rst
- lib/matplotlib/_constrained_layout.py
- lib/matplotlib/tests/test_constrainedlayout.py
Closes #27866.  I found myself wanting this today.  The code from the issue now produces
I am at a loss how to provide a deprecation path for this.
> Compressed layout moves suptitle

- doc/api/next_api_changes/behavior/28501-OV.rst
- lib/matplotlib/dates.py
- lib/matplotlib/tests/test_dates.py
Fixes a bug with ConciseDateFormatter's offset string where the proper label is not shown if the axis is inverted. Closes https://github.com/matplotlib/matplotlib/issues/28481.
> ConciseDateFormatter's offset string is correct on an inverted axis

- lib/matplotlib/offsetbox.py
Fix for the issue #28129. When using a draggable legend with use_blit=True and picking enabled, the bug caused the whole legend to disappear once a line in the legend was clicked.
> Fix draggable legend disappearing when picking while use_blit=True

- doc/api/next_api_changes/behavior/28375-MP.rst
- lib/matplotlib/tests/test_transforms.py
- lib/matplotlib/transforms.py
Makes `mtrans.AffineDeltaTransform` update correctly when axis bounds change. Change made by @anntzer 
closes #28372 
enables the proposed example in #28364 to work correctly
A combination of manual and unit tests.
Manually verified that the example above works as expected now:
Before:
After:
Unit test shows that the parent transform is invalidated when the child is now.
> FIX: Made AffineDeltaTransform pass-through properly

- src/py_converters.cpp
This fixes the following errors from valgrind:
```
Conditional jump or move depends on uninitialised value(s)
at 0x377C3EE4: UnknownInlinedFun (path_converters.h:1025)
by 0x377C3EE4: UnknownInlinedFun (_backend_agg.h:477)
by 0x377C3EE4: PyRendererAgg_draw_path(PyRendererAgg*, _object*) [clone .lto_priv.0] (_backend_agg_wrapper.cpp:197)
by 0x49E8705: method_vectorcall_VARARGS (descrobject.c:331)
by 0x4A03B7B: UnknownInlinedFun (pycore_call.h:92)
by 0x4A03B7B: PyObject_Vectorcall (call.c:325)
by 0x49ECEA4: _PyEval_EvalFrameDefault (bytecodes.c:2714)
by 0x4A2B684: UnknownInlinedFun (call.c:419)
by 0x4A2B684: UnknownInlinedFun (pycore_call.h:92)
by 0x4A2B684: method_vectorcall (classobject.c:91)
by 0x49F1E44: UnknownInlinedFun (call.c:387)
by 0x49F1E44: _PyEval_EvalFrameDefault …
```
> Ensure SketchParams is always fully initialized

- .circleci/config.yml
- requirements/dev/build-requirements.txt
recent numpy breaks `basic_units.py`, which breaks the doc build. 
Someone should fix `basic_units.py`, but for now, force version to be smaller than numpy 2.1
> DOC/TST: lock numpy < 2.1

- lib/matplotlib/__init__.py
- lib/matplotlib/tests/test_pickle.py
For a ditry tree, `setuptools-scm` adds the date to the end of the version. This test runs a subprocess and `subprocess_run_helper` will set `SOURCE_DATE_EPOCH=0`, which forces the date to be 1970-01-01, triggering a mismatched version warning on unpickle.
Since we aren't testing the version-compatibility warning, set `SETUPTOOLS_SCM_PRETEND_VERSION_FOR_MATPLOTLIB` in the subprocess call so that versions match.
We also need to set the `dist_name` parameter when querying setuptools-scm or it won't check that environment variable.
This is something I've long seen, but never investigated.
- [n/a] *Plotting …
> TST: Fix test_pickle_load_from_subprocess in a dirty tree

- lib/matplotlib/tests/test_ft2font.py
- src/ft2font.cpp
- src/ft2font_wrapper.cpp
I tried to cross-compare these against something external, like FontForge or `fonttools`, though a lot are just "make sure it keeps working the same way".
I left out `FT2Font.get_ps_font_info` because it doesn't appear that any of shipped fonts would return anything but `None`.
Additionally, this fixes a few bugs I've found:
* The return value of `FT2Font.set_text` is a NumPy array with a data pointer that was freed, meaning any reading of it would read an invalid pointer. Apparently, we never use this return value internally, so it's never been a problem, but it has existed since about forever.
* The created/modified timestamps in the `head` table from `FT2Font.get_sfnt_table` were signed, which is incorrect, as  they should still be positive now, given that the epoch is some time in …
> Add tests for most of FT2Font, and fix some bugs

- doc/users/next_whats_new/contour_color.rst
- lib/matplotlib/contour.py
- lib/matplotlib/tests/test_contour.py
Within `ContourSet.__init__`, explicitly check whether _colors_ has been passed as a color type and if so make it a single element list.  This removes the restriction that a single color can only be passed as a string, which was somewhat inconsistent with other places that take a single color.
Fixes #28782 since `'green'` becomes `['green']` so we no longer slice the string.
> Handle single color in ContourSet

- .github/labeler.yml
- doc/sphinxext/missing_references.py
In cda437289b0cf41a01571904b6a13bedf8f037a4, I "simplified" from `node['refdomain']` to the existing `domain` argument. With `sphinx-tags`, the `warn-missing-reference` event occurs for a `None` domain, and we crash trying to access `domain.name`. But `node['refdomain']` is still an empty string, so revert back to that.
Noticed this as part of #27302.
- [n/a] *New …
> DOC: Fix missing cross-reference checks for sphinx-tags

- lib/matplotlib/__init__.py
Closes #28817.
There are some use cases where a user might have to make ~/.config a symlink (e.g. if a corporate home directory has limited space, and symlinks are used to offload the storage to a separate storage disk). So resolving configdir beforehand should prevent the is_dir() check from failing, causing a warning to be issued and forcing a temporary directory to be used.
> Resolve configdir so that it's not a symlink when is_dir() is called

- lib/matplotlib/_docstring.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/contour.py
- lib/matplotlib/figure.py
- lib/matplotlib/legend.py
- lib/matplotlib/mlab.py
- lib/matplotlib/offsetbox.py
- lib/matplotlib/patches.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/sankey.py
- lib/matplotlib/spines.py
- lib/matplotlib/table.py
- lib/matplotlib/tri/_tricontour.py
- lib/mpl_toolkits/axes_grid1/inset_locator.py
Historically, they were the different, but are the same for
several years. Since the whole `_docstring` module has become private,
we can simply remove the alias `dedent_interpd`. Note that `interpd`
nowadays also handles indentation smartly, so we don't have to care
about "dedenting".
>  MNT: Replace _docstring.dedent_interpd by its alias _docstring.interpd

- doc/api/next_api_changes/removals/27218-TAC.rst
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backend_bases.pyi
Remove a scheduled deprecation of holding a hard reference to the last event.
> API: finish LocationEvent.lastevent removal

- galleries/examples/text_labels_and_annotations/fonts_demo.py
- galleries/users_explain/text/text_intro.py
Replace default initialization immediately followed by setting values by initialization with values, i.e.
```
fp = FontProperties()
fp.set_[something](val)
fp = FontProperties([something]=val)
```
This is clearer and additionally helps with the possible transition of making FontProperties immutable, see #22495.
> MNT: Use __init__ parameters of font properties

- lib/matplotlib/cbook.py
- lib/matplotlib/tests/test_cbook.py
Closes #26012.
The first two commits are cleanup-ish:
- Record the connected signal in CallbackRegistry weakref cleanup function, to remove the need to loop over all signals in _remove_proxy.
- Flatten CallbackRegistry._func_cid_map: It is easier to manipulate a flat (signal, proxy) -> cid map rather than
a nested signal -> (proxy -> cid) map (especially for the third commit).
The last commit implements support for unhashable callbacks, by replacing _func_cid_map by a dict-like structure (_UnhashDict) that also supports unhashable entries.
Note that _func_cid_map (and thus _UnhashDict) can be dropped if we get rid of proxy deduplication in CallbackRegistry (#20210).
---
edit: ah, the joys of type-checking 😑 (https://github.com/python/mypy/issues/4266)
> Support unhashable callbacks in CallbackRegistry

- doc/users/next_whats_new/subfigures_change_order.rst
- galleries/examples/subplots_axes_and_figures/subfigures.py
- lib/matplotlib/figure.py
> DOC: Mark subfigures as no longer provisional

- lib/matplotlib/tests/test_legend.py
For labelcolor={linecolor,markeredgecolor,markerfacecolor}, text will match the specified attribute if consistent, but fall back to black if they differ within a single labeled artist.
These tests use 10 random colours out of the ['r', 'g', 'b'] set, so 3 (all red, all green, all blue) out of 3**10 will result in the text _not_ being black. This is rare (0.0051%), but does happen once in a while (e.g., https://github.com/matplotlib/matplotlib/actions/runs/10967975776/job/30458622005).
Instead, just hard-code some different colours in the test. …
> Fix flaky labelcolor tests

- lib/matplotlib/backends/_backend_tk.py
Fix scaling in Tk on non-Windows systems, closes #10388
cc: @tacaswell
> Fix scaling in Tk on non-Windows systems

- doc/_embedded_plots/figure_subplots_adjust.py
- lib/matplotlib/figure.py
Closes #23005.
Example: https://output.circle-artifacts.com/output/job/227e8182-1813-47e4-8cfc-1689902c5e28/artifacts/0/doc/build/html/api/_as_gen/matplotlib.figure.Figure.subplots_adjust.html#matplotlib.figure.Figure.subplots_adjust
> DOC: Add illustration to Figure.subplots_adjust

- doc/api/axes_api.rst
- doc/missing-references.json
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_base.py
These were not rendered as links in the current docs, because the
associated code objects do not exist as targets in the docs. For some
reason, sphinx did not complain about it. But it does in some recent
PRs (extracted from #28560) - I'm unclear why, but anyway the correct
solution is to change to explicitly listing the attributes.
> DOC: Fix non-working code object references

- lib/matplotlib/_api/deprecation.py
- lib/matplotlib/_api/deprecation.pyi
- lib/matplotlib/backend_bases.py
- lib/matplotlib/hatch.py
- lib/matplotlib/legend.py
- lib/matplotlib/projections/polar.py
- lib/matplotlib/tests/test_api.py
Ever since #27702, the removal will always be a version, and not "two minor/meso releases later". The implicit "to" tends to get messed up by people writing custom `message` arguments, and since there's no reason to add the "to" into `removal` instead of in the message any more, move it to the message.
Also, fix the autogenerated message to follow what the docstring says (Falsy `removal` leaves out the removal date.)
- [n/a] *New Features* and *API …
> Remove 'in' from removal substitution for deprecation messages

- src/_backend_agg.h
Closes #19693
Seems like sketch was not handled at all for path collections.
Maybe not the nicest code, but my C/C++ is not that good.
If I understand it correctly, sketch isn't really tested (as it is hard to recreate the images?)?
Here is the output anyway:
> Fix issue with sketch not working on PathCollection in Agg

- doc/api/testing_api.rst
- doc/conf.py
- lib/matplotlib/testing/conftest.py
Motivated by #28830, figured it'd be a lot easier for contributors to use/reviewers to suggest if the pandas and xarray fixtures were exposed in the docs. I'm not fond of the subheading title but also can't think of a better one.
> doc: add pandas and xarray fixtures to testing API docs

- galleries/examples/color/color_cycle_default.py
The current visualization is quite messy (
https://matplotlib.org/stable/gallery/color/color_cycle_default.html).
Let's focus on:
- giving a one clear sequence
- giving the color names as 'CN' notation and named colors
- showing lines and patches (colors appear substantially different in thin lines and filled areas)
And don't bother with:
- multiple line widths - they are only a slight visual variation (compared to patches) and multiple widths clutter the example
- black background: It's enough to show the default color cycle on the default background.
New rendered example:
> DOC: Better visualization for the default color cycle example

- lib/matplotlib/lines.py
- lib/matplotlib/tests/test_lines.py
Hello, this PR closes #28386 by replacing `if np.isclose(slope, 0)` with `if slope == 0` in `lines.py`, allowing for better resolution of small slopes with `axlines`. Additionally, I have added the `test_line_slope` function in `test_lines.py` to ensure proper testing of this functionality.
I apologize for any confusion caused by my multiple PRs on this issue; I'm still familiarizing myself with Git and contributing to larger codebases. I appreciate your patience. Thank you. 
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecation …
> Fix `axline` for slopes <= 1E-8. Closes #28386

- lib/matplotlib/dviread.py
Rather, preemptively cache the reference loop by explicitly dropping the traceback.
See also db0c7c3 (#25470) for a longer description of the problem in another context.
(@tacaswell: I wonder whether using with_traceback(None) would have been a cleaner solution in #25470?)
> Don't cache exception with traceback reference loop in dviread.

- lib/matplotlib/tests/test_backends_interactive.py
We noticed this while looking at #28588.
- Close the figure immediately, to avoid the deprecation warning about automatically closing figure when changing backends. This test doesn't intend to test the warning, just the change behaviour itself.
- Enable the post-`show()` result check everywhere. The comment implies it should only be skipped on `(macOS and Qt5)`, but the condition is actually only enabled on `macOS and (not Qt5)`. I'm not sure if this will actually work as it's been disabled for so long unintentionally. …
> TST: Fix minor issues in interactive backend test

- doc/users/next_whats_new/axes_creation_speedup.rst
- lib/matplotlib/axis.py
Closes #28908.
It seems the read-access to `instance.majorTicks` per `instance .majorTicks.append()` still triggers the descriptor, even though `instance.majorTicks = []` previously should have rebound the name. For details see #28908.
> MNT: Fix double evaluation of _LazyTickList

- lib/matplotlib/cbook.py
- lib/matplotlib/dviread.py
- lib/matplotlib/font_manager.py
The original solution using with_traceback didn't actually work because with_traceback doesn't return a new exception instance but rather modifies the original one in place, and the traceback will then be attached to it by the raise statement.
Instead, we actually need to build a new instance, so reuse the _ExceptionProxy machinery from font_manager (slightly expanded).
Redo of #28899; sorry about that...
> Re-fix exception caching in dviread.

- .appveyor.yml
According to the SciPy toolchain roadmap [1], we should be supporting at minimum MSVC 2019. The AppVeyor image has been held back to MSVC 2017 (probably just forgotten since it didn't complain), which is starting to cause issues for more modern code. (Namely #28842 does not work even with the flag for new behaviour.)
There are many [other software changes](https://www.appveyor.com/docs/windows-images-software/#visual-studio-2019), so I'm opening this separately from #28842 just to confirm it doesn't break anything.
[1] https://docs.scipy.org/doc/scipy/dev/toolchain.html
- [n/a] *Plotting related* …
> ci: Bump build image on AppVeyor to MSVC 2019

- galleries/examples/shapes_and_collections/fancybox_demo.py
Noted while reviewing https://github.com/matplotlib/matplotlib/issues/28876#issuecomment-2379589972.
- Create subsections
- The plot for the different boxstyle attributes had mixed mutation_scale with Axes aspect. This makes it more difficult to understand. Therefore, we now show the effect of mutation_scale in isoliation.
- The aspect-correction topic is separated into an additional plot.
> DOC: Improve fancybox demo

- lib/matplotlib/colorbar.py
The `spacing` kwarg only makes sense in relation to `boundaries`, so put the docs for them next to one another and add an explicit reference from `boundaries` to `spacing`.  (The order of the kwargs in the signature did not change, because it already doesn't match the docs anyways; reordering them could be done separately.)
Closes #12312 (by documenting the behavior rather than trying to change anything).
> In colorbar docs, add ref from 'boundaries' doc to 'spacing' doc.

- doc/api/prev_api_changes/api_changes_2.2.0.rst
- doc/api/prev_api_changes/api_changes_3.1.0.rst
- doc/api/prev_api_changes/api_changes_3.2.0/removals.rst
- doc/api/prev_api_changes/api_changes_3.3.0/deprecations.rst
- doc/api/prev_api_changes/api_changes_3.5.0/removals.rst
- doc/api/prev_api_changes/api_changes_3.8.0/behaviour.rst
- doc/devel/MEP/MEP23.rst
- doc/users/prev_whats_new/whats_new_1.3.rst
- doc/users/prev_whats_new/whats_new_1.5.rst
- doc/users/prev_whats_new/whats_new_3.1.0.rst
- doc/users/prev_whats_new/whats_new_3.3.0.rst
- doc/users/prev_whats_new/whats_new_3.6.0.rst
- doc/users/prev_whats_new/whats_new_3.8.0.rst
- lib/matplotlib/axis.py
- lib/matplotlib/collections.py
- lib/matplotlib/contour.py
- lib/matplotlib/dates.py
These have either been deprecated and removed, or just simple typos. A small few were never rcParams in the first place.
These were surfaced by #28930, but don't need to wait for it to be fixed.
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and …
> DOC: Fix invalid rcParam references

- lib/matplotlib/tests/test_rcparams.py
- lib/mpl_toolkits/mplot3d/tests/test_axes3d.py
It now warns if the module is found, but fails to import (rather than not existing and raising ModuleNotFound).
> TST: handle change in pytest.importorskip behavior

- src/_backend_agg_basic_types.h
- src/_backend_agg_wrapper.cpp
- src/_path.h
- src/_path_wrapper.cpp
- src/mplutils.h
- src/numpy_cpp.h
- src/path_converters.h
- src/py_adaptors.h
- src/py_converters_11.h
Now that we are building with pybind11 in all extensions, we can drop/convert several items that were used across extensions. Namely, everything in `py_adaptors` (which was shared between `_path` and `_backend_agg`) can now get a type caster, all the remaining `array_view` can be moved to `py::array_t`, and the `ClipPath` converter issue from #27011 has been fixed.
Additionally, I moved the pybind11 type casters from `py_converters_11.h` to the files that define the related types. This keeps things a bit more consolidated, and avoids the weird `#ifdef` macro magic that was needed before.
- [n/a] …
> Convert remaining code to pybind11

- doc/users/next_whats_new/increased_figure_limits.rst
- extern/agg24-svn/include/agg_rasterizer_cells_aa.h
- lib/matplotlib/tests/test_agg.py
- src/_backend_agg.cpp
- src/_backend_agg.h
- src/_image_resample.h
When rendering objects, Agg rasterizes them into scan line objects (an x/y point, horizontal length, and colour), and the renderer class writes those to the pixels in the final buffer. Though we have determined that Agg buffers cannot be larger than 2**16, the scan line classes that we use contain 16-bit _signed_ integers internally, cutting off positive values at half the maximum.
Since the renderer uses 32-bit integers, this can cause odd behaviour where any horizontal span that _starts_ before 2**15 (such as a horizontal spine) is rendered correctly even if it cross that point, but those that start after (such as a vertical spine or any portion of an angled line) end up clipped. For example, see how the spines and lines break in #28893.
A similar problem occurs for resampled images, …
> Agg: Remove 16-bit limits

- pyproject.toml
We are publishing wheels, but forgot to update the metadata.
> BLD: update trove metadata to support py3.13

- lib/matplotlib/colors.py
This change improves the `rgb_to_hsv` function by adding a clear and explicit error message when the input RGB values are outside the valid range [0, 1]. Previously, the error raised by NumPy was not intuitive, making it difficult for users to understand the issue. This update ensures that users are notified of the value range requirements upfront, enhancing usability and debugging experience.
Fix #28941
> Raise ValueError for RGB values outside the [0, 1] range in rgb_to_hsv function

- lib/matplotlib/animation.py
pymedia has not been updated for 18y, and swf (adobe flash) is also no more.  Directly wrapping x264 could still be done but the comment probably doesn't help much...
> Remove refs to outdated writers in animation.py.

- src/_macosx.m
I'm getting `copy_agg_buffer failed` and no plots to show up with the macosx backend.
The `_renderer` attribute has changed with the pybind11 update and we aren't able to access it as a buffer anymore. We can use the buffer_rgba method to get the direct memoryview of the buffer instead.
git bisect shows me it is this commit: 96dd843546ee410ea27e2a3e8f61953a1d3cdc6a
ping @QuLogic
> FIX macos: Use the agg buffer_rgba rather than private attribute

- doc/api/toolkits/mplot3d/view_angles.rst
- doc/users/next_whats_new/mouse_rotation.rst
- lib/matplotlib/mpl-data/matplotlibrc
- lib/matplotlib/rcsetup.py
- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/mplot3d/tests/test_axes3d.py
Makes the plot3d mouse rotation style adjustable (various styles); 
addresses Issue #28408; an attempt to improve on PR #28236.
- matplotlibrc: add axes3d.mouserotationstyle and axes3d.trackballsize
- lib/matplotlib/rcsetup.py: add validation for axes3d.mouserotationstyle and axes3d.trackballsize
- axes3d.py: implement various mouse rotation styles
- update test_axes3d.py::test_rotate()
- view_angles.rst: add documentation for the mouse rotation styles
- update next_whats_new/mouse_rotation.rst
It also incorporates some of the improvements proposed in PR #28236; what it does not include (yet) is the introduction of `np.clip()` to circumvent [floating point round-off errors on the macos github CI runners](https://github.com/matplotlib/matplotlib/pull/28823#discussion_r1761351324).
- [N/A] …
> Make mplot3d mouse rotation style adjustable

- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_backend_gtk3.py
- lib/matplotlib/tests/test_backend_qt.py
- lib/matplotlib/tests/test_backends_interactive.py
- lib/matplotlib/tests/test_basic.py
- lib/matplotlib/tests/test_cbook.py
- lib/matplotlib/tests/test_collections.py
- lib/matplotlib/tests/test_colors.py
- lib/matplotlib/tests/test_legend.py
- lib/matplotlib/tests/test_pickle.py
I believe there must have been a dependency update in the last day or two that made mypy checks more strict, as Mypy Stubtest CI began failing with the below errors:
```
error: not checking stubs due to mypy build errors:
.tox/stubtest/lib/python3.12/site-packages/matplotlib/tests/test_basic.py:14: error: "type: ignore" comment without error code  [ignore-without-code]
.tox/stubtest/lib/python3.12/site-packages/matplotlib/tests/test_cbook.py:189: error: "type: ignore" comment without error code (consider "type: ignore[assignment]" instead)  [ignore-without-code]
.tox/stubtest/lib/python3.12/site-packages/matplotlib/tests/test_pickle.py:20: error: "type: ignore" comment without error code  [ignore-without-code]
.tox/stubtest/lib/python3.12/site-packages/matplotlib/tests/test_legend.py:405: …
```
> CI: Resolve mypy stubtest build errors

- lib/matplotlib/backends/backend_gtk4.py
In particular, I did not set them for figure_enter_event and figure_leave_event because gtk4 appears leave
controller.get_current_event() as None for them.
Closes #28962.
> Set guiEvent where applicable for gtk4.

- doc/users/next_whats_new/3d_clip_to_axis_limits.rst
- galleries/examples/mplot3d/axlim_clip.py
- lib/mpl_toolkits/mplot3d/art3d.py
I don't like the example I made that shows clipping to 3D axis limits in https://github.com/matplotlib/matplotlib/pull/27349. It's not clear which of the random points are actually supposed to be outside the axis limits. Switched the gallery example and what's new plot to a continuous function, which I think is easier to interpret.
Before:
After: …
> DOC / BUG: Better example for 3D axlim_clip argument

- galleries/examples/mplot3d/fillbetween3d.py
- galleries/examples/mplot3d/fillunder3d.py
https://github.com/matplotlib/matplotlib/pull/28568 missed some examples that were merged in after the PR was first opened. The fill_between examples are covered here, and the axlim_clip example is covered in this PR: https://github.com/matplotlib/matplotlib/pull/28984 …
> DOC: Add tags for 3D fill_between examples

- lib/matplotlib/lines.py
vertical lines (infinite slope) and two identical points as input need special handling in AxLine. The detection was using numeric tolerances, which lead to false-positive detection in cases that are close to but not exactly those special cases.
This PR removes the tolerances. The argument is the same as for the similar case https://github.com/matplotlib/matplotlib/issues/28386#issuecomment-2314629415
Closes #28870.
> Fix: Do not use numeric tolerances for axline special cases

- .github/workflows/cibuildwheel.yml
- .github/workflows/tests.yml
- azure-pipelines.yml
These are going away soon, so let's see how this works out.
https://github.com/actions/runner-images/issues/10721
This may be the last Intel macOS left now.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) …
> Switch macOS 12 runner images to macOS 13

- .github/workflows/cibuildwheel.yml
- .github/workflows/tests.yml
- azure-pipelines.yml
> Backport PR #28972 on branch v3.9.x (Switch macOS 12 runner images to macOS 13)

- environment.yml
#28617 introduced parallel gallery builds. This needs joblib as a dependency for sphinx-gallery. `requirements.txt` solves this via `sphinx-gallery[parallel]>=0.12.0`. Unfortunately, conda does not support variants, therefore we have to add the dependency explicitly to `environment.yml`.
> MNT: Add missing dependency to environment.yml

- lib/matplotlib/tests/test_path.py
- lib/matplotlib/tests/test_simplification.py
- src/path_converters.h
closes #17914
`PathSimplifier` should ignore vertices corresponding to `Path.CLOSEPOLY`, and rather replace them with the most recent `Path.MOVETO` vertex.
```
from matplotlib.path import Path
from matplotlib.patches import PathPatch
p = Path([(0, 0), (1, 0), (1, 1), (np.nan, np.nan)],
[Path.MOVETO, Path.LINETO, Path.LINETO, Path.CLOSEPOLY])
p = p.cleaned(simplify=True)
patch = PathPatch(p, facecolor="none", edgecolor="blue")
ax.add_patch(patch)
ax.set_xlim(-1, 2)
ax.set_ylim(-1, 2)
plt.show()
```
The Path should be closed.
- [N/A] *New Features* and *API Changes* …
> bugfix for `PathSimplifier`

- doc/install/dependencies.rst
- environment.yml
- meson.build
- pyproject.toml
This is necessary for the `py::mod_gil_not_used` tag. Note that this if fairly new, so we could go the other route and `#if` the tag.
See https://matrix.to/#/!BXmyZMTnRjWJldDRLV:gitter.im/$Bsyuv1YBdUjtHnJLP1jE7KjYdk5O6DVBzfG6giPd-D0?via=gitter.im&via=matrix.org&via=aria-net.org
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-fea …
> Bump required pybind11 to 2.13

- tox.ini
The repository in GHA is a shallow checkout (so to tags) so we are going to get the version wrong no matter what.  However, a recent change to our build dependencies (we think meson-python at 0.17) causes setumtools scm to fail to extract any version when installing from a generated sdist.
By setting a pretend version setuptools_scm will never try to look at git.  It is not yet clear if this fixes the sdist itself or just continues to use the pretend version when installing.
Debugged this on a call with @QuLogic and @ksunden 
To generate a checkout in a state that will fail use (in a container):
```bash
/usr/bin/git init /home/runner/work/matplotlib/matplotlib
cd /home/runner/work/matplotlib/matplotlib/
/usr/bin/git remote add origin https://github.com/matplotlib/matplotlib
/usr/bin/git …
```
> FIX: fake out setuptools scm in tox on ci

- environment.yml
- requirements/doc/doc-requirements.txt
This pull request updates the dependencies for building the documentation by adding PyStemmer to requirements/doc/doc-requirements.txt and environment.yml. The addition of PyStemmer is intended to improve the efficiency of Sphinx documentation builds by enabling stemming for search indexing. This change addresses the need for better search functionality in the generated documentation and may result in a performance improvement during the build process.
Relevant files updated:
requirements/doc/doc-requirements.txt
environment.yml
closes #28570
- [N/A] …
> Update requirements to add PyStemmer to doc-requirements and environment

- .github/workflows/tests.yml
- doc/install/dependencies.rst
- environment.yml
- meson.build
- pyproject.toml
- requirements/dev/build-requirements.txt
Update minimum pybind11 to 2.13.2 as use of 2.13.1 can cause mutex problems in Python 3.13 free-threaded builds, see pybind/pybind11#5420.
It would be good to confirm exactly which version of pybind11 was used to build the matplotlib 3.9.2 cp313t wheels on PyPI. They are dated Aug 13, the same date that pybind11 2.13.2 and 2.13.3 were released. So the mpl wheels could potentially have used 2.13.1 which would be bad. The GHA run that built and uploaded the wheel is https://github.com/matplotlib/matplotlib/actions/runs/10361240538/job/28683177700 but it is not verbose enough to including the pybind11 version used.
> Update minimum pybind11 to 2.13.2

- lib/matplotlib/colorbar.py
- lib/matplotlib/colorbar.pyi
- lib/matplotlib/tests/test_colorbar.py
As discussed in https://github.com/matplotlib/matplotlib/issues/26896 exposing a long_axis property for colorbar.
> ENH: add long_axis property to colorbar

- lib/matplotlib/colors.py
The docstring was copied from ColormapRegistry, but using `cmap` in the example is misleading.
> DOC: Fix copy-paste typo in ColorSequenceRegistry

- galleries/examples/images_contours_and_fields/contour_demo.py
- galleries/examples/images_contours_and_fields/contour_label_demo.py
- galleries/examples/misc/demo_agg_filter.py
`inline=True` ("break the contour lines under the labels) is already the default.
> Don't pass redundant inline=True to example clabel() calls.

- lib/matplotlib/backends/_backend_gtk.py
The method is deprecated, and according to docs should just not be used: https://docs.gtk.org/gtk3/method.Window.set_wmclass.html
The docs suggest gtk_window_set_role(), but AFAICS this is only helpful if one want to place the window in a certain position when restarting a session. I assume we don't want/need that.
This might also resolve this test failure https://github.com/matplotlib/matplotlib/pull/27766#issuecomment-2422998894 - t.b.c.
> FIX: Don't set_wmclass on GTK3

- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_figure.py
Closes #29011
`figure.automft_xdate` is a bit of a weird method, that labels outer labels on a subplotgrid in a figure and turns the labels 30 degrees (or more). 
However, before this PR it only did so if all the axes on the figure had a subplotspec. 
By default, colorbars have a subplotspec, so old layout managers worked fine.  However, colorbars in constrained layout are _not_ created with a subplotspec (`colorbar(usegridspec=False)`), so autofmt_xdate would not do anything.
This just checks if an axes is labeled with '<colorbar>' or not, and if so, ignores if for the sake of determining if autofmt_xdate can work or not.  It also doesn't try to do suplots_adjust if the engine is constrained layout as that is incompatible.
> FIX: auto_fmtxdate for constrained layout

- doc/api/next_api_changes/deprecations/28946-TH.rst
- lib/matplotlib/pyplot.py
Before, we only issued a warning. But we clearly cannot fulfill the intention of a polar plot and therefore we should error out instead of just warn.
Also document that `polar()` should typically be called first to prevent having a non-polar Axes already created.
Closes #28944.
> MNT: Deprecate plt.polar() with an existing non-polar Axes

- lib/matplotlib/backend_bases.py
- lib/matplotlib/backend_bases.pyi
- lib/matplotlib/backends/_backend_tk.py
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_gtk4.py
- lib/matplotlib/backends/backend_qt.py
- lib/matplotlib/backends/backend_webagg_core.py
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/backends/web_backend/js/mpl.js
- src/_macosx.m
Previously, for motion_notify_event, `event.attribute` was set by checking the last button_press_event/button_release event.  This is brittle for the same reason as to why we introduced `event.modifiers` to improve over `event.key` (#23473), so introduce the more robust `event.buttons` (see detailed discussion in the attribute docstring).
For a concrete example, consider e.g.
from matplotlib.backends.qt_compat import QtWidgets
def on_button_press(event):
if event.button != 3:  # Right-click.
return
menu = QtWidgets.QMenu()
menu.addAction("Some menu action", lambda: None)
menu.exec(event.guiEvent.globalPosition().toPoint())
fig.canvas.mpl_connect("button_press_event", on_button_press)
fig.add_subplot()
plt.show()
(connecting a …
> Stop relying on dead-reckoning mouse buttons for motion_notify_event.

- src/_macosx.m
We want to defer back to Python's native input hook handling when we don't have any figures to interact with, otherwise our runloop will continue running unecessarily.
Additionally, we need to add a short runloop burst in our hotloop to avoid saturating the CPU while waiting for input. (i.e. sitting on an idle figure would keep 100% cpu while waiting for an input() event without this runloop trigger).
closes #28960 …
> FIX: macos: Use standard NSApp run loop in our input hook

- lib/matplotlib/ticker.py
The x < 1 and x > 10000 branches can come together.
> Factor out common formats strings in LogFormatter, LogFormatterExponent.

- environment.yml
Follow on to #28779 applying the change to environment.yml so that docs will build in the conda environment.
> DOC/TST: lock numpy<2.1 in environment.yml

- lib/matplotlib/animation.py
For animations, #21831 added pre-compositing to white in order to fix odd results when outputting video formats which didn't support transparency. Unfortunately, this meant that formats that _did_ support transparency would no longer be transparent.
This PR disables that pre-compositing when a valid format is found. Currently, this means _anything_ written by Pillow (with the trust that it will correctly "fix" the transparency for formats that don't work), and APNG, AVIF, GIF, WebM, and WebP for ffmpeg/imagemagick. I also added a cutout for `.mov`+`codec='png'` because of https://github.com/matplotlib/matplotlib/issues/27173#issuecomment-2203801082, but Firefox doesn't seem to support that, so couldn't test it. It's possible there are some other codecs that should also be allowed here …
> Fix saving animations to transparent formats

- galleries/examples/images_contours_and_fields/multi_image.py
This PR  fixes the indentation in the `sync_cmaps` example in the "Advanced: Additionally sync the colormap" docs.
> [DOC] Fix indentation in sync_cmaps example

- doc/devel/contribute.rst
- doc/devel/development_setup.rst
- doc/devel/development_workflow.rst
- doc/devel/pr_guide.rst
Feedback from @juanis2112 at Scipy sprints was that the [workflow overview](https://matplotlib.org/devdocs/devel/contribute.html#how-to-pull-request) in the contributing guide was confusing because it required hopping out to [install docs](https://matplotlib.org/devdocs/devel/development_setup.html) and [workflow docs](https://matplotlib.org/devdocs/devel/development_workflow.html) which had overlapping material, so then it was unclear what/when to come back to the contribute: workflow docs for.
This PR:
* integrates the content from the workflow section into the overlapping install/workflow docs sections. 
* A lot of the content was repeated across contribute and install/devel and was geared towards the same audience, so I mostly chose whichever I thought was more explicit/clearer. 
* …
> DOC: integrated pr workflow from contributing guide into install and workflow

- galleries/examples/images_contours_and_fields/image_demo.py
Replaced colormap from RdYlGn to RdYlBu for colorblindness.
> DOC: Replaced colormap for colorblindness

- lib/matplotlib/backends/backend_gtk3agg.py
Reading through the code I found it weird that the backend export class is called "Cairo" within the "Agg" section, I think this was just a typo originally in https://github.com/matplotlib/matplotlib/pull/8773. The actual monkeypatching happens based on the module name,
https://github.com/matplotlib/matplotlib/blob/0b6222b7ffe2ab479c59d90a7b6c83257d8bccc7/lib/matplotlib/backend_bases.py#L3562
not this class so we were using the proper Agg/Cairo renderers as expected. This just helps with naming consistency when looking through the code.
> FIX: Update GTK3Agg backend export name for consistency

- lib/matplotlib/artist.py
The primary property name was given as link and code-formatted but the aliases were plain-text.
This PR adds consistent formatting to the aliases as well, <s>but still does not link them (by setting the `!` prefix).</s>
> DOC: Format aliases in kwargs tables

- lib/matplotlib/axes/_axes.py
changed violin to violinplot in See Also section to correctly reference the violinplot method.
Currently, it incorrectly references to the same violin method while the description references violinplot method.
> DOC: fix link in See Also section of axes.violin

- src/_macosx.m
closes #29045
Adds bit mapping for forward and back buttons on mouse
> ENH: add back/forward buttons to osx backend move

- lib/matplotlib/meson.build
This was missed in #20866
We should not include a stub file for a removed c-extension
> MNT: remove _ttconv.pyi

- galleries/examples/pie_and_polar_charts/nested_pie.py
This makes it clearer that we are just indexing into a list of colors. Calling cmaps with an integer argument is somewhat obscure and we want to move away from this. See also #28198.
> DOC: Switch nested pie example from cmaps to color_sequences

- lib/matplotlib/colors.py
Primary motivation was to remove the N parameter to ListedColormap (in preparation of its deprecation
https://github.com/matplotlib/matplotlib/issues/28763#issuecomment-2322791660).
That parameter is not needed here because
`len(colors[color_slice]) == n_data_colors)`, otherwise the ValueError above would have raised.
Hopefully, this is overall more readable.
> MNT: Refactor matplotlib.colors.from_levels_and_colors()

- lib/matplotlib/tests/test_backends_interactive.py
Works around the failure #29129. A proper analysis and resolution is still needed.
> MNT: Temporarily skip failing test to unbreak CI

- galleries/tutorials/artists.py
This pull request addresses [issue #28920](https://github.com/matplotlib/matplotlib/issues/28920) by updating the `galleries/tutorials/artists.py` file to allow suppressing missing references using a `!` prefix, rather than the `missing_references` extension.
> Updates the `galleries/tutorials/artists.py` file in response to issue #28920

- lib/matplotlib/backend_bases.py
- lib/matplotlib/backend_bases.pyi
- lib/matplotlib/tests/test_backend_bases.py
- lib/mpl_toolkits/mplot3d/tests/test_axes3d.py
Sometimes, the mouse_release_event ending a pan/zoom can be lost, if it occurs while the canvas does not have focus (a typical case is when a context menu is implemented on top of the canvas, see example below); this can result in rather confusing behavior as the pan/zoom continues which no mouse button is pressed.  To fix this, always check that the correct button is still pressed in the motion_notify_event handlers.
To test, use e.g.
```
from matplotlib.backends.qt_compat import QtWidgets
def on_button_press(event):
if event.button != 3:  # Right-click.
return
menu = QtWidgets.QMenu()
menu.addAction("Some menu action", lambda: None)
menu.exec(event.guiEvent.globalPosition().toPoint())
fig.canvas.mpl_connect("button_press_event", …
```
> Check pressed mouse buttons in pan/zoom drag handlers.

- lib/matplotlib/tests/test_backend_bases.py
- lib/mpl_toolkits/mplot3d/tests/test_axes3d.py
The same events can be indiscriminately sent to test panning and zooming, and just calling _process() on the events actually tests a bigger part of the pipeline than calling specifically {press,drag,release}_{pan,zoom}.
Followup to #29066.
> Simplify synthetic event generation in interactive pan/zoom tests.

- doc/api/next_api_changes/deprecations/29135-TH.rst
- lib/matplotlib/cbook.py
- lib/matplotlib/cbook.pyi
- lib/matplotlib/colors.py
- lib/matplotlib/contour.py
- lib/matplotlib/tests/test_cbook.py
- lib/matplotlib/tests/test_colors.py
Truncating or repeating the given colors to a specific value of N is not within the scope of colormaps. Instead, users should create an appropriate color list themselves and feed that to ListedColormap.
Also the current behavior can be surprising: It may well be that a given N was intended to truncate, but depending on the list, it could repeat. Repeated colors in a colormap are dangerous / often not intentended because they create an ambiguity in the color -> value mapping.
> Deprecate ListedColormap(..., N=...) parameter

- .github/workflows/cibuildwheel.yml
- .github/workflows/cygwin.yml
- .github/workflows/tests.yml
This includes updates to `actions/attest-build-provenance`, `pypa/cibuildwheel`, `pypa/gh-action-pypi-publish`, `deadsnakes/action`, and cleanup of `workflow_dispatch` and outdated skips. …
> Backport CI config updates to v3.9.x

- .github/workflows/tests.yml
- azure-pipelines.yml
This works around https://github.com/actions/runner-images/issues/10984 …
> ci: Remove outdated pkg-config package on macOS

- galleries/examples/subplots_axes_and_figures/secondary_axis.py
Closes #29067
Fixes a small [issue](https://github.com/matplotlib/matplotlib/issues/29067) with the secondary_axis tutorial where the interpolation from one axis to the other needs to be defined outside the bounds of the data that is plotted. This was previously noted in the tutorial but was not implemented correctly. The example in question has been simplified and updated so that the secondary axis is correctly derived from the primary axis.
- [ N/A] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
> Update secondary_axis tutorial

- lib/matplotlib/axis.py
- lib/matplotlib/tests/test_units.py
Allow sub/superclass without warning.
This was motivated by Pandas, as they have several instances of the same class in the registry.
We also had this internally, though resolved that by using the same instance for multiple registry
entries rather than by relaxing the warning. This becomes impractical when dealing with downstream.
It may have been sufficient to allow only identical types, but to be safe, decided to allow both
sub- and superclass relationships.
The purpose of the warning was that it gets overwritten without heeding prior data provided which
would break in unexpected ways.
The most common case for this is when one converter class operates on multiple data types, but
separate instances of the class are in the registry. So while the previous data is compatible the
equality …
> Relax conditions for warning on updating converters

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
The new parameter, 'orientation', was only added in the current release, so downstream wanting to avoid warnings
would require version gates. Therefore delaying by at least one release to ease the transition.
This was motivated by Pandas failing tests on this warning.
> Delay warning for deprecated parameter 'vert' of box and violin

- lib/matplotlib/backends/qt_editor/figureoptions.py
Currently, opening the Qt figureoptions UI for an image whose cmap is not registered in the colormap registry, has a name not matching any registry entry, but is actually equal (`==`, i.e. has the same LUT and colorbar-extension attributes) to a registry entry, leads to an error. A typical example would be
```
import cmap, pylab as p  # third-party
p.imshow([[0, 1]], cmap=cmap.Colormap("bids:magma").to_mpl())
```
and opening the qt figure options; this leads to the error "index 'bids:magma' is invalid ...".
Note that if the cmap is different from any registered cmap then we already add it to the UI combobox (try e.g. `cmap=cmap.Colormap("imagej:fire")`); the only problem was if it was equal to a registered cmap (this arises because when the code was originally written, cmap instance …
> Don't fail on equal-but-differently-named cmaps in qt figureoptions.

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/PULL_REQUEST_TEMPLATE.md
- doc/devel/contribute.rst
I am not going to link to the issues or comments that inspired me to write this.  We are starting to see comments that look like the are the output from feeding the OP of an issue in to an ai assitant and at least one bug report that was "chatGPT said this should work but it does not".
I think that users who report bugs with us should expect to get feedaback from an expert human and I do not think we should be spending time doing user support for openAI.
I thought about included a sentence to the effect of "We obviously can't stop you from using them, but please rewrite it in your own words" but did not like any of the formulations I came up with.
I do not think asking people who use LLMs to generate comments/issues to attribute addresses the actual problem and is insufficient.
> DOC: do not posting LLM output as your own work

- .appveyor.yml
Upstream has updated their links, and the latest should have a fix for the error we were seeing. …
> ci: Unpin micromamba again

- lib/matplotlib/backends/backend_qt.py
This PR passes the `parent` of an initialised `SubplotToolQt` to its inherited `__init__`.
It is missed here, but not on other classes.
> Update backend_qt.py: parent not passed to __init__ on subplottool

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
The new parameter, 'orientation', was only added in the current release, so downstream wanting to avoid warnings
would require version gates. Therefore delaying by at least one release to ease the transition.
This was motivated by Pandas failing tests on this warning.
This portion is made direct to v3.10.x with #29155 being the accompanying version to edit the deprecation on main.
> Pending warning for deprecated parameter 'vert' of box and violin on 3.10

- galleries/users_explain/text/text_intro.py
I have made a few minor improvements in the text intro explainer, including the incorrect notation of units within square brackets (my personal pet peeve).
> Minor fixes to text intro explainer

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
These should be equal, but they are not on master:
```python
fig_test = plt.figure()
fig_ref = plt.figure()
x = np.arange(4)
y = np.arange(7)
X, Y = np.meshgrid(x, y)
C = X + Y
ax = fig_test.subplots()
ax.pcolormesh(C, shading="nearest")
ax = fig_ref.subplots()
ax.pcolormesh(x, y, C, shading="nearest")
plt.show()
```
On main the first figure is
and the second figure is 
With this change they are both the same, and look like the second figure. 
Closes https://github.com/matplotlib/matplotlib/issues/29179
> FIX:  pcolormesh with no x y args and nearest interp

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
This PR introduces the `_parse_bar_color_args function`, which provides consistency in color bar arguments by establishing a parameter precedence, "similar" to the one used in `scatter`:
facecolor: facecolor -> color -> 'b' if in classic mode else the result of `get_next_color_func()`
edgecolor: edgecolor -> color -> None
This ensures that when edgecolors is not explicitly defined, it tries color. Additionally, this change allows facecolor to accept sequences of colors, ensuring consistency in argument handling, as issued in #29090. The tests are consistent with examples in #29072.
**Examples:**
- `plt.bar([1, 2, 3], [1, 2, 3], color=['none', 'C2', 'none'], edgecolor=['C1', 'C2', 'C3'])`
- `plt.bar([1, 2, 3], [1, 2, 3], color=['none', 'C2', 'none'])`
- `plt.bar([1, 2, 3], [1, 2, 3]) …
> Creating_parse_bar_color_args to unify color handling in plt.bar with precedence and sequence support for facecolor and edgecolor

- lib/matplotlib/axis.py
Fix a typo in the comment of _LazyTickList class where "lis" was written instead of "list".
To improve code documentation clarity and fix incorrect spelling.
Corrects a spelling mistake in the comments that could cause confusion.
Simple text correction from 'lis' to 'list' to maintain proper documentation.
- [N/A] "closes #0000" - no related issue
- [N/A] *Plotting related* features are demonstrated in an example
- [N/A] *New Features* and *API Changes* are noted with a directive and release note
> Fix typo in _LazyTickList class comment (lis -> list)

- doc/_static/switcher.json
The merge will probably go `v3.9.x` -> `v3.10.x` -> `main`, and I don't want to wait that long to ensure that the stable docs don't have the "unstable" banner.
- [n/a] …
> DOC: Set stable version to 3.9.3

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Within the `_interp_grid function`, unnecessary warnings may be triggered when expanding the grid coordinates. As long as the X coordinates and Y coordinates remain monotonic in their respective directions, negative area grids can be avoided. Therefore, the `require_monotonicity` keyword has been added to avoid triggering monotonicity warnings indiscriminately when calling the function.
Running the following code on the original code before modification will trigger warnings, but the drawn grid is normal because the X and Y coordinates are monotonically increasing in their respective directions. Therefore, I think warnings should not be triggered in this case.
```Python
x = np.linspace(0, 3, 7)  
y = np.linspace(0, 5, 11)
X, Y = …
```
> avoid-unnecessary-warning-in-_pcolorargs-function

- lib/matplotlib/tests/test_backends_interactive.py
wxPython does not support pure Wayland systems (though wxGTK would be fine with it). This was only fixed in https://github.com/wxWidgets/Phoenix/pull/2638 which is not in a release yet.
The cross-Qt tests also need a display since they are initializing their respective toolkits, and should be skipped without Wayland or X. …
> Skip more tests on pure-Wayland systems

- lib/matplotlib/tests/test_animation.py
The animation writers will put its temporary files in `TemporaryDirectory`, so there's no need to `chdir` to avoid polluting the current directory. Instead, just save directly to a temporary file name.
For the same reason, drop `test_cleanup_temporaries`, which is now just a test for the Python standard library.
Also, at some point, `pytest` will want to deprecate the `tmpdir` fixture, so switch to `tmp_path`.
- [n/a] *New Features* and *API Changes* are …
> TST: Simplify parts of animation tests

- galleries/examples/images_contours_and_fields/image_exact_placement.py
New example showing a couple of methods for dealing with images that you want to keep the same _reelative_ size.
> DOC: manually placing images example

- lib/matplotlib/category.py
- lib/matplotlib/patches.py
- lib/matplotlib/tests/test_patches.py
- lib/matplotlib/tests/test_units.py
This PR lets connection patch use the convertor info from the axes that's already being passed in for "data" to support unitized data. I think the original behavior is a bug b/ the original code called the artist convertors but they didn't do anything b/c the artist convertors are looking up the artist axes which doesn't exist b/c connection patch is a figure level artist.
Modifies string convertor to return a scaler when input is only one value b/c that's what the connection patch transform function expects. This is inspired by the datetime convertor, which already behaves this way. 
Updated summary based on @QuLogic's review to reflect current implementation/behavior.
This PR is motivated by the following code, which on main draws the respective plots but crashes at rendering the …
> BUGFIX: use axes unit information in ConnectionPatch 

- lib/matplotlib/pyplot.py
Closes #29227 
As detailed in https://github.com/matplotlib/matplotlib/issues/29227#issuecomment-2522782159:
> I very much believe plt.show() should be added here:
> 
> - This is a first-point-of-contact example. We shouldn't expect that readers are fiamiliar with the details when show() is necessary or not.
> This is an otherwise complete and working example, including imports and data. As the OP noted it is surprising if this does not generate any output by default.
> - The plotting workflow is 1. create a figure 2. add contents 3. output the figure. We shouldn't leave out the third step. Since this is not the place to discuss all aspects of figure output (you could use savefig() instead of show(), jupyter has an auto-show, etc.) using plt.show() is a good default choise for output.
> DOC: Add plt.show() to introductory pyplot example

- environment.yml
Closes #29241 by improving the comment which explains how to up the dev environment using conda. 
Update comment describing conda dev set up
- Update commented commands in environment.yml to match
the command in development_setup.rst
- This version of the command does not cause issues with
zsh (due to the quotation marks).
> Add quotes around [dev] in environment.yml

- lib/matplotlib/axis.py
- lib/matplotlib/tests/test_axis.py
Hi. This fixes a bug in `_translate_tick_params` where some keys are not being mapped correctly with `reverse=True` and `cls.axis_name = 'x'`. 
For example, both 'left' and 'bottom' are mapped to 'tick1On', making the reverse ambiguous. 
Separated from #28968 because this is an independent bug.
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-depreca …
> [Bug Fix] Fix reverse mapping for _translate_tick_params

- .github/workflows/cibuildwheel.yml
- .github/workflows/circleci.yml
- .github/workflows/clean_pr.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/conflictcheck.yml
- .github/workflows/cygwin.yml
- .github/workflows/do_not_merge.yml
- .github/workflows/good-first-issue.yml
- .github/workflows/labeler.yml
- .github/workflows/mypy-stubtest.yml
- .github/workflows/pr_welcome.yml
- .github/workflows/reviewdog.yml
- .github/workflows/stale-tidy.yml
- .github/workflows/stale.yml
- .github/workflows/tests.yml
This applies suggestions from [`zizmor`](https://woodruffw.github.io/zizmor/) to increase the security of the Actions workflows. Currently, we can almost pass the "auditor" persona (the strictest) except for:
- "expression may expand into a self-hosted runner", but we don't have any self-hosted runners, so this is a false positive.
- "pull_request_target is almost always used insecurely", but we do not a) use user-controlled target substitutions, nor b) run any code from the checkout. So I believe these are safe as nothing user-controlled can be injected.
I do not believe we have any glaring security holes here, but this PR just avoids any cause for concern from auditing. …
> Zizmor audit

- .gitignore
The commit adds venv/ to the .gitignore file to prevent the tracking of Python virtual environments so only relevant project files are committed.
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https//matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [N/A] Documentation complies …
> added venv to gitignore

- subprojects/packagefiles/freetype-2.6.1-meson/src/gzip/zconf.h
Freetype 2.6.1 has an outdated copy of a zlib header (like from ~1998) which has a bad check for choosing whether to define Byte on macOS. This adds a patched version of the zconf.h header that has a proper check for __MACTYPES__, which is defined by the macOS SDK.
For posterity, the failure occurred over on conda-forge and looked like:
```
FAILED: subprojects/freetype-2.6.1/libfreetype.a.p/src_gzip_ftgzip.c.o 
x86_64-apple-darwin13.4.0-clang -Isubprojects/freetype-2.6.1/libfreetype.a.p -Isubprojects/freetype-2.6.1 -I../subprojects/freetype-2.6.1 -I../subprojects/freetype-2.6.1/include -fvisibility=hidden -flto -fdiagnostics-color=always -DNDEBUG -Wall -Winvalid-pch -O3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem …
```
> Fix building freetype 2.6.1 on macOS clang 18

- lib/mpl_toolkits/mplot3d/art3d.py
- lib/mpl_toolkits/mplot3d/tests/test_art3d.py
closes issue #29156 
- [ N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines
> addressing issue #29156, converted ps to array before slicing

- lib/mpl_toolkits/mplot3d/art3d.py
- lib/mpl_toolkits/mplot3d/tests/test_art3d.py
https://github.com/matplotlib/matplotlib/pull/29175 accidentally targeted the `v3.9.x` branch instead of `main`, retargeting.
Closes https://github.com/matplotlib/matplotlib/issues/29156
I think only one review needed for this one.
> Retarget PR#29175 to main

- pyproject.toml
This is currently dropping scalable SVG symlinks, which breaks the toolbar on GTK.
Fixes #29229
> BLD: Pin meson-python to <0.17.0

- .github/workflows/cibuildwheel.yml
- cibuildwheel runs builds in a container, so there's no need to pin the runner to old `ubuntu-20.04`, which will be EOL early next year.
- cibuildwheel is warning about using other variables than `CIBW_ENABLE`, so switch to that.
- All dependencies should have Python 3.13 wheels now, so we won't need the nightly builds.
- kiwisolver has a PyPy 3.10 wheel, so we don't need that workaround any more. …
> Update cibuildwheel workflow

- galleries/users_explain/colors/colormaps.py
Fixes #29312.  The footnote syntax seems not to like spaces so I swapped them for hyphens, consistent with the [kovesi-colormaps] footnote.
> DOC: fix footnote in choosing colormaps guide

- lib/matplotlib/legend.py
- lib/matplotlib/tests/test_legend.py
Fixes #29301.
The problem was that `FigureCanvasPS._print_figure` essentially got into a loop of calling itself: somewhere within [figure.draw](https://github.com/matplotlib/matplotlib/blob/28f69ba98708393deb0f35501940f40b0f081504/lib/matplotlib/backends/backend_ps.py#L1050) we needed to call `figure._get_renderer` in order to calculate the annotation window extent and therefore the legend position.  `_get_renderer` ultimately calls `FigureCanvasPS._print_figure` again.  I haven't quite followed why, but by the time we get to the end of `FigureCanvasPS._print_figure`, [_ps_writer](https://github.com/matplotlib/matplotlib/blob/28f69ba98708393deb0f35501940f40b0f081504/lib/matplotlib/backends/backend_ps.py#L1102) which should contain all the information about the artists is empty.
We can …
> FIX: pass renderer through `_auto_legend_data`

- galleries/users_explain/artists/transforms_tutorial.py
AFAICS, there is no place in the library where the coordinate systems are used as strings. - Please correct me if I'm wrong. - I've changed to emphasis to keep a special format in the sense of a technical term, but we could also remove special highlighting totally.
> DOC: Don't put quotes around coordinate system names

- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_backends_interactive.py
Closes #23770. Starting an ipython session with InteractiveShell led to a crash with NotImplementedError being raised. An ImportError needed to be raised from that, allowing for continuation with a different backend. 
[N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
[N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
[N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines
> Adds error handling around install_repl_displayhook

- doc/devel/min_dep_policy.rst
Side-note: We haven't increased the NumPy version.
> DOC: List min. Python version for Matplotlib 3.10

- .github/workflows/tests.yml
Pandas appears to no longer be uploading py310 on intel wheels to the nightly index.
closes #29327
> CI: allow pandas install to fail on nightly test run

- doc/api/next_api_changes/behavior/29054-AL.rst
- lib/matplotlib/tests/test_ticker.py
- lib/matplotlib/ticker.py
In general, avoiding axis with a single labeled tick seems to be a good idea.  Previously, a log axis spanning from 4 to 60 would have its minor ticks unlabeled, LogFormatter making that choice based on the fact that the axis spans more than one decade (60/4>10).  Instead, change the interpretation of the first item in `minor_thresholds` to label the minor ticks (by default) if there is only one (or zero) major tick drawn (as is the case for the above axis limits).
Closes #29050, but probably needs to be discussed as that's technically an API break.  However, note that this doesn't break any test and I suspect that this case may have been missed previously (I added a test for it).
> Label log minor ticks if only one log major tick is drawn.

- lib/mpl_toolkits/axisartist/floating_axes.py
- lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
- lib/mpl_toolkits/axisartist/tests/test_floating_axes.py
grid_helper_curvelinear and floating_axes have code to specifically handle the case where the transform from rectlinear to non-rectilinear axes has null derivatives in one of the directions, inferring the angle of the jacobian from the derivative in the other direction.  (This angle defines the rotation applied to axis labels, ticks, and tick labels.)
This approach, however, is insufficient if the derivatives in both directions are zero.  A classical example is e.g. the ``exp(-1/x**2)`` transform, for which all derivatives are zero.  To handle this case more robustly (and also to better encapsulate the angle calculation, which is currently repeated at a few places), instead, one can increase the step size of the numerical differentiation until the gradient becomes nonzero.  This amounts …
> Improve handling of degenerate jacobians in non-rectilinear grids.

- doc/api/next_api_changes/deprecations/27551-AL.rst
- lib/mpl_toolkits/axisartist/angle_helper.py
- lib/mpl_toolkits/axisartist/axislines.py
- lib/mpl_toolkits/axisartist/floating_axes.py
- lib/mpl_toolkits/axisartist/grid_finder.py
- lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
While Matplotlib normally represents lists of (x, y) coordinates as (N, 2) arrays and transforms (which we'll call "trans") have shape signature (N, 2) -> (N, 2), axisartist uses the opposite convention of using (2, N) arrays (or size-2 tuples of 1D arrays) and transforms (which it typically calls "transform_xy").  Change that and go back to Matplotlib's standard represenation in some of axisartist's internal representations for consistency.  Also replace some uses of (x1, y1, x2, y2) quadruplets by single Bbox objects, which avoid having to keep track of the order of the points (is it x1, y1, x2, y2 or x1, x2, y1, y2?).
- Add a `_find_transformed_bbox(trans, bbox)` API to ExtremeFinderSimple and its subclasses, replacing `__call__(transform_xy, x1, y1, x2, y2)`. (I intentionally did not …
> Move axisartist towards untransposed transforms (operating on (N, 2) arrays instead of (2, N) arrays).

- lib/matplotlib/backends/backend_qt.py
This PR adds `QtCore.Slot` decorations to the methods in `FigureCanvasQT`. (It is similar to #27215)
The motivation for this PR was found due to https://github.com/pyqtgraph/pyqtgraph/pull/3205, which can be summarized as: when tests are run with `pytest-qt` installed, a `QtWarningMsg` will be emitted concerning non-decorated methods used as slots.
- [N/A] *New …
> Add QtCore.Slot() decorations to FigureCanvasQT

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/cm.py
- lib/matplotlib/contour.py
- lib/matplotlib/figure.py
- lib/matplotlib/font_manager.py
- lib/matplotlib/image.py
- lib/matplotlib/legend.py
- lib/matplotlib/lines.py
- lib/matplotlib/markers.py
- lib/matplotlib/offsetbox.py
- lib/matplotlib/patches.py
- lib/matplotlib/streamplot.py
- lib/matplotlib/texmanager.py
- lib/matplotlib/text.py
- lib/matplotlib/ticker.py
- lib/mpl_toolkits/axisartist/axisline_style.py
- lib/mpl_toolkits/mplot3d/axes3d.py
In some cases where the variable was not used again, I assigned directly to the final variable/attribute. But most of the changes are to the same variables.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) …
> Use _val_or_rc in more places

- lib/matplotlib/axis.py
Closes #29284 following the suggestion at https://github.com/matplotlib/matplotlib/issues/29284#issuecomment-2536856135.
> Expand set_ticklabels warning

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Fixes #25274.  The final figure using that code example now looks like
When `add_container` is called, the container [gains the removal method](https://github.com/matplotlib/matplotlib/blob/df49afcdbeacfce25256376dc95841ab41f05424/lib/matplotlib/axes/_base.py#L2508) which then [gets called within `Container.remove`](https://github.com/matplotlib/matplotlib/blob/df49afcdbeacfce25256376dc95841ab41f05424/lib/matplotlib/container.py#L29-L30).
Thanks to @Higgs32584 for the [debugging notes](https://github.com/matplotlib/matplotlib/issues/25274#issuecomment-1483924628), which got me there a lot faster.
- [n/a] *New Features* and *API Changes* are …
> FIX: add errorbars with `add_container`

- doc/devel/development_setup.rst
I've stumbled over this when reading the instructions. While this is in the section "Install external dependencies", I was unclear whether that link would go to / cover the whole doc dependencies. Stating that these are only the "external tools for the documentation build" is a bit clearer.
> DOC: Clearer wording for the installation of external dependencies

- lib/matplotlib/backends/backend_gtk4.py
`get_current_event()` calls within pygobject would cause segfaults. This was fixed in 3.47, so gate the guiEvent information to only access that method in versions that don't segfault.
closes #29350
> FIX: Add version gate to GTK4 calls when necessary

- lib/matplotlib/colors.py
- lib/matplotlib/tests/test_colors.py
* Update check of whether a color has an alpha channel to include hexadecimal and color/alpha tuple formats.
* Add test of the new formats
* Add method to check whether a sequence of colors has an alpha channel
For more explanation see the matplotlib page on [specifying colors](https://matplotlib.org/stable/users/explain/colors/colors.html).
> Update for checking whether colors have an alpha channel

- lib/matplotlib/tests/test_axes.py
This change fixes the test case failing on ppc64le architecture.
This change will pass all the test cases on power.
This change is implemented as required architecture was not specified in the test case.
> Fixed test case(test_axes.py) failing on ppc64le

- lib/matplotlib/axis.py
- lib/matplotlib/tests/test_axis.py
Closes #21337 by ignoring major/minor ticks, if they are not used because of a NullLocator.
> FIX: get_tick_position() should disregard major/minor ticks that are not drawn

- doc/sphinxext/gallery_order.py
- galleries/examples/scales/scales.py
- replace the second "function" scale example by "asinh". We do not need two "function" scale examples, and "asinh" is worth noting.
- simplify code (use linear y instead of random almost linear y, use set_yticks() instead of a locator, ...)
- Move to first place in the gallery section
> DOC: Update scales overview

- doc/api/next_api_changes/behavior/29256_IMT.rst
- lib/matplotlib/backends/backend_webagg_core.py
Closes #29256.
Previously when using the `webagg` backend if you wanted to change the title above a figure you would use `figure.set_label('whatever')` and if you used `figure.canvas.manager.set_window_title('whatever')` it would be ignored. This was inconsistent with other backends which use the latter.
This PR changes the behaviour so that `figure.canvas.manager.set_window_title('whatever')` is used now for `webagg`, the same as the other backends.
There is no test as there isn't currently any visual testing of the `webagg` backend. There is some draft work underway in #23540 for this. So here is a demonstration instead, using this code:
```python
mpl.use('webagg')
fig1, ax1 = plt.subplots(figsize=(3, 2))
ax1.plot([1, 3, 2, 4]) …
```
> Use set_window_title rather than set_label to set title of webagg figure

- lib/matplotlib/patches.py
- lib/matplotlib/tests/test_patches.py
Fixes a regression introduced in #28104 (cc @timhoffm @Impaler343 ):
```
>>> import numpy as np
>>> import matplotlib.patches
>>> rect = matplotlib.patches.Rectangle([0, 0], 1, 1)
>>> rect.set_hatchcolor(np.zeros(3))
File "<stdin>", line 1, in <module>
File "/home/larsoner/python/matplotlib/lib/matplotlib/patches.py", line 445, in set_hatchcolor
self._set_hatchcolor(color)
File "/home/larsoner/python/matplotlib/lib/matplotlib/patches.py", line 428, in _set_hatchcolor
if color == 'edge':
^^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
> BUG: Fix regression with set_hatchcolor

- lib/matplotlib/axes/_base.py
- lib/matplotlib/axes/_base.pyi
The axes (`self.xaxis`, `self.yaxis`) as well as their names (`self._axis_names`) cannot be changed at run time. Therefore, we don't have to recompute the `_axis_map` on every access. Instead, we can do this once after `_init_axis()` and store the resulting dict.
> MNT: Turn Axes._axis_map into a static dict instead of a property

- .github/workflows/tests.yml
Whatever used to require it seems to have dropped it, causing issues with wxPython on Ubuntu 20.04 now. …
> ci: Install libnotify4 on all Ubuntu

- lib/matplotlib/axes/_base.py
- lib/matplotlib/tests/test_axes.py
This PR fix #29410 Modifying Axes' position also alters the original Bbox object used for initialization.
Making a copy of the reference Bbox using its `.frozen()` method solves the problem.
> fix #29410 Modifying Axes' position also alters the original Bbox object used for initialization

- lib/matplotlib/artist.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/backend_mixed.py
- lib/matplotlib/colors.py
In agreement with our standard type descriptions
https://matplotlib.org/devdocs/devel/document.html#parameter-type-descriptions
> DOC: Use float instead for scalar for type descriptions in docstrings

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/collections.py
Coerce to our standard type descriptions
https://matplotlib.org/devdocs/devel/document.html#parameter-type-descriptions
> DOC: Fix type descriptions in fill_between docstring

- galleries/examples/scales/custom_scale.py
- lib/matplotlib/axis.py
- lib/matplotlib/scale.py
Today I spent way too long trying to wrap my head around why someone might write a custom scale.  I have updated the example with what I think I have understood.  Also updated the `set_[xy]scale` docstring as it was missing some built-in options, and I think we can be clearer about what happens to `**kwargs`.
> DOC: scales - built in options and custom scale usefulness

- galleries/users_explain/axes/legend_guide.py
Also made the background lighter, which IMHO looks more pleasing.
Old example: https://matplotlib.org/devdocs/users/explain/axes/legend_guide.html#legend-location
New: plot
> DOC: Add missing examples for legend outside positions

- doc/devel/development_workflow.rst
- galleries/examples/misc/multipage_pdf.py
- This pull request addresses the removal of a broken link in the doc/devel/development_workflow.rst and updates the content to improve clarity and accuracy.
- The original link to [why-the-flag?](https://gitready.com/beginner/2009/01/18/the-staging-area.html) was broken, and the resources are no longer available. 
- Resolving the issue by replacing "For more information, see [why the -a flag?](http://gitready.com/beginner/2009/01/18/the-staging-area.html) and the [git commit](https://git-scm.com/docs/git-commit) manual page." to "For more information, see the [git commit](https://git-scm.com/docs/git-commit) manual page."
Closes #29305.
- [N/A] *Plotting related* features are demonstrated in an …
> Fix dead links in dev workflow docs

- lib/matplotlib/ft2font.pyi
- src/ft2font_wrapper.cpp
By simply defining them if not available.
This fixes the latter half of https://github.com/matplotlib/matplotlib/issues/29396#issuecomment-2576910230 …
> ft2font: Avoid undefined enum values

- .github/workflows/tests.yml
- lib/matplotlib/tests/test_axes.py
Like the macOS jobs are mixed between Intel and ARM, this changes one of the Linux jobs to use ARM.
We'll see if we need to make any changes as in #24597 after the build is complete. …
> ci: Add an ARM Linux test workflow

- .github/workflows/cibuildwheel.yml
Now arm64 runners are in public preview: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/ This should run _much_ faster than emulated builds.
This PR does not enable testing as done in #24597, but we might consider it.
(Also removed the unused `MPL_DISABLE_FH4` environment variable since we moved to static linking.) …
> ci: Enable native ARM builders for wheels

- doc/devel/api_changes.rst
In https://github.com/matplotlib/matplotlib/pull/29152#issuecomment-2558390471 @rcomer flagged that the pending deprecation procedure wasn't documented, so I tried to write up what I inferred from her comment to be the procedure.
> Doc: document pending deprecation procedure

- doc/users/prev_whats_new/whats_new_3.10.0.rst
Adds a blurb for colorizer (#28658) in the what's new of 3.10) as requested in https://github.com/matplotlib/matplotlib/pull/29442#pullrequestreview-2540818969:
@tacaswell @story645 
Screenshot of added blurb:
> DOC: Added blurb for colorizer objects in what's new for 3.10

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Closes #29484.
Note: There's precedence for a similar special-casing on polar Axes for errorbars: https://github.com/matplotlib/matplotlib/blob/3fb9c0961b5c8d5753c88ac37c08cda58a4b7839/lib/matplotlib/axes/_axes.py#L3798
> FIX: Make stem() baseline follow the curvature in polar plots

- lib/matplotlib/axes/_axes.py
The arrow() design is broken beyond repair. Even though we currently only have to offer `annotate` as a workaround, we should make the limitations more prominent then just a note and we should steer users away.
This is a a step towards deprecation (#20387). Unfortunately the discussion of a replacement has stalled (#22435) and we have to revive it later. But that shound not hold us from pointing out the flaws of arrow() more prominently.
> MNT: Discourage arrow()

- doc/devel/development_setup.rst
Currently the codespace instructions are a third tab next to setting up your python environment with either `venv` or `conda`.  This feels a bit out of place to me because the instructions are about more than just getting your python environment: they also include how to get an interactive gui or view the docs under codespaces.  Additionally, when you spin up a codespaces instance, your clone is already there, upstream is already set and all the non-python dependencies are in place.  So we can skip sections that are currently before and after the "create a dedicated environment" section.  The instructions themselves are unchanged, just moved from the tab to a new section.  I also added some brief guidance on why you might or might not want to choose codespaces.
Closes #29524
> DOC: better separation of codespace instructions

- lib/matplotlib/animation.py
- lib/matplotlib/tests/test_animation.py
Correct the variable name from `_frame` to `_frames` in the PillowWriter class to ensure proper functionality.
> FIX: Correct variable name from _frame to _frames in PillowWriter class

- doc/api/next_api_changes/deprecations/ 29529-TH.rst
- lib/matplotlib/rcsetup.py
The `*_or_None` validators have accepted any capitalization of the string "none" as input. This is overly permissive and will likely lead to conflicts in the future because we cannot distinguish between resolving to `None` and `"none"` which may be need for some parameters in the future.
Inspired by #29481.
> MNT: Deprecate other capitalization than "None" in matplotlibrc

- galleries/examples/style_sheets/plot_solarizedlight2.py
Closes #29535. There was a mistake in the [solarized style sheet example](https://matplotlib.org/devdocs/gallery/style_sheets/plot_solarizedlight2.html). There was a `* x` missing in one example plot line so it looked odd. Now it looks nicer. Its a really minor change.
> Fix typo in solarized example plot.

- lib/matplotlib/cbook.py
- lib/matplotlib/collections.py
- lib/matplotlib/path.py
- lib/matplotlib/tests/test_transforms.py
- lib/mpl_toolkits/mplot3d/art3d.py
- lib/mpl_toolkits/mplot3d/proj3d.py
This builds on https://github.com/matplotlib/matplotlib/pull/16793 to implement `__slots__` on Path objects, and to improve a lighter weight creation path. Relative to that MR, it does not modify the garbage collection on Paths, and adds a smattering of minor 3D rendering improvements. For a 200x200 plot_surface test case, I am seeing a 1.3x speedup after averaging over a few profiler runs, though note that this gives better performance over a much wider scope as well.
Relevant issue which this won't fully close: https://github.com/matplotlib/matplotlib/issues/16659
```python
import time
ax = fig.add_subplot(111, projection='3d')
x = y = np.linspace(-1, 1, 200)
X, Y = np.meshgrid(x, y)
Z = X ** 2 + Y ** 2 …
```
> Speed up Collection.set_paths

- doc/users/next_whats_new/violinplot_colors.rst
- galleries/examples/statistics/customized_violin.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_axes.pyi
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_axes.py
This PR adds the option of specifying the fillcolor and linecolor of violinplots. It addresses
issue #27298 (and other discusssions and requests elsewhere).
> Allow user to specify colors in violin plots with constructor method

- lib/matplotlib/tests/test_arrow_patches.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_bbox_tight.py
- lib/matplotlib/tests/test_collections.py
- lib/matplotlib/tests/test_constrainedlayout.py
- lib/matplotlib/tests/test_contour.py
- lib/matplotlib/tests/test_figure.py
- lib/matplotlib/tests/test_legend.py
- lib/matplotlib/tests/test_lines.py
- lib/matplotlib/tests/test_patches.py
- lib/matplotlib/tests/test_path.py
- lib/matplotlib/tests/test_patheffects.py
- lib/matplotlib/tests/test_simplification.py
- lib/matplotlib/tests/test_skew.py
- lib/matplotlib/tests/test_subplots.py
- lib/mpl_toolkits/axes_grid1/tests/test_axes_grid1.py
- lib/mpl_toolkits/mplot3d/tests/test_axes3d.py
- lib/mpl_toolkits/mplot3d/tests/test_legend3d.py
Not sure why this didn't hit Fedora when 3.10.0 was initially built, but it is now during the F42 Mass Rebuild.
These tests are already covered by `arm64`-specific tolerances (aka Apple Silicon), and while one or two won't need it, I've changed all of these.
Additionally, instead of listing every single architecture, just increase the tolerance on non-x86_64. Also, make a few tweaks to existing conditions to make these all consistent.
- n/a ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [n/a] *New …
> TST: Increase tolerance on more arches

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Fixes: #29474
This PR improves the error message for shape mismatches in the barh function by replacing argument indices with original parameter names. This enhances error clarity and helps users identify issues more easily.
> Improve error message for shape mismatches in barh function

- lib/matplotlib/axes/_axes.py
Just adding the right number of spaces in the docstring of ``violinplot`` and ``violin``. This is in reference to my previous PR #27304. 
The documentation looks like this:
> Spacing for description of linecolor

- lib/matplotlib/colors.py
- lib/matplotlib/tests/test_colors.py
Fixes #29042.
By default, a list of colors is assumed. Only if the conversion to rgba values fails, check for (value, color) pairs.
The check of the first entry in colors in preserved to raise more meaningful error messages.
For the first item to be interpreted as a valid (value, color) tuple, it has to be
- of type `Sized` (implements `__len__`),
- not of type `str`,
- length 2.
- first entry being a real number
- second entry passing the `matplotlib.colors.is_color_like` test
Either way, errors are returned if not all entries are (value, color) pairs or if any invalid colors are encountered.
Implemented tests for different combinations of inputs.
> FIX: Checks for (value, color) tuples in LinearSegmentedColormap.from_list

- galleries/examples/color/color_sequences.py
- galleries/examples/color/individual_colors_from_cmap.py
- lib/matplotlib/colors.py
Introducing the Matplotlib Abacus!
I did not know that the color sequence registry was a thing.  Once I did know, the next thing I wanted to know was what sequences are available.  This PR adds an example showing all the built in sequences, analogous to the [Colormaps reference](https://matplotlib.org/stable/gallery/color/colormap_reference.html#sphx-glr-gallery-color-colormap-reference-py) and [List of Named Colors](https://matplotlib.org/stable/gallery/color/named_colors.html#sphx-glr-gallery-color-named-colors-py).
I am in two minds whether to add a second plot with a newly registered color sequence or to leave this as a purely reference example of what is available by default.
> DOC: add color sequences reference example

- doc/users/next_whats_new/depthshading_improvement.rst
The what's new plot introduced in https://github.com/matplotlib/matplotlib/pull/29287 shows the fixed plotting behavior, but doesn't show depthshading well. Updated to something that shows what depthshading is.
Before:
After:
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#an …
> 3D depthshade what's new plot

- lib/matplotlib/contour.py
These attributes have been deprecated and removed for a while already. (ContourSet is now a standard artist, so it has an `.axes` attribute like all other artists; and it is itself a PathCollection.)
Closes #29575.
> Remove documentation for no-longer existent ContourSet attributes.

- lib/matplotlib/__init__.py
- lib/matplotlib/tests/test_rcparams.py
Closes #29562 (plus a second commit which flattens a bit the logic in `__setitem__`, in particular to avoid nested try... excepts).
> Remove rcParams deprecation machinery

- lib/matplotlib/_fontconfig_pattern.py
- lib/matplotlib/dviread.py
- lib/matplotlib/font_manager.py
The intent is clearer (and cache is slightly more optimized).
Followup to #24980.
> Use functools.cache instead of lru_cache to establish singletons.

- doc/users/prev_whats_new/whats_new_1.0.rst
- galleries/examples/subplots_axes_and_figures/gridspec_customization.py
- galleries/examples/subplots_axes_and_figures/subplot2grid.py
Partly adresses #25800. See the individual commit messages.
> Remove some examples from Userdemo

- lib/matplotlib/axes/_axes.py
As reported in the issue which this closes #29606 , the docstring for the argument x of `axvline` says that it sets y, but really it sets x.  Perhaps this was a copy'n'paste error from [`axhline`](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.axhline.html)?  Where the first argument is y which does set y.
This commit simply emends the doc from y to x to reflect the behaviour.
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-dep …
> Correct doc for axvline arg x which sets x not y

- lib/matplotlib/sphinxext/mathmpl.py
- lib/matplotlib/testing/compare.py
- lib/matplotlib/texmanager.py
If you use a FIPS (Federal Information Processing Standards) compliant Python install, then you cannot use `pyplot.show` to display a plot with  `plt.rcParams['text.usetex'] = True` due to a `hashlib.md5` call in [texmanager.py](https://github.com/matplotlib/matplotlib/blob/24bb51c834f7e6714e9ad8e24f7edb6c903028fe/lib/matplotlib/texmanager.py#L171).
Instead of just fixing the one instance I ran into, I changed the other usages of `hashlib.md5` in the codebase to nip those in the bud.
Per https://docs.python.org/3/library/hashlib.html#hash-algorithms, note that `sha256` is in `hashlib.algorithms_guaranteed` (while `md5` might not be), so it seems like a reasonable drop-in-place replacement.
> Constructors for hash algorithms that are always present in this module are …
> Remove md5 usage to prevent issues on FIPS enabled systems (closes #29603)

- lib/matplotlib/axes/_axes.py
Closes #28884 by normalizing kwargs for hist. The behavior of shortened options, such as ls and ec, now behave as expected. 
```python
pyplot.hist([1,2,3,4,5],bins=5,histtype='step',ls=':')
pyplot.savefig('test.pdf')
```
now produces [test.pdf](https://github.com/user-attachments/files/18615675/test.pdf)
First brought to my attention by @ecrohr
> Bug Fix: Normalize kwargs for Histogram

- .circleci/config.yml
- environment.yml
- galleries/examples/units/basic_units.py
Backport of #29616 to `v3.10.x` branch
> Backport PR #29616 on branch v3.10.x (FIX: Fix unit example so that we can unpin numpy<2.1)

- galleries/examples/text_labels_and_annotations/text_rotation_relative_to_line.py
Before: https://matplotlib.org/stable/gallery/text_labels_and_annotations/text_rotation_relative_to_line.html
After:
> DOC: Cleanup text rotation in data coordinates example

- galleries/examples/lines_bars_and_markers/axline.py
Let's reduce the section "pyplot" to examples explicitly showcasing special approaches and features of `pyplot`. An example mainly explaining how to draw infinite lines should be in the "lines" subsection.
> DOC: Move "Infinite lines" example from section "pyplot" to "Lines, bars and markers

- lib/matplotlib/tests/meson.build
There is a new test notebook in 3.10.0 which was not added to the appropriate tag to install test data if so desired. Hence, the unit tests of an installed package (`pytest --pyargs matplotlib.tests`) currently fail. Adding the file to the meson tag fixes it (when `tests` is added to the meson install tags).
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-c …
> Add inline notebook to test data

- galleries/users_explain/figure/interactive_guide.rst
- Harmonize quotation & spacing style.  Fix indentation in example code.
- `_exec` (actually, `exec_`) was used in Py2-compatible libraries where `exec` was a reserved keyword, but PyQt, for example, has now moved to naming the method `exec`.
> Copy-edit "interactive figures & async programming" guide.

- doc/api/next_api_changes/behavior/28437-CH.rst
- lib/matplotlib/image.py
- lib/matplotlib/tests/test_image.py
This PR hopefully closes https://github.com/matplotlib/matplotlib/issues/28382, making sure that array alpha is respected in `_Imagebase::_make_image` when param `interpolation_stage` is set to 'rgba'.
> Respect array alpha with interpolation_stage='rgba' in _Imagebase::_make_image

- lib/matplotlib/colorbar.py
Move "redundant" kwargs (cmap/norm can be specified via mappable; orientation/ticklocation can be specified via location) to the end of the kwarg list and under an "Other Parameters" section.
Also remove mention of Normalize(clip=False);
imshow(rand(10, 10),
cmap=mpl.colormaps["viridis"].with_extremes(under="w", over="k"))
colorbar(extend="both")
seems enough to have over/under colors show up, i.e. no need to fiddle with the clip parameter.
> Reorder kwonly kwargs in Colorbar & related docs.

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/PULL_REQUEST_TEMPLATE.md
Fixes broken link in bug report and PR templates
Old Link: https://dev.matplotlib.org/devel/contributing.html#generative_ai.
New Link: https://matplotlib.org/devdocs/devel/contribute.html#restrictions-on-generative-ai-usage
- [NA ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [NA ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ NA] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [NA] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#annou …
> fix: broken link

- galleries/examples/lines_bars_and_markers/scatter_hist.py
Since this example uses constrained layout, the 75% modification on the gridspec has no effect.  We can therefore simplify this axes creation.  (I have a use-case where constrained layout needs to run more times to fit everything properly.  I saw this example and thought maybe using the 75% approach would help the constrained layout algorithm by starting closer to where it needs to go, but it made no difference to my use-case either).
Also switched out `set(aspect=` for `set_aspect(` following guidance at https://github.com/matplotlib/matplotlib/issues/28693#issuecomment-2278075085.
> DOC: remove redundant gridspec from example

- lib/matplotlib/colorbar.py
Follow-up to #29652.
This prevents numpydoc from inserting Attributes between Parameters and Other Parameters see https://github.com/matplotlib/matplotlib/pull/29652#pullrequestreview-2634087106. It's also a pattern we generally use.
> DOC: Move Colorbar parameters to __init__

- galleries/examples/event_handling/data_browser.py
Closes #22329 
Matplotlib now enforces that line data modifications must be sequences. However, the example script has not been updated accordingly, which will cause errors when running it.
```
...
File "...\matplotlib\galleries\examples\event_handling\data_browser.py", line 72, in on_pick
self.update()
File "...\matplotlib\galleries\examples\event_handling\data_browser.py", line 92, in update
self.selected.set_data(xs[dataind], ys[dataind])
File "...\site-packages\matplotlib\lines.py", line 665, in set_data
self.set_xdata(x)
File "...\matplotlib\lines.py", line 1289, in set_xdata
raise RuntimeError('x must be a sequence')
RuntimeError: x must be a sequence
```
Updated script to fix this bug.
> DOC: fix the bug of examples\event_handling

- galleries/examples/lines_bars_and_markers/scatter_hist.py
Follow up to #29667 to use subplot_mosaic instead of `add_gridspec` and three `add_subplot` calls.
I actually removed the gridspec example, though happy to revert and put at the end.  I don't think users in general should ever need to use gridspec.
> DOC: change marginal scatter plot to subplot_mosaic

- lib/matplotlib/sphinxext/figmpl_directive.py
- lib/matplotlib/sphinxext/plot_directive.py
- lib/matplotlib/tests/test_sphinxext.py
- lib/matplotlib/tests/tinypages/some_plots.rst
We currently template new reST to be re-parsed after the plot is created, but incorrectly copied the `alt` and `caption` values when they were wrapped.
In the future, we should probably drop this template and directly create the nodes we need, but I assume that `TEMPLATE` is not private right now for the purpose of letting people modify it.
Additionally, change `figmpl` to use Sphinx/docutils' tag creation functions. These functions correctly escape attributes and so fixes invalid HTML when alt text contains quotes. I also dropped some attributes if they were empty (e.g., we no longer get `style="" class=""` if those aren't specified.)
For example, this is broken on the [dark colour map image](https://matplotlib.org/3.10.0/users/prev_whats_new/whats_new_3.10.0.html#dark-mode-diverging-colo …
> Fix alt and caption handling in Sphinx directives

- lib/matplotlib/colorizer.py
- lib/matplotlib/tests/test_colorbar.py
- lib/matplotlib/tests/test_colors.py
closes #29522 
- Why is this change necessary? What problem does it solve? What is the reasoning for this implementation?
Previously when norm's limits were updated, self.changed() was called through the callbacks attached to the norm, these callbacks were fired immediately leading to inconsistent state and causing the bug. 
This change blocks the immediate callbacks and emits a update signal after both the limits have been set.
> Blocked set_clim() callbacks to prevent inconsistent state (#29522)

- lib/matplotlib/tests/test_patches.py
Fixes: #29261
This commit adds test cases to verify the behavior of `patch.force_edgecolor` when `facecolor="none"`.
> Add test cases for patch.force_edgecolor behavior with facecolor="none"

- galleries/examples/subplots_axes_and_figures/shared_axis_demo.py
- galleries/examples/text_labels_and_annotations/date.py
- galleries/examples/ticks/centered_ticklabels.py
- galleries/examples/ticks/date_concise_formatter.py
- galleries/examples/units/evans_test.py
- lib/matplotlib/figure.py
Working towards #29594. In particular, usage of `tick_params()` is superior in that it's an axis-wide setting that is applied to new/changed ticks. In contrast, manipulating volatile tick instances may result in inconsistency if the plot is further modified afterwards.
Note this needs the new text rotation mode "xtick" and is thus targeted at 3.11.
> MNT: Reduce the use of get_xticklabels() in examples

- lib/matplotlib/animation.py
Currently, there is no "official" way of knowing whether a Figure hosts an Animation.  Yet, this information can be of interest e.g. for third-party backends.  For example, a variant of the ipython inline backend could choose to actually animate its (inline) output in that case; indeed, this feature was already supported by the itermplot backend. itermplot is actually now outdated but the general idea can still be made to work -- I have a working patch for mplterm.
The idea is for the backend to override FigureCanvas.new_timer (on the backend-specific canvas subclass) to internally register any timer that gets created (e.g. by the animation module), then, when the canvas is show()n, to first trigger a fake draw_event so that animation callbacks (if any) get attached to the timer, and then …
> Connect the Animation event source callback in the constructor.

- doc/devel/min_dep_policy.rst
Since NEP 29 is superseded by SPEC 0, update the link in our dependency policy.
> NEP 29 > SPEC 0 in dependency policy

- doc/devel/min_dep_policy.rst
Reverts matplotlib/matplotlib#29744 - as noted in https://github.com/matplotlib/matplotlib/pull/29744#issuecomment-2718535658 the text below is not consistent with SPEC 0, so making this change requires a better/more complete PR explaining the changes, and leaving time for discussion/input on changing it.
> Revert "NEP 29 > SPEC 0 in dependency policy"

- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_rcparams.py
There seems to be a case-sensitivity bug in the `matplotlib.pyplot` module code that decides whether to configure backend autodetection, and I think that this is the cause of the bug reported in #29713.
The bug means that a current interactive environment value of `TkAgg` is not detected as one of the possible values from a set that includes the string `tkagg` -- and so an auto-backend is _not_ configured, as it would have been previously in v3.8.3 of this library.
A minimal repro example is provided below, for use in a container environment with no graphical/GUI environment available:
```pyi
>>> import matplotlib.pyplot
>>> matplotlib.pyplot.new_figure_manager()
File "<python-input-1>", line 1, in <module>
matplotlib.pyplot.new_figure_manager() …
```
> FIX: pyplot auto-backend detection case-sensitivity fixup

- doc/users/next_whats_new/bar_label_padding_update.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_axes.pyi
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_axes.py
- [X ] "closes #29647 " is in the body of the PR description to [(https://github.com/matplotlib/matplotlib/issues/29647)]
- [ X] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [X ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ X] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines
> ENH: Add support for per-label padding in bar_label

- doc/index.rst
- doc/install/index.rst
Closes #29746.
Notes on issues with uv an tk taken from
https://github.com/astral-sh/uv/issues/6893#issuecomment-2565965851
I'm open whether pyside6 is the right example for installing another GUI framework, but (i) I think we should have one install command written out that has a working interactive backend (ii) I somehow prefer Qt, but think that the permissively licensed pyside6 may in general be the better recommendation compared to PyQt6.
> DOC: Add install instructions for pixi and uv

- doc/users/next_whats_new/logticks.rst
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_colorbar.py
- lib/matplotlib/tests/test_contour.py
- lib/matplotlib/tests/test_scale.py
- lib/matplotlib/tests/test_ticker.py
- lib/matplotlib/ticker.py
Rewrite the logic for subsampling log-scale ticks, so that 1) there's as many ticks as possible without going over numticks (don't draw a single tick when two would fit), and 2) the ticks are spaced as much as possible (when two ticks are drawn, put them on the lowest and highest decade, not somewhere in the middle).  See comments in implementation for details.  For the backcompat-oriented "classic-mode", remove the "stride >= numdec" check (which is a much later addition).
Test changes:
- TestLogLocator changes because tick_values() no longer returns major ticks outside of the (vmin, vmax) range.
- test_small_range_loglocator was likely previously wrong (the assert did not cover the values of ticks, and all iterations of the loop ended up testing the same condition).  Rewrite it fully …
> Improve tick subsampling in LogLocator.

- lib/matplotlib/backend_bases.py
- lib/matplotlib/tests/test_backend_bases.py
Adding a test for this required tweaking a bit the behavior of non-GUI managers (so that they also store the window title); note that the comment of non-GUIs returning None was clearly wrong.
Closes #29779.
> Fix escaping of nulls and "0" in default filenames.

- galleries/examples/text_labels_and_annotations/fancyarrow_demo.py
Position everything in data coordiates rather than Axes coordinates. While the code is not the primary goal of this example, it's slightly simpler to follow if we keep everything in data coordinates, which is what all the commands (plot, text, annotate) are by default in.
The output is basically unchanged, with the exception of making the point marker and the textbox edge dark grey so that the black arrow stands out more.
> DOC: Simplify annotation arrow style reference

- .github/workflows/tests.yml
- requirements/testing/minver.txt
While not exactly a minver test, it's semantically related in that it changes rather old package versions. This should help declutter the test matrix and make the upcoming transition to newer ubuntu images and dropping python 3.10 simpler (related #29766).
> MNT: Move test for old ipython behavior to minver tests

- doc/devel/development_setup.rst
- doc/install/dependencies.rst
At the sprints for PyData NYC, as I was setting up the repo for local development, I ran into an issue with  installing `ninja` directly from the dev requirements file. After chatting with @story645, she suggested I update the documentation and make a separate section to make external dependency on `ninja` more clear.
This PR changes the docs page to add a new section for the `ninja` external dependency, and removes it from the Python section. I also added `ninja` to the list of external dependencies in the documentation.
- [N/A] new and changed code is …
> DOC: Update page to note installation for ninja library

- doc/api/next_api_changes/deprecations/27972-AL.rst
- lib/mpl_toolkits/axes_grid1/axes_grid.py
- lib/mpl_toolkits/axes_grid1/tests/test_axes_grid1.py
This also restores axes_row and axes_column to their behavior prior to 88e0d84 (which is the commit that broke ngrids support).
Closes a small part of #27963.
> Fix ngrids support in axes_grid.Grid().

- galleries/examples/text_labels_and_annotations/fancyarrow_demo.py
- use straight lines for the arrows - the previous curved lines are distracting since this is only about the arrowstyle
- use monospace font for the style names
- adjust positions and colors so that the arrows stand out more
> DOC: Slightly further improve arrowstyle demo

- doc/users/next_whats_new/color_cycle_from_sequence.rst
- galleries/users_explain/artists/color_cycle.py
- lib/matplotlib/__init__.py
- lib/matplotlib/mpl-data/matplotlibrc
- lib/matplotlib/rcsetup.py
- lib/matplotlib/tests/test_rcparams.py
Closes #29799
As mentioned in the issue, it is _possible_ that someone could register a color sequence called something like "rygbk" and then it would be ambiguous whether to use the color sequence or interpret as single character colors.  We agreed that the color sequence would take precedence in this situation.  Should I actually document that precedence either in the user guide section or in a next-api-changes note?  I think in practice it will come up very rarely if at all.
> ENH: set default color cycle to named color sequence

- galleries/users_explain/figure/backends.rst
Make the wx test a one-liner like other backends.  Use PyQt6 as default qt (matching the default in qt_compat).
> Tweak minimal checks for GUI binding installs.

- lib/matplotlib/axes/_base.py
- lib/matplotlib/projections/polar.py
- lib/matplotlib/tests/test_polar.py
**Update:** The final implementation differs from the original proposal. The solution now preserves the `RadialLocator` behavior that was being overwritten on `set_rticks` instead of modifying `handle_single_axis`. The test was renamed to `test_radial_limits_behavior`.
When using `set_rticks` followed by `plot` in polar plots, the lower radial limit (which should
always be 0) was being overwritten by autoscaling logic. This caused visual artifacts and
incorrect axis behavior in polar plots.
This fix prevents the radial origin from moving away from 0 when setting radial ticks with
`set_rticks` and adding data with `plot`.
- Modified `handle_single_axis` in `autoscale_view` to …
> Ensure polar plot radial lower limit remains at 0 after set_rticks + plot

- environment.yml
- requirements/testing/flake8.txt
Flake8 7.2.0 doesn't like 
https://github.com/matplotlib/matplotlib/blob/2933275ae2426c07fd00b7a3da3726515825c930/lib/matplotlib/_mathtext.py#L1612-L1624
But that code passed before.  Seems like maybe a bug on their end?  But I'm not familiar with `nonlocal` to be honest.  
This PR just pins flake8 to unbreak CI
> TST: pin flake8

- doc/api/next_api_changes/behavior/29832-REC.rst
- lib/matplotlib/axes/_base.py
- lib/matplotlib/legend.py
- lib/matplotlib/tests/test_legend.py
Expire the deprecations from #27175 and #27767
> MNT: expire legend-related deprecations

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Fixes https://github.com/matplotlib/matplotlib/issues/29615. Instead of explicitly setting the data lims with the min/max values of the edges, pass all the values to allow `update_datalim` to handle them appropriately. I also took the oppurtunity to de-duplicate the limit setting code in `pcolor()` and `pcolormesh()`, since I needed to update them to match anyway.
The tests are both very similar, but I couldn't think of a good way to de-duplicate testing `pcolor` and `pcolormesh` - suggestions very welcome.
In terms of performance, running the below script locally I see ~10% slowdown with pcolormesh, and no significant slowdown with pcolor.
```python
import time
x = np.arange(512, dtype=float)
y = np.arange(512, dtype=float)
z = …
```
> Fix log scaling for pcolor and pcolormesh

- .github/workflows/tests.yml
GitHub Actions will soon remove support for the Ubuntu 20.04 runner, as described at: https://github.com/actions/runner-images/issues/11101
This pull request raises the baseline runner image from Ubuntu 20.04 to Ubuntu 22.04, allowing GitHub Actions checks to continue after the removal of the former runner image.
Ubuntu 20.04 is only used in the `tests.yml` workflows, for jobs where Ubuntu 22.04 is already in parallel use.  As a result, the approach taken here is to rotate Ubuntu 20.04 out of the roster, and to replace the entry that previously used it with Ubuntu 22.04 instead.
In addition, the fact that we no longer use Ubuntu 20.04 at all during GHA CI means that we can remove …
> ci: rotate soon-to-be-unsupported GitHub Actions ubuntu-20.04 runner out of roster

- doc/api/next_api_changes/deprecations/29817-AL.rst
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/dviread.py
- lib/matplotlib/dviread.pyi
Another small preparatory PR for #29807 ({xe,lua}tex support).
Instead of directly exposing widths, heights, depths dicts, provide a get_metrics method to access a glyph's (tex) metrics.  This change is in preparation for {xe,lua}tex support, which would use an alternative metrics-loading class (`TtfMetrics`) where it would be excessive to load the metrics of all glyphs at once.
> Switch Tfm metrics to TrueType-compatible API.

- .github/workflows/tests.yml
GitHub Actions continuous integration unit test coverage is reduced on Linux due to an unsatisfied system dependency requested by recent versions of the Python `PyGObject` library.
In particular, `PyGObject` version 3.52.0 introduces a requirement for `girepository-2.0`: https://gitlab.gnome.org/GNOME/pygobject/-/blob/e3dee9719e7249acfa7e78a3bbae251301a134a4/NEWS#L9-10
The relevant system package to fulfil the requirement is not available on Ubuntu 22.04, and seems unlikely to become available on that platform.  This causes some Linux GTK UI tests in the CI here to be skipped.
Test coverage can be improved by including an Ubuntu 24.04 test job using a host that provides the `girepository-2.0` dependency.
- What is the reasoning …
> ci: Introduce ubuntu-24.04 to restore GTK test coverage with recent PyGObject versions

- lib/matplotlib/_pylab_helpers.py
Going through manager.num is unnecessary as destroy() only looks up the manager for the given number again.
As the docstring of destroy() explains:
> It is recommended to pass a manager instance, to avoid confusion when two managers share the same number.
https://github.com/matplotlib/matplotlib/blob/90385b4e26efc4b3a0c6c2497e97dac36fc94841/lib/matplotlib/_pylab_helpers.py#L45-L54
> MNT: Use Gcf.destroy(manager) instead of Gcf.destroy(manager.num)

- .github/workflows/tests.yml
This is primarily intended to aid comprehensibility and simplicity of the GitHub Actions `tests.yml` workflow we're using.
The changeset here should make the file shorter and simpler.
The package version restrictions removed by this changeset no longer represent the latest version of each package that would be installed by default on each system during the workflows.
Strictly speaking, all subsequent/current versions of those packages could be removed or yanked from PyPI, but this seems unlikely.
There is some historic value in knowing that these versions were incompatible; I think that given that alternatives have been available and stable for some time (Nov 2023 for `pyqt6-ver` …
> ci: cleanup: remove stale/outdated version range restrictions

- lib/matplotlib/offsetbox.py
Fixes https://github.com/matplotlib/matplotlib/issues/29142; replaces https://github.com/matplotlib/matplotlib/pull/29270. The solution here is to set a custom picker on `DraggableBase` that doesn't fire if the event is a scroll event.
> Don't drag draggables on scroll events

- galleries/users_explain/figure/interactive_guide.rst
Side-topic spinning of from #29742.
- Move the paragraph on "GUI events" to it's own section and before "Event loops". It's related but not directly needed for the event loop discussion. It was an odd side topic in the old location between "Event loops" and "Command prompt integration".
- Rephrase the section on "Blocking the prompt" and some other smaller wording improvements
Note: There will be a follow-up on #29742, but I think it's best to keep these unrelated changes separate and get them out of the way before reworking #29742.
> DOC: Improve interactive figures guide / Blocking input

- doc/users/next_whats_new/figsize_unit.rst
- lib/matplotlib/figure.py
- lib/matplotlib/figure.pyi
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_figure.py
Reviving the spirit of #12402 and #12415, because both had significant user votes on GitHub.  - #12402 is the highest up-voted issue that we have closed as "not planned" (17 up-votes); #12415 got 7 downvotes on the closing note that people should convert themselves.
Also closes #1369.
This PR is intentionally minimal to only expand the `figsize` parameter when creating a figure. It allows `plt.figure(..., figsize=(600, 400, 'px'))` in addition to the current `plt.figure(..., figsize=(6, 4))` - note that this passes through to all figure-creating methods. This should be the most relevant use case. Later changing the figure size or reading it is probably less necessary. The minimal approach removes the need to track and return sizes. It is just an enhanced specification capability which …
> ENH: Support units when specifying the figsize

- lib/matplotlib/backend_bases.py
- lib/matplotlib/backend_bases.pyi
- lib/matplotlib/collections.py
- src/_backend_agg.h
- src/_backend_agg_wrapper.cpp
Fixes #29883 
Removes the `hatchcolors` parameter from `draw_quad_mesh()`, as `QuadMesh` doesn't support hatching.
> Remove hatchcolors parameter from draw_quad_mesh

- lib/matplotlib/image.py
- lib/matplotlib/tests/test_image.py
Fixes #29891.  The problem is that we divide the RGB part of the array by its alpha on each draw.  The simple fix is to make a copy but I assume for efficiency we should only copy when necessary.
* If we didn't start with RGBA, we already made a copy
* If alpha was an array, we already made a copy
* If the alpha channel is one everywhere, it does not matter
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#writ …
> FIX: make_image should not modify original array

- .pre-commit-config.yaml
- ci/codespell-ignore-words.txt
- lib/matplotlib/figure.py
Replaces https://github.com/matplotlib/matplotlib/pull/29884 - instead of rebasing that (because we switched out `flake8`), it was easier to manually update and make the fixes.
> Bump pre-commit versions

- lib/mpl_toolkits/mplot3d/art3d.py
closes issue #26739
Updates `Line3DCollection` doc string to be similar to that of `LineCollection` doc string parameters.
- [ ✅ ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [N/A ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [N/A ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [ ✅ ] Documentation complies with …
> add detail to doc string in Line3DCollection

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
`errorbar` checks that errors are not negative, but a bit convolutedly, in order to avoid triggering on nan. Unfortunately, the work-around for nan means that possible masks get discarded, and hence passing in a masked error array that has a negative but masked value leads to an exception. This PR solves that by simply combining the test for                                                                                                       
negative values with the indirect isnan test (err == err), so that if a masked array is passed, the test values are masked and ignored in the check.
As a bonus, this also means that astropy's ``Masked`` arrays can now be used -- those refuse to write output of tests to unmasked values since that would discard the mask (which is indeed the underlying …
> BUG: ensure that errorbar does not error on masked negative errors.

- lib/matplotlib/_mathtext.py
While trying to figure out what's going on in #29886 I noticed that matplotlib currently incorrectly handles `\rightparen` because of a typo as `\rightparent`. This (tiny) PR fixes that.
I still don't understand what's going on in #29886. …
> Correct rightparen typo

- lib/matplotlib/image.py
- lib/matplotlib/tests/test_image.py
This PR addresses issue #29183 by casting Python sequence types (e.g., lists or tuples) to `NumPy` arrays during the image saving process.
The implementation is inspired by PR #29203 by @gpxxlt, which currently appears to be on hold.
- [ N/A ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ N/A ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [ N/A ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines
> Allow Python native sequences in Matplotlib `imsave()`.

- lib/matplotlib/backend_bases.py
This was found in #29794, but is actually no longer needed there as we decided not to change the backend signature. However, this is still more correct in case we need to look at the signatures in the future. …
> Fix signature of disabled draw methods

- lib/matplotlib/path.py
- lib/matplotlib/tests/test_path.py
Fixes #29917.  The geo projection's path transform relies on `Path.interpolated`
https://github.com/matplotlib/matplotlib/blob/b7e7663155d83fecc82556ec1135f22cf81778f5/lib/matplotlib/projections/geo.py#L249-L252
At v3.8 `ContourSet` changed from having one path per contour to one path per level, and so its paths can now contain internal `MOVETO`'s.  We can make the `interpolated` method handle those by just splitting the path up, applying itself to each sub-path, and re-joining the result.  The example code provided in #29917 now gives
For `contour` the given example also had one or more empty paths which caused an exception in the interpolation.  We can just pass those straight out again.
I welcome better wording for the docstring, though I do not think the original was correct since a …
> Handle MOVETO's, CLOSEPOLY's and empty paths in Path.interpolated

- galleries/users_explain/figure/interactive_guide.rst
I do not know the full history of when/why the doc build started failing on 3.10.x, but this picks out some of the changes made in https://github.com/matplotlib/matplotlib/pull/29400 to hopeully get the doc build passing again.
> Fix doc build on 3.10.x

- lib/matplotlib/tests/test_image.py
- pyproject.toml
This turn 302 (blank lines) back on.
> DEV: have ruff check blank-line counts

- galleries/users_explain/axes/colorbar_placement.py
- galleries/users_explain/axes/constrainedlayout_guide.py
Closes #29938
Adds text to placing colorbars and constrained layout guide that points out the role of compressed layout in making colorbars match the size of the parent axes.  
The colorbar placement example in this section was pretty complex, and I'm not sure it was necessary so I just replaced with the simpler one-axes example.
> Doc fixed aspect colorbar

- tools/boilerplate.py
Before this PR, if the Matplotlib installed in the current environment is not the same as the source tree `boilerplate.py` is from, the `Axes`/`Figure` classes not taken from the correct source tree. This adds a guard to make sure this isn't the case.
I have confirmed locally this prevents situations like those described in https://github.com/matplotlib/matplotlib/issues/29921
I can't think of a situation where one wants to deliberately generate `pyplot.py` from another source tree, but if there is manually specifying the other source tree as an argument to `boilerplate.py` should still work.
Fixes https://github.com/matplotlib/matplotlib/issues/29921.
> Check Axes/Figure import paths in boilerplate.py

- galleries/users_explain/axes/autoscale.py
- galleries/users_explain/axes/index.rst
Closes #29906
Current webpage:
After change:
> Changed "Autoscaling axes" to "Autoscaling axes on user guide page for issue & closes #29906

- galleries/examples/lines_bars_and_markers/multicolored_line.py
- Reduces the number of lines.
- Stops using Numpy functions which is not array-api compatible (`hstack`, `column_stack`, etc.), which improves readability.
- Calls `autoscale_view`, thus `set_xlim`, etc. need not to be called manually.
- Adds `stacklevel=2` in `warnings.warn`.
- (Note: I have created a dedicated package for this function: https://github.com/34j/matplotlib-multicolored-line) …
> Simplify `colored_line()` implementation in Multicolored lines example

- .github/workflows/tests.yml
Manual backport of #29796.  The conflict was because `main` has some extra lines from #29171 right before the if-loop we're removing here.
cherry picked from commit 0d11978c9f933a9fc7a585891b350c09958e034b
> Backport PR #29796 on branch v3.10.x: ci: rotate soon-to-be-unsupported GitHub Actions ubuntu-20.04 runner out of roster

- .github/workflows/tests.yml
Manual backport of https://github.com/matplotlib/matplotlib/pull/29796. The conflict was because main has some extra lines from https://github.com/matplotlib/matplotlib/pull/29171 right before the if-loop we're removing here.
(cherry picked from commit 0d11978c9f933a9fc7a585891b350c09958e034b)
> Backport PR #29796 on branch v3.10.1-doc: ci: rotate soon-to-be-unsupported GitHub Actions ubuntu-20.04 runner out of roster

- lib/matplotlib/tests/test_quiver.py
Check the change of the refcount, instead of the absolute value, as suggested by @ngoldbaum in https://github.com/matplotlib/matplotlib/issues/29959#issuecomment-2824739314.
I did not test against Python 3.14, but perhaps @befeleme could.
> TST: Make refcount tests more resilient to Python changes

- galleries/examples/animation/rain.py
Identified in #29960 by @vnmabus that we had examples with incorrect signatures.
> DOC: correct signature for animation update function in rain example

- lib/matplotlib/_mathtext.py
- lib/matplotlib/tests/test_mathtext.py
- Improve the repr of mathtext boxes (see test_box_repr; previously the entire repr would be in a single line).  Boxes are internal objects not exposed by any public API so the change is purely for debugging purposes.
- In ship, off_h and off_v are never modified, so there's no need to declare them as nonlocal in the nested functions.
> Improve repr of mathtext internal structures; minor cleanup.

- src/ft2font_wrapper.cpp
This is shorter and more readable than defining them with single-use static functions positioned quite far away from the def_property_readonly calls.
> Use inline lambdas to define most FT2Font properties.

- lib/matplotlib/animation.py
- lib/matplotlib/animation.pyi
`func` and `init_func` may return None (which is ok if `blit=False`). Since gating the allowed signature on the state of `blit` is not feasible, we err on the side on being too permissive in the type definition: Rather not flag a type error and only raise on runtime than complain on an actually working signature.
Closes #29960.
> FIX: Typing of FuncAnimation

- doc/_static/mpl.css
- doc/_templates/cheatsheet_sidebar.html
This improves the layout of the cheatsheets so:
- The image takes up the full width of the sidebar
- The heading is aligned with the top of the RH sidebar
- The title drops "Matplotlib" (there are already many 'Matplotlib' strings on the home page 😄) and is now just "Cheatsheets"
Note this depends on https://github.com/matplotlib/mpl-sphinx-theme/pull/97 to remove existing CSS for styling the cheatsheets that was in the theme.
For a before/after comparison, see the companion PR at https://github.com/matplotlib/mpl-sphinx-theme/pull/97
> Improve layout of cheatsheets in sidebar

- doc/users/next_whats_new/log_contour_levels.rst
- lib/matplotlib/contour.py
- lib/matplotlib/tests/test_contour.py
When plotting contours with a log norm, passing an integer value to the ``levels`` argument to cap the maximum number of contour levels now works as intended.  Partially addresses https://github.com/matplotlib/matplotlib/issues/19856 and replaces https://github.com/matplotlib/matplotlib/pull/25149.
I've maually checked that the added test fails before this fix. Testing with the following script:
```python
from matplotlib.colors import LogNorm
x, y = np.mgrid[1:10:0.1, 1:10:0.1]
data = np.abs(np.sin(x)*np.exp(y))
for n_levels in range(2, 20):
im = ax.contourf(x, y, data, norm=LogNorm(), levels=n_levels)
cbar = fig.colorbar(im, ax=ax)
n_ticks = len(cbar.ax.get_yticklabels())
print(f"Requested max {n_levels + 1}, got …
```
> Fix specifying number of levels with log contour

- meson.build
- pyproject.toml
If `python3` is in the path, it might be picked up instead of the one used to build. This is the case on GitHub actions, where cibuildwheel seems to explicitly call the Python (3.11+) it wants, but `python3` is in the hosted tool cache as an older version (3.9) that gets picked by Meson. This matters because we need to run `setuptools_scm` to produce the version, and it may not be installed in the `PATH`-based copy.
By specifying the version, Meson should skip the `PATH` option, and choose its final fallback, the interpreter that it is itself running on. While still not guaranteed to be correct everywhere, this should at least work for CI.
- [n/a] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues …
> BLD: Ensure meson.build has the right version of Python

- meson.build
- pyproject.toml
With correction to the Python version, that should be 3.10 for this branch.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrin …
> Backport PR #29997 on branch v3.10.x (BLD: Ensure meson.build has the right version of Python)

- azure-pipelines.yml
The windows-2019 image will be deprecated on 1.6.2025 (https://github.com/matplotlib/matplotlib/issues/29797#issuecomment-2843052409). Also, this is a test whether the timeouts #29797 are related to the windows-2019 image.
> Update pinned oldest win image on azure

- azure-pipelines.yml
Manual backport of #29992.  Conflicts were because we have more runners on the v3.10.x branch:
* We still support python 3.10 here so the minimum image is used for that instead of python 3.11
* #29171 was not backported so we have multiple platforms and so the modified if-loop is more nested
(cherry picked from commit ab102c079ae0474861bbb1dcc64da436d1a84f8b)
> Backport PR #29992 on v3.10.x: Update pinned oldest win image on azure

- doc/api/next_api_changes/deprecations/30027-AL.rst
- lib/matplotlib/backends/backend_pdf.py
They are clearly intended for internal use, and we may want to change their internal representation in the future to support xetex/luatex (which expose more font types).
> Make PdfFile font-related attributes private.

- lib/matplotlib/colors.py
This patch speeds up conversions of `#rgba`-type formats by between 25% and 40% (while shortening the implementation), although real benefits should be limited because of caching in to_rgba.
> Micro-optimize _to_rgba_no_colorcycle.

- doc/_embedded_plots/figure_subplots_adjust.py
This pull request addresses an issue in the documentation for [](https://matplotlib.org/stable/api/_as_gen/matplotlib.figure.Figure.subplots_adjust.html#matplotlib.figure.Figure.subplots_adjust) where the diagram incorrectly implied that the left, right, top, and bottom parameters were distances from the nearest subplot edges. In reality, these parameters represent distances from the edges of the figure (the overall plotting area).
The current diagram is misleading and contradicts the correct usage of subplots_adjust, potentially causing confusion for users trying to control subplot layout. 
The implementation involves updating the Python script (doc/_embedded_plots/figure_subplots_adjust.py) that generates …
> Update diagram in subplots_adjust documentation to clarify parameters

- lib/matplotlib/__init__.pyi
- lib/matplotlib/_enums.pyi
- lib/matplotlib/axes/_axes.pyi
- lib/matplotlib/colorizer.pyi
- lib/matplotlib/colors.pyi
- lib/matplotlib/contour.pyi
- lib/matplotlib/table.pyi
- lib/matplotlib/text.pyi
- pyproject.toml
Enables linting of .pyi files. Most of the fixes here are line length, other fixes are:
- Fix `__all__` in `__init__.pyi`
- Remove unused imports
> Enable linting of .pyi files

- pyproject.toml
Version 0.18 should restore handling of symlinks:
https://github.com/mesonbuild/meson-python/pull/728 …
> Remove meson-python pinning

- .github/workflows/tests.yml
Unit test coverage for GTK (both v3 and v3) in our GitHub Actions CI `tests.yml` workflow is largely skipped at the moment.
This is because recent versions of `PyGObject` -- as required for `import gi` to succeed -- are incompatible with the `girepository-1.0` system dependency that we install on our Ubuntu 22.04 runners.
Specifically, as noted in #29844, `PyGObject` v3.52 adds a requirement on `girepository-2.0`.
The goal here is to re-enable GTK-related test coverage.
To work around the problem, this pull request suggests pinning the upper-bound version of the `PyGObject` library that we install on the affected Ubuntu 22.04 runners.
1. The `girepository-2.0` system dependency …
> ci: restrict 'pygobject-ver' for Ubuntu 22.04 jobs

- lib/matplotlib/backends/backend_pdf.py
If fontfile is None, an error would already have been raised earlier in dviFontName (which explicitly checks for this case).
(The cutout in _embedTeXFont was introduced first, in ed0066f (2009), but support for that case appears to have been broken a bit later and the check in dviFontName was then introduced in 4fcc0e7 (2016) where it simply improved the clarity of the exception ultimately raised. -- attn @jkseppan, who wrote both commits?)
Noted in relation to #29807.
> Remove cutout for missing font file in PdfFile._embedTeXFont.

- doc/users/resources/index.rst
Following discussions with @tacaswell and @story645, I have added [Matplotlib Journey](https://www.matplotlib-journey.com/), an online course on matplotlib, in the external resources.
Please let me know if any changes need to be made (for example, to make it clear that this is a paying resource).
- [N/A] *New Features* and *API Changes* are noted with a [directive …
> Add Matplotlib Journey online course to external resources

- lib/matplotlib/artist.py
- lib/matplotlib/image.py
Closes #2831
Went with a purely documentation fix (and fleshed out the `BBoxImage` docs while I was at it).
- [/] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [/] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [/] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
> DOC: add warnings about get_window_extent and BboxImage

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
> Backport PR #29895 on branch v3.10.x (The 'lines.markeredgecolor' now doesn't interfere on the color of errorbar caps)"

- doc/api/next_api_changes/removals/xxxxxx-DS.rst
- lib/matplotlib/backends/backend_ps.py
Deprecated in 3.9, so time to remove.
> Remove get_bbox_header

- lib/matplotlib/tests/test_collections.py
This PR adds a new test to verify that changing the colormap of a 3D scatter plot (`Axes3D.scatter`) after drawing the figure properly updates the face colors.
There was previously no test ensuring that colormap updates on 3D scatter plots are reflected after a figure draw. This test ensures consistency with 2D behavior and guards against regressions.
Confirms that calling `set_cmap()` after drawing does in fact update the plotted colors in 3D, which has historically been a bug but seems to be fixed.
The test draws a 3D scatter plot with an initial colormap (`'jet'`), forces a draw, changes the colormap to `'viridis'`, and compares it against a reference plot created directly with `'viridis'`.
This ensures the update mechanism behaves correctly post-render.
```python
sc = ax.scatter(x, y, …
```
> Add 3D scatter test for cmap update

- lib/matplotlib/tests/test_sphinxext.py
Just a couple things I noticed in #30061:
- `test_tinypages` unnecessarily calls `sphinx-build` twice.
- `test_srcset_versions` doesn't need an extra copy of the source files, as it doesn't modify anything. …
> Simplify some Sphinx tests

- lib/matplotlib/offsetbox.py
- lib/matplotlib/tests/test_offsetbox.py
As with the custom picker, `Artist.contains` returns a boolean and a dictionary in a tuple. This non-empty tuple is always true, so the custom picker would always return True for any non-scroll event. It would also lose the related dictionary.
This broke `mplcursors` tests.
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-feature …
> Fix OffsetBox custom picker

- lib/matplotlib/_mathtext.py
Mypy 1.16.0 flags errors here:
lib/matplotlib/_mathtext.py:2531: error: "Node" has no attribute "width"  [attr-defined]
lib/matplotlib/_mathtext.py:2608: error: List item 0 has incompatible type "Kern"; expected "Hlist | Vlist"  [list-item]
The check for the attribute _metrics is equivalent to checking for an
instance of Char, since only Char and its subclasses set self._metrics.
Mypy infers an unnecessarily tight type list[Hlist | Vlist] for
spaced_nucleus so we give it a more general one.
> Add some types to _mathtext.py

- lib/matplotlib/_afm.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/tests/test_afm.py
- lib/matplotlib/tests/test_text.py
Since AFM is now private (though for some reason still in the docs), we can delete unused methods without deprecation.
Additionally, add `AFM.get_glyph_name` so that the PostScript mathtext code doesn't need to special case AFM files. …
> Clean up AFM code

- lib/matplotlib/backends/web_backend/js/mpl.js
CodeQL is now complaining about these. This should be okay since we only talk to ourselves, but better to be safe about it. …
> js: Fix externally-controlled format strings

- lib/matplotlib/colors.py
This small PR ensures that a `ValueError` is raised when the 'alpha' parameter is outside the valid range `[0, 1]`. This prevents silent failures and enforces proper input validation.
> Throw exception when alpha is out of bounds

- galleries/users_explain/text/fonts.py
We now subset Type-1 fonts and no longer have a copy of ttconv.
Make the font comparison table a grid table so we can use a colspan
cell.
Clarify that Type-1 fonts get used only in the usetex/pdf combination.
> Update font-related documentation

- lib/matplotlib/cbook.py
This seems to have changed in NumPy 2.3.0, only on Windows, but there's no reason to not catch this in the test always.
> TST: Fix runtime error checking NaN input to format_cursor_data

- galleries/examples/pie_and_polar_charts/polar_demo.py
This marginally expands the polar example to include examples of setting the limits, and using `rorigin`.
> DOC: expand polar example

- lib/matplotlib/backends/backend_pdf.py
- Use a simpler deterministic mapping of tex font names to pdf embedding names.
- Only resolve the required attributes when needed (in _embedTeXFont), which avoids e.g. having to carry around and worry about attributes with different names (e.g. "encoding" vs. "encodingfile").
followup to #30027.
> Simplify dviFontInfo layout in backend pdf.

- doc/api/prev_api_changes/api_changes_3.5.0/deprecations.rst
- doc/api/prev_api_changes/api_changes_3.7.0/removals.rst
Reference Issue #30211 
There is a typo in the release notes for matplotlib v3.5.0 and v3.7.0.
The item in this [link](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.5.0.html#miscellaneous-deprecations):
> `FancyArrowPatch.get_path_in_displaycoord` and `ConnectionPath.get_path_in_displaycoord` are deprecated. ...
`ConnectionPath` should be `ConnectionPatch`. There is no such a class as `ConnectionPath`.
> [Doc]: fix bug in release notes for matplotlib v3.5.0 and v3.7.0

- lib/matplotlib/projections/polar.py
- lib/matplotlib/spines.py
- lib/matplotlib/tests/test_polar.py
- lib/matplotlib/tests/test_spines.py
Fixes #30179.  The inner patch and spine positions are calculated in linear space, so we need to apply the scale's transform to min, max and origin.
The code from the OP now gives
The code from https://github.com/matplotlib/matplotlib/issues/30179#issuecomment-2990366910 now gives
The test image looks like
I note there is an existing PR at #30185, but it appears to me unlikely to progress. …
> Polar log scale: fix inner patch boundary and spine location

- lib/matplotlib/axes/_base.py
- lib/matplotlib/colorbar.py
- lib/matplotlib/tests/test_subplots.py
The subgridspec to be considered should be the one containing both the axes and the colorbar, not the sub-subgridspec of just the axes.
Closes #27305 (using https://github.com/matplotlib/matplotlib/issues/27305#issuecomment-1812446361 and a test).
> Fix label_outer in the presence of colorbars.

- .appveyor.yml
Let's see if this resolves the build error
--------
Previous description:
Call vcvars batch file in appveyor.yml
As per https://www.appveyor.com/docs/lang/cpp/
Recent Appveyor builds including #30232 and #30236 are failing with
<details><summary>log lines for <code> pip install -v --no-build-isolation --editable .[dev] </code></summary>
```
pip install -v --no-build-isolation --editable .[dev]
Using pip 25.1.1 from C:\Users\appveyor\AppData\Roaming\mamba\envs\mpl-dev\Lib\site-packages\pip (python 3.11)
Obtaining file:///C:/projects/matplotlib
Checking if build backend supports build_editable: started
Running command Checking if build backend supports build_editable
Checking if build backend supports build_editable: finished with status 'done'
Preparing editable metadata (pyproject.toml): …
```
> Upgrade to Visual Studio 2022 in appveyor.yml

- lib/matplotlib/artist.py
Make the difference between the two methods clearer (only the latter takes clipping into account).
> Tweak docstrings of get_window_extent/get_tightbbox.

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
This also has the side-effect of casting torch Tensors to NumPy arrays, which fixes #30216. Since `stem` is made up of `plot` and `[hv]lines` whic already do this cast, this just moves it up one level which prevents doing it twice.
We don't have any testing with torch directly, so I didn't add any of that sort. …
> Check that stem input is 1D

- lib/matplotlib/tests/test_backends_interactive.py
Since the Appveyor run is timing out, I went hunting for some low hanging fruit to speed up the tests. From the slower tests, this seemed like an obvious target as each run of the test is taking ~10 seconds. This seems to work fine.
Since gtk3cairo is disabled in this test, the comment doesn't seem relevant any more.
> Reduce pause time in interactive timer test

- .github/workflows/tests.yml
- azure-pipelines.yml
- lib/matplotlib/mlab.py
I only tested #30231 with a _single_ conflict. Unfortunately, the variable quoting did not work when there were multiple conflicts. This PR should fix that (and currently has a test change to verify it.) …
> ci: Fix image preload with multiple conflicts

- lib/matplotlib/mpl-data/matplotlibrc
The `None` value for `svg.fonttype` is invalid and causes a `ValueError`. This change replaces `None` with the valid string `'none'` to resolve the error.
> fix(config): Correct invalid value for svg.fonttype in matplotlibrc

- lib/matplotlib/axes/_axes.py
Closes #30285
This PR adds a whitespace following the word "or", resulting in a correctly formatted error message.
> Fix whitespace in _axes.py error message

- doc/sphinxext/redirect_from.py
- Only raise an error if trying to redirect one page to a *different* page to the one it's alraedy redirected to
- When raising the error, print the page that's trying to insert the conflicting redirect. This helps debugging where the error is coming from.
> Improve custom sphinx link redirect extension

- lib/matplotlib/typing.py
This PR update the `MarkerType`
- Add `Literal` for accepted `str` and `int` values
- Add `list` for accept [`verts`](https://matplotlib.org/stable/api/markers_api.html#module-matplotlib.markers:~:text=verts,the%20unit%20cell.)
- Add `tuple` for accept [regular polygon, star-like and asterisk](https://matplotlib.org/stable/api/markers_api.html#module-matplotlib.markers:~:text=(numsides%2C%200%2C%20angle),asterisk%20with%20numsides%20sides%2C%20rotated%20by%20angle.)
> [TYP] Add more literals to MarkerType

- doc/users/prev_whats_new/changelog.rst
This PR updates one of the links mentioned in #30306 :
http://www.voidspace.org.uk/python/configobj.html is defunct and is replaced with https://configobj.readthedocs.io/en/latest/
Updated link for configobj at ./doc/users/prev_whats_new/changelog.rst - previous link was inactive.
- [N/A] "closes #0000" is in the body of the PR description to [link the related issue](https://github.com/matplotlib/matplotlib/issues/30306) …
> fix broken configobj link

- lib/matplotlib/patches.py
Fixes #30323.  The code from https://github.com/matplotlib/matplotlib/issues/30323#issuecomment-3083500554 now produces
For now I have not added a test - as noted at https://github.com/matplotlib/matplotlib/issues/30323#issuecomment-3090023905
> The obvious test (set linewidth with a string) would represent a use-case that seems controversial amongst the maintainers, so I am not sure if we want that in there.
> FIX: cast Patch linewidth to float for dash scaling

- galleries/examples/user_interfaces/embedding_in_gtk4_panzoom_sgskip.py
- galleries/examples/user_interfaces/embedding_in_gtk4_sgskip.py
- lib/matplotlib/backends/backend_gtk4.py
Since GTK 4.12, fractional HiDPI is handled, but with a separate property on the backing surface due to it being a different type.
> Support fractional HiDPI in GTK4 backend

- doc/api/next_api_changes/deprecations/30349-AL.rst
- lib/matplotlib/axes/_base.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backend_tools.py
Axes.set_navigate_mode is explicitly documented as private, and one should just defer to the associated toolbar in any case, which is actually handling the relevant event callbacks (calling only set_navigate_mode had no practical effect).
> Axes can't set navigate_mode.

- doc/api/next_api_changes/deprecations/30368-AL.rst
- lib/mpl_toolkits/axisartist/grid_finder.py
- lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
> Switch get_grid_info to take a single Bbox as parameter.

- lib/matplotlib/axes/_axes.pyi
- lib/matplotlib/figure.pyi
- lib/matplotlib/legend.pyi
- lib/matplotlib/typing.py
Instead of accepting any str, we only accept as set of predefined literals. For simplicity, we don't distinguish the between allowed positions for Axes legend and figure legend. It's still better to limit the allowed range to the union of both rather than to accept abitrary strings.
This is a bit cumbersome, but since loc names are hard to remember and easy to misspell, I believe it's a real benefit if in-editor type checkers could notify on an invalid loc name.
> ENH: Type the possible str legend locs as Literals

- lib/matplotlib/mlab.py
- lib/matplotlib/tests/test_mlab.py
Unfortunately, I applied the change from
https://github.com/matplotlib/matplotlib/pull/29115#discussion_r2189746839 directly without noticing the typo, or running full tests.
So fix the swapped condition, and add a test (for `csd` only, which should be enough since everything goes though `_spectral_helper`.) This test should work on 64-bit systems as well, but I also double-checked on WASM. …
> Fix mlab fallback for 32-bit systems

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_collections.py
`autolim=True` is the default value, so no need to specify it.
> MNT: Remove explicit use of default value add_collection(..., autolim=True)

- doc/users/next_whats_new/sliders_callable_valfmt.rst
- lib/matplotlib/widgets.py
- lib/matplotlib/widgets.pyi
- Why is this change necessary? What problem does it solve?
I wanted to create a slider for an "order of magnitude" parameter, that scales logarithmic, but prints concisely the number in the `valfmt` parameter.
Somewhat based on the idea here:
- https://github.com/matplotlib/matplotlib/pull/19187
Example:
```python
from matplotlib.widgets import Slider
fig, ax=plt.subplots()
s = Slider(
ax=ax,
label=r"$\mathcal{O}(x)$",
valmin=0,
valmax=1,
#valfmt=lambda x: f"$10^{{{x:.1f}}}$",
valfmt=lambda x: f"{(10**x):.0f}"
)
s.on_changed(lambda x: print(10**x))
plt.show()
```
I'd like to get feedback before writing examples to documentation.
> {,Range}Slider: accept callable valfmt arguments

- lib/matplotlib/scale.py
Document the current state of of the about-to-be-removed *axis* parameter of Scales as given by #29349
and #29988.
> DOC: Scale axis parameter

- lib/mpl_toolkits/axes_grid1/axes_grid.py
- lib/mpl_toolkits/mplot3d/art3d.py
- lib/mpl_toolkits/mplot3d/axes3d.py
In docs, we rather specify "optional" instead of "default: None" when None is only used as a sentinel for "not given". We also specify prefer concrete types or rc references over None usage if possible.
> DOC: remove some usages of None as explicit defaults

- doc/api/next_api_changes/deprecations/29358-TH.rst
- lib/matplotlib/scale.py
- lib/matplotlib/tests/test_scale.py
> MNT: Registered 3rd party scales do not need an axis parameter anymore

- galleries/examples/pie_and_polar_charts/pie_features.py
- galleries/users_explain/text/text_props.py
- lib/matplotlib/__init__.py
- lib/matplotlib/contour.py
- lib/matplotlib/mpl-data/matplotlibrc
- lib/matplotlib/mpl-data/stylelib/classic.mplstyle
This PR documents the valid values and scaling factors for relative font sizes (`xx-small`, `x-small`, ...). Additionally, all mentions of `smaller`/`larger` are removed from other code since they [remain undocumented](https://github.com/matplotlib/matplotlib/issues/30437#issuecomment-3194486728).
Closes #30437
> Document relative font sizes

- galleries/users_explain/artists/color_cycle.py
- galleries/users_explain/axes/constrainedlayout_guide.py
It is a very small typo correction between **axis** and **axes**. It clarifies the notion in the text [here](https://matplotlib.org/stable/users/explain/axes/constrainedlayout_guide.html#legends) and [here](https://matplotlib.org/stable/users/explain/artists/color_cycle.html) as it is about axes and not axis.
- [N/A ] *New Features* and *API Changes* are noted with …
> Small correction of a typo in the galleries: axis instead of axes

- doc/missing-references.json
I thought this was because this branch was missing d2d969ef9d01297728c15c0fdfa957852201834b, but it was actually a change introduced in #30324 as a separate (but similar-looking) issue.
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-feat …
> DOC: Fix missing references on text-overhaul branch

- lib/matplotlib/contour.py
- lib/matplotlib/tests/test_contour.py
Note that 'color(s)' remains special-cased because the ContourSet constructor needs to do a fair bit of special wrangling for it.
Closes #1963.
> Use standard property alias machinery in contour().

- tools/triage_tests.py
If there's only check_figure_equals tests in a module (e.g. test_pickle, test_axis) then there's no directory in the baseline_images test, but it still makes sense to run triage_tests in case of test failure. Previously, the missing directory caused an error; this patches fixes that.  To test this, change e.g. one of the check_figures_equal tests in test_pickle to make it fail, run that test, and run tools/triage_tests.py.
Closes #29774 (I ran again into the same issue for #30467).
> Let triage_tests support test modules with only figure_equals tests.

- lib/matplotlib/colorizer.py
The @vmin.setter in Normalize (and its subclasses) call colors._sanitize_extrema(), so there is no reason to also do so in Colorizer.
This PR is intended to slightly clean the code before it is modified as the inclusion of MultiNorm https://github.com/matplotlib/matplotlib/pull/29876 and related PRs is propagated to the Colorizer in a future PR.
> No need to sanitize extrema in Colorizer.set_clim

- .github/workflows/cibuildwheel.yml
- pyproject.toml
Our dependencies now have wheels for that platform.
> ci: Remove cibuildwheel override for win_arm64/Py3.14

- lib/matplotlib/backends/_backend_tk.py
Closes #30390.
I've tested this locally. I don't think there's a reasonable way to test this in CI unless we are actually willing to do a uv install for this. Mocking the exception does not bring any benefit in detecting whether the error has changed, so would be largely futile.
> ENH: Gracefully handle python-build-standalone ImportError with Tk

- lib/matplotlib/backends/backend_qt.py
- requirements/testing/all.txt
This can fail if the c++ side of the object has already been cleaned up but the Python side is still lingering (due to refs in callbacks).
closes #29618
I do not think it is worth constructing a test to generate this case, but in the case where I saw it in the wild this fixed the tests locally for me.
- [/] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [/] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [/] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and …
> FIX: be more cautious about checking widget size

- README.md
Congrats! We have onboarded matplotlib to LFX Insights, the Linux Foundation's platform for monitoring the world's most critical open-source projects.
https://insights.linuxfoundation.org/project/matplotlib
> Add Linux Foundation Health Score badge to README

- doc/api/next_api_changes/deprecations/30364-AS.rst
- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/mplot3d/tests/test_axes3d.py
This PR closes #30364 .
This PR cleans up the `Axes3D.set_aspect` method by deprecating the unused `anchor` parameter and clarifying the documentation for 3D-specific behavior.
- **Why is this change necessary?** The method inherited the `anchor` and `adjustable` parameters from its 2D parent, but these are confusing and not applicable in a 3D context. This led to an inaccurate docstring.
- **What problem does it solve?** It removes a confusing, non-functional parameter from the API and provides users with clear, accurate documentation for how `set_aspect` behaves on 3D axes.
- **What is the reasoning for this implementation?**
- A conditional warning is now raised inside the method if `anchor` is used, making the deprecation clear to users without breaking existing tests that rely on the …
> MNT/DOC: Deprecate anchor in Axes3D.set_aspect

- lib/matplotlib/tests/test_image.py
The test `test_image.test_image_cursor_formatting()` is intended to test mouseover formatting of masked image data. 
see issue https://github.com/matplotlib/matplotlib/issues/15103 and resolution in PR https://github.com/matplotlib/matplotlib/pull/15140 . 
```py
def test_image_cursor_formatting():
im = ax.imshow(np.zeros((4, 4)))
data = np.ma.masked_array([0], mask=[True])
assert im.format_cursor_data(data) == '[]'
...
```
However, this test does not work as intended, because it `Artist.format_cursor_data()` will in normal circumstances call `_ColorizerInterface._format_cursor_data_override()`:
```py
def format_cursor_data(self, data):
if np.ndim(data) == 0 and hasattr(self, "_format_cursor_data_override"):
return self._format_cursor_data_override(data)
...
``` …
> removed test_image_cursor_formatting()

- lib/matplotlib/tests/test_backend_qt.py
This avoids having to manually clean up the resulting file, which seems flaky.
Fixes #30493
> TST: Use a temporary directory for test_save_figure_return

- lib/matplotlib/axes/_base.py
It can't be right that we set `_adjustable` on all siblings (including self), but only mark self as stale.
While at it, I've slightly improved the documentation.
> FIX: Mark shared Axes as stale when propagating adjustable

- doc/api/next_api_changes/behavior/30335-ES.rst
- lib/matplotlib/_mathtext.py
- lib/matplotlib/_text_helpers.py
- lib/matplotlib/backends/_backend_pdf_ps.py
- lib/matplotlib/backends/backend_cairo.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/dviread.pyi
- lib/matplotlib/tests/test_backend_pdf.py
- lib/matplotlib/tests/test_backend_svg.py
- lib/matplotlib/textpath.py
With libraqm, string layout produces glyph indices, not character codes, and font features may even produce different glyphs for the same character code (e.g., by picking a different Stylistic Set). Thus we cannot rely on character codes as unique items within a font, and must move toward glyph indices everywhere.
~~The only thing I don't quite like is that PDF uses character codes for its lookup, and I have to map glyph indices back through an inverse charmap. I think I may have to send everything through `CharacterTracker` and produce my own limited charmap, but still need to test out what's required.~~ Better stuff for this is done in #30512.
~~This is based on #30143.~~ …
> Use glyph indices for font tracking in vector formats

- lib/matplotlib/backends/_backend_pdf_ps.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_ps.py
By tracking both character codes and glyph indices, we can handle producing multiple font subsets if needed by a file format.
This was split out of #30512, but based on #30335. …
> pdf/ps: Track full character map in CharacterTracker

- .github/workflows/tests.yml
The VM is being dropped by GH [1] on macOS is no longer supported by homebrew or Apple.
This job is starting to fail on installing homebrew dependencies.  Rather than try to fix this, move on to the next image which we need to do by the end of the CY anyway.
This means we no longer are testing on intel macs.
[1] https://github.blog/changelog/2025-07-11-upcoming-changes-to-macos-hosted-runners-macos-latest-migration-and-xcode-support-policy-updates/#macos-13-is-closing-down
> CI: remove macos13

- .github/workflows/tests.yml
Conflict is oldest macOS is Python 3.10 here, instead of 3.11 on `main`. …
> Backport PR #30571 on branch v3.10.x (CI: remove macos13)

- lib/matplotlib/colors.py
A refactoring pulled out of #30531, because it's a standalone change that can be reviewed simple on its own. This will make the deprecation in #30531, and in particular handling of it in our test suite much simpler.
The behavior is 100% percent backward compatible as far as public API and behavior is concerned.
> MNT: Move all Colormap extremes setter logic into a single _set_extremes()

- src/_path.h
- src/_path_wrapper.cpp
By replacing double pointers by `std::array` and returned tuples. AFAICT, this doesn't have any effect on code size, but ensures that several places are checked at compile time. And for now, we already know these to be correct, but this would prevent any future problems if some sizes change.
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecatio …
> Make path extension a bit safer

- .github/workflows/tests.yml
- lib/matplotlib/tests/test_axes.py
Since earlier today, the `ubuntu-22.04-arm` image has actually been Ubuntu 24.04. Instead of working out how to fix that, switch to the newer image explicitly.
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-page …
> ci: Bump Ubuntu ARM builder to 24.04

- lib/matplotlib/contour.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_colorbar.py
- lib/matplotlib/tests/test_colors.py
- lib/matplotlib/tests/test_contour.py
- lib/matplotlib/tests/test_image.py
- lib/mpl_toolkits/mplot3d/tests/test_axes3d.py
- lib/mpl_toolkits/mplot3d/tests/test_legend3d.py
Instead use the more modern ways to specify extremes during Colormap creation or using `with_extremes()`
This is in preparation of deprecating setters in #30531.
> MNT: Do not use colormap setters in tests

- src/ft2font.cpp
- src/ft2font.h
The former may be used even on PS/PDF backend where nothing is rendered.
I split this out of the actual vector backend changes because it's mostly independent and doesn't need to wait for other PDF code refactors. …
> ft2font: Split layouting from set_text

- doc/api/next_api_changes/deprecations/30512-ES.rst
- doc/release/next_whats_new/pdf_fonts.rst
- lib/matplotlib/backends/_backend_pdf_ps.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/testing/__init__.py
- lib/matplotlib/tests/test_backend_svg.py
For character codes outside the embedded font limits (256 for type 3 and 65536 for type 42), we output them as `XObject`s instead of using text commands. But there is nothing in the PDF spec that requires any specific encoding like this.
Since we now support subsetting all fonts before embedding, split each font into groups based on the maximum character code (e.g., 256-entry groups for type 3), then switch text strings to a different font subset and re-map character codes to it when necessary.
This means all text is true text (albeit with some strange encoding), and we no longer need any XObjects for glyphs. For users of non-English text, this means it will become selectable and copyable again.
There are 3 steps to achieve this change:
1. Track both character codes and glyphs in …
> pdf: Improve text with characters outside embedded font limits

- lib/matplotlib/patches.py
- lib/mpl_toolkits/axes_grid1/axes_grid.py
- lib/mpl_toolkits/axes_grid1/tests/test_axes_grid1.py
The `ngrids` deprecation was missing the version, and style registration incorrectly included the micro version. …
> MNT: Fix some broken deprecations

- galleries/users_explain/text/mathtext.py
This PR closes #30574.
This PR corrects a small typo in the Matplotlib documentation.
- **Why is this change necessary?** The `mathtext` tutorial contained an example for rendering Unicode characters (`r'$\u23ce$'`) that used a raw string (`r''`).
- **What problem does it solve?** Using a raw string prevents Python from interpreting the `\u` escape sequence, causing the example code to crash with a `ParseFatalException`. This could be confusing for users who copy and paste the example directly from the documentation.
- **What is the reasoning for this implementation?** The fix is to simply remove the `r` prefix from the example string, allowing the Unicode escape sequence to be correctly parsed. This makes the documentation accurate and the example functional.
- [N/A] new and changed code …
> DOC: Fix raw string in mathtext unicode example

- lib/matplotlib/backends/_backend_pdf_ps.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_ps.py
The original code split fonts into subsets based on the character modulo the subset size (determined by font type limits). This had some limitations:
1. If characters were used from across various font blocks (especially for type 3, whose blocks were only 256 characters), then there would be many, possibly sparsely-populated, font subsets.
2. Sometimes a single character code may map to multiple glyphs. This is the case if you mix languages (i.e., #29794), but the naive tracking would only produce one glyph.
3. Sometimes multiple characters can map to a single glyph. This is the case for ligatures, and also with complex text shaping (such as Arabic), and this would just fail calling `ord` on a multi-char string.
To fix this, `CharacterTracker` now tracks characters and glyphs more …
> Prepare `CharacterTracker` for advanced font features

- doc/api/next_api_changes/behavior/30634-AL.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Standard autoscaling works just fine there.
Re-closes #3815 (which had previously only been closed by documenting the old behavior; the discussion on that thread clearly suggests that that behavior is not desirable).
> Don't force axes limits in hist2d.

- galleries/users_explain/colors/colormapnorms.py
Fixes #22197
This PR adds a documentation note to the Colormap Normalization tutorial explaining how users can restore the pre-3.5 linear colorbar spacing for `TwoSlopeNorm` and other norms with a scale.
- Added a note section after the `TwoSlopeNorm` example in `galleries/users_explain/colors/colormapnorms.py`
- Documents that colorbars for norms with a `scale` use that scale by default (behavior introduced in matplotlib 3.5)
- Explains the `cb.ax.set_yscale('linear')` workaround for users who prefer linear spacing
Since matplotlib 3.5, colorbars for norms with a scale (like `TwoSlopeNorm`) display the scale in the colorbar itself, which can appear non-linear. While this is consistent with other scaled norms like `LogNorm`, many users expect or prefer the linear spacing behavior from …
> DOC: Add note about linear colorbar scale option for TwoSlopeNorm
