- lib/matplotlib/backends/backend_webagg_core.py
> FIX: Webagg `save_figure` - Raise a Warning Instead of an Error

- lib/matplotlib/backends/backend_wx.py
Should also improve performance and LnF on all platforms.
Compatible with at least wxPython 3.0.x and 2.[89].x.
See issue #3734
> draw_idle and draw_rubberband fixes for wxPython on OSX.

- lib/matplotlib/backends/backend_pgf.py
- lib/matplotlib/backends/backend_webagg_core.py
> pgf can not write to `BytesIO` [back port to 1.4.x]

- .travis.yml
Forgot to change this in #3939
> Fix stupid typo

- lib/matplotlib/animation.py
As  discussed in #4003 
Regarding whitespace changes -- PEP8 is violated like everywhere, can't stand it.
> Provide arguments to mencoder in a more proper way

- .travis.yml
- lib/matplotlib/tests/test_animation.py
> Try to fix mencoder tests. [backport to 1.4.x]

- lib/matplotlib/backends/web_backend/mpl.js
- lib/matplotlib/backends/web_backend/nbagg_mpl.js
> Disable context menu in webagg

- lib/matplotlib/animation.py
- lib/matplotlib/colors.py
- lib/matplotlib/tests/test_colors.py
> BUG : fix PowerNorm with scalars

- lib/matplotlib/image.py
> Slightly improved getstate call based on feedback from Thomas Cuypers.

- src/_macosx.m
This is related to issue #3991. Until now the MacOSX backend did not deliver interrupts while the event loop is running as Python itself would ignore those interrupts anyway. This PR allows interrupts to be delivered once Python is fixed.
> Allow interrupts to be delivered once Python is fixed.

- lib/matplotlib/pyplot.py
Correct docstring typo in subplot2grid.
> DOC: Correct docstring typo in subplot2grid

- lib/matplotlib/tests/baseline_images/test_backend_svg/bold_font_output.svg
> MNT : fix text-based text with new advance-width

- doc/api/api_changes/2015-03-03-LEO.rst
- doc/users/whats_new/2015-03-03_locator-set_params.rst
Added 'api_changes' and 'whats_new' docs on bug fix for issue #3658 with pull request #4172
> Adding 'api_changes' and 'whats_new' docs for PR #4172

- INSTALL
Updated dead links for pip and pillow in the INSTALL text
> Updated links in INSTALL

- lib/matplotlib/backends/backend_cairo.py
+ Fixes https://github.com/matplotlib/matplotlib/issues/4054
> backend_cairo: Clip drawn paths to context.clip_extents()

- doc/users/plotting/colormaps/grayscale.py
- doc/users/plotting/colormaps/lightness.py
Fixed errors introduced by https://github.com/matplotlib/matplotlib/pull/3975
> DOC: Colormap synonyms in examples, fix errors caused by removing duplicates

- lib/matplotlib/backends/backend_macosx.py
- lib/matplotlib/font_manager.py
> forcing weight to int

- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/mlab.py
- src/_path.h
- src/_path_wrapper.cpp
This is an optimization I've meant to implement for a long time.
The hottest spot performance-wise in the PDF and PS backends is the conversion of Path objects to a string of commands to draw that path.  This has been done in C++ in the SVG backend for a long time -- this generalizes that code to make it usable in the PDF and PS backends as well.
> Generate path strings in C++ for PDF and PS

- doc/users/whats_new/updated_pyplot.rst
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_figure.py
Added the ability to check the existance of a figure label instead of just figure number. #2880
> Implemented new feature for Issue #2880

- doc/devel/testing.rst
Suggest only creating png base-line images by default.
> DOC : update testing docs

- lib/matplotlib/tri/tricontour.py
Tiny typo I found while using `tricontour.py`.
> Minor typo fix.

- examples/color/named_colors.py
I made minor stylistic changes (figure, axis creation) to this example.  This is the first of what I intend to be a series of small pull requests (and is actually my first PR ever), working through the examples folder-by-folder and updating as necessary.
> STY: update example with preferred plt.subplots

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/blocking_input.py
- lib/matplotlib/contour.py
- lib/matplotlib/figure.py
- lib/matplotlib/finance.py
- lib/matplotlib/image.py
- lib/matplotlib/mlab.py
- lib/matplotlib/patches.py
- lib/matplotlib/path.py
- lib/matplotlib/projections/geo.py
- lib/matplotlib/projections/polar.py
- lib/matplotlib/rcsetup.py
- lib/matplotlib/sankey.py
- lib/matplotlib/scale.py
- lib/matplotlib/spines.py
- lib/matplotlib/streamplot.py
- lib/matplotlib/table.py
- lib/matplotlib/tests/test_rcparams.py
- lib/matplotlib/text.py
- lib/matplotlib/ticker.py
- lib/matplotlib/transforms.py
- lib/matplotlib/tri/tripcolor.py
- lib/matplotlib/widgets.py
A few days I ago I was experimenting for a possible answer to [this question](http://matplotlib.1069221.n5.nabble.com/Re-combine-different-axes-to-make-new-figure-in-matplotlib-td43385.html). While trying
fig1, ax1 = plt.subplots()
fig2, ax2 = plt.subplots()
fig2.add_axes(ax1)
I stumbled into an `AssertionError` without any explanation (I had to get the doc of `add_axes`). 
My understanding is that `assert` should be reserved for debugging, not to throw errors if the user give a wrong parameter. So I've converted them to exception. 
I've also noticed that `assert` is used all over the places. If there are no strong opinions in the next weeks I'll to go through the code and convert them to exceptions.
> converted assert into exception

- doc/users/whats_new/updated_figimage.rst
- lib/matplotlib/figure.py
- lib/matplotlib/image.py
See #3420 ,
Tried implementing the feature by adding a "resize" parameter in the figimage, which resizes the figure based on the image size.
> added resize parameter to plot 2d-arrays using figimage

- doc/users/whats_new/updated_widgets.rst
- lib/matplotlib/widgets.py
Implemented MultiCursor disable function. Now can disable the multi cursor the same way as Cursor; using "cursor.active = False" 
( #2663)
> Provide way to disable Multi Cursor (Implement #2663)

- lib/matplotlib/mlab.py
- lib/matplotlib/tests/test_mlab.py
> BUG : fix scaling issue with mlab.psd and odd NFFT

- doc/api/ticker_api.rst
- lib/matplotlib/ticker.py
Make sure that StrMethodFormatter is documented and exposed.
> DOC/API : StrMethodFormatter

- lib/matplotlib/axes/_axes.py
everyerror should be errorevery
> fix typo in errorbar docs

- lib/matplotlib/collections.py
- lib/matplotlib/lines.py
- lib/matplotlib/patches.py
> DOC : revert some documentation changes from #3772

- .travis.yml
> Travis, remove quite and verbose from nosetest flags

- .travis.yml
- tools/travis_tools.sh
* Install into our own pristine virtualenv;
* Use travis wheels for dependencies.
> MRG: use travis wheels for dependencies

- doc/conf.py
- doc/users/whats_new/updated_backend_wx.rst
- examples/user_interfaces/embedding_in_wx2.py
- examples/user_interfaces/embedding_in_wx3.py
- examples/user_interfaces/embedding_in_wx4.py
- examples/user_interfaces/embedding_in_wx5.py
- examples/user_interfaces/fourier_demo_wx.py
- examples/user_interfaces/mathtext_wx.py
- examples/user_interfaces/wxcursor_demo.py
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/backends/backend_wxagg.py
- lib/matplotlib/backends/wx_compat.py
- lib/matplotlib/tests/test_coding_standards.py
This is based on the comments made to my previous PR for this.
Note that wxPython Phoenix snapshots can now be installed with pip:
pip install -U --pre -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix
> make wx backends compatible with wxPython-Phoenix

- doc/users/whats_new/2015-01-19_cursor_pixel_data.rst
- doc/users/whats_new/2015-01-19_cursor_zdata.rst
- lib/matplotlib/artist.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/image.py
- lib/matplotlib/tests/test_image.py
Also adds implementation for `AxesImage`.  Closes #3984.
Inspired by [mpldatacursor](https://github.com/joferkington/mpldatacursor).
> Allow Artists to show pixel data in cursor display

- lib/matplotlib/axes/_axes.py
Just adding some missing info to the docstring.
> Minor improvements to the docstring of `step`.

- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/backends/backend_wxagg.py
This should hopefully resolve Issue #4460 and #4461.
I hope @jenshnielsen could give it a try on his MAC, it works for me on Win10 with Py2.7 and Py3.4.
> Problems with mpl.pyplot

- doc/resources/index.rst
Add a link in the docs to the new book by @WeatherGod.
> Add link to new book

- README.osx
- change name for brew -> pkg-config (pkgconfig is alais)
- add pkgconfig for macports
attn @jenshnielsen
> DOC: mac + pkg-config

- lib/matplotlib/tests/test_agg.py
- src/_backend_agg.cpp
Fix #4407.
The cell block calculation changed between agg 2.4 and agg-svn, so we need to increase the value.
> Fix path length limit

- lib/matplotlib/backends/backend_tkagg.py
Thanks for the tip @joferkington
> Get rid of annoying border for Tk Canvases

- .gitignore
- examples/pylab_examples/leftventricle_bulleye.py
Replaces #3518
Going to self-merge this as it is primarily the work of @curiale, I just added minor documentation + white space changes.
> Doc AHA bullseye

- .gitignore
- examples/pylab_examples/leftventricle_bulleye.py
In this example we create the bull eye representation for the left ventricle according to the American Heart Association (AHA)
> Left ventricle bull eye

- lib/matplotlib/_pylab_helpers.py
- lib/matplotlib/backends/backend_gtk.py
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_macosx.py
- lib/matplotlib/backends/backend_nbagg.py
- lib/matplotlib/backends/backend_qt5.py
- lib/matplotlib/backends/backend_tkagg.py
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/backends/backend_wxagg.py
- lib/matplotlib/pyplot.py
Fixes one of the issues raised in comments on https://github.com/matplotlib/matplotlib/commit/b2fbae76c738d5c24e559b98ed494e9b146c16aa
This needs testing on gtk, gkt3, wx, and osx, but I am pretty confident it will work (or at least do no harm).
> Fix draw on show

- doc/users/whats_new/2014-12-23_usetex.rst
- doc/users/whats_new/2015-03-03_locator-set_params.rst
- doc/users/whats_new/autowrap_text.rst
- doc/users/whats_new/axis3d.rst
- doc/users/whats_new/cbook.rst
- doc/users/whats_new/datelocators.rst
- doc/users/whats_new/linestyles.rst
- doc/users/whats_new/pdfpages_notes.rst
- doc/users/whats_new/plotting.rst
- doc/users/whats_new/updated_backend_wx.rst
- doc/users/whats_new/updated_figimage.rst
- doc/users/whats_new/updated_figure.rst
- doc/users/whats_new/updated_pyplot.rst
- doc/users/whats_new/updated_scale.rst
- doc/users/whats_new/updated_table.rst
- doc/users/whats_new/updated_widgets.rst
Start at cleaning up the rst in whats_new.
> DOC: clean up rst in whats_new folder

- lib/matplotlib/figure.py
Fixed a simple typo in the set_canvas docstring
> Fixed typo in docstring #4562 

- lib/matplotlib/contour.py
> DOC: clairify auto-level behavior

- lib/matplotlib/texmanager.py
> FIX: accept non-ascii in dvipng --version output

- lib/matplotlib/backends/qt_editor/figureoptions.py
> FIX: handle empty legend in qt figureoption

- examples/pylab_examples/accented_text.py
plt and np imports instead of pylab
> translated pylab import to plts

- examples/pylab_examples/equal_aspect_ratio.py
1. Changed from pylab import * to import matplotlib.pyplot as plt, and
import numpy as np.
2. Quick test done on local ipython environment.
> Fixed and classified equal_aspect_ratio.py

- examples/pylab_examples/usetex_fonteffects.py
Please merge asap to fix docs build of master
> usetex_fonteffects.py: Import matplotlib here as needed

- examples/pylab_examples/usetex_fonteffects.py
> PEP8 fix usetex_fonteffects

- examples/pylab_examples/zorder_demo.py
Changes:
1. Changed pylab namespace to matplotlib and numpy.
2. Added titles to figure plots to highlight z-order edits.
> MEP12 pylab changes on zorder_demo.py

- examples/pylab_examples/subplots_adjust.py
Placed under wrong branch, but it’s okay.
> MEP12 on subplots_adjust.py

- examples/pylab_examples/transoffset.py
Changes:
1. MEP12.
2. PEP8 on syntax.
> MEP12 on transoffset.py

- examples/pylab_examples/usetex_demo.py
> Mep12 usetex

- examples/pylab_examples/barchart_demo2.py
- examples/pylab_examples/barcode_demo.py
- examples/pylab_examples/boxplot_demo.py
- examples/pylab_examples/break.py
- examples/pylab_examples/clippedline.py
> MEP12-on-barchart_demo2.py

- lib/matplotlib/sphinxext/plot_directive.py
> minor typo in docstring

- lib/matplotlib/axes/_base.py
- lib/matplotlib/tests/test_axes.py
Fixes #4450
Or at least the scary part of the scale change not propagating
to all shared axes.
> FIX: update scale on shared axes

- lib/matplotlib/backends/backend_agg.py
> CLN: remove unused code path

- examples/images_contours_and_fields/streamplot_demo_start_points.py
- lib/matplotlib/streamplot.py
- setup.py
> STY: pep8 that slipped by the tests

- examples/pylab_examples/system_monitor.py
Gets a frame rate of ~75fps on my machine
This also seems to be the example that travis is choking on.
> DOC: slightly update demo

- lib/matplotlib/backends/backend_pdf.py
The close_and_paint method and therefore the first argument to Op.paint_path were unused. Also change all occurrences of fillp and strokep to be just fill and stroke (the -p ending is a Lisp thing).
> MNT: Remove unused code in pdf backend

- doc/users/whats_new/rcparams.rst
> DOC: whats_new for axes.labelpad

- examples/pylab_examples/axes_props.py
> MEP12 on axes_props.py

- examples/pylab_examples/anscombe.py
ported pylab calls to plt and np
> MEP12-on-anscombe.py

- examples/pylab_examples/arrow_demo.py
> MEP12-on-arrow_demo.py

- examples/pylab_examples/axis_equal_demo.py
> MEP12 on axis_equal_demo.py

- examples/pylab_examples/vline_hline_demo.py
1. Explicitly stated where functions are imported from.
> Standardized imports

- lib/matplotlib/mathtext.py
- lib/matplotlib/tests/test_backend_ps.py
Followed suggestion of @pgnub
Closes #3473
Adds test coverage for afm handling
> FIX: fix afm + py3k + logscale

- lib/matplotlib/__init__.py
Closes #4715
Adds a third entry to the value tuple in _deprecated_map to allow
specifying an inverse map from the new value to the old.
attn @WeatherGod  This along the idea of what you want?
> ENH: add inverse function to _deprecated_map

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Make sure we don't try to convert unicode strings to ascii
closes #4765
> FIX: fix python2 unicode compatibility

- examples/pylab_examples/mri_demo.py
Cherrypicked from #4869 to avoid an extra merge commit
> mep12 on mri_demo.py

- lib/matplotlib/backends/backend_cairo.py
Cousin commit to #4202 for cairo.
> Fix cairo graphics context

- doc/faq/usage_faq.rst
- doc/glossary/index.rst
- added qt5 to backend table
- updated glossary with new qt urls + qt5
> DOC: update qt related prose

- examples/pylab_examples/system_monitor.py
- lib/matplotlib/animation.py
- lib/matplotlib/artist.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/figure.py
- lib/matplotlib/image.py
- lib/matplotlib/offsetbox.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_tightlayout.py
> MNT: overhaul stale handling

- examples/pylab_examples/color_by_yvalue.py
- examples/pylab_examples/color_demo.py
- examples/pylab_examples/contour_image.py
- examples/pylab_examples/coords_demo.py
- examples/pylab_examples/coords_report.py
Rebase of #4729 on master with a tiny pep8 fix
> Colormep12rebase

- doc/api/api_changes/2015-08-16_remove_lena_from_sample_data.rst
Follow up to #4928 
Last part of #4927
> Add api change note about lena removal

- lib/matplotlib/backends/backend_nbagg.py
- lib/matplotlib/backends/backend_webagg_core.py
- lib/matplotlib/backends/web_backend/nbagg_mpl.js
- lib/matplotlib/backends/web_backend/nbagg_uat.ipynb
Add callback to destroy figure when the user hits the red x
in the notebook.
This is not the correct solution, but it (might) work for now.
closes #4281 ?
> FIX : first pass at fixing nbagg close issue

- doc/users/pyplot_tutorial.rst
This is an attempt to disambiguate the axes part of a figure from the mathematical term "axes".
> Clarify what "axes" means

- lib/matplotlib/lines.py
- lib/matplotlib/tests/test_artist.py
> FIX: account for None in Line2D.axes setter

- doc/api/api_changes/2015-08-29-custom-axes-view.rst
> DOC: Add information on new views for custom Axes.

- examples/animation/dynamic_image.py
- examples/animation/dynamic_image2.py
- examples/animation/histogram.py
- lib/matplotlib/animation.py
Using draw was triggering infinite recursion, using draw_idle does not.
This fixes the recursion depth reported in #4967
attn @WeatherGod
> animation fixes

- lib/matplotlib/lines.py
This also streamlines the handling of masked arrays and subslices in recache and draw.
> support subslicing when x is masked or has nans; closes #5016

- doc/users/whats_new/updated_widgets.rst
> Update what's new for RectangeSelector

- examples/showcase/bachelors_degrees_by_gender.py
Fix ValueError: zero length field name in format
> Fix format string for Python 2.6

- doc/api/api_changes.rst
- doc/users/whats_new.rst
Typos in api_changes and whats_new in 1.5.0 RC 1.
> Typos in api_changes and whats_new

- examples/tests/backend_driver.py
> Fix backend_driver.py fails on non-existent files

- lib/matplotlib/tests/test_triangulation.py
- lib/matplotlib/tri/tritools.py
Bugfix for a second incidence of issue #4999.  See PR #5065.
Includes an explicit test.
> Bugfix for TriAnalyzer mismatched indices, part 2

- INSTALL
Addresses issue @cgohlke rasied.
> DOC: updated documented dependencies

- doc/users/whats_new.rst
Reorganizing, make a table, fixed grammar/spelling, added more links where I could find them.
There are a lot of inconsistent styling that we should probably be more attentive to in future pull requests. There is much too much stuff here for me to fix all of it, but I think I got it much better than before.
> Improve whats new

- INSTALL
> Add WinPython and Cycler to installation instructions for Windows

- setup.py
closes #5113
maybe #5077 
attn @efiring @michaelaye
> BLD: setup.py magic to get versioneer to work

- examples/pylab_examples/cursor_demo.py
This is the last of them from the `pylab_examples` folder!
> mep12 on cursor_demo.py

- src/numpy_cpp.h
The bug was noticed by @cgohlke in the discussion for #5105.
closes #5105
> Fix a bounds check

- lib/matplotlib/axes/_base.py
> [BUG] symlog support for ax.minorticks_on()

- examples/pylab_examples/agg_buffer.py
Image.fromstring was removed in Pillow 3.0.
Also added missing numpy import.
> Fix exception with Pillow 3

- doc/users/pyplot_tutorial.rst
Only minor changes to grammar, etc.
> Cleaned up text in pyplot_tutorial.rst

- lib/matplotlib/backends/qt_compat.py
> FIX: remove incorrect error checking

- lib/matplotlib/font_manager.py
- lib/matplotlib/tests/test_font_manager.py
> Use json for the font cache instead of pickle

- lib/matplotlib/ticker.py
> [MAINT] Add symlog locator to __all__ and to the docs

- lib/matplotlib/rcsetup.py
> FIX: fix default flier line style

- lib/matplotlib/streamplot.py
Crashes with numpy 1.10.
Fix #5229.
> Fix casting bug in streamplot

- lib/matplotlib/cbook.py
> FIX: subtle race condition in cbook.mkdirs

- README.rst
> DOC: tweak README formatting

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
> Fix bar labels

- doc/users/customizing.rst
- lib/matplotlib/__init__.py
First part of #5268 for 1.5.0.
> Document $MATPLOTLIBRC

- doc/users/colormaps.rst
- doc/users/plotting/colormaps/Lfunction.py
- doc/users/plotting/colormaps/colormaps.py
- doc/users/plotting/colormaps/grayscale.py
- doc/users/plotting/colormaps/lightness.py
- examples/color/colormaps_reference.py
> Backport Merge pull request #5284 from mdboom/colormap-docs

- doc/faq/index.rst
- doc/faq/virtualenv_faq.rst
- src/_macosx.m
The writing could probably still use some work.
> Add documentation about working in virtualenvs to the Matplotlib faq

- examples/pylab_examples/demo_bboximage.py
- lib/matplotlib/cm.py
- lib/matplotlib/colors.py
> Make new colormaps full-fledged citizens

- src/_macosx.m
This is a preliminary fix for issue #5251
> Prelimiary fix for Mac OSX backend threading issues

- lib/matplotlib/axes/_axes.py
> Fix #5316: Remove hardcoded parameter from barh doc

- .travis.yml
- setupext.py
It has broken python 3 support due to print statements in the code.
Just released today so hopefully there will be a new release soon fixing this
> Make sure that pyparsing 2.0.4 is not installed.

- setup.cfg.template
- setup.py
- setupext.py
supersedes #5103
Adds code @mdboom left in comments.
> windows dlls packaging 

- .gitignore
- INSTALL
- doc/devel/testing.rst
- doc/users/github_stats.rst
- doc/users/whats_new.rst
- tools/gh_api.py
- tools/github_stats.py
- unit/memleak_hawaii3.py
Branch I am dumping commits on as I start to do the release.  I am re-writing the release guide as I go.
> 1.5.0 final work

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/mpl-data/stylelib/classic.mplstyle
- lib/matplotlib/rcsetup.py
- matplotlibrc.template
Tiny fix: antialised => antialiased
https://github.com/matplotlib/matplotlib.github.com/pull/13
> Fixed typo

- doc/users/whats_new/2015-10-31_TransformedPatchPath.rst
> DOC: Add what's new entry for TransformedPatchPath.

- doc/style_changes.rst
> Updating 2.0 schedule

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
> Apply asanyarray to arguments for pcolor and family

- src/_backend_agg.h
> Don't draw text when it's completely clipped away

- lib/matplotlib/font_manager.py
Since we no longer ship Vera.
Follow-on to #5214
> Use DejaVu Sans as default fallback font

- lib/matplotlib/rcsetup.py
- lib/matplotlib/tests/test_cycles.py
- lib/matplotlib/tests/test_rcparams.py
Cherry-picked, and added a commit to modify the tests so that they can run in python 2.6.
> Backport #5452

- README.rst
- doc/devel/release_guide.rst
- doc/devel/testing.rst
Docs part of #5434 against the 1.5.0-doc branch
> Change docs to recommend tests.py rather than setup.py test

- lib/matplotlib/backends/backend_agg.py
- lib/matplotlib/image.py
- src/_png.cpp
Possible fix fo #5495, but honestly quite theoretical.
> Fix some theoretical problems with png reading

- lib/matplotlib/axes/_axes.py
> Fix docstring of violin{,plot} for return value.

- doc/api/api_changes.rst
- doc/users/plotting/colormaps/Lfunction.py
- examples/pylab_examples/axes_demo.py
- examples/pylab_examples/color_demo.py
- examples/pylab_examples/finance_work2.py
- examples/pylab_examples/fonts_demo.py
- examples/pylab_examples/fonts_demo_kw.py
- examples/pylab_examples/image_origin.py
- examples/pylab_examples/logo.py
- examples/pylab_examples/mathtext_demo.py
- examples/pylab_examples/mathtext_examples.py
- examples/pylab_examples/matplotlib_icon.py
- examples/pylab_examples/polar_legend.py
- examples/pylab_examples/quadmesh_demo.py
- examples/widgets/cursor.py
- examples/widgets/slider_demo.py
- examples/widgets/span_selector.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/figure.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_image.py
- lib/matplotlib/widgets.py
Partial fix for #5309 (the second bullet point).
This deprecates axisbg and axis_bgcolor (which are axis-specific properties) in favor of facecolor.
> Use facecolor instead of axisbg/axis_bgcolor

- lib/matplotlib/widgets.py
> fix small typo in documentation about CheckButtons.

- lib/matplotlib/backends/qt_editor/figureoptions.py
Fixes the first two points of #5341.
> Sort and uniquify style entries in figure options.

- doc/users/whats_new/ticks_rcparams.rst
- lib/matplotlib/mpl-data/stylelib/classic.mplstyle
- lib/matplotlib/rcsetup.py
- lib/matplotlib/tests/test_rcparams.py
> DOC: add missing whatsnew + classic style to #5503

- lib/matplotlib/dates.py
Please review this fix for #5543
> Fix #5543: Handle timezone in num2date

- doc/api/api_changes/2015-12-01-TAC.rst
- lib/matplotlib/artist.py
Single code path for the property -> setter lookup logic.
attn @mdboom
> MNT: unify code path of set, update, setp

- lib/mpl_toolkits/axes_grid1/colorbar.py
- lib/mpl_toolkits/tests/test_axes_grid1.py
> FIX: do not use removed private methods

- lib/matplotlib/__init__.py
- lib/matplotlib/container.py
- lib/matplotlib/tests/test_container.py
It was not properly looping over sub-children of the container.
closes #5692
> FIX: Container remove method

- doc/_templates/layout.html
> Remove banner about updating styles in 2.0

- lib/matplotlib/tests/test_subplots.py
Backport of relevant part of #5735
> enable assert on 1.5 branch

- lib/matplotlib/figure.py
normalize kwargs keys from fontsize and fontweight.
closes #5747
> FIX: degenerecy in suptitle

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
> FIX: fix passing empty lists to errorbar xerr/yerr

- examples/pylab_examples/barchart_demo2.py
Changes to one of the demos.
I can drop the second commit of this if people think it is too drastic / not an improvement.
> Doc bardemo2 patch

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/tests/test_text.py
I am on the fence about the second commit.
> Fix staletxt

- lib/matplotlib/tests/test_axes.py
> Adjust the tol of two tests to pass on OSX

- lib/matplotlib/ticker.py
Even when not using round_numbers mode
> Fix #5753.  Handle minpos in log scale

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/cbook.py
- lib/matplotlib/dates.py
- lib/matplotlib/tests/test_axes.py
pd.Series prefer indexing via searching the index to positional
indexing.  This method will get the first element of any iterable.
It will advance a generater, but they did not work previously anyway.
Closes #5550
> FIX: pandas indexing error

- lib/matplotlib/axes/_base.py
As @QuLogic mentioned [here](https://github.com/matplotlib/matplotlib/pull/4686/files#r48396069)
> Fix docstring type

- doc/_templates/index.html
Minimal change from discussion in  #5558
> DOC: change Memorial Fund -> Technical Fellowship

- doc/users/whats_new/style_blacklist.rst
- lib/matplotlib/mpl-data/stylelib/classic.mplstyle
- lib/matplotlib/style/core.py
- lib/matplotlib/tests/test_backend_qt4.py
- lib/matplotlib/tests/test_backend_qt5.py
This back ports  #5440 and #5778 
I'm doing this with a PR since it involves two merges.
> Backport blacklist

- tests.py
> MNT: remove no-network from args

- INSTALL
- doc/_templates/index.html
- doc/faq/usage_faq.rst
Closes matplotlib/matplotlib.github.com#17, #5793 and #5449
> Update docs for 1.5.1

- MANIFEST.in
> BLD: include tests.py in sdist

- doc/users/colormapnorms.rst
Fixed a couple of typos and tried to reword a few sentences. Suggestions
welcome.
> Rewordings for normalizations docs.

- examples/axes_grid1/inset_locator_demo.py
- examples/axes_grid1/inset_locator_demo2.py
- lib/matplotlib/axis.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/ticker.py
- lib/mpl_toolkits/tests/test_axes_grid1.py
> Merge v2x to master

- lib/matplotlib/__init__.py
> Fix issues with getting tempdir when unknown uid

- lib/matplotlib/cbook.py
- increase retries, but back off backoff
- add verbose error message
> MNT: tweak lock

- lib/matplotlib/axis.py
> FIX: only draw tick labels if tick is in range

- matplotlibrc.template
> MNT: remove '#' from matplotlibrc

- examples/pylab_examples/polar_legend.py
- examples/widgets/radio_buttons.py
- lib/matplotlib/axes/_base.py
> Fix polar facecolor

- lib/matplotlib/artist.py
Given that it is to a thread about the limitation of python 2.2 we
should revisit some of these choices.
closes #3948
> DOC: fix rotten link

- .github/ISSUE_TEMPLATE.md
Github has just added support for [issue templates](https://github.com/blog/2111-issue-and-pull-request-templates)
I suggest we add something to help users provide better bug reports. This is my first very rough draft of such a thing. You can see it in action by creating an issue on https://github.com/jenshnielsen/matplotlib
> Add Issue template with some guidelines

- doc/users/navigation_toolbar.rst
> DOC: added missing import to navigation_toolbar.rst

- lib/matplotlib/tests/baseline_images/test_axes/log_scales.svg
This appears to be a backporting error.
Closes #6120
> TST: pull test image from master branch

- examples/text_labels_and_annotations/rainbow_text.py
- remove leading space to tighten up words
- reduce font size a bit
> MNT: clean up example

- lib/matplotlib/backends/qt_compat.py
After this is merged and the merge cascade gets this onto master a follow on PR to add a check for pyside2 is needed.
> Mnt qt imports

- setupext.py
- src/_backend_agg_wrapper.cpp
- src/_image_wrapper.cpp
- src/_path_wrapper.cpp
- src/py_converters.cpp
The formatting breaks on Windows (which is only run on master at the moment) see #6188. This just reverts those changes until we can do a proper fix. I think I may have been using the wrong numpy macro in that PR
> Revert part of #6052

- lib/matplotlib/backends/backend_cocoaagg.py
- lib/matplotlib/backends/backend_gtk.py
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_gtkagg.py
- lib/matplotlib/backends/backend_macosx.py
- lib/matplotlib/backends/backend_qt5.py
- lib/matplotlib/backends/backend_tkagg.py
- lib/matplotlib/backends/backend_webagg_core.py
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/figure.py
> Dflt forward figsize

- doc/faq/usage_faq.rst
Most of the fix suggested in #5517 was already implemented, just fleshed the documentation out a drop.
> Documentation bug fix: #5517

- doc/users/style_sheets.rst
Implemented @anntzer's suggestions in #6180
> Documentation bug #6180

- lib/matplotlib/__init__.py
Rebase of #3688
I am in favor of just merging this as-is for 2.0
> add matplotlib.__bibtex__ attribute

- lib/matplotlib/backend_bases.py
Rebase of #4467 to target v2.x
Closes #4467 
closes #3437.
> Fixed interactive save to use rcParams for facecolor and edgecolor.

- lib/matplotlib/axes/_axes.py
Saw this while looking at the function.
> DOC: fix typo

- examples/shapes_and_collections/artist_reference.py
- lib/matplotlib/patches.py
> DOC: Fix FancyBoxPatch -> FancyBboxPatch typo.

- .travis.yml
since we are seeing issues with 1.4.0
> Limit Sphinx to 1.3.6 for the time being

- doc/thirdpartypackages/index.rst
Visualisation package based on matplotlib (and pandas for the data side).
> Add PyUpSet as extension

- doc/thirdpartypackages/index.rst
Fix https://github.com/scls19fr/windrose/issues/33
> Update index.rst - add Windrose as third party tool

- lib/matplotlib/projections/geo.py
> Remove unused variable in GeoAxes class

- lib/matplotlib/axis.py
> BUG: remove inactive rotation handling from get_tick_space

- doc/_templates/layout.html
This is relevant only to the v1.5.x branch.
> DOC: fix broken link with local use; closes #5819

- .travis.yml
- setupext.py
> Block pyparsing 2.1.2 which is broken on python3.4

- INSTALL
> DOC: add disclaimer for tk versions

- lib/matplotlib/backends/backend_qt5.py
> PRF: change draw -> draw_idle

- lib/matplotlib/ticker.py
This just prevents the infinite loop.
The code this touches dates from 2006 so this possible infinite loop has been there for a long time.
> Fix infinite ticker loop

- lib/matplotlib/animation.py
- lib/matplotlib/cbook.py
- lib/matplotlib/contour.py
- lib/matplotlib/image.py
- lib/matplotlib/tests/test_image.py
- lib/matplotlib/ticker.py
This merge required a little bit of manual editing, so I am doing it as a PR to run the tests.  If/when it passes, I will merge it myself.
> Merge from 1.5

- lib/matplotlib/axes/_axes.py
I think this will conflict with changes in v2.x, but it should be easy to resolve.
> BUG: fix corner case in scatter color handling; closes #6362

- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/ticker.py
> FIX: convert to use numpy floor/ceil

- examples/specialty_plots/advanced_hillshading.py
In general no interpolation is the best soloution but in this case shading works better with interpolation.
Closes #6043
> Use interpolation on hill shading examples.

- appveyor.yml
Hopefully there are no issues here...
Fixes #6459.
> CI: Use Miniconda already installed on AppVeyor.

- lib/matplotlib/cbook.py
- lib/matplotlib/widgets.py
I noticed a couple of Python 2 syntax docstrings that need updating.
> py3k: Fix print statements in docstrings.

- lib/matplotlib/rcsetup.py
- matplotlibrc.template
> Style: use 10-pt, no ticks on right, top

- examples/statistics/boxplot_demo.py
- examples/statistics/bxp_demo.py
Just some minor change to the comprehensive demos to ensure that the y-limits all stay the same.
> DOC: made sure boxplot demos share y-axes

- lib/matplotlib/colors.py
- lib/matplotlib/tests/test_colors.py
> Fix conversion of string grays with alpha.

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/text.py
- Annotation class
- OffsetFrom class
- Axes.annotate
attn @efiring @leejjoon 
I would like this merged before a 1.5.2 final, but am going to tag a 1.5.2rc1 without it.
> DOC: update annotation docstrings

- tests.py
> TST: tweak  how to pass args to nose

- lib/matplotlib/ticker.py
> FIX: try to ensure 2 ticks with AutoLocator.

- lib/matplotlib/path.py
- lib/matplotlib/tests/test_path.py
> FIX: cast return of `contains_points` to bool

- lib/matplotlib/tests/test_axes.py
This maybe the source of flaky tests.
I plan to self-merge if this passes tests.
> TST: add missing decorator

- INSTALL
- doc/conf.py
- doc/users/whats_new/2016-04_qt_config-AL.rst
- lib/matplotlib/axes/_base.py
- lib/matplotlib/backends/backend_qt4.py
- lib/matplotlib/backends/backend_qt5.py
- lib/matplotlib/backends/qt_editor/figureoptions.py
- lib/matplotlib/backends/qt_editor/formlayout.py
Backports #5342, #5469, #6346, #6347, #6366, #6372, #6383 and #6599 to 2.x. See discussion in #6383.
> Backport qt editor improvements

- lib/matplotlib/axes/_axes.py
closes #3631 
Haven't had a chance to try to build to docs to make sure I didn't mangle the RST in the docstring. 
Does Travis test that?
> WIP/DOC: explain behavior of notches beyond quartiles

- .travis.yml
- lib/matplotlib/tests/test_font_manager.py
> TST: add test for CFF / OTF files

- lib/matplotlib/cbook.py
At request of fedora package maintainers.
closes #6536 
This just commits the patch provided by @rathann plan to review/self-merge.
Did not patch up the commit as I do not know @rathann 's email address.
> MNT: use _get_data_path is cbook

- lib/matplotlib/backend_bases.py
- lib/matplotlib/collections.py
- lib/matplotlib/lines.py
- lib/matplotlib/patches.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_collections.py
This start to address #6592 
The collection code still is broken.
> FIX: refactor dash scaling

- src/_png.cpp
Fixes the backport of the PNG speed improvements to 2.x
> Fix PNG backport

- lib/matplotlib/path.py
- lib/matplotlib/tests/test_path.py
- src/_path.h
- src/_path_wrapper.cpp
> Support returning polylines from to_polygons

- doc/users/whats_new/style_changes.rst
- lib/mpl_toolkits/mplot3d/axis3d.py
Supersedes #5585. Utilizes the internal classic mode to maintain test images and such.
> Get more rcParams for 3d

- README.rst
Supersedes #6535, which provided some copy-editing of README.rst
> Takeover #6535

- lib/matplotlib/contour.py
> BUG: contourf, restore previous behavior with N=2

- doc/api/api_changes/2016-07-20-EF.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/figure.py
- lib/matplotlib/legend.py
- lib/matplotlib/rcsetup.py
- matplotlibrc.template
Closes #6685.
In addition to the rcParams change I added legend kwargs for edgecolor and facecolor and made slight docstring improvements, but much more could be done to improve the legend docstring.
> STY: make default legend edgecolor gray

- .travis.yml
- doc/conf.py
- doc/make.py
Closes #6636
Change default docs dpi for lowr res png to 100 to match default dpi. Remove hires png from default plot formats.
> Docs change default dpi

- doc/conf.py
> Change default doc image format to png and pdf

- .travis.yml
- setupext.py
I.e. here https://travis-ci.org/matplotlib/matplotlib/jobs/150673723
> Disallow pyparsing 2.1.6 which breaks test_mathtext_exceptions

- lib/matplotlib/backends/qt_editor/figureoptions.py
Test with `imshow(np.random.rand(10))` then click on the figure options
button (Qt only).
> Image interpolation selector in Qt figure options.

- setupext.py
Fixed build error due to gnu savannah being down i.e. https://travis-ci.org/matplotlib/matplotlib/jobs/151229538
> Add mirrors to freetype download

- doc/users/whats_new/2015-11-05_hidpi.rst
- lib/matplotlib/backends/backend_webagg_core.py
- lib/matplotlib/backends/web_backend/mpl.js
- lib/matplotlib/backends/web_backend/nbagg_mpl.js
Fixes the dpi issue noted in #6948
> Backport #5383 Needed for retina support in ipympl 

- .travis.yml
This should fix leaked coverage from pytest builds
> Fixed wrong expression

- doc/users/style_sheets.rst
> Update remaining ggplot links.

- .travis.yml
- doc/make.py
- doc/sphinxext/gen_gallery.py
- doc/sphinxext/gen_rst.py
- doc/sphinxext/github.py
- doc/sphinxext/math_symbol_table.py
- lib/matplotlib/sphinxext/mathmpl.py
- lib/matplotlib/sphinxext/only_directives.py
> Doc parallel build

- lib/matplotlib/backends/backend_agg.py
> DOC: add doc strings to FigureCanvasAgg methods

- lib/mpl_toolkits/mplot3d/axes3d.py
Follow up to #6990
attn (and sorry) @WeatherGod
> FIX: pull from correct cycle

- lib/matplotlib/tests/test_animation.py
> TST: reset rcparams in animation smoke test

- doc/faq/index.rst
- doc/faq/osx_framework.rst
- doc/faq/virtualenv_faq.rst
- src/_macosx.m
Document to use pythonw on conda and reorganise the docs a bit by splitting it into two sections
> Improve virtualenv and framework builds

- examples/pylab_examples/centered_ticklabels.py
[ci skip] allows the docs to build against numpy master.
> partial backport of d82de883d4c

- lib/matplotlib/tests/test_ticker.py
- lib/matplotlib/ticker.py
Closes #7043.
This is a quick and almost minimal fix.  I left in a couple of cosmetic cleanups and a note about something else that should be changed, but that might cause a baseline image change, so I decided not to include it here.
> FIX: LogLocator.set_params() was clobbering methods

- doc/_templates/citing.html
- doc/contents.rst
This corresponds to what I have built and pushed to the website.
The possibly controversial thing I did was drop the PDF link (because I could not get it to build).
> V1.5.3 doc

- lib/matplotlib/backend_bases.py
- lib/matplotlib/backend_tools.py
See https://github.com/matplotlib/matplotlib/pull/6875#issuecomment-242576526.
> Turn off minor grids when interactively turning off major grids.

- lib/matplotlib/backends/qt_editor/figureoptions.py
This is a partial backport.
See https://github.com/matplotlib/matplotlib/pull/6564#issuecomment-246477207
> Fix steps-* drawstyles in Qt figureoptions.

- lib/matplotlib/axes/_axes.py
Hello,
We updated the documentation of plot_date to NumPy/SciPy style.
Thanks,
Michael, Klara
@NelleV
> [MRG+1] DOC Updated plot_date to NumPy/SciPy style

- doc/users/recipes.rst
Just applying proposed changed in #7017
> [DOC] Apply comments from issue #7017

- lib/matplotlib/axes/_axes.py
> PR #7030 rebased

- lib/matplotlib/mlab.py
> PR # 7038 rebased (DOC specgram() documentation now in numpy style)

- examples/ticks_and_spines/tick-formatters.py
- examples/ticks_and_spines/tick-locators.py
This is an example showing the different tick locators (but the IndexLocator since I don't understantd how it works) and tick formatters.
----
> [MRG+1][DOC] Tick locators & formatters examples

- doc/users/customizing.rst
Just a phrase and the same ref as in the next section, as otherwise it is a bit confusing without understanding the internals of the library. Related to #6954
> Docs on how to set a custom directory for stylelib/

- lib/matplotlib/axes/_axes.py
Hi @NelleV,
we tried to update the doc of arrow().
Bye,
Miguel and Bo
@NelleV
> [WIP] DOC Updated documentation of arrow function to numpy docs format.

- doc/users/dflt_style_changes.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_artist.py
Change from 'edge' to 'center'
> API: change default 'align' for bar and barh

- doc/devel/coding_guide.rst
- doc/devel/gitwash/set_up_fork.rst
This is my understanding of the current review guide lines and a starting point to if we want to formalize it any more.
We clearly have a problem getting PRs reviewed and merged in a timely fashion.
attn @matplotlib/developers
> [MRG+1] Doc review guidelines

- lib/matplotlib/patches.py
Make code consistent with documentation for FancyArrow
> Fix default parameters of FancyArrow

- examples/api/bbox_intersect.py
- examples/api/colorbar_basics.py
- examples/api/legend_demo.py
- examples/api/patch_collection.py
- examples/api/power_norm_demo.py
- examples/api/radar_chart.py
- examples/color/color_cycle_demo.py
- examples/images_contours_and_fields/contourf_log.py
- examples/images_contours_and_fields/image_demo.py
- examples/images_contours_and_fields/image_demo_clip_path.py
- examples/images_contours_and_fields/interpolation_none_vs_nearest.py
- examples/images_contours_and_fields/streamplot_demo_masking.py
> DOC: OO interface in api and other examples

- lib/matplotlib/testing/decorators.py
> [MRG+1] TST: Always produce image comparison test result images

- lib/matplotlib/backends/qt_compat.py
Don't require explicit QT_API setting for PySide2 in qt_compat.py
> [MRG+2] ENH: improve PySide2 loading

- lib/matplotlib/pylab.py
Also smuggled in some minor reformattings.
Fixes #7186.  Supersedes #7187 (see discussion there).
> Don't use __builtins__ (an impl. detail) in pylab.

- lib/matplotlib/rcsetup.py
- matplotlibrc.template
> [MRG+1] Ensure meta font names are listed last.

- lib/matplotlib/cbook.py
the documentation of pts_to_poststep, pts_to_midstep was just copied and pasted from pts_to_prestep...
fixed them.
> [MRG+1] added some fixes to the documentation of the functions

- doc/api/api_changes.rst
> [MRG+1] DOC: Add missing API change docs for 1.5.3

- lib/matplotlib/finance.py
Here is a deprecation for the finance module.
Supersedes #7071 
We should probably make a call for contributor out.
> MAINT finance module is deprecated

- examples/axisartist/demo_floating_axis.py
- examples/axisartist/demo_parasite_axes2.py
Changed demo_parasite_axes2.py and demo_floating_axis.py to add pep8 compliance as well a docstring for the sphinx_gallarey.
> Changed Examples for Pep8 Compliance

- examples/axisartist/demo_floating_axes.py
Adding docstring to matplotlib/examples/axisartist.
> add docstring to example: axisartist/demo_floating_axes.py

- lib/matplotlib/axes/_axes.py
> [MRG+1] DOC: Document `verts` in scatter

- doc/devel/MEP/MEP28.rst
I borked the python code blocks in my MEP. 
(they were interpreted as comments)
Small changes to fix that.
> MEP28: fix rst syntax for code blocks

- examples/showcase/bachelors_degrees_by_gender.py
- examples/statistics/boxplot_color_demo.py
- examples/statistics/boxplot_vs_violin_demo.py
> DOC: Boxplot color demo update

- examples/statistics/boxplot_color_demo.py
- examples/statistics/boxplot_demo.py
- examples/statistics/boxplot_vs_violin_demo.py
- examples/statistics/bxp_demo.py
- examples/statistics/customized_violin_demo.py
- examples/statistics/errorbar_demo.py
- examples/statistics/errorbar_demo_features.py
- examples/statistics/errorbar_limits.py
- examples/statistics/errorbars_and_boxes.py
- examples/statistics/histogram_demo_cumulative.py
- examples/statistics/histogram_demo_features.py
- examples/statistics/histogram_demo_histtypes.py
- examples/statistics/histogram_demo_multihist.py
- examples/statistics/multiple_histograms_side_by_side.py
- examples/statistics/violinplot_demo.py
This isn't ready yet -- but I noticed a lot of MEP12 PRs, so I wanted to get this up sooner to avoid duplicate efforts
> [MRG+1] MEP12 improvments for statistics plots

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/mlab.py
Another thing that's been sitting around partially completed. It's not totally complete in that I never really went through it word for word, and I'm not sure if I have the time for that right now. But it should render properly now that the headings and such are correct.
> DOC: mlab numpydoc-ification

- examples/animation/animate_decay.py
- examples/animation/basic_example.py
- examples/animation/basic_example_writer.py
- examples/animation/bayes_update.py
- examples/animation/double_pendulum_animated.py
- examples/animation/dynamic_image.py
- examples/animation/dynamic_image2.py
- examples/animation/histogram.py
- examples/animation/moviewriter.py
- examples/animation/rain.py
- examples/animation/random_data.py
- examples/animation/simple_3danim.py
- examples/animation/strip_chart_demo.py
- examples/animation/subplots.py
- examples/animation/unchained.py
Minor modification to have part of the animation section Sphinx-gallery compatible.
I'm pretty sure there is a problem in the Baye's update example, considering it does not converge to the theoretical value the code mentions…
Supersedes: #6486
See #7206
> [MRG+1] DOC MEP12 - converted animation to SG/MEP12 compatible

- examples/statistics/customized_violin_demo.py
As per issue #7251 , there were certain changes required in the customized violin plot example. 
Here is a list of changes made:
1. Replaced the defined percentile function with a call to np.percentile
2. Used np.clip as suggested
3. Used list comprehensions, this is more pythonic and more readable
Minor changes:
4. Moved the styling of axes to a function
5. Rearranged overall code and added comments to improve readability, made some code more pythonic, renamed certain variables
> [MRG+2] Updated violin plot example as per suggestions in issue #7251

- matplotlibrc.template
This addition is intended to prevent further questions about this on
the mailing list. ;)
https://mail.python.org/pipermail/matplotlib-users/2016-October/000669.html
> [MRG+1] Add example use of axes.spines.SIDE prop in matplotlibrc

- README.rst
Added some links to the various install docs, and want to update the contribute section once #7236 gets merged.
> [MRG]Updating the readme

- lib/matplotlib/image.py
Closes #7373 
Still thinking about the best way to test this.
> FIX: normalize image data in write_png fast path

- lib/matplotlib/rcsetup.py
- lib/matplotlib/tests/test_cycles.py
> ENH: validate dashes in prop_cycle

- lib/matplotlib/backends/backend_tkagg.py
Take two on pull request #7380
> Added spacer to Tk toolbar

- .gitignore
> [MRG+1] Add pytest's .cache to .gitignore.

- examples/showcase/mandelbrot.py
This is a rendering of the Mandelbrot set. I think it is reasonably good looking (using normalized recount, adapted normalized colormap and shading).
> [MRG+1] Showcase example: (kind of mandatory) Mandelbrot set

- lib/matplotlib/axes/_axes.py
Mostly style, use `clip`, get rid of a redundant conditional.
> [MRG+1] Minor cleanup of hist().

- lib/matplotlib/patches.py
This makes the example in #7375 work correctly; let's see if it breaks anything in the tests.
> [MRG+1] BUG: in Patch.update_from, use private variables.  Closes #7375.

- examples/pylab_examples/contour_image.py
- examples/pylab_examples/contourf_demo.py
- examples/pylab_examples/layer_images.py
- examples/pylab_examples/scatter_masked.py
- examples/pylab_examples/toggle_images.py
- examples/user_interfaces/embedding_in_qt4.py
- examples/user_interfaces/embedding_in_qt5.py
This is a start on addressing #3070.  The first commit should be uncontroversial.  I will look into adding the deprecation warning in subsequent commits.
> [MRG] Begin deprecation of "hold": remove from examples

- INSTALL
Added the missing dependencies from our installation instructions.
closes #6580
> [MRG] DOC added new dependencies for 2.0

- doc/api/axes_api.rst
I intend to self-merge this if it passes and no one beats me to it.
> DOC: add API docs for sticky edges

- examples/showcase/xkcd.py
current: http://matplotlib.org/devdocs/users/screenshots.html#xkcd-style-sketch-plots
this PR:
> DOC: make xkcd demo look better with new defaults

- setup.py
Should fix #7056 - this seemed like the neatest way to avoid working out packages to install.
> Don't work out packages to install if user requests information from setup.p

- doc/api/animation_api.rst
- lib/matplotlib/animation.py
The plan (if I have time to get to it is to flesh out the FuncAnimation section with the same example implemented the other 3 ways, but I think that as-is it is still a major improvement.
> Doc animation

- lib/matplotlib/font_manager.py
- lib/matplotlib/tests/test_text.py
- lib/matplotlib/text.py
This bakes into the text artist (via the FontProperties) the default
fontsize at the time of creation.
Possibly closes #7005
> API: convert string fontsize to points immediately

- doc/users/whats_new/plot_surface.rst
- examples/mplot3d/surface3d_demo.py
- examples/mplot3d/surface3d_demo2.py
- examples/mplot3d/surface3d_demo3.py
- examples/mplot3d/surface3d_radial_demo.py
- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/tests/test_mplot3d.py
... providing an alternative to rstride/cstride
Still needs a whats_new.rst entry.
> Added rcount/ccount to plot_surface()

- tools/test_triage.py
This enables use with both qt4 and qt5
> MNT: use qt_compat for qt import in test_triage

- lib/matplotlib/artist.py
See https://github.com/matplotlib/matplotlib/commit/cdb830db76434f058f11c1e3eb1a147e945e65f5#commitcomment-20194251.
> picker may not be callable.

- doc/faq/howto_faq.rst
As this breaks linkchecker, I would like to self-merge to get Travis working again.
> DOC: Remove explicit link to source file for Sphinx 1.5 compat.

- doc/devel/release_guide.rst
- tools/github_stats.py
I have been sitting on this for about a year...
This is a fleshed out version of the checklist I have been using for releases.
Closes  #3707
> [MRG+1] Doc release guide

- doc/users/dflt_style_changes.rst
This includes some reorganization of sections.
> DOC: add ScalarFormatter plot, other tweaks to dflt_style_changes

- doc/users/colormaps.rst
> DOC: Add link to bokeh/colorcet in colormaps.rst

- lib/matplotlib/dates.py
- lib/matplotlib/tests/test_dates.py
> Fixes tzname return type

- lib/matplotlib/legend_handler.py
- lib/matplotlib/tests/test_axes.py
> [MRG+1] Makes eventplot legend work

- lib/matplotlib/legend_handler.py
- lib/matplotlib/tests/test_axes.py
This patch applies #7676 to v2.x and fixes a merge conflict.
> Merged 158f36e

- lib/matplotlib/__init__.py
- lib/matplotlib/rcsetup.py
> [MRG+1] Use mplDeprecation class for all deprecations.

- lib/matplotlib/style/core.py
- lib/matplotlib/tests/test_style.py
Thanks for the feedback. Again forgive my ignorance with the workflow here: I reverted the first commit, made a feature branch from that, and created a PR to matplotlib/v2.x.
Your suggestion makes more sense. My first attempt was closer to that, but I was trying to preserve the original warning attributes, and went down the wrong path.
https://github.com/matplotlib/matplotlib/issues/7601
> [MRG+1] Add warning context

- doc/devel/contributing.rst
- doc/users/tight_layout_guide.rst
- only provide one installation direction
- put details about local testing at the top
attn @NelleV 
attn @goldstarwebs
> DOC: reorganize and simplify contributing.rst

- lib/matplotlib/finance.py
> DOC: Fix finance depr docs to point to mpl_finance

- doc/users/navigation_toolbar.rst
- lib/matplotlib/backend_bases.py
- matplotlibrc.template
> DOC: Sync keyboard shortcuts for fullscreen toggle

- lib/matplotlib/backends/backend_qt5.py
- lib/matplotlib/pyplot.py
See https://github.com/matplotlib/matplotlib/pull/7766#issuecomment-271227446, sorry I missed these initially...
> Fix more invalid escapes sequences.

- .github/ISSUE_TEMPLATE.md
This removes some unnecessary text and formatting from the issue reporting template.
> Adjust markdown and text in ISSUE_TEMPLATE.md

- doc/users/whats_new.rst
If this passes I will self merge.
The issue is that earlier we used `~~~~` for the level of header under `----`
> [MRG+1] DOC: tweak headers so sphinx builds

- examples/axes_grid1/inset_locator_demo.py
Only made it a separate PR so that the "minor note" at the bottom of the otherwise closed https://github.com/matplotlib/matplotlib/issues/6207#issue-142825092 doesn't get lost.
> Minor simplification of inset_locator_demo.

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
> [MRG+1] better input validation on `fill_between`

- lib/matplotlib/dates.py
- lib/matplotlib/tests/test_pickle.py
issue description:
https://github.com/matplotlib/matplotlib/issues/7852
> !B [#7852] fix for _rrule maximum recursion depth exceeded on multiprocessing usage

- examples/style_sheets/plot_bmh.py
- examples/style_sheets/plot_dark_background.py
- examples/style_sheets/plot_fivethirtyeight.py
- examples/style_sheets/plot_ggplot.py
- examples/style_sheets/plot_grayscale.py
Ref: #7206 
Added titles to docstrings for sphinx-gallery and updated some code syntax.
> [MRG+2] DOC Convert style sheet examples to MEP12

- lib/matplotlib/tests/test_widgets.py
See last few comments in #7861.
> Remove extra test backported in #7861.

- lib/matplotlib/__init__.py
- lib/matplotlib/tests/test_mlab.py
This is the single largest file with changes, simply because it's just so big anyway. But that means it can only get simpler from here. I have a feeling that some of these tests could be `parametrize`d, but it was large enough without such changes.
The first commit, while the largest (just barely), is also the automated one, so it's probably safe.
> [MRG+1] Convert mlab tests to pytest

- examples/color/color_cycle_default.py
- examples/color/color_cycle_demo.py
- examples/color/colormaps_reference.py
- examples/color/named_colors.py
- examples/pie_and_polar_charts/pie_demo_features.py
- examples/pie_and_polar_charts/polar_bar_demo.py
- examples/pie_and_polar_charts/polar_scatter_demo.py
- examples/style_sheets/plot_bmh.py
- examples/style_sheets/plot_fivethirtyeight.py
Ref: #7206
Also some small changes from #7890 which didn't make it in before merge
> [MRG+1] DOC MEP12: pie/polar and color examples + style sheets fix

- lib/matplotlib/__init__.py
- lib/matplotlib/tests/test_agg.py
- lib/matplotlib/tests/test_arrow_patches.py
- lib/matplotlib/tests/test_artist.py
- lib/matplotlib/tests/test_basic.py
- lib/matplotlib/tests/test_bbox_tight.py
- lib/matplotlib/tests/test_coding_standards.py
Pretty small set of changes in most of these. Note that `test_backends_*` is in #7863.
> [MRG+1] Convert test_[ab]* files to pytest.

- lib/matplotlib/font_manager.py
- lib/matplotlib/tests/test_font_manager.py
> BUG: Add a newline separator in fc-list call

- lib/matplotlib/tests/test_animation.py
The file-based writers save frame images in consistent names which can end up clobbering each other if run in parallel.
This could be fixed directly by #3536 if someone wants to take that on.
> [MRG+1] Run animation smoketest in a temporary directory.

- conftest.py
- lib/matplotlib/__init__.py
- lib/matplotlib/tests/test_coding_standards.py
- lib/matplotlib/tests/test_colors.py
- lib/matplotlib/tests/test_contour.py
- lib/matplotlib/tests/test_cycles.py
- lib/matplotlib/tests/test_dates.py
- lib/matplotlib/tests/test_image.py
- lib/matplotlib/tests/test_legend.py
- lib/matplotlib/tests/test_lines.py
- lib/matplotlib/tests/test_mlab.py
- lib/matplotlib/tests/test_offsetbox.py
- lib/matplotlib/tests/test_patches.py
- lib/matplotlib/tests/test_path.py
- lib/matplotlib/tests/test_patheffects.py
- lib/matplotlib/tests/test_pickle.py
- lib/matplotlib/tests/test_quiver.py
- tests.py
Also delete the `nose` bit at the end of some other tests.
> [MRG+1] Convert remaining tests to pytest

- lib/matplotlib/patches.py
Apologies but my linter just annoy me enough every time I come by this
file to send a PR.
The comments seemed to be only experiment from 2009 which ended up with current code.
> Cleanup: remove unused variable/assignment/expression and debug comments

- examples/api/custom_projection_example.py
- lib/matplotlib/cm.py
- lib/matplotlib/projections/geo.py
- lib/matplotlib/testing/compare.py
- lib/matplotlib/tests/test_colors.py
- lib/matplotlib/tests/test_path.py
I found the first commit lying around on disk, so better get it merged sometime.
> [MRG+1] Fix/hide some deprecations

- doc/devel/coding_guide.rst
removed a misplaced `please` and some jargony bits it took me a bit long to grok, and made some style choices.
attn @anntzer
> [MRG+1] Coding Guide Edits

- lib/matplotlib/tests/test_figure.py
CI is broken, so I will self merge once it passes.
> Remove assert_true calls from new PRs.

- lib/matplotlib/tests/test_colors.py
The merge up broke this. Sorry about that.
> [MRG+1] Add vega deprecations to tests on master

- .travis.yml
> Test 2.0.x on released python 3.6

- conftest.py
- lib/matplotlib/tests/test_cbook.py
There's only one class that requires this modification, so it can just be fixed.
> [MRG+1] Remove pytest_pycollect_makeitem.

- .coveragerc
- .travis.yml
- appveyor.yml
- ci/codecov.yml
- Cleaning up codecov config to remove commenting
- Remove coveralls
- Trying to set up codecov to report coverage in test code separately
- Also enabled coverage on AppVeyor
> [MRG+1] Coverage config

- doc/devel/coding_guide.rst
I'm so very confused so trying to demystify how this works. @QuLogic
> Clarify backports documentation

- examples/pylab_examples/axis_equal_demo.py
modified:   examples/pylab_examples/axis_equal_demo.py
> [MRG+1] Added tight_layout() to example.

- lib/matplotlib/cbook/__init__.py
> Undeprecate is_scalar_or_string.

- doc/api/api_changes/2017-01-30-AL_negative_bar_height_width.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_patches.py
Set sticky_edges correctly for negative height bar().
the patch did not apply cleaning.
> MAINT Backporting of #7995.

- README.rst
> [MRG+1] fix gitter badge

- examples/mplot3d/polys3d_demo.py
Fixes a violation introduced by #8233. I'll self-merge if/when the doc build and PEP8 build pass.
> Fix pep8 violation

- examples/pylab_examples/vline_hline_demo.py
Add transform to vline example (as discussed [here]
(https://github.com/matplotlib/matplotlib/issues/5896#issuecomment-273818416) )
@tacaswell was this what you had in mind?
> Update vlines example with axes wide lines.

- lib/matplotlib/fontconfig_pattern.py
On my laptop this patch drops the duration of the test suite from 604s
to 554s (with the inkscape patch on as well).
(The fontconfig syntax is simple enough that one could also probably write a simple regex parser.)
attn @NelleV
> Memoize parse_fontconfig_pattern; speeds up test suite by ~1min.

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
> [MRG+2] Plot errorbars when fmt == 'none'

- lib/matplotlib/rcsetup.py
- lib/matplotlib/tests/test_rcparams.py
This PR fixes #8145 .
The type checking of strings was raising errors when non Unicode strings were passed as arguments to `_validate_linestyle` (that was introduced in #8040), which can easily occur under Python 2.7 for example. This PR replaces this type checking with a simple `try: … except: …` approach. It also adds a couple of test cases to explicitly test the situation of non Unicode arguments.
> [MRG+2] FIX: Remove type checking for strings in '_validate_linestyle'

- examples/ticks_and_spines/plot_spines_bounds.py
As part of #8247 , I noticed this example was missing a title.
This PR fixes this.
> [MRG] DOC moved spines examples sphinx-gallery

- doc-requirements.txt
Used the wrong comparison operator in https://github.com/matplotlib/matplotlib/pull/8269.
> Fix sphinx required version

- lib/matplotlib/tests/test_axes.py
style only change to unbreak CI.
Plan to self merge when tests pass (if someone does not beat me to it).
> STY: fix whitespace in the tests

- examples/mplot3d/contour3d_demo.py
- examples/mplot3d/contour3d_demo2.py
- examples/mplot3d/contour3d_demo3.py
- examples/mplot3d/contourf3d_demo.py
- examples/mplot3d/contourf3d_demo2.py
- examples/mplot3d/custom_shaded_3d_surface.py
- examples/mplot3d/lines3d_demo.py
- examples/mplot3d/lorenz_attractor.py
- examples/mplot3d/mixed_subplots_demo.py
- examples/mplot3d/offset_demo.py
This PR should finish up the migration of the axes3D plots to sphinx-gallery. The titles aren't great, but this should help finish up the migration quickly.
> DOC added titles to the rest of the 3D plots

- lib/matplotlib/axes/_axes.py
> [MRG+1] Don't index into __builtins__ (not supported by PyPy).

- lib/matplotlib/cbook/__init__.py
(I still think iterating over rows vs. over columns depending on input
type is rather silly but at least this implementation makes it clearer.)
(Written while working on #8092, attn @phobson)
> [MRG+1] Simplify _reshape_2D.

- lib/matplotlib/patches.py
> Make ArrowStyle docstrings numpydoc compatible

- examples/units/annotate_with_units.py
- examples/units/artist_tests.py
- examples/units/bar_demo2.py
- examples/units/bar_unit_demo.py
- examples/units/evans_test.py
- examples/units/radian_demo.py
- examples/units/units_sample.py
- examples/units/units_scatter.py
Changes in accordance to <a href='https://github.com/matplotlib/matplotlib/issues/7206'>#7206</a>
> Adding headers for examples/units for MEP12/sphinx-gallery compliance

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/collections.py
- lib/matplotlib/tests/test_collections.py
(Instead let invalid entries error.)
Let's see how hard it is to fix #7785...
> Don't reshape offsets into the correct shape.

- examples/widgets/check_buttons.py
Previously you had to manually change the variables in func. Now it's done automatically based on the properties of the lines.
> Make checkbuttons with all plotted lines with correct visibility automatically

- doc/devel/MEP/MEP28.rst
- lib/matplotlib/axes/_axes.py
Some additions in response to https://github.com/matplotlib/matplotlib/issues/8092
> DOC: Update MEP 28

- doc/_static/mpl.css
> Give wide code blocks a scrollbar on website

- doc/README.txt
This complements #8373 and updates the README file to reflect graphviz is also a dependency.
> DOC update build dependencies

- doc/users/whats_new/min_log_scale_exponent.rst
- lib/matplotlib/rcsetup.py
- lib/matplotlib/tests/test_ticker.py
- lib/matplotlib/ticker.py
- matplotlibrc.template
This is a duplicate of #6834 , but with an what's-new entry.
> [MRG+1] Use scalars below a certain exponent in labes of log-scales axis

- lib/matplotlib/axes/_axes.py
> Improve hist2d docstring by inlining properties.

- doc/users/plotting/colormaps/lightness.py
The updated version on the master branch uses a feature which does not
exist on 2.0.x
Intend to self merge once this pass.
> DOC: tweak API usage

- examples/widgets/check_buttons.py
A small fixup/followon from #6310
> Manually collect lines on checkbox example

- doc/api/container_api.rst
- doc/api/index.rst
> [MRG+1] Add container module to API docs

- lib/matplotlib/patches.py
An overhaul of the FancyArrowPatch docstring. There's a couple of kwargs I'm not too sure about so I've left them blank; suggestions welcome.
> FancyArrowPatch docstring overhaul

- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/tests/test_mplot3d.py
> Fixed Issue #7460: Raised an error if argument to xlim is invalid

- examples/widgets/lasso_selector_demo.py
- examples/widgets/polygon_selector_demo.py
- lib/matplotlib/tests/test_widgets.py
- lib/matplotlib/widgets.py
Hello matplotlib community! Please checkout the PolygonSelector widget.  The demo is pretty straight forward, and basically a copy of the LassoSelector demo.  I'm open to any feedback, or suggestions for improvement.  Thanks for your consideration.
> New Feature - PolygonSelector Widget

- doc/devel/coding_guide.rst
since changelog isn't used anymore, removed reference to it from the development docs
> remove changelog from contributing guide

- .github/PULL_REQUEST_TEMPLATE.md
Moved most of the text to comments 'cause of how the template appears in #8481
> Modified PR Template

- examples/units/bar_demo2.py
- PEP8
- `plt.subplots`
- `tight_layout()`
#8254 is a pull request to clean up the docstring at the top - please wait until that is merged in case of conflicts.
> [DOC] Clean up bar_demo2

- doc/faq/osx_framework.rst
Added a link to https://github.com/mapio/jupyter-virtualenv-osx that can solve the issue for Jupyter notebook users.
> [MRG+1] Added a workaround for Jupyter notebooks

- examples/units/artist_tests.py
- examples/units/bar_demo2.py
- examples/units/radian_demo.py
Adds in all the comments from  #8254
> [MRG+1] Clean up unit examples

- .github/PULL_REQUEST_TEMPLATE.md
> Update PR template to encourage PRs off not master.

- lib/matplotlib/legend_handler.py
- lib/matplotlib/tests/test_legend.py
> Fixed Error: local variable 'xdata' referenced before assignment" in legend_handler.py

- .github/ISSUE_TEMPLATE.md
Basically this just used the HTML comment trick to make the
template a little snazzier.
This will hopefully keep the text of the issues from being filled with our guidance about making issues.
> [MRG+1] MNT: update GH issue template [ci skip]

- lib/matplotlib/__init__.py
See discussion at https://github.com/matplotlib/matplotlib/issues/7289.
> [MRG+1] Clarify docs for rcdefaults and friends.

- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/backend_qt5.py
- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_figure.py
attn @efiring 
This is the last thing for 2.0.1 I believe.
> Fix qt5 mouse

- examples/pie_and_polar_charts/nested_pie.py
This adds the nested pyplot examples that were demoed in the gitter by @phobson and @anntzer. Both were cool, and since it was in response to a user asking how to create this, I assume that there are many other users that would like to know how to do this but didn't think to ask on the gitter, thus the example!
> [MRG+1] nested pie example

- doc/devel/documenting_mpl.rst
small change to add some extra useful information for the documentation to help contribute to the docs. We've had a hard time on-boarding new people to help with docs in matplotlib, so hopefully this will help clear up some issues.
> updating developer docs

- .gitignore
- doc-requirements.txt
- doc/conf.py
- doc/make.py
- Add copied depsy_badge to gitignore.
- In conf.py, move all dependency checks together.
- In conf.py and doc-requirements.txt, added dependency on scipy (for
animation/bayes_update.py, animation/double_pendulum_animated.py).
- In conf.py, update copyright years.
- Fix error when invoking make.py without a target.
> Update doc build.

- doc/_static/mpl.css
- doc/conf.py
- examples/misc/keyword_plotting.py
- tutorials/01_introductory/pyplot.py
Two short little snippets of code to demo plotting with keywords. In this case I'm using a dictionary but mention that you could use a `DataFrame` if you wanted. Mentioned in #8555
> [MRG+1] adding keyword plotting

- lib/matplotlib/backends/qt_compat.py
> [MRG+1] FIX: if explicitly asked for Qt5 backend, do not fallback to qt4

- doc/api/contour_api.rst
- doc/api/index.rst
- lib/matplotlib/contour.py
> [MRG+1] Add mpl.contour to api docs; minor fix to docstring.

- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/font_manager.py
- lib/matplotlib/texmanager.py
Hi, I was browsing matplotlib on www.lgtm.com, and noticed a number of alerts (https://lgtm.com/projects/g/matplotlib/matplotlib/alerts/). Some of them were fairly clear-cut, and I saw that I could fix them immediately, hence this PR. Others would require someone with more knowledge of the code to triage.
You can also turn on PR integration to help avoiding introducing more of these kinds of errors: https://lgtm.com/projects/g/matplotlib/matplotlib/ci/
By the way, matplotlib has been incredibly useful in my work, love the project! I hope this can help a little.
> Fix a number of minor local bugs

- lib/matplotlib/colors.py
- lib/matplotlib/tests/test_colors.py
Closes #8299 
Creating new PR to replace #8314 @phobson @tacaswell
> [MRG+1] Issue #8299, implemented copy, added test

- .travis.yml
- lib/matplotlib/tests/test_backends_interactive.py
wxPython provides Trusty wheels, so use them.
(followup to #8660)
> Add basic testing of wxagg backend.

- examples/animation/image_slices_viewer.py
- examples/event_handling/pick_event_demo2.py
- examples/event_handling/zoom_window.py
- examples/frontpage/membrane.py
- examples/images_contours_and_fields/image_clip_path.py
- examples/images_contours_and_fields/image_demo.py
- examples/pylab_examples/ellipse_demo.py
- examples/pylab_examples/fancybox_demo.py
- examples/pylab_examples/line_collection.py
- examples/pylab_examples/major_minor_demo.py
- examples/pylab_examples/mri_demo.py
- examples/pylab_examples/mri_with_eeg.py
- examples/pylab_examples/pcolor_demo.py
- examples/pylab_examples/psd_demo.py
- examples/pylab_examples/spy_demos.py
- examples/pylab_examples/stackplot_demo.py
- examples/pylab_examples/tricontour_vs_griddata.py
- examples/pylab_examples/vline_hline_demo.py
- examples/showcase/bachelors_degrees_by_gender.py
- examples/specialty_plots/topographic_hillshading.py
- examples/statistics/barchart_demo.py
- examples/statistics/boxplot_demo.py
- examples/statistics/hexbin_demo.py
- examples/subplots_axes_and_figures/subplot_toolbar.py
- examples/text_labels_and_annotations/legend_demo.py
- examples/units/units_sample.py
- examples/user_interfaces/histogram_demo_canvasagg_sgskip.py
- examples/userdemo/annotate_text_arrow.py
These are fixes I noticed in #8266 but never finished commenting. And anyway, since that was a merge-everything PR, trying to fill it with a lot of cleanup would be confusing.
Much of this is just trying to maintain some consistency within a file, e.g., if one example used OO and one example used pyplot, switch to just OO.
@choldgraf
> Cleanup of merged pylab examples

- lib/matplotlib/tests/test_backends_interactive.py
> Fix skipif in interactive backends test.

- doc/api/api_changes/2017-05-31-AL_dynamic_update.rst
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/backend_gtk.py
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_macosx.py
- lib/matplotlib/backends/backend_qt5.py
- lib/matplotlib/backends/backend_tkagg.py
- lib/matplotlib/backends/backend_webagg_core.py
- lib/matplotlib/backends/backend_wx.py
The method has been described as "legacy" in comments since 2005
(68eb00ac5412a2ad3477a92bd20bbf76681c71dd).
- NA Has Pytest style unit tests
- NA Code is PEP 8 compliant 
- NA New features are documented, with examples if plot related
- NA Documentation is sphinx and numpydoc compliant
- NA Added an entry to doc/users/whats_new.rst if major new feature
> Deprecate NavigationToolbar2.dynamic_update.

- doc/api/api_changes/code_removal.rst
- lib/matplotlib/__init__.py
- lib/matplotlib/rcsetup.py
> Remove deprecated rcParams entries and functions.

- examples/pylab_examples/arrow_demo.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/backends/qt_compat.py
- lib/matplotlib/figure.py
- lib/matplotlib/mlab.py
- lib/matplotlib/rcsetup.py
- lib/matplotlib/stackplot.py
- lib/matplotlib/transforms.py
- lib/mpl_toolkits/axisartist/clip_path.py
- tools/gh_api.py
Hi,
I just wanted to quickly fix a few alerts flagged up by lgtm.com. These are mostly simple ones but they were a few if statements that likely didn't work as intended.
A total of 371 alerts have been found by lgtm.com, you can enable PR integration for automated PR reviews and flag these in the future before they find their way into the code base.
https://lgtm.com/projects/g/matplotlib/matplotlib/
see here for PR integration details: https://lgtm.com/docs/lgtm/config/pr-integration
I use matplotlib every day so I hope you'll find these useful!
- [x ] Code is PEP 8 compliant
> Fix some lgtm alerts

- lib/matplotlib/backends/backend_agg.py
- lib/matplotlib/backends/backend_cairo.py
- lib/matplotlib/backends/backend_gdk.py
- lib/matplotlib/backends/backend_gtk.py
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_gtkcairo.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/backends/backend_qt4.py
- lib/matplotlib/backends/backend_qt5.py
- lib/matplotlib/backends/backend_tkagg.py
Removed some debug statements and old comments; whitespace / line
wrapping (to 79 characters).
(FWIW the debug code in backend_gtkcairo is apparently broken -- it occasionally refers to a function `fn_name` which doesn't exist (it's `_fn_name`))
> Various cleanups to backends code.

- lib/matplotlib/axes/_base.py
> Simplify cla sharex/sharey code; alternative to #8710

- lib/matplotlib/axes/_axes.py
I was going through `pcolormesh` in Cartopy to optimize it a bit, and I noticed these extra copies of variables, which I cleaned up and want to keep in sync, hence this PR. I don't believe the first bit saves much as they're probably views in latest NumPy, but dropping the extra `pts` should save a little bit of memory.
> Remove redundant variables in pcolormesh.

- doc/api/api_changes/2017-06-06-AL_wxidle.rst
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/tests/test_backends_interactive.py
See https://github.com/matplotlib/matplotlib/issues/8718.
attn @tacaswell
> No longer connect to idle event on wx.

- lib/matplotlib/colorbar.py
> DOC: colorbar.set_ticks() accepts a Locator.

- tutorials/02_intermediate/gridspec.py
Small semantic change in text.
> Updated file

- doc/thirdpartypackages/index.rst
add short description of another toolkit that uses matplotlib
add a short description to another toolkit that uses matplotlib
> [MRG+1] Update index.rst (add DeCiDa to Toolkits paragraph)

- lib/matplotlib/__init__.py
- lib/matplotlib/cbook/_backports.py
- lib/matplotlib/mpl-data/stylelib/_classic_test.mplstyle
- lib/matplotlib/mpl-data/stylelib/classic.mplstyle
- lib/matplotlib/tests/test_backend_pdf.py
- lib/matplotlib/tests/test_backend_ps.py
- lib/matplotlib/tests/test_backend_svg.py
- lib/matplotlib/texmanager.py
- matplotlibrc.template
- pytest.ini
- tutorials/text/usetex.py
Fixes #8748, plus some cleanups.
> Remove tex version check; require dvipng >=1.6

- lib/mpl_toolkits/axes_grid1/axes_divider.py
> [Documentation Typo] Update axes_divider.py

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Fixes pandas KeyError when `align=center` is specified for bar plot by replacing index access with a list comprehension using `zip`.
Added test highlighting the bug to [lib/matplotlib/tests/test_axes.py](https://github.com/ryanlaclair/matplotlib/blob/master/lib/matplotlib/tests/test_axes.py).
Fixed bug in [lib/matplotlib/axes/_axes.py](https://github.com/ryanlaclair/matplotlib/blob/master/lib/matplotlib/axes/_axes.py) by replacing the index access with a list comprehension using `zip`.
Bugfix for issue #[8767 ](https://github.com/matplotlib/matplotlib/issues/8767).
> Fix pandas DataFrame align center

- lib/matplotlib/tests/test_text.py
- tools/triage_tests.py
Remove an extraneous plt.show().
Make the triage_test window's minimal size smaller (so that it fits in
smaller screens).
> Minor cleanups for tests.

- lib/matplotlib/tests/test_axes.py
> Fix typo in test.

- doc/devel/MEP/MEP12.rst
- tutorials/text/mathtext.py
- tutorials/text/text_props.py
Addresses issue https://github.com/matplotlib/matplotlib/issues/8702.
Minor change to the text_props tutorial to point out that the math font needs to be set with the `mathtext` rcParams. I also added a label to the math tutorial so I could link to it.
I'm a new contributor, and this is my first PR. Please let me know if I've done anything incorrectly, and thanks for your patience! If all goes well, I'd like to get more involved!
> Add sentence to textprops tutorial mentioning mathtext rcParams

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/collections.py
- lib/matplotlib/tests/test_axes.py
> Fix eventplot colors kwarg

- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/testing/compare.py
- lib/matplotlib/tests/test_backend_pdf.py
> Pdf color none

- examples/axisartist/demo_axisline_style.py
- examples/event_handling/poly_editor.py
- examples/event_handling/resample.py
- examples/mplot3d/lines3d.py
- examples/mplot3d/lorenz_attractor.py
- examples/mplot3d/mixed_subplots.py
- examples/mplot3d/offset.py
- examples/pylab_examples/bar_stacked.py
- examples/pylab_examples/dolphin.py
- examples/pylab_examples/fill_between_demo.py
- examples/pylab_examples/geo_demo.py
- examples/pylab_examples/log_test.py
- examples/pylab_examples/mri_demo.py
Rebase of #8209
attn @dstansby @choldgraf
> Doc yinleon rebase

- doc/devel/coding_guide.rst
Use "is it better" threshold for doc/example changes.
> DOC: updated review guidelines

- .circleci/config.yml
This should fix the CircleCI build.
> ci: Update Circle-CI apt cache first.

- examples/pylab_examples/log_demo.py
One more PR from the SciPy sprint. Rewrote this example to use the OO format instead of the older API
- [ x] Code is PEP 8 compliant
> rewrote example to OO format

- examples/pylab_examples/markevery_demo.py
> tidy up markevery_demo example

- .appveyor.yml
- lib/matplotlib/backends/backend_pgf.py
> FIX: invalid escapes in backend_pgf

- INSTALL.rst
Windows and mac devs should make sure I have not introduced any false hoods.
Attn @matthew-brett to make sure I have not lied about wheels.
> Doc install docs

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
This allows things like time/height plots.
Closes #8909.
> ENH: Support x,y units for barbs/quiver

- lib/matplotlib/backends/backend_cairo.py
> Fix cairo mathtext.

- lib/matplotlib/animation.py
> Animation doc markup cleanups.

- lib/matplotlib/figure.py
- lib/matplotlib/projections/__init__.py
Extends #9034.  See discussion at #9024.
Feel free to push or force-push additional fixes to this PR.
> Deprecate axes collision

- lib/matplotlib/figure.py
- lib/matplotlib/projections/__init__.py
Reverts matplotlib/matplotlib#7377
> Revert "ENH: Switch to a private, simpler AxesStack."

- tutorials/introductory/pyplot.py
> fix pyplot tutorial bug

- lib/matplotlib/text.py
`matplotlib.text` was importing `matplotlib.backend_bases.RendererBase` without actually using it.
The problem is not that it doesn't use it, the problem is that this import creates a circular import.
The circular import became evident when working on PR https://github.com/matplotlib/matplotlib/pull/9022 adding
`from matplotlib.table import Table` to `matplotlib.backend_tools.py` gave the following error
```
File "histogram_cumulative.py", line 39, in <module>
File "/home/fariza/workspace/matplotlib/lib/matplotlib/pyplot.py", line 29, in <module>
import matplotlib.colorbar
File "/home/fariza/workspace/matplotlib/lib/matplotlib/colorbar.py", line 36, in <module>
import matplotlib.contour as contour
File …
```
> removing import that is prone to circular imports

- doc/api/api_changes/2017-08_TAC.rst
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/tests/test_cbook.py
alternative to #7197
Still needs tests and doc
> Api callback exceptions

- lib/matplotlib/mpl-data/stylelib/fast.mplstyle
- lib/matplotlib/path.py
- tutorials/introductory/usage.py
* Add a lightweight new style that values plotting speed over pixel-perfect accuracy in plotting.
* Update performance docs section.
> New style for fast plotting, updated performance docs

- lib/matplotlib/__init__.py
It's broken further down anyways: see discussion starting at
https://gitter.im/matplotlib/matplotlib?at=59777c5e1c8697534a5be4cb xref #8932
If we want to restore this functionality it should be correctly tested.
> Don't pretend to support Google App Engine.

- tutorials/intermediate/tight_layout_guide.py
Closes https://github.com/matplotlib/matplotlib/issues/5824#issuecomment-256202440.
Changed the section level of some sections for consistency for the first section ("Example").
> Document auto-tightlayouting.

- lib/matplotlib/colors.py
- lib/matplotlib/pyplot.py
- tutorials/colors/colors.py
Update and sync the color format docs between the colors tutorial and the colors module.
Deprecate plt.colors(), which does nothing other than reproducing this documentation but is not even listed (AFAICT) in the pyplot docs or anywhere else anymore.
As a side note, the tutorials should probably all be listed in the overview (http://matplotlib.org/devdocs/contents.html#overview) of the docs, perhaps in the user guide section.
Feel free to (force-)push edits.
> Update color docs.

- doc/users/dflt_style_changes.rst
> DOC: add missing imports

- tutorials/introductory/usage.py
There is alot more work needed on this section, but is an improvement.
Closes https://github.com/matplotlib/jupyter-matplotlib/issues/13
> Doc backends

- doc/api/api_changes.rst
See bottom of http://matplotlib.org/devdocs/api/api_changes.html
> Don't highlight the end of the API changes (plain text).

- tutorials/introductory/usage.py
> DOC: note that ipympl is external dependency

- doc/users/next_whats_new/js-animation.rst
- lib/matplotlib/_animation_data.py
- lib/matplotlib/animation.py
- lib/matplotlib/rcsetup.py
- lib/matplotlib/tests/test_animation.py
- matplotlibrc.template
This pulls http://github.com/jakevdp/JSAnimation into the code. Most of
this is in the HTMLWriter class. This also adds the `jshtml` option for
the animation.html setting.
> Import JSAnimation into the animation module. (Fixes #4703)

- unit/memleak.py
Discovered this while testing for 2.1rc1
> MNT: future numpy only takes ints as index

- .appveyor.yml
I think that appveyor is currently failing because it's picking up a corrupted cache - maybe cleaning conda will help?
> Clean conda on appveyor

- src/_macosx.m
Fixes #9156. See https://github.com/matplotlib/matplotlib/issues/9156#issuecomment-327217962 for more information on the fix.
> Fix osx busy cursor

- .gitattributes
This will suppress them from the github UI diffs (and line counts), see
https://github.com/github/linguist#generated-code.
Alternative (or complementary to) #9214.
> Mark svg files as binary/generated in gitattributes.

- lib/matplotlib/backends/wx_compat.py
> FIX: use str (not unicode) to ensure comparison works on python2

- lib/matplotlib/axes/_base.py
- lib/matplotlib/figure.py
- lib/matplotlib/tests/test_axes.py
> FIX: add missing property decorators

- lib/mpl_toolkits/axes_grid/__init__.py
- lib/mpl_toolkits/axes_grid/anchored_artists.py
- lib/mpl_toolkits/axes_grid/angle_helper.py
- lib/mpl_toolkits/axes_grid/axes_divider.py
- lib/mpl_toolkits/axes_grid/axes_grid.py
- lib/mpl_toolkits/axes_grid/axes_rgb.py
- lib/mpl_toolkits/axes_grid/axes_size.py
- lib/mpl_toolkits/axes_grid/axis_artist.py
- lib/mpl_toolkits/axes_grid/axisline_style.py
- lib/mpl_toolkits/axes_grid/axislines.py
- lib/mpl_toolkits/axes_grid/clip_path.py
- lib/mpl_toolkits/axes_grid/floating_axes.py
- lib/mpl_toolkits/axes_grid/grid_finder.py
- lib/mpl_toolkits/axes_grid/grid_helper_curvelinear.py
- lib/mpl_toolkits/axes_grid/inset_locator.py
- lib/mpl_toolkits/axes_grid/parasite_axes.py
- lib/mpl_toolkits/axisartist/axes_divider.py
- lib/mpl_toolkits/axisartist/axes_grid.py
- lib/mpl_toolkits/axisartist/axes_rgb.py
- lib/mpl_toolkits/axisartist/parasite_axes.py
I cherry-picked one commit out of #7545 and some in-progress work. Whatever the case with the testing from the PR, we should probably fix the invalid imports before the release.
> Cleanup some toolkit six imports

- src/_path.h
> Remove four unused variables in src/_path.h.

- lib/matplotlib/axes/_axes.py
> Fix documents of semilogx and semilogy.

- INSTALL.rst
- doc/devel/contributing.rst
- doc/faq/installing_faq.rst
- doc/faq/troubleshooting_faq.rst
- doc/faq/virtualenv_faq.rst
- Document using pip for installation throughout (closes #7422).
- manylinux wheels are now available and a reasonable approach too.
- Move the git install faq below the non-git install faq.
- Most GUI toolkits are now pip and/or conda-installable on recent Pythons (GObject is the main outlier), update the venv docs as such.  In other cases, https://github.com/stuaxo/vext can be used to punch a hole from the venvs to system-site-packages in a controlled manner.
- Dedent the bullet list at http://matplotlib.org/devdocs/faq/troubleshooting_faq.html#getting-help, which currently appears within a blockquote.
- Suggest using `python -c "from pylab import *; plot(); show()" --verbose-helpful` for a minimal error message, which avoids needing to create a separate script file.
> Doc updates

- tutorials/introductory/usage.py
Deleted a single phrase 'circled in green'. 
Closes #9322
> Axis user guide

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/cbook/__init__.py
Fixes #9241 by adding a filter to `cbook.safe_first_element` to avoid returning masked values.
> Errorbar bugfix

- examples/event_handling/close_event.py
- examples/event_handling/data_browser.py
- examples/event_handling/looking_glass.py
- examples/event_handling/path_editor.py
Add one line descriptions for event handling examples
Part of https://github.com/matplotlib/matplotlib/issues/8921
- [ x] Code is PEP 8 compliant
> Add descriptions for remaining event handling examples

- examples/images_contours_and_fields/griddata_demo.py
- examples/images_contours_and_fields/shading_example.py
Adds one line description for images_contours_and_fields
part of https://github.com/matplotlib/matplotlib/issues/8921
- [X ] Code is PEP 8 compliant
> Update descriptions for images_contours_and_fields

- lib/matplotlib/backends/qt_editor/figureoptions.py
- lib/matplotlib/image.py
- lib/matplotlib/tests/test_image.py
> Fix poorly done deprecations in image.py.

- doc/_templates/citing.html
Makes it a bit easier for readers to find the paper.
> Add link to Matplotlib paper on citing page

- lib/matplotlib/backends/backend_macosx.py
- lib/matplotlib/backends/backend_webagg.py
Almost certain this will fix #9345.  Sorry...
> Fix backend refactor

- tutorials/introductory/sample_plots.py
- Added `imshow`, `pcolor`, and `contour` to `../tutorials/introductory/sample_plots.py`
- Changed `command` to `function`
- Removed `Demo` from many of the titles.  
Redo of #9387 (sorry @anntzer, who already commented)
> [Doc] Add pcolor, contour, imshow to  and other small changes

- examples/subplots_axes_and_figures/subplot_toolbar.py
- examples/subplots_axes_and_figures/subplots_adjust.py
Add descriptions for subplots_axes_and_figures
Extension to PRs for https://github.com/matplotlib/matplotlib/issues/8921
> Add examples for subplots_axes_and_figures

- doc/users/prev_whats_new/whats_new_1.5.rst
- examples/animation/histogram.py
- tutorials/intermediate/color_cycle.py
This is a fix of #8890 . Somehow the PR got borked because of a rebase, and I don't think it should be on @johnh202 to figure that out. So, this makes what I think were the intended changes, now based off of the matplotlib master branch. I've made John the author of this commit so that he still shows up in the commit history.
LMK if this looks OK. The PR has already been reviewed so I think as long as tests pass (and as long as John is cool w/ this) we should be good to merge.
> updating color cycle tutorial

- examples/event_handling/poly_editor.py
> Correct minor typo

- doc/conf.py
> DOC: point python intersphinx at python3 docs

- .appveyor.yml
> TST: Enable xdist on Appveyor

- doc/devel/contributing.rst
- doc/devel/testing.rst
- setupext.py
Trivial changeset to add more complete info for new devs getting started, fixes issue #9355
> DOC: fill out dev docs

- examples/text_labels_and_annotations/autowrap.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_base.py
> Get rid of a few unnecessary line continuations in strings.

- lib/matplotlib/tests/test_backends_interactive.py
It seems to fail quite regularly :-(
closes #9474
> Mark the interactive backend test as flaky.

- lib/matplotlib/colors.py
- lib/matplotlib/tests/test_axes.py
- setup.py
- docstring formatting in colors.py
- simplify test_stackplot_baseline by directly generating data rather than relying on an array-mutating function
- on missing, non-installable dependency in setup.py, just list the dependencies in a single line rather than trying to make a bullet list -- print_message will in fact linewrap the whole thing, mangling the markup attempt.
> minor (unrelated) cleanups

- lib/matplotlib/font_manager.py
> No need to fake sets with dicts anymore.

- tutorials/advanced/transforms_tutorial.py
in http://matplotlib.org/tutorials/advanced/transforms_tutorial.html#transformations-tutorial:
- remove extra backquotes after transData
- the last row of the table was incorrectly split; looks like I *need* a grid table to get around that (http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#simple-tables: "Also, this mechanism limits cells in the first column to only one line of text. Use grid tables if this limitation is unacceptable.")
> fix typo in rst markup

- examples/color/colormap_reference.py
For fast access. The user should not have to go to the tutorials to get the list of available colormaps.
> DOC Added the colormap references back

- lib/matplotlib/tests/test_axes.py
> TST: add test of normed histogram with unequal bins

- lib/matplotlib/backend_bases.py
just moving a comment into a docstring.
> Docstring fix.

- lib/matplotlib/legend_handler.py
- tutorials/intermediate/legend_guide.py
Adds a few docstrings to `legend_handler.py` that I found useful in figuring out what is going on there. Also minor fix to `legend_guide.py`.
> Add some legend handler documentation

- lib/matplotlib/stackplot.py
Will self merge if tests pass.
> Fix PEP8 in stackplot

- lib/matplotlib/axes/_base.py
- lib/matplotlib/figure.py
- lib/matplotlib/ticker.py
This should finish closing #7205.
Also note the funny typo previously in the docs of the `minor` kwarg...
- [NA] Has Pytest style unit tests
- [NA] Code is PEP 8 compliant 
- [NA] New features are documented, with examples if plot related
- [NA] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [NA] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way
> Minor doc markup fixes.

- lib/mpl_toolkits/axes_grid1/inset_locator.py
Snuck in via #9615 .  Master was failing due to the pandas issue and we let a pep8 issue through :disappointed: .
> STY: remove trailing whitespace

- doc/users/next_whats_new/2017-10_capstyle.rst
- doc/users/whats_new.rst
Moves the whats new entry from #8277
> DOC: move whats_new entry to next_whats_new folder

- lib/matplotlib/dates.py
> Only set view/data intervals if axis is set in AutoDateLocator

- examples/color/colormap_reference.py
- lib/matplotlib/cm.py
> Further improve colormap discussion.

- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/texmanager.py
(*very* technically breaks backcompat, but it's not as if these were
likely to be used at all or as if there was a good way to emit a
warning.)
> Remove unused global cmd_split variable.

- lib/matplotlib/dviread.py
> Convert dviread to use lru_cache.

- doc/api/axes_api.rst
- lib/matplotlib/axes/_base.py
The previous order was a bit of a mess.
I went for
set_xfoo, get_xfoo, set_yfoo, get_yfoo
although
set_xfoo, set_yfoo, get_xfoo, get_yfoo
would probably have worked equally well.
Also fixed a few docstrings on the way.
> Reoder Axes API docs.

- .appveyor.yml
- .circleci/config.yml
- .travis.yml
> On CI, just let pip resolve most dependencies.

- .appveyor.yml
xref https://github.com/matplotlib/matplotlib/pull/9673#issuecomment-341877527: I apparently managed to break the Appveyor tests without Appveyor reporting a failure :-)
> Actually install the deps on Appveyor.

- examples/api/colorbar_basics.py
- examples/api/custom_projection_example.py
- examples/api/custom_scale_example.py
- examples/api/donut.py
- examples/api/engineering_formatter.py
- examples/api/filled_step.py
- examples/api/histogram_path.py
- examples/api/image_zcoord.py
- examples/api/joinstyle.py
- examples/api/legend.py
- examples/api/line_with_text.py
- examples/api/mathtext_asarray.py
- examples/api/power_norm.py
Improve api examples.
Removes the redundant keywords in some of api examples and improve them.
- [ X] Code is PEP 8 compliant
> Update API examples

- examples/axisartist/demo_floating_axis.py
- lib/matplotlib/backends/backend_qt5.py
> Remove a few unnecessary global statements.

- INSTALL.rst
- doc/conf.py
- examples/user_interfaces/README.wx
- examples/user_interfaces/embedding_in_wx2_sgskip.py
- examples/user_interfaces/embedding_in_wx3_sgskip.py
- examples/user_interfaces/embedding_in_wx4_sgskip.py
- examples/user_interfaces/embedding_in_wx5_sgskip.py
- examples/user_interfaces/fourier_demo_wx_sgskip.py
- examples/user_interfaces/wxcursor_demo_sgskip.py
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/backends/wx_compat.py
- setupext.py
2.9 was released in 2010; in fact, *before*
2.8.12 (the previous min version), see
https://github.com/wxWidgets/wxPython/releases?after=wxPy-2.9.2.1
Remove some conditional code.
> Raise minimum WX version to 2.9.

- lib/matplotlib/lines.py
(Otherwise the rst parser sees that line as two separate entries in the
table.)
> Minor markup fix.

- lib/matplotlib/backends/backend_nbagg.py
Fixes #9729
Doesn't actually handle block (if it should).
> Allow _BackendNbAgg.show() to take keyword "block"

- doc/api/api_changes/removed-attributes.rst
- lib/matplotlib/backends/backend_agg.py
- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/colors.py
- lib/matplotlib/font_manager.py
- lib/matplotlib/mathtext.py
- lib/matplotlib/path.py
- lib/matplotlib/textpath.py
> Rely more on lru_cache rather than custom caching.

- lib/matplotlib/pyplot.py
Closes #9740.
Feel free to directly push additional edits.
I intentionally replaced "typical call signature" by "call signature" for simplicity.
> Reword subplot() doc.

- doc/api/api_changes/01-11-2017-DS.rst
> Add API note about MovieWriterRegistry exception

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/tests/test_axes.py
Fixes #5898. Hopefully the comment I've added in the code should make it clear what's going on.
> Correctly convert units for a stacked histogram

- MANIFEST.in
> BLD: update MANIFEST.in to account for moved files

- doc/users/next_whats_new/2017_11_15_datetime64.rst
- examples/api/date.py
Should have been in #9779.  Sorry!
> DOC: for datetime64 support

- .github/PULL_REQUEST_TEMPLATE.md
- doc/devel/documenting_mpl.rst
- doc/make.py
Update PULL_REQUEST_TEMPLATE.md to emphasize markup specificities in RST
(as opposed to md) regarding double/single backquotes and asterisks.
(I'm a bit tired of pointing to this every other docstring PR.)
In documenting_mpl.rst:
- Various reformattings/line wrappings/rewordings.
- Explicitly mark the highlighting language of each code block, as we
have a mix of python/shell/rst (and emacs lisp).
- Drop unneeded `:func:`/`:class:` markups.
- Drop request to line wrap docstrings at 70 characters (in practice
they are line-wrapped at 79 like normal Python sources).
- Do not forbid spanned cells in tables, which recent Sphinxes handles
just fine.
In make.py:
- Simplify argument parsing, slightly improving output of `./make.py
--help`
> Update docs on docs.

- lib/matplotlib/sphinxext/tests/test_tinypages.py
> Simplify test_tinypages.

- lib/matplotlib/widgets.py
> FIX: TextBox.disconnect remove from registries that TextBox has

- lib/matplotlib/ticker.py
- tutorials/text/text_intro.py
Working on the default DateLocators I noted that I couldn't really find a good place where Locators are explained.  `tutorials/text/text_intro.py` seems like a good place to explain these things.
> DOC: add more tutorial to text/text_intro

- tutorials/text/text_intro.py
making the table proposed at https://github.com/matplotlib/matplotlib/pull/9827/files#r152655635 (attn @jklymak)
> Move enumeration of text tutorial into table.

- doc/api/axis_api.rst
The heading for `XAxis` related docs was under `YAxis`.
- [x ] Documentation is sphinx and numpydoc compliant
> Fix typo in axis api doc

- examples/animation/animation_demo.py
Focus the pyplot animation demo to just 1) do some simple plotting, 2)
call pause().
Yes, it would be more efficient to reuse the same image.  But if we are
not using the animation module, efficiency is probably the least of our
worries.
> Simplify the pyplot animation demo.

- lib/matplotlib/backend_bases.py
- lib/matplotlib/backend_tools.py
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_tkagg.py
The Tools used by Toolmanager assumed every backend understood `.png` files for the button images.
This is not the case, for example tk works with png in linux but not on mac
This pr fixes this by asking each backend for it's preferred image format
> dynamically finding the backend preferred format for button images

- lib/matplotlib/projections/geo.py
If you benchmark it, the Aitoff projection is [slightly slower than the others](https://qulogic.github.io/mpl-bench/#basic.time_projection). This is because of the use of `np.ma.MaskedArray` which is a bit slow. Using indexing works just the same and is fast enough to make Aitoff run about the same speed as the others. Benchmarking the function directly shows indexing to be faster no matter if the input length is 1 or 1000000 or the number of zeros is 0% or 100%.
(Actually, if you look at the history, polar plots also got a bit slower at some point, though not as slow as Aitoff. This is due to some extra resets from the new tick handling. I have a change in the works to get rid of this soon.)
- [N/A] Documentation is …
> PRF: Don't used MaskedArray in Aitoff transform.

- lib/matplotlib/__init__.py
> Clean tmpdir at exit.

- lib/matplotlib/cbook/__init__.py
> Vectorize and document simple_linear_interpolation.

- doc/devel/documenting_mpl.rst
This is an enhacement to the great work of #9805. The aforementioned PR addresses many points of #9786 and closed it.
IMHO there were some additional points worth mentioning. I've added them in this pull request, before they get lost. The content stems from the discussion in #9786 and the issues linked therein. I hope, I've got everyting right.
Note: I'm aware of #9872, which addresses other enhancements to the documentation guide.
> Additions to the documentation guide

- .appveyor.yml
- .travis.yml
#9878 blacklists a broken pytest version.
I'll merge up when this passes, to avoid any more future conflicts.
> Backport 9878

- doc/users/next_whats_new/20171119-transforms-repr.rst
- lib/matplotlib/projections/geo.py
- lib/matplotlib/projections/polar.py
- lib/matplotlib/transforms.py
This patch should make debugging the transform a bit stack easier, by
changing, for example, the repr of the transform of a line created with
`plot([1, 2])` from
CompositeGenericTransform(TransformWrapper(BlendedAffine2D(IdentityTransform(),IdentityTransform())), CompositeGenericTransform(BboxTransformFrom(TransformedBbox(Bbox([[-0.05, 0.95], [1.05, 2.05]]), TransformWrapper(BlendedAffine2D(IdentityTransform(),IdentityTransform())))), BboxTransformTo(TransformedBbox(Bbox([[0.125, 0.10999999999999999], [0.9, 0.88]]), BboxTransformTo(TransformedBbox(Bbox([[0.0, 0.0], [6.4, 4.8]]), Affine2D(array([[ 100.,    0.,    0.],
[   0.,  100.,    0.],
[   0.,    0.,    1.]]))))))))
to
CompositeGenericTransform(
TransformWrapper(
BlendedAffine2D(
IdentityTransform(),
IdentityTransform())), …
> Improve reprs of transforms.

- lib/matplotlib/pyplot.py
> DOC: correct inverted description of aspect

- doc/api/api_changes/2017-12-01-AL.rst
- lib/matplotlib/contour.py
> Deprecate unused ContourLabeler.get_real_label_width.

- doc/api/api_changes/2017-11-31-AL.rst
- lib/matplotlib/contour.py
- lib/matplotlib/mlab.py
- lib/matplotlib/tests/test_patheffects.py
Also, in contour (the only place that used it), -1 (instead of nan) is
a perfectly reasonable marker for out of bounds which avoids having to
dance with the errstate.
Replaces #9859: @efiring pointed out and I confirmed that we neither implement nor need linear extrapolation, so np.interp is perfectly sufficient.
Made a separate PR as the approach is somewhat different.
> less_simple_linear_interpolation can be replaced by np.interp.

- lib/matplotlib/tests/test_agg.py
- lib/matplotlib/tests/test_animation.py
- lib/matplotlib/tests/test_backend_bases.py
- lib/matplotlib/tests/test_backend_pdf.py
- lib/matplotlib/tests/test_contour.py
- lib/matplotlib/tests/test_dates.py
- lib/matplotlib/tests/test_rcparams.py
- lib/matplotlib/tests/test_text.py
- lib/matplotlib/tests/test_usetex.py
> In tests, remove unused imports and sort some remaining imports.

- lib/matplotlib/patches.py
xref https://github.com/matplotlib/matplotlib/pull/9072#pullrequestreview-81014074
> Fix Rectange.get_bbox()

- lib/matplotlib/axes/_base.py
> Numpydoc conversion and clarification of some AxesBase docstrings

- lib/matplotlib/backends/backend_tkagg.py
Fix https://github.com/matplotlib/matplotlib/issues/9943
> toolbar checkbutton fix bug in tkinter python3.6

- .travis.yml
- doc/glossary/index.rst
- doc/users/next_whats_new/2017-12-04-AL-pgi.rst
- lib/matplotlib/backends/_gtk3_compat.py
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_gtk3agg.py
- lib/matplotlib/backends/backend_gtk3cairo.py
- lib/matplotlib/tests/test_backends_interactive.py
xref #4810: allow using pgi instead of gi as bindings for gtk3.
The *only* reason to use pgi is really to allow testing on Travis (and similar contexts), hence the deliberate choice not to expose a rcParam.
> Support pgi as alternative gobject bindings.

- lib/matplotlib/backend_managers.py
Fix old docstring for ToolManager
ToolManager keeps a reference to figure not to FigureManager
> fix docstring in ToolManager

- examples/api/scatter_piecharts.py
> Fix scatter_piecharts example

- lib/matplotlib/mlab.py
This commit fixes #10003 with a single-character change.
> Fixed critical typo in mlab.cohere

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/container.py
> Improve errorbar returns doc

- .github/PULL_REQUEST_TEMPLATE.md
1. Move all the comment text to the bottom of the template.  This allows
one to fill in the relevant fields without having to look for them
through a wall of text.
2. Reword the comments in a slightly more compact/concise manner (I
believe we can maintain a friendly tone without repeating "please" 9
times in 15 sentences).
> Cleanup issue template.

- lib/matplotlib/colors.py
- lib/matplotlib/tests/test_colors.py
Colors in Matplotlib can come in many weird and wonderful forms; this allows two colors to be compared.
> Add method for comparing two colors

- lib/matplotlib/widgets.py
Explaining what draw a line does in RectangularSelector in doc.
> Doc update: Explain what drawing a line does in RectangularSelector.

- lib/matplotlib/backends/backend_gtkagg.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/backends/qt_editor/formlayout.py
- lib/matplotlib/offsetbox.py
- lib/matplotlib/sankey.py
- lib/matplotlib/transforms.py
> Remove some debugging code.

- doc/devel/contributing.rst
A lot of bullet/numbered lists in contributing.rst are overindented,
causing them to be displayed with too much indentation in the rendered
rst.  Compare e.g.
https://matplotlib.org/devdocs/devel/documenting_mpl.html#keyword-arguments
(correct indentation of "1. single point configuration etc.")
and
https://matplotlib.org/devdocs/devel/contributing.html#submitting-a-bug-report
(extra indentation of "1. A short, top-level summary etc.")
This PR dedents them.
Also closes #9200.
> Dedent docs in contributing.rst bullet/numbered lists.

- examples/api/collections.py
- examples/api/scatter_piecharts.py
- examples/event_handling/poly_editor.py
- examples/event_handling/trifinder_event_demo.py
- examples/lines_bars_and_markers/scatter_custom_symbol.py
- examples/lines_bars_and_markers/scatter_star_poly.py
- examples/shapes_and_collections/line_collection.py
- examples/statistics/boxplot_demo.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/bezier.py
- lib/matplotlib/offsetbox.py
- lib/matplotlib/patches.py
- lib/matplotlib/sankey.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_category.py
- lib/matplotlib/tests/test_streamplot.py
- lib/matplotlib/tests/test_transforms.py
- lib/mpl_toolkits/axisartist/clip_path.py
- lib/mpl_toolkits/axisartist/floating_axes.py
- lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
- lib/mpl_toolkits/mplot3d/art3d.py
- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/mplot3d/proj3d.py
Replace by zip(...) when the result is immediately unpacked.  Replace
by np.column_stack when operating on arrays or when the result will be
immediately converted to an array (e.g. by the Path constructor), as
column_stack is faster in these cases.
(This commit does not remove *all* instances of list(zip(...)).)
> Remove list(zip(...)) when unnecessary.

- lib/matplotlib/colors.py
> Simplify Colormap.__call__.

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/legend_handler.py
- lib/matplotlib/sankey.py
- lib/matplotlib/stackplot.py
- lib/mpl_toolkits/axisartist/clip_path.py
> replace six.next -> next (available since Py2.6).

- lib/matplotlib/container.py
> Let Container reprs report the actual subtype.

- lib/matplotlib/mathtext.py
Not sure how to trigger this issue though.
Closes #9429
> FIX: non-existing variable

- lib/matplotlib/backends/backend_cairo.py
The comment regarding '%%Orientation: Portrait' has been invalid for
more than 10 years, specifically since
https://cgit.freedesktop.org/cairo/commit/?id=09dfd6c3c16ed36b0e9693cfcbb3b679bd18f585
> Minor cleanups to the cairo backend.

- lib/matplotlib/_pylab_helpers.py
The module is private so it's fair game to directly get rid of
error_msg.
> Minor simplification to _pylab_helpers.

- lib/matplotlib/backends/backend_gtk3cairo.py
- lib/matplotlib/transforms.py
- pytest.ini
> Minor style cleanups.

- doc/faq/virtualenv_faq.rst
I don't think we should recommand manual symlinking now that vext is a
perfectly reasonable alternative.
vext 0.7 fixes logging configuration per
https://github.com/stuaxo/vext/issues/43.
> Update docs on installing GUI toolkits in virtualenvs.

- doc/users/navigation_toolbar.rst
The feature has been around for a long time already; update the doc
accordingly.
pointed out by @rayosborn in #10136.
> Zoom out to rectangle is not experimental anymore.

- doc/api/api_changes/2017-12-26-AL.rst
- lib/matplotlib/tests/test_skew.py
- lib/matplotlib/tight_layout.py
- lib/matplotlib/widgets.py
> Some docstring fixes and change a raise type

- lib/matplotlib/backends/backend_qt5agg.py
In 9b8a944db954c8240e14413e517e1b781881b80b the latch logic was moved
above the call to `self.draw` to de-latch the call to
`__draw_idle_agg` in `paintEvent` to protect against `blit` calls
during a draw.
However, this now fails to properly latch the base draw so with
`plt.ion` (not in IPython) the stale callback will cause a (possibly
infinite) recursion in the draw due to stale being set as part of the
draw call (which will re-trigger the draw).
This adds a second flag to track if we are currently rendering and
bail.
closes #10140
I suspect a better fix is to re-think how the stale callbacks propagate or how the non-ipython stale callback works, but I think this is the minimal change which fixes a critical issue.
> FIX: prevent recursive draws with plt.ion not in IPython with qt5agg

- lib/matplotlib/axes/_base.py
- lib/matplotlib/colorbar.py
- lib/matplotlib/contour.py
- lib/matplotlib/figure.py
- lib/matplotlib/legend.py
- lib/matplotlib/lines.py
- lib/matplotlib/patches.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/text.py
- lib/matplotlib/tri/tricontour.py
- lib/mpl_toolkits/axes_grid1/axes_grid.py
- lib/mpl_toolkits/axes_grid1/colorbar.py
- lib/mpl_toolkits/mplot3d/axes3d.py
- tutorials/text/text_props.py
All's in the title (plus various minor doc rewordings).
> Replace "True | False" by "bool" in the docs.

- .travis.yml
- INSTALL.rst
- doc/devel/contributing.rst
- doc/devel/testing.rst
- setupext.py
... to make sure that they are indeed supported.
Basically to avoid issues like like https://github.com/matplotlib/matplotlib/pull/9303.
> On 2.7, run tests on oldest documented supported pytest and pytest-cov.

- lib/matplotlib/axes/_base.py
- lib/matplotlib/tests/test_image.py
Redo of #4137 which has gone stale.  Closes #2508.
> Make relim() take images into account too.

- lib/matplotlib/axes/_axes.py
As part of #10148: Docstring update for `Axes.broken_bar`
> improve Axes.broken_barh docstring

- doc/_templates/donate_sidebar.html
- doc/_templates/index.html
- doc/_templates/layout.html
Changing the link targets at Gina's request.
> Doc change flipcase link

- examples/api/axes_margins.py
> Remove executable bit from example.

- doc/users/next_whats_new/2017_12_17_compare_colors.rst
Issue #10069 
I have updated the what's new entry for the color comparision method. I think we can close the old PR #10071
> Updated what's new entry for color comparision method

- lib/matplotlib/tests/test_image.py
- lib/mpl_toolkits/axes_grid1/mpl_axes.py
- lib/mpl_toolkits/axes_grid1/parasite_axes.py
- lib/mpl_toolkits/axisartist/angle_helper.py
- lib/mpl_toolkits/axisartist/axislines.py
- lib/mpl_toolkits/axisartist/grid_finder.py
- lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
- lib/mpl_toolkits/mplot3d/art3d.py
- pytest.ini
> Remove most instances of pep8 E502 (redundant backslashes).

- lib/matplotlib/__init__.py
This is just a minor refactoring of the `_preprocess_data` decorator when I looked into #10189.
It extracts the docstring manipulation to a dedicated function. The functionality itself is unchanged so far. But it will help for working on #10189 further whatever will be decided there.
> Minor refactoring of docstring formatting in preprocess_data

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/stackplot.py
As part of #10148: Docstring updates for `Axes.bar`, `Axes.barh` and `Axes.stackplot`.
> improve docstrings for Axes.bar, Axes.barh, Axes.stackplot

- lib/matplotlib/rcsetup.py
> Deprecate support for "svg fonts" font embedding.

- lib/matplotlib/_mathtext_data.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/backend_cairo.py
- lib/matplotlib/backends/backend_macosx.py
- lib/matplotlib/backends/backend_template.py
- lib/matplotlib/projections/geo.py
- lib/matplotlib/sphinxext/plot_directive.py
- lib/matplotlib/testing/decorators.py
- lib/matplotlib/testing/jpl_units/UnitDblConverter.py
- lib/matplotlib/testing/jpl_units/__init__.py
- lib/matplotlib/tests/test_rcparams.py
- lib/matplotlib/type1font.py
- lib/mpl_toolkits/axes_grid/parasite_axes.py
- lib/mpl_toolkits/axisartist/__init__.py
- lib/mpl_toolkits/axisartist/axes_divider.py
- lib/mpl_toolkits/axisartist/axes_rgb.py
- lib/mpl_toolkits/axisartist/grid_finder.py
- lib/mpl_toolkits/axisartist/parasite_axes.py
- lib/mpl_toolkits/mplot3d/axis3d.py
- pytest.ini
- setup.py
- setup_external_compile.py
For some files which are "nearly" correct and can thus have an
pep8ignore entry removed after the fix.
> Wrap a few overly long lines.

- lib/matplotlib/backends/backend_tkagg.py
An import went missing probably during some rebase of #9275, so that just broke tkagg.  Sorry :/
> Add missing import to backend_tkagg.

- ci/travis/test_script.sh
This may or may not help with Travis, if we're lucky.
> TST: Don't use set -e.

- lib/matplotlib/axes/_axes.py
Had a recent train journey, so I have a few general docstring cleaning branches hanging around.
> Clean up _axes.py docstrings

- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/fontconfig_pattern.py
- lib/matplotlib/type1font.py
- in backend_ps: when writing to a unicode file, no need to first read the entire tempfile in memory and then decode it; just do everything in one step.
- in type1font: str.split() already strips spaces at the edges of the string (see https://docs.python.org/3/library/stdtypes.html#str.split).
> Minor cleanups.

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/dates.py
Backport of PR #10246: Improve docstring of `Axes.plot_date`
> Backport of PR #10246: Improve docstring of Axes.plot_date

- doc/api/api_changes.rst
- doc/devel/MEP/MEP14.rst
- doc/devel/MEP/MEP19.rst
- doc/devel/MEP/MEP22.rst
- doc/devel/MEP/MEP23.rst
- doc/devel/MEP/MEP26.rst
- doc/devel/MEP/MEP28.rst
- doc/devel/MEP/MEP29.rst
- doc/devel/contributing.rst
- doc/mpl_toolkits/mplot3d/faq.rst
- examples/api/colorbar_basics.py
- examples/axes_grid1/demo_axes_divider.py
- examples/axisartist/simple_axisline.py
- examples/misc/multiprocess_sgskip.py
- setup_external_compile.py
- setupext.py
- tools/subset.py
- tutorials/colors/colormaps.py
- tutorials/introductory/usage.py
- tutorials/text/mathtext.py
- tutorials/toolkits/axisartist.py
> Some comment typo fixes

- lib/matplotlib/backends/backend_ps.py
Handles review comment that I missed in https://github.com/matplotlib/matplotlib/pull/10248#discussion_r161409439.
Probably I should just merge _print_figure and _print_figure_tex at some point...
> Minor refactor of backend_ps.

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/container.py
As part of #10148 and part of the discussion in #10151: Docstring updates for `Axes.stem` and `container`.
> improve Axes.stem docstring

- doc/users/whats_new.rst
Fixes capitalization in the documentation code snippet.
> whats_new.rst: "C" must be capitalized in "CreationDate"

- doc/users/next_whats_new/2018-01-10-AL-pathlike.rst
- lib/matplotlib/animation.py
- lib/matplotlib/backends/backend_agg.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/image.py
- lib/matplotlib/tests/test_animation.py
- lib/matplotlib/tests/test_backend_pdf.py
- lib/matplotlib/tests/test_figure.py
- lib/matplotlib/tests/test_image.py
My take on PathLike support.
Alternate for #8481; marked as release critical only in the sense that one of the two PRs should go in...
Also xref https://github.com/matplotlib/matplotlib/pull/10048.
> Support PathLike inputs.

- lib/matplotlib/__init__.py
git log shows that this has been obsolete since *at least* 2010.
> Deprecate obsolete 'plugins.directory' rcparam.

- doc/users/next_whats_new/180112-AL-pillowanim.rst
- doc/users/next_whats_new/2017-10-19_axes_legend_in_tightbbox.rst
- doc/users/next_whats_new/2017-10_capstyle.rst
- doc/users/next_whats_new/2017_10_10_logging.rst
- doc/users/next_whats_new/2017_11_19_title_pad.rst
- doc/users/next_whats_new/2017_12_17_compare_colors.rst
- doc/users/next_whats_new/2018-01-10-AL-pathlike.rst
- doc/users/next_whats_new/2018_01_10_pypy_tkagg_support.rst
- doc/users/next_whats_new/new_color_cycle.rst
A minor cleanup of what's new
- Make tense of titles consistent
- Made title underlining consistent
> Clean up next what's new files

- lib/matplotlib/axis.py
Extracted from #9727 and its review.
> Simplify Axis.get_{major,minor}_ticks.

- .travis.yml
Alternative to #10315 to fix pyqt5 test on Travis?
> TST FIX pyqt5 5.9

- lib/matplotlib/artist.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
- lib/matplotlib/cm.py
- lib/matplotlib/collections.py
- lib/matplotlib/legend.py
- lib/matplotlib/lines.py
- lib/matplotlib/patches.py
- lib/matplotlib/text.py
- lib/mpl_toolkits/mplot3d/axes3d.py
Docstring cleanup:
Following #10284 this PR changes ACCEPTS from comment blocks to inline comments.
> Make commented ACCEPTS statements inline comments

- lib/matplotlib/backends/backend_pgf.py
- pytest.ini
> Linewrap backend_pgf to 79 characters.

- lib/matplotlib/projections/geo.py
- lib/matplotlib/projections/polar.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/transforms.py
- lib/matplotlib/widgets.py
I find these clearer in intent than explicit multiplication, but again
YMMV...
> Use deg2rad/rad2deg where appropriate.

- lib/matplotlib/animation.py
- lib/matplotlib/backends/backend_pgf.py
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/legend.py
See e.g. https://docs.python.org/3/library/functions.html#sum that
documents "".join as the preferred method (briefly, because summing (or
repeated addition) has quadratic complexity for strings).
side note:
https://github.com/takluyver/astsearch and https://github.com/hchasestevens/astpath are quite nice for this kind of cleanups...
> Join strings instead of adding them.

- examples/misc/font_indexing.py
- examples/tests/backend_driver_sgskip.py
- examples/text_labels_and_annotations/dashpointlabel.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/backends/backend_agg.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/colorbar.py
- lib/matplotlib/mathtext.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_colors.py
- lib/matplotlib/tests/test_triangulation.py
- lib/matplotlib/ticker.py
- lib/matplotlib/widgets.py
- lib/mpl_toolkits/axes_grid1/axes_grid.py
- lib/mpl_toolkits/axes_grid1/colorbar.py
- lib/mpl_toolkits/axisartist/axis_artist.py
- lib/mpl_toolkits/axisartist/clip_path.py
- lib/mpl_toolkits/mplot3d/axis3d.py
- tools/subset.py
- unit/mlab_unit.py
> Remove some commented out debug prints.

- examples/images_contours_and_fields/quadmesh_demo.py
> Minor improvements to quadmesh_demo.

- examples/api/mathtext_asarray.py
- examples/color/color_cycle_default.py
- examples/lines_bars_and_markers/stackplot_demo.py
- examples/statistics/hist.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/backends/backend_agg.py
- lib/matplotlib/backends/backend_mixed.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/colors.py
- lib/matplotlib/contour.py
- lib/matplotlib/dates.py
- lib/matplotlib/figure.py
- lib/matplotlib/image.py
- lib/matplotlib/mlab.py
- lib/matplotlib/patches.py
- lib/matplotlib/streamplot.py
- lib/matplotlib/testing/compare.py
- lib/matplotlib/testing/jpl_units/Duration.py
- lib/matplotlib/tests/test_collections.py
- lib/matplotlib/tests/test_mlab.py
- lib/matplotlib/textpath.py
- lib/matplotlib/ticker.py
- lib/mpl_toolkits/axes_grid1/axes_size.py
- lib/mpl_toolkits/axisartist/angle_helper.py
- lib/mpl_toolkits/mplot3d/axes3d.py
- lib/mpl_toolkits/mplot3d/proj3d.py
- tutorials/colors/colormaps.py
- unit/memleak.py
Most of these calls probably date back to the time before
`__future__`-division existed...
Note that this will have the side effect that some functions that were
accidentally accepting strings instead of floats before will no longer
accept strings -- which seems fine to me.
> Remove unnecessary calls to float() before division.

- doc/api/api_changes/2018-01-29-AL.rst
- lib/matplotlib/backends/backend_tkagg.py
Obsolete since the removal of "classic" (pre-toolbar2) toolbar support
in 4243470.
> Deprecate backend_tkagg.AxisMenu.

- lib/matplotlib/tests/test_backend_pgf.py
- lib/matplotlib/tests/test_compare_images.py
> Update some image_comparison tests.

- doc/conf.py
- doc/devel/MEP/MEP23.rst
- doc/devel/documenting_mpl.rst
- doc/sphinxext/custom_roles.py
- lib/matplotlib/animation.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/backends/__init__.py
- lib/matplotlib/dates.py
- lib/matplotlib/figure.py
- lib/matplotlib/legend.py
- lib/matplotlib/text.py
- lib/matplotlib/ticker.py
Make referencing rcParams in the docs a bit easier.  See #10225 for example of motivation.
Note that this version doesn't actually create any link, but that could come as a followup.
> Custom :rcparam: role.

- lib/matplotlib/axes/_axes.py
As part of #10148: Docstring update for ``Axes.step``.
> improve docstring of Axes.step

- lib/matplotlib/units.py
I don't actually know what some of the docstrings mean, but I figure fixing the grammar is probably a good thing to do anyway.
> Clean up units.py

- doc/README.txt
- doc/conf.py
- doc/devel/documenting_mpl.rst
- doc/mpl_examples
- doc/sphinxext/math_symbol_table.py
- doc/sphinxext/mock_gui_toolkits.py
- doc/sphinxext/skip_deprecated.py
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/collections.py
- pytest.ini
Split out extensions to their own files.
Emit the latex symbol tables without breaks.
> Cleanup doc/conf.py & local sphinx extensions

- lib/matplotlib/units.py
Some small updates to the units documentation that makes a couple of things clearer.
> Minor updates to unit doc

- lib/matplotlib/figure.py
Just a couple things that numpydoc warns about, but seems to ignore otherwise.
> DOC: Fix typos in section names.

- INSTALL.rst
- doc/api/api_changes.rst
- doc/devel/testing.rst
- doc/faq/howto_faq.rst
- doc/index.rst
- doc/users/history.rst
- doc/users/prev_whats_new/changelog.rst
- doc/users/prev_whats_new/whats_new_1.0.rst
- examples/images_contours_and_fields/shading_example.py
- tutorials/introductory/images.py
I'm going to say this fixes #9147, since there's only a handful of broken links left that don't seem to be fixable.
> Fix some broken links

- lib/matplotlib/image.py
This fixes (at least locally) the doc build. I have no idea why.
> Add docstring to set_interpolation

- lib/matplotlib/image.py
Getting a doc build error in #10436 and I think this should fix it.
> Fix doc build error.

- .appveyor.yml
- .circleci/config.yml
- .travis.yml
- INSTALL.rst
- ci/travis/test_script.sh
- doc/faq/installing_faq.rst
- lib/matplotlib/__init__.py
- lib/matplotlib/dates.py
- setup.py
- setupext.py
Matplotlib 3.0 will not support python2.7
> API: only support python 3.5+

- INSTALL.rst
Add activestate link for pre-built distributions
> DOC: add active state to install docs

- lib/matplotlib/font_manager.py
- lib/matplotlib/type1font.py
Just a couple of commits I've had lying around, and I don't think I'll have any time to extend it across the entire file. Might as well get the changes in instead of them just sitting there.
> Some font-related numpydoc changes

- lib/matplotlib/__init__.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/sphinxext/plot_directive.py
- lib/matplotlib/testing/compare.py
- lib/matplotlib/testing/decorators.py
- lib/matplotlib/texmanager.py
> mkdir is in the stdlib in Py3.

- doc/api/next_api_changes/2018-02-15-AL-deprecations.rst
- lib/matplotlib/axes/_axes.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/collections.py
- lib/matplotlib/lines.py
- lib/matplotlib/markers.py
- lib/matplotlib/patches.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/units.py
- lib/mpl_toolkits/axes_grid1/axes_grid.py
- lib/mpl_toolkits/axes_grid1/axes_size.py
Since we bumped the min numpy version to 1.10, numpy scalars are now
also instances of numbers.Number.
Closes #7795.
(Related note: we can't do the same with iterable/isinstance(..., Iterable) as documented at https://docs.python.org/3/library/collections.abc.html#collections.abc.Iterable.)
> Replace is_numlike by isinstance(..., numbers.Number).

- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/tests/test_backend_pdf.py
Remove the now-superfluous compatibility code
> Remove Python 2 compatibility code from backend_pdf.py

- examples/showcase/xkcd.py
Separate plots using full line of `#` characters in [matplotlib/examples/showcase/xkcd.py](https://github.com/matplotlib/matplotlib/blob/master/examples/showcase/xkcd.py) for Sphinx-gallery rendering per issue #8922
> Separate plots using #### in xkcd.py

- lib/matplotlib/backends/backend_svg.py
> Use HTTP Secure for matplotlib.org

- README.rst
> The current master branch is now python 3 only.

- doc/api/next_api_changes/2018-02-15-AL-deprecations.rst
- lib/matplotlib/mathtext.py
> Py3fy mathtext.py.

- doc/api/next_api_changes/2018-02-15-AL-deprecations.rst
- lib/matplotlib/cbook/__init__.py
st_ino has been implemented in Windows for a while
(https://hg.python.org/cpython/rev/9cd1036455e7).
> Modernize cbook.get_realpath_and_stat.

- lib/matplotlib/backends/backend_gtk3.py
- lib/mpl_toolkits/axes_grid1/mpl_axes.py
- lib/mpl_toolkits/axisartist/axislines.py
Some super() occurrences not addressed in #10527.
> More argumentless (py3) super()

- doc/users/next_whats_new/more-cairo.rst
- doc/users/whats_new.rst
This should un-break the docs build on this branch.
> DOC: move tkcairo into main whats_new

- lib/matplotlib/figure.py
> Minor simplification to Figure.__getstate__ logic.

- lib/matplotlib/mlab.py
Note I've changed `np` to `numpy` to make things clearer. Partially solves #10382.
> Add some mlab alternatives

- lib/matplotlib/__init__.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/axis.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/dviread.py
- lib/matplotlib/patches.py
- lib/matplotlib/testing/decorators.py
- lib/matplotlib/transforms.py
- lib/mpl_toolkits/axisartist/axislines.py
- lib/mpl_toolkits/axisartist/floating_axes.py
- lib/mpl_toolkits/axisartist/grid_helper_curvelinear.py
> Use 'yield from' where appropriate.

- examples/event_handling/ginput_manual_clabel_sgskip.py
- lib/matplotlib/afm.py
- lib/matplotlib/animation.py
- lib/matplotlib/backends/backend_gtk3.py
- lib/matplotlib/backends/backend_pdf.py
- lib/matplotlib/backends/backend_ps.py
- lib/matplotlib/backends/backend_svg.py
- lib/matplotlib/backends/backend_webagg.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/colorbar.py
- lib/matplotlib/contour.py
- lib/matplotlib/dviread.py
- lib/matplotlib/figure.py
- lib/matplotlib/lines.py
- lib/matplotlib/mathtext.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/sphinxext/plot_directive.py
- lib/matplotlib/streamplot.py
- lib/matplotlib/testing/disable_internet.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/ticker.py
- lib/matplotlib/tight_layout.py
- lib/matplotlib/transforms.py
- lib/matplotlib/tri/triinterpolate.py
- lib/matplotlib/widgets.py
- lib/mpl_toolkits/axisartist/axis_artist.py
- lib/mpl_toolkits/axisartist/grid_finder.py
Closes (among other things) item 3 of #10556.
> Various style fixes.

- tutorials/intermediate/constrainedlayout_guide.py
> Might be `figure.constrained_layout.use`

- lib/matplotlib/artist.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/backends/backend_svg.py
> Minor style fixes.

- lib/matplotlib/colorbar.py
- lib/mpl_toolkits/axes_grid1/colorbar.py
(Not sure it's *really* more legible, but I don't think it's worse and
it's shorter...)
Closes item 2 of #10556.
> Use np.stack instead of list(zip()) in colorbar.py.

- tutorials/intermediate/constrainedlayout_guide.py
> Fixes to constrainedlayout tutorial markup.

- lib/matplotlib/backends/_gtk3_compat.py
- lib/matplotlib/backends/backend_gtk3agg.py
- lib/matplotlib/backends/backend_gtk3cairo.py
- lib/matplotlib/backends/backend_qt4.py
- lib/matplotlib/backends/backend_qt4agg.py
- lib/matplotlib/backends/backend_qt5agg.py
- lib/matplotlib/backends/backend_qt5cairo.py
- lib/matplotlib/backends/backend_tkagg.py
- lib/matplotlib/backends/backend_tkcairo.py
- lib/matplotlib/backends/backend_wxcairo.py
- lib/matplotlib/pylab.py
> Some trivial py3fications.

- lib/matplotlib/axes/_subplots.py
fix for https://github.com/matplotlib/matplotlib/issues/10585
> make seaborn great again on Matplotlib-2.2

- doc/thirdpartypackages/index.rst
Also reorder other mentioned 3rdparty packages to alphabetical order.
> Add mplcairo to 3rdparty docs.

- setup.py
- setupext.py
> Simplify setupext by using globs.

- .travis.yml
This should help with the recent Travis failures on Mac OS.
See also: https://brew.sh/2018/01/19/homebrew-1.5.0/
> Homebrew python is now python 3

- .appveyor.yml
- .travis.yml
- INSTALL.rst
- README.rst
- doc-requirements.txt
- doc/conf.py
- doc/devel/contributing.rst
- doc/devel/documenting_mpl.rst
- doc/devel/testing.rst
- doc/sphinxext/mock_gui_toolkits.py
- lib/matplotlib/__init__.py
- lib/matplotlib/tests/test_backend_qt4.py
- lib/matplotlib/tests/test_backend_qt5.py
- lib/matplotlib/tests/test_dates.py
- lib/matplotlib/tests/test_legend.py
- lib/matplotlib/tests/test_rcparams.py
- lib/matplotlib/tests/test_units.py
- lib/matplotlib/tests/test_widgets.py
- tests.py
- tox.ini
so don't rely on the 3rd party version.
Also replace py.test by pytest in the docs (recommended since pytest
3.0, https://docs.pytest.org/en/latest/changelog.html#id281; we require
pytest>=3.1 anyways).
Also delete tox.ini which is clearly outdated.
> Mock is in stdlib in Py3.

- lib/matplotlib/_constrained_layout.py
As pointed out by @anntzer constrained layout gets slow for many subplots.  Some slowdown is to be expected, but there were numerous redundant constraints being added, so this now has watchdogs to make sure only one constraint is added.  Also some (probably insignificant) optimizations to reduce the number of calculations.  
"closes" #10655 
- subplots(4, 4) took    4s    now   1.8s  
- subplots(5, 5) took  12s,   now   3.3s
- subplots(6, 6) took  30s,  now   6.3s
Still not quite linear in N, but a lot better than N*2 which it was before.  
```python
import timeit
start = timeit.default_timer()
fig, ax = plt.subplots(6, 6, constrained_layout=False)
fig.canvas.draw()
stop = timeit.default_timer()
print(stop-start)
```
> FIX Speed up constrained layout

- lib/matplotlib/figure.py
> More figure-related doc updates

- doc/api/next_api_changes/2018-02-18-AL-removals.rst
- lib/matplotlib/font_manager.py
> Py3fy font_manager.

- lib/matplotlib/__init__.py
- setupext.py
Matplotlib.nib was used by the old cocoaagg backend (ef8e81e) which has
been deleted a while ago.
> Some py3fication for matplotlib/__init__, setupext.

- doc/api/next_api_changes/2018-02-15-AL-deprecations.rst
- lib/matplotlib/__init__.py
- lib/matplotlib/backends/backend_pgf.py
- lib/matplotlib/mpl-data/stylelib/_classic_test.mplstyle
- lib/matplotlib/mpl-data/stylelib/classic.mplstyle
- matplotlibrc.template
> Py3fy backend_pgf.

- lib/matplotlib/backends/_backend_tk.py
Accidentally broke this for no good reason in #8773.  Milestoning as 2.2 as it's fixing a bug introduced in 2.1.
> Fix tk icon loading.

- lib/matplotlib/axes/_base.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/markers.py
- lib/matplotlib/offsetbox.py
- lib/matplotlib/patches.py
- lib/matplotlib/transforms.py
https://docs.python.org/3/whatsnew/3.5.html#pickle
The previous workarounds were private and can be directly removed.
> Nested classes and instancemethods are directly picklable on Py3.5+.

- lib/matplotlib/figure.py
xref https://github.com/matplotlib/matplotlib/pull/10674#discussion_r172371120.
Sorry :)
> Remove incorrect warning in gca().

- lib/matplotlib/cbook/deprecation.py
cf recent discussion on gitter.
> Autoadd removal version to deprecation message.

- src/_png.cpp
> Fix signature docstring in _png extension.

- .travis.yml
- doc/sphinxext/mock_gui_toolkits.py
- lib/matplotlib/backends/wx_compat.py
- setupext.py
- tutorials/introductory/usage.py
mpl3 wx supports any wxpython that does support Py3 (i.e., wwpython>=4),
so we can drop the version checks.
> Remove some wx version checks.

- lib/matplotlib/backends/_backend_tk.py
- lib/matplotlib/backends/backend_pgf.py
- lib/matplotlib/cbook/__init__.py
- setupext.py
... so we can just do an equality check.  (Likewise, for Windows,
sys.platform is *always* "win32".)
(https://docs.python.org/3/library/sys.html#sys.platform)
> sys.platform is normalized to "linux" on Py3.

- lib/matplotlib/lines.py
This closes #10719
`line.set_linewidth` was being called *after* `line.set_linestyle` but `set_linestyle` needs `self._linewidth`.  In #10719, the user was passing a string, which maybe they shouldn't, but if `set_linewidth` is called first, it will cast the string....
> FIX: reorder linewidth setting before linestyle

- doc/conf.py
Update the copyright date in the doc footer to 2018.
> Update copyright date to 2018

- lib/matplotlib/animation.py
Apparently closes #10729 (thanks @cgohlke and @anntzer )
> FIX: ffmpeg logging level

- .travis.yml
Mac builds are failing.  Per @anntzer on twitter adding to the os x path to try to get them to build...
Fundamental problem is that `python` now needs the be `python3` if we use `homebrew`.
> FIX/TST OS X builds

- lib/matplotlib/tests/test_legend.py
> fixed comment typo

- examples/user_interfaces/fourier_demo_wx_sgskip.py
- lib/matplotlib/animation.py
- lib/matplotlib/axes/_base.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/backend_webagg.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/tests/test_artist.py
- lib/matplotlib/tests/test_simplification.py
- tools/triage_tests.py
> A hodgepodge of Py3 & style fixes.

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/collections.py
- lib/matplotlib/lines.py
- lib/matplotlib/patches.py
- lib/matplotlib/text.py
- lib/mpl_toolkits/mplot3d/art3d.py
Define property aliases in a more systematic manner.  Note that there were some "funny" aliases that I needed to work around, e.g. Text.set_name is an alias for Text.set_family but Text.get_name is different from Text.get_family.
Also use the aliases for kwarg normalization.
For collections, prefer normalizing get_facecolors, etc. to the *singular* form, as this is more consistent with the Artist interface.
This will add some setters/getters that were not defined before, e.g. there was a Patch.set_aa (set_antialiased) but no Patch.get_aa; this PR adds the missing method.
> Declare property aliases in a single place

- examples/lines_bars_and_markers/line_styles_reference.py
- examples/lines_bars_and_markers/marker_fillstyle_reference.py
- examples/lines_bars_and_markers/marker_reference.py
- examples/units/basic_units.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/font_manager.py
- lib/matplotlib/transforms.py
The `nice_repr` functions were there to handle Py2's `u"foo"`.
> repr style fixes.

- lib/matplotlib/artist.py
- lib/matplotlib/tests/test_table.py
> FIX: properties and setp on Table instances

- examples/misc/multipage_pdf.py
- examples/pyplots/text_commands.py
- lib/matplotlib/sphinxext/tests/tinypages/conf.py
- lib/matplotlib/testing/determinism.py
- lib/matplotlib/tests/test_afm.py
- lib/matplotlib/tests/test_animation.py
- lib/matplotlib/tests/test_backend_pgf.py
- lib/matplotlib/tests/test_backend_ps.py
- lib/matplotlib/tests/test_legend.py
- lib/matplotlib/tests/test_ticker.py
- lib/matplotlib/widgets.py
- tutorials/text/text_intro.py
> Py3fication of unicode.

- doc/faq/osx_framework.rst
- doc/faq/virtualenv_faq.rst
Now that venv is in stdlib, we can just recommend it instead of
suggesting a bunch of workarounds for virtualenv on OSX.
In the general venv docs, rework the first paragraph, which was phrased
a bit awkwardly; move vext above virtualenv because the former also
works in venvs (which again should be preferred).
> Simplify venv docs.

- lib/matplotlib/backends/backend_cairo.py
This ensures that when a cairo-based backend is active, animations also
get saved using backend_cairo, rather than falling back on backend_agg.
The fallback on agg was noted in https://github.com/matplotlib/matplotlib/issues/7233#issuecomment-373967684.
> Add print_rgba to backend_cairo.

- doc/api/next_api_changes/2018-02-15-AL-deprecations.rst
- examples/user_interfaces/mathtext_wx_sgskip.py
- examples/user_interfaces/wxcursor_demo_sgskip.py
- lib/matplotlib/backends/backend_wx.py
- lib/matplotlib/backends/backend_wxagg.py
- lib/matplotlib/backends/wx_compat.py
wxpython4 is required for python3 support, so wx_compat can be removed, hem, deprecated.
> wx_compat is no more.

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/mlab.py
As part of #10148: Docstring update for spectral plot functions.
> Minor docstring updates on spectral plot functions

- doc/faq/virtualenv_faq.rst
PyGObject can now be built in a venv, added link to their instructions.
Reworded an awkward sentence.
> Update docs re: pygobject in venv.

- examples/lines_bars_and_markers/scatter_custom_symbol.py
- examples/lines_bars_and_markers/scatter_hist.py
- examples/lines_bars_and_markers/scatter_masked.py
- examples/lines_bars_and_markers/scatter_star_poly.py
- examples/lines_bars_and_markers/scatter_symbol.py
From issue #8921
Added some descriptions for the following:
examples/lines_bars_and_markers/scatter_custom_symbol.py
examples/lines_bars_and_markers/scatter_hist.py
examples/lines_bars_and_markers/scatter_masked.py
examples/lines_bars_and_markers/scatter_star_poly.py
examples/lines_bars_and_markers/scatter_symbol.py
> Added descriptions for line bars and markers examples

- .appveyor.yml
- .travis.yml
- doc/devel/contributing.rst
- doc/devel/testing.rst
- lib/matplotlib/animation.py
- lib/matplotlib/tests/test_animation.py
- setupext.py
xref https://github.com/matplotlib/matplotlib/pull/10793#commitcomment-28114249
Sorry :)
> Fix undefined name.  Add animation tests.

- lib/matplotlib/axes/_axes.py
- lib/matplotlib/backends/qt_compat.py
- lib/matplotlib/pyplot.py
- lib/matplotlib/testing/jpl_units/Duration.py
- lib/matplotlib/testing/jpl_units/Epoch.py
- lib/matplotlib/testing/jpl_units/EpochConverter.py
- lib/matplotlib/testing/jpl_units/StrConverter.py
- lib/matplotlib/testing/jpl_units/UnitDbl.py
- lib/matplotlib/testing/jpl_units/UnitDblConverter.py
- lib/matplotlib/testing/jpl_units/UnitDblFormatter.py
- lib/matplotlib/testing/jpl_units/__init__.py
- lib/matplotlib/text.py
> More python3 cleanup

- lib/matplotlib/cbook/__init__.py
> MNT: move bz2 back to function level

- doc/index.rst
Restore html <title> on main doc page.
"Matplotlib: Python plotting -- Matplotlib vX.Y" used to be the <title> earlier (https://matplotlib.org/2.0.2/index.html); the switch to index.rst (rather than a handwritten index.html) had the infortunate side effect of changing that <title> to "Installation -- Matplotlib vX.Y" (taken from the first section of the page).
This PR restores the previous <title>.
> Restore main doc page <title>.

- lib/matplotlib/table.py
- Basically remove six, and future-import. 
- Clean up some docstrings on the way.
> py3ify table.py and correct some docstrings

- lib/matplotlib/backends/backend_nbagg.py
- lib/matplotlib/backends/backend_webagg_core.py
(The locking of RendererAgg is already done by the super class, and thus
redundant here.)
> Py3fy webagg/nbagg.

- lib/matplotlib/artist.py
- lib/matplotlib/backend_bases.py
- lib/matplotlib/backends/backend_agg.py
- lib/matplotlib/backends/backend_qt5.py
- lib/matplotlib/cbook/__init__.py
- lib/matplotlib/font_manager.py
- lib/matplotlib/style/core.py
- lib/matplotlib/testing/conftest.py
- lib/matplotlib/testing/decorators.py
- lib/matplotlib/tests/test_axes.py
- lib/matplotlib/tests/test_backend_ps.py
The setattr-contextmanager that was proposed in https://github.com/matplotlib/matplotlib/pull/10292#issuecomment-360257086.  Just quickly grepped for all the finallys in the codebase.
I also thought about doing something similar for set_prop() / get_prop() but that only appears twice throughout the codebase afaict so it's not really worth it.
> setattr context manager.

- lib/matplotlib/lines.py
- lib/matplotlib/mpl-data/stylelib/classic.mplstyle
- lib/matplotlib/rcsetup.py
- lib/matplotlib/tests/test_rcparams.py
- matplotlibrc.template
PR for issue #3293 and #8109  as well as suggested by @anntzer
> [MRG+1] FIX markerfacecolor / mfc not in rcparams

- examples/images_contours_and_fields/barb_demo.py
- examples/images_contours_and_fields/barcode_demo.py
- examples/images_contours_and_fields/contour_corner_mask.py
- examples/images_contours_and_fields/contour_demo.py
- examples/images_contours_and_fields/contour_image.py
- examples/images_contours_and_fields/contour_label_demo.py
- examples/images_contours_and_fields/contourf_demo.py
- examples/images_contours_and_fields/contourf_hatching.py
- examples/images_contours_and_fields/demo_bboximage.py
- examples/images_contours_and_fields/figimage_demo.py
- examples/images_contours_and_fields/image_demo.py
- examples/images_contours_and_fields/image_masked.py
- examples/images_contours_and_fields/interpolation_methods.py
- examples/images_contours_and_fields/quadmesh_demo.py
- examples/images_contours_and_fields/quiver_demo.py
- examples/images_contours_and_fields/shading_example.py
- examples/images_contours_and_fields/specgram_demo.py
- examples/images_contours_and_fields/tricontour_demo.py
- examples/images_contours_and_fields/tricontour_smooth_delaunay.py
- examples/images_contours_and_fields/tricontour_smooth_user.py
- examples/images_contours_and_fields/triinterp_demo.py
- examples/images_contours_and_fields/tripcolor_demo.py
- examples/images_contours_and_fields/triplot_demo.py
- lib/matplotlib/axes/_base.py
Basic clean up of `pyplot` ambiguity in some rather complex examples.
> DOC: use OO-ish interface in image, contour, field examples

- setupext.py
I have some bigger plans for setupext (such as stop using multiprocessing there), so I'm first putting out the style fixes as a separate PR.
> Style fixes to setupext.py.
